### ISSUE TITLE
Error in derepfastq

### ISSUE THREAD

**Issue by jslee47** [benjjneb/dada2#1001]
For issue 824, some files are missing, but in my case, all files are present. I really dont know why.. 

![15884411805102364251919063874928](https://user-images.githubusercontent.com/64702625/80871405-00f6ee80-8cdf-11ea-92ad-5954b121779b.jpg)

**Comment by benjjneb** [comment]
The error message indicates that not all the files are present.

What does `file.exists(filtFs)` give as a result? Any `FALSE` entries?

**Comment by bulbul2020** [comment]
Hi, I have the same issue and it shows FALSE 2. Now how to solve this issue?

**Comment by benjjneb** [comment]
Subset down to the files that exist before `derepFastq`.
