### ISSUE TITLE
Mixed read orientation (ITS Miseq) and high error rates

### ISSUE THREAD

**Issue by kamalanichock** [benjjneb/dada2#1003]
Hello,

Thanks for your thorough answers in previous posts, they have been very helpful in my understanding of dada2.  As the title suggests I have demultiplexed Miseq sequences that have a mixed read orientation after checking the primer orientations:

<img width="936" alt="Screen Shot 2020-05-05 at 2 22 37 PM" src="https://user-images.githubusercontent.com/36498273/81117409-e5a50280-8edb-11ea-9876-284cc7c76665.png">

Other threads (i.e. issue #167 and #938) have suggested running the sequences through the pipeline two separate times, once with the current primer orientation and the second with the reverse complement orientation. Then I can merge the generated ASV tables of the two runs together before chimera removal. 

I've followed these suggestions and after cutadapting I get what is expected in the two runs. 
<img width="700" alt="cutadapted_mix_sequences" src="https://user-images.githubusercontent.com/36498273/81118844-7846a100-8ede-11ea-9867-1168f295eded.png">
<img width="719" alt="cutadapted_mix_sequences_revcomp" src="https://user-images.githubusercontent.com/36498273/81118850-7a106480-8ede-11ea-901c-375c9b52cfbf.png">

However, I've encountered another problem when, after checking the error rates w/ LearnErrors, I am observing very high error rates.
[Error_plot_example.pdf](https://github.com/benjjneb/dada2/files/4583803/Error_plot_example.pdf)
I don't see why it would be but, might this be related to me not removing the primers in some orientations? My quality scores are fairly reasonable as seen here.
[QualityProfile_forward.pdf](https://github.com/benjjneb/dada2/files/4584101/QualityProfile_forward.pdf)

Any opinions on why my error rates are so high and suggestions on how to proceed would be greatly appreciated. Thanks!!

**Comment by benjjneb** [comment]
> after cutadapting I get what is expected in the two run

If those figures are correct, your primers are still on the reads after cutadapt, which is a major problem. Given that the primer detect numbers are so consistent, and there aren't any REV (FWD) primers on the FWD (REV) reads, you could just use `filterAndTrim` to remove these primers that are still there I think. But they need to be removed.

**Comment by kamalanichock** [comment]
Wow thank you, you are really quick! I hadn't thought about running the cutadapted sequences through `filterAndTrim` again in the reverse complement to remove the remaining primers. I've done this and all the primers are removed:
<img width="616" alt="Screen Shot 2020-05-05 at 6 07 39 PM" src="https://user-images.githubusercontent.com/36498273/81130260-febdab80-8efb-11ea-8bb9-953d44b25843.png">

Further downstream the error plots, while not perfect, make much more sense to me as well:
[New_Error_Plot.pdf](https://github.com/benjjneb/dada2/files/4584460/New_Error_Plot.pdf)

Thanks so much for your straightforward suggestions and fast response!
