### ISSUE TITLE
Error when using addSpecies() function

### ISSUE THREAD

**Issue by MarwaElnaiem** [benjjneb/dada2#1006]
Dear all, 
I'm working on 16SrRNA data generated by the Ion Torrent platform. I did use DADA2 successfully to analyze my data using the RDP database as the reference database for taxonomy assignment step. 
Now, I'm trying to use the Silva database instead, and I successfully obtained the taxonomy table using assignTaxonomy() function. 
When I tried to add the species to my taxa table, I obtained the following error: 
`taxa_species <- addSpecies(taxa, silva.ref_species)`
Error: cannot allocate vector of size 2.8 Gb

The version of silva that I used is v138. 

Another information:
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit) 16 GB RAM
Running under: Ubuntu 16.04.6 LTS

When I tried to figure out the problem from the internet, I found that it may be a memory problem. I tried 
and the result is :
` memory_limit()`
soft hard 
 Inf  Inf

Does the high number of packages installed in R create such problems?
Would you please help me with that? 

Best Regards, 
Marwa

**Comment by benjjneb** [comment]
This is probably just a memory availability issue, `addSpecies` has fairly high memory requirements, especially with the large Silva db. How much memory is available on the machine where you are doing this calculation? If it is less than 16GB, can you find a higher memory machine to run `assIgnSpecies` on?

**Comment by MarwaElnaiem** [comment]
Thanks very much for your reply. 
The available memory is less than 16 GB 
I tried free command and it gave me this: 

              total        used        free      shared  buff/cache   available
Mem:       16252828     3995016    10932548      582560     1325264    11351620
Swap:      16672764     4258092    12414672

Unfortunately, I may not be able to use another machine. 
Any way to obtain the taxonomy result till species level using assignTaxonomy() function (For silva database)?

**Comment by benjjneb** [comment]
> Any way to obtain the taxonomy result till species level using assignTaxonomy() function (For silva database)?

No not at this time, although in the medium term (a couple months) we do expect to release a species-level Silva `assignTaxonomy` database.

**Comment by MarwaElnaiem** [comment]
That is great!!
Thanks very much.

**Comment by vfonti** [comment]
I have just had the same problem. 
My desktop is quite a good machine, I have already run quite a few bioinformatic analysis on it and without using an external server. I knew it can make it and I found a trick to solve the issue. My desktop is a Windows machine and I have never been able to allocate memory at my choice (I am not geek enough, yet). However, I realised that my session got very heavy and that Rstudio was on for days...
So, I saved my session, I saved my `taxa `object as `.rds`, then closed and opened a new session. Then I loaded exclusively the `taxa.rds` object and the dada2 package and run `addSpecies` function.

It worked perfectly. 

I hope this can help whoever is my same situation.

**Comment by MarwaElnaiem** [comment]
Thanks @vfonti  very much for sharing the information. 
@benjjneb did you release the species-level Silva database that could be used with assignTaxonomy function or not yet?? 

Best, 
Marwa

**Comment by benjjneb** [comment]
@MarwaElnaiem Yes it is released, see the `wSpecies` files here: https://zenodo.org/record/3986799#.X84_FelKjUI

**Comment by marwa38** [comment]
> > Any way to obtain the taxonomy result till species level using assignTaxonomy() function (For silva database)?
> 
> No not at this time, although in the medium term (a couple months) we do expect to release a species-level Silva `assignTaxonomy` database.

Can I use now assignTaxonomy() for assigning all taxa levels to species one?
which one I have to assign to 
1- silva_nr99_v138_wSpecies_train_set.fa.gz
0r 
2- silva_species_assignment_v138.fa.gz

**Comment by wlwhalley** [comment]
As a tip for some others who may not have considered it, I had this exact issue with not having enough memory on my machine. I used an amazon web services EC2 instance for analysis - and just selected an instance with ~32GB memory equivalent. Including all the messing about this took about 2 hours and cost £4.50/$6.38 in the UK. This and other cloud computing services might be a good option for those with an older machine or no access to a computing cluster. I was then able to just download the .rds files.

**Comment by kaastengel1** [comment]
Hi @benjjneb, is the species level database (wSpecies) that was released now appropriate for short reads (Illumina MiSeq) or only suitable for long reads? I having been trying to use addSpecies for my data, however keep running out of memory even when using a high memory machine with 200G allocated.  Thanks!

**Comment by benjjneb** [comment]
We recommend `assignTaxonomy` with the species-level reference for long reads: [silva_nr99_v138.1_wSpecies_train_set.fa.gz](https://zenodo.org/record/4587955/files/silva_nr99_v138.1_wSpecies_train_set.fa.gz?download=1)

We recommend `assignTaxonomy` with the genus-level reference: [silva_nr99_v138.1_train_set.fa.gz](https://zenodo.org/record/4587955/files/silva_nr99_v138.1_train_set.fa.gz?download=1)

For short-read 16S, you can also push farther to the species level with the `assignSpecies` function. This uses a different reference file: [silva_species_assignment_v138.1.fa.gz](https://zenodo.org/record/4587955/files/silva_species_assignment_v138.1.fa.gz?download=1)

You may be giving `addSpecies` the wrong reference file that is intended for `assignTaxonomy`.

**Comment by kaastengel1** [comment]
Hi @benjjneb, thanks for the response. I used addSpecies with the silva_species_assignment_v138.1.fa.gz database. I have previously used the same commands on a smaller tax table and it worked fine, however this one is quite a large file

**Comment by benjjneb** [comment]
@kaastengel1 You may want to try breaking the `addSpecies` step up into chunks. This has helped some folks in the past when memory became a limiting issue at this step.
