### ISSUE TITLE
Differentiating between ASVs with 1 nucleotide difference

### ISSUE THREAD

**Issue by LijMeh** [benjjneb/dada2#1007]
Hello, hope all is going well. 

I am getting ready to sequence an experiment that involved inoculating a single pathogenic species into a defined synthetic community. We were planning to sequence the communities using illumina Mi-Seq v3 2x300 with 16s v4 primers, but the pathogen is relatively closely related to some of the members. Given that we have their genome sequences we can align the v4 regions, and there is a single nucleotide difference between the pathogen of interest and the most similar community member. I'm sure there are some specifics that go into this, but generally speaking would this be ok? Or is there a minimum amount of difference that you would suggest to be able to accurately resolve ASVs?

Thanks!

**Comment by benjjneb** [comment]
> Given that we have their genome sequences we can align the v4 regions, and there is a single nucleotide difference between the pathogen of interest and the most similar community member. I'm sure there are some specifics that go into this, but generally speaking would this be ok? 

Yes that should be OK. That's a big part of why DADA2 was created, to get that level of resolution.

**Comment by LijMeh** [comment]
Perfect, thanks!
