### ISSUE TITLE
assignTaxonomy returns NA for genus name when bootstrap score is 100

### ISSUE THREAD

**Issue by liaochen1988** [benjjneb/dada2#1011]
Hi, 

This may be an easy question but it is confusing to me. When I used assignTaxonomy function with the following sequence "TGCGTAGGTGGCGTACTAAGTCTGTAGTAAAAGGCAATGGCTCAACCATTGTAAGCTATGGAAACTGGTATGCTGGAGTGCAGAAGAGGGCGATGGAATTCCATGTGTAGCGGTAAAATGCGTAGATATATGGAGGAACACCAGTGGCGAAGGCGGTCGCCTGGTCTGTAACTGACACTGAGGCACGAAAG CGTGGGGAGCAAATAGGATTAGATACCCTAGTAGTCCACGCCGTAAACGATGAGAACTAAGTGTTGGAGGAATTCAGTGCTGCAGTTAACGCAATAAGTTCTCCGCCTGGGGAGTATGCACGCAAGTGTGAA", DADA2 returns NA for the genus name but its corresponding bootstrap score is 100. What does this mean?I thought NA is only returned when bootstrap score is below minBoot.

The reference database I used is silva_nr_v138_train_set.fa.gz. Other parameters include outputBootstraps=TRUE, minBoot=80, multithread=TRUE. 

Thanks very much.

**Comment by benjjneb** [comment]
Probably the entry in the database that is being matched doesn't have a genus-level assignment.
