### ISSUE TITLE
Issue with tracking reads through pipeline

### ISSUE THREAD

**Issue by kszelong** [benjjneb/dada2#1012]
![exampleerror](https://user-images.githubusercontent.com/35591204/81971233-9d6d9a80-95d5-11ea-8192-d326691e8494.png)

Hi, this is my first sequencing project and I'm a bit lost, so I apologize for any lack of clarity in advance.  I'm seeing very strange numbers from tracking the reads through the pipeline where a small number of reads go in and an even greater number reads are produced by the end of the pipeline...I am able to follow the code all the way through to the taxonomic assignments which appears to work fine, but this intermediary step just doesn't look right.

Is there a reason for this?  Or is this a problem with how the table was written?  I'm writing the table with:
`write.table(t(track), "track.txt", sep="\t", row.names=TRUE,
col.names=NA, quote=FALSE)`

Thank you for your help.

**Comment by benjjneb** [comment]
What is the command you used to generate the table?
And what does the table itself look like before it is written out: `head(track)`

**Comment by kszelong** [comment]
`getN <- function(x) sum(getUniques(x))
track <- cbind(out, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers, getN), rowSums(seqtab.nochim))
colnames(track) <- c("input", "filtered", "denoisedF", "denoisedR", "merged", "nonchim")
rownames(track) <- sample.names
head(track)`

**Comment by kszelong** [comment]
![trackerror](https://user-images.githubusercontent.com/35591204/82099074-3b876080-96bb-11ea-8ac0-088fad2b1c27.png)

Viewing the table in R before writing yields the same strange numbers.

**Comment by benjjneb** [comment]
OK let's check that the read counts at each step that are being combined in the over all table represent the same numbers of samples:

```
dim(out)
length(sapply(dadaFs, getN))
length(sapply(dadaRs, getN))
length(sapply(mergers, getN))
length(rowSums(seqtab.nochim))
```

**Comment by kszelong** [comment]
`> dim(out)
[1] 121   2
> length(sapply(dadaFs, getN))
[1] 94
> length(sapply(dadaRs, getN))
[1] 94
> length(sapply(mergers, getN))
[1] 94
> length(rowSums(seqtab.nochim))
[1] 94
`

**Comment by benjjneb** [comment]
You have a different number of samples in your `out` data object (121) than in the others (94), hence this error.

This probably occurred because some samples were lost during filtering? If so, you can subset `out` to just contain the samples that were kept, and then you can `cbind` everything together as expected.

**Comment by kszelong** [comment]
Thank you so much!  Everything looks great now.
