### ISSUE TITLE
quality filtering/trimming ITS sequences

### ISSUE THREAD

**Issue by wsteenhu** [benjjneb/dada2#1014]
Following the DADA2 ITS tutorial (v 1.8), I was able to process our groups ITS amplicons (we amplified the ITS1-region using ITS1F and ITS2R primers; 2x250bp protocol). I found that we lose many (50-100%; mostly 80%) sequences at the filtering step (filterandTrim; same parameters as in tutorial, i.e. maxEE=c(2,2); minLen=50; truncQ=2). This seems to do with a poor quality of especially reverse reads, where some profiles show clear drops in quality around a certain length (e.g. 100bp). 
I feel that not truncating these reads + maxEE=2 results in these high percentages of amplicons dropping out. A length profile based on these suboptimal data shows peaks of merged reads of up to 440bp. 

Could you advice on how to go about this. Options in my view are:
1. Set maxEE higher to allow more reads; seems suboptimal and following benchmarking papers maxEE>2 is related to much higher error rates.
2. Truncate reads similar to the 16S pipeline, although I am not sure what lengths to use. Judging from the heterogeneous quality profiles there doesn't seem to be a one-size-fits-all length to truncate at. In addition, I would be afraid to lose certain ITS-lengths (will happen per definition; tutorial advices against this).
3. Use some sort of adaptive window trimming, such as [sickle](https://github.com/najoshi/sickle), trimming when average quality drops below a certain level. Would this be advisable/work in the context of DADA2? How would this relate to the other trimming parameters?

Any other ideas/views on how to handle this? Did I miss any options? Anyone any experience with this problem? Thank you very much in advance for your help.

**Comment by benjjneb** [comment]
> Any other ideas/views on how to handle this?

Use just the forward reads. Especially for ITS data with bad reverse quality, I think this is usually the best choice. There was even a recent publication that came to the same conclusion in a test fungal dataset, i.e. that DADA2 on just forward ITS reads worked best for them: [Bioinformatics matters: The accuracy of plant and soil fungal community data is highly dependent on the metabarcoding pipeline](https://doi.org/10.1016/j.funeco.2019.03.005)

**Comment by wsteenhu** [comment]
Thank you for your quick answer and pointing me towards this paper. I am going to take a thorough look and see whether only forward reads would improve the number of decent quality reads kept.
