### ISSUE TITLE
Comparing results from differently parameterized DADA2 runs

### ISSUE THREAD

**Issue by rabdill** [benjjneb/dada2#1015]
**Short version:**
Are there any tips for choosing one set of DADA2 parameters over another? Assuming the big problems are addressed (e.g. "all the reads get thrown away"), are there other signs that one run is more confident than another?

**Long version:**
This is more of a documentation issue than a code problem, but I was curious if there was any guidance available regarding **which measurements were most helpful in determining which DADA2 runs are "better" than others**, given the same input data. There are plenty of parameters to tweak, but the inference steps add a layer of uncertainty to the clues I'd usually use to figure out which was preferable.

If it's helpful, my specific scenario is trying to process some older 16S data that's particularly messy—the reverse reads are even worse than expected, with kind of peculiar patterns in where the errors crop up, and both sets of reads deteriorate quickly enough that we usually can't find the primer at the far end of each one. There are a bunch of different ways to deal with those, and other issues—how the primers are trimmed off, which method to use for quality filtering (and how strict to be), and so on—but even if we try each combination of approaches, **it's difficult to justify choosing one approach over another**. More reads might be preferable to less, but do longer, lower-quality reads actually improve the results? Would it be worse to just throw away all the reverse reads? Do results improve with less trimming, but more stringent rules for which reads to discard completely?

I know questions like those usually don't have one solid answer, but **are there any heuristics for looking at two different DADA2 pipelines to see which one may result in more "confident" results?** Thanks very much for your time.

**Comment by benjjneb** [comment]
This is a bit of a non-answer, but in my opinion the goal for the vast majority of users of computational methods like DADA2 should not be to find an "optimal" set of parameters, but rather to avoid having an inappropriate set of parameters that gives qualitatively wrong results.

In practice, if two sets of parameters give similar results, they are probably essentially equally useful in most cases. Also in practice, this means doing sanity checks that will catch major problems (e.g. failure to remove primers, or truncating too short to merge later) as a regular step in even production pipelines.

> More reads might be preferable to less, but do longer, lower-quality reads actually improve the results? Would it be worse to just throw away all the reverse reads? Do results improve with less trimming, but more stringent rules for which reads to discard completely?

I think for every one of those answers, there is no one universal answer, and depending on specific datasets that either choice might be "optimal". That's the unsatisfying response I know. However, on the good side I would say that all those choices are reasonable and will yield similar biological conclusions for most datasets as well.

**Comment by rabdill** [comment]
Thanks for responding so quickly! This tracks with what my colleagues have been saying as well—essentially, there are ways to confirm some results are more suspicious than others, but that's as far as we can get quantitatively. I'll keep messing with it, but this was very helpful, thanks again.

**Comment by andzandz11** [comment]
Generally what I do is before I try an experimental setup or a new sequencng technique is that I mix a mock community and check out if the dada2 parameters change anything in regard to the mock community analysis. In my opinion, after the run is finished, and you did put nothing in there on purpose that has a predefined outcome, it's impossible.
