### ISSUE TITLE
pseudo-pooling and multiple runs

### ISSUE THREAD

**Issue by ericamprosdocimi** [benjjneb/dada2#1017]
Hi all,

I am analysing 16S MiSeq data from 3 separate runs for the same project. The 3rd MiSeq run had a higher sequencing depth. Partly for this reason, I observe a significant batch effect, where the samples in the third run have a bigger number of ASVs, affecting not only alpha but also beta diversity tests. This in spite of the fact that all the rarefaction curves reach plateau.

Reasoning that many of the ASVs detected in the third run could be present in the first two as singletons, I tried a pseudo-pooling approach to mitigate the batch effect. I used the big-data approach, with the following steps:

- run DADA2 1st time for plate 1
- run DADA2 1st time for plate 2
- run DADA2 1st time for plate 3
- merge the three plates
- remove chimeras from the merged table
- create a vector of "priors" taking all the sequences from the column names of the merged table
- run DADA2 2nd time for plate 1 with priors
- run DADA2 2nd time for plate 2 with priors
- run DADA2 2nd time for plate 3 with priors
- merge the 3 sequence tables
- remove chimeras from the final table

I was expecting to get a higher number of ASVs doing this, and to detect some of the rarest ASVs in samples where they were not detected in the naive analysis. Oddly, I get the same number of ASVs for plates 1 and 3, and just 1 additional ASV in plate 3.

> dim(seqtab_1)
[1]   270 29606
> dim(seqtab_1_priors)
[1]   270 29606
> dim(seqtab_2)
[1]   250 24510
> dim(seqtab_2_priors)
[1]   250 24511
> dim(seqtab_3)
[1]    27 11677
> dim(seqtab_3_priors)
[1]    27 11677
 
Furthermore, there are only 2 ASVs overall that differ in total counts.
This is not what I expected...

Is it correct to use pseudo-pooling to deal with batch effects?
Is the workflow I applied reasonable?
If so, why am I not observing a bigger variation in the number of ASVs or their counts?

Thank you very much for your time!
Erica

**Comment by benjjneb** [comment]
> Is the workflow I applied reasonable?

From the description you posted it seems reasonable.

> If so, why am I not observing a bigger variation in the number of ASVs or their counts?

I am surprised you aren't seeing more difference, especially in the overall counts of more ASVs than just 2. Is it expected that there should be a good amount of sharing between the ASVs int he samples in the different runs? I would check that first, e.g. what is the overlap between the ASVs in runs 1/2/3 (before priors).

> Is it correct to use pseudo-pooling to deal with batch effects?

It is an approach, but probably not what I would expect to majorly reduce batch effects. There are much larger types of batch effects that can come up from different biases in different runs (from storage, extraction, library prep, sequencing...). Furthermore, if the major issue you are concerned about here is potential bias from the higher coverage in the 3rd run, I would just address that directly by subsampling the third run down to the median coverage in run1/2 before even entering the bioinformatics. That will strongly control that effect.

**Comment by ericamprosdocimi** [comment]
Hi Benjamin,
Thank you for your fast reply. 
Yes, I expected a good sharing of sequences between the groups as they come from very similar samples. However, I now see that before priors runs 1 and 2 share from 39% to 48% of their sequences with the other runs, while run 3 shares only 17% and 19% of its sequences with the other two. 
I already tried the subsampling approach you suggest to reduce batch effect. It doesn't work as it should, and now I see it is probably because of the low percentage of shared sequences which makes the samples in run 3 not only more diverse but completely different.
The trouble is, samples from run 3 all belong to the same treatment group, making it extremely difficult to distinguish between batch effect and treatment effect. 
Do you know any method I could try to address this or should I drop these samples entirely?
Thank you very much for your help.
Erica

**Comment by benjjneb** [comment]
> The trouble is, samples from run 3 all belong to the same treatment group, making it extremely difficult to distinguish between batch effect and treatment effect.
> Do you know any method I could try to address this or should I drop these samples entirely?

Unfortunately when you have complete conflation between the treatment effect and a technical variable like "run", it is hard to completely disentangle. Not helpful now, but in the future this is why trying to randomize samples across technical batches is important whenever possible.

One thing you could consider is doing your analysis only on the "core" microbiome that is shared between all 3 runs. However, this might result in more loss than gain, depending on the relative value of the rest of the taxa being measured versus the 27 samples in Run 3, and may not even remove the batch effect if there are also major bias differences in how well different taxa are being detected.
