### ISSUE TITLE
Is it possible to calculate the overlap length with DADA2?

### ISSUE THREAD

**Issue by BinhongLiu** [benjjneb/dada2#1018]
Hi all,
    I have V3-V4 (341F and 805R) data made up of mice fecal microbiome samples. Since the quality of the base is reduced below a certain threshold at the right side of the reads, I'm trying to apply quality trimming the 3' end of the reads. However, it also should be necessary to remain at least 12 bases that identical to each other in the overlap region after the 3' end quality trimming to meet the minimum requirement of DADA2. So, I'm wondering if it's possible to calculate the overlap length for the pair-end reads first and based on the distribution of overlap length I can decide the bp length that could be trimmed safely under the premise of ensuring the minimum overlap length. Therefore, I might discard the low-quality reads and improve the dada2 denoising result to have more reads kept.
      Thank you!
Best wishes!

**Comment by benjjneb** [comment]
> So, I'm wondering if it's possible to calculate the overlap length for the pair-end reads first and based on the distribution of overlap length I can decide the bp length that could be trimmed safely under the premise of ensuring the minimum overlap length.

We don't have an automated solution to determine the overlap length from the data itself. This is certainly doable in R (or otherwise), but not something we have implemented.

If you are using Illumina V3V4 protocol (with primers included on the sequences) the biologial amplicon length distribution is already known, it is bimodal with the high peak at ~460nts.

**Comment by BinhongLiu** [comment]
> > So, I'm wondering if it's possible to calculate the overlap length for the pair-end reads first and based on the distribution of overlap length I can decide the bp length that could be trimmed safely under the premise of ensuring the minimum overlap length.
> 
> We don't have an automated solution to determine the overlap length from the data itself. This is certainly doable in R (or otherwise), but not something we have implemented.
> 
> If you are using Illumina V3V4 protocol (with primers included on the sequences) the biologial amplicon length distribution is already known, it is bimodal with the high peak at ~460nts.

Thank you for your reply!
Yes, you were right. The high peak for the V3-V4 PCR product is at 460nts. I'll try to find a package that could calculate the overlap length between the R1 and R2.
Any packages recommend for this calculation will be welcome!

**Comment by benjjneb** [comment]
> I'll try to find a package that could calculate the overlap length between the R1 and R2.

You can just get the overlap length from arithmetic once you know the sequenced amplicon length and the lengths of the reads.

For example, if it's 2x250 reads, then that's 500nts of total paied reads for a ~460 nt amplicon = ~40nts of overlap.

**Comment by BinhongLiu** [comment]
> > I'll try to find a package that could calculate the overlap length between the R1 and R2.
> 
> You can just get the overlap length from arithmetic once you know the sequenced amplicon length and the lengths of the reads.
> 
> For example, if it's 2x250 reads, then that's 500nts of total paied reads for a ~460 nt amplicon = ~40nts of overlap.

Yeah, you were right. I've calculated the overlap length and found it was around 40nts. What I need is the distribution of the overlap length since it could be variable between different microbes. Based on this I could draw the relationship between the trimmed length of 3' end and the number of reads discarded caused by their shorter overlap than 12 nts after trimming.

**Comment by benjjneb** [comment]
> What I need is the distribution of the overlap length since it could be variable between different microbes. Based on this I could draw the relationship between the trimmed length of 3' end and the number of reads discarded caused by their shorter overlap than 12 nts after trimming.

You could try sampling from a broad 16S database like Silva.

**Comment by BinhongLiu** [comment]
> > What I need is the distribution of the overlap length since it could be variable between different microbes. Based on this I could draw the relationship between the trimmed length of 3' end and the number of reads discarded caused by their shorter overlap than 12 nts after trimming.
> 
> You could try sampling from a broad 16S database like Silv

**Comment by BinhongLiu** [comment]
> > > What I need is the distribution of the overlap length since it could be variable between different microbes. Based on this I could draw the relationship between the trimmed length of 3' end and the number of reads discarded caused by their shorter overlap than 12 nts after trimming.
> > 
> > 
> > You could try sampling from a broad 16S database like Silv

Great idea! 
Besides, I also find another tool AfterQC (https://github.com/OpenGene/AfterQC) that could calculate the overlap length distribution of pair-end reads. That's exactly what I want.
Thank you for your kindness help!
Best wishes!
