### ISSUE TITLE
updating plotQualityProfile to add main title to plot

### ISSUE THREAD

**Issue by KMKemp** [benjjneb/dada2#102]
It would be helpful to update plotQualityProfile to generate plots that include the sample name as the main title without having to save the ggplot and adding it later.

**Comment by benjjneb** [comment]
The filename is now included in the lower-left corner of the `plotQualityProfile` plot: bc69230206cd8fb015a05448e753d811aac8ad59

**Comment by KMKemp** [comment]
Thanks! Very helpful!
