### ISSUE TITLE
Merging otu table and and taxa table into one txt file 

### ISSUE THREAD

**Issue by razz1618** [benjjneb/dada2#1021]
Hi,
Is there a way to export otu table and taxonomy table merged together  (possibly at single taxonomic level) so as to get a single table of all the sample's otu count at a particular taxonomic level?

**Comment by abhijeetsingh1704** [comment]
`
### using non chimaera sequeces in dada2 seqtab object, giving the sequences name as ASV and extracting OTU sequences, abundance and taxonomy

# seq table
asv_seqs <- colnames(seqtab_nochim)
asv_headers <- vector(dim(seqtab_nochim)[2], mode="character")

### fasta header as ASV_<number>
for (i in 1:dim(seqtab_nochim)[2]) {
	asv_headers[i] <- paste(">ASV", i, sep="_")
}

### OTU sequences
asv_fasta <- c(rbind(asv_headers, asv_seqs))

### OTU abundance
asv_otu <- t(seqtab_nochim)
row.names(asv_otu) <- sub(">", "", asv_headers)

### OTU taxonomy
asv_tax <- taxa
row.names(asv_tax) <- sub(">", "", asv_headers)

### merging abundance and tax table
OTU_TAX_table <- merge(asv_otu, asv_tax, by=0)

### writing out output files
write(asv_fasta, "asv_fasta.fa")
write.table(asv_otu, "asv_otu.csv", sep=",", quote=F, col.names=NA)
write.table(asv_tax, "asv_tax.csv", sep=",", quote=F, col.names=NA)
write.table(OTU_TAX_table, "OTU_TAX_table.csv", sep=","quote=F, col.names=NA)
`

**Comment by razz1618** [comment]
Thanks
