### ISSUE TITLE
loss of reads at filtering for certain forward primers in identical HiSeq but NOT MiSeq

### ISSUE THREAD

**Issue by justingdbyrne** [benjjneb/dada2#1022]
I have run 16S (515-806) bacterial soil samples through dada2. I have done this for 3 MiSeq runs with no problems. However for my HiSeq run, 5 of the forward primers produce plenty of reads but 95%+ are removed at filtering step (see the attached "track" with a subset on my HiSeq data). For both the MiSeq and HiSeq run I used primers diluted from the same stock solutions. The same primer sets, different extractions but very similar to one another. Primers were diluted to several identical stock solutions so ALL of them failing for those forward primers seems unlikely. 

The primer design includes heterogeneity spacers (bolding indicated the problem primers - forward 6,7,8,10,11):
1. [NONE]
2. T
3. GT
4. CGA
5. ATGA
6. **TGCGA**
7. **GAGTGG**
8. **CCTGTGG**
9. [NONE]
10. **GAGTGG**
11.**TGCGA**
12.ATGA

Heres the % remaining after filtering for these 12 forward primers (the 96well plate columns):
![percent_kept_after_filter](https://user-images.githubusercontent.com/52284064/82909731-90e82b00-9f61-11ea-9412-1f2bc963ff06.png)

Verses the reverse:
![loss_by_row](https://user-images.githubusercontent.com/52284064/82909788-a78e8200-9f61-11ea-8eeb-ef3254aa2188.png)

We're getting the reads out of the demultiplexing step (via metabeat), sometimes the primers get left in, but cutting them out with cutadapt changes nothing in the results. Is it possible that this has something to do with the heterogeneity spaces, as all of those with 5+ bases are the ones that fail, primer 9 has no spacer, and despite spatial proximity on the plate, performs fine. That combined with the fact that we do get reads, and it all works fine for the MiSeq with the same primers, makes me think that I've not set the filter up right.

here is my current filter step:

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, maxN = 0, maxEE = c(2, 2), truncLen=c(220,200), 
                     truncQ = 2, minLen = 50, rm.phix = TRUE, compress = TRUE,
                     multithread = TRUE)  # on windows, set multithread = FALSE

What are my next steps. I can run a 40 sample subset in about 10 mins so I could try a few things. 

Reducing the minLen to 20 did not change anything, but I'm not sure where to start next. I could include track and quality plots from my MiSeq run if it would help. 

Thank you!

[16S_track_tst1.xlsx](https://github.com/benjjneb/dada2/files/4682733/16S_track_tst1.xlsx)
[16_Squalityplots.pdf](https://github.com/benjjneb/dada2/files/4682735/16_Squalityplots.pdf)
[16S_ploterrors.pdf](https://github.com/benjjneb/dada2/files/4682736/16S_ploterrors.pdf)

**Comment by benjjneb** [comment]
My guess is that after removal of the heterogeneity spacers and primers, that the samples with long heterogeneity spacers end up with reads just below 220nts (forward) and thus are almost entirely being discarded by `truncLen=c(220, 200)`.

If you lower this to `truncLen=c(210, 200)` does this issue go away?

**Comment by justingdbyrne** [comment]
I think the issue was to do with cutadapt after all and I think I have resolved it.
