### ISSUE TITLE
DADA2 + Pacbio: No combination of different SMRTcells

### ISSUE THREAD

**Issue by pneumowidow** [benjjneb/dada2#1024]
Hi Ben,

We are writing up a manuscript using your Pacbio + DADA2 pipeline and we would like to quote your reasoning behind running DADA2 on single SMRTcells and not on a combination of different ones. However, we couldn't find this quote in your _Nucleic Acids Research_ article. Can you provide a formal reference, so we can cite this in our methods? Perhaps in the DADA2 R package manual?

Many thanks :-)

**Comment by benjjneb** [comment]
TBH I'm not sure I have a "formal" reference for that, i.e. a published manuscript. 

The best that comes to mind immediatley is the DADA2 big data tutorial (https://benjjneb.github.io/dada2/bigdata.html) specifically the "Merge Runs..." section.

**Comment by pneumowidow** [comment]
I think this will suffice. Thank you!
