### ISSUE TITLE
Taxon specific complete loss of reads using ITS pipeline

### ISSUE THREAD

**Issue by kek12e** [benjjneb/dada2#1025]
I believe this to be a sequencing artifact rather than an issue with DADA2, but perhaps you have advice on how best to mitigate this issue computationally. I did an experiment where I basically challenged two species of fungi, _Leucoagaricus_ and _Trichoderma_, and then sampled at timepoints until the _Trichoderma_ had overgrown the _Leucoagaricus_. _Trichoderma_ produces tons of green spores so it’s very easy to detect observationally. However, after amplifying the ITS2 region from these DNA samples, sequencing on Miseq, and analyzing using the DADA2 ITS pipeline, my community abundance plots contained only _Leucoagaricus_ and no _Trichoderma_. This was obviously strange because I knew there should be high abundance of _Trichoderma_ at the late stage timepoints, so I went back to investigate the quality plots and track reads through the pipeline. There was characteristic low quality starting at ~125bp in the forward read and overall low quality in the reverse read associated with _Trichoderma_ abundance. Below is just one example plot, but every sample that contains _Trichoderma_ looks the same, even across multiple experiments and sequencing runs, to the point where I can identify _Trichoderma_ just from looking at the sequencing quality plots. 

![alt text](https://github.com/kek12e/MyFiles/blob/master/TpureQualPlot.png?raw=TRUE)

There was also higher loss of reads after the filtering step and complete loss of reads after the merging step for samples high in _Trichoderma_ which then results in community abundance plots that only contain _Leucoagaricus_. Below is a plot showing number of reads following each step of the DADA2 pipeline for a _Trichoderma_ sample. 

![alt text](https://github.com/kek12e/MyFiles/blob/master/TpureReadLossHoriz.png?raw=TRUE)

Based on the quality plots, I decided to try the pipeline using only the forward reads and trimming them to 125bp to get rid of low quality portions (`truncLen = 125` for `filterAndTrim()`). This resulted in expected levels of _Trichoderma_. Below are the relative abundance plots from a synthetic community experiment where I pooled different ratios of _Leucoagaricus_ to _Trichoderma_ DNA. You can see how _Trichoderma_ is completely undetected under the normal DADA2 trimming/merging process. 

![alt text](https://github.com/kek12e/MyFiles/blob/master/mockNormalVsStringent.png?raw=TRUE)

This very stringent trimming process fixed the problem, however I feel somewhat uncomfortable using only 125 bp in one direction to characterize microbial communities. Outside of these more controlled experiments this method results in many more NA taxonomy calls. It’s also a waste of the rest of the sequencing data we’ve already collected. Do you have any knowledge of this issue or advice for addressing it? 

Thank you!

**Comment by andzandz11** [comment]
I actually don't know enough about dada2 to give you any neat coding advice on noise reduction.

What I do know things about is metabarcoding: Using reads only in one direction is actually recommended in fungi studies.

read: "Bioinformatics matters: The accuracy of plant and soil fungalcommunity data is highly dependent on the metabarcoding pipeline"
