### ISSUE TITLE
learnErrors: crash to desktop

### ISSUE THREAD

**Issue by andzandz11** [benjjneb/dada2#1027]
Whenever I execute learnErrors(file) my RStudio crashes to desktop. I attached the files I was using.
It took me a while to understand it is because of some sequences have a length of zero. I did not lose any data, but a crash to desktop might have very bad consequences. Maybe there is a way to throw an error instead.

[A10-363-VIII-IX-X_R2_noPrim.fastq.zip](https://github.com/benjjneb/dada2/files/4703879/A10-363-VIII-IX-X_R2_noPrim.fastq.zip)

<details>
  <summary>crash report</summary>
  
  ## Heading
Version=1
EventType=APPCRASH
EventTime=132352537324369031
ReportType=2
Consent=1
UploadTime=132352537327807396
ReportStatus=268435456
ReportIdentifier=70fb8d88-e090-4a98-b67a-53aaf7d1b155
IntegratorReportIdentifier=b19a43a2-d137-4d72-8dae-dbf2ec83e691
Wow64Host=34404
NsAppName=rsession.exe
OriginalFilename=rsession.exe
AppSessionGuid=00004344-0001-0006-d43f-0d41ee35d601
TargetAppId=W:00063498911530d27ff34c8089fb87ed660200000904!000018169b55534f103987f9ac939854543a900d480b!rsession.exe
TargetAppVer=2020//04//01:17:07:47!0!rsession.exe
BootId=4294967295
ServiceSplit=820498137
TargetAsId=24323
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=51ce20646c4f0df60ca79c1b8c89d0f5
Response.BucketTable=4
Response.LegacyBucketId=2064790596308553973
Response.type=4
Sig[0].Name=Anwendungsname
Sig[0].Value=rsession.exe
Sig[1].Name=Anwendungsversion
Sig[1].Value=1.2.5042.0
Sig[2].Name=Anwendungszeitstempel
Sig[2].Value=5e84ca63
Sig[3].Name=Fehlermodulname
Sig[3].Value=ShortRead.dll
Sig[4].Name=Fehlermodulversion
Sig[4].Value=0.0.0.0
Sig[5].Name=Fehlermodulzeitstempel
Sig[5].Value=5eaeedd3
Sig[6].Name=Ausnahmecode
Sig[6].Value=c0000005
Sig[7].Name=Ausnahmeoffset
Sig[7].Value=0000000000007863
DynamicSig[1].Name=Betriebsystemversion
DynamicSig[1].Value=10.0.18363.2.0.0.256.48
DynamicSig[2].Name=Gebietsschema-ID
DynamicSig[2].Value=1031
DynamicSig[22].Name=Zusatzinformation 1
DynamicSig[22].Value=e282
DynamicSig[23].Name=Zusatzinformation 2
DynamicSig[23].Value=e28227c4fa912c450f78b80475c216cf
DynamicSig[24].Name=Zusatzinformation 3
DynamicSig[24].Value=6170
DynamicSig[25].Name=Zusatzinformation 4
DynamicSig[25].Value=61703613f58671cea63ebcb4fe9967a5
UI[2]=C:\Program Files\RStudio\bin\rsession.exe
LoadedModule[0]=C:\Program Files\RStudio\bin\rsession.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\system32\hmpalert.dll
LoadedModule[3]=C:\WINDOWS\System32\KERNEL32.dll
LoadedModule[4]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[5]=C:\WINDOWS\SYSTEM32\apphelp.dll
LoadedModule[6]=C:\WINDOWS\System32\ADVAPI32.dll
LoadedModule[7]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[8]=C:\WINDOWS\System32\sechost.dll
LoadedModule[9]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[10]=C:\WINDOWS\System32\WS2_32.dll
LoadedModule[11]=C:\WINDOWS\System32\SHLWAPI.dll
LoadedModule[12]=C:\WINDOWS\System32\combase.dll
LoadedModule[13]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[14]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[15]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[16]=C:\WINDOWS\System32\win32u.dll
LoadedModule[17]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[18]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[19]=C:\WINDOWS\System32\USER32.dll
LoadedModule[20]=C:\WINDOWS\System32\SHELL32.dll
LoadedModule[21]=C:\WINDOWS\System32\cfgmgr32.dll
LoadedModule[22]=C:\WINDOWS\System32\shcore.dll
LoadedModule[23]=C:\WINDOWS\System32\windows.storage.dll
LoadedModule[24]=C:\WINDOWS\System32\profapi.dll
LoadedModule[25]=C:\WINDOWS\System32\powrprof.dll
LoadedModule[26]=C:\WINDOWS\System32\UMPDC.dll
LoadedModule[27]=C:\WINDOWS\System32\kernel.appcore.dll
LoadedModule[28]=C:\WINDOWS\System32\cryptsp.dll
LoadedModule[29]=C:\WINDOWS\System32\ole32.dll
LoadedModule[30]=C:\Program Files\R\R-4.0.0\bin\x64\R.dll
LoadedModule[31]=C:\Program Files\R\R-4.0.0\bin\x64\Rgraphapp.dll
LoadedModule[32]=C:\WINDOWS\System32\comdlg32.dll
LoadedModule[33]=C:\WINDOWS\System32\IMM32.dll
LoadedModule[34]=C:\WINDOWS\SYSTEM32\MSWSOCK.dll
LoadedModule[35]=C:\Program Files\RStudio\bin\MSVCP140.dll
LoadedModule[36]=C:\Program Files\RStudio\bin\VCRUNTIME140.dll
LoadedModule[37]=C:\Program Files\R\R-4.0.0\bin\x64\Rblas.dll
LoadedModule[38]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[39]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[40]=C:\Program Files\R\R-4.0.0\bin\x64\Riconv.dll
LoadedModule[41]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.18362.778_none_2a29d4a64667eb69\COMCTL32.dll
LoadedModule[42]=C:\WINDOWS\SYSTEM32\MSIMG32.dll
LoadedModule[43]=C:\WINDOWS\SYSTEM32\WINMMBASE.dll
LoadedModule[44]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[45]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[46]=C:\WINDOWS\System32\clbcatq.dll
LoadedModule[47]=C:\WINDOWS\SYSTEM32\PROPSYS.dll
LoadedModule[48]=C:\Program Files\R\R-4.0.0\library\methods\libs\x64\methods.dll
LoadedModule[49]=C:\Program Files\R\R-4.0.0\library\utils\libs\x64\utils.dll
LoadedModule[50]=C:\Program Files\R\R-4.0.0\library\grDevices\libs\x64\grDevices.dll
LoadedModule[51]=C:\Program Files\R\R-4.0.0\library\graphics\libs\x64\graphics.dll
LoadedModule[52]=C:\Program Files\R\R-4.0.0\library\stats\libs\x64\stats.dll
LoadedModule[53]=C:\Program Files\R\R-4.0.0\bin\x64\Rlapack.dll
LoadedModule[54]=C:\Program Files\RStudio\bin\rsclang\x86_64\libclang.dll
LoadedModule[55]=C:\Program Files\R\R-4.0.0\library\tools\libs\x64\tools.dll
LoadedModule[56]=C:\PROGRA~1\R\R-40~1.0\modules\x64\internet.dll
LoadedModule[57]=C:\WINDOWS\System32\CRYPT32.dll
LoadedModule[58]=C:\WINDOWS\System32\MSASN1.dll
LoadedModule[59]=C:\WINDOWS\System32\WLDAP32.dll
LoadedModule[60]=C:\WINDOWS\SYSTEM32\WININET.dll
LoadedModule[61]=C:\WINDOWS\SYSTEM32\SspiCli.dll
LoadedModule[62]=C:\Program Files\R\R-4.0.0\library\parallel\libs\x64\parallel.dll
LoadedModule[63]=C:\Program Files\R\R-4.0.0\library\S4Vectors\libs\x64\S4Vectors.dll
LoadedModule[64]=C:\Program Files\R\R-4.0.0\library\IRanges\libs\x64\IRanges.dll
LoadedModule[65]=C:\Program Files\R\R-4.0.0\library\zlibbioc\libs\x64\zlib1bioc.dll
LoadedModule[66]=C:\Program Files\R\R-4.0.0\library\XVector\libs\x64\XVector.dll
LoadedModule[67]=C:\Program Files\R\R-4.0.0\library\Biostrings\libs\x64\Biostrings.dll
LoadedModule[68]=C:\Program Files\R\R-4.0.0\library\BiocParallel\libs\x64\BiocParallel.dll
LoadedModule[69]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[70]=C:\WINDOWS\System32\bcrypt.dll
LoadedModule[71]=C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
LoadedModule[72]=C:\Program Files\R\R-4.0.0\library\bitops\libs\x64\bitops.dll
LoadedModule[73]=C:\Program Files\R\R-4.0.0\library\RCurl\libs\x64\RCurl.dll
LoadedModule[74]=C:\Program Files\R\R-4.0.0\library\GenomicRanges\libs\x64\GenomicRanges.dll
LoadedModule[75]=C:\Program Files\R\R-4.0.0\library\Rsamtools\libs\x64\Rsamtools.dll
LoadedModule[76]=C:\Program Files\R\R-4.0.0\library\Biobase\libs\x64\Biobase.dll
LoadedModule[77]=C:\Program Files\R\R-4.0.0\library\matrixStats\libs\x64\matrixStats.dll
LoadedModule[78]=C:\Program Files\R\R-4.0.0\library\grid\libs\x64\grid.dll
LoadedModule[79]=C:\Program Files\R\R-4.0.0\library\lattice\libs\x64\lattice.dll
LoadedModule[80]=C:\Program Files\R\R-4.0.0\library\Matrix\libs\x64\Matrix.dll
LoadedModule[81]=C:\Program Files\R\R-4.0.0\library\DelayedArray\libs\x64\DelayedArray.dll
LoadedModule[82]=C:\Program Files\R\R-4.0.0\library\GenomicAlignments\libs\x64\GenomicAlignments.dll
LoadedModule[83]=C:\Program Files\R\R-4.0.0\library\png\libs\x64\png.dll
LoadedModule[84]=C:\Program Files\R\R-4.0.0\library\jpeg\libs\x64\jpeg.dll
LoadedModule[85]=C:\Program Files\R\R-4.0.0\library\ShortRead\libs\x64\ShortRead.dll
LoadedModule[86]=C:\Program Files\R\R-4.0.0\library\rlang\libs\x64\rlang.dll
LoadedModule[87]=C:\Program Files\R\R-4.0.0\library\colorspace\libs\x64\colorspace.dll
LoadedModule[88]=C:\Program Files\R\R-4.0.0\library\glue\libs\x64\glue.dll
LoadedModule[89]=C:\Program Files\R\R-4.0.0\library\ellipsis\libs\x64\ellipsis.dll
LoadedModule[90]=C:\Program Files\R\R-4.0.0\library\vctrs\libs\x64\vctrs.dll
LoadedModule[91]=C:\Program Files\R\R-4.0.0\library\tibble\libs\x64\tibble.dll
LoadedModule[92]=C:\Program Files\R\R-4.0.0\library\Rcpp\libs\x64\Rcpp.dll
LoadedModule[93]=C:\Program Files\R\R-4.0.0\library\purrr\libs\x64\purrr.dll
LoadedModule[94]=C:\Program Files\R\R-4.0.0\library\dplyr\libs\x64\dplyr.dll
LoadedModule[95]=C:\Program Files\R\R-4.0.0\library\nlme\libs\x64\nlme.dll
LoadedModule[96]=C:\Program Files\R\R-4.0.0\library\ape\libs\x64\ape.dll
LoadedModule[97]=C:\Program Files\R\R-4.0.0\library\stringi\libs\x64\stringi.dll
LoadedModule[98]=C:\Program Files\R\R-4.0.0\library\xml2\libs\x64\xml2.dll
LoadedModule[99]=C:\Program Files\R\R-4.0.0\library\RcppParallel\lib\x64\tbb.dll
LoadedModule[100]=C:\Program Files\R\R-4.0.0\library\RcppParallel\lib\x64\tbbmalloc.dll
LoadedModule[101]=C:\Program Files\R\R-4.0.0\library\RcppParallel\libs\x64\RcppParallel.dll
LoadedModule[102]=C:\Program Files\R\R-4.0.0\library\plyr\libs\x64\plyr.dll
LoadedModule[103]=C:\Program Files\R\R-4.0.0\library\reshape2\libs\x64\reshape2.dll
LoadedModule[104]=C:\Program Files\R\R-4.0.0\library\dada2\libs\x64\dada2.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=18363
OsInfo[3].Key=ubr
OsInfo[3].Value=778
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1031
OsInfo[7].Key=geoid
OsInfo[7].Value=94
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=1
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=196276
OsInfo[15].Key=osinsty
OsInfo[15].Value=1
OsInfo[16].Key=iever
OsInfo[16].Value=11.778.18362.0-11.0.185
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=16113
OsInfo[19].Key=svolsz
OsInfo[19].Value=237
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=190318
OsInfo[22].Key=bldtm
OsInfo[22].Value=1202
OsInfo[23].Key=bldbrch
OsInfo[23].Value=19h1_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.18362.778.amd64fre.19h1_release.190318-1202
OsInfo[30].Key=buildflightid
OsInfo[30].Value={03DE01D4-EE44-4BA0-910A-53CAE3CEE24C}.202
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[34].Key=containerid
OsInfo[35].Key=containertype
OsInfo[36].Key=edu
OsInfo[36].Value=0
FriendlyEventName=Nicht mehr funktionsfähig
ConsentKey=APPCRASH
AppName=RStudio R Session
AppPath=C:\Program Files\RStudio\bin\rsession.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=5AFC80132B25FA2BDB3FB474F8A17CBA
MetadataHash=-1576858806
</details>

**Comment by benjjneb** [comment]
Can confirm that crash. Workaround is easy w/ standard filtering, but agree would be nice to more gracefully handle this.
