### ISSUE TITLE
Assign Taxonomy UNITE8.2 error

### ISSUE THREAD

**Issue by enurta2020** [benjjneb/dada2#1028]
Hello,

I am having trouble assigning taxonomy using 2 of the UNITE8.2 for fungi from the general release category as suggested in the ITS pipeline for dada2. I am getting the following error:

Error in .Call2("fasta_index", filexp_list, nrec, skip, seek.first.rec,  : 
  reading FASTA file /home/ABO.local/nein/Projects/ITSd/UNITEgeneralFASTAreleaseForFungi.fasta: ">" expected at beginning of line 1
Calls: assignTaxonomy ... lapply -> FUN -> .read_XStringSet -> fasta.index -> .Call2
Execution halted

Ive gone thru some posts here, found people with same problem but nothing solved beside moving for a different comp. i am using HPC therefor moving is not an option.

Thanks so much!

**Comment by benjjneb** [comment]
What do the first couple lines of the fasta look like? In the shell, what is the output of

```
head -n 4 UNITEgeneralFASTAreleaseForFungi.fasta
```

**Comment by enurta2020** [comment]
Thanks benjamin, its:

sh_general_release_04.02.2020/000755 000766 000024 00000000000 13616615434 016305 5ustar00kessystaff000000 000000 sh_general_release_04.02.2020/developer/000755 000766 000024 00000000000 13616615434 020272 5ustar00kessystaff000000 000000 sh_general_release_04.02.2020/sh_general_release_dynamic_04.02.2020.fasta000644 000766 000024 00201300570 13616223120 025740 0ustar00kessystaff000000 000000 >Nectria_magnispora|JF832665|SH1546528.08FU|refs|k__Fungi;p__Ascomycota;c__Sordariomycetes;o__Hypocreales;f__Nectriaceae;g__Nectria;s__Nectria_magnispora
ACCGAGTTTACAACTCCCAAACCCCTGTGAACATACCTTTATTGTTGCTTCGGCGGGATCGCCCCGGCGCCTTCGGGCCCGGACCCAGGCGCCCGCCGGAGGCCCCAAACTCTTGTTTCTATTGTGGATTCTTCTGAGTAATACAAGTTAATAAATTAAAACTTTCAACAACGGATCTCTTGGTTCTGGCATCGATGAAGAACGCAGCGAAATGCGATAAGTAATGTGAATTGCAGAATTCAGTGAACCATCGAATCTTTGAACGCACATTGCGCCCGCTAGTATTCTGGCGGGCATGCCTGTTCGAGCGTCATTTCAACCCTCAAGCCCCCGTGGCTTGGTGTTGGGGATCGGCCAAGCGGCTCCCCGCCCTCACGGGCGGGTGCGCCCGGCCGGCCCCGAAATCTAGTGGCGGTCTCGCTGTAGTCCTCCTCTGCGTAGTAATACACCTCGCACCGGAACTTGGCCTGGCCACGCCGTAAAA
>Thyronectria_okinawensis|JF832674|SH1546620.08FU|refs|k__Fungi;p__Ascomycota;c__Sordariomycetes;o__Hypocreales;f__Nectriaceae;g__Thyronectria;s__Thyronectria_okinawensis
ACCGAGTTTACAACTCCCAAACCCCTGTGAACGTACCTCTTGTTGCTTCGGCGGGATCGCCCCGGCGCCCCCGTGCCCGGAATCAGGTGCCCGCCGGAGACCCCAAACTCTTGTTTCCTTTGGTGAGATCTTCTGAGTCCTACAAACAAATAAATCAAAACTTTCAACAACGGATCTCTTGGTTCTGGCATCGATGAAGAACGCAGCGAAATGCGATAAGTAATGTGAATTGCAGAATTCAGTGAATCATCGAATCTTTGAACGCACATTGCGCCCGCTAGTACTCTAGCGGGCATGCCTGTTCGAGCGTCATTTCAACCCTCAAGCCCCCGGGGCTTGGTGTTGGGGATCGGCCGCCGCTCACCCGGTGGCCGGCCCCGAATTCTAGTGGCGGTCTCGCTGCAGCCTCCCCTGCGTAGTAGCACACCTCGCACCGGAACTCAGCGTGGCCACGCCGTAAAA

Guess ill have to del from the 1st line everything till >Nectria ?

**Comment by benjjneb** [comment]
> Guess ill have to del from the 1st line everything till >Nectria ?

Yeah I think if you do that it should work, but can you let us know either way?

**Comment by enurta2020** [comment]
I am proud to announce, problem solved but, these bad files originated from here https://unite.ut.ee/repository.php thus its a general issue and i think it is worth a note.
Thanks Benjamin!

**Comment by benjjneb** [comment]
Yes definitely worth a note, I'll have to take a look if they changed their format with a new header line in their more recent releases.

**Comment by jarrodscott** [comment]
I used `wget` to download the UNITE general FASTA release for Fungi, [DOI: 10.15156/BIO/786368](https://plutof.ut.ee/#/doi/10.15156/BIO/786368), Anyway, I opened the `.gz` file with `guzip` on the server and it was just some crazy long file name, no extension. I added `.fasta` and ran `head -4...` on the file and  saw the same thing described by @enurta2020. So instead I downloaded the file to may mac and double clicked the `.gz`. Turns out its a directory with a fasta file and then another sub directory with a "dev" version of the fasta file. Open these individually and the header is fine

**Comment by jarrodscott** [comment]
It looks to be the same for the other variations of the new 2020 databases. Unclear to me what the difference between them all is.

**Comment by termithorbor** [comment]
Hi all,
I have also a problem when using the unite db with assignTaxonomy. When I use the 8.0 db for eukarya it works but species is only saved like this in the taxa table: s_guianense
and not like s__Brosimum_guianense.

The first lines of the fasta file look like this:

>Brosimum_guianense|AY635481|SH1641820.08FU|reps|k__Viridiplantae;p__Anthophyta;c__Eudicotyledonae;o__Rosales;f__Moraceae;g__Brosimum;s__Brosimum_guianense
CGTAGGTGAACCTGCGGAAGGATCATTGTCGAAACCTGCCCAGCAGAAAGACCCGCGAACACGTCAGAAACACTCGGGGGGCACAGGGTGCCAATGAGCCTCGAACCCCCTGTGCCTAGGGCTTCGGCCACGGTCGACGTCCTAGGCTTAAAAACAAACCCCGGCGCGGAATGCGTCAAGGAAAAAAGATGGAACGACCCATGCCGCCATAGCCCCGGAAAACGGTGCATTGCTGTGGTGGTTGATTCGTGATTGTTTTAAGTCAAAACGACTCTCGGCAACGGATATCTCGGCTCTCGCATCGATGAAGAACGTAGCGAAATGCGATACTTGGTGTGAATTGCAGAATCCCGTGAACCATCGAGTCTTTGAACGCAAGTTGCGCCCGAAGCCATTTGGTCGAGGGCACGTCTGCCTGGGCGTCACACATCGTTGCCCCCCTAAACACCCCATGACACTCCCTGTTGGGTGTGTCTGGATTGATCAGGGGCGGAGGATGGCCTCCCGTGCGCACTTTGTCTCGCGGTTGGTCCAAAATTGAGTCCTCAGCCACACTGTAGTGGCAATAGGTGGTTGTCGATCATTCGGTGCCCCGTCACGTGTGTTGGCCTTGAATCGGGACTCGTGTAGACCCCAATACATCTCTTACGGATGCTTCCAATGCGACCCCAGG
>Ochroma_pyramidale|AY635547|SH1641804.08FU|reps|k__Viridiplantae;p__Anthophyta;c__Eudicotyledonae;o__Malvales;f__Malvaceae;g__Ochroma;s__Ochroma_pyramidale
TCGTAGTGAACCTGCGGAAGGATCATTGTCGAAACCTGCCCAGCAGAACAACTCGTGAACGCGTTACTAAAAATACATCTTGAGGGGGCGCGGATGCATTCGTGCCCCTGGCCCCCTCAACGCCCCGTCGTGCGTGACCCTGCCTTGCCACGCCTCCAAGGTGGGTGAGATGCCTGGTCTCGTCGCTCGTGGCTGAATAACCAACCCCCGGCGCGAATCGCGCCAAGGAATCGGAACGAAAATGAGCACGTATGCCGTCGCCGCCCCGTTCGCGGTGTCCGTGCGGCAGCAACGTGACTCCTCTGTCGCGAAAATATAAAACGACTCTCGGCAACGGATATCTCGGCTCTCCCATCGATGAAGAACGTAGCGAAATGCGATACTTGGTGTGAATTGCAGAATCCCGTGAACCATCGAGTCTTTGAACGCAAGTTGCGCCCCAAGCCATTAGGCCGAGGGCACGTCTGCCTGGGTGTCACGCATCGTCGCCCCCTGTCAAAAACCCCCGGCCCATTGGGCTCCGGTTGAAGCGGGGGCGGAAATTGGCCTCCCGTGCGCTCCCTGCTCATGGTTGGCCTAAAAACGAGTCCTCGGCAGAGATAGCGCCGTGACGATCGGTGGTAATGCTTCGAGCTGCCTCGTCTCCAGTCGCGCGTGCTTCTTGTTTGCCTGGACCCTTAAACCCTCTCTGCATCACACGGATGATGCTCGCATCGCGACCCCCAGTTCAGGCGGATCACCCGCTGAGTTAA
>Tortula_platyphylla|GQ339756|SH1641826.08FU|reps|k__Viridiplantae;p__Bryophyta;c__Bryopsida;o__Pottiales;f__Pottiaceae;g__Tortula;s__Tortula_platyphylla

Does anyone know the problem?
