### ISSUE TITLE
How to import csv dada2-output to phyloseq

### ISSUE THREAD

**Issue by marcelavillegasp** [benjjneb/dada2#1031]
Hi, 
I am trying to import the csv dada2-output to phyloseq (I do not have the rds files) but I got the error: 
Error in validObject(.Object) : invalid class “phyloseq” object: 
 Component taxa/OTU names do not match.
 Taxa indices are critical to analysis.
 Try taxa_names()

I've tried using: 
> seq_table <- read.table("seqtab.nochim.csv")
> taxa_matrix <- as.matrix("taxa.csv") 
> sampledata1 <- read.table("MappingFile.txt", header = TRUE, row.names=1, fill=TRUE, sep = "\t")
> set1 <- phyloseq(otu_table(seq_table, taxa_are_rows=FALSE), sample_data(sampledata1), tax_table(taxa_matrix))

I do not understand what I have to do with taxa_names. 

Thanks for the help!

**Comment by benjjneb** [comment]
> I do not understand what I have to do with taxa_names.
> Thanks for the help!

What I recommend is inspecting each of the imported objects in your R workspace, and trying to identify the ones that don't look right and figure out how to fix the way they are being imported. 

The sequence table should have rows named by sample, columns named by sequence (or a synonym) and be a numeric matrix.

The taxonomy table should be a character matrix with rows named by sequecne (or synonym) and columns named by the taxonomic levels.

The sample data should be a data.frame with rows named by sample, and columns named by the various metadata categories.

ps: I highly recommend using RDS objects in the future. Much, much easier, and avoids all kinds of formatting/typing headaches when doing input/output to flat text files.
