### ISSUE TITLE
Remove non-target sequences V3V4 region 16s

### ISSUE THREAD

**Issue by termithorbor** [benjjneb/dada2#1033]
Dear all,

I sequenced the v3v4 region of 16s. I have some sequences which are shorter than 400 bp after merging. Would you recommend to remove those short sequences and at which length would you make the cut?

Thanks in advance :)

**Comment by benjjneb** [comment]
What is the expected range of amplicon sequences? Do you care if you include sequences out of that range?

This is a choice based on your science.

**Comment by termithorbor** [comment]
They should be around 450 bp. It is just for metabarcoding so to check what kind of bacteria are in a given sample.

**Comment by benjjneb** [comment]
Then remove sequences shorter than expected from bacteria, if that is important to your future analyses.

**Comment by termithorbor** [comment]
I found that the range for this region is 380-500 bp. Can anyone confirm this?
Thanks in advance.

**Comment by jgrzadziel** [comment]
@termithorbor 
V3-V4 region is quite problematic, and one of it's issues is that length can vary from as little as 280 to almost 500. The easiest way to check this is to run some _in-silico PCR_ using V3V4 primers and for example some curated database.

Here are my results:

**Min.   :286.0**
1st Qu.:404.0  
**Median :421.0**  
**Mean   :415.1**  
3rd Qu.:427.0  
**Max.   :469.0**  

If remove sequences shorter than e.g. 250 bp, you can lost a lot of data, and introduce serious biases to your subsequent analysis.

Just for a comparison, see how the **V4** region is conservative in a lenght:

 **Min.   :242**  
 1st Qu.:253  
 **Median :253**  
 **Mean   :253**  
 3rd Qu.:253  
 **Max.   :263**

**Comment by termithorbor** [comment]
Thanks for this very detailed answer. So cutting everything below 250 might bei okay? I do not really understand how you confirm the length of your own data.

**Comment by jgrzadziel** [comment]
@termithorbor 
I did _in-silico_ PCR *** using mothur, RDP reference database and the primers sequences. I assumed that such database is curated and contain zero non-biological sequences.  Then I calculated some basic statistics for the resulted sequences (after "PCR"). 

Maybe try to cut different lengths, and then compare obtained results. This is the best method to figure out your own data.  You can also keep all sequences and compare the results. But 250 should be ok :) 

For classifying use IDTAXA, it will produce less false positive matches.

*** _in silico_ means that the "reaction" was performed using software (some kind of simulation)

**Comment by termithorbor** [comment]
@jgrzadziel 
Do you probably have a guide/protocol for this:
I did in-silico PCR *** using mothur, RDP reference database and the primers sequences. I assumed that such database is curated and contain zero non-biological sequences. Then I calculated some basic statistics for the resulted sequences (after "PCR").

And thanks again for your answer.

**Comment by jgrzadziel** [comment]
@termithorbor 
Here is my email, if you need some help:
jgrzadziel[at]iung.pulawy.pl

In mothur you simply run the command:
`pcr.seqs(fasta=your.reference.database.fasta, oligos=your.primers.txt, pdiffs = 2, rdiffs = 2)`
where, pdiffs and rdiffs allow to choose how many differences are allowed in each primer.

**See here**
https://mothur.org/wiki/pcr.seqs/

**Comment by termithorbor** [comment]
@jgrzadziel 
Thanks again - I might contact you soon.

**Comment by hlfreund** [comment]
@jgrzadziel Thank you for the detailed answer!! I was having the same question as @termithorbor.
