### ISSUE TITLE
Joining noisy sequences into one ASV

### ISSUE THREAD

**Issue by andzandz11** [benjjneb/dada2#1034]
Sorry to bother you again.
I have 10 sequences from Pinus in my sequence data. The sample has ~45000 reads, each F and R respectively. The sample is split in technical replicates A, B and C with 15000 reads each.

If I set OMEGA_A/P to 0.99 I get all ten sequences from the data, each as an ASV. 
![1591407812](https://user-images.githubusercontent.com/19622117/83933433-b28ab300-a7a8-11ea-927a-d8cd75cc6d9f.gif)

If I set OMEGA_A/P to 1e-10 I loose 4 of the 10 sequences, especially in B (thee A sequences are put into one ASV, great job).
![1591407838](https://user-images.githubusercontent.com/19622117/83933436-bae2ee00-a7a8-11ea-9e46-86653e81fde8.gif)

Can I maybe set a parameter to correct the SNP in B and join them in an ASV instead of discarding the noisy sequences? DADA2 recognizes correctly that these sequences contain errors and removes them, but I would like to join them together more aggressively.
Which value of KDIST_CUTOFF would you recommend? Why does 0.42 correspond to 10%?

[mydata.zip](https://github.com/benjjneb/dada2/files/4739202/mydata.zip)

**Comment by andzandz11** [comment]
/edit
I will try something.

**Comment by benjjneb** [comment]
Sorry I'm confused, is this still an open question?

**Comment by andzandz11** [comment]
Yes. I am checking for presence / absence, so if I loose reads it means I will be unable to detect that respective species. I don't care so much if the reads have errors or not, I must avoid loosing the read at all costs, as long as it can be clearly identified to species level. So I am setting OMEGA to 0.99 but I feel this is not the best thing to do because then I don't get ASVs after all. I struggle to understand why the reads get kicked out in my example above. Thank you!

**Comment by andzandz11** [comment]
Ok, cool! Thanks! I always feel like I am doing something wrong, i.e. not intended, when I crank the parameters all the way to thier maximum to get what I want.
