### ISSUE TITLE
A lot of reads lost (>50%) after chimera check

### ISSUE THREAD

**Issue by shyam-mayengbam** [benjjneb/dada2#1035]
Hi Ben,
I have an issue with my 16S data analysis using dada2. The amplicon is v3-v4. Reads are 300bp. I trimmed at 285 and 240. After chimera removal, I got only around 66% of the merged reads and only around 40% of the input reads. I am not able to figure out where it went wrong. Could you please provide any comments on it. I am pasting some of the codes and the results I got below.

![fnFS agreegate](https://user-images.githubusercontent.com/31748836/83930077-15515f80-a753-11ea-8cc5-d4ab7171c287.jpg)
![fnRS agreegate](https://user-images.githubusercontent.com/31748836/83930076-14b8c900-a753-11ea-87af-565b33fce1bc.jpg)

Here is trimming, I used.
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(285, 240),
                       maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                       compress=TRUE, multithread=FALSE)  

##########################
```{r, echo=TRUE}
table(nchar(getSequences(seqtab)))
```

 294   296   298   301   320   334   342   347   355   357   360   370   375   382   388 
    3     6     1     1     1    13     1     1     1     4     1     2     1     2     1 
  395   400   409   424   427   431   436   438   439   440   441   442   443   444   445 
    1     1     1     7     2     3     3    19  1130 15053  2614  1711  1808    75   600 
  446   447   448   449   450   451   455   456   457   458   459   460   461   463   464 
  283   244    56   561     8     1     1    12    69    47   431  9696    79     5  1333 
  465   466   467   501 
 4355   320     1     1 
#########################
seqtab2 <- seqtab[, nchar(colnames(seqtab))%in% 437:467]
##########################

Summary

 input filtered denoisedF denoisedR Merged Nochim
Li16683 46267    31462     30492     30716  28854  18555
Li16684 37551    25236     24624     24671  23244  15199
Li16685 37460    27190     26664     26799  25483  16158
Li16686 32621    22672     22061     22166  20753  14106
Li16687 34933    24465     24035     24062  22834  14620
Li16688 43182    29885     28756     29083  26816  19772
        out.Percent Merge.Percent Nochim.Percent
Li16683    68.00095      94.62810       64.30651
Li16684    67.20460      94.39571       65.38892
Li16685    72.58409      95.57081       63.40698
Li16686    69.50124      94.07098       67.97090
Li16687    70.03407      95.00312       64.02733
Li16688    69.20708      93.25358       73.73210

**Comment by benjjneb** [comment]
From the tutorial:

> If a majority of reads were removed as chimeric, you may need to revisit the removal of primers, as the ambiguous nucleotides in unremoved primers interfere with chimera identification.

You still have your primers on your reads. You can remove them with `trimLeft=c(FWD_PRIM_LEN, REV_PRIM_LEN)` during the `filterAndTrim` step. If this is the "Illumina" V3V4 protocol, the primer lengths are `17` and `21`.

**Comment by shyam-mayengbam** [comment]
Thanks, Ben. 

I think it works. Please see below.

I have one more question. After filter, I got around 66% (out). Do you think if I can improve this or it is the nature of the data?

Here is some of the codes and their output.

```{r, echo=True}

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs,trimLeft = c(17,21), truncLen=c(285, 240),
                       maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                       compress=TRUE, multithread=FALSE)  

```

                                  reads.in reads.out
Li16683_S1_L001_R1_paired.fasta      46267     31492
Li16684_S13_L001_R1_paired.fasta     37551     25254
Li16685_S25_L001_R1_paired.fasta     37460     27210
Li16686_S37_L001_R1_paired.fasta     32621     22691
Li16687_S49_L001_R1_paired.fasta     34933     24482


```{r, echo=TRUE}
table(nchar(getSequences(seqtab)))
```
268  282  296  304  309  317  319  322  332  337  344  345  350  357  362  371  373  375  386  389  393  398  400  401  402  403  404  405  406  407  408  409  410  411  412  413 
   8    1    2    1    1    1    1    1    2    1    1    2    1    1    1    1    1    1    5    1    3    3    4  303 3517  605  344  445   31  139   61   60   25  130    6    1 
 417  418  419  420  421  422  423  425  426  427  428  429  440  456  463 
   1    8    8   14  136 1289   17    3  210  730  204    1    1    1    1 


```{r,echo=TRUE}
seqtab2 <- seqtab[, nchar(colnames(seqtab))%in% 400:429]
```

```{r, echo=TRUE}
sum(seqtab.nochim)/sum(seqtab2)
```

[1] 0.9607999

   input filtered denoisedF denoisedR Merged Nochim out.Percent Merge.Percent Nochim.Percent
Li16683 46267    31492     30959     31168  29928  29046    68.06579      96.66979       97.05293
Li16684 37551    25254     24835     25017  23995  22471    67.25254      96.61768       93.64868
Li16685 37460    27210     26915     27044  26244  23542    72.63748      97.50697       89.70431
Li16686 32621    22691     22336     22523  21696  21288    69.55949      97.13467       98.11947
Li16687 34933    24482     24203     24251  23565  22228    70.08273      97.36396       94.32633
Li16688 43182    29909     29230     29553  28291  26384    69.26266      96.78755       93.25934
Li16689 35103    24476     23956     24107  23069  22268    69.72623      96.29738       96.52781

Thank you very very very much.

**Comment by benjjneb** [comment]
> After filter, I got around 66% (out). Do you think if I can improve this or it is the nature of the data?

I think that is not a cause for concern at all. More lower-quality data usually doesn't help things, and can even make them worse.

**Comment by shyam-mayengbam** [comment]
Awesome, Thank you so much again.

**Comment by Shanip05** [comment]
Hi Ben, 

I used the trimLeft function to remove primers and still got a large removal of chimeric reads. 
Below is my script. Is it usual to lose this much ? 

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(230,160),trimLeft = c(19,20),
                     maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, multithread=TRUE) # On Windows set multithread=FALSE

      input filtered denoisedF denoisedR merged nonchim
AQ1  245423   237684    236820    237242 227618  189740
AQ10 280143   266031    263602    264823 248786  176173
AQ11 316154   299521    297085    298288 282759  205107
AQ12 192273   186347    185638    185985 181311  147325
AQ13 189885   179901    179539    179641 177315  157305
AQ2  327086   311197    308860    310017 295098  210406

**Comment by benjjneb** [comment]
It looks like at this point you are losing ~25% of your reads as chimeric. This is at the upper limit of what we see in amplicon data, but it is within range.

Going forward, I would consider revisiting the PCR protocols you are using. There are several modifications that can reduce chimera formation, including increasing the extension time during PCR, reducing the number of PCR cycles, and ensuring that you are not exhausting any of the reagents during the reaction.
