### ISSUE TITLE
Getting rid of primers 

### ISSUE THREAD

**Issue by termithorbor** [benjjneb/dada2#1036]
Dear all,

I have a small problem with getting rid of primers using cutable within the pipline.

I checked for primers in my reads and got this:

                                 Forward Complement Reverse RevComp
FWD.ForwardReads  352284          0             0          15
FWD.ReverseReads      47               0            0           289
REV.ForwardReads      34                0            0          444
REV.ReverseReads  291641            0             0          1

Then I used this code:
for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                             fnFs.filtN[i], fnRs.filtN[i])) # input files
}

The result was this:
                                    Forward Complement Reverse RevComp
FWD.ForwardReads       0          0                    0            15
FWD.ReverseReads      47          0                    0            0
REV.ForwardReads      34           0                    0            0
REV.ReverseReads       0             0                    0            1

How do I get rid of the remaining primer sequences?

Many thanks in advance :)

P.S: Might running the script again with the processed reads but loading the forward reads as reverse reads and the reverse reads as the forward reads do the trick?

**Comment by benjjneb** [comment]
I think you're in fine shape. A few primer remaining primer hits in places where they weren't expected to be probably just represents different sensitiviites between cutadapt and the R code, and isn't going to have any meaningful effect on your results.

You've gotten rid of ~99.99% of the originally detected primers, that's success.

**Comment by termithorbor** [comment]
Thank you very much :)

**Comment by termithorbor** [comment]
I now have reads with 0 length - so adjusting the cutadapt part with -m 1 is they way to go to prevent downstream problems, right? But how are 0 length sequences created?
The smallest read had around 200 bp and the primers are each around 20 bp.

Thank´s again for your help.

**Comment by benjjneb** [comment]
After cutadapt you should do a `filterAndTrim` step where you can enforce a `minLen` to remove zero-length reads.

I don't know how the 0 length reads are created, by cutadapt somehow it would seem.

**Comment by termithorbor** [comment]
Is it probably that I only need the -a and -A for 16s paired end primers and not the -g -G one of cutadapt?

Thanks again in advance.

**Comment by benjjneb** [comment]
Yes usually.
