### ISSUE TITLE
   Self-consistency loop terminated before convergence.

### ISSUE THREAD

**Issue by dvc28** [benjjneb/dada2#1039]
Hello, 
I am running the dada2 script (dada2 version1.17.0) with 3 samples (2x250 ilumina miseq amplicon sequencing V3-V4 region) as an initial trail for the rest of my samples (23 in total).  I have already run the filtering and trimming steps, but I am stuck at the error estimation step.
The errF works, but is it ok that the error abruptly increases at Q40? If not, do you have a suggestion on how to better estimate the error?
errR does not converge, but I cannot check if the rates obtained are close to zero. How can I check this? Would it better to use more samples?
thanks!

    errF <- learnErrors(filtFs, multithread=FALSE, verbose=TRUE)
    83562144 total bases in 369744 reads from 3 samples will be used for learning the error rates.
    Initializing error rates to maximum possible estimate.
    selfConsist step 1 ...
    selfConsist step 2
    selfConsist step 3
    selfConsist step 4
    selfConsist step 5
    selfConsist step 6
    selfConsist step 7
    selfConsist step 8
    selfConsist step 9
    Convergence after  9  rounds.

    plotErrors(errF, nominalQ=TRUE)
![sample_errF](https://user-images.githubusercontent.com/66942557/84637832-7668f800-aef6-11ea-9c46-8b69cbb9a4bd.png)

    errR <- learnErrors(filtRs, multithread=FALSE, verbose=TRUE) 
    82452912 total bases in 369744 reads from 3 samples will be used for learning the error rates.
    Initializing error rates to maximum possible estimate.
    selfConsist step 1 ...
    selfConsist step 2
    selfConsist step 3
    selfConsist step 4
    selfConsist step 5
    selfConsist step 6
    selfConsist step 7
    selfConsist step 8
    selfConsist step 9
    selfConsist step 10
    Self-consistency loop terminated before convergence.

    dada2:::checkConvergence(errR[[1]])
    Error: $ operator is invalid for atomic vectors
    dada2:::checkConvergence(errF[[1]])
    Error: $ operator is invalid for atomic vectors

**Comment by benjjneb** [comment]
> errR does not converge, but I cannot check if the rates obtained are close to zero. How can I check this? Would it better to use more samples?

Can you rerun your `checkConvergence` call on `errR` (not `errR[[1]]`), and post the results? That will fix the error you are seeing.

Also, if you like you could try running it on more samples, and see if the error model (black line in the plots) changes significantly. That's the empirical way to test if more data will shift the model.

**Comment by dvc28** [comment]
1-that fix worked, (dada2:::checkConvergence(errR) )  thanks for the quick answer... 

2-this error plot is from the same set but based on the 23 samples, (uses 4 samples to learn error rate). I get the same abrupt increase towards Q40. Do you know any fix for this? 
![errF](https://user-images.githubusercontent.com/66942557/84696648-1d787e80-af4d-11ea-99ed-f7b925b4cf4a.png)

3-When I ran learnErrors for the reverse sequences with max 10 steps it did not converge. However I changed the number of steps to 20 and then the error rate converged after 10 steps. Can you explain why this occurs?
    >errR <- learnErrors(filtRs, multithread=FALSE,verbose=TRUE,MAX_CONSIST = 20) 
     82452912 total bases in 369744 reads from 3 samples will be used for learning the error rates.
     Initializing error rates to maximum possible estimate.
     selfConsist step 1 ...
     selfConsist step 2
     selfConsist step 3
     selfConsist step 4
     selfConsist step 5
     selfConsist step 6
     selfConsist step 7
     selfConsist step 8
     selfConsist step 9
     selfConsist step 10
     Convergence after  10  rounds.
     > dada2:::checkConvergence(errR)
     [1] 40.54649867  2.44729900  0.42826667  0.07084493  0.01272796  0.02365347  0.01352300
     [8]  0.01579505  0.00000000  0.01579439

**Comment by benjjneb** [comment]
The convergence stats look good. Absolute convergence is great, but the goal here is to get a good error model, not a perfect one, and the 4-order-of-magnitude drop in those numbers (representing the absolute difference over all transtiiosn and Q-scores) from start-to-finish indicates that the error model has reached close to what convergence would be.

On the "hook" issue: Did your sequencing data have binned quality scores?

**Comment by dvc28** [comment]
not sure on the binned quality scores. how can I check the quality scores from a fq.gz file? if they were, would this explain the "hook" issue? 

I have now run the learnError with 4 of 23 samples and there was again no convergence after 20 runs, but it is fortunately decreasing. 
    
    > dada2:::checkConvergence(errF)
    [1] 4.861002e+01 2.298380e+00 1.370950e+00 8.368574e-02 1.279634e-02 9.245622e-03
    [7] 6.067103e-03 3.818158e-04 7.158982e-03 7.128227e-03 1.790822e-03 2.376163e-03
    [13] 3.455602e-04 5.843285e-03 6.135505e-03 1.566515e-03 2.864322e-03 7.236288e-03
    [19] 3.158075e-03 1.913263e-03

I would like to use this last error run to obtain the dadaFs ( *dadaFs<-dada(filtFs, err=errF, pool=TRUE, verbose=TRUE*). I am new to all this coding (as you can imagine), how exactly do I do this? err<-errF$err_in[[20]] ??  

Thanks for all your help!!

**Comment by benjjneb** [comment]
> I would like to use this last error run to obtain the dadaFs ( dadaFs<-dada(filtFs, err=errF, pool=TRUE, verbose=TRUE). I am new to all this coding (as you can imagine), how exactly do I do this?

Just use the `err` object. The `dada` command will use the "last" fitted error model from it.

**Comment by dvc28** [comment]
I thought *dada* would not use the "last" fitted error since there was no convergence. thank you for clarifying this. Have a great week!
