### ISSUE TITLE
Does Silva taxonomic training data formatted for DADA2 contain 28S sequences?

### ISSUE THREAD

**Issue by VeronicaBS** [benjjneb/dada2#1040]
I am working with the database from Callahan, Benjamin. (2018). Silva taxonomic training data formatted for DADA2 (Silva version 132) [Data set]. Zenodo.
It is detailed that these DADA2-formatted training fasta files were derived from the Silva Project's version 132 release, but it does not specify if it contains both SSU and LSU sequences or only SSU. In the SILVA Project, it is only possible to download each database separately.

I checked the sequences belonging to nematozoa group and I could not identify any 28S (LSU) sequence.
Does it contain both? If yes, are there SSU and LSU references sequences separately, or are reference sequences where SSU and LSU are artificially concatenated?

Thank you in advance,
Verónica

**Comment by benjjneb** [comment]
No its just SSU data, as the preprocessing to create the training fasta screens for the presence of the full-length 16S gene.

**Comment by VeronicaBS** [comment]
Thank you very much!
