### ISSUE TITLE
Primer removal with cutadapt

### ISSUE THREAD

**Issue by AndBris** [benjjneb/dada2#1041]
Hi all,

Has anyone had any issues using cutadapt through R/Rstudio?

I'm following the DADA2 ITS Pipleine Workflow (1.8) but get the following error when executing;

**> for(i in seq_along(fnFs.filtN)) {
+     system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2,
+                                "-o", fnFs.cut[i], "-p", fnRs.cut[i],
+                                fnFs.filtN[i], fnRs.filtN[i]))
+ }
sh: _Godwit_amps2//cutadapt/1-11_S1_L001_R1_001.fastq.gz: No such file or directory
sh: _Godwit_amps2//cutadapt/1-11_S1_L001_R2_001.fastq.gz: No such file or directory
sh: _Godwit_amps2//filtN/1-11_S1_L001_R1_001.fastq.gz: No such file or directory
sh: _Godwit_amps2//filtN/1-11_S1_L001_R2_001.fastq.gz: No such file or directory

cutadapt: error: You did not provide any input file names. Please give me something to do!**

Thanks for any help

Andy

**Comment by termithorbor** [comment]
How did you define fnFs.cut, fnRs.cut, fnFs.filtN and fnRs.filtN? And what is saved behind those variables?

**Comment by AndBris** [comment]
Thanks for the response and apologies that was a typo. I did use **for(i in seq_along(fnFs))**

I defined the output filenames as per the tutorial;

path.cut <- file.path(path, "cutadapt")
if(!dir.exists(path.cut)) dir.create(path.cut)
fnFs.cut <- file.path(path.cut, basename(fnFs))
fnRs.cut <- file.path(path.cut, basename(fnRs))

fnFs.cut, fnRs.cut, fnFs.filtN and fnRs.filtN are all character strings showing the path and name of each fastq file.

**Comment by benjjneb** [comment]
Can you post the output when you insert a `print` statement in that loop, so we can see what the command was that failed? Specifically, add this insides the loop, and before the system2 call:

```
args <- c(R1.flags, R2.flags, "-n", 2,  "-o", fnFs.cut[i], "-p", fnRs.cut[i], fnFs.filtN[i], fnRs.filtN[i])
print(args)
```

**Comment by AndBris** [comment]
Output below

> for(i in seq_along(fnFs)) 
+     args <- c(R1.flags, R2.flags, "-n", 2,  "-o", fnFs.cut[i], "-p", fnRs.cut[i], fnFs.filtN[i], fnRs.filtN[i])
> print(args)
 [1] "-g CCAGCASCYGCGGTAATWCC -a TYRATCAAGAACGAAAGT"                                   
 [2] "-G ACTTTCGTTCTTGATYRA -A GGWATTACCGCRGSTGCTGG"                                   
 [3] "-n"                                                                              
 [4] "2"                                                                               
 [5] "-o"                                                                              
 [6] "/Users/andrb9/Desktop/Goose_&_Godwit_amps2//cutadapt/G2_S23_L001_R1_001.fastq.gz"
 [7] "-p"                                                                              
 [8] "/Users/andrb9/Desktop/Goose_&_Godwit_amps2//cutadapt/G2_S23_L001_R2_001.fastq.gz"
 [9] "/Users/andrb9/Desktop/Goose_&_Godwit_amps2//filtN/G2_S23_L001_R1_001.fastq.gz"   
[10] "/Users/andrb9/Desktop/Goose_&_Godwit_amps2//filtN/G2_S23_L001_R2_001.fastq.gz"   
> {
+     system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
+                                "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
+                                fnFs.filtN[i], fnRs.filtN[i])) # input files
+ }
sh: _Godwit_amps2//cutadapt/G2_S23_L001_R1_001.fastq.gz: No such file or directory
sh: _Godwit_amps2//cutadapt/G2_S23_L001_R2_001.fastq.gz: No such file or directory
sh: _Godwit_amps2//filtN/G2_S23_L001_R1_001.fastq.gz: No such file or directory
sh: _Godwit_amps2//filtN/G2_S23_L001_R2_001.fastq.gz: No such file or directory
Warning message:
In system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, "-o",  :
  error in running command
This is cutadapt 2.10 with Python 3.7.6
Command line parameters: -g CCAGCASCYGCGGTAATWCC -a TYRATCAAGAACGAAAGT -G ACTTTCGTTCTTGATYRA -A GGWATTACCGCRGSTGCTGG -n 2 -o /Users/andrb9/Desktop/Goose_
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

cutadapt: error: You did not provide any input file names. Please give me something to do!

**Comment by benjjneb** [comment]
Do you notice that the directories with the "Goose_&Godwit" sometimes have underscores before, after, or not at all the ampersand?

I would suggest redefining the directory names to remove all special characters like ampersands, and retrying. Nothing but alphanumerics and underscores. Issues with special character parsing are a classic issue with filenames/systems.

**Comment by AndBris** [comment]
Problem solved. Thanks for you help
