### ISSUE TITLE
assignTaxonomy "Error in h(simpleError(msg, call)) :"

### ISSUE THREAD

**Issue by npcurtis** [benjjneb/dada2#1043]
Hello Dr. Callahan, 

I am having an issue assigning taxonomy to a matrix that I created by subsetting all Eukaryotes from my successful SILVA taxonomic assignment matrix ("SILVA"). When I view the subset matrix ("Euk") I can see that it successfully isolated the Eukaryotes, as desired. Here is what I did to make that matrix before attempting to assign taxonomy with another database (PhytoRef with PR2):

`>SILVA <- assignTaxonomy(seqtab.nochim, "D:/RF/Demulti_samp/silva_nr_v138_train_set.fa.gz", tryRC=TRUE, multithread=FALSE)`
`>SILVA <- addSpecies(SILVA, "D:/RF/Demulti_samp/silva_species_assignment_v138.fa.gz")`
`>SILVA_df <- as.data.frame(SILVA)`
`>Euk_df <- SILVA_df[SILVA_df$Kingdom == "Eukaryota", ]`
`>Euk <- as.matrix(Euk_df)`
`>PR16S <- assignTaxonomy(Euk,"D:/RF/Demulti_samp/pr2_version_4.12.0_16S_dada2.fasta.gz", multithread = FALSE)`

> Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'reverseComplement': key 49 (char '1') not in lookup table

Do you know why I may be getting this message? Would you recommend that I just assignTaxonomy to seqtab.nochim using PhytoRef, as I did with the SILVA database? Thank you!

**Comment by benjjneb** [comment]
Not sure, but your casting the matrix to a data.frame and then back again may be causing something unexpected to happen. I'd just avoid that and work directly with the matrix:

```
is.euk <- SILVA[,"Kingdom"] %in% "Eukaroyota"
Euk <- SILVA[is.euk,]
```

**Comment by npcurtis** [comment]
Thank you, I was having trouble subsetting that matrix by Kingdom without making it a data.frame. Keeping it a matrix as you suggested worked and the taxonomic assignment is running. Much appreciated!
