### ISSUE TITLE
how to customize DADA2-formatted SILVA v.138  reference database?

### ISSUE THREAD

**Issue by VeronicaBS** [benjjneb/dada2#1044]
I am working with SSU sequences from nematodes samples and I need to customize the DADA2 formatted SILVA v.138 database.  I want to add several sequences that are not present in the database and modify the taxonomy classification of some others that are present in the database.

I saw that there are two files assigned to DADA2 formatted database from Michael R. McLaren. (2020). Silva SSU taxonomic training data formatted for DADA2 (Silva version 138) [Data set]. Zenodo. http://doi.org/10.5281/zenodo.3731176:

    - silva_nr_v138_train_set.fa.gz
    - silva_species_assignment_v138.fa.gz

Which file should I use? Are both needed? How should I proceed? Is there a guide in which the steps to follow are described?

Thank you very much.

Best regards,
Verónica

**Comment by benjjneb** [comment]
For using the naive Bayesian classifier as implemented in `assignTaxonomy`, the `train_set` files are the appropriate reference files to use.

Our doc page on taxonomic assignment may be helpful: https://benjjneb.github.io/dada2/assign.html
