### ISSUE TITLE
Comapring sequence from NCBI SRA and custom experimental set 

### ISSUE THREAD

**Issue by Sarsi1411** [benjjneb/dada2#1045]
I am currently working on 16S microbiome analysis using dada2. I was looking to compare the sequences from NCBI SRA database and my experimental sequence. For your information, both are illumina miseq reads and V3-V4 region.

I had trouble during Filter and Trim step as I was not able to put all forward/reverse reads together. The code below, I understand this code recognizes only the file ending with _R1_001.fastq. 

fnFs <- sort(list.files(path, pattern="_R1_001.fastq", full.names = TRUE))
 
So I tried,  
fnFs <- sort(list.files(path, pattern= c("_R1_001.fastq", ".sra_1.fastq"), full.names = TRUE))
still it didn't recongize and I understood that only during this step,

filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
The filtered folder had only files from my experimental set but not from the SRA. So I am not sure how to pull both together?

I hope my question is clear. Since I am new to the microbiome analysis, I am a bit confused. Please help me to overcome this issue. 

I really appreciate your help
Thanks,
Saranya

**Comment by benjjneb** [comment]
What is an example file name of one of the fastq files you are wanting to analyze? Your code should reflect the format of that file name.

If you are trying to process and compare two different studies, you should process them separately, and then combine/compare them afterwards. So you shouldn't be trying to put them together in the first parts of the worfklow. See the Big Data workflow for an example of merging different runs (or studies): https://benjjneb.github.io/dada2/bigdata.html#merge-runs-remove-chimeras-assign-taxonomy

**Comment by Sarsi1411** [comment]
Thanks very much.
That was really helpful, I was able to merge the sequences from two different datasets however the phylogenetic tree construction does not go through and the R session crashes. This may be because of huge data but not sure. 
Just curious, if there are any other phylogenetic tree construction packages other than phangorn?

Thanks again

**Comment by spholmes** [comment]
We often do large tree reconstruction outside of r for very large trees,
RAXML works well.

**Comment by Sarsi1411** [comment]
Thank you. 
I have started the tree construction in RAXML server.
