### ISSUE TITLE
R session aborts at derep stage

### ISSUE THREAD

**Issue by gkpillay** [benjjneb/dada2#1046]
Hi,

My R session keeps aborting at sample inference stage for the forward reads ( dada(fnFor, err=errF, multithread=TRUE)). Command for the reverse reads is completed. 

I am using package version 1.16 and R version 4.0.1.

Would you have any insights?

Many thanks

**Comment by benjjneb** [comment]
What is the output of `table(file.exists(fnFor))`?
If that is all `TRUE`, then what is the output of:
```
library(ShortRead)
nseqs <- sapply(fnFor, function(f) length(readFastq(f)))
summary(nseqs)
```

**Comment by gkpillay** [comment]
Hi

The output is True 253

And below is the output for the second part
Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      4    6300   11683   14008   18613  265009 

Thank you

**Comment by benjjneb** [comment]
That seems fine.
Since the reverse reads are being processed fine, can you try to isolate the forwards sample(s) causing the problem?

One way to do this is to loop through subsets of the samples, running the problem command, and writing to a log file after each chunk succesfully completes. e.g.

```
fn.log <- "log.out" # This is where the output will be written, change filepath as appropriate
sink(fn.log)
for(i in seq_along(fnFor)) {
  dada(fnFor[[i]], err=errF, multithread=TRUE)
  cat(i, "\n")
}
sink()
```

**Comment by gkpillay** [comment]
Hi,

I tried your suggestion but it still kept crashing. So I split the dataset and tried to identify the troublesome sequence manually There were 2 problem samples, which kept showing the error message for command plotQualityProfile:

Error in density.default(qscore) : 'x' contains missing values

I assume this means the file is empty, but when I opened it there are sequences.

**Comment by benjjneb** [comment]
It sounds like these fastq files are malformed in some way, perhaps they don't have quality scores for all nucleotides or something like that.

If you read one of the trouble files in, do you get identical widths for the quality parts and the read parts?

```
library(ShortRead)
fq <- readFastq("path/to/problem_sample.fastq")
table(width(sread(fq)) == width(quality(fq)))
```

**Comment by gkpillay** [comment]
Hi,

Yes the output gives:

TRUE
12223

And TRUE for the other sequence too

**Comment by benjjneb** [comment]
Hmm...

Not sure. Can you share one of the problem files with me?

**Comment by gkpillay** [comment]
Hi

I’ve attached the folder here with the 2 samples.

Thanks
Kirthana

**Comment by benjjneb** [comment]
I don't see an attachment. Might be too big to attach to a GH comment.

You can email me at benjamin DOT j DOT callahan AT gmail DOT com

Please reference the GH issue in the email.

**Comment by benjjneb** [comment]
The problematic fastq files have at least one empty fastq entry (length-0 sequence) and when that entry is removed, they work correctly. I'd recommend you do minimal filtering of your files with `filterAndTrim` which enforces a `minLen=20` by default, and that should remove these problematic entries.

**Comment by gkpillay** [comment]
Hi 

Okay sure, thank you!
