### ISSUE TITLE
new flag "--discard-untrimmed"

### ISSUE THREAD

**Issue by annarizzibramucci** [benjjneb/dada2#1047]
Hello, 
I am running lots of bacterial 16s rRNA V1-V3 plates through your pipeline and finding that I get >50% reads through the entire pipeline, I first wanted to ask if that seems like a good amount and therefore I can stop optimising the run?

Second I just found your added flag "--discard-untrimmed" for the cutadapt section and wanted to run a test on it, and I found using that flag I lost >94% of reads during the first step, which did not happen without this step, does that imply that I am missing a lot of primers on my reads? In which case is that potentially an issue I need to dig into or something that isn't a problem?

Finally, I am merging on 10bp with maxMismatch = 1, and I just wanted to see if you thought that was ok, I have gotten those parameters because I was losing the most reads 30-40% during the merge step so I wanted to loosen restrictions there to optimise the number of reads I got through the pipeline (without allowing too many errors through)...

thanks so much for your help in this matter
Anna

**Comment by annarizzibramucci** [comment]
I rechecked how many primers were in this plate that I was testing with the new flag and it looks like not as many primers are there as we might expect, so maybe I shouldn't use the new flag at all in this circumstance....
                 Forward Complement Reverse RevComp
FWD.ForwardReads       0          0       0       0
FWD.ReverseReads       0          0       0    7709
REV.ForwardReads       0          0       0    8835
REV.ReverseReads       0          0       0       0

**Comment by benjjneb** [comment]
It looks like your primers are not sequenced at the start of the reads, so it isn't necessary to remove them there. They do show up when the reads "read-through" to the other primer when the amplicon is shorter than the read length.

You definitely would not want to use the `--discard-untrimmed` flag in this situation though, as the reads that don't have a primer on them are not spurious, they just come from amplicons that were longer than the read length, which is probably most of them for V1V3.
