### ISSUE TITLE
R/Dada2 version effect on reads passing filterAndTrim

### ISSUE THREAD

**Issue by montoyah** [benjjneb/dada2#1048]
Hi,

I'm working on comparing different primers for 16S amplicon gene seq in MiSeq. I noticed there is a difference of 20% or more reads passing quality control when I run `filterAndTrim` on R 4.0.1 (2020-06-06) with Dada2 1.16.0, versus R 3.6.3 (2020-02-29) with Dada2 1.14.1.

I'm running Ubuntu 18.04 and my reads are demultiplexed, primer-free, paired-end, 2x300 bp.
Is this 20% difference discrepancy something to be expected and "normal"? I wouldn't care for a 2% difference but 20% seems a lot to me.

Thanks in advance for any insights! Let me know if you need data to reproduce my findings or any other contextual info.

`filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(280,230),  maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE, minQ = 2, compress=TRUE, multithread=TRUE, verbose = TRUE)`

**R 4.0.1 (2020-06-06) with Dada2 1.16.0** 
                                                                      reads.in    reads.out   percentage
Sep-341-1-1_S1_L001_R1_001.fastq.gz     136605      88727       64.95150
Sep-341-2-2_S2_L001_R1_001.fastq.gz     141156      96955       68.68642
Sep-341-3-3_S3_L001_R1_001.fastq.gz     137030      91129       66.50296
Sep-341-4-4_S4_L001_R1_001.fastq.gz     122066      76134       62.37118
Sep-341-1-1_S13_L001_R1_001.fastq.gz   117580      61069       51.93825
Pool-341-2-2_S14_L001_R1_001.fastq.gz    87730      52519       59.86436
Pool-341-3-3_S15_L001_R1_001.fastq.gz    70811      42246       59.66022
Pool-341-4-4_S16_L001_R1_001.fastq.gz    89084      55705       62.53087

**R 3.6.3 (2020-02-29) with Dada2 1.14.1**
                                                                       reads.in    reads.out   percentage
Sep-341-1-1_S1_L001_R1_001.fastq.gz      136605      60543        44.31975
Sep-341-2-2_S2_L001_R1_001.fastq.gz      141156      64587        45.75576
Sep-341-3-3_S3_L001_R1_001.fastq.gz      137030      57152        41.70766
Sep-341-4-4_S4_L001_R1_001.fastq.gz      122066      55661        45.59910
Pool-341-1-1_S13_L001_R1_001.fastq.gz    117580      40631       34.55605
Pool-341-2-2_S14_L001_R1_001.fastq.gz     87730      33164        37.80235
Pool-341-3-3_S15_L001_R1_001.fastq.gz     70811      25887        36.55788
Pool-341-4-4_S16_L001_R1_001.fastq.gz     89084      36395        40.85470

**Comment by benjjneb** [comment]
So... no you shouldn't be seeing any difference i don't think. The `filterAndTrim` code was untouched between the 1.14 and 1.16 releases.

Can you try the following, to factor out any differences outside the dada2 code:

```
# Whatever code you had to get to the point above
library(devtools)
devtools::install_github("benjjneb/dada2", ref="v1.14.1")
out14 <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, ...) # Fill in ...
devtools::install_github("benjjneb/dada2", ref="v1.16")
out16 <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, ...) # Fill in ..., same as above
```

You can also consider just doing a couple samples instead of all of them for speed reasons.

That code should run in the same R session so that nothing else changes except the version of the dada2.

**Comment by montoyah** [comment]
The results match:
**out14**
reads.in reads.out
20190114-000-G002-UI46-NMR-MC-Sep-341-1-1_S1_L001_R1_001.fastq.gz   136605     88568
20190114-000-G002-UI47-NMR-MC-Sep-341-2-2_S2_L001_R1_001.fastq.gz   141156     92537
20190114-000-G002-UI48-NMR-MC-Sep-341-3-3_S3_L001_R1_001.fastq.gz   137030     90442

**out16**
                                                                  reads.in reads.out
20190114-000-G002-UI46-NMR-MC-Sep-341-1-1_S1_L001_R1_001.fastq.gz   136605     88568
20190114-000-G002-UI47-NMR-MC-Sep-341-2-2_S2_L001_R1_001.fastq.gz   141156     92537
20190114-000-G002-UI48-NMR-MC-Sep-341-3-3_S3_L001_R1_001.fastq.gz   137030     90442

By the way, version `ref="v1.14.1"` is not available but 1.14 is.

**Comment by benjjneb** [comment]
OK, so... is there a difference when using the same version of the package, let's say 1.16, with the two different versions of R you have installed?

You can use the same `devtools::install_github` approach to install the same version of the package to each version of R.

**Comment by benjjneb** [comment]
Please reopen if you have new results on this.
