### ISSUE TITLE
how does justConcatenate works?

### ISSUE THREAD

**Issue by rezenman** [benjjneb/dada2#1049]
Hey!
I am analyzing a paired-end run with 276 cycles from each side and a amplicon size of ~600bp.
In the mergePairs step, I use justConcatenate = TRUE in order to merge pairs of reads.
I didn't quite understand how the justConcatenate function works - is it based on read ID's? 
how does it handle multiple sequences with multiple read IDs that have "clustered" together? does it combinatorically merge all distinct combinations? 
Hope I explained myself clearly, if not please tell me
Thank u very much!

**Comment by benjjneb** [comment]
> is it based on read ID's?

Yes it is matching read-by-read, but it just uses read order within the original fastqs files (not quite as smart as read IDs, but faster and less memory intensive).

> how does it handle multiple sequences with multiple read IDs that have "clustered" together? does it combinatorically merge all distinct combinations?

Yes, everything is merged on a read-by-read basis, so all distinct combinations that are supported by a paired-read will be output.

**Comment by rezenman** [comment]
just to make sure I got it: let's say I have two sequences that their forward reads have "clustered together but their reverse ones have not - let's call them: A_1 and B_1 and their reverse A_2 and B_2, I'll get the following merged pairs: A_1 - A_2, A_1 - B_2 ?

**Comment by benjjneb** [comment]
Yep.
