### ISSUE TITLE
Can DADA2 be applied to multiple 16S region amplicon datasets?

### ISSUE THREAD

**Issue by GeoMicroSoares** [benjjneb/dada2#105]
Thinking of how feasible it might be to apply DADA2 to a dataset encompassing 454 amplicons across multiple 16S regions. Any thoughts?

**Comment by benjjneb** [comment]
You need to explain a little bit more.

These different-region-amplicons are pooled together in one run, and aren't tagged in a way that lets them be separated them into their own files? Or they can be split out?

Do they overlap at all?

Multiple regions from each sample, or some samples with one region, some with another?

**Comment by GeoMicroSoares** [comment]
Hello there,
They are split up, but some do not overlap, and yes, "some samples with one region, some with another".

**Comment by benjjneb** [comment]
So you can use DADA2 on this sort of data to get to the biological sequence variants, but it won't solve the problem of relating the results on non-overlapping regions of the 16S gene to each other.

Given that you have some samples with one region and some with another, I think the integration options are either to map the sequence variants to a common reference database of full length sequences, or to assign sequence variants to taxonomy and reduce the description of the communities to taxonomic abundances (ultimately this also involves mapping to reference sequences, but allows the option of reduction to levels broader than genus if your environment isn't mapping well to the references).
