### ISSUE TITLE
Loosing quite a lot of reads through filter and trim in the ITS Pipeline 

### ISSUE THREAD

**Issue by termithorbor** [benjjneb/dada2#1050]
Hi all,

I am loosing quite a lot of reads in the filter and trim step of the ITS pipline. I sequenced ITS2 (ITS3-KYO2 and ITS4 primer set) on Illumina Miseq. I have also removed primer sequences with cutadapt bofore this step.

filterAndTrim(fnFs, filtFs, fnRs, filtRs, maxN = 0, maxEE = c(2, 2), 
                     truncQ = 2, minLen = 50, rm.phix = TRUE, compress = TRUE, multithread = FALSE)

                                            reads.in     reads.out
S16_L001_R1_001.fastq.gz   659870    189748
S15_L001_R1_001.fastq.gz   780932    243676
S18_L001_R1_001.fastq.gz   650460    175871
S17_L001_R1_001.fastq.gz   814108    233314

What could the reason be?

Thanks in advance for your help :)

P.S. Setting maxEE to c(2,4) helped a bit, but is it reasonable to do so? Is it even still reasonable to go with c(4,4)? I think it makes sense to do some changes here because cutting the bad part of the sequences at the end is not really doable with ITS because of the length variation I guess. So I found that some people even do c(8,12) - what do you guys normally do?

This is what it looks like wit maxEE=c(8,12):
                                                                       reads.in reads.out
S16_L001_R1_001.fastq.gz   659870    585274
S15_L001_R1_001.fastq.gz    780932    690400
S18_L001_R1_001.fastq.gz   650460    571145
S17_L001_R1_001.fastq.gz    814108    721980

**Comment by benjjneb** [comment]
> What could the reason be?

Most probably your sequences have low-ish read quality.

> Setting maxEE to c(2,4) helped a bit, but is it reasonable to do so? Is it even still reasonable to go with c(4,4)? I think it makes sense to do some changes here because cutting the bad part of the sequences at the end is not really doable with ITS because of the length variation I guess. So I found that some people even do c(8,12) - what do you guys normally do?

Keeping lots of lower quality sequences is not really helping anything. Even with your `maxEE=2` cutoff you are still getting >100k reads in each sample. I personally would just stick with that, outside of very specific circumstances where probing variation at <0.0001 frequency in my samples was critical to my scientific question.

**Comment by termithorbor** [comment]
This is the quality profile of the forward reads:
![image](https://user-images.githubusercontent.com/66436023/85417980-8b85fc80-b570-11ea-81bd-8d0914f1ee87.png)

And this of the reverse reads:
![image](https://user-images.githubusercontent.com/66436023/85418116-b07a6f80-b570-11ea-9f29-2aaf39f2ba14.png)


So for the ITS2 region (ITS3-KYO2 and ITS4 primer set) you would not do truncLen right? Just the settings I used?

Thanks again :)

**Comment by benjjneb** [comment]
> And for the ITS2 region (ITS3-KYO2 and ITS4 primer set) you would not do truncLen right? Just the settings I used?

Yeah probably. I would also consider using only the forward reads, since the reverse reads are the quality issue. See for example: https://doi.org/10.1016/j.funeco.2019.03.005

**Comment by termithorbor** [comment]
Sounds reasonable - Thank you very much!
