### ISSUE TITLE
MakeSequenceTable 

### ISSUE THREAD

**Issue by reemelkabbout** [benjjneb/dada2#1051]
Hello everyone!
I hope you're doing fine.
I'm trying to make a sequence table for my sequences data. Note that the sequences have been merged already (I do not have the non-merged (raw) data). I'm getting that error every time I try: Error in makeSequenceTable(sequences): Requires a list of samples.

Commandes : 
1) sequences <- sort(list.files(my path, pattern=".fastq", full.names = TRUE))
2) sample.names <- sapply(strsplit(basename(sequences), "100_1000sampleA1 , 100_1000sampleA2 , 100_1000sampleA3 , 100_1000sampleB1 , 100_1000sampleB2 , 100_1000sampleB3 , 100_1000sampleC1 , 100_1000sampleC2 , 100_1000sampleC3"), `[`, 1)
**I have 9 samples and the seqeunces are alerady merged (A1, A2, A3 and B1, B2, B3, and C1, C2, C3).**
3) seqtab <- makeSequenceTable(sequences)
**Error in makeSequenceTable(sequences) : Requires a list of samples.**
Could anyone help me, please?
Thank you in advance!

**Comment by benjjneb** [comment]
Are you trying to make a sequence table without doing any denoising first?

Right now your `sequences` object is a list of filenames, which isn't what `makeSequenceTable` is expecting, and isn't how the command is typically used.

You can use it that way if you want though: `seqtab <- makeSequenceTable(derepFastq(sequences))`
