### ISSUE TITLE
Assign Taxonomy UNITE 8.2

### ISSUE THREAD

**Issue by termithorbor** [benjjneb/dada2#1052]
Hi all,
I have also a problem when using the unite db with assignTaxonomy. When I use the 8.2 db for eukarya it works but species is only saved like this in the taxa table: s_guianense
and not like s__Brosimum_guianense.

The first lines of the fasta file look like this:

Brosimum_guianense|AY635481|SH1641820.08FU|reps|k__Viridiplantae;p__Anthophyta;c__Eudicotyledonae;o__Rosales;f__Moraceae;g__Brosimum;s__Brosimum_guianense
CGTAGGTGAACCTGCGGAAGGATCATTGTCGAAACCTGCCCAGCAGAAAGACCCGCGAACACGTCAGAAACACTCGGGGGGCACAGGGTGCCAATGAGCCTCGAACCCCCTGTGCCTAGGGCTTCGGCCACGGTCGACGTCCTAGGCTTAAAAACAAACCCCGGCGCGGAATGCGTCAAGGAAAAAAGATGGAACGACCCATGCCGCCATAGCCCCGGAAAACGGTGCATTGCTGTGGTGGTTGATTCGTGATTGTTTTAAGTCAAAACGACTCTCGGCAACGGATATCTCGGCTCTCGCATCGATGAAGAACGTAGCGAAATGCGATACTTGGTGTGAATTGCAGAATCCCGTGAACCATCGAGTCTTTGAACGCAAGTTGCGCCCGAAGCCATTTGGTCGAGGGCACGTCTGCCTGGGCGTCACACATCGTTGCCCCCCTAAACACCCCATGACACTCCCTGTTGGGTGTGTCTGGATTGATCAGGGGCGGAGGATGGCCTCCCGTGCGCACTTTGTCTCGCGGTTGGTCCAAAATTGAGTCCTCAGCCACACTGTAGTGGCAATAGGTGGTTGTCGATCATTCGGTGCCCCGTCACGTGTGTTGGCCTTGAATCGGGACTCGTGTAGACCCCAATACATCTCTTACGGATGCTTCCAATGCGACCCCAGG
Ochroma_pyramidale|AY635547|SH1641804.08FU|reps|k__Viridiplantae;p__Anthophyta;c__Eudicotyledonae;o__Malvales;f__Malvaceae;g__Ochroma;s__Ochroma_pyramidale
TCGTAGTGAACCTGCGGAAGGATCATTGTCGAAACCTGCCCAGCAGAACAACTCGTGAACGCGTTACTAAAAATACATCTTGAGGGGGCGCGGATGCATTCGTGCCCCTGGCCCCCTCAACGCCCCGTCGTGCGTGACCCTGCCTTGCCACGCCTCCAAGGTGGGTGAGATGCCTGGTCTCGTCGCTCGTGGCTGAATAACCAACCCCCGGCGCGAATCGCGCCAAGGAATCGGAACGAAAATGAGCACGTATGCCGTCGCCGCCCCGTTCGCGGTGTCCGTGCGGCAGCAACGTGACTCCTCTGTCGCGAAAATATAAAACGACTCTCGGCAACGGATATCTCGGCTCTCCCATCGATGAAGAACGTAGCGAAATGCGATACTTGGTGTGAATTGCAGAATCCCGTGAACCATCGAGTCTTTGAACGCAAGTTGCGCCCCAAGCCATTAGGCCGAGGGCACGTCTGCCTGGGTGTCACGCATCGTCGCCCCCTGTCAAAAACCCCCGGCCCATTGGGCTCCGGTTGAAGCGGGGGCGGAAATTGGCCTCCCGTGCGCTCCCTGCTCATGGTTGGCCTAAAAACGAGTCCTCGGCAGAGATAGCGCCGTGACGATCGGTGGTAATGCTTCGAGCTGCCTCGTCTCCAGTCGCGCGTGCTTCTTGTTTGCCTGGACCCTTAAACCCTCTCTGCATCACACGGATGATGCTCGCATCGCGACCCCCAGTTCAGGCGGATCACCCGCTGAGTTAA
Tortula_platyphylla|GQ339756|SH1641826.08FU|reps|k__Viridiplantae;p__Bryophyta;c__Bryopsida;o__Pottiales;f__Pottiaceae;g__Tortula;s__Tortula_platyphylla

Does anyone know the problem? I guess it is because for species getting the names is different then for genus for example because for genus it is _genusname and for species it is _genusname_speciesname and you need both but I guess the algorithm only reads the stuff till the first _ from rigth to left.

Does anyone has an idea how to solve this problem?

**Comment by benjjneb** [comment]
> I have also a problem when using the unite db with assignTaxonomy. When I use the 8.2 db for eukarya it works but species is only saved like this in the taxa table: s_guianense
> and not like s__Brosimum_guianense.

Is this a problem? The same informatino is there, as the genus is recorded in the genus column.

**Comment by termithorbor** [comment]
Making nice graphs on the species level out of an phyloseq object is a bit tricky, because in the legend will allways be only the species name so sometimes it is a bit tricky to find out which one it is.

**Comment by benjjneb** [comment]
You can just use simple R manipulations to revise the species entries to your desired format then. E.g. to put the Genus species binomial in the species column:

```
nice.spec <- paste(tax[,"Genus"], tax[,"Species"])
tax.nice <- tax
tax.nice[,"Species] <- nice.spec
```

**Comment by termithorbor** [comment]
Thanks again :)
