### ISSUE TITLE
RemoveChimera takes too long.

### ISSUE THREAD

**Issue by reemelkabbout** [benjjneb/dada2#1053]
Hello Mr. Callahan,
I hope you're doing fine.

I have executed a script for removing chimera, now its been more than 12hrs and is yet to finish. Is it normal? 
Note that I've used the consensus method (seqtab.nonchim <- removeBimeraDenovo(seqtab, method = "consensus" , multithread= TRUE).
Is there anything I could do? Is there any possibility to pick only the true OTU and exclude chimeric sequences and skip chimera removing step? 

Thank you in advance

**Comment by benjjneb** [comment]
In certain datasets, chimera removal can take longer than denoising (although this is not the norm).
The exact time it is expected is very difficult to know beforehand, as it is affected by your compute resources and the complexity/size of your dataset.

I'd recommend letting it run longer and it will probably finish. If it takes unreasonable amounts of time, you may want to see if you can get access to some more powerful compute resources.

**Comment by reemelkabbout** [comment]
Okay! Thank you for your response, Mr. Callahan.

**Comment by reemelkabbout** [comment]
Hello again Mr. Callahan,
I just want to inform you that the chimera removing step has finished successfully. Thank you for developing such a powerful package for biological analysis!
