### ISSUE TITLE
Problems installing and running dada2 with conda environments

### ISSUE THREAD

**Issue by AleSR13** [benjjneb/dada2#1055]
Hello! I am trying to use dada2 with (mini)conda environments. I seem to have dependency problems between Rstudio and dada2 (I get this error 'Found conflicts! Looking for incompatible packages.' together with a list of multiple packages in which they are incompatible). After few attempts I could install them but then when I ran one of the first steps: plotQualityProfile(sample_1.fastq), it fails throwing an error:

Error in RStudioGD() :

  Shadow graphics device error: r error 4 (R code execution error)

In addition: There were 50 or more warnings (use warnings() to see the first 50)

I googled a solution and they recommended to re-install Rstudio. So I kind of end up going in circles! Do you know which version of Rstudio could be compatible? Thank you for the info!

**Comment by benjjneb** [comment]
Sorry I can't help with this. I don't maintain the bioconda build of dada2. I don't even use python anymore.

Maybe ask at the bioconda repository? Or... if Rstudio has a forum?
