### ISSUE TITLE
Outputting biom file from dada2 outputs

### ISSUE THREAD

**Issue by sandipansamaddar** [benjjneb/dada2#1056]
Hi,
I used dada2 for analyzing the 16S dataset and now I am trying to predict high-level phenotypes in the data using Bugbase. But while outputting the biom file I am facing some problems. I am not sure whether this is the correct forum for posting the question or not but any help will be appreciated. 

Bugbase supports BIOM file in JSON format and with both counts and taxonomy. When I am trying to output biom file using package biomformat with both counts and taxonomy it is ouputting a file but not recognized by Bugbase. The code I am using for outputting the file is :

```
biom16S <- make_biom(count_tab16s, observation_metadata = tax_gg )
biom_file <- biom16S
outfile = tempfile()
write_biom(biom_file, outfile)
```

where count_tab16S is the count file with ASV IDS in rows and sample names in columns and tax_gg is the file with ASV IDS in rows and their hierarchy (from kingdom to Species) in columns.

May I get some help on where I am going wrong or what is the correct way to merge counts and taxonomic information from dada2 to a biom file?

Thanks,

Sandipan

**Comment by benjjneb** [comment]
Apologies but I am not sure. Maybe ask this at the `biomformat` github page? @joey711 is that where such question should go?

**Comment by sandipansamaddar** [comment]
Thanks. I will post it on `biomformat` page.

Best,

Sandipan

**Comment by sandipansamaddar** [comment]
Hello @benjjneb sorry to post an issue here again. As I was unable to use the `biomformat` I am trying to generate the file in a different way so that it works with `bugbase`. I am trying to use the OTU picking tool `NINJA` to create a biom file. But for input it needs a fasta file in a format as shown below :
`>100217.1246514_0 A222Y121112:1:1101:10003:15638/1 orig_bc=AAAAAAAAAAAA new_bc=AAAAAAAAAAAA bc_diffs=0` where 100217.1246514 is a sample, and 0 is the index corresponding to the first read from the sequencing run.

I am wondering can we get an output from dada2 in similar format? The output which I currently have from dada2 looks like 
![image](https://user-images.githubusercontent.com/30172935/86486204-8b73c280-bd0f-11ea-903b-4a9f8638747e.png)

Any help will be really appreciated.

Thank you.

**Comment by benjjneb** [comment]
Trying to put this through an intermediate like NINJA to do this is almost certainly more complicated than figuring out what is going in with your biomformat code. NINJA isn't even a program that's designed to convert between formats.

In your original post you said:

> But while outputting the biom file I am facing some problems...When I am trying to output biom file using package biomformat with both counts and taxonomy it is ouputting a file but not recognized by Bugbase.

Have you checked whether the file is a valid .biom file using another tool, for example the "official" tool provided here? http://biom-format.org/

Also, the biom file type has a, to put it kindly, "complex" history in which it has shifted between completely different formats (e.g. JSON to HDF5) in an opaque way that often cause errors like this. How certain are you that BugBase wants the JSON biom format? Is there a specific range of biom format standards that BugBase uses?

**Comment by sandipansamaddar** [comment]
Hi sorry to make it complicated.

I was using NINJA not to convert between formats but to generate a biom file from the fasta file. But as you said it makes things complicated.

The Bugbase documentation says the OTU table should be in BIOM format (version 1.0, JSON) and picked against a G

**Comment by sandipansamaddar** [comment]
Hi,
Yes with `NINJA` it gets more complicated.

`Bugbase` documentation says it needs a OTU table in BIOM format (version 1.0, JSON) picked against a GG database. (https://bugbase.cs.umn.edu/documentation.html)

I used GG database to classify sequences and created a biom file which looks fine to me but its not working and it says not a correct format. 

The commands used to generate the biom file were :

In R using `biomformat` package:
```
biom16S <- make_biom(count_tab16s )
biom_file <- biom16S
outfile = tempfile()
write_biom(biom_file, outfile)
```
where count_tab16S is the count file with ASV IDS in rows and sample names in columns.

After getting the output I added the metadata in terminal using the command:

`biom add-metadata -i my.biom -o table-with-taxonomy.biom --observation-metadata-fp taxonomyfile.tsv --sc-separated Taxonomy`

where taxonomyfile.tsv is the file with GG taxonomy information.

After getting the output from the above step I converted the file to JSON:

```
biom convert --table-type="OTU table" -i table-with-taxonomy.biom -o your_OTU_table.txt --to-tsv --header-key taxonomy
biom convert -i your_OTU_table.txt -o OTU_table.biom --table-type="OTU table" --to-json --process-obs-metadata taxonomy
```

I used the output in `Bugbase` but it didnt work. 

But when I validated the file using:
`biom validate-table -i OTU_table.biom` 

it says its a correctly formatted file.

On the other hand, I also used `Mothur` to process my sequences and created biom file using `make.biom` command and converted file to json the same way I did above but it worked with `Bugbase`.

So I am afraid whats going wrong.

I will also post in `biom-format `and `biomformat` page to see if I can get some help.

I will also be happy so share any files if needed.

Thanks,

Sandipan

**Comment by sandipansamaddar** [comment]
Hi,
I just posted the issue on `Bugbase` and may be I figured out what is going wrong but not sure how to solve it.

So when I am using `Mothur` and creating a biom file, the OTU identifiers it outputs are the exact Greengenes identifiers which are recognized by Bugbase. But when I am using `biomformat` with `dada2` output and creating the file the identifiers are labelled as ASV_1, ASV_2... in the output file which is not recognized by `Bugbase`. 

I am wondering is there a way where I can replace the identifiers with exact Greengenes OTU IDs instead of ASV IDs? 

Is it something I can do while assigning taxonomy by providing a mapping file? 

Any help will be appreciated and I can share the files if needed.

Thanks,

Sandipan

**Comment by benjjneb** [comment]
OK, I'm getting a better understanding of the issue now.
The biom format was fine before, but it didn't have the specific GreenGenes identifier for each ASV (or OTU) that Bugbase requires.

Unfortunately perhaps, there is not an out-of-the-box way to assign GG IDs to ASVs in the dada2 R package. (technically one could do it, but it would require reformatting the GreenGenes reference fasta, and is less than trivial)

What I would add though, is that if interfacing with Bugbase is the main goal here, DADA2 and ASVs are probably not even the right tool. What I assume Bugbase was designed and validated on is closed-reference OTUs assigned against the GG database, as was commonly used in QIIME1. Bugbase therefore isn't operating at the ASV level anyway. Working with DADA2 and ASVs might still be very useful for other types of analyses, but for Bugbase, you may be better off processing the data as expected via closed-reference assignment against GG.
