### ISSUE TITLE
Memory allocation failed

### ISSUE THREAD

**Issue by reemelkabbout** [benjjneb/dada2#1057]
Hi Mr. Ben,
I just want to know if there is any solution for the "memory allocation failed" error during AssignTaxonomy step?

**Command**: taxa <- assignTaxonomy(seqtab.nochim, "mypath/silva_nr_v128_train_set.fa.gz", multithread= FALSE)  #Note that I also tried it with multithread = TRUE
**What I got :**
Error in C_assign_taxonomy(seqs, rc(seqs), refs, ref.to.genus, tax.mat.int,  : 
  Memory allocation failed.

I do not have another PC currently, is there anything I can do?

**Comment by benjjneb** [comment]
You can try using a smaller training file, like the RDP trainset.
Otherwise I think the solution is just having more memory available.

**Comment by reemelkabbout** [comment]
Thank you for your quick response.
But I want to know if is it about having more memory on my PC or more RAM? Actually I don't know if they are the same, I'm new to programming and PC stuff.

**Comment by benjjneb** [comment]
Memory = RAM.
Storage = disk space.
Two different things.

You need to be able to load what the computer is actively working on into its memory/RAM, and it seems like your computer doesn't have enough to load in the Silva db.

**Comment by reemelkabbout** [comment]
Thank you so much!
Just one more question, I tried to search for RDP db download but I couldn't find a way to download it. Do you have any idea how could I it?

**Comment by benjjneb** [comment]
The DADA2 formatted files are here:  https://benjjneb.github.io/dada2/training.html
