### ISSUE TITLE
Dada2 Fasta Annotation

### ISSUE THREAD

**Issue by zach1905** [benjjneb/dada2#1058]
Dear Benjamin,

I am looking to taxonomically annotate a fasta sequence file and receive a fasta output with annotation. The original **pacbio_otu.fasta** has the id lines:

>consensus=Uniq2;size=24;seqs=2
GTTACCTTGTTACGACTTCACCCCAATCATCTATCCCACCTTAGGCGGCTGGCTCCAAAAGGTTACCTCACCGACTTCGG

To annotate **pacbio_otu.fasta**, the taxonomy database **rdp_16s_v16_sp.fa** has the id lines:

>EF599163_S000871589;tax=d:Bacteria,p:"Proteobacteria",c:Gammaproteobacteria,o:"Vibrionales",f:Vibrionaceae
GTTTGATCCTGGCTCAGATTGAACGCTGGCGGCAGGCCTAACACATGCAAGTCGAGCGGAAACGACACTAACAATCCTTC

If possible, I would like to have taxonomy annotation (from **rdp_16s_v16_sp.fa**) on my **pacbio_otu.fasta** file to build my own taxonomy database in fasta format with the id lines like:

>consensus=Uniq2;size=24;seqs=2;tax=d:Bacteria,p:"Proteobacteria",c:Gammaproteobacteria,o:"Vibrionales",f:Vibrionaceae
GTTACCTTGTTACGACTTCACCCCAATCATCTATCCCACCTTAGGCGGCTGGCTCCAAAAGGTTACCTCACCGACTTCGG

Eventually, with this taxonomy database in fasta format, I would like to run usearch 'sintax' with other fasta data against it. 

Is there a way to produce my own taxonomy database in fasta format using Dada2? Otherwise, do you have any advice on what I could do for my particular case? 

Many thanks,
Zach

[pacbio_otu_rdp_taxonomy_fasta.zip](https://github.com/benjjneb/dada2/files/4859116/pacbio_otu_rdp_taxonomy_fasta.zip)

**Comment by benjjneb** [comment]
One possibility is the `uniquesToFasta` function in dada2. See `?uniquesToFasta` for a description, but it will output to a fasta the unique sequences in a given dada-compatiable object, and accepts a custom vector of id lines corresponding to the sequences.

Even more flexible would be using the `writeFasta` function in the ShortRead package (which is what `uniquesToFasta` is wrapping).
