### ISSUE TITLE
error while constructing a simple sample data.frame from the information encoded in the filenames

### ISSUE THREAD

**Issue by tlp46** [benjjneb/dada2#1059]
##packages I installed
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("phyloseq")
library(phyloseq); packageVersion("phyloseq")

install.packages("Biostrings")
library(Biostrings); packageVersion("Biostrings")

install.packages("ggplot2")
library(ggplot2); packageVersion("ggplot2")

##the errors I keep getting

> theme_set(theme_bw())
> samples.out <- rownames(seqtab.nochim)
> subject <- sapply(strsplit(samples.out, "D"), `[`, 1)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'X' in selecting a method for function 'sapply': non-character argument
> gender <- substr(subject,1,1)
Error in as.vector(x, "character") : 
  cannot coerce type 'closure' to vector of type 'character'
> subject <- substr(subject,2,999)
Error in as.vector(x, "character") : 
  cannot coerce type 'closure' to vector of type 'character'
> day <- as.integer(sapply(strsplit(samples.out, "D"), `[`, 2))
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'X' in selecting a method for function 'sapply': non-character argument
> samdf <- data.frame(Subject=subject, Gender=gender, Day=day)
Error in data.frame(Subject = subject, Gender = gender, Day = day) : 
  object 'gender' not found
> samdf$When <- "Early"
Error in samdf$When <- "Early" : object 'samdf' not found
> samdf$When[samdf$Day>100] <- "Late"
Error in samdf$When[samdf$Day > 100] <- "Late" : object 'samdf' not found
> rownames(samdf) <- samples.out
Error in rownames(samdf) <- samples.out : object 'samdf' not found

**Comment by benjjneb** [comment]
The string parsing is failing right off the bat. Can you show an example of the rownames? 
`head(rownames(seqtab.nochim))`

**Comment by tlp46** [comment]
I'm not really sure if this might help answer the question, but I've been working through the DADA2 Pipeline Tutorial (1.16). 

This is what I've done before that code:

dadaFs[[1]]
## dada-class: object describing DADA2 denoising results
## 128 sequence variants were inferred from 1979 input unique sequences.
## Key parameters: OMEGA_A = 1e-40, OMEGA_C = 1e-40, BAND_SIZE = 16
mergers <- mergePairs(dadaFs, filtFs, dadaRs, filtRs, verbose=TRUE)
# Inspect the merger data.frame from the first sample
head(mergers[[1]])
seqtab <- makeSequenceTable(mergers)
dim(seqtab)
# Inspect distribution of sequence lengths
table(nchar(getSequences(seqtab)))
seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
dim(seqtab.nochim)
sum(seqtab.nochim)/sum(seqtab)
getN <- function(x) sum(getUniques(x))
track <- cbind(out, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers, getN), rowSums(seqtab.nochim))
# If processing a single sample, remove the sapply calls: e.g. replace sapply(dadaFs, getN) with getN(dadaFs)
colnames(track) <- c("input", "filtered", "denoisedF", "denoisedR", "merged", "nonchim")
rownames(track) <- sample.names
head(track)
taxa <- assignTaxonomy(seqtab.nochim, "/Users/tifanipanek/Downloads/silva_nr_v138_train_set.fa.gz", multithread=TRUE)
taxa <- addSpecies(taxa, "/Users/tifanipanek/Downloads/silva_species_assignment_v138.fa.gz")
taxa.print <- taxa # Removing sequence rownames for display only
rownames(taxa.print) <- NULL
head(taxa.print)
head(rownames(seqtab.nochim))


for head(taxa.print) I got:
     Kingdom    Phylum           Class                 Order                Family               
[1,] "Bacteria" "Fusobacteriota" "Fusobacteriia"       "Fusobacteriales"    "Fusobacteriaceae"   
[2,] "Bacteria" "Fusobacteriota" "Fusobacteriia"       "Fusobacteriales"    "Fusobacteriaceae"   
[3,] "Bacteria" "Proteobacteria" "Gammaproteobacteria" "Vibrionales"        "Vibrionaceae"       
[4,] "Bacteria" "Proteobacteria" "Gammaproteobacteria" "Aeromonadales"      "Aeromonadaceae"     
[5,] "Bacteria" "Bacteroidota"   "Bacteroidia"         "Flavobacteriales"   "Flavobacteriaceae"  
[6,] "Bacteria" "Firmicutes"     "Bacilli"             "Erysipelotrichales" "Erysipelotrichaceae"
     Genus            Species  
[1,] "Cetobacterium"  "somerae"
[2,] "Cetobacterium"  "somerae"
[3,] "Vibrio"         NA       
[4,] "Aeromonas"      NA       
[5,] "Flavobacterium" NA       
[6,] "ZOR0006"        NA

Now I'm trying to hand off to Phyloseq and put in the code you asked:
I got this:
> head(rownames(seqtab.nochim))
NULL

As well as the errors I wrote about in my original question. I'm using a large set of demultiplexed FastQ files that I put through the dada2 pipeline to filter. What may the problem as I'm trying to handoff to Phyloseq? I appreciate the help!!

**Comment by benjjneb** [comment]
> head(rownames(seqtab.nochim))
> NULL

There are no sample names on your `seqtab.nochin` ASV table (the sample names should be the `rownames` of that matrix).

If you are following the tutorial workflow, you've somehow lost the sample names at some point. I'd suggest checking for their presence at various steps, perhaps starting with `head(names(dadaFs))`: Are there sample names (or at least the filenames) there? How about `head(names(mergers))`?

Did you skip the sample naming part of the tutorial workflow?

**Comment by benjjneb** [comment]
Feel free to reopen as necessary
