### ISSUE TITLE
Incomplete primer removal - 16S MiSeq data

### ISSUE THREAD

**Issue by Claudioatb** [benjjneb/dada2#1060]
Hello, 

I am trying to remover primers in my Illumina (MiSeq) 16S sequences, but somehow there's several primers sneaking through and I'm not finding the issue. I'm still new to bioinformatics and I'm probably missing something that may be obvious to more advanced users. Anyway, thanks in advance for the help you can provide :)

**Primers used: 799F2 and 1193R**
FWD <- "AACMGGATTAGATACCCKG"
REV <- "ACGTCATCCCCACCTTCC"

**#The output of the initial primer presence and orientation is the following:**

                                  Forward     Complement      Reverse         RevComp
FWD.ForwardReads    116240                       0                 2                       0
FWD.ReverseReads          541                    537             541                 1001
REV.ForwardReads               0                        2                0                    496
REV.ReverseReads     110334                     540             539                   534

**#Now, removing primers with cutadapt with the following loop:**

for i in *_R1_001.fastq.gz
do
  SAMPLE=$(echo ${i} | sed "s/_R1_\001\.fastq\.gz//") 
  echo ${SAMPLE}_R1_001.fastq.gz ${SAMPLE}_R2_001.fastq.gz
cutadapt -b file:primers.fasta -B file:primers.fasta -n 2 -m 50 -o ${SAMPLE}_R1_001.CUT.fastq.gz -p ${SAMPLE}_R2_001.CUT.fastq.gz ${SAMPLE}_R1_001.fastq.gz ${SAMPLE}_R2_001.fastq.gz
done

**#Checking for primers once again to confirm that cutadapt did remove the primers:**

                                   Forward       Complement      Reverse     RevComp
FWD.ForwardReads             40                         0                 2                  0
FWD.ReverseReads            540                     536             540              538
REV.ForwardReads                0                         2                 0                   1
REV.ReverseReads             538                     539             538               533

#- I would still prefer to use cutadapt instead of the common "trimLeft and truncLen" parameters. I find it weird that cutadapt is finding the FWD.ReverseReads and the REV.ReverseReads with roughly the same hits in all orientations. I would expect to (mainly) find FWD.ForwardReads in the Forward orientation; FWD.ReverseReads in the RevComp orientation (and the same for the reverse sequences). 

Any advise on how to proceed with this?

**Comment by benjjneb** [comment]
I would just ignore it. You've removed the primers successfully from the locations they should be at. The other primer "hits" that you are seeing are often hits to low quality or low complexity bits of some reads that will mostly if not all be removed in the denoising process anyway.

**Comment by Claudioatb** [comment]
Hi Benjamin, 

Thank you for your quick reply. I will proceed as advised :)

Cheers,
Cláudio
