### ISSUE TITLE
How to know if there are primer sequences in our sequence?

### ISSUE THREAD

**Issue by dikiprawisuda** [benjjneb/dada2#1062]
Hi,
I want to validate my bioinformatics protocol in analyzing 16S rRNA V3-V4 sequence. I was using the following mock sequences, [https://github.com/andreiprodan/mock-sequences] from [https://doi.org/10.1371/journal.pone.0227434], I was trying to start with mock_1_R1.fastq.

After manually seeing the sequence through Notepad++, I saw that there are similar sequence at the first four bases. The sequences also has some pattern of repeating some bases, not only the first four. Is this the original hypervariable characteristic of rRNA? Or is it primer or adapter or linker?

I also manually search the sequence of 515f 806r primer sequence by Ctrl+F in notepad++ but I see no enough similarity.

**Comment by benjjneb** [comment]
I'd do kind of what you are doing, open the raw sequences up in a text editor, and then scan for the expected primer sequences. But, if this is V3V4, then they aren't using the 515F-806R primer set (that is V4), so you are perhaps looking for the wrong thing.

I'd clarify what the primer sequences that were used to generate your data. Then look for the forward primer sequences at the start of the R1 reads. If this is the common "Illumina" V3V4 sequencing protocol, the primers will be there and thus will need to be removed later.

**Comment by dikiprawisuda** [comment]
Hi Ben, thank you for your response.

I see, I did not know that 515F-806R primer set is used for the V4 region, thank you for letting me know.
Regarding the primer sequence, actually I do not have a clue about the primer sequence. I wonder though if there is a way to get a probable candidate of the primer sequence just by having the sequencing results? Can we reverse-engineer the process given the optimal requirements of the primer, like GC content, common length, and so on?
I was inspired by the cutadapt webpage, they have these wildcard option.

Thank you.

**Comment by benjjneb** [comment]
> Regarding the primer sequence, actually I do not have a clue about the primer sequence.

The best way is to know what the primer sequences were. Whoever did this sequencing had to know that, it's a central component of any amplicon based sequencing. Or if it is data from a publication, it should be described in the methods.

> I wonder though if there is a way to get a probable candidate of the primer sequence just by having the sequencing results? 

Probably your best best is to compare the start of your sequences against known potential primers for the region being sequenced.

> Can we reverse-engineer the process given the optimal requirements of the primer, like GC content, common length, and so on?

You can try to do that, but it is harder with amplicon data then with other types of data, because the sequence after the primer sequence is also often highly conserved biologically.

**Comment by dikiprawisuda** [comment]
I see, thank you. I will ask the author because it seems to be missing in the methods.
