### ISSUE TITLE
Mock Community in DADA2 fungal ITS tutorial

### ISSUE THREAD

**Issue by sarahLy9** [benjjneb/dada2#1064]
Hello, I have a question about the data used for the fungal ITS DADA2 tutorial (https://benjjneb.github.io/dada2/ITS_workflow.html)

I understand you received the mock community from Bakker et al 2018. In that paper, he describes a few versions of the mock community, Staggered A, Staggered B, and Even. Which community did you use in the tutorial? 

Also, am I correct in understanding you used ITS1 primers (ITS1F/ITS2) for this dataset?

I am troubleshooting my classification step, I used the staggered version B in my dataset but I am hoping to narrow down my issue by analyzing your tutorial dataset in parallel but I want to make sure I understand how the data was generated.

Thank you,
 Sarah

**Comment by benjjneb** [comment]
@nagasridhar Do you remember which of the Bakker mocks were used in the ITS tutorial?

**Comment by nagasridhar** [comment]
Hi Ben and Sarah,

For the ITS tutorial, we used the entire set of Amplicon Sequencing Library
#1. This library does consist of Even, Staggered A and Staggered B.

The primers are BITS primers for forward reads and B58S3 for reverse reads.

The library used in the tutorial is described in detail in Section 2.3 in
the Bakker et al 2018 paper.

**Comment by sarahLy9** [comment]
Thank you both for you quick reply.

Do you have a metadata file available to tell me which sample corresponds to which mixture in the test data? I do not see any info available in the link where I downloaded the file (https://www.ebi.ac.uk/ena/data/view/PRJNA377530). 

My apologies if I am missing something, I am new to NGS analysis. I included staggered mixture B in my experiment but did not identify any of the major taxa that are supposed to be in the mixture so I was hoping it was a classification issue. Being able to test my classifier on your data would help me narrow down my issue.

**Comment by nagasridhar** [comment]
Hi Sarah,

The details linking the Run file/fastq file to the community is in the link
below:

https://www.ncbi.nlm.nih.gov/Traces/study/?query_key=13&WebEnv=NCID_1_21797049_130.14.18.48_5555_1594093597_1137155363_0MetA0_S_HStore&o=acc_s%3Aa

**Comment by sarahLy9** [comment]
Sorry, that link does not work, it says page not found.

**Comment by nagasridhar** [comment]
I think NCBI creates a unique link for each individual/session.

The easiest way to do this is go to:

https://www.ncbi.nlm.nih.gov/Traces/study/?

Enter the NCBI BioProject Number: PRJNA377530.

That should give you access to the metadata.
