### ISSUE TITLE
Error in validObject(.Object) 

### ISSUE THREAD

**Issue by HP900** [benjjneb/dada2#1065]
Hi, 
I test run the following code from the "Introduction to dada2",

filterAndTrim(fwd=fnF1, filt=filtF1, rev=fnR1, filt.rev=filtR1,
                  trimLeft=10, truncLen=c(240, 200), 
                  maxN=0, maxEE=2,
                  compress=TRUE, verbose=TRUE)

And got the Error message:
Error in validObject(.Object) : 
  invalid class “ScalarCharacter” object: superclass "characterORconnection" not defined in the environment of the object's class

R version 4.0.0
Bioconductor version 3.12
DADA2 version 1.17.0
Rcpp version 1.0.4.6

Any suggestion is appreciated!
Thanks!

**Comment by benjjneb** [comment]
I would try inspecting the `class(...)` of the objects you are passing to `filterAndTrim`. It seems like one of them is something unexpected.
