### ISSUE TITLE
DADA in Qiime2 vs R

### ISSUE THREAD

**Issue by dikiprawisuda** [benjjneb/dada2#1066]
Hi,
Is there a difference between analyzing data in Qiime2(DADA deonising) versus R?
I tried both method with similar fastaq input (for Qiime2 I gzipped and renamed them accordingly), and same parameter. The only parameter that I know I was changing are trim left; trunc len for Qiime2 and truncLen; trimLeft for R. Other adjustment like removing chimeras were left default.

From my data, R produced 35 variants (from seqtab.nochim) while Qiime2-DADA 46 features (from table.qzv). The dataset input was determine to have only 22 variants of ASV. So, DADA in R seems more accurate, but I am not sure how to appropriately conclude these. Is R better then?

Thank you.

**Comment by benjjneb** [comment]
QIIME2 runs the R package code. The Q2 plugin tends to use a bit older version, and is less flexible with parameters, but its the same code.

If you're already comfortable in R, I'd suggest using that version just for the added flexibility.

**Comment by dikiprawisuda** [comment]
Thank you for your response.
Do you have some insights perhaps as to why the results I was getting are different? They should be the same then, right?
Pardon me asking, I am new to this.

**Comment by benjjneb** [comment]
You are probably using different versions of the package (still 1.10 for the plugin, whereas we are on release 1.16 in R already). In addition, there may be slight differences in parameters between the plugin and the R code you are calling.

**Comment by dikiprawisuda** [comment]
Thanks you very much.
