### ISSUE TITLE
Is trimLeft in filterAndTrim working perfectly?

### ISSUE THREAD

**Issue by tduarte90** [benjjneb/dada2#1067]
Hi,

I've just tried 

trimLeft = c(17, 20)
filterAndTrim(fwd, filt, rev, filt.rev, trimLeft, compress = TRUE)

and my reads where trimmed in the end of the read (sometimes where trimmed all values different than 17 and 20, other times were not trimmed). Then I tried trimRight and gave me the expected trimming in the end of read. After using trimLeft I can still see my primers in the beginning of the read.

I couldn't see anyone questioning if the option "trimLeft" had any issue. Has anyone else seen this?
Thanks

**Comment by benjjneb** [comment]
Never heard of any issues with `trimLeft`.

I think your issue might be that you are not passing the arguments to `filterAndTrim` correctly. You need to have: `filterAndTrim(..., trimLeft=c(17,20), ...)` or `filterAndTrim(..., trimLeft=trimLeft, ...)`, i.e. name the parameter you are passing in. As is, I think `c(17,20)` is being assigned to the first unfilled positional argument, which would be `truncQ`, which would explain the ragged truncation behavior you are seeing.

**Comment by tduarte90** [comment]
Thank you very much. It helped. 
There is no issue. I had written the command wrong. 
I'm a newbie in this space. 
Cheers.
