### ISSUE TITLE
assignTaxonomy only returns Kingdom info

### ISSUE THREAD

**Issue by kbeals2** [benjjneb/dada2#1069]
Hi there, 

I used the RDP training set (rdp_train_set_16.fa.gz, rdp_species_assignment_16.fa.gz) to assign taxonomy to my 16S sequences and only got Kingdom information. Phylum through species for each sequence is reported as 'NA.' I've never had this happen before and I'm not sure what could be causing it. Here is my code for assigning taxonomy:

taxa <- assignTaxonomy(seq_table_nochim, "rdp_train_set_16.fa.gz", multithread = TRUE)  
taxa <- addSpecies(taxa, "rdp_species_assignment_16.fa.gz")

**Comment by benjjneb** [comment]
Your sequences might be in the reverse-complement orientation. What does the output of this look like?

```
taxa <- assignTaxonomy(seq_table_nochim, "rdp_train_set_16.fa.gz", multithread = TRUE, **tryRC=TRUE**)
```

**Comment by kbeals2** [comment]
That returned the same thing, all NA's :(

**Comment by benjjneb** [comment]
Are they junk sequences? Or off-target amplification?

Try just BLAST-ing the top 10 sequences and seeing what you get in return: https://blast.ncbi.nlm.nih.gov/Blast.cgi?PROGRAM=blastn&PAGE_TYPE=BlastSearch&LINK_LOC=blasthome

`dada2:::pfasta(getSequence(taxa)[1:10])` will print them in fasta format that you can copy/paste into the BLAST query box.

**Comment by kbeals2** [comment]
Ok...these are apparently my ITS sequences because BLAST returns them as fungi. So sorry! One of my collaborators gave me the wrong sequence data (face palm).
