### ISSUE TITLE
How to save the phyloseq object generated in dada2' tutorial for later use

### ISSUE THREAD

**Issue by montoyah** [benjjneb/dada2#107]
Hi,

How can I save "seqtab.nochim" and "taxa" objects created during the tutorial, to used them later with:

`phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE), 
tax_table(taxa))`

Currently, if I want to keep working on my data, I've to run all the commands from the dada2 tutorial because I haven't been able to store dada2's final output for later use. If I save the "seqtab.nochim" and "taxa" as .csv (with and without psmelt), then "read.csv(...)" to run the above code, I get the error: 

> Error
 in validObject(.Object) : invalid class “otu_table” object: 
 Non-numeric matrix provided as OTU table.
Abundance is expected to be numeric.

As a disclaim, I get this would be more a question related to phyloseq than to dada2, but haven't found info in phyloseq to solve my problem, or perhaps I haven't comprehended the phyloseq tutorial.

Thanks in advance for any insights.

**Comment by benjjneb** [comment]
R has general facilities for saving and loading objects to disk. To save your session and load it back in later.

```{r}
save.image("path/to/my_session.rdata")
# Close R, Re-open R
load("path/to/my_session.rdata")
```

You can also save and reload individual objects:
```{r}
saveRDS(seqtab, "path/to/seqtab.rds")
# Close and re-open R
seqtab <- readRDS("path/to/seqtab.rds")
```

**Comment by montoyah** [comment]
Fantastic! Thanks, Ben.

**Comment by satopan** [comment]
Fantastic! Thanks, Ben.
