### ISSUE TITLE
Advice regarding implementing DADA2-R on research cluster

### ISSUE THREAD

**Issue by jonasfrankelbricker** [benjjneb/dada2#1070]
Hello all, I have a general question regarding setting up/running DADA2-R on a research computing cluster.

My university is currently in the very early stages of setting up a 16S bioinformatics pipeline on our newly assembled research computing cluster.  I have long been a proponent of utilizing DADA2 for 16S data due to my familiarity with working in R and the high-level support from the community.  However, our computing folks are having a variety of issues setting up R/running DADA2 efficiently (many steps have not been running or take substantially longer than running the code on our personal laptops (learnErrors, filterandtrim, derep/merging step etc.)).  Are there any publicly available resources/advice on how to best implement DADA2 on a research cluster?  I'm sure that the inexperience of our computing team is playing a large role in our struggles, however, many of them are starting to push for us using QIIME2 in python instead (they say it is easier to work with).  I am not a computer scientist, and am solely serving as a liaison and a loyal proponent of DADA2-R.  Thanks for any tips/advice/or direction to resources on how to address these difficulties.

-Jonas

**Comment by benjjneb** [comment]
The one resource we developed ourselves for that is the "Big Data" workflow for DADA2: https://benjjneb.github.io/dada2/bigdata.html. Although that is arguably a bit out of date at this point, as the package has continued to improve.

There certainly are a number of people who have implemented DADA2 on research clusters, but I'm not sure to what extend they have made their experiences publicly available. One recent preprint I saw described a snakemake workflow for DADA2, that could be somewhat helpful: https://www.biorxiv.org/content/10.1101/2020.05.17.095679v1

More generally, the DADA2 workflow is broken into discrete steps: Filtering, Learning error rates, Denoising, Chimera removal, Taxonomic assignment. It can be very useful to profile each step individually, especially if there is unexpected behavior like slower operation on a cluster. That can help diagnose where a slowdown is happening and suggest ways to fix it.

A basic thing to remember is that multithreading is off by defult in all DADA2 commands, it needs to be turned on with the `multithread=TRUE` of `multithread=12` (e.g.) flags in the relevant function calls.
