### ISSUE TITLE
Is there a way to make data2 keep the sequence header for a fasta sequence?

### ISSUE THREAD

**Issue by Lamm-a** [benjjneb/dada2#1071]
I am using dada2 to get the taxa for a large multifasta of ~ 40,000 16s rRNA amplicon sequences. I later wish to make a plot of sequence similarity so would like to somehow relate the sequences in the taxa table generated by dada2 back to the sequence header in the multifasta file. It this possible?

**Comment by benjjneb** [comment]
Sure, you can just read in the fasta file complete with IDs (stored as the `names` of the vector of sequences).

```{r}
fn <- "path/to/my.fasta"
sq <- getSequences(fn)
tax <- assignTaxonomy(sq)
id <- names(sq)
tax[1,]; id[[1]]
```

The last line will give the taxonomy and the header of the first sequence in the fasta file.
