### ISSUE TITLE
0 merging

### ISSUE THREAD

**Issue by Tr1sh** [benjjneb/dada2#1075]
0 paired-reads (in 0 unique pairings) successfully merged out of 541 (in 3 pairings) input.
0 paired-reads (in 0 unique pairings) successfully merged out of 100 (in 1 pairings) input.
0 paired-reads (in 0 unique pairings) successfully merged out of 234 (in 3 pairings) input.
0 paired-reads (in 0 unique pairings) successfully merged out of 318 (in 3 pairings) input.
0 paired-reads (in 0 unique pairings) successfully merged out of 154 (in 1 pairings) input.
0 paired-reads (in 0 unique pairings) successfully merged out of 70 (in 1 pairings) input.
0 paired-reads (in 0 unique pairings) successfully merged out of 221 (in 1 pairings) input.
i have not trimmed but my reads are failing to merge.

**Comment by benjjneb** [comment]
In order to get any kind of useful help you need to provide more information so we can have any idea what is going on.

What amplicon are you seqeuencing. What is your sequencing technology and read lengths? Are you running the tutorial workflow? What prior steps did you run?
