### ISSUE TITLE
Should I separate two datasets from different sequencing run?

### ISSUE THREAD

**Issue by dikiprawisuda** [benjjneb/dada2#1079]
Hi,
I have two datasets from two different sequencing runs. They are from a similar group of animal model. I wonder if this will affect the result somehow.
Those two datasets have different amount of reads.

Thank you.

**Comment by benjjneb** [comment]
For DADA2, you should process each run independently. Then, provided that they come from the same amplicon and you used the same `trimLeft` values, you can merge them together afterwards using `mergeSequenceTables`.

In downstream analysis you should consider possible batch effects of course, but that is beyond the DADA2 part.

**Comment by dikiprawisuda** [comment]
Thank you.
So should I `mergeSequenceTables` before "Remove chimeras" step?

**Comment by benjjneb** [comment]
Yes.

**Comment by dikiprawisuda** [comment]
Thanks

**Comment by dikiprawisuda** [comment]
Hi, I wanted to ask again. 
What about two different group of treatment? Should I run DADA pipeline independently between group? E.g. considering the pooling argument on dada()

**Comment by benjjneb** [comment]
> What about two different group of treatment? Should I run DADA pipeline independently between group? E.g. considering the pooling argument on dada()

No.

**Comment by dikiprawisuda** [comment]
Thank you.
