### ISSUE TITLE
assignTaxonomy is choking on the Ns inserted with justConcatenate=TRUE in mergePairs.Rd

### ISSUE THREAD

**Issue by jennomics** [benjjneb/dada2#108]
Hello!
After running mergePairs.Rd with the justConcatenate=TRUE option, I get the following error when running assignTaxonomy: 

Error: Sequences to be classifed must be ACGT only.

I would love to be able to use both ends of these reads which do not overlap. My assumption would be that the string of Ns would be a place where a gap could be opened up during an alignment to a reference sequence (which I'm assuming is something that happens during assignTaxonomy). Is there a fix or workaround for this, or do I need to assign taxonomy to the forward and reverse reads independently? 

Thank you!
Jenna

**Comment by benjjneb** [comment]
Yeah, you should be able to do this. Sounds like over-strict type checking.

Marking as bug, will investigate.

**Comment by benjjneb** [comment]
Fixed in 21a615ca240d58b5aae0e69f54af697f746f35f0

**Comment by jennomics** [comment]
Thanks for fixing this! I just want to confirm that the Ns will be ignored for both assignTaxonomy and assignSpecies?

**Comment by benjjneb** [comment]
Unfortunately no, it won't yet work for `assignSpecies`, as `assignSpecies` (exact matching) uses a different underlying method than `assignTaxonomy` (kmer overlap).

Improvements to `assignSpecies` are on the to-do list (it should be a lot faster, for one). I will add handling non-overlapping amplicons to that list, but it won't happen immediately.

You can run `assignSpecies` on the F and R parts of the amplicon separately and synthesize the results, but it will take a bit of R hacking on your part.
