### ISSUE TITLE
trimLeft=15 recommendation for denoising Ion Torrent data

### ISSUE THREAD

**Issue by MarwaElnaiem** [benjjneb/dada2#1080]
Dear all, 

I have ITS1 single-end demultiplexed data generated by Ion Torrent sequencing and want to use dada2. 
I removed the primers using cutadapt and want to know if I should use the recommended parameter for pyrosequencing data filterAndTrim(..., trimLeft=15) with my data or not. 

Another question: does the dereplication step have specific value with ITS data or not?? Could I overcome this step and use dada() with my filtered data?? This step is present in the ITS workflow tutorial and not in the 16S tutorial.

Regards, 
Marwa

**Comment by benjjneb** [comment]
You don't have to use `trimLeft=15`. That seemed to work better on the one IT dataset we tested on, but I have very little experience with Ion Torrent data so don't take it as gospel.

> Another question: does the dereplication step have specific value with ITS data or not?? Could I overcome this step and use dada() with my filtered data?? This step is present in the ITS workflow tutorial and not in the 16S tutorial.

The data is dereplicated the same in the ITS and 16S tutorials. Dereplication just happens "behind the scenes" in the updated 16S tutorial.

**Comment by MarwaElnaiem** [comment]
Thanks very much @benjjneb  for your reply. 

Marwa
