### ISSUE TITLE
Overlap in Sequences

### ISSUE THREAD

**Issue by gmkuba** [benjjneb/dada2#1082]
Hello!
I am having trouble trying to identify my minOverlap for my sequences. Our paired-end reads covering the V3-V4 regions using 341F and 785R primers should yield a 444 bp (785 - 341) amplicon. This is where I'm stuck - what do I subtract that from in order to identify the sequence overlap? 

Any help would be much appreciated!
Thank you in advance!

**Comment by benjjneb** [comment]
I'm not 100% sure I understand the question but...

If you have, e.g. 2x250 reads. That is 500 nucletoides of total sequence. If the targeted amplicion is e.g. 444bp, then your paired reads will overlap by 500-444 = 56 nts.

That overlap will change if you truncate your reads, or if they are different lengths etc.
