### ISSUE TITLE
Is it a good idea to combine reference database?

### ISSUE THREAD

**Issue by dikiprawisuda** [benjjneb/dada2#1085]
Hi DADA2 developers,

I was just wondering, is it possible to decrease the NA number in taxa as a result of assignTaxonomy() by refering it to the new combined reference database?

Thank you

**Comment by benjjneb** [comment]
No it is not a good idea to just combine reference dbs. They use different taxonomic definitions and systems, and it's therefore not appropriate to simply paste them together.

There are principled ways to combined enviornment-specific dbs with a general purpose database, see for example these two papers: 

[TaxAss: Leveraging a Custom Freshwater Database Achieves Fine-Scale Taxonomic Resolution](https://msphere.asm.org/content/3/5/e00327-18.short)
[Generation of comprehensive ecosystems-specific reference databases with species-level resolution by high-throughput full-length 16S rRNA gene sequencing and automated taxonomy assignment (AutoTax)](https://www.biorxiv.org/content/10.1101/672873v3)

**Comment by dikiprawisuda** [comment]
I see, yes I was about to simply paste them together and remove possible duplicates based on the one sequence string. I was also planning on doing the same with species reference database.

Does that mean it is okay to simply paste one "general purpose database" above another?
Are those databases in https://benjjneb.github.io/dada2/training.html belong to the "general purpose" database?

Thanks

**Comment by benjjneb** [comment]
> Does that mean it is okay to simply paste one "general purpose database" above another?

No. See comment above. "They use different taxonomic definitions and systems..."

**Comment by dikiprawisuda** [comment]
Ah I see, thank you very much.
