### ISSUE TITLE
pooling TRUE vs. pseudo-pool, ASV disappearing

### ISSUE THREAD

**Issue by Andreas-Bio** [benjjneb/dada2#1086]
As far as I understood pseudo-pooling is a middle ground between pooling and no pooling. However pooling, in my hands, results in much less ASV and I wonder whether or not this is intended behaviour.

DETECT_SINGLETONS =T, all OMEGA values (except OMEGA_C) set to 0.99 for maximum sensitivity

I pool (or pseudo-pool) reads from all 9 PCR replicates of sample 415.

output with pseudo-pooling: 4300 ASV total in all 9 PCR replicates of sample 415
everything the same, but with pool=TRUE: 1400 ASV total in all 9 PCR replicates of sample 415

Here is an example of one species I will be missing completely if I change pooling methods. The ASV of this species have multiple reads in some cases. All ASV of that species are gone when I use pool=TRUE.
![grafik](https://user-images.githubusercontent.com/19622117/89112069-2c17e800-d45e-11ea-9e60-7b802cca4ec3.png)
(rep=PCR replicate number, all replicates are used for pooling, 9 replicates in total)

All results are final results after chimera removal. Workflow: 1) N removal 2) primer removal 3) quality filter 4) dada (up to here everything is the same, afterwards everything is the same) 5) merging reads 6)dada chimera removal 7) ITSx ITS2 region extraction (incl. built in ITSx chimera removal) 8) SINTAX

I checked and each filtering step does not loose more than 10% of the total reads (incl. merging).

I am struggling to understand how and why. I read the manual and from the explanation it seems as if pseudo-pool should yield less ASV and not more. I am not sure if that difference is within acceptable parameters, so I wanted to let you know.

**Comment by benjjneb** [comment]
Can you identify whether the ASVs/reads corresponding to this species are being removed in the denoising step or (my guess) in the chimera removal step?

Can you also describe the quality filtering you are performing. I am wondering if it is possible your quality filtering is introducing length variation amongst the raw reads.

**Comment by andzandz11** [comment]
`maxN = 0, rm.phix = T, compress = T, minLen = 30, **truncQ=20**, maxEE = 0.1, rm.lowcomplex = 4, matchIDs = T`
This is the only operation I persorm on the reads that alters length not by a fixed value (truncate primer).

**Comment by andzandz11** [comment]
Okay so first of all: validation: 
My ASV I am looking for:
```
erica <- c(
"ATTGCGTCGCTCACTCACCCCGTGCCTCACAGGGCGGGTAAGTGCGTGGGCGGATATTGGCCCCCCGTTCACATTTGTGCTCGGTTGGCCTAAAAAGAAGGTCCCTGATGACGGACATCACAACAAGTGGTGGTTGCCAAACTGTCGCGACACGTTGTGCATGCTACGCAGTCGTCGGTGGGCTCATTGACCCTTAAGTGCCATTGAACTTGGTACCTCAA",
"ATTGCGTCGCTCACTCACCCCGTGCCTCACAGGGCGGGTAAGTGCGTGGGCGGATATTGGCCCCCCGTTCACATTTGTGCTCGGTTGGCCTAAAAAGAAGGTCCCTGATGACGGACATCACAACAAGTGGTGGTTGCCAAACTGTCGCGACACGTTGTGCATGCTACGCAGTCGTCGGTGGGCTCATTGACCCTTAAGTGCCATTGAACTTGGTACCTCAA",
"ATTGCGTCGCTCACTCACCCCGTGCCTCACAGGGCGGGTAAGTGCGTGGGCGGATATTGGCCCCCCGTTCACATTTGTGCTCGGTTGGCCTAAAAAGAAGGTCCCTGATGACGGACATCACAACAAGTGGTGGTTGCCAAACTGTCGCGACACGTTGTGCATGCTACGCAGTCGTCGGTGGGCTCATTGACCCTTAAGTGCCATTGAACTTGGTACCTCAA",
"ATTGCGTCGCTCACTCACCCCGTGCCTCACAGGGCGGGTAAGTGCGTGGGCGGATATTGGCCCCCCGTTCACATTTGTGCTCGGTTGCCTAAAAAGAAGGTCCCTGATGACGGACATCACAACAAGTGGTGGTTGCCAAACTGTCGCGACACGTTGTGCACGCTACGCAGTCGTCGGTGGGCTCATTGACCCAACATCCTTA",
"ATTGCGTCGCTCACTCACCCCGTGCCTCACAGGGCGGGTAAGTGCGTGGGCGGATATTGGCCCCCCGTTCACATTTGTGCTCGGTTGGCCTAAAAAGAAGGTCCCTGATGACGGACATCACAACAAGTGGTGGTTGCCAAACTGTCGCGACACGTTGTGCATGCTACGCAGTCGTCGGTGGGCTCATTGACCCTTAAGTGCCATTGAACTTGGTACCTCAA",
"ATTGCGTCGCTCACTCACCCCGTGCCTCACAGGGCGGGTAAGTGCGTGGGCGGATATTGGCCCCCCGTTCACATTTGTGCTCGGTTGGCCTAAAAAGAAGGTCCCTGATGACGGACATCACAACAAGTGGTGGTTGCCAAACTGTCGCGACACGTTGTGCATGCTACGCAGTCGTCGGTGGGCTCATTGACCCTTAAGTGCCATTGAACTTGGTACCTCAA",
"ATTGCGTCGCTCACTCACCCCGTGCCTCACAGGGCGGGTAAGTGCGTGGGCGGATATTGGCCCCCCGTTCACATTTGTGCTCGGTTGGCCTAAAAAGAAGGTCCCTGATGACGGACATCACAACAAGTGGTGGTTGCCAAACTGTCGCGACACGTTGTGCATGCTACGCAGTCGTCGGTGGGCTCATTGACCCTTAAGTGCCATTGGACTTGGTACCTCAA",
"ATTGCGTCGCTCACTCACCCCGTGCCTCACAGGGCGGGTAAGTGCGTGGGCGGATATTGGCCCCCCGATCACATTTGTGCTCGGTTGGCCTAAAAAGAAGGTCCCTGATGACGGACATCACAACAAGTGGTGGTTGCCAAACTGTCGCGACACGTTGTGCATGCTACGCAGTCGTCGGTGGGCTCATTGACCCTTAAGTGCCATTGAACTTGGTACCTCAA",
"ATTGCGTCGCTCACTCACCCCGTGCCTCACAGGGCGGGTAAGTGCGTGGGCGGATATTGGCCCCCCGTTCACATTTGTGCTCGGTTGGCCTAAAAAGAAGGTCCCTGATGACGGACATCACAACAAGTGGTGGTTGCCAAACTGTCGCGACACGTTGTGCATGCTACGCAGTCGTCGGTGGGCTCATTGACCCTTAAGTGCCATTGAACTTGGTACCTCAA",
"ATTGCGTCGCTCACTCACCCCGTGCCTCACAGGGCGGGTAAGTGCGTGGGCGGATATTGGCCCCCCGTTCACATTTGTGCTCGGTTGGCCTAAAAAGAAGGTCCCTGATGACGGACATCACAACAAGTGGTGGTTGCCAAACTGTCGCAACACGTTGTGCATGCTACGCAGTCGTCGGTGGGCTCATTGACCCTTAAGTGCCATTGAACTTGGTACCTCAA",
"ATTGCGTCGCTCACTCACCCCGTGCCTCACAGGGCGGGTAAGTGCGTGGGCGGATATTGGCCCCCCGTTCACATTTGTGCTCGGTTGGCCTAAAAAGAAGGTCCCTGATGACGGACATCACAACAAGTGGTGGTTGCCAAACTGTCGCGACACGTTGTGCATGCTACGCAGTCGTCGGTGGGCTCATTGACCCTTAAGTGCCATTGAACTTGGTACCTCAA",
"ATTGCGTCGCTCACTCACCCCGTGCCTCACAGGGCGGGTAAGTGCGTGGGCGGATATTGGCCCCCCGTTCACATTTGTGCTCGGTTGGCCTAAAAAGAAGGTCCCTGATGACGGACATCACAACAAGTGGTGGTTGCCAAACTGTCGCGACACGTTGTGCATGCTACGCAGTCGTCGGTGGGCTCATTGACCCTTAAGTGCCATTGAACTTGGTACCTCAA")
```


pool="pseudo" omegas=0.99 singletons=T

**Comment by benjjneb** [comment]
> truncQ=20 This is the only operation I perform on the reads that alters length not by a fixed value (truncate primer).

First, I highly recommend **not** using this `truncQ` parameters. This sort of truncation introduces random length variation amongst otherwise identical sequences. This can result in lower sensitivity, but maybe more important can lead to the same ASV in one sample being identified differntly than in another sample, just because the links of the truncated reads were slightly different. There is a good chance this explains the inflation in ASV numbers by pseudo-pooling -- some of the replicates have the same ASVs, but at different lengths. One easy way to test this is to run `collapseNoMismatch` on the pseudo-pooled sequence table, and see if that results in a table with fewer ASVs.

> No, the ASV I am missing are not removed by chimera removal. I was very careful about the primers and stuff. The ASV are removed due to the different pooling method I chose. I would understand if ASV that have one read in only one replicate (the pool is all 9 replicates of sample M2) would be unstable, but ASV1 is present in multiple replicates, in one of them it has 4 reads.

I also don't understand what is happening with the `pool=TRUE` results, i.e. why these ASVs are not showing up in that sequence table. I see you attached the relevant files. I can take a look at them myself, but it might take a couple days.

One improtant question: Are those files from before or after filtering? I would much rather work with the pre-filtered files if at all possible (i.e. before `filterAndTrim` was run on them).

**Comment by andzandz11** [comment]
files before main filtering. Filters that have been already applied: maxN = 0, rm.phix = T, minLen = 30)
https://drive.google.com/file/d/1eZhZHvdMbyik27ew5WQM8UYI908_ZXfB/view?usp=sharing
