### ISSUE TITLE
Doubt in equal sequence length input to dada2

### ISSUE THREAD

**Issue by MrX-NGS** [benjjneb/dada2#1088]
Hi,

I used the figaro software to choose the optimal trimming parameters. It requires all the reads in equal length and i trim the reads in equal length and got the optimal trimming parameters for dada2.

Currently, I am wondering whether dada2 requires the similar input with all the reads in equal length too or due to insert and deletion, it might accept the few read length variations within the dataset. Please clarify so that i can proceed with either trimmed similar read length or actual input with minor read length variations.

Thanks in advance for your help!

Best Regards,
Bala

**Comment by joey711** [comment]
For the same read-direction, you want input to be trimmed at the same locations for all reads.
Differences in end-gaps can be addressed after the fact as "shiftmeras". 
If you have paired-reads, they are denoised separately, with separate trimming locations, and the final denoised-then-merged results can render moot a lot of effect of trimming location and final sequence. The most effective version of this is when the overlap is quite good and there is not a lot of length variation for the locus being amplified.
