### ISSUE TITLE
Exporting merged reads or AVS for further analysis

### ISSUE THREAD

**Issue by lonehusky76** [benjjneb/dada2#1090]
My apologies for this likely being a naive question. I have performed a series of amplicon sequencing of virally expressed genes with sequence-specific barcodes. I have used Dada2 to perform filtering, trimming, and merging of paired reads successfully. I would now like to export the merged reads either as FASTQ files or more desirably the ASV with sequence frequencies as a .CSV file so that I can use an algorithm I created in Python to search for the specific barcodes in each of the sequences, tabulating the appropriate frequencies.

Again, please forgive me, if this is an obvious question, while I have some degree of coding experience, I'm rather new to R.

-VB

**Comment by benjjneb** [comment]
There are a number of ways to write out information contained in R to files, such as .csv files.

One obvious function would be `write.table` or the more specialized `write.csv`. I'd suggest taking a look at the documentation for those functions and giving them a try. If you get stuck feel free to follow up.
