### ISSUE TITLE
Export the reads mapping information

### ISSUE THREAD

**Issue by PengfanZhang** [benjjneb/dada2#1091]
I am currently using DADA2 to analyze amplicon sequencing data. There is a special demand for my project to find out which ASV each read is assigned/corrected to. I am wondering does DADA2 support the function to output the reads-to-ASV mapping file.

Thanks in advance,

Pengfan

**Comment by benjjneb** [comment]
See this issue: https://github.com/benjjneb/dada2/issues/354

And this comment: https://github.com/benjjneb/dada2/issues/889

It's straightforward to track reads to denoised ASVs using the `$map`s described above. Tracking through to merged ASVs is not quite so straightforward unfortunately.
