### ISSUE TITLE
dada2 derepFasta error

### ISSUE THREAD

**Issue by mvelg** [benjjneb/dada2#1092]
I get the following error when I try to apply derepFasta function to a fasta file:

Error in match.arg(tolower(format), c("fasta", "fastq")) :
  'arg' should be one of “fasta”, “fastq”

What may be the problem?

Thank you,

María

**Comment by benjjneb** [comment]
Can you provide the exact command you are executing that is causing this failure?

Also, what is the filepath, and does that file exists? `file.exists("path/to/my.fasta")`

**Comment by mvelg** [comment]
Sure!

dereps  <- derepFasta('/scratch/mvelasco/16SRabbit/QIIME_uclust_pavana/contigs_quality_check/seqs_chimeras_filtered.fna')

file.exists('/scratch/mvelasco/16SRabbit/QIIME_uclust_pavana/contigs_quality_check/seqs_chimeras_filtered.fna')
[1] TRUE

**Comment by benjjneb** [comment]
Can you try renaming that file from `.fna` to `.fasta`?

**Comment by mvelg** [comment]
Yes, I hace renamed the file but the same error persists.

**Comment by benjjneb** [comment]
I don't know. What version of the dada2 R package are you using? Also, how are you calling `derepFasta` without the `:::` operator? It is not exported from the package. You should be calling it like `dada2:::derepFasta(...)`
