### ISSUE TITLE
Use .fastq.gz files instead of .fastq files at the beginning of the DADA2 pipeline?

### ISSUE THREAD

**Issue by seqlt** [benjjneb/dada2#1093]
My question is Can I use .fastq.gz files instead of .fastq files at the beginning of the DADA2 pipeline?
The reason I would like to use .fastq.gz files is because after I unzipped them, some of my .fastq files always broke and I got an error from the pipeline.:

Error in add(bin) : internal: buf != <newline>

ps.I use Mac, so I always use the Unarchiver.app or Archive Utility for my unzipped tool.

Thank you so much.
Seqlt (Nilita)

**Comment by benjjneb** [comment]
Yes.
