### ISSUE TITLE
Converting DECIPHER IDTAXA taxonomy into a matrix analogous to the output from assignTaxonomy

### ISSUE THREAD

**Issue by lgulmann** [benjjneb/dada2#1096]
Hello -
 In trying to convert my decipher output file into a matrix analogous to the output from assignTaxonomy, I receive this error

 Error in x$rank : $ operator is invalid for atomic vectors 

I am reading my decipher results back into R with the following: 

decipherTAX_3757 <- read.csv("~/happy_bin/Decipher_Silva138_50_no_contaminants.csv", header=T)

And then following the tutorial to modify the  format of the decipher output.

ranks <- c("domain", "phylum", "class", "order", "family", "genus", "species")
decipherCS_tax <- t(sapply(decipherTAX_3757, function(x) {
  m <- match(ranks, x$rank)
  taxa <- x$taxon[m]
  taxa[startsWith(taxa, "unclassified_")] <- NA
  taxa
}))

any advice would be greatly appreciated! Thank you!

**Comment by benjjneb** [comment]
Probably the round-trip from csv file back into R has left you with an improperly formatted decipherTAX_3757 data.frame.

If you inspect that, does it look right?

I'd recommend just re-running IDTaxa, and in the future using `saveRDS`/`readRDS` to save and reload R objects to disk. That way, you get back exactly what you saved.

**Comment by lgulmann** [comment]
Hello and Thank you.
But I had an issue running IDTaxa in R, so I ran the classification step via the website and now 
I am struggling to get my dada2 files into phyloseq (I manually changed the IDTAXA output to match the output of assignTaxonomy). If you have a moment to shed some light on what I've done wrong, I'd greatly appreciate it. 

I receive this error when I try ps <- phyloseq(OTU, TAX)

Error in validObject(.Object) : invalid class “phyloseq” object:
Component taxa/OTU names do not match.
Taxa indices are critical to analysis.
Try taxa_names()

I've checked that the ASV's are the same between the 'OTU' file and the 'TAX' file - but when I look at the files in R, there appear to be differences.

> all(rownames(ASV_CS_3757) == rownames(taxon_Decipher_3757))
[1] TRUE

This is how I read the data in, define the row names from the ASV (here "X") column, and removed the X Column:
mytax <- readRDS(file = "taxonomyDecipher50_3757.rds")

taxon_Decipher_3757 <- read.csv("NEWEST_DECIPHER.csv", header = TRUE, sep = ",")
head(taxon_Decipher_3757)
row.names(taxon_Decipher_3757) <- taxon_Decipher_3757$X
taxon_Decipher_3757 <- taxon_Decipher_3757 %>% select (-X)
and for the ASV count file:
SV_CS_3757 <- read.table(file = 'ASVs_countsCS_3757_.tsv', sep = '\t', header = TRUE)
head(ASV_CS_3757)
row.names(ASV_CS_3757) <- ASV_CS_3757$ASV
ASV_CS_3757 <- ASV_CS_3757 %>% select (-ASV)

> ASV_CS_3757 <- as.matrix(ASV_CS_3757)
> taxon_Decipher_3757 <- as.matrix(taxon_Decipher_3757)
> OTU = otu_table(ASV_CS_3757, taxa_are_rows = TRUE)
> TAX = tax_table(taxon_Decipher_3757)

head(OTU)
OTU Table: [6 taxa and 22 samples]
taxa are rows
BKG.11.14 CS.11.14 BKG.LVP1A BKG.LVP6 CS.1.07 CS.1.08 CS.10.08 CS.1.14.LVP2 CS.1.14.LVP3
ASV_1 7779 21 0 0 0 0 0 0 0
ASV_2 0 2802 40 0 105 1056 421 269 407
ASV_3 0 0 0 0 0 0 0 0 0
ASV_4 0 1222 12 2 24 735 198 127 185
ASV_5 0 0 0 0 0 0 0 14 0
ASV_6 0 0 0 0 0 0 0 0 0
CS.1.14.LVP4 TB.LVP5 TB.LVP8 TB.Rock Tica.LVP.11GFF Tica.LVP.11M CS.5.17 A.DNA.R1 B.DNA.R1
ASV_1 0 0 0 0 0 0 0 0 0
ASV_2 309 28 3 0 550 13 1284 205 0
ASV_3 0 0 0 0 0 0 0 0 0
ASV_4 196 2 3 0 649 14 655 0 121
ASV_5 0 0 17 0 12 41 0 143 0
ASV_6 0 0 0 0 0 0 0 553 1378
C.DNA.R1 D.DNA.R1 E.DNA.R1 F.DNA.R1
ASV_1 0 0 0 0
ASV_2 0 0 0 0
ASV_3 0 0 0 0
ASV_4 0 0 0 0
ASV_5 1127 628 917 958
ASV_6 666 194 368 266
head(TAX)
Taxonomy Table: [6 taxa by 7 taxonomic ranks]:
X domain phylum class order
sp1 "ASV_1" "Bacteria" "Proteobacteria" "Gammaproteobacteria" "Thiomicrospirales"
sp2 "ASV_2" "Bacteria" "Campilobacterota" "Campylobacteria" "Campylobacterales"
sp3 "ASV_3" "Bacteria" "Proteobacteria" "Gammaproteobacteria" "Pseudomonadales"
sp4 "ASV_4" "Bacteria" "Campilobacterota" "Campylobacteria" "Campylobacterales"
sp5 "ASV_5" "Bacteria" "Campilobacterota" "Campylobacteria" "Campylobacterales"
sp6 "ASV_6" "Bacteria" "Bacteroidota" "Bacteroidia" "Flavobacteriales"
family genus
sp1 "Thioglobaceae" "SUP05 cluster"
sp2 "Sulfurovaceae" "Sulfurovum"
sp3 "Pseudomonadaceae" "Azotobacter"
sp4 "Sulfurovaceae" "Sulfurovum"
sp5 "Sulfurimonadaceae" "Sulfurimonas"
sp6 "Flavobacteriaceae" "Mesoflavibacter"

SO I can see that the TAX file has a column with sp1, sp2 that doesn't match with my OTU file, but I am not sure of the best way to fix this. Also the TAX file has everything in quotes, while the OTU file doesn't.

Thanks so very much for any advice!

**Comment by benjjneb** [comment]
Your taxonomy table doesn't have the right rownmaes. The `ASV_1` entire should be showing up as the rownames, but instead they are in that first column, and there are some other rownames `sp1`/`sp2/... instead.

It looks like the code to replaces the rownames with the X column, and then remove the X column, didn't quite work out right. I would re-inspect the `taxon_Decipher_3757` objects *after making it a matrix*, i.e. right before the `tax_table(taxon_Decipher_3757)`, and see if that makes the issue clear.

**Comment by lgulmann** [comment]
Thank you.  
Got it to work.  Much appreciated!
