### ISSUE TITLE
Error in writeFastq(fqF, fout[[1]], "w", compress = compress) : failed to open file

### ISSUE THREAD

**Issue by smar2716** [benjjneb/dada2#1098]
Hello,

I am having issues creating the output directory during the filterAndTrim step. I have checked for duplicates and have none. Could I please get some feedback on what may be causing this error? Below is the code I am using and the error output. Thanks in advance!

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(275,265),
              maxN=0, maxEE=c(4,8), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=FALSE)
Error in writeFastq(fqF, fout[[1]], "w", compress = compress) : failed to open file 'C:\Users\Jaxon Smart\Documents\dryAged_Bacteria\filtered\C:\Users\Jaxon Smart\Documents\dryAgedBacteria\1_F_filt.fastq.gz'
6.writeFastq(fqF, fout[[1]], "w", compress = compress)
5.writeFastq(fqF, fout[[1]], "w", compress = compress)
4.(function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0, 0), maxLen = c(Inf, Inf), minLen = c(20, 20), trimLeft = c(0, 0), trimRight = c(0, 0), minQ = c(0, 0), maxEE = c(Inf, Inf), rm.phix = c(TRUE, TRUE), rm.lowcomplex = c(0, 0), matchIDs = FALSE, ...
3.mapply(FUN = FUN, ..., MoreArgs = MoreArgs, SIMPLIFY = SIMPLIFY, USE.NAMES = USE.NAMES)
2.mcmapply(fastqPairedFilter, mapply(c, fwd, rev, SIMPLIFY = FALSE), mapply(c, filt, filt.rev, SIMPLIFY = FALSE), MoreArgs = list(truncQ = truncQ, truncLen = truncLen, trimLeft = trimLeft, trimRight = trimRight, maxLen = maxLen, minLen = minLen, maxN = maxN, minQ = minQ, ...
1.filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen = c(275, 265), maxN = 0, maxEE = c(4, 8), truncQ = 2, rm.phix = TRUE, compress = TRUE, multithread = FALSE)

**Comment by benjjneb** [comment]
> 'C:\Users\Jaxon Smart\Documents\dryAged_Bacteria\filtered\C:\Users\Jaxon Smart\Documents\dryAgedBacteria\1_F_filt.fastq.gz'

That isn't a valid file path. What is the code you are using to create the `filtFs`/`filtRs`? It appears to be combining the full directory path of the filtered file with the full path to the unfiltered files. You will want to use just the `basename(fnFs)` there (that's just the file name without the preceding path).

**Comment by smar2716** [comment]
Below is the code I used to create the filtFs/filtRs

filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names
________________________________

**Comment by benjjneb** [comment]
Probably your sample.names are malformed then. If you inspect them, do they look like sample names, or are there a bunch of directory information?

If the latter, you can edit the code that creates the `sample.names` by replacing `fnFs` with `basename(fnFs)` and it will probably fix the problem.

**Comment by smar2716** [comment]
That fixed the problem. Thank you!

Jaxon Smart
________________________________

**Comment by nafsa2021** [comment]
Hi I wonder if I could ask a question from RStudio. Here is the my function:
filterAndTrim(fnFs, fnFs.filtN, fnRs, fnRs.filtN, maxN = 0, multithread = FALSE)
and I got this error:
Creating output directory: E:/Nafsa/Fungi seq/Fungi seq/Fungi seq/filtN
Error in writeFastq(fqF, fout[[1]], "w", compress = compress) : 
  failed to write record 26998

**Comment by benjjneb** [comment]
Previously this error arose when the hard drive or space assigned to the output directory ran out. See https://github.com/benjjneb/dada2/issues/607 and the linked Q2 forum discussion from there

**Comment by nafsa2021** [comment]
> @nafsa2021 Previously this error arose when the hard drive or space assigned to the output directory ran out. See #607 and the linked Q2 forum discussion from there

Thanks! Is that for RAM or storage?

**Comment by benjjneb** [comment]
Storage

**Comment by nafsa2021** [comment]
> Storage

Thanks! Then would that be fixed if I used an SSD?

**Comment by benjjneb** [comment]
Anything with enough storage space. An SSD, sure.

**Comment by nafsa2021** [comment]
Hi there, I had this function in R:
rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.cut[[1]]), 
+       FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.cut[[1]]), 
+       REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.cut[[1]]), 
+       REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.cut[[1]]))

And I received this error:
Error in h(simpleError(msg, call)) : 
error in evaluating the argument 'subject' in selecting a method for function 'vcountPattern': error in evaluating the argument 'object' in selecting a method for function 'sread': Input/Output
no input files found
dirPath: H:/Analyses/Fungi seq/cutadapt/DNA-2BF4_S238_L001_R1_001.fastq.gz
pattern: character(0)

**Comment by benjjneb** [comment]
> no input files found
> dirPath: H:/Analyses/Fungi seq/cutadapt/DNA-2BF4_S238_L001_R1_001.fastq.gz

R is failling to find the file you are trying to point it towards.
One suggestion, remove all spaces from your file paths, then try rerunning from the start w/ cutadapt.
Spaces in paths (like "Fungi seq") are a notorious cause of file path issues, and should be avoided.

**Comment by Jigyasa3** [comment]
Hi @benjjneb,

I am getting the same error while running on linux machine. The `filterAndTrim` command generates an output file (it has data in it) but I still get an error `Error in writeFastq(fqF, fout[[1]], "a", compress = compress) :
  failed to write record 28708` 

Code used-
`path="/bucket/BourguignonU/Jigs_backup/rotation_data/sasha_unit/16S_metaanalysis/16S_raw_PRJEB27458_11721/FASTQ/51078/"
samples<-c("Jake_Mackeral_1_3_S1_L001")
forward_reads<-paste0(path,samples,"_R1_001.fastq.gz")
reverse_reads<-paste0(path,samples,"_R2_001.fastq.gz")
`
`filtered_forward_reads <- paste0(samples, "_R1_filtered.fq.gz")
filtered_reverse_reads <- paste0(samples, "_R2_filtered.fq.gz")
`
`filtered_out1<-filterAndTrim(forward_reads, filtered_forward_reads, reverse_reads, filtered_reverse_reads, maxEE=c(2,2), rm.phix=TRUE)`

**Comment by benjjneb** [comment]
@Jigyasa3 Can you describe the computing environment you are working on? Is it possible that your storage space is running out?
