### ISSUE TITLE
Recomendation for visualizing the output of "assignTaxonomy"

### ISSUE THREAD

**Issue by ms-gx** [benjjneb/dada2#1099]
Do you have a recommendation on how to visualize the output of "assignTaxonomy".

It would be great to be able to investigate the output on different taxonomic levels, and see where we have branches, etc. That would allow a quick discovery of taxonomic groups we want to investigate in. Ideally something interactive like a Krona plot or Pavian visualization. Of course I should be able to write up something that translates the output to something Krona/Pavian can work with. Bu if there is already anything, even better.

Ideally one could augment it with the numbers for the respective ASV. See this issue as well: https://github.com/benjjneb/dada2/issues/1097

**Comment by benjjneb** [comment]
The dada2 R package focuses only on the sample inference part of microbiome analysis, i.e. processing the raw data into an accurate census of the underlying community. For further analysis, there are of course a vast array of general tools in R for exploratory and inferential statistics, visualization, machine learning etc.

But perhaps most useful would be to take a look at the dedicated R packages that have been developed for microbiome analysis, which include [phyloseq](https://joey711.github.io/phyloseq/), [microbiome](https://microbiome.github.io/tutorials/), and [ampvis2](https://madsalbertsen.github.io/ampvis2/articles/ampvis2.html).
