### ISSUE TITLE
Samples from different MiSeq runs

### ISSUE THREAD

**Issue by huyue87** [benjjneb/dada2#110]
Hey,

I have some bacterial isolates sequenced in two MiSeq runs, and I have combined these samples and ran the dada2 workflow on them. The result looks like what I expected, which might be due to the low diversity in genetic content for each sample (each isolate). However, I know it is better to run dada2 on samples from the same run because of the different errors from different runs. But I do not know how exactly dada2 can be affected by running it on a merged dataset from different runs. Could you please explain it a little bit.

**Comment by benjjneb** [comment]
When you estimate errors from two runs merged together, the fitted error model will be the average error rates between the runs. This will be fine if the runs have the same error rates, but if that is not the case, the error rates will be wrong for both runs (eg. too high for one, too low for the other). The result will be lower accuracy, especially in separating out low frequency and nearby variants from noise.

If runs are on the same machine, error profiles are often similar and this issue mostly goes away. But Illumina error rates, especially on different machines, can be quite different. Thus it is best practice to process runs independently, and merge the output tables later.

To make that more convenient, we recently implemented the `mergeSequenceTables` function. So process each run, and then just `seqtab <- mergeSequenceTables(seqtab_run1, seqtab_run2)`.

**Comment by huyue87** [comment]
Thanks, Benji. You explained it quite clear.
I think I had better run them separately since there is an obvious difference of the error curves from two runs. I will try the function mergeSeqTables soon.

**Comment by huyue87** [comment]
Hi Benji, the table merging function works quite smooth. Very good function!
