### ISSUE TITLE
multithread=TRUE in Window

### ISSUE THREAD

**Issue by seqlt** [benjjneb/dada2#1100]
As we know on Windows set multithread=FALSE

I've been set multithread=FALSE for all of my code lines that have multithread.
However, after I ran the pipeline and finished. I just notice that I forgot to change this one line.

taxa <- assignTaxonomy(seqtab.nochim, "~/tax/silva_nr_v132_train_set.fa.gz", multithread=TRUE)

Are there going to affect my result from the pipeline?

Thank you.

**Comment by benjjneb** [comment]
Nope. And actually you can use `multithread=TRUE` on Windows (and probably should if computation time is an issue) for every command except `filterAndTrim`.

**Comment by seqlt** [comment]
I see, Thank you so much.
