### ISSUE TITLE
Strange error rates and problems downstream with losing reads and assigning taxa

### ISSUE THREAD

**Issue by JakeBrit** [benjjneb/dada2#1105]
Thanks so much for helping with this. I'm having some problems in DADA2 with a 16s microbiome analysis. We are losing a lot of reads especially in the denoising stage but also in the downstream merging and removing chimera stages  (see below)

Here is a summary at the end of the quality control:

                    input.     filtered denoisedF    denoisedR merged nonchim
A107           30310    26464     14020         13105             6502     210
A109           21195    19073      8957                 8785       3706     405
A11             9683     8912      3824                       3212   1402     454
A110           34168    31089     15983               14709   6606     156
A113           13586    12191      6163                  5097   2488     579
A116           38475    35164     14546                11021   5040      94

We have been through all quality plots and removed the samples with very poor quality. We have also used multiple different filter and trim parameters to retain the greatest number of reads. For all samples both positive and negative reads are of good quality and can be trimmed around 240 and 230bp respectively to ensure an overlap between samples. 

We initially thought that primers could be the cause of this, however we have checked whether the primer sequences could be found in the fastq files and found very few in the microbiome run, so it seems that we don't need to remove the primers.

I've checked everything and it all looks normal except the error plots look a little strange to me. I have attached the error rates plots. They don't follow the QQ line as expected but I don't know whether this could cause these problems downstream. I have tried to increase the number of bases which the machine learning uses to learn the error rates and have tried randomizing the samples it learns the error rates from but they do not improve. Could you think of any other reason the error plots might not follow the expected errors? 

[Error_plots_with_all_poor_samples_excluded.pdf](https://github.com/benjjneb/dada2/files/5114124/Error_plots_with_all_poor_samples_excluded.pdf)

Using slightly different parameters, if we push through to later stages using forward reads only, effectively removing the merging phase (see summary below), we maintain more reads but still have problems as many of these sequences remain unassigned at the taxa level in the assign taxonomy stage (see attached). I've tried tryRC =TRUE but it doesn't seem to make that much difference. I think it's an upstream problem I'm a little stuck. Is there anything you could suggest? I can provide any additional information if required. 

<img width="300" alt="Summary reads" src="https://user-images.githubusercontent.com/70102905/90981690-6acf2880-e55a-11ea-9b23-1a4b83247349.png">

<img width="1201" alt="Assign Taxa" src="https://user-images.githubusercontent.com/70102905/90981538-8b4ab300-e559-11ea-8070-4c58c500bf8f.png">

Thank you so much for your help, 
Jake

**Comment by benjjneb** [comment]
Usually this is one of two reasons: Primers are slipping through and haven't really been removed, or high artefact penetration into the sequencing data.

So let's try to rule those possibilities out first.

What are your forward and reverse primers? I.e. in ACGT format.
And can you post an example 10 sequences from your post-trimming reads?

Second, what is the output of `plotComplexity` on an example forward read file from one of these samples?
And, what is the output of a BLAST search of say 10 random sequences from the same file?

**Comment by JakeBrit** [comment]
We are using the following dual index primers for our 16S analysis:

Forward: GTGCCAGCMGCCGCGGTAA 
Reverse: GGACTACHVGGGTWTCTAAT 

Example sequences from our post trimming reads are:

TGGCTCATCGGCATCGCCGCCGGGGCGTGGATCGTGGTGACCATCCTCGACAAAGTGCTGTAAGCCGGATCCATCGGGCACCGGGAGACCGGTGTTCTTTTTGTACCCTGCTTCCGTATCTTTGTTTTTACGGCCCGCGGTTTCCGGACTGTTCCGCCGGGGAACGCGGCAT

TGGTGAAAGCCCTGAGCTCAACTCAGGAACTGCCATTGATACTGTCAGGCTGGAATACGGATGCCGTGGGAGGAATGAGTAGTGTAGCGGTGAAATGCATAGATATTACTCAGAACACCGATTGCGAAGGCATCTCACGAATCCGTCATTGACGCTGAGGCACGAAAGCGTG

ATGTGAAAGCACGAGGCTCAACTTCGTGTCTGCATTTGAAACTGCCGTTCTTGAGTGTTGGAGAGGCTAACGGAACTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAAGAACACCAGTGGCGAAGGCGGTTAGCTGGACAATAACTGACGCTGAGGCGCGAAAGCGTG

ATGTGAAAGCCCACGGCTCAACCGTGGAGGGTCATTGGAAACTGGGAGACTTGAGTGCAGAAGAGGATAGTGGAATTCCAAGTGTAGCGGTGAAATGCGTAGAGATTTGGAGGGACACCAGTGGCGAAGGCGACTGTCTGGTCTGTAACTGACACTGAGGCGCGAAAGCGTG

TGGTCAAAGCGTGTGGCTCAACCATACCACGCCATTGATACTGGATGCCTTGAGTGCACATAAGGATGGTGGAATTCATGGTGTAGCGGTGAAATGCTTAGATATCATGAAGAACTCCGATTGCGAAGGCAGCTGTCCGGGGTGTAACTGACGCTAATGCTCGAAAGTGCGG

AAGTGAAAGCCCGTGGCTCAACTGCGGGACTGCTTTTGAAACTGCTAAGCTAGAGTACTGGAGGGGTAAGCGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAAGAACACCGGAGGCGAAGGCGGCTTACTGGACAGAAACTGACGCTCAGGCACGAAGGCGTG

GAATCAAATCCCGAAGCTTAACTTCGGTTCGTTCTATAAACTGACTTACTCGAGTATAGTAGAGGCAAGTGGAACTTCCAGTGTAGCGGTAGAATGCGTAGATATTGGAAAGAACACCAGTGGCGAAGGCGACTTGCTGGGCTATTACTGACGTTCATGGACGAAAGCGTGG

CGGTGAAATCTCCGGGCTCAACTCGGAAACTGCCGTTGATACTGGCGGCCTTGAGTCATGTCGAGGATGGCGGAATGCAGCGTGTAGCGGTGAAATGCTTAGATATGCTGCAGAACTCCGATTGCGAAGGCAGCTGTCCAGAGATGTACTGACGCTCAGGCACGAAAGCATG

TTGTGAAAGTTTGCGGCTCAACCGTAAAATTGCAGTTGAAACTGAATGTCTTGAGTGCACATGAGGATGGTGGAATTTGTGGTGTAGCGGTGAAATGCATAGATATCACGAAGAACTCCGATTGCGAAGGCAGCTATCTAGGGTGTAACTGACGCTGAGGCTCGAAAGTGCG

ATGTGAAATCCTATGGCTTAACCATAGAACTGCATTAGATACTGGGAAGCTGGAGTGCGGAAGAGGTTGACGGAATTACTAGTGTAGCGGTAGAATGCGTAGATATTAGTAAGAAGACCGGTGGCGAAGGCGGTCAACTGGGACGTAACTGACGCTGAGGCACGAAAGCGTG

As suggested I then used plotComplexity for a single post filtered forward read file and blasted 10 random sequences. 

PlotComplexity graph: 

![A107_F_filt fastq gz](https://user-images.githubusercontent.com/70102905/91972684-f0996380-ed12-11ea-80f0-a85e3cc6fe1a.png)


BLAST top hits for ten random sequences:

— No significant similarity found
— Uncultured bacterium clone IR_aaa04h06 16S ribosomal RNA gene, partial sequence
—Uncultured Ruminococcaceae bacterium clone denovo9504 16S ribosomal RNA gene, partial sequence
— Uncultured bacterium clone A2165 16S ribosomal RNA gene, partial sequence
—Uncultured Prevotellaceae bacterium clone denovo321384 16S ribosomal RNA gene, partial sequence
— Uncultured Lachnospiraceae bacterium clone denovo196073 16S ribosomal RNA gene, partial sequence
— Uncultured prokaryote clone OTU_1518 16S ribosomal RNA gene, partial sequence
— Uncultured bacterium gene for 16S rRNA, partial sequence, clone: YT41
— Uncultured Prevotellaceae bacterium clone denovo216842 16S ribosomal RNA gene, partial sequence
—  Uncultured bacterium clone A1266 16S ribosomal RNA gene, partial sequence

Thank you so much for your help, I really appreciate it. 
Jake 

P.S. Additionally, I have BLAST results from another forward reads file which came up a little strange. The BLAST results consistently came up as a Nematode species for its top hit which is unexpected given we used 16s.  I have provided two examples of the sequence in question here: 

ATGCAATCCCCATTCTAGAAAAGAACTATATTGCAACATGTAGGTTGTCTATGGCTACAGACACAGGTTAACGTAATTGCGCTGTCACTACTAGAACGTTTACCGCCTCTTAACATTCTAGTAGGGCTTGTATGACCGCACTATTGATCGTTATCTGCAATGTGGCTATGGCATACTATACTGAATGATATATATTCGTTATCACTGCTGATTTGTTTATCGCTTATAAAACATTTTAGCAGGGCCTGTACGATAGCGCTATATATTGTCATTTGCAATGCAA

CATCTGATGCAATCCCCATTCTAGAAAAGAACTATATTGCAACATGTAGGTTGTCGATGGCTACAGACACAGATTAACGTAATTGCGCTGTCACTACTAGAACGTTTACCGCCTCTTAACGTTCTGGTAGGGCCTGTATGACCGCGCTATTGATCGTTATCTGCAATGTGACTATGGCATACTATACTGAATGACATATATTCGTTATCACTGCTGATTTGTTTATCGCTCATAAAACATTTTAGCAGGGCCTGTATGATAACGCTATATATTGTCATTTGCAATG

Is there anything you could think of that could lead to this? (sorry for the double question)

**Comment by benjjneb** [comment]
Thanks, one last request, what are the abundances of the post-trimming (forward) reads? I.e. the same ones you posted 10 sequences from above.

**Comment by JakeBrit** [comment]
I apologise for the delay, I've been attempting to calculate the abundances for the post-trimming reads for the 10 sequences above but I'm not sure exactly how to do so. Would you be able to provide any guidance on this so I can get this to you as soon as possible.

Thank you so much,
Jake

**Comment by benjjneb** [comment]
```
unq <- getUniques("path/to/example_post_trim.fastq"). # Values are abundances, names are the sequences
unq[1:10]
```

**Comment by JakeBrit** [comment]
Thank you so much here is the results below: It appears the results vary from the sequences I supplied above but are from the sample file A107_F_filt.fastq (there must have been something wrong with my previous code) so I have also BLAST search these sequences just in case. 

ACGTCTGGTTCAGGGTTGTTTATAAATACTACAATGTGGCCTGTTACATTGTTTGTCGAATGGCGCTTTCATTCATTTGAAATCCCCATTCTAGAAAAGAAGCATATTGCAACATGTATGTTGACTATGCCTTAAGAAGAAGTGAACGCGTTGTTACTGCTGGATCGTTTAATGCCTGTTAACAATCCAGCGGGGCCTGATGACAGCGCTTCGTTATCTGATTTGGCTAT 
                                                                                                                                                                                                                                   616 
ACGTCTGGTTCAGGGTTGTTTATAAATACTACAATGTGGCCTGTTACATTGTTTGTCGAATGGCGCTTGCATTCATTTGCGATCCCCATTCTAGAAAAGAAGCATATTGCAACATGTATGTTAGTTGTGCCTCAAGAACAGAAGTGAATGCGTTGTTACTGCCGAAACGTTTAATGCCTGTTAACGTTCCGGTGGGGGCCTGATGACAATGCTTCGTTATCTGATTTGGC 
                                                                                                                                                                                                                                   454 
TACGTCTGGTTCAGGGTTGTTTATAAATACTACAATGTGGCCTGTTACATTGTTTGTCGAATGGCGCTTTCATTCATTTGAAATCCCCATTCTAGAAAAGAAGCATATTGCAACATGTATGTTGACTATGCCTTAAGAAGAAGTGAACGCGTTGTTACTGCTGGATCGTTTAATGCCTGTTAACAATCCAGCGGGGCCTGATGACAGCGCTTCGTTATCTGATTTGGCTA 
                                                                                                                                                                                                                                   327 
ACGTCTGGTTCAGGGTTGTTTATAAATACTACAATGTGGCCTGTTACATTGTTTGTCGAATGGTGCTTTCATTCACTTGAGATCCCCATTCTAGAAAAGAAGCATATTGCAACATGTATGTTGGCTATGCCTTAAGAACAGAAATGAATGCGTTGTTACTGCTGGGTCGTTTAATGCCTGTTAACGTTCCAGTGGGGCCTGATGACAGCGCTTCGTTATCTGATTTGGCT 
                                                                                                                                                                                                                                   312 
ACGTCTGGTTCAGGGTTGTTTATACGTACTACAATGTGGCCTGTAACATTGTTTGTCGAATGGTGCTTGCAATTCTGCAATCCCCGTTCTAGAAAAGAAGCATATTGCAACATGTACGTTGGTTATGGTTTGCAAAACAGAATAACGTAAGTTCGTTGTCGATACTAGATTGTTTACCGCCTGCTAACGATCTAGTAGAGCTTGATGACAACGTTCTTTACTGTTGTTTC 
                                                                                                                                                                                                                                   304 
ACGTCTGGTTCAGGGTTGTTTATAAATACTACAATGTGGCCTGTTACATTGTTTGTCGAATGGCGCTTGCATTCATTTGCGATCCCCATTCTAGAAAAGAAGCATATTGCAACATGTATGTTAGTTGTGCCTCAAGAACAGAAGTGAATGCGTTGTTACTGCCGAAACGTTTAATGCCTGTTAACGTTCCGGTGGGGACCTGATGACAATGCTTCGTTATCTGATTTGGC 
                                                                                                                                                                                                                                   281 
TACGTCTGGTTCAGGGTTGTTTATAAATACTACAATGTGGCCTGTTACATTGTTTGTCGAATGGCGCTTGCATTCATTTGCGATCCCCATTCTAGAAAAGAAGCATATTGCAACATGTATGTTAGTTGTGCCTCAAGAACAGAAGTGAATGCGTTGTTACTGCCGAAACGTTTAATGCCTGTTAACGTTCCGGTGGGGGCCTGATGACAATGCTTCGTTATCTGATTTGG 
                                                                                                                                                                                                                                   263 
ACGTCTGGTTCAGGGTTGTTTATAAATACTACAATGTGGCCTGTTACATTGTTTGTCGAATGGCGCTTGCATACATTTGCAGTCCCCATTTTAGAGAAGAAGCATATTGCAACATGTATGTTGGCGATGCCTTACGAACAGAATGAATGCGTTGTTACTACTGGATTGTTTAATGCCTTTTAACATTCCGGTGGGGCCTGATGACAAAGCTTCGTTATCTGATTTGGCTA 
                                                                                                                                                                                                                                   240 
ACGTCTGGTTCAGGGTTGTTTATAAATACTACAATGTGGCCTGTTACATTGTTTGTCGAATGGCGCTTTCATTCATTTGAAATCCCCATTCTAGAAAAGAAGCATATTGCAACATGTATGTTGACCATGCCTTAAGAAGAAGTGAACGCGTTGTTACTGCTGGATCGTTTAATGCCTGTTAACAATCCAGCGGGGCCTGATGACAGCGCTTCGTTATCTGATTTGGCCAT 
                                                                                                                                                                                                                                   196 
ACGTCTGGTTCAGGGTTGTTTATATATACTACAATGTGGCCTGTTACATTGTTTGTCGAATGGCGCTTGCATCTGATGCAATCCCCATTTTAGAAAAGAACTATATTGCAACATGTATGTTGTCTATGGCTACAGACACAGATTAACATAATTGCGCTGTCACTATTAGAACGTTTACCGCCTGCTAACGTTCTAGTAGAGCCTGTATGACTGCGCTATTGATCGTTATC 
                                                                                                                                                                                                                                   160 

BLAST results:

Sequence 1: Cylicodontophorus bicoronatus internal transcribed spacer 1, partial sequence; 5.8S ribosomal RNA gene, complete sequence; and internal transcribed spacer 2, partial sequence
Sequence 2:Cylicocyclus auriculatus isolate Cau2 internal transcribed spacer 1, partial sequence; 5.8S ribosomal RNA gene, complete sequence; and internal transcribed spacer 2, partial sequence
Sequence 3: Cylicodontophorus bicoronatus internal transcribed spacer 1, partial sequence; 5.8S ribosomal RNA gene, complete sequence; and internal transcribed spacer 2, partial sequence
Sequence 4: Cylicostephanus longibursatus voucher Unknown_11 5.8S ribosomal RNA gene and internal transcribed spacer 2, partial sequence
Sequence 5: Parapoteriostomum euproctus isolate Paeu1 internal transcribed spacer 1, partial sequence; 5.8S ribosomal RNA gene, complete sequence; and internal transcribed spacer 2, partial sequence
Sequence 6:Cylicocyclus auriculatus isolate Cau2 internal transcribed spacer 1, partial sequence; 5.8S ribosomal RNA gene, complete sequence; and internal transcribed spacer 2, partial sequence
Sequence 7:Cylicocyclus auriculatus isolate Cau2 internal transcribed spacer 1, partial sequence; 5.8S ribosomal RNA gene, complete sequence; and internal transcribed spacer 2, partial sequence
Sequence 8: Coronocyclus labratus isolate LBR_G_f_01 5.8S ribosomal RNA gene, partial sequence; internal transcribed spacer 2, complete sequence; and 28S ribosomal RNA gene, partial sequence
Sequence 9:Cylicodontophorus bicoronatus internal transcribed spacer 1, partial sequence; 5.8S ribosomal RNA gene, complete sequence; and internal transcribed spacer 2, partial sequence
Sequence 10: Skrjabinodentus caragandicus isolate Skca1 internal transcribed spacer 1, partial sequence; 5.8S ribosomal RNA gene, complete sequence; and internal transcribed spacer 2, partial sequence

These sequences are all nematode sequences. 

Thank you so much for your time and help. If there is anything else you need please let me know. 

Best,
Jake

P.S we have recently found out that the V3 600 cycle miseq flowcell which was used for this run had expired by a 2-3 months, could this have caused high artefact penetration?

**Comment by benjjneb** [comment]
> P.S we have recently found out that the V3 600 cycle miseq flowcell which was used for this run had expired by a 2-3 months, could this have caused high artefact penetration?

I think it's more likely that the primers you are using have a high cross-reactivity with nematode DNA.
