### ISSUE TITLE
assigning genus and species level information for Muribaculaceae family

### ISSUE THREAD

**Issue by saifsikdar** [benjjneb/dada2#1107]
Hi @joey711 
Thank you for your nice tutorial. I am curious if you have any plan to add further taxonomic classification to the Muribaculaceae family soon. I followed your taxonomy assignment designed based on the Silva database. I found the family Muribaculaceae very interesting. I have seen a limited number of papers described this family. Could you please suggest how can I add genus or species level information to this family?

**Comment by benjjneb** [comment]
> Could you please suggest how can I add genus or species level information to this family?

Once I've narrowed down to a small number of ASVs of interest (in this case perhaps those assigned to the Muribaculaceae family) I've often found by-hand inspection of the matches of those ASVs to known taxa via BLAST againt the nt database to be very helpful.

I usually just use the web interface for this part, and exclude uncultured/environmental samples (as they typically don't have good names): https://blast.ncbi.nlm.nih.gov/Blast.cgi?PROGRAM=blastn&PAGE_TYPE=BlastSearch&LINK_LOC=blasthome

**Comment by saifsikdar** [comment]
Thank you!
