### ISSUE TITLE
Parallelization failing on Amazon Linux 2

### ISSUE THREAD

**Issue by madkinsz** [benjjneb/dada2#1110]
Hi! This is a cross-post of the issue at https://github.com/RcppCore/RcppParallel/issues/128 because I noticed the lack of parallelization in dada2 and have gotten to the point where I am testing the `RcppParallel` dependency manually to try to identify the issue. Basically: dada2 is not running multiple threads on EC2.

I'm hoping this is useful to anyone else who encounters the issue and that perhaps someone here can provide some guidance. Is anyone else encountering this? If not, how did you install dada2 on your AWS environment? Should I consider moving dada2 into a docker image with a different base than amazon linux?

Thanks! 

-- If this does not fit here I will certainly not be offended if it is closed.

**Comment by benjjneb** [comment]
Thanks for the report. I'm not sure we can do much about it, we entirely depend on RcppParallel's implementation of multi-threading, but I'll be following that issue.

**Comment by madkinsz** [comment]
For reference, this was an issue with the May Amazon Linux 2 release and has been resolved in a later patch. I'm still not sure what the source was, but upgrading is a viable solution.
