### ISSUE TITLE
Trimming variable length primers

### ISSUE THREAD

**Issue by Freemacl** [benjjneb/dada2#1111]
My reads are the V3/V4 region of 16S, sequenced by a service provider. They demultiplexed the data but did not remove adapters or primers. They used staggered primers (see sequences below), to increase the base diversity on the flowcell. CS1 and CS2 are the tags used to incorporate the index and Illumina sequencing adapters. The library was sequenced with MiSeq Reagent Kit v3 600 cycles from Illumina with LNATM modified custom primers (Exiqon):
 
Primer read1: LNA-CS1: ACACTGACGACATGGTTCTACA
Primer read2: LNA-CS2: TACGGTAGCAGAGACTTGGTCT
Primer index read: LNA-CS2rc: AGACCAAGTCTCTGCTACCGTA
 
Primers used for amplification of v3v4 16S region:
341FP1-CS1	**ACACTGACGACATGGTTCTACA**CCTACGGGNGGCWGCAG
341FP2-CS1	**ACACTGACGACATGGTTCTACA**TCCTACGGGNGGCWGCAG
341FP3-CS1	**ACACTGACGACATGGTTCTACA**ACCCTACGGGNGGCWGCAG
341FP4-CS1	**ACACTGACGACATGGTTCTACA**CTACCTACGGGNGGCWGCAG
 
805RP1-CS2	**TACGGTAGCAGAGACTTGGTCT**GACTACHVGGGTATCTAATCC
805RP2-CS2	**TACGGTAGCAGAGACTTGGTCT**TGACTACHVGGGTATCTAATCC
805RP3-CS2	**TACGGTAGCAGAGACTTGGTCT**ACGACTACHVGGGTATCTAATCC
805RP4-CS2	**TACGGTAGCAGAGACTTGGTCT**CTAGACTACHVGGGTATCTAATCC

Since the adapter/primers used for sequencing here are varying lengths, what would be the right approach for trimming?

Right now I am using 
`filterAndTrim(fnFs, filtFs, fnRs, filtRs, trimLeft=c(22, 22), truncLen=c(270,280),maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE, multithread=FALSE)`
But I am worried that this trimming is not stringent enough because I am getting a pretty huge number of ASVs for a not overly complex environment. Before I realized the adapter/primer sequencers were still in the reads, I ran into the chimera issue you have described in the documentation, and adding 'trimLeft=c(22, 22)' at least solved that. Additionally, after trimming I am getting the bimodal distribution of lengths (peaks around 398 and 418), so I think I am at least on the right track. Should I expand the trimming value to cover the entire length of the longest sequences displayed above? e.g. 'trimLeft=c(42,46)'?

Thank you for any guidance you can provide.

**Comment by termithorbor** [comment]
You can use cutadapt like it is done in the ITS example: https://benjjneb.github.io/dada2/ITS_workflow.html
