### ISSUE TITLE
No length warning lernErrors ITS

### ISSUE THREAD

**Issue by termithorbor** [benjjneb/dada2#1112]
Hi all,

I do not recieve this Warning "Not all sequences were the same length" when running the lernErrors function on my ITS fungal samples. Is this normal because when I check sequence distribution in the end I end up with something like this:

77   79   89   90   99  101  108  111  116  117  119  121  129  132  138  147  148  150  158  159  160  162  165  166  167 
   1    2    1    1    1    2    1    2    1    1    1    1    1    1    1    1    2    1    2    2    1    1    2    1    2 
 170  171  173  177  178  182  195  198  201  203  204  205  206  208  212  213  215  216  217  219  221  223  224  226  228 
   1    2    2    1    1    1    1    1    1    1    1    1    1    3    1    2    1    1    1    1    1    2    2    3    1 
 230  233  234  235  237  238  239  240  241  242  243  244  245  246  247  248  249  250  251  252  253  254  256  257  258 
   3    1    3    4    2    2    6    1    4    6    6    3    2    3    4    2    3    1    2    7    2    1    6    6    9 
 259  260  261  262  263  264  265  266  267  268  269  270  271  272  273  274  275  276  277  278  279  280  281  282  283 
   7    4    8    4    3    4    5    5    5    2    6    5    3   10   12   14    9    7   11   10   33  142  281 1102 2772 
 284  286  291  296  297  298  299  300  301 
  23    1    1    1    1    2    1    9   49

Thanks in advance for your help :)

**Comment by benjjneb** [comment]
Yes that's normal, we removed that warning a release or two ago, as the `dada(...)` algorithm handles (biological) length variation fine these days.
