### ISSUE TITLE
Different results for dadaFs on two different machines

### ISSUE THREAD

**Issue by termithorbor** [benjjneb/dada2#1113]
Hi all,

when running the dada function on a Windows laptop and on a Ubuntu server I get slightly different results when using the same data (the corrosponding sequence tables made by makeSequencetable) have a slightly different distribution.

Any ideas why that is happening?

Many thanks in advance :)

**Comment by benjjneb** [comment]
Did you include any stochasticity in the processing? For example `learnErrors(..., randomize = TRUE)`?
Are the package versions exactly the same between the two machines? `packageVersion("dada2")
Is the exact same code being executed on each?

**Comment by termithorbor** [comment]
I just used errF <- learnErrors(filtFs, multithread=TRUE) and the versions are both 1.16. I also used derepFastq before using the dada function. 
Within each machine the sequence length distribution is always the same. The difference is only between the machines and I run the exact same code on both of them.

**Comment by termithorbor** [comment]
Tried it again today and somehow there is no difference anymore - must have been a goblin involved or something :D
