### ISSUE TITLE
plotqualityprofile - grayscale heatmap issue

### ISSUE THREAD

**Issue by chongchunwie** [benjjneb/dada2#1114]
I have tried to generate quality plots of  raw fq files. However, the background grayscale heatmap is not aligned properly. I have never have this issue before. What might be causing this? Appreciate if there is any solution. 

Thank you. 

Regards,
Chun Wie
![Rplot01](https://user-images.githubusercontent.com/40225749/91863139-5ea54280-eca1-11ea-814e-2ccd1831b680.png)

**Comment by benjjneb** [comment]
My suspicion is that the underlying data has binned quality scores, i.e. only a very small number of quality scores are used. What Illumina sequencing technology are you using?

You can also just open one of the fastq files and look at the quality scores. Are they all from a very small set of characters?

**Comment by chongchunwie** [comment]
Hi, it was sequenced using novaseq. Yes, the quality scores are generally all "F". Is there a way for me to get the "unbinned" quality scores?

**Comment by and3k** [comment]
Here is the documentation on NovaSeq quality scores, which are all binned: https://emea.illumina.com/content/dam/illumina-marketing/documents/products/appnotes/novaseq-hiseq-q30-app-note-770-2017-010.pdf. I don’t think there is a way to get unbinned quality scores with NovaSeq.

Also check out #791.

**Comment by csmiguel** [comment]
Hi, I created a code for visualizing binned quality data from NovaSeq as an alternative to plotQualityProfile from dada2.

First, a function to read and tidy quality data:
```r
tidy_qual <- function(dirpath = NULL, pattern = NULL, nsubsample = NULL) {
  #tidy quality data for multiple files
  # dirpath, is the path to the folder with the fastq files
  # pattern, the pattern used for selecting the files in the directory and for extracting the sample name
  library(stringr)
  allfiles <- dir(dirpath, full.names = T, pattern = pattern)
  if(is.numeric(nsubsample))
    allfiles <- sample(allfiles, nsubsample)
  allfiles %>%
  lapply(function(x){
    sname <- stringr::str_extract(x,
                                  pattern)
    Rsubread::qualityScores(x,
                            nreads = 10000) %>%
      t() %>%
      as.data.frame %>%
      tibble::rownames_to_column(var = "cycle") %>%
      reshape2::melt(id.vars = "cycle", value.name = "quality") %>%
      dplyr::select(cycle, quality) %>%
      filter(!is.na(quality)) %>%
      dplyr::group_by(cycle, quality) %>%
      summarise(countn = n()) %>%
      group_by(cycle) %>%
      summarise(total = sum(countn), quality, countn) %>%
      mutate(prop = countn/total,
             cycle = as.numeric(cycle),
             readName = sname) %>%
      select(-total)
  }) %>%
  do.call(what = "rbind")
  }
```
Secondly, few lines to plot quality data:


```r
library(dplyr)
library(Rsubread)
library(ggplot2)


# tidy quality data from multiple fastq files
qualITSR1 <-
  tidy_qual(dirpath = "data/intermediate/", pattern = "ITS.*_R1")
# plot data
my_breaks <- c(0.1, 0.5, 0.9)

ggplot(qualITSR1) +
  geom_tile(aes(x = cycle, y = as.factor(quality), fill = prop)) +
  scale_fill_gradient(name = "Proportion",
                      # trans = "log",
                      breaks = my_breaks,
                      labels = my_breaks,
                      low = "red", high = "green") +
  facet_wrap(~readName) +
  ylab("NovaSeq binned quality") +
  xlab("cycle") +
  theme_classic()
```
![example](https://user-images.githubusercontent.com/12279367/161957826-a8a82872-336b-4125-862a-fc1a31220c3e.png)
