### ISSUE TITLE
DADA2 installation issues

### ISSUE THREAD

**Issue by lbegona** [benjjneb/dada2#1116]
Hello!

I have been trying to install DADA2 package in R studio (v 4.0.2), following the installation guidelines from GitHub. I have tried both to install it from source and from Bioconductors. It seems like it works fine but then when I try to load the package it gives me the following error message:

"Error: package or namespace load failed for ‘dada2’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘GenomeInfoDbData’"

Obviously I have tried downloading "GenomeInfoDbData" using Bioconductor, but it also gives me the error that: installation of package ‘GenomeInfoDbData’ had non-zero exit status, or alternative that his package is not available for my R version.

I need to use DADA2 for my NGS data analysis pipeline and it is frustrating me a lot not to be able to get it so any help would be greatly appreciated!!!

THANKS

**Comment by termithorbor** [comment]
Have you tried installing GenomeInfo from source using the tar.gz? Are there any other errors while installing? Sometimes you will see that installation stops because other packages are missing - just check every step of the installation process to make sure nothing else is missing.
