### ISSUE TITLE
Unusual quality profile plots

### ISSUE THREAD

**Issue by razz1618** [benjjneb/dada2#1117]
Is this a normal plot. The black-gray map doesn't looks like other plots I got in dada2 (previous analysis). 
[XL001.1.raw.R1.fq.qual.pdf](https://github.com/benjjneb/dada2/files/5163026/XL001.1.raw.R1.fq.qual.pdf).
![capture-20200902-225007](https://user-images.githubusercontent.com/59241611/91999252-c4133500-ed6e-11ea-82d6-7b7bbdd7c8df.png)

**Comment by benjjneb** [comment]
You have binned quality scores (perhaps NovaSeq?), so... yes.

With binned quality scores, only very few (~3-8) quality scores are used, and this is the kind of plot you therefore see.

**Comment by razz1618** [comment]
Thanks. Is it ok to proceed with DADA2 normally with such sequences or does it require modifying DADA2 steps?

**Comment by benjjneb** [comment]
You should be fine.

**Comment by razz1618** [comment]
Thanks.
