### ISSUE TITLE
How to extract taxonomy tables as .txt files or .csv files after finishing?

### ISSUE THREAD

**Issue by Ravivemuri9** [benjjneb/dada2#1118]

**Comment by benjjneb** [comment]
If you are saving them to look at in R again, DON'T write them out as csv/txt files. Instead store them as RDS objects with `saveRDS`/`readRDS`.

That said, if you are writing them out for use in another program, use the `write.table` or `write.csv` base R functions for that purpose. I recommend at least quickly perusing the docs on those functions first though, e.g. `?write.csv`.

**Comment by Ravivemuri9** [comment]
Thank you for your help. 
However, I'm still unable to figure out to export my phylum. if I execute the following commands, the table reflects on console, but not providing me option to export to my computer. Alternatively, can I export it as a .biom file? If possible? Thank you again.

`write.table(taxa_abundance_table_phylum)`
`write.csv(taxa_abundance_table_phylum)`

**Comment by benjjneb** [comment]
```
?write.table
```

> Data Output
> Description
> write.table prints its required argument x (after converting it to a data frame if it is not one nor a matrix) to a file or connection.
> 
> Usage
> write.table(x, file = "", append = FALSE, quote = TRUE, sep = " ",
>             eol = "\n", na = "NA", dec = ".", row.names = TRUE,
>             col.names = TRUE, qmethod = c("escape", "double"),
>             fileEncoding = "")
> 
> write.csv(...)
> write.csv2(...)
>
> Arguments
> x	
> the object to be written, preferably a matrix or data frame. If not, it is attempted to coerce x to a data frame.
> 
> **file**	
> **either a character string naming a file or a connection open for writing. "" indicates output to the console.**
> 
> ...

**Comment by Ravivemuri9** [comment]
Thank you very much. I got it now.
