### ISSUE TITLE
Unable to add Species with Silva 138

### ISSUE THREAD

**Issue by awe421** [benjjneb/dada2#1119]
Hi,

I have been working for the first time with the dada2 pipeline and have no experience with working in Rstudio. 
As my reads were not merging properly I played around a bit with the trim&filter and tried out working with only forward reads and the JustConcatenate function. 
I assigned taxonomy to the forward reads with the zipped database from Silva, as I was unable to unpack the zipfile on my macbook.
When I arrived at the addSpecies part, it gave me the following error: "Error in assignSpecies(seqs, refFasta = refFasta, allowMultiple = allowMultiple,   : Incorrect reference file format for assignSpecies (this looks like a file formatted for assignTaxonomy). 

I tried unzipping but this does not work. Is there another way to use the species database?

Thank you in advance!

**Comment by and3k** [comment]
Hi @awe421!

I have used the SILVA database gzipped and unzipped before, so both should work.

from the error message, it looks like you used the reference file for assignTaxonomy and not the reference file for addSpecies/assignSpecies. Those are two different files, which are differently formatted. For `addSpecies` you should use `silva_species_assignment_v138.fa.gz`.

See also https://benjjneb.github.io/dada2/training.html

Best,
Bela

**Comment by awe421** [comment]
Dear @and3k 

Thank you for your quick response. Indeed I downloaded the taxonomy-with-species file instead of the species-assignment.
Thank you very much for your help!
