### ISSUE TITLE
MAX_CONSIST and Early Termination Question

### ISSUE THREAD

**Issue by gblanchard4** [benjjneb/dada2#112]
I often have to change the `MAX_CONSIST` value higher than the default of 10 for my reverse reads (MiSeq 16S data)  and have a few questions about it.

1. Most of the time my data will reach convergence by cycle 15 or so, but if I can't reach convergence in 10 cycles, should I go back and refilter my data with more stringent parameters?

2. Since we may not be able to reach convergence with a default value or even a higher value and have to start the lengthy process all over with a higher `MAX_CONSIST`, is there a problem setting  `MAX_CONSIST=9999`?  Or possible adding a kwarg option for it to use as many cycles as needed to reach convergence. 

Best, 
Gene Blanchard

**Comment by benjjneb** [comment]
Hi Gene,

Refiltering isn't necessary. Higher diversity and lower-quality data takes a bit longer to converge, which is probably what you are experiencing.

It's completely reasonable to set a higher MAX_CONSIST from the get-go if you expect this for your data. I'm not sure I would go straight to `9999`, but setting `MAX_CONSIST=30` for your reverse reads might make sense.

Also, you can save the error rates from a `dada-class` object that stopped prior to convergence, and then use those error rates as the starting point for a new `dada` call (keeping the benefit of the computation time):

```{r}
dd <- dada(..., selfConsist=TRUE)
# Stopped at MAX_CONSIST=10 prior to convergence

err.10 <- dd$err_out
# err.10 <- dd[[1]]$err out if running multiple samples
dd2 <- dada(..., err=err.10, selfConsist=TRUE)
```

ps. If computation time is an issue, I recommend taking a look at our [workflow for big datasets](http://benjjneb.github.io/dada2/bigdata.html), and the multithreading introduced in the 1.1 version of the package. Can speed things up greatly.

**Comment by gblanchard4** [comment]
Thanks for the clarification and the handy tip on saving the error rates!  That is exactly what I was looking for.
