### ISSUE TITLE
assignTaxonomy, what is the cutoff used for classification ?

### ISSUE THREAD

**Issue by sankadinesh** [benjjneb/dada2#1123]
Hi There,
Mothur uses default cutoff that is set at 80. What is the default cutoff used in DADA2 ?
I generated ASVs using DADA2 and performed classification in DADA2 using nifH database. I also performed classification using same ASVs in MOTHUR (classify.seqs, cutoff=89) using same nifH database. I used inbuilt **assignTaxonomy** in DADA2. 

The percentage of reads classified and taxonomic diversity was higher in DADA2 compared to MOTHUR. I would like to know the reason since both use same naive bayesian algorithm. Please help me.

Regards,
Dinesh

**Comment by benjjneb** [comment]
You can see the key parameter settings in the help text for the fuction: `help("assignTaxonomy")` or shorthand `?assignTaxonomy`.

The default `minBoot` parameter is 50.
