### ISSUE TITLE
Escherichia/Shigella species level classificaiton missing with version 2 of the SILVA release

### ISSUE THREAD

**Issue by nr0cinu** [benjjneb/dada2#1124]
Hi!

I upgraded the SILVA taxonomy reference from version 1 (10.5281/zenodo.3731176) to version 2 (10.5281/zenodo.3986799), which generally improved the classification. However, I noticed that that Escherichia/Shigella does not get classified at species level any more:

version 1 results:
- Genus: Escherichia/Shigella
- Species: albertii/boydii/coli/dysenteriae/fergusonii/flexneri/marmotae/sonnei

version 2  results:
- Genus: Escherichia-Shigella
- Species: NA

I guess this is because the dash got replaced by a hypen? I use `allowMultiple = TRUE` in `addSpecies()`.

Thanks!

Best,
Bela

PS: this is the sequence in question: `TGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTATGAAGAAGGCCTTCGGGTTGTAAAGTACTTTCAGCGGGGAGGAAGGGAGTAAAGTTAATACCTTTGCTCATTGACGTTACCCGCAGAAGAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATCTGATACTGGCAAGCTTGAGTCTCGTAGAGGGGGGTAGAATTCCAGGTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACGAAGACTGACGCTCAGGTGCGAAAGCGTGGGGAGCAAACA`

**Comment by termithorbor** [comment]
I also noticed that some sequences which got classified to a genus before are now only classified to family. For example:


Bacillaceae__Bacillus__longiquaesitum__TAGGGAATCTTCCGCAATGGACGAAAGTCTGACGGAGCAACGCCGCGTGAGTGATGAAGGTTTTCGGATCGTAAAACTCTGTTGTTAGGGAAGAACAAGTACGAGAGTAACTGCTCGTACCTTGACGGTACCTAACCAGAAAGCCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCAAGCGTTGTCCGGAATTATTGGGCGTAAAGCGCGCGCAGGCGGTCCTTTAAGTCTGATGTGAAAGCCCACGGCTCAACCGTGGAGGGTCATTGGAAACTGGGGGACTTGAGTGCAGGAGAGAAGAGTGGAATTCCACGTGTAGCGGTGAAATGCGTAGAGATGTGGAGGAACACCAGTGGCGAAGGCGACTCTTTGGCCTGTAACTGACGCTGAGGCGCGAAAGCGTGGGGAGCAAACA

Is now only 


Bacillaceae__NA__NA__TAGGGAATCTTCCGCAATGGACGAAAGTCTGACGGAGCAACGCCGCGTGAGTGATGAAGGTTTTCGGATCGTAAAACTCTGTTGTTAGGGAAGAACAAGTACGAGAGTAACTGCTCGTACCTTGACGGTACCTAACCAGAAAGCCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCAAGCGTTGTCCGGAATTATTGGGCGTAAAGCGCGCGCAGGCGGTCCTTTAAGTCTGATGTGAAAGCCCACGGCTCAACCGTGGAGGGTCATTGGAAACTGGGGGACTTGAGTGCAGGAGAGAAGAGTGGAATTCCACGTGTAGCGGTGAAATGCGTAGAGATGTGGAGGAACACCAGTGGCGAAGGCGACTCTTTGGCCTGTAACTGACGCTGAGGCGCGAAAGCGTGGGGAGCAAACA

**Comment by benjjneb** [comment]
> I guess this is because the dash got replaced by a hypen? I use allowMultiple = TRUE in addSpecies().

Darn. Thank you for reporting this! Yes... there was previously special reformatting of `Escherichia-Shigella` (Silva-formatting) to `Escherichia/Shigella` (DADA2 formatting), but I forgot to move it over to the new digestion script. Marking as bug.

**Comment by benjjneb** [comment]
@termithorbor With the new digestion of Silva that keeps a larger number of Bacteria/Archaea reference sequences, there will be cases in which some ASVs are assigned at a lower level as you observed in this specific case. This is because a closely-related reference sequences from a different e.g. genus is now kept in the DADA2 reference, whereas before it was removed.

**Comment by termithorbor** [comment]
Okay but I do not get why it is only Bacillaceae now and before it was Bacillaceae__Bacillus__longiquaesitum.
