### ISSUE TITLE
dada2 error function for filtered data re-inpu

### ISSUE THREAD

**Issue by CarlaCristinaUranga** [benjjneb/dada2#1126]
Hi,

I am using dada2 for 16s sequencing and obtained my results. However, I removed all sequences that only assigned to the Kingdom level and created a new test fastq out of the remaining sequences. However, this added quality scores of 40 artificially to the data. I was able to run the dada2 pipeline again with this test fastq but had to adjust the error function with USE_QUALS=FALSE because I got an error with the loess error function. Is this a valid approach?

**Comment by benjjneb** [comment]
> However, I removed all sequences that only assigned to the Kingdom level and created a new test fastq out of the remaining sequences. However, this added quality scores of 40 artificially to the data.

No, don't do this. 

Why not just remove the Kingdom-only ASVs from the final table? Otherwise, remove those sequences from the fastq file (thereby keeping the real quality scores).

**Comment by CarlaCristinaUranga** [comment]
Ok. Thank you! How would I remove these sequences from the original fastq
files?

Best wishes,
Carla

**Comment by benjjneb** [comment]
You're going to need to tell me more about what processing you are doing. Are you using the dada2 package? How? How are you defining these "Kingdom-only" sequencing reads?

**Comment by CarlaCristinaUranga** [comment]
So I am using the dada2 R package because of the freedom and flexibility in
setting parameters. I am running our 16s data using the Silva, RDP and HOMD
databases successfully, but get a lot of Kingdom-only sequences that, when
run through blast, turn out to be Eukaryotic. So we want to remove these
and re-run filtered our sequences using dada2, since the literature reports
its superior precision, but we want to try qiime2 as well, but without
these eukaryotic sequences, with the hope of improving identification
precision.


Best,
Carla

**Comment by benjjneb** [comment]
OK, can you post the dada2 R code you are using (and packge version)? 
The posted code should go from reading in the sequences to assigning the taxonomy.

**Comment by CarlaCristinaUranga** [comment]
Thank you here is the code:

path <- "~/Desktop/16s/CLOTS"
list.files(path)
fnFs <- sort(list.files(path, pattern="_R1_001.fastq", full.names = TRUE))

# Extract sample names, assuming filenames have format: SAMPLENAME_XXX.fastq
sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)

plotQualityProfile(fnFs[1:4])

filtFs <- file.path(path, "filtered", paste0(sample.names,
"_F_filt.fastq.gz"))

out <- filterAndTrim(fnFs, filtFs, truncLen=100,
                     maxN=0, maxEE=2, truncQ=2, rm.phix=TRUE,
                     compress=TRUE, multithread=TRUE)

errF <- learnErrors(filtFs, multithread=TRUE)

plotErrors(errF, nominalQ=TRUE)

derepFs <- derepFastq(filtFs, verbose=TRUE)
names(derepFs) <- sample.names

dadaFs <- dada(derepFs, err=errF, pool=TRUE, multithread=TRUE)

seqtabF <- makeSequenceTable(dadaFs)
dim(seqtabF)
table(nchar(getSequences(seqtabF)))
seqtab.nochimF <- removeBimeraDenovo(seqtabF, method="consensus",
multithread=TRUE, verbose=TRUE)
dim(seqtab.nochimF)
sum(seqtab.nochimF)/sum(seqtabF)

otu_valuesF<-t(seqtab.nochimF)
otuF<-dplyr::as_data_frame(otu_valuesF, rownames = "sequence")

getN <- function(x) sum(getUniques(x))
track1 <- cbind(out, sapply(dadaFs, getN), sapply(dadaFs, getN),
rowSums(seqtab.nochimF))
colnames(track1) <- c("input", "filtered", "denoisedF", "denoisedR",
"merged", "nonchim")
rownames(track1) <- sample.names
head(track1)

taxaHOMDF <- assignTaxonomy(seqtab.nochimF,
"~/Desktop/16s/blastdb/dada2HOMD_db.fasta", tryRC=TRUE, multithread=TRUE)

taxaRDPF <- assignTaxonomy(seqtab.nochimF,
"~/Desktop/16s/fastq/RefSeq-RDP16S_v2_May2018.fa.gz", tryRC=TRUE,
multithread=TRUE)

taxaSilva138F <- assignTaxonomy(seqtab.nochimF,
"~/Desktop/16s/fastq/silva_nr_v138_train_set.fa.gz", tryRC=TRUE,
multithread=TRUE)
taxaSilva138F <- addSpecies(taxaSilva138F,
"~/Desktop/16s/fastq/silva_species_assignment_v138.fa.gz")

**Comment by CarlaCristinaUranga** [comment]
Sorry to bother you I know how to remove these sequences from the original
fast files.

Best

Carla

**Comment by benjjneb** [comment]
> Sorry to bother you I know how to remove these sequences from the original
fast files.

You are good to go? That is, can we close this issue?

**Comment by CarlaCristinaUranga** [comment]
Yes! Thank you for your patience!

Carla
