### ISSUE TITLE
Merging OTU and Taxonomy Tables

### ISSUE THREAD

**Issue by siuguy** [benjjneb/dada2#1128]
Dear all,

I have a question regarding dada2. After analyzing all data, is there a way to export the OTU table having taxonomy (genus/family...) in the columns instead of sequences?

From
                 ACTGACTG     ACTGACTG    ACTGACTG      ACTGACTG
Sample 1       1                        0                     1                           0    
sample 2       1                        3                     2                          3      
Sample 3       1                        0                    1                           0   

To
                 Genus1             Genus2          Genus3               Genus4
Sample 1       1                        0                     1                           0    
sample 2       1                        3                     2                          3      
Sample 3       1                        0                    1                           0   

Thank you!

**Comment by madkinsz** [comment]
Do you want the full taxonomy or just the genus? If the full taxonomy, you'll need to join each row into a single string e.g. Kingdom;Phylum;...Genus. If just the genus, you can just select that column. Then you can assign the resulting string vector to the column names of your OTU table.

**Comment by benjjneb** [comment]
You can do all of this with base R. I'm assuming you have a taxonomy table already, i.e. rows are ASVs and taxonomic levels are columns. To get the last assigned taxonomic level for each ASV:

```
get.last.assigned.taxon <- function(x) { 
  x <- x[!is.na(x)] # Remove NA entries (no assignment made)
  rev(x)[[1]]  # Return last non-NA entry
}
last.taxon <- apply(taxtab, 1, get.last.assigned.taxon)
```

That should get you a vector named by ASV, and with its value being the last assigned taxon.

**Comment by siuguy** [comment]
Awesome, thank you for helping. Just have an additional question.

In the dada2 script, the taxonomy file is named taxa. When I run the following code, it shows an error.

`get.last.assigned.taxon <- function(x) { 
  x <- x[!is.na(x)] # Remove NA entries (no assignment made)
  rev(x)[[1]]  # Return last non-NA entry
}
last.taxon <- apply(taxa, 1, get.last.assigned.taxon)`

> **Error in rev(x)[[1]] : subscript out of bounds**

BTW my taxa file is formatted as follows and it is pretty large ( 45,603 entries x 7 total columns) 

![taxonomy_table](https://user-images.githubusercontent.com/69690046/92788314-751d5f00-f36f-11ea-9360-48db280a2c15.PNG)

Thanks

**Comment by benjjneb** [comment]
Sorry should have used a single bracket to get a graceful NA when the vector is empty:

```
rev(x)[1]  # Return last non-NA entry
```

**Comment by siuguy** [comment]
Great, now it works like a charm. Great work developing and helping us with all these scripts!

Thank you so much!!! :)
