### ISSUE TITLE
Low prevalence for ASVs inferred

### ISSUE THREAD

**Issue by rainbow218** [benjjneb/dada2#1129]
Hi Benjamin,

I would like to seek your advice regarding low prevalence observed for all the ASVs inferred from 250bp PE reads of 16S v4 amplicons of ~1600 stool samples. (prevalence: number of samples in which an ASV appears at least once).
The total number of samples include stool samples from ~700 subjects taken at various time points.
 
Out of 50,001 unique ASVs inferred after chimera removal, 94% of those ASVs have <1% prevalence and the remaining 6% of those ASVs have prevalence ranging from 2-10%.  

I'm wondering if this low level prevalence is due to any missing consideration of the DADA2 pipeline parameter settings.
The settings for each of the steps (dereplication, dada denoising, merging, chimera removal) were the default settings except for merging minOverlap=20 instead of 12.

Here is the information for each of the steps…
Quality of raw reads:

![image](https://user-images.githubusercontent.com/54792999/93014082-891bc780-f5e0-11ea-8311-aa84eba9baad.png)
![image](https://user-images.githubusercontent.com/54792999/93014085-8faa3f00-f5e0-11ea-978f-339ae9847363.png)

Filter and trimming criteria: 
truncQ = 2, minLen = 150, maxEE = 1, truncLen = c(0,150) 

Quality of reads after filter and trimming:
![image](https://user-images.githubusercontent.com/54792999/93014094-a51f6900-f5e0-11ea-8346-e263c6b1d6ba.png)
![image](https://user-images.githubusercontent.com/54792999/93014096-a94b8680-f5e0-11ea-9023-16e275e46b02.png)

summary of read counts at each step:
![image](https://user-images.githubusercontent.com/54792999/93014112-c97b4580-f5e0-11ea-8b66-c14960a53838.png)

summary of unique ASVs at each step:
![image](https://user-images.githubusercontent.com/54792999/93014120-d5ff9e00-f5e0-11ea-9e8e-61ca0ce42624.png)

Greatly appreciate your insight and comments,
Thank you!

**Comment by benjjneb** [comment]
Usually this is because of technical variation in the sequencing data that was not corrected prior to starting the DADA2 pipeline.

IN particular, did your library preparation include any steps which introduce artefactual length variation? This could include "heterogeneity spacers", variable length primers, or variable length barcodes.

**Comment by rainbow218** [comment]
Dear Benjamin,

thank you for your feedback, indeed there were artefactual length variation introduced from BCL to fastq conversion. The prevalence of ASVs improved after the length variation issue was resolved.
