### ISSUE TITLE
dada2:::combineDereps2 with loaded derep objects?

### ISSUE THREAD

**Issue by elsherbini** [benjjneb/dada2#113]
Hi @joey711 , I am trying to use this function for pooling a random sample of samples to do the error inference step.

I am writing out each derep object using saveRDS (the weird syntax for filenames is because I'm using [snakemake](https://bitbucket.org/snakemake/snakemake/wiki/Home) to make my pipeline:

```
derep <- derepFastq("{input.fq}", verbose=TRUE)
saveRDS(derep, "{output.derep}")
```

Then, to do the inference, I am trying the following:

```
 # {input} is the path to derep objects for 20 samples
debug <- sapply(c({input}), readRDS)
saveRDS(debug, "{wildcards.set}.{wildcards.direction}.derep.debug.rds") # save the debug object
drp.learn <- dada2:::combineDereps2(debug)

 dd.learn <- dada(drp.learn, err=NULL, selfConsist=TRUE)
err <- dd.learn[[1]]$err_out
saveRDS(err, "{output.error_matrix}")
```

This gives the error: `Error in dada2:::combineDereps2(debug) : Requires derep-class objects.`

[Here is a link to that rds file of derep objects i tried to write out](https://drive.google.com/file/d/0B8zpZcbxw7kdR3hHbmFGNElQMlE/view?usp=sharing)

They seem to be correct, but don't have the metadata saying they are derep objects, so `combineDereps` flunks them in the `if (!all(sapply(dereps, function(x) class(x) == "derep")))` test.

**Comment by benjjneb** [comment]
Hi Joseph,
I recommend sticking with the supported interface (i.e. no ::: function calls).

The problem here is that the way you have sapply/combined the derep objects has created an invalid object (a matrix of lists). What you need is a list of derep-class objects.

I don't quite follow the snakemake syntax, but in R this would look like:

```
learnFNs <- sample(allFNs, 20) # RDS filenames for the derep-class objects
drp.learn <- lapply(learnFNs, readRDS)
dd.learn <- dada(drp.learn, err=NULL, selfConsist=TRUE)
```

**Comment by elsherbini** [comment]
Yep, changing `sapply` out for `lapply` seems to have worked. 

I think if I want to have the derep step be done on separate nodes, I need to use a function to combine derep objects for the error rate inference step. I am basically useless in R, so very happy that the `combineDereps` object is already implemented. Thanks for your help!

If this works, I'll do a write up on how to use snakemake in combination with dada2, which I think is a good combination for common cluster environments that use either slurm, torque, or PBS.

**Comment by joey711** [comment]
@elsherbini I'm considering composing a docker image that might be helpful for some of this. Let me know if you have any feedback/suggestions. Cluster environments are the expected use case there.
