### ISSUE TITLE
format of pacbio ccs fastq

### ISSUE THREAD

**Issue by anjexq** [benjjneb/dada2#1131]
Hello,

I have bacterial 16S CCS produced  using  PacBio's sequel II and I would like to analyze using dada2. The quality scores for many of the sequences are ~  which is great, but I was told this quality exceeds both Phred+33 and Phred+64 scores which I thought dada2 used. I am wondering if it is possible to work with this data in its current format or if the quality scores needed to be converted/"down-score" into some other standard first. 

Here is an example of the current format my sequences are in;
@m64047_200829_233421/329592/ccs
CACGCACACACGCGCGAGAGTTCGATCATGGTTCAGATTGAATGCTGACGGCGTGGATGAGGCATGCGAGTCGAACGAAGTAGTAGCAATACTACTTAGTGGCGGAAGGGTTAGTAATACATGGGTAACTTGCCTTTAACAGTGGAATAACGGTTGGAAACGACCGCTAATACTACATGTGGTGATACAGGGCATCCTGTACTCATTAAAGTGGGGGATCGTAAGACCTTGCGGTTAAAGAGAGGCCCATGGGATATCAGCTAGTTGGTGTGGTAAAAGCGCACCAAGGCTAAGACGTCTAGGCGGATTGAGAGATTGACCGCCAACACTGGGACTGAGAACTGCCCAGACTCCTACGGGAGGCTGCAGTCGAGAATCATTCGCAATGGGCGAAAGCCTGACGATGCGACGCCGTGTGAGCGATGAAGGCCTTAGGGTCGTAAAGCTCTTTCGCTTGGGAACAAGAGATGCTGGCCAATATCCAGCAAATTTGAGGGTACCAGGTAAAGAAGCACCGGCTAACTCCGTGCCAGCAGCTGCGGTAATACGGAGGGTGCAAGCATTAATCGGATTTATTGGGCGTAAAGGGCGCGTAGGCTGGAGGATAAGTCAGATGTGAAATCCCGGGGCTCAACCTCGGAACAGCATTTGAAACTATCTTTCTAGAGGCTAGAAGGAGAAAACGGAATTCCACAAGTAGCGGTGAAATGCGTAGATATGTGGAAGAACACCGGTGGCGAAGGCGGTTTTCTATTTTAGACCTGACGCTGAGGCGCGAAAGTAAGGGGATCAAACAGGATTAGATACCCTGGTAGTCCTTACTGTAAACGATGTATACTTGGTGTAGCTGGAATCAACCCTGGCTGTGCCGTAGCTAACGCGATAAGTATACCGCCTGGGGAGTACGCTCGCAAGGGTGAAACTCAAAAGAATTGACGGGGACCCGCACAAGCAGTGGAGCATGTGGTTTAATTCGATGCAACGCGAAGAACCTTACCCAGACTTGACATACAGTGGAAGTTAGTAGAAATATTAACGCTCTTCGGAGCCGCTGAACAGGTGCTGCATGGCTGTCGTCAGCTCGTGCCGTGAGGTGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTATCGTTAGTTGCCAACAGGTAATGCTGGGAACTCTAGCGAGACTGCCTGGGTTAACCAGGAGGAAGGTGAGGATGACGTCAAGTCCGCATGGCCCTTATGTCTGGGGCTACACACGTGCTACAATGGTCGGTACAGAAGGCAGCGAAACCGTGAGGTGAAGCAAATCCCAAAAGCCGACCCCAGTTCAGATTGTAGTCTGCAACTCGACTACATGAAGATGGAATTGCTAGTAATGGCGAGTCAGCAACATCGCCGTGAATACGTTCCCGGGTCTTGTACACACCGCCAGTCACATCATGGGAGTTGGTTTTACCCGAAGCCGCTGGCTCAACCGCAAGGAGAGAGGCGTCTAAGGTGAGGCTGATGACTGGGATGAAGTCGGTAACAAGGTAGCGGTACTATACGTATATCT
+
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by benjjneb** [comment]
DADA2 happily works with Q-scores up to 93 (as assigned to CCS reads). See the example workflows here for PacBio CCS specific processing: https://github.com/benjjneb/LRASManuscript
