### ISSUE TITLE
Reverse complement question

### ISSUE THREAD

**Issue by anjexq** [benjjneb/dada2#1132]
Hello,

I am confused on what to do with my reverse complement sequences during the dada2 step where primers are removed. I thought I had read that dada2 does not care what orientation the sequences are in but I am confused how I would define the forward and reverse primers for my reverse complements. My PCR products were generated using 27F and 1492 but for my reverse complements  the first "primer" you would hit  would be 1492 so do I call it as the "forward" primer and the reverse complement of 27F as the "reverse"? Or do I keep 27F as the forward primer and indicate to dada2 in some other way that the sequences are reversed? My end goal is to assign taxonomy and I want to make sure the sequences are in the correct orientation for that step.

**Comment by benjjneb** [comment]
In the standard DADA2+PacBio workflow, reads are oriented into a consistent direction in the `removePrimers` step, see more here: https://benjjneb.github.io/LRASManuscript/LRASms_Zymo.html

**Comment by anjexq** [comment]
Thank you but what does "reads are oriented into a consistent direction in the removePrimers step" mean practically? The program is able to tell that my sequence is a reverse complement, just define the forward primer as 27F and the reverse as the reverse complement of 1492 per the manuscript and proceed?

**Comment by benjjneb** [comment]
The help text about the `orient` parameter in `removePrimers` might answer your question:

```
orient | (Optional). Default TRUE. If TRUE, reads are re-oriented if the reverse complement of the read is a better match to the provided primer sequence(s). This is recommended for PacBio CCS reads, which come in a random mix of forward and reverse-complement orientations.
```

That is, by default, the forward/reverse primers are compared to each read **and** to the reverse complement of each read, and if the reverse-complement of the read is a better match, the read is reverse-complemented. The end result is that the reads after `removePrimers(..., orient=TRUE)` are in a consistent orientation, as defined by having the forward primer (e.g. 27F) at the start of the read.
