### ISSUE TITLE
error in read tracking step

### ISSUE THREAD

**Issue by anjexq** [benjjneb/dada2#1134]
Hello,

I am following your DADA2 + PacBio Fecal Samples workflow. When I reached the read tracking code section I typed 

cbind(ccs=prim2[,1], primers=prim2[,2], filtered=track2[,2], denoised=sapply(dd2, function(x) sum(x$denoised)))

but instead of a lovely table I get the following error message;
Error in x$denoised : $ operator is invalid for atomic vectors

Could you tell me where I am going wrong?

**Comment by benjjneb** [comment]
Are you currently working with just a single sample? If so, replace with `denoised=sum(dd2$denoised)`
