### ISSUE TITLE
Non-fitted error rates

### ISSUE THREAD

**Issue by GianyA** [benjjneb/dada2#1135]
Hello there,
 
I was running the pipeline and during the error rate modeling, I got a quite bizarre results during the modeling (find attached the graphs).
[forward-err.pdf](https://github.com/benjjneb/dada2/files/5240594/forward-err.pdf)
[reverse-error.pdf](https://github.com/benjjneb/dada2/files/5240595/reverse-error.pdf)

This data was sequenced with Iseq-Illumina and it's 16s amplicons from a bioreactor.
So, is this kind of deviation normal for the error learning or it's just my data? 

Cheers, 
Giany.

**Comment by benjjneb** [comment]
The issue here is that the iSeq uses binned quality scores, rather than the normal quality scores 1-40, and this interacts with error model learning. See this issue for a longer discussion: https://github.com/benjjneb/dada2/issues/791

Short answer, things still seem to work fine as far as we can tell, but there are tweaks you can pursue to improve the monotonicity of the fitted error rates.

**Comment by benjjneb** [comment]
See also this analysis of DADA2 performance on iSeq data by @ong8181: https://github.com/benjjneb/dada2/issues/1083#issuecomment-665422538

**Comment by diriano** [comment]
Hi,
I think I am having a problem with binned quality scores.
I have 56 samples, each with over 400K paired-end reads (2x150bp, using 16S rDNA V4 region), after filtering.
When trying to run learnErros using loessErrfun, the R1 was OK, could fit the data. But learnErrors was always failing for R2, no matter which sample I was using. The error mesage is:

```
139227062 total bases in 926543 reads from 2 samples will be used for learning the error rates.
Error rates could not be estimated (this is usually because of very few reads).
Error in getErrors(err, enforce = TRUE) : Error matrix is NULL.
```

See the aggregate quality plots for the 56 samples forward reads:

![image](https://user-images.githubusercontent.com/13472703/101795974-3bcbcb00-3ae7-11eb-942d-ad905fa8a164.png)

And reverse reads:

![image](https://user-images.githubusercontent.com/13472703/101796024-4ab27d80-3ae7-11eb-8481-9f3f217c16ae.png)

From these figs, the quality valies seems to be binned.

Following are the results of plotErrors for the foward reads, where loessErrfun works. That seems OK to me.

![image](https://user-images.githubusercontent.com/13472703/101795799-04f5b500-3ae7-11eb-9490-69566590d60c.png)

AS the reverse reads dis not work with loessErrfun , I tried with noqualErrfun, and that was able to finish fitting the data. Here is the plotErrors
![image](https://user-images.githubusercontent.com/13472703/101795922-2f477280-3ae7-11eb-81e2-7514c03d0b37.png)

Would it be OK to go on with the learnErrors for the reverse reads? Can I mix the learnError of the reverse reads using loessErrfun  and the reverse reads with noqualErrfun?^

Thanks,
Diego

**Comment by benjjneb** [comment]
I think I might just use the forward read error model for both forward and reverse reads in this case. The observed data looks very similar, so it should work well enough.
