### ISSUE TITLE
Cutadapt primer removal

### ISSUE THREAD

**Issue by CarlaCristinaUranga** [benjjneb/dada2#1136]
Hi I am trying to remove primers from my data via the ITS dada2 tutorial. I am able to get things to work, however, when I check to see if the primers are actually gone, I get the exact same output from these commands:

rbind(FWD.ForwardReads = sapply(FWD.orients20, primerHits, fn = fnFs.filtN[[1]]), 
      FWD.ReverseReads = sapply(FWD.orients20, primerHits, fn = fnRs.filtN[[1]]), 
      REV.ForwardReads = sapply(REV.orients20, primerHits, fn = fnFs.filtN[[1]]), 
      REV.ReverseReads = sapply(REV.orients20, primerHits, fn = fnRs.filtN[[1]]))

rbind(FWD.ForwardReads = sapply(FWD.orients20, primerHits, fn = fnFs.cut[[1]]), 
      FWD.ReverseReads = sapply(FWD.orients20, primerHits, fn = fnRs.cut[[1]]), 
      REV.ForwardReads = sapply(REV.orients20, primerHits, fn = fnFs.cut[[1]]), 
      REV.ReverseReads = sapply(REV.orients20, primerHits, fn = fnRs.cut[[1]]))

Do you have any insight as to why cutadapt is not removing primer sequences? I verified my cutadapt version is functioning. Thank you kindly in advance.

Best,
Carla

**Comment by benjjneb** [comment]
What are the outputs of those commands?

And what is the cutadapt command you are running?
