### ISSUE TITLE
Error: record does not start with '@'

### ISSUE THREAD

**Issue by manuelzc** [benjjneb/dada2#1137]
Hi,
I apologize if this is not appropriate. I've left this comment in a closed issue (already deleted) but, in case it passes unnoticed, I have opened this one. I've got my sequences in gz files dowloaded from Google Drive. I've checked them and seem to be all right, as far as I can tell. They do start each record with '@'. However, when I try plotQualityProfile I get an error message: Error: record does not start with '@'. I am running dada2 in windows 10, RGui ver 3.6.3. Thanks in advance for any suggestion.
I am attaching one of the files I am having problems with.
[C-4-5-DI_S_R1.fastq.gz](https://github.com/benjjneb/dada2/files/5254849/C-4-5-DI_S_R1.fastq.gz)

**Comment by benjjneb** [comment]
That file works fine for me. Are you sure you have your path defined to the correct file in your R session?

**Comment by manuelzc** [comment]
Thank you very much for your quick answer. Yes, I defined the path as you indicate in the dada2 tutorial and checked  with list.files(path). I was thinking that it might be a problem with the file encoding but if it works for you, I am at a loss.

**Comment by manuelzc** [comment]
I have been able to work with my files after decompressing them, so I guess the problem comes from the compression but, I have not figured out what is wrong.
