### ISSUE TITLE
PCoA Graphs

### ISSUE THREAD

**Issue by siuguy** [benjjneb/dada2#1139]
Hello, are there any scripts to build PCoA graphs using data from DADA2?

Could we integrate MicrobeR after DADA2? 
`
PCoA(METRIC="braycurtis", METADATA=experiment_metadata, FEATURES=otutable, TREE=ggtree, COLOR="Time", SHAPE="Group", SUBSAMPLE=TRUE, AXIS=c(1,2))
`

Thank you!

**Comment by benjjneb** [comment]
The tutorial demonstrates importing DADA2 ASV/taxonomy information into phyloseq, and then using phyloseq to perform and plot ordinations: https://benjjneb.github.io/dada2/tutorial.html#bonus-handoff-to-phyloseq

But you can integrate DADA2 output into any other microbiome analysis/viz package just as long as you understand how to hand the DADA2 objects (sequence table: numeric matrix, taxonomy table: character matrix) to that package correctly.
