### ISSUE TITLE
Filtering negative control Dada2 

### ISSUE THREAD

**Issue by Biancabrown** [benjjneb/dada2#114]
Hey Benji, 

Question: 

1) Is there a way to use my negative control to filter out the contaminants from my other samples? 
I dont just simply want to remove it from my dataset like what you did in 
"seqtab <- makeSequenceTable(mergers[names(mergers) != "Mock"])" I want to use it to remove all sequences that match with it in my other samples. 

Best, 
Bianca

**Comment by elsherbini** [comment]
One way to accomplish this is to use the hadleyverse packagages `dplyr` and `tibble`:

```
seqtab <- makeSequenceTable(mergers)
transformed <- seqtab %>%
     t() %>% 
    as.data.frame() %>%
    tibble::rownames_to_column("sequence")
```

Now the object `transformed` is a data frame, the first column is the inferred sequence and the other columns are the abundance in each sample. All sequences which appeared in the negative control are filtered out.

To get sequences that have 0 counts in the negative control:

```
negative_control_filtered <- transformed %>%
    dplyr::filter(negative_control_name == 0)
```

A shortcoming of this method is it's no longer the same shape/type as the object returned by `makeSequenceTable`. If you did want the resulting object to still be a matrix with the sequences as column names and samples as rownames, there might be a better way rather than going through the dataframe route.

**Comment by benjjneb** [comment]
@Biancabrown 

There are many ways to do this in R (see also @elsherbini method above). If we are sticking with base R:

```
ctrl.samples <- c("ctrl1", "ctrl2", "ctrl3") # CHANGE to names of your negative controls
found.in.ctrls <- colSums(seqtab[ctrl.samples,])>0
seqtab.no.ctrl.seqs <- seqtab[,!found.in.ctrls]
```

I want to warn you about removing every sequence seen in your controls though. One of the types of contamination is cross-sample contamination. This is generally significantly less than reagent contamination, but it is generally not zero. And cross-sample contamination will tend to cause the most common real sequences to be found in negative controls.

So be careful about blanket removal of every sequence seen in your controls, especially if those sequences are very highly abundant amongst real samples.

**Comment by Biancabrown** [comment]
Thank you guys! This was really helpful. After going through the pipeline, and figuring out several different things. It seems as if my sequence data is horrible. My merge sizes are extremely varied(see below). Do you think I may have done this all wrong? 

230 231 233 234 235 236 237 238 239 240 241 242 243 244 245 246 248 249 250 251 
 15   1   4   1   1   2  29   1   1   6   1   8   1   3   2   1   2   3   1   2 
253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 272 273 274 
  1   3   8   2   2   7   1   2   3   6   4   1   1   3   2   2   2   4   1   3 
276 279 281 282 283 284 285 286 287 288 290 291 292 293 294 296 297 298 299 300 
  3   1   2   1   3   2   4   1   8   2   6   4   6   1   5   3   3   4   3   5 
301 302 303 306 307 308 309 310 312 313 314 315 316 317 318 319 320 321 322 323 
  8   4  23   1   3   4   1  12  10   3   1   3   1   3   8  10   4   1   1   6 
324 325 326 327 328 329 330 332 333 334 335 336 338 339 340 341 342 343 344 345 
  2   5  10  34   9   3   6   3   5   2   3   1  45   5   4   1   7   4   9   3 
346 347 348 349 350 351 352 353 354 355 356 357 358 359 
 24   5  11  13   6  11   7   1   5   3   1   3   6   1

**Comment by benjjneb** [comment]
Hi Bianca,
That's not what you hope to see, but its not necessarily the end of the world. First question: how long is the amplicon you are sequencing? That is, what merged length are you expecting given your primers?

Two things to check then are -- how many total reads made it through your workflow (eg. `sum seqtab.nochim`) compared to how many went in? And, how are the reads concentrated in the merged sequence lengths?

```
reads.by.seqlen <- tapply(colSums(st), nchar(colnames(st)), sum)
plot(as.integer(names(reads.by.seqlen)), reads.by.seqlen, xlab="Merged length", ylab="Total Reads")
```

**Comment by Biancabrown** [comment]
Hey, 
My primer was expected to amplify ~408 nucleotide length, and I used illumina 250 bp paired end reads. 
sum(seqtab.nochim) is 13513

This is the plot from the concentrated merged sequence length. 

![image](https://cloud.githubusercontent.com/assets/15444656/18450674/f16a4aec-7901-11e6-9a27-648dd3f2f6a4.png)

_bianca

**Comment by benjjneb** [comment]
My guess is that when you trimmed your sequencing reads, you trimmed them so much that they no longer overlap, and therefore lost nearly all of your reads at the `mergePairs` step.

When trimming, you must keep enough DNA for the reads to still overlap, with more than 20 nts preferred. You can't just plug in the values from the tutorial in this case, as the tutorial used completely overlapping reads (2x250 reads for a 250nt amplicon) and thus can trim entirely based on quality scores.

**Comment by Biancabrown** [comment]
Great. Yes, this was silly on my part. Going through the protocol> I just realized that I did exactly what you pointed out. I trunclen(240,160) which doesn't make sense because that leaves roughly 2bp overlap.  Thank you so much for pointing this out. 

One more question and I should be great. 

I have been going through the protocol but when I get to this stage, I received this error message. Do you have any idea how to fix it? It worked fine before. 

Error in dada(derepRs, err = NULL, selfConsist = TRUE) : Invalid derep$uniques vector. Must be integer valued.

Best and thank you, 

Bianca

**Comment by benjjneb** [comment]
Can you post the exact commands you used to create `derepRs`?

**Comment by Biancabrown** [comment]
Keep it simple, I followed your syntax. 
The only thing I've changed prior to this was the file path which is directed to a folder with the fastq files. 

filt_path <- file.path(path, "filtered")
if(!file_test("-d", filt_path)) dir.create(filt_path)
filtFs <- file.path(filt_path, paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(filt_path, paste0(sample.names, "_R_filt.fastq.gz"))
# Filter
for(i in seq_along(fnFs)) {
  fastqPairedFilter(c(fnFs[i], fnRs[i]), c(filtFs[i], filtRs[i]),
                    trimLeft=c(10, 10), truncLen=c(245,240), 
                    maxN=0, maxEE=2, truncQ=2, 
                    compress=TRUE, verbose=TRUE)
}

derepFs <- derepFastq(filtFs, verbose=TRUE)
derepRs <- derepFastq(filtRs, verbose=TRUE)

**Comment by benjjneb** [comment]
Not clear from that.

Can you post the output from the following:
```
class(derepRs)
length(derepRs)
table(sapply(derepRs, class))
```

Could also be useful to share a .rds of the derepRs object (`saveRDS(derepRs, "derepRs.rds")`)

**Comment by Biancabrown** [comment]
Here you go: 

class(derepRs)
[1] "derep"
attr(,"package")
[1] "dada2"

length(derepRs)
[1] 3

table(sapply(derepRs, class))

integer  matrix 
      2       1

**Comment by benjjneb** [comment]
That all looks like it should be just fine?

I don't know. I think I would need you to post the .rds of the derepRs object (`saveRDS(derepRs, "derepRs.rds")`). Or you can email it to me: benjamin DOT j DOT callahan AT gmail DOT com
