### ISSUE TITLE
Use dada2 with plant psbA-trnH amplicon

### ISSUE THREAD

**Issue by termithorbor** [benjjneb/dada2#1140]
Hi all,

Just a short question - can I use dada2 also for analysing psbA-trnH plant amplicons? I think it should be possible till the sequence table preparation step, right?

Thank you very much in advance for your help.

Cheers

**Comment by benjjneb** [comment]
Yes, dada2 is agnostic to the underlying amplicon being sequenced. You may need a different taxonomoy assignment solution though (or custom database).
