### ISSUE TITLE
Primer removal 16S cutadapt or trim left

### ISSUE THREAD

**Issue by termithorbor** [benjjneb/dada2#1141]
Hi all,

for 16S V3-4 amplicon Illumina data is it better to use cutadapt to remove primers or trimLeft? I noticed that with using cutadapt you end up with less reads in the end.

Thanks for your help.

**Comment by benjjneb** [comment]
If you have the normal situation, with fixed length primers at the start of your forward and reverse reads, I would just use `trimLeft=c(FWD_PRIMER_LEN, REV_PRIMER_LEN)`
