### ISSUE TITLE
Too few PacBio ASVs

### ISSUE THREAD

**Issue by bitcometz** [benjjneb/dada2#1142]
hello，
I follow the guide of [DADA2 + PacBio: Fecal Samples](https://benjjneb.github.io/LRASManuscript/LRASms_fecal.html) to 
do analysis for my three sampels sequenced on the **Sequel II** platform and I set the parameters as follow:

--min-passes 3 --num-threads 5 --min-rq 0.999 --min-length 1000 --max-length 1700
primerF='AGRGTTYGATYMTGGCTCAG'
primerR='RGYTACCTTGTTACGACTT'

Then I got the statistics:
ccs	primers	filtered	denoised
Sample1.ccs.fastq.gz	3805	1894	1756	1318
Sample2.ccs.fastq.gz	10492	6022	5845	5361
Sample3.ccs.fastq.gz	5580	4024	3646	2357

I wonder why so many datas are filted by primers and finally I got 66 ASVs, is the result normal?

Thanks

**Comment by benjjneb** [comment]
"Normal" always depends on the amplicon and environment being sequenced, there is no one "normal".

You may want to try to increase denoising sensitivity by using `DETECT_SINGLETONS=TRUE` and `pool=TRUE`.

**Comment by bitcometz** [comment]
Thanks for your reply !
