### ISSUE TITLE
Link input sequence to sequence variant

### ISSUE THREAD

**Issue by florian-gschwend** [benjjneb/dada2#1144]
Hello
is there a way to identify the sequence variant to which a given sequence of the input is accounted to?

Thank you for your help.

**Comment by benjjneb** [comment]
See this issue: #354

And this comment: https://github.com/benjjneb/dada2/issues/889#issuecomment-553919284

It's straightforward to track reads to denoised ASVs using the $maps described above. Tracking through to merged ASVs is not quite so straightforward unfortunately.

**Comment by florian-gschwend** [comment]
Thank you for the quick response. As you said, it was easy to track reads to denoised SVs using $map - but with the merged reads it was quite difficult.
