### ISSUE TITLE
Issue in species specific taxonomic assignment

### ISSUE THREAD

**Issue by dunnbrooke** [benjjneb/dada2#1146]
Hello, 

I am following along with your 1.16 tutorial. I am on a windows and am rather new to Rstudio. 
I am attempting to run this command
`taxa <- assignSpecies("C:/Users/Brooke/OneDrive - University of New Mexico/Dada2 UNM/tax_silva_species_assignment_v132.fa.gz")`

I get the following error:
`Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'dirPath' in selecting a method for function 'readFasta': argument "refFasta" is missing, with no default`

Do you have any ideas how I can fix this error? Thank you.

**Comment by benjjneb** [comment]
`assignSpecies` needs two arguments, the sequences you want to assign taxonomy too (often in the form of a sequence table), and then the path to the reference fasta. Look closely at the syntax for `addSpecies` here, which is essentially the same: https://benjjneb.github.io/dada2/tutorial.html#assign-taxonomy

Also, you can get detailed help information on all functions through R with the shorthand `?assignSpecies` (For example).
