### ISSUE TITLE
How to get a list of honchimeric ASV?

### ISSUE THREAD

**Issue by TrosAVT** [benjjneb/dada2#1148]
Hello,
I am a neophyte in R and DADA.
Following the example in DADA2 Pipeline Tutorial (1.16) after removing chimeras sum(seqtab.nochim)/sum(seqtab) I get[1] 0.964263. How can I get alignment of nonchimeric sequences and save them somewhere?
Thanks to all.

**Comment by benjjneb** [comment]
You just want the list of non-chimeric sequences? You can use `getSequences(seqtab.nochim)` to get those.
If you want to write them to a file, there are a few different ways depending on the format you want.

**Comment by TrosAVT** [comment]
Thank you very much for your answer.
I have a further simple question: how to export non-chimeric sequences to a fasta files for further search in databases, not only Silva but also NSBI. 
I would be grateful for your advice.

**Comment by benjjneb** [comment]
`writeFasta(my.seqs, "path/to/output.fasta")`
