### ISSUE TITLE
creating metadata file

### ISSUE THREAD

**Issue by MohammadRezaSe** [benjjneb/dada2#1150]
Hi,
How can I create the metadata file? in Tutorial: mouse.dpw.metadata

**Comment by benjjneb** [comment]
That file isn't used in the tutorial.

But it comes as part of the zip file you download to get the sequence data to follow the tutorial, see https://benjjneb.github.io/dada2/tutorial.html#getting-ready

**Comment by MohammadRezaSe** [comment]
Actually I edited that file to use in my project. But it doesn't work. I don't know how to rename the sample names. 

As my second question, how can I merge samples in phyloseq?

**Comment by MohammadRezaSe** [comment]
Also I want to remove some samples from the plots. How can I do it?

**Comment by benjjneb** [comment]
It sounds like the issue you are having are with they phyloseq R package, and perhaps are better asked in their issues forum: https://github.com/joey711/phyloseq/issues

I'd recommend including more detail about what exactly you are trying to do, and what isn't working, perhaps including current code, when reposting these questions there.
