### ISSUE TITLE
How to process a single file?

### ISSUE THREAD

**Issue by CiraLab** [benjjneb/dada2#1151]
Hello! I'm trying to run DADA2 on a folder that contains a single fastq file, but I keep running into an error. Does anyone have thoughts on what could be causing it?

The code is below, and the error is:
Error in filterAndTrim(samples, filt_samples, trimLeft = myvals[1], trimRight = myvals[2],  : 
  Every input file must have a corresponding output file.

### Change the path to fastq file directory
path <- args[1]
### List the full filenames
samples = sort(list.files(path, pattern=".fastq", full.names=TRUE))
### Extract the sample names
sample.names <- file_path_sans_ext(list.files(path))
### Eliminate unwanted folders and filenames
retain = grepl(".fastq", samples, fixed=TRUE)
samples = samples [retain]
sample.names = sample.names [retain]

### Don't trim
myvals <- c(0,0)
### Filter and trim
print('Filtering Samples')
filt_samples <- file.path(path, "filtered", paste0(sample.names, "_filt.fastq.gz"))
names(filt_samples) <- sample.names

out <- filterAndTrim(samples, filt_samples, trimLeft=myvals[1], trimRight=myvals[2],
              maxN=0, maxEE=2, truncQ=2, rm.phix=TRUE,
              compress=TRUE)#, verbose=TRUE, multithread=TRUE)

**Comment by benjjneb** [comment]
What do `samples` and `filt_samples` look like? I.e. what's the output of:

```
samples
filt_samples
```

**Comment by CiraLab** [comment]
It looks like
```
samples = <NA> 
filt_samples = "/home//Bioinform/demultiplexed/filtered/_filt.fastq.gz" 
```

**Comment by benjjneb** [comment]
I think there might be a problem with `samples`.
Where might that have arisen?
