### ISSUE TITLE
Error in filterAndTrim

### ISSUE THREAD

**Issue by lizza20** [benjjneb/dada2#1152]
Error in `colnames<-`(`*tmp*`, value = c("DNP04_F.fastq", "DNP06_F.fastq",  : 
  attempt to set 'colnames' on an object with less than two dimensions
In addition: Warning message:
In mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule,  :
  scheduled cores 7, 3, 6, 1, 5, 4 encountered errors in user code, all values of the jobs will be affected

**Comment by benjjneb** [comment]
A couple things:

First, please don't title threads "HELP!!!" or the like. We are here to help, but what we need is useful information about the problem you are experiencing.

Second, can you re-run your `filterAndTrim` step with `multithread=FALSE` and report the error messages?

Third, consider making sure the file names you are providing are appropriate. This is a common cause of errors in the `filterAndTrim` step, and you can inspect the filenames by printing them out in the R console.

**Comment by lizza20** [comment]
Thanks a lot. I re-imported my data and the filtering is worked.
