### ISSUE TITLE
Cutadapt error: unrecognized arguments

### ISSUE THREAD

**Issue by EcoGinger** [benjjneb/dada2#1153]
Hi There!

I'm having issues on the step where you use cutadapt to remove the primers. I am using R in RStudio in Windows 10. I keep getting the following error after running the code below. 

"cutadapt: error: unrecognized arguments: Drafts/Greenhouse Feedback Manuscript/GH Metabarcoding/fastq files/cutadapt/VhasLive1057_S67_L001_R2_001.fastq C:/Users/rache/OneDrive/Documents/Dissertation/Manuscript Drafts/Greenhouse Feedback Manuscript/GH Metabarcoding/fastq files/filtN/VhasLive1057_S67_L001_R1_001.fastq C:/Users/rache/OneDrive/Documents/Dissertation/Manuscript Drafts/Greenhouse Feedback Manuscript/GH Metabarcoding/fastq files/filtN/VhasLive1057_S67_L001_R2_001.fastq
This is cutadapt 2.10 with Python 3.9.0
Command line parameters: -g GTGAATCATCGAATCTTTGAA -a GCATATCAATAAGCGGAGGA -G TCCTCCGCTTATTGATATGC -A TTCAAAGATTCGATGATTCAC -n 2 -o C:/Users/rache/OneDrive/Documents/Dissertation/Manuscript Drafts/Greenhouse Feedback Manuscript/GH Metabarcoding/fastq files/cutadapt/VhasSterile2117_S86_L001_R1_001.fastq -p C:/Users/rache/OneDrive/Documents/Dissertation/Manuscript Drafts/Greenhouse Feedback Manuscript/GH Metabarcoding/fastq files/cutadapt/VhasSterile2117_S86_L001_R2_001.fastq C:/Users/rache/OneDrive/Documents/Dissertation/Manuscript Drafts/Greenhouse Feedback Manuscript/GH Metabarcoding/fastq files/filtN/VhasSterile2117_S86_L001_R1_001.fastq C:/Users/rache/OneDrive/Documents/Dissertation/Manuscript Drafts/Greenhouse Feedback Manuscript/GH Metabarcoding/fastq files/filtN/VhasSterile2117_S86_L001_R2_001.fastq
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation."

I saw the post from earlier this year, but I wasn't able to find anything helpful for my situation on it. The filtered files end up in the filtN folder just fine, but the cutadapt folder that is created is completely empty. 

Please let me know if there's anything else that I need to include on here to clarify and thank you in advance for any help that you might be able to offer!

#####DADA2 ITS Pipeline Workflow#####
##Source: https://benjjneb.github.io/dada2/ITS_workflow.html##

##Install necessary packages##
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("dada2", version = "3.11")

##Load packages##
library(dada2)
packageVersion("dada2")
library(ShortRead)
packageVersion("ShortRead")
library(Biostrings)
packageVersion("Biostrings")

##Define path where fastq files are located##
path <- "C:/Users/rache/OneDrive/Documents/Dissertation/Manuscript Drafts/Greenhouse Feedback Manuscript/GH Metabarcoding/fastq files"
list.files(path)

##Housekeeping - Generate matched lists of the forward and reverse read files & parsing out sample name##
fnFs <- sort(list.files(path, pattern = "_R1_001.fastq", full.names = TRUE))
fnRs <- sort(list.files(path, pattern = "_R2_001.fastq", full.names = TRUE))

##Identifying primers##
FWD <- "GTGAATCATCGAATCTTTGAA"
REV <- "TCCTCCGCTTATTGATATGC"

##Verify the presence and orientation of these primers in the data##
allOrients <- function(primer) {
  # Create all orientations of the input sequence
  require(Biostrings)
  dna <- DNAString(primer)  # The Biostrings works w/ DNAString objects rather than character vectors
  orients <- c(Forward = dna, Complement = complement(dna), Reverse = reverse(dna), 
               RevComp = reverseComplement(dna))
  return(sapply(orients, toString))  # Convert back to character vector
}
FWD.orients <- allOrients(FWD)
REV.orients <- allOrients(REV)
FWD.orients

##Pre-filter ambiguous bases (Ns) from the sequencing reads##
fnFs.filtN <- file.path(path, "filtN", basename(fnFs)) # Put N-filterd files in filtN/ subdirectory
fnRs.filtN <- file.path(path, "filtN", basename(fnRs))
filterAndTrim(fnFs, fnFs.filtN, fnRs, fnRs.filtN, maxN = 0,maxEE = c(2,5), multithread = FALSE)

##Count number of times that primers appear in the FWD and REV read##
  primerHits <- function(primer, fn) { # Counts number of reads in which the primer is found
    nhits <- vcountPattern(primer, sread(readFastq(fn)), fixed = FALSE)
    return(sum(nhits > 0))
  }

rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.filtN[[1]]), 
      FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.filtN[[1]]), 
      REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.filtN[[1]]), 
      REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.filtN[[1]]))

##Remove primers##
cutadapt <- "C:/Users/rache/AppData/Local/Programs/Python/Python39/Scripts/cutadapt.exe" # CHANGE ME to the cutadapt path on your machine
system2(cutadapt, args = "--version") # Run shell commands from R

path.cut <- file.path(path, "cutadapt")
if(!dir.exists(path.cut)) dir.create(path.cut)
fnFs.cut <- file.path(path.cut, basename(fnFs))
fnRs.cut <- file.path(path.cut, basename(fnRs))

FWD.RC <- dada2:::rc(FWD)
REV.RC <- dada2:::rc(REV)
# Trim FWD and the reverse-complement of REV off of R1 (forward reads)
R1.flags <- paste("-g", FWD, "-a", REV.RC) 
# Trim REV and the reverse-complement of FWD off of R2 (reverse reads)
R2.flags <- paste("-G", REV, "-A", FWD.RC) 
# Run Cutadapt
for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                             fnFs.filtN[i], fnRs.filtN[i])) # input files
}

**Comment by benjjneb** [comment]
The problem probably is the spaces in your filepaths. Spaces in filepaths do not play well with many command line applications, including cutadapt.

Your best bet is to redefine the directories you are storing your files in without using any spaces in their names.

**Comment by EcoGinger** [comment]
Thanks for your response! I changed the filepaths and cutadapt seemed to run. There were a few errors that all looked like this: 

" File "c:\users\rache\appdata\local\programs\python\python39\lib\site-packages\dnaio\readers.py", line 114, in __init__
    self.two_headers = next(self._iter)
  File "src/dnaio/_core.pyx", line 193, in fastq_iter
**dnaio.exceptions.FastqFormatError: Error in FASTQ file at line 1: Line expected to start with '@', but found '\x1f'**
This is cutadapt 2.10 with Python 3.9.0
Command line parameters: -g GTGAATCATCGAATCTTTGAA -a GCATATCAATAAGCGGAGGA -G TCCTCCGCTTATTGATATGC -A TTCAAAGATTCGATGATTCAC -n 2 -o C:/Users/rache/OneDrive/Desktop/fastq/cutadapt/VhasSterile2117_R1.fastq -p C:/Users/rache/OneDrive/Desktop/fastq/cutadapt/VhasSterile2117_R2.fastq C:/Users/rache/OneDrive/Desktop/fastq/filtN/VhasSterile2117_R1.fastq C:/Users/rache/OneDrive/Desktop/fastq/filtN/VhasSterile2117_R2.fastq
Traceback (most recent call last):
  File "c:\users\rache\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\rache\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)"

I then noted that even though only 168 files went into this process, 174 files came out. These files are also all 0 KB. 

Any thoughts on what may be going on?

**Comment by benjjneb** [comment]
Well my first guess is there is a fastq format error with your files.
If you open them in a text editor, do they look like fastq files?

**Comment by EcoGinger** [comment]
@benjjneb I believe that they look like fastq files. I just looked up the formatting and they seem similar. Here are the first four sequences in one of the files. 

"@M02226:23:000000000-AL7CF:1:1101:18462:1399 2:N:0:66
TCCTCCGCTTCTTGCTCTGCTTCCGTTCCGCGGGTTTTCCTCCCTTCTCTGCGGTCTCCCTCTTTTTGTTGCTTTTTTTTCCGCTCTTCCCCTCCTTCCCCTCTCCCCGCTTTTCTTCTTCTTACGTCTCTTTGCTCTCCCCCCCCTCCTCCCGCTGTCTTTCTCTCTCGCCGCCTTGCCCCATGGCCCCTTCTCCTTCCTCCTCTTTCCTTCACCCTGCTCCTTCCCTCCTGCGCCGCTCTCCTCCCCCCTCTTCTCTCTTCCCCCCTCCCCTCCTGCTCTCTCTCCTTTCTTCTCTT
+
CCCCCGFGEC,C@E,C6CCFFF,,,C@F,6C+6+@,8,<,;,;8A,,;55,,++8@,6-9,,66,--+,,,,,<,9:76+,,,,,++9,<,,,++44,444,+,,,,4++4++,,,,6,,,44+6+33,,,,,,,,3+,3,+++8+)*00*33**4**,27,89*,,**33)(/)**))++(**0**,/**2(/))+,+(++)(/+++).6)*)/*))..**.,++(,)((()((((-,/*()(*(*(((0)))*)2++2+))*),/*(---,(((()((..))+0+*++,,,,,,))-
@M02226:23:000000000-AL7CF:1:1101:13437:1458 2:N:0:66
TCCTCCGCTTATTGATATGCTTAAGTTCAGCGGGTATCCCTACCTGATCTGAGGTCAAGCTGTAGAAATAAATCGTTCAGTTGGCAGACAGCCGAACAGCTGCTTCGCCGAGGCATTACTTCCTACGTCTTGCAAGCTAGAACAGCGCCGCCAATAGCTTTCAGCAGAGTGACATAGATGCCCCTTCCTCCCATACCAAACCTAAGTTTGATCGATTTATTGACCCCTTGTCCGGCATGCCCTTCGGATTACCCAAGGGCGCCACTGCCGTGCAAACATTCTCTTTTCTTTCCGTTCCTT
+
CCCCCGGGGGFGGG<FGGGGGG<@CEDGGGGGGGG>E5CC@9EEFF@FAB@6E8EF8<@CEFC,<--,<,,,,C,CE8,,<6,,,,,,9,999+++64,,,,9,,9>,,++8:++,9,99=,4=,?+51A4,4,,,46,,,,5,,+)6+++6+*+,,,,,,,*2*7,)*+2+*+++,33,38,***,,*59*39)::,,)*3*))45,/*/*+/)/1)**++**,0(*(0)))/(((.(*,(((.2*(((*2+)/(*1***(()),,+(((((().((<)))-)+20+++,,,*,0,.55
@M02226:23:000000000-AL7CF:1:1101:17792:1527 2:N:0:66
TCCTCCGCTTATTGATATGCTTAAGTTCAGCGGGTATCCCTACCTGATCTGAGGTCACCCAGTTTAAGTTGGGTGTTTTTCGGCAAGTACAATGATTCCCCACTAGACGCTTTTCTTATTATTACGTCTGTTTGACATCCATACCTTACTGCCGCTCTATTTCTGAATCTCAGCCTTGCACGCTGGCCACCTCTTCATATTAATCCAAGCTTCACACATATTCTTACCTGGGCCCGCGCTCTCGCTCCGCCCGTCTTTCCCTCCTGCAGACCCTAGGCCCCCTCTTCCTTTCTTAGATG
+
CCCCCGGGGGEFFGEFFGGGFGGFDECFGGGDGGGG<,<6@;CEDF6E,@@,C,;E,C-C,,;E,--,,6,,+8,@@C<@,++4++,:,?,95,,9@96?<,+,,4596+44,A,,9,,999=D;+931A,99,,,9+,9,,,,9+*+6++,8<+4++,,83;C7,,*5+6+2++66:*,,)++++33)+,0)03*3,,*5++*3,,,*))*4**+**)*+4**,,1,**)))))((-()*(.()(2(/()))).(*++5+/(.)08*().((((((((((-((*0+++3,,,,,,).4
@M02226:23:000000000-AL7CF:1:1101:15574:1531 2:N:0:66
TCCTCCGCTTATTGATATGCTTAAGTTCAGCGGGTAGTCCTACCTGATTTGAGGTGAAATGGTTCAAATTGTTTCCATAGGAAACTGTTAGAAAGCAGTCAAGATCAACCAACTGTATATGCAAGGCGCACATAGACTATTACACCAAGCCAGTGGGATCCAAAAGGTTCGAATGAACCCAGACAACCCATGCATTAAAGAAGAGCTGACCTCCAGTGAAGCCAGCAACTTCCATACCCAAGCCCTAACCGGGGTAAAAAAGTTAAAAATGGAGGATTTAATAATTATCTAAAAGGCACA
+
CCCCCGGGGGGGGGGGGGGGGGFGEFFGGEEFGGGECEF9DCFEEEF8A<6CFFF,@EEE9E,F@--,9,6CAE<9,C,,,6,:@,BE9<A,,,9:,,9:,9,,,,5,,,,,64=9,9,9@,,?D6,:6+++9,9,=+,,5,9,>65+=8DBD9+@,,,+,,5+0=>0<++0)+6+=856+=,6,+3+)+6=)+**,,,5+538C6,8>)0*3);*13**+*08D*)8))*/***2)))**:)4)0,(-(:)).),0++0*()++<,?)/.))6((()..6))-+*++++033,2/(.((
@M02226:23:000000000-AL7CF:1:1101:14903:1548 2:N:0:66
TCCTCCGCTTATTGATATGCTTAAGTTCCGCGGGTTTTCTTACCTCATCTGAGGTCTACCTGTTAAGGTTGGGTTTGTTTCCTCACATCCATTCCTTCCCCTCTTCCCGCTTTTACTATTCTTACGTGTGTTTGCACTTCCAACCCTTCTCCCGATGTATTTCTGAATAGCGACCTTGCCCGGTACCCCCTTCTTCAACGTACTATACCCTTACACCAGCTCCTTCAGGCTGGGCGAGCTTTCGATACGCCAAGCCTGGCCAACGGCAGACCATACGGCGACACCTCTCCTGCGGCGTGG
+
CCCCCGGGGGFGGGFGGGGGGGGGFFEG,?FFGDF:8,<,,<<-;,6=,C@CCCEG,,-,,,,,,6-C69,@FF7,,:96,,,:,,,:,8,,,,9,,B?<=,,,,,,4,+4++,,,,9,:,9,6,+,*9+,9,9,,@+4,,,,,+0)+++6,7*+++,,3,,*+3,,*++33)0++,*3,,)++++,,)*4*);*07,,0***)*,6,*)*)/.3***)(*)((2,0,*((/((((((()5))(21*./,))))7,<****(())***((((().((4(((-((*0*+**03,*/*(,-("

Does this look correct?

**Comment by EcoGinger** [comment]
@benjjneb After the initial step of filtering out Ns, this is what it looks like... 

‹      ìýÉbã¸²ŠÎÏWÜ¡H3m±‚hˆ†“ûÞHÿÿ-7" Re›ÎÊÜ{WU²*m‰YK±¢5ÿ¿sÓ4ƒhZqÞ¶öÿe.ŠZÔõ¹ïÎbh†ñÿ©Åÿ_ÀÃÿ[/«µÿÓïËŸ»ÕÁú…{.ðÊÅ9üË×Õâk×‹…ÿà :^Ó8ÜµÒ~<œæ²ýGoV:#]êbWº€]ñêttAºp:¹ÅeŽN·Ewàö5ô¢Ýî	^Ã;£sÁËé
¬tŠíT+ž‰žÃ›~Út5‡Kñ€ôœKKñª°÷ÿ^þÏá¶ÒÃÖ¼Eü±?Ëûb~!Â–qŸx\L/Ãæã×Ç#ï÷¸t¢¸ºm‡%ÜGÚ·cb:›÷ÁÑÕãâáá·÷‹_B4´þŸ¦}œ}XVÆ,ÝQ€ã‚Æ»Ãw½-§ ÏDˆ!ð¶™æÒÙÑ„èÂì¢“ÁZ<7¹(qÝlðÐ²¥[Ú¡TýÜÂÿ™/ñØŸ»Z0~nþàñ/éüx|¶ÝBrU °D‹ß_aGHð¸EŸw‡>"sÛí²ÒáøÕðÁäƒ
±Ÿ'ŸÐ`FO]\UXMÕÎˆG/£éø‹)g_2@ùÊ£uspˆ› ß jÔ¥]5ëŒ³€¿Þâ‚-ð'~Ûº3{™C7‰5.R§ÓäŽà±îÇzãÐ $*Öu“ðQÑ‹îˆ"—äÈJ§ O1}¬kCúTWú áxD«Ããiyú?I¶hð$ÂEzOL ·éŽÓWfÍ ¤º¤+Øô¦Ò	÷t¸Í@¤K,ívïÿéð~/mZ|ù
áéÞu“~ôÁ­w²pìœOÈ#r{ƒØJBÑÁîj¯~õ•5Kè+ø@Š#á'ÏK1¼ ¤@4p+X5„¹œ^f¥à!q=÷&2’ÔG¦ðÆ`%ÜBàp
_”N‹0es)zSi”“fb¹Q
B» EU|ºQ&åÊs’RšØ.¾”G Ù´5¼gÃ	I€Á„Òº&‡p$pÂñ—ü	_.¨pÉ%ÚúÜ}þx*ÿC‘‹hÈ²r]Ý&aWŠÿ$Zî!$ÉÒî­Éxué!~q2àðÀYñ]á™W’â.]!½û ‰ý-h‚y*£>ÃÞ‘Í½×ÒûÕã£&NOIµ#&£s1Ð«(šxÄÄ¼~Q YWü%¨SA{Ï«ÒÏàEãè<°|l9\4ÕØ+¶,â €x‡øáçîA ÙŸhöF ÙÍh	ýWvÙTó&ÑÖ¯5ìLm¸€ÿíz«MÓÃd+*úôß©Ó›Å«Ed…Û—DH¹lñ€Z™¼wäR ›ŽLN&#˜m†(êh0æªùÅùå³ÐŒ®Ysž@RU’;3+áÜŸ°•ý(ºº²®«¶eÉµ”e©´Ôc1ðì‚kíüË!
;ðó<4ç¯é2"}þ‘™$š#ùDÂ
U&m	k¸&Y[+>IVÔÅæóãÿ(½Ü®ÈP”­¤à\‚bº%xiM—¿ÐåèÜø½@¹–D¥ÍVÞá]ó;"˜âéß’xÎbÑ:úše¸n2÷=‘éºl¾ç |‡¯õññ3Æõ½ä£W631nÂ0¿˜ŒÄÝÂŒ¼=•ñ™ŒCCÜ	Ñrêx£¾5­Lo6fµmÑ¶­žÂª²>½U½Óc/u30þÊ›¢
5R±C×5ˆÈá€Ñç\–‘ô`Cä&#tlâ —üÉ‘Açì&½’H¢œ€IL†@F¨YÑ°É"µ.A{—›tè…@†×$f~Cjš®¿&Z‘%3]8ÝA¶gÔéëD6]:Õ%‹âË{U
Çûr ã
0Ò»H1'nÅZ\×}rúí®¸ÙNs}ôtC:@ËÒ}ä‚Ô8 …}>=üÓUqïƒ"ð›ØCÌ%Fk@2™…ßåyeÔÄŸAÒr ˆL³AL
ìLæ	lŒØg:Nºx™Ný4jS¼6ïƒ!h-Û®ÀÒ‹Qv²ëtÓqŒƒçñÙp@gÿaÅŸ{ià]’éÿ@§¡»¹ŸýZÑ‚DAJ@@ —I”¨XcÜe›©ä.Èè—c:þ›ˆƒŸcàÛ,_™Yâ-ŒÞù]Bzt8*çÑz ³ä’aYL.qÍ
ÈC.^àfJÍ›[áC¹÷q„uç‰±,l®Ì\Ã©Z¸žlÉB¤®Õ ©Ð5˜0°òM‰%tÁ,ë!/MÝ6-ƒ‡œõ¿[B^þãr½JÈË·$¤ý®„|"¿n\zRîÎ·ø-FöÕïUü{•
²mÊ˜¥$
ÐËt(
>¹©løZK&äŒ´ºòU4ìÈ1Hâ7÷`}‹¡ÜÌJ«³œu§+®[ÇÉ´ÂÈ @Bí+×n(ØTô ñÈ¤6¢
þ‹Gð84dÓ5õù-éž¸±Ÿ¡K=Ç[Ü•üƒ—ð`7Îí5fâìÜ­ß&?ºº
7<’˜JO¢&Ý¾9+c¢Ù€WN–"ù±h7Gÿ‚ÆŸG±‰*t6®“œ' Ò™à*Ñ”B”•iÏ=HÐë°“HÒsÓRurV &ßêRXiÚæØ‡Tv}æ€È¾=XùÈï™»€´?/ ?ÞâÍÏ›½×>~zÂø\ª’½Ö„ôQcp„¼åø\ƒ6î=l+Ñq¤ÉWN“ô,™d×ºÎ¬ëìÂ„ †ï@Xy˜"Ú/]3öÚ¦†cÎžNÃì
îŠq©VÔ3nRº“ #;!õâ•>hBvíÐƒÚ®ÿC²?"ÙÏÉ1ù !ŸÃèF~ºm/û5ÇCîÁödåŽNÀK²#Ã=ÉféiØIvÈ•¡·Ž¬FX“$.­OhÅëén ¼¢!ÜyX	\‰7
¬]"á;èž8ÈL3¢ŽNš©1¦K<sŒ^;¿H¹RÁ_òÉn$»›¯$¤Ížá„!’CôjÖˆÙK½nÒ'KÈ¤R“fßµ y‹¯B—0–É.kR§äyÎnìäO*:½âìæ±$ßwÒþk–…	?YÐ]vÔ%ûÀÒ÷jÍwœ-¤×Ó\³ñ±{ÉêHH%0¯ÉÑníÇ"2n^ÅwänJ?âï„úáÀ=î—Q´"³ÃæÒÉ¦eæò(Ií“Ã;­Âƒ7÷Ù#œç¥Æ`ÝÊ¢³
¡Xõ¦Q ÿÙ†‘”º{{Õ7Ò…ÊHÙ»ÈÐÒýÀ'[cq*Þ:yÖ:
vHg3vNÓòý1"ÿr.Ä'Û£|ŒwHÏ–\qøù–ß èoDäHÃMäˆ	 hœ³²Ž[.DX§	X9Pj´_üÿ}l^ˆ€÷ŒÈjrƒv"P”Ð_>#D%Hìy	
4¾T¥<ó\ö ù#J›75÷ÐqŒÿ‹mÈËòN°=Âm‡Ï»Þ{"ÿ}
Î«Z‡MÄw/orž/	chÁLÁnK/:aÈ?wee?™Å%`M˜–Ãà.ó
F#ApAx†¥Uníg3LÇRNº•R¹VØ)Nó<ÉI€
iäÀ\ÛÀ‰Z©»¾a²;¿ŽëN½cGàØ7#Àq<Biìß3òì¾Ž<_iþ(ò|¬p…]2¦2@X¼Êãa7ëÒ—à£¢4wZ7¿†€âÎ{Td'\ªò…§ì7r·€2ÀXcŠ¹jë®×lšˆq3w3¯f°ô\ðöé¯rž]9Ã+fæaŒ•+‘°Á…y,‹vœU%Ä\òÎJ]è›Ä¸i6r!ñ²	´õ*Ð\Š'o‚€,5—b¾d0%µòJê“%ã+™€t& .‡PéV›€»©Å$ô’¡G12ë’%*OPÔ" \ŽxÓº$“ 9]’`„Ñ|}¼8/ÙµI¨ÙÇoIº™t¸ûg_‘}31>‰È¼{¸Ù€a]¶lÆ«÷ð
;í6

**Comment by benjjneb** [comment]
This may be an issue with the files being compressed and cutadapt not realizing it.
By default, `filterAndTrim` will output gzipped fastq files.
But cutadapt may not auto-detect that, and just rely on the file extensions to tell it whether the files are compressed or not.

If you try adding `compress=FALSE` to the `filterAndTrim` calls, does that fix the issue with cutadapt?

**Comment by EcoGinger** [comment]
> This may be an issue with the files being compressed and cutadapt not realizing it.
> By default, `filterAndTrim` will output gzipped fastq files.
> But cutadapt may not auto-detect that, and just rely on the file extensions to tell it whether the files are compressed or not.
> 
> If you try adding `compress=FALSE` to the `filterAndTrim` calls, does that fix the issue with cutadapt?

Thank you! That was the issue. My files aren't compressed, so it must have been confusing it. It seems to have worked, but I do still have some primers showing up (see attached image). I did have a number of errors thrown at me while cutadapt was running. Cut this by why? I am pasting an example of the error below.

"=== Second read: Adapter 4 ===

Sequence: TTCAAAGATTCGATGATTCAC; Type: regular 3'; Length: 21; Trimmed: 9398 times

No. of allowed errors:
0-9 bp: 0; 10-19 bp: 1; 20-21 bp: 2

Bases preceding removed adapters:
  A: 3.0%
  C: 3.8%
  G: 87.0%
  T: 6.3%
  none/other: 0.0%
WARNING:
    The adapter is preceded by "G" extremely often.
    The provided adapter sequence could be incomplete at its 3' end.

Overview of removed sequences
length	count	expect	max.err	error counts
3	337	1703.6	0	337
4	349	425.9	0	349
5	95	106.5	0	95
6	20	26.6	0	20
7	18	6.7	0	18
8	14	1.7	0	14
9	76	0.4	0	22 54
10	5003	0.1	1	1744 3259
11	1004	0.0	1	2 1002
12	39	0.0	1	12 27
14	8	0.0	1	2 6
19	3	0.0	1	1 1 1
20	14	0.0	2	1 5 8
21	620	0.0	2	186 215 219
23	1	0.0	2	0 0 1
24	3	0.0	2	0 0 3
25	9	0.0	2	0 2 7
27	3	0.0	2	0 3
29	1	0.0	2	0 1
30	4	0.0	2	1 0 3
31	35	0.0	2	2 6 27
32	19	0.0	2	1 5 13
33	76	0.0	2	6 26 44
34	40	0.0	2	0 13 27
35	465	0.0	2	27 115 323
36	560	0.0	2	26 165 369
37	248	0.0	2	18 63 167
38	83	0.0	2	8 22 53
39	2	0.0	2	1 1
40	2	0.0	2	0 2
41	19	0.0	2	3 4 12
42	23	0.0	2	5 9 9
43	12	0.0	2	2 2 8
44	13	0.0	2	0 5 8
53	1	0.0	2	0 0 1
81	1	0.0	2	0 0 1
85	6	0.0	2	0 0 6
86	1	0.0	2	1
87	37	0.0	2	13 14 10
88	58	0.0	2	13 21 24
89	72	0.0	2	18 26 28
90	1	0.0	2	0 1
131	1	0.0	2	0 0 1
132	1	0.0	2	1
170	1	0.0	2	0 0 1


WARNING:
    One or more of your adapter sequences may be incomplete.
    Please see the detailed output above." 
![Primer removal](https://user-images.githubusercontent.com/57043568/95631455-5b903580-0a49-11eb-8d77-ffdea432cb28.png)

**Comment by benjjneb** [comment]
TBH if this isn't ITS data, I don't recomment using cutadapt at all. I would just remove the primers based on their fixed lengths.

But... that output is fine, there are a few extraneous unremoved hitsa t the end, but not so many that they are a major concern.

**Comment by EcoGinger** [comment]
@benjjneb It is ITS data, but I'm beginning to suspect the quality and whether I can actually use it at all. The quality profiles for the samples are not good. 
![Forward Quality](https://user-images.githubusercontent.com/57043568/95632589-97c49580-0a4b-11eb-8ce2-3d1317f012d4.png)
![Reverse Quality](https://user-images.githubusercontent.com/57043568/95632590-985d2c00-0a4b-11eb-8d13-21a78e2c2694.png)

**Comment by benjjneb** [comment]
That's not great, but not unusuable I don't think. I would not be afraid to lose a significant amount of reads at the filtering stage though -- losing half the reads (or more sometimes) is often preferable when you are keeping the good (and much more informative) half of the reads.

I'd also note that at least one of your samples (Mfisinoculum) has very few reads, and may represent either a PCR failure or something with no target DNA in it.

**Comment by EcoGinger** [comment]
@benjjneb Thanks for all of your help! Most of the inoculum samples are like this. All of them were amplified at the same time, so I think that it was probably a PCR failure.
