### ISSUE TITLE
Taxonomic assignment with mitochondrial sequence reference libraries

### ISSUE THREAD

**Issue by Salps** [benjjneb/dada2#1155]
I would like to use the dada2 pipeline to assign mitochondrial sequence data to species. Formatted sequence reference libraries are only found for nuclear genes.

Do you have any pipeline to develop a sequence reference library (from BOLD or Genbank) in a dada2 format to be used with the assignTaxonomy command?

It would be great if you have any suggestions

**Comment by benjjneb** [comment]
Sorry we do not have any official recommendations for how to build an appropriate mitochondrial gene reference database (other than the formatting so it would work with `assignTaxonomy`/`assignSpecies`).
