### ISSUE TITLE
Lingering concerns about learnErrors output

### ISSUE THREAD

**Issue by vfonti** [benjjneb/dada2#1156]
Hi everyone,
I am analysing some 16S reads (V4-V5 region, 2x250). Unfortunately, protocol and machine used for sequencing are "obscure" (we asked for MiSeq but the group providing the service just told us they used "a new machine"). I have reasons to think they used NovaSeq but I am not sure.
My problem is that after running learnErrors function I got quite unusual patterns (to me). Please, have a look and tell me what you think:

Fw reads:
![plotErrors_Fw](https://user-images.githubusercontent.com/9551014/95661021-3f18f980-0b2c-11eb-888b-bfbb52729848.jpeg)

Rev reads:
![plotErrors_Rev](https://user-images.githubusercontent.com/9551014/95661056-7daeb400-0b2c-11eb-8b1e-c2706588ebb5.jpeg)

I am concerned by the fact that the error model doesn't seem to fit the real data very well. I tried to get to the root of the problem but I still have my doubts. After looking for similar cases, I've found that Ben suggests to enforce monotonicity in the fitted error model. However, I am not so good at coding in R and I simply applied a code I found in [#722.](https://github.com/benjjneb/dada2/issues/722) . That's what I have done:

`errF = learnErrors(filtFs, qualityType = "Auto")`
`errR = learnErrors(filtRs, qualityType = "Auto")`
`plotErrors(errF, nominalQ=TRUE)`
`plotErrors(errR, nominalQ=TRUE)`       

`# And then I tried:`
`errF.mat <- getErrors(errF)         `
`View(errF.mat)         `                  
`errR.mat <- getErrors(errR)`

`for(trans in c("A2C", "A2G", "A2T", "C2A", "C2G", "C2T", "G2A", "G2C", "G2T", "T2A", "T2C", "T2G")) {
errF.mat[trans,] <- pmax(errF.mat[trans,], errF.mat[trans,ncol(errF.mat)])
}`

`for(trans in c("A2C", "A2G", "A2T", "C2A", "C2G", "C2T", "G2A", "G2C", "G2T", "T2A", "T2C", "T2G")) {
errR.mat[trans,] <- pmax(errR.mat[trans,], errF.mat[trans,ncol(errR.mat)])
}`
`plotErrors(errF.mat, nominalQ=TRUE, obs = TRUE)`
`plotErrors(errR.mat, nominalQ=TRUE)`

First of all, I don't understand why I get plots with no observations: 
![plotErrors_Fw_modified](https://user-images.githubusercontent.com/9551014/95661598-e4ce6780-0b30-11eb-9af8-8e47c1c79faa.jpeg)
![plotErrors_Rev_modified](https://user-images.githubusercontent.com/9551014/95661602-e9931b80-0b30-11eb-8886-6533c15eaeb7.jpeg)
But most importantly, I would like to understand if I can use the loess modelled errors as they are or if I should modified the model. And, in the latter case, how should I do....
Obviously, any comment is welcome.

I hope somebody can help me.
Have a nice WE.

**Comment by benjjneb** [comment]
> But most importantly, I would like to understand if I can use the loess modelled errors as they are or if I should modified the model.

I think your solution is fine, and I personally would use the modified error model to safeguard against false-positives due to underestimated error rates at average qualities 30-36. However, they both probably work pretty well, as because you have binned quality score data, there is almost no average qualities in the relevant range.

> First of all, I don't understand why I get plots with no observations:

The output of `learnErrors` is a little bit more complex than a simple matrix, it includes both a matrix of observed and fitted error rates. You've extracted just the fitted error rates above (see `getErrors` for a bit more detail). Thus when you use `plotErrors`, it only has access to the fitted error rates and that's all that is shown.

**Comment by vfonti** [comment]
Hi Ben,
Thanks a lot! I will do as you suggest.
