### ISSUE TITLE
Trouble Installing dada2 using Rstudio

### ISSUE THREAD

**Issue by brittanyaseibert** [benjjneb/dada2#1160]
Hello, 

I am having some trouble with installing dada2 using RStudio.  Any help would be so greatly appreciated. I tried to install using devtools and manually. 

Thank you so much!
Brittany 

------------------------------------------------------------------------
When I try to install using devtools with the following command: 

devtools::install_github("benjjneb/dada2")

I get this output: 

✓  checking for file ‘/private/var/folders/j6/4pc8mjsd1bv68n2dbh86xt1m0000gp/T/Rtmpho6RjG/remotes6fa940fde695/benjjneb-dada2-9b9184a/DESCRIPTION’ ...
─  preparing ‘dada2’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘dada2_1.17.3.tar.gz’
   
* installing *source* package ‘dada2’ ...
** using staged installation
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppParallel/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
In file included from ./../inst/include/dada2.h:7:
In file included from ./../inst/include/dada2_RcppExports.h:7:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include/Rcpp.h:27:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include/RcppCommon.h:29:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:304:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/math.h:301:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdlib.h:20:15: fatal error: 'stdlib.h' file not found
#include_next <stdlib.h>
              ^~~~~~~~~~
1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘dada2’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/dada2’
Error: Failed to install 'dada2' from GitHub:
  (converted from warning) installation of package ‘/var/folders/j6/4pc8mjsd1bv68n2dbh86xt1m0000gp/T//Rtmpho6RjG/file6fa95d2d6188/dada2_1.17.3.tar.gz’ had non-zero exit status

------------------------------------------------
I then tried to install in manually using the following code: 

install.packages("/Users/baseibert/dada2",repos = NULL,
+                  type = "source",
+                  dependencies = c("Depends", "Suggests","Imports"))

and get the following Output: 

* installing *source* package ‘dada2’ ...
** using staged installation
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppParallel/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
In file included from ./../inst/include/dada2.h:7:
In file included from ./../inst/include/dada2_RcppExports.h:7:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include/Rcpp.h:27:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include/RcppCommon.h:29:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include/Rcpp/r/headers.h:67:
In file included from /Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:100:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:304:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/math.h:301:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdlib.h:20:15: fatal error: 'stdlib.h' file not found
#include_next <stdlib.h>
              ^~~~~~~~~~
1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘dada2’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/dada2’
Warning in install.packages :
  installation of package ‘/Users/baseibert/dada2’ had non-zero exit status

**Comment by benjjneb** [comment]
Did you try installing through the recommended Bioconductor route? https://benjjneb.github.io/dada2/dada-installation.html

**Comment by brittanyaseibert** [comment]
Hello,

I apologize for the very late response.

Yes. It ended up being a problem with my R and I had to uninstall and reinstall R for it to work.

Thank you so much for your help and quick response! I apologize if I wasted your time.
Brittany
