### ISSUE TITLE
ERROR from filterAndTrim

### ISSUE THREAD

**Issue by CaiWang0503** [benjjneb/dada2#1163]
when i run filterAndTrim, why i get this error?
> filterAndTrim(fnFs, fnFs.filtN, fnRs, fnRs.filtN, multithread =T)
Error in filterAndTrim(fnFs, fnFs.filtN, fnRs, fnRs.filtN, multithread = T) : 
  These are the errors (up to 5) encountered in individual cores...
Error in (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0,  : 
  Mismatched forward and reverse sequence files: 85500, 86375.

thank you

**Comment by benjjneb** [comment]
Your forward and reverse read files have different numbers of reads. Did you perform a filtering step prior to this, that could cause that mismatch? Or you may want to inspect `cbind(fnFs, fnRs)` and make sure the forward/reverse files are matched up correctly.

**Comment by CaiWang0503** [comment]
ah, thank you.

**Comment by cccchensir** [comment]
how do you fix it?suffering the same issue.....

**Comment by cccchensir** [comment]
> ah, thank you.

how do you fix it?suffering the same issue.....

**Comment by cccchensir** [comment]
> Your forward and reverse read files have different numbers of reads. Did you perform a filtering step prior to this, that could cause that mismatch? Or you may want to inspect `cbind(fnFs, fnRs)` and make sure the forward/reverse files are matched up correctly.

i have no any ideal for figuring it out. can you explained more concretely?here are debug informations:
1) Filtering Error in filterAndTrim(unfiltsF, filtsF, unfiltsR, filtsR, truncLen = c(truncLenF,  : 
  These are the errors (up to 5) encountered in individual cores...
Error in (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0,  : 
  Mismatched forward and reverse sequence files: 55746， 54717.
Error in (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0,  : 
  Mismatched forward and reverse sequence files: 54717， 21166.
Error in (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0,  : 
  Mismatched forward and reverse sequence files: 21166， 55746.
Error in (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0,  : 
  Mismatched forward and reverse sequence files: 55746， 54717.
Error in (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0,  : 
  Mismatched forward and reverse sequence files: 54717， 21166.
Traceback (most recent call last):
  File "/home/CauchyChen/anaconda3/envs/qiime2-2020.2/lib/python3.6/site-packages/q2_dada2/_denoise.py", line 257, in denoise_paired
    run_commands([cmd])
  File "/home/CauchyChen/anaconda3/envs/qiime2-2020.2/lib/python3.6/site-packages/q2_dada2/_denoise.py", line 36, in run_commands
    subprocess.run(cmd, check=True)
  File "/home/CauchyChen/anaconda3/envs/qiime2-2020.2/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['run_dada_paired.R', '/tmp/tmpmmuwp4hl/forward', '/tmp/tmpmmuwp4hl/reverse', '/tmp/tmpmmuwp4hl/output.tsv.biom', '/tmp/tmpmmuwp4hl/track.tsv', '/tmp/tmpmmuwp4hl/filt_f', '/tmp/tmpmmuwp4hl/filt_r', '100', '100', '0', '0', '2.0', '2.0', '2', 'consensus', '1.0', '0', '1000000']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/CauchyChen/anaconda3/envs/qiime2-2020.2/lib/python3.6/site-packages/q2cli/commands.py", line 328, in __call__
    results = action(**arguments)
  File "</home/CauchyChen/anaconda3/envs/qiime2-2020.2/lib/python3.6/site-packages/decorator.py:decorator-gen-455>", line 2, in denoise_paired
  File "/home/CauchyChen/anaconda3/envs/qiime2-2020.2/lib/python3.6/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    output_types, provenance)
  File "/home/CauchyChen/anaconda3/envs/qiime2-2020.2/lib/python3.6/site-packages/qiime2/sdk/action.py", line 390, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/home/CauchyChen/anaconda3/envs/qiime2-2020.2/lib/python3.6/site-packages/q2_dada2/_denoise.py", line 272, in denoise_paired
    " and stderr to learn more." % e.returncode)
Exception: An error was encountered while running DADA2 in R (return code 1), please inspect stdout and stderr to learn more.

Plugin error from dada2:

  An error was encountered while running DADA2 in R (return code 1), please inspect stdout and stderr to learn more.

See above for debug info.

Thank you a lot!

**Comment by benjjneb** [comment]
@cccchensir

For example, this error message: `Mismatched forward and reverse sequence files: 55746， 54717.` indicates that a matched forward read file and reverse read file had different numbers of reads in them, 55746 and 54717 respectively.

I see you are running dada2 through QIIME2, so you are probably best off asking your question at the QIIME2 forum, as QIIME2 is handling the organization of the files. You may have a sample name scheme that is incompatible with their parsing, for example by including underscores in the sample names.
