### ISSUE TITLE
Convert SINTAX format to file useable as DADA2 database

### ISSUE THREAD

**Issue by termithorbor** [benjjneb/dada2#1167]
Hi all,

is there an easy way to convert a SINTAX formated.fas file into a file useable with the assignTaxonomy function?

I am thin king of the SINTAX files of the PLANiTS database: https://github.com/apallavicini/PLANiTS

Thank you very much in advance.

**Comment by benjjneb** [comment]
If by "easy way" a pre-existing script to convert between them, then no. However inspecting the format it should be pretty straightforward. Example Sintax ID line:

```
>KU904773.1;tax=p:Chlorophyta,c:Ulvophyceae,o:Cladophorales,f:Cladophoraceae,g:Basicladia,s:unknown Basicladia ;
```

So to convert it to `assignTaxonomy` format, one just needs to remove the initial accession number and the `tax=` part, and then convert the commas separating the levels to semicolons, i.e.

```
>p:Chlorophyta;c:Ulvophyceae;o:Cladophorales;f:Cladophoraceae;g:Basicladia;s:unknown Basicladia ;
```

**Comment by andzandz11** [comment]
Do never use the PLANiTS database with k-mer identifiers. It will produce terribly inaccurate data. The PLANiTS has been created by performing "sequence collapse by identity %" which removes a lot of unique k-mers. In general I would not recommend to use any plant database that uses bins of any sort, it is a grave technical error.
