### ISSUE TITLE
Minimal output in seqtab and taxonomy list

### ISSUE THREAD

**Issue by mf0083** [benjjneb/dada2#1168]
Hello! I am very new to this process and am trying to follow the DADA2 workflow for pair ended big data with some 16s files in the fastq.gz format. I have tried several small changes to the filtering parameters but am only getting 5 items in the taxonomy list when I know there should be much more. 

These are the filtering parameters I used. I am not sure how to optimize them for my data. I also read that trimming the primers using trimLeft can be very helpful, but I don't know how to determine the length of the primers? 

filterAndTrim(fwd=file.path(pathF, fastqFs), filt=file.path(filtpathF, fastqFs),
                    rev=file.path(pathR, fastqRs), filt.rev=file.path(filtpathR, fastqRs),
                    truncLen=c(220,180), maxEE=2, truncQ=2, maxN=0, rm.phix=TRUE,
                    compress=TRUE, verbose=TRUE, multithread=TRUE)

After filtering, I got this output for my 3 samples:
                                                                reads.in reads.out
Psych-27_S31_L001_R1_001.fastq.gz   222774    188858
Psych-29_S32_L001_R1_001.fastq.gz   294199    230120
Psych-36_S33_L001_R1_001.fastq.gz   171374    144661

This is the output after the merger step: 

Processing: Psych-27 
Sample 1 - 188858 reads in 32402 unique sequences.
Sample 1 - 188858 reads in 58871 unique sequences.
Processing: Psych-29 
Sample 1 - 230120 reads in 65118 unique sequences.
Sample 1 - 230120 reads in 70157 unique sequences.
Processing: Psych-36 
Sample 1 - 144661 reads in 24878 unique sequences.
Sample 1 - 144661 reads in 45790 unique sequences.

Does anyone have an idea of where I am going wrong/losing data? Thanks!

**Comment by benjjneb** [comment]
First, I would recommend retrying this using [the current version of the tutorial workflow](https://benjjneb.github.io/dada2/tutorial.html). Upgrades to the package now allow the tutorial to work well even for "Big Data" sets, and there is more informative help text and process checking in the tutorial workflow.

Second, what is the amplicon that you are sequencing? I.e. what region, what primers, and are the primers included on the reads?

**Comment by mf0083** [comment]
Thank you for getting back to me! I tried the current version of the workflow and it worked much more quickly for me, although my output is still quite small.

It was 16s sequencing, but I'm not sure what the primer is. I am working on this for someone else and have been waiting to hear back from them on what the primers are. Is there any other way I can figure out what the primers are from the fastq files?

**Comment by benjjneb** [comment]
What you really need to know is what part (if any) of those primer constructs are included in the sequencing reads. This should be something that the folks who did the sequncing can tell you.

Alternatively, you can simply open up a forward read file, and compare the start of those reads to the "I5amp" sequence, to determine what part (if any) is included at the starts of the reads. And then likewise for the reverse reads.

**Comment by mf0083** [comment]
I don't see any overlap between the very beginning of the files and the 15amp sequence. So I guess something else must be causing problems for me?

**Comment by benjjneb** [comment]
Can you post the first 4 sequencing reads from the fastq file of an example forward file?

**Comment by mf0083** [comment]
Is this what you are looking for? 

@M00780:262:cp9nv:1:1101:20333:1726 1:N:0:CGATGT+TCTTCT
TTTACCTACGGGAGGCTGCAGTGGGGAATTTTGTTCTTTGTGCTTTTCCCTCTTCCTCCCTCTCCTCTTGTTTTTTCTTTTTTCTCTTTTTTTTCTTCTCTTTCTTCTTTCTCCCCTTCCTTTTCTTTTCCTTTCTTTTTTTCCCCTTCTTTCTTCCTTCCTCCCTCCTCTTTTTTTCCTCCCCCCCTTTCTTTTTCCTTTTTTTCTTTTTTTTTTTTTTTTTTTTTCTTCTTTTCTTTTCTTTTTTTTCTTTTCTTTCCCCTTCCCCTTTTCTTCTTTCCTTTCTTTCTTTCTTTTTTT
+
-8A@CEFCFFDD7@@CFCCD@C<A8+,,C,<C,,-6,,<,,,,,,,,66,;,-6;<,,;,,;,6;,,,:,,,:,,+,,,,9,7,66,,<,C+7+,,,,5,9,55,,,,,,,,,,,+,,,4,55,5,,9,5,5,,59,,,,++,,54,,37,,,5,5,,,5,,,3+,,3,,,,3,,5+,,3,,++**1*,,,,22,4,,2,,424*26,,,4*1*****1*/*/2***++++++++++**2*2++3+1))*+++00***+2+0**0*0***2+02+**++++++*00*0).)*)00***))
@M00780:262:cp9nv:1:1101:8906:1742 1:N:0:CGCTGT+TCTTCT
TTCCTACGGGCGGCTGCAGTGGGGAATATTTCCCATTTTGGTCCACCCTTTTCCCCCCCTTCCCCTTTTTTTTTTTCTTTTTTCTTTTTTTTTTCTCCTTTCTTTTTCTCCCCTTTTTCCTTTTCTTTTTTTTTTTTCTCCTTCTCTCTTCTTTCCCCCTCCCTCTTTTTTCCTTTTTCTCCCCCCTTTTTCCTTTTTTTCTTTTTTTTTTTTTTTCTTTTTCTTTTTTTCTTTTCTTTTTTTTTTTCCTTCTTCTTACCCTCTTTTCTTCTTTTTTTCCTCTTTTTCTTTTTTTTTTTTT
+
-8BBCAFCCBC@+@F>FA@FC,<7:,E,CC,,,6-,;,,,+,,,,6669,,:-6,,8++6,66,9,9,5,++++++,,,59?44,,,<?+=+++333,3,8,83,,,,,,8,+,,,3,,3,,3,,<83,,*******,222,,22,,22,,,8,,2,+1***1+2+,,,,/++00++++++3***1/22+2+0++++31*+3++00*1********++2++0+++++0:*++++00+**029****2*0*0+3+*22*+2+2/2++++2**+32:*)*++2+0**1/)6.)*)0)))).))
@M00780:262:cp9nv:1:1101:15738:1746 1:N:0:CGATGT+TCTTCT
TGGCCTACGGGCGGCTGCAGTGGGGGATATTGCACAATGGGGGGAACCCTTTTCCCCCCCCCCCCCTTTTTTTTCTTTTTTCTTCTTCTTTTTTCTCCCTTTCTTCTCTTTCCCCTCTTTCTTTTCCTTTCTTTTTTTCCCCTTCTCTCTTCTTTCCCCCCTCCTCCTTTTTTCTTTTCTGTCCACCTTTTTCCTTTTTTTCTTTTTTTTTTTTTTTCTTTTTCTTCCTTCCCTTCCTTCTTTTTCTTCCCCTTCCCCCCCCCCTCTCCTTCCCTTTCCCCCTTTCTTCTTTTTTCCCTC
+
888ACGDGC;7FCC@FCGFGG88@@77@,CE,9,:,,:,,,,++++:838,,8-:,,8++3+53***8,,,4**,,,,,8*,8<,,,,,<,2,*,,0002,3,,,,,,,,,,,,,0*0,,,,,2,0,2,,,0,,,,**,0,,,,00,,20+0,2,22+*/**//****2++0*0+0++++++3+++0*22+00++++33**+0+++2*2***/****++3+++++++++3+0*++0****0*2++++*000****00***1*//****22*2**+0*+++0**0****)))*)*0)1***
@M00780:262:cp9nv:1:1101:14916:1757 1:N:0:CGATGT+TCTTCT
TTCCTACGGGCGGCAGCAGTGGGGAATCTTCCGCAATGGGCGCAAGCCTTTCTTACCACTTCCCCTTTTTTGTTTTATTCCTTCTTTTTTTTTTCCTCTTTCCTTTTCGTTCCTCTTTTTTTTTTTTTTTTTTTTTCCTTTTTTTCTCTTTTTTTTCCTTTTTCCCCTTCTTTCTTCTTTCCCCCATCCTCCTTCTTTCTTTTTTTTCTTTCTTTTTCCTTTTTCTCTTTTCTTTTTTTTTTCTTTTTCTTTTTCTTTTTTCTTTTTTTTTTTTCTTCCCCTCTTCCTTTTTTTTCCTTTT

**Comment by benjjneb** [comment]
Yep that's it. What immediately jumps out is that your sequencing reads are highly repetitive. This probably indicates serious problems with the sequencing process. Can you post the output of `plotComplexity("path/to/forward_reads.fastq")`?

**Comment by mf0083** [comment]
Here is one of them, would you like to see any others?

![complexity_Psych27_R1](https://user-images.githubusercontent.com/57810208/97191404-39065800-177d-11eb-86c9-c75477d607cf.jpeg)

**Comment by benjjneb** [comment]
Something isn't lining up here. Is this from the same file that those 4 reads posted above were from? This plot indicates there are essentially no low-complexity reads in the sample, but the posted reads were all low complexity.

**Comment by mf0083** [comment]
I just double checked and they are from the same file? This is what I typed for the plot: plotComplexity("FOLDER_Path/Cole-Psych-27_S31_L001_R1_001.fastq"). That Cole-Psych-27 file is where I grabbed the sequencing reads from as well. Would you like me to post the reads and the complexity plot from a different file?

**Comment by benjjneb** [comment]
Can you post 4 reads from the middle of that file then? Maybe the first XX reads are bad ones for some reason.

**Comment by mf0083** [comment]
CCCCCGGGGGGGGFGGGGGGGGGGGDFFGGGFFFGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFEFGGECFGGGGGGGGGGGGFFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCFFGGGFGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGFFGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGG?EFGCFGGGFGFGGGFGGGGG+
@M00780:262:cp9nv:1:1118:13754:21257 1:N:0:CGATGT+TCTTCT
GTCCTACGGGAGGCAGCAGTGAGGAATATTGGTCAATGGGCGCGAGCCTGAACCAGCCAAGTAGCGTGCAGGACGACGGCCCTATGGGTTGTAAACTGCTTTTATACGGGGATAAAGTATGCCACGTGTGGTTTATTGCAGGTACCGTATGAATAAGGACCGGCTAATTCCGTGCCAGCAGCCGCGGTAATACGGAAGGTCCGGGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCCGGGTTTTAAGCGTGCCGTGAAATGTCGGGGCTCAACCTTGACACTGCGGCGCGAA
+
CCC?CFGGGGFGGGGGGGGGGGGGGGDGGGFGGFGFGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGEGFFEGFGGGGGGGGGGFGFFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGGEGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGEEGGGGFGGGGEEGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGFGGFGFFFG3C>EGEG
@M00780:262:cp9nv:1:1118:26139:21264 1:N:0:CGATGT+TCTTCT
TCACCTACGGGCGGCAGCAGTGGGGAATATTGCACAAGGGGAGAAAGCCTGATGCAGCAACGCCGCGTGAAGGAAGAAGGCCTTCGGGTCGTAAACTTCTGTCCTTGGGGAAGAAGAACTGACGGTACCCAAGGAGGAAGCCCCGGCTAACTACGTGCCAGCAGCCGCGGCAATACGCAGGGGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGAGTACGTAGGTGGCAACCTAAGCGCAGGGTTTAAGGCAATGGCTTAACCATTGTTCGCCCTGCGAACTGGGATGCTTGAGTGCAGG
+
CCCCCE<;@BC@7B6@:F<EF@FFECF;@,CF,CFG<6@FE+CC,E@FA6<FDECFAEGFFFGG@EE==CFAEEFFCD<?,,BE,=+>BB:C,==<,<B,5CCFFEGF?EGEGFEGFFFFF=8:C>+CFFFGGFFFGGGGGGFGD:F*<CFGGG7@87>DFEFCC3<7*1*4<,?CC:<F<7CCEG:8;*2/8CGFE**2;@7C+9?FCGGGGG9@>EGGG8C88AFEFGFFF6:FGCEDGEE8C6EFF+CGGGCFGFF*A?FGGGF79<CE>EGGGCE8:EGGF5>4>44>F5?FD97CC
@M00780:262:cp9nv:1:1118:9279:21265 1:N:0:CGCTGT+TCTTCT
TCCCTACGGGGGGCTGCAGTAGGGAATCTTCCACAATGGGCGAAAGCCTGATGGAGCAACGCCGCGTGAGTGAAGAAGGTTTTCGGATCGTAAAGCTCTGTTGTTGGTGAAGAAGGATAGAGGTAGTAACTGGCCCCTATTTGACGGTAATCAACCAGAAAGTCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCAAGCGTTGTCCGGATTTATTGGGCGTAAAGCGAGCGCAGGCGGAAAGATAAGTCTGATGTGAAAACCATGGGCTCAACCTGTGGCCTGCATTTG
+
CCCCCGGGGGGGGFGGGGGGGGGGGGGGGGGFBFGGGEEF-@@CCEGGFGGGGGGGGGGGGGGGGGGFGGFFGGGFGGG@@CFBF@@FGGGGGGGEFEDBDFGGGGGBFGGGGGFGFGGG9FGGGGGGGGGGGGGGGGGGGCFGGGGGGGGGGGGFGGGDGGGGGGGDGGGFCGGGGGGGGFFGGGGGGGGGCGGGFCFFGGEFFGGGGGFGGECGFFGEGEEGFGGFFCCEGGDGGGGCGGDE>E>ECEEG>CFG+AFCGFC+CFGCFCF@FG=CEFFGFDFGGGGGFFFGFGFGG9>GG
@M00780:262:cp9nv:1:1118:22998:21278 1:N:0:CGATGT+TCTTCT
GATACCTACGGGTGGCTGCAGTAGGGAATCTTCCACAATGGGCGCAAGCCTGATGGAGCAACACCGCGTGAGTGAAGAAGGGTTTCGGCTCGTAAAACTCTGTTGTTGGAGAAGAACGTGCGTGAGAGTAACTGTTCACGCAGTGACGGTATCCAACCAGAAAGTCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCAAGCGTTATCCGGATTTATTGGGCGTAAAGCGAGCGCAGGCGGTTGCTTAGGTCTGATGTGAAAGCCTTCGGCTTAACCGAAGAAGTGCAT

**Comment by benjjneb** [comment]
Your primers are on your reads, but you also have variable starting positions of your reads, probably because of the use of heteogeneity spacers during sequencing. See alignment of reads and the forward primer construct below:

```
AATGATACGGCGACCACCGAGATCTACACNNNNNNTCGTCGGCAGCGTCAGATGTGTATAAGAGACAGNCCTACGGGNGGCWGCAG
                                                                   GTCCTACGGGAGGCAGCAGTGAGGAATATTGGTCAATGGGCGCGAGCCTGAACCAGCCAAGTAGCGTGCAGGACGACG...
                                                                  TCACCTACGGGCGGCAGCAGTGGGGAATATTGCACAAGGGGAGAAAGCCTGATGCAGCAACGCCGCGTGAAGGAAGAAG...
                                                                   TCCCTACGGGGGGCTGCAGTAGGGAATCTTCCACAATGGGCGAAAGCCTGATGGAGCAACGCCGCGTGAGTGAAGAAGG...
                                                                 GATACCTACGGGTGGCTGCAGTAGGGAATCTTCCACAATGGGCGCAAGCCTGATGGAGCAACACCGCGTGAGTGAAGAAG...
```

In order to process this data, you will need to use an external program to remove the primers from the reads (both forward and reverse) first, and then you can enter the dada2 workflow, at which point you would not use `trimLeft` at all. I would also highly recommend getting a complete description of the library preparation performed by the sequencing provider, if only to double-check this diagnosis.

**Comment by mf0083** [comment]
Thank you so much for providing such thoughtful and quick responses. I appreciate it so much. Is there a particular external program you would recommend? I saw cutadapt and trimmomatic mentioned in the FAQ.

**Comment by benjjneb** [comment]
I use cutadapt myself, but either will work. You can take a look at the cutadapt part of the DADA2 ITS tutorial for an example of using that tool to remove primer sequences: https://benjjneb.github.io/dada2/ITS_workflow.html

**Comment by mf0083** [comment]
For this approach, do I follow along the ITS tutorial through the remove primers step and then switch back to the 16s tutorial and just make sure to use consistent variable names between the two tutorials?

**Comment by benjjneb** [comment]
> Error in add(bin) : internal: buf !=

As far as we know, these errors have always arisen before from pre-processing of the sequence data that broke the fastq format. In at least one case this led to mismatches in the lengths of the sequences and the associated quality annotations.

Have your fastq files been preprocessed in anyway before getting into your hands? If so, can you get the un-processed files? (i.e. the output of Illumina's bcl2fastq).

**Comment by mf0083** [comment]
They weren't pre-processed at all, but I was able to talk with the group that processed the data and remove the primers. The tutorial workflow was working great for me, but I ended up losing almost all the reads at the merging stage. 

I attached images of the output from the merging stage and from the syntax to track reads through the pipeline. For filtering, I used (truncLen=c(230,150), maxN=0, maxEE=c(2,2), truncQ=2). The tutorial says to make adjustments here if merges are unsuccessful, but the quality of my reverse reads is really sharply dropping in the mid 100s level, so I'm not sure if that is a good idea. Any thoughts on what is causing this? 

<img width="697" alt="DADA2 merging" src="https://user-images.githubusercontent.com/57810208/98447548-b8881580-20f3-11eb-98e0-0f3c1d960d9f.png">
<img width="516" alt="Track reads" src="https://user-images.githubusercontent.com/57810208/98447551-ba51d900-20f3-11eb-92e8-b28859d49424.png">

**Comment by benjjneb** [comment]
Usually when reads failt to merge like that, it is because the reads were truncated too much and no longer overlap. How long is the amplicon you are sequencing? You `truncLen`s need to add up to that length plus another 20 bases to ensure overlap.

If the reverse reads are very bad quality, it is also valid to simply proceed with the forward reads.

**Comment by mf0083** [comment]
Thank you! When I used the reverse files only it worked so much better! I think it is 300 amplicon because that is the x-axis limit on my quality plot, but I'm not 100% sure. I tried loosening up the truncLen substantially, and it has been stuck on learnErrors for the reverse reads for over 3 hours.

I think I am going to keep trying with just the forward reads for now. I was able to make the seqtab and taxonomy list. In what type of format should I save these files so that I can read them back into R to use for phyloseq? I tried writing the seqtab to a csv, and when I read in back in and tried this code:

ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE), tax_table(taxa))

It resulted in this error: 

Error in validObject(.Object) : invalid class “otu_table” object: 
 Non-numeric matrix provided as OTU table.
Abundance is expected to be numeric.

**Comment by benjjneb** [comment]
> In what type of format should I save these files so that I can read them back into R to use for phyloseq? I tried writing the seqtab to a csv, and when I read in back in and tried this code:

I highly recommend using the `saveRDS`/`readRDS` set of functions to save R objects to files, and then read them back in. With those functions you will get back exactly what you saved. When going to csv file intermediates, a lot of extra information (the data types, how row.names and col.names are organized) can be lost, which leads to errors like what you are seeing.

**Comment by mf0083** [comment]
Ok great, thank you so much! I really appreciate all the thoughtful feedback.
