### ISSUE TITLE
Removing chimeras

### ISSUE THREAD

**Issue by Apanphil** [benjjneb/dada2#1169]
Hi Benj,

I am using dada2 v1.14 and i am trying remove chimeras from a single end reads
The code as in the tutorial: 
seqtab.nochim<-removeBimeraDenovo(seqtab,method="consensus",multithread=TRUE,verbose=TRUE)

Output: Error in removeBimeraDenovo(seqtab, method = "consensus", multithread = TRUE,  :
  Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.

How do i avoid this error in order to remove the chimeras in my single end reads?

Apanphil

**Comment by benjjneb** [comment]
How did you create `seqtab`? The `removeBimeraDenovo` function is saying its not in the expected format that would be created via the normal DADA2 worfklow. Was it possibly read in from a file?

What is the output of:
```
dada2:::is.sequence.table(seqtab)
class(seqtab)
seqtab[1:3, 1:3]
```

**Comment by Apanphil** [comment]
Thank you for asking that question.
 I created seqtab with this code: seqtab <- makeSequenceTable(dadaFs)

And then ran the chimera code: 
seqtab.nochim<-removeBimeraDenovo(seqtab,method="consensus",multithread=TRUE,verbose=TRUE)

It removed the chimera in the reads. Thank you
