### ISSUE TITLE
dada2::removeBimeraDenovo fails(?) with large sequence tables

### ISSUE THREAD

**Issue by FabianRoger** [benjjneb/dada2#117]
I am trying to run the DADA2 pipeline on a functional gene that we sequenced with 2*250 bp paired end Illumina chemistry (50 samples, 2.4 M paired reads total). 

First I tried to run it with the Primers on, which resulted in ~65 K sequence variants (after merging). With the primers cut off, ~1.7M reads remain, split in ~11K sequence variants before chimera checking. 

This seem to be too much sequences for ```removaeBimeraDenovo()``` to run (with default parameters). It does't crash but  it doesn't run in any reasonable time (< 3h), i.e. no message appear during that time. As I don't know how the runtime scales I don't know how long I should expect it to run?

Also, the sequence table contains singleton reads (135 / 11K). Doesn't dada2 exclude singletons during sequence inference? Or did I misunderstand that?

Any suggestions would be appreciated!

**Comment by benjjneb** [comment]
On singletons:

>singletons cannot appear in the raw output of the dada(...) function, but can appear after merging, if for example the reverse read of one member of a doubleton was misassigned due to low quality. This is relatively rare, but possible.

On the running time of `removeBimeraDenovo`:

What package version are you using, and what compute resources? The bimera functions were sped up significantly in the more recent 1.1 branch, and now can be multithreaded as well.

As long as you aren't running out of memory (and being forced into lots of slow swaps) the function will complete, but it may take a while especially if using version 1.0.3

**Comment by FabianRoger** [comment]
Sorry I was too fast. With the new, smaller sequence table, the function run in ~3h. It would be helpful though if there was a way to estimate the expectation, i.e. what running time would be reasonable or how it scales. I understand that this can be difficult though. 

The issue can be closed.

**Comment by benjjneb** [comment]
The newest version is available via github, and a mostly up-to-date version is available from [bioc-devel](https://www.bioconductor.org/developers/how-to/useDevel/) as well. At the next Bioconductor release (usually in October) these improvements will get pushed to the release branch that you are using, but until then the release version will stay the same (modulo possible bug fixes).
