### ISSUE TITLE
Dada2_trunclen

### ISSUE THREAD

**Issue by biohp90** [benjjneb/dada2#1170]
Dear all

I am very new to DADA2 and I am trying my best to analyze data using dada2. Our targeted organism is bacteria, Primer used: 

341F 5′-CCTACGGGNGGCWGCAG-3′

805R 5′-GACTACHVGGGTATCTAATCC-3′
Target region: V3-V4 region of 16S rRNA gene
During the analysis process, I am not sure I can choose trucLen parameter properly. For filter and trim, I used:

filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(280,190),
maxN=0, maxEE=c(2,2), trimLeft=c(20,20), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=FALSE)

I would be grateful If you can guide me how to select correctly trunclen parameter.
![plotqualityprofile_fnFs](https://user-images.githubusercontent.com/73317805/96938785-3bab4800-1506-11eb-9daf-dc10ff933850.png)
![plotqualityprofilefnRs](https://user-images.githubusercontent.com/73317805/96938791-3f3ecf00-1506-11eb-9bf1-79d385969279.png)

**Comment by benjjneb** [comment]
Basically you want to achive two things: First, keep enough sequence after truncation that your reads still overlap for later merging, and second truncate off the lowest quality bases at the ends of the reads. The first thing has priority.

So, V3V4 amplicons with primers sequenced (the "Illumina" protocol) will produce amplicons up to ~460nts in length. So your two `truncLen`s must add up to at least 460, and a bit more is nice to be on the safe side. Then you want to choose the forward/reverse truncation lengths to remove the most low-quality tail sequences. The reverse reads here drop in quality much sooner than the forward reads (as is typical) so the reverse truncation length should be shorter.

Put that together, and I'd probably end up very close to what you got: `truncLen=c(280,190)`. Maybe push it to `truncLen=c(290,180)`. One can always play around a bit if you want, but you seem to have made reasonable choices.
