### ISSUE TITLE
Problem in downloading SILVA_SSU_r132_March2018.RData

### ISSUE THREAD

**Issue by Zakeel-stack** [benjjneb/dada2#1171]
I was trying to download the SILVA_SSU_r132_March2018.RData database, but I could find it out. Instead I found another site at http://www2.decipher.codes/Downloads.html with a link to SILVA SSU r138 (modified). But, the problem is I don't know how to download it. I am trying this in a Windows machine. Can anyone help me please?

**Comment by benjjneb** [comment]
When I click on the SILVA_SSU_r132_March2018.RData link on the page you've provided, it downloads for me. When you click on that link, is it not downloading? You may want to check your "downloads" location or folder.
