### ISSUE TITLE
About sample dataframe in the tutorial 1.16

### ISSUE THREAD

**Issue by Zakeel-stack** [benjjneb/dada2#1172]
I am following the DADA2 pipeline tutorial 1.16 and I am new to this. I have most of the analysis with my dataset and am currently at phyloseq steps. The functions given for data.frame construction is quite confusing to me. My metadata is like the one given below.

group	status        tissue
Zak1        	Dis             Lf
Zak2 	Dis             Lf
Zak3 	Non_dis     Lf
Zak4 	Non_dis     Lf
Zak5 	Dis             Lf
Zak6 	Dis             Rt
Zak7 	Dis             Sm

I have group and status in one csv file and group and tissue in another csv file. 
I have fastq files were also named as Zak1_R1.fastq, Zak1_R2.fastq, and so on. 

I would appreciate if any one could kindly give me your suggestion how I can modify the functions to fit my experiment. 

Thanks.

Zakeel

**Comment by benjjneb** [comment]
First, it would be easiest for you to first create one csv file with all the metadata (i.e. group, status and tissue). Then you can use the `read.csv` function to read in the csv file into an R `data.frame`. It is probably worth reading the help text `?read.csv` as well, especialy if you run into any issues with that step.
