### ISSUE TITLE
Receiving error with function sread in the primer counting function assignment

### ISSUE THREAD

**Issue by k-vincent** [benjjneb/dada2#1174]
Hi, I'm running into some trouble with the primerHits function assignment. Has this been updated in more recent versions of DADA2? I just updated to R 4.0.3 and DADA2 (version 3.8) package version 1.16.0. Your help is much appreciated. 

When assigning the primer hit function as... 

```
primerHits <- function(primer, fn) {
    # Counts number of reads in which the primer is found
    nhits <- vcountPattern(primer, sread(readFastq(fn)), fixed = FALSE)
    return(sum(nhits > 0))
}
```

I am receiving the following error: 
> Error in h(simpleError(msg, call)) : 
> error in evaluating the argument 'subject' in selecting a method for function 'vcountPattern': could not 
> find function "sread"

Thank you in advance!

**Comment by k-vincent** [comment]
clarification... 
**BiocManager version 3.8

**Comment by benjjneb** [comment]
That error message indicates that the function is failing to find the `sread` function frmo the ShortRead package in the package environment, but the package is including that import in its NAMESPACE file so not sure what's up.

Does it work if you `library(ShortRead)` first? Does restarting R and reloading dada2 resolve the issue?

**Comment by k-vincent** [comment]
Thank you for your quick response.

Unfortunately, `library(ShortRead)` has been run, and restarting R and reloading dada2 does not resolve the issue. 

I'm not very versed in bioconductor. Is there something wrong with the way that I am installing the packages and loading the libraries? 

```
if (!require(dada2)) {install.packages("dada2")}

if (!require(BiocManager)) {install.packages("BiocManager")}
BiocManager::install("dada2", version = "3.8")
source("https://bioconductor.org/biocLite.R")
biocLite("ShortRead")

library(dada2); packageVersion("dada2") # the dada2 pipeline
library(ShortRead); packageVersion("ShortRead") # dada2 depends on this
```

**Comment by benjjneb** [comment]
Well, the way written there you would install dada2 via `install.packages` rather than Bioconductor first, so I think you want to get rid of that first line. But, I don't know why that would lead to this sort of namespace error...

Can you try resinstalling the package direct from Github, and see if that helps?
```
library(devtools)
devtools::install_github("benjjneb/dada2", ref="v1.16")
```

**Comment by k-vincent** [comment]
I tried loading it that way and it didn't change anything. 

But I think I might have found what was causing the error message... `biocLite("ShortRead")` wasn't installing ShortRead (when I looked that up, it said to use BiocManager instead). I tried install.packages to load ShortRead and now I don't get that error message. 

But... when I run the function, all the primer counts are 0. Any thoughts? 
>                 Forward Complement Reverse RevComp
> FWD.ForwardReads       0          0       0       0
> FWD.ReverseReads       0          0       0       0
> REV.ForwardReads       0          0       0       0
> REV.ReverseReads       0          0       0       0

Thanks again!

**Comment by benjjneb** [comment]
> But... when I run the function, all the primer counts are 0. Any thoughts?

You don't have primers on your reads? Or your primers are mis-specified I guess.

**Comment by k-vincent** [comment]
I think mis-specified. I ran this particular set of samples a couple years ago and had a non-zero count of primers.

**Comment by k-vincent** [comment]
Thanks for your help- I will trouble shoot from here.
