### ISSUE TITLE
confusion regarding differences between sequences types at various stages of denoising

### ISSUE THREAD

**Issue by anjexq** [benjjneb/dada2#1176]
Hello,

Please forgive the basic nature of my question. I am confused on how denoised sequences, sequent variants and unique input sequences differ from each other? When I look at my dd2 output, all of these are present but I am not sure exactly how they differs from each other.  

Thank you

**Comment by benjjneb** [comment]
An initial reference that could be useful would be the paper describing the DADA2 method: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4927377/
