### ISSUE TITLE
Merging multiple runs of the same samples

### ISSUE THREAD

**Issue by BoertienJM** [benjjneb/dada2#1177]
Dear dr. Callahan,
When reading the DADA2 documentation and closed issues on combining multiple runs, it is advised to process different runs separately until chimera removal as the error rates might differ between runs. However, the earlier discussions on this topic that I've found concerned situations where the different runs were comprised of different samples. Therefore, I was wondering whether this still applied to multiple runs of the same samples, all performed on the same MiSeq. 

In short, all our samples were in one pool that was sequenced multiple times. The only difference between these runs were the concentration of samples with a low number of reads in the previous run: a higher concentration of these samples was loaded in the subsequent run (that still contained all the samples). Intuitively, I would assume that the possibility for different error rates between these runs is very small and the reads from the same sample can be combined safely. Or would you suggest to still treat them as completely separate runs given that mergeSequenceTables() has a "sum" option for repeats?

**Comment by benjjneb** [comment]
In you rcase, I would still process the runs separately. There are ways that much lower loadings of the flow cell could lead to different error processes between the runs.

However, you would be fine to "sum" the runs at the end as you described (i.e. with the sum mode of `mergeSequenceTables`).

**Comment by BoertienJM** [comment]
Thank you for the swift reply! Which leads me to two follow-up questions within the same topic: how to deal with different read lengths and starting points across runs and within samples?

Based on the discussion of previous issues #716 and #881 I think I can conclude the following:
1. different runs might require different truncLen settings
2. it is advisable to truncate the reads of the same sample to the same length to help detecting rare variants
3. all reads should start at the exact same place 

Is it correct that point 2 regarding the same length of the reads refers to the reads after paired-end merging? Otherwise, it might be problematic to use different truncLen settings across runs? Also, within a sample, some reads might actually be shorter than truncLen, but might still merge.

Since we used primers of variable length, I had to remove these first using cutadapt. Ideally, all reads should now start at the exact same place, but there are probably some exceptions where the primer removal was inadequate or the read never contained the primer sequence. Can these exceptions be ignored or should I stay on the safe side and use collapseNoMismatch after merging the sequence tables to avoid any issues?

**Comment by benjjneb** [comment]
> Is it correct that point 2 regarding the same length of the reads refers to the reads after paired-end merging? Otherwise, it might be problematic to use different truncLen settings across runs? Also, within a sample, some reads might actually be shorter than truncLen, but might still merge.

With paired-end reads, that will later be merged, as long as the merged amplicon sequence is the same across reads, it is less important what the `truncLen` for each individual read is. In practice, you can have different `truncLen`s from one run to the other, as long as the starting points (primers) are the same, and you maintain overlap.

> Since we used primers of variable length, I had to remove these first using cutadapt. Ideally, all reads should now start at the exact same place, but there are probably some exceptions where the primer removal was inadequate or the read never contained the primer sequence. Can these exceptions be ignored or should I stay on the safe side and use collapseNoMismatch after merging the sequence tables to avoid any issues?

In my not extensive experience, the cutadapt output was good enough that I could just ignore the "ragged" sequences. That said, running `collapseNoMismatch` shouldn't hurt anything outside of costing computation cycles (it is not very efficiently implemented).

**Comment by BoertienJM** [comment]
Thanks for the elaborate answers! I can move forward from here.
