### ISSUE TITLE
Can't specify a length 2 vector for `compress=` in filterAndTrim()

### ISSUE THREAD

**Issue by cpauvert** [benjjneb/dada2#1178]
Hi, 
I am using the latest version of dada2 v1.16.0 on R v4.0.2. I realize that contrary to the manual, unfortunately, we can't specify a length 2 vector for the `compress=` option in filterAndTrim() function. Here is a reproducible example :

```r
library(dada2)
example(filterAndTrim)
filterAndTrim(testFastqs, filtFastqs, compress=c(T,F))
filterAndTrim(testFastqs, filtFastqs, compress=c(T,T))
```

I got the following same error for both calls (full `TRUE` or mixed) and when calling the downstream function `fastqPairedFilter`:

```
example(fastqPairedFilter)
fastqPairedFilter(c(testFastqF, testFastqR), c(filtFastqF, filtFastqR), compress=c(T,T))
```

Error message:
```
Error in writeFastq(fq, fout, "w", compress = compress) : 
  'compress' must be 'logical(1) (TRUE or FALSE)'
```

I don't have any suggestions so far,
Best, 
Charlie

**Comment by benjjneb** [comment]
Yes, in fact all of the arguments from `orient.fwd` through to `verbose` don't support length 2 arguments.
But that isn't indicated well in the help text right now (these aren't FILTERING AND TRIMMING PARAMETERS ———, but you can't tell that from the text).

**Comment by cpauvert** [comment]
Ok thank you very much for the clear (and super fast) explanation.
