### ISSUE TITLE
addSpecies with lots of NA

### ISSUE THREAD

**Issue by provirasanz** [benjjneb/dada2#1179]
Hello,

I am wondering if it is common to have very few ASVs assigned at the specie level (100% match). I am using the flollowing script:

taxa_sp <- addSpecies(taxa, "silva_species_assignment_v132.fa")

For example, I have a taxa table with 8251 ASVs and only 5 of them were assigned at the specie level, while 4603 were assigned at the genus level.
Thank you very much in advance
Regards,

Pablo

**Comment by benjjneb** [comment]
That's fewer assignments than I usually see in human microbiome data, but it may not be unusual at all. Remember that species assignment by `assignSpecies` is quite strict: It require an unambiguous exact match to the database.

So, if your sequenced amplicon is short (<200nts), or if your samples are from environments outside the human micorbiome (much lower coverage of named species in the reference dbs), the vast majority may end up with no species assignment.

You can also try `allowMultiple=TRUE` to see if some are matching multiple species (reported as NA by default).

**Comment by provirasanz** [comment]
Thanks for your quick reply. It makes sense! 
Samples are feces from cattle and by using the allowMultiple=TRUE option I got 13 ASVs assigned at the specie level. By the way, how are multiple matches assigned to species? Randomly? 
Thanks again.
Regards,

Pablo

**Comment by benjjneb** [comment]
> By the way, how are multiple matches assigned to species? Randomly?

By default, if a sequence exactly matches multiple species, it is not assigned at the species level. With `allowMultiple=TRUE` all exact species matches are reported, separated by backslashes.
