### ISSUE TITLE
Error: Sequences must be at least 50 nts to classify. (in assignTaxonomy)

### ISSUE THREAD

**Issue by jennomics** [benjjneb/dada2#118]
I'm following the tutorial here: http://benjjneb.github.io/dada2/tutorial.html

I'm using dada2 version 1.1.5

The only modifications I've made to that workflow are 1) adding multithread=TRUE to the dada step and 2) adding justConcatenate=TRUE to the mergePairs step.

All seems to work fine until I get to assignTaxonomy, at which time I get the error message above. I've attached the seqtab.nochim as a csv here. I can't see where the problem is. Hopefully you can help?

(I tried to attach it, but apparently csv isn't supported. That's weird. Anyway, I can email it to you if you need to look at it to figure out what the problem is.)

**Comment by benjjneb** [comment]
What sequence data/package version are you using? I just tried it with the tutorial data and 1.1.6 and all worked as expected.

**Comment by jennomics** [comment]
I actually just edited my post to include that information. I'm using 1.1.5

I will update and try again. Thank you!

**Comment by jennomics** [comment]
OK, I updated dada2 and encountered the same error. I have ITS sequences
from a MiSeq run.

when I run:

> table(nchar(colnames(seqtab.nochim)))

I get:

 440

5188

Looks like all of the sequences are the same length (440), right?


The error message is slightly different:


Error in eval(expr, envir, enclos) :

  Sequences must be at least 50 nts to classify.

**Comment by benjjneb** [comment]
Could you post a text file (or fasta) of the sequences you are classifying?

eg. `uniquesToFasta(seqtab.nochim, "foo.fa")`

Even better, if you could check if it happens on the first couple sequences (try `assignTaxonomy(colnames(seqtab.nochim)[1:5]), and then just post the offending sequences.

**Comment by jennomics** [comment]
OK, I figured out the problem. I had seqtab.nochim in quotes. Obviously, I
should have included my code! Oh well, next time...

Thank you, and sorry for wasting your time!
