### ISSUE TITLE
Parameters for PacBio CCS reads

### ISSUE THREAD

**Issue by bitcometz** [benjjneb/dada2#1180]
hello,
I follow the suggetions to do the PacBio CCS reads generated from Sequel II:
https://benjjneb.github.io/LRASManuscript/LRASms_fecal.html
`CCS reads were constructed using PacBio’s software, default parameters (including minPasses of 3) and a minPredictedAccuracy of 99.9%.`

And got the results:

Sample | input-reads | Fail full passes (%) | Below predicted accuracy (%) | Pass CCS (%)
-- | -- | -- | -- | --
Soil | 12109 | 2883 (23.82%) | 5914 (48.86%) | 2563 (21.18%)

About 48% reads were filtered because of `Below predicted accuracy 99.9%`

I want to set the accuracy of 99%, And ** Do I need to ajust the parameters for downstream DADA2 analysis ?

Thanks

**Comment by benjjneb** [comment]
> I want to set the accuracy of 99%, And ** Do I need to ajust the parameters for downstream DADA2 analysis ?

Nope.
