### ISSUE TITLE
rereplication in DADA2

### ISSUE THREAD

**Issue by ZuzanaKolarikova** [benjjneb/dada2#1181]
Hi all, I have a very basic question, sorry for that. Is there a rereplication step in the DADA2 workflow at some point? I know that the reads are de-replicated, but for the construction of the ASV table, I think we need to go back to the original read numbers, right? Thanks Zuzana

**Comment by benjjneb** [comment]
The total read numbers are kept the whole time. Dereplication stores alongside the unique sequences the number of times that they were observed in the original data.
