### ISSUE TITLE
How are prevalence and abundance `PSEUDO_*` options combined when picking pseudo-pooling priors?

### ISSUE THREAD

**Issue by mikemc** [benjjneb/dada2#1183]
I wanted to check how the prevalence and abundance settings are combined;  [link to code location](https://github.com/benjjneb/dada2/blob/71854020df02862c925544ba02a1a6b3590e73dd/R/dada.R#L580)
```
#' PSEUDO_PREVALENCE: When performing pseudo-pooling, all sequence variants found in at least two
#'  samples are used as priors for a subsequent round of sample inference. 
#'  Only relevant if `pool="pseudo"`. Default is 2.
#' 
#' PSEUDO_ABUNDANCE: When performing pseudo-pooling, all denoised sequence variants with total
#'  abundance (over all samples) greater than this are used as priors for a subsequent round 
#'  of sample inference.
#'  Only relevant if `pool="pseudo"`. Default is Inf (i.e. abundance ignored for this purpose).
```
What happens when PSEUDO_ABUNDANCE is reduced below Inf - does it take precedence, or are the two options OR'ed or AND'ed? From the wording I would guess that they are OR'ed; i.e., if an ASV has a prev >= PSEUDO_PREVALENCE or abundance >= PSEUDO_ABUNDANCE it will be added to the priors.

**Comment by benjjneb** [comment]
Yes it's "OR": https://github.com/benjjneb/dada2/blob/71854020df02862c925544ba02a1a6b3590e73dd/R/dada.R#L400

**Comment by mikemc** [comment]
Thanks!
