### ISSUE TITLE
Secon example on the vignette

### ISSUE THREAD

**Issue by llrs** [benjjneb/dada2#1184]
On the vignette on Bioconductor, on the [second example](http://bioconductor.org/packages/release/bioc/vignettes/dada2/inst/doc/dada2-intro.html#a-second-sample) the `errF` and `errR` are based on the first example/sample. Is this a mistake?

I assume that it is a mistake and the following lines are needed on the vignette:

```r
errF <- learnErrors(derepF2, multithread=FALSE)
errR <- learnErrors(derepR2, multithread=FALSE)
```

**Comment by benjjneb** [comment]
The assumption is that the two samples are from the same run/experiment, and so can use the same error model.

**Comment by llrs** [comment]
Thanks for the quick reply. Just so you know, I got a bit confused because I only ran the second example and got the errors.
