### ISSUE TITLE
Filtering too much reads 

### ISSUE THREAD

**Issue by bitcometz** [benjjneb/dada2#1185]
hello,

I run the PacBio CCS reads with parameters:
`CCS reads were constructed using PacBio’s software, default parameters (including minPasses of 3) and a minPredictedAccuracy of 99%`:

And then I run DADA2 with parameters:
```
track2 <- filterAndTrim(nops2, filts2, minQ=3, minLen=1000, maxLen=1600, maxN=0, rm.phix=FALSE, maxEE=6)
dd2 <- dada(drp2, err=err2, BAND_SIZE=32, multithread=TRUE, pool=TRUE)
```

then I got the final resutls:
```
IDs            no_primers      filtered        denoised        nochim
sample1    19205   10030   8063    7718
sample2    37637   24097   21023   20453
sample3     28311   17636   15800   15233
sample4   38273   23981   21275   20471
sample5    7569    5121    4280    4171
sample6    9599    6091    5221    5064
sample7    19209   12856   12031   11485
sample8   28071   18629   16934   16217
sample9   7213    2569    233     233
sample10   16594   6791    1113    1113
sample11   5445    2102    185     185
sample12   10496   3874    370     370
sample13   9770    3432    289     289
sample14   9470    3608    420     420
sample15   5587    2465    1090    1090
sample16   9377    4286    1601    1601
sample17   17987   8549    3460    3460
sample18   13844   5586    1849    1849
sample19   19649   8933    2921    2921
sample20   16042   6590    1700    1700
```

I found there are too much reads filtered for same samples :heartbeat: . So I changed the DADA2 parameters:

```
track2 <- filterAndTrim(nops2, filts2, minQ=3, minLen=1000, maxLen=1600, maxN=0, rm.phix=FALSE, maxEE=10)
dd2 <- dada(drp2, err=err2, BAND_SIZE=32, multithread=TRUE, pool=TRUE, DETECT_SINGLETONS=TRUE)
```

The first try took me about less than half of an hour. However, the second one have run for more then 12 hours :heartbeat: .

Could you give some suggestions on parametes, which help me avoid filtering too much reads for samples with resonable running times? Thanks !!!

Best

**Comment by benjjneb** [comment]
I would probably stick with your original filtering. Adding a bunch of lower quality reads isn't going to help.

I would also look into why there is a seeming clear separation between your first 8 samples, which seem to have worked quite well, and the rest of the samples, which often are losing almost all their reads in the denoising step. Adding `DETECT_SINGLETONS=TRUE` may help, but is there some systematic difference between those sets of samples?
