### ISSUE TITLE
Primer removal

### ISSUE THREAD

**Issue by Apanphil** [benjjneb/dada2#1189]
Hi,

I am running the ITS version of dada2 1.14. I have reached at a stage of removing the primers and have got an error. See below. I do not how to solve the error. Any help?
primerHits <- function(primer, fn) {

nhits <- vcountPattern(primer, sread(readFastq(fn)), fixed = FALSE)
return(sum(nhits > 0))
}
rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.filtN[[1]]),

FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.filtN[[1]]),
REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.filtN[[1]]),
REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.filtN[[1]]))
Error in sread(readFastq(fn)) : could not find function "sread"
rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.filtN[[1]]),

FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.filtN[[1]]),
REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.filtN[[1]]))
Error in sread(readFastq(fn)) : could not find function "sread"

**Comment by mikemc** [comment]
`sread()` is a function from the ShortRead package. Perhaps you skipped the step of loading the ShortRead package in the beginning of [the ITS Tutorial](https://benjjneb.github.io/dada2/ITS_workflow.html)?

**Comment by Apanphil** [comment]
Yes, after re-starting R and loading ShortReads package first before DADA2, it all worked.

Thank you Benj and Mike
