### ISSUE TITLE
error when running dada on a single sample

### ISSUE THREAD

**Issue by jennomics** [benjjneb/dada2#119]
Hello, I'm following the dada2 tutorial here:
http://benjjneb.github.io/dada2/tutorial.html

If I read in 2 samples from the input directory, all goes well, but if I only read in a single sample, I get stuck at this step, with this error:

> dadaFs <- dada(derepFs, err=inflateErr(tperr1,3), selfConsist = TRUE, multithread=TRUE)
Error in dada(derepFs, err = inflateErr(tperr1, 3), selfConsist = TRUE,  : 
  Invalid derep$uniques vector. Must be integer valued.

I'm running dada2 v. 1.1.6 on Illumina MiSeq data

Code is pasted below. Thank you!
Jenna

source("https://bioconductor.org/biocLite.R")
biocLite("devtools")
library("devtools")
devtools::install_github("benjjneb/dada2")
library(dada2)
library(ShortRead)

inpath <- "/home/ubuntu/data/qc/Run27/"
fns <- list.files(inpath)
fns

#First read in the file names for a pair of fastq files and do a little string manipulation to get lists of the forward and reverse fastq files in matched order

#reading in one sample:
fastqs <- fns[grepl("Run27_70", fns)]
fnFs <- fastqs[grepl("_R1_", fastqs)] # Just the forward read file
fnRs <- fastqs[grepl("_R2_", fastqs)] # Just the reverse read file
# Get sample names from the first part of the forward read filename
sample.names <- sapply(strsplit(fnFs, "_"), `[`, 2)
# Fully specify the path for the fnFs and fnRs
fnFs <- paste0(inpath, fnFs)
fnRs <- paste0(inpath, fnRs)

outpath <- "/home/ubuntu/Run27/"
# Make filenames for the filtered fastq files
filtFs <- paste0(outpath, sample.names, "_F_filt.fastq.gz")
filtRs <- paste0(outpath, sample.names, "_R_filt.fastq.gz")
saveRDS(filtFs, "/home/ubuntu/Run27/filtFs.rds")
saveRDS(filtRs, "/home/ubuntu/Run27/filtRs.rds")

# Filter 
for(i in seq_along(fnFs)) {
  fastqPairedFilter(c(fnFs[i], fnRs[i]), c(filtFs[i], filtRs[i]),
                    trimLeft=c(25, 25), truncLen=c(250,220), 
                    maxN=0, maxEE=2, truncQ=2, 
                    compress=TRUE, verbose=TRUE)
}

#Dereplicate the filtered fastq files:

derepFs <- derepFastq(filtFs, verbose=TRUE)
derepRs <- derepFastq(filtRs, verbose=TRUE)

# Name the derep-class objects by the sample names
names(derepFs) <- sample.names
names(derepRs) <- sample.names
saveRDS(derepFs, "/home/ubuntu/Run27/derepFs.rds")
saveRDS(derepRs, "/home/ubuntu/Run27/derepRs.rds")

#Perform joint sample inference and error rate estimation

dadaFs <- dada(derepFs, err=inflateErr(tperr1,3), selfConsist = TRUE, multithread=TRUE)
saveRDS(dadaFs, "/home/ubuntu/Run27/dadaFs.rds")
dadaRs <- dada(derepRs, err=inflateErr(tperr1,3), selfConsist = TRUE, multithread=TRUE)
saveRDS(dadaRs, "/home/ubuntu/Run27/dadaRs.rds")

#merge reads, adding 10Ns to concatenate when they do not overlap
mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, justConcatenate=TRUE, verbose=TRUE)

#make sequence table
seqtab <- makeSequenceTable(mergers[names(mergers)])

#remove chimeras
seqtab.nochim <- removeBimeraDenovo(seqtab, verbose=TRUE, multithread=TRUE)

#save the R object
saveRDS(seqtab.nochim, "/home/ubuntu/Run27/seqtab.nochim.rds")
#then, to open in a new R session: 
#seqtab <- readRDS("/home/ubuntu/Run27/seqtab.nochim.rds")

**Comment by benjjneb** [comment]
Ah. The offending lines are:

```
names(derepFs) <- sample.names
names(derepRs) <- sample.names
```

If you remove them it will work for 1 sample. Those lines expect a `list` of `derep-class` objects, and are instead getting a single `derep-class` object, with the result being that the assignment of names messes up the structure of the obejct itself.

That's a very non-obvious edge-case bug. Refactoring the way the S4 classes are defined might be worth doing, to avoid this and to avoid the problems where people `sapply` or `c` these objects and end up with invalid outputs.

**Comment by jennomics** [comment]
OK, thank you! It's hard to do this stuff while learning R; I appreciate the help

**Comment by benjjneb** [comment]
As of 1b6d245 the names of `derep-class` and `dada-class` objects can no longer be reassigned. When running the offending single-sample code, a warning will be produced when trying to assign names, but the rest of the code will run as expected.
