### ISSUE TITLE
Error in validObject(.Object) :    invalid class “ScalarCharacter” object: superclass 

### ISSUE THREAD

**Issue by majorel101197** [benjjneb/dada2#1190]
Hello,
Hello,
I recently started using DADA2 pipeline, to analyze fastqs from Illumina run. But as soon as I get to the filterAndTrim function, it shows me an error?
can you help me?
Bourake

> library(dada2); packageVersion("dada2")
Le chargement a nécessité le package : Rcpp
[1] ‘1.18.0’
> library(dada2)
> setwd("C:/Users/cmajorel/Desktop/Genoscreen DATA microbiome/TEST2")
> path <- "C:/Users/cmajorel/Desktop/Genoscreen DATA microbiome/TEST2"
> list.files(path)
[1] "BGR1_R1.fastq"  "BGR1_R2.fastq"  "BMyc2_R1.fastq"
[4] "BMyc2_R2.fastq" "filtered"       "VASE1_R1.fastq"
[7] "VASE1_R2.fastq" "YRG2_R1.fastq"  "YRG2_R2.fastq" 
> fnFs <- sort(list.files(path, pattern="_R1.fastq", full.names = TRUE))
> fnRs <- sort(list.files(path, pattern="_R2.fastq", full.names = TRUE))
> sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
> filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
> filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
> names(filtFs) <- sample.names
> out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=0,
+                      maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
+                      compress=TRUE, multithread=FALSE)
**Error in validObject(.Object) : 
  invalid class “ScalarCharacter” object: superclass "characterORconnection" not defined in the environment of the object's class****

**Comment by benjjneb** [comment]
There have been some previous reports of errors like this, eg. https://github.com/benjjneb/dada2/issues/212

There was no clearly identified issue. My best guess at this point is that there is some inconsistency that arose at the time of package installation or package loading. What I would recommend is uninstalling dada2/Biostrings/ShortRead and reinstalling from Bioconductor:

```
remove.packages(c("dada2", "ShortRead", "Biostrings"))
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("Biostrings")
BiocManager::install("ShortRead")
BiocManager::install("dada2")
```

Then restart R, and retry.

**Comment by majorel101197** [comment]
When running your code, i get the following warning : 

package ‘Biostrings’ successfully unpacked and MD5 sums checked
package ‘ShortRead’ successfully unpacked and MD5 sums checked
package ‘dada2’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\cmajorel\AppData\Local\Temp\RtmpEjSSni\downloaded_packages
Installation path not writeable, unable to update packages: KernSmooth, nlme
Old packages: 'backports'
Update all/some/none? [a/s/n]:

**Comment by majorel101197** [comment]
thank you I have everything to install R and Rstudio, because I think there was a conflict between package! 


Clarisse Majorel 
Ingénieur Biologie Moléculaire et fonctionnelle 
UMR IRD_ENTROPIE_Equipe Transversale 
Centre IRD Nouméa 
Tel: 260788 
Port: 503283 


De: "Benjamin Callahan" <notifications@github.com> 
À: "benjjneb/dada2" <dada2@noreply.github.com> 
Cc: "clarisse.majorel" <clarisse.majorel@ird.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 4 Novembre 2020 08:44:26 
Objet: Re: [benjjneb/dada2] Error in validObject(.Object) : invalid class “ScalarCharacter” object: superclass (#1190) 





There have been some previous reports of errors like this, eg. [ https://github.com/benjjneb/dada2/issues/212 | #212 ] 

There was no clearly identified issue. My best guess at this point is that there is some inconsistency that arose at the time of package installation or package loading. What I would recommend is uninstalling dada2/Biostrings/ShortRead and reinstalling from Bioconductor: 
remove.packages(c("dada2", "ShortRead", "Biostrings"))
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("Biostrings")
BiocManager::install("ShortRead")
BiocManager::install("dada2") 


Then restart R, and retry.

**Comment by majorel101197** [comment]
hello,
When running your code, i get the following warning :

> R1_erreur = learnErrors(R1_filt)
Error in derepFastq(fls[[i]], qualityType = qualityType) : 
  Not all provided files exist.

Could you help me?
TY

**Comment by benjjneb** [comment]
I think the file path you provided doesn't exist.

To diagnose, I'd suggest inspecting the file paths `R1_filt` to see if there are any file name errors, and you can also determine which don't exist with `file.exists(R1_filt)`.
