### ISSUE TITLE
Combining / Joining forward and reverse 454 sequencing data?

### ISSUE THREAD

**Issue by paytonyau** [benjjneb/dada2#1191]
Hi, 

I am trying to analyse some 454 sequencing data and this data converted into fastq format already. The data also has forward and reverse reads. 

My understanding about 454 sequencing is, it is not "paired-end" reads and thus `mergePairs` or `mergePairsByID` could not be  used in this situation.

My question is, what is the appropriate approach to deal with this kind of data?

Thank you for your hlep.

Payton

**Comment by benjjneb** [comment]
I'm not familiar with 454 "psuedo" paired data. What are the forward and reverse reads then?

The simplest thing to do would be to just analyze the forward reads.
