### ISSUE TITLE
Error with Assigning Taxonomy 

### ISSUE THREAD

**Issue by monicahruzd** [benjjneb/dada2#1193]
I keep getting error messages when trying to assign taxonomy on data2. 

This is the command I am using:
taxa <- assignTaxonomy(seqtab.nochim, "silva_nr99_v138_train_set.fa.gz", multithread=TRUE)

This is the error message I am getting:
Error in assignTaxonomy(seqtab.nochim, "silva_nr99_v138_train_set.fa.gz",  : 
  could not find function "assignTaxonomy"

I am supposed to do something special to use the "assignTaxonomy" function? I do not understand how the program cannot find it.

**Comment by benjjneb** [comment]
You need to load the package into your R session before you can use the associated functions: `library(dada2)`
