### ISSUE TITLE
Working with sensitive dada2 to detect known species in a sample

### ISSUE THREAD

**Issue by Apanphil** [benjjneb/dada2#1195]
Hi there,
I am using dada2 version 1.14 to analyse air samples and assign fungal species using UNITE database v.8.2. From other methods, i know that species x exists in the air samples. However, dada2 is not detecting it. How do i use a more sensitive dada2 in order to detect the known species x in the air samples?
Any help is appreciated.

Thank you

Apaphil

**Comment by benjjneb** [comment]
The most probable reason you aren't detecting a species known to be in the sample is (1) the species isn't in the amplicon sequencing data or (2) the sequences from that species aren't being assigned to the species level.

It is critical to distinguish between those two scenarios. I would start by obtaining example ITS sequences from that species, and then determining if any ITS sequences in your data match those known sequences.

**Comment by andzandz11** [comment]
I had the same problem with dada2 and there is no answer to your question as it does not work.

If your species just has a few reads it gets kicked out with all other low read specimen, no matter how finely you tune the parameters. It is the core function of the denoising step and it cannot be avioded. I tried to tune all parameters to the maximum.

I would advise you to not run any pipeline if you are looking for super rare stuff.

**Comment by benjjneb** [comment]
My recommendation is that if trying to glean the data for known species that are of interest, to provide their known amplicon sequences as `priors=c(SEQ1, SEQ2,...)` to get maximum sensitivity. They will then be detected if present in just one read matching those sequences.

Or you could could also just match the raw data directly if you don't care about the overall removal of dataset errors.
