### ISSUE TITLE
primerHits command returning all zeros

### ISSUE THREAD

**Issue by LaurCharl** [benjjneb/dada2#1196]
Hi, I am trying to complete all analysis from V1-V2 16s rRNA sequencing using dada2 as opposed to QIIME. I am just attempting to follow along with the tutorials supplied on GitHub but with my own data. The data I have require primer removal and so I am following the ITS example (https://benjjneb.github.io/dada2/ITS_workflow.html. However, when I come to checking the number of times the primer appears in the forward and reverse reads I keep receiving the following:

primerHits <- function(primer, fn) {
  nhits <- vcountPattern(primer, sread(readFastq(fn)), fixed = FALSE)
  return(sum(nhits > 0))
}
rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.filtN[[1]]), 
      FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.filtN[[1]]), 
      REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.filtN[[1]]), 
      REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.filtN[[1]]))

                 Forward Complement Reverse RevComp
FWD.ForwardReads       0          0       0       0
FWD.ReverseReads       0          0       0       0
REV.ForwardReads       0          0       0       0
REV.ReverseReads       0          0       0       0

This would suggest that the primers are not present in any of the reads which cannot be possible! Any guidance is much appreciated!

**Comment by benjjneb** [comment]
Can you describe the amplicon you are sequencing, and post the output of:

```
FWD.orients
REV.orients
```

**Comment by LaurCharl** [comment]
Hi, the amplicon is of the V1-V2 region of the 16S gene, sequenced using Illumina MiSeq platform with a 250bp paired-end sequencing kit.

 FWD.orients
                                                     Forward 
"ACACTCTTTCCCTACACGACGCTCTTCCGATCTNNNNNAGAGTTTGATCMTGGCTCAG" 
                                                  Complement 
"TGTGAGAAAGGGATGTGCTGCGAGAAGGCTAGANNNNNTCTCAAACTAGKACCGAGTC" 
                                                     Reverse 
"GACTCGGTMCTAGTTTGAGANNNNNTCTAGCCTTCTCGCAGCACATCCCTTTCTCACA" 
                                                     RevComp 
"CTGAGCCAKGATCAAACTCTNNNNNAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT" 
> REV.orients
                                               Forward 
"GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCTTGCTGCCTCCCGTAGGAG" 
                                            Complement 
"CACTGACCTCAAGTCTGCACACGAGAAGGCTAGAACGACGGAGGGCATCCTC" 
                                               Reverse 
"GAGGATGCCCTCCGTCGTTCTAGCCTTCTCGTGTGCAGACTTGAGGTCAGTG" 
                                               RevComp 
"CTCCTACGGGAGGCAGCAAGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"

**Comment by benjjneb** [comment]
Typically in amplicon library preparations, only the primer is sequenced, not the entire adapter/barcode/primer construct. The sequences you've provided are from that entire construct, and aren't being detected.

First I'd confirm for sure that your primers are on the reads. You can do this by pulling out the first sequence or two from a forward fastq file, and hand-aligning them to that construct. They might start right after the NNNNN bit or thereabouts, if the primers were sequenced.

If that's the case, redo primerHits with the primers redefined as just the primer sequence.

**Comment by LaurCharl** [comment]
Brilliant, Thank you so much!!
