### ISSUE TITLE
Error Error in open.connection(con, "rb") : cannot open the connection during filterAndTrim step

### ISSUE THREAD

**Issue by Rosiekstein** [benjjneb/dada2#1197]
Hello,

I am having some issues with my dada2 code. when I try the filter and trim step, I get the error "Error in open.connection(con, "rb") : cannot open the connection". My code is as follows: 

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(200,200), maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=) # On Windows set multithread=FALSE
head(out)

and the expanded error trackback is: 

Error in open.connection(con, "rb") : cannot open the connection
8.
open.connection(con, "rb")
7.
open(con, "rb")
6.
FastqStreamer(fn[[1]], n = n)
5.
FastqStreamer(fn[[1]], n = n)
4.
(function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0, 0), maxLen = c(Inf, Inf), minLen = c(20, 20), trimLeft = c(0, 0), trimRight = c(0, 0), minQ = c(0, 0), maxEE = c(Inf, Inf), rm.phix = c(TRUE, TRUE), rm.lowcomplex = c(0, 0), matchIDs = FALSE, ...
3.
mapply(FUN = FUN, ..., MoreArgs = MoreArgs, SIMPLIFY = SIMPLIFY, USE.NAMES = USE.NAMES)
2.
mcmapply(fastqPairedFilter, mapply(c, fwd, rev, SIMPLIFY = FALSE), mapply(c, filt, filt.rev, SIMPLIFY = FALSE), MoreArgs = list(truncQ = truncQ, truncLen = truncLen, trimLeft = trimLeft, trimRight = trimRight, maxLen = maxLen, minLen = minLen, maxN = maxN, minQ = minQ, ...
1.
filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen = c(150, 150), maxN = 0, maxEE = c(2, 2), truncQ = 2, rm.phix = TRUE, compress = TRUE, multithread = )

I have looked through other similar errors on the github page and the solutions did not seem to help. Any suggestions will be greatly appreciated. Thank you.

**Comment by benjjneb** [comment]
This error suggests that the file paths your are providing to `filterAndTrim` are not (all) valid.

If you inspect `fnFs` (etc) do you see any issues?

**Comment by Rosiekstein** [comment]
Thank you so much for the reply. I inspected the fnFs and fnRs, and both seem to be showing correct paths for all files. All the files will run for the quality profiles with no errors, so seem to be valid. Do you have any reccomendations for what issues in the file names to look for?

**Comment by Rosiekstein** [comment]
I looked through the files more closely and found the problem! If you use 7zip to unzip your files it puts them into individual folders instead of extracting direclty to the folder, which messes up the filterAndTrim but not plotQualityProfile. Putting all the files in one folder has fixed the issue. Hopefully this can help others who have a similar problem. Thank you again for your time and the suggestion that prompted me to look more closely at my files.
