### ISSUE TITLE
input/output no input files found, file.path doesn't create the files

### ISSUE THREAD

**Issue by FannyFronton** [benjjneb/dada2#1199]
Hi, I am a beginner with the dada2 package, and I am almost sure the problem isn't with dada2 but I don't know where to post it.
I and just trying to filter my reads, I used the script which worked really well until that precise moment:
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("dada2", version = "3.11")
library(dada2); packageVersion("dada2")
library(digest)
setwd("C:/Users/HP/Desktop/These/Donnees_reads/Truites")

path <- "C:/Users/HP/Desktop/These/Donnees_reads/Truites"
list.files(path)

fnFs <- sort(list.files(path, pattern="_R1.fastq", full.names = TRUE))
fnRs <- sort(list.files(path, pattern="_R2.fastq", full.names = TRUE))

sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
sample.names
plotQualityProfile(fnFs[20:5])
plotQualityProfile(fnRs[20:5]) #trunc at 220

#### Filtering ####
filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtFs
file.exists(filtFs)

The plotQualityProfile works really well, but the file.path() function won't create anything, but it doesn't give me back an error message. The filtFS variable is created with the path "C:/Users/HP/Desktop/These/Donnees_reads/Truites/filtered/names.fastq.gz"
but the file.exists() function only give me FALSE results and when I checked directly in the files on windows, nothing was created.

**Comment by benjjneb** [comment]
`filtFs` won't exist yet at that point in your R script.
You've defined a new file path to a filtered fastq file that will be created after you run `filterAndTrim`.
You should check `file.exists(filtFs)` after running the filtering.

**Comment by FannyFronton** [comment]
Oh ok, I feel dumb! It works perfectly thank yo.
