### ISSUE TITLE
license information

### ISSUE THREAD

**Issue by elsherbini** [benjjneb/dada2#120]
It might be a good idea to add a license to this project. Not sure if there are any restrictions from your institution, but if not, I'd recommend a [GPL license](https://www.gnu.org/licenses/gpl-howto.en.html), which ensures that the software is open for use and modification, but doesn't allow the source to be used in for-profit endeavors without making those open source as well.

I noticed that USEARCH v9, which is closed source, is adding a --denoise option, and part of the appeal of dada2 to me is that it is open source. This prompted the recommendation.

**Comment by joey711** [comment]
The license is [LGPL-3](https://www.r-project.org/Licenses/LGPL-3), as specified in the usual way for R packages, in [the description file](https://github.com/benjjneb/dada2/blob/master/DESCRIPTION). 

This doesn't seem ambiguous to me.

**Comment by elsherbini** [comment]
Sorry for the noise. I'm used to a LICENSE.txt in the root of the repository.

**Comment by joey711** [comment]
Yeah, no worries. As with many an idiosyncratic thing in R, the license is specified in a different way than for other languages/conventions. The fact that you asked in this public way means it's that much more clear to others, so net positive 👍
