### ISSUE TITLE
PCR optimization - suggestions?

### ISSUE THREAD

**Issue by vrbacky** [benjjneb/dada2#1200]
Hi,

our V4-V5 sequencing data contain a lot of chimeras. PCR seems to be OK from mol. biol. point of view but we get a lot of chimeras. I'd expect a high chimera rate with this setup because of the conservative region involved but I lose about 94% unique sequences and 20% reads as chimeras with `minFoldParentOverAbundance=4` (it is 96% and 25% with default value). `dada()` is not pooled and method of `removeBimeraDenovo()` is consensus. I think there could be some room for improvement. Or is it OK? What would you suggest? Do you have any experience, how to improve such data?

Thank you.

F.

**Comment by benjjneb** [comment]
To be honest, I am not the person to ask on this topic really, as I run a "dry" computational lab.

That said, in general fewer PCR cycles, longer elongation times, and making sure that there is no exhaustion of reagents in the last cycles, are all strongly suggested to reduce PCR formation.

**Comment by vrbacky** [comment]
Hi Ben,

all suggestions seem reasonable. Please don't close the issue for some time. Some "wet" lab colleagues might add their experience. Thanks.
