### ISSUE TITLE
Filtering and trimming 

### ISSUE THREAD

**Issue by Zuby88** [benjjneb/dada2#1203]
Hi, I am getting error message on the "out" command saying that some input files fo not exist. see error message : Error in filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen = c(250, 200), : Some input files do not exist.

I have checked my data files and all my sample data files are in the folder. Please, I need help and guideline on what to do. 

Below is my command line : 
outpath<-("/Users/egboluch/Desktop/Rawdata_folder")
filt_path<-file.path(outpath, "filtered")
filtFs<-file.path(filt_path, "filtered", paste0(sample.names, "_F_filt.fastq"))
filtRs<-file.path(filt_path,"filtered", paste0(sample.names, "_R_filt.fastq"))
out<-filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen = c(250,200), maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=FALSE)

**Comment by benjjneb** [comment]
You can use `file.exists` to look yourself at which input files are missing (or perhaps misnamed).

```
file.exists(fnFs)
file.exists(fnRs)
```

Also remember that absolute file paths will typically cause less headaches.

**Comment by Zuby88** [comment]
Thank you for your suggestion. I will do that and get back to you. I hope
it works.


Nzube

Nzube Prisca Egboluche
Graduate Research Assistant
Bioenvironmental Science Program
Morgan State University

**Comment by Zuby88** [comment]
I ran the file.exists(fnFs) command. The output showed  "False" for one of my filename. I took a  close look at that particular  file name , there is nothing different or misspelt or space. How do you think I can rectify that? 

I decided to run the "out" command again after the file.exists(fnFs)command 
 I got  a new error comment; Error in filterAndTrim(fwd = fnFs, filt = filtFs, rev = fnRs, filt.rev = filtRs, : All output files must be distinct. 

Please how can this issue be resolved. I am stuck at this stage .

**Comment by benjjneb** [comment]
> I ran the file.exists(fnFs) command. The output showed "False" for one of my filename. I took a close look at that particular file name , there is nothing different or misspelt or space. How do you think I can rectify that?

When you explore to that point in your file system, does that file exist? It doesn't as far as R can tell, so that needs to be rectified or this error will persist.

> I decided to run the "out" command again after the file.exists(fnFs)command
> I got a new error comment; Error in filterAndTrim(fwd = fnFs, filt = filtFs, rev = fnRs, filt.rev = filtRs, : All output files must be distinct.

This suggests that the output files you have provided are not all unique. One way to check this would be to run the following commands, and determine if there are any `TRUE` values:

```
duplicated(c(filtFs, filtRs))
```

Duplicated file names will need to be remedied.

**Comment by Zuby88** [comment]
Thank you . I am on it.

**Comment by Zuby88** [comment]
This is output I got after running the duplicated(c(flitFs, filtRs) command looks like this. So I have "False " value. 

 [1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE
[14]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

Please how can I remedy this issue.

**Comment by benjjneb** [comment]
The results indicate that every filename in `filtFs` is identical (all are duplicates of a previous filename except for the first), and likewise for `filtRs`. I'd suggest inspecting those, and then revisiting how you created `filtFs` and `filtRs` -- something went wrong there.

**Comment by Zuby88** [comment]
Yes, I have changed the files names. and everything works fine now. Thank you so much for your help.

**Comment by Zuby88** [comment]
After changing the filename , I ran the command again : 
filt_path<-file.path(outpath, "filtered")
filtFs<-file.path(filt_path, paste0(sample.names, "_F_filt.fastq.gz"))
filtRs<-file.path(filt_path, paste0(sample.names, "_R_filt.fastq.gz"))
out<-filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen = c(250,200), maxN=0, maxEE=c(2,2), truncQ = 2, rm.phix=TRUE, compress=TRUE, multithread=TRUE)
head(out)

The output says : no reads passed the filter. Please revisit your filtering parameters. The reads.out were all zeros. Please do I need to do at this point. what could be causing this error?

Please

**Comment by benjjneb** [comment]
> The output says : no reads passed the filter. Please revisit your filtering parameters. The reads.out were all zeros. Please what do I need to do at this point. what could be causing this error?

The filtering parameters you have chosen result in no reads passing the filters. In order to fix this, you need to understand the details of the reads you are processing. What is the technology used? What are the read lengths? Was any prior preprocessing done?

The `plotQualityProfile` function is very useful at this stage, to understand how the quality score and length distributions look like in your reads. The most likely issue is that your reads don't extend to your truncation lengths, thus are all being thrown out for being too short.

**Comment by Zuby88** [comment]
Here is the result of the plotQualityProfile output and the filterAndTrim command parameters that I used. Do you think I need to change any of my filtering parameters? 

filt_path<-file.path(outpath, "filtered")
filtFs<-file.path(filt_path, paste0(sample.names, "_F_filt.fastq.gz"))
filtRs<-file.path(filt_path, paste0(sample.names, "_R_filt.fastq.gz"))
out<-filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen = c(240,160), maxN=0, maxEE=c(2,2), truncQ = 2, rm.phix=TRUE, compress=TRUE, multithread=TRUE)

![Screen Shot 2020-11-19 at 12 14 03 PM](https://user-images.githubusercontent.com/64235799/99700465-37b90a00-2a61-11eb-89a3-e6abb34fd2be.png)
![Screen Shot 2020-11-19 at 12 13 47 PM](https://user-images.githubusercontent.com/64235799/99700468-38ea3700-2a61-11eb-80cb-66f6770a3c11.png)

**Comment by Zuby88** [comment]
Hi Ben,

The issue has been rectified. I was able to get the filtered reads. Thank you so much for help and assistance. I greatly appreciate it.
