### ISSUE TITLE
Pooling samples during ASV inference results in fewer ASVs than for non-pooling and pseudo-pooling

### ISSUE THREAD

**Issue by naurasd** [benjjneb/dada2#1205]
Hi @benjjneb ,

I am running dada2 for ITS MiSeq paired-end reads and our primers (ITS1f, Gardes & Bruns 1993 and ITS2, White et al. 1990) target amplicons of 250 - 600 bp.  The issue: I am obtaining fewer ASVs when I pool my samples during sequence variant  inference compared to non-pooling or pseudo-pooling.

I have looked through the other issues before submitting mine. This has obiously been discussed before. In this issue #511, the final response focussed on the merging problem unfortunately, and not the initial pooling problem. In the #1081 issue, the problem was the chimera removal step and the minFoldParentOverabundance parameter.

In my case, I end up with fewer ASVs with pooling compared to non- and pseudo-pooling even before removing chimeras. Here are my numbers:

Pooling:
pre-chimera-removal: 960
post-chiemra-removal: 926

Non-pooling:
pre-chimera-removal: 1036
post-chiemra-removal: 1005

Pseudo-pooling:
pre-chimera-removal: 1048
post-chiemra-removal: 1014

Any idea why I end up with fewer ASVs pre-chimera-removal when setting pool = T ? It does seem to happen according to what other users report, but I have so far not discovered an explanation for this on the forum.

Thanks a lot,
Nauras

**Comment by benjjneb** [comment]
I'm not sure. What I would check is whether there are move ASVs detected per-sample by pooling than non-pooling (which is expected). The way these different modes affect the total number of study-wide ASVs can be a bit more complex.

In any case, you look like you are getting fairly consistent results between the three modes, which is a good thing.

**Comment by naurasd** [comment]
Thanks for the quick reply @benjjneb.

I will just accept the fact that the study-wide number of ASVs is a complex thing and may indeed be lower for pooled samples ;-)

However, something is puzzling me. Here is a table of my ASVs (after chimera removal) per sample. The last 5 samples show a substantial gap in the number of ASVs between non-/pseudo-pooled and the pooled ASV inference. This makes me wonder 

  | no_pool | pseudo | pool
-- | -- | -- | --
Sample1 | 108 | 108 | 116
Sample2 | 12 | 12 | 14
Sample3 | 159 | 163 | 182
Sample4 | 36 | 38 | 52
Sample5 | 175 | 176 | 187
Sample6 | 151 | 156 | 179
Sample7 | 110 | 110 | 122
Sample8 | 41 | 61 | 112
Sample9 | 170 | 192 | 312
Sample10 | 133 | 151 | 223
Sample11 | 45 | 57 | 102
Sample12 | 201 | 217 | 302

These last 5 samples are from a different sequencing run so this has most likely got something to do with this. I know MiSeq reads from different runs should not be denoised together in dada2 so I won't do this again in the future. Just as a final question: is such a big discrepancy in the number of ASVs between non-/pseudo-pooled and pooled samples a warning sign in general?

**Comment by benjjneb** [comment]
> These last 5 samples are from a different sequencing run so this has most likely got something to do with this. I know MiSeq reads from different runs should not be denoised together in dada2 so I won't do this again in the future. Just as a final question: is such a big discrepancy in the number of ASVs between non-/pseudo-pooled and pooled samples a warning sign in general?

The two aspects of your question are hard to disambiguate here. It is not recommended to denoise different runs together in dada2, as they can have different errors modes, and depending on a common error model can therefore lead to errors. This is exacerbated in pooled denoising which is more sensitive to rare variants, and rare deviations from the error model.

That said, the discrepancies in total ASVs you are seeing are not huge, and what I would check to make myself feel better is that the pool-unique ASVs in the "second run" are at relatively low relative abundances. If so, I would just accept them as a cost of doing multi-run business (while doing one-run denoising) but not worry too much about it for downstream analyses.

* Your different runs should not be conflated with the comparisons you are trying to investigate. If they are, more serious consideration at the statistical analysis is needed.

**Comment by naurasd** [comment]
Thanks for the clarification and the quick replies. I will close this issue.
