### ISSUE TITLE
confused on GTDB and Refseq-RDP database

### ISSUE THREAD

**Issue by liangyong1991** [benjjneb/dada2#1206]
I have download  GTDB, Refseq-RDP from  https://benjjneb.github.io/dada2/training.html. 
Found that both GTDB and Refseq-RDP's train_set have contained the 'Species-level",  so is it necessary to run "addSpecies" step to add the ''Species-level"?

**Comment by benjjneb** [comment]
`assignSpecies`/`addSpecies` uses a different methods (exact unambiguous matching) to assign to the species level. So you may want to consider it for that reason. But no you don't have to use it if you are already using `assignTaxonomy` with a reference db that goes down to the species level.

**Comment by liangyong1991** [comment]
> `assignSpecies`/`addSpecies` uses a different methods (exact unambiguous matching) to assign to the species level. So you may want to consider it for that reason. But no you don't have to use it if you are already using `assignTaxonomy` with a reference db that goes down to the species level.

Thanks for your reply! As I mentioned above, the GTDB and RefSeq-RDP databases have 'Species-level' already in train_set, and I can use assignTaxonomy() function to get 'Species-level' taxonomy, so, does it necessary(or right) to run AddSpecies() function, what will AddSpecies() do if the input already has 'Species-level'?

**Comment by benjjneb** [comment]
`addSpecies`/`assignSpecies` uses a different method for species assignment. I personally would argue it is more appropriate for short-read 16S. But if you are happy with your 16S species level assignments using `assignTaxonomy` and thos databases, then there is no need for you to use it.

**Comment by liangyong1991** [comment]
> `addSpecies`/`assignSpecies` uses a different method for species assignment. I personally would argue it is more appropriate for short-read 16S. But if you are happy with your 16S species level assignments using `assignTaxonomy` and thos databases, then there is no need for you to use it.

Thank you for your advice, which help me a lot.
