### ISSUE TITLE
Newby question

### ISSUE THREAD

**Issue by josemseoane** [benjjneb/dada2#121]
Dear Ben, 

Thank you very much for the package, it worked great for me on unfiltered fastaq sequences.
I am very new to R and I would like to use the assignTaxonomy function on a fasta filtered and trimmed elsewhere. Using bash, I have formatted my fasta to look exactly like the example you provided in the "taxonomy" documentation. However I don't get the function to read it even thought if I copy and pasta the sequences manually from the fasta file it worked out.
Sorry for the low level question but I would really appreciate if you could help me to figure this out.

Thank you very much for sharing such a nice piece of work!

**Comment by benjjneb** [comment]
We don't have a native function in our package to read in fasta files, but you can use the `ShortRead` R package for that purpose. Code would look like this:

```
library(ShortRead)
sr <- readFasta("path/to/myseqs.fasta")
seqs <- as.character(sread(sr))
taxa <- assignTaxonomy(seqs, "path/to/silva_nr_v123_train_set.fa.gz")
```

Hope that helps. Let me know if it doesn't work for you.

**Comment by josemseoane** [comment]
Dear Ben, 

It worked perfectly. Thank you again for your help, this is a really nice library!

Best,

Jose
