### ISSUE TITLE
How to remove multiple forward and reverse ITS primers?

### ISSUE THREAD

**Issue by jlli2000** [benjjneb/dada2#1210]
Hello:

We use a mix of 8 forward and 7 reverse primers to make ITS libraries.    How can we remove multiple primers in DADA2 ITS pipeline?   I am very new to this.

Thanks,

jlli

**Comment by benjjneb** [comment]
The dada2 R package does not have an implementation for this problem. You will need to use another software package for your situation. You could re-enter dada2 after removing all the primers.

**Comment by jlli2000** [comment]
Thanks for your quick response.   I will look for other software package.    Thanks,
Jin
    On Thursday, November 19, 2020, 02:09:40 PM PST, Benjamin Callahan <notifications@github.com> wrote:  
 
 


The dada2 R package does not have an implementation for this problem. You will need to use another software package for your situation. You could re-enter dada2 after removing all the primers.

**Comment by andzandz11** [comment]
Just use the filterAndTrim function orient.fwd once for each primer and use a different output file each time. Voila, one file for wach primer combination. You can now either merge everything together using any R package that can handle fastq or more interesting: check which primer is recovering which taxa.
