### ISSUE TITLE
readout less than 10%

### ISSUE THREAD

**Issue by ShyamMayengbam** [benjjneb/dada2#1212]
Hi Benjamin,
After FilterAndTrim, I got less than 10% of the readout. The data is a little bit old. I am not sure what is wrong here. Is it because of the wrong primer or wrong number in the FilterAndTrim function? Could you have a look, please?
![image](https://user-images.githubusercontent.com/74869371/99909216-ad231580-2cc1-11eb-8c46-a8edc980fade.png)

![image](https://user-images.githubusercontent.com/74869371/99909225-b7ddaa80-2cc1-11eb-815e-ed68c96366e7.png)

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(280, 245),
                       maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                       compress=TRUE, multithread=FALSE) 

out.d <- data.frame(out)
out.per <- out.d%>%
  mutate(out.perpent= (100*reads.out/reads.in))
head(out.per)

reads.in
<dbl>
reads.out
<dbl>
out.perpent
<dbl>
1	168601	26119	15.49160	
2	219887	39371	17.90511	
3	156224	28090	17.98059	
4	173933	26163	15.04200	
5	94467	15330	16.22789

**Comment by benjjneb** [comment]
You could try reducing the reverse `truncLen` to see if that makes a significant difference, since the quality gets pretty bad at the end of your reverse reads. This is with the caveat that I don't know how long your sequenced amplicon is, and you still need to keep enough sequence to overlap.

**Comment by ShyamMayengbam** [comment]
Thank you, Benjamin.
