### ISSUE TITLE
Error in assignTaxonomy

### ISSUE THREAD

**Issue by Zuby88** [benjjneb/dada2#1217]
Hi Ben,

I have been getting this error message when i run the assignTaxonomy command. I downloaded the silva refseq  and placed in my fastq folder. I had to restart my Rstudio but still get the same error. 

taxa <- assignTaxonomy(seqtab.nochim, "/Users/egboluch/Desktop/FASTQ/silva_nr_v132_train_set.fa.gz", multithread=TRUE, tryRC = TRUE)
taxa <- addSpecies(taxa, "/Users/egboluch/Desktop/FASTQ/silva_species_assignment_v132.fa.gz", tryRC = TRUE)
taxa.print <- taxa # Removing sequence rownames for display only
rownames(taxa.print) <- NULL
head(taxa.print)

The error output reads 
Error in assignTaxonomy(seqtab.nochim, "/Users/egboluch/Desktop/FASTQ/silva_nr_v132_train_set.fa.gz",  : 
  could not find function "assignTaxonomy"

Please how can i resolve this issue? 

Thanks

**Comment by benjjneb** [comment]
Have you loaded the dada2 library into your R session before these commands? `library(dada2)`

**Comment by Zuby88** [comment]
Yes, I have loaded dada2 in my R session.

**Comment by benjjneb** [comment]
Somehow the R session is failing to find `assignTaxonomy` in its search path.

Maybe try `dada2::assignTaxonomy(...)`? That format explicitly specifies to the R intepreter that the function is defined in the dada2 package.

**Comment by Zuby88** [comment]
I just tried it the dada2::assignTaxonomy and I got this error - 

Error in is(object, "character") : object 'seqtab.nochim' not found

**Comment by benjjneb** [comment]
That means there is no `seqtab.nochim` in your R session.

When you restarted Rstudio it also reloaded your R session, so none of the previously defined variables are going to be in your session anymore. Did you save them somewhere? If not, you'll need to rerun the workflow from the start to create `seqtab.nochim` again.

**Comment by Zuby88** [comment]
Okay I will do that. But I think I saved because the previous workflow I ran are still on my R session after I restarted the R studio.

**Comment by Zuby88** [comment]
Thank you . I will let you know if that works.
