### ISSUE TITLE
Costumized training fasta - multiple sequences with same lineage

### ISSUE THREAD

**Issue by naurasd** [benjjneb/dada2#1219]
Hi @benjjneb,

I am currently trying to create a costumized reference database as a training fasta for COI taxonomy assignment in dada2. Will it be a problem for assigntaxonomy if I have multiple sequences of the same taxid / lineage in there? My database will include unique haplotypes, not taxa. Will I need to provide every sequence a unique taxid / lineage in this case?

Cheers
Nauras

**Comment by benjjneb** [comment]
> Will it be a problem for assigntaxonomy if I have multiple sequences of the same taxid / lineage in there? My database will include unique haplotypes, not taxa. Will I need to provide every sequence a unique taxid / lineage in this case?

Nope, that's totally fine.

**Comment by naurasd** [comment]
Alright, thanks for the quick reply.
