### ISSUE TITLE
Instalation Error

### ISSUE THREAD

**Issue by aefs** [benjjneb/dada2#122]
I am trying to install data2 on my 32bit Windows 10 PC.  When I try to install using devtools, I get the following error: 

** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'gtable'
ERROR: lazy loading failed for package 'dada2'
* removing 'C:/Users/Anna/Documents/R/win-library/3.3/dada2'
Error: Command failed (1)

So I tried directly installing and got this one:

Installing package into ‘C:/Users/Anna/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning: invalid package 'C:\Users\Anna\Documents/github/dada2'
Error: ERROR: no packages specified
Warning messages:
1: running command '"C:/PROGRA~1/R/R-33~1.1/bin/i386/R" CMD INSTALL -l "C:\Users\Anna\Documents\R\win-library\3.3" "C:\Users\Anna\Documents/github/dada2"' had status 1 
2: In install.packages("~/github/dada2", repos = NULL, type = "source",  :
  installation of package ‘C:\Users\Anna\Documents/github/dada2’ had non-zero exit status

Any ideas on how to fix this?

Thanks!

**Comment by benjjneb** [comment]
I do not have easy access to a 32-bit Windows machine, but I'll try to help troubleshoot.

First things first it seems as if the devtools installation is failing to install the gtable package, so let's try to install that by hand.

Can you try the following:

```
install.packages("gtable")
library(gtable)
packageVersion("gtable")
```

Also, for the install from source it seems to think that the path you gave it is not a valid path for the package. Could you double-check that path? You can also give it a path directly to the .tar.gz (before uncompressing) and see if that works.

**Comment by benjjneb** [comment]
Reopen if still having problems.
