### ISSUE TITLE
IDTAXA 32% of ASV is not assigned

### ISSUE THREAD

**Issue by vfonti** [benjjneb/dada2#1220]
Hello,
I am working on some V4V5 16S sequences obtained from marine water samples. To process the reads I have basically just followed your tutorial. I was very curious about IDTAXA, so I have assigned the taxonomy using both the dada2 bayesian classifier and idtaxa. 
Exploring the two relative output, I found that idtaxa is giving me 34% ASV with a NA domain, while using the `assignTaxonomy` function I get only 0.9% NA domain ASVs. In both cases I used silva 138 as reference database.

Here is what I have done (it's pretty much the same as in the online tutorial...): 
```
dna <- DNAStringSet(getSequences(seqtab.nochim)) 
load("F:/SILVA_SSU_r138_2019.RData")
ids <- IdTaxa(dna, trainingSet, strand="top", processors=NULL, verbose=FALSE) 
ranks <- c("domain", "phylum", "class", "order", "family", "genus", "species")

taxid <- t(sapply(ids, function(x) {
  m <- match(ranks, x$rank)
  taxa <- x$taxon[m]
  taxa[startsWith(taxa, "unclassified_")] <- NA
  taxa
}))

colnames(taxid) <- ranks; rownames(taxid) <- getSequences(seqtab.nochim)`
```

And then just to check:
```
dim(taxid)
# [1] 18135     7

```
While with assigntaxonomy:
```
taxaBay <- assignTaxonomy(seqtab.nochim, "F:silva_nr99_v138_train_set.fa.gz", multithread=F)
taxaBay <- addSpecies(taxaBay, "F:silva_species_assignment_v138.fa.gz")
```
And again:
```
dim(taxa)
# [1] 18135     7
```

Any suggestion? Should I stick on the dada2 native classifier?
Many thanks

**Comment by benjjneb** [comment]
`IdTaxa` is intentionally somewhat more conservative than the naive Bayesian classifier (which is what `assignTaxonomy` implements) in a couple of ways so as to avoid the errors of over-classification. Thus the result that there are more NAs with `idTaxa` is not surprising.

What is surprising is that there is such a high fraction of NAs at the top "domain" level... I would probably grab a sample of those ASVs, BLAST them, and see what turns up. Do they look like junk? Or something else?

**Comment by vfonti** [comment]
Hi Ben, 
Thanks a lot for replying.
Yes, I tried. I picked 5 or 6 of the most abundant NA domain ASVs. The output has a certain degree of ambiguity but it is not that bad.. I mean, I don't get a unique assignation but at least I can say the listed correspondences are all in the same domain and often in the phylum. I also tried to blast the few Na domain obtained with dada2 native classifier and I definitely get much worse results.

A few notes:
1.  The distribution of sequence length in my libraries is very large, from 234 to 451 bp (V4-V5 regions):
```
table(nchar(getSequences(pooled.seqtab.nochim)))
# 231  232  233  234  235  236  237  238  239  240  241  242  243  245  246  247  248  249  250  251  252  253  254  255  256  257 
# 2   21    7   10    8    9   13   12   14    7    6   11    1    4   12    9    4   18   11    7    5    9    6    6   12    7 
# 258  259  260  261  262  263  264  265  266  267  268  269  270  271  272  273  274  275  276  277  278  279  280  281  282  283 
# 11   10    8    6    7    2    3    8    6    7    6    4    3    8    8    9    5   10   11    8    8    2   19   20    3    1 
# 284  285  286  287  288  289  290  291  292  293  294  295  296  297  298  299  300  301  302  303  304  305  306  307  308  309 
# 10   10    6    8    5   14   10   27   11    3    4    4   16    6    3    3    3    8    2    1    4    3    1    1    1    5 
# 310  311  312  313  314  315  316  317  318  319  320  321  322  324  325  326  327  328  329  330  331  332  333  334  335  336 
# 4    3    1    9    4    1    4    1    1    3    4    1    2    2    4    4    5    2    4   10   10    4    8    4    2    3 
# 337  338  339  340  341  342  343  344  345  346  347  348  349  350  351  352  353  354  355  356  357  358  359  360  361  362 
# 1    4    1    3    1    5   12    4    2    9    3    7    5    2    2    3    5    8    9   11   11   12   16   12    1   13 
# 363  364  365  366  367  368  369  370  371  372  373  374  375  376  377  378  379  380  381  382  383  384  385  386  387  388 
# 86   56  204  254  151  478  631 2502 1116 3057 3027 5501  825  485  214  348   80   29   74   31   20   28   23   15   16    4 
# 389  390  391  392  393  394  395  396  397  398  399  400  401  402  403  404  405  406  407  408  409  410  411  412  413  414 
# 12   11   11   16   12   10    6    6    5   19    5   12   10    7    8    8   11   11   14    8   13    5    9    5   10    4 
# 415  416  417  418  419  420  421  422  423  424  425  426  427  428  429  430  431  432  433  434  435  436  437  438  439  440 
# 6    9    5    4    5    3    4    3   11    6   12    5    9    2    3    6    5    5    4   11    4    3    6    6    4    8 
# 441  442  443  444  445  446  447  448  449  450  451 
# 13   11   16   10    4    9   14    6   13   16    3 
```
It's the first time I see something like this with the primers I used. 

2. I have analysed my sequences in a `pool= FALSE` mode. I am thinking to redo the analysis pooling my samples together and try with IDTAXA, again. Could this make any difference?

**Comment by vfonti** [comment]
UPDATE
So, I re-analyzed my reads in pooled mode and the classified them with IDTAXA. The situation has not improved.

**Comment by benjjneb** [comment]
If I'm reading what you've done so far correctly: You noticed a difference in the classifications provided by `assignTaxonomy` (i.e. the naive Bayesian classifier) and `IdTaxa`, you evaluated the particular differences you were concerned about (NAs at the domain level) and you observed that you thought that the ASVs (well, those of higher abundance) getting NAs in `IdTaxa` should probably have been being assigned at least down to the domain/phylum level.

To me, you are describing a thoughtful and appropriate approach to choosing between two comparable methods within the context of your own data, and you can feel justified to move forward based on your evaluation.

On other points: You do have a wide range of ASV lengths in your data (although the bulk are seen in the expected length range). One common cause of this is that there is some off-target amplification happening. It is not invalid to consider imposing a length window on the data you want to keep for your analysis. See the "Considerations for your own data" box here in the tutorial: https://benjjneb.github.io/dada2/tutorial.html#construct-sequence-table

**Comment by vfonti** [comment]
Hi Ben,
Thank you very much for your comment and for helping me to make a (peaceful) decision. I appreciate so much your efforts.
V.
