### ISSUE TITLE
Get specific ASV sequences

### ISSUE THREAD

**Issue by provirasanz** [benjjneb/dada2#1221]
Hello,

After assigning taxonomy, I would like to know if there is a way to extract only ASV sequences belonging to a specific genus (i.e. Pseudomonas) in R. 
Thanks in advance

Pablo

**Comment by benjjneb** [comment]
Sure, all that information is available in the taxonomic table output by `assignTaxonomy`:

```
seqs.shewanella <- getSequences(taxtab)[taxtab[,"Genus"] %in% "Shewanella"]
```
