### ISSUE TITLE
Error: invalid class"otu_table" object

### ISSUE THREAD

**Issue by Zuby88** [benjjneb/dada2#1225]
Hello,

I ran this command  - ps.ctrls<-prune_samples(samples = ctrls, x = ps0) and I got an error that says : Error in validObject(.Object) : invalid class “otu_table” object: 
 OTU abundance data must have non-zero dimensions.

Please what can I do to resolve this . Thanks

**Comment by Zuby88** [comment]
I have figured this out. It worked after some trials

**Comment by Jarvis87MDx** [comment]
Hello, 
I am experiencing the same issue. Can you provide some insight into what the problem was/what you changed?

Thank you

**Comment by Zuby88** [comment]
I have to provide the correct variable in which I stored my OTU_table. So when I put the right variable in the above code, it ran successfully .

**Comment by Jarvis87MDx** [comment]
I have it working now also. Thank you so much for the help. 

Best

**Comment by aff30** [comment]
Hi 
I am doing some microbiome analysis I am in the filtering step after the decontam and I got to this error that I can’t find any solution. Could you help me with that?  After the following code, I get the error                                                                                                                                                                                     
### filter for relative abundance

# transform to relative abundance
pst <- transform_sample_counts(psf3, function(x) x / sum(x) )

> # remove taxa with total relative abundance less than 10e-5
> psr <- filter_taxa(pst, function(x) mean(x) > 1e-5, TRUE)
Error in validObject(.Object) : invalid class “otu_table” object:
 OTU abundance data must have non-zero dimensions. 

I thought there was a problem in my pst but here is the info of it: 
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 3377 taxa and 51 samples ]
sample_data() Sample Data:       [ 51 samples by 3 sample variables ]
tax_table()   Taxonomy Table:    [ 3377 taxa by 6 taxonomic ranks ]

Any help would be very appreciatted. 
Thank you

**Comment by benjjneb** [comment]
@aff30 This looks like an issue with the phyloseq package rather than the dada2 package, you might want to look at the phyloseq site.

I don't know what is going on, but I'd start by taking a look at the logical vector that `filter_taxa` makes, to see if it sensible or if perhaps every taxa is being removed or something.
