### ISSUE TITLE
RDP Classifier 16S trainset No18

### ISSUE THREAD

**Issue by travisgibson** [benjjneb/dada2#1226]
RDP has a new training set for taxa and species assignments. Has anyone formatted the new RDP set for DADA2?

**Comment by benjjneb** [comment]
Just did this today: https://doi.org/10.5281/zenodo.4310150

**Comment by travisgibson** [comment]
you rock!!

**Comment by jeffkimbrel** [comment]
For some reason this link to training set 18 (and the same link from the dada2 [taxanomic reference data](https://benjjneb.github.io/dada2/training.html) page) are giving a Zenodo internal server error. The other training set links do work at Zenodo.

Not sure what can be done about it, just documenting here.
