### ISSUE TITLE
Explanation of observed transition rates with binned Q-scores

### ISSUE THREAD

**Issue by LukeJMcCartin** [benjjneb/dada2#1228]
I am dealing with NovaSeq data where the quality scores are binned (11, 25, 37). I'm looking into the best way to fit the observed transition errors when learning the error rates, and I'm a bit confused. While my data only have the three quality scores listed above, the matrix of observed nucleotide transitions ('trans') has observed transitions at all consensus Q scores, not simply at 37, 11, 25 or their averages. Does each value in the matrix reflect a single observed transition error, or does it reflect the mean of some distribution of all transitions around the most frequently observed sequence in a partition?

An explanation here would be greatly appreciated as I investigate the best way to handle this data. Thanks!

**Comment by benjjneb** [comment]
> Does each value in the matrix reflect a single observed transition error, or does it reflect the mean of some distribution of all transitions around the most frequently observed sequence in a partition?

It reflects the mean quality score of a collection of identical sequences at a given position. So if there are 10 reads with the exact same sequence, the mean quality scores at each position are calculated, which can then vary between the binned scores.

The observed data is highly-highly enriched at the binned Q scores though, which is not well communicated by the `plotErrors` viz.

**Comment by LukeJMcCartin** [comment]
Ben, thanks so much for this helpful answer. So would a transition, let's say A - G at q-score 31, reflect an error where a sequence contained a G rather than an A that is found in the inferred ASV it is derived from at a position where the mean Q score is 31?

I have thought about approaching this problem with the binned q scores by either using the error model that does not incorporate Q scores (noqualErrfun) after some stringent quality filtering or using a model other than the weighted loess.

**Comment by benjjneb** [comment]
> So would a transition, let's say A - G at q-score 31, reflect an error where a sequence contained a G rather than an A that is found in the inferred ASV it is derived from at a position where the mean Q score is 31?

Yes.

> I have thought about approaching this problem with the binned q scores by either using the error model that does not incorporate Q scores (noqualErrfun) after some stringent quality filtering or using a model other than the weighted loess.

The binned qual score issue is an open one. The current DADA2 error-fitting works OK, but... it could work better.

**Comment by LukeJMcCartin** [comment]
Thanks so much! This is very clear to me now.
