### ISSUE TITLE
Trimming poly-A and poly-T with cutadapt using DADA2 

### ISSUE THREAD

**Issue by MatGola** [benjjneb/dada2#1229]
Hi,
I've been using the example in the following workflow: https://benjjneb.github.io/dada2/ITS_workflow.html

It seems to work just fine so far. I'm trying to understand if there is a way to further use cutadapt to trim poly-A and poly-T 
sequences as cutadapt suggests?

Best

**Comment by benjjneb** [comment]
I think yes, at least according to the cutadapt docs: https://cutadapt.readthedocs.io/en/stable/recipes.html#trim-poly-a-tails

You'll have to look there though for help on cutadapt-specific features.
