### ISSUE TITLE
Interested in trying isBimeraDenovoTable--- don't know how

### ISSUE THREAD

**Issue by KMKemp** [benjjneb/dada2#123]
Hello Ben,

I have been running two different datasets through dada2 (I pasted some stats below). In one of my datasets, 40% of the sequence variants are detected as bimeras (but only 10% of the overall reads). In the other dataset, bimeras only make up about 8% of the sequence variants and 3.4% of the total sequence reads... same primer set and pcr conditions. I am interested in trying the "per sample" method to detect bimeras.... your new isBimeraDenovoTable function.... to see if less of the sequence variants are detected as bimeras in the first dataset. 

I've taken a look at the code and tried running some of it in R... but as a novice... I am not really sure how to do this. I would be grateful for any tips you can provide to set me straight! Thanks!

[dataset1.pdf](https://github.com/benjjneb/dada2/files/486406/dataset1.pdf)
[dataset2.pdf](https://github.com/benjjneb/dada2/files/486407/dataset2.pdf)

**Comment by benjjneb** [comment]
Hi,
I'll have `isBimeraDenovoTable` integrated into the `removeBimeraDenovo` convenience interface soon, but for now you can use it in the following way:

```
bim <- isBimeraDenovoTable(seqtab)
seqtab.nochim <- seqtab[,!bim]
```

According to our testing the consensus approach in `isBimeraDenovoTable` outperforms both pooling (the current default for tables) and independent sample-wise chimera removal in accuracy. It will be the new default chimera removal method for sequence tables in the next package release.

ps. You're chimera values don't look crazy, chimera rates can fluctuate a fair amount even when using the same protocol. I don't think `isBimeraDenovoTable` will make them more equal, but if it does, let me know!

**Comment by KMKemp** [comment]
Thats good to hear about my chimera values!

I think I'll just wait until you get the R package updated. I still can't get it to work, but it sounds like what I have done this far with the "old" bimera detection methods is okay.

Thanks!
