### ISSUE TITLE
Thoughts on concatenation

### ISSUE THREAD

**Issue by AlexaBennett** [benjjneb/dada2#1231]
I am curious as to your opinion on concatenation of long amplicons' forward and reverse reads. QIIME2 does not support this functionality for DADA2 within their environment. In fact, they regularly urge individuals to utilize only the forward or reverse reads stating it is more 'trustworthy' and produces 'reliable results'. 

Follow up: would you be open adding this functionality to the QIIME2 environment?

**Comment by benjjneb** [comment]
I did not realize this was general suggestion on the QIIME forums.

That said, as a general suggestion I think I agree. Typically using one high-quality read will produce good results. Sometimes better than forcing overlaps, especially for ambitious amplicons where the reads barely overlap.

> Follow up: would you be open adding this functionality to the QIIME2 environment?

Yes. If this was a common request on the Q2 forums. Is it? (admittedly I really only go there these days when the Q2 folks "tag me in").

**Comment by AlexaBennett** [comment]
> Yes. If this was a common request on the Q2 forums. Is it?

It is a topic which is more common than others. A quick search on the forum shows ~1 question per month. 

From personal experience, the desire to concatenate is due to the limited diversity of high coverage priming locations. In short, the best primer pair to answer a given question produces an amplicon larger than ~450bp. Therefore, the reads are not expected to overlap. Moreover, there is the issue of directionality of insertion regarding sequencing adapters (within certain pipelines). The forward primer is located in read 1 or 2 with approximately equal distribution. This reduces the desire to restrict use to one read because data is a mixture of 5' and 3' amplicon.

**Comment by benjjneb** [comment]
Can you comment on the thread in the Q2-dada2 plugin GH package on this topic? https://github.com/qiime2/q2-dada2/issues/129
