### ISSUE TITLE
30% of reads are missing after merging paired-end reads using dada2

### ISSUE THREAD

**Issue by mingleiR** [benjjneb/dada2#1234]
Hi Ben,
Thank your for providing the powerful tool 'dada2'.

Following the dada2 tutorial, I analyzed the amplicon data and adjusted the important parameters (like truncLen, and minOverlap), finally I still could not find the solution or the reason why more than 30% of reads are missing after merging ASV from paired-end reads. 

The target amplicon is archaeal 16S rRNA V4-V5 region, which was amplified using the primer pair arch519F-915R (Forward 5-3: CAGCCGCCGCGGTAA; Reverse 5-3: GTGCTCCCCCGCCAATTCCT). The reads were generated using HiSeq PE250 platform. Actually, the real length of forward and reverse reads I got from sequencing company is 250 and 235 bp, respectively, both of which contains the primers mentioned above. Firstly, the primers were trimmed from both forward and reverse reads using cutadapt as recommended by [this blog (https://astrobiomike.github.io/amplicon/dada2_workflow_ex). The primer was removed successfully through manually check using linux command tools. Secondly, the trimmed reads were analyzed using the dada2 package (v1.13.1) following the tutorial: (1) trim the reads; (2) learn the error rate; (3) dereplicate the sequence and then run the core algorithm of dada2 using the estimated error rate; (4) merge paired-end data; (5) make ASV table and delete chimera, and assign taxonomy. And the statistics for each steps is as follows:

site    input   filtered        denoisedF       denoisedR       merged  nonchim
lgs01   145744  145744  134637  136652  85423   75348
lgs02   132251  132251  125123  126198  96728   78025
lgs03   162398  162398  150429  152660  94638   64429

Obviously, from denoised to merged step, more than 30% of reads is missing. I'm not sure the result is normal. Just wanna to find the reason or save the data. The target fragment of archaeal 16S V4-V5 is about 396 bp, and the total length of both primers is 35 bp. When trimming primers from forward and reverse reads, the length of paired reads are 235 and 215 bp. Therefore, I believe there is much overlap between the paired read. The distribution of the number of matched base from the ~85423 merged ASV also verify this point. The truncLen and minOverlap was set with default value (0 and 12). I also decreased the minOverlap to 5 (according to one issue in your github), the result didn't change much. For me, the error rate plot is a little strange (when compared to the plot in the dada2 tutorial), with the expected error rate at the highest Phred (Q=40) becoming higher.  Could you give me any hint about the missing reads after merging ASVs from both ends of reads?

Thanks in advance.
minglei

Two scripts (for running cutadapt and dada pipeline) were attached. Three plots for visualizing the phred quality for primer-free reads and trimmed reads, and estimated error rates were also attached. 
[dada2_script.txt](https://github.com/benjjneb/dada2/files/5713472/dada2_script.txt)
[cutadapt_script.txt](https://github.com/benjjneb/dada2/files/5713473/cutadapt_script.txt)
[quality_before_trimming.pdf](https://github.com/benjjneb/dada2/files/5713475/quality_before_trimming.pdf)
[quality_after_trimming.pdf](https://github.com/benjjneb/dada2/files/5713477/quality_after_trimming.pdf)
[estimated_error_rate.pdf](https://github.com/benjjneb/dada2/files/5713476/estimated_error_rate.pdf)

**Comment by benjjneb** [comment]
You are suffering a potentially problematic drop in the merger step, but the quality profiles and the chimera removal numbers are not the reason why. Your quality profiles look different because your data is from a binned-quality-score machine. Your chimera removal fraction is in bounds of common fractions (albeit higher than you would want if using a well-chosen PCR protocol).

The only concerning step here is the merger step. How much hav eyou investigated extending the `truncLen` parameters to see if that can be ameoliorated?

**Comment by mingleiR** [comment]
Thanks for your quick reply and sorry for my later response. 

Could you give more explanation about "binned-quality-score" machine?  When you mention "in bounds of common fraction", does it mean that the result could be acceptable (although not best)?  

 The tracking statistics through setting different values of the **truncLen**  parameter (keeping the **minOverlap** as the default value) were shown as follows:
(1) default value (0)

site    input   filtered        denoisedF       denoisedR       merged  nonchim
lgs01   145744  145744  134637  136652  85423   75348
lgs02   132251  132251  125123  126198  96728   78025
lgs03   162398  162398  150429  152660  94638   64429

(2) truncLen = c(210, 200)

site    input   filtered        denoisedF       denoisedR       merged  nonchim
lgs01   145744  145707  137408  138445  88281   74749
lgs02   132251  132231  126504  127552  100469  77904
lgs03   162398  162378  153450  154995  102299  64046

(3) truncLen = c(190, 190)

site    input   filtered        denoisedF       denoisedR       merged  nonchim
lgs01   145744  145730  138695  139633  171     171
lgs02   132251  132239  127420  128064  74      74
lgs03   162398  162386  155029  156055  85      85

When truncating more bases from the ends of the forward and reverse reads,  more reads are missing.

**Comment by benjjneb** [comment]
> When truncating more bases from the ends of the forward and reverse reads, more reads are missing.

Yes with the `c(190, 190)` truncation lengths the reads become too short to overlap and therefore aren't merging, which is as expected for a ~396bp amplicon.

What I would investigate is whether increasing the truncation lengths somewhat from `c(210,200)` could get eiven better merging values than you are already seeing (perhaps due to biological variation in the amplicon length that is kept by longer lengths). I would at least try `c(220,210)` and see if it is an improvement.

> cutadapt_script.txt

I'll also mention, I've typically found that using `trimLeft=c(FWD_PRIM_LEN, REV_PRIM_LEN)` works better than cutadapt **IF** you are in the common circumstance where fixed length primers are present only at the starts of the forward and reverse reads.

**Comment by mingleiR** [comment]
Bens, Thanks for your reply.


(1)  I compare the effect of different 'truncLen' with the default value of 'minOverlap', as following

truncLen = 0
site input filtered denoisedF denoisedR merged nonchim
lgs01 145744 145744 134637 136652 85423 75348
lgs02 132251 132251 125123 126198 96728 78025
lgs03 162398 162398 150429 152660 94638 64429

truncLen= c(220, 210)
site    input   filtered        denoisedF       denoisedR       merged  nonchim
lgs01   145744  145672  136056  137126  85586   74883
lgs02   132251  132215  125815  126798  97520   78370
lgs03   162398  162372  151819  153299  95553   64551

truncLen= c(215, 210)
site    input   filtered        denoisedF       denoisedR       merged  nonchim
lgs01   145744  145698  136687  137142  85613   74893
lgs02   132251  132223  126177  126808  97759   78502
lgs03   162398  162376  152425  153309  95247   64519

truncLen = c(210, 200)
site input filtered denoisedF denoisedR merged nonchim
lgs01 145744 145707 137408 138445 88281 74749
lgs02 132251 132231 126504 127552 100469 77904
lgs03 162398 162378 153450 154995 102299 64046

truncLen= c(205, 200)
site    input   filtered        denoisedF       denoisedR       merged  nonchim
lgs01   145744  145724  138006  138465  90242   74867
lgs02   132251  132235  126913  127529  102599  77930
lgs03   162398  162385  154133  154974  105718  63726


(2)  I also tried the parameter of the trimLeft=c(15, 20) on the primer-containing sequence, and the resulting result looks the same as (the default one):
site    input   filtered        denoisedF       denoisedR       merged  nonchim
lgs01   160052  146564  135276  137290  85727   75068
lgs02   145341  132863  125590  126708  97035   77650
lgs03   177606  163384  151215  153518  94971   63715

These results show that there is no difference in regarding to the number of ASV after removing chimera. Maybe these number is true for these ASV-represented species. However, I cannot give the explanation for the missing nearly 30% reads at the final 'merging' stage.

**Comment by benjjneb** [comment]
That is quite useful, and suggests that the results are robust to (minor) variation around the `truncLen=c(210, 200)` parameter choice. So, I would go with that.

> However, I cannot give the explanation for the missing nearly 30% reads at the final 'merging' stage.

At this point it is hard to say why that is happening. There are multiple reasons it could occur, including at least off-target amplification producing amplicons much longer or shorter than the expected length, poor resolution of very rare variants in the low quality part of the sequencing reads, and artefacts introduced by the sequencer and/or PCR.

We do not have automated facilities to check for those possibilities. An intrepid R user could go farther using the output of `mergePairs(..., returnRejects=TRUE)`, which produced a data.frame that includes all the failed mergers as well.

**Comment by mingleiR** [comment]
Bens, Thanks for your helpful comment about the possible reasons. 

Besides, I analyzed bacteria amplicon dataset (V4-V5) using the same pipeline (cutadapt + dada2), and the result looks perfect based on statistics at each step. Maybe the question occur in the wet experiment for Archaea amplicon. As you suggested, I'll explore the question later.

Thanks again.

Minglei
