### ISSUE TITLE
Species identification

### ISSUE THREAD

**Issue by termithorbor** [benjjneb/dada2#1237]
Hi all,

can I use dada2 also when I have isolated DNA from a single colony and want to identify which species it is or are there other more suitable pipelines/tools available?

Thanks in advance :)

**Comment by benjjneb** [comment]
You can, it has even been used in that way in a couple clinical micro labs. Note, this is only really appropriate if you are doing next-gen amplicon sequencing on your colony (i.e. generating 100s or more reads). If it's just a Sanger read or a few, should use a different tool.

**Comment by termithorbor** [comment]
It is sequencing in Illumina MiSeq. Can I also analyse different samples from single colonies in parallel?

**Comment by benjjneb** [comment]
Sure, they are just different samples same as in an environmental sequencing experiment.
