### ISSUE TITLE
Error in writeFastq(fqF, fout[[1]], "w", compress = compress) 

### ISSUE THREAD

**Issue by pstevens2109** [benjjneb/dada2#1238]
Hi benjjneb, 

I was following your tutorial and everything was working well until this problem : 

> out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,compress=TRUE, multithread=FALSE) # On Windows set multithread=FALSE

Error in writeFastq(fqF, fout[[1]], "w", compress = compress) : 
  failed to open file 'C:\Users\pstevens\OneDrive\MÃ©decine\ThÃ¨se\Bio_inf projet\miseqsopdata\MiSeq_SOP\filtered\F3D0_F_filt.fastq.gz'
  
  Here my previous code : 
  
> fnFs <- sort(list.files(path, pattern="_R1_001.fastq", full.names = TRUE))
> fnRs <- sort(list.files(path, pattern="_R2_001.fastq", full.names = TRUE))
> sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
> filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
> filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))

and then the error : 

> out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
                     maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, multithread=FALSE) # On Windows set multithread=FALSE
> head(out)

Could you help me to identify the problem ? 

Many thanks !

**Comment by benjjneb** [comment]
There are special characters that are malformed in the filenames you are attempting to write to (see the message you posted above).

Can you fix that, either on the filesystem side or on the R character parsing side?

**Comment by pstevens2109** [comment]
It works when removing characters, many thanks !
