### ISSUE TITLE
learn error step for samples from multiple studies

### ISSUE THREAD

**Issue by sankadinesh** [benjjneb/dada2#1239]
Dear all,
I would like to perform learn error step. By default, DADA2 is taking only one file (largest). All my files (120 files) are from 8 different studies. What would be the best approach ? Is it possible to input 2 files/study to get even representation ?

Thanks 
Regards,
Dinesh

**Comment by benjjneb** [comment]
Since different studies use different protocols, and therefore can have different error rates, the recommendation is to learn errors on each study individually, use that model to denoise that study, then merge the ASV tables together at the end.

**Comment by sankadinesh** [comment]
Dear Sir, 
Thank you for reply. For meta-analysis approach involving a single gene from multiple studies using different primers what should be the best approach ?

As I understand, 
1. Error modelling individually (based on your reply)
2. Is it necessary to align and trim ASVs before merging ? Because the ASVs are of different length and when aligned, there are unaligned portion in both sides (please check image). Will it lead to overestimation of ASVs, if directly ASVs and count files combined ?

Is this correct approach or pls correct if I am wrong. 

![Screenshot 2021-01-04 at 12 07 50 PM](https://user-images.githubusercontent.com/43870684/103508276-b689cb00-4e86-11eb-9624-d747d1d0bd29.png)


Thanks 
Regards,
Dinesh S L

**Comment by benjjneb** [comment]
On (2), you can simply merge ASVs from different studies only if they are starting and ending at the same positions. Typically this means that they used the same forward/reverse primers, or at least the same forward primers and all reads were (truncated to) the same length across studies.

Combining ASVs using different primer sets is either impossible if they don't overlap, or requires a careful additional step in which the ASVs from different studies are all truncated to the same starting/ending positions.

**Comment by sankadinesh** [comment]
Dear Sir, 
Thanks for your reply. 
Can you please provide some references (method containing necessary command) for merging ASV tables ?
Regards,
Dinesh S L

**Comment by benjjneb** [comment]
> Can you please provide some references (method containing necessary command) for merging ASV tables ?

From studies using different primer sets? I can't, as that is not often done.

**Comment by sankadinesh** [comment]
Dear Sir, 
No. For sequences of same length with similar primer. 
Regards,
Dinesh SL

**Comment by benjjneb** [comment]
"similar primer" sounds like different primers, albeit overlapping.

They need to be trimmed to the same starting position first, and then truncated to a common length. I don't know of an existing resource describing specific commands to do that though.
