### ISSUE TITLE
Regarding Taxanomy

### ISSUE THREAD

**Issue by njepsi** [benjjneb/dada2#1240]
Hi,

I am new to amplicon sequencing. I was wondering if you could provide me some suggestions regarding the DADA2 package.

I have MiSeq data that performed on hCoV-229E positive nasal positive samples data. I applied the DADA2 package in the "Assign Taxonomy" step I got confused. Which taxa should I use? Any suggestions would be greatly appreciated. 

Thank you very much in advance!

**Comment by benjjneb** [comment]
> Which taxa should I use?

I don't know what this means. Like, which taxonomic database (RDP, Silva etc.)? Or, which taxa to keep for your further analysis? Or...? Please elaborate. Also, is this 16S sequencing?

**Comment by njepsi** [comment]
Hi, 

Yes, this is 16S sequencing data. I mean which taxonomic database should I use.

Thank you!

**Comment by benjjneb** [comment]
I recommend Silva.

**Comment by njepsi** [comment]
Thank you!
