### ISSUE TITLE
Taxonomy Assignment tryRC

### ISSUE THREAD

**Issue by naurasd** [benjjneb/dada2#1241]
Hi and happy new year,

I just have a quick question regarding the tryRC parameter of the assignTaxonomy function. As described, for tryRC = TRUE "the reverse-complement of each sequences will be used for classification if it is a better match to the reference sequences than the forward sequence." So to me that means that both options (reverse-complement and regular forward sequence) are being evaluated and the best option is chosen. If this is the case, why not set tryRC = TRUE every time we run taxonomy assignment? Is this a matter of computation time and tryRC = FALSE is just faster?

Thanks
Nauras

**Comment by benjjneb** [comment]
> If this is the case, why not set tryRC = TRUE every time we run taxonomy assignment? Is this a matter of computation time and tryRC = FALSE is just faster?

Yep. `tryRC=TRUE` takes ~2x as long.

Is it preferable to have the default be a 2x slowdown if that helps folks with reads in an orientation they weren't expecting? Input welcome, maybe that would be a better default. Right now `tryRC=FALSE` is the default for purely historical reasons, there was no `tryRC` option in the first implementation of the function.

**Comment by naurasd** [comment]
Thanks for the quick reply. I will set tryRC=T from now on then, just to be on the safe side. Might not be a big factor for marker genes such as COI, but I guess it could make a difference for amplicon reads of a more challenging marker gene such as ITS.

I guess when running dada2 on HPC resources, the computation time is a trade off I am willing to accept as I am not dealing with thousands of samples with millions of reads.

thanks again
Nauras
