### ISSUE TITLE
"sequence tables found invalid"

### ISSUE THREAD

**Issue by sankadinesh** [benjjneb/dada2#1242]
Hi there, 
I have imported sequence tables and tried to merge using mergeSequenceTables function but unable to merge. 

Table_PRJDB5679 <- read.table(file = "PRJDB5679.tsv", header = T, sep = "\t", row.names=1, check.names = F)

Table_PRJDB9222 <- read.table(file = "PRJDB9222-water.tsv", header = T, sep = "\t", row.names=1, check.names = F)

Table_PRJNA476143 <- read.table(file = "PRJNA476143.tsv", header = T, sep = "\t", row.names=1, check.names = F)

Table_PRJNA578352 <- read.table(file = "PRJNA578352.tsv", header = T, sep = "\t", row.names=1, check.names = F)

mergetab <- mergeSequenceTables(Table_PRJDB5679, Table_PRJDB9222, Table_PRJNA476143, Table_PRJNA578352)

**Error in mergeSequenceTables(Table_PRJDB5679, Table_PRJDB9222, Table_PRJNA476143, : Some sequence tables found invalid**

Herewith, I have attached files for perusal. Please tell me why I am getting the error
[https://www.dropbox.com/sh/lom2fd4f8gwbkd8/AACKuKT-dpF6KM8a6LBPQC__a?dl=0](url)

Regards,
Dinesh S L

**Comment by benjjneb** [comment]
I strongly recommend using the `saveRDS`/`readRDS` functions for saving a reading tables from R. This maintains all the information about those tables, including rownames/colnames and the data types of the table. This information is often lost when writing out to a tab separated file and reading back in, which is almost certainly the issue you are running into.
