### ISSUE TITLE
Merging sequence tables generated with varying truncLen values

### ISSUE THREAD

**Issue by naurasd** [benjjneb/dada2#1245]
Hi @benjjneb ,

I am using dada2 for ASV inference of an COI amplicon dataset. Reads were generated during various sequencing events. The same primers were used to amplify the target region. Performing all the steps down to forward/reverse read merging separately for each sequencing run and am merging sequence tables prior to chimera removal. 

Here my question: Given the quality profile plots of my reads, I set different maxEE values during filterAndTrim of my various read datasets from different sequencing runs. This should not be a problem for downstream analysis I think, I have seen in papers that this has been done to improve the error model estimation later on. However, I also set different truncLen values for my read datasets. My intuition tells me that this is also not a problem when merging sequence tables of various sequence runs, as these different read lengths are eliminated during the mergePairs step. Is this correct? Or does the use of different truncLen values cause any analytical problems downstream? 

Thanks
Nauras

**Comment by benjjneb** [comment]
> However, I also set different truncLen values for my read datasets. My intuition tells me that this is also not a problem when merging sequence tables of various sequence runs, as these different read lengths are eliminated during the mergePairs step. Is this correct? Or does the use of different truncLen values cause any analytical problems downstream?

Yes you are correct. You can use different `truncLen` parameters based on the quality profiles if the merged reads are use thereafter.

**Comment by naurasd** [comment]
thanks so much as always for the quick and clear reply.
