### ISSUE TITLE
Non AGTC sequences in Unite 8.2 database

### ISSUE THREAD

**Issue by termithorbor** [benjjneb/dada2#1248]
Dear all,

when I use the latest fasta release of the Unite db version 8.2 I get the following warning:

fasta: ignored 2 invalid one-letter sequence codes

Has anybody encoutered the same error and figured out which sequences contain the invalid letter?

Thanks in advance :)

**Comment by benjjneb** [comment]
I haven't but this is a warning I wouldn't worry about.

The non-ACGT sequences just get filtered out automatically, and if only 2 invalid sequence codes were detected, then at most 2 sequences (and perhaps just one) in the whole db were affected.
