### ISSUE TITLE
Error in assignTaxonomy:

### ISSUE THREAD

**Issue by ninglinwang** [benjjneb/dada2#1250]
Dear Sir, 
When I am processing my data following "A DADA2 workflow for Big Data: Paired-end (1.4 or later)", an erroe happened in assignTaxonomy:
seqtab_final <- assignTaxonomy(seqtab, paste0(path, "/silva_nr_v132_train_set.fa.gz"), multithread=FALSE)
Error in C_assign_taxonomy(seqs, rc(seqs), refs, ref.to.genus, tax.mat.int,  : 
  Sequences must be at least 50 nts to classify.

I have looked into the issues and 
 table(nchar(colnames(seqtab_final)))
39    40    46    48    50    51    52    53    54    57    58    59    61    62    69    70    71    76    78    80    82    84 
   11     1     1     3     2     8     8     1     1     1     1     1     5     1     1     1     2     2     1     1     1     1 
   99   101   102   104   108   109   115   116   121   125   130   132   134   135   136   137   141   145   150   152   154   157 
    1     1     2     1     1     1     1     1     1     1     1     1     1     1     1     2     1     1     1     2     1     1 
  160   161   167   172   174   176   179   180   181   182   184   185   186   189   190   192   193   194   195   196   197   198 
    1     1     1     3     1     1     5    38    23     1     4     6     1     3     5     2     1     1    21    15    17     3 
  199   200   201   202   203   204   205   206   207   208   209   210   211   212   213   214   215   216   217   218   219   220 
    1     1     7     7    12    14    18     6     5     4     2     1     4    32    17     5     7     1    74  7384  2601   551 
  221   222   223   224   225   226   227   228   229   230   231   232   233   234   235   236   237   238   239   240   241   242 
  152   167   180   271   281   301   274   289   267   215   186   195   171   255   255   261   270   223   270   282   290   289 
  243   244   245   246   247   248   249   250   251   252   253   254   255   256   257   258   259   260   261   262   263   264 
  233   223   125    85    44    48    37    63    72    59    70   105    86    72    62    50    36    34    46    52    60    49 
  265   266   267   268   269   270   271   272   273   274   275   276   277   278   279   280   281   282   283   284   285   286 
   32    51    54    48    35    40    47    45    47    63    58    64    98    96    74    45    23    28    18    19    29    38 
  287   288   289   290   291   292   293   294   295   296   297   298   299   300   301   302   303   304   305   306   307   308 
   22    22    24    15    19    17    24    14    20    13    20    28    21    27    19    21    28    26    30    33    31    31 
  309   310   311   312   313   314   315   316   317   318   319   320   321   322   323   324   325   326   327   328   329   330 
   43    34    36    31    24    39    51    44    38    37    44    34    54    50    71    75   108    95    65    86   100    67 
  331   332   333   334   335   336   337   338   339   340   341   342   343   344   345   346   347   348   349   350   351   352 
   62    64    67    55    76    81    90   104    66    53    68    77    85    76    90    57    63    58    48    57    50    51 
  353   354   355   356   357   358   359   360   361   362   363   364   365   366   367   368   369   370   371   372   373   374 
   65    68    67    72    77    91    83    73   100    77    72    88    72    64    55    70    88    55    47    61    72    78 
  375   376   377   378   379   380   381   382   383   384   385   386   387   388   389   390   391   392   393   394   395   396 
   58    86    91    75    73    58    61    79    65    86    90   153   112   124   106    63    92   137    63    50    49    37 
  397   398   399   400   401   402   403   404   405   406   407   408   409   410   411   412   413   414   415   416   417   418 
   54    62    85   105    81   129  1059 10383  4057  3807  5592  1195  3548   779   366   242   211   101   120   416   404   538 
  419   420   421   422   423   424   425   426   427   428 
  278   312  1211   644  2733 14489  1985  1057   759  9988 

It seemed that there are a lot of short sequences. Where is my mistake?
Thank you!

**Comment by benjjneb** [comment]
How did you pre-process this data? I.e. prior to using the dada2 R package, and also including any `filterAndTrim` steps within the package.
