### ISSUE TITLE
learnErrors dada2 1.19.1 (R 4.0.2)

### ISSUE THREAD

**Issue by AlinJulia** [benjjneb/dada2#1251]
Hi benjjneb,
I'm trying to achieve the learnErrors step in one set of 10 seqs (Illumina Miseq 250) running the dada2 pipeline on dada2 package version 1.19.1.
The problem is that I get the output but the process appears still running and also I don't get the related object created (see the capture attached).
Could you please help me?

![Capture](https://user-images.githubusercontent.com/65224244/104849651-31250280-58eb-11eb-9704-1b33dd655cc9.PNG)

**Comment by icotto25** [comment]
Hello @AlinJulia @benjjneb,
 I am having the same issue. Can you please let me know you to fix it? I am using dada2 v1.19.2.

![image](https://user-images.githubusercontent.com/65976667/119272932-86915900-bbd6-11eb-8cf7-3492ae15b545.png)

**Comment by benjjneb** [comment]
@icotto25 It probably is just a run-time issue. I would try running with `verbose=TRUE` which will at least give output through each cycle of the self-consistency loop.
