### ISSUE TITLE
pool=TURE in workflow of big pacbio data 

### ISSUE THREAD

**Issue by 7kylin** [benjjneb/dada2#1253]
hi Ben @benjjneb ：
I have some questions while  using pool=TURE in the workflow of big pacbio data.
      Here is my script  I wrote based on your answer at [https://github.com/benjjneb/dada2/issues/479](url) :

     filts <- list.files(path,pattern="fastq.gz",full.names=TRUE)

      drp <- derepFastq(filts, verbose=TRUE)

      err <- learnErrors(drp, errorEstimationFunction=PacBioErrfun, BAND_SIZE=32, multithread=TRUE)  

      sample.names <- sapply(strsplit(basename(filts), "_"), `[`, 1)  

      names(filts) <- sample.names  

      dds<-dada(drp, err=err, BAND_SIZE=32, multithread=TRUE,DETECT_SINGLETONS=TRUE)  

      seqtab <- makeSequenceTable(dds)  

      priors <- getSequences(seqtab)[colSums(seqtab)>=2]  

      dds2 <- vector("list", length(sample.names))  

      names(dds2) <- sample.names  

      for(sam in sample.names){  

           cat("Processing:", sam, "\n")  

           derep <- derepFastq(filts[[sam]])  

           dds2[[sam]] <- dada(derep, err=err, multithread=TRUE,priors=priors,BAND_SIZE=32)  

      }  

      seqtab2 <- makeSequenceTable(dds2)  

      saveRDS(seqtab2,file.path(path.rds,"Test2_dd.rds"))

Then I tested the script and a normal  script with pool=TURE with 20 samples. But the results was different from what had been expected which still had ”unique ASV“. The unique ASV means that has only one reads support.  In addition I got more than 2000 ASV with pool=TURE and more than 4000 ASV with this script.  I don't kown the why  the results still had ”unique ASV“ and I have no idea about the latter case.
Please  what should I do then if I only want to get rid of the "unique ASV" ?
Thank yo very much !

**Comment by benjjneb** [comment]
A couple things. First, the package has been updated since 2018 in a way that makes running `pool="pseudo"` easier on large datasets. As long as you work with filenames directly (and leave out `derepFastq` calls), then you can run large datasets in the normal tutorial way without memory problems. So the above would largely simplify to:

```
# Define sample files
filts <- list.files(path,pattern="fastq.gz",full.names=TRUE)
sample.names <- sapply(strsplit(basename(filts), "_"), `[`, 1)  
names(filts) <- sample.names
## Denoise
err <- learnErrors(filts, errorEstimationFunction=PacBioErrfun, BAND_SIZE=32, multithread=TRUE)
dd <- dada(filts, err=err, multithread=TRUE, pool="pseudo", BAND_SIZE=32)
```

Alternatively you can stick in `pool=TRUE` there at the `dada(...)` step, although that does intrinsically require all samples loaded into memory at once. Then it would be good to also show the code you are using to call `pool=TRUE` mode, as that is unclear from the above.

> Please what should I do then if I only want to get rid of the "unique ASV" ?

You can always filter out "unique ASVs" (ASVs with just one read in one sample supporting them?) from the final table if desired.

**Comment by 7kylin** [comment]
Thank you for your reply.   I'm sorry about that  I didn't express it clearly.   I have more than 200  samples and each one has more than 10,000 reads.  I  got too few ASVs with DETECT_SINGLETONS=FALSE, so I runing dada with pool=TURE which can filter singleton in all the samples. But it runned too slow for more than 200 samples with pool=TURE. So is there some approach to slove this question?  The  "unique ASV"  refers to at least 2 reads support in all samples.

**Comment by isidoramorel** [comment]
Hi Ben @benjjneb
I'm currently running dada2 in a 28 samples dataset of full-length 16S (pacbio) sequences.
The dada step has been running for more over a week now (in a highmem server), this is my command: 

`dd <- dada(drp, err=err, multithread=TRUE, BAND_SIZE=32, pool=T) 
28 samples were pooled: 2286977 reads in 1350925 unique sequences
`

Do you think changing to pool="pseudo" would make it much faster? What would you recommend in this case? 

Thanks!!

**Comment by benjjneb** [comment]
> Do you think changing to pool="pseudo" would make it much faster? What would you recommend in this case?

Yes and yes.

**Comment by isidoramorel** [comment]
> > Do you think changing to pool="pseudo" would make it much faster? What would you recommend in this case?
> 
> Yes and yes.

Great, thank you @benjjneb ! I'll give it a try and let you know how long it takes, the other process is still running after almost two weeks.

**Comment by 7kylin** [comment]
> A couple things. First, the package has been updated since 2018 in a way that makes running `pool="pseudo"` easier on large datasets. As long as you work with filenames directly (and leave out `derepFastq` calls), then you can run large datasets in the normal tutorial way without memory problems. So the above would largely simplify to:
> 
> ```
> # Define sample files
> filts <- list.files(path,pattern="fastq.gz",full.names=TRUE)
> sample.names <- sapply(strsplit(basename(filts), "_"), `[`, 1)  
> names(filts) <- sample.names
> ## Denoise
> err <- learnErrors(filts, errorEstimationFunction=PacBioErrfun, BAND_SIZE=32, multithread=TRUE)
> dd <- dada(filts, err=err, multithread=TRUE, pool="pseudo", BAND_SIZE=32)
> ```
> 
> Alternatively you can stick in `pool=TRUE` there at the `dada(...)` step, although that does intrinsically require all samples loaded into memory at once. Then it would be good to also show the code you are using to call `pool=TRUE` mode, as that is unclear from the above.
> 
> > Please what should I do then if I only want to get rid of the "unique ASV" ?
> 
> You can always filter out "unique ASVs" (ASVs with just one read in one sample supporting them?) from the final table if desired.

hi~Ben @benjjneb 
I runned dada2 with 200 samples using pool="pseudo" but the results still had singleton. What's the difference between pool =TURE and pool="pseudo".
Thanks and best wishes for you!

**Comment by benjjneb** [comment]
@7kylin This page give a fair amount of detail about pseudo-pooling that I think should answer your questions. It also includes a direct comparison between default, pseudo-pooling and pool=TRUE at the end.

> I runned dada2 with 200 samples using pool="pseudo" but the results still had singleton. What's the difference between pool =TURE and pool="pseudo".

I'm not sure why you would not expect singletons when you are using pseudo-pooling. One of the reasons to use pooling methods is to detect ASVs even as singletons.

**Comment by 7kylin** [comment]
> @7kylin This page give a fair amount of detail about pseudo-pooling that I think should answer your questions. It also includes a direct comparison between default, pseudo-pooling and pool=TRUE at the end.
> 
> > I runned dada2 with 200 samples using pool="pseudo" but the results still had singleton. What's the difference between pool =TURE and pool="pseudo".
> 
> I'm not sure why you would not expect singletons when you are using pseudo-pooling. One of the reasons to use pooling methods is to detect ASVs even as singletons.
I got it. I think I had a wrong understanding of  pool = "pseudo". 
Thank you very much！

**Comment by isidoramorel** [comment]
> > Do you think changing to pool="pseudo" would make it much faster? What would you recommend in this case?
> 
> Yes and yes.

@benjjneb worked in aprox. 4 days! (with pool=T took three weeks). thanks!!
