### ISSUE TITLE
loosing reads after merging

### ISSUE THREAD

**Issue by pandan74** [benjjneb/dada2#1257]
Hi,
I saw this problem was reported previously, however I couldn't find any solution. 
I sequenced the V4 fragment (515-806) of 16S. I use idemp for demultiplexing. Unfortunately I'm loosing almost ~50% of reads after merging. 

input filtered Retained % SampleID denoisedF denoisedR merged nonchim TtRetained
CY001 48101    44771   93.07707    CY001     42487     42678  27711   27243   56.63708
CY002 53419    51587   96.57051    CY002     49335     49217  32736   31776   59.48445
CY003 49494    46701   94.35689    CY003     44234     44679  29580   29003   58.59902
CY004 51504    49142   95.41395    CY004     46748     47127  31335   30576   59.36626
CY005 54252    52235   96.28216    CY005     49938     49985  33418   32185   59.32500
CY006 67598    64735   95.76467    CY006     62013     61977  40463   39296   58.13190
CY007 53888    51812   96.14757    CY007     49447     49782  32341   31302   58.08714
CY008 49540    46809   94.48728    CY008     44426     44782  29274   28406   57.33952

because there were some suggestion that it can be problem with the chemistry or heterogeneity spacers... I always run 16S amplicons using v2 300 (2x150) MiSe kit, and don't have any heterogeneity spacers. I prepare library and run sequencing by myself. I have been using this protocol for 3-4 years and never had that problem until now. The run metrics look very good, I don't see nay problem with the sequencing run.

Merging it looks like this:
    abundance forward reverse nmatch nmismatch nindel prefer accept
1         732       1       1     37         0      0      2   TRUE
2         467       2       2     37         0      0      2   TRUE
3         448       3       6     37         0      0      1   TRUE
4         398       5       5     37         0      0      1   TRUE
5         362       4       3     37         0      0      2   TRUE
6         320       9     237     37         0      0      1   TRUE
7         314      14       7     37         0      0      2   TRUE
8         292       7       1     37         0      0      2   TRUE
9         287       8      11     37         0      0      1   TRUE

Do you have any suggestions what is going on and how to fix it? Thank you!

**Comment by benjjneb** [comment]
Everything is the same library prep wise as all the successful runs you've had in the past?

Can. you post your `filterAndTrim` command that you used for this run?

Also an example `plotQualityProfile` from the forward and reverse reads would help too.

**Comment by benjjneb** [comment]
Is there any substantial difference in the underlying environment you are sampling relative to the past environments you have been successfully sampling and processing?

I'd also suggest doing a check for low-complexity infiltration with `plotComplexity` on an example read file.
