### ISSUE TITLE
errors with installing dada2

### ISSUE THREAD

**Issue by JAkorli** [benjjneb/dada2#1259]
Hello,
I am trying to install DADA2 following the instructions available. However, I am running into some errors. I am using R version 4.0.3. 

I run the following after trying out preceding steps

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("ShortRead", version = "3.12") 

I got this back:
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/reprex_1.0.0.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/reprex_1.0.0.tgz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/reprex_1.0.0.tgz': HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘reprex’ failed
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/withr_2.4.1.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/withr_2.4.1.tgz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/withr_2.4.1.tgz': HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘withr’ failed

What could be wrong?

**Comment by benjjneb** [comment]
Did you check if you might be having any network connectivity issues? Those error messages just indicate that the necessary files are failing to be donwloaded because your computer can't connect to the http addresses.

**Comment by JAkorli** [comment]
I had stablr network at the time of installation bit but I will try it again and give you feedback.

Jewelna

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
