### ISSUE TITLE
Error in FUN(X[[i]], ...) :    Non-corresponding derep-class and dada-class objects.

### ISSUE THREAD

**Issue by multisporting2** [benjjneb/dada2#1261]
I'm trying to run some data through Dada2 in Rstudio. I've run into this error: "Error in FUN(X[[i]], ...) : 
  Non-corresponding derep-class and dada-class objects."

Here is my code:
library(dada2); packageVersion("dada2")
setwd("~/Desktop/research/MicroResearch")
path <- setwd("~/Desktop/research/MicroResearch")
list.files(path)
fnFs <- sort(list.files(path, pattern="_R1.fastq", full.names = TRUE))
fnRs <- sort(list.files(path, pattern="_R2.fastq", full.names = TRUE))
sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names
out <- filterAndTrim(fnFs, filtFs, truncLen=c(240),
                     maxN=0, maxEE=c(2), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, multithread=TRUE, matchIDs=TRUE)
head(out)
out2 <- filterAndTrim(fnRs, filtRs, truncLen=c(120),
                     maxN=0, maxEE=c(2), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, multithread=TRUE, matchIDs=TRUE)
head(out2)
errF <- learnErrors(filtFs, multithread=TRUE)
errR <- learnErrors(filtRs, multithread=TRUE)
plotErrors(errF, nominalQ=TRUE)
dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
dadaRs <- dada(filtRs, err=errR, multithread=TRUE)
dadaFs[[1]]
mergers <- mergePairs(dadaFs, filtFs, dadaRs, filtRs, verbose=TRUE)
head(mergers[[1]])

I think the problem is that I am running filter and trim separately for the forward and reverse reads, so it is not matching up later on in "mergers". Please let me know what you think.

**Comment by benjjneb** [comment]
> I think the problem is that I am running filter and trim separately for the forward and reverse reads, so it is not matching up later on in "mergers". Please let me know what you think.

Yes. Don't do this. `filterAndTrim` will happily filter the forward and reverse reads together, which keeps those files consistent with one another. See https://benjjneb.github.io/dada2/tutorial.html#filter-and-trim

**Comment by multisporting2** [comment]
I have tried them together, but because I ran all of my data through a barcode splitter, the number of reads don't match and filter and trim won't take.

**Comment by benjjneb** [comment]
> because I ran all of my data through a barcode splitter, the number of reads don't match

This is the problem then. We don't directly support demultiplexing, typically today that is done by the standard software (e.g. Illumina), but in older sequencing datasets the user needed to do the demultiplexing themselves.

Can you say a bit more about what kind of data you are working with? Also, what demultiplexing (or barcode splitting) software are you using?

**Comment by multisporting2** [comment]
I am working with MiSeq paired end 250 with 8 pair barcodes on the 5' end. I used barcode splitter (Galaxy Version 1.0.1) on usegalaxy.org.

**Comment by benjjneb** [comment]
I can't find the link to that method, can you provide a link to what you are using, not just Galaxy in general?

First, I would not use that method, since it isn't working correctly. Or, perhaps it works with paired end reads, in which case use it in that mode.

**Comment by multisporting2** [comment]
There isn't a link leading directly to the program, but if you go to https://usegalaxy.org/ and the type "barcode splitter" in the tools section on the left side of the page, it should be the fourth option. 

If that is too much trouble then I what method would you suggest I use to demultiplex?

**Comment by benjjneb** [comment]
Please describe the data you are working with in enough detail that we can offer useful advice.

(a tool we have used in the past, for paired-end Illumina data with a barcode read file, is idemp available here: https://github.com/yhwu/idemp)

**Comment by multisporting2** [comment]
Here is a description of the data:

PCR-quality DNA was isolated from 234 samples. Primers F515 (forward: 5′-GTGCCAGCMGCCGCGGTAA-3′) and R806 (5′-GGACTACHVGGGTWTCTAAT-3′) were used to amplify the V4 domain bacterial 16S rRNA genes, along with a unique barcode on each forward primer for each sample [20–22]. PCR, product purifcation, and agarose gel electrophoresis visualization were performed. Combined barcoded libraries were submitted to the University of California Davis Genome Center DNA Technologies Core for 250  bp paired-end sequencing using the Illumina MiSeq platform.


Because other samples were submitted along with this data set for sequencing, a metafile was used for barcode splitting via Galaxy Sample (Barcode Splitter (Galaxy Version 1.0.1). Our barcode splitter file had a format like:

#Sample ID and barcode

Barcode               Sequence

548         GCAACCTA

549         GCATATGC

550         GCCGATTA

Both forward (R1) and reverse (R2) FASTQ.gz files were use to generate demultiplexed fastq R1.fastq (forward) and R2.fastq (reverse files).

**Comment by benjjneb** [comment]
Your reverse reads don't have a barcode on them, so doing this splitting by barcode separately on the forward then reverse reads isn't going to work appropriately. I'd merge these reads together first, then you can probably use your current barcode splitter to get sensible results from the merged library.
