### ISSUE TITLE
Length variation V3V4 16S

### ISSUE THREAD

**Issue by termithorbor** [benjjneb/dada2#1262]
Hi,

it is known that the bacterial 16S V3V4 region has a small length variation with peaks at 440 and 460 bp. Is therefore truncLen still suitable here or should the fungi ITS2 approach from the tutorial better be used.?

And has anyone any experience with plant ITS2 and which approach is better here?

Probably just look at the quality graphs of the reads? 

When you have some thing like this you have sequence variation

![image](https://user-images.githubusercontent.com/66436023/106751698-d77e4100-6629-11eb-8ac0-d28b5619fb6f.png)

And when it is mor like this 
![image](https://user-images.githubusercontent.com/66436023/106751777-f67cd300-6629-11eb-8413-00f6e5b59e8f.png)

Or this 
![image](https://user-images.githubusercontent.com/66436023/106751835-0bf1fd00-662a-11eb-85f0-463d662a5a4b.png)

You do not have a lot variance?

Thanks in advance.

**Comment by benjjneb** [comment]
Yes your interpretation of the cumulative sequence length plots (the red line) is correct.

For V3V4: Yes the whole amplicon has that significant bimodal length variation in it. However, in paired-end sequencing approaches, it is still fine to use `truncLen`, with the important caveat that the truncation lengths should be long enough that the longer amplicons can merge too.

**Comment by termithorbor** [comment]
Okay so when I see a steady decline of the cumulative sequence length like in the first example or when I probably lose to many reads by using truncLen I should use the ITS2 approach otherwise the 16S one, right?

**Comment by benjjneb** [comment]
> Okay so when I see a steady decline of the cumulative sequence length like in the first example or when I probably lose to many reads by using truncLen I should use the ITS2 approach otherwise the 16S one, right?

To be honest, I would probably want to understand why that was happening and then make a decision. If it is from biological length variation in the amplicon (i.e. real signal) then yes probably use the ITS approach with no `truncLen`. If it is from a technical artefact, than perhaps a different choice.

**Comment by termithorbor** [comment]
Yes you are right. So digging the literature :D
