### ISSUE TITLE
Compare the Illumina short-read sequencing and Pacbio's 16S full-length sequencing

### ISSUE THREAD

**Issue by liangxia1995** [benjjneb/dada2#1265]
Dear Benjamin J Callahan,

In my research, I want to compare the results of both Illumina short-read sequencing and Pacbio's 16S full-length sequencing. In order to objectively compare the two sequencing methods, I need to ensure that the two sequencing data have the same analysis process as possible. I use the process given in your article and make appropriate adjustments on this basis. I hope you can make some suggestions for my script to see if there are any adjustments, thank you.

(1) Long read 16S sequencing data processing, taxonomic assignment: 

###removePrimer###
fns2 <- list.files('/Pacbio/rawdata', pattern="fq.gz", full.names=TRUE)
F27 <- "AGRGTTYGATYMTGGCTCAG"
R1492 <- "RGYTACCTTGTTACGACTT"
rc <- dada2:::rc
theme_set(theme_bw())
nops2 <- file.path(path2, "noprimers", basename(fns2))
prim2 <- removePrimers(fns2, nops2, primer.fwd=F27, primer.rev=dada2:::rc(R1492), orient=TRUE)
lens.fn <- lapply(nops2, function(fn) nchar(getSequences(fn)))
lens <- do.call(c, lens.fn)
hist(lens, 100)
filts2 <- file.path(path2, "noprimers", "filtered", basename(fns2))

###filterAndTrim###
track2 <- filterAndTrim(nops2, filts2, maxN = 0, truncQ = 2, rm.phix = FALSE, maxEE = 1, minQ=3, minLen=1400, maxLen=1600)

###learnErrors###

drp2 <- derepFastq(filts2, verbose=TRUE)
err2 <- learnErrors(drp2, errorEstimationFunction=PacBioErrfun, BAND_SIZE=32, multithread=TRUE)
saveRDS(err2, file.path(path.rds, "Fecal_err2.rds"))
plotErrors(err2)
###dada### followed your advice(https://github.com/benjjneb/dada2/issues/991)

dd2 <- dada(drp2, err=err2, BAND_SIZE=32, OMEGA_A=1e-10, DETECT_SINGLETONS=TRUE, multithread=TRUE)
saveRDS(dd2, file.path(path.rds, "Fecal_dd2.rds"))
dd2<-readRDS('/Pacbio/RDS/Fecal_dd2.rds')
st2 <- makeSequenceTable(dd2); dim(st2)
### removeBimeraDenovo### （use consensus）
seqtab.nochim <- removeBimeraDenovo(st2 , method="consensus", multithread=TRUE, verbose=TRUE)
###Taxonom### followed your advice to use silva_nr99_v138_wSpecies_train_set.fa.gz (https://github.com/benjjneb/dada2/issues/1122)
tax2 <- assignTaxonomy(seqtab.nochim, "/Pacbio/database/silva_nr99_v138_wSpecies_train_set.fa.gz",tryRC = TRUE, minBoot = 80, multithread=TRUE) 

(2) Short read 16S sequencing data processing, taxonomic assignment 

###removePrimer & filterAndTrim### In order to consistent with Pacbio processing (maxEE = c(1,1), minQ=3)
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, maxN = 0, truncQ = 2, rm.phix=TRUE, maxEE = c(1,1), minQ=3, trimLeft = c(19,20),compress=TRUE, multithread=TRUE) 
###learnErrors###In order to consistent with Pacbio processing (BAND_SIZE=32) 
errF <- learnErrors(filtFs, BAND_SIZE=32,multithread=TRUE)
errR <- learnErrors(filtRs, BAND_SIZE=32,multithread=TRUE)

derepFs <- derepFastq(filtFs, verbose=TRUE)
derepRs <- derepFastq(filtRs, verbose=TRUE)

names(derepFs) <- sample.names
names(derepRs) <- sample.names

###dada###In order to consistent with Pacbio processing (BAND_SIZE=32,OMEGA_A=1e-10, DETECT_SINGLETONS=TRUE)
dadaFs <- dada(derepFs, err=errF,BAND_SIZE=32,OMEGA_A=1e-10, DETECT_SINGLETONS=TRUE, multithread=TRUE)
dadaRs <- dada(derepRs, err=errR,BAND_SIZE=32,OMEGA_A=1e-10, DETECT_SINGLETONS=TRUE, multithread=TRUE)
###merge###
mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE)
###removeBimeraDenovo###(method="consensus")
seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
write.table(cbind(samplename=rownames(seqtab.nochim),seqtab.nochim),'nochim_seq_profile.table.txt',row.names = F,sep = '\t',quote = F)
###Taxonomy###followed your advice to use assignTaxonomy  and  addSpecies (silva_nr99_v138_train_set.fa.gz and silva_species_assignment_v138.fa.gz  (https://github.com/benjjneb/dada2/issues/1122)
tax2 <- assignTaxonomy(seqtab.nochim, "/Illumina/database/silva_nr99_v138_train_set.fa.gz",tryRC = TRUE, minBoot = 80, multithread=TRUE) 
tax2 <- addSpecies(tax2, "/Illumina/database/silva_species_assignment_v138.fa.gz",tryRC = TRUE)

The main problems are as follows:

（1）In order to objectively compare the two sequencing methods, I need to ensure that the two sequencing data have the same analysis process as possible. So, I modified some parameters, can you help me see if this is feasible.

（2）At the time of species taxonomy, Pacbio uses silva_nr99_v138_wSpecies_train_set.fa.gz, while Illumina data uses silva_nr99_v138_train_set.fa.gz and silva_species_assignment_v138.fa.gz. Will this cause a difference? What is the minboot parameter of addspecies? Does it need to be set to 80, in order to be consistent?
[Fig.1.pdf](https://github.com/benjjneb/dada2/files/5942438/Fig.1.pdf)
[Fig.1.pdf](https://github.com/benjjneb/dada2/files/5942445/Fig.1.pdf)

PS：My Illumina Quality Score is as provided in Appendix 1. Does this mean that the sequencing data is relatively good, and I don’t want to discard and cut?

 Thank you very much! Looking forwards to your reply!

**Comment by benjjneb** [comment]
1) In an admittedly quick skim I don't see any parameters that are obviously amiss.

2) The most appropriate `minBoot` parameter differs by the sequence length. This isn't something that is "solved" by making the parameter the same between methods -- longer reads have more information and should use a higher `minBoot` parameter.

That goes for other parameters too. Making every subsequent processing parameter the same is not always the best way to compare between different technologies.

**Comment by liangxia1995** [comment]
PS：My Illumina Quality Score is as provided in Appendix 1. Does this mean that the sequencing data is relatively good, and I don’t want to discard and cut?

**Comment by liangxia1995** [comment]
[Rplots.pdf](https://github.com/benjjneb/dada2/files/6056293/Rplots.pdf)
My Illumina Quality Score is as provided in Appendix 1. Does this mean that the sequencing data is relatively good, and I don’t want to discard and cut?

**Comment by liangxia1995** [comment]
PS：My Illumina Quality Score is as provided in Appendix 1. Does this mean that the sequencing data is relatively good, and I don’t need
[Rplots.pdf](https://github.com/benjjneb/dada2/files/6056297/Rplots.pdf)
 to discard and cut?

**Comment by benjjneb** [comment]
I would still do expected errors filtering, and be sure that any primers are removed from the reads.

**Comment by liangxia1995** [comment]
After the "plotQualityProfile" operation, we got the quality profiles of the forward reads and quality profile of the reverse reads（
）. The quality values of the sequencing data are all above Q20, and the sequencing quality is very good. I think there is no need to subtract the sequence. The primer I used trimLeft = c(19,20), minus the 19bp primer on the left and the 20bp primer on the right.
