### ISSUE TITLE
merging technical repetitions within one run

### ISSUE THREAD

**Issue by pandan74** [benjjneb/dada2#1268]
I have a run where one samples was sequenced several times (technical repetitions). Each of them has unique sampleID. How to merge/collapse those samples based on e.g. patientID variable.
Thank you. Daniel

**Comment by benjjneb** [comment]
What is your comfort level with R data manipulations?

This is pretty straightforward in R I think, just summing up the rows in the sequence table that are from the same patient. See `rowsum`

**Comment by pandan74** [comment]
I must be tired. It's so obvious. Thank you and I am sorry for taking your time.
