### ISSUE TITLE
Problem with primer identification (char. not in lookup table)

### ISSUE THREAD

**Issue by Roxe4228** [benjjneb/dada2#1269]
Hi, 
I am currently running my ITS sequences in the DADA2 ITS workflow, but I can't run the orientation loop function :

_allOrients <- function(primer) {
    # Create all orientations of the input sequence
    require(Biostrings)
    dna <- DNAString(primer)  # The Biostrings works w/ DNAString objects rather than character vectors
    orients <- c(Forward = dna, Complement = complement(dna), Reverse = reverse(dna), 
        RevComp = reverseComplement(dna))
    return(sapply(orients, toString))  # Convert back to character vector
}
FWD.orients <- allOrients(FWD)
REV.orients <- allOrients(REV)
FWD.orients_

because I get this error : 

**_Error in .Call2("new_XString_from_CHARACTER", class(x0), string, start, : key 73 (char 'I') not in lookup table_**

The primers we use are ITS9F-ITS4R [(5′-GAACGCAGCRAA**II**GYGA-3′) - (5′-TCCTCCGCTTATTGATATGC-3′)] 
ref:(https://academic.oup.com/femsec/article/81/2/438/504793?login=true). 

Can someone help me please ?

**Comment by benjjneb** [comment]
I is not an IUPAC DNA code. What is it supposed to represent here?

**Comment by astanabe** [comment]
"I" means deoxyinosine (See [https://doi.org/10.1111/j.1574-6941.2012.01437.x](url)). Deoxyinosine is used instead of "N". I recommend you to substitute "I" to "N".

**Comment by benjjneb** [comment]
@astanabe Cleaning up issues today, and I've seen that you provided helpful answers on several over the past few months. It is much appreciated!
