### ISSUE TITLE
Problem importing output from dada2 in phyloseq

### ISSUE THREAD

**Issue by VFlad** [benjjneb/dada2#1270]
Dear all,
I'm new to dada2 and R in general, so I followed the dada2 tutorial for 16S and ITS, for the cutadapt workflow.
I finally reached the point to import my data in phyloseq. Unfortunately I have the following issue:

This is what I did:
samdf <- read_excel("path/samples_modified.xlsx", sheet = "samples_modified")
# To get identical sample names
samples.out <- rownames(seqtab.nochim)
rownames(samdf) <- samples.out
# Warning message:
Setting row names on a tibble is deprecated. 
# Creating phyloseq object
ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE), 
               sample_data(samdf), 
               tax_table(taxa))

# This is what I get:
Error in validObject(.Object) : invalid class “phyloseq” object: 
 Component sample names do not match.
 Try sample_names()

I tried to find a solution in all the already existing forum threads but none of the hints worked for me. I'm really lost at this point and would highly appreciate if anyone can help me solving this issue. Also let me know if I would need to post any additional files to better locate the problem.
Best Vroni 

P.S.: I think the problem is the sample data file, because I can merge taxa and seqtab.nochim to a phyloseq object without an error

**Comment by benjjneb** [comment]
The core issue here is a phyloseq issue, but we can try to help you here.

First I would recommend trying to diagnose the issue as recommended by the error message.

What is `sample_names(samdf)`?
What is `sample_names(seqtab.nochim)`?
What is `sample_names(taxa)`?

Are they the same?
I might try looking at the first few entries, because often the issues show up quickly.

**Comment by mariemoinet** [comment]
I might be wrong, but it seems your `samdf` is an object of R class tibble, and not dataframe.
maybe try
```
samdf <- read_excel("path/samples_modified.xlsx", sheet = "samples_modified")
samdf<- data.frame(samdf) # this line added
samples.out <- rownames(seqtab.nochim)
rownames(samdf) <- samples.out
```

It worked for me.
