### ISSUE TITLE
Problem with DADA2 output in phyloseq

### ISSUE THREAD

**Issue by concscid** [benjjneb/dada2#1271]
Dear all,

I'm trying to use DADA2 to treat my 16S sequences (V3V4) and then use the decontam R package on the phyloseq output to remove contaminants. When I try to create a new phyloseq object with the clean otu and taxa tables after using decontam on DADA2 output, I get the following message:

Error in validObject(.Object) : invalid class “otu_table” object:
OTU abundance data must have non-zero dimensions.

I don't understand what is going on, I've always used decontam on RDP outputs converted to phyloseq and never had that issue. I guess there is a problem with the DADA2 RDS object but I can't figure out what it is. When I save the otu_table I get only ASV indexes without abundances, but I'm able to perform downstream analyses (richness and diversity) on the phyloseq object.

If you have any hints I'd really appreciate your help. Here's the code I've used to import DADA2 to phyloseq (I've done all previous steps exactly as described in the tutorial with some modifications in the trimming parameters):

library(phyloseq)
library(Biostrings)
sam.data2 <- read.csv("meta_data2.csv", sep=";", header = TRUE, row.names = 1)
row.names(sam.data2)
Phyloseq_Master2 <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE),  sample_data(sam.data2), tax_table(taxa))
Phyloseq_Master2 <- prune_samples(sample_names(Phyloseq_Master2), Phyloseq_Master2)
dna <- Biostrings::DNAStringSet(taxa_names(Phyloseq_Master2))
names(dna) <- taxa_names(Phyloseq_Master2)
Phyloseq_Master2<- merge_phyloseq(Phyloseq_Master2, dna)
taxa_names(Phyloseq_Master2) <- paste0("ASV", seq(ntaxa(Phyloseq_Master2)))

saveRDS(Phyloseq_Master2, "phyloseq.RDS")

Thank you!

**Comment by benjjneb** [comment]
> OTU abundance data must have non-zero dimensions.

I'm unsure about the exact object you were working with when you got this error. Can you clarify?
Also, you should look at that object, which this error message suggests is empty, and think about how that came to be.
