### ISSUE TITLE
 Allocate GPU memory in conjunction with ram to solve the out-of-memory problem in the "assignTaxonomy" function

### ISSUE THREAD

**Issue by HeloisaAllgayer** [benjjneb/dada2#1272]
I am working with metagenomics the sequencing was done through the Ion torrent.
I am assembling the single file with the fastq per sample of the experiment.
The error I got was in the "assignTaxonomy" function.
For the error I had, it would be necessary 8.8 gb of RAM "Error: it is not possible to allocate vector of size 8.8 Gb".
On the computer I am currently working on I have 8GB of RAM and 4GB of the memory on my video card.
Was there any way compatible with the DADA2 library for me to parallelize the two memories to perform the analysis?

**Comment by benjjneb** [comment]
It's not possible to pool the GPU and CPU RAM like that.
Can you get access to a machine with more RAM?

Alternatively, can you clarify:

> I am assembling the single file with the fastq per sample of the experiment.

Is all the data in a single fastq file? If so, it really needs to be split up into a fastq for each sample prior to starting the DADA2 workflow. I don't have experience with Ion Torrent, but you should be able to ask the sequence provider how to do that in y our case.
