### ISSUE TITLE
strage results for dada2 removePrimers with max.mismatch

### ISSUE THREAD

**Issue by bitcometz** [benjjneb/dada2#1276]
hi,
I change the max.mismatch to get more reads, however, I got less reads:

```
prim2 <- removePrimers(fns2, nops2, primer.fwd=F27, primer.rev=dada2:::rc(R1492), orient=TRUE, max.mismatch=3, allow.indels=TRUE)
```
Results with `max.mismatch=3`:

SampleID | ccs | primers | 
-- | -- | -- | 
sampleA | 6367 | 5559

```
prim2 <- removePrimers(fns2, nops2, primer.fwd=F27, primer.rev=dada2:::rc(R1492), orient=TRUE, max.mismatch=4, allow.indels=TRUE)
```
Results with `max.mismatch=4`:

SampleID | ccs | primers | 
-- | -- | -- | 
sampleA | 6367 | 3634

Could you help me with this problem? 
Thanks!!!

**Comment by benjjneb** [comment]
That's weird. `removePrimers` is using the `Biostrings::vmatchPattern` or `Biostrings::matchPattern` methods to match the primer sequences to each read. I don't know why there would be a decrease with a higher `max.mismatch`.

Also though, the results with `max.mismatch=3` look pretty good, keeping >85% of the reads.

**Comment by bitcometz** [comment]
thanks for your help ！ I use the `max.mismatch=3` to finish the analysis.
