### ISSUE TITLE
error dadaFs <-- dada (filteFs, err=errR)

### ISSUE THREAD

**Issue by marco2985** [benjjneb/dada2#1279]
Hi,
I am following this tutorial and when I reach the sample interference I have problems. It start to give warning errors and I do not know how it should be fixed. I hope you can help me...

#sample interference
dadaRs <- dada(filtRs, err=errR,multithread=FALSE)
dadaFs<-- dada(filtFs, err=err, multithread=FALSE)

I got the same error message for both:
Error in dada(filtFs, err = errF, multithread = FALSE) : 
  Some of the filenames provided do not exist. This may have happened because some samples had zero reads after filtering.

The error plots looks ok . I compared them when the ones in the tutorial and they have the same shape.

Thank you very much in advace,
Maria//

**Comment by benjjneb** [comment]
> Some of the filenames provided do not exist. This may have happened because some samples had zero reads after filtering.

This error message is telling you what is going on. When filtering on a sample removes all the reads, there is no filtered file created. But, that filename is still in your `filtFs` and `filtRs` even though it doesn't exist, which is causing this error.

You can fix this by subsetting your `filtFs` and `filtRs` to those where the files exist.

```
filtFs <- filtFs[file.exists(filtFs)]
filtRs <- filtRs[file.exists(filtRs)]
```

**Comment by marco2985** [comment]
Great!!!
Now it is working :) 😊
Thank you very much,
Maria//
