### ISSUE TITLE
Put taxonomy DBs on Zenodo or Figshare

### ISSUE THREAD

**Issue by cdiener** [benjjneb/dada2#128]
This is a feature request. 

Currently the taxonomy databases uses during `assignTaxonomy` are kept on Dropbox which requires a manual confirmation of the download (can not be downloaded by a script). So you could use something like:

```R
download.file("bla/bla/silva_123.tar.gz")
```

in your R markdown files which would help reproducibility.

Also many journal are skeptical of dropbox links in methods sections and require DOIs for resources. Thus, it might be a good idea to rather have those on http://zenodo.org or http://figshare.com which will allow automated downloads and indexing by DOI.  

P.S.: I also have a version of [HITdb](http://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-015-2265-y) converted to Dada2. I don't know if there is interest in that...

Thanks.

**Comment by benjjneb** [comment]
Seems like a good idea, but I'm going to double-check on the Silva license.

I'd be happy to also share your HITdb training fasta as well. Would need to specify the version in the filename, and I'm assuming the linked paper can be the citation for it?

**Comment by cdiener** [comment]
Looking at their license it looks ok if you include the link they specify:


> (1) SILVA is free for academic/non-commercial users. The SILVA webpage can be browsed and all downloads offered (data sets, subsets thereof, and analysis results) can be used and modified without any restrictions. **Also redistribution of the downloads or derivatives thereof is permitted, but only as long as the SILVA Terms of Use/License Information are made transparent by linking/referring to www.arb-silva.de/silva-license-information.**

Zenodo allows you to specify a license for the data files as well, I don't know about figshare. The HITdb file in dad2 format [can be found here](https://github.com/cdiener/microbiome/blob/master/mbtools/inst/extdata/hitdb.fa.gz). It was converted using the `mothur_to_dada` function [in the same repo](https://github.com/cdiener/microbiome). The source repo of HITdb is https://github.com/microbiome/HITdb.

Cheers and thanks for dada2 :)

**Comment by joey711** [comment]
+1 for extending method option for HITdb...

**Comment by cdiener** [comment]
But maybe wait a bit before including hitdb as I still haven't figured out how to deal with the nearest-neighbor annotations. 

HITdb is based on clustering an in the cases where a cluster maps to several species it reports the nearest neighbor species and the sequence identity. The linked file assigns a species if identity is larger than 90% but that seems to be too lenient...

**Comment by cdiener** [comment]
Okay, should be good now. When there is no agreement on a taxa level in a 97% cluster I now assigned "unclassified" to the specific taxonomy level which should be more in line with what silva and green genes do. 

https://github.com/cdiener/microbiome/blob/master/mbtools/inst/extdata/hitdb_v1.00.fa.gz

**Comment by benjjneb** [comment]
For DADA2 purposes it would be better to leave off the unclassified taxonomic levels (eg. a taxonomy 4 fields long rather than 6). The code understands that as ambiguous assignment of that sequence at those missing levels.

**Comment by cdiener** [comment]
Ah ok. Didn't know about that and assumed it would be the same as the green genes db which still has the empty `...;g_;s_;` classes. Changed it now so that unclassified is just removed from the fields.

Still the same link. The actual script to download and convert is now [found here](https://github.com/cdiener/microbiome/blob/master/scripts/hitdb.R).

**Comment by benjjneb** [comment]
Added [RDP and GreenGenes taxonomic training files](http://dx.doi.org/10.5281/zenodo.158955) and [Silva taxonomic training files](http://dx.doi.org/10.5281/zenodo.158958) (different license) to Zenodo.

**Comment by cdiener** [comment]
Awesome, thanks!

**Comment by benjjneb** [comment]
Reopening to remind me I still need to propagate the new doi-able file locations to the web site.

Also, @cdiener if you make the HitDB file similarly available (eg. FigShare/Zenodo), I will include a mention and link from our updated online documentation.

**Comment by cdiener** [comment]
Here it is: https://zenodo.org/record/159205 .

Thanks!

**Comment by benjjneb** [comment]
Updated documentation in 68df64ce7048154d113a8b166eb6f3c3234ad0c3 and 42f2aa6790bb94b93869f72b3b8ad0cac0451296
