### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by JW-solve** [benjjneb/dada2#1280]
Evening
Never done this before so..

Although I used R before.. Dada2 is over my head.. I run into various errors, and tried various versions of DADA2.. My ultimate goal, alpha and betabiodiversity with heatmaps from my microbiome data

I am adding my script,  would you like some of my samples(FASTQ data) too?   

Please advise, Thanks

My script:
#Only need to run this once
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install(c("knitr", "gridExtra", "BiocStyle", "dada2"))
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("dada2", version = "3.12")
install.package(dada2)
library(dada2); packageVersion("dada2")
library("knitr")
library("gridExtra")
library("BiocStyle")
library("dada2")
library("DECIPHER")
library("phangorn")
library("ggplot2")
library("phyloseq")

packageVersion("dada2")
R.version

set.seed(100)
#Make sure that this folder is in the current working directory
list.files()
#raw_reads should appear as a folder
#else you need to change directories
#setwd("/where/my/raw_reads/folder/is")
miseq_path <- "C://Users//User//Desktop//RSPhd_Jeanette_2020-20200724T185840Z-001//RSPhd_Jeanette_2020//RAW Data//alfa Data//unzipped"
list.files(miseq_path)
fnFs <- sort(list.files(miseq_path, pattern="_R1_001.fastq"))
fnRs <- sort(list.files(miseq_path, pattern="_R2_001.fastq"))

fnFs <- file.path(miseq_path, fnFs)
fnRs <- file.path(miseq_path, fnRs)

filt_path <- file.path(miseq_path, "filtered")
filtFs <- file.path(filtpath, paste0(sample.names, "_F_filt.fastq.gz"))

length(fnFs)
##out <- filterAndTrim(fnFs, filtFs,  fnRs, filtRs,
##                   head(out)
filtFs <- file.path(filt_path, paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(filt_path, paste0(sample.names, "_R_filt.fastq.gz"))
# Filter
##out <- filterAndTrim(fnFs, filtFs,fnRs,filtFs, truncLen = c(240, 160), 
##                  compress=TRUE, multithread=TRUE)
                    
plotQualityProfile(fnFs[1:2])
plotQualityProfile(fnRs[1:2])
out <- filterAndTrim(fnFs, filtFs,  fnRs, filtRs,truncLen=c(60,100),
                     maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, multithread=FALSE) # On Windows set multithread=FALSE
head(out)
                     

                    
write.table(out, "readsinout.txt", quote = FALSE)
exists <- file.exists(filtFs)
derepFs <- derepFastq(filtFs[exists], verbose=TRUE)
derepRs <- derepFastq(filtRs[exists], verbose=TRUE)
names(derepFs) <- sample.names[exists]
names(derepRs) <- sample.names[exists]

errF <- learnErrors(filtFs, multithread=TRUE)
errR <- learnErrors(filtRs, multithread=TRUE)

dadaFs <- dada(derepFs, err=errF, multithread=TRUE)
dadaRs <- dada(derepRs, err=errF, multithread=TRUE)
dadaFs[[1]]

mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs)
mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE)
head(mergers[[1]])
seqtab <- makeSequenceTable(mergers)
dim(seqtab)

seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
dim(seqtab.nochim)
sum(seqtab.nochim)/sum(seqtab)

seqtabAll <- makeSequenceTable(mergers[!grepl("Mock", names(mergers))])
table(nchar(getSequences(seqtabAll)))

seqtabAll <- makeSequenceTable(dadaFs)
seqtabNoC <- removeBimeraDenovo(seqtabAll)

class(dds)
sapply(dds, class)
head(sample.names)
head(names(filtFs))

# Track reads through the pipeline
getN <- function(x) sum(getUniques(x))
track <- cbind(out, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers, getN), rowSums(seqtab.nochim))
# If processing a single sample, remove the sapply calls: e.g. replace sapply(dadaFs, getN) with getN(dadaFs)
colnames(track) <- c("input", "filtered", "denoisedF", "denoisedR", "merged", "nonchim")
rownames(track) <- sample.names
head(track)

#Now you need a reference db
#I use silva
#https://zenodo.org/record/3986799/files/silva_nr99_v138_train_set.fa.gz?download=1
#Move the db to the current directory or set the path

file.exists("C://Users//User//Desktop//RSPhd_Jeanette_2020-20200724T185840Z-001//RSPhd_Jeanette_2020//RAW Data//alfa Data//tax//silva_nr99_v138_train_set.fa")
fastaRef <- "C://Users//User//Desktop//RSPhd_Jeanette_2020-20200724T185840Z-001//RSPhd_Jeanette_2020//RAW Data//alfa Data//tax//silva_nr99_v138_train_set.fa"
set.seed(100) # Initialize random number generator for reproducibility
taxTab <- assignTaxonomy(seqtabNoC, fastaRef, multithread = TRUE)
taxa <- assignTaxonomy(seqtab.nochim, "C://Users//User//Desktop//RSPhd_Jeanette_2020-20200724T185840Z-001//RSPhd_Jeanette_2020//RAW Data//alfa Data//tax//silva_nr99_v138_train_set.fa", multithread=TRUE)
unname(head(taxa))
unname(head(taxTab))

taxa.plus <- addSpecies(taxa, "C://Users//User//Desktop//RSPhd_Jeanette_2020-20200724T185840Z-001//RSPhd_Jeanette_2020//RAW Data//alfa Data//tax//silva_species_assignment_v138.fa", verbose=TRUE)
colnames(taxa.plus) <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus","Species")
unname(taxa.plus)

sequences<-getSequences(seqtab.nochim)
names(sequences)<-sequences

alignment <- AlignSeqs(DNAStringSet(sequences), anchor=NA)
phang.align <- phyDat(as(alignment, "matrix"), type="DNA")
dm <- dist.ml(phang.align)
treeNJ <- NJ(dm) # Note, tip order != sequence order
fit = pml(treeNJ, data=phang.align)
fitGTR <- update(fit, k=4, inv=0.2)
fitGTR <- optim.pml(fitGTR, model="GTR", optInv=TRUE, optGamma=TRUE,
                    rearrangement = "stochastic", control = pml.control(trace = 0))

map <- import_qiime_sample_data("C://Users//User//Desktop//RSPhd_Jeanette_2020-20200724T185840Z-001//RSPhd_Jeanette_2020//RAW Data//alfa Data//Gilbert Genet//OTU Genet.xsls")
ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE), 
            tax_table(taxa.plus),phy_tree(fitGTR$tree))

ps <- merge_phyloseq(ps,map)
ps

set.seed(711)
phy_tree(ps) <- root(phy_tree(ps), sample(taxa_names(ps), 1), resolve.root = TRUE)
is.rooted(phy_tree(ps))

plot_richness(ps, x="day", measures=c("Shannon", "Simpson"), color="when") + theme_bw()
ord.nmds.bray <- ordinate(ps, method="NMDS", distance="bray")

plot_ordination(ps, ord.nmds.bray, color="when", title="Bray NMDS")

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("DECIPHER")

packageVersion("DECIPHER")

seqs <- getSequences(seqtabNoC)
names(seqs) <- seqs

alignment <- AlignSeqs(DNAStringSet(seqs), anchor=NA)

dim(seqtab.nochim)

library(phangorn)

alignment <- AlignSeqs(DNAStringSet(seqs), anchor=NA,verbose=FALSE)
phangAlign <- phyDat(as(alignment, "matrix"), type="DNA")
dm <- dist.ml(phangAlign)
treeNJ <- NJ(dm) # Note, tip order != sequence order
fit = pml(treeNJ, data=phangAlign)
fitGTR <- update(fit, k=4, inv=0.2)
fitGTR <- optim.pml(fitGTR, model="GTR", optInv=TRUE, optGamma=TRUE,
                    rearrangement = "stochastic", control = pml.control(trace = 0))
detach("package:phangorn", unload=TRUE)

#alignment <- read.seqs("alignment.fasta",format="fasta",as.matrix=TRUE)

##addSpecies(taxTab, fastaRef, allowMultiple = TRUE, verbose = FALSE)
taxa <- assignTaxonomy(seqs, "C://Users//User//Desktop//RSPhd_Jeanette_2020-20200724T185840Z-001//RSPhd_Jeanette_2020//RAW Data//alfa Data//tax//silva_nr99_v138_train_set.fa", multithread=FALSE,taxLevels =c("Kingdom","class","Order","Family","Genus","Species"))
##taxa <-assignTaxonomy("C://Users//User//Desktop//RSPhd_Jeanette_2020-20200724T185840Z-001//RSPhd_Jeanette_2020//RAW Data//alfa Data//unzipped//tax//silva_nr99_v138_train_set.fa", tryRC=TRue)
taxa <- addSpecies(taxa, "C://Users//User//Desktop//RSPhd_Jeanette_2020-20200724T185840Z-001//RSPhd_Jeanette_2020//RAW Data//alfa Data//tax//silva_species_assignment_v138.fa")
genus.species <- assignSpecies(seqs, "C://Users//User//Desktop//RSPhd_Jeanette_2020-20200724T185840Z-001//RSPhd_Jeanette_2020//RAW Data//alfa Data//tax//silva_species_assignment_v138.fa")
##taxtab <- assignTaxonomy(dadaFs, "C://Users//User//Desktop//RSPhd_Jeanette_2020-20200724T185840Z-001//RSPhd_Jeanette_2020//RAW Data//alfa Data//tax//silva_nr99_v138_train_set.fa")
##taxtab <- addSpecies(taxtab, "C://Users//User//Desktop//RSPhd_Jeanette_2020-20200724T185840Z-001//RSPhd_Jeanette_2020//RAW Data//alfa Data//tax//silva_nr99_v138_train_set.fa")

unname(head(taxTab))
colnames(taxtab)<- c("Kingdom","Phylum","Class","Order","Family","Genus")
write.table(seqtabNoC, "seqtabNoC.txt", quote = FALSE, sep = "\t", col.names = TRUE, row.names = TRUE)
write.table(taxTab, "taxTab.txt", quote = FALSE, sep = "\t", col.names = TRUE, row.names = TRUE)

#Here is where you would need a metadata file
set.seed(100) # Initialize random number generator for reproducibility
##taxa <- assignTaxonomy(seqtabNoC, "C://Users//User//Desktop//RSPhd_Jeanette_2020-20200724T185840Z-001//RSPhd_Jeanette_2020//RAW Data//alfa Data//unzipped//Animal_Data.csv", multithread=FALSE)

#Not included in the previous script
#It is possible to create fastqc plots in R
#Before filtering, sample 1 and 2
plotQualityProfile(fnFs[1:2])
#After filtering, sample 1 and 2
plotQualityProfile(filtFs[1:2])
#If you closed the R session you can reload the files
taxTab <- read.table("taxTab.txt", row.names = 1, header = TRUE, sep = "\t")
seqtabNoC <- read.table("seqtabNoC.txt", row.names = 1, header = TRUE, sep = "\t")

#If not the variables should still be in your environment
#Read in the metadata.csv
file.exists("C://Users//User//Desktop//RSPhd_Jeanette_2020-20200724T185840Z-001//RSPhd_Jeanette_2020//RAW Data//alfa Data//unzipped//Animal_Data.csv")
metadata <- read.csv("C://Users//User//Desktop//RSPhd_Jeanette_2020-20200724T185840Z-001//RSPhd_Jeanette_2020//RAW Data//alfa Data//unzipped//Animal_Data.csv", row.names = 1, header = TRUE)
#file.exists("C://Users//User//Desktop//RSPhd_Jeanette_2020-20200724T185840Z-001//RSPhd_Jeanette_2020//RAW Data//alfa Data//tax//myfile.txt")

## Tab 
#count.fields("C://Users//User//Desktop//RSPhd_Jeanette_2020-20200724T185840Z-001//RSPhd_Jeanette_2020//RAW Data//alfa Data//unzipped//myfile.dat")
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("microbiome")
library(microbiome)
microbiome::summarize_phyloseq(ps)

##Reg tot hier 2022021
tax_tab[1:5,1:5] # for my table show me [1 to 5 otu ids, 1 to 5 first five ranks]
taxa_names(ps)[1:5] # print first 5 ids
colnames(tax_table(ps))
taxa_names(ps) <- paste0("ASV", seq(ntaxa(ps)))
library(microbiome)
library(knitr)

otu_tab <- microbiome::abundances(ps)
tax_tab <- phyloseq::tax_table(ps)
data("C://Users//User//Desktop//RSPhd_Jeanette_2020-20200724T185840Z-001//RSPhd_Jeanette_2020//RAW Data//alfa Data//unzipped//Animal_Data.csv")

dna <- DNAStringSet(getSequences(seqtab.nochim)) # Create a DNAStringSet from the ASVs
load("C://Users//User//Desktop//RSPhd_Jeanette_2020-20200724T185840Z-001//RSPhd_Jeanette_2020//RAW Data//alfa Data//unzipped//silva_nr99_v138_train_set.fa") # CHANGE TO THE PATH OF YOUR TRAINING SET
load("C://Users//User//Desktop//RSPhd_Jeanette_2020-20200724T185840Z-001//RSPhd_Jeanette_2020/RAW Data//Alfa Data//unzipped//tax//silva_nr99_v138_train_set.RData") # CHANGE TO THE PATH OF YOUR TRAINING SET.RData") # CHANGE TO THE PATH OF YOUR TRAINING SET

ids <- IdTaxa(dna, trainingSet, strand="top", processors=NULL, verbose=FALSE) # use all processors
ranks <- c("domain", "phylum", "class", "order", "family", "genus", "species") # ranks of interest
# Convert the output object of class "Taxa" to a matrix analogous to the output from assignTaxonomy
taxid <- t(sapply(ids, function(x) {
  m <- match(ranks, x$rank)
  taxa <- x$taxon[m]
  taxa[startsWith(taxa, "unclassified_")] <- NA
  taxa
}))
colnames(taxid) <- ranks; rownames(taxid) <- getSequences(seqtab.nochim)

#unqs.mock <- seqtab.nochim["Mock",]
#unqs.mock <- sort(unqs.mock[unqs.mock>0], decreasing=TRUE) # Drop ASVs absent in the Mock
#cat("DADA2 inferred", length(unqs.mock), "sample sequences present in the Mock community.\n")

#mock.ref <- getSequences(file.path(path, "HMP_MOCK.v35.fasta"))
#match.ref <- sum(sapply(names(unqs.mock), function(x) any(grepl(x, mock.ref))))
#cat("Of those,", sum(match.ref), "were exact matches to the expected reference sequences.\n")

library(phyloseq); packageVersion("phyloseq")

library(Biostrings); packageVersion("Biostrings")

library(ggplot2); packageVersion("ggplot2")
theme_set(theme_bw())

samples.out <- rownames(seqtab.nochim)
subject <- sapply(strsplit(samples.out, "D"), `[`, 1)
gender <- substr(subject,1,1)
subject <- substr(subject,2,999)
day <- as.integer(sapply(strsplit(samples.out, "D"), `[`, 2))
samdf <- data.frame(Subject=subject, Gender=gender, Day=day)
samdf$When <- "Early"
samdf$When[samdf$Day>100] <- "Late"
rownames(samdf) <- samples.out

ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE), 
               sample_data(samdf), 
               tax_table(taxa))
ps <- prune_samples(sample_names(ps) != "Mock", ps) # Remove mock sample

## Alpha biodiversity
dna <- Biostrings::DNAStringSet(taxa_names(ps))
names(dna) <- taxa_names(ps)
ps <- merge_phyloseq(ps, dna)
taxa_names(ps) <- paste0("ASV", seq(ntaxa(ps)))
ps

plot_richness(ps, measures=c("Shannon", "Simpson"), color="When")

**Comment by JW-solve** [comment]
Apologies I never gave the errors.

Error 1) Cant find "functions"- I did restart and reinstall R
         2) With assign Taxonomy I only get "kingdom", eventhough I do have a list of organisms for each sample in access.
Thanks

**Comment by benjjneb** [comment]
On (1), where do you get that error? In order to start to troubleshoot, we need to know exactly what command produced the error, and ideally the entire error message copy-pasted.

On (2), I'm guessing what you mean is that you only get assignments to the Kingdom level, and all other levels are NA? One thing to try is to add the `tryRC=TRUE` flag to the `assignTaxonomy` call. If your sequencing data is in the opposite orientation of the reference database, it can lead to assignments only to the kingdom level, but `tryRC=TRUE` will try both orientations and will fix the issue if that is the problem.

If that doesn't fix the issue, if you could paste in the top couple sequences from your sequence table that would help. BLAST-ing them might be informative.

**Comment by JW-solve** [comment]
Evening

Some progress.. thanks
1)Can the RAM/memory of a Computer cause this problem.. it normally started at FilterandTrim .. then I have to switch all off and restart

2) The tryRC=TRUE worked thanks

3) New question: Why would only some of the data pull through to the alpha diversity, only 4 samples out of 11 show?
Thanks

**Comment by benjjneb** [comment]
> 1)Can the RAM/memory of a Computer cause this problem.. it normally started at FilterandTrim .. then I have to switch all off and restart

What problem?

> New question: Why would only some of the data pull through to the alpha diversity, only 4 samples out of 11 show?
Thanks

I don't know and from the information you are providing its pretty impossible to tell. What I'd recommend actually is using the DADA2 tutorial workflow instead of the F1000 workflow, at least until you get all the way through the DADA2 part. That has a lot more explanation and troubleshooting help along the way.

https://benjjneb.github.io/dada2/tutorial.html
