### ISSUE TITLE
Error: vector memory exhausted (limit reached?)

### ISSUE THREAD

**Issue by multisporting2** [benjjneb/dada2#1282]
Here is the code I have been running, the last step is what has caused the error: 

library(dada2); packageVersion("dada2")
setwd("~/Desktop/research/JBS")
path <- setwd("~/Desktop/research/JBS")
list.files(path)
fnFs <- sort(list.files(path, pattern=".fastqsanger.R1", full.names = TRUE))
fnRs <- sort(list.files(path, pattern=".fastqsanger.R2", full.names = TRUE))
sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
plotQualityProfile(fnFs[1:2])
plotQualityProfile(fnRs[1:2])
filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastqsanger.R1"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastqsanger.R2"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
                     maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, multithread=TRUE)
head(out)
errF <- learnErrors(filtFs, multithread=TRUE)
errR <- learnErrors(filtRs, multithread=TRUE)
plotErrors(errF, nominalQ=TRUE)
derepFs <- derepFastq(filtFs, verbose=TRUE)
derepRs <- derepFastq(filtRs, verbose=TRUE)
names(derepFs) <- sample.names
names(derepRs) <- sample.names
dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
dadaRs <- dada(filtRs, err=errR, multithread=TRUE)
dadaFs[[1]]
mergers <- mergePairs(dadaFs, filtFs, dadaRs, filtRs, verbose=TRUE)
head(mergers[[1]])
seqtab <- makeSequenceTable(mergers)
dim(seqtab)
table(nchar(getSequences(seqtab)))
seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
dim(seqtab.nochim)
sum(seqtab.nochim)/sum(seqtab)
getN <- function(x) sum(getUniques(x))
track <- cbind(out, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers, getN), rowSums(seqtab.nochim))
colnames(track) <- c("input", "filtered", "denoisedF", "denoisedR", "merged", "nonchim")
rownames(track) <- sample.names
head(track)
sil_taxa <- assignTaxonomy(seqtab.nochim, "~/Desktop/research/JBS/silva_nr_v132_train_set.fa.gz", multithread=TRUE)
sil_taxa.sp <- addSpecies(sil_taxa, "~/Desktop/research/JBS/silva_species_assignment_v132.fa.gz")

I've been trying the solutions from a website (https://datasquad.at.sites.carleton.edu/data/storage-design/dealing-with-a-vector-memory-exhausted-error-in-r/) but it appears I cant get them to work, or just don't know how to use them properly. Either way, I'm stuck and need someone with more expertise.

**Comment by benjjneb** [comment]
To clarify, the command leading to an error is the `assignTaxonomy` command above? And the error message at least include "Error: vector memory exhausted"?

If so, can you describe the memory resources of the machine you are using, and also the version of dada2 us are using. `assignTaxonomy` does have non-trivial memory requirements with large reference databases like Silva.

**Comment by multisporting2** [comment]
No, sorry, the command got slashed out, it is "addSpecies" and the whole error message is "Error: vector memory exhausted (limit reached?)"

Im using a Mac with 16GB of RAM and Dada2 version 1.18.0.

**Comment by benjjneb** [comment]
Unfortunately this might just be a memory limitation. `addSpecies` is not very memory efficient, especially if you are using the larger databases like Silva.

If that step is necessary, can you get access to a machine with more memory? 64GB should be plenty sufficient.

**Comment by multisporting2** [comment]
The step is necessary, and I might have access to a machine with 64GB. If not, would it possible to use parallel computing with that command?

**Comment by benjjneb** [comment]
> The step is necessary, and I might have access to a machine with 64GB. If not, **would it possible to use parallel computing with that command**?

Unfortunately no, the underlying algorithm that dada2 in `assignSpecies` is using is not multithreaded.

**Comment by multisporting2** [comment]
Alright, thank you for your help.

**Comment by MMSKI** [comment]
Because of this issue at this "add species" step since there are 236 samples (x2 since R1 & R), would it be possible to begin analyzing this data with the samples broken into two categories? What I mean by two categories is that the DNA was isolated and amplified from swabs and from milk. Could there be a swab run and a milk run? Then could they be rejoined after the "add species" step?  Thanks for any info.

**Comment by benjjneb** [comment]
@MMSKI Give it a try and see? I think the query set size actually does impact the memory usage of the underlying algorithm, but I'd have to dig into the docs to remember.

**Comment by elaine-shen** [comment]
Hi all,

Just wanted to say that I am reaching memory limitations as well on my remote server, despite me changing the memory load from anywhere between 100 GB - 500 GB (the error looks the same each time - the job clocks out):

Here is the exact error: 

State: FAILED (exit code 1)
Nodes: 1
Cores per node: 24
CPU Utilized: 17:04:04
CPU Efficiency: 4.17% of 17-01:45:12 core-walltime
Job Wall-clock time: 17:04:23
Memory Utilized: 120.55 GB
Memory Efficiency: 94.18% of 128.00 GB

I am using the Midori COI database to classify ~40k ASV's that were generated from Dada2. Below is my code - I ran DADA2 locally to generate my sequence table and imported it into the server. I also reformatted the Midori database (formatted for the original Wang et al. 2007 RDP classifier, I believe) to fit the DADA2 formatting requirements.

```
ibrary(phylotools)
library(dada2)

# Reformat database
database = read.fasta("MIDORI_UNIQ_GB240_CO1_RDP.fasta")
database1 = gsub(".*\t","", database)
database1 = data.frame(database1, database$seq.text)
colnames(database1) = c('seq.name', 'seq.text')
dat2fasta(database1, 'midori-rdp-dada2.fasta')

database = read.fasta('midori-rdp-dada2.fasta')
seqs = readRDS("combined.rds")
taxa <- assignTaxonomy(seqs, database, multithread= $SLURM_CPUS_ON_NODE, minBoot = 80)
saveRDS(taxa, "combined-taxonomy-rdp-dada2.rds")
```

Thank you in advance for your insights!

**Comment by benjjneb** [comment]
> I also reformatted the Midori database (formatted for the original Wang et al. 2007 RDP classifier, I believe) to fit the DADA2 formatting requirements.

My initial suspicion is that there is a formatting issue because 100GB (let alone 500GB) should be more than enough.

Can you post the first few lines of your reformatted Midori COI database?

Also, if you have any summary stats on the Midori database (number of entries, number of unique taxonomies present) that can help diagnose memory issues as well if it isn't just a formatting issue.

**Comment by elaine-shen** [comment]
Hi @benjjneb, 

Thanks for your initial suspicion - it's correct. I just tried running my reformatting code on just a subset of the database, and it doesn't work - I'll need to work with regex more! Any suggestions for resources would be greatly appreciated.

I am using the Midori Database formatted for RDP which has 1,332,086  entries and these headers:

`MG559732.1.<1.>690	root_1;Eukaryota_2759;Discosea_555280;Flabellinia_1485085;order_Vannellidae_95227;Vannellidae_95227;Clydonella_218657;Clydonella sawyeri_2201168
GATATTGGTACTTTATATTTAATATTCGCAGGGTTTGCTGGTATTATAGGTACAATCTTT
TCTGTTGTGATTCGTATGGAATTAGCTTATCCAGGAGATCAAATTTTACAAGGAGATTAT
CAATTATATAATGTAATTATTACTGCACATGCTTTTATAATGATTTTCTTTATGCTAATG
CCTGCTTTAATTGGTGGTTTAGGTAATTGGTTTGTTCCTTTAATGATTGGTGCTCCAGAT
ATGGCTTTTCCTAGATTAAATAATATAAGTTTTTGGTTATTACCTCCATCTTTTTTTTTA
TTATTGTCTTCTGCTTTAGTAGAAGTAGGTGCAGGTACTGGTTGGACTGTTTATCCACCT
TTAGCAGGTATTCAAAGTCATTCAGGAGGTTCTGTTGACTTAGCTATTTTTAGTTTACAT
TTAGCAGGTGTATCTTCTTTATTAGGTGCTATAAATTTTATTACAACTGTTTTTAATATG
AGAAGTCCTGAAATGGAATGGCATAAAATTTCACTTTTTGTGTGGTCTGTTTTTATAACA`
