### ISSUE TITLE
Constructing phyloseq object from dada2 output with different taxonomic ranks

### ISSUE THREAD

**Issue by simonh-b** [benjjneb/dada2#1284]
Hello,

I have used the PR2 database to assign taxonomy to my sequences using the following code: 
```
taxa_pr2 <- assignTaxonomy(seqtab.nochim, "pr2_version_4.12.0_18S_dada2.fasta.gz", multithread = TRUE, taxLevels 
                               = c("Kingdom","Supergroup","Division","Class","Order","Family","Genus","Species"))
```
This works fine but when I come to convert my output into a phyloseq object, I'm getting an error as the taxonomic ranks requiredfor the PR2 database don't match those required for the phyloseq object.
The code i'm using is:
`ps<- phyloseq(otu_table(seqtab.nochim,taxa_are_rows=FALSE),
              sample_data(samdf),
              tax_table(taxa_pr2))
`
The output error is as follows:

> Error in validObject(.Object) : invalid class “phyloseq” object: 
>  Component taxa/OTU names do not match.
>  Taxa indices are critical to analysis.
>  Try taxa_names()

I have tried using the taxa_names() as instructed by the error but I'm not able to fix it. Any advice on how to convert the reads to the required taxonomic ranks in either dada2 or phyloseq would be appreciated!

Thanks

**Comment by benjjneb** [comment]
I don't think the issue is in the taxonomic ranks, but rather that there is a mismatch between the "taxa" (or ASVs in this case) in your `seqtab.nochim` and in `tax_table` somehow.

What is the output of:

```
taxnm.st <- taxa_names(otu_table(seqtab.nochim,taxa_are_rows=FALSE))
taxnm.tt <- taxa_names(taxa_pr2)
identical(taxnm.st, taxnm.tt)
```

**Comment by simonh-b** [comment]
Hello, 

The output for that code is 
[1] FALSE

I assume this means there is a mismatch between the two? If so, what could be causing this?

Thanks!
