### ISSUE TITLE
verbose = T doesn't work in filterAndTrim (only linux)

### ISSUE THREAD

**Issue by jgrzadziel** [benjjneb/dada2#1286]
As mentioned, 
Using `_verbose = T_` on Windows, I can see in real-time the parameters of filtered sequences.
However, this doesn't work on Linux.  There is only:
`Creating output directory: fastq/filtered` and that's it. 

I miss that functionality because sometimes when I process > 50 samples I would like to stop the process, change the parameters and run it over. When I don't see the parameters in real-time I need to wait until the whole process ends.

DADA2 version: 1.16

Thanks
Jarek

**Comment by benjjneb** [comment]
The verbose output in `filterAndTrim` doesn't work in real time when multithreading is turned on. I suspect what you are seeing is a result of that, as on Windows multithreading in `filterAndTrim` doesn't work, hence it is always running in single-thread mode on Windows.

So one solution would be to just run `filterAndTrim(..., multi=FALSE)` on Linux.

**Comment by jgrzadziel** [comment]
Thank you @benjjneb ;) You are right, single-thread is an answer :)
