### ISSUE TITLE
merging a .xlsx file with DADA2 outputs

### ISSUE THREAD

**Issue by clairewoodall** [benjjneb/dada2#1287]
Hi Ben and others, I've made a ps object, which is v exciting. See below. 

```
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 9285 taxa and 208 samples ]
tax_table()   Taxonomy Table:    [ 9285 taxa by 7 taxonomic ranks ]
refseq()      DNAStringSet:      [ 9285 reference sequences ]

```
I would like to merge my metadata table with this ps object and I'm not sure how to do this. I've read in MD.xlsx metadata file into R. My metadata table is made up of 62 variables. It has a header row including a column that matches the original name of the sequence. The column that matches is called "sample_names". I tried this...

``` 
ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE), 
               sample_names(MD), 
               tax_table(taxa))
```
I have also tried the tidyverse command inner_join using this...

```
metadata_ps <-inner_join(MD, ps by=c(sample_names))

```
Neither of these have merged my metadata. If anyone has any suggestions on how I can merge my metadata into the ps object that would be greatly appreciated. 

Thank you 🙂

**Comment by benjjneb** [comment]
What you want to create is a `data.frame` with the rows named by the same SampleID that was used in your OTU table, and the columns named by the variable name in the metadata.

I don't know how you read in the xslx file, but if it used tidyverse, then it doesn't include rownames, and should be converted to a data.frame first. Another way to do this is to save the data from excel as a .csv file, and then read it in as a data.frame using standard R function `read.csv`.

**Comment by mikemc** [comment]
If you'd like to read the Excel file directly into R and get it in a data.frame for phyloseq, you can try using the readxl and tibble packages as follows:
```r
tbl <- readxl::read_excel("path/to/MD.xlsx")
df <- tibble::column_to_rownames(tbl, sample_names)
```
at this point you should be able to do
```r
ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE), 
               sample_data(df), 
               tax_table(taxa))
```
Note that you need to use `sample_data()` not `sample_names()`
