### ISSUE TITLE
Non-corresponding derep-class and dada-class objects.

### ISSUE THREAD

**Issue by nherna55** [benjjneb/dada2#1288]
Hello There!

I am following your DADA2 pipeline line-by-line and am running into a problem when I try to merge pairs. My code is below- I saw that there were some other people who had this issue as well but they seemed to be tweaking your code just a bit. Mine should be exactly the same as yours- just trying to run through this and get better acquainted with dada2. Please let me know if you see any red flags. Thank you so much!

```
path <- "/Users/patnodelab/Downloads/MiSeq_SOP"
list.files(path)


fnFs <- sort(list.files(path, pattern="_R1_001.fastq", full.names = TRUE))
fnRs <- sort(list.files(path, pattern="_R2_001.fastq", full.names = TRUE))

sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)


plotQualityProfile(fnFs[1:2])
plotQualityProfile(fnRs[1:2])

filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
                     maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, multithread=TRUE) # On Windows set multithread=FALSE
head(out)

errF <- learnErrors(filtFs, multithread=TRUE)
errR <- learnErrors(filtRs, multithread=TRUE)

plotErrors(errF, nominalQ=TRUE)

dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
dadaRs <- dada (filtFs, err=errR, multithread=TRUE)

dadaFs[[1]]


mergers <- mergePairs(dadaFs, filtFs, dadaRs, filtRs, verbose=TRUE)
head(mergers[[1]])
```

>**Error in FUN(X[[i]], ...) : 
> Non-corresponding derep-class and dada-class objects.**

**Comment by benjjneb** [comment]
Are you running this code on the same data used by the tutorial?
Also, what version of the dada2 R package are you using? `packageVersion("dada2")`

**Comment by nherna55** [comment]
Thank you for your response!
Yes I am running it on the same data. All of the files that are included in
my script are below. The dada2 package that I am using is 1.16.0.
 [image: Screen Shot 2021-03-05 at 2.52.31 PM.png]

**Comment by benjjneb** [comment]
Ah, I think it's just a typo bug. Your `dadaRs` line:

```
dadaRs <- dada (filtFs, err=errR, multithread=TRUE)
```

is using `filtFs` instead of `filtRs`.

**Comment by nherna55** [comment]
Oh my gosh- it was! Thank you so much, I really appreciate your help. I
don't know if i ever would have found that.
