### ISSUE TITLE
Access to original read names

### ISSUE THREAD

**Issue by manutamminen** [benjjneb/dada2#1289]
Hello all,
I'm testing DADA2 with my custom single cell genomics workflow (https://www.nature.com/articles/ismej2015124/). Here I would need to map back each OTU to those reads which were merged into it. Essentially this would be something like a list (or a character vector) of fastq ids for each OTU, embedded in the dada objects. Would it be possible to have this implemented at some point?
Thanks!

**Comment by astanabe** [comment]
See #889 and #354 .
