### ISSUE TITLE
ASV clustering and reads low in abundance

### ISSUE THREAD

**Issue by enaym001** [benjjneb/dada2#1290]
Hello, 

Are any reads removed from the dataset at sample inference (construction of ASVs)? If a read is deemed low in abundance is it removed at this step, downstream, or does it remain in the analysis as part of an ASV with a low sequence count?

Thank you!

**Comment by benjjneb** [comment]
ASVs that are supported by less than one error-free read are not retained during denoising.

Typically this results in a small number of reads being removed at the denoising step.
