### ISSUE TITLE
RTools are already installed, but it shows the following error: 

### ISSUE THREAD

**Issue by Ruddhida** [benjjneb/dada2#1292]
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/hp/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)

**Comment by benjjneb** [comment]
You might want to check with Rtools.

But if its just a warning, perhaps you were still able to install the packages you needed.
