### ISSUE TITLE
Taxonomy assignment issue for ITS on dada2

### ISSUE THREAD

**Issue by zacklah** [benjjneb/dada2#1298]
Hello,
I am new in this field and I have some problems in the taxonomy assignment for ITS workflow.
When I ran this part of the script below on RStudio, each time gives me the same error. Could you help me please?
Thank you

# Assign taxonomy
unite.ref <-"/storage/zakaria/exp1/ITS/all_seq/seq/sh_general_release_04.02.2020.tar.gz"
taxa <- assignTaxonomy(seqtab.nochim, unite.ref, multithread=TRUE, tryRC = TRUE)
taxa.print<-taxa  #removing sequence rownames for display only
rownames(taxa.print)<-NULL
head(taxa.print)

What appears after running the second line:

> # Assign taxonomy
> unite.ref <-"/storage/zakaria/exp1/ITS/all_seq/seq/sh_general_release_04.02.2020.tar.gz"
> taxa <- assignTaxonomy(seqtab.nochim, unite.ref, multithread=TRUE, tryRC = TRUE)
Error in .Call2("fasta_index", filexp_list, nrec, skip, seek.first.rec,  :   reading FASTA file /storage/zakaria/exp1/ITS/all_seq/seq/sh_general_release_04.02.2020.tar.gz: 
">" expected at beginning of line 1I tried to look for this error online, but I couldn't find anything about this error.--

**Comment by benjjneb** [comment]
You downloaded the tar.gz archive. You need to decompress it, then use the fasta file you'll see inside the decompressed folder.

**Comment by zacklah** [comment]
It works. Thank you Benjamin for your prompt response.
