### ISSUE TITLE
Issue with Sample inference and merger of paired-end reads step in Big Data Pipeline

### ISSUE THREAD

**Issue by Brianna-Walker** [benjjneb/dada2#1299]
I'm having difficulty processing some 16s data.

I have proceeded through the pipeline to the "Sample inference and merger of paired-end reads" step with no issues.

The following command seems to run without issue:
mergers <- vector("list", length(sample.names))
names(mergers) <- sample.names
for(sam in sample.names) {
  cat("Processing:", sam, "\n")
    derepF <- derepFastq(filtFs[[sam]])
    ddF <- dada(derepF, err=errF, multithread=FALSE)
    derepR <- derepFastq(filtRs[[sam]])
    ddR <- dada(derepR, err=errR, multithread=FALSE)
    merger <- mergePairs(ddF, derepF, ddR, derepR)
    mergers[[sam]] <- merger
}
rm(derepF); rm(derepR)

This is the output, it looks ok to me.

Processing: 2F1 
Sample 1 - 37560 reads in 18945 unique sequences.
Sample 1 - 37560 reads in 12720 unique sequences.
Processing: 2F10 
Sample 1 - 37241 reads in 18471 unique sequences.
Sample 1 - 37241 reads in 12433 unique sequences.
Processing: 2F11 
Sample 1 - 55831 reads in 25751 unique sequences.
Sample 1 - 55831 reads in 17296 unique sequences.
Processing: 2F12 
Sample 1 - 42912 reads in 20545 unique sequences.
Sample 1 - 42912 reads in 13825 unique sequences.
Processing: 2F13 
Sample 1 - 39996 reads in 19313 unique sequences.
Sample 1 - 39996 reads in 13284 unique sequences.
Processing: 2F14 
Sample 1 - 49174 reads in 23187 unique sequences.
Sample 1 - 49174 reads in 16533 unique sequences.
Processing: 2F15 
Sample 1 - 54793 reads in 25379 unique sequences.
Sample 1 - 54793 reads in 17641 unique sequences.
Processing: 2F16 
Sample 1 - 36789 reads in 18550 unique sequences.
Sample 1 - 36789 reads in 12877 unique sequences.
Processing: 2F17 
Sample 1 - 40181 reads in 19999 unique sequences.
Sample 1 - 40181 reads in 13996 unique sequences.
Processing: 2F18 
Sample 1 - 48010 reads in 23215 unique sequences.
Sample 1 - 48010 reads in 16115 unique sequences.
Processing: 2F19 
Sample 1 - 57400 reads in 25854 unique sequences.
Sample 1 - 57400 reads in 17264 unique sequences.
Processing: 2F2 
Sample 1 - 37495 reads in 19011 unique sequences.
Sample 1 - 37495 reads in 12742 unique sequences.
Processing: 2F20 
Sample 1 - 42560 reads in 19666 unique sequences.
Sample 1 - 42560 reads in 13487 unique sequences.
Processing: 2F21 
Sample 1 - 39820 reads in 20036 unique sequences.
Sample 1 - 39820 reads in 13561 unique sequences.
Processing: 2F22 
Sample 1 - 46286 reads in 22088 unique sequences.
Sample 1 - 46286 reads in 15201 unique sequences.
Processing: 2F3 
Sample 1 - 36998 reads in 18763 unique sequences.
Sample 1 - 36998 reads in 12854 unique sequences.
Processing: 2F4 
Sample 1 - 49616 reads in 23545 unique sequences.
Sample 1 - 49616 reads in 15863 unique sequences.
Processing: 2F5 
Sample 1 - 42790 reads in 21153 unique sequences.
Sample 1 - 42790 reads in 14240 unique sequences.
Processing: 2F6 
Sample 1 - 49141 reads in 24002 unique sequences.
Sample 1 - 49141 reads in 15622 unique sequences.
Processing: 2F7 
Sample 1 - 48093 reads in 23082 unique sequences.
Sample 1 - 48093 reads in 15838 unique sequences.
Processing: 2F8 
Sample 1 - 47138 reads in 22247 unique sequences.
Sample 1 - 47138 reads in 14566 unique sequences.
Processing: 2F9 
Sample 1 - 39419 reads in 19418 unique sequences.
Sample 1 - 39419 reads in 13033 unique sequences.

But when I try to produce the seqtab file (attached as xlsx file [seqtab.xlsx (https://github.com/benjjneb/dada2/files/6127633/seqtab.xlsx)
), it contains very little data.

Could I have some assistance in troubleshooting?

Kind regards
Brianna

**Comment by benjjneb** [comment]
Hi Brianna,
I recommend using [the DADA2 Tutorial workflow](https://benjjneb.github.io/dada2/tutorial.html) instead, as it includes more trouble-shooting steps. In particular the tracking of read counts at each stage of processing is a very useful diagnostic: https://benjjneb.github.io/dada2/tutorial.html#track-reads-through-the-pipeline

For troubleshooting purposes, you can just run a subset of your samples (e.g. 10 of them) to make things go faster.

**Comment by Brianna-Walker** [comment]
I did as you suggested and found that my reads weren't merging. I think due to poor quality reverse reads? I managed to run just the forward reads and things seem to be working ok.

Thanks for you help,
Brianna
