### ISSUE TITLE
Job killed when pooling for sample inference

### ISSUE THREAD

**Issue by yijuanhu** [benjjneb/dada2#130]
Hi,

I have 700+ samples. I first used 20 samples for error rate estimation:
errorF_sub <- dada(derepFs[1:20], err=NULL, selfConsist = TRUE) 

Then, I pooled all 700+ samples for sample inference:
dadaFs <- dada(derepFs, err=errorF_sub[[1]]$err_out, selfConsist = FALSE, pool=TRUE) 

My job always got killed during the step of sample inference and gave me this message:
/usr/lib64/R/bin/BATCH: line 60: 41923 Killed           
${R_HOME}/bin/R -f ${in} ${opts} ${R_BATCH_OPTIONS} > ${out} 2>&1

Is this a memory issue? How many samples can typically be pooled for sample inference? 

Thank you very much in advance!
Yijuan

**Comment by benjjneb** [comment]
Hi Yijuan,
This may be a memory issue, how much memory is available to you?
Pooled inference is not that memory intensive, so that should be addressable. It can be time-limited though.

What sequencing tech? And how many unique sequences are in your set of 700 pooled samples? That's the key number. If the number of unique sequences after filtering gets above a million, running time becomes quite long even on a server (>2 days on one of our 16-core 32GB compute nodes).

Rule of thumb is that Miseq-scale data can be pooled and processed, but Hiseq-scale data generally cannot be all pooled together (for running time reasons).

**Comment by yijuanhu** [comment]
Hi Ben,

Thanks for your quick response. I was running it on a cluster, with about 6.4GB rams per core. 

It is MiSeq. There are 15,000 - 20,000 unique sequences 'per sample' after filtering. 

I am also running a subset of 50 samples this time, with a total of 607,564 unique sequences. It has taken 24 hours but still hasn't finished. Is this normal?

Yijuan

**Comment by yijuanhu** [comment]
Hi Ben,

Just to give you an update. The run with 50 samples now finished with 24.5 hours. I used 20 samples for error rate estimation and then pooled 50 samples for sample inference.

Yijuan

**Comment by benjjneb** [comment]
Hi Yijuan,
Was just looking up some of our time benchmarks on pooled datasets, and that sounds in line with what we were seeing on a comparable dataset: 16 hours for ~500k 250nt unique sequences on our 16 core/32 GB compute node.

That strongly suggests that you won't be able to pool all 700 samples for sample inference, as the scaling is nearly quadratic with sequencing depth when pooling (so 50 -> 700 samples ~ 1day -> 100days). More stringent filtering/trimming (< uniques) and making sure things like phiX are removed from the raw reads (< uniques) can help somewhat, but it probably wouldn't be easy.

You shouldn't have any trouble running in the normal independent-sample-inference mode though.

**Comment by benjjneb** [comment]
Just looked at your initial code: Are using the Bioconductor release version (1.0.x)? Or the current devel branch (from github)?

If using 1.0.x, you should upgrade to the 1.1 branch with multithreading. Then activate multithreading (its off by default) when making the time-limiting dada call ```dada(..., multithread=TRUE)```. This can speed things up as much as 10x depending on the hardware you have available.

**Comment by yijuanhu** [comment]
Ben,

Thank you very much for all your suggestions and your timely responses! I am using the version 1.1.5. I will try the multithreading option.

Yijuan

**Comment by yijuanhu** [comment]
Hi Ben,

If pooling all 700 samples is not possible, would you suggest the independent-sample-inference mode or a 'batch' model which pools a subset (e.g., 50 samples) in each batch?

Yijuan

**Comment by benjjneb** [comment]
In general, per-sample inference works very well and is what I would suggest.

Pooling in batches can be useful in special circumstances, where it really makes sense to group into batches (eg. samples from different environments or subjects) and where detecting very rare variants is important.
