### ISSUE TITLE
Removing chimeras from Sequel full-length 16S rRNA data using DADA2

### ISSUE THREAD

**Issue by yuharasatoshi** [benjjneb/dada2#1300]
We obtained full-length 16S rRNA sequencing data of ZymoBIOMICS Microbial Community Standards using Sequel according to the manufacturer's instructions. 
https://www.pacb.com/wp-content/uploads/Procedure-Checklist-%E2%80%93-Amplification-of-Full-Length-16S-Gene-with-Barcoded-Primers-for-Multiplexed-SMRTbell-Library-Preparation-and-Sequencing.pdf

And we are now analyzing the data according to your paper.
https://benjjneb.github.io/LRASManuscript/LRASms_Zymo.html

However, the majority of the data was lost after removing chimeras.

ccs primers filtered denoised
[1,] 222830  197310   189307   185756

bim <- isBimeraDenovo(dd, minFoldParentOverAbundance=3.5) 
table(bim)

bim
FALSE  TRUE 
   34   162

Any advice or comments would be appreciated.

**Comment by benjjneb** [comment]
What fraction of the reads were lost?

```
sum(dd$denoised[bim])/sum(dd$denoised)
```

**Comment by yuharasatoshi** [comment]
Thank you for your reply.

>sum(dd$denoised[bim])/sum(dd$denoised)
0.03910054

**Comment by benjjneb** [comment]
4% of reads being identified as chimeras is totally normal. Not a cause for concern.

**Comment by yuharasatoshi** [comment]
Thank you for your comment. 

According to the analysis log,  196 variants were obtained after denoizing.
> 189,307 reads in 38,141 unique seqs. 196 seq variants were inferred from 38,141 input unique seqs.

165 out of 196 variants were removed after removeBimeraDenovo.
Is it also normal?

**Comment by benjjneb** [comment]
Many ASVs but few reads being chimeric is totally normal, especially in low diversity samples like a mock community.

Lots of very low abundance chimeras can be produced by PCR. That's what you are seeing.
