### ISSUE TITLE
Issues with chimera removal

### ISSUE THREAD

**Issue by robdalen** [benjjneb/dada2#1302]
I am getting stuck at the chimera removal step when analyzing my Illumina 16S data, sequenced in a asymmetric 100x400 configuration (as detailed [here](https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-020-00841-w)), using dada2 1.18.
I have followed the dada2 tutorial without any major alterations, except that I merge my reads by concatenation as they are non-overlapping. This all went fine, until I get to the chimera removal step. Although I run the function as verbose=TRUE, nothing seems to be coming out. Yet, I can see that my computer is doing _something_, as the CPU utilization shoots up to 100%. I've let it run for several hours, but without anything coming our before interrupting R.

I have also ran the analysis using the dada2 tutorial data or with own data from a parallel sequencing run of the same amplicons (this time in 2x250 configuration, but again without overlap and therefore also requiring concatenation to merge reads). In both of these instances, the chimera removal progressed without any issues.

What might be the issue causing dada2 to get stuck here?

> dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
Sample 1 - 109182 reads in 13655 unique sequences.
Sample 2 - 113939 reads in 12568 unique sequences.
Sample 3 - 125132 reads in 11328 unique sequences.
Sample 4 - 91319 reads in 9169 unique sequences.
Sample 5 - 101805 reads in 11009 unique sequences.
Sample 6 - 319 reads in 298 unique sequences.
Sample 7 - 58504 reads in 5652 unique sequences.

> dadaRs <- dada(filtRs, err=errR, multithread=TRUE)
Sample 1 - 109182 reads in 40022 unique sequences.
Sample 2 - 113939 reads in 34463 unique sequences.
Sample 3 - 125132 reads in 36703 unique sequences.
Sample 4 - 91319 reads in 28212 unique sequences.
Sample 5 - 101805 reads in 34897 unique sequences.
Sample 6 - 319 reads in 318 unique sequences.
Sample 7 - 58504 reads in 27389 unique sequences.

> mergers <- mergePairs(dadaFs, filtFs, dadaRs, filtRs, verbose=TRUE, justConcatenate = TRUE)
103986 paired-reads (in 41515 unique pairings) successfully merged out of 103986 (in 41515 pairings) input.
108175 paired-reads (in 44435 unique pairings) successfully merged out of 108175 (in 44435 pairings) input.
120528 paired-reads (in 67649 unique pairings) successfully merged out of 120528 (in 67649 pairings) input.
87195 paired-reads (in 41443 unique pairings) successfully merged out of 87195 (in 41443 pairings) input.
96211 paired-reads (in 44834 unique pairings) successfully merged out of 96211 (in 44834 pairings) input.
31 paired-reads (in 2 unique pairings) successfully merged out of 31 (in 2 pairings) input.
55796 paired-reads (in 24992 unique pairings) successfully merged out of 55796 (in 24992 pairings) input.

> seqtab <- makeSequenceTable(mergers)
> dim(seqtab)
[1]      7 230407

> seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)

**Comment by benjjneb** [comment]
What is the problem?

**Comment by robdalen** [comment]
As I mentioned above, there's literally nothing coming out of removeBimeraDenovo.

**Comment by benjjneb** [comment]
Ah I see. 

> Is this normal and perhaps a lack of processing power?

In certain circumstances, chimera removal can take significantly longer than the denoising steps. You may be in one of those circumstances. In particular, because you are concatenating rather than merging overlapping reads, there could be a very high fraction of chimeric sequences, and a larger number of potentially artefactual "parents' to scan through.

A total ASV count of 230k shouldn't be a major compute challenge, but could take some time especially depending on your compute resources. One thing to try is the `minParentAbundance` at a higher setting than the default of 2. This will cause only potential chimeric "parents" with an abundance over the threshold to be considered when considering whether the query ASV is a chimera. If there is a very high fraction of very low abundance ASVs in your table, this can lead to a substantial speedup.

In general we recommend using overlapping amplicons though.

**Comment by robdalen** [comment]
That makes a lot of sense, thanks for your input Benjamin!

I quickly checked whether altering minParentAbundance would have an effect by setting it to the way too high number of 100. The function now processes within a minute, but of course only identifies a very tiny proportion of chimera sequences (500 out of 230k). I'll have to play around with this to find an optimum that processes a bit faster than the default, yet identifies a still reasonable proportion of the chimeric sequences. It definitely provides some direction on how to proceed.

Yes, I understand using overlapping reads would be preferable. We're looking into the option!
