### ISSUE TITLE
Suggestions in building a taxonomic database

### ISSUE THREAD

**Issue by lcamVz** [benjjneb/dada2#1303]
I am looking for taxonomic databases specific to amoA archaea and bacteria. but can't find one regarding the dada2 format. Have you in your experience came by to something similar and/or how would you go about this?

**Comment by benjjneb** [comment]
I don't have amoA specific advice to offer as I haven't done any work using that marker gene.

The fasta format to create a dada2 `assignTaxonomy` reference file is described here: https://benjjneb.github.io/dada2/training.html

**Comment by lcamVz** [comment]
Awesome! 

Thank you. 

I think I got the idea to make it work in combination with this. [https://www.biostars.org/p/317073/
](url)

Let you know how it goes.

**Comment by lcamVz** [comment]
Does the taxonomic database built need to be aligned for dada2 or the main thing to consider is the header format?

**Comment by lcamVz** [comment]
I closed it by mistake. 

had help from sherill-mix to get the ranks accordingly using taxonomizr in R

**Comment by benjjneb** [comment]
> Does the taxonomic database built need to be aligned for dada2 or the main thing to consider is the header format?

Alignment is totally unnecessary, and thrown away by the RDP classifier method implemented by `assignTaxonomy`.

Good high quality sequences for you taxa of interest are the best thing.
