### ISSUE TITLE
A DADA2 workflow for Big Data: Error in mergeSequenceTables(st1, st2) : 

### ISSUE THREAD

**Issue by seqlt** [benjjneb/dada2#1304]
I tried to merge data from my two run together (following this link: https://benjjneb.github.io/dada2/bigdata.html) but got an error...

Code that I ran: 

library(dada2); packageVersion("dada2")
# Merge multiple runs (if necessary)
st1 <- readRDS("path/to/run1/output/seqtab.rds")
st2 <- readRDS("path/to/run2/output/seqtab.rds")
st.all <- mergeSequenceTables(st1, st2)

Error:

Error in mergeSequenceTables(st1, st2) : 
  Duplicated sample names detected in the sequence table row names: NM-SOS-P1-G-12-control-positive, NM-SOS-P1-H-12-control-negative

How to fix the error rather than go back to delete the duplicated samples or change sample names?
Can I tell them that the duplicated samples are different?

Thank you

**Comment by benjjneb** [comment]
There is an option in `mergeSequenceTables` that modifies the behavior when duplicated sample names are detected:

```
repeats | (Optional). Default "error". Specifies how merging should proceed in the presence of repeated sample names. Valid values: "error", "sum". If "sum", then samples with the same name are summed together in the merged table.
```

So the "sum" option will get rid of the error and sum those samples together in the merged table. However, if I'm reading this right these are your control samples from each run. So your best option might be to rename the control samples with a run-specific suffix, e.g. "NM-SOS-P1-G-12-control-positive.Run1", since you might want to keep them separate for any downstream QC. You can do that by just renaming those rows in the sequence table. e.g. something like:

```
ctls <- c("NM-SOS-P1-G-12-control-positive", "NM-SOS-P1-H-12-control-negative")
is.ctl.1 <- rownames(st1) %in% ctls
rownames(st1)[is.ctl.1] <- paste0(rownames(st1[is.ctl.1]), ".Run1")
```

**Comment by seqlt** [comment]
Thank you for your reply.
I'm sorry in advance if I'm being silly with this...
I tried to rename the duplicated samples following your codes:

ctls <- c("NM-SOS-P1-G-12-control-positive", "NM-SOS-P1-H-12-control-negative")
is.ctl.1 <- rownames(st1) %in% ctls
rownames(st1)[is.ctl.1] <- paste0(rownames(st1[is.ctl.1]), ".Run1")

and I got ".Run1" and ".Run1.1" to replace "NM-SOS-P1-G-12-control-positive", "NM-SOS-P1-H-12-control-negative", respectively.  And all of my samples name were change to . form e.g.  "NM-SOS-P1-A-01-SP-TD-010" to  "NM.SOS.P1.A.01.SP.TD.010"

When I ran:
st.all <- mergeSequenceTables(st1, st2)

And the result is: 
Error in mergeSequenceTables(st1, st2) : 
  Duplicated sample names detected in the sequence table row names: .Run1
In addition: Warning message:
In FUN(X[[i]], ...) : Duplicated row (sample) names.

**Comment by benjjneb** [comment]
I might have messed up my code. Here's something a little more robust:

```
rn.new.1 <- rownames(st1)
rn.new.1 <- gsub("control-positive$", "control-positive.Run1", rn.new.1)
rn.new.1 <- gsub("control-negative$", "control-negative.Run1", rn.new.1)
rownames(st1) <- rn.new.1
### And again as above for st2
```
