### ISSUE TITLE
assignTaxonomy with not exact matching

### ISSUE THREAD

**Issue by nvasanthika** [benjjneb/dada2#1308]
Hi,

Assigntaxonomy function from dada2 working with exact match only. Is it possible to make it work with mismatch of specific number allowed. For example, Assigntaxonomy if there are 5 mismatches. 

Thanks in advance
Mounika

**Comment by benjjneb** [comment]
`assignTaxonomy` does not require exact matching. `assignSpecies` requires exact matching (this is a different algorithm).

Can you clarify what you mean? And perhaps exactly what command you are running?
