### ISSUE TITLE
Low complexity sequences causing issues with learnErrors()

### ISSUE THREAD

**Issue by develynw** [benjjneb/dada2#1309]
Hi there,

My data are 16s amplicon sequences from a NovaSeq. I am having issues with the learnErrors() step and decided to troubleshoot on a reverse read file:
learnErrors(MV04_T01_R2, verbose = 2).

I received the following error message: 
Error rates could not be estimated (this is usually because of very few reads).
Error in err[c(1, 6, 11, 16), ] <- 1 : incorrect number of subscripts on matrix

I checked and plotted the sequence complexity, determining that the distribution appears to be bimodal:
cmp_MV04_T01_R2 <- seqComplexity(getSequences(MV04_T01_R2))
plot(cmp_MV04_T01_R2)
![image](https://user-images.githubusercontent.com/75599317/113197388-504fe280-9200-11eb-9253-03f276d5aaff.png)

As a side note, here is what the forward complexities look like:
![image](https://user-images.githubusercontent.com/75599317/113197511-79707300-9200-11eb-81fd-5ac883849049.png)

I believe I need to remove low complexity sequences for all of my samples, but I want to ensure that I am identifying the correct problem here.
Has anyone else come across this issue? If so, how did you address it? 
Many thanks for your time!

**Comment by benjjneb** [comment]
I have not seen exactly this issue (i.e. NovaSeq data with lots of low complexity reads failing `learnErrors`).

That low complexity fraction is striking int he reverse reads, so I definitely would start there. Note, in `filterAndTrim` there is a `rm.lowcomplex` option that will easily remove those reads for you.

So, I would try that and see if that resolves the problem as the first step.

**Comment by develynw** [comment]
Thanks @benjjneb 
I will look into the rm.lowcomplex option
