### ISSUE TITLE
matchIDs=True or FALSE(default) have completely different results

### ISSUE THREAD

**Issue by jianshu93** [benjjneb/dada2#1311]
Hello,
my primer removal reads file R1 and R2 was run using dada2 for both matchIDs=True  and default mode. I got no error message for both but the filtered reads is 2 times bigger in default than in TRUE mode, which is really strange (cutadapt was used to remove primers).but the final results are exactly the same. What happened to my R1 and R2 file then. 

Thanks,

Jianshu

**Comment by benjjneb** [comment]
Not sure. Are you sure that the `compress` flag was set equally in both commands?
