### ISSUE TITLE
dada2 (Silva_metaxa2 training set) -Interesting expanded training set

### ISSUE THREAD

**Issue by anrongloh93** [benjjneb/dada2#1312]
Hi Benjamin,

 

Greetings from Singapore! I am currently working on a coral microbiome study on investigating ASVs at different sites and timepoint.

First of all thank you for designing such an excellent tool dada2 and the associated tutorials which proved very helpful, especially for someone new to using R for microbiome analysis.

 

Recently, there was a published study on improving the annotation of unknown ASVs with an expanded Silva_metaxa2 database that has more mitochondrial DNA sequences inside of it to replace the current Silva_r138 training set.

 

However, the authors made this silva_metaxa2_reference_taxonomy as a qiime2 artifact (qza). The paper can be found here https://www.biorxiv.org/content/10.1101/2021.02.23.431501v1

With their github codes and files stored at https://zenodo.org/record/4551201#.YGRXw68zY2w

https://github.com/zaneveld/GCMP_Global_Disease/tree/master/analysis/organelle_removal

My question would be how can this be converted into a fastq or .Rdata file so that it can be used as part of the dada2 pipeline that you created at the following step below:

![image](https://user-images.githubusercontent.com/81685777/113564354-d5415e80-963b-11eb-9fb5-601b16f8647a.png)

I believe that the Silva_metaxa2 file that the team managed to combine is in a qza file that I have emailed you personally, as I am unable to attach the specific file here.

Do let me know if you require more information too!

Thank you very much in advance for all your help Benjamin! 😁

Best Regards
Aaron

**Comment by benjjneb** [comment]
To clarify, you specifically want to use IdTaxa as your taxonomic assignment method?

If so, that is implemented in the DECIPHER package not dada2. There are instructions on creating their reference database files available here: https://bioconductor.org/packages/release/bioc/vignettes/DECIPHER/inst/doc/ClassifySequences.pdf

We can ping the DECIPHER developer on here, but specific questions on DECIPHER::IdTaxa will need their input and perhaps should use their support system.

**Comment by anrongloh93** [comment]
Hi Benjamin,

Thank you for your response! Yes I am looking to use the IdTaxa as the taxonomic assignment method. 

We could potentially use the assigntaxonomy step too, if we could somehow convert this silva_metaxa2 training set qza file into a fastq.gz file 
![image](https://user-images.githubusercontent.com/81685777/113674079-5a844c00-96ec-11eb-94a6-f34506e4cb36.png)

May I know how to keep you in the loop if I contact the developer of DECIPHER? Or would you prefer to contact them directly haha

Thanks Benjamin!

**Comment by anrongloh93** [comment]
Hi Benjamin, 
I have posted a question here on Bioconductor for us to be in the loop of any updates to the response
https://support.bioconductor.org/p/9136076/

**Comment by benjjneb** [comment]
You can just let us know on here. It is also possible to tag the creator on Github (although he prefers to do support via BioC I believe).

**Comment by benjjneb** [comment]
Also for `assignTaxonomy`, the format of our training file is quite simple: https://benjjneb.github.io/dada2/training.html

So, if a fasta of the updated Silva training file you are talking about above can be extracted from the QZA (which is just a zip file, you can unzip it and inspect its contents), then it should be pretty straigthforward to convert it to `assignTaxonomy` format.

**Comment by anrongloh93** [comment]
Hi Benjamin,

I am keen on trying the assignTaxonomy function instead. We have manage to convert the QZA file into a TSV file and currently a CSV file but we still have difficulty importing it to be used as part of the pipeline as it is not a fasta.gz file. Would it be possible if I email you the csv/tsv file instead? I can't seem to attach the csv file here.


Thanks Benjamin!

**Comment by benjjneb** [comment]
You should be able to post the first few lines of a csv file, for example. That will help show what kind of reformatting might need to be done to put it into `assignTaxonomy` format.
