### ISSUE TITLE
Dada2 maximum number of threads used limited to 24?

### ISSUE THREAD

**Issue by jianshu93** [benjjneb/dada2#1313]
Dear Benjamin,

I am try to use dada2 (version 1.18.0) for a very large dataset but I noticed that the threads used for error learning and dada() function are very small (8 at the beginning, 24 after setting to 128 via setThreadOptions()). Is that because those 2 functions does not scale well with increased threads? How I can I change it to the maximum number of threads on my machine (128)

Thank you,

Best,

Jianshu

**Comment by benjjneb** [comment]
Can you clarify exactly what commands you are calling where you see this behavior? I.e., the full command as it is being called in your R script.

**Comment by jianshu93** [comment]
thread <- 128

set.seed(100)
# Filtered forward reads
errF <- learnErrors(filtFs, nread=1e6, multithread=threads,randomize=TRUE)
# Filtered reverse reads
errR <- learnErrors(filtRs, nread=1e6, multithread=threads,randomize=TRUE)

......

mergers <- vector("list", length(sample.names))
  names(mergers) <- sample.names
  names(filtFs) <- sample.names
  names(filtRs) <- sample.names
  for(sam in sample.names) {
    cat("Processing:", sam, "\n")
      derepF <- derepFastq(filtFs[[sam]])
      ddF <- dada(derepF, err=errF, multithread=threads)
      derepR <- derepFastq(filtRs[[sam]])
      ddR <- dada(derepR, err=errR, multithread=threads)
      merger <- mergePairs(ddF, derepF, ddR, derepR)
      mergers[[sam]] <- merger
  }


Thanks


jianshu

**Comment by benjjneb** [comment]
My first guess is that the compute environment you are using only has 32 threads available in a single CPU. Multithreading implemented in DADA2 is via the RcppParallel package, and as I understand it will only take advantage of the threads available within a CPU, and cannot utilize multiple CPUs.

Is that possible in your compute environment? That is, might it be a multi-CPU system that in total adds up to 128 threads, but on a single CPU only has 32.

**Comment by jianshu93** [comment]
yes correct afer confirmation. Any possibility to use all？

**Comment by jianshu93** [comment]
when I run RcppParallel::defaultNumThreads() I have 128. it seems that not the RcppParallel problem?

thanks,

Jianshu

**Comment by jianshu93** [comment]
How about this parallel R package to use all cpus?(https://www.jstatsoft.org/article/view/v097c01)

thanks,

Jianshu

**Comment by benjjneb** [comment]
We will continue to rely on RcppParallel for our multithreading implementation.

Notable for your case, denoising after the error-learning step is "embarassingly parallel", and can take full advantage of multiple compute nodes by dispatching the processing of each sample to its own node. This does require a bit of R/server scripting, but might be worth pursuing here.
