### ISSUE TITLE
x-axis scale to trim

### ISSUE THREAD

**Issue by marwa38** [benjjneb/dada2#1314]
Hello 

I need to change the scale of the x-axis from 0, 100, 200, 300 to include 50, 150, 250 in "plotQualityProfile" in R 
So that from which bp I need to trim before further downstream analysis using dada2

Could you please help me with this?

Thanks,
Marwa

**Comment by benjjneb** [comment]
The output of `plotQualityProfile` is a ggplot2 object. You can customize anything about it using standard ggplot2 approaches. In this case, I would use `scale_x_continuous` to define the `breaks` where you want labeled tick marks. See here for a tutorial to this: http://www.sthda.com/english/wiki/ggplot2-axis-ticks-a-guide-to-customize-tick-marks-and-labels

**Comment by marwa38** [comment]
Thanks for your reply. 
My query was answered, thanks again
