### ISSUE TITLE
plotQualityProfile(fastqRs[8]) Error in density.default(qscore) : 'x' contains missing values

### ISSUE THREAD

**Issue by lcamVz** [benjjneb/dada2#1316]
I trimmed my sequences with cutadapt I am running amoA sequences. while my forward reads are great and all my reverse reads I get the following error: 

```
plotQualityProfile(fastqRs[8])
Error in density.default(qscore) : 'x' contains missing values
```

Funny thing is that is not in all of the samples that I get that error other reads are good to be plotted. What would you recommend?

The cutadapt retained reads are in the 90-95% in forward and like > 80% in the reverse reads.

**Comment by benjjneb** [comment]
What are the contents of the files giving this error? I'd try inspecting them by hand, or by reading them into R with `ShortRead::readFastq` and taking a look that way.

Are they empty?

**Comment by benjjneb** [comment]
My first guess is that the failure might be from the zero-length reads in the sample (`width: 0...283 cycles`).

Can you look at the same for some samples that don't fail? Do they also have (or don't ahve) 0-cycle reads?

**Comment by lcamVz** [comment]
I ran the `plotQualityProfile` command for which I got a plot and after ran `readFastq` and got this output. 

```
> plotQualityProfile(fastqRs[6])
Warning message:
In .Internal(get(x, envir, mode, inherits)) :
  closing unused connection 3 (../Arch amoA/TRIMMED/111_M_150_BulkSoil_amoA_Arch_sub_R2_trimmed.fastq.gz)
```

```
> readFastq(fastqRs[6])
class: ShortReadQ
length: 26212 reads; width: 1..283 cycles
```

**Comment by benjjneb** [comment]
If I'm reading this right, that sample with no zero-length reads (shortest read is length 1) plotted fine?

Then I think that is probably the issue.

A simple workaround would be to remove all zero-length reads (or perhaps even those below some minimum length cutoff) before doing the quality profile plotting. See the `minLen` parameters in `filterAndTrim` for one way to do that.

**Comment by lcamVz** [comment]
So it doesn't matter how the trimming of adapters goes with cutadapt this can be managed with the commands you have suggested ? Just want to make sure. Will update you how it goes.

**Comment by benjjneb** [comment]
> So it doesn't matter how the trimming of adapters goes with cutadapt this can be managed with the commands you have suggested ?

Removing zero-read samples post-cutadapt can be managed with `filterAndTrim` definitely. The fact that some samples are having very few reads pass through the cutadapt step might indicate some issues with that step though.

**Comment by gabrielet** [comment]
@benjjneb can you give us more info about this thing you said:

> > So it doesn't matter how the trimming of adapters goes with cutadapt this can be managed with the commands you have suggested ?
> 
> Removing zero-read samples post-cutadapt can be managed with `filterAndTrim` definitely. The fact that some samples are having very few reads pass through the cutadapt step might indicate some issues with that step though.

which issues might be related to the cutadapt returning very short, or even 0-length, reads?

**Comment by benjjneb** [comment]
> which issues might be related to the cutadapt returning very short, or even 0-length, reads?

The underlying methods we use to read in fastq files break when zero-length reads are present.
