### ISSUE TITLE
AssignTaxonomy() using custom COI database yields Arthropods or NA's

### ISSUE THREAD

**Issue by elaine-shen** [benjjneb/dada2#1318]
Hello,

I am using a custom COI database formatted as DADA2 requires on my marine samples and getting back that almost all of my sequences are phylum Arthropoda (and NA's past that). I've run this using tryRC = TRUE and with a min Bootstrap of 50 and 80 with little differences.

Here is a preview of the database:
```
>Eukaryota;Mollusca;Gastropoda;Neogastropoda;Cancellariidae;NA;NA;
TTTGTCTAGAAACCTAGCTCATATAGGTGGGTCTGTAGATTTAGCTATTTTTTCTCTTCATTTAGCAGGGGCTTCGTCAATTTTAGGTGCGGTAAATTTTATTACTACCGTAACTAACATGCGATGGGCAGGGATGCAATGAGAGCGCCTTACTTTATTTACTTGGTCTGTAAAAATTACTGCTGTTTTGCTTCTTTTGTCTCTTCCAGTTTTAGCCGGTGCAATTACAATATTACTAACGGACCGTAATTTTAATACTGCCTTTTTTGACCCTGCGGGAGGGGGGGACCCCGTACTATACCAGCATCTGTTT
>Eukaryota;Arthropoda;Insecta;Coleoptera;Dytiscidae;Agabus;NA;
CCTATCATCAGGTATTGCTCACGGGGGGGCTTCAGTAGATTTAGCTATTTTTAGATTACATTTAGCGGGAATCTCATCAATTTTAGGGGCTGTGAATTTCATTACTACAATTATTAATATACGATCTGTTGGAATAACTTTTGATCGAATACCATTATTTGTGTGATCAGTAGGAATTACAGCACTATTATTACTTTTATCTYTACCTGTATTAGCGGGAGCTATTACAATATTATTAACTGATCGAAATTTAAATACTTCATTTTTTGATCCGGCGGGAGGGGGAGACCCTATTCTCTATCAACATTTATTT
```

The dimensions of my sequence table:
```
dim(seqtab.nochim)
[1]   211 41017
```

The code I ran:
```
library(dada2)

seqs = readRDS("combined.rds")
taxa <- assignTaxonomy(seqs, "coi_dada2_v2.fasta", multithread=TRUE,tryRC=TRUE,  minBoot=50)
saveRDS(taxa, "combined-taxonomy.rds")

```

And here is the first ASV in my table that unambiguously comes back as Cephalopholis cyanostigma on BLAST that is getting the following assignment using `assignTaxonomy()`

  | Kingdom | Phylum | Class | Order | Family | Genus | Species
-- | -- | -- | -- | -- | -- | -- | --
TAGCCGGCAACCTGGCTCATGCAGGCGCTTCCGTTGATTTAACAATCTTTTCACTACATTTAGCAGGTATTTCATCAATTCTAGGGGCAATCAACTTTATCACAACCATTATTAACATGAAACCTCCCGCCATCTCCCAATACCAAACACCCCTGTTTGTATGGGCTGTATTAATTACAGCTGTCCTTCTTCTTCTTTCCCTCCCCGTTCTCGCTGCAGGTATTACAATGCTTCTAACTGATCGAAACCTGAACACCACCTTCTTTGACCCAGCTGGTGGAGGAGACCCAATTCTTTATCAACACTTATTT | Eukaryota | Arthropoda | NA | NA | NA | NA | NA

Thanks in advance for the help!

**Comment by benjjneb** [comment]
Custom database issues can be tricky to diagnose. Can you try a couple experiments to see if they can provide some guidance?

One thing to try is to subset the reference down dramatically, maybe to just entries from the Teleosts (or even lower), and see if the correct Genus or Family at least is being picked out from that reference set. Another idea would be to search the reference fasta for all exact matches to this example query sequence, and then inspect the ID lines for all of them. Are they as expected?

Finally, what version of the dada2 R package are you using?

**Comment by elaine-shen** [comment]
Hi @benjjneb , 
Thanks for getting back to me! I greatly appreciate the time you take for me and others on this forum. 

I am running a new job where I am running `assignTaxonomy()` on my sequences, this time with just a subset of my reference fasta to only Teleosts. I will report back when it's finished!

To answer your other questions, when I look up the full sequence from my data (posted above, it BLASTs to Cephalopholis cyanostigma) in the reference database, I do not get an exact match, but when I look up just a subset of the sequence (GCAGGCGCTTCCGTTGATTTAACAATCTTTTCACTACATTTAGCAGGTATTTCATCAATTCTAGGGGCAATCAACTTTATCACAACCATTATTAACATGAAACCTCCCGCCATCTCCCAATACCAAACACCCCTGTTTGTATG), I am able to find entries in my reference database pointing to Cephalopholis cyanostigma entries or other fish species in the same genus.

I am running 
```
> packageVersion("dada2")
[1] ‘1.18.0’
```

**Comment by elaine-shen** [comment]
As an update,

When I subset my database to sequences that contain class = Actinopteri and rerun `assignTaxonomy()` on my full dataset, 100% of my ASVs come back as Actinopteri, with some species-level assignments that admittedly, make sense. Here's an example below, where the first ASV is assigned now to a fish despite it (probably) being an algae, while the second ASV correctly gets identified to a fish species (verified with BLAST searches). What could be causing this issue? 


GTTAAGTAGTGTTCAAGCACATTCTGGGCCTTCTGTCGATTTAGCTATTTTTAGCCTTCACTTATCTGGGGCTTCTTCTATTTTGGGAGCGATAAACTTTATAACTACTATTTTCAATATGAGGTCACCTGGTATGACTATGCACAGATTACCACTAATGGTTTGGGCTGTCTTAATAACAGCTTTCCTATTATTGTTATCTTTACCTGTGCTTGCTGGAGCGATCACAATGCTTCTTACAGACAGAAACTTTAATACCACTTTTTTTGATCCCGCTGGTGGTGGAGATCCCGTGTTGTATCAACATTTGTTC | Eukaryota | Chordata | Actinopteri | NA | NA | NA | NA
-- | -- | -- | -- | -- | -- | -- | --
ACTATCCGGAAACCTAGCCCACGCAGGGGCATCAGTAGACCTAACCATTTTCTCCCTTCACCTAGCAGGTGTTTCATCAATTCTGGGAGCAATTAACTTTATTACCACTATTATTAACATGAAACCTCCTGCCATTTCACAATATCAAACCCCCCTGTTTGTTTGAGCCGTGCTAATTACTGCCGTCCTGCTTCTCTTATCTCTCCCCGTTCTGGCAGCTGGTATTACCATGTTATTAACAGACCGAAATCTAAACACCACCTTCTTTGACCCAGCAGGAGGAGGAGATCCGATTCTTTACCAGCACCTCTTC | Eukaryota | Chordata | Actinopteri | NA | Pomacentridae | Amblyglyphidodon | Amblyglyphidodon curacao

**Comment by benjjneb** [comment]
> When I subset my database to sequences that contain class = Actinopteri and rerun assignTaxonomy() on my full dataset, 100% of my ASVs come back as Actinopteri, with some species-level assignments that admittedly, make sense. Here's an example below, where the first ASV is assigned now to a fish despite it (probably) being an algae, while the second ASV correctly gets identified to a fish species (verified with BLAST searches). What could be causing this issue?

This is the expected behavior actually, so that is promising.

The "issue" here is that the way the naive Bayesian classifier works is that if your entire database only contains Actinopteri, everything will be reported as Actinopteri, because uncertainty is only quantified by this method as sometimes the subsampled sequence gets assigned to one taxon, and sometimes another. But when everything in the reference db is the same taxon, you'll always get that taxon back (include outgroups!).

So... assignment appears to be workign as expected on this subset, so that rules out any gross mismatch between the expected header format.

**Comment by benjjneb** [comment]
> To answer your other questions, when I look up the full sequence from my data (posted above, it BLASTs to Cephalopholis cyanostigma) in the reference database, I do not get an exact match, but when I look up just a subset of the sequence (GCAGGCGCTTCCGTTGATTTAACAATCTTTTCACTACATTTAGCAGGTATTTCATCAATTCTAGGGGCAATCAACTTTATCACAACCATTATTAACATGAAACCTCCCGCCATCTCCCAATACCAAACACCCCTGTTTGTATG), I am able to find entries in my reference database pointing to Cephalopholis cyanostigma entries or other fish species in the same genus. This is what's confusing me, as I don't think it's a formatting issue on my end, but perhaps some misalignment happening with the database?

That is confusing. One more experiment, if you BLAST this example query against just the subset of your reference db from Arthropoda, do any relevant hits come up?

**Comment by elaine-shen** [comment]
It's good that it's not a header mismatch! 

I BLASTed the example query against the subset of the reference DB with just Actinopteri (class of bony fishes) and attached here are the results - the top 10+ hits are to Cephalopholis cyanostigma (the anticipated ID). This is the first time I've run BLAST like this, so below is my code, where testseq.fasta is just a dummy header and the query sequence:

`makeblastdb -in crux_dada2_v2_fish_modified.fasta -dbtype nucl


Building a new DB, current time: 04/20/2021 11:26:06
New DB name:   /data/lanelab/eshen/dada2-taxonomy/crux_dada2_v2_fish_modified.fasta
New DB title:  crux_dada2_v2_fish_modified.fasta
Sequence type: Nucleotide
Keep Linkouts: T
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 128396 sequences in 7.73792 seconds.

blastn -query testseq.fasta -db crux_dada2_v2_fish_modified.fasta -evalue 1e-6 -num_threads 4 -out blastn_test.txt`
 
[blastn_test.txt](https://github.com/benjjneb/dada2/files/6345676/blastn_test.txt)

**Comment by elaine-shen** [comment]
Also, I ran into similar issues using this database with qiime2, and you can see what folks on that forum said here: [https://forum.qiime2.org/t/taxonomy-assignment-with-custom-coi-database-odd-wrong-classifications/19258/6]

**Comment by benjjneb** [comment]
I do think it's worth taking a look at your reference sequences in terms of their overall lengths, and number of ambiguous nucleotides. That is something I hadn't considered, but in general you want to remove too-short sequences and those with lots of Ns, as they can cause the mistaken hits mentioned in the Q2 forum post you linked.

**Comment by elaine-shen** [comment]
Thanks for all of your help on this! I will try to take a look and update this forum if anything arises.
