### ISSUE TITLE
Optimal processing of Illumina PE reads from multiplexed samples employing tagged primers?

### ISSUE THREAD

**Issue by tobiasgf** [benjjneb/dada2#132]
Dear

Impressive study and R package! Thanks.
I have successfully applied the method for a few test samples and are now looking forward to try it on larger datasets.

However I have a different approach in my data generation - a variation that is widely used – that call for some custom preparations before running DADA2. And I would like to hear you opinion on that.

I am using Illumina MiSeq Paired end (usually 250 bp) sequencing of amplicons. But for amplification of my samples, I use forward and reverse primers with small (6-8 bp) tags to be able to multiplex several samples in each library. Individually tagged PCR products are pooled and build into one library by annealing adapters onto the amplicons.
Lets assume that I have data from one library (LibA) consisting of one R1 and one R2 file. And that this library consists of PCR products from 20 different samples, each tagged with different forward tags and reverse tags (using combinations Forward_tag_01+Reverse_tag_01 to Forward_tag_20+Reverse_tag_20).
For running DADA2 as suggested in the tutorial, I need to split (demultiplex) my R1 and R2 file into 20 R1 and R2 files corresponding to my 20 samples. This I presently do by using a custom script based on CUTADAPT which finds and removes the 20 different specified tag+primer combinations for both forward and reverse primer in both R1 and R2 file - resulting in 20 "R1" and 20 "R2" files. Afterwards I use the fastqPairedFilter command described here in the FAQ under the section "What if my forward and reverse reads aren’t in matching order?" to synchronize my 20 demultiplexed "R1"/"R2" files pairwise. This (the CUTADAPT part) is very time consuming, and suggestions for alternative methods are wellcome!
Also, there is the (potential) problem, that my reads are in random orientation (due to the annealing of adapters on to the amplicons), meaning that half of my R1 (and R2) file will have the reads in reverse order.
This I solve by concatenating the (full Library!) R1 and R2 (in that order, and before demultiplexing), and let's call that resulting file "C1") and likewise concatenate R2 and R1 - in that order - and let's call that file "C2"). Then I use the CUTADAPT script to look for the 20 different forward_tags in C1, and subsequently look for the 20 different reverse_tags in C2. Then I will have one forward file "R1" and one reverse file "R2" for each sample - corresponding (almost) to "your" R1 and R2 for each sample. And then I run the fastqPairedFilter to get the reads in matching order. However, the first half of the Forward "R1" reads will be from the R1 file and the second half will actually be from the R2 file, and visa versa for the Reverse reads. Is that a problem for DADA2 to run optimally (assuming that error rates will be different between R1 and R2, and that mixing them will make the DADA2 run suboptimally)? Should I rather keep them separate, having two (a sense and an antisense orientated) R1/R2 pairs for each sample, and process those separately, and merge these later in the process? and when? and how?
Or maybe you have other suggestions for processing paired end Illumina reads from multiplexed samples employing tagged primers?

Thanks in advance
Tobias

**Comment by benjjneb** [comment]
The demultiplexing you described seems good as far as I can tell. The random orientations is a bit tricky though, for exactly the reason you described: "(assuming that error rates will be different between R1 and R2, and that mixing them will make the DADA2 run suboptimally)".

I would recommend your suggestion: "keep them separate, having two (a sense and an antisense orientated) R1/R2 pairs for each sample, and process those separately, and merge these later in the process"

Assuming you are using the same `trimLeft` value for both F/R reads: You should be able to merge the sense/anti-sense sequence tables at the end by:

```S
colnames(seqtab.antisense) <- dada2:::rc(colnames(seqtab.antisense)) # reverse-complement
seqtab <- mergeSequenceTables(seqtab.sense, seqtab.antisense)
```

**Comment by tobiasgf** [comment]
The procedure you describe will produce two entries (columns) pr sample in the final table, right?
Is there a way to merge these pairs in the DADA2 pipeline (maybe even prior to building the seqtab?), or will I have to do that with dplyr or some other R approach, after the DADA2 mergeSequenceTables.

**Comment by benjjneb** [comment]
Good point. Actually it will fail because `mergeSequenceTables` will complain about the duplicate sample names.

That's probably the right default behavior, so here is a modified version of the function that will do what you want (sum duplicated samples):

```S
sumSequenceTables <- function(table1, table2, ..., orderBy = "abundance") {
  # Combine passed tables into a list
  tables <- list(table1, table2)
  tables <- c(tables, list(...))
  # Validate tables
  if(!(all(sapply(tables, dada2:::is.sequence.table)))) {
    stop("At least two valid sequence tables, and no invalid objects, are expected.")
  }
  sample.names <- rownames(tables[[1]])
  for(i in seq(2, length(tables))) {
    sample.names <- c(sample.names, rownames(tables[[i]]))
  }
  seqs <- unique(c(sapply(tables, colnames), recursive=TRUE))
  sams <- unique(sample.names)
  # Make merged table
  rval <- matrix(0L, nrow=length(sams), ncol=length(seqs))
  rownames(rval) <- sams
  colnames(rval) <- seqs
  for(tab in tables) {
    rval[rownames(tab), colnames(tab)] <- rval[rownames(tab), colnames(tab)] + tab
  }
  # Order columns
  if(!is.null(orderBy)) {
    if(orderBy == "abundance") {
      rval <- rval[,order(colSums(rval), decreasing=TRUE),drop=FALSE]
    } else if(orderBy == "nsamples") {
      rval <- rval[,order(colSums(rval>0), decreasing=TRUE),drop=FALSE]
    }
  }
  rval
}
```

**Comment by benjjneb** [comment]
Closing under assumption this worked, but please reopen if that's not the case.

**Comment by Perugolate** [comment]
I had the same issue and it worked fine for me

**Comment by tobiasgf** [comment]
I am not that far in my analyses yet. I'll let you know whether it works :-) - thanks!

**Comment by tobiasgf** [comment]
Opening again, to ask a small question.

I try to filter (pair) paired reads in R1/R2 files using this command:
```
for(i in seq_along(fnFs)) {
  fastqPairedFilter(c(fnFs[i], fnRs[i]), c(filtFs[i], filtRs[i]),
                    matchIDs=TRUE)
}

```
When I do that I often get an error:
```Error in (lastF + 1):length(fqF) : result would be too long a vector
Calls: fastqPairedFilter -> [
In addition: Warning messages:
1: In max(which(idsF %in% idsR)) :
  no non-missing arguments to max; returning -Inf
2: In max(which(idsR %in% idsF)) :
  no non-missing arguments to max; returning -Inf
Execution halted
```

I think I have found out that this is happening when I try to process R1/R2 files with no matching reads.  This will often be the case for controls and samples with very few reads. I can of course avoid the error by deleting those files beforehand, but they (R1/R2 with no matching reads) are difficult to spot as the files are not empty.

Is there some way to run the pairing command without stopping on encountering R1/R2 with no matches? (Or maybe a way to identify and exclude those before?)

Kind regards
Tobias

**Comment by Oruku-Ososo** [comment]
Hello benjjneb. I was trying out your Bioconductor tutorial and everything seemed to be wotking until I ran into this error: Error in fastqPairedFilter(c(fnFs[[i]], fnRs[[i]]), c(filtFs[[i]], filtRs[[i]]),  :   object 'filtFs' not found. please any way around it?
Thank you.

**Comment by benjjneb** [comment]
@Oruku-Ososo

There is (was) a typo in a couple commands in the F1000 workflow in which `filtsFs` was used instead of `filtFs`. Can you check if making sure everything is `filtFs` in the code you are usihng fixes the problem?

If that doesn't work, can you post exactly the code you are running up to the poiunt of the error?

**Comment by Oruku-Ososo** [comment]
Thank you for your response. Here are the codes:

library("knitr")
library("BiocStyle")
opts_chunk$set(cache = FALSE,fig.path="dadafigure/")
read_chunk(file.path("src", "bioinformatics.R"))
.cran_packages <- c("ggplot2", "gridExtra")
.bioc_packages <- c("dada2", "phyloseq", "DECIPHER", "phangorn")
.inst <- .cran_packages %in% installed.packages()
if(any(!.inst)) {
   install.packages(.cran_packages[!.inst])
}
.inst <- .bioc_packages %in% installed.packages()
if(any(!.inst)) {
   source("http://bioconductor.org/biocLite.R")
   biocLite(.bioc_packages[!.inst], ask = F)
}
# Load packages into session, and print package version
sapply(c(.cran_packages, .bioc_packages), require, character.only = TRUE)
set.seed(100).

fns <- sort(list.files(miseq_path, full.names = TRUE))
fnFs <- fns[grepl("R1", fns)]
fnRs <- fns[grepl("R2", fns)]

ii <- sample(length(fnFs), 3)
for(i in ii) { print(plotQualityProfile(fnFs[i]) + ggtitle("Fwd")) }
for(i in ii) { print(plotQualityProfile(fnRs[i]) + ggtitle("Rev")) }

Everything seemed to work up till this point. The error I kept having was from the following code:

if(!file_test("-d", filt_path)) dir.create(filt_path)
filtFs <- file.path(filt_path, basename(fnFs))
filtRs <- file.path(filt_path, basename(fnRs))
for(i in seq_along(fnFs)) {
  fastqPairedFilter(c(fnFs[[i]], fnRs[[i]]),
                    c(filtFs[[i]], filtRs[[i]]),
                    trimLeft=10, truncLen=c(245, 160),
                    maxN=0, maxEE=2, truncQ=2,
                    compress=TRUE)
}

**Comment by benjjneb** [comment]
@Oruku-Ososo Have you defined the `filt_path` variable? I don't see it in the code you listed, and if not you need to define that path, which should be the directory you want to write the filtered files too.

If that's not it, can you post the output of the following:
```
filt_path
head(fnFs)
head(filtFs)
```

**Comment by Oruku-Ososo** [comment]
I couldn't get the following code to run: 
miseq_path <- file.path("data", "MiSeq_SOP")
filt_path <- file.path("data", "filtered")
if(!file_test("-d", miseq_path)) {
  dir.create(miseq_path)
  download.file("http://www.mothur.org/MiSeqDevelopmentData/StabilityNoMetaG.tar",
                
                destfile = file.path(miseq_path, "StabilityNoMetaG.tar"))
  
  system(paste("tar -xvf ", file.path(miseq_path, "StabilityNoMetaG.tar"),
                " -C ", miseq_path, "/"))
}
--------------------------------------------------------------------------------------
I did a slight modification after downloading the Miseq_SOP data file in the following: 
miseq_path <- file.path("C:", "MiSeq_SOP")
filt_path <- file.path("MiSeq_SOP", "filtered")
-------------------------------------------------------------------------------------
After the above mentioned modification, I was able to run the quality filtering code to get the sequence quality charts, without problems.
However, I couldn't get past this commands: 

for(i in seq_along(fnFs)) {
  fastqPairedFilter(c(fnFs[[i]], fnRs[[i]]),
                    c(filtFs[[i]], filtRs[[i]]),
                    trimLeft=10, truncLen=c(245, 160),
                    maxN=0, maxEE=2, truncQ=2,
                    compress=TRUE)
}

It showed the following:
Error in writeFastq(fqF, fout[[1]], "w", compress = compress) : 
  failed to open file 'MiSeq_SOP/filtered/F3D0_S188_L001_R1_001.fastq'
----------------------------------------------------------------------------
Here are the outputs you requested for:
> **filt_path**
[1] "MiSeq_SOP/filtered"
> **head(filtFs)**
[1] "MiSeq_SOP/filtered/F3D0_S188_L001_R1_001.fastq"  
[2] "MiSeq_SOP/filtered/F3D1_S189_L001_R1_001.fastq"  
[3] "MiSeq_SOP/filtered/F3D141_S207_L001_R1_001.fastq"
[4] "MiSeq_SOP/filtered/F3D142_S208_L001_R1_001.fastq"
[5] "MiSeq_SOP/filtered/F3D143_S209_L001_R1_001.fastq"
[6] "MiSeq_SOP/filtered/F3D144_S210_L001_R1_001.fastq"
> **head(fnFs)**
[1] "C:/MiSeq_SOP/F3D0_S188_L001_R1_001.fastq"  
[2] "C:/MiSeq_SOP/F3D1_S189_L001_R1_001.fastq"  
[3] "C:/MiSeq_SOP/F3D141_S207_L001_R1_001.fastq"
[4] "C:/MiSeq_SOP/F3D142_S208_L001_R1_001.fastq"
[5] "C:/MiSeq_SOP/F3D143_S209_L001_R1_001.fastq"
[6] "C:/MiSeq_SOP/F3D144_S210_L001_R1_001.fastq"

Looking forward to you response.

Thank you.
Oruku-Ososo

**Comment by benjjneb** [comment]
@Oruku-Ososo 

There is a line in the F1000 code that creates the filtered directory. Did you execute that command?

```
if(!file_test("-d", filt_path)) dir.create(filt_path)
```

If you haven't created the filtered subdirectory, you will get the error you saw.

Also, happy to help with your issues, but it would be better to post problems running the F1000 workflow over at the github for the F1000 paper: https://github.com/spholmes/F1000_workflow/issues
