### ISSUE TITLE
Primer removal with dada2/cutadapt in R

### ISSUE THREAD

**Issue by tgaire** [benjjneb/dada2#1320]
Hi,
I'm running dada2, and I wanted to identify and removed the primers (v4 primers):
My data : Illumina Miseq 2X300 paired end sequencing,
V4 primers:
 
FWD <- 'GTGCCAGCMGCCGCGGTAA'
REV <- 'GGACTACHVGGGTWTCTAAT'

So I ran the code up to Identify primers and got following output results:
                                 Forward Complement Reverse RevComp
FWD.ForwardReads   28572          0             0                   66
FWD.ReverseReads      59              0             0                   18788
REV.ForwardReads      68              0             0                    25886
REV.ReverseReads   28014            0             0                    35

Does this okay?

Also, I wanted to removed primers using cutadapt function, but could not find the function for V4 primers?

I found following code for ITS primer,
path.cut <- file.path(path, "cutadapt")
if(!dir.exists(path.cut)) dir.create(path.cut)
fnFs.cut <- file.path(path.cut, basename(fnFs))
fnRs.cut <- file.path(path.cut, basename(fnRs))

FWD.RC <- dada2:::rc(FWD)
REV.RC <- dada2:::rc(REV)
# Trim FWD and the reverse-complement of REV off of R1 (forward reads)
R1.flags <- paste("-g", FWD, "-a", REV.RC) 
# Trim REV and the reverse-complement of FWD off of R2 (reverse reads)
R2.flags <- paste("-G", REV, "-A", FWD.RC) 
# Run Cutadapt
for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                             fnFs.filtN[i], fnRs.filtN[i])) # input files
}

Can we use the same code for v4? Hope you can suggest a workaround.

**Comment by benjjneb** [comment]
Your identify primers results suggests that your sequencing data is in random orientation (i.e. half one way,  half the other), is that expected?

**Comment by tgaire** [comment]
Thank you! I’m not quite sure about random orientation of primer! Data generated from 2x300 miseq!
Is there any way I can fix the orientation and remove the primer? 
Thank you so much

**Comment by benjjneb** [comment]
> Thank you! I’m not quite sure about random orientation of primer!

The first thing to do here is to confirm with the sequencing provider that their libraries produced reads in random orientation.

**Comment by tgaire** [comment]
Sure, thank you!

**Comment by tgaire** [comment]
I'm still waiting for their reply, but I did additional steps:

head(dadaFs[[1]]$clustering)
                                                                                                                                                                                                                       sequence
1 TACGTAGGTGGCGAGCGTTGTCCGGATTTACTGGGCGTAAAGGGAGCGTAGGCGGACTTTTAAGTGAGATGTGAAATACCCGGGCTCAACTTGGGTGCTGCATTTCAAACTGGAAGTCTAGAGTGCAGGAGAGGAGAATGGAATTCCTAGTGTAGCGGTGAAATGCGTAGAGATTAGGAAGAACACCAGTGGCGAAGGCGATTCTCTGGACTGTAACTGAC
2 TACGTAGGGTGCGAGCGTTGTCCGGAATTACTGGGCGTAAAGAGCTCGTAGGTGGTTTGTCGCGTCGTCTGTGAAAGTCCAGCGCTTAACGCTGGGATTGCAGGCGATACGGGCTTACTTGAGTGCTGTAGGGGAGACTGGAATTCCTGGTGTAGCGGTGAAATGCGCAGATATCAGGAGGAACACCAATGGCGAAGGCAGGTCTCTGGGCAGTCACTGAC
3 TACGTAGGGGGCTAGCGTTATCCGGAATTACTGGGCGTAAAGGGTGCGTAGGTGGTTTCTTAAGTCAGAGGTGAAAGGCTACGGCTCAACCGTAGTAAGCCTTTGAAACTGGGAAACTTGAGTGCAGGAGAGGAGAGTGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAGGAACACCAGTTGCGAAGGCGGCTCTCTGGACTGTAACTGACA
4 TACGTAGGGTGCAAGCGTTATCCGGATTTATTGGGCGTAAAGGGCTCGTAGGCGGTTCGTCGCGTCCGGTGTGAAAGTCCATCGCTTAACGGTGGATCCGCGCCGGGTACGGGCGGGCTTGAGTGCGGTAGGGGAGACTGGAATTCCCGGTGTAACGGTGGAATGTGTAGATATCGGGAAGAACACCAATGGCGAAGGCAGGTCTCTGGGCCGTTACTGAC
5 TACGTAGGTGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGAGCGCGCAGGTGGTTGATTAAGTCTGATGTGAAAGCCCACGGCTTAACCGTGGAGGGTCATTGGAAACTGGTCGACTTGAGTGCAGAAGAGGGAAGTGGAATTCCATGTGTAGCGGTGAAATGCGTAGAGATATGGAGGAACACCAGTGGCGAAGGCGGCTTCCTGGTCTGTAACTGAC
6 CACCGGCAGCTCTAGTGGTAGCAATTTTTATTGGGCCTAAAGCGTCCGTAGCCGGTTTAATAAGTCTCTGGTGAAATCCTGTAGCTTAACTGTGGGAATTGCTGGAGATACTATTAGACTTGAGACCGGGAGAGGTTAGAGGTACTCCCAGGGTAGAGGTGAAATTCTGTAATCCTGGGAGGACCGCCTGTTGCGAAGGCGTCTAACTGGAACGGTTCTGA
  abundance  n0  n1 nunq pval birth_type birth_pval    birth_fold birth_ham birth_qave
1      1171 685 216  377    0          I         NA            NA        NA         NA
2      1011 664 147  299    0          A          0 4.356239e+130        52   37.40385
3      1067 608 214  359    0          A          0  3.866433e+83        34   37.88235
4       802 537 116  227    0          A          0 2.629659e+141        57   37.33333
5       781 480  91  265    0          A          0  1.966570e+92        37   37.54054
6       652 458 136  158    0          A          0 2.461636e+182        72   37.44444

> head(dadaRs[[1]]$clustering)
                                                                                                                                                                              sequence
1 CCTGTTTGCTCCCCACGCTTTCGAGCCTCAGCGTCAGTTACAGTCCAGAGAATCGCCTTCGCCACTGGTGTTCTTCCTAATCTCTACGCATTTCACCGCTACACTAGGAATTCCATTCTCCTCTCCTGCACTCTAGACTTCCAGTTTGAAATGCAGCACCCAAGTTGAGCCCGGGTATTT
2 CCTGTTTGCTCCCCACGCTTTCGCGCCTCAGTGTCAGTTACAGACCAGGAAGCCGCCTTCGCCACTGGTGTTCCTCCATATCTCTACGCATTTCACCGCTACACATGGAATTCCACTTCCCTCTTCTGCACTCAAGTCGACCAGTTTCCAATGACCCTCCACGGTTAAGCCGTGGGCTTT
3 CCTGTTGGCTACCCATGCTTTCGCTCCTCAGTGTCAGTGACTGCCCAGAGACCTGCCTTCGCCATTGGTGTTCCTCCTGATATCTGCGCATTTCACCGCTACACCAGGAATTCCAGTCTCCCCTACAGCACTCAAGTAAGCCCGTATCGCCTGCAATCCCAGCGTTAAGCGCTGGACTTT
4 CCTGTTTGCTCCCCACGCTTTCGTGCCTCAGTGTCAGTTACAGTCCAGAGAGCCGCCTTCGCAACTGGTGTTCCTCCTAATATCTACGCATTTCACCGCTACACTAGGAATTCCACTCTCCTCTCCTGCACTCAAGTTTCCCAGTTTCAAAGGCTTACTACGGTTGAGCCGTAGCCTTTC
5 CCGGTTCGCGCCCCTAACTTTCGTCCCTCACCGTCAGAACCGTTCCAGTTAGACGCCTTCGCAACAGGCGGTCCTCCCAGGATTACAGAATTTCACCTCTACCCTGGGAGTACCTCTAACCTCTCCCGGTCTCAAGTCTAATAGTATCTCCAGCAATTCCCACAGTTAAGCTACAGGATT
6 CCTGTTCGCTCCCCACGCTTTCGCTCCTCAGCGTCAGTAACGGCCCAGAGACCTGCCTTCGCCATTGGTGTTCTTCCCGATATCTACACATTCCACCGTTACACCGGGAATTCCAGTCTCCCCTACCGCACTCAAGCCCGCCCGTACCCGGCGCGGATCCACCGTTAAGCGATGGACTTT
  abundance  n0  n1 nunq pval birth_type birth_pval    birth_fold birth_ham birth_qave
1      1119 672 208  340    0          I         NA            NA        NA         NA
2      1117 661 155  391    0          A          0  9.991186e+62        25   36.76000
3       995 642 154  294    0          A          0 8.641481e+100        41   37.04878
4       992 635 172  286    0          A          0  4.184598e+60        25   37.12000
5       806 521 150  248    0          A          0 4.767551e+133        54   36.98148
6       792 492 127  259    0          A          0 5.459318e+102        43   36.81395

would it be possible to see from the above results--still primers present or not on reads?
