### ISSUE TITLE
ASV for fungal community with variable length

### ISSUE THREAD

**Issue by jianshu93** [benjjneb/dada2#1324]
Dear Benjamin,

I read the ITS tutorial for fungal community. Theoretically, DADA2 does not modeling indels errors right(though low in MiSeq) and the band_size was not set for high indel sequences, how should I then adjust it for ITS2 sequences. What about algorithms that model indels like AmpliCI for ITS sequences? I know the newest version can handle variable length sequences.

Thanks,

Jianshu

**Comment by benjjneb** [comment]
> Theoretically, DADA2 does not modeling indels errors right(though low in MiSeq) and the band_size was not set for high indel sequences, how should I then adjust it for ITS2 sequences.

The variability in length of real sequences is not an issue for DADA2, so it will work well with ITS2. However there is a limitation in that variants that differ only by just small indels won't be detected.

> What about algorithms that model indels like AmpliCI for ITS sequences? I know the newest version can handle variable length sequences.

AmpliCI is in my opinion a very promising method. I haven't used it on ITS sequences though, so I can't say anything practical.
