### ISSUE TITLE
Preparing dada2 outputs for CoNet

### ISSUE THREAD

**Issue by spriyansh** [benjjneb/dada2#1327]
I am pretty new to metagenomics. I was following this tutorial https://benjjneb.github.io/dada2/tutorial.html,

I have completed taxonomic assignments using RDP. My end goal is to feed the output from dada2 (ASVs) to [CoNet](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5089131/) for co-occurrence network analysis.

CoNet takes a presence/absence, count or abundance matrix as input, where rows represent the objects of interest and columns their observations across locations or time points. 

Can you tell me how I can make this matrix in dada2, or is this the same matrix we make using ```removeBimeraDenovo(seqtab.all)```?

**Comment by benjjneb** [comment]
The sequence table created in dada2 is a matrix where the rows correspond to the samples, the columns correspond to the ASVs (features), and the values correspond to the relative abundances in terms of counts.

So it's basically already the format desired by CoNet, with the caveat that I think what you are saying is that CoNet wants the transpose of this matrix, i.e. the rows to be the features (ASVs) and the columns to be the samples. So: `t(seqtab)` will give you that transposed matrix.

**Comment by spriyansh** [comment]
Thank you @benjjneb  it worked.
