### ISSUE TITLE
PacBio 16s rRNA full length sequence analysis

### ISSUE THREAD

**Issue by sramani-spark** [benjjneb/dada2#1328]
Dear Benjamin,
I have 16s full length sequences from mice digesta samples to be analyzed which are in .fasta format. I tried to follow both Tutorial and Bigdata pipelines but I'm unable to proceed after the following code and it is resulting as follow:
1)
> plotQualityProfile(fnFs[1:2])
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'dirPath' in selecting a method for function 'qa': record does not start with '@'
2)
> plotQualityProfile(fnFs, 1:2)
Error in FastqSampler(dirPath, ...) : 
  'n' must be length 1, finite and >= 0
3)
>plotQualityProfile(path [1]) /
Error: BiocParallel errors
  element index: 1, 2, 3, 4, 5, 6, ...
  first error: error in evaluating the argument 'dirPath' in selecting a method for function 'qa': record does not start with '@'
In addition: Warning messages:
1: In .Internal(gc(verbose, reset, full)) :
  closing unused connection 3 (C:/Users/user/Documents/Articles/dada2/Working_Directory/rawseq_ccs_7z/samples/111_CCS.fasta)
2: In serialize(data, node$con) :

Is the error due to .fasta format? if so what should work well?

Also, will this workflow fits full length sequence analysis?

**Comment by benjjneb** [comment]
We don't recommend DADA2 for use with data without quality scores (i.e fasta files). You could use standard OTU clustering methods instead, or could try alternative ASV methods such as Deblur or Unoise3, although I don't know if either of those methods has been tested on full-length 16S data.

> Also, will this workflow fits full length sequence analysis?

For those with full-length 16S data in fastq format, we recommend some slight modifications to the workflow to get the most out of it. [Examples for PacBio HiFi data are here](https://github.com/benjjneb/LRASManuscript), and for [LoopSeq data are here](https://github.com/benjjneb/LoopManuscript).

**Comment by SisuPark** [comment]
Dear Benjamin,
Thank you for the response.

I also have .bam, .bam.pbi, .xml, and .fasta file formats, so in this case is it possible?
![image](https://user-images.githubusercontent.com/15093709/116269435-2f57be80-a7b9-11eb-862d-19673908a088.png)
![Capture](https://user-images.githubusercontent.com/15093709/116269745-6d54e280-a7b9-11eb-84c5-37b284060a17.JPG)

**Comment by benjjneb** [comment]
Is this PacBio CCS data? If so, you will want to use their SMRT Link software to create the CCS reads in fastq format, using the `ccs` command in that software. Then that can be used directly in DADA2.

User guide for SMRT Link: https://www.pacb.com/wp-content/uploads/SMRT-Link-User-Guide-v8.0.pdf
The `ccs` command is described on P57.

**Comment by SisuPark** [comment]
Thank you so much for the fast response and information.

I will try that method and update here. Thank you once again.

**Comment by SisuPark** [comment]
Thank you so much for the fast response and information.

Yes they are PacBio CCS data. Luckily I asked the vendor for both fasta and raw data where he provided all this 4 types of file formats. I will try that method and update here again. 

I'm new to this type of analysis so I'm unaware of such information. Kindly tell what is the best resource to understand and know all these information.

Thank you once again.

**Comment by benjjneb** [comment]
> I'm new to this type of analysis so I'm unaware of such information. Kindly tell what is the best resource to understand and know all these information.

For PacBio CCS processing, the best resource is probably PacBio itself, as they develop the bioinformatics software that you use to process the raw reads into the high-accuracy CCS reads (or "HiFi" reads as they are now branded).

**Comment by cjfields** [comment]
@SisuPark to add a few additional points of consideration. the default minimal consensus error rate for CCS data is 99%, but the PacBio workflow (and code @benjjneb points to) I believe uses a default of _99.9%_ minimum error rate for the inputs, so you would need to adjust the consensus calling step accordingly to generate the FASTQ. I'm not sure if anyone has tested default 99% error rate data yet, it's been on our TODO list for a while though in general we haven't seen significant enough loss of data to make this a priority and follow it up.

Additionally, if the data are generated from a Sequel IIe the final PacBio BAM will no longer have the raw subreads included by default to reduce data size (they are preprocessed consensus calls).  PacBio developed a newer filtering step to generate the proper FASTQ data with minimal errors. 

In both cases, hopefully your sequencing center can generate these for you.

**Comment by SisuPark** [comment]
@benjjneb and all,

Thank you for the response.
As per your previous instructions I managed to get the fastq format of all my data and tried dada2 as mentioned in "Examples for PacBio HiFi data" in previous comments, I'm not able to get the results. I think my sequence is not getting assigned or being mapped with the taxonomy. when I tried to check the results it shows there is no bacteria is being mapped. very few times the bacteria list is being showed very differently whereas, mostly it shows NA, So further to confirm I opened individual file and selected a random sequence and BLAST checked which results in classified bacteria. 
 
Hence I here have showed one such example of the results obtained and also I have attached the code file which I used.

> rowSums(st2[,is.ecoli]>0)
  111 12172 13183 17233 19255   222 25322 26333 27344   291 29361   302 30372   313 32394   333   393   404   415   426 
    0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0 
  437   448   451   462   473   484   495   506   511   533   555   566   578   591   602   613   624   641   652   663 
    0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0 
  674   685   707   711   722   733   741   752 
    0     0     0     0     0     0     0     0

Since the mapping is not completed though I get plots for only one bacteria I'm not able to believe as such. Also, for the same I couldnt get the timepoint based plots. 



[16s.zip](https://github.com/benjjneb/dada2/files/6466005/16s.zip)


> 
> 
> We don't recommend DADA2 for use with data without quality scores (i.e fasta files). You could use standard OTU clustering methods instead, or could try alternative ASV methods such as Deblur or Unoise3, although I don't know if either of those methods has been tested on full-length 16S data.
> 
> > Also, will this workflow fits full length sequence analysis?
> 
> For those with full-length 16S data in fastq format, we recommend some slight modifications to the workflow to get the most out of it. [Examples for PacBio HiFi data are here](https://github.com/benjjneb/LRASManuscript), and for [LoopSeq data are here](https://github.com/benjjneb/LoopManuscript).

Thank you in advance.

**Comment by benjjneb** [comment]
> I think my sequence is not getting assigned or being mapped with the taxonomy. when I tried to check the results it shows there is no bacteria is being mapped. very few times the bacteria list is being showed very differently whereas, mostly it shows NA, So further to confirm I opened individual file and selected a random sequence and BLAST checked which results in classified bacteria.

What would be most useful is if you would be very specific about what is going on, and why you think th results are incorrect.

Show us a sequence, and the associated classification command, that is being potentially misassigned.
