### ISSUE TITLE
Error modeling with different amplicon lengths in the same run

### ISSUE THREAD

**Issue by thallinger** [benjjneb/dada2#1329]
First of all, thanks a lot for providing such a great tool for
the analysis of microbiome amplicon data together with the informative
tutorials.

We have several community samples where we amplified three types
of full length amplicons (16S, 18S and partial 18S with full length
ITS) to be able to characterize their bacterial- as well as their
unicellular eukaryotic members.
The amplicons have an average length of 1570, 1830, and 2000 bps,
respectively. All samples were sequenced on the same lane of a PacBio
Sequel SMRT Cell 1M v3 and yielded between 100 and 40,000 CCS reads
per sample.

Up to now we have determined the error model for the different 
amplicons individually, using all reads available from the specific
type (see attached plots).

As the number of bases in the 16S is rather low (~7.5 Mbps) and there
seem to be some artefacts in the plot of the error model, we are now 
wondering, whether we could build the error model from an appropriate
number of reads independent of amplicon type.

Furthermore, we would like to know, what the minimal/recommended
number of reads/nucleotides is to get a reliable error model.

We also noticed some outlying transition probabilities for 16S 
(e.g. for C2A and T2A) and 18S models (e.g. for A2C and G2C). 
Is this something of concern or can this be ignored?

Finally, the transition probability drops considerably for quality
values 91 and 92, but increases sharply for 93, which is counter-
intuitive, as for higher quality base a further decrease would be
expected. In addition, the sum of transition probabilities for QV 93
exceeds 1.0 for the 16S and 18S error models.

Any thoughts on these issues are highly appreciated.

[Error models.pdf](https://github.com/benjjneb/dada2/files/6385508/Error.models.pdf)

Environment: dada2 1.18.0 on R 4.0.4.

**Comment by benjjneb** [comment]
> As the number of bases in the 16S is rather low (~7.5 Mbps) and there seem to be some artefacts in the plot of the error model, we are now wondering, whether we could build the error model from an appropriate number of reads independent of amplicon type.

To be honest, I think all these error models look OK. The point of error model fitting is to get a good error model, not a perfect error model. That said, I agree that the amount of data going into the 16S and 18S models is pretty small, and the error model generated by pooling the amplicons together would probably give a better result.

> Furthermore, we would like to know, what the minimal/recommended number of reads/nucleotides is to get a reliable error model.

Rough numbers here are that error models tend to improve up to 10M bases, and up to 100k reads. The limiting factor here is the relatively small number of reads in the 16S and 18S regions, which is why pooling the amplicons together for error modeling seems appropriate.

> Finally, the transition probability drops considerably for quality values 91 and 92, but increases sharply for 93, which is counter- intuitive, as for higher quality base a further decrease would be expected.

This is something we've seen repeatedly in PacBio CCS data -- there is just something different about what's being assigned to Q=93 vs. Q=90-92. It's why there is a PacBio specific error estimation function that fits the model using a smoother up to Q=92, and then independntly on Q=93. That said, we've seen no real cause for concern about this.

> In addition, the sum of transition probabilities for QV 93 exceeds 1.0 for the 16S and 18S error models.

Really? That's weird. Can you post the numbers, or maybe share the error model?

**Comment by thallinger** [comment]
> Rough numbers here are that error models tend to improve up to 10M bases, and up to 100k reads. The limiting factor here is the relatively small number of reads in the 16S and 18S regions, which is why pooling the amplicons together for error modeling seems appropriate.

We generated ASVs with the different error models (with `pooling="pseudo"` and `"DETECT_SINGLETONS=FALSE"`), which
seem to support this:
 ```
     data \ errmodel        16S        18S        ITS
       16S                          54          51        51
       18S                          47          36        33
       ITS                          158         79        67  
```

> Really? That's weird. Can you post the numbers, or maybe share the error model?

The colSums for the transistion probabilities for QV93 are as follows:
```
  base\ err.model               16S                18S                  ITS 
   A2x                       1.000001317   1.000000430   1.000000064
   C2x                       1.000001616   1.000000532   1.000000069
   G2x                       1.000001207   1.000000418   1.000000060
   T2x                       1.000001530   1.000000421   1.000000059
```
The sums for all other QVs are exactly 1.0.

The objects for the different error models are attached.
[err.models.zip](https://github.com/benjjneb/dada2/files/6413451/err.models.zip)

**Comment by benjjneb** [comment]
Thanks for additional information. I found the (very minor) bug in the Q93 calculation, and the latest commit should result in the summed transition probabilties at Q93 equalling exactly one.

The effect here is negligible though, and of no concern for your own data processing.
