### ISSUE TITLE
Modifying dada2 to use forward reads of V1-V3 only?

### ISSUE THREAD

**Issue by sachasuca** [benjjneb/dada2#133]
How can I modify dada2 code to look at forward reads only? My 16S amplicons are V1-V3 with little overlap between the R1 and R2 primers. My reverse reads are very poor quality but the forward reads look good. By using filtered paired-sequences I suspect I am throwing away many good forward sequences because the overlapping region is poor quality. **Is there a way to modify the FastqPairedFilter command to just filter forward reads only?**

**Comment by gblanchard4** [comment]
You can use the `fastqFilter` command instead, it's made for just taking in a single fastq instead of paired fastqs. The usage is nearly the same:

```
fastqFilter(fn, fout, truncQ = 2, truncLen = 0, trimLeft = 0, maxN = 0,
       minQ = 0, maxEE = Inf, rm.phix = FALSE, n = 1e+06, compress = TRUE,
       verbose = FALSE, ...)
```

**Comment by joey711** [comment]
Yep. The single-direction methods were actually implemented first in dada2. Paired read data is so common that it is more prevalent in our workflows/documentation, but single-direction data has always been supported.

**Comment by sachasuca** [comment]
Thanks so much!

**Comment by sachasuca** [comment]
So to be clear, when I construct the sequence table using only filtered forward reads, do I need to merge dadaFs and derepFs lists? If yes, how do I do that?

**Comment by ShirleySteffany** [comment]
> So to be clear, when I construct the sequence table using only filtered forward reads, do I need to merge dadaFs and derepFs lists? If yes, how do I do that?

Hi sachasuca! 
I have this same doubt, please, could you solve it?

**Comment by benjjneb** [comment]
@ShirleySteffany If using only forward reads, just omit the merging step. That step is for merging the forward and reverse reads, and irrelevant then in a single-end processing workflow.

**Comment by ShirleySteffany** [comment]
@benjjneb Thank you very much!
