### ISSUE TITLE
Compressing data or no?

### ISSUE THREAD

**Issue by vehamel** [benjjneb/dada2#1331]
Hi there!

I am sorry if this question as already been ask, I was not able to find it in the issues. Do we need to decompress or not our fastq.gz data for the dada2 pipeline? I was not sure about it, because before, I was using a pipeline already build up and I was using them compressed!

Thanks a lot!

**Comment by benjjneb** [comment]
The dada2 package can use gzipped fastq files the same as decompressed fastq files.
