### ISSUE TITLE
How to cope with significant differences in sequencing depth?

### ISSUE THREAD

**Issue by vfonti** [benjjneb/dada2#1332]
Hi everybody,
I need to process about 100 samples sequenced in two different sequencing runs by Illumina Novaseq for the V4-V5 region, in  pair ends. 
For reasons way far from my control, we ended up with a sequencing depth of 150-300 K reads in the first run and 0.5-6.5 M reads in the second one. I randomised samples to eventually avoid batch effects. However, I wasn't expecting such a huge difference and I am very concerned about potential batch effects. 
From a first inspection, reads quality is very high (in terms of q-score). So, I am thinking to subsample the second batch, also to decrease the computational demand beyond so many samples with so many reads.

I would much appreciate if someone could give me a hint about how to best procced in these conditions.
Cheers

**Comment by benjjneb** [comment]
That's not really that huge a difference, about a factor of 2-4, and with everything at >100k reads per sample.

But if this is a major concern, I concur with your idea of subsampling the second batch, or even all the samples to like 100k reads.

**Comment by JacobRPrice** [comment]
Are you concerned with the effects of the dada2 pipeline itself (fitting the error model, OTU/ASV picking and classification) or are you more concerned with having large discrepancies in total counts in the final OTU table? The first is a dada2/software question, while the other is centered on the challenges of analyzing compositional data.

**Comment by vfonti** [comment]
Thanks a lot both for your answers. 
On average the difference is about 10 times, but knowing that might not necessarily be a problem it's a relief.
I will try with subsampling. 

> Before downsampling or rarifying your data you may want to check this paper out.
> **Waste Not, Want Not: Why Rarefying Microbiome Data Is Inadmissible**
> https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003531

Thanks for the suggestion. I have read that paper years ago and I might be wrong, but I don't think that subsampling raw reads is the same as flattening the total count of ASVs after processing. Will think about this with more care.

**Comment by JacobRPrice** [comment]
@vfonti I'm sorry for not being precise with my language. Your memory is correct regarding the paper's main point! I'll edit my original comment for clarity.

**Comment by vfonti** [comment]
Hi @benjjneb and  @JacobRPrice,
Sorry to ask such a silly question but... after several trials I still haven't found a way to subsample my samples to a even reads count. I have tried with _shortread_ (bioconductor) but in the subsequent downstream analysis I have lost several sequences during merging, although I set the same seed for reverse and forward files. So, I have moved to qiime2 and used _subsample-paired_ function, which allow ONLY to subsample the same proportion for all samples (e.g. 30%), resulting in different reads count.
I have tried also with the command line but I only managed to pick the first 200k reads from each .fastq file, while I think a random sampling should be a better choice..

So, which tool would you use? How do I achieve an even number of reads keeping the same reads in the forward and reverse reads??

Thanks to anyone who would like to help!

**Comment by benjjneb** [comment]
You should be able to do it with ShortRead, but you'll have to keep the pairing between the forward and reverse fastqs by hand. Something like:

```
fqF <- readFastq("path/to/forward.fastq.gz")
fqR <- readFastq("path/to/reverse.fastq.gz")
fqF.sub <- "path/to/forward_subsampled.fastq.gz")
fqR.sub <- "path/to/reverse_subsampled.fastq.gz")

nreads <- length(fqF)
nsub <- 10000 # Or whatever subsampled depth you want to set
keep <- sample(nreads, nsub, replace=FALSE)

writeFastq(fqF[keep], fqF.sub, compress=TRUE, width=20000L)
writeFastq(fqR[keep], fqR.sub, compress=TRUE, width=20000L)
```

**Comment by vfonti** [comment]
Hi @benjjneb,
As I mentioned above, I am not going anywhere with ShortRead and I don't understand why. Where did you find this piece of coding for ShortRead? I searched a lot but, basically, I've only found bioconductor website documentations. I am running into some errors using your script. An example among others, I don't understand what the "width" parameters does. 

And, by the way, wouldn't this take the first n reads instead of doing a random sub-sampling?? 


-----
# Additional info:
For my first (unsuccessful) trials I followed the [vignette](http://127.0.0.1:31547/library/ShortRead/doc/Overview.pdf) and did something like this:

`sampler <- FastqSampler('E-MTAB-1147/fastq/ERR127302_1.fastq.gz', 20000)
set.seed(123); ERR127302_1 <- yield(sampler)
sampler <- FastqSampler('E-MTAB-1147/fastq/ERR127302_2.fastq.gz', 20000)
set.seed(123); ERR127302_2 <- yield(sampler)`

which ended up with unmatched forward and reverse file.

**Comment by benjjneb** [comment]
The code should work, or at least the un-typoed code below. I just ran it successfully on my machine, and it keeps the forward and reverse read files in the same order after subsampling:

```
library(ShortRead)
fqF <- readFastq("path/to/forward.fastq.gz")
fqR <- readFastq("path/to/reverse.fastq.gz")
fqF.sub <- "path/to/forward_subsampled.fastq.gz"
fqR.sub <- "path/to/reverse_subsampled.fastq.gz"
# Delete pre-existing files with the output path if they already exist
if(file.exists(fqF.sub)) file.remove(fqF.sub)
if(file.exists(fqR.sub)) file.remove(fqR.sub)

nreads <- length(fqF)
nsub <- 1000 # Or whatever subsampled depth you want to set
if(nsub > nreads) nsub <- nreads # Not enough reads to subsample to nsub depth
## You may want to change the above logic, for example to skip samples w/o enough reads
keep <- sample(nreads, nsub, replace=FALSE) # Defines the indices of the reads to keep

writeFastq(fqF[keep], fqF.sub, compress=TRUE)
writeFastq(fqR[keep], fqR.sub, compress=TRUE)
```

The `width` argument was unnecessary before.

**Comment by vfonti** [comment]
Nope... but the good news is that I figured out why I keep getting an error or a useless file. Because I am working with multiple samples, while readFastq and writeFastaq read and create a single file!! Sorry, I should have specified this!

**Comment by benjjneb** [comment]
So you'll just want to put the previous code inside a `for` loop in R, that loops through the samples and does the subsampling on each one.

**Comment by vfonti** [comment]
Hi there, 
I am sorry to ask help for something like this... but I have tried my best and kept failing on this. 
This is the code I am trying to use. It works very well on the first pair of fastq files but when I put it in a loop it does not work anymore:

```
setwd("path/to/mywd")

path <- path/to/mywd"
fqF <- list()
fqR <- list()
listFw <- dir(path = path, pattern = "*_R1_001.fastq.gz")      # It's weird: if I dont set a wd it does  not find my files...
listRev <- dir(path = path, pattern = "*_R2_001.fastq.gz")

for (i in 1:length(listFw)) {
  fqF[[i]] <- readFastq(listFw[i])
  fqR[[i]] <- readFastq(listRev[i])
  
  x= strsplit(basename(listFw[i]), "_R1")
  y= strsplit(basename(listRev[i]), "_R2")
   
  fqF.sub <- file.path ("path/to/subsampled.fastq.gz",  pattern = paste0(x[[1]][[1]], "R1_SUB_001.fastq.gz"))
  fqR.sub <- file.path (path/to/subsampled.fastq.gz"",  pattern = paste0(x[[1]][[1]], "R2_SUB_001.fastq.gz"))
  
  if(file.exists(fqF.sub)) file.remove(fqF.sub)
  if(file.exists(fqR.sub)) file.remove(fqR.sub)
  
  nreads <- length(fqF)
  nsub <- 1000 
  if(nsub > nreads) nsub <- nreads 
  keep <- sample(nreads, nsub, replace=FALSE) 
  
  writeFastq(fqF[keep], fqF.sub, compress=TRUE, mode = "a")
  writeFastq(fqR[keep], fqR.sub, compress=TRUE, mode = "a")

}
```
And that's the error I get whatever I try:
```
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘writeFastq’ for signature ‘"list", "character"’
```

I hope someone can help... This is driving me crazy.

**Comment by vfonti** [comment]
Hi there!
Since I struggled a lot in creating a loop that would actually work properly, I post here my piece of code, just in case somebody would need it. @benjjneb Thanks a lot for helping me.

```
setwd("path/to/mywd")
path <- path/to/mywd"
fqF <- list()
fqR <- list()
listFw <- dir(path = path, pattern = "*_R1_001.fastq.gz") 
listRev <- dir(path = path, pattern = "*_R2_001.fastq.gz")

for (i in 1:length(listFw)) {
  fqF[[i]] <- readFastq(listFw[[i]])
  fqR[[i]] <- readFastq(listRev[[i]])
  
  x= strsplit(basename(listFw[i]), "_R1")
  y= strsplit(basename(listRev[i]), "_R2")
   
  fqF.sub <- file.path ("path/to/subsampled.fastq.gz",  pattern = paste0(x[[1]][[1]], "R1_SUB_001.fastq.gz"))
  fqR.sub <- file.path (path/to/subsampled.fastq.gz"",  pattern = paste0(x[[1]][[1]], "R2_SUB_001.fastq.gz"))
  if(file.exists(fqF.sub)) file.remove(fqF.sub)
  if(file.exists(fqR.sub)) file.remove(fqR.sub)
  
  nreads <- length(fqF[[i]])
  nsub <- 100000                                                             # subsapling depth
  if(nsub > nreads) nsub <- nreads                                  # This is in case of not enough reads to subsample to nsub depth
  keep <- sample(nreads, nsub, replace=FALSE)                              
  
  writeFastq(fqF[[i]][keep], fqF.sub, compress=TRUE)
  writeFastq(fqR[[i]][keep], fqR.sub, compress=TRUE)

}

```
