### ISSUE TITLE
DECIPHER IdTaxa uses max 1 processor

### ISSUE THREAD

**Issue by csmiguel** [benjjneb/dada2#1333]
For an unknown reason I can not get DECIPHER IdTaxa to use more than 1 processor in my 4 core machine, at:
```
ids <- DECIPHER::IdTaxa(dna,
                        trainingSet,
                        processors = NULL,
                        strand = "top",
                        verbose = T)
```

 > sessionInfo()
> R version 4.0.3 (2020-10-10)
> Platform: x86_64-apple-darwin17.0 (64-bit)
> Running under: macOS Mojave 10.14.6
> 
> Matrix products: default
> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] es_ES.UTF-8/es_ES.UTF-8/es_ES.UTF-8/C/es_ES.UTF-8/es_ES.UTF-8
> 
> attached base packages:
> [1] stats4    parallel  stats     graphics  grDevices utils     datasets 
> [8] methods   base     
> 
> other attached packages:
>  [1] DECIPHER_2.18.1     RSQLite_2.2.7       dplyr_1.0.5        
>  [4] dada2_1.18.0        Rcpp_1.0.6          Biostrings_2.58.0  
>  [7] XVector_0.30.0      IRanges_2.24.1      S4Vectors_0.28.1   
> [10] BiocGenerics_0.36.1

**Comment by benjjneb** [comment]
I'm not sure whether `IdTaxa` is multithreaded or not, as it is part of a different package.

@digitalwright Any thoughts?

**Comment by digitalwright** [comment]
`IdTaxa` is multithreaded using OpenMP. Unfortunately Apple does not officially support OpenMP with the version of the complier (clang) that they provide. The instructions to build R packages with OpenMP code are [here](https://mac.r-project.org/openmp/). The process is non-trivial, but I was able to get it to work on my machine.

**Comment by csmiguel** [comment]
Thanks @digitalwright and @benjjneb
I used a sub-optimal workaround with `parallel`. It works but RAM memory usage scales linearly with cores created.

```
library(parallel)
library(dada2)
library(dplyr)

dna <- Biostrings::DNAStringSet(dada2::getSequences(seqtabNoC)) 

#function to split dna object into ~similar size chunks for parallel processing
split_vector <- function(for_n_clusters = NULL, query_seqs = NULL) {
  h <-
    rep(letters[1:for_n_clusters],
      length.out = length(query_seqs),
      each = ceiling(length(query_seqs) / for_n_clusters))[1:length(query_seqs)]
  as.factor(h)
}
####
#load training database
db_silva <- "SILVA_SSU_r138_2019.RData"
dest_path <- "data/raw"
load(file.path(dest_path, db_silva)) #load SILVA trainingSet

#number of cores to use
numcl <- detectCores() - 2

#create clusters
cl <- makeCluster(numcl,
                  setup_strategy = "sequential") #https://github.com/rstudio/rstudio/issues/6692
#add desired environment variables to cl
clusterExport(cl, c("dna", "trainingSet"))

#lists with positions of dna seqs from the object dna to ID in each cluster
hh <-
  seq_along(dna) %>%
  split(f = split_vector(for_n_clusters = numcl, query_seqs = dna))

# run IdTaxa in parallel
results <-
  parLapply(cl, hh, function(x) {
    DECIPHER::IdTaxa(dna[x],
                            trainingSet,
                            processors = 1,
                            strand = "top",
                            verbose = T)
  }) %>% do.call(what = c) %>% setNames(NULL)
stopCluster(cl)

```

**Comment by jorondo1** [comment]
Here's what worked for me (mac M3 sonoma)
```
cd ~/Downloads
curl -O https://mac.r-project.org/openmp/openmp-16.0.4-darwin20-Release.tar.gz
sudo tar fvxz openmp-16.0.4-darwin20-Release.tar.gz -C /

mkdir -p ~/.R
nano ~/.R/Makevars
```
add these lines to the Makevars file: 
```
CPPFLAGS += -Xclang -fopenmp
LDFLAGS += -lomp
```

uninstall DECIPHER, restart my R session, then reinstall DECIPHER.
