### ISSUE TITLE
Escherichia/Shigella species in assignSpecies results

### ISSUE THREAD

**Issue by mammerlin** [benjjneb/dada2#1335]
Hi benjjneb,
I was noticed the assigntaxonomy function does not work so well for species-level.
I tried to use assignSpecies to improve the results.

The results of assignSpecies (with allowMultiple = T) show many the genus-species name like "Escherichia/Shigella coli" .
I use BLAST to check the similarity list below,
![Image 107](https://user-images.githubusercontent.com/35716885/117308632-5185c680-aeb4-11eb-8812-906a9115f490.png)
 
There are two problem. 
First, there is only one E.coli exactly match to ASV_17, but the result report Escherichia/Shigella coli.
Second, there is no sequence exactly match to ASV_19, but the result report Escherichia/Shigella coli as well.

In  assignSpecies source code, there is a subfunction called "mapHits".
The mapHits will turn "Escherichia" or "Shigella" into "Escherichia/Shigella".
Could you explain more detail about this?
Thanks a lot.

`# Helper function for assignSpecies
mapHits <- function(x, refs, keep, sep="/") {
  hits <- refs[x]
  hits[grepl("Escherichia", hits, fixed=TRUE) | grepl("Shigella", hits, fixed=TRUE)] <- "Escherichia/Shigella"
  if(length(unique(hits))<=keep) {
    rval <- do.call(paste, c(as.list(sort(unique(hits))), sep=sep))
  } else { rval <- NA_character_ }
  if(length(rval)==0) rval <- NA_character_
  rval
}`

**Comment by benjjneb** [comment]
> In assignSpecies source code, there is a subfunction called "mapHits".
> The mapHits will turn "Escherichia" or "Shigella" into "Escherichia/Shigella".
> Could you explain more detail about this?

Sure. Esherichia and Shigella are not distinct genera, they are mixed together in a phylogenetic tree. Given that, it makes more sense to simply define a combined genus as "Escherichia/Shigella" and allow finer differentiation to be made at the species level where it is appropriate.

The Silva project takes the same approach: https://www.arb-silva.de/browser/ssu-138/AM184304

![image](https://user-images.githubusercontent.com/5797204/117326168-6421e080-ae5f-11eb-8769-9e9aa0e2f695.png)

**Comment by mammerlin** [comment]
Thanks for the explanation.
I understand the genus of Esherichia and Shigella have highly similarity. 
Combined "Escherichia/Shigella" is great in assignTaxonmy function. 
However, assignSpecies assign species-level by exact matching. Combined "Escherichia/Shigella" might not so necessary.
It would be helpful when using customized reference to assign to species- or strain-level.

**Comment by salix-d** [comment]
> Second, there is no sequence exactly match to ASV_19, but the result report Escherichia/Shigella coli as well.

That's only because blast and assignSpecies() define 'exact match' differently.
If you look at the length coloumn in your ASV_19 results, you'll see that it's one nucleotide longer than your qlen, hence not a 100% pident (ASV_17 had a length of 1464 matching the qlen).
assignSpecies() does the equivalent of 'grep' in the reference database, so if the sequence queried is only half the sequence of the ref db, if it greps it, it counts as a match.
