### ISSUE TITLE
Error in validObject(.Object) :    invalid class SRFilterResult object: superclass "Mnumeric" not defined in the environment of the object's class

### ISSUE THREAD

**Issue by Skastalli** [benjjneb/dada2#1338]
Hello,
I recently started using DADA2 pipeline, to analyze fastqs from Illumina run. But as soon as I get to the filterAndTrim function, it shows me an error?
can you help me?

This is my command : 
``` library(dada2)
library("ShortRead")
library(Matrix)
filterAndTrim(snakemake@input[[1]],snakemake@output[[1]], snakemake@input[[2]], snakemake@output[[2]], maxN=0, rm.phix=TRUE, compress=TRUE, verbose = TRUE)
``` 
I use sankemake to run my pipeline.

**Comment by yinglu1** [comment]
Hi,
I am running into the same issue while following dada2 tutorial (https://benjjneb.github.io/dada2/tutorial.html).  Here is the error message:  

> out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
+                      maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
+                      compress=TRUE, multithread=FALSE) # On Windows set multithread=FALSE
Error in validObject(.Object) : 
  invalid class “SRFilterResult” object: superclass "Mnumeric" not defined in the environment of the object's class

My R studio is Version 1.2.1335 on window's 10. DADA2 v 1.18. Both shortRead and Matirx are installed. 

I looked at the open issue #212 link from bashihamidi's post but can't find relevant method. 

Please help!

Many thanks in advance

**Comment by laxvid** [comment]
Same issue:

> filterAndTrim(fwd=file.path(pathF, fastqFs), filt=file.path(filtpathF, fastqFs),
+               rev=file.path(pathR, fastqRs), filt.rev=file.path(filtpathR, fastqRs),
+               maxEE=2, maxN=0, rm.phix=TRUE,
+               compress=TRUE, verbose=TRUE, multithread=FALSE)
Error in validObject(.Object) : 
  invalid class “SRFilterResult” object: superclass "Mnumeric" not defined in the environment of the object's class
> session_info()
- Session info ---------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.1 (2020-06-06)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/New_York            
 date     2021-05-13                  

- Packages -------------------------------------------------------------------------------------------------------------------
 ! package              * version  date       lib source        
   assertthat             0.2.1    2019-03-21 [1] CRAN (R 4.0.0)
   Biobase              * 2.48.0   2020-04-27 [1] Bioconductor  
   BiocGenerics         * 0.34.0   2020-04-27 [1] Bioconductor  
 V BiocManager            1.30.10  2021-05-11 [1] CRAN (R 4.0.1)
   BiocParallel         * 1.22.0   2020-04-27 [1] Bioconductor  
   Biostrings           * 2.56.0   2020-04-27 [1] Bioconductor  
   bitops                 1.0-7    2021-04-24 [1] CRAN (R 4.0.5)
   cachem                 1.0.3    2021-02-04 [1] CRAN (R 4.0.1)
   callr                  3.7.0    2021-04-20 [1] CRAN (R 4.0.5)
   cli                    2.5.0    2021-04-26 [1] CRAN (R 4.0.5)
   colorspace             2.0-1    2021-05-04 [1] CRAN (R 4.0.5)
 V crayon                 1.4.0    2021-02-08 [1] CRAN (R 4.0.5)
   curl                   4.3      2019-12-02 [1] CRAN (R 4.0.0)
   dada2                * 1.16.0   2020-04-27 [1] Bioconductor  
   DBI                    1.1.1    2021-01-15 [1] CRAN (R 4.0.3)
   DelayedArray         * 0.14.1   2020-07-15 [1] Bioconductor  
   desc                   1.3.0    2021-03-05 [1] CRAN (R 4.0.5)
   devtools             * 2.4.1    2021-05-05 [1] CRAN (R 4.0.5)
   digest                 0.6.27   2020-10-24 [1] CRAN (R 4.0.3)
   dplyr                  1.0.6    2021-05-05 [1] CRAN (R 4.0.5)
   ellipsis               0.3.1    2020-05-15 [1] CRAN (R 4.0.0)
   evaluate               0.14     2019-05-28 [1] CRAN (R 4.0.0)
   fansi                  0.4.2    2021-01-15 [1] CRAN (R 4.0.5)
   fastmap                1.1.0    2021-01-25 [1] CRAN (R 4.0.3)
   fs                     1.5.0    2020-07-31 [1] CRAN (R 4.0.2)
   generics               0.1.0    2020-10-31 [1] CRAN (R 4.0.3)
   GenomeInfoDb         * 1.24.2   2020-06-15 [1] Bioconductor  
   GenomeInfoDbData       1.2.3    2020-07-14 [1] Bioconductor  
   GenomicAlignments    * 1.24.0   2020-04-27 [1] Bioconductor  
   GenomicRanges        * 1.40.0   2020-04-27 [1] Bioconductor  
   ggplot2                3.3.3    2020-12-30 [1] CRAN (R 4.0.5)
   glue                   1.4.2    2020-08-27 [1] CRAN (R 4.0.3)
   gtable                 0.3.0    2019-03-25 [1] CRAN (R 4.0.0)
   htmltools              0.5.1.1  2021-01-22 [1] CRAN (R 4.0.5)
   hwriter                1.3.2    2014-09-10 [1] CRAN (R 4.0.0)
   IRanges              * 2.22.2   2020-05-21 [1] Bioconductor  
   jpeg                   0.1-8.1  2019-10-24 [1] CRAN (R 4.0.0)
   knitr                  1.33     2021-04-24 [1] CRAN (R 4.0.5)
   lattice                0.20-44  2021-05-02 [1] CRAN (R 4.0.5)
   latticeExtra           0.6-29   2019-12-19 [1] CRAN (R 4.0.2)
   lifecycle              1.0.0    2021-02-15 [1] CRAN (R 4.0.5)
   magrittr               2.0.1    2020-11-17 [1] CRAN (R 4.0.3)
   Matrix               * 1.3-3    2021-05-04 [1] CRAN (R 4.0.1)
   matrixStats          * 0.58.0   2021-01-29 [1] CRAN (R 4.0.3)
   memoise                2.0.0    2021-01-26 [1] CRAN (R 4.0.3)
   munsell                0.5.0    2018-06-12 [1] CRAN (R 4.0.0)
   pillar                 1.6.0    2021-04-13 [1] CRAN (R 4.0.5)
   pkgbuild               1.2.0    2020-12-15 [1] CRAN (R 4.0.3)
   pkgconfig              2.0.3    2019-09-22 [1] CRAN (R 4.0.0)
   pkgload                1.2.1    2021-04-06 [1] CRAN (R 4.0.5)
   plyr                   1.8.6    2020-03-03 [1] CRAN (R 4.0.0)
   png                    0.1-7    2013-12-03 [1] CRAN (R 4.0.0)
   prettyunits            1.1.1    2020-01-24 [1] CRAN (R 4.0.0)
   processx               3.5.2    2021-04-30 [1] CRAN (R 4.0.5)
   ps                     1.5.0    2020-12-05 [1] CRAN (R 4.0.3)
   purrr                  0.3.4    2020-04-17 [1] CRAN (R 4.0.0)
   R6                     2.5.0    2020-10-28 [1] CRAN (R 4.0.3)
   RColorBrewer           1.1-2    2014-12-07 [1] CRAN (R 4.0.0)
   Rcpp                 * 1.0.6    2021-01-15 [1] CRAN (R 4.0.5)
 D RcppParallel           5.1.4    2021-05-04 [1] CRAN (R 4.0.5)
   RCurl                  1.98-1.3 2021-03-16 [1] CRAN (R 4.0.5)
   remotes                2.3.0    2021-04-01 [1] CRAN (R 4.0.5)
   reshape2               1.4.4    2020-04-09 [1] CRAN (R 4.0.0)
   rlang                  0.4.11   2021-04-30 [1] CRAN (R 4.0.5)
   rmarkdown              2.8      2021-05-07 [1] CRAN (R 4.0.5)
   rprojroot              2.0.2    2020-11-15 [1] CRAN (R 4.0.3)
   Rsamtools            * 2.4.0    2020-04-27 [1] Bioconductor  
   rstudioapi             0.13     2020-11-12 [1] CRAN (R 4.0.3)
   S4Vectors            * 0.26.1   2020-05-16 [1] Bioconductor  
   scales                 1.1.1    2020-05-11 [1] CRAN (R 4.0.0)
   sessioninfo            1.1.1    2018-11-05 [1] CRAN (R 4.0.0)
   ShortRead            * 1.46.0   2020-04-27 [1] Bioconductor  
   stringi                1.5.3    2020-09-09 [1] CRAN (R 4.0.3)
   stringr                1.4.0    2019-02-10 [1] CRAN (R 4.0.0)
   SummarizedExperiment * 1.18.2   2020-07-09 [1] Bioconductor  
   testthat               3.0.2    2021-02-14 [1] CRAN (R 4.0.5)
   tibble                 3.1.1    2021-04-18 [1] CRAN (R 4.0.5)
   tidyselect             1.1.1    2021-04-30 [1] CRAN (R 4.0.5)
   usethis              * 2.0.1    2021-02-10 [1] CRAN (R 4.0.5)
   utf8                   1.2.1    2021-03-12 [1] CRAN (R 4.0.5)
   vctrs                  0.3.8    2021-04-29 [1] CRAN (R 4.0.5)
 V withr                  2.4.1    2021-04-18 [1] CRAN (R 4.0.5)
   xfun                   0.22     2021-03-11 [1] CRAN (R 4.0.5)
   XVector              * 0.28.0   2020-04-27 [1] Bioconductor  
   yaml                   2.2.1    2020-02-01 [1] CRAN (R 4.0.0)
   zlibbioc               1.34.0   2020-04-27 [1] Bioconductor  

[1] C:/Program Files/R/R-4.0.1/library

 V -- Loaded and on-disk version mismatch.
 D -- DLL MD5 mismatch, broken installation.

**Comment by bashirhamidi** [comment]
@yinglu1 @laxvid 
Please note that this is not a dada2 issue but rather a dependency package `Matrix` v 1.3.3. Here are the steps to resolving the issue https://github.com/benjjneb/dada2/issues/212#issuecomment-836757295

**Comment by laxvid** [comment]
Thanks. Trying it out now. 
Lax
