### ISSUE TITLE
assign feature ids?

### ISSUE THREAD

**Issue by afgovindarajan** [benjjneb/dada2#1339]
Is there a way to assign feature id's that are md5sums (as when dada2 is run in QIIME2)? When I bring my ASVs from dada2 into QIIME2, the feature id's are just the sequences themselves. Thanks.

**Comment by benjjneb** [comment]
Sure, `md5sum(...)`: https://www.rdocumentation.org/packages/tools/versions/3.6.2/topics/md5sum
