### ISSUE TITLE
Constructing sequence table with forward reads only

### ISSUE THREAD

**Issue by sachasuca** [benjjneb/dada2#134]
Do I need to merge dadaFs and derepFs lists before making the sequence table? If so, what is the best way to do this?

**Comment by benjjneb** [comment]
Our "Big Data" workflow uses just forward reads, so might be useful to answer some of these questions: http://benjjneb.github.io/dada2/bigdata.html

You won't perform any merge step if using just forward reads. You'll simply make the sequence table from the `dadaFs` object:

```S
seqtab <- makeSequenceTable(dadaFs)
```
