### ISSUE TITLE
error when using filterAndTrim

### ISSUE THREAD

**Issue by lauraewing** [benjjneb/dada2#1340]
I get the following error when using the filterAndTrim function towards the beginning of the tutorial:
Error in validObject(.Object) : 
  invalid class “SRFilterResult” object: superclass "Mnumeric" not defined in the environment of the object's class
How can I fix this?

**Comment by benjjneb** [comment]
See https://github.com/benjjneb/dada2/issues/212#issuecomment-836757295 for a workaround, and https://github.com/benjjneb/dada2/issues/212#issuecomment-841703077 for the latest fixed version.

This should be resolved in the current devel version and in the next BioC release (a week or two out).

**Comment by icotto25** [comment]
I already installed the last version of dada2 (V1.19.2) and I am getting the same error.

**Comment by benjjneb** [comment]
@icotto25 Can you double-check by restart R to get a clean new environment. Then load dada2 and check the `packageVersion("dada2")`. Does the error still arise?

**Comment by icotto25** [comment]
@benjjneb thanks for the suggestion. It worked, I did not get an error now.

**Comment by cpavloud** [comment]
Thank you. 
The isssue is now solved.
