### ISSUE TITLE
mergeSequenceTables(seqtab, seqtab2): Some sequence tables found invalid

### ISSUE THREAD

**Issue by FrancescoMontemagno94** [benjjneb/dada2#1344]
I'm trying to do dada2 on 172 samples, and all of them are paired and have only one read. I get a warning message when I try to assign the sample.name after the dereplication: 
**names(derepFR2) <- sample.names2
Warning message in `names<-`(`*tmp*`, value = "SRR5828730"):
“derep-class objects cannot be renamed.”** 
And when I try to do the final merge of the seqtables I get this error:
**seqtab <- mergeSequenceTables(seqtab, seqtab2)
Warning message in FUN(X[[i]], ...):
“Row (sample) names are missing.”
Warning message in FUN(X[[i]], ...):
“Row (sample) names are missing.”
Error in mergeSequenceTables(seqtab, seqtab2): Some sequence tables found invalid
Traceback:

1. mergeSequenceTables(seqtab, seqtab2)
2. stop("Some sequence tables found invalid", errorMessage)**
From what I understand the problem lies in the fact that I have only one read and I cannot assign the sample names to the dereplication, but then this produces me seqtables without rownames. How can I solve?
Thank for your help in advance

**Comment by benjjneb** [comment]
> all of them are paired and have only one read

Can you clarify? What does "only have one read mean"? There is only one read in each sample?

**Comment by FrancescoMontemagno94** [comment]
yes, every sample has only one read.

**Comment by benjjneb** [comment]
> yes, every sample has only one read.

You shouldn't be using DADA2 at all then, it's not intended for this kind of use case.
