### ISSUE TITLE
removeBimeraDenovo command in dada2 (chimera removal step)

### ISSUE THREAD

**Issue by DhebbieF** [benjjneb/dada2#1345]
Hello,
Can you please help?
The chimera detection step is removing  a a large chunk of my reads.
I'm working with 20 samples, and have their V1-V3 regions amplified and sequenced.
These regions were sequenced on a hiseq 2500 platform and primers 8F and 518R were used.

When my sequences were sent back, they were:
 1. NOT of equal length  (fastQC showed different sequence lengths with different ranges  such as 134 -292)
2.They had all primers and adapters removed (I also confirmed this using Trimmomatic).

I ran the removeBimeraDenovo command in dada2: 
> Seqtab.nochim <- removeBimeraDenovo(Seqtab, method = "consensus", multithread=TRUE, verbose = TRUE)

>sum(Seqtab.nochim/sum(Seqtab))  
0.6301443

I also tracked each step to see how many reads made it in each step of the pipeline:
                          input      filtered    denoisedF    denoisedR          merged                nonchim.
C1-Soil-dry      34473    31124      30487          30510                  23340                  15139
C1-Soil-wet-    34887    30217     29686           29731                 19223                    15567
C1-Water-dry    34629    30608    29845        29922                  20241                  11647
C1-Water-wet-   34729    29316    28783         28788                 17653                   10944
MPC1-Soil-dry   34611    30763     30310          30409                 25507                 13092
MPC1-Soil-wet   34404    30830     30132        30264                  23155                13346
MPC1-Water-dry  34723    30451     29683     29623                   20986                 14518
MPC1-Water-wet  34786    29904     29188     29066                 21456                   13032
MPW-1-Soil-wet  34956    29767     29496     29523                  4724                     4015
MPW1-Soil-dry   34626    29579     29237     29355                    6463                    4136
MPW1-water-dry  34615    30492     30123     30154                   17907                   12561
MPW1-Water-wet  34725    29182     28580     28600                  21757                  12502
SC1-Soil-dry        34759    30202       29412     29610                   17312                   10107
SC1-Soil-wet        34447    30562     29970     30154                     13272                 8592
SC1-Water-dry   34830    30372     29563     29637                       20746                12638
SC1-Water-wet   34785    30252     29578     29564                      22942                 12429
SW1-Soil--wet   35039    28984     28548     28671                        10703                 6992
SW1-Soil-dry       34495    30771     30423     30433                      27727               22453
SW1-water--wet- 34893    29929     29477     29543                      17272               9133
SW1-Water-dry   34504    30705     30239     30234                      17661                 10340 

From the above tracking, I am beginning to wonder if this isn't too much of a loss, as some reads barely made it out.

Also, my expected length of V1 -V3 from literatures is approximately 490, but when I inspected the distribution of sequence length I saw so many short lengths that made me wonder if I'm not missing something vital.

I ran the following for the distribution of sequence length after merging (before I ran the chimera removal step) 
   > table (nchar(getSequences(Seqtab))).   and got the following :

268  282  293  296  300  302  303  304  326  338  363  365  398  404  413  423 
   1      1        1       1       1        1      1       2        1     1        2     2       1        5    1    1 
 431  433  434  435  437  438  439  440  441  442  443  444  445  447  448  449 
  61  271    1         60    3      29      2      7         5    1       6        2     24      43    3    5 
 450  451  452  453  454  455  456  457   458   459  460    461  462  463  464  465 
  64   21     53    172    1        27   55     928   698  1323  256  138  137  157     90  413 
 466  467  468  469  470  471  472  473  474  475  476  477  478  479  480  481 
  18  328    47       27    73   24    198   57    21    92     101   464  118  950 1268   88 
 482  483  484  485  486  487  488 
3329  508 5775 2707  559  557 2194 

After running the chimera removal step, I inspected the distribution of sequence length again and got the following:

>table (nchar(getSequences(Seqtab.nochim)))
268 282 293 296 302 304 326 338 404 413 431 433 434 435 438 441 442 444 450 451 452 
  1     1      1       1      1       2     1       1      5     1     31     52   1      5     1       2    1          1  12    3      14 
453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468 469 470 471 472 473 
  6      1     3      14    5    35    12     9     4     20   6       18    91   3      76   9      14     11   8     11     23 
474 475 476 477 478 479 480 481 482 483 484 485 486 487 488 
 10      8   2      11     22  63.  116  12.  158  15    392 269  49 127 345 

Your expert advise would be highly welcome, as I am not sure what to think of this output, is it that the variable length supplied by the sequencing facility is the reason why I see so much variable lengths?  or probably there wasn't sufficient overlap? or is this kind of output expected for this variable region?

I used the following parameter to filter and trim the reads, after plotting a quality control plots for all.

 > OUT <- filterAndTrim(dataF, filt.dataF, dataR, filt.dataR, truncLen=c(260,240),
                     maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, multithread=TRUE)

I look forward to reading from you,
Apologies for the very lengthy message,
I was trying to be as explicit as possible.

Many thanks,
'Debbie.

**Comment by benjjneb** [comment]
If possible, I would recommend asking the sequencing provider for the sequencing reads as they came off the sequencer, i.e. without their trimming and QC.

It's usually easier to just do the trimming/QC yourself than it is to try to understand and account for whatever the sequencing provider did.

**Comment by DhebbieF** [comment]
Many thanks,
I would request for this.

Debbie.
