### ISSUE TITLE
"merging" 2 taxa tables

### ISSUE THREAD

**Issue by eaherder** [benjjneb/dada2#1346]
Hi there,

I have been running into an issue with a dataset I am working on but that was processed by someone else so I only have access to certain files. Because the phyloseq object was made many years ago using a reference database that typically doesn't work as well for our data, I was trying to re-run the assigntaxonomy part to the .fna file containing all of the sequences. This is a giant file so, even using a cluster, I am getting errors about negative length vectors when I try to process the full file. If I just use the first 50 rows, or even half of the file, it is able to run (but not the addspecies because apparently there are N's in this file). I am wondering if it's possible to split the file into two .fna files, one with the first half of the rows and the second with the second half of the rows, run this command on each of them, and then merge the two taxa files together? Is this something that can be done? Thanks for any help!!

**Comment by benjjneb** [comment]
Yep. `assignTaxonomy` operates on each input sequence completely independently, so you can break it into chunks however you like.

You would put the individual taxonomy tables back together at the end by `rbind`. For example, `tax.all <- rbind(tax.1, tax.2, tax.3)`

**Comment by eaherder** [comment]
Thank you!
