### ISSUE TITLE
Memory allocation failed

### ISSUE THREAD

**Issue by Xinming9606** [benjjneb/dada2#1347]
Hi,
I've met same problems of memory allocation failed. I am using exactly the same ITS tutorial datasets and the recommended UNITE database to do the fungal taxonmic assignment as practicing.

> taxa <- assignTaxonomy(seqtab.nochim, unite.ref, multithread = TRUE, tryRC = TRUE)
>Error in C_assign_taxonomy2(seqs, rc(seqs), refs, ref.to.genus, tax.mat.int,  : 
  Memory allocation failed.

I also tried multithread = FALSE, and run it in our university cluster which should have enough memory.

I do not have another PC , is there anything I can do?

**Comment by benjjneb** [comment]
How much memory do you have available on your PC? How about on the University cluster?

If you have at least 16GB available, it should be able to load and use the UNITE reference. On the cluster, sometimes you need to specify how much memory you want a job to have or it can get assigned a small default amount of memory.

**Comment by Xinming9606** [comment]
> If you have at least 16GB available, it should be able to load and use the UNITE reference. On the cluster, sometimes you need to specify how much memory you want a job to have or it can get assigned a small default amount of memory.

 8.9 GB available on my own PC. For the University cluster is around 16GB I have in total. I will ask them to assign more memory to my account.
Thanks for your reply!!
