### ISSUE TITLE
Sequence Extraction

### ISSUE THREAD

**Issue by markdjohnson** [benjjneb/dada2#1351]
Hello Ben, 

A few weeks ago i asked you how to extract unique sequences from the DADA2 program that had been aligned, chimera removed, trimmed etc. In the end, I ended up removing 621 unique sequences that were taken from my data. A question I had for you was if those 621 sequences were ASVs that were extracted, I am almost positive they were but I just wanted to make sure.

https://github.com/benjjneb/dada2/issues/1321 here is the link to my previous question.

Thank you so much,
Mark

**Comment by benjjneb** [comment]
Yes, if you are extracing the unique sequences after denoising, then you are looking at the denoised ASVs.

**Comment by markdjohnson** [comment]
Thank you very much! I had another question... I had gotten the code to work and had finally exported all of my ASVs. However after a few weeks I went back today and now my code is not running and functions are not working. For example I cannot plotQualityProfile or other functions like that, yet this had all been working about a month ago. The word file I attached has the screenshot of my code with the console on the side (the bracket I added shows the lines of code I used to get the error message in the console). Any help you could provide would be greatly appreciated.

[R issue.docx](https://github.com/benjjneb/dada2/files/6611592/R.issue.docx)

**Comment by markdjohnson** [comment]
Thank you very much! I did have another question(the setbacks can't seem to stop). I had code that worked and was able to run dada2 and extract my filtered asvs. However, I went back to the code today (about a month later) and now none of the commands are working. I am wondering if it now out of date in the month since I visited this code but I am not sure. I pasted my code below, do you have any insight into why my code suddenly stopped working?

Thank you very much for you help,
Mark
My own data trnL


if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("dada2", version = "3.12 #this is to include a single file discrepancy then downloaded DADA2
library("devtools")
devtools::install_github("benjjneb/dada2")
library(dada2); packageVersion("dada2")

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("ShortRead")

library("ShortRead")


if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("BiocGenerics")
library("BiocGenerics")

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.12")


library(ShortRead)

**Comment by markdjohnson** [comment]
Hi Ben, 

So I ended up just trying to use...
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install()
library("dada2")

And this got me passed where I had been stuck before but as I continued down the workflow I got a new message when i attempted to run the following command...

standard filting paramters the 240 and 210 are determined looking at visualizaztin
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,210),
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=TRUE) # On Windows set multithread=FALSE

I received this error message...

Multithreading has been DISABLED, as forking is not supported on .Platform$OS.type 'windows'
Error in validObject(.Object) : 
  invalid class “SRFilterResult” object: superclass "Mnumeric" not defined in the environment of the object's class

When I attempt to run it with multithread=False the error message doesn't show the first line but keeps the second two. 


Do you have any insight into what this error is referring to or how to correct it?
Thank you,
Mark

**Comment by benjjneb** [comment]
Closing in favor of the new issue #1362
