### ISSUE TITLE
chimera removal

### ISSUE THREAD

**Issue by ARBramucci** [benjjneb/dada2#1353]
Hi Benjamin and collaborators,
I have a question about how to correctly merge multiple runs of plates. I think I have figured out my initial problem, which was that during chimera removal different chimeras were removed from different plates leading to a weird batch effect where the same ASVs were not found in different batches (even after collapse no mismatch on the full seqtab).

Background: my project is marine samples, I have sequenced them using V1_V3 primers (without heterogeneity spacers) amplicon length ~490bp
1) 
>filtN N=4 (just to make sure I am not losing samples here)
>cutadapt primer removal
> filter and trim step (truncLeng 270, 250 maxEE 4,6) (_I have increased this because my reverse reads are a little poorer quality_)
>merge and chimera step
>combining chimera free seqtabs into one seqtab and running collapse no mismatch on them (which we did because is greatly speeds up the collapse no mismatch step)
^^However I had a very weird result when I ran my plates this way, it looked like each ASV was only present in one sample never found in multiple samples (I doing the chimera step here caused this)

2) I re-ran my dataset as follows:
   >filter and trim step
   >mergers
  >save seqtab
  >combine 3 seqtabs
  >run chimera removal on combined seqtab -> chim2.seqtab
  >run collapse no mismatch on chim2.seqtab
This greatly improved my results

3) Given that my project is critically looking for overlap between samples run across 3 plates, should I also do the extra step suggested by a previous user: (issue 1017); running dada2 as in (2) and then use the whole ASV list as a list of priors to ensure potential overlap between plates isn't lost during dada step 
https://github.com/benjjneb/dada2/issues/1017

**but I also don't want to artificially increase overlap between samples. So I am wondering if you think 2) alone is safer or if I should do the added step of 3) is better to not lose real ASVs in dada2 or merge steps.

Thanks so much
Anna

PS. one other question I have really been wanting to ask you. I have Illumina sequenced 20 bacterial isolates from these  locations and found they each have 7-14 ASVs, some of which I can find more than one of in my samples (meaning I can find the top 2-3 ASVs from each bacterial isolate) I was considering collapsing those somehow but given that I want to use ASVs (as you've suggested in your work) not OTUs I was wondering if you have thoughts about this type of issue....

**Comment by ARBramucci** [comment]
perhaps this user's suggestion is an approach I will try
https://github.com/benjjneb/dada2/issues/1017

**Comment by benjjneb** [comment]
Sorry for slow response, when the issue got closed it fell out of my email to-do list.

> Given that my project is critically looking for overlap between samples run across 3 plates, should I also do the extra step suggested by a previous user: (issue 1017); running dada2 as in (2) and then use the whole ASV list as a list of priors to ensure potential overlap between plates isn't lost during dada step
#1017

That wouldn't be a bad idea. But to be honest my suggestion would be different: Only use the forward reads.
If the overlap between runs is critical, you are probably better off erring on the side of high-quality, more sensitive and more consistent denoising that you will get by using just the higher quality forward reads, and avoiding the merge step entirely, than you will get by trying to retain the (marginal) gain in taxonomic resolution that comes with the entire V1V3 operon.

Then, if you want to do as in #1017 and share information between runs via `priors`, even better. But the gain from that is probably smaller than it would be from moving to forward-reads only.

> one other question I have really been wanting to ask you. I have Illumina sequenced 20 bacterial isolates from these locations and found they each have 7-14 ASVs, some of which I can find more than one of in my samples (meaning I can find the top 2-3 ASVs from each bacterial isolate) I was considering collapsing those somehow but given that I want to use ASVs (as you've suggested in your work) not OTUs I was wondering if you have thoughts about this type of issue....

I would not perform that type of collapsing prior to merging runs together. Once everything is merged (which ASVs allow), then one can cluster the data further as appropriate for your research question.
