### ISSUE TITLE
DADA2 with Loop Genomics 16S long read data

### ISSUE THREAD

**Issue by sgreimanbio** [benjjneb/dada2#1355]
We are running DADA2 following the PACBIO Fecal Sample example for loop genomics 16S data. We are at the learn error section but keep getting an error on the saveRDS command. Any idea what we could be doing wrong?

saveRDS(err1, file.path(path.rds, "Fecal_err1.rds"))
Error in gzfile(file, mode) : cannot open the connection
In addition: Warning message:
In gzfile(file, mode) :
cannot open compressed file 'RDS//Fecal_err1.rds', probable reason 'No such file or directory'

**Comment by benjjneb** [comment]
R isn't finding a file at the location you are providing.

What does `file.path(path.rds, "Fecal_err1.rds")` look like in plain text?
Did you already create the `RDS` directory? if not, it needs to be pre-created before you can save a file in it.

**Comment by sgreimanbio** [comment]
Thanks for the help. We were able to figure that out. However, we have run into another issue.

I have been able to export a final fasta file with all ASV sequences, as well as a count table and taxa table using the commands (below) for short read data, but cannot figure out an equivalent way to do it with the long read data. 

Any suggestions for how to do this at the end (we have followed along with the Pacbio fecal sample example. Thanks so much. 

 # giving our seq headers more manageable names (ASV_1, ASV_2...)
asv_seqs <- colnames(seqtab.nochim)
asv_headers <- vector(dim(seqtab.nochim)[2], mode="character")

for (i in 1:dim(seqtab.nochim)[2]) {
  asv_headers[i] <- paste(">ASV", i, sep="_")
}

  # making and writing out a fasta of our final ASV seqs:
asv_fasta <- c(rbind(asv_headers, asv_seqs))
write(asv_fasta, "ASVs.fa")

  # count table:
asv_tab <- t(seqtab.nochim)
row.names(asv_tab) <- sub(">", "", asv_headers)
write.table(asv_tab, "ASVs_counts.tsv", sep="\t", quote=F, col.names=NA)

  # tax table:
  # creating table of taxonomy and setting any that are unclassified as "NA"
ranks <- c("domain", "phylum", "class", "order", "family", "genus", "species")
asv_tax <- t(sapply(tax_info, function(x) {
  m <- match(ranks, x$rank)
  taxa <- x$taxon[m]
  taxa[startsWith(taxa, "unclassified_")] <- NA
  taxa
}))
colnames(asv_tax) <- ranks
rownames(asv_tax) <- gsub(pattern=">", replacement="", x=asv_headers)

write.table(asv_tax, "ASVs_taxonomy.tsv", sep = "\t", quote=F, col.names=NA)

**Comment by benjjneb** [comment]
We need a more specific and identifiable problem in order to help. You've provided some code, but what is going wrong is unclear.

Ideally, problems are isolated to small reproducible chunks of code. That makes helping with the issue much easier (or even possible).
