### ISSUE TITLE
How to proceed with fastq files containing a mixture of forward and reverse reads

### ISSUE THREAD

**Issue by adamsorbie** [benjjneb/dada2#1357]
Hi, 

Apologies if this is slightly off-topic but I wasn't sure where to ask for help. 

In my group we are currently conducting a meta-analysis study. Since trying to find information on whether the reads still contain primers or not is usually a challenge, I adapted your primerHits function from the ITS tutorial into a cli script to facilitate identifying primer presence. 

I recently obtained a dataset from the SRA (V4, 150BP PE 514f-805r), and ran the script as usual but the output was a little strange. 

```
                 Forward Complement Reverse RevComp
FWD.ForwardReads   11227          0       0       1
FWD.ReverseReads    7752          0       0       1
REV.ForwardReads    7839          0       0       0
REV.ReverseReads   11353          0       0       2
                 Forward Complement Reverse RevComp
FWD.ForwardReads   11227          0       0       1
FWD.ReverseReads    7752          0       0       1
REV.ForwardReads    7839          0       0       0
REV.ReverseReads   11353          0       0       2
                 Forward Complement Reverse RevComp
FWD.ForwardReads    9683          0       0       0
FWD.ReverseReads    8637          0       0       1
REV.ForwardReads    8831          0       0       0
REV.ReverseReads   10240          0       0       0
```

It seems that the forward and reverse primers are found in both forward and reverse reads. I had a look into the fastq files themselves and it almost seems like they contain a random mixture of forward and reverse reads: 

```
@NS500181:15:H0YA6BGXX:4:23612:7477:3050 2:N:0
TTCTCTGAGCCGGACTACCCGGGTTTCTAATCCTGTTTGCTCCCCACGCTTTCGCACCTGAGCGTCAGTCTTCGTCCAGGGGGCCGCCTTCGCCACCGGTATTCCTCCAGATCTCTACGCATTTCACCGCTACACCTGGAATTCTACCCCC
+
<AAAAFFFFFFFFFFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFF<FFFFFFFFF7FFFF.FFFFFFFFFAFFFFFFFFFFFFFFFFFFFFFFF.FFFFFFFFAFFAFFFFFFFFFF<FFFFFFF.FFFAF.F<FFFFFFFA<AFAF<7FF
@NS500181:15:H0YA6BGXX:4:23612:12806:3814 2:N:0
GGCAAGAGTGCCAGCAGCCGCGGTAATACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATCTGATACTGGCAAGCTTGAGTC
+
AAAAAFFFFFFFFFFFFFFFFFAFFFFFFFFFFFFFFFFAFFFFFFFFFFFFFFFFFFAFFFFFFF<FFFF<FFFFFFFFFFFFFFFFFFFFFFFFFFAAAFFFFFFAFFAFFA.FFFFFF.FFF<FFFFFAFF.FFFFF<AF.FFFFFF<
@NS500181:15:H0YA6BGXX:4:23612:2184:4859 2:N:0
TTCTCTGAGCCGGACTACAAGGGTTTCTAATCCTGTTTGCTCCCCACGCTTTCGCACCTGAGCGTCAGTCTTCGTCCAGGGGGCCGCCTTCGCCACCGGTATTCCTCCAGATCTCTACGCATTTCACCGCTACACCTGGAATTCTACCCCC
+
AAAAAFF.FFFFFFFFFFFFFFFFFFFFFAFFFFFFFFFFFFFFFFFFFFFFFFF.FFFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAFFFFFFFFFAFFAFFAFFFFFFFFFA<FFF.FFFFFFF.FF<FFFFFFFFFF.FFF
@NS500181:15:H0YA6BGXX:4:23612:26145:5128 2:N:0
TTCTCTGAGCCGGACTACTAGGGTTTCTAATCCTGTTTGCTCCCCACGCTTTCGCACCTGAGCGTCAGTCTTCGTCCAGGGGGCCGCCTTCGCCACCGGTATTCCTCCAGATCTCTACGCATTTCACCGCTACACCTGGAATTCTACCCCC
+
AAAAAFF<FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAFFFFFFFFF7FFFFAFFFFFFFFFFFFFFFFFFFFFFFFFAFFFFFFFAFFFFFFFFFFF<FFFAFFFFFAFFFFFFFF.FFFFAFF<FFFFFFFFFFF.F.FFF
@NS500181:15:H0YA6BGXX:4:23612:8745:5435 2:N:0
TTCTCTGAGCCGGACTACTAGGGTATCTAATCCTGTTTGCTCCCACGCTTTCGCACCTGAGCGTCAGTCTTTGTCCAGGGGGCCGCCTTCGCCACCGGTATTCCTCCAGATCTCTACGCATTTCACCGCTACACCTGGAATTCTACCCCCC
```

This isn't something i've seen before and i'm not 100% sure how to proceed. There seems to be a 7-11 bp padding at the start and the primers are different lengths so trimLeft is not an option. I also tried cutadapt but it doesn't seem to recognising the primers. 

Do you have any idea how to process these reads so I can run dada2?

**Comment by benjjneb** [comment]
If there is a consistent oligonucleotide that marks the start of the reads, you can use the `orient.fwd` parameter in `filterAndTrim` to reorient the reads (including paired reads) so that they are in a consistent direction. For example, `filterAndTrim(..., orient.fwd="TTCTCT")` would reorient the reads so that "TTCTCT" is always at the start of the reads.

Note that this functionality is limited in some ways, for example it does not support ambiguous nucleotides. But it gets the job done in a good chunk of random orientation cases.

After that, you'll still need to trim primers, and if the padding at the front is variable length you'll need to use something like cutadapt. But that might work better once the reads are consistently oriented.

**Comment by adamsorbie** [comment]
Thanks! Unfortunately there doesn't seem to a common oligonucleotide at the start of the reads, at least not between different read pairs. 

Do you have any idea why there would be a mixture of reads containing forward and reverse primers in one file? All of the data i've worked with in the past, those containing the forward are in one file and the reverse in the other. I've been searching through here and the qiime2 forums but couldn't seem to find anyone with a similar issue. 

The only thing I can find of at the moment to solve this is trying to pull out reads based on primer hits and then placing them in separate (new) files based on whether they contain the forward or reverse then that should allow use of cutadapt or even the trimLeft function.

**Comment by benjjneb** [comment]
> Do you have any idea why there would be a mixture of reads containing forward and reverse primers in one file?

There are library preparations that create reads in mixed orientations. I don't know what the benefit of that is, but it's something we've seen before (hence the `orient.fwd` functionality). I'd have to imagine there are more general solutions out there, but I don't know them off hand. You might want to look at QIIME1-era discussions, as mixed-orientation libraries were in my experience more common a few years ago than they are now.

**Comment by harish0201** [comment]
Hi!

I'm currently stuck in the same (sinking) boat as @adamsorbie . I think the term in Bi-Directional Sequencing and thanks to @benjjneb I was able to get a lead on qiime-1 fora. The dataset that I'm working on is a few years old, say about 4-5 years? It does really seem to be prevalent back then :/

The relevant link is here: https://groups.google.com/g/qiime-forum/c/MJNNsXTQpUA

The gist is to basically segregate the reads, flip the orientation of the Rev-comped one, concatenate them and then do the rest of the analyses.

**Comment by benjjneb** [comment]
@harish0201 That looks like what would be expected from reads in mixed orientation.

The FWD primer, in the provided ("Forward") orientation, is matching about half the Forward reads (i.e. R1) in the sample.
The REV primer, in the provided ("Forward") orientation, is matching about the same number of Reverse reads (i.e. R2) in the sample. That alone looks like what you see in the DADA2 ITS tutorial.

Then, because half the reads are in the flipped orientation...
The FWD primer, in the provided ("Forward") orientation, is matching about half the Reverse (i.e. R2) reads.
And the REV primer, in the provided ("Forward") orientation, is matching about the same number of Forward reads (i.e. R1).

That makes the difference between your output and what we see in a "normal" sample where all the reads were in the same orientation.

**Comment by harish0201** [comment]
Great! So I understood it correctly. So, I was able to go through the dataset and flip these reads. These are V3-V4 regions so I chose the 1st set of primers (the ones below were V4), anyhoo.

Now it looks likes this:
````
                 Forward Complement Reverse RevComp
FWD.ForwardReads  133467          0       0     168
FWD.ReverseReads     176          0       0  149150
REV.ForwardReads      27          0       0  148587
REV.ReverseReads  132896          0       0      17
````

I think now it likes like the table that was mentioned in ITS tutorial to an extent, but this is most that can be done, after tons of experimentation from my end.
