### ISSUE TITLE
chimera removal biased

### ISSUE THREAD

**Issue by andzandz11** [benjjneb/dada2#1359]
I found that if I have a lot of very similar ASV with very low genetic variation that the chimera removal step tries to remove almost all of these. (chim = chimera as being detected by dada2, no "chim" = not being detected as chimera)

This removes the plant families in my dataset with low genetic variation leading to an overestimation of families with higher genetic variation.

![grafik](https://user-images.githubusercontent.com/19622117/120480625-8d2a8800-c3af-11eb-9b7e-5369d8233ec9.png)

The list goes on like that for another 3 pages. I am surprised so many near-identical ASV make it through the ASV "clustering". I bet some of the "chimeras" are maybe PCR or sequencing errors. Does that maybe have to do with the underestimation of error rates I raised in an earlier issue?

If I set minOneOffParentDistance = 0 it gets a little bit better, but not satisfactory.

I wished there was a condition for chimera detection that requires both parents to be at least x % genetically different or an option to include prior information (the reference database used to identify my amplicons) as additional information. Maybe such a tool exists and I am not aware of it?

**Comment by benjjneb** [comment]
There is literature suggesting that increaseing the `minFoldParentOverAbundance` parameter can help reduce false positives in chimera identification (this sets how much more abundant, in fold-terms, the putative parents of a chimera must be than the putative chimeric child).

> I wished there was a condition for chimera detection that requires both parents to be at least x % genetically different 

That's actually a good idea. We already have that implemented, but it is only exposed when allowing "one off" chimera detection. Flagging this post enhancement on this point.

> an option to include prior information (the reference database used to identify my amplicons) as additional information

This can certainly be done, but by hand in R. For example, if you have a vector of sequences (`asvs.ref`) that are known to be good non-chimeric amplicons, the below code should do the trick:

```
# assuming seqtab is the sequence table prior to chimera removal
seqtab.nochim.intermediate <- removeBimeraDenovo(seqtab, ...)
keep <- unique(c(getSequences(seqtab.nochim.intermediate, asvs.ref))
seqtab.nochim <- seqtab[,getSequences(seqtab) %in% keep]
```

**Comment by andzandz11** [comment]
Thank you I will try to make the minFoldParentOverAbundance even more strict (I tried 4 before), i think UCHIME3 has it set to 16 by default.

**Comment by andzandz11** [comment]
I changed the `minFoldParentOverAbundance` parameter (first number after #) 
I made 3 PCR replicates before sequencing with individual tagging.
I applied the rule that I only want to keep ASV that can be found in 2 out of 3 replicates after the bimeria removal step.
The last number per line indicates the total number of ASV removed by the chimera removal and the 2of3 rule.
The 2of3 rule step seems to prevent me from making terrible choices beause when setting `minFoldParentOverAbundance` to 1 it only removes 43 ASV but when i choose `minFoldParentOverAbundance` 16 it removes 1683 ASV.

I can see that the number of removed bimeras fluctuates by ~2600, but after the replicate screening only by ~1000.

I decided to go with the 2nd conservative (2nd from top) option, because the next best option only removes ~300 putative bimeras more but at the cost of ~20% of my total sequences. I consider this cutoff to be sensible. 

I find it hard to decide which `minFoldParentOverAbundance` to choose without additional information (such as my three PCR replicates). Maybe it is a beginner problem.

```
#16: Identified 928 bimeras out of 4070 input sequences. seq%removed: 0.9     total ASV removed after 2of3 rule: 2611
#4: Identified 2192 bimeras out of 4070 input sequences. seq%removed: 4.7     total ASV removed by 2of3 rule: 2995
#2: Identified 3044 bimeras out of 4070 input sequences. seq%removed: 24     total ASV removed by 2of3 rule: 3268
#1.5: Identified 3114 bimeras out of 4070 input sequences. seq%removed: 30     total ASV removed by 2of3 rule: 3434
#1: Identified 3568 bimeras out of 4070 input sequences. seq%removed: 76     total ASV removed by 2of3 rule: 3611
```

**Comment by benjjneb** [comment]
> Is it normal that the algorithm thinks 76% of my reads are bimeras?

My concern with your data is exactly this. Usually this indicates a technical problem -- in 16S world this almost always ends ubs being that primers with ambiguous nucleotides weren't fully removed.

Maybe with this plant locus there are more real sequences that look like chimeras, but... 76%. I still suspect there is an as of yet unidentified technical issue.

**Comment by andzandz11** [comment]
I removed the flanking regions, because they might be partially conserved. That might have been the technical issue.

The sequence removed rate is now 43% at minFoldParentOverAbundance 1 and 20% at minFoldParentOverAbundance 2.

It is a multi-copy marker that has multiple closely related variants per genome copy. Maybe that does look like a chimera?

I have BLASTed some sequences and they are all correct, there is no technical issue remaining.

**Comment by andzandz11** [comment]
Sorry.
Not sure how to proceed. 

I will just do the 3 PCR replicates every time to have a "second opinion" about the chimera rate.
