### ISSUE TITLE
Sample_data() not showing up during creation of phyloseq object

### ISSUE THREAD

**Issue by aarondeming** [benjjneb/dada2#1360]
Hi everyone,

I require a little help here. I have the three essential components to creating a phyloseq object but for some strange reason when the command was executed, sample_data() does not appear. 

```
row.names(taxa.ps) = row.names(assign.taxa)
colnames(taxa.ps) <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")
taxa.ps <- tax_table(assign.taxa)
seqtab.nochim.ps <- otu_table(seqtab.nochim, taxa_are_rows=FALSE) 
samdata.ps <- sample_data(metadata)

ps <- phyloseq(otu_table(seqtab.nochim.ps, taxa_are_rows=FALSE), #non chimeric sequences 
               sample_names(samdata.ps),                         #metadata table
               tax_table(taxa.ps))                               #from the taxanomy assignment
ps

```
console outcome:
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 1962 taxa and 47 samples ]
tax_table()   Taxonomy Table:    [ 1962 taxa by 7 taxonomic ranks ]

I have been trying to figure out a fix for this, but I can't seem to find a solution. Any help or advice is greatly appreciated!

**Comment by benjjneb** [comment]
You are giving the `phyloseq` constructor `sample_names` instead of `sample_data`.

**Comment by aarondeming** [comment]
Oh, did not notice my mistake there. Thank you so much!
