### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by markdjohnson** [benjjneb/dada2#1362]
Hi Ben,

My code has been working perfectly but I have, since I visited it last month, been having issues getting it to work

Today I got a new message when I attempted to run the following command...

standard filting paramters the 240 and 210 are determined looking at visualizaztin
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,210),
maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
compress=TRUE, multithread=TRUE) # On Windows set multithread=FALSE

I received this error message...

Multithreading has been DISABLED, as forking is not supported on .Platform$OS.type 'windows'
Error in validObject(.Object) :
invalid class “SRFilterResult” object: superclass "Mnumeric" not defined in the environment of the object's class

When I attempt to run it with multithread=False the error message doesn't show the first line but keeps the second two.

Do you have any insight into what this error is referring to or how to correct it?
Thank you,
Mark

**Comment by benjjneb** [comment]
Yep, see #212. This was caused by a change in the Matrix package.

There is a workaround fix here: https://github.com/benjjneb/dada2/issues/212#issuecomment-836757295

Or you can just upgrade the dada2 R package to the latest version, 1.19.2 (or later): https://github.com/benjjneb/dada2/issues/212#issuecomment-840782264

**Comment by cm0109** [comment]
Getting the "Multithreading has been DISABLED, as forking is not supported on .Platform$OS.type 'windows'" error on

packageVersion("dada2")
[1] ‘1.22.0’

packageVersion("Matrix")
[1] ‘1.3.4’

Any help is appreciated!

**Comment by benjjneb** [comment]
> Getting the "Multithreading has been DISABLED, as forking is not supported on .Platform$OS.type 'windows'" error

Not an error. Just a warning that mulithreading of `filterAndTrim` was disabled because it isn't supported on Windwos. multithreading in other commands will work as expected.

**Comment by cm0109** [comment]
Thanks Ben, I stand corrected! Using DADA2 on Windows for the first time and the lack of multithreading there threw me off. Any way to get multithreading to work for filterAndTrim on Windows at all?

**Comment by benjjneb** [comment]
There are definitely ways to get it to work, but it's not a priority to fix, especially since it would require some Windows-specific code and platform-specific code is a bigger headache to maintain long-term.
