### ISSUE TITLE
Assign Taxonomy HOMD

### ISSUE THREAD

**Issue by abakhsh90** [benjjneb/dada2#1365]
Hello, 
I'm trying to assign the taxonomy using HOMD database but I keep getting the error 
Incorrect reference file format for assignTaxonomy.

I have been through the https://benjjneb.github.io/dada2/training.html#formatting-custom-databases 

I was wondering is there a code or script that I can use to transform the database to the correct format or if anyone have the correct format for it ?

Thanks a lot

**Comment by benjjneb** [comment]
There is no pre-written script to reformat the HOMD database that I am aware of, and a DADA2 version of that database has not been contributed. So, you'll need to convert HOMD to the `assignTaxonomy` format to be able to use it.

**Comment by fconstancias** [comment]
You can find the latest eHOMD database formated for dada2 (i.e. dada2::assignTaxonomy(seqs, "eHOMD_RefSeq_dada2_V15.22.fasta.gz" and dada2::addSpecies(taxa, "eHOMD_RefSeq_dada2_assign_species_V15.22.fasta.gz", verbose=TRUE) [here](https://github.com/fconstancias/metabaRpipe/tree/master/databases). 
Happy to include those into the https://benjjneb.github.io/dada2/training.html

Duplicate from https://github.com/benjjneb/dada2/issues/431 and https://github.com/benjjneb/dada2/issues/1451

**Comment by benjjneb** [comment]
That's awesome @fconstancias thanks for doing that!

**Comment by benjjneb** [comment]
Also a follow-up: I'd be happy to add these to the training.html page, but our standard has been that contributed databases have an associated doi. Would it be possible to do that for your reformatting of HOMD?

Deposition in Zenodo is one easy way to do that, as that will come with a doi.

**Comment by fconstancias** [comment]
Hi @benjjneb,

Done, please let me know if it is OK - https://zenodo.org/record/7380292#.Y4czLbLMK2o

**Comment by benjjneb** [comment]
Looks good to me, thanks!
