### ISSUE TITLE
converting multi-level taxonomy of OTUs to 7-level taxonomy

### ISSUE THREAD

**Issue by alinawazfcc** [benjjneb/dada2#1371]
Hi ! I used DADA2 pipeline to analyze the SSU dataset and I used SILVA database for taxonomy assignment. However, in the taxonomy column, I got many levels of taxonomy instead of most widely 7 taxonomy ranks. Can you suggest a solution to get 7 ranks of taxonomy from the output now? file is attached 

many thanks 
[taxonomy problem.xlsx](https://github.com/benjjneb/dada2/files/6754347/taxonomy.problem.xlsx)

**Comment by benjjneb** [comment]
Are you. using the `assignTaxonomy` function in DADA2 to do taxonmic assignment? If so, what reference fasta file are you using?
