### ISSUE TITLE
Possible to show 'top 3' taxonomy assignments?

### ISSUE THREAD

**Issue by eefj33** [benjjneb/dada2#1373]
Hi!

I want to use DADA2 to handle ITS sequences more efficiently in the future. I was wondering if it would be possible to get a 'top 3' of best matching assignments per ASV, instead of only the one that matches best. Is this possible and if so, how?
I was thinking of having 3 lines per ASV in the output file, preferably with a percentage of how well it aligns.

See this as a control. When BLASTing the sequences individually, the no.1 hit is not always the hit I would expect (not even close), yet the follwing 10 hits are. By showing the top 3 best matches, it would be easier to pick out the ones that would be doubtful to give it a closer inspection.

**Comment by benjjneb** [comment]
We don't have that sort of functionality implemented in the DADA2 R package. Alternatives would be to use another software package, or to use the alignment methods implemented in R (e.g. `nwalign`/`nwhamming` in dada2, or the more general purpose methods available through `Biostrings::pairwiseAlignment`).
