### ISSUE TITLE
Is it valid to calculate Good's coverage for DADA2 output ?

### ISSUE THREAD

**Issue by ShailNair** [benjjneb/dada2#1374]
Hi Ben,

Recently i used DADA2 on my 16s amplicon samples. As my samples had variable sequencing depth and quality,  i transformed and rarefied my ASV counts to a uniform sequencing depth.  Now, i  want to measure some sequencing estimates such as rarefaction curve, good's coverage, to make sure that the inferred results are not biased. As DADA2 processing removes singletons, is it valid to calculate Good's coverage?

Also, do you recommend any other measure/method to put forth that the filtered data have uniformity and enough coverage?

Thanks,

**Comment by benjjneb** [comment]
See previous discussion at the Q2 forum: https://forum.qiime2.org/t/is-it-valid-to-calculate-goods-coverage-on-dada2-denoised-feature-table/4109

In general, I would say Good's coverage is not valid for high-throughput 16S profiling period, as it is implicitly assuming that there are no mistakes in the identification of rare taxa.

> Also, do you recommend any other measure/method to put forth that the filtered data have uniformity and enough coverage?

"Enough coverage" is hard to define. I would say that the sequencing depth tells you what your effective limit of detection is (proportion~1/LIBRARY_SIZE), and that results should be interpreted with that detection limit in mind.

**Comment by razz1618** [comment]
Thanks.
