### ISSUE TITLE
Problems installing dada2

### ISSUE THREAD

**Issue by Newtoeri000** [benjjneb/dada2#1377]
Hello, I am not very familiar with Rstudio or R-coding in general and I am struggling with it. I'm starting off with this code

install.packages("devtools")
library ("devtools")
devtools::install_github("benjjneb/dada2", ref="v1.16")
library(dada2);packageVersion("dada2")
library(ggplot2)

but when this is ran, it ends in the error

Warning message:
In i.p(...) :
  installation of package ‘C:/Users/ERICE~1.NEW/AppData/Local/Temp/RtmpcHOVlL/file26f82fbc66d1/dada2_1.16.0.tar.gz’ had non-zero exit status

Any solutions? :)

**Comment by benjjneb** [comment]
I would recommend trying to Bioconductor installation method if you can: https://www.bioconductor.org/packages/release/bioc/html/dada2.html
