### ISSUE TITLE
Problem in assigning taxonomy

### ISSUE THREAD

**Issue by sonacharles** [benjjneb/dada2#1379]
I am getting this error when assigning taxonomy. I tried to use 138_1 version of SILVA. Kindly help me to go further.

taxa <- assignTaxonomy(seqtab.nochim, "D:/Drsheeja/1_Data/SILVA_138.1_SSURef_tax_silva.fasta.gz", multithread=TRUE)
Error in C_assign_taxonomy2(seqs, rc(seqs), refs, ref.to.genus, tax.mat.int,  :
  Invalid map from references to genus.
In addition: Warning messages:
1: In .Call2("fasta_index", filexp_list, nrec, skip, seek.first.rec,  :
  reading FASTA file D:/Drsheeja/1_Data/SILVA_138.1_SSURef_tax_silva.fasta.gz: ignored 673602224 invalid one-letter sequence codes

2: In matrix(unlist(strsplit(genus.unq, ";")), ncol = td, byrow = TRUE) :
  data length [42271358] is not a sub-multiple or multiple of the number of rows [2113568]

**Comment by benjjneb** [comment]
`SILVA_138.1_SSURef_tax_silva.fasta.gz` isn't formatted for use with dada2's `assignTaxonomy`. DADA2-formatted training fasta files are available here: https://benjjneb.github.io/dada2/training.html

**Comment by sonacharles** [comment]
Thank you .That was done! 
Could you please help with the following error too.

> taxa <- addSpecies(taxa, "D:/Drsheeja/1_Data/tax/silva_species_assignment_v138.1.fa.gz")
Error: cannot allocate vector of size 489.8 Mb

**Comment by benjjneb** [comment]
The data structures used by the `assignSpecies`/`addSpecies` functions are fairly memory intensive. Do you have access to a machine with more memory? 8GB should work I think with Silva, but 16GB would be even better.
