### ISSUE TITLE
Filtering in parallel

### ISSUE THREAD

**Issue by fanli-gcb** [benjjneb/dada2#138]
Hi, looking at the big data doc (http://benjjneb.github.io/dada2/bigdata.html), I'm not sure how the filtering step is parallelized. Is that snippet supposed to be submitted for each sample (e.g. via qsub)? 

For people using a single multi-core server, would replacing `seq_along` with `mclapply` in the `fastqPairedFilter` loop be a simple way to do it?

**Comment by benjjneb** [comment]
The filtering code is not appropriately parellelized right now, as it is rare that filtering is a time-limiting step.

If you do want to multithread the filtering, you can use an `mclapply` loop. However, it is recommended that you turn off the OMP multithreading (largely ineffective here) that is used by the `FastqStreamer` function. See discussion and code here: https://github.com/benjjneb/dada2/issues/41#issuecomment-148210175

**Comment by fanli-gcb** [comment]
Got it, thanks!
