### ISSUE TITLE
About single forward fastq files

### ISSUE THREAD

**Issue by M1chibata** [benjjneb/dada2#1380]
Hello, I am not very familiar with R and dada2, and I'm learning dada2 to analyze fastq files from activated sludge. However, the files only have single forward and I got choked when merging paired reads. Can you tell me what to do next？ And I found a "merge_processed.fastq", maybe it can be used for analysis.
![QQ截图20210718225354](https://user-images.githubusercontent.com/87610169/126071867-75c47e76-5ca5-4d6c-a216-66744736ec31.jpg)

**Comment by benjjneb** [comment]
The tutorial workflow is the basically the same for single-end reads, just with the read-merging step omitted. So skip red merging, and the subseqeuent sequence table line with:

```
seqtab <- makeSequenceTable(dadaFs)
```

**Comment by M1chibata** [comment]
Thanks a lot
