### ISSUE TITLE
Use future instead of mcapply to enable parallel in all platform

### ISSUE THREAD

**Issue by sixvable** [benjjneb/dada2#1381]
Hi @benjjneb,

Thanks for this excellent package!

Is there a plan to replace mcapply with [future](https://github.com/HenrikBengtsson/future) ? This should make the code more flexible and easier to maintain. 

There is a [video](https://youtu.be/Ph8jItU7Dlo) on bioconductor youtube channel taking about the future package.

sixvable

**Comment by benjjneb** [comment]
No such plan at this time. Most of the parallelization in dada2 is done C-side with Rcpp. It's just the parallelization of the filtering step (which is not usually rate limiting) that is done via R -- ShortReads's OMP implementation.
