### ISSUE TITLE
red line at 30 of y-axis?

### ISSUE THREAD

**Issue by marwa38** [benjjneb/dada2#1384]
Could you please inform me how to draw a red line in my graph? 

I am using plotQualityProfile to plot the first three forward and reverse samples as following:

forward:

fplot <-plotQualityProfile(fnFs[1:3])
fplot + scale_x_continous(breaks=seq(0,300,20))

reverse:
rplot <-plotQualityProfile(fnRs[1:3])
rplot + scale_x_continous(breaks=seq(0,300,20))

the red line I mean shown in the screenshot attached
![image](https://user-images.githubusercontent.com/68851733/126902480-0d9878ff-07e8-46b9-93e2-dda613320a5b.png)

**Comment by benjjneb** [comment]
The output of `plotQualityProfile` is a ggplot object, and you can add or modify it in the usual ggplot fashion. To make that red line, you can just add a horizontal line geom:

```
p <- plotQualityProfile(...)
p + geom_hline(yintercept=30, color="red")
```

**Comment by marwa38** [comment]
Thanks very much :)
Do you know why some figures have a red line representing the number of reads and some other don't? can I remove it? it is not a straight line though, which means that the number of reads is not consistent along the sequencing process

**Comment by benjjneb** [comment]
The red line is only included when there is variation in the lengths of reads in the associated sample(s).

The output of `plotQualityProfile` is a ggplot2 object, so it can be manipulated in all the ways such objects can be manipulated. This includes removing "geom"s, such as the red line, by reassigning them as NULL as decsribed here: https://stackoverflow.com/questions/50434608/remove-geoms-from-an-existing-ggplot-chart

e.g.
```
p <- plotQualityProfile(...)
p$layers # What is the mapping: y = ~Cum  layer?
p$layers[[7]] <- NULL
p
```

That said, that is pretty hacky and leaves the red-labeled right axis and labels. More sophisticated ggplot2 tricks could probably remove those too I suppose.
