### ISSUE TITLE
what is wrong with my sequences (or with plotQualityProfile)?

### ISSUE THREAD

**Issue by gabrielet** [benjjneb/dada2#1385]
UPDATE: I found something [in this post](https://github.com/benjjneb/dada2/issues/1316), finally. I guess this is the problem. I am going through this, to see what is going on but it looks like I have reads that are of length 0.

EDIT TO UPDATE: I am almost sure that the problem was related to the fact that some reads were of length 0. Indeed, I apparently solved by telling cutadapt to remove those reads that had a length under a certain threshold. I choose the threshold equal to 10 but have no clues about that is ok or not. I guess that using a threshold equal to 1 should work fine too. However, I don't know if that makes sense or not.

This is the updated cutadapt command:

```
for(i in seq_along(fnFs)) {
   system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                           "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                           cutFwd[i], cutRev[i], "--minimum-length", 10)) # input files
}
```

After this, I am now able to plot the quality profile for all the FASTQs.

ORIGINAL QUESTION:
Hello everyone,

basically, I have a list of fastq file (ITS) which were processed by `cutadapt()` as shown [here](https://benjjneb.github.io/dada2/ITS_workflow.html): 

```
# Run Cutadapt
for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                             fnFs.filtN[i], fnRs.filtN[i])) # input files
}
```
According to the check I do after cutadapt nothing was removed but some of the sequences are shorter, meaning something was actually trimmed.

This shows that, apparently, nothing was removed:
```
                 Forward Complement Reverse RevComp
FWD.ForwardReads       0          0       0       0
FWD.ReverseReads       0          0       0       0
REV.ForwardReads       0          0       0       0
REV.ReverseReads       0          0       0       0
```

Then, when I try to analyse their quality using `plotQualityProfile()` using this piece of code:

```
# forward reads all
for (smpl in c(1:length(cutFs))){
   print(cutFs[smpl])
   p <- plotQualityProfile(cutFs[smpl])
   png(paste0(saveImg, "seqs_quality_profile_sample_", smpl, "_forward.png"), type="cairo", units="in", width=8, height=6, pointsize=12, res=300)
      plot(p)
   dev.off()
}
```

I get this error, which apply to only some of the sequences...which means that some fastq are fine, some others are not.

`Error: BiocParallel errors element index: 1 first error: 'x' contains missing values`

This is the traceback:
```
12. stop(.error_bplist(res))
11. bplapply(X, FUN, ..., BPREDO = BPREDO, BPPARAM = param)
10. bplapply(X, FUN, ..., BPREDO = BPREDO, BPPARAM = param)
9. bplapply(X, FUN, ..., BPREDO = BPREDO, BPPARAM = BPPARAM)
8. bplapply(X, FUN, ..., BPREDO = BPREDO, BPPARAM = BPPARAM)
7. bplapply(fls, .qa_fastq_lane, type = type, ..., verbose = verbose)
6. bplapply(fls, .qa_fastq_lane, type = type, ..., verbose = verbose)
5. .qa_fastq(dirPath, pattern, type = type, ...)
4. .local(dirPath, ...)
3. qa(f, n = n)
2. qa(f, n = n)
1. plotQualityProfile(cutFs[smpl])
```
I also tried to run the same for loop on the fastq pre-cutadapting them and everything works fine.

Any clue about what might be wrong?

-----------------------------------------------------------------------------------

EDIT 1: I am not sure whether this may matter but cutadapt, when running, throws a warning which, according to cutadapt [documentation](https://cutadapt.readthedocs.io/en/stable/guide.html#warning-about-incomplete-adapter-sequences) is not an actual issue but...I am not sure.

The warning:

>WARNING:
    One or more of your adapter sequences may be incomplete.
    Please see the detailed output above.

EDIT 2: after looking into the sequences I found out that the primers I was using were matched only partially. So, I modified the primers that I am detecting and something weird happens.
To clarify this, let's say i have a primer `nonmatchingPARTIALPRIMER`

which returns the results shown above, i.e. is never found. I found out that some of my sequences, but not all of them, partially match the primer and the sequence I need to use to match it is `PARTIALPRIMER`

At this point I searched for it and this is the result:

```
[rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFsFiltN[[1]]), 
      FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRsFiltN[[1]]), 
      REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFsFiltN[[1]]), 
      REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRsFiltN[[1]]))

                 Forward Complement Reverse RevComp
FWD.ForwardReads    7586          0       0       0
FWD.ReverseReads    7399          0       0       0
REV.ForwardReads    7377          0       0       0
REV.ReverseReads    7546          0       0       0
```
Then, I run cutadapt to remove those new shortened-primers sequences and this is the result:

```
rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.cut[[1]]), 
      FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.cut[[1]]), 
      REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.cut[[1]]), 
      REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.cut[[1]]))

                 Forward Complement Reverse RevComp
FWD.ForwardReads       0          0       0       0
FWD.ReverseReads    7399          0       0       0
REV.ForwardReads    7377          0       0       0
REV.ReverseReads       0          0       0       0
```
At this point I guess there are issues with the sequences. I tried to go further with the plotQualityProfile function as mentioned above, i.e. through the for loop, and the same error appeared.

EDIT 3: I found this [post](https://github.com/benjjneb/dada2/issues/159) that might be related to my problem. If this is true, i.e. I am having cutadapted sequences that are of length 0...how do I know? I think all my sequences have length which is different from zero.

EDIT 4: Ok, I managed to remove all the primers, but the error still is there:

```
> plotQualityProfile(cutFs[1:2])
Error: BiocParallel errors
  element index: 1
  first error: 'x' contains missing values
```

but I can't find anything about it.

**Comment by benjjneb** [comment]
Just wanted to say thank you for updating your comment as you found the solution. That is really useful to future people who run into the same issue.

Please re-open as needed if you have further issues.
