### ISSUE TITLE
DADA2 learnErrors() using reads from only 87 of the total 380 samples

### ISSUE THREAD

**Issue by vanormbr** [benjjneb/dada2#1387]
Hello all,

I'm working through the DADA2 pipeline and I'm wondering why the status of my learnErrors() command says that it is using reads from only 87 samples where the dataset has a total of 380 samples. Should I be concerned with this? Code below.
Example forward reads File Names:
OmyF1_S1_L001_R1_001.fastq.gz
OmyF10_S10_L001_R1_001.fastq.gz
OmyF99_S100_L001_R1_001.fastq.gz
Example Sample Names:
OmyF1
OmyF10
OmyF100

```
library(dada2); packageVersion("dada2")
#File parsing for the first round of sequencing
#define path into folder where forward and reverse subfolders are located
base_path <- "C:/VanOrman_laetitia_O.mykiss/Omykiss_gut_Dada2/fastq/"

#define fullname for forward subdirectory 
pathFpaste <- paste0(base_path, "pathF")
#define fullname for reverse subdirectory 
pathRpaste <- paste0(base_path, "pathR")

#make an unsorted list of all forward fastq.gz file names
fastqFs_round1 <- list.files(pathFpaste, pattern="fastq.gz")
#make an ussorted list of all reverse fastq.gz file names
fastqRs_round1 <- list.files(pathRpaste, pattern="fastq.gz")

#correct to a sorted list of forward filenames
fastqFs_round1<- paste("OmyF", c(1:380),"_S", c(1:95, 97:191, 193:287, 289:383), "_L001_R1_001.fastq.gz", sep ="")
#correct to a sorted list of reverse filenames
fastqRs_round1<- paste("OmyF", c(1:380),"_S", c(01:95, 97:191, 193:287, 289:383), "_L001_R2_001.fastq.gz", sep ="")

#make a list of sample names from the list of forward fastq.gz file names  
sample.names <- sapply(strsplit(fastqFs_round1, "_"), `[`, 1)

#redefine the variable from having only sorted forward fastq.gz filenames to having sorted fullname file and path because the filter steps needs full path, very inefficient here
fastqFs_round1 <- file.path(pathFpaste, fastqFs_round1)
fastqRs_round1 <- file.path(pathRpaste, fastqRs_round1)

#inspect quality profile
plotQualityProfile(fastqFs_round1[1:2])
plotQualityProfile(fastqRs_round1[1:2])

#define file path into the forward filtered subdirectory 
filtpathF <- file.path(pathFpaste, "filtered")
#define file path into the reverse filtered subdirectory 
filtpathR <- file.path(pathRpaste, "filtered")

#store empty variables for storing filtered forward reads in this variable using ordered sample.names and modified extensions
filtFs <- file.path(filtpathF, paste0(sample.names, "_F_filt.fastq.gz"))
#store empty variables for storing filtered reverse reads in this variable using ordered sample.names and modified extensions
filtRs <- file.path(filtpathR, paste0(sample.names, "_R_filt.fastq.gz"))

out <- filterAndTrim(fastqFs_round1, filtFs, fastqRs_round1, filtRs, truncLen=200, maxEE=c(2,5), maxN=0, trimLeft = c(20,20), compress=TRUE, verbose=TRUE, multithread=FALSE)
head(out)
```
Filenames followed by reads in and reads out.
OmyF1_S1_L001_R1_001.fastq.gz    31113     15166
OmyF2_S2_L001_R1_001.fastq.gz    24651     18974
OmyF3_S3_L001_R1_001.fastq.gz    19238     14552
OmyF4_S4_L001_R1_001.fastq.gz    25276     19840
OmyF5_S5_L001_R1_001.fastq.gz    16910      8568
OmyF6_S6_L001_R1_001.fastq.gz    20859      7352
Note, all samples have retained greater than 0 reads. The lowest is roughly 40 reads for a sample

```
#Learn error rates forward
errF_round1_filt <- learnErrors(filtFs, nread=1e6, multithread=FALSE)
```
182032560 total bases in 1011292 reads from 87 samples will be used for learning the error rates.
Warning message:
In learnErrors(filtFs, nread = 1e+06, multithread = FALSE) :
  The nreads parameter is DEPRECATED. Please update your code with the nbases parameter.
```
#Learn error rates reverse
errR_round1_filt <- learnErrors(filtRs, nread=1e6, multithread=FALSE)
```
182032560 total bases in 1011292 reads from 87 samples will be used for learning the error rates.
Warning message:
In learnErrors(filtRs, nread = 1e+06, multithread = FALSE) :
  The nreads parameter is DEPRECATED. Please update your code with the nbases parameter.

Thanks for any help!
-Bryan V.

**Comment by benjjneb** [comment]
`learnErrors` by default uses a subset of the data that reaches the `nbases` threshold (or `nbases`). This is the sum of bases (or reads) across all the samples used by `learnErrors`. So, your first 87 samples together contained over 1M reads, hence no furthe samples were used.

**Comment by vanormbr** [comment]
Ahh, thank you. And I also appreciate how quick the response was.
