### ISSUE TITLE
Mismatch error and forward reads 

### ISSUE THREAD

**Issue by edmundtayzy** [benjjneb/dada2#1389]
Hi all, 

I am currently trying out to run some analysis with fastq datasets that are published on various databases (NCBI/ENA) and i'm currently trying to analyze 26 samples. 

When I load and trim all 26 samples together with the command below:

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(150,150),
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=FALSE)

I received an error message: 
Error in (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0, : Mismatched forward and reverse sequence files: 97993, 100000.

However, I was able to trim the samples in small batches. So instead of loading 26 samples into R and run the codes, I did it in batches - load first 10 trim, load second 10 trim, load last 6 trim and I was able to trim it successfully without an issue. But I just can't find a way to load and trim them together.

Any idea what might be the issue and the way to resolve this?

Thanks in advance.

**Comment by benjjneb** [comment]
That error message indicates that there were different numbers of reads in one of the forward read files than in the matching reverse read file. It is not clear why doing this processing in batches would avoid that problem.

My guess is that there is some sort of mismatch between the ordering of the filenames when you are processing all the samples together. It might be useful to inspect the filenames to look for such a possibility:

```
cbind(fnFs, fnRs)
```
