### ISSUE TITLE
In QC, how change titles for each sample from long sequencing name to the sample label?

### ISSUE THREAD

**Issue by marwa38** [benjjneb/dada2#1390]
Hello 

Thanks very much for your support. 
Could you please let me know how can I change the name for each sample as it is very long and need to make it just a sample label I have in my metadata file? any idea how could this be done? this will help in publication as I will add supplementary materials.

plotQaulityProfile(fnFs[1:6])+
scale_x_continous(breaks=seq(0,300,20) +
geom_hline(yintercept=30, color="blue") +
ggtitle("Forward QC")

![fwdQC](https://user-images.githubusercontent.com/68851733/128644426-7814f82d-6fe5-474a-921e-9df08597fc15.jpg)
Thanks 
Marwa

**Comment by benjjneb** [comment]
`plotQualityProfile` returns a ggplot2 object, so the various ways to manipulate such objects will work here. Poking around, this looks like a pretty elegant solution to the facet re-labeling issue here: https://stackoverflow.com/questions/3472980/how-to-change-facet-labels/34811062#34811062

An example that works in my hands with `plotQualityProfile` is:
```
new.labs <- c("Sam1", "Sam2")
names(new.labs) <- basename(fnFs)[1:2]
plotQualityProfile(fnFs[1:2]) + facet_wrap(~file, labeller=as_labeller(new.labs))
```
