### ISSUE TITLE
Problems with AssignTaxonomy 

### ISSUE THREAD

**Issue by Sufia463** [benjjneb/dada2#1393]
Hello. I tried to assigntaxonomy with RDP database (rdp_train_set_16.fa). But I couldn't able to add fa.gz file. I set the directory to this file, but it still shows an error. Could you help me out with what to do now?

**Comment by jgrzadziel** [comment]
@Sufia463 can you share your code ? Maybe there is some typo?

**Comment by Sufia463** [comment]
Hello,
Here's the code. I couldn't add fa.gz file. So I set my directory directly to the folders that contain RDP reference database for 16s.

taxa <- assignTaxonomy(seqtab.nochim, "/Metagenomics (Course 5001)/Metagenomics_Plague_Y. pestis (my research)/Bacteria_unaligned", multithread=TRUE).

I hope this helps. Thank you so much for your response.

Sufia*


________________________________

**Comment by jgrzadziel** [comment]
@Sufia463 can you also provide what kind of error you received ?
 Try to change directories names to avoid spaces and symbols e.g:

taxa <- assignTaxonomy(seqtab.nochim, "/Metagenomics_ Course_5001/Metagenomics_Plague_Ypestis_my_research/Bacteria_unaligned/rdp_train_set_16.fa", multithread=TRUE).

**Comment by Sufia463** [comment]
I neither get any error not get any results from the coding. It just stuck there. I will try to change the name of the directory to see how it goes. I will keep you posted. Thank you so much for your kind help.

Sufia
________________________________
