### ISSUE TITLE
DADA 2 citation

### ISSUE THREAD

**Issue by JLNutrition** [benjjneb/dada2#1394]
Dear DADA2 team: We have recently submitted a paper and the journal requires us to provide information for any software used (In addition to the citation). Who should be the maker/supplier of DADA2? Thanks!!

**Comment by benjjneb** [comment]
I think the information you need is probably in the package DESCRIPTION file: https://github.com/benjjneb/dada2/blob/master/DESCRIPTION

But let me know if there's some other specific bit of info you need that isn't there.
