### ISSUE TITLE
Silva 138, Dada2 and Eukaryotes

### ISSUE THREAD

**Issue by seven-tenths** [benjjneb/dada2#1398]
RE::
NOTE: As of Silva version 138, the official DADA2-formatted reference fastas are optimized for classification of Bacteria and Archaea, and are not suitable for classifying Eukaryotes.

Any update on this?

**Comment by benjjneb** [comment]
Sorry no updates at this time. Still on the radar, but for now it is still recommended to use the DADA2 formatted version of Silva v132 for Euk 18S assignment.
