### ISSUE TITLE
R programming_str_contains function_How to concatenate two outputs of str_contains function

### ISSUE THREAD

**Issue by ananya231284** [benjjneb/dada2#1399]
I have a large file in the form of a term document matrix. The rows contains file no and the columns contains the terms. There are in total around 876 terms. (File A)
I have another file which has a list of about 70 terms. (File B)
I want to find out which documents in File A have atleast two terms of File B. I want the count of the documents. 
Now, I am using a str_contains function to match the terms but it is returning a boolean value and when I concatenate the output of str_contains 1(contains first term of File B) and output of str_contains 2 (contains second term of File B), I just get returned a boolean value. (False). Also, it is not searching the term document matrix properly. Though terms like "social", school" in File B are present in term document matrix together, they dont show up and str_contains return FALSE. May be it is not able to search through the loop.
I am using a for loop to search the term document matrix. 
I am attaching the code, file A and File B. 
I am new to R and not that expert i n programmimg. I might be applying a wrong logic. 
I want to know how I can perform this task.
[code_2208.txt](https://github.com/benjjneb/dada2/files/7027082/code_2208.txt)

The first file(Assoscruleinput_uni_bi.txt) is File A which is the term document matrix
and the second file cterms.csv is the File B. 
[Assocruleinput_uni_bi.txt](https://github.com/benjjneb/dada2/files/7027074/Assocruleinput_uni_bi.txt)
[cterms.csv](https://github.com/benjjneb/dada2/files/7027077/cterms.csv)

**Comment by benjjneb** [comment]
@ananya231284 Did you post this issue to the right repository? The dada2 package does not implement `str_contains`
