### ISSUE TITLE
Generally fill-in missing documentation pages

### ISSUE THREAD

**Issue by joey711** [benjjneb/dada2#14]
I can do most of this.

There are often missing sections of documentation pages, including missing examples or output definition. Most importantly, in some cases there are undefined or mismatch parameter definitions between the doc and the function.

Good idea to clean this up in general, and obviously necessary for Bioconductor.

**Comment by benjjneb** [comment]
Progress being made here. I think nearly all the core functions have complete documentation now. I am going to start removing the exports for non-core functions as well that are mostly in the package for my convenience.

**Comment by joey711** [comment]
Great. Part of the "learning curve" for me early on with phyloseq was discriminating functions that were mostly for internal use, versus those that are user-facing. Once users start using your exported functions, you have to maintain and document them, and it's [a bit of a process to get rid of them](http://www.bioconductor.org/developers/how-to/deprecation/).

**Comment by benjjneb** [comment]
All functions should meet documentation expectations now.
