### ISSUE TITLE
Start with single strand fasta file

### ISSUE THREAD

**Issue by yingliu3** [benjjneb/dada2#1403]
The tutorial suggests DADA2's starting point is a set of paired end fastq files split by sample and barcode removed. If we have access to only single strand files (perhaps only forward strand) or only fasta files are downloaded, do you have some suggestions on how to analyze using DADA2? Thanks!

**Comment by benjjneb** [comment]
If you have single-strand data, the tutorial is the same, except leave out the reverse read parts, skip merging, and construct the sequence table from the denoised data with `makeSequenceTable(dadaFs)`.

For fasta files, see https://github.com/benjjneb/dada2/issues/826#issuecomment-521400440

> We don't recommend it, as the quality scores provide important information about the likelihood of errors.
>
> If you must, you can run a fasta file through dada2. Replace derepFastq with dada2:::derepFasta, and when calling learnErrors and dada, include the argument errorEstimationFunction=noqualErrfun.
