### ISSUE TITLE
Lack of taxa after taxonomic assignments

### ISSUE THREAD

**Issue by felix9609** [benjjneb/dada2#1405]
Hi, might be I have issues with TAXA results after taxonomic assignments. 
- The results only got around 6 species from over 42,000 sequences, it was really small in comparison with when I run with QIIME (results about 400 species). Even though I changed trunclen and maxEE values many times. And the score quality is very high in my case.
- When I opened the filtered folder after filterAndTrim, the content in .fastq file were strange character, not ATGC (eg.  ?      肄???v?E?霹?jDbW%?⑿??  !
현뢨?m?n?G퐵???_냿콓[?屹廂y?矮?8옥??c薩눉??瀕뾵/%皇眺홌	;窪?|~욍Ax瞳颯??). 
I do not know it is okay or not.

Thank you.

**Comment by benjjneb** [comment]
By default, the output of `filterAndTrim` will be gzipped fastq files. If you want plain fastq files, you can either expand the gzip files, or output plain text files with `filterAndTrim(..., compress=FALSE)`.

Can you clarify what you mean when you say you "got around 6 species"?

The ASV table had only 6 entries? Or, you performed taxonomic assignment (what method? what database?) and only had 6 ASVs that had species-level assignments? Probably also useful to know what region/primer set you are using.

**Comment by felix9609** [comment]
Hi @benjjneb, thanks for your reply. 
I follow the script here https://benjjneb.github.io/dada2/tutorial.html
I received the raw date .fastq file (including Forward and Reverse) from company, then I used the script above to determine which species existing in this. 
After mergers, only 6 specific sequences was shown.
After assign taxonomy, only 6 Species was shown. 
However, my lab-mate used QIIME2 to assign taxonomy, about 400 species were detected. So I do not deeply which step I was wrong.
And here is all my data and result: https://drive.google.com/drive/folders/1s-6r7c3LZWWFtisDDVFbeaaPIuHwGvBX?usp=sharing
Could you have a look at this and tell me the reasons?
Thank you.

**Comment by benjjneb** [comment]
Given that you are following the tutorial workflow, can you post the results from the read-tracking step: https://benjjneb.github.io/dada2/tutorial.html#track-reads-through-the-pipeline

The number of reads that are making it through each stage is highly diagnostic as to what may be going on.

**Comment by felix9609** [comment]
Yes, the result after command head(track) here: https://drive.google.com/drive/u/1/folders/1s-6r7c3LZWWFtisDDVFbeaaPIuHwGvBX

**Comment by benjjneb** [comment]
First off, this makes it seem unlikely that only 6 ASVs were in your final table, if over 15k reads from multiple samples were making it to the end of the workflow. Can. you check again how many ASVs were in your final sequence table?

Second, the big dropoff during the chimera removal step suggests that the primers were not removed from your reads prior to processing. Are there primers on your reads? What primers? Were they removed?

**Comment by felix9609** [comment]
- The result 
seqtab <- makeSequenceTable(mergers) 
dim(seqtab) is
[1]   2    2388
table(nchar(getSequences(seqtab)))
438 439 440 ... 466 467
1      1    186 ... 353 100
- Sorry, I just begin with this work and phyloseq also. After received the raw data from a sequence company, I put in script and run

**Comment by benjjneb** [comment]
> Sorry, I just begin with this work and phyloseq also. After received the raw data from a sequence company, I put in script and run

You need to know what the data is you are working with. Please go find out what the primer-set and region that was sequenced, whether ther primers were on the reads. This is critical information to be able to appropriately process the data.

**Comment by felix9609** [comment]
@benjjneb thank you very much, I will find it out.
