### ISSUE TITLE
How to combine multiple runs that have different subsets of samples?

### ISSUE THREAD

**Issue by gabrielet** [benjjneb/dada2#1406]
This is the situation: we run an experiment with **n** samples just to find out that some of them, lets say **m**, don't have enough reads. So what was done next was to re-run those **m** samples in order to reach a minimum amount of reads that we consider as sufficient (i.e. 10K).

At this point I wonder how should I merge the information I am getting from the two runs. I found two threads (#1177 and #716) but I am having further issues which I try to summarise here.

As suggested in the two mentioned threads, I analysed the two runs separely to obtain two sequence tables (through `makeSequenceTable()`) that should be merged (through `mergeSequenceTables()`).

The two `seqtabs` were exported and then loaded as RDS, so we are not losing any information.

I have two problems, though.

The first is that one column in both sequence tables has no name. This means that the function `is.sequence.table()` is returning this warning:

```
if(!all(sapply(colnames(tab), nchar)>0)) {
    if(verbose) warning("Some column (sequence) names are blank.")
        return(FALSE)
}
```
I have no idea why `makeSequenceTable()` would return an empty column name.

Anyway, this issue is solved by removing the column with no name. However, I am not sure that is something I should be doing, or is it?

Assuming I am removing such column, I still don't know how to merge the two tables since they contain 1) a different number of samples (one with **n**, one with **m** samples) and 2) a different number of columns, i.e. sequences.

I subsetted the two `seqtabs` to obtain the same sequences, i.e. columns, and the same samples, i.e. rows, and then run the `mergeSequenceTables()` function. However, I get a message stating that I can't merge two tables that have the same row names:

```
> fullSeqTab <- mergeSequenceTables(libDTwoEight, libDThreeFive)
Error in mergeSequenceTables(libDTwoEight, libDThreeFive) : 
  Duplicated sample names detected in the sequence table row names:
```

This issue is also easy to solve. Indeed, I can simply rename the rownames but then...is `mergeSequenceTables()` summing up row-wise, so that if I have the samples in the same order I am sure that the summing is working?

If this is true, what should I do with those samples and those sequences that are not in the two subsets of shared samples/sequences? Should I simply attach columns and rows to the merged table and I will be ok?

Is there an alternative way to achieve this merging?

EDIT:

There is also another small point, which I believe it's not really an issue. I noticed that not all the sequences found by DADA2 were found in the two `seqtabs` but I believe this is ok. But, since we are using DADA2 and sequences are comparable across different experiments, I thinkl I should add up those that are shared, then attach all the unique sequences counts, and finally attach all the remaining samples to this summed-up table as mentioned above.

**Comment by benjjneb** [comment]
I think the `repeats` parameter in `mergeSequenceTables` might answer your main questions. By default, this is set to `"error"`, i.e. an error is returned if merging tables with the same sample names. But you can change it to `"sum"`, and get the behavior it seems you want, i.e. summing the counts between same-named samples. See the help-text '?mergeSequenceTables' for more info.

As for the columns with no name, that I don't understand... Are there perhaps zero-length sequences in your data? Otherwise, I'm not sure how that would come to be. Maybe you are running `mergePairs` with some unusual parameters?

**Comment by gabrielet** [comment]
sorry for my super-late reply and thank you for your answers.

> I think the repeats parameter in mergeSequenceTables might answer your main questions

yes, this is what I need. So...after merging the two seqTabs, I will simply analyse the resulting seqTab as if it were computed from one single run, and everything should be ok. Is this right?

> Maybe you are running mergePairs with some unusual parameters?

The only parameter that I was using was `returnRejects` which was set equal to TRUE. I now removed it and apparently everything is fine, i.e. no more sequences without a name.

**Comment by benjjneb** [comment]
> I will simply analyse the resulting seqTab as if it were computed from one single run, and everything should be ok. Is this right?

Yes.
