### ISSUE TITLE
Empty Filtered File

### ISSUE THREAD

**Issue by amandarwills** [benjjneb/dada2#1407]
Hello!

When I run the script (below), my filtered file is empty. I'm not sure what is happening, but I'm also attaching the Quality profiles of the 2 samples I'm testing with the script, just in case they are helpful. I am definitely using paired files. Any help would be greatly appreciated!

> # Place filtered files in filtered/ subdirectory
> filt_path <- file.path(path, "filtered")
> # Place filtered files in filtered/ subdirectory
> filt_path <- file.path(path, "filtered")
> filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
> filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
> names(filtFs) <- sample.names
> names(filtRs) <- sample.names
> #Filter the forward and reverse reads
> out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(290,200), maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE) 
Error in validObject(.Object) : 
  invalid class “SRFilterResult” object: superclass "Mnumeric" not defined in the environment of the object's class

![Rplot](https://user-images.githubusercontent.com/80725688/132779883-6c0e3455-14c0-4472-9d8b-d049e7dbb6f0.jpeg)
![Rplot01](https://user-images.githubusercontent.com/80725688/132779884-c1413a97-d214-4ed6-93b1-480768697490.jpeg)

**Comment by benjjneb** [comment]
See https://github.com/benjjneb/dada2/issues/1378#issuecomment-881815297

For the fix to this bug (which is basically just update to the most recent package version, 1.20).
