### ISSUE TITLE
assignTaxonomy returns table with no taxon identification, all results are as NA

### ISSUE THREAD

**Issue by Donandrade** [benjjneb/dada2#1408]
Dears!

I'm running DADA2 to identify the fungi community in some samples of ITS sequencing. I finished the pipeline, but the function assignTaxonomy is creating an object without results (all taxa are assigned as NA). All other objects look ok, but only the taxa table created by assignTaxonomy function looks bad (with no results, all results as NA). See the object created by  assignTaxonomy function, below:

![image](https://user-images.githubusercontent.com/3967276/132989439-7b657262-69d9-4c3e-bc7b-38759fa04748.png)

My data are 2X300 bp reads comes from illumina sequencing;
I made the denoising step using cutadapt to remove adapters and remove 20 bases pairs from 5' and 3' end (to remove the sequencing primers/adapters)
To assignTaxonomy function, I'm providing the reference fasta file available here: https://plutof.ut.ee/#/doi/10.15156/BIO/1281531
On "filterAndTrim" step I used the parameters below:
**out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=50)**

Please, can anybody help me?

**Comment by benjjneb** [comment]
Can you report the results of two tests: First, if you BLAST the top 5 ASVs against nt (https://blast.ncbi.nlm.nih.gov/Blast.cgi?PROGRAM=blastn&PAGE_TYPE=BlastSearch&LINK_LOC=blasthome) are the results fungi? Second, If you run `assignTaxonomy(..., tryRC=TRUE)` is everything also NA?

The other question would be about the formatting of the reference fasta file you are using. DADA2 `assignTaxonomy` tries to "sniff" UNITE formatted files, but that is only guaranteed to work for the official files. It might work for these, but it might not if the format has changed in fairly fiddly ways. When you `assignTaxonomy` with this reference, is there a "UNITE detected" message that is output?

**Comment by Donandrade** [comment]
Dear Callahan!

Thanks for helping me.

Abut your questions:
**1. First, if you BLAST the top 5 ASVs against nt (https://blast.ncbi.nlm.nih.gov/Blast.cgi?PROGRAM=blastn&PAGE_TYPE=BlastSearch&LINK_LOC=blasthome) are the results fungi?**  
These are my results:
![image](https://user-images.githubusercontent.com/3967276/133535649-e1d47642-ff25-4457-b87a-e133225954f2.png)

**2. Second, If you run assignTaxonomy(..., tryRC=TRUE) is everything also NA?:**
Yes! I'm running as you suggest: "assignTaxonomy(..., tryRC=TRUE)" and my results continue all with NA.

About your last question/consideration, I downloaded and used the reference fasta file available here: https://plutof.ut.ee/#/doi/10.15156/BIO/1281531 .  The general format of my reference fasta file is:
![image](https://user-images.githubusercontent.com/3967276/133537036-8f208a74-aeb6-4ef4-88e8-11dc8c5219ed.png)

One more time, thank you very much for your help!

**Comment by benjjneb** [comment]
The format of the fasta id lines is the problem. `assignTaxonomy` is not expecting the `UDB#######|` bit at the beginning, which is being parsed as being part of the kingdom designation. Thus, every entry is parsed as having a unique Kingdom, which ends up in there being no confidence in assigning at Kingdom level, and an `NA` at the highest level cascades down to all the rest. The `|SH######.####` at the end is also undesirable, as it will cause a similar issue at the Species level should the sequence be assignable there.

I'm not great with awk, but I imagine this is fixable in a one or two-liner. Basically, you want to the id line to be just the second "field" as delimited by the pipe characters (but also keeping a `>` at the start of the line to stay in fasta format).

**Comment by Donandrade** [comment]
@benjjneb!
Great! You are the best.
Your suggestion solve my problem. Now, my taxon table has the expected information.
Thanks so much.
