### ISSUE TITLE
Troubling(?) results when assigning taxonomy and building phylogeny

### ISSUE THREAD

**Issue by jsilve24** [benjjneb/dada2#141]
First off, thank you for creating and updating dada2. I am very excited by by your approach and am trying to build it into my lab's pipeline. I have however seen a few odd things and I think something may be going wrong. 

I have followed your walkthrough for Big Data (training the model on a subset of samples that should and then denoising on the full set of samples that should have similar noise profiles). Subsequently I have been using both the assignTaxonomy and addSpecies functions to assign taxonomy as you discuss in your walkthrough and building a phylogenetic tree with phangorn as you describe in your f1000 paper. 

Here is the tree I get and the tips labeled by phylum. Note if no color is associated with a tip it means that tip  was assigned NA from taxonomic assignment at the Phylum level.

![image](https://cloud.githubusercontent.com/assets/452422/19530320/646442d4-9601-11e6-92f8-39b96d237bd5.png)

As you can see there are only a minority of sequence variants that are able to be identified at the Phylum level. 

Using the Silva training sets here are the percentages of sequence variants assigned (not NA) at different levels (the results are about identical for the RDP).

```
> colSums(!is.na(tax_table(ps)))/nrow(tax_table(ps))
  Kingdom    Phylum     Class     Order    Family     Genus   Species 
0.9042985 0.2789943 0.2741281 0.2668289 0.2635848 0.2311436 0.0486618  
```
 
I feel like my processing pipeline follows your suggestions pretty closely: (1) remove primers with trimmomatic (2) sync the barcodes files with the now trimmed sequence files (3) demultiplex without quality filtering using Qiime (4) filter paired reads using dada2 (4) denoise using dada2.  Note: my data is split over two sequencing runs and I denoise separately and combine at the end. 
Note: bimera checking resulted in 30% of reads being flagged as bimeras. This seemed quite high to me and did not change with or without trimmomatic.

I have put together a zip file containing a subset of the data (part of the s1 run) from after filtering, the output from my filtering script, my denoising script (dada2.R), and the short scripts I use to assign taxonomy and build the phylogeny. Available here: [https://dl.dropboxusercontent.com/u/4314134/bioreactor_subset.zip](https://dl.dropboxusercontent.com/u/4314134/bioreactor_subset.zip)

I do appreciate that the majority of these taxonomically unresolved sequence variants are very low abundance and that together those that are unresolved at the phylum level represent only a fraction of a percent (0.01%) of my total reads. However I must say, even with that explanation the tree still looks very strange to me, where are these very unrelated low abundance sequence variants arising from? 

Any help would be much appreciated, 
Thank you again, 
Justin

**Comment by jsilve24** [comment]
So I may have solved think PhiX contamination may be to blame...
I plotted the same tree at the Kingdom level:
![image](https://cloud.githubusercontent.com/assets/452422/19532182/9edcb412-9608-11e6-921a-202f9c3e6cec.png)

And then took a few of the Eukaryota sequences and ran them through BLAST - 3/3 so far have mapped to PhiX. 

Now the question becomes 
(1) Does this make sense? 
(2) How should I go about removing PhiX? My initial thought is to keep my dada2 pipeline the same and once I have the inferred sequence variants to check each of them to see if they map to PhiX. I am just concerned as to whether leaving these reads in during denoising and chimera checking could cause problems with the inference of the Bacterial sequence variants?  Thoughts?

**Comment by jsilve24** [comment]
I think perhaps you have already answred my question:
Just found the 'rm.phix=TRUE' option from fastqPariedFilter.  

I am going to try that and see if my results improve.

**Comment by benjjneb** [comment]
You're too fast, I was just checking for phiX myself!

You are right that removing phiX at the filtering step with `rm.phix=TRUE` is the best and recommended approach, because keeping the phiX sequences around slows down all the subsequent processing. However, since you've already processed the data, you can also remove phiX from your sequence table:

```
isphi <- isPhiX(getSequences(seqtab.nochim))
seqtab.nochim.nophi <- seqtab.nochim[,!isphi]
```

**Comment by benjjneb** [comment]
One more comment about the high fraction of chimeric reads being identified (and 30% of **reads** is high).

I am now using a consensus method to identify chimeras in many-sample datasets. In short, chimeras are identified in each sample individually, and then a "consensus" decision is made for each sequence variant as to whether it is chimeric based on the sample-by-sample results. By default a sequence variant must be identified as chimeric in ~90% of samples to be flagged chimeric.

I am finding it to be more accurate, in that it reduces FP chimera identification that can occur for variants very near to other variants (Robert Edgar discusses this issue in his recent UCHIME2 preprint).

This might be worth at least testing on your data (although I generally see only ~1% more reads pass chimera removal as compared to the default pooled approach):

```
seqtab.nochim <- removeBimeraDenovo(seqtab, tableMethod="consensus")
```

ps. You'll need version 1.1.6 or later for this functionality. See `?isBimeraDenovoTable' for more details on the consensus method.

**Comment by jsilve24** [comment]
I like this consensus chimera detection idea. I will try this out. I also have suspicion that the high rate is due to too many PCR cycles when amplifying for sequencing (i.e., not a data analysis problem). 

Thank you!
