### ISSUE TITLE
cutting a band in-silico

### ISSUE THREAD

**Issue by dikiprawisuda** [benjjneb/dada2#1412]
Hi, thank you for your hard work.

In the tutorial section of "Construct sequence table", there are in-silico cutting step.
In the example, sequence length distributions is quite narrow (251 to 255). My samples however is not looking like that, ie they are verry wide. Is this normal? 
My target amplicon should have ~443 bp (V3-V4), but what I have are ranging from 248 to 413. Normally I would have cut the right-end with subjectively acceptable number, i.e. tail-peak-tail.

Thank you in advance

Diki.

**Comment by benjjneb** [comment]
The V3V4 region of the 16S gene has some natural biological variation in length, which usually shows up as two modes about 20 nts different in length.

The variation you are seeing at the low end is beyond what is expected. I would inspect the histogram of ASV lengths, and the histogram of read lengths (i.e. ASVs lengths wieghted by their abundance) to see if the two expected V3V4 peaks are clear. Then I would either "cut" to keep those two peaks, or further inspect the low-length tail and make a determination based on what those ASVs look like (e.g. they might be off-target mitochondria amplification, but could be something else).

**Comment by dikiprawisuda** [comment]
Thank you very much for your prompt reply.

For example, if these off-target mitochondria amplification are kept, will they be assigned to taxonomy later?
