### ISSUE TITLE
Dereplication step removed from tutorial?

### ISSUE THREAD

**Issue by LaraMacheriotou** [benjjneb/dada2#1415]
Dear Mr. Callahan, 

I have been using DADA2 since 2015; first thank you for this contribution and for providing so much support to the user community. 

I recall that prior to inferring ASVs, the filtered reads (`filtFs, filtRs`) undergo dereplication to yield the objects `derepFs`, `derepRs`. These are then fed into the `dada` command which requires an object of class `derep`. The current tutorial online no longer includes this step;  the `filtFs`, `filtRs` are fed into the `dada` command. I think this would not work as the output of `filterAndTrim` is a matrix while `dada` needs a `derep-class`. 

Am I mistaken or did I miss a step? Any clarifications would be greatly appreciated, thank you!

Lara

**Comment by benjjneb** [comment]
See https://github.com/benjjneb/dada2/issues/1095#issuecomment-671333174
