### ISSUE TITLE
Question about number of OTU reported by DADA2

### ISSUE THREAD

**Issue by mentorwan** [benjjneb/dada2#142]
Thanks for great tools for open reference OTU picking method. 

I have run on our local artificial community data. It supposed to be from 20 bacteria strains. We have that sequences. 

After I run DADA2,  I used very stringent way to do filtering:

for(i in seq_along(fnFs)) {
  fastqPairedFilter(c(fnFs[i], fnRs[i]), c(filtFs[i], filtRs[i]),
                    trimLeft=c(10, 10), truncLen=c(240,160), 
                    maxN=0, maxEE=1, truncQ=19, 
                    compress=TRUE, verbose=TRUE)
}

After chimera removal, I still get 117 sequences. I compared those sequences with 20 sequences we have, 18 of them have exact matches, 2 of them have only one or two NA differences.  But the problem I have is that we still have much more sequences than what samples have. 

However, I run MiSeq_SOP examples and got exactly 20 sequences. Can you shed some lights on why I got a lot more OTU cases?

One more question, for other pipeline (Mothur and QIIME), it will generate OTU first, and then do clustering to get OTU representative sequences such as get.oturep in Mothur and pick_rep_set in QIIME. Does DADA2 need to do that or not? 

Thanks a lot.

**Comment by benjjneb** [comment]
There are a couple reasons why there may be many more sequence variants than expected in your mock. Could you BLAST a couple of the unexpected sequences and see what they are hitting (and if they are hitting things exaclty)? That will help diagnose the issue.

Also, could you post the total reads in the mock sample after processing, and the fraction of reads that are from unexpected variants?

For the second question: DADA2 is inferring the sequence variants exactly. There is no "representative" sequence that needs to be later picked -- the sequence assigned by DADA2 is the sequence of those reads after errors are removed.

**Comment by mentorwan** [comment]
20 matched one has 287335 reads (96%). Attach a table with 117 sequences and their taxonomy analysis if I am doing correctly. It worths to note that two matches are only with 9 reads.
[taxa.txt](https://github.com/benjjneb/dada2/files/542407/taxa.txt)

Thanks you very much!

Yunhu Wan

**Comment by joey711** [comment]
A clarification, @mentorwan , but DADA2 is **not** an open reference OTU picking method. For starters, it is not an OTU picking method. The step to classification output sequences, while useful, is not the DADA2 algorithm, but a convenience utility included with the dada2 package. 

For some additional discussion and details about why/how it is not an OTU picking method, see the following issue thread:

https://github.com/benjjneb/dada2/issues/62

**Comment by mentorwan** [comment]
Thanks @joey711. I got a lot of information from the post you provided. I understand differences between DADA2 output and traditional OTUs.  After my tryout, I found very high resolution sequences been picked out. I have no doubt about that. 

For my case, I just want to learn how to get best sequence features or RSV(whatever terminology) in my mock samples. The result was generated from 18 AC samples. I am very interested in post 98.  Will removing single-sample variant , blasting for sequence similarity etc will work? The goal is to reduce potential false positive. Can you shed some lights on that? Thanks

**Comment by benjjneb** [comment]
Taking a look at the non-mock sequences, I think the likely explanation for most of them is contamination.

17 of the sequences are phiX sequences from the Illumina spike-in, and so are clearly contamination (these are easy to remove, see discussion here: #141).

I BLAST-ed ~10 of the remaining non-matching sequences, and every one was an exact hit (100% ID/100% coverage) to previously observed sequences, strongly suggesting that they are contaminants and not uncorrected sequence errors. Additionally, some of the more abundant non-mock sequences look to be thing like Sphingomonas that are known to be common kit contaminants.

Contamination, both from kits and from cross-talk between multiplexed samples, is an issue, and as you sequence more deeply you will find more contaminants. Removing contaminants is not a solved problem at this point, so you'll have to live with some of them, especially amongst the very rare sequences.

(We are working on a method to remove the kit contaminants, which tend to be the highest abundance contaminants, but its not available yet.)

ps. The most abundant non-matching sequence probably is not a contaminant, but rather an intra-genomic 16S rRNA variant in the Bilophila genome: It's 1-off of the expected mock sequence (which is also observed) and has an abundance in about a 1:3 ratio with the expected mock sequence, which fits the fact that that Bilophila wadsworthia has 4 rRNA genes according to PATRIC. The 20 mock strains contain 21 different sequence variants over this gene region.

**Comment by mentorwan** [comment]
Perfect. Thanks a lot! @benjjneb

**Comment by mentorwan** [comment]
Sorry for bothering you @benjjneb. It will be my last questions. Can you clarify your last sentence: "The 20 mock strains contain 21 different sequence variants over this gene region"?

I do see some new one sq24 (Acinetobacter) and sq22 (Phyllobacterium). Are they cross-talk contaminations from real samples? Is following assumption correct: If sequences predicted can find exact match in Blast so it mostly likely inside samples? Thanks.

**Comment by benjjneb** [comment]
One of the strains (Bilophila) has two different 16S rRNA variants in its genome. That means that 2 sequence variants are outputted for that strain, and hence 21 real sequence variants are present in the 20 mock strains.

One the second point, if sequences predicted are exact BLAST hits, they are probably comtaminants. But contaminants can come from both kit contaminants (DNA in the extraction kits or other parts of the wet lab prep), and from "cross-talk" between the samples you ran.

**Comment by mentorwan** [comment]
Appreciated for great tools. No more questions.
