### ISSUE TITLE
Error in getUniques(x) when running sapply(dadaFs, getN)

### ISSUE THREAD

**Issue by tamerhage** [benjjneb/dada2#1421]
Hello, 

I am new to R and running fast files through this dada2 and getting these two errors from this section of the code: 

Code: 
track <- cbind(out, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers, getN), rowSums(seqtab.nochim))
# If processing a single sample, remove the sapply calls: e.g. replace sapply(dadaFs, getN) with getN(dadaFs)
colnames(track) <- c("input", "filtered", "denoisedF", "denoisedR", "merged", "nonchim")
rownames(track) <- sample.names

Error in getUniques(x) : 

1st error: 

Unrecognized format: Requires named integer vector, fastq filename, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns. > # If processing a single sample, remove the sapply calls: e.g. replace sapply(dadaFs, getN) with getN(dadaFs)

second error: 

> colnames(track) <- c("input", "filtered", "denoisedF", "denoisedR", "merged", "nonchim")
Error in colnames(track) <- c("input", "filtered", "denoisedF", "denoisedR",  : 
  object 'track' not found
> rownames(track) <- sample.names
Error in rownames(track) <- sample.names : object 'track' not found

Does anyone know a fix? I read previous posts about similar errors and I am using more than one file in my input.

**Comment by benjjneb** [comment]
Are you processing a single sample, or multiple samples?
If a single sample, did you try the suggested remedy?

If it is multiple samples, try each of these commands individually. Is the error arising in just one of them?

```
sapply(dadaFs, getN)
sapply(dadaRs, getN)
sapply(mergers, getN)
```

**Comment by tamerhage** [comment]
Hi, Thank you for the response. I am processing multiple samples. I ran each of those individually and got the same error for each:

Error in getUniques(x) : 
Unrecognized format: Requires named integer vector, fastq filename, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.

**Comment by otaviolovison** [comment]
Hello @benjjneb! I have the same issue.

I performed both suggested test above, with the following output:

> table(sapply(ddF1, class))
Error in table(sapply(ddF1, class)) : 
  all arguments must have the same length
> class(ddF1)
[1] "dada"
attr(,"package")
[1] "dada2"
> sapply(ddF1, getN)
Error in getUniques(x) : 
  Unrecognized format: Requires named integer vector, fastq filename, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.

Any suggestions?

Thanks in advance!

**Comment by benjjneb** [comment]
If you are dealing with a single sample, you shouldn't use `sapply` here, but just directly call `getUniques` or `getN` to your dada-class object. Since the dada-class object is also a list, when `sapply` is called on a single dada-class object, it tries to apply the function to each element of the dada-class list, which yields this error.

When working with multiple samples, you have a list of dada-class objects, and `sapply` works as expected.
