### ISSUE TITLE
truncLen on filterAndTrim and relation with taxonomy classification 

### ISSUE THREAD

**Issue by Donandrade** [benjjneb/dada2#1422]
Dear, @benjjneb !

A company performed a metabarcode sequencing (V3-V4 regions of the 16S rRNA gene) and sent to me the paired reads, already trimmed. The reads F and R came with the average lengths of 265 and 205 bp, respectively. Even so, I still cut 20 base pairs from the ends to eliminate barcode sequences.

**The first question is:**
Considering the above information, what would be the most suitable values ​​for the "truncLen" parameter of the filterAndTrim function?

I'm asking that because I'm testing some values ​​and I see that it has a big impact on the amount of sequences and taxon diversity identified. One of the tested values ​​(truncLen=c(250, 180)) generated, in the later steps, the object "seqtab.nochim" with 1360 non-chimeric sequences. For me, this is a good number of sequences, however, the diversity and quantity of taxon obtained, in the taxonomic classification, is far from what I expected. I already know a little of these communities, and the results really aren't very coherent with what I expected. So, I think I'm not using the most suitable parameters during the analysis.
Just to complete with some more information, the sequencing generated around 841,164,898 bases. My overall abundance graph is this one below:

![image](https://user-images.githubusercontent.com/3967276/136459607-87bb3529-5344-4723-b89b-0e4e12c13426.png)
![image](https://user-images.githubusercontent.com/3967276/136459631-08b2e318-d503-439b-989f-c512fcc1335e.png)

With that, **my second question is**:
Besides the "truncLen" parameter, could you suggest the best approach to try to help me get the most reliable and coherent results?

Since then, thank you very much for your attention here on the forum

At.te
Edson Andrade

**Comment by s-christel** [comment]
I am not sure actually, I think because this primer sequence will be universal for all your reads, many people remove it.
