### ISSUE TITLE
Error in filterAndTrim

### ISSUE THREAD

**Issue by rtavares96** [benjjneb/dada2#1426]
after running, filterAndTrim(fnFs, fnFs.filtN, fnRs, fnRs.filtN, maxN = 0, multithread = TRUE), I received this error message.

scheduled core 26 encountered error in user code, all values of the job will be affectedError in filterAndTrim(fnFs, fnFs.filtN, fnRs, fnRs.filtN, maxN = 0, multithread = TRUE) : 
  These are the errors (up to 5) encountered in individual cores...
Error in (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0,  : 
  Mismatched forward and reverse sequence files: 77263, 100000.

How do I identify the problem files? I did run this once before and my RStudio crashed so it didn't fully execute. I'm thinking that is probably the issue, some files were already filtered out previously causing the mismatch. How do I confirm this? I hate to move forward with cutadapt without knowing for sure the filtn worked.

**Comment by benjjneb** [comment]
See https://github.com/benjjneb/dada2/issues/1413

Can you go through the same initial troubleshooting steps as described there?

**Comment by benjjneb** [comment]
@rtavares96 Sorry, can you repeat that code using `fnFs` and `fnRs`? Was a typo that I had `filtFs` and `filtRs` there.

**Comment by btupper** [comment]
> @btupper The regression caused by the Matrix 1.3.3 package Mnumeric change is fixed in the latest release version 1.20. See here: [#1378 (comment)](https://github.com/benjjneb/dada2/issues/1378#issuecomment-881815297)

Thanks - I'm sorry that I missed that in the closed issues.
