### ISSUE TITLE
how to extract all merged reads at once

### ISSUE THREAD

**Issue by marco2985** [benjjneb/dada2#1427]
I would like to extract all merged sequences into a fasta file. I have found information on how to extract all unique sequences by using this code uniques
ToFasta(getUniques(seqtab), fout="F:/MHC_VR/Dada2/uniqueSeqs.fasta", ids=paste0("Seq", seq(length(getUniques(seqtab)))))
 but I would like to extract all of them at once and tranformed them into a fasta file (all copies). Do you think that is possible?

Can you help me with that?
Thank you very much in advance

**Comment by marco2985** [comment]
That is very useful. Thank you very much. I am not using DADA for
microbiome analyses this time. Therefore, I do not have "ASV", Is that a
problem. Can I change ASV by MHC for example?

Actually, I would like to ask another related thing:  I am working with
around 300bp MHC  sequences (major histocompatibility complex class II
exon2). I had some problems with the MIseq run and when I combine the reads
with other softwares like FLASH, I can only combine 32% of the reads. The
IT bioinformaticians from my university have suggested to used DADA2 for
combining forward and reverse reads by using "justconcatenated=TRUE" option
and I think it is working better than by using the other software. I have
done all this without demultiplexing the reads. I thought that I could
extract all the merged reads and then dimultiplex. However, they have
recommended to me to do the other way around. What is your suggestion? and
Is it a possible way of demultiplexing by using DADA2. The problem is that
my sequences has NNN- 8bp barcode- primer. Samples are dual index. Do you
think I can do it with DADA2?

Thank you very much,
Maria//

**Comment by benjjneb** [comment]
@marco2985 It sounds like what you need is a `for` loop, so you can loop through the different file names (and perhaps another to loop through the pools). This can all be done with base R commands, but the dada2 package doesn't really come in.
