### ISSUE TITLE
Error in assignTaxonomy on a BIG seqtab

### ISSUE THREAD

**Issue by padpadpadpad** [benjjneb/dada2#1429]
Hi

This problem is very similar to [Issue 961](https://github.com/benjjneb/dada2/issues/691).

The sequencing is from a big Novaseq run of the protein coding gene rpoB so I do have 400,000 unique sequences to assign. Is there anyway to do this in batches?

An earlier run of ~40,000 sequences did assign fine. Which makes me think it is the number of sequences in `seqtab` rather than the reference database.

When trying to assign taxonomy. I am getting an error:

`Error in C_assign_taxonomy2(seqs, rc(seqs), refs, ref.to.genus, tax.mat.int, : negative length vectors are not allowed Calls: assignTaxonomy -> C_assign_taxonomy2`

When running it on a server. The server info is:

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS
```
I run it currently with 16 cores, but the error persists if I use 25. I have created a smaller reference database (going from 26000 sequences including species rank to 11000 including only down to genus level. The error persists.

Any thoughts much appreciated.

**Comment by benjjneb** [comment]
Yes you can go in batches, no difference in results since each sequence is being assigned individually w/in the function itself anyway.

**Comment by padpadpadpad** [comment]
Hi @mmanus. I suppose what I don't understand is how the taxa names for the OTU table and taxa table do not match? 

The tax table created from the sequence table automatically gives the rownames (taxa names) to be the same as for the sequence table.

The string of characters (i.e. the DNA sequence) should be unique for each row of the OTU (feature) table, because each row is a unique ASV and each column is their abundance in each sample. So if you have the EXACT same sequence has multiple rows they can be aggregated as I understand it.
