### ISSUE TITLE
removeBimeraDenovo and multithreading

### ISSUE THREAD

**Issue by jsilve24** [benjjneb/dada2#144]
Just a heads up on an error I ran into. 

The default behavior of removeBimeraDenovo is to call the tableMethod='pooling' I believe. This seems to call isBimeraDenovo which supports multithreading. 

setting tableMethod='consensus' calls isBimeraDenovoTable (I believe) which does not support multithreading. Therefore when I tried to change the tableMethod but keeping the rest of the code the same I got an error saying that the multithreading=4 argument was not used. 

Its a small issue but a little frustrating. Just wanted to bring it to your attention. Obviously multithreading for isBimeraDenovoTable would be great but save that could you modify the code to give a warning rather than throwing an error?

Thanks again for all the hard work!
Justin

**Comment by benjjneb** [comment]
Agreed, this should be a warning and not an error.

**Comment by benjjneb** [comment]
An appropriate message, and not an error, is now given when `tableMethod="consensus"` and `multithread=TRUE`: 6803e6fa9539cbbaaa6022df503a269fc7ead02a
