### ISSUE TITLE
Unexplained read loss during merging step 

### ISSUE THREAD

**Issue by SimonMorvan** [benjjneb/dada2#1440]
Hello @benjjneb and DADA2 community!

  I am having a very similar problem as issue #831 where I lose a considerable portion of my sequences during the merging step although I maintain a sufficient overlap. 
 
Context:
Soil samples
2x300 bp Illumina MiSeq sequencing
16S V3-V4 region with primers 341F-805R

For FilterAndTrim
I used maxEE(2,2) and truncLen(270,240) which should leave enough overlap.  
I removed the primers using trimLeft(17,21). Other settings were left at their default values.

I used pool = pseudo for dada2() and left the minimum overlap at 12bp. Here is what my track table looks like with 3 of my samples. 

![image](https://user-images.githubusercontent.com/32374188/138951961-67226485-e4df-4f39-ad22-9f2719b030e5.png)

At first, I thought there was a quality problem with the reads that was interfering with the merging step. However, the quality profiles of the filtered reads look okay.
![QP_filtered](https://user-images.githubusercontent.com/32374188/138952256-7b7e444d-7f9c-4c9e-8ac0-870c166da9c1.png)
Furthermore, when I use returnRjects = TRUE to generate the mergers object, there are very few rejects due to mismatches. The main reason of the rejected sequences seems to be that the nmatch is <12 with a lot of sequences matching only on 3bp. 

I’ve asked the sequencing provider about heterogeneity spacers as I saw this could explain a proportion not making it through the merging step. They responded that they did not use heterogeneity spacers but used staggered primers that look like this:  

Forward Primer | Sequence
341FP1-CS1 | CCTACGGGNGGCWGCAG
341FP2-CS1 | TCCTACGGGNGGCWGCAG
341FP3-CS1 | ACCCTACGGGNGGCWGCAG
341FP4-CS1 | CTACCTACGGGNGGCWGCAG

Reverse Primer | Sequence
805RP1| GACTACHVGGGTATCTAATCC
805RP2| TGACTACHVGGGTATCTAATCC
805RP3| ACGACTACHVGGGTATCTAATCC
805RP4| CTAGACTACHVGGGTATCTAATCC

I've tried being more stringent on the primer removal and changed truncLen from (17,21) to (20,24) in order to remove even the longest versions of the primers but the track table remains similar and I still lose a lot of reads during the merging step. 

![image](https://user-images.githubusercontent.com/32374188/138953183-cc8d39bb-6163-4bf1-aa6b-e039bdcccee2.png)

I really don't know what is going on. I've also sequenced the ITS communities of the same samples and I don't lose as many sequences during the merging step so something seems to be going on with the 16S dataset. 
 
I’ve included the 6 fastq files corresponding to the three samples containing the raw sequences obtained from the sequencing provider if you want to take a look.  	

[3B_16S_R1.fastq.gz](https://github.com/benjjneb/dada2/files/7421390/3B_16S_R1.fastq.gz)
[3B_16S_R2.fastq.gz](https://github.com/benjjneb/dada2/files/7421391/3B_16S_R2.fastq.gz)
[5A_16S_R1.fastq.gz](https://github.com/benjjneb/dada2/files/7421246/5A_16S_R1.fastq.gz)
[5A_16S_R2.fastq.gz](https://github.com/benjjneb/dada2/files/7421247/5A_16S_R2.fastq.gz)
[12B_16S_R1.fastq.gz](https://github.com/benjjneb/dada2/files/7421271/12B_16S_R1.fastq.gz)
[12B_16S_R2.fastq.gz](https://github.com/benjjneb/dada2/files/7421272/12B_16S_R2.fastq.gz)

Thank you for your help !

**Comment by benjjneb** [comment]
That looks like the primers are being effectively removed, so I am somewhat confused about why there is still a merging issue.

Can you attach the exact cutadapt/DADA2 script you are running, so I can try to reproduce on the three example files you provided?

**Comment by SimonMorvan** [comment]
Absolutly,
Script 1 is the original script I used based on your recommandation.
[Script1.docx](https://github.com/benjjneb/dada2/files/7462068/Script1.docx)

I've also tested Script 2 after talking to a bio-informatician who advised me to only put the longest versions of the primers and their RC into cutadapt and to add some parameters to cutadapt (overlap = 7, discard-untrimmed, minimun-length = 220,220 and pair-filter=any). I've checked that the other versions of the primers were effectively removed after cutadapt. 
[Script2.docx](https://github.com/benjjneb/dada2/files/7462070/Script2.docx)

Even with those adjustments, the track stays similar.
               input     filtered denoisedF denoisedR merged nonchim  ID
3B_16S  103150    83947     74405     80139  45066   29042  3B_16S
5A_16S  101317    83210     74684     80091  49469   38389  5A_16S
12B_16S  99173    80767     69632     76137  37528   24235 12B_16S

I've looked at the rejected sequences that did not make it through that merging step. Some of them are rejected because of a mismatch or an indel in the overlap, but it's a minority. Most of the rejected sequence are removed because the overlap between 2 sequences is <5bp when the overlap I've set is 12bp. I have a hard time understanding what is causing this. I trim down the sequences to 270,240 after cutadapt which should leave enough overlap as the 16 V3V4 amplicon is supposed to be around 460bp. 

Thank you for your time!

**Comment by SimonMorvan** [comment]
Hi Ben, 

Have you had the time to check if something was off with the sequences or with how I was treating them ? 
Although I loose a lot of reads during the merging step, the rarefaction curves show I reach a plateau so I guess I will continue on with my analysis unless you believe I should try something else. 

Thank you for your time!

Simon

![Rarefaction_curve](https://user-images.githubusercontent.com/32374188/142888099-275b6681-ca77-4b6f-9cb5-62c429afa16d.png)

**Comment by gcuster1991** [comment]
Hi Simon and Ben, I am experiencing this exact issue with the same primer pair on the same sequencing platform. Even after removing primers with cutadapt, I am still only retaining ~ 19% of my reads through the entire pipeline, with the majority being lost at the merger step. Was the root of this issue ever tracked down?

**Comment by SimonMorvan** [comment]
Hi @gcuster1991, in my case I continued on with my analyses as the rarefaction curves were looking okay. 
It's still a bit frustrating to keep such a small percentage of your sequencing dataset..

**Comment by Mehrdad-M3614** [comment]
> Hi Ben,
> 
> Have you had the time to check if something was off with the sequences or with how I was treating them ? Although I loose a lot of reads during the merging step, the rarefaction curves show I reach a plateau so I guess I will continue on with my analysis unless you believe I should try something else.
> 
> Thank you for your time!
> 
> Simon
> 
> ![Rarefaction_curve](https://user-images.githubusercontent.com/32374188/142888099-275b6681-ca77-4b6f-9cb5-62c429afa16d.png)

Hello Simon, 
I am trying to make rarefaction curves for my reads to see if they reach to plateau. Would you be able please to share the code that you used for extracting the rarefaction curves plot, here? Thanks and regards!

**Comment by Aline-Git** [comment]
I'm not sure that rarefaction analysis is the guaranty that you did not introduce a bias in your analysis.

In my case I noticed that the merging step failed preferentially for specific taxa. 

By using 
```
mergers_diag <- mergePairs(dadaFs[[sample]], derepF[[sample]],
                                   dadaRs[[sample]], derepR[[sample]],
                                   minOverlap = 20,
				   returnRejects = TRUE,
                                   maxMismatch = 1,
                                   verbose = TRUE)
```
The table mergers_diag gives the reason why it fails (too short overlap or too many differences).

In my case, there are two types of fails:
- the first type is long overlap (>80bp) but too many differences -> this one will I hope be solved by trimming the reads more agressively toward the end.
- the second type is overlap of 1bp that partly seem to be due to the denoising step collapsing microdiversity. Using pool="pseudo" in the denoising step (dada()), decreased the number of this type of merge fails.
