### ISSUE TITLE
Minimun reads per sample after removeBimeraDenovo

### ISSUE THREAD

**Issue by sarpiens** [benjjneb/dada2#1443]
Hello,

I have found an old thread where is said that Chimeras as a percentage of sequences should be less than 30% generally (https://github.com/benjjneb/dada2/issues/236).

However, I have a few doubts regarding this:

a) I wonder how the type of sample influences this? I.e. would this criterion apply equally to human fecal samples compared to environmental samples? I don't know if a higher number of chimeras would be expected in one type of sample than others.

b) On the other hand, this criterion seems to refer to the average of the dataset, but I wonder what would be an appropriate threshold per sample? Because there maybe cases in which this criterion is met for all samples as a whole, but not in individual samples.

I.e. I have a large dataset of samples (225 samples), and after eliminating chimeras, I went from aprox. 130 thousand to 20 thousand ASVs (losing aprox. 80% of the ASVs), which means losing 9.9% of all reads with respect to the previous step in my case. However, when I look at the data for each sample, I see some samples that retain only 50-70% of the reads compared to the previous step, and thus would not met the 30% loss criterion. 

c)  Finally, I think that there may be cases where a large fraction of sequences are lost in this step with respect to the input in a particular sample, but that at the end of the DADA2 processing this sample could retain a considerable or "enough" number of reads. What would be advisable, to continue and retain these samples or to eliminate them, even if we have "enough" reads at the end?

Thanks in advance

**Comment by benjjneb** [comment]
> if it has enough reads at the end of the DADA2 processing, and not eliminate it a priori, correct?

Yes that is what I would normally do.
