### ISSUE TITLE
Processing non-directional libraries with primers containing ambiguous bases

### ISSUE THREAD

**Issue by mimouschka** [benjjneb/dada2#1447]
Hi @benjjneb,
first of all, thanks for DADA2, such an amazing tool!
I have been reading issues #451 and #167 about dealing with data prepared through adapter-ligation based libraries.
Following issue #451 , you updated the `orient.fwd` parameter in `filter and trim` to reorient both single-end and paired-end fastq data, but it seems that this parameter does not accept character strings with ambiguous nucleotides (https://github.com/benjjneb/dada2/blob/master/R/filter.R).

My problem is that I have ligation-based libraries and 4 primer pairs all containing ambiguous bases...
I noticed that DADA2 now has a `removePrimers` function that also includes read re-orientation (`orient=TRUE`), but where `primer.fwd` and `primer.rev` allow ambiguous IUPAC codes.
Although you specify that this function is _Intended for use with PacBio CCS data_ can I still use it on illumina data, even though it may be slower than cutadapt or trimmomatic?

Thanks for your feedback!

**Comment by benjjneb** [comment]
If there are enough non-ambiguous nucleotides at the start of the primers, you can just use that partial sequence with `orient.fwd`. You just want enough nucleotides to avoid random matching, but 6 is plenty and even 4 is probably enough.

You can use `removePrimers`, but it just isn't optimized to reach acceptable (IMO) performance on high-depth Illumina data. For that reason, an `orient.fwd` or other software solution is usually preferable with Illumina.

**Comment by mimouschka** [comment]
Thanks so much, this is very clear!
I unfortunately have ambiguous nucleotides at the 3rd and 4th position (from the 5' end)... so I guess I will have to either use `removePrimers` or find another faster solution.
