### ISSUE TITLE
Incorrect class level identification using the reference database silva_nr99_v138.1

### ISSUE THREAD

**Issue by AritriSanyal** [benjjneb/dada2#1449]
Hi - I have used the reference database silva_nr99_v138.1_train_set and the silva_species_assignment_v138.1 data set through dada2 for identifying the amplicon sequences generated from the V4 region. However, there is a mistake in the class level identity. The class beta-proteobacteria seems to have been omitted and all the bacteria from that class have been assigned the class gamma-proteobacteria.  For example, one ASV has been identified as Curvibacter at the genera level, which belongs to beta-proteobacteria, but the class level taxonomic assignment for the same is showing as gamma-proteobacteria. I have downloaded the database again, and run the analysis, but the same problem persists.

**Comment by AritriSanyal** [comment]
I ran the same dataset with the silva_species_assignment_v132 reference data, with and without species assignment, both of which show the same error as mentioned before, where the class level taxonomic assignment is incorrect. However, I wasn't able to run the analysis using the arb files from silva directly as I do not have the bandwidth.

**Comment by benjjneb** [comment]
See this from [the release notes for Silva v132](https://www.arb-silva.de/documentation/release-132/):

> Proteobacteria drastically rearranged. Epsilonproteobacteria are own phylum, Betaproteobacteria now an order of Gammaproteobacteria.

**Comment by AritriSanyal** [comment]
Thank you for the clarification, I did miss the release note.
