### ISSUE TITLE
Is nonchimeras reads means final reads? Will assign taxonomy filter certain reads ?

### ISSUE THREAD

**Issue by phxu452** [benjjneb/dada2#1450]
Hi. I used DADA2 pipeline to conduct 16s sequencing, and the reads after each step are checked and showed as attached. I wonder is nonchimeras reads are final reads? As after the nonchimeras, I did taxonomy assign and write ASV count and taxonomy tables out and import to ampvis2. By both ampvis2 and a manual way, the final raw reads are lower than the one showed in nonchimera. Therefore, I wonder does taxonomy assign step also filter reads out or not? Otherwise, what the reason for the reads to be less after nonchimera?

[reads from DADA2.docx](https://github.com/benjjneb/dada2/files/7555625/reads.from.DADA2.docx)

**Comment by benjjneb** [comment]
`assignTaxonomy` won't classify every read to a specific taxonomic level, e.g. Genus. Some reads don't have enough information for the method to distinguish e.g. Genus. So, my first thought is that the read counts you are examining that have fewer reads than were present after chimera removal are limited to those reads which received a classification at some specific taxonomic level.

**Comment by phxu452** [comment]
Thanks very much for your reply. The assign taxonomy table could show up even only in Kingdom level (with Phylum Na...). But I guess the filtered reads may not be able to be assigned even into Kingdom level or they are not presence in the database.

**Comment by benjjneb** [comment]
If a lot of your ASVs are not being assigned even at the "Phylum" level, you should try to understand why that is. It could be amplification of non-target material, it could also be a technical issue, such as the reads being in the opposite orientation to the reference database (that is easily checked with `assignTaxonomy(..., tryRC=TRUE)`.

But it's worth taking a look at that. Just [BLASTing](https://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE_TYPE=BlastSearch) a few of the more abundant Kingdom unclassified sequences against nr/nt is often very informative.
