### ISSUE TITLE
HOMD-training set formatted for dada2

### ISSUE THREAD

**Issue by kilaza** [benjjneb/dada2#1451]
Hi, I am working with the nasopharyngeal microbiome data and I am interested to use HOMD database for taxonomy assignment. I have tried to format HOMD trained to be used in the dada2 pipeline without success. I would appreciate any help on this. 
Thanks,
Sam

**Comment by benjjneb** [comment]
We don't have an official or contributed version of HOMD, but the description of the reference format file for `assignTaxonomy` is here: https://benjjneb.github.io/dada2/training.html#formatting-custom-databases

Do you have a more specific question about that format?

**Comment by fconstancias** [comment]
You can find the latest eHOMD database formated for dada2 (i.e. dada2::assignTaxonomy(seqs, "eHOMD_RefSeq_dada2_V15.22.fasta.gz" and dada2::addSpecies(taxa, "eHOMD_RefSeq_dada2_assign_species_V15.22.fasta.gz", verbose=TRUE) [here](https://github.com/fconstancias/metabaRpipe/tree/master/databases). 
Happy to include those into the https://benjjneb.github.io/dada2/training.html
