### ISSUE TITLE
Cyanobacteria proportion of each sample in a phyloseq object

### ISSUE THREAD

**Issue by paulaguastello** [benjjneb/dada2#1453]
Hi, I am trying to do multiple regression to determine what impacts proportion of cyanobacteria in each sample.  How can I pull out the proportion of cyanobacteria of each sample in my phyloseq object?

**Comment by benjjneb** [comment]
You'll want to ask questions about phyloseq on the phyloseq issues page: https://github.com/joey711/phyloseq/issues

**Comment by paulaguastello** [comment]
New to github, sorry! Thanks!
