### ISSUE TITLE
Running time

### ISSUE THREAD

**Issue by AkilaMuthalagu** [benjjneb/dada2#1454]
HEllo Ben,

I ran the below code and its running for more 60hrs now. I have in 22 samples and bit confused/worried about the running time. Does it usually takes this much time?

fitGTR <- optim.pml(fitGTR, model="GTR", optInv=TRUE, optGamma=TRUE,
+                     rearrangement = "stochastic", control = pml.control(trace = 0))

**Comment by benjjneb** [comment]
You'll want to post this issue at the Github issues forum for the F1000 workflow: https://github.com/spholmes/F1000_workflow

Please also check out the previous issues there, several of which have been about the run-time scaling of tree-building using phangorn, including some solutions using external tools like RaxML.
