### ISSUE TITLE
Issues with data frame making

### ISSUE THREAD

**Issue by AkilaMuthalagu** [benjjneb/dada2#1456]
Hello there,

Can anyone explain me the below code, because when I try the final output says FALSE. Attached is the format of my csv file. I am interested to keep ( Sample ID, Sample name,	Subject,	Activity)

[Metadata_Akila.csv](https://github.com/benjjneb/dada2/files/7595551/Metadata_Akila.csv)

samdf <- read.csv("https://raw.githubusercontent.com/spholmes/F1000_workflow/master/data/MIMARKS_Data_combined.csv",header=TRUE)
samdf$SampleID <- paste0(gsub("00", "", samdf$host_subject_id), "D", samdf$age-21)
samdf <- samdf[!duplicated(samdf$SampleID),] # Remove dupicate entries for reverse reads
rownames(seqtabAll) <- gsub("124", "125", rownames(seqtabAll)) # Fix discrepancy
all(rownames(seqtabAll) %in% samdf$SampleID) # TRUE
## [1] TRUE

**Comment by benjjneb** [comment]
You're going to want to take a look at the help text for `read.csv` with `?read.csv`.

IN particular, the csv file you are using starts with a `#`, which by default will cause that line to be ignored by `read.csv(..., comment.char=#)`. Also, if your rownames are the first column, you can describe that with `read.csv(..., row.names=1)`.

Long term it is highly useful to get to know some of the basic options for these tabular import commands, so as to handle the many minor variations in formatting that exist in these file types.

**Comment by karapareddy15** [comment]
Hello benjjneb,

I runned the code, even I got the false, but Sample_data shown as "NA".
Would you please help me.
Thank you in advance.

samdf <- read.csv("C:/Users/karap/Downloads/Ala.sol/ITS_sample-metadata_sow.csv", header=TRUE)
> samdf$SampleID <- paste0(gsub("0", "", samdf$host_subject_id), "D", samdf$rep-1)
> samdf <- samdf[!duplicated(samdf$SampleID),] 
> head(samdf)
                  sample_id host_subject_id rep groups site.name   location Latitude Longitude           field     crop      date     barcode.sequence
1 zr13068_1ITS2_R1.fastq.gz         zr13068   1      A       CUL Hanceville 34.09316 -86.84925 RN-Not-Detected  Soybean 10/4/2023 ACTCGGCAATTTCAGTTGTC
3 zr13068_2ITS2_R1.fastq.gz         zr13068   2      A       CUL Hanceville 34.09313 -86.84909 RN-Not-Detected  Soybean 10/4/2023 GTCTAATGGCCCTGACCACT
5 zr13068_3ITS2_R1.fastq.gz         zr13068   3      A       CUL Hanceville 34.09311 -86.84913 RN-Not-Detected  Soybean 10/4/2023 CCATCTCGCCAACCATAGAA
  SampleID
1 zr1368D0
3 zr1368D1
5 zr1368D2
> samdf <- samdf[!duplicated(samdf$SampleID),] 
all(rownames(seqtabAll) %in% samdf$SampleID)
[1] FALSE
 rownames(samdf) <- samdf$SampleID
> head(rownames(samdf))
[1] "zr1368D0" "zr1368D1" "zr1368D2"
> keep.cols <- c( "groups", "site.name", "location",
+                "Latitude", "Longitude", "field", "crop", "date",
+                "barcode.sequence", "SampleID")
> head(keep.cols)
[1] "groups"    "site.name" "location"  "Latitude"  "Longitude" "field"    
> samdf <- samdf[rownames(seqtabAll), keep.cols]
> head(samdf)
     groups site.name location Latitude Longitude field crop date barcode.sequence SampleID
NA     <NA>      <NA>     <NA>       NA        NA  <NA> <NA> <NA>             <NA>     <NA>
NA.1   <NA>      <NA>     <NA>       NA        NA  <NA> <NA> <NA>             <NA>     <NA>
NA.2   <NA>      <NA>     <NA>       NA        NA  <NA> <NA> <NA>             <NA>     <NA>
NA.3   <NA>      <NA>     <NA>       NA        NA  <NA> <NA> <NA>             <NA>     <NA>
NA.4   <NA>      <NA>     <NA>       NA        NA  <NA> <NA> <NA>             <NA>     <NA>
NA.5   <NA>      <NA>     <NA>       NA        NA  <NA> <NA> <NA>             <NA>     <NA>

Enclosed CSV file:
[ITS_sample-metadata_sow.csv](https://github.com/benjjneb/dada2/files/14594253/ITS_sample-metadata_sow.csv)

**Comment by benjjneb** [comment]
The SampleID you are creating from reading in your metadata does not match the rownames of your sequence table. What are the rownames of your sequence table?

**Comment by karapareddy15** [comment]
head(rownames(seqtabAll),n=20)
 [1] "zr14068_1ITS2_R1.fastq.gz_NA"  "zr14068_2ITS2_R1.fastq.gz_NA"  "zr14068_31ITS2_R1.fastq.gz_NA" "zr14068_32ITS2_R1.fastq.gz_NA"
 [5] "zr14068_33ITS2_R1.fastq.gz_NA" "zr14068_34ITS2_R1.fastq.gz_NA" "zr14068_35ITS2_R1.fastq.gz_NA" "zr14068_36ITS2_R1.fastq.gz_NA"
 [9] "zr14068_3ITS2_R1.fastq.gz_NA"  "zr14068_40ITS2_R1.fastq.gz_NA" "zr14068_41ITS2_R1.fastq.gz_NA" "zr14068_42ITS2_R1.fastq.gz_NA" this are the row names in sequence table

**Comment by karapareddy15** [comment]
Appreciate your help.

Could you please help me, how to generate rds file in loading the data section.
