### ISSUE TITLE
assignTaxonomy yields different lineages for same ASV

### ISSUE THREAD

**Issue by weinmaier** [benjjneb/dada2#1457]
Hello,

I am running `assignTaxonomy` against the provided Silva database v138 with multithreading and default bootstrap cutoff of 50.
For logistical reasons I process every sample on its own.
While comparing multiple samples I noticed cases where two identical ASVs in different samples receive slightly different taxonomic classifications, e.g.
     Bacteria;Firmicutes;Bacilli;Bacillales;Bacillaceae;NA;NA
     Bacteria;Firmicutes;Bacilli;Bacillales;Bacillaceae;Anaerobacillus;NA
or
     Bacteria;Proteobacteria;Gammaproteobacteria;Pseudomonadales;Pseudomonadaceae;Pseudomonas;composti
     Bacteria;Proteobacteria;Gammaproteobacteria;Pseudomonadales;Pseudomonadaceae;Pseudomonas;NA

I don't see a trend towards higher or lower taxonomic levels or certain clades but the bootstrap values of the affected taxonomic
levels are always close to the cutoff value.

Is there a way for me to ensure that a given ASV sequence always gets the same taxonomic classification from `assignTaxonomy`?
I tried setting a common seed in all my runs but it did not change the outcome.

Cheers,
 Thomas

**Comment by benjjneb** [comment]
> Is there a way for me to ensure that a given ASV sequence always gets the same taxonomic classification from assignTaxonomy?

Don't process each sample individually. There is a random element to the algorithm implemented by `assignTaxonomy` that assigns the bootstrap confidence values, so assignments close to the threshold may or may not be assigned, as you are seeing here.

So, just do the assignments on the final collated sequence table. You can split that assignment step up into separate jobs (e.g. with 1k sequences per job) if you want.

**Comment by weinmaier** [comment]
Thank you for the advise, I'll do that.
