### ISSUE TITLE
feature request: identify ASVs coming from mitochondrial genome

### ISSUE THREAD

**Issue by wbazant** [benjjneb/dada2#1458]
I've been looking at a lineage "Bacteria;Proteobacteria;Alphaproteobacteria;Rickettsiales;Mitochondria", common in MicrobiomeDB data. We use DADA2 with 138_SSURef_NR99 version of Silva, which does not include human mitochondria.

I've found a paper from October 2020, doi:10.1038/s41598-020-73403-7 , "Non-specific amplification of human DNA is a major challenge for 16S rRNA gene sequence analysis". Apparently in samples with a lot of human DNA, the primers target the mito genome as well as the bacteria, which according to the authors happens particularly in V3-V4 samples.

In MicrobiomeDB this lineage is commonly present, looks to be very common in some samples ( not just in V3-V4, it's also in V1-V2 data) and in general it's more common in samples that have a lot of eukaryotic DNA, which loosely fits the hypothesis that this is human DNA.

When I BLAST one of the ASVs I got in our new V3-V4 dataset assigned to this lineage:

```
> Uganda Maternal V3-V4 dataset, example asv
ACAGGGGTATCTAATCCCAGTTTGGGTCTTAGCTATTGTGTGTTCAGATATGTTAAAGCCACTTTCGTAGTCTATTTTGTGT
CAACTGGAGTTTTTTACAACTCAGGTGAGTTTTAGCTTTATTGGGGAGGGGGTGATCTAAAACACTCTTTACGCCGGCTTCT
ATTGACTTGGGTTAATCGTGTGACCGCGGTGGCTGGCACGAAATTGACCAACCCTGGGGTTAGTATAGCTTAGTTAAACTTT
CGTTTATTGCTAAAGGTTAATCACTGCTGCCTCCCGTAGGGTCGTGACTGGGAAAA
```

using NCBI online BLAST, all the top hits indicate that this is from the human mitochondrion.

I'm keen to solve it, because it affects relative abundance results - in some samples these spurious Mitochondria that are supposedly in the microbiome form the majority of taxa.

@benjjneb have you seen this before, and also, would you have a suggestion about how to deal with this? Two possible paths that I see is extending the DADA2 R code with something like "rm.euk.mitochondria" similar to "rm.phiX" already present, or adding eukaryotic mitochondria to the reference and filtering it out later.

**Comment by cmmertz** [comment]
I think I am also running into this issue, about 100 out of my 2800 ASV's are categorized as Eukarya even though I used V4 primers for gut microbiome samples. Any thoughts on this? I plan to remove these in the decontam workflow, but was wondering if there is anything else available?

**Comment by wbazant** [comment]
@cmmertz you can just remove the ASVs that say Eukarya, no?

With mito genomes being reported as "Bacteria;Proteobacteria;Alphaproteobacteria;Rickettsiales;Mitochondria" it's slightly different because there can actually be bacteria lika that in the sample.

**Comment by benjjneb** [comment]
@wbazant The code to do something like this probably already exists in the `dada2` package. The `rm.phix` functionality in `filterAndTrim` is built on a simple word/kmer matching method implemented in `[dada2:::C_matchRef](https://github.com/benjjneb/dada2/blob/master/src/filter.cpp#L7)`. This code can take any reference sequence, it doesn't have to be a phiX genome as in the current wrapper function  `[isPhiX](https://github.com/benjjneb/dada2/blob/master/R/filter.R#L1180) that `filterAndTrim` calls.

That said, the challenge in implementing this into the package itself, is defining what the reference set of mitocondrial genomes should be, and testing the sensitivity/specificity. That second part in particular is more challenging than with phiX as there is sequence similarity betweeen mitos and bacteria.

**Comment by cmmertz** [comment]
Thank you for your response! This is an interesting challenge! For now I am going removing the Kingdom Eukarya ASVs from the DADA2 taxa table. Is that what you all recommend? Thanks again!

**Comment by wbazant** [comment]
@benjjneb I've re-emailed SILVA to see what they think about extending the reference -

> That said, the challenge in implementing this into the package itself, is defining what the reference set of mitocondrial genomes should be, and testing the sensitivity/specificity. That second part in particular is more challenging than with phiX as there is sequence similarity betweeen mitos and bacteria.

I agree! I guess adding the sequences to the reference corresponds to putting the decision boundary between Rickettsiales;Mitochondria and euk mitochondria straight in the middle of these two groups. If adding this as a separate function, I can choose another sensitivity/specificity tradeoff, but I should still make sure that legitimate Rickettsiales;Mitochondria do not get filtered out.

**Comment by benjjneb** [comment]
> I agree! I guess adding the sequences to the reference corresponds to putting the decision boundary between Rickettsiales;Mitochondria and euk mitochondria straight in the middle of these two groups. If adding this as a separate function, I can choose another sensitivity/specificity tradeoff, but I should still make sure that legitimate Rickettsiales;Mitochondria do not get filtered out.

Yep, totally agree.

When making the `isPhiX` function, I set a decision boundary at `wordSize=16, minMatches=2` based on testing with data where I drew random reads from phiX, simulated errors, and mixed them with real 16S amplicon data to evaluate sens/spec. Sadly my dev practices were not great at that time, and my testing code is now lost.

**Comment by wbazant** [comment]
Just to update this issue - I still think it's a good issue, it might be a while until I work on it if I ever do - I'd do it as part of a round of improvements to MicrobiomeDB 16s data if I have an opportunity, but I've not even analysed any such data for a while: we're more focused on WGS for now.

I've asked SILVA about including those host sequences - this is their conclusion:

> 
> - if you want to filter Mitochondria from your results, you can safely filter everything that is classified as Rickettsiales;Mitochondria, these sequences are with a very high probability mitochondrial sequences and not Bacteria
> - curating Mitochondria to add the host as metadata and then include this information when creating the non-redundant dataset (to make sure we do not lose a host) is currently not possible for us due to limitation of resources
> 

Also, I found out what EBI Metagenomics with their data aligned to SILVA reference - in the older versions of their pipeline they lifted Mitochondria and Chloroplasts to show them as separate results, but now they delete them:

> For version 4.1 of the pipeline any lineage containing
> Chloroplast or Mitochondria were promoted to the super kingdom level followed
> by the related species. I believe in the silva taxonomy these are usually
> under Cyanobacteria and Rickettsiales respectively. These are the hits you may
> seeing. You will not see these hits in v5.0 analyses however, as any taxonomy
> with consecutive empty levels were filtered out.

Filtering out final results is not equally appropriate for DADA2 because some of the mito - sourced ASVs are not classified as Rickettsiales;Mitochondria, but Rickettsiales, or higher - it's not as good as either extending the sequence or adding a filtering step similar to isPhix.
