### ISSUE TITLE
The use of trimming vs keeping larger overlap in DADA2

### ISSUE THREAD

**Issue by FabianRoger** [benjjneb/dada2#1459]
Hi,

A thought hit me while analysing a dataset with almost fully overlapping foward and reverse reads. As far as I understand DADA2 doesn't make use of the consenus information form overlapping reads other than that it requires perfect match-up during the merging step and after denoising each read seperately. 

Of course the accuracy of the merging increases with increasing overlap, but I would assume that there is a diminishing return with overlap length. On the other hand, the quality of illumina reads tends to decline versus the end, meaning that the less we trim, the more reads will be filtered out by expected error filtration (and potentially more errors remain in the overlap region preventing merging)

Does this mean that it is always advisable to trimm the reads aggresively keeping a minimum advisable overlap (say 50 bp or so), even if that means trimming over half the reads? or is there any advantage in keeping more of each read?

I am asking for markers that do not have large biological length variations (COI / 16S). 

Also, I was wondering if you had ever done some benchmarking comparing fixed-length trimming to setting the parameter `truncQ`? (e.g. to 25 or so) 

Thanks for your thoughts!

Fabian

**Comment by benjjneb** [comment]
Totally agree. In general it is advisable to cut off the low quality end, as long as enough is left to overlap and merge.
