### ISSUE TITLE
Reverse complementing sequence table to allow taxonomic classification 

### ISSUE THREAD

**Issue by Nick243** [benjjneb/dada2#146]
Hi Ben,

I was hoping I might be able to ask your advice/thoughts on some samples we recently received that we hope to denoise using DADA2. We have about 700 samples that were sequenced (2x300bp) using the V3/4 (319F/806R) primers described by Fadrosh et al.  I looked at processing these as PE reads, but found very few pairs were passing filtering due to the high expected error rate of the reverse reads. Truncating to a length that allows for a more reasonable MAXEE would result in non-overlapping reads, so it seems we might just have to treat this as single-end data and process the F reads alone.

What is confusing is that the files we received demarked as F (for forward) contain the 806R primer sequence. Thus, they look to be what I would expect to be the read2 sequences running 3’ to 5’ from the 806R primer (however the sequencing quality looks exactly like that that for read1 and not read2). When I trim the primers and process the reads on a test set of 10 samples from the same run everything looks great in terms of the number of reads passing filtering, error profile, and output sequence variants.  However, when I try to classify these RSVs using assignSpecies() and assignTaxonomy() I do not get any hits…most not even to bacteria.  If I take the reverse complement the RSVs I get the classification I would expect based on manually running some of these through blastn (and what I would expect to see in these samples).

So I wanted to ask whether it sounds like maybe the sequencing was just ran in the opposite direction here, and if so, is it reasonable to process the sequences following the tutorial walkthrough up through chimera filtering…and then change the RSVs to their reverse complement for taxonomic classification, generating a tree, and reporting…using something like… 

colnames(seqtab.nochim) <- as.character(reverseComplement(DNAStringSet(colnames(seqtab.nochim)))) 
    
Or are there problems with this approach ?  

Thanks in advance for any thoughts.

**Comment by benjjneb** [comment]
Your troubleshooting and proposed solution is completely appropriate.

There is also an unexported convenience function in the dada2 package for reverse-complementing ACGT sequences: `dada2:::rc`

**Comment by Nick243** [comment]
Thanks so much for your thoughts and for pointing me to the unexported function in dada2.  It  is much appreciated.
