### ISSUE TITLE
No reads passed the filter for a single sample

### ISSUE THREAD

**Issue by AritriSanyal** [benjjneb/dada2#1462]
Hi 

I have been using the dada2 pipeline for analyzing the V4 region from my samples. However, for one single sample, I keep getting the error of no reads passed the filter. 
The codes I followed

>pathMV4 <- #set to samples containing files#
>fnsMV4 <- list.files(pathMV4)
>fastqsMV4 <- pathMV4[grepl(".fq$", fnsMV4)]
>fastqsMV4 <- sort(fastqsMV4)
>fnFsMV4 <- sort(list.files(pathMV4, pattern="_1.fq", full.names = TRUE))
>fnRsMV4 <- sort(list.files(pathMV4, pattern="_2.fq", full.names = TRUE))
>sample.names <- sapply(strsplit(basename(fnFsMV4), "_"), `[`, 1)
>length(fnFsMV4)
_1_
>length(fnRsMV4)
_1_
>foo1 <- readFastq(fnFsMV4[[1]])
>foo1
_class: ShortReadQ
length: 70867 reads; width: 180..220 cycles_
>foo2 <- readFastq(fnRsMV4[[1]])
>foo2
_class: ShortReadQ
length: 70867 reads; width: 180..220 cycles_
>plotQualityProfile(fnFsMV4[1:1])

![image](https://user-images.githubusercontent.com/32352178/144847481-b489396c-4e50-4ba9-afd5-b8ccddd499a0.png)

>plotQualityProfile(fnRsMV4[3:4])
![image](https://user-images.githubusercontent.com/32352178/144847440-b20b6d09-d2f3-4156-9324-afb1384b9f59.png)

>filtFs <- file.path(pathMV4, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
>filtRs <- file.path(pathMV4, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
>names(filtFs) <- sample.names
>names(filtRs) <- sample.names

>outMV4 <- filterAndTrim(fnFsMV4, filtFs, fnRsMV4, filtRs, truncLen=c(230,160),
                        maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                        compress=TRUE, multithread=TRUE, trimLeft = c(19,20))
_The filter removed all reads: Forward and Reverse reads not written.
Warning message:
In filterAndTrim(fnFsMV4, filtFs, fnRsMV4, filtRs, truncLen = c(230,  :
  No reads passed the filter. Please revisit your filtering parameters._

I have tried the workarounds suggested in issue #618 by turning off the filters one by one to find the issue, but all of them resulted in the removal of all reads. Even tried removing and installing the package. 

I have other samples which have worked perfectly fine and given me results, except for this sample. I am not entirely sure where the error is from.
Thanks for the help and also for dada2!

**Comment by sarah-mangum** [comment]
Hi there, I'm no expert but have been working with dada2, it looks like your read length is 220 bp and your trunclen is set to cut the forward reads at 230bp, where trunclen by default discards any reads shorter than the set number.  You may try setting that to 220 to see if that helps!

**Comment by AritriSanyal** [comment]
Hi! 
Thanks! I cannot believe, I missed that. I played around with the length of the reverse reads but not the forward. Thanks again!
