### ISSUE TITLE
Variants identified with DADA not present in mapped files

### ISSUE THREAD

**Issue by jlastoll** [benjjneb/dada2#1463]
I wanted to run some checks to see if I could identify the variants produced by DADA2 in my input files. I mapped my original PE amplicon fastq files to a high quality species-specific reference genome and produced bam files from this process (aligner was bowtie2). 

I'm finding that there were a few variants commonly identified by DADA2 across the samples in my dataset, but when I search the bam files produced above for the particular sequences generated by DADA2, I'm not finding them in the bam files. 

I'm wondering how this variant could be called from the reads in my dataset and then not be present when I produce bam files from mapping to a reference genome?

**Comment by benjjneb** [comment]
> I'm wondering how this variant could be called from the reads in my dataset and then not be present when I produce bam files from mapping to a reference genome?

FIrst guess, the sequences aren't coming from the reference genome. Either they are off-target amplification, or the sequences in your data were not identical (perhaps different at a couple positions) from the reference you are looking at.

I'd try BLAST-ing these sequences againt nt as a first step to resolve what they could be.
