### ISSUE TITLE
WARNING:     One or more of your adapter sequences may be incomplete.     Please see the detailed output above

### ISSUE THREAD

**Issue by Eric2791** [benjjneb/dada2#1466]
When I run the cutadapt to remove primers I get this warining.

WARNING:
    One or more of your adapter sequences may be incomplete.
    Please see the detailed output above

I am using this code.

path.cut <- file.path(path, "cutadapt")
if(!dir.exists(path.cut)) dir.create(path.cut)
fnFs.cut <- file.path(path.cut, basename(fnFs))
fnRs.cut <- file.path(path.cut, basename(fnRs))

FWD.RC <- dada2:::rc(FWD)
REV.RC <- dada2:::rc(REV)
# Trim FWD and the reverse-complement of REV off of R1 (forward reads)
R1.flags <- paste("-g", FWD, "-a", REV.RC) 
# Trim REV and the reverse-complement of FWD off of R2 (reverse reads)
R2.flags <- paste("-G", REV, "-A", FWD.RC) 
# Run Cutadapt
for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                             fnFs.filtN[i], fnRs.filtN[i])) # input files
}

As well when i run the check I am getting the following; 
Forward Complement Reverse RevComp
FWD.ForwardReads       0          0       0       2
FWD.ReverseReads      22          0       0       0
REV.ForwardReads      25          0       0       0
REV.ReverseReads       0          0       0       2

Is cutadapt supposed to remove the adapters too, if so where is that code?

**Comment by benjjneb** [comment]
The message you are getting is from cutdapt, not dada2, so you may need to look at documentation there to figure out what it means.  I'd start by looking at what "adapter" sequences you are providing, i.e. FWD, REV, FWD.RC and REV.RC, and making sure that they look correct.

That said, if you saw the primers on your reads before running cutadapt, and then they are gone afterwards (which it looks like in the check stats you provided), then you can probably ignore the warning.

**Comment by pdhrati02** [comment]
@benjjneb I got the same warning and my stats look pretty similar with just few sequences having the primers. I did check cutadapt and it says that adding A to the start of primer sequence might fix the problem. 
But like you said "That said, if you saw the primers on your reads before running cutadapt, and then they are gone afterwards (which it looks like in the check stats you provided), then you can probably ignore the warning.", does this mean that we don't need to worry about those few reads and can proceed anyway?
Thank you in advance
DP

**Comment by benjjneb** [comment]
> That said, if you saw the primers on your reads before running cutadapt, and then they are gone afterwards (which it looks like in the check stats you provided), then you can probably ignore the warning.", does this mean that we don't need to worry about those few reads and can proceed anyway?

Yes.
