### ISSUE TITLE
Taxonomy assignment function

### ISSUE THREAD

**Issue by thessyed** [benjjneb/dada2#147]
Hi,

I have successfully run DADA2 and created a sequence variant table. I then downloaded and tried the rdp train set and also tried with greengenes (see below) to do taxonomy assignment.

`taxa <- assignTaxonomy(seqtab.nochim, "gg_13_8_train_set_97.fa.gz")
colnames(taxa) <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus")
unname(head(taxa))
write.csv(seqtab.nochim, file = "test")`

However, I am getting poor assignment, with many sequences being classified simply as "Bacteria" and others not even being classified as bacteria (example attached)..
[test_DADA2.xlsx](https://github.com/benjjneb/dada2/files/562807/test_DADA2.xlsx)

. When I input the sequences into something like NCBI 16S BLAST or HOMB BLAST, I am able to get perfect or near perfect matches to known bacteria. The example I've attached is from DADA2 release 1.0.3 but this issue has also occurred on the newest release. Any help with this would be great! 

-- Saad

**Comment by benjjneb** [comment]
Hi Saad,
`assignTaxonomy` assumes that your sequences are in 5'-3' orientation. If they are not it won't work correctly. But this is easy to fix by reverse-complementing them:

```
colnames(seqtab.nochim) <- dada2:::rc(colnames(seqtab.nochim))
```

When I tested this on your first 5 sequences, all of them classified appropriately after reverse-complementation.
