### ISSUE TITLE
Error in Filter and Trim

### ISSUE THREAD

**Issue by bbenz0216** [benjjneb/dada2#1471]
Hello,

I'm very new to R and trying to run my first analysis of my sequencing run. I've gotten up to the Filter and Trim steps, and have gotten an error message. 
Here's the code I input:
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, trimLeft=c(19,21), #remove the 19 bp V4_515_Nextera primer GTGCCAGCMGCCGCGGTAA and the 21 BP V4 R primer GACAGGACTACHVGGGTATCTAATCC
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=FALSE) # On Windows set multithread=FALSE
head(out)

and here's the error message I got: 
Warning message in open.connection(con, "rb"):
"cannot open file 'C:\Users\merce\Barley Microbiome Project\Fastq\FD-15-1_S1_L001_R1_001.fastq': Permission denied"

I've tried checking the permissions on my folder where the fastq files are in, and it looks like I should have access to everything. Although I might have looked in the wrong area. 

I also noticed that the folder "filtered" within my fastq folder is empty. 

Any help would be greatly appreciated!

**Comment by bbenz0216** [comment]
I restarted everything and tried running this again. Instead of the previous error message, I got this one:

Error in filterAndTrim(fnFs, filtFs, fnRs, filtRs, trimLeft = c(19, 21), : could not find function "filterAndTrim"
Traceback:

**Comment by benjjneb** [comment]
One quick idea would be to remove any spaces from your filenames, spaces are notoroius.

I would also note, that is just a warning, and not an error. So.... the command still executed?

**Comment by benjjneb** [comment]
The issue is with your file paths or permissions, which is making R unable to open the files you are providing it. A couple quick things to try:

```{r}
table(file.exists(fnFs))
table(file.exists(fnRs))
```

Are those all `TRUE`?

Can you also clarify whether the error message if triggering with a file path from `fnFs`? Or from `filtFs`?

**Comment by bbenz0216** [comment]
Both outputs were true from 
table(file.exists(fnFs))
table(file.exists(fnRs))

How do I determine if the error is triggering from fnFs or filtFs? Sorry I'm new to R

**Comment by benjjneb** [comment]
At this point it's time to start focusing in by finding a minimal example.

Instead of `fnFs` and `fnRs` etc., can you cut this down to a single sample that causes the error? At that point, it would be shareable and something that could be reproduced by others.
