### ISSUE TITLE
Error in makeSequenceTable

### ISSUE THREAD

**Issue by alecbiom** [benjjneb/dada2#1472]
Hello, I am trying to make ASV tables of my samples and it gave me this error:

Error in makeSequenceTable(dadaFs, filtFs, dadaRs, filtRs) : 
  unused arguments (dadaRs, filtRs)"

I use this command:

filtFs <- file.path(bio, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(bio, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names
filt_all <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
                     maxN=0, maxEE=c(2,5), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, multithread=FALSE)
head(filt_all)

derepFs <- derepFastq(filtFs, verbose=TRUE)
derepRs <- derepFastq(filtRs, verbose=TRUE)
names(derepFs) <- sample.names
names(derepRs) <- sample.names
names(derepFs)
names(derepRs)

errF <- learnErrors(filtFs, multithread=TRUE)
errR <- learnErrors(filtRs, multithread=TRUE)
plotErrors(errF, nominalQ=TRUE)

dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
dadaRs <- dada(filtRs, err=errR, multithread=TRUE)
dadaFs[[1]]

seq.tab <- makeSequenceTable(dadaFs, filtFs, dadaRs, filtRs)

Can anybody help me? @benjjneb

**Comment by benjjneb** [comment]
You need to merge your forward and reverse reads first. See the DADA2 tutorial for an example workflow you can follow along with: https://benjjneb.github.io/dada2/tutorial.html

**Comment by alecbiom** [comment]
> You need to merge your forward and reverse reads first. See the DADA2 tutorial for an example workflow you can follow along with: https://benjjneb.github.io/dada2/tutorial.html

Thank you! I did it, but it appear this error:

> merge <- mergePairs(dadaFs, filtFs, dadaRs, filtRs, verbose=TRUE)
Error in mergePairs(dadaFs, filtFs, dadaRs, filtRs, verbose = TRUE) : 
  The dadaF/derepF/dadaR/derepR arguments must be the same length.

Sorry but I am new in this bioinformatics world

**Comment by alecbiom** [comment]
> You need to merge your forward and reverse reads first. See the DADA2 tutorial for an example workflow you can follow along with: https://benjjneb.github.io/dada2/tutorial.html

Thank you @benjjneb ! 

Another thing, I have 89 samples and when I filt it gave me this error:

> sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
> filtFs <- file.path(bio, "filtered_2", paste0(sample.names, "_F_filt.fastq.gz"))
> filtRs <- file.path(bio, "filtered_2", paste0(sample.names, "_R_filt.fastq.gz"))
> names(filtFs) <- sample.names
> names(filtRs) <- sample.names
> filt_all <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
+                      maxN=0, maxEE=c(2,5), truncQ=2, rm.phix=TRUE,
+                      compress=TRUE, multithread=FALSE)
Creating output directory: D:/MBS/Tese/Samples_Biom/MetaG_raraujo/filtered_2
Error in filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen = c(240, 160),  : 
  All output files must be distinct.

Can you help?

**Comment by alecbiom** [comment]
Thank you @benjjneb !! 

It went well and now I have my ASV tables and TAXA tables
