### ISSUE TITLE
Error when running assignTaxonomy on PacBio 16S reads

### ISSUE THREAD

**Issue by emankhalaf** [benjjneb/dada2#1474]
Hi,

I have 16S sequences generated from PacBio technology.
When I ran:
tax <- assignTaxonomy(st.nochim, "/home/silva_nr99_v138.1_wSpecies_train_set.fa.gz", tryRC = TRUE, minBoot = 80, multithread=TRUE)

I got this error:
Warning in doTryCatch(return(expr), name, parentenv, handler) :
  restarting interrupted promise evaluation

Any recommendations, please!

Thanks in advance!

**Comment by benjjneb** [comment]
That is a warning, not an error. Did the command still execute? What does the retunred `tax` object look like -- does it have taxonomic assignments in line with what you were expecting?

If those questions are true, you can probably just ignore that warning.

**Comment by emankhalaf** [comment]
@benjjneb 
Much thanks for your reply! Yes, I re-ran the entire workflow, and the command was executed but it took over 10 hours. When converted the tax object into csv file, it included 67,239 ASVs with the taxonomic assignment. However, I have other relevant questions as follows:

1- When converting st object into csv file, then opening the spreadsheet, I got a warning "the data could not be loaded completely because the maximum number of characters per cell was exceeded" So, I could not browse this file, any recommendation here?

2- I have sequences for 2 different projects, so, when I ran the workflow on sequences from the other project where samples are expected not to have big microbial diversity, the command was executed much quicker (less than an hour) and the tax object included 12056 taxa. Is this the reason behind the difference between the time needed to execute the command on different sets of samples?

3- In this workflow, I followed your recommendations for Pacbio 16S reads :
track <- filterAndTrim(nops2, filts2, maxN = 0, truncQ = 2, rm.phix = FALSE, **maxEE = 1**, minQ=3, minLen=1400, maxLen=1600)
dd <- dada(drp, err=err, BAND_SIZE=32, **OMEGA_A=1e-10, DETECT_SINGLETONS=TRUE**, multithread=TRUE)
tax <- assignTaxonomy(st.nochim, "/Pacbio/database/**silva_nr99_v138_wSpecies_train_set.fa.gz",tryRC = TRUE, minBoot = 80**, multithread=TRUE)

and I got 67,239 taxa
However, when using the default workflow (maxEE = 2, default OMEGA_A, default DETECT_SINGLETONS=FALSE, silva_nr99_v138_train_set.fa.gz, minBoot = 50) I got 1462 taxa (huge difference???) any comment here, please? since I do not understand why changing these parameters produced significant differences in the microbial diversity.

4- when checking chimeras 
in the first project using the adjusted workflow: sum(st[,bim])/sum(st)  results in 0.097
but when using the default workflow, results in 0.064

any comment here?

5- When I exported tax object into csv file, the records are not displayed uniformly one per row, but a few records are displayed stacked in the same csv row. I am wondering how to adjust them?

6- since I used the adjusted workflow, Rstudio freezes because of displaying such big files with a huge number of taxa, and I have to restart the machine because Rstudio does not respond at all. Any suggestions here?

Thanks in advance for your support!
Eman

**Comment by benjjneb** [comment]
1. Reduce the data prior to outputting it to spreadsheet intended csv files.

2. Is what the reason?

3. The default workflow is intended for Illumina sequencning, you may get different results when applying that vs. the workflow we developed for PacBio HiFi reads. Exactly where differences are arising is harder to say, and would require more detailed reporting of reads through the workflow.

4. In both cases less than 1% of reads are being identified as chimeric. This is usually an OK value to observe.

5. I think this is an issue with `write.csv` and Excel importing? Or... other specific functions and spreadsheet importing?

6. Don't create commands that print large matrices/data.frames to the screen. Everything shoudl be assienged to a variable, and if anything it printed (which R does by default if you enter a variable name), then only the first few lines should be displayed.

**Comment by emankhalaf** [comment]
@benjjneb 

1- Any suggestions about how to reduce/split rds object content prior exporting to spreadsheets?
2- I mean the command execution time differs according to the richness of samples. For example, in project 1, the samples generated > 65,000 ASVs and the command took > 10 hrs to be executed, whereas in project 2, the samples generated approx 12,000 ASVs and the command executed in ~ 1 hr. Am I correct?
3- I was following this workflow https://benjjneb.github.io/LRASManuscript/LRASms_fecal.html, then I updated it according to your recommendations for PacBio  https://github.com/benjjneb/dada2/issues/991

I will report examples of differences of reads through both workflows and I hope I could explain it properly:
**default workflow**                                                         **updated/PacBio workflow**
a. when using maxEE=1
Read in 3770, output 1408 (37.3%) filtered sequences                        Read in 3770, output 1050 (27.9%) filtered sequences
So, filtered sequences are less in PacBio side (same for the rest of samples)

b. when using OMEGA_A=1e-10, DETECT_SINGLETONS=TRUE
Sample 1 - 1408 reads in 1322 unique sequences.                              Sample 1 - 1050 reads in 964 unique sequences.
Sample 2 - 1371 reads in 1337 unique sequences.                              Sample 2 - 875 reads in 841 unique sequences
and so on

c. st <- makeSequenceTable(dd); dim(st)
                             56 **535**                                                                                      56 **70326**        
d. 
bim                                                                                                                       bim
 FALSE  TRUE                                                                                                   FALSE  TRUE 
  351   184                                                                                                          67408  2918

I think when I considered singletons, the count jumped up, correct?

4- That is okay.
5- I will double-check it.
6- Totally agree

Much thanks for your help and waiting for your suggestions
Eman

**Comment by benjjneb** [comment]
1. You can filter out low abundance or low prevalence taxa. Or non-target taxa. Or whatever filter is appropriate for your analysis.
2. Yes, executino time will scale roughly linearly in the number of unique taxa/ASVs being classified.
3. What would really be useful is a table like that in the tutorial here: https://benjjneb.github.io/dada2/tutorial.html#track-reads-through-the-pipeline

That would help diagnose if there is any step in the data processing that is causing big drops in read counts unexpectedly. Based on what you've put, I may consider relaxing the quality filtering a bit to let more read through that step.

**Comment by emankhalaf** [comment]
@benjjneb 
Kindly, please check the tables below from both workflows

Default workflow
                                                                                                                                        ccs primers filtered   denoised noChimera 
Sequel.RunS192.bc1097-CS1_forward---PBBC01-CS2_reverse.S1_192.ccs.fastq        4407    3770     1408     499       497
Sequel.RunS192.bc1098-CS1_forward---PBBC02-CS2_reverse.S2_192.ccs.fastq        5271    4445     1371     281       281
Sequel.RunS192.bc1099-CS1_forward---PBBC03-CS2_reverse.S3_192.ccs.fastq        4602    3921     2110    1270      1264
Sequel.RunS192.bc1100-CS1_forward---PBBC04-CS2_reverse.S4_192.ccs.fastq        8314    6977     2878    1215      1059
Sequel.RunS192.bc1101-CS1_forward---PBBC05-CS2_reverse.S5_192.ccs.fastq        4997    4160     1275     182       182
Sequel.RunS192.bc1102-CS1_forward---PBBC06-CS2_reverse.S6_192.ccs.fastq        4171    3528     1689     842       838
Sequel.RunS192.bc1103-CS1_forward---PBBC07-CS2_reverse.S7_192.ccs.fastq        5995    5068     2209    1138      1128
Sequel.RunS192.bc1104-CS1_forward---PBBC08-CS2_reverse.S8_192.ccs.fastq        9534    7937     3859    2115      1915

#check chimeras
sum(st[,bim])/sum(st)
0.06553758

----------------------------------------------------------------------
Adjusted workflow
                                                                                                                                        ccs primers filtered   denoised noChimera
Sequel.RunS192.bc1097-CS1_forward---PBBC01-CS2_reverse.S1_192.ccs.fastq        4407    3770     1050    1047      1017
Sequel.RunS192.bc1098-CS1_forward---PBBC02-CS2_reverse.S2_192.ccs.fastq        5271    4445      875     875       852
Sequel.RunS192.bc1099-CS1_forward---PBBC03-CS2_reverse.S3_192.ccs.fastq        4602    3921     1775    1747      1658
Sequel.RunS192.bc1100-CS1_forward---PBBC04-CS2_reverse.S4_192.ccs.fastq        8314    6977     2121    2032      1965
Sequel.RunS192.bc1101-CS1_forward---PBBC05-CS2_reverse.S5_192.ccs.fastq        4997    4160      786     786       783
Sequel.RunS192.bc1102-CS1_forward---PBBC06-CS2_reverse.S6_192.ccs.fastq        4171    3528     1340    1301      1257
Sequel.RunS192.bc1103-CS1_forward---PBBC07-CS2_reverse.S7_192.ccs.fastq        5995    5068     1691    1678      1630
Sequel.RunS192.bc1104-CS1_forward---PBBC08-CS2_reverse.S8_192.ccs.fastq        9534    7937     3078    2820      2723

#check chimeras
sum(st[,bim])/sum(st)
0.04902948

I think the denoise step (dada) made this huge difference where I adjusted 2 parameters as follows (OMEGA_A=1e-10, DETECT_SINGLETONS=TRUE). So, probably, this retained a huge number of singletons (rare taxa) to the output.
In these projects, rare taxa are important since I will be comparing a set of genotypes of the same plant. So, reducing low abundance or less prevalent taxa may lead to losing valuable information.

Looking forward to your advice
Eman

**Comment by benjjneb** [comment]
The updated workflow looks like it is performing better. I would consider relaxing the quality filtering a bit to see if the number passing that step can be increased by a modest increase in `maxEE`, perhaps to `maxEE=2`. But other than that, this looks like it is working.

**Comment by emankhalaf** [comment]
@benjjneb 

Thank you very much for your recommendations.
So, what I did in brief:
- project 1 (maxEE=2, singletons= False (default), this resulted in 353 ASVs. when tested maxEE=1 along with considering singleton=True the count increased to 67,239. but when tested maxEE=2,  singleton=True the count became 94,763 ASVs.
- For project 2, (maxEE=2, singletons= False (default), this resulted in 464 ASVs. when tested maxEE=1 along with considering singleton=True the count increased to 12,182. Then, tested maxEE=2,  singleton=True the count became 17,371 ASVs. 
So, I think relaxing the maxEE filter to 2 as you recommended and considering singletons seem to be the proper parameters for my projects, right?

Your help is much appreciated!
Eman

**Comment by benjjneb** [comment]
I would probably go with `DETECT_SINGLETONS=TRUE`. I don't see much gain from `maxEE=2`, but the numebr of ASVs is not a good metric on its own. What fraction of total reads are passing in each case? If very few further reads are making it through with `maxEE=2`, then i would just stick with the better quality data.

**Comment by emankhalaf** [comment]
@benjjneb 

Hi,

Sorry for my very late response (almost a month) since I was traveling and I just got access to a new computer a few days ago.
First, I would like to note that the genomic facility that did the PacBio sequencing said that there was a problem with the polymerase enzyme that might cause point mutation (they still optimizing the reaction conditions). This might explain why when I choose (Singelton = True) the taxa count massively jumps from a few hundred (400-600 taxa) to 70,000-95,000 taxa according to whether we use maxEE= 1 or 2
Anyway, I re-ran the DADA2 workflow using these parameters:
maxEE=2
OMEGA_A=1e-10, DETECT_SINGLETONS=FALSE
minBoot = 80
that eventually resulted in 646 taxa. 
However, the same samples were MiSeq sequenced and generated 1535 taxa. I can tell that the most dominant and prevalent taxa from MiSeq are the most diverse from PacBio. Sorry, I do not know how to calculate the read counts from the generated files from PacBio since it is my first time dealing with PacBio reads and creating a phyloseq object from DADA2 output in R. I used to use qiime2, then generate the phyloseq object using the exported biom files, tree and seq files. So, I am still not well-oriented with the generated file formats to combine them as a phyloseq object. Your recommendations here are highly appreciated.

Though, what I did so far to explore the PacBio seq is as follows:
- I have st.nochim (as a feature table where sample names displayed as rows, column names are sequences ), tax (sequences are displayed as row names along with the taxonomy), and sq (sequences file). All are saved as .rds

- generate a phylogenetic tree from sq as follow:

names(sq) <- sq 
alignment <- AlignSeqs(DNAStringSet(sq), anchor=NA,verbose=FALSE)

phangAlign <- phyDat(as(alignment, "matrix"), type="DNA")
dm <- dist.ml(phangAlign)
treeNJ <- NJ(dm) # Note, tip order != sequence order
fit = pml(treeNJ, data=phangAlign)
fitGTR <- update(fit, k=4, inv=0.2)
fitGTR <- optim.pml(fitGTR, model="GTR", optInv=TRUE, optGamma=TRUE,
        rearrangement = "stochastic", control = pml.control(trace = 0))
detach("package:phangorn", unload=TRUE)

ape::write.tree(fitGTR$tree, file='fitGTR$tree.txt') # to get a file of the phylogenetic tree 

But I need to have a nexus format, so I can upload the phyloseq object without generating the tree every time I am working with the analyses. 
So, I used
ape::write.nexus(fitGTR, file='fitGTR.nex')
and I got nexus file but with this warning "Error: $ operator is invalid for atomic vectors" So, I do not know if I can use the generated nexus tree when creating a phyloseq object in other markdowns or not?

Also, I renamed sample names in the feature table as follows
samples.out <- rownames(st.nochim)
names <- sapply(strsplit(samples.out, "reverse."), `[`, 2)
names <- sapply(strsplit(names, "_"), function(x) paste(x[1]))
names

But I was stuck when going further in analysis and combining the metadata file with the rest of the files. So, this is the most challenging step. After having the phyloseq object, life would be good!

Thanks in advance for your support!

**Comment by benjjneb** [comment]
> that eventually resulted in 646 taxa, 614 taxa after removal of organelles and account for 62320 reads
However, the same samples were MiSeq sequenced and generated 1535 taxa, 1464 after cleaning organelles and account for approx. over 1,600,000 reads. I can tell that the most dominant and prevalent taxa are the same from both technologies, but the diversity and read counts from PacBIo are very low when compared to MiSeq results.

To me this is very unsurprising -- your PacBio data had many fewer reads and less taxa were detected in it. That's a normal consequence of lower sampling effort, less rare tatxa are discovered. That the dominant and prevalent taxa are the same between the two is a very positive sign.

**Comment by emankhalaf** [comment]
@benjjneb 
One more question, when working with the phyloseq object that I created from DADA2 output, features are displayed as sequences. Is there a way to assign these sequences to feature IDs? I used to work with Qiime2 output files which are pretty helpful.
Thank you!

**Comment by benjjneb** [comment]
> The opposite happened with the other project but different plant tissue. Pacbio showed higher diversity (333 taxa of approx 40,000 reads but Illumina generated 88 taxa of 10,000 reads. Is it a sort of compatibility between the tissue and the sequencing technology, or something else?

There are a lot of potential reasons for such an observation, I can't even usefully speculate.

> One more question, when working with the phyloseq object that I created from DADA2 output, features are displayed as sequences. Is there a way to assign these sequences to feature IDs? I used to work with Qiime2 output files which are pretty helpful.

Please review the DADA2 tutorial section on the handoff to phyloseq: https://benjjneb.github.io/dada2/tutorial.html#bonus-handoff-to-phyloseq

In particular, the 3rd code block describes how to rename ASVs with shorter ASV21 type names, while retaining the sequence information in the phyloseq object.

**Comment by emankhalaf** [comment]
@benjjneb 
Really appreciate your help! Much thanks!
Eman
