### ISSUE TITLE
Assingn Taxonomy Reverse

### ISSUE THREAD

**Issue by alecbiom** [benjjneb/dada2#1475]
I @benjjneb!! Is it possible to assingn taxonomy only in the reverse sequence?

I tried it using the workflow and in the AssignTaxonomy part I did this:

seq.tabR <- makeSequenceTable(dadaRs, filtRs)
dim(seq.tabR)
table(nchar(getSequences(seq.tabR)))
seq.tab_cleanR <-removeBimeraDenovo(seq.tabR, method = "consensus", multithread=TRUE, verbose=TRUE)
dim(seq.tab_cleanR)
sum(seq.tab_cleanR)/sum(seq.tabR)
taxaR <- assignTaxonomy(seq.tabR, "D:/MBS/Tese/Treinamento/silva_nr_v132_train_set.fa.gz", multithread=TRUE)
taxaR <- addSpecies(taxaR, "D:/MBS/Tese/Treinamento/GTDB_dada2_assignment_species.fa.gz")
super.taxaR <- taxaR # Removing sequence rownames for display only
rownames(super.taxaR) <- NULL
head(super.taxaR)

Why doesn't it give me the Taxonomy table? I did the same for the Foward sequence and it went well...

**Comment by benjjneb** [comment]
`makeSequenceTable` should be given just a single parameter, in this case the list of denoised reverse samples `dadaRs`. This may be leading to subsequent issues (see `?makeSequenceTable` for more info on the function).

```
st.R <- makeSequenceTable(dadaRs)
```

Then you can manpulate it further, for example by removing chimieras, but you can check that it is still a valid sequence table with:

```
dada2:::is.sequence.table(st.R, verbose=TRUE) 
```

As long as that returns TRUE, you are good to go. You should turn on the `tryRC=TRUE` flag when u sing the reverse sequences though, as they are probably in the reverse complement orientation to the reference data:

```
tax <- assignTaxonomy(st.R, "path/to/reference.fasta", multi=TRUE, tryRC=TRUE)
```
