### ISSUE TITLE
High error frequency for 40 quality score with learnErrors R Package (dada2)

### ISSUE THREAD

**Issue by baptistebidon** [benjjneb/dada2#1477]
Hello everyone,
I am analyzing 16S meta-genomic data with dada2 R package. When it comes time to learn errors rates of trimmed files, there seems to be a problem. Indeed, the error frequency first follows the expected values (red line) but finally turns back to poor log value for high quality score (>38), for some transitions.
Does anyone might know what is happening?
[errFd.pdf](https://github.com/benjjneb/dada2/files/7847043/errFd.pdf)
[errRv.pdf](https://github.com/benjjneb/dada2/files/7847044/errRv.pdf)

**Comment by benjjneb** [comment]
This is common and not a cause for concern. Q=40 values are very rarely assigned in some Illumina runs, at least for certain transitions. Thus the points you are seeing are the result of a very small number of observations, and are downweighted appropriately by the model fitting method.

In short, you are OK, and we should think about how we can improve our `learnErrors` visualization to more clearly indicate that some "points" have a lot more support than others.

**Comment by baptistebidon** [comment]
Thank you for your reply. Indeed, it could be relevant to add a color intensity or diagram to represent the relative number of reads.
Thank you again for your work.
