### ISSUE TITLE
[Question] How do I know if my R and F reads are in a proper order when merging? [mergePairs()]

### ISSUE THREAD

**Issue by wolass** [benjjneb/dada2#148]
Hi! 
I have quite a big problem merging pairs of F and R reads.

I have an Illumina miSeq data after with clipped Adapters and primers (so without non-biological seqs).

But how do I know if the sequencing company gave them in a proper order for merging as required by the `mergePairs()` function?

The result of my merging is 0 sequences... with 43 samples (mean 100 uniqe seqs per sample).

Maybe I am doing sth wrong...
My steps follow exactly the methodology presented in the Callahan et. al paper.

**Comment by benjjneb** [comment]
The most likely cause of issues with merging is that when you truncated your F/R reads, you didn't leave enough overlap for them to be later merged. The walkthrough data is from almost completely overlapping 2x250 V4 reads, so this isn't an issue, but it is for longer amplicons (or shorter reads).

What is the size of your amplicon? What did you set the `truncLen` parameter to for the F/R reads?

**Comment by wolass** [comment]
my amplicon is 300 bp and I am using the 341F-785R primer pair. 
I have put various numbers in the `truncLen` parameter of the filter function... and still get from 0 to just a few sequences merged.
QIIME pipeline worked OK on this dataset.

**Comment by joey711** [comment]
Oh, thems fightin' words! (J/K)

@benjjneb might have a comment on this regarding package organization and future planning. The truth is I've always been uncomfortable with the assumption that the reads are in the correct order in both files. You can imagine lots of ways this could be a problem and result in wrongly-paired sequences, and you're bringing up just one example. 

I drafted some code that is currently a private/internal function in DADA2 that will match up the results from running dada separately on the forward and reverse reads - using their sequence identifiers. 

@benjjneb if you want I can draft a function to perform this pairing, or at least verify the ordering of reads, at the outset. The key sorting infrastructure in data.table is so fast and memory efficient that this could probably stay within the peak-mem reqs of the downstream dada() run.

Thoughts?

**Comment by benjjneb** [comment]
@wolass

We don't currently have an automated way to recomment trimming/filtering parameters, but this is probably the most common problem people have with the pipeline so we should probably consider doing more here. Perhaps a tutorial on picking the parameters would make sense as a first step. For now, some empirical playing around with a subset of the data is the best choice for lower quality sequencing runs.

In order to get more reads through the pipeline, relax the filtering parameters. For example, a filter which allows lower qualities in the reverse reads might make sense. Eg:

```
fastqPairedFilter(c(fnF, fnR), c(filtF, filtR), truncLen=c(280,230), maxEE=c(2,8))
```

(*those numbers are just illustrative*). DADA2 is dramatically less sensitive to the quality filtering parameters than OTU methods are, as it is directly modeling the error rates of different quality scores.

**Comment by wolass** [comment]
@benjjneb Thanks, relaxing the `maxEE` does help. 

After relaxing it to 5,10 I'm getting only 1.5% of initial reads after filtration.
Do we have some kind of 'standard' for the fraction of reads for which we say that the filtration was sufficient?

I do not want to work on data just to find out (before publishing the finished paper = Murphys law) that I selected an insufficient number of sequences for the analysis.

**Comment by benjjneb** [comment]
1.5% is really low still...

Could you share a single-sample pair of fastq files?

**Comment by benjjneb** [comment]
@joey711

Right now the officially supported method for enforcing pairing between unbalanced F/R files is to set `matchIDs=TRUE` in the filtering functions. What do you mean by verifying matching "at the outset"? Is it different than that?

**Comment by wolass** [comment]
@benjjneb Thanks for the help. here is a sample pair of seqs. 

To be thorough:
my filtration arguments:

```
for(i in seq_along(fnFs)){
  fastqPairedFilter(c(fnFs[[i]],fnRs[[i]]),
                    c(fnFs_t[[i]],fnRs_t[[i]]),
                    trimLeft = 0,
                    truncLen=c(270,270),
                    maxN=c(0,0),
                    maxEE=c(5,10), 
                    truncQ=2,
                    compress=T,
                    verbose = T,
                    matchIDs = T)
}
```

and my errors:

![image](https://cloud.githubusercontent.com/assets/2356167/20133345/7cc048f2-a667-11e6-887b-7ea8e8ef28ec.png)

The resulting fraction of filtrated reads:

![image](https://cloud.githubusercontent.com/assets/2356167/20133414/be0208fa-a667-11e6-89f5-a793960d319f.png)


These are calculated using the follwing formula:

$$n_fraction = {n_{pre-filtration} \over n_{post-filtration}}$$

and these numbers derive from the verbose output of the `fastqPairedFilter()`

NOTE. I had to change names to zip of the original bz2 because of github...


[341F-785R-001-IS_R1.fastq.bz2.zip](https://github.com/benjjneb/dada2/files/580408/341F-785R-001-IS_R1.fastq.bz2.zip)
[341F-785R-001-IS_R2.fastq.bz2.zip](https://github.com/benjjneb/dada2/files/580412/341F-785R-001-IS_R2.fastq.bz2.zip)

**Comment by benjjneb** [comment]
Your reads aren't long enough to truncate to that length. Most of the reverse reads are 267 nts long. All reads with a length less than `truncLen` will be tossed.

Just setting `truncLen=260` in the above gets >50% of reads through the filter in the example files.

**Comment by joey711** [comment]
Oh cool, I didn't know this had been added. That sounds like what I meant: defining the pairs by their read-ID rather than by their order in the files. Obviously the former is more expensive computationally.

So is that what the `matchIDs=TRUE` option does?

**Comment by benjjneb** [comment]
`matchIDs=TRUE` filters out reads that don't have an ID-matched pair in the other direction.

It does make an assumption that the ordering between reads present in both is the same. In practice, it is intended to solve the most common issue - prior filtering performed on F/R reads individually. If you randomly permute the order of your R reads, it won't work.

**Comment by benjjneb** [comment]
Relevant to filtering tutorial #156
