### ISSUE TITLE
rm.lowcomplex in filterAndTrim does not filter reverse read in paired mode

### ISSUE THREAD

**Issue by marie-vallier-valbiotis** [benjjneb/dada2#1480]
Hello, 

I recently tried dada2, and faced an issue with filtering paired reads. When I ran the command filterAndTrim on paired mode with the low complexity filter, it removed low complexity sequences only in the forward read but not the reverse. I tried giving one criteria (rm.lowcomplex=14) and two (rm.lowcomplex=c(14,14)) but both gave the same outcome. I worked around it by filtering forward and reverse separately, and them filtering them together with just the matchIDs=T option to get the intersection of the reads.

I'm running dada2 version 1.22.0 with R version 4.1.1 (2021-08-10) -- "Kick Things"
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Comment by benjjneb** [comment]
By default, when `filterAndTrim` is run with paired data, and only one value is provided for a filtering paramter like `rm.lowcomplex`, it is applied to both the forward and reverse reads. From `?filterAndTrim`:

> Note: When filtering paired reads... If a length 1 vector is provided, the same parameter value is used for the forward and reverse reads. If a length 2 vector is provided, the first value is used for the forward reads, and the second for the reverse reads.

Does this explain what you are seeing?

**Comment by marie-vallier-valbiotis** [comment]
Hi, not really.

The problem I have is in the output sequences. Low complexity sequences are filtered out correctly in the forward read, but not in the reverse, so the output reverse reads still have low complexity sequences.

The other options do not seem to be affected, as the reverse is correctly truncated and filtered for quality, but it is not filtered for low complexity.

I just tried with the two way to specify the low complexity threshold, just to see if maybe one way of specifying would solve the issue.

**Comment by benjjneb** [comment]
How are you determining that there is still low-complexity sequences in the reverse reads? One way to check would be to use `plotComplexity` after filtering. For an example sample:

```
filterAndTrim(fnF1, filtF1, fnF2, filtF2, rm.lowcomplex=...)
# Check to see if low complexity sequences were removed from forward reads
plotComplexity(fnF1)
plotComplexity(filtF1)
# Check to see ... from reverse reads
plotComplexity(fnR1)
plotComplexity(filtR1)
```

**Comment by marie-vallier-valbiotis** [comment]
hi, yes this is exactly how I did it.

**Comment by benjjneb** [comment]
OK, can you show your exact code (including `filterAndTrim` call), and the plots you are getting?
