### ISSUE TITLE
Include the MiDAS taxonomic reference database

### ISSUE THREAD

**Issue by KasperSkytte** [benjjneb/dada2#1481]
Hi Benjamin!

I have formatted the MiDAS taxonomic database for use with DADA2. Would you please include it on the https://benjjneb.github.io/dada2/training.html page? The latest version will always be available for download at [midasfieldguide.org](https://midasfieldguide.org/guide/downloads), but I can also upload an exact version to zenodo og figshare for a DOI link if you prefer, let me know.

**Briefly about the database**
The MiDAS taxonomic reference database is an ecosystem specific database with species-level resolution built from full-length 16S rRNA gene sequences obtained directly from the activated sludge and anaerobic digester ecosystems. The samples used are from full-scale treatment plants across Denmark (version 3, [reference](https://doi.org/10.1016/j.watres.2020.115955)) and across the world (version 4, [reference](https://doi.org/10.1101/2021.07.06.451231)). Version 5 will be released hopefully this year which includes sequences from digester samples from across the world as well (already made, but paper in writing before release). The database is generated using the [AutoTax](https://github.com/KasperSkytte/AutoTax) pipeline to provide de novo placeholder names based on sequence clusters at predefined identity thresholds whereever SILVA is inadequate, especially at species level. The database currently includes 9461 Genera and 31301 species, but most importantly a complete catalogue of full-length 16S reference sequences obtained directly from the AS and AD ecosystems.

Kind regards
Kasper Skytte Andersen
Morten Dueholm
Per Halkjær Nielsen
Aalborg University, Denmark

**Comment by benjjneb** [comment]
Hi Kasper et al.,
I've added the MiDAS reference fasta as a link in the contributed section of the DADA2 taxonomic reference page (should be live now): https://benjjneb.github.io/dada2/training.html

As an admirer of the MiDAS project, thank you for making a DADA2 version and keep up the great work.

Regards,
Ben

**Comment by KasperSkytte** [comment]
Hi Ben

Thank you very much! And you too
