### ISSUE TITLE
Primers detected only in few reads: ITS sequencing

### ISSUE THREAD

**Issue by pdhrati02** [benjjneb/dada2#1482]
Hi, 
I am trying processing ITS data for the first time, when trying with only 4 samples everything worked well. But it did not when I tried with the complete dataset. The primers used for sequencing are ITSF1 and ITS2.
I tried 2 scenarios:
1. Using the primer sequence as follows:
ITS1F CTTGGTCATTTAGAGGAAGTAA and ITS2 GCTGCGTTCTTCATCGATGC
This worked just fine with 4 samples but with the whole dataset gave errors at the cutadapt stage: WARNING: One or more of your adapter sequences may be incomplete. And in the reads post cut adapt 2-3 reads are seen in some columns when sanity check is done post cutadapt. 
Also the quality plots gives errors.

2. Scenario 2 I tried using a complete primer sequence as follows: 
Forward primer 5’ TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTACGGGNGGCWGCAG; reverse primer 5’ GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGGACTACHVGGGTATCTAATCC

This is not detected in many reads, just in some in rev.forward reads as rev complement. Thus this is not the best way to proceed I guess. 

Can you suggest how to go about this? And how to overcome the issues in scenario 1?

Thank you in advance
DP

</body>
</html>

**Comment by benjjneb** [comment]
What is your sequenced amplicon?

That is, does your sequence amplicon include just the primers? Not the primers at all? The primers plus adapters?

If unknown, speak to you rsequence provider and find out, because once you know that, proceeding is easy.

**Comment by pdhrati02** [comment]
Hi @benjjneb The sequencing facility people said that they turn off “trim adaptors” so as far as they know adaptor sequences should also be present.
I did not prepare this library and hence a bit of confusion, apologies about the same. The primer sequence used are:
 primers specific to the ITS1-ITS2 region of the ITS gene, but they were modified to incorporate the Illumina overhang adaptor (i.e., ITSF1 primer 5′ TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCTTGGTCATTTAGAGGAAGTAA 3′ and ITS2 primer 5′ GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGGCTGCGTTCTTCATCGATGC 3′). 

But when I check the raw reads I only see the end part of the primers : ITS1F CTTGGTCATTTAGAGGAAGTAA and ITS2 GCTGCGTTCTTCATCGATGC
For example see highlighted. While in other samples last 2/3 nucleotides of the primer are missing - based on a random check:

@M01385:165:000000000-K5M5J:1:1101:12850:2103 1:N:0:GGACTCCT+ACTGCATA
**CTTGGTCATTTAGAGGAAGTAA**AAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTACCGAGTGCGGGCCCTCTGGGTCCAACCTCCCATCCGTGTCTATCTGTACCCTGTTGCTTCGGCGTGGCCACGGCCCGCCGGAGACTAACATTTGAACGCTGTCTGAAGTTTGCAGTCTGAGTTTTTAGTTAAACAATCGTTAAAACTTTCAACAACGGATCTCTTGGTTCCGGCATCGATGAA
+
>AA??FDDFFFFCFF111AF33331FF0FC0A11B0GGHFE0GC00DADDFFG00///A/A0BA0GHBAA///F/1///>/>FEG110BF>11>>F>>?0F0B/F/F<G2FBG2GDD>FHFGHEBGHFG/</AC?@<1FC-<<<-<----:-:G00:CCFFF009AAEBFFGF00;CCF000BFFFFBBFGGGGEFFFFB/9/9FBAEE--9/:FFFBBBB9AA=-9B=FFFF/9BE9B---9@B-/;//9
@M01385:165:000000000-K5M5J:1:1101:11974:2122 1:N:0:GGACTCCT+ACTGCATA
**CTTGGTCATTTAGAGGAAGTAA**AAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTACCGAGTGTAGGGTTCCTAGCGAGCCCAACCTCCCACCCGTGTTTACTGTACCTTAGTTGCTTCGGCGGGCCCGCCATTCATTGCCGCCGGGGGCTCTCAGCCCCGGGCCCGCGCCCGCCGGAGACACCACGCACTCTGTCTGATCTAGTGAAGTCTGAGTTGATTGTATCGCAATCAGTTAAA
+
AAB??FF5FFFFFBFB4E4F55555FF2F44B54A2FGHGF2FA22DFDFGGH2C2000E11BB1FGBBA110B1G5531FFCFG443///>>?11>>GEC?0??>/?/FGH4FG4GDGHHHB1GHHFHHH//</@-<@@-?@-CGC0C000:-:9----->@AFB/;9BAD----99----@B-=@--9-9ABBE.A..99999/:/9//;9B/9B//;BFFF///9F//BB/B/B9....;B//BF///
@M01385:165:000000000-K5M5J:1:1101:17744:2215 1:N:0:GGACTCCT+ACTGCATA
**CTTGGTCATTTAGAGGAAGTAA**AAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTACCGAGTGTAGGGTTCCTAGCGAGCCCAACCTCCCACCCGTGTTTACTGTACCTTAGTTGCTTCGGCGGGCCCGCCATTCATGGCCCCCGGGGGCTCTCAGCCCCGGGCCCGCGCCCGCCGGAGACACCACGAACTCTGTCTGTTCTAGTGAAGTCTGAGTTGTTTGTA

Can you help me with how to proceed in this case?

Thank you very much for your help
DP

**Comment by benjjneb** [comment]
That's as expected. Typically only the primer is sequenced by these library setups. You should be able to move forward as expected with the ITS tutorial, using just the primer sequences (i.e. your original option 1).

> but with the whole dataset gave errors at the cutadapt stage: WARNING: One or more of your adapter sequences may be incomplete

That's just a warning. If it works for most samples, I would just disregard.

> And in the reads post cut adapt 2-3 reads are seen in some columns when sanity check is done post cutadapt.

It's fine if a few reads here and there sneak by primer removal. As long as the vast majority are removed.

> Also the quality plots gives errors.

Errors? Or warnings? If just a warning, and the plot looks as expected, feel free to proceed.

**Comment by pdhrati02** [comment]
Hi @benjjneb Thank you so much for answering all my questions. It is huge help. I tried with the option one and seems to work. Thank you for all your help. 
DP
