### ISSUE TITLE
Versions Dont Match

### ISSUE THREAD

**Issue by Eric2791** [benjjneb/dada2#1483]
The DADA2 pipeline wont work because packages in Bioconductor were updated to version 3.15 which apparently only works with R 4.2 but the latest R release is 4.1.2

So what are we supposed to do?

**Comment by Eric2791** [comment]
Specifically the function "vcountPattern" wont work

**Comment by benjjneb** [comment]
You can reinstall Bioconductor and associated packages on your machine using `BiocManager` which should avoid any of these version issues. How did a version of some packages with an R requirement that exceeds yours get installed in the first place?

**Comment by Eric2791** [comment]
Biomanager 3.14 no longer works. The code stopped working and I got the error that

package 'vcountPattern' is not available for Bioconductor version '3.14'

This is why I went to the Bioconductor cute which says that they are now on Bioconductor 3.15

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by benjjneb** [comment]
`vcountPattern` is installed in the `Biostrings` package. Is that package available on your machine?

You may need to be more explicit about exactly what commands you are running that are causing errors, and what exactly you are running to try to install packages. Maybe you just don't have `Biostrings` loaded? If you `library(Biostrings)`, then `vcountPattern` should work in the session.

**Comment by Eric2791** [comment]
###Im running this first

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install( version = "3.14")

###Then this

BiocManager::install(c("dada2", "Biostrings", "ShortRead"))

### Then this

install.packages("pacman")
pacman::p_load(dada2, Biostrings, ShortRead)


### I have also tried running it this way but I get the same problem.

if (!requireNamespace("BiocManager", force = TRUE))
  install.packages("BiocManager")
BiocManager::install(c("dada2", "Biostrings", "ShortRead"))

install.packages("pacman")
pacman::p_load(dada2, Biostrings, ShortRead)

### The problem arises at the step below, basically nothing happens at all when I run this. Like literally nothing happens it just gets stuck and I have to force it to stop. But if I clear the code and then just run the below code I get the error about the vcountPattern package. A month ago, it worked perfectly fine with the above code.

allOrients <- function(primer) {
  # Create all orientations of the input sequence
  require(Biostrings)
  dna <- DNAString(primer)  # The Biostrings works w/ DNAString objects rather than character vectors
  orients <- c(Forward = dna, Complement = complement(dna), Reverse = reverse(dna),
               RevComp = reverseComplement(dna))
  return(sapply(orients, toString))  # Convert back to character vector
}
FWD.orients <- allOrients(FWD)
REV.orients <- allOrients(REV)
FWD.orients
REV.orients



From: Benjamin Callahan ***@***.***>
Date: Tuesday, January 25, 2022 at 9:32 PM
To: benjjneb/dada2 ***@***.***>
Cc: Larson, Eric ***@***.***>, Author ***@***.***>
Subject: Re: [benjjneb/dada2] Versions Dont Match (Issue #1483)

vcountPattern is installed in the Biostrings package. Is that package available on your machine?

You may need to be more explicit about exactly what commands you are running that are causing errors, and what exactly you are running to try to install packages. Maybe you just don't have Biostrings loaded? If you library(Biostrings), then vcountPattern should work in the session.

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbenjjneb%2Fdada2%2Fissues%2F1483%23issuecomment-1021804813&data=04%7C01%7Cejl5778%40psu.edu%7Cf5750ddc70364d6c979c08d9e07417d6%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C637787611487098552%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Fxy%2F0Hpjx%2BukbS1ZH0FPZUxocGx8JLrM0YuundMI4d0%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAW2VMPCMCH36EZDENIFZYMLUX5MLVANCNFSM5MZF4BXQ&data=04%7C01%7Cejl5778%40psu.edu%7Cf5750ddc70364d6c979c08d9e07417d6%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C637787611487098552%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2Mwv4%2F%2FM2a7ymU%2FmZwJZUotEArHdUkpPraSW2kgMXkg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cejl5778%40psu.edu%7Cf5750ddc70364d6c979c08d9e07417d6%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C637787611487098552%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qE9qRDS%2BSDykNlQR7uMlxRI%2BOf6Odz2wjQNCMKlenO4%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cejl5778%40psu.edu%7Cf5750ddc70364d6c979c08d9e07417d6%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C637787611487098552%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JV9BaaGRSm1b%2FO0c0tLQqCkKCLDPiVb3SckB0bA%2BKnk%3D&reserved=0>.

**Comment by benjjneb** [comment]
OK, so there is no issue with versions here. When you run the above code without loading the `Biostrings` library (that defines the `vcountPattern` function) it doesn't work. That's just a library loading issue.

So can you reflarify the problem? Assuming that `library(Biostrings)` has been run. What exact command is hanging (i.e. producing no output)? And, can you check your system monitoring application to see if R is still running, hence the command may just be taking a while to complete?

**Comment by Eric2791** [comment]
Hey,

This is all working now. I'm not actually sure what happened, but I think I was getting that error because of something weird on my end. Thank you for taking the time to try and help me fix it!
