### ISSUE TITLE
Matching between Silva original sequences (138.1 release) and formatted files on zenodo.org

### ISSUE THREAD

**Issue by cppjocker** [benjjneb/dada2#1485]
Hi! 

there is official taxonomy on Silva database

https://www.arb-silva.de/no_cache/download/archive/release_138_1/Exports/

and there is your reformatted sequences

https://zenodo.org/record/4587955#.YfPkvuormUn

if I will take this file from Silva --- "SILVA_138.1_SSURef_tax_silva.fasta.gz" it will contain 10 times more sequences (from 'Bacteria' and 'Archea') than reformatted "silva_species_assignment_v138.1.fa.gz". In fact I got approx 2050000 sequence from Silva and 360000 sequences from zenodo.org. And all 360000 ID from zenodo I found in Silva, so files partly have a match

I don't quite understand reasons of that. Could you provide filtering routines which  transformed original Silva data to your reformatted data? I need to understand why original file was compressed 10 times (considering only 'Bacteria' and 'Archea' sequences)

Also I'm not sure that this is "issue", it's more like a question. But I didn't find your email, so posting it here.

**Comment by benjjneb** [comment]
The DADA2 reference is generated from the nr99 version of Silva (non redundant at 99% identity), which is probably the main reason for the decrease in sequence numbers you are observing. We also, for this prokaryotic reference fasta, filter out the eukaryotes (except for 100 Euk sequences kept as an outgroup).

**Comment by cppjocker** [comment]
Thank you much for your quick response. I will inspect code and then return to you.

Important thing which should be noticed is that in zenodo.org you have three files 

"silva_nr99_v138.1_train_set.fa.gz"
"silva_nr99_v138.1_wSpecies_train_set.fa.gz"
"silva_species_assignment_v138.1.fa.gz"

so first two files are indeed from nr99 (it seems from their calling), but "silva_species_assignment_v138.1.fa.gz" which is of my interests it seems that not. Because not all its IDs found in original NR99 Silva files but all his IDs found in standard Silva file  "SILVA_138.1_SSURef_tax_silva.fasta.gz"

And yes as I said when checked I compared only Bacteria and Archea counts, so Eukaryota was filtered out

**Comment by benjjneb** [comment]
Yes, the code for how "silva_species_assignment_v138.1.fa.gz" intended for the `assignSpecies` function is digested is here: https://github.com/benjjneb/dada2/blob/master/R/taxonomy.R#L679

Important point is that it requires matching between the Silva genus and the genus-species binomial propoagate over from ENA(?) to keep an entry, so many entries are lost at that step.

**Comment by cppjocker** [comment]
Hi

I launched makeSpeciesFasta_Silva function from your rep and looks like I got the same result file as posted on zenodo.org (silva_species_assignment_v138.1.fa.gz).

Also I have inspected code.  To be honest I was not very satisfied with results

First thing - you remain only 'Bacteria' Domain. So 'Archaea' was filtered out inded

Also you filter out all uncultered and unidentified. It probably also not very good since some researches may be interested in such families

Also I'm not sure in other filters since you remain only sequences where genera matches to species with some regular exp ( which not very clear ). Also I'm not sure than sp. or 'endosymbiont' should always be expected

So in fact your files posted on  https://zenodo.org/record/4587955#.YfPkvuormUn have these issues.

You should at least provide description on that page about these issues. And good solution would be relax your filters also.

**Comment by benjjneb** [comment]
> Also I have inspected code. To be honest I was not very satisfied with results

Well, that's why we provide the code! If you would like to make changes to how Silva is digested, you can just modify the provided code to create a new species assignment fasta file that matches with your preferences.

**Comment by cppjocker** [comment]
Yes, you right. I will do modifications by myself. 

But what I was talking about is that description on page https://zenodo.org/record/4587955#.YfPkvuormUn is incomplete
