### ISSUE TITLE
Adapting the DADA2 pipeline for multiple amplicons

### ISSUE THREAD

**Issue by LaurCC** [benjjneb/dada2#1487]
Hello,

We have sequenced different hypervariable regions using two primer sets in order to amplify: V1-V2 (27F & 338R), and V4 (515F & 806R) regions. These were sequenced on the same illumina run and so the amplicons are currently pooled together. We have sequenced both regions in order to assess them independently and evaluate their ability to assign taxonomy to our sample type. In order to undertake this analysis should I separate the two different amplicons before the pipeline or is there a step within the pipeline where I can see the output of either amplicon independently?

I hope I have made sense, thank you for any help!

**Comment by benjjneb** [comment]
DADA2 will naturally handle mixed amplicons in a sample, so you don't have to separate the amplicons prior to DADA2 (but you can if you want). I think the question is whether you will need to separate them eventually anyway for subsequent analysis.

**Comment by LaurCC** [comment]
Thank you so much for your response! Yes I will need to separate them eventually, or at least be able to visualise the results separately based on hypervariable region. If I did want to separate them prior to DADA2 do you have any advice on the best method for doing this and therefore treating them as two independent data sets?

**Comment by cjfields** [comment]
@LaurCC we do this quite frequently w/ [Fluidigm-generated data](https://biotech.illinois.edu/htdna/services-equipment/amplicons) where we get up to 24 amplicon pairs; I'm guessing this is similar?   We basically demultiplex by sample _and_ primer pair and run them independently.

**Comment by LaurCC** [comment]
Hi @cjfields thanks for sharing! Is this still possible if I'm already working with demultiplexed files?

**Comment by cjfields** [comment]
@LaurCC if you want to run each PCR primer pair through DADA2 independently and if your PCR rxns are pooled and barcoded by sample (like our case), you'd need to split each barcode-demultiplexed samples further by primer pair first.   Essentially two levels of demultiplexing, if that makes sense.

**Comment by LaurCC** [comment]
Yes that makes sense thank you! I had seen in a previous thread that the samples already being demultiplexed had caused issues so just wanted to check I can demultiplex data that is already demultiplexed by barcode so thank you for clarifying! 

Is there a recommended tool for demultiplexing by primer? (Sorry I'm quite new to the field) Thanks again for your help!

**Comment by andzandz11** [comment]
You cound try 

``
temp_forw <- readFastq(dirPath = ".", pattern="_R1_filt.fastq.gz")
  temp_forw_match <- vmatchPattern(rev_primer_sequence,
                                  temp_forw@sread %>% subseq(., start=1, end=nchar(rev_primer_sequence)+3),
                                  max.mismatch = 3, fixed = F) %>% startIndex
  temp_forw_match <- lapply(temp_forw_match, function (x) ifelse(length(x) > 0 , x, NA)) %>% unlist
  temp_forw_match[temp_forw_match!=1] <- NA
```

to search for your primer and then use this information to subset your sequence file.

Very basic, definitely not the most sophisticated approch, but works for me.
