### ISSUE TITLE
filter low quality reads out of dada object

### ISSUE THREAD

**Issue by marie-vallier-valbiotis** [benjjneb/dada2#1488]
Hello,

I noticed that after the denoising step, some reads in the dada object have low quality, and I would like to filter them out in a paired manner, so that I can still merge F and R together. I did not find a function in dada2 to do that, so I was think of writing a piece of code to do that. However, I cannot fully make sense of the dada object format.

I understand that the "denoised", "clustering", "sequence" and "quality" items have one dimension equals to the number of denoised reads; then the "trans", "err_in", "err_out" and "opts" items are input parameters and seem to be independent of the number of reads, so I don't need to midify them. I am guessing that the "map" and "pval" have length equals to the number of unique sequences before denoising, but I do not understand the dimension of the "birth_subs", and I do not see where the correspondance to the original sequence is.

It seems straight forward enough to make a condition on the "quality" item, and select corresponding rows in the other items containing denoised or unique sequences informations, but how do I handle the "birth_subs", and how do I make sure the link to the original sequence is preserved so that I can still merge F and R?

Thank you.

**Comment by benjjneb** [comment]
`mergePairs` has an optional argument `propagateCol` that I think will solve this use case pretty straightforwardly. 

> @param propagateCol (Optional). \code{character}. Default \code{character(0)}.
> The return data.frame will include values from columns in the $clustering \code{data.frame}
>  of the provided \code{\link{dada-class}} objects with the provided names.

So, if you `mergePairs(..., propagateCol="quality")`, then the merged data.frame that is created will include `$F.quality` and `$R.quality` columns that contain the quality information from the `$clustering` data.frame for the forward and reverse denoised sequences being merged. Then you can just filter out low quality merged sequences from the data.frame in whatever way you choose.
