### ISSUE TITLE
Strange results after filtering and trimming!

### ISSUE THREAD

**Issue by yijuanhu** [benjjneb/dada2#149]
Hi there, 

We encountered something strange when we perform the filtering and trimming step. First of all, we ended up with fewer reads when we trimmed less for the reads. Second, even with maxEE=inf, we still lost too many reads. 

Here are some statistics we obtained for one sample when we gradually trim less of the reads (all with maxN=0, maxEE=inf, truncQ=2, compress=TRUE, verbose=TRUE):

"
trimLeft=c(20,10), truncLen=c(200,150)
==> Read in 101089 paired-sequences, output 62682 filtered paired-sequences.

trimLeft=c(0,0), truncLen=c(290,220)
==> Read in 101089 paired-sequences, output 62673 filtered paired-sequences.

trimLeft=c(0,0), truncLen=c(300,280)
==> Read in 101089 paired-sequences, output 16084 filtered paired-sequences.
"

Is this normal? How can we keep more reads?

Thanks!

**Comment by wolass** [comment]
relax the truncQ argument?

**Comment by benjjneb** [comment]
The probable reason you are getting less reads with longer `truncLen` is that there are Ns of Q=2 bases showing up at the end of your reads. An N or Q=2 w/in the trimmed length means the read is lost filtered out. This is especially a problem with the Illumina 2x300 chemistry, which we do not recommend for amplicon sequencing (use 2x250 instead, much better quality throughout the reads).

As @wolass suggested, turning off truncQ (`truncQ=0`) may help. Although if there are lots of Ns being called, your only recourse is trimming appropriately.

Looking at your numbers though, the `truncLen=c(290,220)` set of parametes, that's getting 60% of the reads through, looks like a solid choice.

**Comment by benjjneb** [comment]
Closing as assumed fixed, please reopen if necessary.
