### ISSUE TITLE
trimOverhang with ITS data

### ISSUE THREAD

**Issue by andressamv** [benjjneb/dada2#1490]
Hi, this is my first time using Dada2 to work with ITS. I sequenced the ITS1-1F region using 2 x 250 bp, so I have a lot of variation in the amplicon size. I followed the ITS workflow so far (https://benjjneb.github.io/dada2/ITS_workflow.html), including the removal of primers using Cutadapt. However, it is not clear to me if I should use the trimOverhang = TRUE argument during the merge because of this variation. How would that affect my results?

**Comment by benjjneb** [comment]
`trimOverhand=TRUE` will only be relevant to your results if your sequenced amplicon is sometimes smaller than the read size, i.e. less than 250bp in your case. Do you know if the ITS1 region you are sequencing is sometimes less than 250bp?

That said, if uncertain, `trimOverhang=TRUE` is perhaps a safer choice. If the amplicon is >250 bps, this will have no effect, and if it is <250bp it will appropriately trim off the overhang on each side.

**Comment by andzandz11** [comment]
@[andressamv](https://github.com/andressamv) You don't need to worry about overhangs if you use ITSx software to cut everything except the ITS1 region.
