### ISSUE TITLE
dada2 does not throw away singleton *reads*. However, it does not infer *amplicon sequence variants* that are only supported by a single read - singletons are assumed too difficult to differentiate from errors. Hence no singletons in the output table of amplicon sequence variants.

### ISSUE THREAD

**Issue by bodya67** [benjjneb/dada2#1491]
dada2 does not throw away singleton *reads*. However, it does not infer *amplicon sequence variants* that are only supported by a single read - singletons are assumed too difficult to differentiate from errors. Hence no singletons in the output table of amplicon sequence variants.

Right now we have no option to infer sequence variants supported by singleton reads.

_Originally posted by @benjjneb in https://github.com/benjjneb/dada2/issues/320#issuecomment-324635406_

Hello. I have an issue about singletons. 
As you said "Hence no singletons in the output table of amplicon sequence variants.". 
I have processed my data with standard parameters as in the tutorial and with my parameters. There were about 140 samples with 40000-100000 per sample. Dada denoised 11524 ASV, 2078 of which were singletons.
Previously i was working with small but noisy dataset(4 samples, ~10000-20000 reads in each ). I did not have this problem...
QUESTION. Is it a mistake, that i have singletons or it is possible to obtain such amount of singletons?
I have read how dada works and i can not understand how singletons can appear in final table(otu table)

P.S. There were also many doubletons.

I am using R version 4.1, dada2 version 1.22.0

My code
filtered_out <- filterAndTrim(forward_reads, filtered_forward_reads, 
                              reverse_reads, filtered_reverse_reads, 
                              compress = F,
                              truncQ = 0,
                              multithread=TRUE, 
                              #minLen = 250,
                              truncLen = c(280,270),
                              maxEE = c(2,3))

err_forward_reads <- learnErrors(filtered_forward_reads, nbases = 1e8, multithread=TRUE)
err_reverse_reads <- learnErrors(filtered_reverse_reads, nbases = 1e8, multithread=TRUE)

derep_forward <- derepFastq(filtered_forward_reads, verbose=TRUE)
names(derep_forward) <- samples 
derep_reverse <- derepFastq(filtered_reverse_reads, verbose=TRUE)
names(derep_reverse) <- samples

dada_forward <- dada(derep_forward, err=err_forward_reads, multithread=TRUE, pool="pseudo")
dada_reverse <- dada(derep_reverse, err=err_reverse_reads, multithread=TRUE, pool="pseudo")

merged_amplicons <- mergePairs(dada_forward, derep_forward, dada_reverse, derep_reverse, minOverlap = 20)

seqtab <- makeSequenceTable(merged_amplicons)

seqtab.nochim <- removeBimeraDenovo(seqtab_filtered, method = "consensus", multithread=T, verbose=T)

asv_seqs <- colnames(seqtab.nochim)
asv_headers <- vector(dim(seqtab.nochim)[2], mode="character")

for (i in 1:dim(seqtab.nochim)[2]) {
  asv_headers[i] <- paste(">ASV", i, sep="_")
}

asv_fasta <- c(rbind(asv_headers, asv_seqs))

asv_tab <- t(seqtab.nochim)
row.names(asv_tab) <- sub(">", "", asv_headers)
write.table(asv_tab, "../ASVs_counts.txt", sep="\t", quote=F)

Best regards, Bogdan

**Comment by benjjneb** [comment]
Hi Bogdan,
Is this supposed to be opened in a new issue? Or did you mean to be responding to some other issue?

> dada2 does not throw away singleton reads. However, it does not infer amplicon sequence variants that are only supported by a single read - singletons are assumed too difficult to differentiate from errors. Hence no singletons in the output table of amplicon sequence variants.

Well put.

> Right now we have no option to infer sequence variants supported by singleton reads.

Now we do have that option, actually. One approach is to [use pooling](https://benjjneb.github.io/dada2/pool.html), either `pool=TRUE` or `pool="pseudo"` to identify sample-wise singleton ASVs. The other option is to use the `DETECT_SINGLETONS=TRUE` option in the `dada(...)` function. This will detect singleton ASVs using the DADA2 algorithm.

**Comment by bodya67** [comment]
I am sorry if i did something wrong by opening a new issue. As i said, i read article about dada2 and its algorithm. I was confused about singletons. I did not find information how dada2 can produce them. I thought there was some problems with dada2 on my computer or something. 

Thank you for your explanation!
