### ISSUE TITLE
INCREASE in reads following merging

### ISSUE THREAD

**Issue by rosieeccy** [benjjneb/dada2#1493]
Hello, 

I've been successfully using a version of the dada2 pipeline customised to our samples, but in my latest run it looks like the number of reads INCREASES following merging - see attached Tracking csv for examples, where those with an increasing no of reads are highighted in red/orange. I've tried increasing the length of trimmed reverse reads (within what looks OK on quality plots) and the minOverlap parameter to no avail. Do you have any idea what might be going on here?

One theory I had was that errors may mean some ID reads are being wrongly allocated to samples - the error plots don't like quite as nice as on previous analysis sets - especially as they are 'next' to each other in our homemade ID database so potentially also similar ID sequence wise.

Thanks in advance,

Rosie

[ErrorPlots.docx](https://github.com/benjjneb/dada2/files/8042961/ErrorPlots.docx)
[Track_edit.csv](https://github.com/benjjneb/dada2/files/8042965/Track_edit.csv)

**Comment by cjfields** [comment]
Looking at the table, I think there might be issues with how samples are being tracked in your custom pipeline and issues with the pipeline logic, possibly between the filtering and denoising steps ('filtered' and 'denoisedF/R' columns) though in some cases it also look like a mismatch between input and filtering steps.  For example, you have samples with very high initial counts like 5C_31 suddenly drop to 10%, then others like 4A_98 with very low inputs which suddenly have 10k reads.  

W/o seeing the code itself it's hard to diagnose, but we have seen something like this before when using workflow tools like Nextflow when needing to mix or combine steps, for example when pulling in R1 and R2 channels to merge, or when combining them with the error model for the `dada` call.  The resolution is to track all data with samples IDs and join data where needed by their ID.
