### ISSUE TITLE
Problem with taxonomic assignment?

### ISSUE THREAD

**Issue by rahulnccs** [benjjneb/dada2#1495]
Dear @benjjneb, I ran DADA2 on my microbiome data and got an issue with taxonomic assignment. 
I am working with synthetic microbial community so used customized database (full length 16S rRNA gene seq). However, in the output I couldn't get the taxonomic assignment for one of my bacteria (Enterobacter).  The thing is I have already confirmed the presence/high abundance of that Enterobacter by fluorescent microscopy (bacteria was labelled with red fluorescent protein). 

Here are details:
1. When used default parameter of  mergePairs got very few (almost nothing) nochim and merged reads. So, I changed the "mergePairs" parameters  as below and got satisfactory number of merged/nochim reads:
     a. mergers <- mergePairs(dadaFs, filtFs, dadaRs, filtRs, verbose=TRUE, **justConcatenate = T**)  &
     b.  mergers <- mergePairs(dadaFs, filtFs, dadaRs, filtRs, verbose=TRUE, **minOverlap = 4**)  

2. My data is generated my Miniseq platoform that generated  forward/reverse read of 150bases. Sequence quality was good (Q>30)so I did not trim at filterTrim. 

3. Kindly, guide through this and let me know where I can improve.

**Comment by benjjneb** [comment]
> When used default parameter of mergePairs got very few (almost nothing) nochim and merged reads.

The issue is almost certainly here. But the answer is usually not to just concatenate the reads together, rather it is to understand the sequencing library and use the appropriate merging approach.

What is the length of the sequenced amplicon you are using? Will the reads overlap? Or.... will they not? It is important to understand the length of the "sequenced amplicon", which may or may not include the primer sequences depending on your library preparation.

**Comment by rahulnccs** [comment]
I agree with you. F and R reads aren't long enough to merge by default parameters. The amplicon is close to 300bases (V4 region primers: 515F and 806R) and I have used 150*2 chemistry. I will try using forward reads only. Further suggestions are most welcome.

In case you want to inspect. Here are the reads from one sample. 
[S27_L001_R1_001.fastq.gz](https://github.com/benjjneb/dada2/files/8057062/S27_L001_R1_001.fastq.gz)
[S27_L001_R2_001.fastq.gz](https://github.com/benjjneb/dada2/files/8057069/S27_L001_R2_001.fastq.gz)
