### ISSUE TITLE
filterAndTrim object retains all sample names   

### ISSUE THREAD

**Issue by vanormbr** [benjjneb/dada2#1496]
Dear Dr. Callahan,

I am processing Miseq v3 600 PE data for the 16S V3-V4 region (319F, 806R). I used cutadapt to remove heterogeneity spacer/primer at the 5'-end. What remains are mostly 250-280 bp insert reads. Upon reaching the track table part of the DADA2 tutorial I find that counts are not ordered properly, associated with the wrong sample. Samples which begin with low read counts end up with more after denoising or merging. I don't see how this could be the actual case. 

![TrackTableIssue](https://user-images.githubusercontent.com/64625376/154004709-a645250e-0276-4ccc-a801-8e908fac2445.png)

It looks like the out dataframe retains all input sample names (n=307), but some of these are dropped due to low sequence count/quality resulting in 298 samples in the "filtered" directory. The absence of these 9 samples in subsequent seqtab and seqtab.nochim tables appears to affect track table construction.  
dim(out)
[1] 307 2
dim(seqtab.nochim)
[1] 298 10603 
dim(track)
[1] 307 6

My rudimentary fix is running filterAndTrim again with updated sample.names list and on the filtered files folder, naming it out2, and using this updated object when building the track table. has this issue already been addressed in a prior string, and if not, do you any suggestions for doing this that do not involved re-running filterAndTrim, preferably retaining all sample in the final track table?

I appreciate the help!
Best,
-Bryan

**Comment by benjjneb** [comment]
Hi Bryan,
The normal fix here is to just subset the `out` table to the set of samples that passed the filter with >0 reads. Then the subset version of that table will be of the same dimension as the other tables when you put them together at the track step (and I hope R gave you a warning when you put those tables together that were of different dimensions?).

```
passed.filter <- out[,2] > 0 # or file.exists(filtF)
out.nonzero <- out[passed.filter,]
```

That doesn't keep the samples in the final table that were lost at filtering step, but that could also be achieved with a little more R manipulation.
