### ISSUE TITLE
Too many sequences from 16s analysis

### ISSUE THREAD

**Issue by otaviolovison** [benjjneb/dada2#1497]
Hello!

I am running a 16s analysis and apparently I'm getting too many sequences/taxa (based on videos I have watched - I'm a rookie).
The samples were sequenced using Ion Torrent plataform - v4 region. I am getting like 2507 taxa from 66 samples (I have watched a video were the researcher shows like 300 taxa from an Illumina sequencing, so, I believe 2507 taxa are too much).
I have reviewed the entire script and apparently everything is right.
I am removing primers with the trimleft argument and performing the adjustments in the script based on the tutorial. Maybe there's something wrong and I am not seeing it. Or, maybe, this taxa count is correct...? I don't know..

Sorry for the inconvenience and thank you so much in advance.

Best regards.

**Comment by benjjneb** [comment]
The number of unique sequences/taxa that are present varies greatly from environment to environment, and often between conditions within common environments. On top of this, the number of taxa detected by maker-gene sequences (e.g. 16S ASVs) will depend on how deeply samples are sequenced -- the deeper the sequencing, the more new taxa will be detected.

It is also true that the number of artefacts and errors also varies a lot between studies and protocols.

That said, that you are seeing a higher number of taxa than what you saw in the video you are watching does not immediately indicate cause for concern. And the numbers of different taxa you are reporting seem pretty normal for medium-high diversity microbiomes.

**Comment by otaviolovison** [comment]
Thank you so much!
