### ISSUE TITLE
mergeSequenceTables - Shared Variants Between Runs

### ISSUE THREAD

**Issue by gblanchard4** [benjjneb/dada2#150]
I am currently working with two MiSeq runs worth of V4 vaginal sequencing and attempting to do the CST generations like you describe in your (fantastic) [CST Analysis: Vaginal Samples
](http://statweb.stanford.edu/~susan/papers/Pregnancy/PNAS_Vaginal_Analysis.html) writeup.

The data had good quality for both runs. I used `trimLeft=c(10, 10), truncLen=c(240, 240)` to filter each run. I wanted to use the same filtering steps so the variants could be compared equally between runs. 

Next, I used the steps described in the [Big Data: Paired-end tutorial](http://benjjneb.github.io/dada2/bigdata_paired.html) and infered sequence variants for each run independently. I removed bimeras then merged the `seqtab.nochim` files together using `mergeSequenceTables()`

I end up with a 4323 of variants, which I _feel_ is a lot for the vaginal microbiome. I made a heatmap of the top 75 most abundant variants to view the differences in the runs. 

![run_diffs](https://cloud.githubusercontent.com/assets/1793818/20087540/0004974c-a53f-11e6-9844-13ef9ffb9dd0.png)

To inspect the data further I brought it into phyloseq
```
> ps
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 4323 taxa and 365 samples ]
sample_data() Sample Data:       [ 365 samples by 56 sample variables ]
tax_table()   Taxonomy Table:    [ 4323 taxa by 8 taxonomic ranks ]
```

I then subsetted my phyloseq object per MiSeq run and computed the shared variants using the intersection of each run's variants
```
# Subset by Run
ps.25 <- subset_samples(ps, Run=="R25")
ps.28 <- subset_samples(ps, Run=="R28") 
# Filter out empty rows
ps.25 <- filter_taxa(ps.25, function(x) sum(x) > 0, TRUE) # [ 1926 taxa and 199 samples ]
ps.28 <- filter_taxa(ps.28, function(x) sum(x) > 0, TRUE) # [ 2585 taxa and 166 samples ]
# Compare otutables
# Node is a unique numerical identifier
otus.25 <- tax_table(ps.25)[,"Node"] # length(otus.25)==1926
otus.28 <- tax_table(ps.28)[,"Node"] # length(otus.28)==2585
taxa.shared <- intersect(otus.25, otus.28)  # length(taxa.shared)==304
ps.share <- prune_taxa(tax_table(ps)[,"Node"] %in% taxa.shared, ps)
```

So I end up with 304 variants shared between runs. to me, this seems a little more reasonable for the vaginal microbiome. 

My questions to you:
* Do you think I should be more stringent with filtering to reduce the number of run-specific-variants?
* Would computing CSTs using only shared variants be a valid approach?
* Should `mergeSequenceTables` have an option to output only consensus variants? Or should this be handled separately?
* Should `mergeSequenceTables` have a verbose flag to let you know how many variants are shared/unique?

**Comment by benjjneb** [comment]
A lot here, so I may have to come back to this one later.

To answer a couple questions:

> Do you think I should be more stringent with filtering to reduce the number of run-specific-variants?

It's definitely worth trying but, because contamination, especially at low-levels, can be a big and very run-specific issue, it may not solve the problem. Another thing to try is to perform chimera removal on the merged table, rather than on the per-run tables before merging. (*We are working on better methods to remove contaminants, but they are still in progress for now*)

> Would computing CSTs using only shared variants be a valid approach?

Probably. I would want to know what the total fraction of reads the non-shared variants make up before stating that for certain though. CST assignment should be pretty insensitive to low-frequency variants.

>  Should mergeSequenceTables have an option to output only consensus variants? Or should this be handled separately?

Maybe. I'll have to think about that one.

> Should mergeSequenceTables have a verbose flag to let you know how many variants are shared/unique?

Yes. The complication here is how to deal with the output from merging multiple tables. It should also warn when one of the merged tables is completely unique from the rest (this happens when trimming is different between runs).

**Comment by gblanchard4** [comment]
Yeah, this was a big brain dump last night I understand if you need to come back.

I am going to try the removing bimeras after merging sequence tables. I'll calculate the non-shared variant percentages for both the merge-then-filter and the filter-then-merge techniques to give you a bit more information too.

**Comment by gblanchard4** [comment]
So after reviewing my steps (and getting some sleep) I realized I actually did filter the runs slightly different. 
I reran each run (and confirmed the same filtering) and it looks like my run-specific-variant issue largely vanished. 

I did take a look at merging before and after bimera filtering, here are some numbers I got:

| File                | Count  | Description                 |
| :------------------ | :----- | :-------------------------- |
| seqtab.25           | 5192   | Run25 Reads                 |
| seqtab.28           | 6136   | Run28 Reads                 |
| seqtab.merge        | 9854   | Merged Runs                 |
| seqtab.nochim.25    | 1926   | Run25 Bimera Filtered       |
| seqtab.nochim.28    | 2762   | Run25 Bimera Filtered       |
| seqtab.merge.nochim | 3908   | Merged then Bimera Removal  |
| seqtab.nochim.merge | 4375   | Bimera Filtered then Merged |

I don't feel like I need to look at the shared variants, the effect I saw before was due to different filtering. 
I ran the numbers anyway for my own curiosity though. 

| File                | Counts |
| :------------------ | :----- |
| seqtab.merge.nochim | 381    |
| seqtab.nochim.merge | 304    |

The shared variants both make up about 91% of the total reads
