### ISSUE TITLE
After Clustering ASVs  of DADA2, what exactly to deal with the New OTU table?

### ISSUE THREAD

**Issue by fenglong616** [benjjneb/dada2#1500]
Hi, I am new about metadata, I am trying to follow the pipe ITS of Dada2, and I got the ASVs table, but I want to cluster the ASVs to an OTUs table.(97%) according to the codes you have been given, I have OTUs table now.  But I am wondering about what to do next. I am going to use Phyloseq for processing. I am not sure about  the ASVs_ taxonomy  can be used for the OTUs table.  
Do I need to assign taxonomy by the new OTU? and how can I do it? I am so confused about the process.

**Comment by fenglong616** [comment]
@benjjneb
Hi again, thanks for your reply!
I tried to do assign taxonomy, it seems like does not work! I upload the screenshot of my script. it is based on the tutorial of DADA2, I am not sure whether it is correct after clustering  ASVs to the new OTUs. could you give me more advice?
![1645461173512](https://user-images.githubusercontent.com/76115577/154996497-ad900e3c-fc34-4191-bc93-b63899303830.jpg)

**Comment by benjjneb** [comment]
You want to make sure that whatever you give `assignTaxonomy` (in this case `merged_seqtab`) can correctly get the DNA sequences in character format extracted from it by the `dada2::getSequences` function.

The easiest thing is to just make a character vector yourself to ensure its in the right format. That is, extract a character vector of the cluster sequences from the `merged_seqtab` object, and give that to `assignTaxonomy`.
