### ISSUE TITLE
Cutadapt issue: system2 function cannot find cutadapt file

### ISSUE THREAD

**Issue by qzjsyb** [benjjneb/dada2#1502]
Hi Ben,
I wonder if it is a common issue with cutadpt and system2 function, or it only happens on me. When I used the system2 function to access cutadapt, as the ITS Tutorial indicates, an error shows as 

> system2(cutadapt, args = "--version")
sh: ~/.local/bin/cutadapt: No such file or directory
Warning message:
In system2(cutadapt, args = "--version") : error in running command

However, the directory should not be an issue, since system function works well. The code also runs well on Terminal. 

> system("~/.local/bin/cutadapt --version") 
3.6

It is not the first time I use DADA2 for ITS. This error didn't occur in previous times (probabally a year ago). Any idea?

Best regards,
Ben Yang

**Comment by benjjneb** [comment]
Try giving an absolute path from root, something like `/usr/username/.local/bin/cutadapt`. The problem may be how the tilde character is being interpreted by `system2`.

**Comment by qzjsyb** [comment]
Works! thanks a lot.
