### ISSUE TITLE
Error in generating quality plots, similar to case #977?

### ISSUE THREAD

**Issue by science-chump** [benjjneb/dada2#1503]
Hello, I am running into a problem similar to issue #977.  When I use cutadapt, it is getting rid of most of the primers but not all of them. I tried switching the F and R primers and also used the reverse compliments and each time it leaves some primers in the sequences. Additionally, I increased the # of times cudadpt checks sequences from 2 to 100 and the results were the same. Since it appears to be a low amount of primers kept and the sequences are going to be filtered, then trimmed with ITSxpress, it didn't seem particularly alarming.

In any case when I go to proceed to the next step to generate quality plots it is giving me an error message resembling the previous case which makes me think they may be related. Here is the error:

```
Error in data.frame(sequence = names(freqtbl$top), count = as.integer(freqtbl$top),  : 
  arguments imply differing number of rows: 0, 1
Calls: plotQualityProfile ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

The solution you provided in case #977 does not appear to apply to mine because when looking at the files the code is being directed to, they all are zipped and end in .gz. Likewise when I changed the flag to compress=FALSE, I generated a ton more errors. It also does not appear that cutadapt is removing all of the sequences in any instance because the size of the files are above 1,000 kb (in the past when cutadapt has removed everything the file size was 1kb).

Anyways I was hoping you could help me figure out what to do next. Appreciate the insight and all the work you do on the dada2 github.

![image](https://user-images.githubusercontent.com/61884350/155611697-c301366f-b5bf-4d5e-ac43-1045e24a4b44.png)

**Comment by science-chump** [comment]
I figured out the issue and it turned out not to be a dada2 issue but an issue with the sequencing platform. Since these were done using novaseq, a string of poly G's were added to many of the sequences. By adding a flag in cutadapt I was able to generate quality plots :)

This is the flag in case anyone else runs into the same issue.
"--nextseq-trim=20" in your cutadapt code line.

**Comment by leoneago** [comment]
I got the very same error and the solution proposed by @science-chump doesn't work with my data. Anyone else figured out how to solve this?
Best,

**Comment by science-chump** [comment]
Following up on this thread, I have run into this issue again after adding in the line above.

The issue is that some samples (like PCR blanks) are completely empty following the cutadapt step. My solution was to remove these samples, then rerun the cutadapt step without them. Should make the quality plot issue solved.
