### ISSUE TITLE
segfault error on denoising 

### ISSUE THREAD

**Issue by afvrbanac** [benjjneb/dada2#1505]
Hello, I'm working with long PacBio reads (trimmed/filtered to between 1900 to 3000 bp) for 95 samples. I am using a beefy r5a.12xlarge AWS EC2 instance running Ubuntu 20.04. I have successfully made it through the learnErrors step, but am getting the following segfault error when I try to run dada2:

`dd <- dada(drp, err=err, BAND_SIZE=32, multithread=TRUE, OMEGA_A=1e-10, OMEGA_C=1e-80, PSEUDO_PREVALENCE=2, pool=TRUE)

Loading required package: Rcpp
95 samples were pooled: 1810347 reads in 1769593 unique sequences.

 *** caught segfault ***
address (nil), cause 'unknown'
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation

Traceback:
 1: dada_uniques(names(drpi$uniques), unname(drpi$uniques), names(drpi$uniques) %in%     c(priors, pseudo_priors), erri, unname(t(drpi$quals)), opts[["MATCH"]],     opts[["MISMATCH"]], opts[["GAP_PENALTY"]], opts[["USE_KMERS"]],     opts[["KDIST_CUTOFF"]], opts[["BAND_SIZE"]], opts[["OMEGA_A"]],     opts[["OMEGA_P"]], opts[["OMEGA_C"]], opts[["DETECT_SINGLETONS"]],     if (initializeErr) {        1    } else {        opts[["MAX_CLUST"]]    }, opts[["MIN_FOLD"]], opts[["MIN_HAMMING"]], opts[["MIN_ABUNDANCE"]],     TRUE, FALSE, opts[["VECTORIZED_ALIGNMENT"]], opts[["HOMOPOLYMER_GAP_PENALTY"]],     multithread, (verbose >= 2), opts[["SSE"]], opts[["GAPLESS"]],     opts[["GREEDY"]])
 2: dada(drp, err = err, BAND_SIZE = 32, multithread = TRUE, OMEGA_A = 1e-10,     OMEGA_C = 1e-80, PSEUDO_PREVALENCE = 2, pool = TRUE)
An irrecoverable exception occurred. R is aborting now `

Here is my R session info:

```
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.3.5 dada2_1.20.0  Rcpp_1.0.8   

loaded via a namespace (and not attached):
 [1] SummarizedExperiment_1.24.0 reshape2_1.4.4             
 [3] lattice_0.20-45             colorspace_2.0-3           
 [5] vctrs_0.3.8                 stats4_4.1.2               
 [7] utf8_1.2.2                  rlang_1.0.1                
 [9] pillar_1.7.0                glue_1.6.1                 
[11] withr_2.4.3                 BiocParallel_1.28.3        
[13] BiocGenerics_0.40.0         RColorBrewer_1.1-2         
[15] matrixStats_0.61.0          jpeg_0.1-9                 
[17] GenomeInfoDbData_1.2.7      lifecycle_1.0.1            
[19] plyr_1.8.6                  stringr_1.4.0              
[21] zlibbioc_1.40.0             MatrixGenerics_1.6.0       
[23] Biostrings_2.62.0           munsell_0.5.0              
[25] gtable_0.3.0                hwriter_1.3.2              
[27] labeling_0.4.2              latticeExtra_0.6-29        
[29] Biobase_2.54.0              IRanges_2.28.0             
[31] GenomeInfoDb_1.30.1         parallel_4.1.2             
[33] fansi_1.0.2                 scales_1.1.1               
[35] DelayedArray_0.20.0         S4Vectors_0.32.3           
[37] RcppParallel_5.1.5          XVector_0.34.0             
[39] ShortRead_1.52.0            farver_2.1.0               
[41] Rsamtools_2.10.0            png_0.1-7                  
[43] digest_0.6.29               stringi_1.7.6              
[45] GenomicRanges_1.46.1        grid_4.1.2                 
[47] cli_3.2.0                   tools_4.1.2                
[49] bitops_1.0-7                magrittr_2.0.2             
[51] RCurl_1.98-1.6              tibble_3.1.6               
[53] crayon_1.5.0                pkgconfig_2.0.3            
[55] ellipsis_0.3.2              Matrix_1.4-0               
[57] R6_2.5.1                    GenomicAlignments_1.30.0   
[59] compiler_4.1
```

**Comment by benjjneb** [comment]
My first guess is that this would be a memory issue, can you try a quick test where you just run say the first 3 samples, and see if that proceeds as expected? If that also fails, then it would be good to try to create a minimal example using as little data as possible that reproduces the error.

I'll also note, the instantiation of `dada(..., PSEUDO_PREVALENCE=2, pool=TRUE)` doesn't make sense. The `PSEUDO_PREVALENCE` option only matters if you are using the pseudo-pooling mode, which is enabled by `pool="pseudo"`. See more here: https://benjjneb.github.io/dada2/pseudo.html

**Comment by afvrbanac** [comment]
Hello, I actually just got it to run with both having pool=FALSE or pool="pseudo" so I assume you are right! I'll test out your suggestion once my other dataset finishes to confirm. 

Just curious, do the longer reads use significantly more memory when running denoising in your experience than short reads? I'm wondering if it would even be possible to pool for larger PacBio datasets or if I would need some absolutely massive EC2 instance.

**Comment by benjjneb** [comment]
`dada(..., pool="pseudo")` only needs to load one sample into memory at a time, so it's memory usage scales just fine to long reads. But yes, long reads to take more memory, total memory usage scales roughly linearly in read-length (all else constant), and this can cause an issue with `pool=TRUE`, which is the most memory intensive way to run DADA2.
