### ISSUE TITLE
fastqFilter() cant write new file 

### ISSUE THREAD

**Issue by BjnNowak** [benjjneb/dada2#1506]
In the [Zymo tutorial](https://benjjneb.github.io/LRASManuscript/LRASms_Zymo.html), I found a small bug with the fastqFilter() function

- the removePrimers() function (the first one we use) creates by itself the folder + the file according to the 'nop' object (in which we specified the access path)
- But, the next one, fastqFilter() does not succeed in creating the 'filtered' folder + the new filtered file. To work around this, I had to manually create a 'filtered' folder + copy a copy of the unfiltered file. This file was then be replaced by the filtered version when I executed the function.

(R version 4.0.3)

**Comment by BjnNowak** [comment]
I realized the tile was unclear coz the error message was:
"Error in writeFastq(fq, fout, "w", compress = compress) : 
  failed to open file 'Data_test/filtered/zymo_CCS_99_9.fastq'"

**Comment by benjjneb** [comment]
I'm not familiar with an error that presents like what you have described.

Can you create a "minimal example", i.e. code alongside test data (preferably a single sample) that reproduces this error?

**Comment by BjnNowak** [comment]
Hi, thanks for the reply. Below is my code. Sorry, I did not extract a sample data coz I rather not mess with fastq file... The original file is the zymo file for your [tuto](https://benjjneb.github.io/LRASManuscript/LRASms_Zymo.html) that I downloaded [here](https://sra-pub-src-1.s3.amazonaws.com/SRR9089357/zymo_CCS_99_9.fastq.gz.1). Though it should work with compressed file, I 'decompressed' the file in this example, but I have the same problem as mentionned in previous post.

# Load libraries 
library(dada2)
library(Biostrings)
library(ShortRead)
library(tidyverse)
library(reshape2)
library(RColorBrewer)

# Set environment (working here inside an RStudio project)
path <- "Data_test" 
path.out <- "Figures/" 
path.rds <- "RDS/" 
fn <- file.path(path, "zymo_CCS_99_9.fastq") # 'Decompressed' file 
F27 <- "AGRGTTYGATYMTGGCTCAG"
R1492 <- "RGYTACCTTGTTACGACTT"
rc <- dada2:::rc
theme_set(theme_bw())
genusPalette <- c(
  Bacillus="#e41a1c", Enterococcus="#377eb8", Escherichia="#4daf4a", 
  Lactobacillus="#984ea3", Listeria="#ff7f00", Pseudomonas="#ffff33", 
  Salmonella="#a65628", Staphylococcus="#f781bf"
)

# Remove primers
nop <- file.path(path, "noprimers", basename(fn))
prim <- removePrimers(
  fn, 
  nop, 
  primer.fwd=F27, 
  primer.rev=dada2:::rc(R1492), 
  orient=TRUE, verbose=TRUE)

# Same output as in the tuto -> seems to work

# Inspect length distribution
hist(nchar(getSequences(nop)), 100)

# Filter -> Works only if folder and file created beforehand
filt <- file.path(path, "noprimers", "filtered", basename(fn))
track <- fastqFilter(
  fn = nop, 
  fout = filt, 
  minQ=3, minLen=1000,
  maxLen=1600, maxN=0, rm.phix=FALSE, maxEE=2, verbose=TRUE)
