### ISSUE TITLE
Understanding exactly how "assignTaxonomy" works

### ISSUE THREAD

**Issue by laura-vangalen** [benjjneb/dada2#1507]
Hello, I'm trying to understand how the "assignTaxonomy" function works. 

Ultimately I want to know whether it's possible for a sequence to be named as "genus A" with a bootstrap confidence of 100, but it really belongs to "genus B" that's not included in the reference database. I.e. I want to know whether bootstrap confidence levels are based on exact matches or closest matches.

I've tried to read extensively about the Naïve Bayesian Classifier algorithm in [Wang et al 2007](https://journals.asm.org/doi/10.1128/AEM.00062-07) but I'm really struggling to understand it. From what the [dada2 tutorial says](https://benjjneb.github.io/dada2/assign.html#:~:text=assignSpecies%20uses%20exact%20string%20matching,returned%20if%20it%20is%20unambiguous.) it seems that firstly, the reference sequence with the most similar kmer profile to the query sequence is selected. To calculate the bootstrap confidence, Wang et al 2007 then says that subsets of kmers of size 8 are selected, and I gather matched to the reference sequence. Is the bootstrap confidence level then the number of times the kmers exactly matched the reference sequence? I.e. can I then be confident that the taxonomic assignment is correct, and not just the best possible assignment given what's in the reference database?

I would love it if someone could summarise the explanation of how the bootstrapping works from Wang et al 2007 in more understandable language.

**Comment by benjjneb** [comment]
> Is the bootstrap confidence level then the number of times the kmers exactly matched the reference sequence? I.e. can I then be confident that the taxonomic assignment is correct, and not just the best possible assignment given what's in the reference database?

The bootstrap confidence is the number of times the subset of kmers matched the same taxon (not necessarily the same reference sequence) as the full kmer representation of the query sequence. Exact matching is not required, it is only a best match.

It is possible to get spurious assignments with high bootstrap confidence when the reference database does not include appropriate outgroups, i.e. representatives of other taxa that would be the best match to the subsetted kmer profiles if they were present.
