### ISSUE TITLE
Tracking paired-end reads after merging

### ISSUE THREAD

**Issue by Username-felix-is-not-available** [benjjneb/dada2#1508]
First of all: Thank you for your amazing work and well documented software.

I am aware that there have already been several issues about read tracking (e.g.: #354 and #890 ), but I haven’t found any exact match for my problem. I simulated paired-end MiSeq reads and I want to benchmark tools downstream of DADA2. Each raw read uses the expected taxonomy ID as the read ID. I processed my reads following the tutorial (https://benjjneb.github.io/dada2/tutorial.html) with the latest version of DADA2. I only skipped the chimera filtering, as my simulation did not produce any chimeras. Now I need to map the expected classification from my raw reads to the reads merged by DADA2.
My raw reads were in matching order and named with patterns like taxonA-read1/1, taxonB-read1/1,... and taxonA-read1/2, taxonB-read1/2, .... Will DADA2 consider which read IDs were put in each ASV and only merge forward “taxonA” ASVs with reverse “taxonA” ASVs? Or is the merging purely based on alignment and perfect overlap between the ASVs? In the latter case, I guess technically “taxonA” and “taxonB” ASVs could be merged, if they were similar enough. This would complicate things a little bit for me, because then the expected classification of the “chimeric” read would not just be the expected classification of the forward ASV or reverse ASV, but something like the LCA.

Have a nice day,
Felix

**Comment by benjjneb** [comment]
> My raw reads were in matching order and named with patterns like taxonA-read1/1, taxonB-read1/1,... and taxonA-read1/2, taxonB-read1/2, .... Will DADA2 consider which read IDs were put in each ASV and only merge forward “taxonA” ASVs with reverse “taxonA” ASVs?

No. `mergePairs` has no knowledge of the taxonomic assignment.

> Or is the merging purely based on alignment and perfect overlap between the ASVs? In the latter case, I guess technically “taxonA” and “taxonB” ASVs could be merged, if they were similar enough. 

Yes, this could happen.

**Comment by Username-felix-is-not-available** [comment]
Thank you for the clarification! 

I would like to double-check one more thing with you: The dada-class$map vector sometimes contains "NA". Are these the unique reads that were lost/filtered during ASV generation?

Best,
Felix

**Comment by benjjneb** [comment]
> The dada-class$map vector sometimes contains "NA". Are these the unique reads that were lost/filtered during ASV generation?

Yes. That behavior is controlled by the `OMEGA_C` parameter descibed (briefly) here: https://benjjneb.github.io/dada2/ReleaseNotes_1_8.html

In a typical sample and with default `OMEGA_C`, only a small fraction of reads should be lost at the denoising stage though.
