### ISSUE TITLE
Problems with merged batches

### ISSUE THREAD

**Issue by marcinschmidt** [benjjneb/dada2#1510]
Hi!
I have three sequencing batches that were all prepared with the same primers (V3-4) and send to a company for the second stage of library preparation and sequencing on MiSeq using 2x300PE. The first run was perfect as I can judge by plotQualityProfile, I went smooth with it through the analysis according to the tutorial (Great job!, I love it!). Later I decided to sequence more samples. The second batch was further divided by company so finally, I have three batches and the latter two are worse, but I think still fine (based on plotQualityProfile). I reviewed threads:
How to combine multiple runs that have different subsets of samples? #1406 
Merging Multiple Batches in DADA2 #175
Combining dada2 runs #716

I kept `trimLeft` for all bathes the same, for the latter two I had to relax `maxEE` and did:

>seqtab_all <-mergeSequenceTables(table1 = seqtab_run1, table2 = seqtab_run2, table3 = seqtab_run3, tryRC= TRUE)
Reverse complemented sequences detected and re-oriented.

But finally I did not like what I got all together. So I decided to check all three runs separately and all combined:
> seqtab.nochim.R1 <- removeBimeraDenovo(seqtab_run1, method="consensus", multithread=TRUE, verbose=TRUE)
Identified 26572 bimeras out of 36062 input sequences.
> seqtab.nochim.R2 <- removeBimeraDenovo(seqtab_run2, method="consensus", multithread=TRUE, verbose=TRUE)
Identified 5168 bimeras out of 7949 input sequences.
> seqtab.nochim.R3 <- removeBimeraDenovo(seqtab_run3, method="consensus", multithread=TRUE, verbose=TRUE)
Identified 2606 bimeras out of 5111 input sequences.
> seqtab.nochim.All <- removeBimeraDenovo(seqtab_all, method="consensus", multithread=TRUE, verbose=TRUE)
Identified 34273 bimeras out of 48412 input sequences.
> dim(seqtab.nochim.R1)
[1]  242 9490
![seqfreq_nochimR1](https://user-images.githubusercontent.com/45597260/157251119-b8af77f6-8a92-4532-926b-e0730367a6e9.png)

> dim(seqtab.nochim.R2)
[1]   96 2781
![seqfreq_nochimR2](https://user-images.githubusercontent.com/45597260/157251220-b795f06d-6cb3-4777-9d88-b11f233204f6.png)

> dim(seqtab.nochim.R3)
[1]   82 2505
![seqfreq_nochimR3](https://user-images.githubusercontent.com/45597260/157251255-792b2a2b-ba29-4d2a-bc95-4b9db73a1e27.png)

> dim(seqtab.nochim.All)
[1]   420 14139
![seqfreq_nochimAll](https://user-images.githubusercontent.com/45597260/157251272-d449b6df-9f2a-4848-984e-c93ce2f09ff6.png)

I removed sequences <380, assignTaxonomy, made phyloseq

> ps.R1
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 9320 taxa and 242 samples ]
tax_table()   Taxonomy Table:    [ 9320 taxa by 6 taxonomic ranks ]
> ps.R2
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 2656 taxa and 96 samples ]
tax_table()   Taxonomy Table:    [ 2656 taxa by 6 taxonomic ranks ]
> ps.R3
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 2494 taxa and 82 samples ]
tax_table()   Taxonomy Table:    [ 2494 taxa by 6 taxonomic ranks ]
> ps.All #show summary
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 13837 taxa and 420 samples ]
tax_table()   Taxonomy Table:    [ 13837 taxa by 6 taxonomic ranks ]

All the batches separately look fine but combined not. See the NMDS plots (vegan::metaMDS), run 1, run 2, run 3, all merged
![Rplot_NMDS_123ALL](https://user-images.githubusercontent.com/45597260/157251662-f94dadd6-de56-4552-91d0-56de68a7f238.png)

Can anyone tell me what I did wrong and how to fix it?
Best regards, Marcin

**Comment by marcinschmidt** [comment]
The distribution of sequences length for Run2 and Run3 looks shifted in comparison to Run1, so I checked for primers
 ```
rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.filtN[[1]]), 
+       FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.filtN[[1]]), 
+       REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.filtN[[1]]), 
+       REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.filtN[[1]]))

```
Run1 (242 samples)

```
                 Forward Complement Reverse RevComp
FWD.ForwardReads   43695          0       0       0
FWD.ReverseReads       3          0       0      27
REV.ForwardReads       4          0       0      72
REV.ReverseReads   44733          0       0       0
```

Run2 (96 samples)

```
                 Forward Complement Reverse RevComp
FWD.ForwardReads       0          0       0       0
FWD.ReverseReads      16          0       0      15
REV.ForwardReads      19          0       0      82
REV.ReverseReads       0          0       0       0
```

Run3 (82 samples)

```
                 Forward Complement Reverse RevComp
FWD.ForwardReads       0          0       0       0
FWD.ReverseReads       1          0       0       0
REV.ForwardReads       1          0       0       0
REV.ReverseReads       0          0       0       0
```
 
does it mean I need to omit `trimLeft=c(17, 21)` for the Run2&3? May it be the few sequences with primers found are by chance? Inspecting `plotQualityProfile` gives me impression that Run2&3 have already primers trimmed/
![Run1_plotQualityProfileR1](https://user-images.githubusercontent.com/45597260/157725695-e784701b-369c-4c39-960e-d67a16bad889.png)
![Run1_plotQualityProfileR2](https://user-images.githubusercontent.com/45597260/157725772-2bcb250b-4b54-454d-86f2-6558dd025370.png)
![Run2_plotQualityProfileR1](https://user-images.githubusercontent.com/45597260/157725799-a3d00d16-3cfa-4a2c-a3c9-03dfe30c717f.png)
![Run2_plotQualityProfileR2](https://user-images.githubusercontent.com/45597260/157725839-4c449164-8af0-4b6e-a158-ff228c32c478.png)
![Run3_plotQualityProfileR1](https://user-images.githubusercontent.com/45597260/157725862-fe168840-6a37-471c-bc94-845df567bcdc.png)
![Run3_plotQualityProfileR2](https://user-images.githubusercontent.com/45597260/157725901-8f93e3f2-ba76-43b7-80b0-5fde0c22af8e.png)

I used

```
filterAndTrim(minLen=175, trimLeft=c(17,21), truncLen=c(290,270), maxN=0, maxEE=c(2,2), truncQ=2)  #for Run1
filterAndTrim(minLen=175, trimLeft=c(17,21), truncLen=c(275,250), maxN=0, maxEE=c(2,4), truncQ=2) #for Run2
filterAndTrim(minLen=175, trimLeft=c(17,21), truncLen=c(275,250), maxN=0, maxEE=c(3,5), truncQ=2) #for Run3

```
Should I omit `minLen` ?

**Comment by marcinschmidt** [comment]
Looks like it was the primer issue. Run1 had the primer sequences left, but in Run2 & 3 the primers were already trimmed out. 

```
filterAndTrim(trimLeft=c(17,21), truncLen=c(290,270), maxN=0, maxEE=c(2,2), truncQ=2)  #for Run1
filterAndTrim(truncLen=c(275,250), maxN=0, maxEE=c(2,4), truncQ=2) #for Run2
filterAndTrim(truncLen=c(275,250), maxN=0, maxEE=c(3,5), truncQ=2) #for Run3
```

after merging the sequence tables the data looks promising:
![image](https://user-images.githubusercontent.com/45597260/157865188-6cbb3e61-ce0f-4838-9c34-18e15808495d.png)

Sorry to bother you with it.

Best regards,
Marcin

**Comment by benjjneb** [comment]
No worries, thanks for following up with the answer you worked out!
