### ISSUE TITLE
Fewer assignments when reference has more taxonomic labels

### ISSUE THREAD

**Issue by johnne** [benjjneb/dada2#1511]
Hi!
We're trying to benchmark assignTaxonomy together with some other tools for taxonomic classification of ASVs. In doing so we ran assignTaxonomy with 1000 test sequences against 3 versions of a reference database. These versions contained the same reference sequences but had different number of taxonomic levels in the fasta headers: 
1) Kingdom, Phylum, Class, Order, Family, Genus
2) Kingdom, Phylum, Class, Order, Family, Genus, Species
3) Kingdom, Phylum, Class, Order, Family, Genus, Species, BOLD_BIN

In the first attempt we used three different values for `minBoot`: `80`, `90` and `95`. The results are shown in the first figure below where `gen`, `spe` and `all` correspond to 1), 2) and 3) in the list above. As you can see, when the reference data has more taxonomic labels we get fewer taxonomic assignments, also for the higher taxonomic levels. This was a bit puzzling for us. We also ran with `outputBootstraps=TRUE` and plotted the distribution of bootstrap values at the Genus level in the 3 references (second figure below).

So bootstrap values are lowered when there are more taxonomic labels, also for higher taxonomic levels, resulting in fewer assignments at the same `minBoot` value. Maybe this is expected behaviour and a consequence of how the bootstrapping works, but it'd be great to hear your thoughts.

Cheers,
John

![Figure1](https://user-images.githubusercontent.com/4045781/157392124-39e4b288-3b65-4c0c-80f7-3ede5ae67e63.jpeg)
![bootstrap_assignTaxonomy](https://user-images.githubusercontent.com/4045781/157392911-d17acc1f-43f3-447e-9cfc-2c3ce61aae70.png)

**Comment by cjfields** [comment]
@johnne interesting result!  I'm guessing this is with the BOLD database?  We had issues with this one and used a VSEARCH-based approach, but now this makes me wonder if we should have delved into it more.  

Have you tested whether this occurs using the [original RDP implementation](https://github.com/rdpstaff/classifier)?

**Comment by johnne** [comment]
@cjfields, yes exactly this is with a training set from the BOLD database (clustered at 99% identity). We are also testing vsearch and SINTAX, as well as the sk-learn classifier (via qiime2) which is using the original RDP classifier method as I understand it. These other methods do not show the same type of unexpected results.

**Comment by benjjneb** [comment]
Thanks for reporting this behavior, and apologies for taking so long to respond.

In part I've been slow because I am confused as to what could be causing this behavior. I haven't seen anything similar, and the undrelying nBC algorithm we are implementing isn't obviously (to me) producing this sort of signal. Plus, you aren't seeing this same effect in other nBC implementations.

Do you have a realtively minmal example of this you could share? For example, a reduced genus-level and matched BOLD_BIN-level references together with query sequence(s) that show this effect?
