### ISSUE TITLE
Quality_plot_plotQualityProfile

### ISSUE THREAD

**Issue by ebertomeu** [benjjneb/dada2#1514]
Hello!! My name is Edgar, I am a new user of dada2 and microbiome analysis in general. I have a question about the tricked out value of R1 and R2 in my samples. I enclose quality graphs of each of the samples and the quality graphs with the average values ​​to see if someone can help me decide the trick values ​​and if I have to discard any sample.

Thank you

![image](https://user-images.githubusercontent.com/80527355/158339730-56624985-ef50-4f6f-8cdb-e30d8d431264.png)
![image](https://user-images.githubusercontent.com/80527355/158339782-c00dbc79-e3df-446d-8363-5bae0ea9ed6e.png)
![image](https://user-images.githubusercontent.com/80527355/158339821-1e97af52-01d8-4fdc-8bb5-8a38d706d0a0.png)
![image](https://user-images.githubusercontent.com/80527355/158339841-1575138d-631a-44f2-9483-c3edc49e3cf1.png)

**Comment by benjjneb** [comment]
First you need to identify how much overlap there is between. your forward and reverse reads. This depends on your primer set and how your library is prepared, in particular whether the primers are sequenced or not. Once you've identified the length of the sequenced amplicon (which may or may not include primers), you have to make sure that your truncation lengths add up to the sequenced amlpicon length plus an overlap margin of say 20 nts or more.

From there, select truncation lengths that are long enough to overlap, and that cut off as much low quality tail as you can.
