### ISSUE TITLE
Explanation on dada2 class object and its related table

### ISSUE THREAD

**Issue by ahkamsaddam** [benjjneb/dada2#1516]
![image](https://user-images.githubusercontent.com/29905262/158942005-710c2d44-2b64-41bc-a829-7405daf42351.png)
![image](https://user-images.githubusercontent.com/29905262/158942077-0105b2c0-05bc-4452-b06a-58907fc32b68.png)
![image](https://user-images.githubusercontent.com/29905262/158942159-5f2f09c9-5603-4ded-a815-b2595b01f0e1.png)
![image](https://user-images.githubusercontent.com/29905262/158944233-911f7ef4-35b8-47ec-86c0-61bc4021f0e4.png)

Hi, thanks for the DADA2 tool, I was recently working with dada2 tool in R. I have the following questions:
1) I came across the dada-object which contains lot of inner components. Some of the terms are explained in the tutorial. However, other components like birth_subs, trans, err_in, err_out needs some explanation. Also in the clustering table, it would be help if there could be some clarification on n0, n1, birth_from, birth_pval and other columns.  Also what the number in dadaFs[[1]]$trans indicate??? (Tried googling but failed to get any documentation to explain the terms). 

2) After executing dada() function in R, I got the sequence variants from the unique sequences. There were p-values for the unique sequences. My question is are the sequence variants selected from unique sequences based on p-value? If so what is the cut off?

I have attached the screenshots above. Thanks in advance for the explanation.

**Comment by benjjneb** [comment]
On 1. See `help("dada-class")` for some documentation of the components of a `dada-class` object. That said, you don't typically need to mess with the internals of a `dada-class` object in normal use cases.

On 2. The original paper describing DADA2 goes into some detail on how p-values are calculated and used. The default threshold is `OMEGA_A = 1e-40`, but that can be modified. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4927377/
