### ISSUE TITLE
Error Plot interpretation Illumina NovaSeq 6000

### ISSUE THREAD

**Issue by vollkorrn** [benjjneb/dada2#1524]
Hi there, 

I have a question about the interpretation of the error plot in Dada2. I have 250 bp PE reads of the v3v4 region (470 bp Amplicon) from Illumina NovaSeq 6000. 
The read quality is on the total length over 30, the search of adapters by Cutadapt has shown no adapter contamination of the reads. 
The error plot shows strange patterns where the error rate jumps at the highest phred score. This effect is always present even if only a subset of the samples is considered, the raw files or preprocessed Novoseq reads are used or if the number of bases used  to calculate the error rate is increased. 
I have not been able to find any similar plots so far and wonder what could be the cause, if any measures need to be taken. 
Another question would be why so many observed error rates are on the X-axis. Similar samples from MiSeq with a different primer pair but the same region do not show these patterns. 

Thank you very much for help! :)

<img width="970" alt="Screenshot 2022-04-03 at 15 10 56" src="https://user-images.githubusercontent.com/82929865/161429759-ad6e273d-0e56-4eb2-8874-17733dcfe59b.png">

**Comment by benjjneb** [comment]
Please see https://github.com/benjjneb/dada2/issues/1307

Short answer, you are OK to move forward with these error models. They look weird, but work well in previously analyzed mock community data.
