### ISSUE TITLE
getting such merged and nonchim results.

### ISSUE THREAD

**Issue by komalchrs** [benjjneb/dada2#1525]
hi I am getting these results, but I am not sure whether I am doing correctly or not. are the merged and nonchim fine like i am getting results less numbers. can someone please explain me. 
                input  filtered denoisedF denoisedR merged nonchim
10002S91 30364    24809     24675     24753      2       2
10003S32 43810    34515     34273     34414      0       0
10017S79 48933    40907     40557     40663     31      31
10023S44 42875    34968     34584     34802      6       6
10028S57 42237    34366     34038     34098     29      29
10070S83 44319    36770     36232     36427     45      45

**Comment by komalchrs** [comment]
Hi, in my asv file I am getting too much NA values, I tried all the options mentioned in the tutorial but the results is same. Can you please assist me how to solve this issue.

**Comment by benjjneb** [comment]
You are losing all your reads at the merging step. This is almost always because in your filtering/trimming step, the reads were cut too short, thus they now don't overlap.

How long is your sequenced amplicon? What truncation lengths did you use? Your truncation lengths should sum up to at least 20 more than the maximum length (accounting for possible biological length variation) of the sequenced amplicon.

**Comment by komalchrs** [comment]
> You are losing all your reads at the merging step. This is almost always because in your filtering/trimming step, the reads were cut too short, thus they now don't overlap.
> 
> How long is your sequenced amplicon? What truncation lengths did you use? Your truncation lengths should sum up to at least 20 more than the maximum length (accounting for possible biological length variation) of the sequenced amplicon.

hi, thank you very much for the reply you were right I was losing reads after truncation. I am working on the V1-V3 region.

**Comment by komalchrs** [comment]
Hello,
I am facing problem in creating phyloseq object can you please help me. For
example the name of my sample files is 102_S12_L001_R1_001, i have only
this much details. And I also don't have mock data, how to follow that code
please guide me.

Thanks and regards
Komal Chaurasia

**Comment by benjjneb** [comment]
@komalchrs This isn't enough information to be able to help. You'll have to be more precise about your problem, probably including what commands aren't working and what the error messages are.
