### ISSUE TITLE
Custom Taxonomy Training Set 

### ISSUE THREAD

**Issue by RFlazcano** [benjjneb/dada2#1526]
I have custom taxa and fasta files someone in my lab made for algal/cyanobacteria sequences but I believe they were formatted for mothur. I would like to use these datasets for IDTaxa but I've had no success in trying to format them correctly. 
How could I get them to work with dada2 and IDTaxa?
I've attached the zipped fasta file and taxa file for reference 

[cyano_and_algal_LSU_seqs.zip](https://github.com/benjjneb/dada2/files/8422610/cyano_and_algal_LSU_seqs.zip)
[cop_cyano_and_algal_LSU_seqs.txt](https://github.com/benjjneb/dada2/files/8422625/cop_cyano_and_algal_LSU_seqs.txt)

**Comment by benjjneb** [comment]
The `assignTaxonomy` format is described here: https://benjjneb.github.io/dada2/training.html#formatting-custom-databases

Get them in this format, and it will work with `assignTaxonomy`. For `IdTaxa`, I would refer to the DECIPHER package documentation.

**Comment by RFlazcano** [comment]
I took a look at the documentation for assignTaxonomy and tried using the `makeTaxonomyFasta_SilvaNR` function and its source code to get the format correct.  However I got the following error below: I thought this was a standard fasta file so I am not sure what the error refers to

Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: In .Call2("fasta_index", filexp_list, nrec, skip, seek.first.rec,  :
  reading FASTA file cyano_and_algal_LSU_seqs.fasta: ignored 1116877 invalid one-letter sequence codes
2: In file(file, "rt") :
 
 Error in file(file, "rt") : cannot open the connection
3.
file(file, "rt")
2.
read.table(ftax, sep = "\t", col.names = c("Taxon", "V2", "Level", 
"V4", "V5"), stringsAsFactors = FALSE)
1.
makeTaxonomyFasta_SilvaNR("cyano_and_algal_LSU_seqs.fasta", "cyano_and_algal_LSU_seqs.txt", 
"train_set.fa.gz", include.species = TRUE, compress = TRUE)

**Comment by benjjneb** [comment]
I wouldn't try using `makeTaxonomyFasta_SilvaNR` here, that is tailored specificaly for digesting the Silva database from its release format.

You probable need a bit of custom code here to convert the files in the format they are currently in to the fasta format specified for `assignTaxonomy`. Do you or a collaborator have any experience in this sort of format wrangling?

> I thought this was a standard fasta file so I am not sure what the error refers to

If you open your fasta file, you will see it is an "aligned" fasta file with lots of . and - characters, rather than just the sequences themselves as is more common (and expected by the function).

**Comment by RFlazcano** [comment]
Ok, that makes sense. I have some experience, though not much. I was just trying to remake the custom data set through arb but I'm new to ARB

**Comment by RFlazcano** [comment]
> You probable need a bit of custom code here to convert the files in the format they are currently in to the fasta format specified for `assignTaxonomy`. Do you or a collaborator have any experience in this sort of format wrangling?

I actually figured it out using regex and sed and it worked now with assign taxonomy!

**Comment by JFranklin5221** [comment]
> 

Hello, I see that you got the dataset to combine. I am interested in finding a dataset for 23S. Is there any chance you would be able to share the dataset you created so I may use it with DADA2. No worries if its a no, but thanks all the same!
