### ISSUE TITLE
error in fastqPairedFilter

### ISSUE THREAD

**Issue by m-ocejo** [benjjneb/dada2#153]
Hi!
I am a newbie and I am trying to include DADA2 in my pipeline.
The problem is that running fastqPairedFilter:

for(i in seq_along(fnFs)) {
  fastqPairedFilter(c(fnFs[i], fnRs[i]), c(filtFs[i], filtRs[i]),
                    trimLeft=c(10, 10), truncLen=c(240,160), 
                    maxN=0, maxEE=2, truncQ=2, 
                    compress=TRUE, verbose=TRUE)
}

Everything seems to be OK until it reaches the last file and gives me this error message: 
Read in 100298 paired-sequences, output 91391 filtered paired-sequences.
Read in 94644 paired-sequences, output 85291 filtered paired-sequences.
Read in 82795 paired-sequences, output 75003 filtered paired-sequences.
_Error in add(bin) : record does not start with '@'_

Any help??? Thanks a lot!

**Comment by benjjneb** [comment]
It's hard to say exactly, but that message indicates that the fastq files for the last sample aren't properly formatted. It might be worth glancing at the top of those fastq files in a text editor to see if there's something obviously amiss.

**Comment by m-ocejo** [comment]
Hi Ben! You were right! I think something was went wrong with the gunzip command so I rerun it.
Now I can carry on with the analysis.

Big thanks for such a quick reply!

**Comment by peterwc** [comment]
Hello!
I guess it is my turn to write one of these. I also received an error of "record does not start with '@'". 

For me this was caused by something adding (still uncertain of what that is) a '--' into my fastq file. This shifted the lines and caused some real problems. 

Thanks,
Peter
