### ISSUE TITLE
Can I use aa sequences with DADA2?

### ISSUE THREAD

**Issue by cahuparo** [benjjneb/dada2#1530]
Hi! 

I have somewhat random question:

I work with intracellular immune receptor proteins that carry a highly variable but also conserved domain ([NB-ARC domain](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3001124)). This domain is normally used to generate phylogenies that allow diversity studies. In my organism, I have annotated ~3000 of these proteins per individual. The NBARC domain can be align and matching columns of residues removed leaving only variable sites. The sequence can be reduced to ~400 amino acids long across all 3000 starting protein sequences. 

I am curious if there is way to utilize this short aa sequence to group these proteins in somewhat similar fashion used to group reads and assign OTUs in microbiome studies. If we have multiple individuals each carrying ~3000 of these sequences, can DADA2 be modify to use amino acid sequences as input files? 

I guess my ultimate goal is to be able to determine across individuals what sequences are common and if they could be group in "Operational units". 

Any suggestions are welcome!  

Best, 

Camilo

**Comment by benjjneb** [comment]
We do not support AA sequences, and don't expect to in any reasonable time frame.

In principle it is possible, but it would require replacing the core alignment algorithm, and significant testing on learning error models from the much larger 20x20 space of potential AA errors.
