### ISSUE TITLE
dada2 or DADA2

### ISSUE THREAD

**Issue by andzandz11** [benjjneb/dada2#1532]
![grafik](https://user-images.githubusercontent.com/19622117/163380704-4e02ca34-9259-45a1-bfc2-7dd8ac82c8c1.png)
![grafik](https://user-images.githubusercontent.com/19622117/163380774-537add5e-357a-416e-92f8-53be78a8eee9.png)

dada2 or DADA2, what is the official name? I am confused because it changes a lot on the official websites.
If DADA2 is the official name of the algorithm and dada2 is the name of the R package, why is the title of the website in the first image dada2?

**Comment by benjjneb** [comment]
Good question. We aren't consistent. The original idea was that DADA2 was the algorithm, which was implemented in the dada2 R package. That's possibly a silly distinction. When in doubt, DADA2 is preferred.

**Comment by andzandz11** [comment]
Thanks! This makes things clearer.
