### ISSUE TITLE
Dada2 vs Phyloseq generation fails: Component sample names do not match

### ISSUE THREAD

**Issue by safinaARK** [benjjneb/dada2#1533]
When im trying to make ps object using the following command I'm getting
 ```
Error in validObject(.Object) : invalid class “phyloseq” object: 
 Component sample names do not match
```
Command I ran:

```
> samdf <- data.frame(read.csv('sample_names.csv', header = TRUE, sep = ","))
> ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE), sample_data(samdf), tax_table(taxa))
```
What files do I need to provide to show where is the error?

**Comment by benjjneb** [comment]
The sample names in your otu_table and `sample_data` don't match one another. You can inspect this directly using:

```
otab <- otu_table(seqtab.nochim, taxa_are_rows=FALSE)
samdat <- sample_data(samdf)
sample_names(otab)
sample_names(samdat)
```

So take a look at the different sample_names and see if that helps diagnose the issue.
