### ISSUE TITLE
In filterAndTrim: No reads passed the filter

### ISSUE THREAD

**Issue by ng1dor** [benjjneb/dada2#1534]
Hello,

we came across problem with filterAndTrim, I run the 

> out <- filterAndTrim(fwd_reads, filtered_fwd_reads, rev_reads, filtered_rev_reads, truncLen = c(150,150),
>                      maxEE=c(2,2), rm.phix=TRUE, compress=TRUE, multithread=FALSE, matchIDs=TRUE)

but this warning showed:

> _In filterAndTrim(fwd_reads, filtered_fwd_reads, rev_reads, filtered_rev_reads,  :
>   No reads passed the filter. Please revisit your filtering parameters._

We used data after primers were removed (SEED2). Below you can see the quality profiles for first 3 samples, there are some drop in the beginning (in all forward samples), could that be the problem? I also tried  maxEE=c(8,8), but no success.

![forward](https://user-images.githubusercontent.com/104068837/164212530-dffeb056-aef8-4e31-a5d6-2ae543de812a.png)
![reverse](https://user-images.githubusercontent.com/104068837/164212536-a53a36ba-5615-4251-9ac8-693fd76c5fe5.png)

Overall we have 40 samples, but there are in most cases quite low number of reads (usually less than 10 000 reads), could that also be a problem?

Thank you very much!
Have a nice day :)

**Comment by benjjneb** [comment]
To diagnose, I'd start by pulling out a single sample (e.g. APP101), and then relax the filtering parameters until some reads pass the filter. First, if you turn off `matchIDs` do reads start passing? I don't know SEED2 in particular, but if that pre-processing step changes the id lines in the fastqs, that could result in total failure of `matchIDs`.

Second, `maxN=0` filtering is on by default. Set `maxN=500` and see if that allows reads to pass.

You can also set `maxEE=Inf` to just turn off that filtering entirely, and `truncQ=0`.
