### ISSUE TITLE
Taxonomy assign using IdTaxa

### ISSUE THREAD

**Issue by alanxelena** [benjjneb/dada2#1535]
Hi!!

 I have been trying to assign the taxonomy of my 16S sequencing using IdTaxa and the Silva_138 database but for some reason I get a weird output. In my taxonomy assigned ASV tab I get more than one ASV which correspond to the same taxon, each of them assigned to one sample but not to the rest of them.
 
To make it more graphic, this is an example of a repeated taxon
 
ASV_1024 | Bacteria | Proteobacteria | Gammaproteobacteria | Aeromonadales | Aeromonadaceae | Aeromonas
ASV_3019 | Bacteria | Proteobacteria | Gammaproteobacteria | Aeromonadales | Aeromonadaceae | Aeromonas
ASV_4757 | Bacteria | Proteobacteria | Gammaproteobacteria | Aeromonadales | Aeromonadaceae | Aeromonas
ASV_4798 | Bacteria | Proteobacteria | Gammaproteobacteria | Aeromonadales | Aeromonadaceae | Aeromonas
ASV_7982 | Bacteria | Proteobacteria | Gammaproteobacteria | Aeromonadales | Aeromonadaceae | Aeromonas

Which are assigned as follows (Columns are samples):

  | S107 | S108 | S131 | S158 | S187 | S221 | S233 | S44 | S48 | S76 | S97 | S99
ASV_1024 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 55 | 0 | 0 | 0
ASV_3019 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 28 | 0 | 0
ASV_4757 | 0 | 0 | 0 | 0 | 0 | 18 | 0 | 0 | 0 | 0 | 0 | 0
ASV_4798 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 18 | 0 | 0 | 0 | 0
ASV_7982 | 0 | 0 | 0 | 0 | 7 | 0 | 0 | 0 | 0 | 0 | 0 | 0

This output is confusing since I get (depending on the ASV that I look at) false unique ASVs/sample.

Do you have any suggestions regarding this? It would really really help me if you could solve this issue. I am pretty new at this so I am not that confident with playing around with the output myself.

By the way, this is the script I am using:

dna <- DNAStringSet(getSequences(seqtab.nochim))
tax_info <- IdTaxa(test=dna, trainingSet=trainingSet, strand="both", processors=NULL)
asv_seqs <- colnames(seqtab.nochim)
asv_headers <- vector(dim(seqtab.nochim)[2], mode="character")
for (i in 1:dim(seqtab.nochim)[2]) {
asv_headers[i] <- paste(">ASV", i, sep="_")
}
asv_fasta <- c(rbind(asv_headers, asv_seqs))
write(asv_fasta, "ASVs.fa")
asv_tab <- t(seqtab.nochim)
row.names(asv_tab) <- sub(">", "", asv_headers)
ranks <- c("domain", "phylum", "class", "order", "family", "genus", "species")
asv_tax <- t(sapply(tax_info, function(x) {
  m <- match(ranks, x$rank)
  taxa <- x$taxon[m]
  taxa[startsWith(taxa, "unclassified_")] <- NA
  taxa
}))
colnames(asv_tax) <- ranks
rownames(asv_tax) <- gsub(pattern=">", replacement="", x=asv_headers)

The shown (filtered) output corresponds to asv_tax and asv_count respectively

Thank you so so much!

**Comment by benjjneb** [comment]
In your example, when you compare those same-taxons ASVs to one another, how do they differ? I.e. at what rough positions in the reads?

To me, this pattern suggests there could be something wrong in your upstream processing that is leading to sample-specific ASVs, such as unremoved primers or sample-barcodes.

**Comment by alanxelena** [comment]
I have performed a previous QC check followed by quality trimming actually (I just didn't post the whole script). The FastQC report shows no signs of primers, adapters or so and the quality of the reads seems good enough, as a matter of fact I don't get Phret values below 28 even at the end. I am not sure about the rough position of the ASV in the reads though

**Comment by benjjneb** [comment]
Try aligning the same-taxon ASVs and identifying where the differences are. It is a helpful exercise at worst, and may immediately diagnose the issue.

**Comment by alanxelena** [comment]
Hi!

   Thanks for the reply and help! I have rerun the whole script using other samples to check if there was something wrong with the fastq files of that particular run but I still get this problem (sorry about the change but the issue is sitll the same :) ).
   In this case for example, I have a lot of Acinetobacter (Burkholderia, Acidiphilium, Aeromonas, among others):
  
This is a subset of the repeated results that I get:

ASV_95 | Bacteria | Proteobacteria | Gammaproteobacteria | Pseudomonadales | Moraxellaceae | Acinetobacter | NA
ASV_109 | Bacteria | Proteobacteria | Gammaproteobacteria | Pseudomonadales | Moraxellaceae | Acinetobacter | NA
ASV_115 | Bacteria | Proteobacteria | Gammaproteobacteria | Pseudomonadales | Moraxellaceae | Acinetobacter | NA
ASV_124 | Bacteria | Proteobacteria | Gammaproteobacteria | Pseudomonadales | Moraxellaceae | Acinetobacter | NA
ASV_159 | Bacteria | Proteobacteria | Gammaproteobacteria | Pseudomonadales | Moraxellaceae | Acinetobacter | NA

This is the count tab:

             | 21Dez609-DL160 | 21Dez609-DL161
ASV_95 | 56 | 0
ASV_109 | 0 | 50
ASV_115 | 0 | 48
ASV_124 | 0 | 44
ASV_159 | 33 | 0

When I align these, I get:

![image](https://user-images.githubusercontent.com/32276720/164397789-3256333a-c1d1-4d96-9206-e259b29bc333.png)

It seems that the differences are in the middle of the DNA string, that makes me think that adapters/primers should not be the issue here :/ 

And when I blast them, they all actually belong to Acinetobacter sp. or some species within Acinetobacter that doesn't differ between ASVs.
Do you have any suggestions?

Thank you very much!

**Comment by alanxelena** [comment]
Hey! It's me again, I think I might have detected the cause of my problem but I don't really know how to fix it. Whenever I look at my count table, there are a lot (Most) of ASVs that are only present in one sample. It seems to me that each ASV in each sample gets its own number but then similar ASVs are not collapsed and summed, it is like my count tab is a preliminary count table with all the ASVs present in every sample and independent on whether they are in the remaining samples.

I think in theory what I should do is to collapse every ASV with the same name into one unique ASV and sum the counts for each sample but I'm not really sure how to perform this, additionally the counts are in one table (count_tab) and the taxonomic assignments corresponding to that count_tab are in another table (tax_tab)

Thank you for your replies!

**Comment by alanxelena** [comment]
Hey, just letting you know that the issue has been solved, thank you for your assistance!

**Comment by benjjneb** [comment]
Great. Any short explanation on what solved it? In case it might be useful for others who come across this thread later with a similar issue.

**Comment by alanxelena** [comment]
Yes, sorry! my bad.
First of all, I have tried running a similar pipeline which uses IdTaxa using raw data from different people and even users online which make their data available for teaching purposes and I have experienced the same issue. Plus, running the same datasets through a Mothur pipeline gives an output with similar characteristics.
For future users that might have the same problem: Graphing the species/genera/ whichever taxa will not make the issue noticeable since the taxa for each sample are assigned correctly, the problem is while calculating different indexes since the number of ASVs will be falsely overestimated. Another important things is that **this is not a solution to the problem but rather a workaround.**

I first merged the counts and taxonomic output tables together:

`>merged_ASV_tax <- cbind(asv_tab, asv_tax[c("domain", "phylum", "class", "order", "family", "genus", "species")])
`
where asv_tab in my case was the table containing the counts for each ASV in each sample and asv_tax was the table containing the taxonomic classification for each ASV.

Then I collapsed all those ASVs that were repeated and added the count for each of them in the corresponding sample column:

`library(data.table)
Merged_ASV_Tax_count <- data.table(merged_ASV_tax)
Final_ASV_count_tab<-Merged_ASV_Tax_count[, lapply(.SD, sum), by=list(domain, phylum, class, order, family, genus, species)]
write.table(Final_ASV_count_tab,"Final_ASV_count.tsv", sep="\t", row.names=TRUE, col.names=NA)`

Please note that not every taxon might be present in the ASV_tax depending on the method used to assign taxonomy (e.g.: species might be missing), no error will be displayed but the final table will still have replicate ASVs. To solve this, just modify accordingly the by=list().
