### ISSUE TITLE
How to find primer sequences in ITS data after sequencing

### ISSUE THREAD

**Issue by Jessica345** [benjjneb/dada2#1536]
Hy! I'm working with ITS sequencing data processing in DADA2. However, I have no information on which set of primers the previous researcher used for sequencing. Is there any program to find primers in the ITS data after sequencing? Not knowing the sequences, I can't use "cutadapt" to remove them.

I really appreciate any help you can provide.

**Comment by benjjneb** [comment]
I'd try to find out what the primers were.

I suppose you can try to reverse-engineer it. BLAST some sequences to figure out if its ITS1 or ITS2 or something, and then look up the common primer sets for that locus and check them against the sequences. But... this information should be knowable.

**Comment by Jessica345** [comment]
Thank you @benjjneb! I'll do some tests to see what I can find.
