### ISSUE TITLE
merge step required for analyzing the R1 reads only?

### ISSUE THREAD

**Issue by Jigyasa3** [benjjneb/dada2#1537]
Hi @benjjneb ,

I am analyzing the R1 reads only for 16S data and I wanted to confirm if the merge step is still required for this?
In the tutorials, the merge step merges the error files and drep files from R1 and R2 `mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE)`  
If the the `dadaFs` variable is already combining `derepFs` and `errF`. Does that mean that I can generate the ASV table directly from `dadaFs`, like so `seqtab <- makeSequenceTable(dadaFs)` ?

**Comment by benjjneb** [comment]
Yep, exactly as you said. Just skip the merger part and make the seqtab as you described.
