### ISSUE TITLE
how long is approximately the time to run dadaFs 

### ISSUE THREAD

**Issue by m-ocejo** [benjjneb/dada2#154]
Hi again!
I was wondering how much time can it take to run the command dadaFs <- dada(derepFs, err=NULL, selfConsist = TRUE) for 80 samples. I suppose that it takes time, but I don´t know what is considered normal, since I am in "selfConsist step 2" for about 40 minutes already. After 30min the first time, I thought that R collapsed so I rerun it.

Thx!

**Comment by m-ocejo** [comment]
Finally it took about 4 hours. Just read another issue with similar question and I added multithread=TRUE. The command for the dadaRs took 1,5h. 
Now I have another question, for 

dadaFs: 
selfConsist step 2 
   selfConsist step 3 
   selfConsist step 4 
   selfConsist step 5 
   selfConsist step 6 
   
while for dadaRs "Convergence after  7  rounds."
Is that fine?

Best!

**Comment by benjjneb** [comment]
Yes that all looks fine.

**Comment by m-ocejo** [comment]
OK! Gracias! 👍
