### ISSUE TITLE
DADA2 filterAndTrim with previously quality trimmed sequences. Is it advisable?

### ISSUE THREAD

**Issue by auroralabastida** [benjjneb/dada2#1540]
Dear developer,

I am processing Illumina 2x250 paired-end reads corresponding to a 16S V3-V4 region sequencing. My usual pipeline implies primer and adapter elimination with Cutadapt followed by quality trimming with Trimmomatic. Here I eliminate any 5' and 3' bases with sequence quality lower than 3, apply a sliding-window filtering (window of size 10 with min. average quality of 15) and filter-out any surviving reads with average quality below 25 and length shorter than 50.

I am planning to use these pre-processed reads as input for DADA2 filterAndTrim, which I would use mainly to implement the Maximum Expected Errors filter and to eliminate any remaining Ns with parameters:

maxN=0, maxEE=c(2,2), truncLen = c(0,0), trimLeft = 0, trimRight=0, truncQ=0

I would then continue with the steps listed in the DADA2 Pipeline Tutorial (1.16) 

Is it advisable to use quality-trimmed reads as input for dada2?
Do you have any advice about the chosen filterAndTrim parameters?

Thanks in advance

**Comment by benjjneb** [comment]
In general you **should not** apply "sliding-window filtering" that cuts off reads at variable positions prior to using DADA2. In general, you **should** enforce a `truncLen` during the `filterAndTrim` step (outside of extremely length-variable loci like ITS).

Pre-processing to remove primers prior to DADA2 is fine, but in most use cases, you are best served in leaving the quality filtering to `filterAndTrim` using the standard `maxEE` and `truncLen` approaches.

**Comment by auroralabastida** [comment]
Thank you very much. I will certainly follow your recommendations. 
About the fw and rv read merging: Is it advisable to pre-merge the reads (ej. with FLASH) and then use them as single-end input for DADA2? I have seem several discussions elsewhere where this is either recommended or strongly discouraged.

**Comment by benjjneb** [comment]
> Is it advisable to pre-merge the reads (ej. with FLASH) and then use them as single-end input for DADA2?

Not recommended.
