### ISSUE TITLE
Reference database problem

### ISSUE THREAD

**Issue by safiqu** [benjjneb/dada2#1541]
Dear dada2 users,

I am trying to use our customised data set. Genus format is working for species fpormat is not working
I tried a lot but i could not solve it. 

Genus data format is: 
Bacteria;Actinobacteriota;Actinobacteria;Propionibacteriales;Propionibacteriaceae;Cutibacterium;Cutibacterium acnes_A1;
GTTGCACACCAGGGGGTCAACTTGGCGTCCTCAGTTCAAAATTGATTCAAACTAACAGTTCCATGTCGGGAAACAGCACCAGGAAGCTCGTGACATATCGTCTTTCATTGCGAGAAACATCTTACTTATGTACATTTCTAAGCTATAGCGTCTACCCTTGTCAGACCCAGGACGATGGGTGTCACATCTCCTTTCTAGTCAACCTAAGAGAGGAGGAAATGCCGCGATATATGTTCCACCCTGTCATCACGAAGGCCACCACAATCTATCCCAGAACAGCCGGCACTTCACTCACGATGCCCCGATGCTGGATTCCTATTGTCGCCCTTATTAGGGCAAGCGGTGCCAGTAGCAGAATATGTCACCTCAACAACTCGATCCACCCCTGCCCATTACATGGGTAACATATCCATGGAGGTTCGATGTATACTCGAGGATACAGTCGTCCATCACGCCCGCCTACATACCCATTACATCAGCATAG
>Bacteria;Actinobacteriota;Actinobacteria;Propionibacteriales;Propionibacteriaceae;Cutibacterium;Cutibacterium acnes_A10;
GTTGCACACCAGGGGGTCAACTTGGCGTCCTCAGTTCAAAATTGATTCAAACTAACAGTTCCATGCCGGGAAACAGCACCAGGAAGCTCGTGACATATCGTCTTTCATTGCGAGAAACATCTTACTTATGTACATTTCTAAGCTATAGCGTCTACCCTTGTCAGACCCAGGACGATGGGTGTCACATCTCCTTTCTAGTCAACCTAAGAGAGGAGGAAATGCCGCGATATATGTTCCACCCTGTCATCACGAAGGCCACCACAATCTATCCCAGAACAGCCGGCACTTCACTCACGATGCCCCGATGCTGGATTCCTATTGTCGCCCTTATTAGGGCAAGCGGTGCCAGTAGCAGAATATGTCACCTCAACAACTCGATCTACCCCTGCCCATTACATGGGTAACATATCCATGGAGGTTCGATGTATACTCGAGGATACAGTCGTCCATCACGCCCGCCTACATACCCATTACATCAGCATAG

Species data Format is: 
>ID001	Cutibacterium	acnes_A1
GTTGCACACCAGGGGGTCAACTTGGCGTCCTCAGTTCAAAATTGATTCAAACTAACAGTTCCATGTCGGGAAACAGCACCAGGAAGCTCGTGACATATCGTCTTTCATTGCGAGAAACATCTTACTTATGTACATTTCTAAGCTATAGCGTCTACCCTTGTCAGACCCAGGACGATGGGTGTCACATCTCCTTTCTAGTCAACCTAAGAGAGGAGGAAATGCCGCGATATATGTTCCACCCTGTCATCACGAAGGCCACCACAATCTATCCCAGAACAGCCGGCACTTCACTCACGATGCCCCGATGCTGGATTCCTATTGTCGCCCTTATTAGGGCAAGCGGTGCCAGTAGCAGAATATGTCACCTCAACAACTCGATCCACCCCTGCCCATTACATGGGTAACATATCCATGGAGGTTCGATGTATACTCGAGGATACAGTCGTCCATCACGCCCGCCTACATACCCATTACATCAGCATAG
>ID002	Cutibacterium	acnes_A10
GTTGCACACCAGGGGGTCAACTTGGCGTCCTCAGTTCAAAATTGATTCAAACTAACAGTTCCATGCCGGGAAACAGCACCAGGAAGCTCGTGACATATCGTCTTTCATTGCGAGAAACATCTTACTTATGTACATTTCTAAGCTATAGCGTCTACCCTTGTCAGACCCAGGACGATGGGTGTCACATCTCCTTTCTAGTCAACCTAAGAGAGGAGGAAATGCCGCGATATATGTTCCACCCTGTCATCACGAAGGCCACCACAATCTATCCCAGAACAGCCGGCACTTCACTCACGATGCCCCGATGCTGGATTCCTATTGTCGCCCTTATTAGGGCAAGCGGTGCCAGTAGCAGAATATGTCACCTCAACAACTCGATCTACCCCTGCCCATTACATGGGTAACATATCCATGGAGGTTCGATGTATACTCGAGGATACAGTCGTCCATCACGCCCGCCTACATACCCATTACATCAGCATAG

I dont understand what I did wrong, suggestion please, 
Thank you in ana advance

**Comment by benjjneb** [comment]
The way you have written the species names, every species is being considered as distinct. The text parser reads `acnes_A1` and `acnes_A10` as two difference species. You didn't state what problem you are having, but my guess is that is the root cause.
