### ISSUE TITLE
Bad quality forward and reverse sequences

### ISSUE THREAD

**Issue by darjniki** [benjjneb/dada2#1543]
Hi all,

I am analyzing data from fecal sequencing of 16S rRNA V1-V2, primers: 27F and 338R (MiSeq 2x300 bp). 

According to quality graphs, the sequencing didn't go well, especially for reverse sequences:

![1](https://user-images.githubusercontent.com/60159020/166456318-b32719bd-74ba-417f-adfb-0c9550a1a7cf.JPG)

According to quality graphs, I decided to cut first and last 50 nt from forward sequences and first and last 100 nt from reverse sequences **(trimLeft=c(50,100), trimRight = c(50,100)).** Since I read that it is critical at this stage to remove as many poor-quality nucleotides as possible (but so that at least 10 percent of the sequences remain after filtering).

Next, I tried **truncQ** = 2 and = 5; since there was not much difference in terms of the left reads, I settled on higher score - 5.

After that, I tried several **maxEE** from 2 to 6 (for the reverse sequence always higher score). As a result, I settled on **maxEE = c (4.5)**.

![2](https://user-images.githubusercontent.com/60159020/166456607-2f27ca85-2e00-416e-bbda-a33c685bf30c.JPG)

Forward:

![3](https://user-images.githubusercontent.com/60159020/166456795-690da030-4b4d-43c8-b1bf-80e81fa40f5e.JPG)

Reverse: 

![4](https://user-images.githubusercontent.com/60159020/166456801-39686bd2-630a-4a2c-841e-effc4bc06ab4.JPG)

After first filtation about 48% were left; after merging about 30% of reads were left.
Final table: 

![5](https://user-images.githubusercontent.com/60159020/166456897-b8eb2377-08e6-44e0-93e5-6b7b4f633d25.JPG)

Do you think it is possible to work further with such data?
Is there anything else I could do with this data? 

I read that in some cases people work only with forward sequences. But in this case, the forward sequences did not go very well ...

Thank you in advance for your help.

**Comment by benjjneb** [comment]
> I read that in some cases people work only with forward sequences. But in this case, the forward sequences did not go very well ...

Given what you've shown, that would still be my recommendation. Stick with the somewhat higher quality forward sequences costs a bit in terms of taxonomic resolution (although probably barely perceptible there), but is a better bet with data like this to keep effective sequencing depth and avoid issues with merging biases driven by the lower-quality reverse reads.
