### ISSUE TITLE
Different sequencing runs present different alpha diversity

### ISSUE THREAD

**Issue by CristianVillenaAlemany** [benjjneb/dada2#1544]
I'm working with a environmental dataset from a 3 year sampling campaign in a freshwater lake.
I sequenced one marker gene from 215 samples and split randomly the sequencing of these samples in 2 illumina runs. 
The number of reads and quality of the sequencing files is similar in both runs. I analysed every run independently and merged before the chimera removal.
When I plot the alpha diversity, one run has a substantial higher diversity than the other run, even after rarefaction. (Image attached)
Any clue how to solve it?
Thank you very much
![image](https://user-images.githubusercontent.com/104840250/166460630-979924c1-4b9a-4d29-97da-e12b1537c0e8.png)

**Comment by benjjneb** [comment]
Well, in downstream analyses of alpha-diversity, you will need to control for the batch effect, for example by including a batch term in any linear regression analyses of alpha-diversity.
