### ISSUE TITLE
Inferring ASV across samples from merged and denoised reads

### ISSUE THREAD

**Issue by dcastaneda5** [benjjneb/dada2#1545]
Hello!

I am working on a genotyping malaria project using DADA2. Briefly, we want to look at unique ASV across a patient with malaria under treatment. We are interested in identifying unique amplicons across a longitudinal analysis. We sequenced a 430 bp gene (Illumina 2x250 PE with no fragmentation on the reads), and we want to identify these ASV as genotypes in each point of the treatment. I am particularly interested in comparing the ASVs across data points to see if they are repeated or if the treatment successfully cleared that genotype. How can I extract the ASV/genotypes from these samples and compare if they are the same or not across different samples?

I understand that the` dadaFs <-(filtFs, err=errF)` and `dadaRs <-(filtFs, err=errR)` provide me with these information, but I am interested in the merged reads after removing the chimeras. Is there a way of getting a table that provides this?

Thanks for your help and time,

Daniel

**Comment by benjjneb** [comment]
>I understand that the dadaFs <-(filtFs, err=errF) and dadaRs <-(filtFs, err=errR) provide me with these information, but I am interested in the merged reads after removing the chimeras. Is there a way of getting a table that provides this?

The dada2 tutorial handles paired-end reads and is probably helpful here: https://benjjneb.github.io/dada2/tutorial.html

**Comment by dcastaneda5** [comment]
Thank you! I don't know how I missed that!
