### ISSUE TITLE
Error in dada2 object 'tax' not found

### ISSUE THREAD

**Issue by luna32-mwsr** [benjjneb/dada2#1546]
I am using dada2. I keep getting:

Error in base::try(tax, silent = TRUE) : object 'tax' not found

after running:
```{r}
out<-filterAndTrim(fwd = fnFs, filt = filtFs, rev = fnRs, filt.rev = filtRs, truncLen = c(250,200), maxN=0, maxEE=c(2,2), truncQ = 2, rm.phix=TRUE, compress=TRUE, multithread=FALSE)

I have received this error before but cannot remember how to correct it and google searches have failed me.

**Comment by benjjneb** [comment]
No idea, and at first glance that doesn't make sense, since there is not `tax` object involved in the command you posted.

Can you clarify the exact command that you are running when this error arises?

**Comment by luna32-mwsr** [comment]
Hello,

I think I need to reinstall or re-instigate the tax object/package/system but I do not know how.

This is the exact command I am running:

out<-filterAndTrim(fwd = fnFs, filt = filtFs, rev = fnRs, filt.rev = filtRs, truncLen = c(250,200), maxN=0, maxEE=c(2,2), truncQ = 2, rm.phix=TRUE, compress=TRUE, multithread=FALSE)

**Comment by luna32-mwsr** [comment]
The entire traceback is:

23. initialize(value, ...)
22. new(...)
21. new2("NativeNSBS", subscript = subscript, upper_bound = upper_bound, 
upper_bound_is_strict = upper_bound_is_strict, has_NAs = has_NAs, 
check = FALSE)
20. NativeNSBS(i, x_NROW, strict.upper.bound, FALSE)
19. NSBS(i, x, exact = exact, strict.upper.bound = !allow.append, 
allow.NAs = allow.NAs)
18. NSBS(i, x, exact = exact, strict.upper.bound = !allow.append, 
allow.NAs = allow.NAs)
17. normalizeSingleBracketSubscript(i, x, as.NSBS = TRUE)
16. .nextMethod(x = x, i = i)
15. callNextMethod()
14. .dropUnusedPoolElts(callNextMethod())
13. extractROWS(x, i)
12. extractROWS(x, i)
11. subset_along_ROWS(x, i, drop = drop)
10. sread(x)[i]
9. sread(x)[i]
8. initialize(x, sread = sread(x)[i], id = id(x)[i], quality = quality(x)[i])
7. initialize(x, sread = sread(x)[i], id = id(x)[i], quality = quality(x)[i])
6. fqF[!is.phi]
5. fqF[!is.phi]
4. (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0, 
0), maxLen = c(Inf, Inf), minLen = c(20, 20), trimLeft = c(0, 
0), trimRight = c(0, 0), minQ = c(0, 0), maxEE = c(Inf, Inf), 
rm.phix = c(TRUE, TRUE), rm.lowcomplex = c(0, 0), matchIDs = FALSE, ...
3. mapply(FUN = FUN, ..., MoreArgs = MoreArgs, SIMPLIFY = SIMPLIFY, 
USE.NAMES = USE.NAMES)
2. mcmapply(fastqPairedFilter, mapply(c, fwd, rev, SIMPLIFY = FALSE), 
mapply(c, filt, filt.rev, SIMPLIFY = FALSE), MoreArgs = list(truncQ = truncQ, 
truncLen = truncLen, trimLeft = trimLeft, trimRight = trimRight, 
maxLen = maxLen, minLen = minLen, maxN = maxN, minQ = minQ, ...
1. filterAndTrim(fwd = fnFs, filt = filtFs, rev = fnRs, filt.rev = filtRs, 
truncLen = c(150, 150), maxN = 0, maxEE = c(2, 2), truncQ = 2, 
rm.phix = TRUE, compress = TRUE, multithread = FALSE)

**Comment by luna32-mwsr** [comment]
Hello,

I have resolved the issue at this time. It appears the computer was timing out the code run and this error appeared after the code was halted.

I am going to try to rig my computer so it does not stop the code until this step is completed. Thank you for your time.

I will let you know if this clears the issue. When run with a small sample size, the code worked.



Sent via the Samsung Galaxy S21 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
