### ISSUE TITLE
50 % of ASV removed after removeBimeraDenovo

### ISSUE THREAD

**Issue by soluna1** [benjjneb/dada2#1547]
Hi:
I'm running the removing chimera function with 30 samples from V4 16s 250 x following the standard dada2 protocol.
I would like just to confirm that removing 50% of chimera and 2,59% of reads it's ok.

Thank you. 

**function**:
seqtab.raw <- removeBimeraDenovo(st.all, method="consensus",multithread=TRUE, verbose = TRUE)

**Output**:
[1] "Starting removeBimeraDenovo"
# 6607 chimera were found and removed
# These represent **50.02% of total ASVs and 2.59% of total reads**

# The variants (ASVs) have the following length distribution:

 210  216  218  222  271  334  349  350  357  358  359  360  362  363  364  365 
   1    1    1    1    1    1    2    1    4    5    1    1    6    4   16   17 
 366  367  368  369  370  371  372  373  374  375  376  377  378  379  380  381 
 130   52  168  251  983  391  809  865 1596  283  237  235  349   46   32   75 
 382  383  384  385  386  387  389  390  392 
  15    9    3    3    1    1    1    2    2

**Comment by benjjneb** [comment]
From [the tutorial](https://benjjneb.github.io/dada2/tutorial.html#remove-chimeras):

> Considerations for your own data: Most of your reads should remain after chimera removal (it is not uncommon for a majority of sequence variants to be removed though).
