### ISSUE TITLE
Error in DADA2 for microbial analysis

### ISSUE THREAD

**Issue by Vetshweta** [benjjneb/dada2#1549]
Hi Ben,
I am working on analyzing demultiplexed data from shoreline Biome kit (Pacbio). I am kind of new in this so reaching out to you if you can help me. I am having error in creating dd2. I am following DADA2 + PacBio: Fecal Samples and A DADA2 workflow for Big Data tutorial. Can you please help me with this? Also, I am not sure if the file used in drp2 is correct.

my code:
path <-"C:/Users/........./demux/" # CHANGE ME to the directory containing your demultiplexed fastq files
filtpath <- file.path(path, "filtered") # Filtered files go into the filtered/ subdirectory
fns <- list.files(path, pattern="fastq") # CHANGE if different file extensions
# Filtering
a<-filterAndTrim(file.path(path,fns), file.path(filtpath,fns), 
              truncLen=240, maxEE=1, truncQ=11, rm.phix=TRUE,
              compress=TRUE, verbose=TRUE, multithread=TRUE)

# File parsing
filtpath <- "C:/Users/............../demux/filtered" # CHANGE ME to the directory containing your filtered fastq files
filts <- list.files(filtpath, pattern="fastq", full.names=TRUE) # CHANGE if different file extensions
sample.names <- sapply(strsplit(basename(filts), "_"), `[`, 1) # Assumes filename = sample_XXX.fastq.gz
names(filts) <- sample.names

drp2 <- derepFastq(filts, verbose=TRUE)

err2 <- learnErrors(drp2, errorEstimationFunction=PacBioErrfun, BAND_SIZE=32, multithread=TRUE)

dd2 <- dada(drp2, err=err2, BAND_SIZE=32, multithread=TRUE,  USE_QUALS=TRUE)

Error in dada(drp2, err = err2, BAND_SIZE = 32, multithread = TRUE, USE_QUALS = TRUE) : 
  Invalid derep$quals matrix. Quality values must be positive integers.

![error_dada](https://user-images.githubusercontent.com/66678674/167484559-bc60f7a1-3173-498d-a9cf-b6bd007b0dfc.PNG)

**Comment by benjjneb** [comment]
The issue is probably that the quality score encoding is being incorrectly auto-detected in some of your small read count samples. See https://github.com/benjjneb/dada2/issues/968 and https://github.com/benjjneb/dada2/issues/838

> THere is an easy workaround though thanks to a contribution from @brendanf
>
> If you pass the argument qualityType="FastqQuality" to derepFastq it will specify the quality encoding as score + 33 and qualityType="SFastqQuality" will specify the encoding as score + 64.

**Comment by Vetshweta** [comment]
I got it working. Thank you. 
One quick question, you are using silva for taxonomic assignment. Do you have link for athena taxonomic file that can be used in r?

**Comment by benjjneb** [comment]
The reference fastas available for `assignTaxonomy` can be seen at this page: https://benjjneb.github.io/dada2/training.html

I'm not familiar with the athena taxonomic database, so to use it w/ `assignTaxonomy you would need to format it appropriately. See the formatting custom databases section on that page for more information.
