### ISSUE TITLE
computer efficiency

### ISSUE THREAD

**Issue by giriarteS** [benjjneb/dada2#155]
There is a way to run dada2 more efficiently? I am running dada2 on a set of 12 samples (Illumina Hi-seq 2x250, 16S V4) using a mac pro (24 core, 64 GB of memory) but the inference step is using 100% of CPU and 30% of memory. Here is the command I am running since monday morning:
ddF <- dada(derepFs[1:20], err=NULL, selfConsist=TRUE)
Initial error matrix unspecified. Error rates will be initialized to the maximum possible estimate from this data.
Initializing error rates to maximum possible estimate.
Sample 1 - 947515 reads in 233627 unique sequences.
Sample 2 - 1316661 reads in 500083 unique sequences.
Sample 3 - 845517 reads in 345400 unique sequences.
Sample 4 - 733867 reads in 327366 unique sequences.
Sample 5 - 698431 reads in 298808 unique sequences.
Sample 6 - 830012 reads in 356947 unique sequences.
Sample 7 - 914136 reads in 354255 unique sequences.
Sample 8 - 720018 reads in 292512 unique sequences.
Sample 9 - 874846 reads in 346995 unique sequences.
Sample 10 - 948966 reads in 391792 unique sequences.
Sample 11 - 754109 reads in 313972 unique sequences.
Sample 12 - 732984 reads in 67829 unique sequences.
Sample 13 - 1162966 reads in 85734 unique sequences.
Sample 14 - 894705 reads in 49678 unique sequences.
Sample 15 - 938346 reads in 59068 unique sequences.
Sample 16 - 646597 reads in 34678 unique sequences.
Sample 17 - 686017 reads in 63860 unique sequences.
Sample 18 - 1116534 reads in 50885 unique sequences.
Sample 19 - 802629 reads in 49645 unique sequences.
Sample 20 - 678223 reads in 44278 unique sequences.
  selfConsist step 2 
  selfConsist step 3 
  selfConsist step 4 
  selfConsist step 5 
  selfConsist step 6 
  selfConsist step 7 

I still have to run the ddR and then run it again with the inferred error. So, to get my final table it will take a month?

**Comment by gblanchard4** [comment]
You should try subsampling your reads to create your error model. Check out the [Big Data Workflow for Paired End Reads](http://benjjneb.github.io/dada2/bigdata_paired.html) for a great explanation on how. 

You don't list the `multithread` option in your `dada()` command, but since it's using 100% of your cpu I presume you are using that too.

**Comment by benjjneb** [comment]
As @gblanchard4 mentioned, you are going to want to look at the big data workflow (see the [single read Big Data Workflow](http://benjjneb.github.io/dada2/bigdata.html) for more detailed discussion of the strategy).

The key things you are doing are turning on multithreading, reducing the number of samples you are using to infer the error rates, and potentially more stringent filtering to lower the number of input unique sequences.

**Comment by giriarteS** [comment]
I followed the pair read workflow and after 20 hours I got this:
dd.learnF <- dada(drp.learnF, err=NULL, selfConsist=TRUE, multithread=TRUE)
Initial error matrix unspecified. Error rates will be initialized to the maximum possible estimate from this data.
Initializing error rates to maximum possible estimate.
Sample 1 - 898208 reads in 346368 unique sequences.
Sample 2 - 815042 reads in 349267 unique sequences.
Sample 3 - 721719 reads in 65283 unique sequences.
Sample 4 - 1294066 reads in 489570 unique sequences.
Sample 5 - 859739 reads in 339622 unique sequences.
Sample 6 - 1095594 reads in 47550 unique sequences.
Sample 7 - 1145262 reads in 81964 unique sequences.
Sample 8 - 961627 reads in 55046 unique sequences.
Sample 9 - 708307 reads in 286653 unique sequences.
Sample 10 - 830625 reads in 338156 unique sequences.
Sample 11 - 881129 reads in 47106 unique sequences.
Sample 12 - 931140 reads in 382969 unique sequences.
Sample 13 - 636965 reads in 32765 unique sequences.
Sample 14 - 721270 reads in 320632 unique sequences.
Sample 15 - 1272541 reads in 64788 unique sequences.
   selfConsist step 2 
   selfConsist step 3 
   selfConsist step 4 
   selfConsist step 5 
   selfConsist step 6 
   selfConsist step 7 
   selfConsist step 8 
   selfConsist step 9 
   selfConsist step 10 

Warning message:
In dada(drp.learnF, err = NULL, selfConsist = TRUE, multithread = TRUE) :
  Self-consistency loop terminated before convergence.

**Comment by benjjneb** [comment]
You can probably ignore this warning, and simply use the error rate estimates after 10 rounds of self-consistency looping. 

"To check if the rates are close to convergence, use the function `dada2:::checkConvergence(dadaRs[[1]])`. That will give you a vector of the sum of absolute differences between the error rate parameters in each step. That should have gotten much, much smaller from where it started, and if it did, then it the error rates at the end are a good estimate, even though they haven't yet technically converged. Feel free to post the results here as well if you are unsure."

There is more discussion of this in #77 if you are interested.

**Comment by giriarteS** [comment]
This is what I got, here you can see the commands used and the results:
> dada2:::checkConvergence(dd.learnF[[1]])
 [1] 55.958406789  2.944086378  0.034224615  0.003323703  0.005027891  0.003078527  0.002812893  0.004130487  0.003089021  0.004258349
dada2:::checkConvergence(dd.learnR[[1]])
 [1] 58.750564477  1.119649678  0.018383670  0.003840726  0.001437791  0.002470987  0.001676019  0.001908797  0.001502633  0.001621563
plotErrors(dd.learnF[[1]], nominalQ=TRUE)
[Errors.F.pdf](https://github.com/benjjneb/dada2/files/595284/Errors.F.pdf)
[Errors.R.pdf](https://github.com/benjjneb/dada2/files/595286/Errors.R.pdf)

**Comment by benjjneb** [comment]
I would just go ahead and use those learned error rates.

For the future, those error rate plots suggest relatively poor accuracy for Illumina sequencing -- something to consider when picking a sequencing provider for later projects.

**Comment by giriarteS** [comment]
Thank you!!

**Comment by giriarteS** [comment]
I am analizing an ITS dataset(several locations - 108 samples) and the self-consistency loop terminated before convergence. I tried:
dadaFs <- dada(derepFs, err=errF, selfConsist = TRUE, pool = TRUE, multithread=TRUE, BAND_SIZE=32, MAX_CONSIST=30)
> dada2:::checkConvergence(dadaFs2[[1]])
 [1] 6.9468456755 0.2574713344 0.0211787792 0.0015825995 0.0012978634 0.0011893173 0.0014106707 0.0034805102 0.0013209918 0.0016058412 0.0010666868 0.0015879755
[13] 0.0008638495 0.0005940889 0.0016313829 0.0006979553 0.0015720604 0.0011951319 0.0012107537 0.0010109498 0.0016659809 0.0012910476 0.0013622625 0.0014482462
[25] 0.0014380736 0.0017496242 0.0015063826 0.0016407720 0.0009882741 0.0017532063
![image](https://cloud.githubusercontent.com/assets/15178644/24209791/d84c81fc-0eec-11e7-8129-846bd8eea76d.png)

dada2:::checkConvergence(dadaRs2[[1]])
[1] 5.9125574116 0.2940650389 0.0044018386 0.0008412936 0.0011474025 0.0011952873 0.0005599031 0.0006299523 0.0009909111 0.0012142437 0.0004618683 0.0014023838
[13] 0.0005015984 0.0012125691 0.0007788931 0.0013900628 0.0005191586 0.0011871890 0.0003114471 0.0012026863 0.0004787637 0.0004062359 0.0013007854 0.0005314126
[25] 0.0005422079 0.0004218850 0.0011838594 0.0013884449 0.0008082560 0.0013551501
![image](https://cloud.githubusercontent.com/assets/15178644/24209985/466189e4-0eed-11e7-98da-72292fff3c62.png)

dadaFs2 <- dada(derepFs, err=errF, selfConsist = TRUE, pool = TRUE, multithread=TRUE, BAND_SIZE=32, MAX_CONSIST=50)
 [1] 6.9470589763 0.2574973941 0.0218715981 0.0009444096 0.0011476212 0.0011841116 0.0013991999 0.0042315697 0.0010280749 0.0011117989 0.0004603374 0.0010537059
[13] 0.0010927181 0.0008672225 0.0012302081 0.0014221955 0.0010379283 0.0002351916 0.0011153523 0.0006967183 0.0011736337 0.0014013011 0.0008055993 0.0009843855
[25] 0.0010490838 0.0012577211 0.0010246366 0.0012442237 0.0010713174 0.0012757051 0.0012614838 0.0011424983 0.0011989401 0.0010496771 0.0009781210 0.0014706554
[37] 0.0009183767 0.0046706320 0.0047163798 0.0012922453 0.0010607650 0.0011910723 0.0010276545 0.0008023605 0.0010741693 0.0012096640 0.0009144929 0.0011848432
[49] 0.0011618862 0.0011276540
![image](https://cloud.githubusercontent.com/assets/15178644/24209947/2d20ded0-0eed-11e7-9afb-b31852772f69.png)

Should I increase the MAX_CONSIST or should I go ahead with MAX_CONSIST=50?
This dataset has soil, root and rhizosphere samples from 4 locations (2 in USA and 2 out of USA) and I just finished the analysis of my training set with MAX_CONSIST=25 without any problem (soil, root, rhizosphere and leaves from 2 locations(1 in USA and 1 out of USA) ).

**Comment by benjjneb** [comment]
Those plots look good, you can just go ahead and use the error model as is.

**Comment by fjlicht** [comment]
Hello,
I have 16S soil data and have this issue when running the command below on the server. Do you have any advice, can 'MAXCONSIST=' be added to this function? This ran for 2-3 days before this result. Thank you.
> errF <- learnErrors(filtFs, multithread=TRUE)
Initializing error rates to maximum possible estimate.
Sample 1 - 858214 reads in 386301 unique sequences.
Sample 2 - 892971 reads in 457037 unique sequences.
   selfConsist step 2
   selfConsist step 3
   selfConsist step 4
   selfConsist step 5
   selfConsist step 6
   selfConsist step 7
   selfConsist step 8
   selfConsist step 9
   selfConsist step 10

Total reads used:  1751185
Warning message:
In dada(drps, err = NULL, selfConsist = TRUE, multithread = multithread) :
  Self-consistency loop terminated before convergence.

**Comment by benjjneb** [comment]
@fjlicht

You are probably fine to use the error rates after 10 rounds, even though they haven't technically converged they are likely very close. 

As described in the thread above, I would use the `plotErrors` command to look at the error rates and visually see if they are fitting well. If they are, just go ahead and use them. If they aren't we can try something else (perhaps higher MAX_CONSIST).
