### ISSUE TITLE
Implementing maxMismatch as a proportion of overlap region rather than fixed value?

### ISSUE THREAD

**Issue by sgavril** [benjjneb/dada2#1552]
Hello,

A challenge I have had with DADA2 is working with a marker gene of variable length (like the ITS gene for fungi, or recently we have been working with the ITS2 gene for gastrointestinal nematodes). During the mergePairs step, our concern was that setting a constant value for maxMismatch might bias against paired reads with longer overlaps. So we wanted to see if we could merge pairs with the maxMismatch parameter as a proportion of total overlap length instead. 

I have a crude implementation below, but I am not 100% sure this is correct. We are working with ITS2 sequences from an Illumina MiSeq using a v2 500 cycle kit. Essentially I merge pairs with maxMismatch set to infinity (I prefer this over the behavior of setting returnRejects = T). Then I allocate a list of the same length as the merged pairs with all rejects. Then for each sample, I compute the overlap region length as the number of matches + the number of mismatches, then I just filter for sequences that have a percent mismatch less than some percentage value (1.5% roughly corresponds to 3 bp). 

```
mergers_w_rejects <- mergePairs(dadaFsPooled, filtFs, dadaRsPooled, filtRs, 
                                verbose=TRUE, maxMismatch = Inf)

#Create empty vector to contain merged reads by sample
mergers <- vector("list", length(mergers_w_rejects)) 
names(mergers) <- sample.names #  Name samples

for (i in c(1:length(mergers_w_rejects))) {
  mergers_w_rejects[[i]]$length <- mergers_w_rejects[[i]]$nmatch + mergers_w_rejects[[i]]$nmismatch
    
  
  mergers_w_rejects[[i]]$percent_mismatch <- 
    (mergers_w_rejects[[i]]$nmismatch)/mergers_w_rejects[[i]]$length*100
  
  mergers_w_rejects[[i]] <- mergers_w_rejects[[i]] %>% dplyr::filter(percent_mismatch < 1.5)
  
  mergers[[i]] <- mergers_w_rejects[[i]]
  
}
```
I am not sure if the length of the overlap region is equal to the # of mismatches + the # of matches. The rest of the pipeline appears to run and this seems to remove sequences as intended. For the sake of comparison, below I compute the overlap lengths from 1 sample after merging pairs with maxMismatch set to the default 0 and then set to 3 (approximately 1.5% of the read length).

```
mergers_no_mismatch <- mergePairs(dadaFsPooled, filtFs, dadaRsPooled, filtRs, 
                                  verbose=TRUE, maxMismatch = 0)
mergers_no_mismatch[[1]]$overlap_length <- mergers_no_mismatch[[1]]$nmatch + 
  mergers_no_mismatch[[1]]$nmismatch


mergers_mismatch3 <- mergePairs(dadaFsPooled, filtFs, dadaRsPooled, filtRs, 
                                verbose=TRUE, maxMismatch = 3)
mergers_mismatch3[[1]]$overlap_length <- mergers_mismatch3[[1]]$nmatch +
  mergers_mismatch3[[1]]$nmismatch
```

When I look at the distribution of overlap lengths among unique ASVs with maxMismatch = 0, a lot of sequences are lost while relaxing maxMismatch = 3 retains a lot more sequences (approximately double for this sample). But with maxMismatch set to 1.5% of the overlap lengths, we retain 1 fewer ASV of length 188 and 2 more ASVs of length 275. This is quite a small difference, but across many samples my hope is that this will help retain more biologically relevant ASVs overall. 

```
> mergers_no_mismatch[[1]] %>% pull(overlap_length) %>% table()
.
186 188 189 265 266 267 268 271 277 278 
  1   2   1   1   1   6   1   1   2   1 
> mergers_mismatch3[[1]] %>% pull(overlap_length) %>% table()
.
186 188 189 190 265 266 267 268 271 277 278 
  2   3   2   2   2   1  10   1   2   4   3 
> mergers[[1]] %>% pull(overlap_length) %>% table()
.
186 188 189 190 265 266 267 268 271 275 277 278 
  2   2   2   2   2   1  10   1   2   2   4   3 
```

Does this appear to be a viable approach for setting the maxMismatch parameter? Or could this lead to some unintended consequences downstream? 

Below are the .rds objects in .gz format used as input for mergePairs. I am using the following packages:
[dadaFsPooled.gz](https://github.com/benjjneb/dada2/files/8664982/dadaFsPooled.gz)
   ###[dadaRsPooled.gz](https://github.com/benjjneb/dada2/files/8664983/dadaRsPooled.gz)
[filtFs.gz](https://github.com/benjjneb/dada2/files/8664984/filtFs.gz)
[filtRs.gz](https://github.com/benjjneb/dada2/files/8664985/filtRs.gz)

```
> version ; packageVersion("dada2")
               _                           
platform       x86_64-conda-linux-gnu      
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          1.3                         
year           2022                        
month          03                          
day            10                          
svn rev        81868                       
language       R                           
version.string R version 4.1.3 (2022-03-10)
nickname       One Push-Up                 
[1] ‘1.22.0’
```

**Comment by benjjneb** [comment]
First, it might be useful to take a look at #565 for a look at what some other people have been looking at with regards to variable length merging, and some text on why we aren't trying to add hybrid merging into the package.

That said, we are happy for folks to develop their own solutions here, especially if they are willing to share them as this is a question that has come up repeatedly in the past.

In your specific approach, there is one important thing to note -- the default alignment being performed between the forward and reverse reads heavily penalizes mismatches, and thus very short but spurious alignments are often preferred over longer mostly-matching alignments. This is the right alignment behavior assuming a strict `maxMismatch=0` standard is being enforced (as by default). But, it isn't the right behavior is something more lenient like a %match threshold is being enforced.

Alignment parameters (i.e. match/mismatch/gap scores) can be modified when calling `mergePairs` though. See`?mergePairs` on the `...` argument, and the `?nwalign` function.

**Comment by sgavril** [comment]
Thanks for your quick reply @benjjneb , the note about the different behavior for `maxMismatch = 0` was really informative. We have been trying to narrow down a value for this maxMismatch parameter, with our idea being that read pairs with a longer overlap region are expected to have more mismatches by chance. However, when I plot the number of mismatches as a function of the overlap region length using our data, there appears to be no relationship, which leads us to believe that just a value such as 0 or 1 maxMismatch would suffice.

![image](https://user-images.githubusercontent.com/40210747/170708133-c6145574-6b09-4022-ac91-9966f9a7affd.png)

However, the above data was obtained from using the following command: 
```
mergers_w_rejects <- mergePairs(dadaFsPooled, filtFs, dadaRsPooled, filtRs, 
                                verbose=TRUE, maxMismatch = Inf)
```
After reading your reply we were interested in what this same plot would look like if we used `maxMismatch = 0`, so I created an object using 
```
misMatch0.keep.rejects <- mergePairs(dadaFsPooled, filtFs, dadaRsPooled, filtRs,
                                verbose=TRUE, maxMismatch = 0, returnRejects = T)
```
and then tried to re-create the plot from above:

![image](https://user-images.githubusercontent.com/40210747/170709131-4f3c2c5e-b235-4cbf-883b-a2a294f81435.png)

(this is using `+ geom_jitter()` so all of the mismatches are spaced around 0, 1 or 2). Though you noted that the behavior using `maxMismatch = 0` would be different I was quite confused by the results. Is there a reason for each plot going up to either 15 or 2 mismatches? I would have thought that enabling `returnRejects` should keep all sequences with more mismatches as above, and now it appears that there is a relationship between the length of the overlap region at maxMismatch = 1 or 2 in the latter plot (though these would be filtered out anyways).

Just hoping to hear some thoughts on this situation. Should we expect that read pairs with longer overlaps have more mismatches? Or since the reads have been denoised, all reads are expected to have a constant number of mismatches regardless of overlap length?

**Comment by benjjneb** [comment]
> Is there a reason for each plot going up to either 15 or 2 mismatches? 

Yes, see this block of code from the `mergePairs` function:

```
            if(maxMismatch==0) {
                setDadaOpt(MATCH=1L, MISMATCH=-64L, GAP_PENALTY=-64L)
            } else {
                setDadaOpt(MATCH=1L, MISMATCH=-8L, GAP_PENALTY=-8L)
            }
 ```

What is happening is that if `maxMismatch==0`, then alignment is performed with very high penalties for mismatches and gaps. This results in short overlaps with 1 or 2 mismatches being  strongly preferred over longer overlaps with more mismatches. That is the "right" behavior when `maxMismatch==0` is being enforced, but not the right behavior for more lenient thresholds. Hence the different alignment behaviors depending on that parameter, and the different numbers of mismatches you are seeing between the two choices.

**Comment by markschl** [comment]
This issue is closed and some time has passed, but I'm wondering what people think is a good threshold for a mismatch rate (mismatches normalized by overlap length).

We have fungal ITS2 datasets and I feel (similarly to other people) that using only forward reads would mean throwing away too much information (since anyway reads should merge for *almost all* species in our case).

Clearly, rare ASVs have more mismatches in the overlap zone, so they appear likely to be more errorneous. The below images show a Illumina NextSeq 2x300 dataset but AVITI data looks similar. Maybe we didn't do enough stringent quality filtering/truncation beforehand?

![grafik](https://github.com/user-attachments/assets/8f4efe9d-b465-4975-bbe8-36132094d861)

![grafik](https://github.com/user-attachments/assets/996fca10-263c-4cb4-a4fa-7b144a1411c5)

Very stringent filtering by a mismatch rate in the overlap zone can remove many ASVs, but not necessarily many reads. Still, meaningful ASVs could in theory be lost and it seems a tradeoff between loosing potentially interesting rare ASVs vs. accepting errorneous sequences plus some risk of false alignments (which should hopefully be low if e.g. enforcing a large enough overlap).

**Comment by benjjneb** [comment]
@markschl Not something we've looked ourselves at but an interesting observation.
