### ISSUE TITLE
Filter suspicious taxa

### ISSUE THREAD

**Issue by termithorbor** [benjjneb/dada2#1554]
Hi,

should any filtering for suspecious species in 16S data be done beyond the chimera filtering and filtering for singletons in phyloseq objects?

For example filter out species which are less abundant than let's say 0,25 % or something like suggested in this paper? 
https://www.nature.com/articles/s43705-021-00033-z

Thanks in advance.

**Comment by benjjneb** [comment]
Depends on your study goals. I would recommend just not calculating richness at all, for the reasons discussed in that paper. If you want to look at alpha-diversity, the Shannon and Simpson indices are much less affected by rare taxa enriched with artefacts.

**Comment by benjjneb** [comment]
Chimera removal and singletons cannot eliminate many of the types of artefacts they talk about in the paper, like cross-contamination between samples. That said, enforcing a minimum abundance threshold necessarily also throws away all real taxa that are below that threshold. So, whether to do so depends on your study goals and the specific analyses you are pursuing.
