### ISSUE TITLE
selfConsist running when selfConsist = FALSE in dada() step

### ISSUE THREAD

**Issue by Rosiekstein** [benjjneb/dada2#1555]
Hello,

I am having an issue running the dada() step on a large dataset as it keeps running selfConsist even though I have specified the errors and specified selfConsist = FALSE. I am running dada2 v. 1.18 on R v. 4.02 on a supercomputing cluster. 

My relevant code is as follows:

errF <- learnErrors(filtFs, multithread=TRUE)

errR <- learnErrors(filtRs, multithread=TRUE)

derepFs <- derepFastq(filtFs, verbose=TRUE)
derepRs <- derepFastq(filtRs, verbose=TRUE)

 Name the derep-class objects by the sample names

names(derepFs) <- sample.names
names(derepRs) <- sample.names

dadaFs <- dada(derepFs, err=errF, multithread=TRUE, pool = "pseudo", selfConsist = FALSE)
dadaRs <- dada(derepRs, err=errR, multithread=TRUE, pool = "pseudo", selfConsist = FALSE)

I am running the code on a supercomputer and the error rates still take several hours to learn, so having it run twice adds a lot of time. Any suggestions would be greatly appreciated.

Rosie

**Comment by benjjneb** [comment]
I think you might be misinterpreting the output from `pool="pseudo"`. In that mode, every sample needs to be run twice, the first time to generate the list of ASVs observed by individual processing, and the second time with that information passed in as priors. So, the samples are all run through twice. This isn't related to learning the error rates with `selfConsist=TRUE`.

**Comment by Rosiekstein** [comment]
Thank you. I left it to run overnight and seems to have finished correctly.
