### ISSUE TITLE
Sequences with binominal species aren't in silva_species_assignment_v138.1.fa.gz

### ISSUE THREAD

**Issue by salix-d** [benjjneb/dada2#1557]
I was looking at the function making the silva_species_assignment_v138.1.fa.gz file from SILVA_138_SSURef_tax_silva.fasta.gz. 
I noticed that since only sequences with 7 taxonomy fields are chosen, some sequences who do have binomial species name are excluded because of missing family in the SILVA taxonomy.

For example :
`MG264252.1.1380 Bacteria;Fibrobacterota;Fibrobacteria;Fibrobacterales;Chitinispirillum;Chitinispirillum alkaliphilum`
(missing the _Chitinispirillaceae_ family)
and 
`AGBB01000258.24.1341 Bacteria;Firmicutes;Clostridia;Peptostreptococcales-Tissierellales;Peptoniphilus;Peptoniphilus indolicus ATCC 29427`
(missing the _Peptoniphilaceae_ family)

The weird thing is that if you look at the ncbi pages for those accessions (MG264252; AGBB01000258), the taxonomy is complete
https://www.ncbi.nlm.nih.gov/nuccore/MG264252 and https://www.ncbi.nlm.nih.gov/nuccore/AGBB01000258

I don't know if it's a thing to fix on SILVA's side or if the filtering of species could be done differently when making the file?

**Comment by salix-d** [comment]
There's also 
```
"JOMG01000002.8815.10326 Bacteria;Desulfobacterota;Desulfuromonadia;Geopsychrobacteraceae;Pelobacter;Pelobacter seleniigenes DSM 18267"
"JOMG01000002.3301.4811 Bacteria;Desulfobacterota;Desulfuromonadia;Geopsychrobacteraceae;Pelobacter;Pelobacter seleniigenes DSM 18267"
```
This one is missing the order _Desulfuromonadales_, but the taxonomy seems to also be mixed up between NCBI and GTDB : https://gtdb.ecogenomic.org/searches?s=al&q=seleniigenes

I haven't looked at all the sequences; there's about a 1k bacterial sequences whose taxonomy has only 6 fields but still have binominal species.
I removed '[Uu]ncultured', '[Uu]nidentified', 'Cadidatus ', '[' and ']' following the function. 
Only kept the names ending with a binominal name.
Then checked if the genus was the same as the first part of the species binominal. (didn't used gen.match, so there might be more)

**Comment by benjjneb** [comment]
Closed as wont-fix on our end.

That said the Silva 138.2 update was a nice one in several ways, including now being much more consistent in their 6-level official taxonomy, so some of these cases may have been resolved.
