### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by Otshepeng0157** [benjjneb/dada2#1558]
I am trying to run out <- filterAndTrim(dataF, filt.dataF, dataR, filt.dataR, truncLen=c(290,275),
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=TRUE) 
But i keep getting a Error in filterAndTrim(dataF, filt.dataF, truncLen = c(290, 275), maxN = 0,  : 
  All output files must be distinct. 
I read a few comments and check for duplicates any(duplicated(c(filt.dataR)))
[1] TRUE
> any(duplicated(c(filt.dataF)))
[1] TRUE

I am new to R so I am confused and am not sure what to do. Kindly help

**Comment by salix-d** [comment]
How did you make 'filt.dataF' ? 
Do you have multiple files for the same sample name?
In any cases, you need to make sure there's no duplicates (the function stops because otherwise it would overwrite some files).

**Comment by Otshepeng0157** [comment]
filt.dataF <- file.path("Assignment Folder", "filtered", paste0(list.sample.names, "_F_filt.fastq.gz"))
filt.dataR <- file.path("Assignment Folder", "filtered", paste0(list.sample.names, "_R_filt.fastq.gz"))

I dont have files with same sample name

**Comment by benjjneb** [comment]
What is `any(duplicated(list.samples.names))`? That apparently has duplicate names in it. You can identify the duplicates with:

```
is.dup <- duplicated(list.sample.names)
list.samples.names[is.dup]
```
