### ISSUE TITLE
tutorial on the parallelisation approach for filtering and derep step?

### ISSUE THREAD

**Issue by mghanbari** [benjjneb/dada2#156]
Hi
I am writing in connection with Dada2 parallelisation issue. While the recent version of dada2 supports multithreading in some steps, I read in the repo that it is also possible to parallelise the sequence filter step and derep (from joey711). I think it would be very informative and useful to include a tutorial on this parallelisation approach as I found these steps really time-consuming while I analyzed my dataset (90 samples, MiSeq). Also, I'd appreciate if you could comment on how I can have a log file from the different step in dada2. 

Thanks in advance for the support.
Regards
Mahdi

**Comment by benjjneb** [comment]
A new tutorial on filtering is in the planning stages. We will make sure to add information on how to parallelize the filtering process, and I'll try to remember to post here when the tutorial goes live.

Could you clarify a bit more what you mean by a "log file". What information do you want exactly? We are looking at tracking reads through the pipeline in #151 so any input on what information would be most useful is very timely.

**Comment by mghanbari** [comment]
That would be really good to have a tutorial on filtering..thank you.

Regarding the log file, the information that could be useful for filtering step (before and after) are the length distribution of reads (number/percentage) and Q scores or expected error information per read per sample. The same log files are also useful after merging step to see how good are the reads after quality filtering. I am not expert in programming, but I think that log files should be produced by default in each step rather than as an option (if that is possible).

Thank you for the great tool DADA2!

**Comment by benjjneb** [comment]
Parallelized filtering via the new unified (single- and paired-end) filtering method `filterAndTrim` as of b2006fe011336e39c36da7b840dda2a28e4da3c5

This will be the new supported filtering interface starting with the next release. Example usage:
```
fns <- list.files("path/to/fastqs", pattern="fastq.gz", full.names = TRUE)
filts <- file.path(dirname(fns), "filtered", basename(fns))
foo <- filterAndTrim(fns, filts, maxEE=2, truncLen=245, rm.phix=TRUE, multithread=TRUE)
```

*Parallelization implemented via `mcmapply` (forking).*
