### ISSUE TITLE
primer count tables

### ISSUE THREAD

**Issue by zhber7** [benjjneb/dada2#1560]
I was using the DADA2 ITS pipeline workflow (1.8) and encountered an issue- the primer counting tables before and after cutadapt weren't similar to the example ones in the workflow page. I attached the tables before ("primer_table_bef") and after ("primer_table_aft"), with the original workflow ("primer_table_*_orig.RData") and again when using the REV <- REV.orient[["RevComp"]] suggestion ("primer_table_*_revcomp.RData"). Has someone seen this before, and would they possibly know what the problem is?
Thanks!
![dada2_1 8_run_180522](https://user-images.githubusercontent.com/76435594/169145049-bf9155fa-641e-4a90-ba4d-75194924f723.png)

**Comment by zhber7** [comment]
does this mean that there was probably a problem in the demultiplexing stage?

**Comment by benjjneb** [comment]
No, there are some amplicon library preparation protocols that create mixed orientation reads, and they demultiplex fine. I would start by going back to whoever did the sequencing, and nailing down that the amplicon library prep was expected to yield mixed orienatation reads though.

**Comment by zhber7** [comment]
ok thanks will do!
