### ISSUE TITLE
Mismatched forward and reverse sequence files...

### ISSUE THREAD

**Issue by chuynh96** [benjjneb/dada2#1561]
Hello,

I'm going through DADA2 on a publicly available dataset, and am running into this error. I have sorted both my filtered and unfiltered files and am still getting this error. I have also tried setting matchIDs = TRUE and matchIDs = FALSE and that did not work. Any suggestions?

> out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
+                      maxN=0, maxEE=2, truncQ=2, rm.phix=TRUE,
+                      compress=TRUE, multithread=TRUE)

Error in filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen = c(240, 160),  : 
  These are the errors (up to 5) encountered in individual cores...
Error in (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0,  : 
  Mismatched forward and reverse sequence files: 28342, 100000.
Error in (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0,  : 
  Mismatched forward and reverse sequence files: 28342, 100000.
Error in (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0,  : 
  Mismatched forward and reverse sequence files: 28342, 100000.
Error in (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0,  : 
  Mismatched forward and reverse sequence files: 28342, 100000.
Error in (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0,  : 
  Mismatched forward and reverse sequence files: 28342, 100000.
In addition: Warning message:
In mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule,  :
  scheduled core 4 encountered error in user code, all values of the job will be affected

**Comment by benjjneb** [comment]
What is the output of `head(cbind(fnFs, fnRs))`?

**Comment by chuynh96** [comment]
>head(cbind(fnFs, fnRs))
     fnFs                                                                  
[1,] "/Users/mai/Desktop/Bioinformatics Stuff/Lung2/SRR12264494_1.fastq.gz"
[2,] "/Users/mai/Desktop/Bioinformatics Stuff/Lung2/SRR12264495_1.fastq.gz"
[3,] "/Users/mai/Desktop/Bioinformatics Stuff/Lung2/SRR12264496_1.fastq.gz"
[4,] "/Users/mai/Desktop/Bioinformatics Stuff/Lung2/SRR12264497_1.fastq.gz"
[5,] "/Users/mai/Desktop/Bioinformatics Stuff/Lung2/SRR12264498_1.fastq.gz"
[6,] "/Users/mai/Desktop/Bioinformatics Stuff/Lung2/SRR12264499_1.fastq.gz"
     fnRs                                                                  
[1,] "/Users/mai/Desktop/Bioinformatics Stuff/Lung2/SRR12264494_2.fastq.gz"
[2,] "/Users/mai/Desktop/Bioinformatics Stuff/Lung2/SRR12264495_2.fastq.gz"
[3,] "/Users/mai/Desktop/Bioinformatics Stuff/Lung2/SRR12264496_2.fastq.gz"
[4,] "/Users/mai/Desktop/Bioinformatics Stuff/Lung2/SRR12264497_2.fastq.gz"
[5,] "/Users/mai/Desktop/Bioinformatics Stuff/Lung2/SRR12264498_2.fastq.gz"
[6,] "/Users/mai/Desktop/Bioinformatics Stuff/Lung2/SRR12264499_2.fastq.gz"

**Comment by chuynh96** [comment]
I got this error:
> nseqF <- sapply(fnFs, nseq)
 Error: Input/Output
file(s):
/Users/mai/Desktop/Bioinformatics Stuff/Lung2/SRR12264497_1.fastq.gz
message: IncompatibleTypes
message: invalid class “ShortReadQ” object: some sread and quality widths differ

**Comment by benjjneb** [comment]
This error indicates that in at least one file (but probably more) the fastq file contains entries where there are a different number of bases than quality scores. 

This is something that is seen when sequencing data was already processed with read trimming software that produced inconsistent (and technically not valid) fastq files. This was more common with older tools. It is likely that the number of sequences in the forward and reverse read files is also not the same, and thus the reads are mismatched. Also likely that the fastq ids have been rewritten in a way that makes it impossible to match them (although you could inspect the id lines to check on that).

Unfortunately, I don't have a solution on how to use this kind of data with DADA2. You might consider dropping the reverse reads and quality scores and just clustering sequences into OTUs instead, as that approach doesn't require qualities.

**Comment by chuynh96** [comment]
I removed that fastq file (both forward and reverse) and it ended up working. Thank you for helping me troubleshoot this!

**Comment by benjjneb** [comment]
Nice, just one bogey sample. Glad it worked out!

**Comment by benjjneb** [comment]
@DimitraIoli Where did this data come from? If the reads are mismatched and the original fastq ID lines have been lost, then I'm not sure there is a solution. You could take a look at the first couple ID lines in a fastq file -- what do they look like?

You can always just use the forward reads.

**Comment by DimitraIoli** [comment]
Hi @benjjneb !
 These data are demultiplexed sequences for 16S (sequenced with illumina Miseq 2x300bp). 
The fastaq files looks like this: 
@M02434_75_000000000-AJDWB_1_1101_18995_2127 2:N:0:1
GACTACTCGGGTATCTAATCCCTTTCGCTACCCTAGCCTTCGAGCCTCAGCGTCAGTAAATGTCCAGTAACCTGCCTTCGCCGTTGGTCTTCCTCTCGATATCTACGCATTTCACTGCTACACCGAGAATTCCAGTTACCCCTCCATTACTCTAGCGCGGCAGTATCGGATGCAGTTTCAGAGTTGAGCTCTGAGATTTCACATCTGACTTACCGCGCAGCCTACGCTCCCTTTACGCCCAGTGATTCCGAATAACGCTCGGGACCTTCGTATTACCGCGGCTCCTGGCACGAAGTTAGC
+
CCCCCGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGFGFGGCGGFGGGGGGGGGGGFGGGGGGGGGG7EGGGGGGCEDECDGFFFFFFGFGCF7A:CFFG9+BD;CFCFFEFC8F)*@B)85CF=EF=>()6;FA3.4;A):;?1=47)1<E?1<?9*4)(-(,,7),(44?0:4(.-2(49;1((,(),.1*.44::7-))
@M02434_75_000000000-AJDWB_1_1101_17960_2253 2:N:0:1
GACTACCGGGGTATCTAATCCCTTTCGCTACCCTGGCCTTCGTACCTCAGCGTCAGTAAATGTCCAGCAGGCTGCCTTCGCCATTGGTCTTCCTCTCGATATCCACGCATTTCACTGCTACACCGAGAATTCCACCTGCCCCTCCATTACTCAAGTCTAGCAGTATCGGATGCAGTTCCGGCGTTGAGCTCCGGGATTTCACACCTGACTTACCAAACCGCCTACGTACTCTTTACGCCCAGTGATTCCGAATAACTCTCGGGGCCTTCCGATTACCGCGGCTGCTGCGCCGACGCTACC

**Comment by benjjneb** [comment]
That looks like standard Illumina Id headers, which `matchIDs` should handle by default, so I'm not sure what could be going wrong. Can you simplify by running `filterAndTrim(..., matchIDs=TRUE)` on a single sample to make sure that sample throws this error? Then, for that sample, can you post the first 8 lines of the fastq files (i.e. first 2 reads) from both the forward and the reverse fastq files?

**Comment by DimitraIoli** [comment]
I run filterAndTrim(...,matchIDa=TRUE) on a single sample and I've got the following error:
Error in filterAndTrim(forward_reads, filtFs, reverse_reads, filtRs, maxEE = c(3,  : 
  formal argument "matchIDs" matched by multiple actual arguments

Forward:
@M02434_75_000000000-AJDWB_1_1101_16390_1775 1:N:0:1
CCTACGGGGGGCAGCAGTGGGGAATTTTCCGCAATGGGCGAAAGCCTGACGGAGCAACGCCGCGTGAGGGATGAAGGCCTCTTTTCTTTTTCCCTCTTTTTTCTTTTTTTTTTTTCTTTCTTTTCTTTTTTTTTCTCCCTCTTCTTTTTCCTTTCCTTCTTCCTCTTTTTTTCTCTTTTTTCTTTCTTTTTCCTCTCTTCTTTTTCTTTTTTCTTCCTCTTTCTTCCCTTCTTTTCTTCTCTTTCTTTTTTTTTCTTTCCTCCTTCTTTTCCCTTTTTTCTTTTTTTCTTTTTTTTTCT
+
6ACCCGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGFGGGEGGDGGG<FGEGGEGGGGCGGCEEGC@+<E>DE@,=8:@>3<,,,3<,8,,,8383><<>,13,,,,,******188,,,,,2,033++0***2,+,,,,0*+03++30+++2+0+++0+++0+2++3++2*0+++++0+*0+++++23+20++++*20+00+++++2+++*0+00++0+++0+20+2++0***0*2*+2*22***++22))))0:7***/0*)//*0*****1***)()0*/0*((()*))/((,((.
@M02434_75_000000000-AJDWB_1_1101_16032_1802 1:N:0:1
CCTACGGGGGGCTGCAGTGGGGAATCTTGCACAATGGGCGAAAGCCTGATGCAGCGATGCCGCGTGCGGGAAGAAGGCCCTTTTTTTTTTCTCCTCTTTCTTTCTTTTTTCTTTTTTCTTTTCCTCCTTTTTTCTCTTCTTCCCCCTTCTTTCCTTCTTCCTCTCTTTCCCCTTTTCTCCCTTCTTTTTCCTTCTTTTTTTTTCTTTTCTTTCTCTTTTTCTTTTTTTTTTTTCCTTTTTCTTTTCTTTTTTCTCTTCCCTTCTTTCCCTCTCCTTTCTTCTTTTTCTTTTTTTCTTTTTT
+
68ACCGGGGGGGGG7FFGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGFG@FGGGFGE7F7BCEGEEG8,,3@BF@,,,,55*4*,,,,,3<<<3,,,,,,,,,*,,,,8,*22,<,,,2,,+,,,+*,,+0,0,+0+**//**+0+00++0+++0+0+*3+++++*2*++++0+**+0+22+0+++++020+01***++2+++2++00++2++++++00+**/*))/**22*+2)*****0+00*))0*****0*****0**/*0.))*0*.-/0/*/*)(.)/))7((-)-).,
@M02434_75_000000000-AJDWB_1_1101_14889_1806 1:N:0:1
CCTACGGGTGGCAGCAGTGGGGAATATTGCGCAATGGGGGCAACCCTGACGCAGCCATGCCGCGTGTGTGAAGAAGGCCTTAGGTTTGTTAATCACTTTCATTTTTTTTTTTTTTTTTTTCTTTTTTTTCTTCTCTCCCTTTCTTTTCCTTTCTTTTTTTCTCCTTCTTTCTCCTTTCCATCATCCTCTGTTATACTTCTTTTTCTTTCTTTTTTCTTTTTTTCTTTTCTTCTTTCTCTCTTTTTCTTTTTTTTTTTTCTTTTGTTTCTTCCCTTTTCTCTTCCTTTTATCTTCATTCTTT

Reverse:
@M02434_75_000000000-AJDWB_1_1101_18995_2127 2:N:0:1
GACTACTCGGGTATCTAATCCCTTTCGCTACCCTAGCCTTCGAGCCTCAGCGTCAGTAAATGTCCAGTAACCTGCCTTCGCCGTTGGTCTTCCTCTCGATATCTACGCATTTCACTGCTACACCGAGAATTCCAGTTACCCCTCCATTACTCTAGCGCGGCAGTATCGGATGCAGTTTCAGAGTTGAGCTCTGAGATTTCACATCTGACTTACCGCGCAGCCTACGCTCCCTTTACGCCCAGTGATTCCGAATAACGCTCGGGACCTTCGTATTACCGCGGCTCCTGGCACGAAGTTAGC
+
CCCCCGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGFGFGGCGGFGGGGGGGGGGGFGGGGGGGGGG7EGGGGGGCEDECDGFFFFFFGFGCF7A:CFFG9+BD;CFCFFEFC8F)*@B)85CF=EF=>()6;FA3.4;A):;?1=47)1<E?1<?9*4)(-(,,7),(44?0:4(.-2(49;1((,(),.1*.44::7-))
@M02434_75_000000000-AJDWB_1_1101_17960_2253 2:N:0:1
GACTACCGGGGTATCTAATCCCTTTCGCTACCCTGGCCTTCGTACCTCAGCGTCAGTAAATGTCCAGCAGGCTGCCTTCGCCATTGGTCTTCCTCTCGATATCCACGCATTTCACTGCTACACCGAGAATTCCACCTGCCCCTCCATTACTCAAGTCTAGCAGTATCGGATGCAGTTCCGGCGTTGAGCTCCGGGATTTCACACCTGACTTACCAAACCGCCTACGTACTCTTTACGCCCAGTGATTCCGAATAACTCTCGGGGCCTTCCGATTACCGCGGCTGCTGCGCCGACGCTACC
+
CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGCEEGGGCFFCFGGGGGFGGFEGFFFEGFCFDFGGG8DGGGGGGGGC+?CCDDDEGGGE;CE:C5*A8@FAGE>49*++6+;C7FBEFAE838;(CF2D><;FDFEF?FFF57>;:DDD@(.7<??94,3<0AF)*)8::6))3(,)((,42(.2(-6(49632:))(..2(4(:-31
@M02434_75_000000000-AJDWB_1_1101_13208_2254 2:N:0:1
GACTACCGGGGTATCTAATCCTGTTCGCTCCCCACGCTTTCGTCCATTAGCGTCAGTATACAGTTAGTAGACTGCCTTCGCAATCGGTATTCTATGTAATATCTATGCATTTCACCGCTACACTACATATTCTATCTACTTCACTGTAACTCAAGACAACCAGTATCAAAGGCAGTTCCACAGTTGAGCTGTGGGATTTCACCTCTGACTTAATTGCCCGCCTACGGACCCTTTAAACCCAATGATTCCGGATAACGCTTGGACCCACCGTATTACCGCGGCTGCTGGGCAGGAGGTAGC

**Comment by benjjneb** [comment]
> I run filterAndTrim(...,matchIDa=TRUE) on a single sample and I've got the following error:
> Error in filterAndTrim(forward_reads, filtFs, reverse_reads, filtRs, maxEE = c(3, :
> formal argument "matchIDs" matched by multiple actual arguments

Can you clarify the exact command you are running? That error message suggests something is amiss with the syntax of the  command you are running (multiple matchIDs arguments).

**Comment by DimitraIoli** [comment]
Sorry for that
I run the command FilterAndTrim again on a singe sample
filtered_out1 <- filterAndTrim(forward_reads, filtFs,
                                 reverse_reads, filtRs,
                                 maxEE=c(3,4),
                                 rm.phix=TRUE,matchIDs = T,
                                 multithread=FALSE,
                                 compress=TRUE,
                                 truncLen = c(210,200),
                                 trimLeft = c(17,21), minLen =200)
and I've got the following error message, as in the first place:
Error in (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0,  : 
  Couldn't automatically detect the sequence identifier field in the fastq id string.

**Comment by benjjneb** [comment]
Oh I think I see the issue. In standard Illumina fastq id line, the different fields in the id line are separated by colons (see here: https://support.illumina.com/help/BaseSpace_OLH_009008/Content/Source/Informatics/BS/FileFormat_FASTQ-files_swBS.htm) whereas here somehow those colons are underscores (in the first word anyway). This is confusing the autodetection of the id line format: https://github.com/benjjneb/dada2/blob/master/R/filter.R#L940.

I think the solution might be as easy as specifying the `id.sep` and `id.field` parameters that `matchIDs` will then use to match forward to reverse reads. The read id part is in the first word, so `id.sep="\\s"` and `id.field=1` should work...

**Comment by DimitraIoli** [comment]
Perfect! It worked :-)
Thanks a lot for your time and your help!
