### ISSUE TITLE
Manual assignment of ASV after BLASTing 

### ISSUE THREAD

**Issue by callmcgovern** [benjjneb/dada2#1564]
Hello, 
I have been running a microbial community analysis through the dada2 pipeline and it has been working well however when I go to assign taxonomy I notice that my top 3 most abundance ASVs are being assigned to "Tychonema" but when I blast the ASV on Genbank I am seeing "phormidium autumnale" as a 100% match. Is there a way I can manually change the taxonomic assignment from tychonema to phormidium? The samples are benthic and, based on our in-culture experiments, we are pretty sure it is truly a phormidium, not a tychonema (which is usually planktonic). 
Thank you so much for the help.

**Comment by benjjneb** [comment]
> Is there a way I can manually change the taxonomic assignment from tychonema to phormidium?

Yes, you can just use base R to manipulate the taxonomy table returned by `assignTaxonomy`. That table is just a character matrix, and you can overwrite the values in the appropriate cells to your hand assignments. For example:

```
## asv1 is the sequence of asv1
tax[asv1, "Genus"] <- "Tychonema"
```

**Comment by callmcgovern** [comment]
Thank you very much Ben, this helps a lot!
