### ISSUE TITLE
R session aborted when using assignTaxonomy.

### ISSUE THREAD

**Issue by zo88** [benjjneb/dada2#1566]
Hi,

My R session keeps crashing when I try to assign taxonomy.
<img width="584" alt="Capture d’écran 2022-05-27 à 14 06 39" src="https://user-images.githubusercontent.com/106404812/170774919-63a28fcf-e857-4fab-b724-e481cf6d8ae8.png">

Here is the code I am trying to run:
`Test_blocking.nochim.tax <- assignTaxonomy(Test_blocking.nochim, 
                                    "/.../MIDORI_UNIQ_NUC_SP_GB249_CO1_DADA2.fasta",
                                    multithread=TRUE)`

Here are the versions of dada2 and R I am using.
<img width="350" alt="Capture d’écran 2022-05-27 à 14 10 00" src="https://user-images.githubusercontent.com/106404812/170775360-c6cfe1f9-996f-47ce-88ee-fe3c4848cf7e.png">

I don't think it comes from a memory issue because I have 16 Go RAM.

Does anybody know where it could come ?

Thank you for your help

**Comment by benjjneb** [comment]
It's probably a memory issue, or a databse format issue (as that doesn't look like one of our standard databases), or a combination of the two.

How was that reference file created? How many sequences are in that reference file? Can you post what the first few header lines look like? Has someone else used it successfully on their machine?

**Comment by zo88** [comment]
That reference file comes from the MIDORI database and it is supposed to me formatted for dada2.

<img width="519" alt="Capture d’écran 2022-05-27 à 15 34 00" src="https://user-images.githubusercontent.com/106404812/170785751-c5c60c59-6ffb-422a-a058-615826a2005b.png">

**Comment by benjjneb** [comment]
Can you post the full ID lines, not just the beginnings?

When you say it "comes from the MIDORI database" -- this is released by the MIDORI database folks? Or, someone created this file themselves out of the MIDORI database? If the former, I'd ask someone there what sort of memory requirements are needed to use it with DADA2.

**Comment by zo88** [comment]
<img width="979" alt="Capture d’écran 2022-05-27 à 15 46 45" src="https://user-images.githubusercontent.com/106404812/170787358-fea4496c-d830-4424-8b57-3ce64236577c.png">

It was released by the MIDORI team.
