### ISSUE TITLE
Filterandtrim on forward and reverse reads, combined and seperatly

### ISSUE THREAD

**Issue by slq356** [benjjneb/dada2#1567]
Hi all
Im going through the Dada2 tutorial with the std dataset and commandset.

During filtering and trimming, the normal command is to do the step with both reverse and forward reads at the same time:

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=TRUE) 

Its all good man, and a fine table can be printed of the output:

> print(out)
                              reads.in reads.out
F3D0_S188_L001_R1_001.fastq       7793      7722
F3D1_S189_L001_R1_001.fastq       5869      5816
F3D141_S207_L001_R1_001.fastq     5958      5911
F3D142_S208_L001_R1_001.fastq     3183      3156
F3D143_S209_L001_R1_001.fastq     3178      3163
F3D144_S210_L001_R1_001.fastq     4827      4783
F3D145_S211_L001_R1_001.fastq     7377      7316
F3D146_S212_L001_R1_001.fastq     5021      4984
F3D147_S213_L001_R1_001.fastq    17070     16924
F3D148_S214_L001_R1_001.fastq    12405     12317
F3D149_S215_L001_R1_001.fastq    13083     12976
F3D150_S216_L001_R1_001.fastq     5509      5460
F3D2_S190_L001_R1_001.fastq      19620     19445
F3D3_S191_L001_R1_001.fastq       6758      6717
F3D5_S193_L001_R1_001.fastq       4448      4409
F3D6_S194_L001_R1_001.fastq       7989      7918
F3D7_S195_L001_R1_001.fastq       5129      5094
F3D8_S196_L001_R1_001.fastq       5294      5254
F3D9_S197_L001_R1_001.fastq       7070      7003
Mock_S280_L001_R1_001.fastq       4779      4738

However, only forward data is presented. What happens to the reverse data???

So when i do the filtering and trimming for the forward and reverse reads and get the output, this is different from the combined:
outF <- filterAndTrim(fnFs,filtFs,truncLen=c(240), maxN=0, truncQ=10,rm.phix=TRUE, compress=TRUE, multithread=FALSE) 
outR <- filterAndTrim(fnRs,filtRs,truncLen=c(160), maxN=0, truncQ=10,rm.phix=TRUE, compress=TRUE, multithread=FALSE) 

> outF
                              reads.in reads.out
F3D0_S188_L001_R1_001.fastq       7793      7774
F3D1_S189_L001_R1_001.fastq       5869      5857
F3D141_S207_L001_R1_001.fastq     5958      5947
F3D142_S208_L001_R1_001.fastq     3183      3178
F3D143_S209_L001_R1_001.fastq     3178      3172
F3D144_S210_L001_R1_001.fastq     4827      4816
F3D145_S211_L001_R1_001.fastq     7377      7363
F3D146_S212_L001_R1_001.fastq     5021      5010
F3D147_S213_L001_R1_001.fastq    17070     17021
F3D148_S214_L001_R1_001.fastq    12405     12384
F3D149_S215_L001_R1_001.fastq    13083     13053
F3D150_S216_L001_R1_001.fastq     5509      5490
F3D2_S190_L001_R1_001.fastq      19620     19568
F3D3_S191_L001_R1_001.fastq       6758      6746
F3D5_S193_L001_R1_001.fastq       4448      4439
F3D6_S194_L001_R1_001.fastq       7989      7968
F3D7_S195_L001_R1_001.fastq       5129      5123
F3D8_S196_L001_R1_001.fastq       5294      5285
F3D9_S197_L001_R1_001.fastq       7070      7053
Mock_S280_L001_R1_001.fastq       4779      4762

> outR
                              reads.in reads.out
F3D0_S188_L001_R2_001.fastq       7793      7741
F3D1_S189_L001_R2_001.fastq       5869      5828
F3D141_S207_L001_R2_001.fastq     5958      5922
F3D142_S208_L001_R2_001.fastq     3183      3161
F3D143_S209_L001_R2_001.fastq     3178      3169
F3D144_S210_L001_R2_001.fastq     4827      4794
F3D145_S211_L001_R2_001.fastq     7377      7327
F3D146_S212_L001_R2_001.fastq     5021      4995
F3D147_S213_L001_R2_001.fastq    17070     16973
F3D148_S214_L001_R2_001.fastq    12405     12337
F3D149_S215_L001_R2_001.fastq    13083     13006
F3D150_S216_L001_R2_001.fastq     5509      5479
F3D2_S190_L001_R2_001.fastq      19620     19496
F3D3_S191_L001_R2_001.fastq       6758      6729
F3D5_S193_L001_R2_001.fastq       4448      4418
F3D6_S194_L001_R2_001.fastq       7989      7936
F3D7_S195_L001_R2_001.fastq       5129      5100
F3D8_S196_L001_R2_001.fastq       5294      5263
F3D9_S197_L001_R2_001.fastq       7070      7020
Mock_S280_L001_R2_001.fastq       4779      4754

The seperate output data is not similar to the output when trimmed combined. 
Howcome this difference? Is there a reason why only forward data is presented when done combined? 

When i run through the rest of the tutorial with the seperatly filtered and trimmed data, everything works fine 'till i get to the merging step:

mergers <- mergePairs(dadaFs,filtFs,dadaRs,filtRs,minOverlap = 12,  maxMismatch = 0,verbose=TRUE) 

Error in FUN(X[[i]], ...) : 
  Non-corresponding derep-class and dada-class objects.

Lastly. When going through the rest of the tutorial with the combined filter and trimmed data, one is supposed to make a table of the samples reads when going through the different steps. But here, both the denoised forward and reverse data is presented?! 

input filtered denoisedF denoisedR merged nonchim
F3D0    7793     7722      7540      7552   7022    7009
F3D1    5869     5816      5716      5731   5443    5431
F3D141  5958     5911      5750      5761   5321    5190
F3D142  3183     3156      3016      3061   2773    2691
F3D143  3178     3163      3022      3069   2721    2686
F3D144  4827     4783      4563      4662   3972    3813
F3D145  7377     7316      7129      7150   6528    6258
F3D146  5021     4984      4831      4861   4288    4185
F3D147 17070    16924     16666     16671  15215   13968
F3D148 12405    12317     12082     12151  11280   10635
F3D149 13083    12976     12763     12807  11965   11424
F3D150  5509     5460      5251      5337   4685    4598
F3D2   19620    19445     19209     19242  18540   17910
F3D3    6758     6717      6571      6618   6303    5911
F3D5    4448     4409      4260      4317   4001    4001
F3D6    7989     7918      7751      7814   7280    7087
F3D7    5129     5094      4933      4996   4627    4408
F3D8    5294     5254      5126      5112   4856    4827
F3D9    7070     7003      6799      6907   6505    6424
Mock    4779     4738      4685      4677   4640    4640

Im sure theres a fine reason why it only works when the filter and trimming is done combined, why the data is different from when filtered and trimmed seperatly and why seperatly filtered and trimmed data can not be merged. But i'd like to know why. Hope someone can help :)

Cheers

**Comment by benjjneb** [comment]
When you apply `filterAndTrim` to paired reads, only those read pairs in which BOTH the forward AND reverse read pass the filters are output.

That isn't the case when you apply `filterAndTrim` to the forward and reverse reads separately. There, forward reads that pass the filter are output even if the corresponding reverse read failed the filter (and vice versa).

For merging you want the paired read version of filtering, since you can't merge unpaired reads, i.e. read pairs where only the forward or reverse read but not both passed the filter.
