### ISSUE TITLE
forward - reverse reads counts don´t match after trimming primers with cutadapt 

### ISSUE THREAD

**Issue by m-ocejo** [benjjneb/dada2#157]
HI!
Our lab sent samples to an external sequencing service and the data obtained was demultiplexed paired-end sequences without the adapters but the primers are still in the fastq files.

To fulfill the conditions mentioned in the "Starting Point" of the tutorial, I first removed the primers with cutadapt. When running the fastqPairedFilter, this error message came out:

Error in fastqPairedFilter(c(file.path(pathF, fqF), file.path(pathR, fqR)),  : 
  Mismatched forward and reverse sequence files: 105472, 105128.

I realized that in the primers-trimming step the output is not the same and I think this is the problem.
How can I deal with it? Any suggestions?
Thank you very much!

**Comment by vmikk** [comment]
@m-ocejo 
This could be because you trimmed primers with `cutadapt` not in the [paired-end mode](https://cutadapt.readthedocs.io/en/stable/guide.html#trimming-paired-end-reads).

**Comment by m-ocejo** [comment]
Oh thank you! That makes sense!

Best!
