### ISSUE TITLE
dada2 ITS: using cutadapt from a remote server

### ISSUE THREAD

**Issue by amlemoin98** [benjjneb/dada2#1573]
I am currently attempting to employ the dada2 ITS workflow for the removal of primers through a remote server HPC. The issue I run into comes from attempting to designate a path to the cutadapt command. The Linux platform I am working through exists on the remote server, and therefore so does the cutadapt command, while R studio exists in the local computer. Although I can input the path provided to the cutadapt command into R , when I attempt to count the presence of primers in the first cutadapt-ed sample. I will include the code run and the the error featured below:

cutadapt <- "/home/amlemoin/miniconda3/envs/qiime2-2021.2/bin/" 
system2(cutadapt, args = "--version") 
path.cut <- file.path(path, "cutadapt")
if(!dir.exists(path.cut)) dir.create(path.cut)
fnFs.cut <- file.path(path.cut, basename(fnFs))
fnRs.cut <- file.path(path.cut, basename(fnRs))
FWD.RC <- dada2:::rc(FWD)
REV.RC <- dada2:::rc(REV)
# Trim FWD and the reverse-complement of REV off of R1 (forward reads)
R1.flags <- paste("-g", FWD, "-a", REV.RC) 
# Trim REV and the reverse-complement of FWD off of R2 (reverse reads)
R2.flags <- paste("-G", REV, "-A", FWD.RC) 
# Run Cutadapt
for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                             fnFs.filtN[i], fnRs.filtN[i])) # input files
}
rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.cut[[1]]), 
      FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.cut[[1]]), 
      REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.cut[[1]]), 
      REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.cut[[1]]))

**Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'subject' in selecting a method for function 'vcountPattern': error in evaluating the argument 'object' in selecting a method for function 'sread': Input/Output
  no input files found
  dirPath: //hd.ad.syr.edu/03/ca8fb7/Documents/Desktop/USEARCH/fq/cutadapt/RG025_R1.fastq
  pattern: character(0)** 

I was also unsure if there was a better way around installing cutadapt to my local computer, as Bioconda requires a linux or Mac OS, and there are administrative holds on certain dowloads through this remote server, as it is accessed through a university.

**Comment by benjjneb** [comment]
Probably this is an issue with pathing or permissions on your local environment. I can't help with those issues. Have you tried contacting the IT support for your machine?
