### ISSUE TITLE
Zero read.out  - 16S PacBio reads

### ISSUE THREAD

**Issue by emankhalaf** [benjjneb/dada2#1575]
Hi @benjjneb 

I have a new batch of sequenced samples that have been 16S sequenced using PacBio technology. I have two significant issues when processing the reads using DADA2 pipeline for PacBio:

First, when removing the primers and orienting the reads.
`prim <- removePrimers(fns, nops, primer.fwd=F27, primer.rev=dada2:::rc(R1492), orient=TRUE, verbose=TRUE)`

I got this error message at 6 different samples (stopped the code from running), 2 of them were water (negative control):
Error in sum(hits.fwd): invalid 'type' (list) of argument
Does this message mean that the samples do not have any sequences since I got the same error with water/negative control?

The second issue, after removing these 6 samples, and proceeding according to DADA2 workflow, at the step of filter and trim:
`track <- filterAndTrim(nops, filts, minQ=3, minLen=1000, maxLen=1600, maxN=0, rm.phix=FALSE, maxEE=2, verbose=TRUE)`

I got the message below with 3 samples as follows:

-Warning in FUN(if (length(d.call) < 2L) newX[, 1] else array(newX[, 1L],  :
  no non-missing arguments to min; returning Inf
Read in 14, output 0 (0%) filtered sequences.
The filter removed all reads: /home/Documents/sample_name.ccs.fq not written. 
(These 3 samples have read.out = zero)
and at the end, got this message 
Some input samples had no reads pass the filter.

So, when I proceeded to the dereplication step, it did not work which make sense and I got this message:
Error in derepFastq(filts, verbose = TRUE) : 
Not all provided files exist.

Also, when I checked the read.out of all samples, I found that some samples have very low reads (for example; 1 , 2, 3, 4, 5, 6, up to 90's). So, should I exclude these samples from the analysis? If, so is there a threshold of the read.out to exclude samples (for example, samples with read.out count of 1 or 2 will never pass the dereplication step, correct?

Your recommendations are much appreciated!

**Comment by benjjneb** [comment]
The first error message isn't very helpful, but is probably being triggered when no reads are passing `removePrimers`. We should handle that case better though.

In the second part, yes some sequences are having no reads pass the filter, and so no filtered fastq file is output. This can be handled by subsetting down to the filtered fastq files that exist: `filts <- filts[file.exists(filts)]`, and then proceeding to dereplication and onwards.

I definitely would look at the number of reads passing through these samples from start -> remove primers -> filter. This is important to diagnose if there could be something going wrong in the processing. Are these samples dropping out the exception? Or are almost no reads passing these steps in most samples?
