### ISSUE TITLE
Where to start the DADA2, when your sequence are already quality filtered by the sequencing company?

### ISSUE THREAD

**Issue by isuvodeep** [benjjneb/dada2#1576]
Hi, 
I was looking at some sequences like- 
https://www.ebi.ac.uk/ena/browser/view/SRR13756225?show=reads

Where there is one sequencing file from Illumina MiSeq, and in the published paper it mentioned that - The raw sequence data
were obtained from the full-length nifH gene sequence after quality control. 

The sequence files are like that
@SRR13756225.1 1/1
GGTCGTCTGCGCGAGGCCATGGCAGGAGATGATGCAGGGCAGGCCCGCCTTGATAAGATCACTCAGCTGATTGCCGACAGCATGGGCACCGAAGTGTGCTCCATCTATCTGTTTCGCGACGAAGAAACACTGGAACTCTGCGCCACTGAAGGTCTGAACCGCGAATCCGTTCACCAGACCCGTATGCGTGTGGGCGAGGGGCTGGTGGGGCGCGTGGCGCGCACCGGCAAGGTCATCAACACCCCCGACGCCCCCAGCGCGCGTGGCTTTCGCTATATGCCAGAGACCGGAGAGGAGCGGTTTTCCCCCTTCCTTGGTATCCCGGTC
+
GGFGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG

The last part is similar to all the following reads of this sample. 

So, I am a bit confused. 

So, now If I want to analyze those sequences, where do I have to start in DADA2?

Thank you in advance.

**Comment by benjjneb** [comment]
Start at the same place. Presumably you won't lose many reads at the filtering step.
