### ISSUE TITLE
Multi-gene amplicon sequences with dada2

### ISSUE THREAD

**Issue by DimitraIoli** [benjjneb/dada2#1579]
Hi!
I have demultiplexed sequences for eukaryotes (18S) and bacteria (16S) in the same fasta file. I would like to analyze only the sequences for bacteria. I was wondering if I should separate them before running dada2. If yes how I can do that? Otherwise,  can I proceed without separating the two different amplicons by setting the appropriate parameters in filterAndTrim?
Thanks,
Ioli

**Comment by benjjneb** [comment]
> I was wondering if I should separate them before running dada2.

It isn't necessary. You can run the data with both 16S + 18S sequences in it through DADA2 as per normal, and will get a mix of 16S/18S ASVs in the end pretty much as normal.

> Otherwise, can I proceed without separating the two different amplicons by setting the appropriate parameters in filterAndTrim?

If your focus is on the bacterial sequences, make sure that your `filterAndTrim` parameters are appropriate for the bacterial 16S amplicon, e.g. removing the primers correctly and keeping overlap in paired-end data.

**Comment by DimitraIoli** [comment]
Hi Benjamin!
Thank you for your reply.
Cheers,
Ioli
