### ISSUE TITLE
Merge Operation identify multiple files

### ISSUE THREAD

**Issue by Abiola1602** [benjjneb/dada2#1582]
Hi, 
I am using the DADA2 outputs tutorial to analyze my data and I am having issue with the merging step.
The commands that I used are listed below:

# Load custom functions, set working directories, import data --------------------------

#Read in ASV counts
ASVs <- readRDS("ASVs_counts.RDS")#Default options with primer trimming & new refseq_rdp DB
str(ASVs)
dim(ASVs)

#Read in taxonomy table
taxa <- readRDS("ASVs_taxonomy.RDS")
dim(taxa)
#
identical(rownames(ASVs),rownames(taxa))#TRUE
#Assign user-friendly ASV IDs to replace sequences
head(rownames(ASVs))
seqs <- rownames(ASVs)
ASV.IDs <- paste0("ASV",c(1:length(seqs)))
#Named vector:
names(seqs) <- ASV.IDs
head(seqs)
seq_lens <- nchar(seqs)
seq_lens
plot(density(seq_lens))
#Merge ASV table and taxonomic table as a phyloseq object
phy <- phyloseq(otu_table(ASVs,taxa_are_rows=TRUE),tax_table(taxa))
identical(taxa_names(phy),rownames(ASVs))#TRUE
taxa_names(phy) <- names(seqs)
str(phy)
tax_df <- data.frame(tax_table(phy))
tax_df$seq_len <- seq_lens
head(tax_df)
dim(tax_df)
length(which(is.na(tax_df[,"Species"])))# if GG ~ 32% assigned | If RefSeq-RDP ~ 70% assigned at species-level (3048/4415)

Result
 ASVs <- readRDS("ASVs_counts.RDS")#Default options with primer trimming & new refseq_rdp DB
> str(ASVs)
 int [1:771, 1:7] 6438 0 430929 57 0 186 491 21 1644 0 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:771] "" "" "" "" ...
  ..$ : chr [1:7] "Sample.1.515F" "Sample.2.515F" "Sample.3.515F" "Sample.A.515F" ...
> dim(ASVs)
[1] 771   7
> taxa <- readRDS("ASVs_taxonomy.RDS")
> dim(taxa)
[1] 771   7
> #
> identical(rownames(ASVs),rownames(taxa))#TRUE
[1] FALSE
> #
> identical(rownames(ASVs),colnames(taxa))#TRUE
[1] FALSE
> #
> identical(colnames(ASVs),rownames(taxa))#TRUE
[1] FALSE
> #Assign user-friendly ASV IDs to replace sequences
> head(rownames(ASVs))
[1] "" "" "" "" "" ""
> seqs <- rownames(ASVs)
> ASV.IDs <- paste0("ASV",c(1:length(seqs)))
> #Named vector:
> names(seqs) <- ASV.IDs
> head(seqs)
ASV1 ASV2 ASV3 ASV4 ASV5 ASV6 
  ""   ""   ""   ""   ""   "" 
> seq_lens <- nchar(seqs)
> seq_lens
  ASV1   ASV2   ASV3   ASV4   ASV5   ASV6   ASV7   ASV8   ASV9  ASV10  ASV11  ASV12 
     0      0      0      0      0      0      0      0      0      0      0      0 
 ASV13  ASV14  ASV15  ASV16  ASV17  ASV18  ASV19  ASV20  ASV21  ASV22  ASV23  ASV24 
     0      0      0      0      0      0      0      0      0      0      0      0 
 ASV25  ASV26  ASV27  ASV28  ASV29  ASV30  ASV31  ASV32  ASV33  ASV34  ASV35  ASV36 
     0      0      0      0      0      0      0      0      0      0      0      0 
 ASV37  ASV38  ASV39  ASV40  ASV41  ASV42  ASV43  ASV44  ASV45  ASV46  ASV47  ASV48 
     0      0      0      0      0      0      0      0      0      0      0      0 
 ASV49  ASV50  ASV51  ASV52  ASV53  ASV54  ASV55  ASV56  ASV57  ASV58  ASV59  ASV60 
     0      0      0      0      0      0      0      0      0      0      0      0 
 ASV61  ASV62  ASV63  ASV64  ASV65  ASV66  ASV67  ASV68  ASV69  ASV70  ASV71  ASV72 
     0      0      0      0      0      0      0      0      0      0      0      0 
 ASV73  ASV74  ASV75  ASV76  ASV77  ASV78  ASV79  ASV80  ASV81  ASV82  ASV83  ASV84 
     0      0      0      0      0      0      0      0      0      0      0      0 
 ASV85  ASV86  ASV87  ASV88  ASV89  ASV90  ASV91  ASV92  ASV93  ASV94  ASV95  ASV96 
     0      0      0      0      0      0      0      0      0      0      0      0 
 ASV97  ASV98  ASV99 ASV100 ASV101 ASV102 ASV103 ASV104 ASV105 ASV106 ASV107 ASV108 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV109 ASV110 ASV111 ASV112 ASV113 ASV114 ASV115 ASV116 ASV117 ASV118 ASV119 ASV120 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV121 ASV122 ASV123 ASV124 ASV125 ASV126 ASV127 ASV128 ASV129 ASV130 ASV131 ASV132 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV133 ASV134 ASV135 ASV136 ASV137 ASV138 ASV139 ASV140 ASV141 ASV142 ASV143 ASV144 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV145 ASV146 ASV147 ASV148 ASV149 ASV150 ASV151 ASV152 ASV153 ASV154 ASV155 ASV156 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV157 ASV158 ASV159 ASV160 ASV161 ASV162 ASV163 ASV164 ASV165 ASV166 ASV167 ASV168 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV169 ASV170 ASV171 ASV172 ASV173 ASV174 ASV175 ASV176 ASV177 ASV178 ASV179 ASV180 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV181 ASV182 ASV183 ASV184 ASV185 ASV186 ASV187 ASV188 ASV189 ASV190 ASV191 ASV192 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV193 ASV194 ASV195 ASV196 ASV197 ASV198 ASV199 ASV200 ASV201 ASV202 ASV203 ASV204 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV205 ASV206 ASV207 ASV208 ASV209 ASV210 ASV211 ASV212 ASV213 ASV214 ASV215 ASV216 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV217 ASV218 ASV219 ASV220 ASV221 ASV222 ASV223 ASV224 ASV225 ASV226 ASV227 ASV228 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV229 ASV230 ASV231 ASV232 ASV233 ASV234 ASV235 ASV236 ASV237 ASV238 ASV239 ASV240 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV241 ASV242 ASV243 ASV244 ASV245 ASV246 ASV247 ASV248 ASV249 ASV250 ASV251 ASV252 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV253 ASV254 ASV255 ASV256 ASV257 ASV258 ASV259 ASV260 ASV261 ASV262 ASV263 ASV264 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV265 ASV266 ASV267 ASV268 ASV269 ASV270 ASV271 ASV272 ASV273 ASV274 ASV275 ASV276 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV277 ASV278 ASV279 ASV280 ASV281 ASV282 ASV283 ASV284 ASV285 ASV286 ASV287 ASV288 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV289 ASV290 ASV291 ASV292 ASV293 ASV294 ASV295 ASV296 ASV297 ASV298 ASV299 ASV300 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV301 ASV302 ASV303 ASV304 ASV305 ASV306 ASV307 ASV308 ASV309 ASV310 ASV311 ASV312 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV313 ASV314 ASV315 ASV316 ASV317 ASV318 ASV319 ASV320 ASV321 ASV322 ASV323 ASV324 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV325 ASV326 ASV327 ASV328 ASV329 ASV330 ASV331 ASV332 ASV333 ASV334 ASV335 ASV336 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV337 ASV338 ASV339 ASV340 ASV341 ASV342 ASV343 ASV344 ASV345 ASV346 ASV347 ASV348 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV349 ASV350 ASV351 ASV352 ASV353 ASV354 ASV355 ASV356 ASV357 ASV358 ASV359 ASV360 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV361 ASV362 ASV363 ASV364 ASV365 ASV366 ASV367 ASV368 ASV369 ASV370 ASV371 ASV372 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV373 ASV374 ASV375 ASV376 ASV377 ASV378 ASV379 ASV380 ASV381 ASV382 ASV383 ASV384 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV385 ASV386 ASV387 ASV388 ASV389 ASV390 ASV391 ASV392 ASV393 ASV394 ASV395 ASV396 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV397 ASV398 ASV399 ASV400 ASV401 ASV402 ASV403 ASV404 ASV405 ASV406 ASV407 ASV408 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV409 ASV410 ASV411 ASV412 ASV413 ASV414 ASV415 ASV416 ASV417 ASV418 ASV419 ASV420 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV421 ASV422 ASV423 ASV424 ASV425 ASV426 ASV427 ASV428 ASV429 ASV430 ASV431 ASV432 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV433 ASV434 ASV435 ASV436 ASV437 ASV438 ASV439 ASV440 ASV441 ASV442 ASV443 ASV444 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV445 ASV446 ASV447 ASV448 ASV449 ASV450 ASV451 ASV452 ASV453 ASV454 ASV455 ASV456 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV457 ASV458 ASV459 ASV460 ASV461 ASV462 ASV463 ASV464 ASV465 ASV466 ASV467 ASV468 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV469 ASV470 ASV471 ASV472 ASV473 ASV474 ASV475 ASV476 ASV477 ASV478 ASV479 ASV480 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV481 ASV482 ASV483 ASV484 ASV485 ASV486 ASV487 ASV488 ASV489 ASV490 ASV491 ASV492 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV493 ASV494 ASV495 ASV496 ASV497 ASV498 ASV499 ASV500 ASV501 ASV502 ASV503 ASV504 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV505 ASV506 ASV507 ASV508 ASV509 ASV510 ASV511 ASV512 ASV513 ASV514 ASV515 ASV516 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV517 ASV518 ASV519 ASV520 ASV521 ASV522 ASV523 ASV524 ASV525 ASV526 ASV527 ASV528 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV529 ASV530 ASV531 ASV532 ASV533 ASV534 ASV535 ASV536 ASV537 ASV538 ASV539 ASV540 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV541 ASV542 ASV543 ASV544 ASV545 ASV546 ASV547 ASV548 ASV549 ASV550 ASV551 ASV552 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV553 ASV554 ASV555 ASV556 ASV557 ASV558 ASV559 ASV560 ASV561 ASV562 ASV563 ASV564 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV565 ASV566 ASV567 ASV568 ASV569 ASV570 ASV571 ASV572 ASV573 ASV574 ASV575 ASV576 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV577 ASV578 ASV579 ASV580 ASV581 ASV582 ASV583 ASV584 ASV585 ASV586 ASV587 ASV588 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV589 ASV590 ASV591 ASV592 ASV593 ASV594 ASV595 ASV596 ASV597 ASV598 ASV599 ASV600 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV601 ASV602 ASV603 ASV604 ASV605 ASV606 ASV607 ASV608 ASV609 ASV610 ASV611 ASV612 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV613 ASV614 ASV615 ASV616 ASV617 ASV618 ASV619 ASV620 ASV621 ASV622 ASV623 ASV624 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV625 ASV626 ASV627 ASV628 ASV629 ASV630 ASV631 ASV632 ASV633 ASV634 ASV635 ASV636 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV637 ASV638 ASV639 ASV640 ASV641 ASV642 ASV643 ASV644 ASV645 ASV646 ASV647 ASV648 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV649 ASV650 ASV651 ASV652 ASV653 ASV654 ASV655 ASV656 ASV657 ASV658 ASV659 ASV660 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV661 ASV662 ASV663 ASV664 ASV665 ASV666 ASV667 ASV668 ASV669 ASV670 ASV671 ASV672 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV673 ASV674 ASV675 ASV676 ASV677 ASV678 ASV679 ASV680 ASV681 ASV682 ASV683 ASV684 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV685 ASV686 ASV687 ASV688 ASV689 ASV690 ASV691 ASV692 ASV693 ASV694 ASV695 ASV696 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV697 ASV698 ASV699 ASV700 ASV701 ASV702 ASV703 ASV704 ASV705 ASV706 ASV707 ASV708 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV709 ASV710 ASV711 ASV712 ASV713 ASV714 ASV715 ASV716 ASV717 ASV718 ASV719 ASV720 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV721 ASV722 ASV723 ASV724 ASV725 ASV726 ASV727 ASV728 ASV729 ASV730 ASV731 ASV732 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV733 ASV734 ASV735 ASV736 ASV737 ASV738 ASV739 ASV740 ASV741 ASV742 ASV743 ASV744 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV745 ASV746 ASV747 ASV748 ASV749 ASV750 ASV751 ASV752 ASV753 ASV754 ASV755 ASV756 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV757 ASV758 ASV759 ASV760 ASV761 ASV762 ASV763 ASV764 ASV765 ASV766 ASV767 ASV768 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV769 ASV770 ASV771 
     0      0      0 
> plot(density(seq_lens))
> #Merge ASV table and taxonomic table as a phyloseq object
> phy <- phyloseq(otu_table(ASVs,taxa_are_rows=TRUE),tax_table(taxa))
Error in `taxa_names<-`(`*tmp*`, value = gsub("\"", "", taxa_names(x),  : 
  taxa_names<-: You are attempting to assign duplicated taxa_names

I do not understand what this error message means that taxa_names were duplicated.
I can show you my taxa and ASV table if you want.
Kindly help.

Thanks.

**Comment by benjjneb** [comment]
All of the column names in your `ASVs` matris (the sequence table?) have the same empty string `""` name. This isn't a valid sequence table. It also appears to be in the opposite orientation (samples as columns instead of rows) as is used in the standard DADA2 tutorial workflow. 

The problem here comes beforehand, with whatever code generated `ASVs_counts.RDS`.

**Comment by Abiola1602** [comment]
Yes, sample as column,  I know something is wrong with the ASVs table. when
the density is plotted, it doesn't give me the length of the reads, it's
showing 1,2, 3, which doesn't tally with the length of the sequence.

Please, how do I rectify this problem?

Thanks,
Abiola

**Comment by Abiola1602** [comment]
After Tracking reads for two sample
                  input       Filtered    denoisedF   denoisedR  Merged   nonchem
Sample 1   1225431  1098159   1092853    1091220      1038421  625513
Sample2    1023850   899510    896644      896552         859530   517453

**Comment by benjjneb** [comment]
That output suggests you are getting through the tutorial and generating a sequence table successfully. However, the large number of reads (>30\%) lost at the chimera stage typically indicate a problem, usually that primers have not been removed from the reads.

Leaving that aside for now, what is the code you are using to save the sequence table into `ASVs_counts.RDS`? Because it appears there is some manipulation happening prior to it being saved.

**Comment by Abiola1602** [comment]
I noticed most of the reads were lost during chimera, I used fastqprocessor
to remove the primers and demultiplexed. Please can you provide me a way of
demultiplexing? Also I don't know how you get the percentage (30%). I saw
this in the script you sent.

Below are two codes used to save my ASVs and Taxonomy. Thanks

write.csv(taxa, file="ASVs_taxonomy.csv")
saveRDS(taxa, "ASVs_taxonomy.rds")


asv_headers <- vector(dim(seqtab.nochim)[2], mode="character")
count.asv.tab <- t(seqtab.nochim)
row.names(count.asv.tab) <- sub(">", "", asv_headers)
write.csv(count.asv.tab, file="ASVs_counts.csv")
saveRDS(count.asv.tab, file="ASVs_counts.rds")

**Comment by benjjneb** [comment]
> I noticed most of the reads were lost during chimera, I used fastqprocessor
to remove the primers and demultiplexed

I am not familiar with fastqprocessor, but for normal amplicon library setups, we recommend removing primers (if needed) with `filterAndTrim(..., trimLen=c(FWD_PRIMER_LEN, REV_PRIMER_LEN)` rather than using an external program. What is your sequenced amplicon? What are the primers? Are the primers on the reads to begin?

> Please can you provide me a way of demultiplexing?

I don't understand what this means. Usually demultiplexing refers to separating out reads from different samples within a single sequencing run, and these days is usually performed automatically by the Illumina software. Do you have separate fastq files for each sample? Then the reads are already demultiplexed.

> write.csv(taxa, file="ASVs_taxonomy.csv")
> saveRDS(taxa, "ASVs_taxonomy.rds")

Are you reading things back in using `readRDS`? Or `read.csv`?

You should be saving and loading objects using the `saveRDS`/`readRDS` pair of functions, not csv files. When saving/loading from csv files, aspects of the R objects like row names are often lost.

**Comment by Abiola1602** [comment]
Thanks. I got a new issue now. I tried to plot the quality of my read but I
am getting an error message. What should I do?

Thanks
Abiola

**Comment by benjjneb** [comment]
> Thanks. I got a new issue now. I tried to plot the quality of my read but I
am getting an error message. What should I do?

What command are you running and what is the error message?

**Comment by Abiola1602** [comment]
Hi
Thank you for your response, I really appreciate it. I was able to solve
the issue, I got the quality plot.

Please, I need your help and I will be glad if you can help me. I wanted to
run PICRUST on my sample which I don't know how to go about it. I was
looking at your tutorial online but please I need your guidance.

Kindly put me through. Looking forward to your help

Sincerely,
Abiola

**Comment by benjjneb** [comment]
This repository https://github.com/vmaffei/dada2_to_picrust or this issue https://github.com/picrust/picrust2/issues/135 could provide some guidance.

**Comment by Abiola1602** [comment]
Thank you for the link, I will go over it.


Kind regards,
Abiola

**Comment by Abiola1602** [comment]
Dear Benjamin,
I went through these links but I didn't understand. I also note that I
can't run PICRUST on windows. Please kindly guide me, I really want to know
it and if you don't mind, I want to be your student.

Regards
Abiola

**Comment by benjjneb** [comment]
I can't provide PICRUSt support. I don't know the software. You should look for the support channels for that software.

**Comment by Abiola1602** [comment]
Good evening Doc.,
complement of the season and wish you a great and prosperous 2023.

I hope you'll be able to help me out. I entered a wrong code on my R studio
and ever since then I couldn't use it. I decided to uninstall it and
reinstall but it's NOT allowing me to install GenomeInfoDbData. Most
packages depend on this. I have tried all possible things, downloading from
source, CRAN, GitHub but all failed. The GenomeInfoDbData actually
downloaded but it's not loading on R studio.

Please kindly assist me

Kind regards
Abiola
