### ISSUE TITLE
Issues with assigning identical(colnames(ASVs),rownames(taxa))

### ISSUE THREAD

**Issue by Abiola1602** [benjjneb/dada2#1583]
Please can anyone tell me why i kept on getting FALSE for this command identical(colnames(ASVs),rownames(taxa)). identical(colnames(ASVs),rownames(taxa))i tried checking the ASV counts and Taxonomy counts, they are both the same number but it is still giving me FALSE. I also change the command to col and row but all efforts prove abortive. Thanks for your support

**Comment by benjjneb** [comment]
You haven't provided enough information here to diagnose your problem. Are you... following the DADA2 tutorial? Where are you in it? Are things working previously? What are the `dim(ASVs)` and `dim(taxa)`?

**Comment by benjjneb** [comment]
This doesn't help, your comments are not giving enough information to identify the issue you are having. You have "finished running DADA2" -- how? By following the DADA2 tutorial? And, did you get something sensible at the end? How did you save the RDS objects?

In order to get useful support what you are doing needs to be clearly defined. One way to start might be to start over using just two samples from your dataset, run through the DADA2 tutorial, then report the read tracking numbers at the end.

**Comment by Abiola1602** [comment]
Yes, I have finished running DADA2, I followed the tutorial. I think I did
get a good result and saved it as RDS.  Please find attached some of My
results, you can advise further.

**Comment by Abiola1602** [comment]
I am currently rerunning the DADA2 script. Are there different script for
DADA2? maybe you can send me your script. How can I solve the problem of
reorientation? could this be from when I am demultiplexing, removing
primers and barcode using FASTQProcessor?

Thank you for your help, I am indeed grateful.

Sincerely,
Abiola

**Comment by benjjneb** [comment]
> Yes, I have finished running DADA2, I followed the tutorial. I think I did
get a good result and saved it as RDS. 

We know, from this thread and your other thread, that the result you have at the end is not correct. The goal now is to diagnose where the workflow went wrong.

> Could this be from when I am demultiplexing, removing primers and barcode using FASTQProcessor?

It could be, but it could be from other things.

What I recommend is to subset your data down to 2 samples. Then run through the DADA2 tutorial workflow, and start by reporting the read tracking numbers: https://benjjneb.github.io/dada2/tutorial.html#track-reads-through-the-pipeline

That will help a lot in identifying where the workflow is going wrong.

**Comment by Abiola1602** [comment]
Good morning,
Thank you for the assistance, I got relieved when you assist. I am running
for two samples as suggested by you, calculating the error rate is taking
forever but as soon as I finish, will track the read number and send the
results to you. Thank you so much.

Warm regards,
Abiola

**Comment by Abiola1602** [comment]
The error rate for forward reads is still running since morning, can I
terminate it and rerun or does it take this long. I am only running for two
samples as directed by you. Thank you so much for your response.

Sincerely,
Abiola

**Comment by Abiola1602** [comment]
Good day,
You are not responding to my email. Please kindly respond so that I can
meet up with the deadline. Please

Thanks
Abiola

**Comment by benjjneb** [comment]
> Sequel to our discussion, please find attached, my results for two sample
run. 

I don't see anything attached to your post. I don't think it is possible to attach large files to GH comments.

Can you paste in the results of the read-tracking section of the tutorial workflow for these two samples?

**Comment by Abiola1602** [comment]
Good evening,
After Tracking reads
                  input       Filtered    denoisedF   denoisedR  Merged
nonchem
Sample 1   1225431  1098159   1092853    1091220      1038421  625513
Sample2    1023850   899510    896644      896552         859530   517453
