### ISSUE TITLE
Error in writeFastq(fqF, fout[[1]], "w", compress = compress) 

### ISSUE THREAD

**Issue by Th5P** [benjjneb/dada2#1584]
Hello!

I'm following the Dada2 tutorial to preprocess my sequences and suddenly I obtained this error. I have already done it before with the same samples and it worked pretty well. Until now I have tried restarting R, changing the directory, and creating a new folder with the samples but it is not working. Could you help me, please?

> #Filtering Ns (ambiguous bases)
> fnFs.filtN <- file.path(path, "filtN", basename(fnFs)) 
> fnRs.filtN <- file.path(path, "filtN", basename(fnRs))
> filterAndTrim(fnFs, fnFs.filtN, fnRs, fnRs.filtN, maxN = 0, multithread = FALSE)
Creating output directory: F://dirR/Project0/ITS_data/filtN
Creating output directory:F://dirR/Project0/ITS_data/filtN
Error in writeFastq(fqF, fout[[1]], "w", compress = compress) : 
  failed to open file 'F:\dirR\Project0\ITS_data\filtN\1-01A_S63_L001_R1_001.fastq'
In addition: Warning messages:
1: In dir.create(odir, recursive = TRUE, mode = "0777") :
  cannot create dir 'F:\', reason 'Permission denied'
2: In dir.create(odir, recursive = TRUE, mode = "0777") :
  cannot create dir 'F:\', reason 'Permission denied'

**Comment by benjjneb** [comment]
> cannot create dir 'F:', reason 'Permission denied'

This indicates that your R session does not have permission to create a new subdirectory in the `F:\dirR\Project0\ITS_data` directory.

One approach, if you have root privileges there, is to change the permissions on that directory. One could also just manually create those subdirectories to sidestep this problem. If F: is a some sort of shared or network drive, you may need to talk to your local IT/sysadmin folks.

**Comment by Th5P** [comment]
Hi benjjneb

Thank you very much for replying and offering this solution. I'm working directly on my laptop, not as part of a network, I wasn't sure how to change the privileges but I executed Rstudio as administrator and created the folders manually. It worked but then I received this error and I don't know what to do. Does it come from the same issue? What can I do?

#Filter and Trim
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, maxN = 0, 
                     truncQ = 2, minLen = 50, rm.phix = TRUE, compress = TRUE, multithread = FALSE)  
6295F://R/R Work/R/ITS_data/filtN
Creating output directory:F://R/R Work/R/ITS_data/filtered/6299F://R/R Work/R/ITS_data/filtN
Creating output directory:F://R/R Work/R/ITS_data/filtered/6300F://R/R Work/R/ITS_data/filtN
Error in writeFastq(fqF, fout[[1]], "w", compress = compress) : 
  failed to open file 'F:\R\R Work\R\ITS_data\filtered\1-01AF:\R\R Work\R\ITS_data\filtN\1-01A_S63_L001_R1_001.fastq'
In addition: There were 50 or more warnings (use warnings() to see the first 50)

Best wishes,
Thais

**Comment by Th5P** [comment]
Oh, yes it is true! But R put it automatically. How or where should I change it?
