### ISSUE TITLE
issue with assigning taxonomy for 18S

### ISSUE THREAD

**Issue by Rosiekstein** [benjjneb/dada2#1587]
Hello,

I have a set of 18S sequences that have worked perfectly for all of the steps up until assign taxonomy. I downloaded the 18S training set from here: https://benjjneb.github.io/dada2/training.html, but when I try to assign it as in the DADA2 tutorial it completely freezes the supercomuting cluster I am using until it times out, and then I get an error that it was not able to save on startup. This is running 4 cores and 248GB of RAM with multithread = TRUE. Do you have any suggetions? Thank you.

Sincerely,

Rosie

**Comment by benjjneb** [comment]
Can you try assigning taxonomy to a small number of sequences, e.g. `assignTaxonomy(getSequences(seqtab)[1:5], ...)`, and report if that runs smoothly?

**Comment by Rosiekstein** [comment]
so running it in batches ran fine through the whole code, so I used the same idea and wrote in the full range of my samples [1:106] and it ran. So I am not sure what the problem was, but it now runs in ~3 minutes.
