### ISSUE TITLE
Create R1,R2 files to start DADA2 workflow

### ISSUE THREAD

**Issue by Bioinforosy** [benjjneb/dada2#1588]
I am a bioinfo noob. Please suggest how do we create the R1 and R2 files from a sample run's fastq file taken from NCBI and how to we count the no. of reads of the R1 and R2 files. This is for the DADA2 workflow

**Comment by benjjneb** [comment]
Need more information. Is this a fastq you obtained from a single sample from the SRA? What is the library format of that sample? That information should be in the associated "Experiment" entry, i.e. the SRX accession.

**Comment by Bioinforosy** [comment]
Hello my issue was to know how to split the SRA fastq files.. The issue got resolved thank you.
