### ISSUE TITLE
Analyzing 2 batches of sequenced samples separately or together - using qiime dada2 denoise-ccs

### ISSUE THREAD

**Issue by emankhalaf** [benjjneb/dada2#1589]
Hi@benjjneb,

I have 2 questions regarding the use of dada2 for PacBio ccs sequences.
First, I have samples from the same tissue that have been sequenced using PacBio technology on 2 batches. Should I process each batch separately, especially if I am using the pooling option in DADA2, then merge the generated files (seqtab, sq, tax_table) from each batch?
Second, I knew recently that Qiime2 is supporting PacBio ccs sequences, however, when I went through the workflow, I noticed that the denoise step (qiime dada2 denoise-ccs) does not include the pooling option. Is it feasible to replicate the same options of DADA2 in R and use them in qiime2 platform?  In another word, how can I use the pooling option in q2-dada2? Also, the tutorial has SILVA 138 version, and I am using 138.1 version in R. How can I generate qza file of 138.1 version?

Also, when I compared the dada2_stat.qzv for miseq and pacbio sequences of the same samples, I noticed that % of input non-chimeric reads from miseq are within the expected range (above 70%), but those from pacbio ranged between 34%- 0.05%. Any suggestions, here?

Thanks!

**Comment by benjjneb** [comment]
> First, I have samples from the same tissue that have been sequenced using PacBio technology on 2 batches. Should I process each batch separately, especially if I am using the pooling option in DADA2, then merge the generated files (seqtab, sq, tax_table) from each batch?

Is everything the same between the batches? Same library prep, same instrument etc.? If so, I might favor processing them together so I could use pseudo-pooling across the batches.

If any processing is different (and hence the error model might be different) it would be better to process each batch individually and merge.

> Second, I knew recently that Qiime2 is supporting PacBio ccs sequences, however, when I went through the workflow, I noticed that the denoise step (qiime dada2 denoise-ccs) does not include the pooling option.

Psuedo-pooling has been added to the q2-dada2 plugin: https://github.com/qiime2/q2-dada2/pull/122

Full pooling still hasn't I don't think because of the memory issues.

> Also, the tutorial has SILVA 138 version, and I am using 138.1 version in R. How can I generate qza file of 138.1 version?

These kind of versioning updates will percolate through to different platforms at different times.

> Also, when I compared the dada2_stat.qzv for miseq and pacbio sequences of the same samples, I noticed that % of input non-chimeric reads from miseq are within the expected range (above 70%), but those from pacbio ranged between 34%- 0.05%. Any suggestions, here?

There is something fundamentally wrong with the PacBio read pre-processing if >50% of the reads are being identified as chimeric. How were primers removed and reads consistently oriented?

**Comment by emankhalaf** [comment]
@benjjneb 

> Is everything the same between the batches? Same library prep, same instrument etc.? If so, I might favor processing them together so I could use pseudo-pooling across the batches.

If any processing is different (and hence the error model might be different) it would be better to process each batch individually and merge.
Yes, everything the same between batches. In total, I have 358 samples from both batches, and when I processed them in R, at the denoise step using this code
`dd <- dada(drp, err=err, pool=TRUE, BAND_SIZE=32, OMEGA_A=1e-10, DETECT_SINGLETONS=FALSE, multithread=TRUE)`
I got an error message from R that it found a fatal error and to start a new session.
So, I processed half of the samples (second batch), since I already processed the first batch earlier, but I got the same error message. Then, when I restarted R session, I found these errors:
Error in .rs.parsePackageDependencies(contents, extension) : 
  object 'partition_yaml_front_matter' not found
Error in .rs.parsePackageDependencies(contents, extension) : 
  object 'partition_yaml_front_matter' not found
Error in .rs.parsePackageDependencies(contents, extension) : 
  object 'partition_yaml_front_matter' not found
Error in .rs.parsePackageDependencies(contents, extension) : 
  object 'partition_yaml_front_matter' not found
Error in .rs.parsePackageDependencies(contents, extension) : 
  object 'partition_yaml_front_matter' not found
Error in .rs.parsePackageDependencies(contents, extension) : 
  object 'partition_yaml_front_matter' not found
Error in .rs.parsePackageDependencies(contents, extension) : 
  object 'partition_yaml_front_matter' not found
Error in .rs.parsePackageDependencies(contents, extension) : 
  object 'partition_yaml_front_matter' not found

I am not sure what to do to figure it out.

> Psuedo-pooling has been added to the q2-dada2 plugin: https://github.com/qiime2/q2-dada2/pull/122

Full pooling still hasn't I don't think because of the memory issues.

Thank you! So, to use the pseudo option, should I add it to the denosie step as follows:
```
qiime dada2 denoise-ccs --i-demultiplexed-seqs ./samples.qza \
 --o-table dada2-ccs_table.qza \
 --o-representative-sequences dada2-ccs_rep.qza \
 --o-denoising-stats dada2-ccs_stats.qza \
 --p-min-len 1000 --p-max-len 1600 \
 --p-pooling-method = pseudo \
 --p-front AGRGTTYGATYMTGGCTCAG --p-adapter RGYTACCTTGTTACGACTT \
 --p-n-threads 8 \
 --verbose
```

> These kind of versioning updates will percolate through to different platforms at different times.
Thank you!

> There is something fundamentally wrong with the PacBio read pre-processing if >50% of the reads are being identified as chimeric. How were primers removed and reads consistently oriented?
I am following the tutorial as follow:

```
qiime tools import --type 'SampleData[SequencesWithQuality]' \
 --input-path manifest.txt \
 --output-path samples.qza \
 --input-format SingleEndFastqManifestPhred33V2
 
```

 #summarize the read statistics of each barcode pair by running
```
 qiime demux summarize --i-data samples.qza \
 --o-visualization samples.demux.summary.qzv
```
But when I view the demux.summary.qzv, I got the warning below:
 
 ## Danger: Some of the forward PHRED quality values are out of range. This is likely because an incorrect PHRED offset was chosen on import of your raw data. You can learn how to choose your PHRED offset during import in the importing tutorial.

Then I denoised the reads:
```
qiime dada2 denoise-ccs --i-demultiplexed-seqs ./samples.qza \
 --o-table dada2-ccs_table.qza \
 --o-representative-sequences dada2-ccs_rep.qza \
 --o-denoising-stats dada2-ccs_stats.qza \
 --p-min-len 1000 --p-max-len 1600 \
 --p-front AGRGTTYGATYMTGGCTCAG --p-adapter RGYTACCTTGTTACGACTT \
 --p-n-threads 8 \
 --verbose

```

So, what is wrong in the steps above?

Thanks so much!

**Comment by benjjneb** [comment]
Are you using the dada2 R package, or the Q2 plugin, or both at various times? I don't know what is wrong with the q2 plugin part but you may need to look for support on the Q2 site for that. In regards to the out-of-range quality score warning, Pacbio CCS assigns quality scores up to 93 (whereas Illumina only goes to 40) so I think the warning might just be because of that.

> Error in .rs.parsePackageDependencies(contents, extension) :
> object 'partition_yaml_front_matter' not found

I don't know what that message entails, but googling the error message suggests this is an issue with caching data between sessions, e.g.: https://github.com/rstudio/rstudio/issues/11552

**Comment by emankhalaf** [comment]
@benjjneb 
Yes, I am using both at various times. Okay, I will check with Qiime support. 

> In regards to the out-of-range quality score warning, Pacbio CCS assigns quality scores up to 93 (whereas Illumina only goes to 40) so I think the warning might just be because of that.
This makes sense. Thank you!

> I don't know what that message entails, but googling the error message suggests this is an issue with caching data between sessions, e.g.: https://github.com/rstudio/rstudio/issues/11552

Yes, I updated all packages and now the problem is solved. I think this is because of declining RStudio upgrade request.

Thanks so much!
