### ISSUE TITLE
Can DADA2 pipeline assign taxonomy for vertebrate DNA sequences?

### ISSUE THREAD

**Issue by Ecotone23** [benjjneb/dada2#1594]
Hi All,

I am new to DADA2 pipeline and wondering if there is any database/package that can be used in DADA2 pipeline for assigning taxonomy for DNA sequences of vertebrates. I know that the taxonomy assignment can be done for bacterial/fungal sequences, but not sure if the same work can be done for vertebrate sequences. 

Otherwise, is "copy, paste & blast"  on NCBI Blast the only option for assigning the taxonomy for vertebrate sequences?

Thank you,

Gabriel

**Comment by benjjneb** [comment]
Yes it is possible, but it requires identifying an appropriate reference database for the marker-gene and taxonomic groups you are investigating. If there is, it is probably possible to format that reference database to work with `assignTaxonomy`, see format specifications here: https://benjjneb.github.io/dada2/training.html#formatting-custom-databases

However, there may already be specific tools built to work with that reference database (or web services), which is another option for performing the taxonomic assignment.

**Comment by Ecotone23** [comment]
Thank you for the reply. It seems there is no such reference database at the moment.
