### ISSUE TITLE
Are there any tools that automatically detect where to truncate forward and reverse reads for 16S?

### ISSUE THREAD

**Issue by jolespin** [benjjneb/dada2#1596]
I'm trying to run DADA2 via QIIME2 and noticing that it's very hands-on and not completely automated.

**Are there any reliable tools that can indicate where I should trim my forward and reverse reads based on input fastq?**

I understand that every case is different but most of the tutorials I've seen use the consensus of finding the position where the 25th percentile is lower than 30 for the quality. 

Is it not advised to merge all the reads, run through something like FastQC, and then calculating this? 

I'm sure someone has done this and would prefer not to reinvent the wheel.

**Comment by benjjneb** [comment]
You can try Figaro: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7424690/

**Comment by jolespin** [comment]
Yea I ended up finding that tool but I think it might be dead b/c it has a lot of errors and hasn't been updated in over a year.  Been following some threads w/ the author and I think they may have stopped working on it but I'm not sure.

Is the following approach too simple?
1. Get position-specific quality metrics for each fastq file
2. Get the 25th percentile for all the positions and all the samples into a table
3. Find the position for each where the 25th percentile is lower than a specified value (e.g., 30)
4. Make the cutoff at the lowest position

To get around cutting something too short, there could be a parameter that says something like minimum_length so if a cut is suggested that's lower than the length the user can either remove the sample causing that length or go to the next lowest.

**Comment by benjjneb** [comment]
You don't usually want to make sample-specific truncation choices, as the quality profile will be shared for all samples in a sequencing run (excepting problems with library preparation for certain samples).

But your general approach is probably fine, stressing that knowing how long the sequenced amplicon is and ensuring truncation keeps the paired reads overlapping is critical.

**Comment by elpape** [comment]
Hi jolespin,

1. I have been using figaro as well (I even ran it yesterday) and it still works. You just have to make sure your reads have the same length, otherwise figaro will not be able to run. I inspect the range of read lengths and then cut to the smallest size with trimmomatic to circumvent this issue.
2. What I also tend to look at as well is the aggregated read quality profile i.e.  `plotQualityProfile(.., aggregate = T)` and see where read quality drops considerably (some seem to focus on the medium or median, some on the 25th percentile)

There seems to be "no golden standard" and this is also somewhat troublesome for me being new to the field ;-)

Hope this answer was somewhat helpful,
Ellen

**Comment by jolespin** [comment]
How did you end up installing it? Iirc I installed via bioconda and got an error message when I tried to check the install.

**Comment by elpape** [comment]
I used the command line option, explained on the github page (https://github.com/Zymo-Research/figaro). I did install it a while ago, so cannot really recall how smoothly it went, but I got it to work eventually ;-)

The script to run figaro is in the figaro/figaro folder (in my home folder) ...

`git clone https://github.com/Zymo-Research/figaro.git
cd figaro
# depending on your system configuration, the following commands
# are either python3/pip3 or python/pip
python3 setup.py bdist_wheel
pip3 install --force-reinstall dist/*.whl
figaro -i /path/to/fastq/directory -o /path/to/output/files -a [amplicon length] \
    -f [forward primer length] -r [reverse primer length]`
