### ISSUE TITLE
Creating Stacked Bar Chart using Dada2

### ISSUE THREAD

**Issue by EJS01** [benjjneb/dada2#1597]
Good day! Is there a way how can I create a stacked bar chart (i.e. 100% stacked bar chart) at the end of the pipeline? 

[barplot2 family.pdf](https://github.com/benjjneb/dada2/files/9288358/barplot2.family.pdf)

**Comment by benjjneb** [comment]
At the end of the tutorial, the handoff to phyloseq is described. Phyloseq is the R package that (I think) produced the bar plot you linked, via the `plot_bar` function.

**Comment by EJS01** [comment]
I have generated that linked bar plot using this script below:
> plot_bar(ps.top20, fill="Family")

Is there a way on how can I convert that bar graph into 100% stacked column chart?

You may see my entire script below:

[Run Script Big Data DADA2 forwards 220731.docx](https://github.com/benjjneb/dada2/files/9295898/Run.Script.Big.Data.DADA2.forwards.220731.docx)

**Comment by benjjneb** [comment]
You would want to look for that information on the phyloseq support site. I think this is a pretty common question, so searching within the issues there, or just googling will probably find a solution.

For example, perhaps this hit from googling `phyloseq stacked bar chart` will give you a solution: https://github.com/joey711/phyloseq/issues/901

**Comment by EJS01** [comment]
Thank you! Will look at it

**Comment by EJS01** [comment]
Thanks! Will look at it
