### ISSUE TITLE
Issues with assignTaxonomy Function

### ISSUE THREAD

**Issue by userJ123** [benjjneb/dada2#1598]
Hi, I was wondering if anyone could help me figure out why the assignTaxonomy function isn’t running in my code. I know it can sometimes take a while to run, but I’ve let it go for many hours and with the amount of samples it should really only be a few minutes. 

I’ve confirmed that the pathway is correct on my computer, tried changing the “multithread=TRUE” statement to “FALSE” and excluding it altogether. I've confirmed that my seq.nochim file is created and accounted for. My R studio is version 4.1.3 and my dada2 package is version 1.22.0.

No error pops up, the code will just run eternally. If I try to manually stop the code, R Studio crashes.

taxa <- assignTaxonomy(seqtab.nochim, "/Users/J/Downloads/RNA-Seq/silva_nr99_v138.1_wSpecies_train_set.fa.gz")

**Comment by benjjneb** [comment]
How much memory is available on this machine? Running `assignTaxonomy` with the Silva db is fairly memory intensive, especially the `wSpecies` version.

**Comment by userJ123** [comment]
The physical memory of the machine is 8GB but it says that the "Memory Used" is 6.32GB. Is there a less memory-intensive version of Silva db that you recommend trying?

**Comment by benjjneb** [comment]
Try the non `wSpecies` version, and see if that helps. Test it on a small test dataset.

In my experience, running Silva on 8GB is not recommended. 16GB seems to be fine though.

**Comment by userJ123** [comment]
Thank you so much, the non wSpecies version worked!
