### ISSUE TITLE
DADA2 terminated in cluster during 'dereplication'

### ISSUE THREAD

**Issue by yijuanhu** [benjjneb/dada2#160]
Hi,

DADA2 always got terminated in my cluster during the dereplication step. I have 366 forward-read files and 366 reverse. Each file has about 50,000-100,000 unique reads. I guess I have run out of memory. Is it correct? If it is, how can I get around this issue? 

Many thanks!
Yijuan

**Comment by benjjneb** [comment]
Are you using the tutorial workflow or the [big data workflow](http://benjjneb.github.io/dada2/bigdata.html)?

The big data workflow should take care of any memory issues, as it processes samples in a streaming fashion so only one is loaded into memory at a time.

**Comment by yijuanhu** [comment]
I am using the tutorial workflow. I will try the big data workflow. 

Thank you for your quick response!
Yijuan

**Comment by benjjneb** [comment]
Closing as assumed fixed by the big data workflow
