### ISSUE TITLE
Issues assigning species with custom library

### ISSUE THREAD

**Issue by devinjones18** [benjjneb/dada2#1604]
Hi Ben!

I am trying to assign sequences to species using a .fasta file created for a custom library. However, whenever I use my code, I get an error message.

taxa<-assignSpecies(seqtab.nochim, "/Users/filePathway/RefLibFile.fasta")

My ref library has a standard .fasta format: >ID Genus species with following sequence below in all caps (does that even matter if it's in all caps?)

This is the error I keep getting: Error in .Call2("fasta_index", filexp_list, nrec, skip, seek.first.rec, : 
reading FASTA file /Users/filePathway/RefLibFile.fasta: ">" expected at beginning of line 1

I cannot figure out why this is happening...

**Comment by benjjneb** [comment]
The fasta file isn't in the expected format, not sure how else that error could arise.

Have you opened it up in a text editor for close inspection? Were any parts of this fasta file created in Windows and might have hanging carriage returns?

What happens when you run `library(Biostrings); readFastq("path/to/the/file.fastq")`?

**Comment by devinjones18** [comment]
I will go through the fasta file and check to see if there are any hanging returns.

When I run that code, I get:

! Tibble columns must have compatible sizes.
• Size 1321: Existing data.
• Size 1320: Column `Sequence`.
ℹ Only values of size one are recycled.
Backtrace:
 1. microseq::readFastq("/Users/dnjones/Documents/ESP_mifish_2021/fish_ref_dnj2.fasta")
 2. tibble::tibble(...)
 3. tibble:::tibble_quos(xs, .rows, .name_repair)
 4. tibble:::vectbl_recycle_rows(res, first_size, j, given_col_names[[j]])

**Comment by benjjneb** [comment]
Does `microseq::readFastq` handle fasta files?

**Comment by devinjones18** [comment]
Hi Ben! The issues was that my .fasta file didn't have all unique ID's... fixed the problem! Thank you!
