### ISSUE TITLE
Possible to group fastq files of different amplicon lengths

### ISSUE THREAD

**Issue by jesrieder** [benjjneb/dada2#1605]
Hello. 

I am comparing 16S rRNA primers to understand their impact on the community composition of my samples. 

The two primers are 515F_806R and 341F_805R. 

Amplicon libraries were prepared and sequenced on the Illumina MiSeq (2*300PE) on the same lane, which I now know could cause issues, but it is what it is. 

The fastq files for each primer were processed individivually through DADA2 using the trimleft function (515F_806R (trimLeft = c(19,20) and 341F_805R (trimLeft = c(17,21)) and trimRight to remove reads of low quality trimeRight = c(90, 100). This data was used to analysis read quality and enriched ASVs for each primer.

However, to understand how primer choice may influence community composition, we would like to combine the fastq files into one file and then run it through DADA2 so that the two datasets are processed the same and then analyzed for an MDS analysis and Alpha indices. Is this possible since the amplicons are of different lengths? Or what is the best method forward?

**Comment by benjjneb** [comment]
For comparing between them, what I'd recommend is using just the reverse reads, and making them compatible by enforcing a common `truncLen` (not `trimRight`) and a `trimLeft` that cuts one more nucleotide from the 806R primer set. That should get you the same starting position and length from both primer sets.
