### ISSUE TITLE
Error in writeFastq(fqF, fout[[1]], "w", compress = compress) : failed to open file

### ISSUE THREAD

**Issue by tcaspi** [benjjneb/dada2#1608]
Hello,

I'm having issues with the filterAndTrim step. I've successfully done this step on two pilot projects without issue, but am struggling with some new sequence data even though the lines of code I'm running are the same. I have renamed files to remove dashes, tried changing various parts of the code within filterAndTrim, and tried on a small subset of a single sample (F & R) - nothing has worked. Could I please get some advice on what might be causing the issue? The code and output is below. Thank you!

> forward_reads <- sort(list.files(pattern="_R1_001_ca.fastq"))
> reverse_reads <- sort(list.files(pattern="_R2_001_ca.fastq"))
> filtered_forward_reads <- paste0(samples, "_R1_dfilt.fastq")
> filtered_reverse_reads <- paste0(samples, "_R2_dfilt.fastq")
> filtered_out <- filterAndTrim(forward_reads, filtered_forward_reads, reverse_reads, filtered_reverse_reads, matchIDs = TRUE, maxEE=c(2,2),  rm.phix=TRUE, multithread=TRUE, minLen=10, maxLen=110)

Error in filterAndTrim(forward_reads, filtered_forward_reads, reverse_reads,  :
  These are the errors (up to 5) encountered in individual cores...
Error in writeFastq(fqF, fout[[1]], "w", compress = compress) :
  failed to open file 'BLANK_MB2_S74_R1_dfilt.fastq'
Error in writeFastq(fqF, fout[[1]], "w", compress = compress) :
  failed to open file 'BLANK_MB3_S171_R1_dfilt.fastq'
Error in writeFastq(fqF, fout[[1]], "w", compress = compress) :
  failed to open file 'BLANK_MB4_S18_R1_dfilt.fastq'
Error in writeFastq(fqF, fout[[1]], "w", compress = compress) :
  failed to open file 'BLANK_MB5_S115_R1_dfilt.fastq'
Error in writeFastq(fqF, fout[[1]], "w", compress = compress) :
  failed to open file 'BLANK_MB2_S74_R1_dfilt.fastq'
In addition: Warning message:
In mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule,  :
  all scheduled cores encountered errors in user code

**Comment by benjjneb** [comment]
What kind of computing and file system environment are you working with? Is it possible that you don't have permission (or the R script doesn't have permission) to write files to the directory you are trying to write them too? You can test this with something simple, like `write.csv` a data.frame to whatever location you are trying to save the filtered fastqs in.

**Comment by tcaspi** [comment]
Oh yes that was the problem! I was able to get the permissions changed such that I could write files in this directory and now it worked - thank you!
