### ISSUE TITLE
Not sure about wich Silva 138 classifier it is

### ISSUE THREAD

**Issue by CamargoFP** [benjjneb/dada2#1610]
Hello,

I am using the DADA2 pipeline tutorial in order to process some samples. I would like to know wich SILVA version is used in this pipeline, in the line

taxa <- assignTaxonomy(seqtab.nochim, "~/tax/silva_nr_v132_train_set.fa.gz", multithread=TRUE)

I am not sure if it is "Silva 138 99% OTUs full-length sequences", "Silva 138 99% OTUs from 515F/806R region of sequences" or maybe neither of them. I got >70% Archaea in my sample and don't know if it is correct, even being a sample from a methanogenic anaerobic reactor. The primer set used was F515-R806 (DOI: 10.1002/bit.20347).

Many thanks!

**Comment by benjjneb** [comment]
You can download different reference datasets, including different versions of the Silva database, that are curated and formatted for the `assignTaxonomy` function in DADA2 here: https://benjjneb.github.io/dada2/training.html

The links in the contributed reference data entries are to Zenodo entries with more information about the specifics, including exactly what Silva files were used in their construction. In this case, the filename has a bit of a hint: the `v132` part indicates that file was is built from the Silva v132 release, not the v138 release at all.
