### ISSUE TITLE
seqtab shows many sequences with same length as forward read truncation

### ISSUE THREAD

**Issue by ashleigh-f-marshall** [benjjneb/dada2#1613]
Hello,

I apologise if I have missed this being discussed elsewhere but I couldn't find anything! I am following the DADA2 Pipeline Tutorial (1.16) and have not had any obvious issues, but I am curious about something I have noticed in the sequence table. My data is of the V4 region using 515F-806R primers and is in the form of Casava 1.8 paired-end demultiplexed fastq files.
I trimmed my forward and reverse reads at 240 and 160 respectively as follows:

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
                     maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, multithread=TRUE)

The next steps appear to run fine, and when I check the sequence table using table(nchar(getSequences(seqtab))) most sequences appear to be clustered around 253 as expected (screenshot below), but there are a large number of sequences (~10%) with length 240, which is the trimmed length of the forward reads. 

![Screenshot 2022-09-28 at 17 44 20](https://user-images.githubusercontent.com/54185001/192841531-9ccd4ad1-c2be-4074-81bd-a14313d15af4.png)

I've checked the distribution of the read counts by length and I think it looks ok:

![Screenshot 2022-09-28 at 17 43 11](https://user-images.githubusercontent.com/54185001/192841628-fa43538d-af1e-4404-aac9-094e359aeeb2.png)

Is this to be expected? Am I safe to removed these non-target-length sequences using: seqtab2 <- seqtab[,nchar(colnames(seqtab)) %in% 250:256]? When I do this and track the reads through the pipeline it looks like most of the raw reads have been kept.

![Screenshot 2022-09-28 at 17 45 29](https://user-images.githubusercontent.com/54185001/192841935-59586965-e321-4af8-a70d-a649ce8281da.png)

Thanks in advance for any advice on this! It would be really appreciated.

All the best,
Ashleigh

**Comment by benjjneb** [comment]
> Am I safe to removed these non-target-length sequences using: seqtab2 <- seqtab[,nchar(colnames(seqtab)) %in% 250:256]?

Yep, that is fine. No different than cutting out a band from a gel.

> Is this to be expected?

I don't usually see this with these V4 primers, but off-target amplification of genetic loci outside the expected length range is not uncommon in general, and is my guess for what is causing this observation. If you want to dig in more, you could pull out a few example ASVs in those unexpected lengths and BLAST them just to get a sense of what they might be. But in any case, selecting only ASVs in the expected V4 length range is valid.

**Comment by benjjneb** [comment]
> Does this still follow with it just being off-target amplification? Thanks!

Yes. Short off-target amplicons will end up in the final ASV table as being the length of the shortest truncation length.
