### ISSUE TITLE
weird output from learnErrors

### ISSUE THREAD

**Issue by botanicalboy** [benjjneb/dada2#1615]
Hi,

I'm working with an 18S amplicon dataset sequenced on NovaSeq. On the error modelling step, learnErrors met convergence for both the forward and reverse reads, but the output graph looks weird. Should I be concerned? 

Code used:
errF <- learnErrors(filtFs, nbases=1e8, randomize = T, verbose = T, multithread=T)
errR <- learnErrors(filtRs, nbases=1e8, randomize = T, verbose = T, multithread=T)

Here's the output:
![image](https://user-images.githubusercontent.com/86253987/193362231-03ea3b80-e333-444f-af01-c497420fb778.png)

Fwd error model
![image](https://user-images.githubusercontent.com/86253987/193362351-5512c8f5-53eb-49c8-b68c-212763ae8946.png)

Rev error model
![image](https://user-images.githubusercontent.com/86253987/193362457-9d07b4e2-4c2b-4991-9d9f-949ce133bd8f.png)

**Comment by benjjneb** [comment]
See https://github.com/benjjneb/dada2/issues/1307

In short, we haven't found evidence that this is a concern in practice, but there is much more discussion and some alternatives in that Issue.
