### ISSUE TITLE
16S data on Nextseq 2000

### ISSUE THREAD

**Issue by nagasridhar** [benjjneb/dada2#1616]
Hi Ben,

We have a Nextseq 2000 run for low biomass for 16S data. On an average the samples have about 500 million reads which possibly includes human contamination as well. 

I set up the analysis on unlimited node on a HPC for error learning and even after 15 days the error learning on the dataset did not complete. 

Please provide a guidance on how to analyze data generated on Nextseq 2000 for low biomass samples.

**Comment by benjjneb** [comment]
Hi Naga,
Good to hear from you!
Unfortunately at this point I may have to recommend looking at a different tool.

Our core target datasets with DADA2 development were up to 1M reads per sample, with up to 10M reads per sample as reach targets given sufficient computational power. I just don't think we have an implementation right now that is going to be computationally effective on 100M+ read samples.

Preparing the samples beforehand by removing human contamination, aggressively filtering and so forth will help. But at this point I think these samples are probably too big.

**Comment by nagasridhar** [comment]
Thanks for the guidance Ben. I will try out removing human contamination and see if that makes any sort of difference. I keep my fingers crossed.
