### ISSUE TITLE
Print non chimeric sequences per individual

### ISSUE THREAD

**Issue by BWri** [benjjneb/dada2#1617]
We are using DADA2 to infer alleles from MHC amplicon sequences. Basically we have hundreds of samples and need DADA2 to output fastas for each sample after merging and getting rid of chimeras so that we can blast these against a custom database. I have managed to get the mergers out but not the non-chimeric seqs out:

for(i in seq_along(sample.names)) {
uniquesToFasta(mergers[[i]], paste0(sample_", i, ".fasta"))
}
#works for merged seqs, however:

for(i in seq_along(sample.names)) {
  uniquesToFasta(seqtab.nochim[[i]], paste0(sample_", i, ".fasta"))
}

gives the following error:

Error in getUniques(unqs, collapse = FALSE) :
  Unrecognized format: Requires named integer vector, fastq filename, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.

#seqtab.nochim is a matrix but I can't figure out how to print the seqs (and their counts) per individual- can only print the entirety using:

uniquesToFasta(seqtab.nochim, "uniqueSeqs.fasta")

#but we need this for each sample separately- advice much appreciated!

**Comment by benjjneb** [comment]
Since `seqtab.nochim` is a matrix with rows corresponding to samples and columns corresponding to ASVs, the syntax you are using `seqtab.nochim[[i]]` isn't correct. Should be:

`seqtab.nochim[i,]` to get the row corresponding to the ith sample.

That said, this will output all the ASVs in each sample, even those with zero reads. To only output the ASVs that are present in each sample:

```
seqvec <- seqtab.nochim[i,]
seqvec <- seqvec[seqvec>0]
```

**Comment by BWri** [comment]
Thanks very much for this Ben!

**Comment by y-sierra** [comment]
Thanks for the help Ben!
I applied the changes you suggested in two methods, with both resulting in the same output:

#method one
for(i in seq_along(sample.names)) {
  seqvec <- seqtab.nochim[i,]
  seqvec <- seqvec[seqvec>0]
  }
uniquesToFasta(seqvec, paste0("Sample_", i ,".fasta"))

#method two
  seqvec <- seqtab.nochim[i,]
  seqvec <- seqvec[seqvec>0]
uniquesToFasta(seqvec, paste0("Sample_", i ,".fasta"))

However, both output only one sample's result as a fasta. Would you know how I should change the code to direct a fasta file for each sample?

**Comment by benjjneb** [comment]
You need to put the `uniquesToFasta` call inside the loop. Right now it is looping through each sample, and making a `seqvec` for each, but it doesn't output the fasta until all the looping is done, so you just get one fasta for the last sample.

**Comment by y-sierra** [comment]
Thank you Ben, This worked.
