### ISSUE TITLE
Minimal length of merged sequences?

### ISSUE THREAD

**Issue by vrbacky** [benjjneb/dada2#162]
Would it be possible to specify minimal length of merged sequences? I get some unreasonably short sequences. BTW, how does the *mergePairs* function work? Does it search for the longest overlap fulfilling *maxMismatch* restriction? THX.

**Comment by benjjneb** [comment]
`mergePairs` performs a "local" NW alignment of the two sequences (end-gaps are free) and then ensures that this alignment meets the specified criteriea (mismatches <= `maxMixmatch`, overlap between them is >= `minOverlap`).

There is no dedicated command to filter merged sequences based on length, but it can be easily done with base R commands (and is often worth doing):

```S
MINLEN <- 200; MAXLEN <- 220
seqlen <- nchar(getSequences(seqtab))
seqtab.rightlen <- seqtab[,seqlen>MINLEN & seqlen<MAXLEN]
```

**Comment by vrbacky** [comment]
Thank you for the clarification.
