### ISSUE TITLE
Failing to Merge using filter and trim

### ISSUE THREAD

**Issue by staffordv** [benjjneb/dada2#1622]
I have been testing out DADA2 out of interest to compare to OTU based analysis. My data is 300bp paired end reads using v3-v5 primers. When  I attempt to trim the reads using truncLen to remove poor quality ends of reads I am losing the majority of reads (see below). This is due to the lack of overlap of the reads across the large amplicon. If I remove the the truncLen parameter I get the majority of reads merging.  Is there a way to trim the reads for quality but still maintain sufficient length to allow merging.

input filtered denoisedF denoisedR merged nonchim
105C 128309    68112     66001     65634     41      41
105I 107248    71210     70996     71009     36      36
107C  57739    25751     24693     24173    100     100
107I  98047    65988     65906     65940     23      23
10C  245522   118914    118272    117061    118     118
10I  141103    88058     87903     87777     41      41

**Comment by benjjneb** [comment]
Sorry for the late reply...

The first priority when merging is that you must maintain enough length for them to overlap afterwards. So, what is the maximum length of the sequenced amplicon, and then add ~15 nts. That is what your forward and reverse truncation lengths should add up to as a minimum.

You can still use the `maxEE` filter to remove the lower quality reads.

Another option in the case of very low quality reverse reads (as sometimes happen w/ Illumina paired-end) is to just use the forward reads alone.

**Comment by staffordv** [comment]
Hi Benjamin,

Thank you for your reply. The maximum amplicon length is 600bp so I think
this is the issue that when I truncate at all the reads don't join. I will
try using maxEE and not truncate

Kind regards,

Stafford
