### ISSUE TITLE
Dada2 with time series data

### ISSUE THREAD

**Issue by Hewang11111** [benjjneb/dada2#1624]
Hi there, I have a problem about processing time series data using dada2 (groundwater). I took over a project that has been running already for 9 years and has been ongoing. My former colleague ran previous amplicon sequencing (2013 to 2021) with version 1.16 of dada2, but it is understood that the version of dada2 has been upgraded to 1.24. My question is, should I use the latest version to run the new data (from 2021) and incorporate them into the old database or should I continue to use version of 1.16 of dada2 to keep all the data consistency?
Many thanks!

**Comment by benjjneb** [comment]
Staying at 1.16 is fine. Assuming this is short-read sequencing, there have been no substantial changes to the package that would impact the results.

**Comment by Hewang11111** [comment]
Thanks a lot! Could you please also let us know if there will be a version with a substantial change from the previous one. So we could update our database totally?

**Comment by benjjneb** [comment]
Note: I am not actively maintaining a twitter presence anymore.
