### ISSUE TITLE
Facing problem to analyze the data downloaded from DDBJ

### ISSUE THREAD

**Issue by isuvodeep** [benjjneb/dada2#1627]
Hi,
I am trying to analyze some data that I downloaded from the DDBJ platform. As the files in DDBJ are available in bz2 archive format, I converted those files online to gz archive format. But, I am facing some problems and getting the error 
Error in add(bin): record does not start with '@'
But, I checked all the files contained the format @ like other fastq.gz files

The second error I am getting when I merged different downloaded data from the different studies and tried to analyze them together (including the file downloaded from DDBJ and converted in gz archive). 
Error: Not all files exist (I also checked I have all the files).

How do I proceed with this problem?

Thank you in advance for your help.

**Comment by benjjneb** [comment]
The dada2 R package should read in bz2 compressed fastq files natively. Have you tried with just those original files?

> Error: Not all files exist (I also checked I have all the files).

You can use the function `file.exists(vec_of_filepaths)` in R to identify what is "missing". This will return a logical TRUE/FALSE vector showing where R can or cannot find the filepath that was provided.
