### ISSUE TITLE
creating a reference DB to assign taxonomy in Dada2

### ISSUE THREAD

**Issue by mycotonia3** [benjjneb/dada2#1628]
I am creating an Insect DB to assign taxonomy to my ASVs (i extracted all insect COI sequences from the BOLD DB - full COI Folmer region ~ 658bp).

I will use 2 primer sets to test which is the best to assign taxonomy.  One primer set amplifies the first ~200pb of the Full Folmer COI region and the second amplifies the last 400bp.

Can I use the full ~658 bp region in my DB when assigning taxonomy or should i create different DB depending on the region amplified by the primers?  in other words, should i align all my sequenced, trim and use only the first 200pb for primer pair #1 and create another with the last 400bp for primer#2.

I did try to assign taxonomy on a small subset of samples with the full 658 COI region and did not get many matches. Just wondering if there is something I can do to improve this. thanks

**Comment by benjjneb** [comment]
> Can I use the full ~658 bp region in my DB when assigning taxonomy or should i create different DB depending on the region amplified by the primers?

You should use the whole region. The `assignTaxonomy` function implements the [naive Bayesian classifer method of Wang et al.](https://pubmed.ncbi.nlm.nih.gov/17586664/) This method breaks up sequences into kmers (8mers by default) before making comparisons. Thus there is little if any cost in including longer sequences as the reference, and in fact in pratical terms that is often preferable to avoid any issues with clipping reference sequences at the wrong spots.

**Comment by mycotonia3** [comment]
thanks for the reply!  good news - i do not have to create 2 different DB, bad news is I dd not get many ASvs assigned.  Would you know of a Insect or (Arthropod) reference database that has been used with dada2.  Maybe I can compare it with the one i am using?

**Comment by benjjneb** [comment]
> Would you know of a Insect or (Arthropod) reference database that has been used with dada2. Maybe I can compare it with the one i am using?

I have exactly zero experience working with arthropod metabarcoding. Is there a community more in tune with that subject area that you could reach out to?

**Comment by mycotonia3** [comment]
Hi Ben,  
made some progress but have a few new questions.  I created a DB for Arthropods with COI sequences from the BOLD  DB. After speaking with a local insect taxonomist he told me to be careful with some of those entries as some cannot be trusted.  Since I am concentrating on pollinators from my study, I thoroughly examined all bee entries and made sure to get sequences from bees in my area of study from reputable researchers only.  That curated "bee"  database has ~ 270 entries.  Then i also downloaded all Arthropod sequences from the BOLD DB.  That arthropod DB has about 189K sequences.  
I ran the assigntaxonomy with the Bee DB and got 30 ASVs assigned to Order level.  I thought that was a petty cool result!
But I then ran the same ASV table with the full Arthropod DB and only got one ASV assigned to order. I then pasted the curated bee DB to the full arthropod DB and still got only one ASV assigned to order.  Does this sound correct or is something odd going on?

I also got this error when i combined the DB:
Warning message:
In .Call2("fasta_index", filexp_list, nrec, skip, seek.first.rec,  :
  reading FASTA file /home/shared/tonia.debellis/eFlower_seqs1/arthropoda_ref_BEE2.fas: ignored 28 invalid one-letter sequence codes

thanks for your help.

**Comment by benjjneb** [comment]
> I also got this error when i combined the DB:
> Warning message:
> In .Call2("fasta_index", filexp_list, nrec, skip, seek.first.rec, :
reading FASTA file /home/shared/tonia.debellis/eFlower_seqs1/arthropoda_ref_BEE2.fas: ignored 28 invalid one-letter sequence codes

Warnings are often ignorable. In this case, I think it indicates that some entries in the database you are using have non-ACGT letters. But those will be "gracefully" handles by being ignored.

> That curated "bee" database has ~ 270 entries. Then i also downloaded all Arthropod sequences from the BOLD DB. That arthropod DB has about 189K sequences.
I ran the assigntaxonomy with the Bee DB and got 30 ASVs assigned to Order level. I thought that was a petty cool result!
But I then ran the same ASV table with the full Arthropod DB and only got one ASV assigned to order. I then pasted the curated bee DB to the full arthropod DB and still got only one ASV assigned to order. Does this sound correct or is something odd going on?

I am not, and don't pretend to be, an expert on systematics, especially in the Eukaryota. I can offer a few thoughts. Quality is more important than quantity, as long as you have sufficient representation in your "outgroups", i.e. taxa related but outside the groups you are most interested in for your study. Low quality can somtimes mean misassigment of taxonomy, and that can be very damaging to many assignment methods, including `assignTaxonomy`. Worst case scenario -- a sequence you are including in the reference comes from one of your taxa of interest, but for some reason was assigned a taxonomicially distance (and totally wrong) name.

**Comment by mycotonia3** [comment]
Hello Ben & happy new year,
I am still on the quest to develop a DB for insects for Eastern Canada that I could use with dada2.
I made 2 using the sequences from BOLD.  
1) arthropod_ref.fas seems to be  working in dada 2, but I do not get many ASV identifications (very few!)
2) Insectata_seqs.fas  is not working and i do not know why?  All i get back after i run assigntaxonomy is NA  for Kingdom, Phylum, Class , Order...
Arthropod_ref includes all arthropod sequences found in BOLD and for the Insecta DB i selected insects from 3 Eastern provinces in Canada (the area that i work in). I thought this would be a better  DB to use for my work. 
Can you please have a look at the two DB and can you spot the reason why the Insecta DB is not working? I would assume it's a formatting issue?  the 2 files were too big to send in full, so i attached a few entries from each.  thank you. 
[arthropoda_edit.txt](https://github.com/benjjneb/da
[Insecta_edit.txt](https://github.com/benjjneb/dada2/files/10355896/Insecta_edit.txt)
da2/files/10355891/arthropoda_edit.txt)

**Comment by benjjneb** [comment]
Sorry for delay in responding.

The link to your Insecta DB is not working for me.
Also, have you tried running `assignTaxonomy(..., tryRC=TRUE)`?
This will also try the reverse complement of all query sequences, and this can sometimes solve these sorts of issues if the root prohblem is that the queries are in the opposite orientation to the reference databse.

**Comment by mycotonia3** [comment]
Hello,  I got access to another COI DB and i'd like to format it to use with assigntaxonomy with dada2. 
at the moment i have 2 files, that look like the following:
File 1: Sequence file, in this format:
>GBA28166-15
AACATTATATTTAATTTTCGGTGTCTGGGCAGGCCTGATTGGCACATCCTTAAGAATTTTAATTCGTGCTGTCGTAATTTAAATACATCATTTTTCGATCCAGCAGGAGGTGGTGATCCTATTTTATATCAACACCTATTC….
>TTSOW533-11
TACTTTGTATNTATTATTTGGAGTTTGAGCAGGTTTAGTAGGNACTTCATTAAGAGTTTTAATTCGTGCTGAATTAGGTCAACCTGGAAACCTTATTGGTGATGATCAAATTTATAATGTAATTGTTACAGCTCATGCA…
>GBMH8364-13
TCTCTCAGTGTACTAATTCGTGCCGAACTCGATCCAGCAGGAGGTGGTGATCCTATTTTATATCAACACCTATTC….

File 2: Taxonomy file in this format:
GBA28166-15	p__Arthropoda;c__Insecta;o__Archaeognatha;f__Machilidae;sf__Petrobiinae;g__Pedetontinus;s__Pedetontinus luanchuanensis
TTSOW533-11	p__Arthropoda;c__Insecta;o__Archaeognatha;f__Machilidae;sf__Petrobiinae;g__Pedetontus;s__Pedetontus saltator
GBMH8364-13	p__Arthropoda;c__Insecta;o__Archaeognatha;f__Machilidae;sf__Machilinae;g__Haslundichilis;s__Haslundichilis hedini

Would this format work for dada2? (see below) Specifically, will the sf__ be accepted?  Will species in this format work Pedetontinus luanchuanensis or should it be changed to this: Pedetontinus_luanchuanensis – with the underscore between genus and species? Also is the Accession code followed by a bar |  and p__  correct format?

>GBA28166-15|p__Arthropoda;c__Insecta;o__Archaeognatha;f__Machilidae;sf__Petrobiinae; g__Pedetontinus;s__Pedetontinus luanchuanensis AACATTATATTTAATTTTCGGTGTCTGGGCAGGCCTGATTGGCACATCCTTAAGAATTTTAATTCGTGCTGTCGTAATTTAAATACATCATTTTTCGATCCAGCAGGAGGTGGTGATCCTATTTTATATCAACACCTATTC

thank you.

**Comment by benjjneb** [comment]
Drop the accession number at the start of the id line, and you'll need to remove the white space from the species designation as well. So like this:

```
p__Arthropoda;c__Insecta;o__Archaeognatha;f__Machilidae;sf__Petrobiinae; g__Pedetontinus;s__Pedetontinus_luanchuanensis AACATTATATTTAATTTTCGGTGTCTGGGCAGGCCTGATTGGCACATCCTTAAGAATTTTAATTCGTGCTGTCGTAATTTAAATACATCATTTTTCGATCCAGCAGGAGGTGGTGATCCTATTTTATATCAACACCTATTC
```

**Comment by mycotonia3** [comment]
thank you



Tonia De Bellis, PhD
Faculty, Biology Department &
Co-coordinator, Environmental Science|Dawson College
Affiliate associate professor, Biology Department|Concordia University

​

________________________________
