### ISSUE TITLE
Assignment of taxa for reads matching multiple species

### ISSUE THREAD

**Issue by NextGenSeek** [benjjneb/dada2#1629]
Hi,

I’ve noticed that several species that we expected to be in the sample were not identified. I checked the sequences in the raw data file and it looks like there are thousands of reads, that have a 100 percent matching sequence to those species (according to blast). 

Several of these very abundant sequences were assigned to rare species with the same sequence, rather than the expected common species. Both gave a 100% Blast match, so I understand there is no way of knowing which one is correct. How does dada2 assign it to a species if there are multiple options? Is there a way to control for this to encourage assigning the reads to the common, expected species, rather than the rare species?

**Comment by benjjneb** [comment]
The DADA2 R package has two different methods that could be used to assign speciecs, the `assignTaxonomy` function and the `assignSpecies` function. Can you clarify what commands you are using? And give examples of assignments that you think might be incorrect.

**Comment by NextGenSeek** [comment]
I use assignTaxonomy. The assignments are not incorrect, it is just that several sequences are a 100% match with multiple species and it looks like they are just (randomly?) assigned to one species.

**Comment by benjjneb** [comment]
> I use assignTaxonomy

Can you clarify the exact command you are using? `assignTaxonomy` is not usually used to assign past the genus level in short-read 16S data.

The exact results of a small test set of sequences would also be helpful.
