### ISSUE TITLE
applying DADA2 on nirK data

### ISSUE THREAD

**Issue by MartonSzoboszlay** [benjjneb/dada2#163]
Hello,
I would like to apply DADA2 on a nirK dataset and I'm wondering if you have any experience with this. I'm quite sure, that I have to disable the banded alignment heuristic, but are there any other parameters in the default DADA2 pipeline you would recommend to change? For example, I'm unsure if it would be better to turn off the k-mer distance screen too, or increase omega A.
Thank you very much!

**Comment by benjjneb** [comment]
Could you comment a bit more on what might be unusual about nirK? I'm not familiar with that gene.

For functional genes, we generally find that the default parameters work perfectly fine, although I do often expand to BAND_SIZE=32 to be cautious about potentially higher indel rates.

**Comment by MartonSzoboszlay** [comment]
Thanks for your reply! NirK is one of the nitrite reductase genes. I've never worked with it before, so I'm still learning about it. I definitely expect a much higher indel rate than for 16S. I also see in the literature, that in contrast to 16S, nirK OTUs are often picked with a rather low sequence similarity threshold (e.g. 83%). Unfortunately I haven't found any good explanation for this yet, and this may not have any implications if I process the data with DADA2 anyway, but it made me wonder if I should adjust any parameters in the pipeline.

**Comment by benjjneb** [comment]
One reason that much looser clustering thresholds are used for some classes of functional genes is because of the higher rates of evolutionary divergence in those genes relative to the core housekeeping 16S gene.
