### ISSUE TITLE
Accuracy of data when changing parameters in DADA2

### ISSUE THREAD

**Issue by moladi** [benjjneb/dada2#1630]
Hello,

I wanted to know your expert opinion on something. The quality of the R2 reads of my Illumina sequences (16S V3V4) are not good, and the basic parameters in DADA2 would result in a 90% loss of the reads after quality trimming and merging. When I change the parameters to maxEE = c(2, 5) and minOverlap = 10, only 50% of the reads are discarded (which is good enough for me). Now I was wondering if my data with these parameters are accurate enough (especially in the peer review process)?

Thanks & best regards!

**Comment by benjjneb** [comment]
In the presence of very poor quality reverse reads, my recommendation is to just drop the reverse reads and work with the forward reads alone.
