### ISSUE TITLE
Reduced Representation Sequencing or GBS

### ISSUE THREAD

**Issue by Pablo-UY** [benjjneb/dada2#1631]
Dear Ben,
I am new at working with these sequences.
Can I use dada2 to analyze them? 

If yes, these sequences are part of genomes so, wich database should be better to use?
Thank you,
Pablo.

**Comment by benjjneb** [comment]
DADA2 is not intended for use with that kind of data.

**Comment by Pablo-UY** [comment]
Excellent. Thank you!
Do you recommend me any other for this?

**Comment by benjjneb** [comment]
I don't have experience with that data type, so no recommendation.
