### ISSUE TITLE
Should I agglomerate taxa of the same type?

### ISSUE THREAD

**Issue by michaelaohare** [benjjneb/dada2#1632]
Hi Ben!

I am in the process of generating alpha diversity values using 16S (V4) data from the human gut microbiome. In the DADA2 tutorial (1.16) it doesn't mention agglomerating taxa of the same type. However, from what I have heard, in a previous version of this pipeline, there used to be mention of agglomeration as follows:

```
ps.genus <- tax_glom(ps, taxrank="Genus")

taxa_names(ps.genus) = c(tax_table(ps.genus)[,6])

sort(sample_sums(ps.genus))
```

Do you have any advice as to why one would or wouldn't agglomerate taxa?

Thanks in advance!

**Comment by benjjneb** [comment]
> Do you have any advice as to why one would or wouldn't agglomerate taxa?

Depends on the question. In general, robust alpha-diversity differences should be visible across a range of levels, at least from ASV to genus. So as long as you report the level your are working at, you should be OK.
