### ISSUE TITLE
ITS workflow using cutadapt to trim primers?

### ISSUE THREAD

**Issue by marwa38** [benjjneb/dada2#1634]
Hello :)

I was wondering if you have tried to trim primers that have N and H nucleotides (V3-V4) before using this ITS workflow?
I found that V3_V4 primers were removed without the need to change N and H to wildcards as qiime2 do. Just as a reassurance, do you think that by default, cutadapt understands what N and H nucleotide means? 
https://benjjneb.github.io/dada2/ITS_workflow.html

Thank you 
M

**Comment by benjjneb** [comment]
Yes, this is described in the cutadapt documentation: https://cutadapt.readthedocs.io/en/stable/guide.html#specifying-adapter-sequences
