### ISSUE TITLE
Error in .Call2("new_XStringSet_from_CHARACTER", class(x0), elementType(x0), :  key 50 (char '2') not in lookup table

### ISSUE THREAD

**Issue by alaakhalil2** [benjjneb/dada2#1636]
I am analyzing my data with dada2, I used 16S V3-V4 regions. the problem is am getting" Error in .Call2("new_XStringSet_from_CHARACTER", class(x0), elementType(x0),  : 
  key 50 (char '2') not in the lookup table" when I try to add species 
taxa <- addSpecies(seqnochim,"C:/Users/alaak/Downloads/silva_species_assignment_v138.1.fa.gz"), however when I assigned taxonomy 
 taxa <- assignTaxonomy(seqnochim,"C:/Users/alaak/Downloads/silva_nr99_v138.1_wSpecies_train_set.fa.gz", multithread=TRUE
it was fine and had no errors . if the noncheimeric sequence table has any problem it shouldn't work from the start I tried another data set it showed me the same error 
i have no clue what to do

**Comment by benjjneb** [comment]
What is the result if you run `table(dada2:::C_isACGT(getSequences(seqnochim)))`?

**Comment by alaakhalil2** [comment]
TRUE 
6569
