### ISSUE TITLE
Can barcodes of different length affect the error model construction?

### ISSUE THREAD

**Issue by gabrielet** [benjjneb/dada2#1637]
Say, I have two sequences with barcodes of different length:

**barcodeone**AACTCGCCTCATCAG
**barcodeoneb**TTGCTCATCGACTCAG

What I would do is removing both **barcodeone** and **barcodeoneb**, then proceed with the ASVs retrieval. What happens, though, when DADA2 aligns the sequences, and then computes the error model?

I expect that, from a sequencer machine perspective, the first two useful bases (which are actually in two different positions, i.e. 11 and 12 in the original reads) should have different errors so...is comparing them meaningful?

If I got it right, I believe this issue is taken care of by DADA2 because (from DADA2 paper):

> DADA2 models errors as occurring independently within a read and independently between reads.

Am I correct in my understanding or should I do some more preprocessing, if I have barcodes with different length?

**Comment by benjjneb** [comment]
If you have removed both barcodes from your reads, and thus all reads start at the same biological position, then you are in good shape. You've hit on exactly the reason, the DADA2 error model does not include read position -- so whether a nucletotide is at position 110 or 111 in the read is irrelevant to DADA2. What is critical is that all reads start at the same biological position. Hence the importance of pre-processing data that uses mixed-length primers to remove them appropriately.

**Comment by gabrielet** [comment]
alright! i assume that by biological position you mean, for example, either 16s/ITS1/ITS2 or "whatever is found, exactly after the barcode".

**Comment by benjjneb** [comment]
"whatever is found, exactly after the barcode" should be the same "position 1" in the genetic loci you are sequencing. If that is the case, and you've removed the barcodes, you're in good shape.
