### ISSUE TITLE
Unconventional quality score dip in the mid-range

### ISSUE THREAD

**Issue by nuorenarra** [benjjneb/dada2#1639]
Hello! I am working with some 16S rRNA V4-V5 reads (250 bp F and 250 bp R reads between primers 515F and 926R), sequenced with Illumina NovaSeq using S4 chemistry. Running these through DADA2, I noticesd something unusual: Some samples have quality score profiles that dip around 50-100 bp and then go back up, like top righth and bottom left cases in this plot:

<img width="961" alt="quality_plots" src="https://user-images.githubusercontent.com/77113596/202698022-4bdd07a6-44ab-42a8-aef4-f88170e7c8bf.png">

I have never seen anything like this, and wonder why this would happen? I am trying to solve this with the sequencing facility, but wanted to check also if you have ever seen this kind of pattern or have any guesses of why it might arise?

I am using DADA 1.26,  on R 4.2.0, with an M1 chip Mac OS Monterey.

**Comment by benjjneb** [comment]
I don't know why this happens, but the nature of the DADA2 error model that accounts for quality scores makes it pretty robust to these types of unusual quality drops.

**Comment by nuorenarra** [comment]
Thank you. One more question: Does this drop need to be in the region of primer overlap for the error model to realistically account for it? 

These reads are 250 bp long F and R reads covering a region approx 370 bp long, so there is 130 bp overlap in the rear-end of both, which to me seems like may be outside the region where this quality drop happens

**Comment by benjjneb** [comment]
> Does this drop need to be in the region of primer overlap for the error model to realistically account for it?

No. The error model does not know about the overlap or non-overlap regions.

**Comment by nuorenarra** [comment]
Ok thanks again! I hope from here onwards "everything is reasonable so I can proceed with confidence". 

I will attach the error plot here as well as a reference for anyone else having similar issues. It also shows some pretty nonlinear deviations from the fit. No need to reply if this does not bring any new perspective on the issue.

<img width="723" alt="errorrates-wytcon" src="https://user-images.githubusercontent.com/77113596/203625075-9d121e65-2727-4131-b3c5-ef1b9fb76f8f.png">
