### ISSUE TITLE
plotQualityProfile ggplot2 missing values ('geom_tile()')

### ISSUE THREAD

**Issue by delavegapab** [benjjneb/dada2#1642]
While following the tutorial, I got to the point of visualizing the quality profiles of my reads and got the following message:

Warning messages:
1: The `<scale>` argument of `guides()` cannot be `FALSE`. Use "none" instead as of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the dada2 package.
  Please report the issue at <https://github.com/benjjneb/dada2/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
2: Removed 407 rows containing missing values (`geom_tile()`). 

Not sure what the solution would be, any help would be greatly appreciated.

**Comment by benjjneb** [comment]
That warning is OK, we should fix it but it won't stop any of your plots.

**Comment by delavegapab** [comment]
Thank you so much for your help! I really appreciate all you have done for
the scientific community, as well as your prompt response to this matter.

Kind regards,

Pablo
