### ISSUE TITLE
Variable length reads - ASV abundance question

### ISSUE THREAD

**Issue by louellette** [benjjneb/dada2#1643]
I have short reads - let's say like this:
unique:
CGTCCATCAGGTCAACGTTCTTGCGGTCAACCTCGACGAACTCGTCGCGCATACGG
unique:
CGTCCATCAGGTCAACGTTCTTGCGGTCAACCTCGACGAACTCGTCGCGCAGTATT
sequence matches the first of both uniques: 
CGTCCATCAGGTCAACGTTCTTGCGGTCAACCTCGACGAACTCGTC----------
sequence matches the first of both uniques: 
CGTCCATCAGGTCAACGTTCTTGCGGTCAACCTCGA--------------------

dada2 seems to be collapsing the abundance into the shortest read. What I would like to do is divide the abundance of the shorter sequences into the two unique longer sequences based on their relative abundance. 

Can you suggest something?

**Comment by louellette** [comment]
Thanks for the reply. Another question: Can I extract the denoised reads from dada2?

**Comment by benjjneb** [comment]
1. can you be more specific? Extract to what format? And by "denoised reads" you mean just the sequences, or the sequences and associated abundances?

2. Yes. A workaround when your priors are "long" is to create all shortened versions of that prior you want to include.

**Comment by louellette** [comment]
By 'denoised reads' I mean the error-corrected full-length dereplicated read sequences. My goal is to be able to accomplish dividing the abundance of the shorter sequences into the longer sequences:
unique (dereplicated read only):
CGTCCATCAGGTCAACGTTCTTGCGGTCAACCTCGACGAACTCGTCGCGCATACGG
unique (dereplicated read only):
CGTCCATCAGGTCAACGTTCTTGCGGTCAACCTCGACGAACTCGTCGCGCAGTATT
sequence matches the first of both unique (dereplicated read only):
CGTCCATCAGGTCAACGTTCTTGCGGTCAACCTCGACGAACTCGTC----------
sequence matches the first of both unique (ASV):
CGTCCATCAGGTCAACGTTCTTGCGGTCAACCTCGA--------------------

I've figured out how to map the ASVs back to the dereplicated reads, so I could 'make' an ASV out of the longer dereplicated read but those are not error corrected. I hope this makes sense. Thank you so much in advance.

**Comment by benjjneb** [comment]
I'm a bit confused by your last comment. On first read I thought you had things figures out, but on a re-read I'm not sure. Can you clarify if you still have a question here or not?

**Comment by louellette** [comment]
I do still have a question, thanks for your patience. I would like to get the error-corrected dereplicated reads so that I can divide the shorter ASVs up into the 'error-corrected' longer dereplicated reads, essentially 'making' the 'error corrected' longer dereplicated reads an ASV. My next step is classifying the ASVs and I would like to use the longer 'error-corrected' longer dereplicated reads to do this.

**Comment by benjjneb** [comment]
I'm still kind of confused, but what you can do is use the `$map` slots in dada-class and derep-class objects to go back to the dereplicated or raw reads.

```
drp <- derepFastq(...) # 1 sample for simplicity
drp$map # A vector of integers of length the number of reads in the sample
# The i-th value corresponds to the index of the dereplicated sequence to which the i-th read was assigned
dd <- dada(...) # 1 sample for simplicity
dd$map # A vector of integers of length the number of unique dereplicated sequences
# The j-th value corresponds to the index of the denoised ASV to which the j-th dereplicated sequence was assigned
```
