### ISSUE TITLE
Error in plotErrors

### ISSUE THREAD

**Issue by JulienTerroire** [benjjneb/dada2#1644]
Hi, 
I wanted to know what should I do with this (just starting to use R) : 

I had an error when I was using these commands :
errF <- learnErrors(filtFs, multithread=TRUE)
errR <- learnErrors(filtRs, multithread=TRUE) 
 -> Error in derepFastq(fls[[i]], qualityType = qualityType) : Not all provided files exist.

I used these commands to solve the problem : 
exists <- file.exists(filtFs)
errF <- derepFastq(filtFs[exists], verbose=TRUE)
errR <- derepFastq(filtRs[exists], verbose=TRUE)
names(errF) <- sample.names[exists]
names(errR) <- sample.names[exists]

So with this I should be able to plot the Error graphs but with this command, a new error occurs : 
plotErrors(errF, nominalQ=TRUE)
->  Error in plotErrors(errF, nominalQ = TRUE) : 
Non-null observed and/or estimated error rates (dq$trans or dq$err_out) must be provided.

I don't really understand where is the probleme here... Can you help me please?``

**Comment by benjjneb** [comment]
> errF <- derepFastq(filtFs[exists], verbose=TRUE)

Here you are skippin ga step. You are assigning the output of `derepFastq` to `errF`. You should be running the `learnErrors` command to assign to `errF`.
