### ISSUE TITLE
16S/18S/ITS

### ISSUE THREAD

**Issue by agnieszka6552** [benjjneb/dada2#1647]
I have a data from 16S/18S/ITS Amplicon Sequencing. Can I use dada2 for analyzing such data? Should I divide them into 16S, 18S and ITS subsets as the reads have different lengths?

**Comment by benjjneb** [comment]
Yes it can. If you have a way to divide things out before DADA2 that's ideal. If you don't, DADA2 will still work, but you'll probably have to be more delibrate about how you do some downstream steps like taxonomic ID.
