### ISSUE TITLE
Starting analysis in dada2 at the taxonomy assignment step

### ISSUE THREAD

**Issue by edersonjesus** [benjjneb/dada2#1648]
Hello! 
I am helping a friend to analyze some 16S rRNA gene and ITS sequence data, and I would like to use dada2 and phyloseq. The point that the company that provided the service gave him the merged sequences in fasta files only, not the fastaq files that we use form scratch in dada2. Is there a way to import the fasta file into R and start the analysis with dada2 at the taxonomy assignment step?

Thank you,

Ederson

**Comment by benjjneb** [comment]
Yes. You can read each fasta file in dereplicated format, then construct a sequence table from those objects. If `fn` is a list of filepaths, then something like:

```{r}
unqs <- lapply(fn, getUniques)
seqtab <- makeSequenceTable(unqs)
dim(seqtab) # Sanity check, number of rows should equal the number of samples
# And then proceed in the tutorial from the taxonomy assignment step
```

**Comment by benjjneb** [comment]
What I see in your comment is some confusion about how to use the `lapply` command, but not anything about the dada2 R package necessarily.

To test if there is any dada2/fastq-import issue, I would suggest creating a script that tries to investigate one sample fastq. Leave aside all the `lapply` commands.
