### ISSUE TITLE
I can't install 'dada2' using BiocManager 

### ISSUE THREAD

**Issue by SLJUNG0120** [benjjneb/dada2#1649]
I've been struggling with installing dada2 for a long time. The R version is 4.2.2. In the Windows system, it was easy to install dada2 through BiocManager, but an error continues in the Ubuntu 18.04 system. It is not possible to install the package directly, and the error message, dependency 'shortread' is not available for package 'dada2', appears.

**Comment by benjjneb** [comment]
If there are dependencies missing, then the best approach is to try to install those dependencies, then retry installing dada2. ShortRead is also a bioconductor package.
