### ISSUE TITLE
Unable to assign taxonomy from sequence table

### ISSUE THREAD

**Issue by tataridiss** [benjjneb/dada2#1650]
Hi, 
I'm trying to use the _assignTaxonomy_ function on a sequence matrix with the sample ID as row names, the ASV sequences as column names and the counts as values. As a reference I'm using the SILVA training set. This is the code I'm using:

`taxtab <- assignTaxonomy(seqtab, "silva_nr_v138_train_set.fa.gz")`

Two problems occur: taxtab turns up as a function in the environment (I assume it should me a matrix or similar) and I get this error: 

`Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'reverseComplement': key 48 (char '0') not in lookup table
In addition: Warning message:
In assignTaxonomy(seqtab, "silva_nr_v138_train_set.fa.gz") :
  Some sequences were shorter than 50 nts and will not receive a taxonomic classification.`

My end goal is to construct a phylogenetic tree with DECIPHER after this. 

Any suggestions are very welcome!

**Comment by benjjneb** [comment]
What is the result of the following:

```
sq <- getSequences(seqtab)
head(sq)
table(nchar(sq))
```

**Comment by tataridiss** [comment]
This is the result: 

<img width="1237" alt="Bildschirmfoto 2022-12-04 um 13 21 46" src="https://user-images.githubusercontent.com/119605016/205490116-457184ea-ae84-4a6c-bc53-d2b50834769b.png">

**Comment by AnyiHu** [comment]
Hi,

I got a similar issue. Here are the results:

> sq <- getSequences(seqtab) > head(sq) [1] "ATACGGAGGGTGCAAGCGTTGTCCGGATTTATTGGGTTTAAAGGGTGCGCAGGTGGTTTATTAAGTCAGTGGTGAAAGACGGTCGCTCAACGATTGCAGTGCCATTGAAACTGGTAGACTTGAGTAAAGTAGAGGTGGGCGGAATTGATAGTGTAGCGGTGAAATGCATAGATATTATCAAGAACTCCAATTGCGTAGGCAGCTCACTTGGCTTTTACTGACACTCATGCACGAAAGTGTGGGTATCAAACAGGATTAGATACCCTGGTAGTCCACACTGTAAACGATGATAACTAGGTGTCGGCCGAATCTGGTCGGTGCCACAGCGAAAGCGTTAAGTTATCCACCTGGGGAGTACGCCGGCAACGGTG"    
[2] "ATACGGGAGTGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGCGTCCGCAGGCGGCCTTTTAAGTCTGTCGTTAAAGCGTGGAGCTTAACTCCATTTAAGCGATGGAAACTGGAAGGCTAGAGTGTGGTAGGGGCAGAGGGAATTCCCGGTGTAGCGGTGAAATGCGTAGATATCGGGAAGAACACCAGTGGCGAAGGCGCTCTGCTGGGCCATAACTGACGCTCATGGACGAAAGCCAGGGGAGCGAAAGGGATTAGATACCCCTGTAGTCCTGGCCGTAAACGATGAACACTAGGTGTCGGGGGAATCGACCCCCTCGGTGTCGTAGCCAACGCGTTAAGTGTTCCGCCTGGGGAGTACGCACGCAAGTGTG"
[3] "ATACATAGGGTGCAAGCGTTGTCCGGAATTATTGGGCGTAAAGAGCTCGTAGGTGGTTCGATACGTCGGATGTGAAAATCAGGGGCTCAACCCCTGACCTGCATCCGATACGGTCGAGCTAGAGTTTGGTAGGGGAGACTGGAATTCCTGGTGTAGCGGTGGAATGCGCAGATATCAGGAGGAACACCGATGGCGAAGGCAGGTCTCTGGGCCAATACTGACACTGAGGAGCGAAAGCGTGGGGAGCGAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGGTGGGCGCTAGTTGTGCGAACCTTCCACGGTTTGTGCGACGCAGCTAACGCATTAAGCGCCCCGCCTGGGGAGTACGATCGCAAGATTA"
[4] "ATACGTAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGTGCGCAGGCGGTGATGTAAGACAGAGGTGAAATCCCCGGGCTCAACCTGGGAACTGCCTTTGTGACTGCATCGCTGGAGTACGGCAGAGGGGGATGGAATTCCGCGTGTAGCAGTGAAATGCGTAGATATGCGGAGGAACACCGATGGCGAAGGCAATCCCCTGGGCCTGTACTGACGCTCATGCACGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCCTAAACGATGTCAACTGGTTGTTGGGTCTTCACTGACTCAGTAACGAAGCTAACGCGTGAAGTTGACCGCCTGGGGAGTACGGCCGCAAGGTTG"  
[5] "ATACGTAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGTGCGCAGGCGGTGATGTAAGACAGGCGTGAAATCCCCGGGCTCAACCTGGGAATGGCGCTTGTGACTGCATCGCTGGAGTGCGGCAGAGGGGGATGGAATTCCGCGTGTAGCAGTGAAATGCGTAGATATGCGGAGGAACACCGATGGCGAAGGCAATCCCCTGGGCCTGCACTGACGCTCATGCACGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCCTAAACGATGTCAACTGGTTGTTGGGTCTTAGCTGACTCAGTAACGAAGCTAACGCGTGAAGTTGACCGCCTGGGGAGTACGGCCGCAAGGTTG"  
[6] "ATACATAGGGTGCAAGCGTTGTCCGGAATTATTGGGCGTAAAGAGCTCGTAGGTCGTTTGTTACGTCGGATGTGAAAACCTGAGGCTCAACCTCAGGCCTGCATTCGATACGGGCAAACTAGAGTTTGGTAGGGGAGACTGGAATTCCTGGTGTAGCGGTGGAATGCGCAGATATCAGGAGGAACACCAATGGCGAAGGCAGGTCTCTGGGCCAATACTGACACTGAGGAGCGAAAGTCTGGGGAGCGAACAGGATTAGATACCCTGGTAGTCCAGACCGTAAACGGTGGGCACTAGTTGTGGGAACCTTCCACGGTTTCTGCGACGCAGCTAACGCATTAAGTGCCCCGCCTGGGGAGTACGATCGCAAGATTA" 

> table(nchar(sq))  220    221    222    223    224    225    226    227    228    229    230    231 
    33      9     22     11     31     15     23     12     16     12     11     18 
   232    233    234    235    236    237    238    239    240    241    242    243 
    13     11      6     10      8      2     13     29      7     11      4     17 
   244    245    246    247    248    249    250    251    252    253    254    255 
    10     11      4     13     21     17     13     22      9      8     16     43 
   256    257    258    259    260    261    262    263    264    265    266    267 
     7     21     21     28     20     10     24     16     18     13     28     25 
   268    269    270    271    272    273    274    275    276    277    278    279 
    69     33     36     24     39     77     39     57    167     62    116     99 
   280    281    282    283    284    285    286    287    288    289    290    291 
    44     56     40     98     62    150     66     51     74     80     49    162 
   292    293    294    295    296    297    298    299    300    301    302    303 
   190    194    321    228    337     80    123     46     82     65     78    120 
   304    305    306    307    308    309    310    311    312    313    314    315 
    72    104     93    123     94    101    181    107    115     80    189    149 
   316    317    318    319    320    321    322    323    324    325    326    327 
   173    363     74     64     68     93    113    128    189    213    240    149 
   328    329    330    331    332    333    334    335    336    337    338    339 
   233    108     91     87     71     99    112     95    161    114     82    101 
   340    341    342    343    344    345    346    347    348    349    350    351 
   171    114     74    158     94    111    126     95    113    245    161    201 
   352    353    354    355    356    357    358    359    360    361    362    363 
   144    152    227    197    125    125    141    119    179    266    250    324 
   364    365    366    367    368    369    370    371    372    373    374    375 
  1305   2531  12924  21623   8352 105910  19661 374480  64345 405633 241981 630603 
   376    377    378    379    380    381    382    383    384    385    386    387 
121961  21117  11175  19255   5203   5144   5007   1766    704    629    840   1075 
   388    389    390    391    392    393    394    395    396    397    398 
   647    606   1233    771    911   1332   1682   1839   2047   2379   2266

**Comment by benjjneb** [comment]
@tataridiss 

Something isn't adding up. The length distribution of your ASVs in the sequence table has a minimum of 221, yet you are getting a warning about there being sequences of <50 nts when running `assignTaxonomy`. Can you double-check that the same objects are being used here with the following:

```
sq <- getSequences(seqtab)
summary(nchar(sq)) # Is minimum still 221?
taxtab <- assignTaxonomy(sq, "silva_nr_v138_train_set.fa.gz")
```

Do you still get the minimum length warning, and the unexpected key error?

**Comment by benjjneb** [comment]
@AnyiHu 

Please provide a more complete description of the command you are running, and the exact error/warning messages being produced.

**Comment by AnyiHu** [comment]
@benjjneb 

Here are the error/warning messages and the commands we ran. Thanks.

![微信图片_20221213224018](https://user-images.githubusercontent.com/57850945/207363056-a955d0b3-2d17-4955-9fb4-77dbe1626d05.jpg)


![微信图片_202212132238382](https://user-images.githubusercontent.com/57850945/207362721-eaa919a9-ea7c-4c86-a485-ec115b16872b.jpg)


![微信图片_20221213223838](https://user-images.githubusercontent.com/57850945/207362607-4efd3a34-e6e0-48b5-ac54-f9c3e14818e4.jpg)
![微信图片_202212132238381](https://user-images.githubusercontent.com/57850945/207362712-1190e7d8-7c04-40c1-85a1-d8f2e69fa781.jpg)

**Comment by benjjneb** [comment]
@AnyiHu

You have a very large (>3M) number of ASVs in your sequence table. If you subset this down say to 100k ASVs, does `assignTaxonomy` work?
