### ISSUE TITLE
How to draw the error bar to plot_richness and plot_bar when using phyloseq package?

### ISSUE THREAD

**Issue by EnvrionmentalEngineer** [benjjneb/dada2#1653]
Hi, I have already successfully run the DADA2 pipeline and prepare the phyloseq dataset, my metadata contains 5 samples, each sample has three replications, after I use the plot_richness() and plot_bar() to draw the plot, I found I cannot show the mean value with errorbar, like only show the sum of the ASV abundance in barplot, so I guess the phyloseq package maynot able to do that, is there any convinent way to achieve that?

**Comment by EnvrionmentalEngineer** [comment]
> Hi, I have already successfully run the DADA2 pipeline and prepare the phyloseq dataset, my metadata contains 5 samples, each sample has three replications, after I use the plot_richness() and plot_bar() to draw the plot, I found I cannot show the mean value with errorbar, like only show the sum of the ASV abundance in barplot, so I guess the phyloseq package maynot able to do that, is there any convinent way to achieve that?

@joey711 @benjjneb

**Comment by EnvrionmentalEngineer** [comment]
> Hi, I have already successfully run the DADA2 pipeline and prepare the phyloseq dataset, my metadata contains 5 samples, each sample has three replications, after I use the plot_richness() and plot_bar() to draw the plot, I found I cannot show the mean value with errorbar, like only show the sum of the ASV abundance in barplot, so I guess the phyloseq package maynot able to do that, is there any convinent way to achieve that?

**Comment by EnvrionmentalEngineer** [comment]
> Hi, I have already successfully run the DADA2 pipeline and prepare the phyloseq dataset, my metadata contains 5 samples, each sample has three replications, after I use the plot_richness() and plot_bar() to draw the plot, I found I cannot show the mean value with errorbar, like only show the sum of the ASV abundance in barplot, so I guess the phyloseq package maynot able to do that, is there any convinent way to achieve that?

@joey711 @benjjneb

**Comment by benjjneb** [comment]
This seems like an issue with the phyloseq package, not the dada2 package, so I am closing it here.

You could try reposting on the phyloseq github issues: https://github.com/joey711/phyloseq/issues
