### ISSUE TITLE
rare ASVs in specific runs

### ISSUE THREAD

**Issue by wsteenhu** [benjjneb/dada2#1658]
I am currently analysing a respiratory microbiome study in which we compare healthy controls vs children with an RSV-infection, as well as recovery samples (MiSeq 2x250; V4).
The data were sequenced across 5 MiSeq-runs.
Strikingly, I find that some ASVs only occur in specific runs. These ASVs are strikingly frequent and occur across study sites and study groups (healthy controls/infection/recovery. The ASVs are absent in MiSeq-PCR blanks and isolation controls, making laboratory contamination less likely.
The ASVs include biologically plausible species like Corynebacterium and Dolosigranulum. Please see the figure below (numbers right correspond with MiSeq runs).

![Schermafbeelding 2022-12-12 om 15 24 37](https://user-images.githubusercontent.com/29248372/207069705-b1b617b6-5ff5-4955-846e-a3f2581dc69b.png)

These ASVs differ only one nucleotide from their most abundant counterpart.
I can't find a plausible explanation for these findings. Could this be introduced bioinformatically? Could it be these ASVs are non-denoised equivalents of the most abundant ASV (for run 43/46 specifically?). If this would be DADA2-related, is there a way to verify and can this be adjusted post-processing?

**Comment by benjjneb** [comment]
Thanks for the update!
