### ISSUE TITLE
Error with derepFastq

### ISSUE THREAD

**Issue by ChristinaOvergaard** [benjjneb/dada2#1659]
Hi,

I am trying to dereplicate one sample containing 1 250 905 CCS reads with length between 3000-6000 bp (most around 4500bp). 
The reads have been oriented, trimmed for primers and quality filtered.
I am using the following command:
`drp <- derepFastq(sample.fastq, qualityType = "FastqQuality", verbose=TRUE)`

However, I get the following error message
`Error in asMethod(object) : long vectors not supported yet: memory.c:3887`

Any help would be really appreciated! 

Best regards,
Christina

**Comment by benjjneb** [comment]
Unfortunately, my suspicion is that you are running into some fundamental memory limitations in the plumbing underlying some of the objets the dada2 R package creates, and for which we have no current solutions.

I guess one thing to try would be to subsample down, just to establish that things are working with a smaller subset of the sample. And I'd be interested to see rough numbers on where this memory issue crops up.

**Comment by ChristinaOvergaard** [comment]
Hi again,

Sorry for the late reply.
I tried to subset my data and the highest amount of sequences that I was able to dereplicate was 360.000 reads. 
However, I tried to set the n argument to n = 100000 and that seemed to fix my problem. I was able to dereplicate all my 1.2 mio reads.

**Comment by benjjneb** [comment]
> However, I tried to set the n argument to n = 100000 and that seemed to fix my problem. I was able to dereplicate all my 1.2 mio reads.

That's great. I don't quite understand why that would work though. Just for reference (in case a similar issue comes up), can you copy the exact command you executed that worked for your 1.2M reads?

**Comment by cjfields** [comment]
I am seeing the same issue (though via `learnErrors`, which is running `derepFastq` internally):

```
> err <- learnErrors(filts, multithread=4, verbose =1)
Error in asMethod(object) : long vectors not supported yet: memory.c:3846
> filts <- derepFastq(filts, verbose = TRUE)
Dereplicating sequence entries in Fastq file: ./Heavy_Sorted2_T1.R1.filtered.fastq.gz
Error in asMethod(object) : long vectors not supported yet: memory.c:3846
```

But when I set `n` within `derepFastq`, it works, though with a (probably minor and unrelated) warning:

```
> filts <- derepFastq(filts, verbose = TRUE, n=100000)
Dereplicating sequence entries in Fastq file: ./Heavy_Sorted2_T1.R1.filtered.fastq.gz
......................Encountered 325365 unique sequences from 2253025 total sequences read.
Warning messages:
1: closing unused connection 4 (./Heavy_Sorted2_T1.R1.filtered.fastq.gz)
2: closing unused connection 3 (./Heavy_Sorted2_T1.R1.filtered.fastq.gz)
```

The library in question here is an amplified library with lots of modifications so is a bit atypical for DADA2, we could always try a simple dereplication tool (`vsearch` or similar).  But we'd like something that can denoise if possible.

**Comment by cjfields** [comment]
> ...But we'd like something that can denoise if possible

And TIL that `vsearch` does implement the UNOISE3 algorithm, which I may try.
