### ISSUE TITLE
Computational requirements of assignTaxonomy() and addSpecies()

### ISSUE THREAD

**Issue by jtvanleuven** [benjjneb/dada2#166]
I'm trying to add species classification to a taxonomy table, but addSpecies() is using quite a bit of ram (~80gb) and has been running for several days. Do you have estimates for how long and how much resources the assignTaxonomy() and addSpecies() functions require? 
My command;
taxtab.species <- addSpecies(taxtab, "../rdp_species_assignment_14.fa", verbose=TRUE)

My taxtab table has 141,140 sequences in it.

Thank you. 
-james

**Comment by benjjneb** [comment]
Right now the implementation of `addSpecies` leaves much to be desired performance-wise (`assignTaxonomy` scales more robustly). I have never tried to use it on as many sequences as you are attempting to classify.

That is a lot of sequences in a final table in my experience, at least for human data. Have chimeras been removed yet?

**Comment by jtvanleuven** [comment]
Yes, chimeras were removed. The samples are soil from many locations. I did notice that assignTaxonomy() ran much faster. Took a fraction of the time and less ram. 

I just checked and the job finished, although, it doesn't look particularly successful;
775 out of 141140 were assigned to the species level.
Of which 739 had genera consistent with the input table.


Thank you for your input. Very much appreciated.

**Comment by jtvanleuven** [comment]
45217/141140 classified to Genus
60750/141140 classified to Family
79278/141140 classified to Order
97710/141140 classified to Class
121677/141140 classified to Phylum

**Comment by benjjneb** [comment]
Those classification numbers sounds about right.

`assignSpecies` only assigns species in which there is an exact match to the reference database. That's usually 1/3-1/2 of the more frequent stuff in human microbiome data, but is going to be much, much lower for soil data.

**Comment by jtvanleuven** [comment]
Okay. Thanks.
