### ISSUE TITLE
Issue loading dada2

### ISSUE THREAD

**Issue by jspychalla** [benjjneb/dada2#1664]
Hi I get the following error when I try to load dada2

library(dada2)
Loading required package: Rcpp
Error: package or namespace load failed for ‘dada2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/dada2/libs/dada2.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/dada2/libs/dada2.so, 6): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/dada2/libs/dada2.so (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib 

I have R 4.2.2 and I have dada2 1.26.0 

Would uninstalling and reinstalling the dada2 package help with this? 

Thank you for your time

**Comment by jspychalla** [comment]
PS I was able to run the dada2 successfully a few months ago. I think I have updated R since then I don't know what else could be causing this issue

**Comment by benjjneb** [comment]
What operating system are you using?

**Comment by jspychalla** [comment]
Never mind I was able to install and load it using the install_github() from devtools
