### ISSUE TITLE
Many reads lost at filterAndTrim step - any work around 'N' bases in sequences?

### ISSUE THREAD

**Issue by hwipf** [benjjneb/dada2#1665]
Hello,

I'm loosing about ~96% of my reads for each sample at the filterAndTrim step, and I have pinpointed that it is due to the presence of at least 1 N in many reads:

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(149,20), _**maxN=0**_, maxEE=c(2,2), truncQ=1, rm.phix=TRUE, compress=TRUE, verbose=TRUE, multithread=TRUE,matchIDs=FALSE)
                             reads.in.    reads.out
sample1.fastq     24817        862
sample2.fastq    40762        1457

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(149,20), _**maxN=1**_, maxEE=c(2,2), truncQ=1, rm.phix=TRUE, compress=TRUE, verbose=TRUE, multithread=TRUE,matchIDs=FALSE)
                             reads.in.    reads.out
sample1.fastq     24817        19185
sample2.fastq    40762        31082

Would anyone have any advice on how to still preserve more reads (possibly by deleting the 1N in sequences? code for this would be greatly appreciated!)

Thank you for any and all help.
-Edi

**Comment by benjjneb** [comment]
All Ns must be removed at the filtering/trimming stage. The subsequent functions don't handle Ns in the raw sequences.

If the Ns are mostly all happening at a specific position in the reads (something I have seen before), then trimming away that portion can solve this issue. If the Ns are in almost all reads and scattered in position, you probably need to use a different method to process your data.
