### ISSUE TITLE
Unable to install Dada2 package 

### ISSUE THREAD

**Issue by RosaCatherina** [benjjneb/dada2#1667]
I am experiencing problems with installing the Dada2 package and I think it has something to do with my directory/path.. not an expert on this, but hope someone can help me! 
I have added all the relevant information in the section underneath. 

#########I have downloaded the Dada2 package with 

if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install(version = "3.16")

BiocManager::install("dada2", version = "3.16")
library("dada2")
library(dada2); packageVersion("dada2")

in R studio version 
Version 2022.12.0+353 (2022.12.0+353)
R 4.2.2 

#######During installation:
> BiocManager::install("dada2", version = "3.16")
'getOption("repos")' replaces Bioconductor standard repositories, see
'?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.16 (BiocManager 1.30.19), R 4.2.2 (2022-10-31)
Installing package(s) 'dada2'
also installing the dependencies ‘formatR’, ‘matrixStats’, ‘colorspace’, ‘utf8’, ‘lambda.r’, ‘futile.options’, ‘MatrixGenerics’, ‘DelayedArray’, ‘deldir’, ‘RcppEigen’, ‘RCurl’, ‘GenomeInfoDbData’, ‘farver’, ‘labeling’, ‘munsell’, ‘R6’, ‘RColorBrewer’, ‘viridisLite’, ‘fansi’, ‘magrittr’, ‘pillar’, ‘pkgconfig’, ‘stringi’, ‘futile.logger’, ‘snow’, ‘BH’, ‘cpp11’, ‘bitops’, ‘SummarizedExperiment’, ‘png’, ‘jpeg’, ‘interp’, ‘S4Vectors’, ‘GenomeInfoDb’, ‘crayon’, ‘cli’, ‘glue’, ‘gtable’, ‘isoband’, ‘lifecycle’, ‘rlang’, ‘scales’, ‘tibble’, ‘vctrs’, ‘withr’, ‘plyr’, ‘stringr’, ‘BiocParallel’, ‘Rsamtools’, ‘GenomicAlignments’, ‘Biobase’, ‘GenomicRanges’, ‘hwriter’, ‘zlibbioc’, ‘latticeExtra’, ‘Rhtslib’, ‘Rcpp’, ‘Biostrings’, ‘ggplot2’, ‘reshape2’, ‘ShortRead’, ‘RcppParallel’, ‘IRanges’, ‘XVector’, ‘BiocGenerics’

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/formatR_1.13.tgz'
Content type 'application/x-gzip' length 150244 bytes (146 KB)
==================================================
downloaded 146 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/matrixStats_0.63.0.tgz'
Content type 'application/x-gzip' length 578671 bytes (565 KB)
==================================================
downloaded 565 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/colorspace_2.0-3.tgz'
Content type 'application/x-gzip' length 2622583 bytes (2.5 MB)
==================================================
downloaded 2.5 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/utf8_1.2.2.tgz'
Content type 'application/x-gzip' length 209238 bytes (204 KB)
==================================================
downloaded 204 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/lambda.r_1.2.4.tgz'
Content type 'application/x-gzip' length 109402 bytes (106 KB)
==================================================
downloaded 106 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/futile.options_1.0.1.tgz'
Content type 'application/x-gzip' length 18019 bytes (17 KB)
==================================================
downloaded 17 KB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/MatrixGenerics_1.10.0.tgz'
Content type 'application/x-gzip' length 312365 bytes (305 KB)
==================================================
downloaded 305 KB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/DelayedArray_0.24.0.tgz'
Content type 'application/x-gzip' length 2652665 bytes (2.5 MB)
==================================================
downloaded 2.5 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/deldir_1.0-6.tgz'
Content type 'application/x-gzip' length 307156 bytes (299 KB)
==================================================
downloaded 299 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/RcppEigen_0.3.3.9.3.tgz'
Content type 'application/x-gzip' length 4626500 bytes (4.4 MB)
==================================================
downloaded 4.4 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/RCurl_1.98-1.9.tgz'
Content type 'application/x-gzip' length 1102353 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/farver_2.1.1.tgz'
Content type 'application/x-gzip' length 1933421 bytes (1.8 MB)
==================================================
downloaded 1.8 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/labeling_0.4.2.tgz'
Content type 'application/x-gzip' length 60132 bytes (58 KB)
==================================================
downloaded 58 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/munsell_0.5.0.tgz'
Content type 'application/x-gzip' length 241653 bytes (235 KB)
==================================================
downloaded 235 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/R6_2.5.1.tgz'
Content type 'application/x-gzip' length 82518 bytes (80 KB)
==================================================
downloaded 80 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/RColorBrewer_1.1-3.tgz'
Content type 'application/x-gzip' length 52946 bytes (51 KB)
==================================================
downloaded 51 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/viridisLite_0.4.1.tgz'
Content type 'application/x-gzip' length 1297181 bytes (1.2 MB)
==================================================
downloaded 1.2 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/fansi_1.0.3.tgz'
Content type 'application/x-gzip' length 379227 bytes (370 KB)
==================================================
downloaded 370 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/magrittr_2.0.3.tgz'
Content type 'application/x-gzip' length 231251 bytes (225 KB)
==================================================
downloaded 225 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/pillar_1.8.1.tgz'
Content type 'application/x-gzip' length 676781 bytes (660 KB)
==================================================
downloaded 660 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/pkgconfig_2.0.3.tgz'
Content type 'application/x-gzip' length 17697 bytes (17 KB)
==================================================
downloaded 17 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/stringi_1.7.8.tgz'
Content type 'application/x-gzip' length 14520326 bytes (13.8 MB)
==================================================
downloaded 13.8 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/futile.logger_1.4.3.tgz'
Content type 'application/x-gzip' length 94479 bytes (92 KB)
==================================================
downloaded 92 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/snow_0.4-4.tgz'
Content type 'application/x-gzip' length 95697 bytes (93 KB)
==================================================
downloaded 93 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/BH_1.78.0-0.tgz'
Content type 'application/x-gzip' length 12844003 bytes (12.2 MB)
==================================================
downloaded 12.2 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/cpp11_0.4.3.tgz'
Content type 'application/x-gzip' length 300090 bytes (293 KB)
==================================================
downloaded 293 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/bitops_1.0-7.tgz'
Content type 'application/x-gzip' length 31222 bytes (30 KB)
==================================================
downloaded 30 KB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/SummarizedExperiment_1.28.0.tgz'
Content type 'application/x-gzip' length 2854131 bytes (2.7 MB)
==================================================
downloaded 2.7 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/png_0.1-8.tgz'
Content type 'application/x-gzip' length 388635 bytes (379 KB)
==================================================
downloaded 379 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/jpeg_0.1-10.tgz'
Content type 'application/x-gzip' length 417889 bytes (408 KB)
==================================================
downloaded 408 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/interp_1.1-3.tgz'
Content type 'application/x-gzip' length 5285830 bytes (5.0 MB)
==================================================
downloaded 5.0 MB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/S4Vectors_0.36.1.tgz'
Content type 'application/x-gzip' length 2249549 bytes (2.1 MB)
==================================================
downloaded 2.1 MB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/GenomeInfoDb_1.34.5.tgz'
Content type 'application/x-gzip' length 4053328 bytes (3.9 MB)
==================================================
downloaded 3.9 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/crayon_1.5.2.tgz'
Content type 'application/x-gzip' length 161499 bytes (157 KB)
==================================================
downloaded 157 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/cli_3.5.0.tgz'
Content type 'application/x-gzip' length 1324712 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/glue_1.6.2.tgz'
Content type 'application/x-gzip' length 154637 bytes (151 KB)
==================================================
downloaded 151 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/gtable_0.3.1.tgz'
Content type 'application/x-gzip' length 159185 bytes (155 KB)
==================================================
downloaded 155 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/isoband_0.2.7.tgz'
Content type 'application/x-gzip' length 1870161 bytes (1.8 MB)
==================================================
downloaded 1.8 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/lifecycle_1.0.3.tgz'
Content type 'application/x-gzip' length 122947 bytes (120 KB)
==================================================
downloaded 120 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/rlang_1.0.6.tgz'
Content type 'application/x-gzip' length 1825147 bytes (1.7 MB)
==================================================
downloaded 1.7 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/scales_1.2.1.tgz'
Content type 'application/x-gzip' length 610060 bytes (595 KB)
==================================================
downloaded 595 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/tibble_3.1.8.tgz'
Content type 'application/x-gzip' length 724320 bytes (707 KB)
==================================================
downloaded 707 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/vctrs_0.5.1.tgz'
Content type 'application/x-gzip' length 1844185 bytes (1.8 MB)
==================================================
downloaded 1.8 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/withr_2.5.0.tgz'
Content type 'application/x-gzip' length 229478 bytes (224 KB)
==================================================
downloaded 224 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/plyr_1.8.8.tgz'
Content type 'application/x-gzip' length 1018719 bytes (994 KB)
==================================================
downloaded 994 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/stringr_1.5.0.tgz'
Content type 'application/x-gzip' length 308752 bytes (301 KB)
==================================================
downloaded 301 KB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/BiocParallel_1.32.5.tgz'
Content type 'application/x-gzip' length 1590098 bytes (1.5 MB)
==================================================
downloaded 1.5 MB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/Rsamtools_2.14.0.tgz'
Content type 'application/x-gzip' length 4087277 bytes (3.9 MB)
==================================================
downloaded 3.9 MB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/GenomicAlignments_1.34.0.tgz'
Content type 'application/x-gzip' length 2374231 bytes (2.3 MB)
==================================================
downloaded 2.3 MB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/Biobase_2.58.0.tgz'
Content type 'application/x-gzip' length 2605757 bytes (2.5 MB)
==================================================
downloaded 2.5 MB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/GenomicRanges_1.50.2.tgz'
Content type 'application/x-gzip' length 2354390 bytes (2.2 MB)
==================================================
downloaded 2.2 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/hwriter_1.3.2.1.tgz'
Content type 'application/x-gzip' length 107049 bytes (104 KB)
==================================================
downloaded 104 KB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/zlibbioc_1.44.0.tgz'
Content type 'application/x-gzip' length 64914 bytes (63 KB)
==================================================
downloaded 63 KB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/latticeExtra_0.6-30.tgz'
Content type 'application/x-gzip' length 2203766 bytes (2.1 MB)
==================================================
downloaded 2.1 MB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/Rhtslib_2.0.0.tgz'
Content type 'application/x-gzip' length 3092303 bytes (2.9 MB)
==================================================
downloaded 2.9 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/Rcpp_1.0.9.tgz'
Content type 'application/x-gzip' length 3303254 bytes (3.2 MB)
==================================================
downloaded 3.2 MB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/Biostrings_2.66.0.tgz'
Content type 'application/x-gzip' length 14296487 bytes (13.6 MB)
==================================================
downloaded 13.6 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/ggplot2_3.4.0.tgz'
Content type 'application/x-gzip' length 4211193 bytes (4.0 MB)
==================================================
downloaded 4.0 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/reshape2_1.4.4.tgz'
Content type 'application/x-gzip' length 339140 bytes (331 KB)
==================================================
downloaded 331 KB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/ShortRead_1.56.1.tgz'
Content type 'application/x-gzip' length 5667939 bytes (5.4 MB)
==================================================
downloaded 5.4 MB

trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.2/RcppParallel_5.1.5.tgz'
Content type 'application/x-gzip' length 584075 bytes (570 KB)
==================================================
downloaded 570 KB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/IRanges_2.32.0.tgz'
Content type 'application/x-gzip' length 2274456 bytes (2.2 MB)
==================================================
downloaded 2.2 MB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/XVector_0.38.0.tgz'
Content type 'application/x-gzip' length 622135 bytes (607 KB)
==================================================
downloaded 607 KB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/BiocGenerics_0.44.0.tgz'
Content type 'application/x-gzip' length 605966 bytes (591 KB)
==================================================
downloaded 591 KB

trying URL 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/big-sur-arm64/contrib/4.2/dada2_1.26.0.tgz'
Content type 'application/x-gzip' length 3468884 bytes (3.3 MB)
==================================================
downloaded 3.3 MB

The downloaded binary packages are in
	/var/folders/cf/gynnf1bn75b3cdcc785nplzr0000gn/T//RtmpBGQsH9/downloaded_packages
installing the source package ‘GenomeInfoDbData’

trying URL 'https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz'
Content type 'application/x-gzip' length 11725198 bytes (11.2 MB)
==================================================
downloaded 11.2 MB

* installing *source* package ‘GenomeInfoDbData’ ...
** using staged installation
** data
** inst
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (GenomeInfoDbData)

The downloaded source packages are in
	‘/private/var/folders/cf/gynnf1bn75b3cdcc785nplzr0000gn/T/RtmpBGQsH9/downloaded_packages’
> library("dada2")
Loading required package: Rcpp
Error: package or namespace load failed for ‘dada2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/dada2/libs/dada2.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/dada2/libs/dada2.so, 6): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/dada2/libs/dada2.so (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib

#########However, when I tried to open the package;
> library("dada2")
Loading required package: Rcpp
Error: package or namespace load failed for ‘dada2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/dada2/libs/dada2.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/dada2/libs/dada2.so, 6): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/dada2/libs/dada2.so (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib

#######Same with:

> library(dada2); packageVersion("dada2")
Error: package or namespace load failed for ‘dada2’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/dada2/libs/dada2.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/dada2/libs/dada2.so, 6): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/dada2/libs/dada2.so (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib

**Comment by benjjneb** [comment]
The error messages are indicating that there is a function name that is being called by C++ but is failing to be found in underlying libraries. You can ["demangle" the name](http://demangler.com/) to see what it is:

> _std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str() const

As to how to fix this, I'm not sure. This is not a function implemented in dada2, but rather in the core `std` C++ library.

I might start by trying to reinstall Rcpp? After that, you've reached the boundaries of my ability to help, and may have to look for more general C++ support. Or maybe try googling the demangled missing function name to see if anything useful comes back.

**Comment by RosaCatherina** [comment]
Thanks for the reply. In the end, it all came down to a Mac OS update. It is all fixed now, thank you.
