### ISSUE TITLE
Bad Forward and Reverse quality profiles

### ISSUE THREAD

**Issue by QGaelle** [benjjneb/dada2#1668]
Hi @benjjneb, 

I have been reading threads on the same issue, for example https://github.com/benjjneb/dada2/issues/828 or https://github.com/benjjneb/dada2/issues/910, but some questions remain. 

I have sent samples for sequencing in several batches. We increased the number of samples we sent to the sequencing platform for each run, we started with 144 samples, were happy with the results and decided to send 192 samples for the next run and finally send 288 samples for the third run. Of course, we increased the number of samples after checking that the sequencing depth and output data should be ok. 

The quality profiles of the last run (with 288 samples) seem to have much lower quality profiles both forward and reverse than the previous runs. 

<img width="746" alt="Quality_Run4_R1" src="https://user-images.githubusercontent.com/119663200/210848610-eaf5a165-7a14-40ad-80bf-dfab2f456bce.png">

<img width="789" alt="Quality_Run4_R2" src="https://user-images.githubusercontent.com/119663200/210848618-42479007-478e-4b3b-b965-b5fa5d7f0889.png">

Are they that bad? They are to me but my experience is limited. Could the low quality be related to the number of samples we sent? We didn't have as bad profiles in the previous runs (all samples from all runs are the same kind of samples). 

My second question would be, how should I deal with this poor quality? Obviously I can't trim where the quality crashes or there won't be any overlap. In other threads, you mentioned using just forward or reverse reads, but it looks like in my case they are both quite bad. For instance, the second sample in the plots shows really bad quality. I only ran a couple of samples though, should I check more samples before deciding? 

Thank you for your help, 
Gaëlle

**Comment by benjjneb** [comment]
Perhaps these are lower qualities than what you saw before from this sequencing provider, but these profiles look to me to be well inside the normal range seen in Illumina sequencing.

On this alone, I see no problem.
