### ISSUE TITLE
Random read direction in MiSeq data

### ISSUE THREAD

**Issue by miamynta** [benjjneb/dada2#167]
First of all, thanks for an amazing resource!!

The sequencing facility I have collaborated with use a somewhat unusual adaptor-barcode construct for generating MiSeq paired-end amplicon data. The same adaptor is used on both ends of the fragments, which leads to half the reads being in the opposite direction compared to the other half. If I run the dada2 pipeline (as in the tutorial) on this data, it comes up with twice the number of sequence variants compared to what is expected from a mock community. It turns out that half of these are exact reverse-complements of the other half. **Question 1: Is there a simple way of finding the reverse complements in a large sequence table and removing them, while still compensating for their abundance?**

The company also provides me with a version of the data where they have switched around the reads in the "wrong" direction, and dada2 performs surprisingly well also on this data, although the original R1 and R2 reads have been bunched together. This bunching together of the R1 and R2 reads causes the average quality profiles (as plotted using plotQualityProfile()) to look quite shitty, and the truncation length becomes a compromise between the good quality of the original R1 reads and the poor quality of the original R2 reads. **Question 2: Does running dada() on reads that have very varying quality profiles (since they are a mix of R1 and reverse-complemented R2 reads) compromise the output of the error estimation?** I notice that selfConsist takes many rounds to converge (6-7 rounds) compared to with "normal" data (3-4 rounds). The error plots look OK as far as I can tell.

Grateful for any tips! 

/ Mia

**Comment by benjjneb** [comment]
Q1: We do not have a simple function to merge together a table of sequences in random orientation. However, the tools are there to do so with a little bit of R scripting.

`nwhamming(dada2:::rc(sq), sqs.all, vec=TRUE)` will return a vector of hamming distances between the reverse-complement of `sq` and the sequences in `sqs.all`. In your case, that vector should usually contain two zeros, one for the two directions of `sq` in the output data. That information can be used to group those paired orientations together.

Q2: Maybe. We have observed multiple instances in which the error rates of forward and reverse reads, **after controlling for quality**, were quite different. That is not usually the case, but if that is the case then the rates estimated on a mixture of forward/reverse reads will not be ideal.

However, if the error rates for F/R are basically the same, then it is OK to just process them together in this way. You can check this by fitting the error model to the forward reads, plotting it w/ `plotErrors`, doing the same for the reverse reads, and inspecting the two plots.

**Comment by miamynta** [comment]
Thanks, this helps a lot! In order to check if the error rates are the same for R1 and R2 reads, what features of the plot are most important? Slope of the modeled black line? Fit of the line to the points?

**Comment by benjjneb** [comment]
The black line in the `plotErrors` output is the fitted error model, and that should be close to the same for both.

You can also look directly at the matrices of fitted error rates if you want (`dadaFs[[1]]$err_out`).

**Comment by rec3141** [comment]
Here's my solution to this problem:


```
mergers.bak <- mergers #copy to avoid obliterating data
ref.seq <- head(mergers[[1]][1,1]) #should be a sequence you know is in correct orientation

for(plate in names(mergers)) {
    seq.hd <- nwhamming(substr(ref.seq,1,50), substr(mergers[[plate]][,1],1,50), vec=TRUE, endsfree=F)
    seq.rc <- nwhamming(substr(dada2:::rc(ref.seq),1,50), substr(mergers[[plate]][,1],1,50), vec=TRUE, endsfree=F)
    seq.df <- seq.rc - seq.hd #positive = original orientation, negative = reverse orientation
    hist(seq.df, breaks=100)

    seq.r <- which(seq.df < 0)
    mergers[[plate]][seq.r,1] <- dada2:::rc(mergers[[plate]][seq.r,1])   
}


```

**Comment by ramongallego** [comment]
I should have looked for this issue long time ago! I also use indexing by ligation for preparing libraries and therefore I have Forward and Reverse reads in both .1 and .2 fastq files.  I was worried that calculating errors using reads in both directions might affect the final output, and that it was better to reorient reads before the pipeline starts. The downside of it is that the whole process takes some more time. 
I used the last version of cutadapt to split both fastq files.  Then I run the DADA2 pipeline in parallel and merge Forward and ReversedComplemented reads after makeSequenceTable but before looking for chimeras.
