### ISSUE TITLE
ITS sequencing - Duplicate sequences detected and merged

### ISSUE THREAD

**Issue by andressamv** [benjjneb/dada2#1670]
Hi @benjjneb! I am running DADA2 for an ITS sequencing (2 x 250 bp) following the standard ITS pipeline (with cutadapt). Following the recommendations, I did not use truncLen during the filtering/trimming step. However, I later got the following error:

> seqtab <- makeSequenceTable(mergers)
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.
Duplicate sequences detected and merged.

I saw here https://github.com/benjjneb/dada2/issues/213 that this could be related to remaining primers. I was not in charge of this sequence, so I do not know if the Illumina sequencing adapters were removed. However, I removed the ITS primers using Cutadapt. Using truncLen, I got rid of this error, but I lost a significant amount of sequences. How should I deal with this, considering that I working with ITS? Do you have any recommendations? Thank you!

**Comment by benjjneb** [comment]
This is not an error, its just a warning.
Given your described processing, i.e. no use of `truncLen`, it is not surprising there may have been multiple length-variants of some ASVs in your forward or reverse reads. These would be merged into the same merged ASV, and then the duplicated merged ASVs would be detected and "merged" (in another sense) when you ran `makeSequenceTable`.

So, I wouldn't worry about this, as long as other diagnostics look OK.
