### ISSUE TITLE
Plot quality profile - evaluation

### ISSUE THREAD

**Issue by otaviolovison** [benjjneb/dada2#1671]
Dear DADA2 community,

while following the tutorial, the instructions are to perform a visual evaluation of the quality plot to define the trunclen parameters.
My supervisor thinks that visual evaluation is too subjective and is questioning about an alternative approach. 

Do you have any suggestions or any answers to support that visual evaluation approach?

Best wishes.

**Comment by fconstancias** [comment]
Well, this parameter is basically used to removed the noisy ends - especially for Rev reads which are not necessary depending of the amplicon length you amplified and to make sure all the reads have the same length for dadas pipeline.

You could also use the knowledge of the length distribution of the amplicon you are focusing on and based the `trunclen` on that making sure you have enough overlap to capture the length polymorphism.

Hope this helps.

**Comment by otaviolovison** [comment]
You could also use the knowledge of the length distribution of the amplicon you are focusing on and based the trunclen on that making sure you have enough overlap to capture the length polymorphism.

Yes, that's what I am doing.

Thank you.
