### ISSUE TITLE
ggplot <scale> arguent

### ISSUE THREAD

**Issue by omarkr8** [benjjneb/dada2#1672]
perhaps a package update discrepency? unsure what the consequences are yet.

_> plotQualityProfile(cutFs[1])
Warning message:
The `<scale>` argument of `guides()` cannot be `FALSE`. Use "none" instead as of
ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the dada2 package.
  Please report the issue at <https://github.com/benjjneb/dada2/issues>._

**Comment by fconstancias** [comment]
This is is a warning related to a deprecated argument in ggplot. This does not impact the visualisation but might in a future ggplot version.
