### ISSUE TITLE
DNBseq takes forever to run

### ISSUE THREAD

**Issue by thecrobe** [benjjneb/dada2#1674]
Hello, 

I have been running 10 samples of 16s amplicon data generated using the DNBseq platform. The reads are high quality and have about 100K bp per fasta file (for forward nd reverse). The sequences filter fine but then denoising and merging took over 2 days on a 16 core server with more than enough RAM. 

Has anyone run into issues using DNBseq and DADA2 before? 
Copies of a few fasta files can be found [here](https://www.dropbox.com/sh/rideweljowg1a0b/AAARmSNXmREOEMW8CRgF5TUFa?dl=0). 

DNBseq: https://en.mgi-tech.com/products/instruments_info/2/

Any advice or thoughts would be appreciated. 

Best, 
Justin

**Comment by benjjneb** [comment]
I have zero experience with DNBseq, so I'd also be interested if anyone has worked with it.

> Copies of a few fasta files can be found [here](https://github.com/Users/justinstewart/Dropbox/DNBseqProblems).

This link doesn't work for me.

**Comment by thecrobe** [comment]
Link is fixed!

**Comment by llpiggyll** [comment]
Any new updates on this issue?

**Comment by benjjneb** [comment]
Sorry no. I have test data and its on the to-do list, but hasn't bubble to the top yet.
