### ISSUE TITLE
Can't assign taxonomy to LULU reads. 

### ISSUE THREAD

**Issue by jjhackma** [benjjneb/dada2#1675]
I have no idea what Key 49 (char '1') is referring to.  When I run the reads using seqtab.nochim from the 1.8 fungal protocol it works just fine. 
taxa <- assignTaxonomy(asvs.lulu.t, unite.ref , minBoot = 80, multithread=FALSE)
UNITE fungal taxonomic reference detected.
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'reverseComplement': key 49 (char '1') not in lookup table
![image](https://user-images.githubusercontent.com/77695530/213773128-e508ddc8-50c8-4248-827e-4d32012955c6.png)

![image](https://user-images.githubusercontent.com/77695530/213773219-de6d992d-ba63-467f-b3ff-184b134c58bf.png)

**Comment by benjjneb** [comment]
`assignTaxonomy` expects the column names to be the sequences. In your `asvs.lulu.t` table, they are ASV ids, like `ASV1`, which are throwing an error when they are reverse-complemented.

**Comment by jjhackma** [comment]
So my output table from lulu only had the ASV ids, how do I make sure that it keeps the full sequences associated with each one?

**Comment by benjjneb** [comment]
You'd have to look at the documentation for LULU if it is changing the names of the ASVs.

**Comment by jjhackma** [comment]
Thanks Ben, got it figured out. However, I noticed that there are no singletons in my data which seems very strange. I'm following the dada2 1.8 pipeline for ITS reads. Is there a step in the pipeline that removes singletons?
