### ISSUE TITLE
custom database for plants and insects

### ISSUE THREAD

**Issue by FarzanehRah** [benjjneb/dada2#1676]
Hello,
We are working on a project with insect and plant barcodes, I have  two questions:
 1. Should we create two different databases for each insect and plant barcodes or is it better to use a combined database?
2. To create a database, do we just need to put the sequences in the proper format (like below) or do we need to do additional works?
```
Bacteria;Proteobacteria;Gammaproteobacteria;Pseudomonadales;Pseudomonadaceae;Pseudomonas;
AACTGAAGAGTTTGATCATGGCTCAGGA
```
Thank you so much

**Comment by benjjneb** [comment]
1. Is it the same locus? If so, combined is fine. If not, different databases.

2. That's it. Only additional note is that `assignTaxonomy` assumes a fixed set of taxonomic levels -- i.e. it doesn't handle levels like "superfamily" that only some taxa are assigned but not others.

**Comment by FarzanehRah** [comment]
Thank you, I appreciate your prompt response.

**Comment by FarzanehRah** [comment]
Regarding the custom database, I wonder if duplicate records in the database affect the classification assignment results?
