### ISSUE TITLE
Dark plotQualityProfile

### ISSUE THREAD

**Issue by RosaCatherina** [benjjneb/dada2#1677]
Has anyone experience with dark/weird looking plotQualityProfiles? 
The plots don't seem as they should or how they normally look like on the internet. 
<img width="392" alt="Screenshot 2023-01-23 at 16 03 36" src="https://user-images.githubusercontent.com/121615514/214083112-b72a448c-65b6-4184-b20e-3d51761c2390.png">

Could it be that the length of the cycle is longer? 
if I run the .fastq files with 
fn <- "/Users/xxx/Documents/PhD/DNA/FASTQ_Raw_16S/Subset/ZSIA1_2.fq"
srq <- readFastq(fn)
seqlen.tab <- table(width(srq)) # Table of how many RSVs have a given length in nts
seqlen.tab
seqlens <- as.integer(names(seqlen.tab))
counts <- as.integer(seqlen.tab)
plot(x=seqlens, y=counts)
plot(x=seqlens, y=log10(counts))

The vast majority of the length of the samples is always at 220.

**Comment by benjjneb** [comment]
You are working with data with binned quality scores (i.e. only a very small number of quality scores, like 4 maybe) are used).

The plot doesn't render ideally with this data, but what you are seeing is normal for binned quality scores. And quality looks fine, the high quality score account sfor almost all the reads, hence why the top "bar" of the 3 remains much darker throughout the read.
