### ISSUE TITLE
poor quality score_Forward/Reverse V3-V4region

### ISSUE THREAD

**Issue by Gigiagio** [benjjneb/dada2#1685]
Dear all,

Dear ALL,
My QC graphs have a bad quality score. I attached Ffile and Rfile
I was wondering about the truncLen parameter settings in filterAndTrim that you would suggest for the reads 
The amplicon has a size of ~426 bp and is sequenced 2x300 V3-V4. The primers usually have 38bp

Many thanks in advance.
Best regards.
[Rquality.pdf](https://github.com/benjjneb/dada2/files/10521199/Rquality.pdf)
[Fquality.pdf](https://github.com/benjjneb/dada2/files/10521200/Fquality.pdf)

**Comment by benjjneb** [comment]
One option to consider is just using the forward reads alone if the reverse reads are particularly poor quality.

If you are merging, and the sequenced amplicon is 420-440nts (roughly), then the total `truncLen` forward and reverse shoudl add up to at least 460 to be safe.
