### ISSUE TITLE
AssignTaxonomy on only one sample out of table

### ISSUE THREAD

**Issue by saskiaterhorst** [benjjneb/dada2#1689]
Hi,
Currently doing taxonomy on about 100 samples. I want to test if it works on one single sample before leaving it to run overnight to do the rest. It takes really long to complete. 

`seqtab.nochim <-"outputs/seqtab.nochim.RDS"`
`unite.ref <- "taxDBs/sh_release.fasta"  `
`taxa <- assignTaxonomy(seqtab.nochim, unite.ref, multithread = TRUE, tryRC = TRUE`
`taxa.print <- taxa`

I have tried` taxa <- assignTaxonomy(seqtab.nochim, unite.ref, multithread = TRUE, tryRC = TRUE)[1:2]` But that did not work
Any help would be aprreciated!

**Comment by benjjneb** [comment]
Typically such slow behavior is due to the computer `assignTaxonomy` is being run on not having enough memory for the selected reference database. So the solution is either to find a machine with more memory for this stage, or to try references with lower memory requirements.
