### ISSUE TITLE
Error rates could not be estimated. Error in err[c(1, 6, 11, 16), ] <- 1

### ISSUE THREAD

**Issue by naarkhoo** [benjjneb/dada2#169]
I wonder if there is any reason behind the following error. I am using the tutorial with 359 samples

```
dadaFs.lrn <- dada(derepFs, err=NULL, selfConsist=TRUE, multithread=TRUE)
Initial error matrix unspecified. Error rates will be initialized to the maximum possible estimate from this data.
Initializing error rates to maximum possible estimate.
Error rates could not be estimated.
Error in err[c(1, 6, 11, 16), ] <- 1 : 
  incorrect number of subscripts on matrix
```
here is how I prepare the samples

```
filtFs <- paste0("dada_dir/", sample.names, "_F_filt.fastq.gz")
filtRs <- paste0("dada_dir/", sample.names, "_R_filt.fastq.gz")
# Filter
for(i in seq_along(fnFs)) {
  fastqPairedFilter(c(fnFs[i], fnRs[i]), c(filtFs[i], filtRs[i]),
                    trimLeft=c(10, 10), truncLen=c(240,150), 
                    maxN=0, maxEE=c(1,1), truncQ=2, 
                    compress=TRUE, verbose=TRUE)
}

derepFs <- derepFastq(filtFs, verbose=TRUE)
derepRs <- derepFastq(filtRs, verbose=TRUE)
# Name the derep-class objects by the sample names
names(derepFs) <- sample.names
names(derepRs) <- sample.names

dadaFs.lrn <- dada(derepFs, err=NULL, selfConsist=TRUE, multithread=TRUE)
```
When I use `inflateErr(tperr1,3)` instead of null I get 

```
> dadaFs <- dada(derepRs[1], err=inflateErr(tperr1,3), selfConsist = TRUE)
Sample 1 - 37263 reads in 13462 unique sequences.
Error rates could not be estimated.
Error in dada(derepRs[1], err = inflateErr(tperr1, 3), selfConsist = TRUE) : 
  Error matrix returned by errorEstimationFunction not numeric.

```

I am using dada2 version 1.1.8
Thank you

**Comment by benjjneb** [comment]
Hm... I'm not sure. Would you be willing to update to the current release version (1.2.0, available via Bioconductor install) and see if this persists?

If that doesn't work, could you share one of the derep objects that is causing this problem, eg:

```S
saveRDS(derepRs[[1]], "derep.bug.rds")
```

**Comment by naarkhoo** [comment]
Thanks. here is the file, [https://www.dropbox.com/s/w7lg9bu2bxhjs2l/derep.bug.rds?dl=0](url)

**Comment by benjjneb** [comment]
The following works for me as expected:

```
drp <- readRDS("~/Desktop/derep.bug.rds")
dd <- dada(drp, err=inflateErr(tperr1,3), selfConsist=TRUE)
```

> Initial error matrix unspecified. Error rates will be initialized to the maximum possible estimate from this data.
Initializing error rates to maximum possible estimate.
Sample 1 - 37263 reads in 13462 unique sequences.
   selfConsist step 2 
   selfConsist step 3 
   selfConsist step 4 
   selfConsist step 5 
   selfConsist step 6 
   selfConsist step 7 


>Convergence after  7  rounds.


With `packageVersion("dada2")` of 1.2.0 on OSX and R 3.3.2

Does this derep object definitely trigger that error on your machine? Did you try updating the dada2 R package to 1.2.0?

**Comment by naarkhoo** [comment]
I updated biostrings, genomicsRanges and other prerequisite packages and now works fine. Thanks again.
