### ISSUE TITLE
dada2 plotQualityProfile issue

### ISSUE THREAD

**Issue by SowjanyLakshmi** [benjjneb/dada2#1690]
when i try to plot the qualityplots i am getting this issue

please let me know how to resolve this

plotQualityProfile(fnFs[1:10])
Warning message:
The `<scale>` argument of `guides()` cannot be `FALSE`. Use "none" instead as of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the dada2 package.
  Please report the issue at <https://github.com/benjjneb/dada2/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

**Comment by benjjneb** [comment]
It's just a warning, you can ignore it.
