### ISSUE TITLE
"negative vector not allowed" in assignTaxonomy

### ISSUE THREAD

**Issue by whitnersyrena** [benjjneb/dada2#1691]
Hi there, 
I am trying to use the assign taxonomy function in dada2 on my HPC and am getting this error: 

Error in C_assign_taxonomy2(seqs, rc(seqs), refs, ref.to.genus, tax.mat.int,  : 
  negative length vectors are not allowed

I have tried running with/without multithread (47 cores), 140GB memory, so I do not believe it is a memory issue. 

The code I am trying to execute is: 
taxa_pr2 <- assignTaxonomy(seqs, PR2.ref, 
                           taxLevels = c("Kingdom","Supergroup","Division","Class","Order","Family","Genus","Species"), 
                           multithread = F, minBoot = 0, outputBootstraps = TRUE, verbose = TRUE)

Please let me know how I can go about troubleshooting this, I have ran a subset of the data successfully on my local machine so I am pretty confident that the script works...

**Comment by benjjneb** [comment]
Have you seen anything useful in https://github.com/benjjneb/dada2/issues/691 ?

It would be good to find a test example that produces this error on the HPC, and does not on your local machine.
