### ISSUE TITLE
Is it possible to make a .fna and .biom file?

### ISSUE THREAD

**Issue by chuynh96** [benjjneb/dada2#1692]
Is there a way to make a .fna file and .biom file after using the DADA2 pipeline in order to run PICRUST2 as described below:

The standard pipeline will generate metagenome predictions for 16S rRNA gene data. The input files should be a FASTA of amplicon sequences variants (ASVs; i.e. your representative sequences, not your raw reads, which is study_seqs.fna below) and a BIOM table of the abundance of each ASV across each sample (study_seqs.biom below).

Thank you!

**Comment by benjjneb** [comment]
I would suggest searching the GH repository for previous issues about Picrust2

**Comment by chuynh96** [comment]
I couldn't seem to find what I am looking for, so I apologize if this is the incorrect place to ask! But I was wondering if it was possible with the objects generated from using the DADA2 pipeline, that it was possible to make a the .fna file and the .biom table as described above using the ps object made after using phyloseq?

**Comment by benjjneb** [comment]
https://github.com/picrust/picrust2/issues/135 and https://github.com/picrust/picrust2/issues/136#issuecomment-743696114
