### ISSUE TITLE
Cannot Download package 'usethis'

### ISSUE THREAD

**Issue by elliottchon97** [benjjneb/dada2#1694]
I installed "devtools" but when I use library("devtools") , it shows:
> library("devtools")
Error: package ‘usethis’ required by ‘devtools’ could not be found
So i try:
install.packages("usethis")
but it gives me this error:
Warning in install.packages :
  downloaded length 712800 != reported length 818712
Warning in install.packages :
  URL 'http://cran.rstudio.com/bin/windows/contrib/4.2/usethis_2.1.6.zip': status was 'Failure when receiving data from the peer'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'http://cran.rstudio.com/bin/windows/contrib/4.2/usethis_2.1.6.zip' failed
Warning in install.packages :
  download of package ‘usethis’ failed

Why is this occurring? 

Thank you for your help!

**Comment by benjjneb** [comment]
Is this posted to the right repository? This is the issues forum for the dada2 R package.

**Comment by elliottchon97** [comment]
Yes this is for the right repository. I am having trouble downloading the dada2 package. The instructions told me to install devtools first.

**Comment by benjjneb** [comment]
Have you tried the recommended installation method using Bioconductor?

**Comment by elliottchon97** [comment]
Yes I have tried that. It did not work as well.
Error:
Warning: unable to access index for repository https://bioconductor.org/packages/3.16/data/experiment/bin/windows/contrib/4.2:
  cannot open URL 'https://bioconductor.org/packages/3.16/data/experiment/bin/windows/contrib/4.2/PACKAGES'

**Comment by benjjneb** [comment]
Do you have a consistent internet connection? Is your computer managed in some way (or network) that doesn't allow some internet connections?

I'm not sure what's going on, but it appears to be related to your ability to connect to these repositories.

**Comment by elliottchon97** [comment]
I am currently on a work computer and it only allows me to use their internet.

**Comment by elliottchon97** [comment]
Okay! Thank you!
