### ISSUE TITLE
dada2 on ITS sequences

### ISSUE THREAD

**Issue by jspychalla** [benjjneb/dada2#1695]
Hello, 
   I am running the dada2 pipeline on ITS sequences the version of R I am using is 4.2.2 and the version of dada2 I am using is 1.26.0

When I ran the filterAndTrim command 
out <- filterAndTrim(cutFs, filtFs, cutRs, filtRs, maxN = 0, maxEE = c(2, 2), 
+                      truncQ = 2, minLen = 50, rm.phix = TRUE, compress = TRUE, multithread = TRUE) 

I got the below message 
Some input samples had no reads pass the filter.

I figured this meant that for some samples reads.out would be 0. 

When I go on to learn the error rates I get the following message
errF <- learnErrors(filtFs, multithread = TRUE)
Error in derepFastq(fls[[i]], qualityType = qualityType) : 
  Not all provided files exist.

How do I move forward with the rest of the pipeline? Do I remove somehow the samples that did not pass the filter? 
Is it alright to have some input samples have no reads pass the filter? This has not happened to me before. 

Thank you so much for your time!

**Comment by benjjneb** [comment]
Check with the output of `filterAndTrim` that this isn't a general problem (i.e. most samples are having most reads pass the filter in the `out` object from the tutorial).

After that, just subset your samples down to those that exist post filtering: `filtFs <- filtFs[file.exists(filtFs)]`. Then move forward as usual.

**Comment by jspychalla** [comment]
PS never mind I found your answer to some who had the previous problems. 
https://github.com/benjjneb/dada2/issues/375

Yes only two samples did not have reads pass the filter 

Just saw your comment will 
exists <- file.exists(filtFs) & file.exists(filtRs)
filtFs <- filtFs[exists]
filtRs <- filtRs[exists]
work as well that is what I found on a previous thread

**Comment by jspychalla** [comment]
Also further in the pipeline I am getting this error 
names(derepFs) <- sample.names
Error in names(derepFs) <- sample.names : 
  'names' attribute [100] must be the same length as the vector [98]

I'm assuming this is due to the 2 samples that did not pass the filter.

**Comment by benjjneb** [comment]
Yes that should work.
