### ISSUE TITLE
Issue using cutadadapt in R

### ISSUE THREAD

**Issue by Microzach** [benjjneb/dada2#1696]
I am currently running through the tutorial for dada2, test running everything as I go, got cutadapt installed, and then did a test run of it to get the version #. 

> cutadapt <- "C:/Users/zburton/Box/BurtonZach-Microbial corrosion inhibition project/cutadapt.exe"
> system2(cutadapt, args = "--version") # Run shell commands from R
4.0

I then went on to setup and run cutadapt for the primer removal, this is were I ran into issues. After setting up where to send the output files I ran the program and got this error in the output screen of R. 

> path.cut <- file.path(path, "cutadapt")
> if(!dir.exists(path.cut)) dir.create(path.cut)
> fnFs.cut <- file.path(path.cut, basename(fnFs))
> fnRs.cut <- file.path(path.cut, basename(fnRs))
> 
> FWD.RC <- dada2:::rc(FWD)
> REV.RC <- dada2:::rc(REV)
> Trim FWD and the reverse-complement of REV off of R1 (forward reads)
> R1.flags <- paste("-g", FWD, "-a", REV.RC) 
> Trim REV and the reverse-complement of FWD off of R2 (reverse reads)
> R2.flags <- paste("-G", REV, "-A", FWD.RC) 
> 
> R1.flags
[1] "-g ACCTGCGGARGGATCA -a AACTTTYARCAAYGGATCTC"
> Run cutadapt

>for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                             fnFs.filtN[i], fnRs.filtN[i])) # input files
}

The ERROR: 
>This is cutadapt 4.0 with Python 3.9.12
Command line parameters: -g ACCTGCGGARGGATCA -a AACTTTYARCAAYGGATCTC -G GAGATCCRTTGYTRAAAGTT -A TGATCCYTCCGCAGGT -n 2 -o C:/Users/zburton/Box/BurtonZach-Microbial corrosion inhibition project/Feb2023_ITSand16S/practice/cutadapt/SRR5314314_1.fastq.gz -p C:/Users/zburton/Box/BurtonZach-Microbial corrosion inhibition project/Feb2023_ITSand16S/practice/cutadapt/SRR5314314_2.fastq.gz C:/Users/zburton/Box/BurtonZach-Microbial corrosion inhibition project/Feb2023_ITSand16S/practice/filtN/SRR5314314_1.fastq.gz C:/Users/zburton/Box/BurtonZach-Microbial corrosion inhibition project/Feb2023_ITSand16S/practice/filtN/SRR5314314_2.fastq.gz
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

This popped up multiple times, so I am wondering where did I make a mistake or mess up to get this back? Also sorry for how the text may look, this is my first time commenting/writing on GitHub

**Comment by benjjneb** [comment]
Can you clarify where the error is? The text you posted just looks like the command line call you made, plus a little standard output from cutadapt.

Were the expected output files created?

**Comment by Microzach** [comment]
I have no output files inside of the cutadapt directory that was created, which means when I run the rbind to see the amount of primers left I get this output message:

> rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.cut[[1]]), 
>      + FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.cut[[1]]), 
>     + REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.cut[[1]]), 
>     + REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.cut[[1]]))

>Error in h(simpleError(msg, call)) :
error in evaluating the argument 'subject' in selecting a method for function 'vcountPattern': error in evaluating the argument 'object' in selecting a method for function 'sread': Input/Output
no input files found
dirPath: C:/Users/zburton/Box/BurtonZach-Microbial corrosion inhibition project/Feb2023_ITSand16S/practice/cutadapt/SRR5314314_1.fastq.gz
pattern: character(0)

I am assuming this is occurring due to getting something wrong when I did the previous parts of the cutadapt setup due to the this line in that I mean to include in the previous post (so this is the error that is output after run cutadapt on the sequences):  

>cutadapt.exe: error: unrecognized arguments: corrosion inhibition project/Feb2023_ITSand16S/practice/cutadapt/SRR5314357_2.fastq.gz C:/Users/zburton/Box/BurtonZach-Microbial corrosion inhibition project/Feb2023_ITSand16S/practice/filtN/SRR5314357_1.fastq.gz C:/Users/zburton/Box/BurtonZach-Microbial corrosion inhibition project/Feb2023_ITSand16S/practice/filtN/SRR5314357_2.fastq.gz

**Comment by benjjneb** [comment]
Ah, the issue is that you have spaces in your filepaths, which are being misinterpreted by the command line as indicating different arguments.

It is highly recommended to not use spaces (or other special characters) in the names of files and directories for this reason. I would recommend renaming the directory with spaces in the name, and then things will probably just work. Alternatively, appropriate use of either quotes or escapes in the command-line call can handle spaces, but that takes a bit more care to get working especially since you are building this call in R.
