### ISSUE TITLE
Merging the results of multiprimer metabarcoding 

### ISSUE THREAD

**Issue by FarzanehRah** [benjjneb/dada2#1697]
Hi,
We are working on a multiprimer metabarcoding for plants, since there are 2 different amplicons in each sample (nuclear and chloroplast markers), we need to build a custom database for each amplicon and run the analysis separately for each amplicon.
So, is it statistically correct to combine the results of the 2 analyzes for the downstream analysis or should they be separated? Is there another solution for these complex analyses? 

Thank you,

**Comment by benjjneb** [comment]
> So, is it statistically correct to combine the results of the 2 analyzes for the downstream analysis or should they be separated?

What do you mean by "combine"? Summing taxonomic abundances from the different markers into a common table? Or something else?

**Comment by FarzanehRah** [comment]
Thanks for your response; Yes exactly, create a taxonomic count table for both markers for differential abundance analysis.

**Comment by benjjneb** [comment]
I would not take that approach. For a variety of reasons including at least differences in taxonomic resolution and taxonomic bias between different makers, I think it is preferable to analyze the tables from each separately, and then consider synthesizing the results from those marker-specific analyses.

**Comment by FarzanehRah** [comment]
Thank you for your help!

**Comment by FarzanehRah** [comment]
For metabarcoding analysis, the most commonly accepted method is dada2, however, there are not many multi-primer metabarcoding studies, in the paper I found, they used BLAST. So, since the input files are a mixture of amplicons (in our case, a 400 bp region and a 10-143 bp ITS), is it a good idea to do this kind of analysis using dada2? Do we need to split the input reads according to primers before starting the analysis or we can run two separate analyses on all the reads? Thanks

**Comment by benjjneb** [comment]
I would recommend splitting the reads by amplicon at the start, especially here since you will might make some different filtering/trimming decisions for the ITS region because of its variable length.

**Comment by FarzanehRah** [comment]
Thank you for your valuable comment!
