### ISSUE TITLE
Can I export results of taxonomy assigned to each sequence by DADA2 as a CSV/Excel file?

### ISSUE THREAD

**Issue by Ecotone23** [benjjneb/dada2#1700]
Hi,

I wonder how I can export results of taxonomy assigned to each sequence by DADA2 as a csv file?

I followed the DADA2 pipeline tutorial (1.16) to edit my paired-end sequencing data and successfully assigned the taxonomy for the data. 

However, after running the following scripts:

# Let’s inspect the taxonomic assignments:
taxa.print <- taxa # Removing sequence rownames for display only
rownames(taxa.print) <- NULL
head(taxa.print)

It only printed results for 6 samples and I don't know how to export the results for all samples, ideally in a CSV or Excel file. 

Thank you,

**Comment by benjjneb** [comment]
Most of the outputs of the dada2 R package are basic R variable types (e.g. data.frame, or matrix), and so can be written to files using standard R functions like `write.csv`.

That should work here.

**Comment by Ecotone23** [comment]
Thanks!  It works! But the exported file doesn't contain any sample/sequence IDs for the taxonomy, how can I get a file of taxonomy assigned to each sequence ?

**Comment by benjjneb** [comment]
`write.csv` the `taxa` object instead. That object still has the rownames (ASVs).

**Comment by Ecotone23** [comment]
Hi Ben @benjjneb ,

I tried to export the results of taxonomy assigned to each sequence ID using the following scripts:

write_csv(as.tibble(taxa), file= str_c(dada2_dir, "DecaturMicroTaxa.csv"))

but still ended up getting a taxonomy file without any IDs(rownames) like this:
![Screen Shot 2023-02-15 at 12 13 55 PM](https://user-images.githubusercontent.com/110413335/219116907-53858d6a-1915-4fbf-81ac-660db701e979.png)

And I also wonder why there are so many sequences that have no species name assigned, how can I increase the chance of getting more species names assigned to my sequences?

**Comment by benjjneb** [comment]
Either don't convert it to a tibble (which drops the rownames), or add back a column `$Sequence` that is equal to `rownames(taxa)`.

> And I also wonder why there are so many sequences that have no species name assigned, how can I increase the chance of getting more species names assigned to my sequences?

Robust species assignment to short 16S fragments is often not possible. You can get more species names by taking a different approach, like assigning species to whatever the best hit it, but a lot of those species asignments will be wrong.

**Comment by Ecotone23** [comment]
Got it. I really appreciate your time and answers.
