### ISSUE TITLE
DADA2 warning: some input samples had no reads pass the filter

### ISSUE THREAD

**Issue by Ecotone23** [benjjneb/dada2#1701]
Hi Ben @benjjneb ,

I followed your DADA2 pipeline 1.16 edit my sequencing data and I had removed Ns bases, primers and sequences  less than 5 reads. I visualized my data using PlotQualityProfile() and found the forwards and reverses start dropping below 30 (quality score) from 250 and 210. So I further processed the sequences using filterAndTrim with setting of truncLen=c(250,210).

I ended up getting a warning that some input samples had no reads pass the filter, even I changed the truncLen to (200,160). Is there any way to let all input samples to pass the filter? Or it is okay to have some samples had no read to pass the filter?

Thank you,

**Comment by Ecotone23** [comment]
And some samples lost all their reads after merging. Are these the same samples that had no reads pass the filterAnd Trim, how can I let make these samples passed as well?
<img width="675" alt="Screen Shot 2023-02-15 at 5 12 18 PM" src="https://user-images.githubusercontent.com/110413335/219213537-5fb55ca8-c7d0-4fe1-b270-ca0392152daa.png">

**Comment by Ecotone23** [comment]
And some samples lost all/most of their reads after merging. Are these the same samples that had no reads pass the filterAnd Trim, how can I let these samples pass the filtering as well?
<img width="675" alt="Screen Shot 2023-02-15 at 5 12 18 PM" src="https://user-images.githubusercontent.com/110413335/219213871-b836d5cd-e141-44d4-bbcf-9a42038b183f.png">

**Comment by benjjneb** [comment]
> Or it is okay to have some samples had no read to pass the filter?

Having some samples that don't have any reads pass the filter is not uncommon, especially in larger datasets. These samples are typically ones where the library construction failed in some way. Looking at the `head(track)` output you included, it looks like some samples have vastly fewer reads than the others, and that one of those with just 330 reads is one where no reads passed. The other samples iwth healthy starting read counts (5000+) are seeing healthy read counts pass through each step.

So based on what you've shown here, I would not be concerned.
