### ISSUE TITLE
Error with Generating Initial Quality Plots for DADA2 Pipeline Tutorial

### ISSUE THREAD

**Issue by shconnolly** [benjjneb/dada2#1703]
Hello,

Whenever I try to initially generate the quality plots for some of my samples I get the following message & the plot can not be opened due to an error popping up. Additionally it is worth noting that the file size of my plots are 0 KB. I thought it was due to a problem with string manipulations for my filenames so I tried to format them in the same way as the tutorial but I was still running into the same issue. Any help would be appreciated, running on version 1.26.0

Warning message:
The `<scale>` argument of `guides()` cannot be `FALSE`. Use "none" instead as
of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the dada2 package.
  Please report the issue at <https://github.com/benjjneb/dada2/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
generated.

lifecycle::last_lifecycle_warnings()

[[1]]
<warning/lifecycle_warning_deprecated>
Warning:
The `<scale>` argument of `guides()` cannot be `FALSE`. Use "none" instead as
of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the dada2 package.
  Please report the issue at <https://github.com/benjjneb/dada2/issues>.
---
Backtrace:
 1. dada2::plotQualityProfile(fnFs[1:2])
 2. ggplot2::guides(fill = FALSE)
 3. ggplot2:::deprecate_warn0("3.3.4", "guides(`<scale>` = 'cannot be `FALSE`. Use \"none\" instead')")

**Comment by benjjneb** [comment]
Not an error, just a warning. The warning will be gone in the next release.

This shouldn't affect the generation of the plots, so that would seem to be a separate issue.
