### ISSUE TITLE
Interpreting error plots

### ISSUE THREAD

**Issue by pig-raffles** [benjjneb/dada2#1705]
Hi,

I have created error plots in Dada2 for 16S V4 data. I think the plots show that the estimated error rate models are suitable for moving forward with.

The model line seems to fit the points well and decreases with phred score as expected. Does this mean I should move onward with the data in the Dada2 pipleine? Is there other aspects of this plot that I should look out for?

In the attached combined figure there is a dip around phred score 10-15  in error frequency in all A2A, C2C, G2G, T2T. What is causing this and is this something to be concerned about?

Thanks in advance,

Alan
![errorPlot](https://user-images.githubusercontent.com/12744869/220785596-48d186a1-5852-456e-b9f9-c8dc3c86d813.png)

**Comment by benjjneb** [comment]
That looks good. Nothing to be concerned about here.

**Comment by pig-raffles** [comment]
Thanks!
