### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by githubPratima** [benjjneb/dada2#1708]
Hi, I tried to install tidyverse packages not for tidyverse all the package installation is giving an error in window10. I am using r-kernel from anaconda in jupyter notebook making virtual env. I checked the installed packages in virtual env, all the packages are installed but when I run the packages in R kernel, install.packages("tidyverse")it shows a lot of errors. Any help, please!!

installing the source packages 'lifecycle', 'tidyselect', 'scales', 'gargle', 'callr', 'bslib', 'tinytex', 'pkgload', 'waldo', 'broom', 'conflicted', 'dbplyr', 'dtplyr', 'forcats', 'ggplot2', 'googledrive', 'googlesheets4', 'hms', 'modelr', 'pillar', 'reprex', 'rvest', 'stringr', 'knitr', 'rmarkdown', 'tidyverse'

Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'lifecycle' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'callr' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'bslib' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'tinytex' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'pkgload' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'waldo' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'conflicted' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'knitr' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'tidyselect' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'scales' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'gargle' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'forcats' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'hms' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'pillar' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'rvest' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'stringr' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'broom' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'dbplyr' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'dtplyr' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'ggplot2' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'googledrive' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'rmarkdown' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'googlesheets4' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'modelr' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'reprex' had non-zero exit status"Warning message in install.packages("tidyverse", dependencies = TRUE):
"installation of package 'tidyverse' had non-zero exit status"
Error in library(tidyverse): there is no package called 'tidyverse'
Traceback:

1. library(tidyverse)

**Comment by benjjneb** [comment]
This would be better addressed to the support for the tidyverse package/project.
