### ISSUE TITLE
species assignment using UNITE

### ISSUE THREAD

**Issue by wittney-m** [benjjneb/dada2#1710]
I am using the UNITE database to assign species to my taxa matrix. I used this code:

taxa <- assignTaxonomy(seqtab.nochim, paste(path,"sh_general_release_dynamic_s_all_16.10.2022.fasta",sep = "/"),  multithread$
taxa <- addSpecies(taxa, paste(path, "sh_general_release_dynamic_s_all_16.10.2022.fasta", sep = "/"))

I received this error message:

UNITE fungal taxonomic reference detected.
Error in assignSpecies(seqs, refFasta = refFasta, allowMultiple = allowMultiple,  :
  Incorrect reference file format for assignSpecies (this looks like a file formatted for assignTaxonomy).
Calls: addSpecies -> assignSpecies

How do I make the file needed from the UNITE database for species assignment?

**Comment by benjjneb** [comment]
> How do I make the file needed from the UNITE database for species assignment?

We don't officially support species assignment using UNITE.
You would have to manually curate UNITE into the appropriate format (and probably enforce appropriate QC standards). See here for information on the `assignSpecies` format: https://benjjneb.github.io/dada2/training.html#formatting-custom-databases
