### ISSUE TITLE
fastq.gz files still contain primers after using cutadapt

### ISSUE THREAD

**Issue by chrissy005** [benjjneb/dada2#1712]
I am trying out your ITS-workflow tutorial in a stepwise manner using my own dataset by adapting it for 16S V4 reads  . However I encounter fastq reads with primer sequences still present after invoking cutadapt. 

I am using cutadapt in R (on a Windows system) to trim away primers from a NovaSeq 6000 -paired-end 250bp amplicon sequencing run. The 16S V4 region was targeted using the 515F-"GTGCCAGCMGCCGCGGTAA" and 806R- "GGACTACHVGGGTWTCTAAT" .

#The Cutadapt and Python version used : cutadapt 4.2 with Python 3.11.2

#Prior to running cutadapt, primer detection resulted in:

Forward Complement Reverse RevComp
#FWD.ForwardReads 15693 0 0 83
#FWD.ReverseReads 122 0 0 335
#REV.ForwardReads 19 0 0 9003
#REV.ReverseReads 2540 0 0 88

#After running cutadapt, primer detection resulted in:

Forward Complement Reverse RevComp
#FWD.ForwardReads 706 0 0 82
#FWD.ReverseReads 108 0 0 15
#REV.ForwardReads 18 0 0 160
#REV.ReverseReads 18 0 0 73

#This clearly shows that the primers remain untrimmed in many reads as the output should all be 0 as seen in your tutorial.

I am not sure how to proceed from here and would appreciate help to process these reads using cutadapt in R.

#Exact Command-line parameters used are as follows (which is similar to your tutorial):

#Pre-processing data for dada2 - remove sequences with Ns, cutadapt####

Get full paths for all files and save for downstream analyses
fnFs <- sort(list.files(SBW.TG.fq.r1.r2.fp, pattern="_1.fq.gz", full.names = TRUE))
fnRs <- sort(list.files(SBW.TG.fq.r1.r2.fp, pattern="_2.fq.gz", full.names = TRUE))

Extract sample names, assuming filenames have format: SAMPLENAME_XXX.fastq
sample.names <- sapply(strsplit(basename(fnFs), "_"), [, 1)

#Pre-filter to remove sequence reads with Ns

Name the N-filtered files to put them in filtN
fnFs.filtN <- file.path(preprocess.fp, "filtN", basename(fnFs))
fnRs.filtN <- file.path(preprocess.fp, "filtN", basename(fnRs))

Filter Ns from reads and put them into the filtN directory.
filterAndTrim(fnFs, fnFs.filtN, fnRs, fnRs.filtN, maxN = 0, multithread = FALSE)

CHANGE multithread to FALSE on Windows (here and elsewhere in the program)
Set up the primer sequences to pass along to cutadapt
FWD <- "GTGCCAGCMGCCGCGGTAA" ## CHANGE ME # this is 515f
REV <- "GGACTACHVGGGTWTCTAAT" ## CHANGE ME # this is 806r

Write a function that creates a list of all orientations of the primers
allOrients <- function(primer) {

Create all orientations of the input sequence
require(Biostrings)
dna <- DNAString(primer) # The Biostrings works w/ DNAString objects rather than character vectors
orients <- c(Forward = dna, Complement = complement(dna), Reverse = reverse(dna),
RevComp = reverseComplement(dna))
return(sapply(orients, toString)) # Convert back to character vector
}

Save the primer orientations to pass to cutadapt
FWD.orients <- allOrients(FWD)
REV.orients <- allOrients(REV)

Write a function that counts how many time primers appear in a sequence
primerHits <- function(primer, fn) {

Counts number of reads in which the primer is found
nhits <- vcountPattern(primer, sread(readFastq(fn)), fixed = FALSE)
return(sum(nhits > 0))
}

#Before running cutadapt, look at primer detection in all samples. There may be some primers here, we will remove them below using cutadapt.
rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.filtN),
FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.filtN),
REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.filtN),
REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.filtN))

##Result copied from console for checking in all reads:

Forward Complement Reverse RevComp
#FWD.ForwardReads 15693 0 0 83
#FWD.ReverseReads 122 0 0 335
#REV.ForwardReads 19 0 0 9003
#REV.ReverseReads 2540 0 0 88

Create directory to hold the output from cutadapt.
#prep files for cutadapt
fnFs.cut <- file.path(trimmed.fp, basename(fnFs))
fnRs.cut <- file.path(trimmed.fp, basename(fnRs))

Save the reverse complements of the primers to variables
FWD.RC <- dada2:::rc(FWD)
REV.RC <- dada2:::rc(REV)

Create the cutadapt flags
Trim FWD and the reverse-complement of REV off of R1 (forward reads)
R1.flags <- paste("-g", FWD, "-a", REV.RC, "--minimum-length 50")

Trim REV and the reverse-complement of FWD off of R2 (reverse reads)
R2.flags <- paste("-G", REV, "-A", FWD.RC, "--minimum-length 50")

Run Cutadapt
for (i in seq_along(fnFs)) {
system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
"-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
fnFs.filtN[i], fnRs.filtN[i])) # input files
}

As a sanity check,check for primers in the first cutadapt-ed sample:
rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.cut),
FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.cut),
REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.cut),
REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.cut))

#Results

Forward Complement Reverse RevComp
#FWD.ForwardReads 706 0 0 82
#FWD.ReverseReads 108 0 0 15
#REV.ForwardReads 18 0 0 160
#REV.ReverseReads 18 0 0 73

#The output of cutadapt during primer trimming was as follows:

This is cutadapt 4.2 with Python 3.11.2
Command line parameters: -g GTGCCAGCMGCCGCGGTAA -a ATTAGAWACCCBDGTAGTCC --minimum-length 50 -G GGACTACHVGGGTWTCTAAT -A TTACCGCGGCKGCTGGCAC --minimum-length 50 -n 2 -o processed/01_preprocess/trimmed.cutadapt/D5_1.fq.gz -p processed/01_preprocess/trimmed.cutadapt/D5_2.fq.gz processed/01_preprocess/filtN/D5_1.fq.gz processed/01_preprocess/filtN/D5_2.fq.gz
Processing paired-end reads on 1 core ...
Finished in 4.988 s (27.903 µs/read; 2.15 M reads/minute).

=== Summary ===

Total read pairs processed: 178,762
Read 1 with adapter: 260 (0.1%)
Read 2 with adapter: 646 (0.4%)

== Read fate breakdown ==
Pairs that were too short: 329 (0.2%)
Pairs written (passing filters): 178,433 (99.8%)

Total basepairs processed: 71,446,981 bp
Read 1: 35,723,153 bp
Read 2: 35,723,828 bp
Total written (filtered): 71,357,954 bp (99.9%)
Read 1: 35,679,766 bp
Read 2: 35,678,188 bp

=== First read: Adapter 1 ===

Sequence: GTGCCAGCMGCCGCGGTAA; Type: regular 5'; Length: 19; Trimmed: 172 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-19 bp: 1

Overview of removed sequences
length count expect max.err error counts
3 9 2793.2 0 9
18 72 0.0 1 0 72
20 73 0.0 1 0 73
47 2 0.0 1 2
51 3 0.0 1 3
52 3 0.0 1 3
53 5 0.0 1 5
54 3 0.0 1 3
55 1 0.0 1 1
173 1 0.0 1 1

=== First read: Adapter 2 ===

Sequence: ATTAGAWACCCBDGTAGTCC; Type: regular 3'; Length: 20; Trimmed: 91 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-19 bp: 1; 20 bp: 2

Bases preceding removed adapters:
A: 7.7%
C: 1.1%
G: 90.1%
T: 0.0%
none/other: 1.1%
WARNING:
The adapter is preceded by 'G' extremely often.
The provided adapter sequence could be incomplete at its 5' end.
Ignore this warning when trimming primers.

Overview of removed sequences
length count expect max.err error counts
3 21 2793.2 0 21
5 3 174.6 0 3
6 4 43.6 0 4
10 6 0.2 1 6
12 14 0.0 1 10 4
14 11 0.0 1 11
19 1 0.0 1 1
26 14 0.0 2 13 1
27 2 0.0 2 2
28 4 0.0 2 4
29 1 0.0 2 1
30 4 0.0 2 4
35 1 0.0 2 0 1
37 1 0.0 2 1
93 1 0.0 2 1
113 2 0.0 2 1 0 1
122 1 0.0 2 1

=== Second read: Adapter 3 ===

Sequence: GGACTACHVGGGTWTCTAAT; Type: regular 5'; Length: 20; Trimmed: 168 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-19 bp: 1; 20 bp: 2

Overview of removed sequences
length count expect max.err error counts
18 5 0.0 1 0 0 5
19 78 0.0 1 0 76 2
21 83 0.0 2 0 81 2
51 1 0.0 2 1
55 1 0.0 2 0 1

=== Second read: Adapter 4 ===

Sequence: TTACCGCGGCKGCTGGCAC; Type: regular 3'; Length: 19; Trimmed: 486 times

Minimum overlap: 3
No. of allowed errors:
1-9 bp: 0; 10-19 bp: 1

Bases preceding removed adapters:
A: 1.0%
C: 4.3%
G: 0.0%
T: 94.0%
none/other: 0.6%
WARNING:
The adapter is preceded by 'T' extremely often.
The provided adapter sequence could be incomplete at its 5' end.
Ignore this warning when trimming primers.

Overview of removed sequences
length count expect max.err error counts
3 151 2793.2 0 151
4 3 698.3 0 3
5 303 174.6 0 303
6 2 43.6 0 2
9 3 0.7 0 0 3
10 11 0.2 1 0 11
12 3 0.0 1 3
14 1 0.0 1 0 1
28 1 0.0 1 0 1
43 1 0.0 1 0 1
47 2 0.0 1 0 2
73 1 0.0 1 0 1
113 1 0.0 1 0 1
122 1 0.0 1 0 1
153 1 0.0 1 1
200 1 0.0 1 0 1

WARNING:
One or more of your adapter sequences may be incomplete.
Please see the detailed output above.

Some of the raw fastq.gz forward and reverse files are attached:
[D2_2.fq.gz](https://github.com/benjjneb/dada2/files/10899182/D2_2.fq.gz)
[D3_1.fq.gz](https://github.com/benjjneb/dada2/files/10899184/D3_1.fq.gz)
[D3_2.fq.gz](https://github.com/benjjneb/dada2/files/10899186/D3_2.fq.gz)
[A1_1.fq.gz](https://github.com/benjjneb/dada2/files/10899187/A1_1.fq.gz)
[A1_2.fq.gz](https://github.com/benjjneb/dada2/files/10899188/A1_2.fq.gz)
[A2_1.fq.gz](https://github.com/benjjneb/dada2/files/10899189/A2_1.fq.gz)
[A2_2.fq.gz](https://github.com/benjjneb/dada2/files/10899190/A2_2.fq.gz)
[A3_1.fq.gz](https://github.com/benjjneb/dada2/files/10899191/A3_1.fq.gz)
[A3_2.fq.gz](https://github.com/benjjneb/dada2/files/10899192/A3_2.fq.gz)
[B1_1.fq.gz](https://github.com/benjjneb/dada2/files/10899194/B1_1.fq.gz)
[B1_2.fq.gz](https://github.com/benjjneb/dada2/files/10899195/B1_2.fq.gz)
[B2_1.fq.gz](https://github.com/benjjneb/dada2/files/10899197/B2_1.fq.gz)
[B2_2.fq.gz](https://github.com/benjjneb/dada2/files/10899198/B2_2.fq.gz)
[B3_1.fq.gz](https://github.com/benjjneb/dada2/files/10899200/B3_1.fq.gz)
[B3_2.fq.gz](https://github.com/benjjneb/dada2/files/10899201/B3_2.fq.gz)
[C1_1.fq.gz](https://github.com/benjjneb/dada2/files/10899202/C1_1.fq.gz)
[C1_2.fq.gz](https://github.com/benjjneb/dada2/files/10899203/C1_2.fq.gz)
[C3_1.fq.gz](https://github.com/benjjneb/dada2/files/10899205/C3_1.fq.gz)
[C3_2.fq.gz](https://github.com/benjjneb/dada2/files/10899206/C3_2.fq.gz)
[D1_1.fq.gz](https://github.com/benjjneb/dada2/files/10899207/D1_1.fq.gz)
[D1_2.fq.gz](https://github.com/benjjneb/dada2/files/10899208/D1_2.fq.gz)
[D2_1.fq.gz](https://github.com/benjjneb/dada2/files/10899209/D2_1.fq.gz)

Some of the primer trimmed fastq files are as follows:
[D2_2.fq.gz](https://github.com/benjjneb/dada2/files/10899233/D2_2.fq.gz)
[D3_1.fq.gz](https://github.com/benjjneb/dada2/files/10899235/D3_1.fq.gz)
[D3_2.fq.gz](https://github.com/benjjneb/dada2/files/10899236/D3_2.fq.gz)
[A1_1.fq.gz](https://github.com/benjjneb/dada2/files/10899237/A1_1.fq.gz)
[A1_2.fq.gz](https://github.com/benjjneb/dada2/files/10899239/A1_2.fq.gz)
[A2_1.fq.gz](https://github.com/benjjneb/dada2/files/10899240/A2_1.fq.gz)
[A2_2.fq.gz](https://github.com/benjjneb/dada2/files/10899241/A2_2.fq.gz)
[A3_1.fq.gz](https://github.com/benjjneb/dada2/files/10899244/A3_1.fq.gz)
[A3_2.fq.gz](https://github.com/benjjneb/dada2/files/10899245/A3_2.fq.gz)
[B1_1.fq.gz](https://github.com/benjjneb/dada2/files/10899246/B1_1.fq.gz)
[B1_2.fq.gz](https://github.com/benjjneb/dada2/files/10899248/B1_2.fq.gz)
[B2_1.fq.gz](https://github.com/benjjneb/dada2/files/10899249/B2_1.fq.gz)
[B2_2.fq.gz](https://github.com/benjjneb/dada2/files/10899252/B2_2.fq.gz)
[B3_1.fq.gz](https://github.com/benjjneb/dada2/files/10899254/B3_1.fq.gz)
[B3_2.fq.gz](https://github.com/benjjneb/dada2/files/10899255/B3_2.fq.gz)
[C1_1.fq.gz](https://github.com/benjjneb/dada2/files/10899256/C1_1.fq.gz)
[C1_2.fq.gz](https://github.com/benjjneb/dada2/files/10899257/C1_2.fq.gz)
[C3_1.fq.gz](https://github.com/benjjneb/dada2/files/10899258/C3_1.fq.gz)
[C3_2.fq.gz](https://github.com/benjjneb/dada2/files/10899260/C3_2.fq.gz)
[D1_1.fq.gz](https://github.com/benjjneb/dada2/files/10899261/D1_1.fq.gz)
[D1_2.fq.gz](https://github.com/benjjneb/dada2/files/10899263/D1_2.fq.gz)
[D2_1.fq.gz](https://github.com/benjjneb/dada2/files/10899265/D2_1.fq.gz)

**Comment by hhollandmoritz** [comment]
Hi @chrissy005!

I noticed you also posted your question here. You may get an answer here, since I'm sure many users of this repository are also users of Cutadapt, but since Cutadapt is not technically part of dada2, it's probably not the best place to find an answer for this question. 

(For context, in the Ernakovich lab, we use Cutadapt as a pre-filtering step in our in-house version of the dada2 pipeline but it's not developed by the folks in the dada2 team. And I don't want them being held to account for my poor coding practices! :D ).

Your original post on the Ernakovich lab pipeline, is probably the best place for your question and I've [replied](https://github.com/ErnakovichLab/dada2_ernakovichlab/issues/13#issuecomment-1456403572) over there so I think this issue can probably be closed on this repository.

Cheers,
Hannah

**Comment by chrissy005** [comment]
Hello Hannah,
Thank you for your response here. Did not realize that the codes in the ITS-workflow were written by you. Since I found it here, I thought they may have worked through it similarly too. I will try out your suggestions on the other post and respond there then.

Thank you for the details and your time

**Comment by hhollandmoritz** [comment]
Hi @chrissy005,

I didn't create the ITS-workflow codes. :) That was done by the lovely folks here at dada2. But I did create the dada2_ernakovich version of the pipeline - which I think is the code that's giving you trouble. The main differences are just in the implementation (novaseq, slurm-scritps, etc) and the specific cutadapt calls.
