### ISSUE TITLE
the assign taxonomy step from dada2 (big data) aborts my R session

### ISSUE THREAD

**Issue by ELK929** [benjjneb/dada2#1713]
Hi! 
I'm clueless on why my R session aborts every time I run the assignTaxonomy step from the dada2 pipeline (big data)
I work via a supercomputer (hpc), so my computer is not the problem. Currently, I'm trying to optimize my pipeline with only 1 sample in the running (about 5Mb, after trimming only 3.6Mb). I use the SILVA database (silva_nr99_v138.1_wSpecies_train_set.fa.gz) and dada2 v1.24.0

Does anyone have an idea what could be the problem?

**Comment by benjjneb** [comment]
Try also testing with the other provided reference files, e.g. RDP or Silva w/o species. Does that change the abort issue?

You might also want to double-check the amount of memory you are requesting (and being allocated?) for your hpc jobs. On some job submissions systems, default memory allocations are pretty small.

**Comment by benjjneb** [comment]
Please try with the appropriate RDP classifier training fasta: [rdp_train_set_18.fa.gz](https://zenodo.org/record/4310151/files/rdp_train_set_18.fa.gz?download=1)

**Comment by ELK929** [comment]
with that RDP, it does work! But I would prefer to use the Silva database since it would be a better fit for my type of samples.

**Comment by benjjneb** [comment]
This suggests that you don't have enough memory. The largest contributor to the memory usage of `assignTaxonomy` is the size/complexity of the reference data. Silva requires ~16GB, and 32GB is even better.

I'm not sure how you are running dada2 on your cluster, but default interactive sessions and job submissions often only get small memory allocations on many HPCs. You must request more memory to have access to it for your computation. So I would look into how memory resources are allocated in your hpc, and figure out how to request 32GB+ for your interactive session or job submission.
