### ISSUE TITLE
High loss of reads in certain samples following chimera removal

### ISSUE THREAD

**Issue by pig-raffles** [benjjneb/dada2#1715]
Hi,

I have run through the tutorial pipeline for Dada2 and whilst I get good read retention overall (92%+ of merged reads), certain samples show very high drop-offs in read numbers as you go thru the pipeline, with the majority being lost at the remove chimeras stage.

The worst of these samples show only 5-20% read retention. I have tried changing the “minFoldParentOverAbundance” parameter from the default to the values of 4, 6, 8 as recommended in this forum. However, this did nothing to really affect the numbers of reads retained for these samples. So, the reads being removed likely are true chimeras.

Unfortunately, some of these affected samples are quite important to my data set. So I guess my question would be: should I retain these samples for downstream analysis or remove them? Will the retained reads in these samples represent a hopelessly biased view of the microbiome?

Thanks,

Alan

**Comment by benjjneb** [comment]
[From the dada2 tutorial](https://benjjneb.github.io/dada2/tutorial.html#remove-chimeras):

> Considerations for your own data: Most of your reads should remain after chimera removal (it is not uncommon for a majority of sequence variants to be removed though). If most of your reads were removed as chimeric, upstream processing may need to be revisited. In almost all cases this is caused by primer sequences with ambiguous nucleotides that were not removed prior to beginning the DADA2 pipeline.

**Comment by pig-raffles** [comment]
Thanks for getting back to me so quickly. 

I used EMP 16S V4 primers and I thought that with these types of primers, the primer sequence could not contaminate the reads

**Comment by benjjneb** [comment]
In the most common forms of libraries created from the EMP V4 protocol, the primers aren't sequenced. But, given the high loss at the chimera step which almost always (in practice) is associated with unremoved primers, detailed verification on whether this is true for your data is appropriate.

The easiest thing to do is to just open up an example fastq file or two, look at the start of the first few sequences, and see if the forward primer is there at the start of the read. If that is inconclusive, then using t[he approaches for identifying primers in reads described in the dada2 ITS tutorial](https://benjjneb.github.io/dada2/ITS_workflow.html#identify-primers) can be an effective way to learn more. Finally, double-checking with the folks who generated the data is appropriate: Were the libraries definitely generated using the EMP V4 protocol? Or were there changes/elaborations?

**Comment by pig-raffles** [comment]
Hi,

I followed your advice and went through the "approaches for identifying primers in reads" tutorial. The counts of the number of times each primer appears gave the following output:

# Forward Complement Reverse RevComp
# FWD.ForwardReads       0          0       0       0
# FWD.ReverseReads       0          0       0   10959
# REV.ForwardReads       0          0       0   13477
# REV.ReverseReads       0          0       0       0

I have now proceeded with using to Cutadapt to remove these primer sequences. But how should I interpret this result: is this due to read-thru when the 16S V4 fragment is short? This might explain why I found EMP primers in that orientation as they are not supposed to be sequenced.

Moving forward, I will carry out the Dada2 workflow using the primer-decontaminated sequences. As primer contamination affected certain samples way more than others, should I still keep an eye on these samples?

Thanks again,

Alan

**Comment by benjjneb** [comment]
See post here: https://github.com/benjjneb/dada2/issues/1721#issuecomment-1490909591

In short, you need to truncate your reads to <=250nts to avoid read-through into the other primer and adapter sequences.
