### ISSUE TITLE
Error rates could not be estimated

### ISSUE THREAD

**Issue by MiriJ15** [benjjneb/dada2#1716]
I am working on a shotgun pair-end dataset and having some issues after the filter and trim step. My sequences are 150bp long and I have tried setting trunclen to different values below and above 150, but I always get the issue listed below:
![image](https://user-images.githubusercontent.com/86243044/224472333-e69159b4-79b4-4ce2-9026-fe2d34668315.png)

Not really sure what might be causing this issue.

**Comment by benjjneb** [comment]
DADA2 is not intended for shotgun metagenomics data, only amplicon sequencing data.

**Comment by MiriJ15** [comment]
thank you so much!
