### ISSUE TITLE
Error in .standalone_types_check_dot_call(ffi_standalone_check_number_1.0.7,  :    object 'ffi_standalone_check_number_1.0.7' not found

### ISSUE THREAD

**Issue by sudhan2709** [benjjneb/dada2#1717]
Error in .standalone_types_check_dot_call(ffi_standalone_check_number_1.0.7,  : 
  object 'ffi_standalone_check_number_1.0.7' not found
In addition: Warning messages:
1: In serialize(data, node$con) :
  'package:stats' may not be available when loading
2: The `<scale>` argument of `guides()` cannot be `FALSE`. Use
"none" instead as of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the dada2 package.
  Please report the issue at
  <https://github.com/benjjneb/dada2/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this
warning was generated.

**Comment by benjjneb** [comment]
> Error in .standalone_types_check_dot_call(ffi_standalone_check_number_1.0.7, :
object 'ffi_standalone_check_number_1.0.7' not found

Dunno what this is about.

> In addition: Warning messages:
> 1: In serialize(data, node$con) :
> 'package:stats' may not be available when loading
> 2: The <scale> argument of guides() cannot be FALSE. Use
> "none" instead as of ggplot2 3.3.4.

This warning is fixed in the next package release.
