### ISSUE TITLE
How to import dada2 files from R to QIIME2

### ISSUE THREAD

**Issue by dixi06** [benjjneb/dada2#1718]
Hello sir,

I have done filtering, merging and chimera removal steps in dada2 using R package. Now I would like to use q2 classifier for taxonomy assignment in QIIME2.  Can you please let me know how can I import the dada2 FILES from R to QIIME2?

Thanks.

**Comment by benjjneb** [comment]
I would recommend searching qiime2 to dada2 either via google, or in the qiime2 forum. There are several examples available.

**Comment by dixi06** [comment]
> I would recommend searching qiime2 to dada2 either via google, or in the qiime2 forum. There are several examples available.

 I want to export seqtab file from R to QIIME2. Is writeFasta a good option after doing getSequences?
