### ISSUE TITLE
The links to the reference databases are invalid

### ISSUE THREAD

**Issue by Suntoa-hub** [benjjneb/dada2#1719]
Hi,
When I performed `Assign taxonomy`, I found that the links to the reference databases were invalid. Is there any solution?
Thanks.

**Comment by benjjneb** [comment]
Could you provide the exact command that you executed and the exact error message?

My guess is that you have not defined the file path to the reference fasta file correctly. That can easily be checked by looking at the output of `file.exists(fn)` where `fn` is the variable where the filepath to the reference fasta is stored.
