### ISSUE TITLE
Error rates cannot be estimated in high quality data.

### ISSUE THREAD

**Issue by robbueck** [benjjneb/dada2#1720]
I'm running dada2 on some high quality reads where all quality scores are the same (30).
![image](https://user-images.githubusercontent.com/23408662/227907769-d86b64ca-1b39-4fba-adff-488848060107.png)
Estimating the error rates gives me:
Error in getErrors(err, enforce = TRUE) : Error matrix is NULL.
It works when I set USE_QUALS=FALSE
From my understanding of dada2 the problem here is the high/equal quality? When I run error estimation with USE_QUALS=FALSE, I get very low error rates. Does this seem reasonable or am I missing something here?
![image](https://user-images.githubusercontent.com/23408662/227908364-5e7b4071-08a6-4641-8c24-a264f3032d74.png)

**Comment by benjjneb** [comment]
I'm not sure what kind of sequencing instrument generates all the same quality score, or maybe this is simulated data?

In any case, when all the quality scores are the same, there is no information in the quality scores, so `USE_QUALS=FALSE` is the correct way to go. As to whether ~0.001 error rates are reasonable, that depends on how this data was generated, e.g. the simulation parameters or whatever.

**Comment by robbueck** [comment]
The data is from a published study (https://www.ebi.ac.uk/ena/browser/view/PRJNA833324), it's supposed to be MiSeq-data. In total it's around 41.650.000 reads. When I run dada() on the data, it consistently crashes with:
` *** caught segfault *** 
address (nil), cause 'memory not mapped'
`
even when I run it on 5 cores with 200 GB per core.

**Comment by benjjneb** [comment]
Note for later: Data with all Q30 probably comes from accessing data from the SRA via the web interface, which returns "SRALite" data format with all quality scores replaced with Q30. The real sequencing data can be obtained using sra-toolkit.
