### ISSUE TITLE
Question about umi 'aware' abundance 'correction'

### ISSUE THREAD

**Issue by louellette** [benjjneb/dada2#1722]
I see where dada2 does not do UMI aware error correction. I would like to take advantage of dada2 error correction but also take advantage of the UMI to tell me original molecule abundance prior to PCR.

I wonder if it makes sense to map the ASVs back to the dereplicated reads and then back to the raw reads (where the UMI is in the read-id) and set the abundance of the ASV to the number of unique UMI in the raw reads that map back to the ASV.

Thanks so much in advance for your insight.
*

**Comment by benjjneb** [comment]
I have not worked much with UMI data, but what you describe seems reasonable to me.

Mapping from ASVs back to the original reads is possible using the `$map` components of the dada-class and derep-class objects output by the `dada` and `derepFastq` functions respectively.
