### ISSUE TITLE
ITS2 trimming issues

### ISSUE THREAD

**Issue by peggy17688** [benjjneb/dada2#1723]
Hi Benjamin,

Peggy here. Thank you for the help the other time for the filterAndTrim issues. 

This time, also another trimming issues, but with ITS2 sequences. I followed your protocol for the ITS pipeline, including the use of cutadapt. However, 50% of the reads were removed after the filterAndTrim process (even when I specify minLen = 0), I checked that the primers were already removed completely as well. I was just wondering if I could use the TrimLeft function (minus TruncLen) instead of cutadapt to retain the reads? 

I actually had an earlier file which worked fine with cutadapt, but was wondering maybe this time because there were 2 species for this library which caused the problem.

I have attached images of the sequence quality and the read numbers after trimming with cutadapt.

Thanks in advance for the help!

Best,
Peggy

![image](https://user-images.githubusercontent.com/64371748/229317079-6c024ebc-6b79-477f-a982-535cda500a1a.png)

![image](https://user-images.githubusercontent.com/64371748/229317133-66a69d77-e897-4696-971b-0f4bf8f1a498.png)

reads.in reads.out
1201K1ma_ITS2_S26_R1_001.fastq.gz    89337     34885
1201K1pa_ITS2_S74_R1_001.fastq.gz    86173     26931
1201K2pa_ITS2_S86_R1_001.fastq.gz    71748      8663
1201K3ma_ITS2_S38_R1_001.fastq.gz   125259     50783
1201K3pa_ITS2_S3_R1_001.fastq.gz    105200     41949
1201K4ma_ITS2_S50_R1_001.fastq.gz   106018     42317

**Comment by benjjneb** [comment]
What is the exact `filterAndTrim` command you are using?

> because there were 2 species for this library

What does this mean? This is from a test dataset with two species in it?
