### ISSUE TITLE
Repetitive de chimerism with similar loss ratio

### ISSUE THREAD

**Issue by rainjy** [benjjneb/dada2#1724]
First, according to the mapping relationship, the non-chimeric data ID is extracted to extract the original sequence.
Second, the extracted sequence is used as an input, and the dada2 is run again, and the non-chimera sequence ratio is about the same as the first time
Are the non-chimera sequences change?

**Comment by benjjneb** [comment]
I don't understand the question here.

**Comment by rainjy** [comment]
My question, (myflow, filterAndTrim---derepFastq----dada---mergePairs--removeBimeraDenovo)
first, according to the mapping relationship， such as (derepF$uniques, dadaF$clustering, dadaF$map, mergeFmap, mergeRmap)，I extracted the non-chimera sequences from raw data
second, use the non-chimera sequences as inputs for  next flow (as first flow),  the non-chimera ration still with similar loss ratio

some code :
out <- suppressWarnings(filterAndTrim(fnF, filtsF, fnR, filtsR, compress = F, multithread = 8, minLen = 5, truncLen=c(0, 0), trimLeft=c(0, 0), maxEE=c(2, 2), truncQ = 2, rm.phix=TRUE ))
derep1 = derepFastq(filtsF)  # raw->1500 uniques->896
derep2 = derepFastq(filtsR)
errF = suppressWarnings(learnErrors(filtsF, nreads=200000, multithread=4))
errR = suppressWarnings(learnErrors(filtsR, nreads=200000, multithread=4))
uniqmapF = lapply(1:length(derep1$uniques), function(x) which(derep1$map == x))
uniqmapR = lapply(1:length(derep2$uniques), function(x) which(derep2$map == x))
dadaF <- dada(derep1, err = errF, multithread = 4,DETECT_SINGLETONS=TRUE )
dadaR <- dada(derep2, err = errR, multithread = 4,DETECT_SINGLETONS=TRUE)
denoisedF <- getN(dadaF)

clustermapToraw <- function(clustmap, uniqmap) {
    clustmapraw = list()
    for (i in 1:length(clustmap)) {
        clustmapraw[[i]] = unlist(lapply(clustmap[[i]], function(y) uniqmap[[y]]))
    }
    return(clustmapraw)
}
## map: cluster To uniq
clustmapF = lapply(1:nrow(dadaF$clustering), function(x) which(dadaF$map == x))  # key 1:9 value:which896
clustmapR = lapply(1:nrow(dadaR$clustering), function(x) which(dadaR$map == x))

clustmapraw_F = clustermapToraw(clustmapF, uniqmapF)
clustmapraw_R = clustermapToraw(clustmapR, uniqmapR)
cluster1reads = length(unlist(clustmapraw_F))
cluster2reads = length(unlist(clustmapraw_R))

merger <- mergePairs(dadaF, derep1, dadaR, derep2, minOverlap = 8, maxMismatch = 2)
mergerFmap = lapply(merger$forward, function(x) clustmapraw_F[[x]])
mergerRmap = lapply(merger$reverse, function(x) clustmapraw_R[[x]])

for (i in 1:length(mergerFmap)) {
    intersectrawi = intersect(mergerFmap[[i]], mergerRmap[[i]])
    if(length(intersectrawi)>0){
    mergerFmap[[i]] = intersectrawi
    mergerRmap[[i]] = intersectrawi
    }
}
seqtab <- makeSequenceTable(merger)  # merger$sequence has dup
ttt = removeBimeraDenovo(seqtab, method = "consensus", minFoldParentOverAbundance = 1, multithread = 8)
nochimeraorder = which(merger$sequence %in% colnames(ttt))
nochimeraFmap = lapply(nochimeraorder, function(x) mergerFmap[[x]])
nochimeraRmap = lapply(nochimeraorder, function(x) mergerRmap[[x]])
