### ISSUE TITLE
Windows multithreading error

### ISSUE THREAD

**Issue by lalma** [benjjneb/dada2#1725]
Its possible this has been asked already, but is there any way to get around this error when running removeBimeraDenovo and filterAndTrim functions on a windows machine? ...

**Multithreading has been DISABLED, as forking is not supported on .Platform$OS.type 'windows'**

**Comment by benjjneb** [comment]
> Not an error. Just a warning that mulithreading of `filterAndTrim` was disabled because it isn't supported on Windwos. multithreading in other commands will work as expected.

https://github.com/benjjneb/dada2/issues/1362#issuecomment-1080955949
