### ISSUE TITLE
Taxonomy assignment, reads alignment and mapping?

### ISSUE THREAD

**Issue by marwa38** [benjjneb/dada2#1726]
Hey
Just kind of confused about terminologies differences between reads alignment and mapping against SILVA for example. When to use any of those terms?
DADA2 tutorial presented taxonomy assignment step without mentioning if that is a kind of alignment or mapping if there is differences between both terms?
For the phylogenetic tree creation in DADA2 tutorial, DECIPHER have been used and alignment term was used alongside. 
Thanks 
Marwa

**Comment by benjjneb** [comment]
I'm not entirely clear on the question here. If it is the methodology behind `assignTaxonomy`, that function is a reimplentation of the naive Bayesian classifier method: https://journals.asm.org/doi/full/10.1128/AEM.00062-07

"taxonomic assignment" or "taxonomic classification" would be an appropriate terminology for what the naive Bayesian classifier does.
