### ISSUE TITLE
Trimming suggestions/practice with DADA2

### ISSUE THREAD

**Issue by LennWhy** [benjjneb/dada2#1727]
Hi,

I have a naive question about how filtering parameters (especially trimming) can affect the final results depending on the number of samples being analyzed in a directory using the DADA2 pipeline. I have analyzed a directory with 40 samples for which the median trimming cut-offs were averaged to be 240 (F) and 180 (R). This first analysis resulted in a set of ASVs that were assigned to a species list based on a custom database (using rBLAST). In a second run, I re-did the same analysis but on directory with a randomized subsample of 9 (from the 40 original), for which median trimming cut-offs changed a bit (220, 177), and the final results for those 9 samples changed (vs. when I analyzed in with all 40 together) That is, for some samples in the 9 sample analysis, new species were assigned, that were not previously present when I analyzed all 40 samples together. I must also say that some new species are very closely related to those from the 40 sample analysis.

In any case, I was wondering how trimming differences based on the number of samples being analyzed might affect these result variation. Is it better to analyzed each sample individually rather in a batch (such as in a directory) for which a median trim cut off is calculated? Do you have any suggestions to make sure that results remain consistent depending on the number of samples being analyzed?

Forgive my ignorance, and thanks for reading.

**Comment by benjjneb** [comment]
> Is it better to analyzed each sample individually rather in a batch (such as in a directory) for which a median trim cut off is calculated? Do you have any suggestions to make sure that results remain consistent depending on the number of samples being analyzed?

I would recommend that truncation lengths and other trimming parameters be selected once for an entire study, and not adaptively changed for each batch of samples that is being analyzed.
