### ISSUE TITLE
learnErrors 

### ISSUE THREAD

**Issue by Pablo-UY** [benjjneb/dada2#1730]
Hi everyone.
I'm exploring a GBS metagenomics dataset, where the sequences are SE from Illumina, and I'm getting this error profile plot.
Reads have a wide range distribution from 40bp to 90bp, but mostly 90 bp.
I only trimmed by Q and min length and then: 
errF = learnErrors(filtered_R, multithread = T)
Could be this the main problem in obtaining these results? or is it due to the nature of the sequences?

Thanks.
Pablo
![Plot_errors](https://user-images.githubusercontent.com/117089370/233521289-6964029a-c7c5-4061-892f-1017294e7dff.png)

**Comment by benjjneb** [comment]
What sequencing instrument and read size are you using? (e.g. HiSeq 1x100)

> Reads have a wide range distribution from 40bp to 90bp, but mostly 90 bp.

The raw reads are varying in size? Or this is after some sort of trimming step?
What does an example sample `plotQualityProfile` look like?

**Comment by Pablo-UY** [comment]
It was sequenced in a Novaseq 1x91.
Yes. Raw reads vary in size (15-91) and I trimmed to keep sequences more than 40pb.
plotQualityProfile looks like this:
![FASTQ_crudo y Filtrado](https://user-images.githubusercontent.com/117089370/233694174-a58bac3c-503d-4aaf-87fc-0da371bf846c.png)

**Comment by benjjneb** [comment]
Probably part of what you are seeing is the less-good fit of the error model for binned quality score data like NovaSeq produces, see more here: https://github.com/benjjneb/dada2/issues/1307

> Yes. Raw reads vary in size (15-91)

This is still concerning to me though. Typically Illumina raw reads are all of uniform length. If there is a step that is introducing random length variation (e.g. read-by-read truncation at a specific quality score threshold) then this will reduce the sensitivity of dada2 and hurt its ability to accurately infer the error model.
