### ISSUE TITLE
Issue FilterAndTrim step, Error in add(raw()) : internal: buf != <newline>

### ISSUE THREAD

**Issue by UsernameUrie** [benjjneb/dada2#1731]
Hello, 

I have an issu with my data when running the filterAndTrim step:

R1_R2_filt = filterAndTrim(fwd=file.path(pathF, fastqFs), 
                           filt=file.path(filtpathF, fastqFs),
                           rev=file.path(pathR, fastqRs),
                           filt.rev=file.path(filtpathR, fastqRs),
                           trimLeft = c(R1_primers, R2_primers),
                           truncLen=c(240,190), maxEE=2, truncQ=5,
                           mutithread = TRUE,
                           compress=TRUE, verbose=TRUE)

error message: Error in add(raw()) : internal: buf != <newline>

I have tried to look in the previous issues and tried the solutions proposed in Error in filterAndTrim #285 from Jul 19, 2017. However, it does not fix my problem. I tried the ShortRead package, the multithread=FALSE, and even re-decompressed the original files.

Weirdly, once the error stop the calculations at a specific sample, if I remove the samples from fastqFs and fastqRs that were already calculated, the calculs successfully run from the  specific sample and for a while. Then again it stops at a different number of samples processed and I can partially run successfully the step with all my samples. Thus, I don't seem to have an issue with any specific sample. I don't seem neither to have an issue with the time of run, nor the memory available in the environment. 

I have checked all the packages updates, R and RStudio too, I tried with an older version of R and RStudio and the problem remains identical. I have previously runned the same script from other datas (with lower sequencing depths) without any issues.

Have you ever seen such issue? And by any chance, do you know how I can fix it?

Thank you very much for your time and attention.
Urie

**Comment by benjjneb** [comment]
As mentioned in #285, previous examples of this with DADA2 came down to malformed fastq files.

> Weirdly, once the error stop the calculations at a specific sample, if I remove the samples from fastqFs and fastqRs that were already calculated, the calculs successfully run from the specific sample and for a while.

If I'm reading this correctly, this behavior suggests there is something about that specific sample fastq files that is causing this problem.

> Then again it stops at a different number of samples processed and I can partially run successfully the step with all my samples. Thus, I don't seem to have an issue with any specific sample.

I don't follow this conclusion. From what I am understanding most of your samples run fine? So there may be multiple malformed samples, but once those are identified and removed then processing should proceed as normal on the rest.
