### ISSUE TITLE
Illumina sequencing only or also sanger sequencing or nanopore sequencing?

### ISSUE THREAD

**Issue by marwa38** [benjjneb/dada2#1733]
asking for a friend

Could you please let me know if I could run the dada2 workflow for Sanger sequencing or nanopore sequencing?

Thanks

**Comment by benjjneb** [comment]
It's not Illumina only, DADA2 also works with e.g. PacBio HiFi, LoopSeq, pyrosequencing (now defunct) etc.

However, it does not work with Sanger sequencing or nanopore sequencing at this time. We are keeping an eye on ONT progress though, and if error rates there continue to drop, it could be a possiblity in the future.
