### ISSUE TITLE
18S Reverse-Complement Error ( FWD.RC <- dada2:::rc(FWD) )

### ISSUE THREAD

**Issue by PGR23** [benjjneb/dada2#1734]
Hello, any assistance is appreciated. I am working with 23S data that is 250bp long. Since, this is on the shorter end I have been using the 18S instructions of looking for primer matches in more orientations of the data. Every time I try to run the reverse-complement for the forward or reverse primers it gives me an error about how it is not formatted according to IUPAC. The reverse-complements are being formatted "primer-rc" and the "-" character is what causes my error. Below is the code I am using. How can I fix this? 

path.cut <- file.path(path, "cutadapt")               
if(!dir.exists(path.cut)) dir.create(path.cut)
fnFs.cut <- file.path(path.cut, basename(fnFs))
fnRs.cut <- file.path(path.cut, basename(fnRs))
# It doesn't like how the reverse-compliments are written for the primers. Problem HERE
FWD.RC <- dada2:::rc(FWD)
REV.RC <- dada2:::rc(REV)

**Comment by benjjneb** [comment]
What is the output of `print(FWD)` and `print(REV)`?

**Comment by benjjneb** [comment]
So, the previous error went away... how?

This new error is being caused by a malformed command-line argument. Somehow no space is being put between the flags and the arguments to those flags in your `system2` call. That is:

```
-g^GGACAGAAAGACCCTATGAA-aCTCTAGGGATAACAGGCTGA
``

should be

```
-g ^GGACAGAAAGACCCTATGAA -a CTCTAGGGATAACAGGCTGA
```

Maybe you have malformed your R1.flags and R2.flags values. What does `print(R1.flags)` and `print(R2.flags)` look like? What were the command that you ran to generate those variables?

**Comment by PGR23** [comment]
Thank you for your quick response. My apologies the error I sent is the original error. I thought it was coming from upstream in the code and I thought  FWD.RC <- dada2:::rc(FWD) was the issue.  Here is the output for the code you sent. 
`` print(R1.flags)
[1] "-g^GGACAGAAAGACCCTATGAA-aCTCTAGGGATAACAGGCTGA"
 print(R1.flags)
[1] "-g^GGACAGAAAGACCCTATGAA-aCTCTAGGGATAACAGGCTGA" ``

**Comment by benjjneb** [comment]
Those flags are malformed, they do not have spaces between the flags and their arguments.

Did you use `paste0` instead of `paste` to create them? `paste` by default inserts spaces between the strings being concatenated together.

Alternatively you can just manually define the `R1.flags` and `R2.flags` variables with correct spacing.

**Comment by PGR23** [comment]
I have changed `paste0` to `paste` and my output looks different than before. Just to double check that the flags are correct now. This is what they look like. Thank you for your help.  
`print(R1.flags)
[1] "-g  ^ GGACAGAAAGACCCTATGAA"
> print(R2.flags)`

**Comment by benjjneb** [comment]
The correct flag syntax is shown above: https://github.com/benjjneb/dada2/issues/1734#issuecomment-1546143002

So no, this isn't correct, there shouldn't be a space between the `^` and the start of the DNA sequence.

**Comment by PGR23** [comment]
I was able to resolve the issue from your assistance. Thank you.
