### ISSUE TITLE
Reduce seqtab.nochim or overall ASV count?

### ISSUE THREAD

**Issue by camcecc** [benjjneb/dada2#1735]
Hi, I need to trim down the ASV tables before continuing the analysis, as I have more than 65k ASVs and they are killing my machine. I've tried to continue anyway with the analysis, but generating the tree was too time-consuming and blocked my server, so I found a way to create the alignment step by selecting seqtab.nochim[1:10000], trimming it down. But now I have real issues in combining the taxa generated before (with the 65k ASVs) and the 10k tree into the phyloseq object. So I was thinking: is there a safe way to trim/select the ASV count beforehand (seqtab dimension was 109299, decreased to 65862 after chimeras removal) and continue the rest of the pipeline with a lighter input?

Thank you in advance!

**Comment by benjjneb** [comment]
It is common the perform a filtering step to remove ASVs that are present in few reads or few samples (i.e. abundance or prevalence filtering). As long as this filtering process is independent of any subsequent statistical analysis you are doing, it is valid, and in fact will increase the power of future testing by reducing the number of hypotheses.

See this paper for more description from a statistical perspective on this sort of filtering: https://www.pnas.org/doi/10.1073/pnas.0914005107

**Comment by camcecc** [comment]
Thank you for the link. I was wondering if you could show me where in your dada2 pipeline (currently using the 1.16 version) I should remove the ASVs and precisely how - everytime I try to do manually something like this it messes up the process and issues start rising anywhere stopping me for days... I guess it could be a command right after the seqtab.nochim generation?

**Comment by benjjneb** [comment]
>  I guess it could be a command right after the seqtab.nochim generation?

Yes, you would just use basic R commands to subset down the sequence table, which is just an R matrix. For example

```
keep <- colSums(seqtab.nochim>0) > 3 # TRUE if ASV in >3 samples
seqtab.prevalence.filtered <- seqtab.nochim[,keep]
```

**Comment by camcecc** [comment]
It worked perfectly, thank you so much!

**Comment by camcecc** [comment]
... and here it comes. I thought it worked perfectly, but then I got this error that I never encountered before:

```
fit = pml(treeNJ, data=phang.align)
negative edges length changed to 0!
Error in pml(treeNJ, data = phang.align) : tip labels are not in data

```
I read in another forum topic that it could have been related to a matrix-type seq input, but I don't think I have any... 

```
seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
dim(seqtab.nochim) #65862

keep <- colSums(seqtab.nochim>0) > 3 
seqtab.prevalence.filtered <- seqtab.nochim[,keep]
dim(seqtab.prevalence.filtered) #4129

names <- rownames(seqtab.prevalence.filtered)
rownames(seqtab.prevalence.filtered) <- gsub("_1.fastq$", "", rownames(seqtab.prevalence.filtered))
```

From this I did the subsetting as you suggested and then proceeded as in the tutorial pipeline: 

```
ASVs.nochim_red = DNAStringSet(colnames(seqtab.prevalence.filtered))
names(seqtab.prevalence.filtered) = paste0("ASV", 1:ncol(seqtab.prevalence.filtered))
alignment = AlignSeqs(ASVs.nochim_red, anchor=NA, processors=30) 
phang.align <- phyDat(as(alignment, "matrix"), type="DNA")
dm <- dist.ml(phang.align)
treeNJ <- NJ(dm) # Note, tip order != sequence order
fit = pml(treeNJ, data=phang.align)

```

**Comment by benjjneb** [comment]
This error is produced when the following condition is met (from the `pml` code):

```
    if (any(is.na(match(tree$tip.label, attr(data, "names"))))) 
        stop("tip labels are not in data")
```

So I'd start by inspecting `treeNJ$tip.label` and `names(phang.align)` -- is there an obvious mismatch? If so, when did that mismatch in how things are being named arise? I vaguely remember running into an issue like this long ago, that was fixed by naming the vector of sequences by the sequence IDs somewhere in the alignment/phangorn steps.

**Comment by camcecc** [comment]
Thank you again, that was exactly the issue! I checked back in the steps and found the mismatch, it worked with no problems afterwards
