### ISSUE TITLE
filterandTrim question 

### ISSUE THREAD

**Issue by jspychalla** [benjjneb/dada2#1736]
Hi, 

I noticed that when I ran filterandTrim the ITS data did pretty well (for example reads in 85737  reads out 79225). For the 16S data fewer reads made it past the filter (for example reads in 546072    reads out 282). 

I contacted the sequencing center to see if there was any issues or abnormalities with the 16S run and got the following response "_data is fine .. sounds like a problem with the processing  with 515 definitely make sure you look for primers at the beginning only (good idea with any primers)_"

I use cutadapt to remove the primer sequences. I have done this before with 16S sequences. Do you have any suggestions on how to look for primers at the beginning only (I thought cutadapt addresses this but maybe it does not)? 

Thank you for your time!

**Comment by benjjneb** [comment]
After primer removal, the remaining trimmed forward sequence will be 250 - FWD_PRIMER_LEN long. That is probably less than 240 nts, so you are losing almost all your reads because `trucnLen` is throwing out all reads that don't reach the forward truncation length of 240.

So, reduce `truncLen` a bit and probably all is well.

**Comment by jspychalla** [comment]
Awesome thank you! One other thing I found out is that these sequences were run on NovaSeq. In the past when I did not have this issue my 16S reads were run on a MiSeq. Do I need to account this anywhere in the dada2 pipeline?

**Comment by jspychalla** [comment]
Dropping it down to 235 yield reads in  546072  reads out 318. Dropping truncheon to 230 yielded reads in 546072    reads out 484256. Just checking to make sure this not too much of a decrease in this parameter
