### ISSUE TITLE
Some input samples had no reads pass the filter --> Error rates could not be estimated (this is usually because of very few reads). Error in getErrors(err, enforce = TRUE) : Error matrix is NULL.

### ISSUE THREAD

**Issue by chuynh96** [benjjneb/dada2#1738]
As stated in the title, I'm running into this issue and I'm not sure how to proceed or fix this?

> out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs,
+                      maxN=0, maxEE=2, truncQ=2, rm.phix=TRUE,
+                      compress=TRUE, multithread=TRUE)
Some input samples had no reads pass the filter.
> head(out)
                       reads.in reads.out
SRR14825040_1.fastq.gz   644802    221908
SRR14825041_1.fastq.gz     2294       504
SRR14825042_1.fastq.gz   864765    280319
SRR14825043_1.fastq.gz   678906    241955
SRR14825044_1.fastq.gz   865014    289631
SRR14825045_1.fastq.gz  7741596   1746684
> #Learn the error rates of your samples.
> #Forward
> errF <- learnErrors(filtFs, multithread=TRUE)
111973169 total bases in 744686 reads from 4 samples will be used for learning the error rates.
Error rates could not be estimated (this is usually because of very few reads).
Error in getErrors(err, enforce = TRUE) : Error matrix is NULL.
> #Reverse
> errR <- learnErrors(filtRs, multithread=TRUE)
111975043 total bases in 744686 reads from 4 samples will be used for learning the error rates.
Error rates could not be estimated (this is usually because of very few reads).
Error in getErrors(err, enforce = TRUE) : Error matrix is NULL.

**Comment by benjjneb** [comment]
Can you provide some more information on these samples? What environement/amplicon is being sequenced? What is the sequencing machine?

Also, what does the output of `plotQualityProfile` look like? Does it look like real data, or is everything perhaps been assigned the same quality score?

**Comment by chuynh96** [comment]
These samples are skin microbiome samples from a publicly available dataset https://www.ebi.ac.uk/ena/browser/view/PRJNA736108

**Comment by benjjneb** [comment]
> What amplicon is being sequenced? What is the sequencing machine?
>
> Also, what does the output of plotQualityProfile look like? Does it look like real data, or is everything perhaps been assigned the same quality score?

**Comment by benjjneb** [comment]
> This dataset appears to be a shotgun library

DADA2 is not an appropriate tool for analyzing this data then.

**Comment by chuynh96** [comment]
I am running into this problem again, and this time on a dataset I've confirmed to be 16s data from an Illumina. How should I proceed?

Error rates could not be estimated (this is usually because of very few reads).
Error in getErrors(err, enforce = TRUE) : Error matrix is NULL.

**Comment by benjjneb** [comment]
Your beginning diagnostics should be the same as what I mentioned previoulsy in this thread.

> Can you provide some more information on these samples? What environement/amplicon is being sequenced? What is the sequencing machine?

> Also, what does the output of plotQualityProfile look like? Does it look like real data, or is everything perhaps been assigned the same quality score?

**Comment by chuynh96** [comment]
<img width="692" alt="Screenshot 2023-06-27 at 10 52 10 PM" src="https://github.com/benjjneb/dada2/assets/93216242/a3e6d42c-8716-4fdf-bddf-a9c9e00c32a3">

Sorry for the delay--this is an image of one of the quality profiles

**Comment by benjjneb** [comment]
This is what the quality profile looks like when every quality value is the same. This data didn't come off a sequencer, it was either simulated or had fake (constant) quality values added back to it later.

**Comment by chuynh96** [comment]
Does this mean I can't proceed at all with this data on the dada2 pipeline?

**Comment by chuynh96** [comment]
That's unfortunate...thank you for letting me know!
