### ISSUE TITLE
Amplicon size 233bp using DADA2 (2x250 cycles V3 Kit)

### ISSUE THREAD

**Issue by acpaulo** [benjjneb/dada2#1739]
HI,

I'm not sure I've done something wrong. Although it doesn't seem so.
I'm using the V4 region 16S rRNA and expecting 250bp. Samples (294 in total) are from nasopharynx and oropharynx, Low biomass.
Sending the Plot quality profile Fw reads in suppl.

`out <- filterAndTrim(fnFs,filtFs,fnRs,filtRs,
                      trimLeft=10, truncLen=c(220,160),
                      maxN=0, maxEE=c(2,2),truncQ=2,rm.phix=TRUE,
                      compress=FALSE,multithread=TRUE)`

```
head(mergers[[1]])
#  abundance forward reverse nmatch nmismatch nindel prefer accept
#1     47293       1       1    113         0      0      1   TRUE
#2      1235      31       1    113         0      0      2   TRUE
#3       669       2       2    113         0      0      1   TRUE
#4       130       3       3    112         0      0      1   TRUE
#5        56       4       4    113         0      0      2   TRUE
#6        53       5       6    113         0      0      1   TRUE
```

```
table(nchar(getSequences(seqtab)))

# 210  211  214  228  229  230  231  232  233  234  235  240  284  295  301 
#  42   34    4    1    1    1   13  572 2160  107    5    1    1    1    1 
```

Why are my amplicons lower than 250bp? Can it be acceptable?

[PLotError_Fwd.pdf](https://github.com/benjjneb/dada2/files/11565142/PLotError_Fwd.pdf)

Thank you in advance

**Comment by benjjneb** [comment]
`trimLeft=10` trimmed off the first 10 bases of the forward and reverse reads. So, if the sequenced amplicon was originally ~250 nts, after this trimming (and merging them together), the trimmed amplicon will be ~230 nts.

**Comment by acpaulo** [comment]
Hi Benjamin,

Thank you very much for your answer I should had reasoned out by myself. 
Thanks a lot.
