### ISSUE TITLE
demultiplexing

### ISSUE THREAD

**Issue by reidgrahamgriggs** [benjjneb/dada2#174]
Is there a suggested way to demultiplex paired end data without having an index file?  We are using the  sequencing paradigm described here (http://www.earthmicrobiome.org/emp-standard-protocols/16s/).   I have an r1 and r2 (multiplexed) file and made a simple barcode file, but didn't the index file from the sequencing center, which is what idemp wants.  

Any help is greatly appreciated!

Thanks!
Reid

**Comment by benjjneb** [comment]
Given this is EMP format, I would guess that QIIME should be able to appropriately demultiplex this?

Did you try the QIIME approach in [our FAQ](http://benjjneb.github.io/dada2/faq.html#how-can-i-demultiplex-my-fastq-files)?

**Comment by reidgrahamgriggs** [comment]
Hi Ben, 
Sorry for the delayed reply.  I have an issue request in to QIIME as well.  The issue seems to be that this sequencing paradigm does not use barcodes on the reverse reads.  Perhaps its operator error but I am not getting it to work.  My thought is that one should be able to associate forward reads to the proper sample ids with barcodes using a barcode file, and then associate the reverse reads to their respective sample id using the laneid.  If I had a fastq index file I think this could be done with idemp.

**Comment by benjjneb** [comment]
Hi Reid,
Unfortunately I'm not sure how to demultiplex all the various sequencing paradigms out there. We actually intentionally chose not to include demultiplexing in this package to avoid the thickets of edge cases that exist. The setup you describe is surely do-able, I just can't name you the tool for that setup.

*one hacky idea, pull out the first X nts of the forward read (the barcode) into a new file and call it the index file?*

**Comment by bstamps** [comment]
Reid- 

We use an approach where the sequencing center gives us back just the R1/R2 read files. Our barcode is on the forward read... give this a shot. 

- Join paired ends (Either in QIIME or with another tool)
- Extract barcodes with http://qiime.org/scripts/extract_barcodes.html
- Run split_libraries_fastq.py followed by split_sequence_file_on_sample_ids.py as recommended in the Dada2 FAQ.

**Comment by reidgrahamgriggs** [comment]
Thanks Ben.  I actually used extraxt_barcodes on the forward reads last
night and used the resulting barcode/index file to  demultiplex the
forwards and reverse reads separately last night.  I have to look at it
further but I think it worked properly.

The reason I'm doing this is because the merging step is a key piece of the
dada2 quality filtering as I understand it.  Is that correct?

**Comment by benjjneb** [comment]
dada2 performs best on unmerged reads, because then you merge first, the quality scores int he merged region are different.

This deserves more testing at some point, but that is the recommended workflow for now
