### ISSUE TITLE
SAMPLE NOT CALLED FOR LEARNING ERRORS

### ISSUE THREAD

**Issue by angithamelvin** [benjjneb/dada2#1740]
Hi
I am trying to do amplicon sequence analysis using DADA2 for the soil metagenomes, I had in total 11 forward reads foe the paired amplicon sequence data which I placed in a folder and when I tried to learn errors from the 11 reads only 6 was being called for the analysis.
I am attaching the code and the error here,
> library(dada2); packageVersion("dada2")
Loading required package: Rcpp
[1] ‘1.26.0’
> path2 <- file.path("d:", "angitha", "paired_n")  
> list.files(path2)
 [1] "BZDC_R1.fastq.gz" "BZDC_R2.fastq.gz" "BZDT_R1.fastq.gz" "BZDT_R2.fastq.gz" "C1DC_R1.fastq.gz" "C1DC_R2.fastq.gz"
 [7] "C1DT_R1.fastq.gz" "C1DT_R2.fastq.gz" "C2DC_R1.fastq.gz" "C2DC_R2.fastq.gz" "C3DC_R1.fastq.gz" "C3DC_R2.fastq.gz"
[13] "C3DT_R1.fastq.gz" "C3DT_R2.fastq.gz" "C4DC_R1.fastq.gz" "C4DC_R2.fastq.gz" "C4DT_R1.fastq.gz" "C4DT_R2.fastq.gz"
[19] "filtered_fwd"     "filtered_rev"     "NLDC_R1.fastq.gz" "NLDC_R2.fastq.gz" "NLDT_R1.fastq.gz" "NLDT_R2.fastq.gz"
> fnFsp <- sort(list.files(path2, pattern="_R1.fastq", full.names = TRUE))
> fnRsp <- sort(list.files(path2, pattern="_R2.fastq", full.names = TRUE))
> sample.namesp <- sapply(strsplit(basename(fnFsp), "_"), `[`, 1)
> filtFsp <- file.path("d:", "angitha", "paired_n", "filtered_fwd")
> filtRsp <- file.path("d:", "angitha", "paired_n", "filtered_rev")
> list.files(filtFsp)
 [1] "BZDC_R1filt.fastq.gz" "BZDT_R1filt.fastq.gz" "C1DC_R1filt.fastq.gz" "C1DT_R1filt.fastq.gz" "C2DC_R1filt.fastq.gz"
 [6] "C3DC_R1filt.fastq.gz" "C3DT_R1filt.fastq.gz" "C4DC_R1filt.fastq.gz" "C4DT_R1filt.fastq.gz" "NLDC_R1filt.fastq.gz"
[11] "NLDT_R1filt.fastq.gz"
> errFp <- learnErrors(filtFsp, multithread=TRUE, sample = -1)
106070975 total bases in 420707 reads from 6 samples will be used for learning the error rates.

How can I resolve this matter

**Comment by benjjneb** [comment]
`learnErrors` will incorporate samples until reaching a pre-specified number of bases (1E8 by default). The reason being at that point additional data doesn't help the error model get better, but does make everything run slower.

If you want to force `learnErrors` to use every sample you give it, just set `learnErrors(..., nbases=Inf)`

**Comment by angithamelvin** [comment]
Hi,
I tried this for sample by sample.
when I tried it for one of my sample, its showing error because of few reads as given below but it was working fine for the forward read of the same sample, because of the error I am not able to proceed. Could you help me with this.
errRp <- learnErrors(filtRsp, nbases=Inf) 
16613280 total bases in 69222 reads from 1 samples will be used for learning the error rates. Error rates could not be estimated (this is usually because of very few reads). 
Error in getErrors(err, enforce = TRUE) : Error matrix is NULL.

**Comment by benjjneb** [comment]
> I tried this for sample by sample.

Don't learn errors sample by sample. Just give it all your samples at once. That should solve the error you are seeing now.

**Comment by angithamelvin** [comment]
Hi, 
I was doing it for sample by sample to get the taxa files individually for each samples as I was not able to extract the sample taxa files separately
