### ISSUE TITLE
fastqPairedFilter  error subscript is a logical vector with out-of-bounds TRUE values

### ISSUE THREAD

**Issue by carlopacioni** [benjjneb/dada2#1742]
Hello Benjamin,
I understand this might not be really a problem with your R package, but I’m hoping you might be able to offer a solution from the top of your head and that you won’t mind me dropping a line!
 
I have pre-processed paired-end reads from a MySeq run, which I have separated by primer and have dropped the reads where there were mismatches. I am trying to use `dada2::fastqPairedFilter` to filter these using `matchIDs = TRUE` because the number of reads are different since I dropped some. This fails with the error:
`Error: subscript is a logical vector with out-of-bounds TRUE values`
Upon investigating the error I tracked down that it stems from Line 153-154 of your code:
```
fqF <- fqF[keep]
fqR <- fqR[keep]
```
 
that is because the vector `keep` is longer than `length(fqR)`. That happens because I have (in the file I have investigated as an example) 4 reads with the same ID in the forward fastq file (two unique sequences present twice) and 3 in the reverse (two identical and one different). Grabbing the seq identifier using ShortReads, the ID looks like this:
`M03633:613:000000000-GDT6R:1:1101:14653:2663`
 
So, I have been wondering whether this is expected. I would have thought I’d only have one identifier per read. Also, I wonder if the identifier is complete as from the description that I saw in Illumina documentation there are other elements that are not present. Ultimately, I was wondering what would be the best/simpler solution in your opinion to solve this problem?
 
Thank you very much for your time, I’d appreciate any help you can offer!
Carlo

**Comment by benjjneb** [comment]
> I have (in the file I have investigated as an example) 4 reads with the same ID in the forward fastq file (two unique sequences present twice) and 3 in the reverse (two identical and one different)

This is not something that was considered a possibility when designing the code for `matchIDs=TRUE`. 

> Grabbing the seq identifier using ShortReads, the ID looks like this:
M03633:613:000000000-GDT6R:1:1101:14653:2663

This seems similar, but not entirely consistent with the expected ID line for current Illumina (although if this is old Illumina data, there were some previous formats).

> Ultimately, I was wondering what would be the best/simpler solution in your opinion to solve this problem?

For me, I would probably try to go back and identify what previous processing steps produced these anomalies (duplicated ID lines, non-standard ID lines), and correct the issue there. Without understanding how this happened, I would be unsure that after-the-fact remedies (like deleting duplicate IDs) might not be fixing the real problem.

**Comment by carlopacioni** [comment]
Thanks Ben,
that was my thought too. I'm looking into this and will let you know what I find out.

cheers,
carlo

**Comment by carlopacioni** [comment]
So, somehow I have not been able to replicate the error once I have cleared up the whole chain of files I had previously created. I am not sure what happened but the only logical explanation is that I must have (manually) written multiple times to the same files without realising it while debugging other errors. Things are working as expected now. happy for you to close this issue.
Thanks!
