### ISSUE TITLE
GTR + G + I for evolutionary inference of 16S relatedeness

### ISSUE THREAD

**Issue by ManuelAOS** [benjjneb/dada2#1743]
Hi all!

I was reading the Bioconductor workflow published by Callahan and collaborators in F1000 research. I would like help to understand the following issue related with the maximum likelihood estimation among sequences:

**Why is it appropiate to fit a GTR + G + I model to 16S data?**

From what I understand, the GTR model would allow bases to change bidirectionally with the same probability, that is, the same probability that A --> C, and C --> A at each site.

Invariant sites (+ I) is related with differential evolutionary rates that might occur at different sites of the amplicon sequence? Is there any paper supporting this?

Gamma (+ G) Does this means that evolutionary changes might vary across sequences? I imagine that it could be intuitively concluded that 16S sequences hypervariable regions belonging to different taxa (phyla) might have different evolutionary change rates.

So, does including GTR +I +G means that it allows hypervariable regions from different sequences to change at different rates?

Thanks in advance for your time.

Best regards,

Manuel

**Comment by benjjneb** [comment]
> Gamma (+ G) Does this means that evolutionary changes might vary across sequences? I imagine that it could be intuitively concluded that 16S sequences hypervariable regions belonging to different taxa (phyla) might have different evolutionary change rates.

Yes. See here: https://academic.oup.com/femsec/article/93/4/fix029/3065615

> Invariant sites (+ I) is related with differential evolutionary rates that might occur at different sites of the amplicon sequence? Is there any paper supporting this?

Yes. See Fig 1: https://www.nature.com/articles/s41467-019-13036-1

> So, does including GTR +I +G means that it allows hypervariable regions from different sequences to change at different rates?

Yes.
