### ISSUE TITLE
Batch effects and small sample size

### ISSUE THREAD

**Issue by ChrisMcMullen** [benjjneb/dada2#1744]
I have a set samples which, for reasons I could not avoid, were sequenced in different labs using the same sequencing protocol. I know that batches should be handled separately in DADA2 due to potential differences in error profiles, but I am concerned about the variation I have created by having samples sequenced in different labs. Additionally, I had 20 samples done at one lab and 160 done at the other lab. I am concerned that the smaller sample size of 20 could increase uncontrolled variation. Do you have any suggestions for how I should handle my data? I am debating simply omitting the 20 samples, but would prefer to not. Any insight here is greatly appreciated. Thank you.

**Comment by benjjneb** [comment]
I think this question isn't really about DADA2, but rather about methodological batch effects in general. As such, I'm not going to give anything that should be construed as authoritative advice. That said, I would suggest two things, investigating in an exploratory fashion whether there is a batch signal (e.g. variation explained by the sequencing batches), investigating whether batches are confounded with the covariate of interest you are investigating (e.g. are there a much higher proportion of cases in batch 2 vs. batch 1), and including batch as an additional variable in downstream modeling (e.g. as an independent term in a linear model).

Throwing away the second batch to start is probably hasty, but taking potential batch effects seriously is important, and it looks like you are already off to a good start there.

**Comment by ChrisMcMullen** [comment]
@benjjneb thank you for taking the time to respond to my post. I had been wondering if there was a function of some sort in DADA2 that could account for this type of variation, but I am assuming there is not. You have confirmed everything I had already figured I should do to check my data, so your response has been immensely helpful. 

@otaviolovison thank you for the resource. I will certainly have a look at it.
