### ISSUE TITLE
Is it possible to get quality score profiles for ASVs? 

### ISSUE THREAD

**Issue by mskb01** [benjjneb/dada2#1745]
Hello amazing people behind Dada2, I had a small question, but not sure if it makes sense. Is it possible for Dada2 to also output a representative quality score profile for each ASV? Or is this something already available currently? If so, could you let me know where to look?

Thanks!

**Comment by benjjneb** [comment]
A quality profile base-by-base, no. But in the `$clustering` data.frame associated with the dada-class objects (the output of the `dada` command), there is a column that has the average quality score for each ASV identified in that sample.

**Comment by mskb01** [comment]
Thanks Ben.
