### ISSUE TITLE
"NAs produced by integer overflow" when running learnErrors

### ISSUE THREAD

**Issue by ycl6** [benjjneb/dada2#1747]
Hi @benjjneb 

Similar to issue #1074, I encounter an error when running `learnErrors`.
It happens when one of the samples has a lot of reads, and due to the nature of the limited range of `integer` type, `learnErrors` was not able to proceed when calculating cumulative `NBASES`.

```
Error in if (is.null(nreads) && NBASES > nbases) { :
  missing value where TRUE/FALSE needed
Calls: learnErrors
In addition: Warning message:
In drps[[i]]$uniques * nchar(names(drps[[i]]$uniques)) :
  NAs produced by integer overflow
Execution halted
```

https://github.com/benjjneb/dada2/blob/004ce26909268e1318a2f68e0ea26807412c7a2d/R/errorModels.R#L261-L264

I tracked down the sample that is casuing the error.

```r
> sum(derepFs[[9]]$uniques * nchar(names(derepFs[[9]]$uniques)))
[1] NA
Warning message:
In derepFs[[9]]$uniques * nchar(names(derepFs[[9]]$uniques)) :
  NAs produced by integer overflow

> sum(as.numeric(derepFs[[9]]$uniques) * as.numeric(nchar(names(derepFs[[9]]$uniques))))
[1] 18891919575

>  .Machine$integer.max
[1] 2147483647
```

I wonder if you will consider placing a safeguard in the function to ignore big files? Thanks

**Comment by benjjneb** [comment]
Can I borrow your `as.numeric` solution? Seems like that will do the trick pretty cleanly.

**Comment by ycl6** [comment]
Hi @benjjneb Of course. 

I am using a modified function to run the function. Although I double the number fo reads will go beyond the `integer` limit, I still cast it to numeric.

```r
NREADS <- NREADS + sum(as.numeric(drps[[i]]$uniques))
NBASES <- NBASES + sum(as.numeric(drps[[i]]$uniques) * as.numeric(nchar(names(drps[[i]]$uniques))))
```
