### ISSUE TITLE
issue in quality profile plots caused by ggplot2 3.3.4

### ISSUE THREAD

**Issue by ep142** [benjjneb/dada2#1748]
The new version of ggplot2 generates a warning
The `<scale>` argument of `guides()` cannot be `FALSE`. Use "none" instead as of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the dada2 package.
  Please report the issue at <https://github.com/benjjneb/dada2/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

Backtrace:
    ▆
 1. └─dada2::plotQualityProfile(toplot_fwd)
 2.   └─ggplot2::guides(fill = FALSE)
 3.     └─ggplot2:::deprecate_warn0("3.3.4", "guides(`<scale>` = 'cannot be `FALSE`. Use \"none\" instead')")

**Comment by benjjneb** [comment]
This is fixed in the current release version of dada2 (v 1.27.1 or later)

**Comment by sckieran** [comment]
Is this version of dada2 (1.27.1) available yet? I am only able to install 1.26.0, which github also says is the most recent version. I tried using a devtools install but there was no tarball for this version.

I am having issues with plotqualityprofile (extremely slow on large datasets, trouble printing to PDF) and I want to try to figure out if this is the culprit before I dig too much deeper.

**Comment by benjjneb** [comment]
> Is this version of dada2 (1.27.1) available yet?

Yes it is. It seems I did not cut a 1.28 release on Github yet though. But you can just install the devel version (i.e. the master branch). Or install through the most recent version of Bioconductor.

> I am having issues with plotqualityprofile (extremely slow on large datasets, trouble printing to PDF) and I want to try to figure out if this is the culprit before I dig too much deeper.

I doubt this is the culprit, this warning is just an auto-generated nag message from ggplot2 designed to generate user reports to downstream packages.
