### ISSUE TITLE
DECIPHER: IdTaxa Run Time Question 

### ISSUE THREAD

**Issue by Nataliexscarr** [benjjneb/dada2#1750]
Hi, 
I'm currently going through the dada2 tutorial, provided in https://benjjneb.github.io/dada2/ITS_workflow.html . I'm working with 100 multiplexed FASTQ fungi samples. I've been able to successfully get to the part where I have to run the IdTaxa function. The website doesn't call for this function to be executed, but one of my professor's colleagues created a derivative of this tutorial, which is tailored to professor's research. Anyways, I've ran this function in my macbook air 13" to incompletion because it ran for about a day and a half. I figured it's because i don't have sufficient RAM on it. So, I decided to do it on a University computer, which has an installed RAM of 16 Gb, whereas my laptop had 8 Gb. In addition, the University computer has 255 Gb of free storage. My question is, how long should the IdTaxa function take and why has it been running for hours when I execute it on both my personal laptop and a University computer? should I utilize a virtual machine and if so, how should I set it up and connect to my Rstudio desktop?

Ive provided an excerpt of the dada2 tutorial I'm working with below:
#Download the training set here: http://www2.decipher.codes/Downloads.html

load("C:/Users/ernie/OneDrive/Desktop/QIIME/UNITE_v2020_February2020.RData") # CHANGE TO THE PATH OF YOUR TRAINING SET
ids <- IdTaxa(dna, trainingSet, strand="top", processors=NULL, verbose=FALSE) # use all processors
ranks <- c("kingdom", "phylum", "class", "order", "family", "genus", "species") # ranks of interest
# Convert the output object of class "Taxa" to a matrix analogous to the output from assignTaxonomy
taxid <- t(sapply(ids, function(x) {
  m <- match(ranks, x$rank)
  taxa <- x$taxon[m]
  taxa[startsWith(taxa, "unclassified_")] <- NA
  taxa
}))
colnames(taxid) <- ranks; rownames(taxid) <- getSequences(seqtab.nochim)
....

**Comment by benjjneb** [comment]
@digitalwright Any guidance on time/memory scaling of `IdTaxa`?

@Nataliexscarr It would help to have more details on the size of the data you are classifying (number of ASVs, seq lengths) and the reference dataset.

**Comment by Nataliexscarr** [comment]
@benjjneb, thank you for you're speedy response! I truly appreciate it! 
I'm a beginner in bioinformatics, so i'll try my best to provide you with as much information necessary. the "dna" and "trainingSet" I'm utilizing for IdTaxa is seqtab.nochim and a training set I got from the UNITE sequence database, from http://www2.decipher.codes/Downloads.html . This seqtab.nochim has the ASVs and i believe will infer seq lengths too? the seqtab.nochim has 3.9 MB.  The training set has 5.7 GB. If you need more information please let me know!
Thank you for your patience

**Comment by digitalwright** [comment]
@Nataliexscarr Do I understand correctly that the IDTAXA function is not completing? How many sequences are in seqtab.nochim? If you turn on verbose=TRUE, how far does the progress bar make it?

**Comment by Nataliexscarr** [comment]
@digitalwright It turns out I needed to execute IdTaxa on a computer with more RAM, considering the large amount of sequences and the training set I was working with. I've resolved the issue. Thank you!
