### ISSUE TITLE
Meta-analysis-different primers

### ISSUE THREAD

**Issue by Balakulandai** [benjjneb/dada2#1751]
Hi I am doing meta-analysis using Dada2. The sequence files were from different primer region (eg. V3-V4, V5-V9), and different sequences platforms (Illumina, 454 and ion torrent). My questions is how to merge the table before chimera check. Any codes available to merge.

Thanks

**Comment by Balakulandai** [comment]
Hi 
Thank you for your suggestion
Now I am using only using sequences file generated using V3-V4 primer, and I have 50 files saved in rds after error learning dada and merge.
Now I am facing a problem in merging, it shows error as
Error: cannot allocate vector of size 74.65 Gb

Kindly provide some suggestion.

Thank you

**Comment by benjjneb** [comment]
I dont' know?

You haven't provided how this data was generated and saved, nor how you are loading it into the session again, nor what command you are running that sparks this error.

**Comment by Balakulandai** [comment]
Hi benjjneb
I downloaded the sequences from the public server (NCBI and ENA), ran them separately as instructed in dada2 big-data analysis, and saved the file as rds after the merge step.
The merging is working fine for 20 rds files 
eg. 
kt1 <- readRDS("Panama_seqtab.rds")
kt2 <- readRDS("PRJEB0_seqtab.rds")
kt3 <- readRDS("PRJEB1_seqtab.rds")
kt4 <- readRDS("PRJEB2_seqtab.rds") up to kt20
ktseqtab.all <- mergeSequenceTables(kt1, kt2,...kt20)
this is working, but if I try to merge more than 20 rds files, it shows an Error: cannot allocate vector of size 74.65 Gb.

Thank you for your time and suggestions.

**Comment by benjjneb** [comment]
What is the size and data type of these objects you are reading back in?

```
class(kt1)
dim(kt1)
object.size(kt1)
```

Overall, I probably wouldn't recommend indpendently processing this samples. The current tutorial workflow controls memory well and obviates many use cases for the big data tutorial.

**Comment by Balakulandai** [comment]
Thank you the suggestion

> class(kt)
[1] "matrix" "array" 
> dim(kt)
[1]     817 4968746
> object.size(kt)
17838475232 bytes

So your are suggesting to use dada2 big-data workflow.
Thank you

**Comment by benjjneb** [comment]
This suggests there are about 5 million ASVs from just this one dataset?
What is the study that produced this data? Is it an amplicon sequencing study?

If each of these datasets is of this size, you may just be running into memory limitations of storing a non-sparse matrix of size nsamples * nASVs.

Are there even overlaps in the ASVs you are getting between studies? Are you sure that all these studies have had their data properly pre-processed in your pipeline, to remove primers and to trim each study to the exact same region of the 16S gene? (not just "V3v4", but the exact starting and finishing coordinates?)

**Comment by Balakulandai** [comment]
Hi benjjneb
Sorry for the confusion from my side.
I pre-processed each study separately as they used different primers, based on the publication I removed the primers using rbind
 primerHits <- function(primer, fn) {
  nhits <- vcountPattern(primer, sread(readFastq(fn)))
  return(sum(nhits > 0))
}
### in the demultiplexed files SS ####
Primers.SS<-rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs[[1]]), 
                  FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs[[1]]), 
                  REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs[[1]]), 
                  REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs[[1]]))

Then I trimmed the read based on the length 
out.SS <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, 
                        truncLen=c(235, 215),-- varied between studies 
                        trimLeft = c(primer_length_fwd, primer_length_rev ), -- varied between studies 
                        maxN=0, maxEE=c(2,2), truncQ=2, 
                        rm.phix=TRUE, compress=TRUE, multithread=T)

Then I do error learning, dada2 (ASV) and merge, with merge table
seqtab.SS <- makeSequenceTable(mergers.SS)
dim(seqtab.SS)
saveRDS(seqtab.SS, "PRJNA_seqtab.rds") I saved here as rds

Likewise, I did this for all the studies and tried to merge the PRJNA_seqtab.rds files. Where our university hpc system is able to merge only 20 rds files.

I know this region is not exact same region of the 16S gene and also not the exact starting and finishing coordinates. From here I planned to merge the rds files, followed by chimera removal and fragment insertion to overcome the different primers and different lengths.

Thank you so much for your time and support.

**Comment by benjjneb** [comment]
> I know this region is not exact same region of the 16S gene and also not the exact starting and finishing coordinates. From here I planned to merge the rds files, followed by chimera removal and fragment insertion to overcome the different primers and different lengths.

Unfortunately I think that it will be necessary to trim the reads or ASVs to common starting/finishing starting points before merging studies (and post-merging steps like chimera removal) in order to get proper functioning of these steps. This should also address some of the memory issues, which are probably stemming in large part from there not being overlap of ASVs between studies that have different starting/finishing points.

This trimming isn't a trivial step, but is something we have dealt with in the past: See the "bioinformatics" section in this preprint: https://www.medrxiv.org/content/10.1101/2022.09.26.22280389v2.full-text
