### ISSUE TITLE
Selecting truncLen parameters-FilterandTrim

### ISSUE THREAD

**Issue by gabrielaicg** [benjjneb/dada2#1752]
Good evening, 

We had samples from swine oral swabs that were sent to a core facility for sequencing. I am currently working with 16S V3-V4 amplicon sequences using 341F- 805R primers.  Sequences were obtained on a MiSeq platform in a 2x 300bp paired-end run. First, I removed the primers using cutadapt. Based on the quality plot scores (posted below), my sequences do not seem to be of good quality in comparison to most of the examples I have seen posted online and the plots I ran for the last batch of samples. Because of this, I have been struggling to select truncation parameters that allow at least 12 bp overlap and do not filter reads significantly. 
![Reverse_PlotQualityScore](https://github.com/benjjneb/dada2/assets/135883024/df89ab19-f1d6-4fc3-8722-55e022f5e3a2)
![Forward_PlotQualityScore](https://github.com/benjjneb/dada2/assets/135883024/c47c72f3-c168-435a-9e76-8bb2a189bea5)

Despite my understanding of the overlap (length of forward read + length of reverse read - length of amplicon), I still cannot seem to determine the best truncLen parameters after observing these plots. So far I have started with truncLen=c(270, 210) and worked around different options all of which either leave most reads filtered out or leave no overlap. 

Are these sequencing runs bad? Could you offer any advice on how I should move forward? 

Thank you for your time!

**Comment by benjjneb** [comment]
> Are these sequencing runs bad?

Yes.

> Could you offer any advice on how I should move forward?

As I understand, you have already removed the primers with cutadapt. Thus, you only need to keep ~400 + 20 (overlap) of total bases. So, you can drop the `truncLen` somewhat from where you started. But, with these quality score profiles, the best you can do may not be great, but could be good enough? Something like `truncLen=c(210,210)` might be one I'd try to start.

**Comment by gabrielaicg** [comment]
I have not been so lucky and can see now that the input reads are pretty low for a few of the samples.  

![image](https://github.com/benjjneb/dada2/assets/135883024/8c2dfd9e-65b9-4989-bee2-bbc5a4cd43ec)

I think I will contact the core facility to see about a rerun. Thank you so much for your prompt response. I greatly appreciate your time!
