### ISSUE TITLE
Error rates could not be estimated (this is usually because of very few reads)

### ISSUE THREAD

**Issue by ShailNair** [benjjneb/dada2#1755]
Hi @benjjneb , I have paired-end files generated through novaseq6000 sequencer. The adapters and primers were trimmed. the read quality is binned at 30.

![Ht1-1R1_filt-fq-gz-FastQC-Report](https://github.com/benjjneb/dada2/assets/59241611/2a5326c3-13e1-462f-a886-e47e32d52ebe)

When I run the learn error code I get error as **Error rates could not be estimated (this is usually because of very few reads)**
However, the code is could grep enough reads
```
126542304 total bases in 518616 reads from 4 samples will be used for learning the error rates.
```

Here is the error code
 ```
rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fns_R1.cut[[1]]), 
+       FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fns_R2.cut[[1]]), 
+       REV.ForwardReads = sapply(REV.orients, primerHits, fn = fns_R1.cut[[1]]), 
+       REV.ReverseReads = sapply(REV.orients, primerHits, fn = fns_R2.cut[[1]]))
                 Forward Complement Reverse RevComp
FWD.ForwardReads       0          0       0       0
FWD.ReverseReads       0          0       0       0
REV.ForwardReads       0          0       0       0
REV.ReverseReads       0          0       0       0

> fns_cut <- sort(list.files(cutadapt_trimmed_dir, full.names = TRUE))
> fns_cut <- fns[str_detect(basename(fns), "fastq.gz")]
> cut_R1 <- fns[str_detect(basename(fns), "_1")]
> cut_R2 <- fns[str_detect(basename(fns), "_2")]
> get.sample.name <- function(fname) strsplit(basename(fname), "_")[[1]][1]
> sample.names <- unname(sapply(cut_R1, get.sample.name))
> head(sample.names)
[1] "Ht1-1" "Ht1-2" "Ht1-3" "Ht1-4" "Ht1-5" "Ht2-1"
> filt_R1 <- file.path(filtered_dir, paste0(sample.names, "R1_filt.fq.gz"))
> filt_R2 <- file.path(filtered_dir, paste0(sample.names, "R2_filt.fq.gz"))
> names(filt_R1) <- sample.names
> names(filt_R2) <- sample.names
> out <- filterAndTrim(cut_R1, filt_R1, cut_R2, filt_R2,
+                      maxN=0, maxEE=c(2,5), truncQ=2, rm.phix=TRUE,
+                      compress=TRUE,multithread=FALSE)
> head(out)
                 reads.in reads.out
Ht1-1_1.fastq.gz   129826    129705
Ht1-2_1.fastq.gz   133637    133497
Ht1-3_1.fastq.gz   125243    125144
Ht1-4_1.fastq.gz   130410    130270
Ht1-5_1.fastq.gz   120537    120428
Ht2-1_1.fastq.gz   122955    122885

> err_R1 <- learnErrors(filt_R1, multithread = TRUE)
126542304 total bases in 518616 reads from 4 samples will be used for learning the error rates.
Error rates could not be estimated (this is usually because of very few reads).
Error in getErrors(err, enforce = TRUE) : Error matrix is NULL.

> err_R1 <- learnErrors(filt_R1, nbases=1e8, multithread = TRUE)
126542304 total bases in 518616 reads from 4 samples will be used for learning the error rates.
Error rates could not be estimated (this is usually because of very few reads).
Error in getErrors(err, enforce = TRUE) : Error matrix is NULL.
```

I did check the [this](https://github.com/benjjneb/dada2/issues/791#issuecomment-502256869) and [this](https://github.com/benjjneb/dada2/issues/1166) issues but could not resolve the error. Is there any workaround or did I make some mistakes while running the code?

**Comment by benjjneb** [comment]
Every base has been assigned the same quality score in your data. This is coming from the sequencer? Binned quality score data does, but I've never seen sequencing data with only one quality score unless some sort of pre-processing that stripped the real quality scores already happened.

**Comment by ShailNair** [comment]
Yes, I found that to be unusual as well. I downloaded the raw fastq data. The authors stated that it was sequenced through novoseq6000. Here is the multiqc per base sequence plot of the raw data:
![MultiQC-Report](https://github.com/benjjneb/dada2/assets/59241611/74962981-de78-4542-85b0-fcad3653fa3d)
The score is binned to 29-30. Is there a way to successfully execute this through Dada2?

**Comment by benjjneb** [comment]
> Is there a way to successfully execute this through Dada2?

Probably not. This isn't the raw sequencing data.

The deblur method does not depend on quality score information and would be an alternative for identifying ASVs from this data.

**Comment by ShailNair** [comment]
Understand. Yes,  deblur will work with this. Thank you for the prompt response

**Comment by callabush** [comment]
Hi! I am having a very similar issue. All of my quality scores are 30. We sequenced the V4 region of the 16S rRNA gene using Illumina sequencing. Did you figure out what caused your issue? What did you end up doing to solve it?

**Comment by ShailNair** [comment]
@callabush Hi, 
Due to the binned quality scores for [Novaseq sequences, the default error estimation in dada2 may throw an error or overestimate](https://github.com/benjjneb/dada2/issues/791#issuecomment-502256869). However, in your case all the quality scores are binned at 30, which is unusual. You could ask the sequencing company about this unusual pattern. Possibly, they pre-processed your data and if so, you could request the raw data. 

In my case, I use the Deblur method.

**Comment by benjjneb** [comment]
> All of my quality scores are 30.

As far as I know, this is not the output of binned quality scores. This indicates that the data lacks real quailty scores, and they have been replaced with Q30 in some preprocessing step. I would check with the sequencing provider.
