### ISSUE TITLE
Error: object 'errF' not found

### ISSUE THREAD

**Issue by KOMALSKK** [benjjneb/dada2#1756]
Error: object 'errF' not found.
I keep getting this error, even though results for errF <- learnErrors(filtFs,fnF multithread=TRUE)
errR <- learnErrors(filtRs, multithread=TRUE) are displayed in the console. kKindly help

**Comment by benjjneb** [comment]
Can you provide the exact code you are executing, both to define `errF` and that produces this error message?

(it sounds though like the code you are executing is not assigning the output of `learnErrors` to `errF` correctly, but instead just printing the results to the console?)

**Comment by KOMALSKK** [comment]
> errF <- learnErrors(filtFs,fnFs, multithread=TRUE)
78547440 total bases in 327281 reads from 1 samples will be used for learning the error rates.
The above code runs fine for errF and errR, it generates output for both errF and errR.
However when I run dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
and dadaRs <- dada(filtRs, err=errR, multithread=TRUE)
I get error "Error: object 'errF' not found"AND object 'errR' not found"
The errF and errR values are also not generated in the environment.

Thank you
