### ISSUE TITLE
16S trimming parameters

### ISSUE THREAD

**Issue by kristab** [benjjneb/dada2#1758]
Hello,
With our 16S V3/V4 data (primers removed using cutadapt), I'm seeing a difference of 5% in the number of reads retained between the default DADA2 filtering parameters and custom parameters (maxEE=(4,4), truncQ=7). After reading through various guidance, I thought it was wise to just stick with the default settings but it turns out that the 5% drop in reads also results in a 25% reduction in the number of ASVs. 

The DADA2 tutorial for Big Data uses maxEE=1 & truncQ=11 and states, “If too few reads are passing the filter, increase maxEE and/or reduce truncQ" but I've also seen comments that specify that only the error filtering should be manipulated. 

I hate to throw away useful information. Is it appropriate to use the custom parameters? Is there a best practice for checking the output quality?

**Comment by benjjneb** [comment]
> Is it appropriate to use the custom parameters?

Yes.

> Is there a best practice for checking the output quality?

See the tutorial section on read tracking: https://benjjneb.github.io/dada2/tutorial.html#track-reads-through-the-pipeline

**Comment by kristab** [comment]
Thanks so much for your help. I've tracked the reads and assigned taxonomy with a minimum bootstrap of 80 and everything seems fine. I will do a bit more checking but I'm glad that we can finally proceed with more confidence. 

Thank you for developing an excellent tool and maintaining such an informative forum!
