### ISSUE TITLE
dada2: Removal of singletons and non-bacterial ASVs

### ISSUE THREAD

**Issue by kemerson3** [benjjneb/dada2#1760]
I have a couple questions regarding the dada2 pipeline listed below:

1) During the mergePairs step of the pipeline, I notice that my number of matches in the overlap region is consistently around ~14 nts in the overlap region, and this seems quite low compared to the number outlined in your tutorial (~140 nts). Is this low (I know default is at least 12 nts of overlap), and did I mess up during the Filter and Trim step?

2) How does your pipeline handle singleton reads? I've seen it covered on some forums ([dada2 singletons - can we keep them? · Issue #320 · benjjneb/dada2 (github.com)](https://github.com/benjjneb/dada2/issues/320), but my question is if I follow the pipeline, the final rarefied ASV table I create will not have any singleton ASVs that can skew my results and interpretation, correct?

3) I've seen in MB papers that they remove any ASVs identified as mitochondria, chloroplasts, archaea, etc. Do you have any input on how exactly to go about that?

Any and all help is appreciated, thank you!

**Comment by benjjneb** [comment]
1. This depends entirely on the length of the sequenced amplicon and the `truncLen` parameters you chose during filtering and trimming. The overlap length should be approximately [truncLenF - truncLenR - sequenced_amplicon_length].

2. By default, singleton ASVs are not called during the denoising step (`dada(...)`). Some small number of singletons can arise after merging. You can also change this behavior by turning on singleton ASV detection: `dada(..., DETECT_SINGLETONS=TRUE)`

3. Typically this is done by performing taxonomic assignment, then removing from the ASV table all ASVs assigned to mitochondria or chloroplast taxonomies.

**Comment by kemerson3** [comment]
Thank you for getting back to me. This is all very helpful. Just one more clarification, for Question 1 above:

I had 2x150 paired end reads and the data was very clean, and my forward and reverse reads did not dip in quality, and I therefore did not use the truncLen function (I only used the trimLeft = c(19,20) function to remove my primers). Is the truncLen function necessary even when the data is all of relatively high quality, or will the package default to use the entirety of the reads if no truncation parameters are included?

**Comment by benjjneb** [comment]
> will the package default to use the entirety of the reads if no truncation parameters are included?

Yes that will be the default behavior w/o `truncLen`
