### ISSUE TITLE
silva_nr99_v138.1_train_set.fa.gz is suitable for V3-V4 region taxonomic assignment?

### ISSUE THREAD

**Issue by Tinh1425** [benjjneb/dada2#1763]
Dear experts and colleagues,

I am doing 16S amplicon sequencing for the V3-V4 region. I am wondering whether I can directly use "silva_nr99_v138.1_train_set.fa.gz" for taxonomic assignment or if I need to train the classifier for specific V3-V4 region.

Thank you so much in advance.

Best regards,

Tinh Nguyen

**Comment by benjjneb** [comment]
> I am wondering whether I can directly use "silva_nr99_v138.1_train_set.fa.gz" for taxonomic assignment

Yes.

> or if I need to train the classifier for specific V3-V4 region.

Not necessary.

**Comment by Tinh1425** [comment]
Thank you so much!

Tinh
