### ISSUE TITLE
addSpecies database doesn't entirely match silva

### ISSUE THREAD

**Issue by korneeld** [benjjneb/dada2#1764]
I'm having problems finding the sequences in the species training set in the SILVA database.

I downloaded the file [silva_species_assignment_v138.1.fa.gz](https://zenodo.org/record/4587955/files/silva_species_assignment_v138.1.fa.gz?download=1). For example, it contains this sequence: `>ACYT02000005.305.1832 Actinomyces odontolyticus F0309` which is not part of the silva database (at least I cannot find it in this fasta file [SILVA_138.1_SSURef_NR99_tax_silva.fasta.gz](https://ftp.arb-silva.de/release_138_1/Exports/SILVA_138.1_SSURef_NR99_tax_silva.fasta.gz)).
The species file also seems to contain less sequences than the full silva fasta file.

I'm wondering if this is expected behaviour? Is the species database modified from the silva DB somehow? I'm considering building my own species database from the silva fasta file to fix this, but I would like to understand these differences before I do so.

**Comment by benjjneb** [comment]
The assign/add species training fastas are curated from the Silva releases, not exactly identical to them. You can see the code that produces them here: https://github.com/benjjneb/dada2/blob/master/R/taxonomy.R#LL679C11-L679C11

Probably the most important point of curation is that only sequences where the Silva genus and the genus/species binomial name agree are retained.
