### ISSUE TITLE
Merging sequence tables from different runs and different amplicons.

### ISSUE THREAD

**Issue by Varun9599** [benjjneb/dada2#1765]
Hello!
I am currently working on 16s miseq sequences from different runs and amplicons (2x150-V4, 2x250-V4, 2x250- V3V4). I am using the mergeSequenceTables function to merge the three sequence tables before taxonomy assignment. The problem with my V3V4 sequences is that they have huge number of reads and ASV counts. After taxa assignment, I am getting a lot of rare taxa that usually are not there. Also, the huge number of ASVs is messing with the alpha and beta diversity values. Is there any way I can eliminate the excessive ASVs in the V3V4 sequences?

Best regards,
Varun

**Comment by benjjneb** [comment]
To meaningfully merge at the ASV level, the ASVs need to be trimmed to the same gene region. At the ASV level, your V3V4 ASVs are not being merged with the V4 ASVs.

> Is there any way I can eliminate the excessive ASVs in the V3V4 sequences?

One thing I would double-check is whether you have unremoved primers on your V3V4 reads. The most common "Illumina" V3V4 protocol sequences primers, and those must be removed for proper processing (unremoved primers with ambiguoous nucleotides blow up the ASV counts and interfere with chimera removal).

**Comment by Varun9599** [comment]
@benjjneb Thanks for the reply!
> To meaningfully merge at the ASV level, the ASVs need to be trimmed to the same gene region. At the ASV level, your 
V3V4 ASVs are not being merged with the V4 ASVs.

How do I proceed for this step? will simply trimming by using trimLeft be sufficient? How do I make sure that the reads are in same orientation for this and only V4 region is retained after trimming?

Best regards,
Varun

**Comment by Varun9599** [comment]
Hello @benjjneb !
To convert the V3V4 reads to only V4, I went through the sequencing protocol and figured that since we are using 2x 250 bp sequencing to cover V3V4, the whole amplicon is not getting covered and does not have any major overlap. Thus the reads that have been sequenced from 806R primer must contain only the V4 region and not V3. From the primer detection method you have mentioned in ITS pipeline , I found out that half of the reads in my R1.fastq file were starting with the REV primer 806R.
Thus I subsampled the reads present in R1.fastq file starting from the sequence of 806R primer into a new file. I ran this new fastq file thorugh `DADA2` (Single End) and used `tryRC=TRUE` for taxonomy assignement. I obsereved that the rare taxa and junk ASVs I was getting by running V3V4 were not there and the data was pretty clean. Did not ovserve any major changes in the taxonomic composition.
Is this a correct approach? Would you suggest any other modifications?

Best Regards,
Varun

**Comment by benjjneb** [comment]
I don't know every detail, but in general the idea of using just forward reads, trimmed to the same length and starting from the same primer position, is an approach that would work to merge e.g. V4 and V3V4 amplified amplicons.

Devil in the details of course (does your processing/trimming result in read starting at the exact same position for both classes of amplicons?), but it's achieveable.

Our meta-analysis preprint describes another approach based on trimming after aligning to a broad 16S database: https://www.medrxiv.org/content/10.1101/2022.09.26.22280389v2.full (see Bioinformatics section, and associated analysis repository for details)

**Comment by Varun9599** [comment]
Thank you for the guidance! 

Best Regards,
Varun
