### ISSUE TITLE
mergePairs issues

### ISSUE THREAD

**Issue by kemerson3** [benjjneb/dada2#1766]
Hi benj,
I have been having trouble with the mergePairs step when working with some new microbiome data (V4, 16S, 2x150 paired end, 515F 806R primers). My quality plots look good and don't require any trimming aside from the last few nucelotides, and primers were removed using the filter and trim code below following the tutorial:

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen = c(140, 130), trimLeft = c(19,20),
                     maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, multithread=FALSE, matchIDs = TRUE)

                                                                   readsin    readsout
Kyle049-1.2_S49_L001_R1_001.fastq.gz    13489     13158
Kyle050-2.2_S50_L001_R1_001.fastq.gz    92444     90742
etc.

My error rates look reasonable, and my sample inference step for my samples looks right as well:
$`Kyle049-1.2`
dada-class: object describing DADA2 denoising results
87 sequence variants were inferred from 3955 input unique sequences.
Key parameters: OMEGA_A = 1e-40, OMEGA_C = 1e-40, BAND_SIZE = 16

But, when I merge my reads using the code from the tutorial (and that I have used in the past), I lose a ton of reads and the output looks generally like this for every sample:
seq   abundance forward reverse nmatch nmismatch nindel prefer accept
4                  280            4           5         60                0          0       1    TRUE
88                   4           46         31         25                0          0       1    TRUE

I have tried altering my truncLens multiple times, adjusting maxEE, not trimming primers, and can't seem to get my reads to merge with this data. Any help is greatly appreciated!

**Comment by Varun9599** [comment]
Hello @kemerson3 ,
I have been working with 2x150 V4 paired end data. I've observed that the V4 amplicon doesnt get properly covered in 2x150 sequencing and there are very few bases that overlap between forward and reverse reads. This usually causes problems in the merging step. You can try running the data as Single End and use the object `dadaFs` for preparation of sequence table.

**Comment by benjjneb** [comment]
Agree with @Varun9599 

Going forward with the forward reads alone may be appropriate here.
