### ISSUE TITLE
ITS cutadapt primer trimming

### ISSUE THREAD

**Issue by ImperialBV** [benjjneb/dada2#1767]
Hi 

I have used the ITS DADA2 pipeline several times before without a problem - with no changes from your workflow. I couldn't find the exact answer in any previous issues raised, although some have been helpful. I have used the following primers:

FWD <- "CTTGGTCATTTAGAGGAAGTAA"
REV <- "GCTGCGTTCTTCATCGATGC"

The last nucleotide on the reverse primer is variable across the sequences - attached.

<img width="677" alt="FWD primer seq" src="https://github.com/benjjneb/dada2/assets/137567532/4ac4dd77-0637-4bb5-b2e9-1ab0eacd6388">
<img width="676" alt="REV primer sequence" src="https://github.com/benjjneb/dada2/assets/137567532/33286b0e-5ecb-47e3-a95d-ac6472317021">

Identification and removal of the primers is shown below. The issue is the presence of the primers in the incorrect orientation, which persist after removal of the primers. 

<img width="379" alt="FWD+REV reads" src="https://github.com/benjjneb/dada2/assets/137567532/238eb3f3-f896-4dfa-a3c3-e6d52d1c628a">
<img width="382" alt="Primer removal" src="https://github.com/benjjneb/dada2/assets/137567532/5bdc24fd-3718-4edb-9ac0-e6a8cedf69bb">

I continued because there weren't many. The quality profiles are extremely poor. 

<img width="644" alt="Quality_REV" src="https://github.com/benjjneb/dada2/assets/137567532/9c526029-a776-4c2e-b280-ed6187772ce1">

<img width="642" alt="Quality_FWD" src="https://github.com/benjjneb/dada2/assets/137567532/b6041e5d-5aca-4c24-be28-97f84088e5d7">

The filtered reads are extremely low, and with this number I can't continue processing.

<img width="313" alt="Filtered reads" src="https://github.com/benjjneb/dada2/assets/137567532/53b8a3cf-a8ac-4e41-8b31-2f007e00ad42">

The questions I have:

1. Should I be removing the identification of primers in the incorrect orientation? If so, how can I do this?
2. Could there be a reason why the quality profiles are so poor? I assume its the quality of the data itself.
3. Is there a way to improve the output of filtered reads to yield better results?

Thanks in advance.

**Comment by benjjneb** [comment]
> Should I be removing the identification of primers in the incorrect orientation? If so, how can I do this?

No. There are a trival number of reads being flagged as having primers in the opposite orientation. Ignorable.

> Could there be a reason why the quality profiles are so poor? I assume its the quality of the data itself.

In my experience, this most often represents an issue with the amplification. For example, amplification has produced a lot of 100bp DNA fragments because of [insert long list of reasons why PCR can go wrong].

> Is there a way to improve the output of filtered reads to yield better results?

You could take a look at what you get using forward reads alone, and truncating them to 80 bp. I would probably do that actually as a sanity check. But my guess is that it will look "weird" and suggest that the issue here is with the underlying generation of amplicons.

**Comment by ImperialBV** [comment]
Thank you for your advice. I am using your code to run forward reads alone, but I am running into problems with trimming the primers. Please see below. I can't see an obvious error in this. Would be grateful to know where I may be going wrong.


list.files(path)

fnFs <- sort(list.files(path, pattern = "_1.fastq.gz", full.names = TRUE))

FWD <- "CTTGGTCATTTAGAGGAAGTAA"

allOrients <- function(primer) {
  require(Biostrings)
  dna <- DNAString(primer)  
  orients <- c(Forward = dna, Complement = complement(dna)) 
  return(sapply(orients, toString))  
}
FWD.orients <- allOrients(FWD)
FWD.orients

fnFs.filtN <- file.path(path, "filtN", basename(fnFs)) 
filterAndTrim(fnFs, fnFs.filtN, maxN = 0, multithread = TRUE)

primerHits <- function(primer, fn) {
  # Counts number of reads in which the primer is found
  nhits <- vcountPattern(primer, sread(readFastq(fn)), fixed = FALSE)
  return(sum(nhits > 0))
}
rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.filtN[[1]]))

cutadapt <- "/Users/cutadapt"
system2(cutadapt, args = "--version") 

path.cut <- file.path(path, "cutadapt")
if(!dir.exists(path.cut)) dir.create(path.cut)
fnFs.cut <- file.path(path.cut, basename(fnFs))

FWD.RC <- dada2:::rc(FWD)
R1.flags <- paste("-g", FWD, "-a") 

# Run Cutadapt
for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                             "-o", fnFs.cut[i], "-p", # output files
                             fnFs.filtN[i])) # input files
}

rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.cut[[1]])

cutFs <- sort(list.files(path.cut, pattern = "_1.fastq.gz", full.names = TRUE))

get.sample.name <- function(fname) strsplit(basename(fname), "_")[[1]][1]
sample.names <- unname(sapply(cutFs, get.sample.name))
head(sample.names)

**Comment by benjjneb** [comment]
> I am running into problems with trimming the primers.

What's the problem?

**Comment by ImperialBV** [comment]
I ran the following:

for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, # -n 2 required to remove FWD and REV from reads
                             "-o", fnFs.cut[i], "-p", # output files
                             fnFs.filtN[i])) # input files


This is the error I'm getting:

cutadapt: error: argument -a/--adapter: expected one argument

**Comment by benjjneb** [comment]
You defined `R1.flags <- paste("-g", FWD, "-a")`, so `-g CTTGGTCATTTAGAGGAAGTAA -a`.

What is the argument to the -a flag? It doens't have one right now, just a hanging flag on the command line call, which is causing the error.

**Comment by ImperialBV** [comment]
I used FWD reads only and I got some data I can work with. 

Thanks for your help.
