### ISSUE TITLE
16S V4 region frequently occurring sequences at start of R1 and R2

### ISSUE THREAD

**Issue by johannalheureux23** [benjjneb/dada2#1769]
Hi all,

So I recently completed a 2x150 MiSeq run on the V4 region of 16S using primers 515F and 806R. Looking at my reads, I'm noticing some frequently occurring sequences at the beginning of R1 and R2. Here are some examples of some of the reads. I've bolded the frequently occurring sequences.

R1:
**TACGGAGGGTGCAAGCGTTA**CTCGGAATCACTGGGCGTAAAGCGCGCGCAGGCGGCCTTTTAAGTTGGATGTGAAAGCCTATGGCTCAACCATAGAACTGCATCCAAAACTATCAGGCTAGAGTGTGGGAGAGGAAGATGGAATTAGTTGT

**TACGGAGGGTGCAAGCGTTA**ATCGGAATTACTGGGCGTAAAGCGCGCGTAGGCGGTTTGTTAAGTCAGATGTGAAAGCCCCGGGCTCAACCTGGGAACTGCATTTGAAACTGTCAAGCTAGAGTATGGTAGAGGGAAGTGGAATTCCGGGT

R2:
**CCTGTTCGCTCCCCACGCTTTC**GTGCCTCAGCGTCAGTATCGGTCCAGGTAGCCGCCTTCGCCACCGGTGTTCCTTCGAATATCTACGGATTTCACCCCTACACTCGAAATTCCACTACCCTCTCCCGTACTCAAGTCTGCCAGTATCCAA

**CCTGTTTGCTACCCACGCTTTC**GCACCTCAGTGTCAGTACCGGTCCAGGGAGCCGCCTTCGCCACCGGTGTTCCTCCCAGTATCTACGCATTTCACCGCTACACTGGGAATTCCGCTCCCCCCTCCCGGACTCAAGCAAAGCAGTTTCAAA

At first I thought these might be primers, but these do not match my sequencing primers sand they don't occur in all of my reads. For some samples, they occur in 20% of my reads, for others, 50% and others 2%. 

When I went through DADA2, I lost a lot of reads in the remove chimeras step so then I trimmed off the frequently occurring sequences but that didn't leave me with much overlap (8bp) so I lost a lot of reads when merging. 

Has anyone else seen this before or have any suggestions? 

Thank you!
-Johanna

**Comment by benjjneb** [comment]
What you are describing looks exactly like unremoved primers. How confident are you that you know what primers were used to create this library?

> For some samples, they occur in 20% of my reads, for others, 50% and others 2%.

This is somewhat curious though. Was there any pre-processing that might have partially removed primers before the fastq files you are looking at now? Is it possible that some less common library preparation strategy was used, like heterogeneity spacers or mixed orientation libraries, that would obscure the primer pattern somewhat?

**Comment by johannalheureux23** [comment]
Hi @benjjneb 

I am very confident that I know what primers were used for this library. I used the primers outlined by the Earth Microbiome Project (https://earthmicrobiome.org/protocols-and-standards/16s/).  There are the sequencing primers:

R1:
TATGGTAATT GT GTGYCAGCMGCCGCGGTAA

R2:
AGTCAGCCAG CC GGACTACNVGGGTWTCTAAT

Index:
AATGATACGGCGACCACCGAGATCTACACGCT

As you can see, they don't match up with my frequently occurring sequences. I just checked with the company that sequenced this library and they said there was no pre-processing done or any heterogeneity spacers used. 

If these were unremoved primers, I'm confused as to why most of the samples have it occurring in <10% of the reads (see attached). 

Another thing I've noticed is that even after trimming 20 bp off the beginning of the R1 and 20bp off the R2 reads, I'm still getting about 60% of sequences merging with 48bp of overlap. I would've thought that trimming off 40bp of a 2x150 sequencing run would not leave 48bp of overlap for a sequence that is ~250bp long. 

I appreciate your help!
-Johanna

[230616_R1_troubleshoot.txt](https://github.com/benjjneb/dada2/files/11960516/230616_R1_troubleshoot.txt)

**Comment by benjjneb** [comment]
Are you just observing conserved regions of the 16S gene near the primer (which is of course a highly conserved gene region) and that are shared across organisms of varying abundance in your samples?

When I BLAST the concatenation of the forward primer and the example R1 bolded sequence above, I get perfect hits to a variety of bacterial 16S sequences.

> Another thing I've noticed is that even after trimming 20 bp off the beginning of the R1 and 20bp off the R2 reads, I'm still getting about 60% of sequences merging with 48bp of overlap. I would've thought that trimming off 40bp of a 2x150 sequencing run would not leave 48bp of overlap for a sequence that is ~250bp long.

Trimming at the start of the seuences won't affect the overlap region. The overlap occurs between the ends of R1 and R2.

**Comment by johannalheureux23** [comment]
I think you're right - I think this is a very conserved region. I looked back at previous sequencing runs and observed the same thing. 

I noticed that when I don't trim off that highly conserved region, I lose a lot more sequences during the remove chimeras step. However, when I do trim off that highly conserved region, I get less sequences that merge. Do you recommend trimming off that highly conserved region?

**Comment by benjjneb** [comment]
> Do you recommend trimming off that highly conserved region?

No, it is real DNA.

**Comment by johannalheureux23** [comment]
Ok - thank you so much for your help!
