### ISSUE TITLE
Issue with taxa assignment using custom database

### ISSUE THREAD

**Issue by MGMarine** [benjjneb/dada2#1770]
Hi, 

I have a final dataset of 330 ASVs from 95 samples sitting in my seqtab.nochim file. I am trying to assign taxonomy and species using the dada2 functions using a custom database I recently made. 

Whenever I use the assignTaxonomy function this is the results I get returned for all 95 samples

      [,1]                                          [,2] [,3] [,4] [,5] [,6] [,7]
  [1,] "GQ461734.1 Thunnus obesus_DADA2_UNSPECIFIED" NA   NA   NA   NA   NA   NA  
  [2,] "GQ461734.1 Thunnus obesus_DADA2_UNSPECIFIED" NA   NA   NA   NA   NA   NA  
  [3,] "GQ461734.1 Thunnus obesus_DADA2_UNSPECIFIED" NA   NA   NA   NA   NA   NA  
  [4,] "GQ461734.1 Thunnus obesus_DADA2_UNSPECIFIED" NA   NA   NA   NA   NA   NA  
  [5,] "GQ461734.1 Thunnus obesus_DADA2_UNSPECIFIED" NA   NA   NA   NA   NA   NA    

And when I use the AssignSpecies function I get only NA's returned for [,1] and [,2] for all ASVs. 

Not sure what I'm doing wrong and would love some help please.

**Comment by benjjneb** [comment]
What is the format of your custom database ID lines? Can you post e.g. the first 3 ID lines in the custom database?

**Comment by MGMarine** [comment]
Hi, thanks for getting back to me. I've just realised something was going wrong between my AssignTax and AssignSp files and I think I called the wrong one for the AssignTax function. So I've cleared everything, run it again and now I am getting more sensible results but most of my 330 ASVs are matching to a single species Acanthocybium solandri, I know this isn't correct so I'm wondering why that species is being pulled out more than others? 
Does the length of reference sequence matter? 
In my samples I have fish species with highly similar 16S regions, I've been curious how the assignment functions will handle this. I'm anticipating it gets assigned to genus or family level. 


Here is my AssignTaxonomy file

>Animalia;Chordata;Actinopterygii;Scombriformes;Scombridae;Acanthocybium;solandri
CAAATCAAGAATAGAGGTCAGCCTGCCCTGTGACTATATGTTTAACGGCCGCGGTATTTTAACCGTGCGAAGGTAGCGCAATCACTTGTCTTTTAAATGGAGACCTGTATGAATGGCATTACGAGGGCTTAACTGTCTCCTTTTTCAAGTCAGTGAAATTGATCTCCCCGTGCAGAAGCGGGGATAAACCCATAAGACGAGAAGACCCTATGGAGCTTTAGACACTAAAGCATGTCATGTTAAACACCCCTAAATAAAGGGCCAAACCAAATGAATTATGCCCGTATGTCTTTGGTTGGGGCGACCGCGGGGAAATAAAAAACCCCCACGTGGAATGGGAGTACTACTTCCTACAACTAAGAGCTGCAGCTCTAATGAACAGAATTTCTGACCAATAAGATCCGGCAATGCCGATCAACGGACCGAGTTACCCTAGGGATAACAGCGCAATCCCCTTTTAGAGCCCATATCGACAAGGGGGTTTACGACCTCGATGTTGGATCAGGACATCCTAATGGTGCAGCCGCTGTTAAGGGTTCGTTTGTTCAACGATTAAAGTCCTACGTGATCTGAGTC

>Animalia;Chordata;Actinopterygii;Scombriformes;Scombridae;Acanthocybium;solandri
CAAATCAAGAATAGAGGTCAGCCTGCCCTGTGACTATATGTTTAACGGCCGCGGTATTTTAACCGTGCGAAGGTAGCGCAATCACTTGTCTTTTAAATGGAGACCTGTATGAATGGCATTACGAGGGCTTAACTGTCTCCTTTTTCAAGTCAGTGAAATTGATCTCCCCGTGCAGAAGCGGGGATAAACCCATAAGACGAGAAGACCCTATGGAGCTTTAGACACTAAAGCATGTCATGTTAAACACCCCTAAATAAAGGGCCAAACCAAATGAATTATGCCCGTATGTCTTTGGTTGGGGCGACCGCGGGGAAATAAAAAACCCCCACGTGGAATGGGAGTACTACTTCCTACAACTAAGAGCTGCAGCTCTAATGAACAGAATTTCTGACCAATAAGATCCGGCAATGCCGATCAACGGACCGAGTTACCCTAGGGATAACAGCGCAATCCCCTTTTAGAGCCCATATCGACAAGGGGGTTTACGACCTCGATGTTGGATCAGGACATCCTAATGGTGCAGCCGCTGTTAAGGGTTCGTTTGTTCAACGATTAAAGTCCTACGTGATCTGAGTC

>Animalia;Chordata;Actinopterygii;Perciformes;Bramidae;Brama;brama
GCCTGCCCTGTGACTATATGTTTAACGGCCGCGGTATTTTAACCGTGCGAAGGTAGCGCAATCACTTGTCTTTTAAATGAAGACCTGTATGAATGGCACGACGAGGGCTTAACTGTCTCCTCCCTCAAGTCAATGAAATTGATCTCCCCGTGCAGAAGCGAGGATGAACCCATAAGACGAGAAGACCCTATGGAGCTTTAGACATATGGTATGTCCCGTTAAATACCCCCGGATAAAGGACTTAACTAAAGGAACCATACCCCCCTGTCTTTGGTTGGGGCGACCACGGGGAAACAAAGAACCCCCATGTGGAAGGGGAGCACTGCTCCTACAACCAAGAGCCGCAACTCTAGTGAACAGAACTTCTGACCAAATATGATCCGGCAGTGCCGATCAACGGACCGAGTTACCCTAGGGATAACAGCGCAATCCTCTTTTAGAGCCCATATCGACAAGAGGGTTTACGACCTCGATGTTGGATCAGGACATCCTAATGGTGCAACCGCTATTGAGGGTTCGTTTGTTCAACGATTAAAGTCCTACGTGATCTGAGTTCAGACCGGA


And here is my AssignSpecies file

>EU099493.1 Acanthocybium solandri
CAAATCAAGAATAGAGGTCAGCCTGCCCTGTGACTATATGTTTAACGGCCGCGGTATTTTAACCGTGCGAAGGTAGCGCAATCACTTGTCTTTTAAATGGAGACCTGTATGAATGGCATTACGAGGGCTTAACTGTCTCCTTTTTCAAGTCAGTGAAATTGATCTCCCCGTGCAGAAGCGGGGATAAACCCATAAGACGAGAAGACCCTATGGAGCTTTAGACACTAAAGCATGTCATGTTAAACACCCCTAAATAAAGGGCCAAACCAAATGAATTATGCCCGTATGTCTTTGGTTGGGGCGACCGCGGGGAAATAAAAAACCCCCACGTGGAATGGGAGTACTACTTCCTACAACTAAGAGCTGCAGCTCTAATGAACAGAATTTCTGACCAATAAGATCCGGCAATGCCGATCAACGGACCGAGTTACCCTAGGGATAACAGCGCAATCCCCTTTTAGAGCCCATATCGACAAGGGGGTTTACGACCTCGATGTTGGATCAGGACATCCTAATGGTGCAGCCGCTGTTAAGGGTTCGTTTGTTCAACGATTAAAGTCCTACGTGATCTGAGTC
>MW595782.1 Acanthocybium solandri
CAAATCAAGAATAGAGGTCAGCCTGCCCTGTGACTATATGTTTAACGGCCGCGGTATTTTAACCGTGCGAAGGTAGCGCAATCACTTGTCTTTTAAATGGAGACCTGTATGAATGGCATTACGAGGGCTTAACTGTCTCCTTTTTCAAGTCAGTGAAATTGATCTCCCCGTGCAGAAGCGGGGATAAACCCATAAGACGAGAAGACCCTATGGAGCTTTAGACACTAAAGCATGTCATGTTAAACACCCCTAAATAAAGGGCCAAACCAAATGAATTATGCCCGTATGTCTTTGGTTGGGGCGACCGCGGGGAAATAAAAAACCCCCACGTGGAATGGGAGTACTACTTCCTACAACTAAGAGCTGCAGCTCTAATGAACAGAATTTCTGACCAATAAGATCCGGCAATGCCGATCAACGGACCGAGTTACCCTAGGGATAACAGCGCAATCCCCTTTTAGAGCCCATATCGACAAGGGGGTTTACGACCTCGATGTTGGATCAGGACATCCTAATGGTGCAGCCGCTGTTAAGGGTTCGTTTGTTCAACGATTAAAGTCCTACGTGATCTGAGTC
>AB642259.1 Brama brama
GCCTGCCCTGTGACTATATGTTTAACGGCCGCGGTATTTTAACCGTGCGAAGGTAGCGCAATCACTTGTCTTTTAAATGAAGACCTGTATGAATGGCACGACGAGGGCTTAACTGTCTCCTCCCTCAAGTCAATGAAATTGATCTCCCCGTGCAGAAGCGAGGATGAACCCATAAGACGAGAAGACCCTATGGAGCTTTAGACATATGGTATGTCCCGTTAAATACCCCCGGATAAAGGACTTAACTAAAGGAACCATACCCCCCTGTCTTTGGTTGGGGCGACCACGGGGAAACAAAGAACCCCCATGTGGAAGGGGAGCACTGCTCCTACAACCAAGAGCCGCAACTCTAGTGAACAGAACTTCTGACCAAATATGATCCGGCAGTGCCGATCAACGGACCGAGTTACCCTAGGGATAACAGCGCAATCCTCTTTTAGAGCCCATATCGACAAGAGGGTTTACGACCTCGATGTTGGATCAGGACATCCTAATGGTGCAACCGCTATTGAGGGTTCGTTTGTTCAACGATTAAAGTCCTACGTGATCTGAGTTCAGACCGGA

Here are my most recent results for AssignTax, I'm still getting NA's for my Assign Species. 
 [1,] "Animalia" "Chordata" "Actinopterygii" "Scombriformes"    "Scombridae"    "Acanthocybium" "solandri"   
  [2,] "Animalia" "Chordata" "Actinopterygii" "Scombriformes"    "Scombridae"    "Acanthocybium" "solandri"   
  [3,] "Animalia" "Chordata" "Actinopterygii" "Scombriformes"    "Scombridae"    "Acanthocybium" "solandri"

**Comment by benjjneb** [comment]
Do you have any outgroup sequences in your custom database? You should.

The naive Bayesian classifier method will assign the best taxonomy it can against the databse, which can result in bad assignments when the query sequences aren't related to the reference.

**Comment by MGMarine** [comment]
How much of an outgroup are we talking about? I have different fish from different orders but all are in the class Actinopterygii. 

Attached is my AssignTax file

[Custom_16S_assignTax.csv](https://github.com/benjjneb/dada2/files/11943471/Custom_16S_assignTax.csv)

**Comment by benjjneb** [comment]
More of an outgroup than that.

You can also try `assignTaxonomy(..., tryRC=TRUE)` to make sure its not a database orientation issue.

But if you BLAST a few of these unclassified sequences against nt, are they showing up as expected fish in your database?

**Comment by MGMarine** [comment]
Okay I just used the tryRC=T and now it seems to be working. What does that function do? How can I make sure to not have orientation issues when I generate databases in the future?

Thank you so much for your help!

**Comment by benjjneb** [comment]
`tryRC=TRUE` test every query in the reverse-complement orientation as well. It solves the issue of a difference between the sequencing and the orientation of the compiled reference database.
