### ISSUE TITLE
Too many ASVs in mock community

### ISSUE THREAD

**Issue by rachel-1212** [benjjneb/dada2#1773]
Hi, this is my first time using DADA2. I have 16S sequencing data for the V3-V4 region using 300bp paired end reads. I included Zymo mock communities (both the DNA standard and bacterial cells extracted alongside my samples) and have checked the ASVs in these mock communities as described in the tutorial. I get 22 ASVs found in the mock communities, whereas there are 8 bacterial species in the Zymo standard. The taxonomic assignments for all 22 ASVs match the bacterial species found in the Zymo standard so my thought is that there is some biological variation in the sequences from the species in the mock community which is leading to multiple ASVs for each species. My question was whether this would be expected, or whether there is something I should change in the pipeline to rectify this? Thanks for your help.

**Comment by benjjneb** [comment]
> my thought is that there is some biological variation in the sequences from the species in the mock community which is leading to multiple ASVs for each species. My question was whether this would be expected, or whether there is something I should change in the pipeline to rectify this?

Each of these bacteria has multiple copies of the 16S rRNA gene, which can differ from one another. So some biological variation is encoded in the genome of single strains.

That said, 22 seems like a high number for V3V4 sequencing. An easy way to check is to look at the relative abundances of these ASVs from the same species: Are they at roughly similar proportions (as would be expected if different alleles within the genome)? Or are some at an order of magnitude lower abundance?

You can review the analysis of full-length 16S sequencing of the Zymo mock community in our PacBio HiFi manuscript to get a clearer sense of what I am describing: https://academic.oup.com/nar/article/47/18/e103/5527971
