### ISSUE TITLE
Question about reverse complement in assignTaxonomy

### ISSUE THREAD

**Issue by mtsiknia** [benjjneb/dada2#1775]
Hello!

I have a question about the tryRC argument of the assignTaxonomy function.
For those representative sequences that their RC gave a better match, shouldn't then be replaced by the reversed-complement? I believe that it would affect any downstream analysis, like alignment and phylogenetic tree construction.

Thank you in advance,

Myrto

**Comment by benjjneb** [comment]
> For those representative sequences that their RC gave a better match, shouldn't then be replaced by the reversed-complement? I believe that it would affect any downstream analysis, like alignment and phylogenetic tree construction.

Makes sense to me. There is no automated way to do this right now though. It would require some custom R code (or an external re-orientation solution).

**Comment by mtsiknia** [comment]
Hi again

I found a way to replace sequences with their RC in the taxa and seqtab.nochim tables so to use them for any downstream analysis, like alignment and phylogenetic tree construction. My skills in coding are not advanced, so my solution could be improved, be more elegant or efficient from someone who is more skilled, but it works and I thought to share it with the community here:

#load libraries
library("tablecompare")
library("dplyr")
library("Biostrings")

#Run assignTaxonomy twice with tryRC=T and tryRC=F and store them separately
taxa <- assignTaxonomy(seqtab.nochim, "../silva_nr99_v138.1_train_set.fa.gz", tryRC=T, multithread=TRUE)
taxa2 <- assignTaxonomy(seqtab.nochim, "../silva_nr99_v138.1_train_set.fa.gz", tryRC=F, multithread=TRUE)

#make data.frame these two tables and unite all columns in one, then add a column that contains the sequences
noRC<-as.data.frame(taxa2)
output <- unite(noRC, all, c("Kingdom","Phylum","Class","Order","Family","Genus"))
output$seq<-rownames(output)
RC<-as.data.frame(taxa)
output2 <- unite(RC, all, c("Kingdom","Phylum","Class","Order","Family","Genus"))
output2$seq<-rownames(output2)
#add another column with the sequences that fill be needed later to be replaced with the RC sequences
output2$seq_RC <- output2$seq

#compare the two tables output and output2 to find the different rows
comp <- tblcompare(output, output2, by = seq)
comp
#extract the different rows in a new table
dif<-as.data.frame(comp$summ$value_diffs)
#add a column that contains the RC of the sequences
dif$revComp <- sapply(dif$seq, function(x) as.character(reverseComplement(DNAString(x))));
head(dif);

# The following loop will compare output2, that has the taxonomy corrected with RC and will replace those sequences with their # RC if they used for taxonomy assignment
for (i in 1:nrow(output2)) {
  matching_row <- dif$seq == output2$seq[i]
  if (any(matching_row)) {
    output2$seq_RC[i] <- dif$revComp[matching_row]
  }
}

#Finally replace rownames of taxa2 (tryRC=T) and colnames of seqtab.nochim with values in column output2$seq_RC

rownames(taxa)<-output2$seq_RC
colnames(seqtab.nochim)<-output2$seq_RC

Cheers,

Myrto
