### ISSUE TITLE
Question about merged read for assigning taxonomy by dada2 package in R

### ISSUE THREAD

**Issue by chengcheng0625** [benjjneb/dada2#1776]
Hello!

I have a question about assigning taxonomy of merged read by dada2 in R.
I used to follow the tutorial for generating error model,  dereplication, inferring ASVs, then merging forward and reverse reads, finally, assigning taxonomy. Because I received the raw data by company which are 'fastq' file of forward and reverse reads, respectively.

But now, I got my data which already were removed primers, filtered, already merged forward and reverse reads by company.  
Can I use these merged read for generating an error model, then do dereplication and inferring ASVs by dada2?

**Comment by benjjneb** [comment]
> Can I use these merged read for generating an error model, then do dereplication and inferring ASVs by dada2?

It's not recommended, especially depending on how the quality scores were assigned in the merged region (i.e. do they have roughly the same relationship to error rates as in the unmerged region?).

But you could probably do it anyway and the results wouldn't be crazy.

**Comment by chengcheng0625** [comment]
Thanks for your reply!
Actually, when I generated error model as follow:
err_merged_reads <- learnErrors(filtered_merged_reads, nbases=2e8, multithread=TRUE)

209253421 total bases in 515383 reads from 5 samples will be used for learning the error rates.

 Although, I increased the value of nbases, there is an error as follow:
Error rates could not be estimated (this is usually because of very few reads).
Error in getErrors(err, enforce = TRUE) : Error matrix is NULL.

Do you think I can still assign taxonomy of my already merged reads by dada2 in R?

Thank you so much.

**Comment by benjjneb** [comment]
Most likely the pre-merging and pre-processing already done has resulted in a pathological distribution of quality scores. I'm not sure if there is an easy solution, other than getting the raw data from the provider.

> Do you think I can still assign taxonomy of my already merged reads by dada2 in R?

You can still use `assignTaxonomy` if that is what you mean, but I don't recommend the whole DADA2 ASV workflow in the absence of real quality scores. You could consider other tools that don't depend on there being real quality scores, like deblur or unoise3 for ASVs, or swarm/uclust/mothur for OTUs.

**Comment by chengcheng0625** [comment]
Thank you so much.
