### ISSUE TITLE
OTUs from V4 region of 16S rRNA assigned as eukaryota

### ISSUE THREAD

**Issue by Ecotone23** [benjjneb/dada2#1777]
Hi Ben@benjjneb,

I have some microbial samples that had been previously sequenced with primers (515F, 806R) for V4 region of 16 rRNA and edited by DADA2 to get the OTUs. After assigning taxonomy following DADA2 pipeline, there are  almost 40 OTUs (out of 1000) assigned as eukaryota. Most of these eukaryotic OTUs have no identified information for Phylum and lower levels, but only identified as eukaryota Kingdom.

I was wondering why there are aukaryotic OTUs given the primers were specifically for bacteria? Was there any errors/mistakes during my DADA2 process that may account for it? If these are true results, any advice for how to deal with it in the follow-up microbial diversity analyses?

Thank you,
Gabriel

**Comment by benjjneb** [comment]
I would try BLAST-ing them against a broad database like nt or the ribosomal database here: https://blast.ncbi.nlm.nih.gov/Blast.cgi?PROGRAM=blastn&PAGE_TYPE=BlastSearch&LINK_LOC=blasthome

Does that provide any insight?

**Comment by Ecotone23** [comment]
Thanks for the suggestion. I did the Blast, and found that, out of those 37 suspicious OUTs, 14 of them without hitting anything or have been filtered automatically, 7 with greater than 96% identity and 100% coverage are Culex mosquitoes(we sequenced mosquito samples using primers for V4 region of 16s RNA to get microbial data), the rest of them having either very poor coverage and low identity score are either bacteria, fungi or mosquitoes.

While I am still not sure why these eukaryotic OTUs can en maintained to the final stage, is it a common practice to just ignore and remove these OTUs from follow-up microbial diversity analysis?

**Comment by benjjneb** [comment]
>  is it a common practice to just ignore and remove these OTUs from follow-up microbial diversity analysis?

Yes. Filtering your data down to the taxonomic range expected is normal and valid. You are just following bioinformatically to what the primers were supposed to do alone.

**Comment by Ecotone23** [comment]
Sounds good. Thank you.
