### ISSUE TITLE
18S workflow in DADA2 issue：Error in h(simpleError(msg, call)) :    Error evaluating 'x' parameter when selecting method for 'reverseComplement' function: key 70 (char 'F') not in lookup table

### ISSUE THREAD

**Issue by hehanhhh** [benjjneb/dada2#1779]
Hello.

Many thanks for DADA2 and the support you provide to the community.
When I am doing the 18S species annotation "taxa <-assignTaxonomy(seqtab.nochim, paste0(path, "/pr2_version_5.0.0_SSU_dada2.fasta.gz"))", it comes up with
"Error in h(simpleError(msg, call)) : 
  Error evaluating 'x' parameter when selecting method for 'reverseComplement' function: key 70 (char 'F') not in lookup table"

Your help on resolving the issue would be much appreciated.
Thanks.

**Comment by benjjneb** [comment]
Are the column names of `seqtab.nochim` the DNA sequences? Or have they been renamed? `head(colnames(seqtab.nochim))`.

You can troubleshoot which input is causing the problem by replacing each one in turn.

```
sq.test <- "ACGGAGGGTCCGAGCGTTAATCGGAATTACTGGGCGTAAAGCGTGCGCAGGCGGTTTGTTAAGCGAGATGTGAAAGCCCCGGGCTCA"
taxa <-assignTaxonomy(sq.test, paste0(path, "/pr2_version_5.0.0_SSU_dada2.fasta.gz"))
# Download another reference file -- say the stock rdp 16S training file
taxa <-assignTaxonomy(seqtab.nochim, file.path(path, "rdp_train_set_18.fa.gz")
```

Which one breaks?

**Comment by naurasd** [comment]
Hi @hehanhhh,

could you elaborate what you error looked like and how you were able to fix it in the end?

Cheers

nauras

**Comment by hehanhhh** [comment]
> 

Hi,
The problem is due to my carelessness in running
"seqtable.taxa.plus <- cbind('#seq'=rownames(taxa), t(seqtab.nochim), taxa)
seqtab.nochim <- t(seqtab.nochim) "
before running 
"taxa <-assignTaxonomy(seqtab.nochim, paste0(path, "/pr2_version_5.0.0_SSU_dada2.fasta.gz"))",
such that seqtab.nochim rows and columns change.

**Comment by naurasd** [comment]
Ah yeah, I actually made a similar mistake. Thanks for your reply.
