### ISSUE TITLE
Parellelizing assignTaxonomy

### ISSUE THREAD

**Issue by nmshahir** [benjjneb/dada2#178]
Quick question, is there anyway to parallelize the assignTaxonomy step?

Thank you!

**Comment by benjjneb** [comment]
Not right now, but I've been wanting this too and it should be pretty easy to implement.

**Comment by benjjneb** [comment]
Parallelization with `assignTaxonomy(...,multithread=TRUE)` added in 5dcb15384275f0d84532798ea54fd4df21e1bbe7
