### ISSUE TITLE
Error models and ASV detection

### ISSUE THREAD

**Issue by zinfin** [benjjneb/dada2#1780]
We’ve experimented with the `learnErrors` algorithm to generate two error models by using two different values for the `nbases` parameter - the default value of 1e08 and an alternate value of 5e08.  When each of these error models is used by dada and the pairs merged, we detect 2881 ASVs using the default model and 2871 ASVs using the alternate model with 98.5% of ASVs from the default model found in the alternate model. The default model identifies 42 unique ASVs not found by the alternate model. The alternate model identifies 32 unique ASVs not found in using the default model. The error models look virtually identical. The distribution of ASV counts across samples in both models look very similar:

![Screen Shot 2023-07-18 at 7 51 28 AM](https://github.com/benjjneb/dada2/assets/7891400/3146dcf2-c39c-49f8-b804-eb984663a919)

Examining the count frequency of ASVs unique to each model shows some differences:

![Screen Shot 2023-07-18 at 7 52 49 AM](https://github.com/benjjneb/dada2/assets/7891400/b4633a15-fd3c-4b3c-9d19-13cc95f84870)

We are trying to establish an appropriate error model for our pipeline. How do we know which model is correct?  Granted, these are error models and will be inherently different from each other, but do you have any guidance on choosing one over the other? Can you provide some insight into what impact changing the nbases parameters will have in ASV calling?

Thank you for putting together such a great tool set that is well-documented!

**Comment by benjjneb** [comment]
I would consider those two models virtually indistinguishable and effectively equally good.
