### ISSUE TITLE
Missing samples in bar plot 

### ISSUE THREAD

**Issue by arna3** [benjjneb/dada2#1781]
Hello, first thanks for creating the dada2 pipeline. I have been working with it since last week with the intention to see the taxonomic distribution of my data set. I have 9 samples, they are demultiplexed and I removed the primers. 
I run the whole pipeline several times but I haven´t been able to generate the bar plot for all my samples. 
I can see all the samples in the richness plots. 
![image](https://github.com/benjjneb/dada2/assets/140090954/3327b9e8-0763-4c94-adfa-c9dda08b06db)
![image](https://github.com/benjjneb/dada2/assets/140090954/f0024aac-5e71-4586-842a-91714ba58074)

But I see just 5 of them (corresponding to the control treatment) when I run the plot_bar. 
![image](https://github.com/benjjneb/dada2/assets/140090954/f0cfddba-bce4-42dd-a156-956baed0e4f9)
Could you please give me any suggestions of what could be the reason or how to fix this issue? 
Thanks in advance

**Comment by benjjneb** [comment]
Are you making the bar plot in phyloseq? If so, can you post the output when you print that phyloseq object? (just put in the name of the object and hit enter).

Are the alpha-diversity and ordination plots also being done via phyloseq?

**Comment by arna3** [comment]
Yes 
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 260 taxa and 9 samples ]
sample_data() Sample Data:       [ 9 samples by 1 sample variables ]
tax_table()   Taxonomy Table:    [ 260 taxa by 7 taxonomic ranks ]
refseq()      DNAStringSet:      [ 260 reference sequences ]

**Comment by benjjneb** [comment]
Hm... I'm not sure. I see it is all the `T#` samples that are missing.
Can you try subsetting the phyloseq object to just those samples and then try bar_plot again on that T-only phyloseq?

**Comment by arna3** [comment]
I did it and I got an empty bar_plot. For some reason it is like my ¨T¨ samples´ information just disappeared after running the plot_richness. Because until then, everything okay.

**Comment by benjjneb** [comment]
Can you post your exact `plot_bar` command?

**Comment by arna3** [comment]
plot_bar(ps.top20, x="EPN_sample", fill="Family")

**Comment by benjjneb** [comment]
In the subset phyloseq object (with just the "T" samples), what is the output of `taxa_sums(ps.Ts)`?

**Comment by benjjneb** [comment]
Replace `ps.Ts` with whatever the name of your subset phyloseq object with just the T samples is. If that is `ps`, then what is `taxa_sums(ps)`?

**Comment by arna3** [comment]
This was the output 
ASV1   ASV2   ASV3   ASV4   ASV5   ASV6   ASV7   ASV8   ASV9  ASV10  ASV11  ASV12 
589567 426759    599    363     22  13413     72     96      0   1043     19  15544 
 ASV13  ASV14  ASV15  ASV16  ASV17  ASV18  ASV19  ASV20  ASV21  ASV22  ASV23  ASV24 
 15201    207    126  11089  10875    689   8954   2530     50   6437      0      0 
 ASV25  ASV26  ASV27  ASV28  ASV29  ASV30  ASV31  ASV32  ASV33  ASV34  ASV35  ASV36 
     0      0    109      0      0      0      0      0      0     44      9      0 
 ASV37  ASV38  ASV39  ASV40  ASV41  ASV42  ASV43  ASV44  ASV45  ASV46  ASV47  ASV48 
    93      0     29      0      0      0    328      0    174      0      0     50 
 ASV49  ASV50  ASV51  ASV52  ASV53  ASV54  ASV55  ASV56  ASV57  ASV58  ASV59  ASV60 
     0      0     43      0      0      0     37      0      0     80      0      0 
 ASV61  ASV62  ASV63  ASV64  ASV65  ASV66  ASV67  ASV68  ASV69  ASV70  ASV71  ASV72 
     0      0      0     31      0      0      0      0     39      0    232      0 
 ASV73  ASV74  ASV75  ASV76  ASV77  ASV78  ASV79  ASV80  ASV81  ASV82  ASV83  ASV84 
     0    226      0      0      0      0      0      0      0      0      0      0 
 ASV85  ASV86  ASV87  ASV88  ASV89  ASV90  ASV91  ASV92  ASV93  ASV94  ASV95  ASV96 
     0      0      0      0      0      0      0      0      0      0      0      0 
 ASV97  ASV98  ASV99 ASV100 ASV101 ASV102 ASV103 ASV104 ASV105 ASV106 ASV107 ASV108 
     0      0      0      0      0      0      0      0      0      0      0      0 
ASV109 ASV110 ASV111 ASV112 ASV113 ASV114 ASV115 ASV116 ASV117 ASV118 ASV119 ASV120 
     0      0      0      0      0      0      0     75     13      0     50     15 
ASV121 ASV122 ASV123 ASV124 ASV125 ASV126 ASV127 ASV128 ASV129 ASV130 ASV131 ASV132 
     0      0      0      0      0      0      0     20     26     51      0     50 
ASV133 ASV134 ASV135 ASV136 ASV137 ASV138 ASV139 ASV140 ASV141 ASV142 ASV143 ASV144 
     0      0      0      0      0      0     41      0      0     36     31     35 
ASV145 ASV146 ASV147 ASV148 ASV149 ASV150 ASV151 ASV152 ASV153 ASV154 ASV155 ASV156 
    34      0      0      0     28      0      0      0     23     23     16     22 
ASV157 ASV158 ASV159 ASV160 ASV161 ASV162 ASV163 ASV164 ASV165 ASV166 ASV167 ASV168 
    22      0      0     20      0      0      6     17      7      0      0      0 
ASV169 ASV170 ASV171 ASV172 ASV173 ASV174 ASV175 ASV176 ASV177 ASV178 ASV179 ASV180 
    14      0      0     13      0      0     13      0      0     12      0      0 
ASV181 ASV182 ASV183 ASV184 ASV185 ASV186 ASV187 ASV188 ASV189 ASV190 ASV191 ASV192 
    11      0      0      0      5      0      0      0      0      0      0      0 
ASV193 ASV194 ASV195 ASV196 ASV197 ASV198 ASV199 ASV200 ASV201 ASV202 ASV203 ASV204 
     0      0      0      0      7      7      7      7      0      0      0      0 
ASV205 ASV206 ASV207 ASV208 ASV209 ASV210 ASV211 ASV212 ASV213 ASV214 ASV215 ASV216 
     7      7      7      0      0      0      0      6      0      5      0      5 
ASV217 ASV218 ASV219 ASV220 ASV221 ASV222 ASV223 ASV224 ASV225 ASV226 ASV227 ASV228 
     0      0      0      5      0      4      0      0      4      0      0      3 
ASV229 ASV230 ASV231 ASV232 ASV233 ASV234 ASV235 ASV236 ASV237 ASV238 ASV239 ASV240 
     3      0      0      0      0      3      0      0      0      0      3      3 
ASV241 ASV242 ASV243 ASV244 ASV245 ASV246 ASV247 ASV248 ASV249 ASV250 ASV251 ASV252 
     3      3      0      0      0      0      2      0      0      0      0      0 
ASV253 ASV254 ASV255 ASV256 ASV257 ASV258 ASV259 ASV260 
     0      2      0      0      2      2      0      0

**Comment by benjjneb** [comment]
I'm at a loss.
If you want, you could share the "minimal" phyloseq object that leads to this behavior, and I could try to reproduce the issue with `plot_bar`. You could also ask at the phyloseq github Issues forum.

**Comment by arna3** [comment]
Hello, okay, thanks, I will check the phyloseq forum.
