### ISSUE TITLE
Making a custom LSU database with DADA2 from Silva files

### ISSUE THREAD

**Issue by JFranklin5221** [benjjneb/dada2#1783]
I am trying to create a LSU dada2 taxonomy file for from files from the Silva Database.

path<-"G:"
dada2:::makeTaxonomyFasta_SilvaNR(file.path(path,"SILVA_138.1_LSURef_NR99_tax_silva.fasta.gz"), file.path(path, "tax_slv_lsu_138.1.txt"),"G:/Test.gz",include.species=FALSE, compress=TRUE)

But when I create this file I seem to get very few Eukaryotes which seems incorrect to me.

Archaea Bacteria Eukaryota
991           78144       100

Thank you for any help!

**Comment by benjjneb** [comment]
`dada2:::makeTaxonomyFasta_SilvaNR` is specific for creating a Bacteria/Archaea reference. You can view the code by typing `dada2:::makeTaxonomyFasta_SilvaNR` and pressing enter. It excludes all Eukaryota except for a random set of 100 to serve as an outgroup.

**Comment by JFranklin5221** [comment]
Thank you for the clarification! Forgive my ignorance but is there a way to work around this to make a Eukaryotic database using the makeTaxonomyFasta_SilvaNR code? 
Essentially what I am trying to do is I have a bunch of 23S sequences and would like to assign taxonomy to them.

**Comment by JFranklin5221** [comment]
I also have 23S files from http://microgreen-23sdatabase.ea.inra.fr/ressources.html but I am a little lost on how I would convert them to be able to be used in DADA2. Again thank you so much for your help!

**Comment by JFranklin5221** [comment]
> `dada2:::makeTaxonomyFasta_SilvaNR` is specific for creating a Bacteria/Archaea reference. You can view the code by typing `dada2:::makeTaxonomyFasta_SilvaNR` and pressing enter. It excludes all Eukaryota except for a random set of 100 to serve as an outgroup.

Thank you for the clarification! Forgive my ignorance but is there a way to work around this to make a Eukaryotic database using the makeTaxonomyFasta_SilvaNR code?
Essentially what I am trying to do is I have a bunch of 23S sequences and would like to assign taxonomy to them.

I also have 23S files from http://microgreen-23sdatabase.ea.inra.fr/ressources.html but I am a little lost on how I would convert them to be able to be used in DADA2. Again thank you so much for your help!

**Comment by JFranklin5221** [comment]
I was able to format the microgreen mothur data into a dada2 format using a text editor and excel but I would still be curious how to format LSU data from Silva.

**Comment by benjjneb** [comment]
Have you taken a look at the contributed Silva 18S training fasta? https://zenodo.org/record/1447330

It's listed on our webpage of reference databases under the "Contributed" section: https://benjjneb.github.io/dada2/training.html

> Forgive my ignorance but is there a way to work around this to make a Eukaryotic database using the makeTaxonomyFasta_SilvaNR code?

Parts can be re-used, but there is a fair amount of bacteria/archaea-specific code in there that would have to be removed/replaced.

**Comment by JFranklin5221** [comment]
I did see the 18S database thank you. The customization of the code to format makeTaxonomyFasta_SilvaNR is a bit beyond me but I do appreciate the suggestion.
