### ISSUE TITLE
zero unclassified taxa at genus level?

### ISSUE THREAD

**Issue by gabrielet** [benjjneb/dada2#1784]
not a real issue here, just wanted to share and ask if anyone had the same outcome when using the `assignTaxonomy` function. for some reasons, when i see a 100% rate of success i start to wonder what is wrong.

so, how likely is it to have zero unclassified organisms, considering they are fungi (ITS), at genus level? i do have unclassified at species level but having all classified at genus level somehow sounds weird.

i tested the blast algorithm implemented by qiime2 and, as expected, i get many unclassified up to phylum level. for bacteria i get unclassified organisms at all taxonomic level, with both qiime2's blast and dada2's `assignTaxonomy` so no suspicious behaviour there.

any comments, anyone?

**Comment by benjjneb** [comment]
My ITS experience is extremely limited, so hopefully some others with more expertise there can comment.
