### ISSUE TITLE
% similarity against best match for each ASV

### ISSUE THREAD

**Issue by Paoluxxe** [benjjneb/dada2#1785]
Hello,

I followed the online tutorial to apply dada2 to my data via RSTUDIO. Thank you, the tutorial and the tool are very useful!
I am looking in vain for the % similarity  against best match for each ASV. How can I proceed?

Thank you for your attention.

Paola

**Comment by benjjneb** [comment]
> the % similarity against best match for each ASV

Can you clarify what this means? Is this referring to the taxonomic assignments?

**Comment by Paoluxxe** [comment]
Yes, these are taxonomic assignments.
I'm interested in the percentage of bases identical to the reference
genome, i.e. the extent to which the query sequence (my ASV) contains
exactly the same nucleotides or amino acids at the same positions as the
reference sequence.
I need this information because I'm looking to identify ASVs whose
sequences are too different from the references, on the assumption that
ASVs that are too far removed from the reference databases are more likely
to be degraded sequences (I'm applying this protocol as part of a process
to decontaminate my dataset).

**Comment by benjjneb** [comment]
The dada2 R package doesn't have a specific tool to do that. `assignTaxonomy` is based on shredding the sequences into kmers (8-mers) and comparing to the reference database, thus it doesn't calculate a % identity score.

If you want to stay in R, you could consider implementing a custom pairwise alignment approach to a set of references, using tools available in the Biostrings package. Or I'm sure there are external tools that would generate the data you want.
