### ISSUE TITLE
Combining ASV feature table and taxonomy table?

### ISSUE THREAD

**Issue by skose82** [benjjneb/dada2#1789]
dada2 outputs a feature table with abundance/hits of that feature for each sample, and another table (taxonomy table) resolving the feature ids as bacterial taxa - I remember there was a simple way of merging these tables into one, but I can't seem to remember it! it's been while. Anyone remember how to do this?

**Comment by benjjneb** [comment]
You can create a data.frame that combines these with something like:

```
foo <- data.frame(t(st.filt), tax.filt)
```

This will give you a row for each ASV, and the first `n` columns for the `n` samples in the data, and the last `t` columns for the `t` taxonomic levels in the data.

You may want to play with the rownames/colnames though. The simple one-liner above has no ASV column, it just has the ASV names defined in the rownames, and the sample names in the colnames might be a bit garbled.

**Comment by skose82** [comment]
Thanks, I guess I can do it with the pandas df too.

**Comment by skose82** [comment]
Thanks for suggestion, I guess I can do it with the pandas df too.
