### ISSUE TITLE
Duplicate taxa

### ISSUE THREAD

**Issue by StollML** [benjjneb/dada2#179]
Hi:
Thank you for introducing an alternative to OTU-based analysis. I ran dada2 with 49 paired-end samples from the human intestinal microbiota, using only the default options. The output was 1400 unique sequences, many of which resulted in duplicate taxa. (For example, there were about 25 instances of Faecalibacterium prausnitzii). Should I interpret these findings as indicating multiple unique strains within the species that greengenes cannot capture, or that the default options are not working for me? Perhaps I should set OMEGA_A to a lower value, e.g. 1e-60? Thanks --

Matt

**Comment by benjjneb** [comment]
The answer to this is that it depends. If it is important that you be certain all of these sequence variants are indeed legitimate biological sequences, it is always worth looking at some additional sources of validation.

I've been working quite a lot with longitudinal data, and so my go-to approach is to look at the distribution of the rarer variants of a species over time. I've generally found that most if not all of the SVs from the same species, even up to 25 as here, have shown auto-correlation in time strongly indicating they are biological.

Another approach is to BLAST sequences against nt and look at exact hits. This has real limitations though, as the rarer variants start to be quite unlikely to be in nt simply due to insufficient sampling effort.

Another approach is to inspect the diagnostic information associated with each SV that `dada` calls. The return `dada-class` object has a `$clustering$` data.frame that contains useful information on each called variant, such as the quality scores at the positions that differ, and the number of exact and 1-away reads from that SV.

**Comment by StollML** [comment]
Thank you very much for the reply. Looking for the consistency of the sequence variants is a great idea in principal, although I only have one sample from each subject. Could you walk me through how I would inspect the $clustering$ data.frame within the dada-class object? Also, many of the SV are infrequent, occurring in only one or two of the 49 subjects, which precludes statistical analysis. How would you recommend that I adjust the parameters of the dada runs to lose these SVs? Maybe decrease the OMEGA_A to 1e-50 or so?

Thanks,

Matt

**Comment by benjjneb** [comment]
Quick question first: Are you using single or paired reads?
And if paired, how overlapping are they?

**Comment by StollML** [comment]
They are MiSeq 250 bp paired-end reads. I won't be back in my office until later, but at the top of my head, I believe I trimmed at 200. The reverse reads drop have the usual Illumina quality issues.

Thanks,

Matt

Sent from my iPhone

On Feb 3, 2017, at 9:45 AM, benjjneb <notifications@github.com<mailto:notifications@github.com>> wrote:


Quick question first: Are you using single or paired reads?
And if paired, how overlapping are they?

**Comment by StollML** [comment]
Sorry, I didn’t fully answer your question. The original reads are virtually 100% overlapping. Just checked my code – the truncated length was c(240,200).

Thanks,

Matt

**Comment by benjjneb** [comment]
Below is a slight modification of the tutorial workflow, that will allow you to view the key diagnostics for a sequence (`sqj`) in a sample (`sami`) that you are particularly interested in:

Replace the `mergePaires(...)` call with:
```
mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE, propagateCol=c("birth_pval", "birth_fold", "birth_ham", "birth_qave"))
```

This "propagates" those diagnostics columns to the merger dataframe. Then, after creating the sequence table and identifying the sample/sequence of interest:

```
sami <- sample.names[[1]]
sqj <- colnames(seqtab.nochim)[[2]]
mm <- mergers[[sami]]
mm[match(sqj,mm$sequence),-1] # Info for SV/sample of interest
mm[sample(nrow(mm), 10),-1] # Comparison diagnostics
```

What to look at here... You should pay attention to the propagated diagnostic columns, which will be there for both the call on the forward read and on the reverse reads. Indicators of bad calls are a `birth_qave` that is much lower than in other calls (`birth_qave` is the average quality scores at the **differences** that caused that SV to be called). Low `birth_fold` (the fold over-abundance of the SV compared to the error model) can also suggest bad calls (where low is 1x-4x). And `birth_ham` (the hamming distance to the more abundant SV from which this one was divided) of 1 is the most  likely class to be miscalled. You can also test-drive the impact of changing `OMEGA_A`, as the `birth_pval` column gives the p-value that was compared to `OMEGA_A` when calling this variant.

All that said, the fact that your reads are so highly overlapping greatly increases confidence, as it means these variants are being **independently** called on the F/R reads and exactly matching each other (with the caveat that if the key differences are in the non-overlapping part its just one call).

Hope that helps, I realize that the diagnostic stuff is a bit more effort than the standard workflow, but it can be worth it to convince yourself what you're seeing is legitimate.

**Comment by StollML** [comment]
Thank you very much for the additional information. To make sure I understand: if I am interested in, let’s say, the fourth sequence on the SeqTab output file in the third subject down, then the code would be:

sami <- sample.names[[3]]
sqj <- colnames(seqtab.nochim)[[4]]

And the rest would be as below?

Also, I gather from your point below about the merger step that if the overlapping portion of the forward and reverse reads were to yield different SVs, then the merger would be unsuccessful and the sequences discarded?

Thanks,

Matt

**Comment by benjjneb** [comment]
@StollML

Yes, your description and commands look right (presuming you are following the tutorial workflow). 

And also yes on your second point: By default, dada2 will discard all merged reads that do not exactly match over the overlap. Thus any difference that occurred in the overlap region was independently inferred from the F and R reads.

**Comment by StollML** [comment]
Thank you very much –

Matt
