### ISSUE TITLE
DADA2: Filtering and Trimming

### ISSUE THREAD

**Issue by Lightcrane-h** [benjjneb/dada2#1790]
Hi there! Sorry if this is already answered elsewhere, but I'm having a hard time figuring it out, so I wanted to ask.

I have some reads that had paired-end sequencing (V3-V4, 341F, 805R) with the Mi-Seq 2x250 platform.
Currently, I decided on the length of the sequence to be trimmed through the plotQualityProfile function. (Forward: 280, Reverse: 200)
[quality_profiles.pdf](https://github.com/benjjneb/dada2/files/12224854/quality_profiles.pdf)
[quality_profiles_R.pdf](https://github.com/benjjneb/dada2/files/12224855/quality_profiles_R.pdf)

Based on quality score, I'm using the following code to filter them but I'm having trouble retaining enough reads. In fact, when I first performed the filterAndTrim function with the same data, most of reads.out passed filtering. However, from the second attempt, a significant number of reads were discarded. I don't understand what factors make this difference...

*First performed
> out  <- filterAndTrim (fnFs, filtFs, fnRs, filtRs, **truncLen=c(280,200)**, trimLeft=c(17,21), maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE)    

#Honestly, I'm not sure if I put this number in the truncLen function. 
#However, I think that the difference between reads.out of out (first performed) and out1 (second) is related to the position at which reads were truncate.

>head(out)
                                                            reads.in  reads.out
21_G_Ok_4_S103_L001_R1_001.fastq   120438    120282
21_G_Ok_5_S104_L001_R1_001.fastq   124858    124675
21_G_Pp_6_S97_L001_R1_001.fastq     127916    127708
21_G_Pp_7_S98_L001_R1_001.fastq     101197    101049
21_I_Ha_6_S99_L001_R1_001.fastq      118954    118812
21_I_Ha_7_S100_L001_R1_001.fastq    144736    144616

*Second
> out1 <- filterAndTrim (fnFs, filtFs, fnRs, filtRs, truncLen=c(280,200), trimLeft=c(17,21), maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE)

>head(out1)
                                                             reads.in   reads.out
21_G_Ok_4_S103_L001_R1_001.fastq   120438     95469
21_G_Ok_5_S104_L001_R1_001.fastq   124858     90474
21_G_Pp_6_S97_L001_R1_001.fastq     127916     96420
21_G_Pp_7_S98_L001_R1_001.fastq     101197     78543
21_I_Ha_6_S99_L001_R1_001.fastq      118954    101274
21_I_Ha_7_S100_L001_R1_001.fastq    144736    123708
 
Also, in the process of filterAndTrim, I thought that if the number (length) of truncLen increased (ex. truncLen=c(280,200)  -> truncLen=c(300,220), more reads.out would be generated, but the number actually decreased (Second vs. Third). I don't understand this result. Thank you for answering this question as well. 

*Third
> out2 <-  filterAndTrim (fnFs, filtFs, fnRs, filtRs, truncLen=c(300,220), trimLeft=c(17,21), maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE)

> head(out2)
                                                            reads.in   reads.out
21_G_Ok_4_S103_L001_R1_001.fastq   120438     84162
21_G_Ok_5_S104_L001_R1_001.fastq   124858     80253
21_G_Pp_6_S97_L001_R1_001.fastq     127916     86206
21_G_Pp_7_S98_L001_R1_001.fastq     101197     69638
21_I_Ha_6_S99_L001_R1_001.fastq      118954     94642
21_I_Ha_7_S100_L001_R1_001.fastq    144736    115751

**Comment by benjjneb** [comment]
> In fact, when I first performed the filterAndTrim function with the same data, most of reads.out passed filtering. However, from the second attempt, a significant number of reads were discarded.

Unless I am missing something, I also don't understand the different numbers of reads that are passing the filter form the same(?) `filterAndTrim` command. Can you speak more to what the differences were here?

> Also, in the process of filterAndTrim, I thought that if the number (length) of truncLen increased (ex. truncLen=c(280,200) -> truncLen=c(300,220), more reads.out would be generated, but the number actually decreased (Second vs. Third). I don't understand this result. Thank you for answering this question as well.

`maxEE` is a summation over the bases that are left after triming/truncation. So, keeping longer reads with a higher `truncL` will cause more reads to be filtered out by the `maxEE` filter, since the additional bases will add to the `EE` score.
