### ISSUE TITLE
Error in removeBimeraDenovo

### ISSUE THREAD

**Issue by JulianMiGoe** [benjjneb/dada2#1792]
Hi,

I face an issue when running the DADA2 pipeline on my 16S data. Im quite new to this field, so maybe the issue is also very basic :) When I run the following command:

> seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)

I receive the following error message. 
Error in if (class(unqs) != "list") { : the condition has length > 1

I get a similar error when running this command:
table(nchar(getSequences(seqtab)))

The seqtab has the sequences as headers and my samples can be found in the rows. 

I thank you in advance for helping me here.

Cheers,
Julian

**Comment by benjjneb** [comment]
What is `dim(seqtab)`?
What is 'head(getSequences(seqtab))`?

**Comment by JulianMiGoe** [comment]
> dim(seqtab)
[1]   12 3729
> head(getSequences(seqtab))
Error in h(simpleError(msg, call)) : Error in evaluating argument 'x' in method selection for function 'head': the condition has length > 1.

**Comment by benjjneb** [comment]
I guess `seqtab` is malformed in some way?
What is `class(seqtab)`?
What is `head(colnames(seqtab))`?

Did you follow the DADA2 tutorial to make these objects?

**Comment by JulianMiGoe** [comment]
Hi, I finally found time again to work on the data. I followed the DADA 2 piepline tutorial. I redid everything until this step and again I receive an error when running this command:

table(nchar(getSequences(seqtab)))
Error in h(simpleError(msg, call)) : 
  Error in evaluating argument 'x' in the method selection for function 'nchar': Condition has length > 1

class(seqtab) is [1] "matrix" "array" 

head(colnames(seqtab)) is 
[1] "TGAGGAATATTGGACAATGGGCGAGAGCCTGATCCAGCCATGCCGCGTGCAGGAAGACGGCCCTATGGGTTGTAAACTGCTTTTATAGAGGAAGAAACACTCCTACGTGTAGGAGCTTGACGGTACTCTACGAATAAGGATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATCCAAGCGTTATCCGGAATCATTGGGTTTAAAGGGTCCGTAGGCGGGACAATCAGTCAGCGGTGAAAGTCTGTGGCTCAACCATAGAATTGCCATTGATACTGTTGTTCTTGAATACTTATGAAGTGGTTGGAATATGTAGTGTAGCGGTGAAATGCATAGATATTACATAGAACACCGATTGCGAAGGCAGATCACTAATAAGTCATTGACGCTGATGGACGAAAGCGTGGGTAGCGAACAGG"  [...]

Do you have any idea how to fix this? Thanks in advance for the help.

Cheers
Julian

**Comment by benjjneb** [comment]
> The sequences being tabled vary in length.

Not an error. Just a message.

**Comment by JulianMiGoe** [comment]
Yes, but I still can´t create the seqtab.nochim. with the removeBimeraDenovo() function.

**Comment by ariannacapparotto** [comment]
Hi, I had the same problem and I solved it by updating dada2 to version 1.28.0

**Comment by JulianMiGoe** [comment]
Hi @ariannacapparotto, this did solve the problem. Thank you! My Version was 1.8., 1.16 did the Job.

> remotes::install_github("benjjneb/dada2", ref = "v1.16")
