### ISSUE TITLE
error loading quality score plots

### ISSUE THREAD

**Issue by sophiasaleki** [benjjneb/dada2#1793]
> plotQualityProfile(fnFs)
Warning messages:
1: In serialize(data, node$con) :
  'package:stats' may not be available when loading
2: In serialize(data, node$con) :
  'package:stats' may not be available when loading
3: In serialize(data, node$con) :
  'package:stats' may not be available when loading
4: The `<scale>` argument of `guides()` cannot be `FALSE`. Use "none" instead as of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the dada2 package.

Not really sure what any of this means.

**Comment by benjjneb** [comment]
It's just a warning, you can ignore.
Also, the warning is fixed in the latest release.
