### ISSUE TITLE
errF <- learnErrors

### ISSUE THREAD

**Issue by genesandbones** [benjjneb/dada2#1794]
Hello,
I've tried to do my due diligence to make sure this hasn't been asked and answered here and I think it has not, though there have been similar and those didn't seem to help me solve it.
#1001 #1659 

I'm getting the following error:
`Error in derepFastq(fls[[i]], qualityType = qualityType) : File paths must be provided in character format`
This error results from running this code for learn errors:
`errF <- learnErrors(file.exists(filtFs), multithread=TRUE)`

My paths look like this:
"C:/Users/OneDrive/Documents/2023-fastq/vertebrate/cutadapt/filtered/1-19-23-Control-16sVert_S542_L001_R1_001.fastq.gz"
"C:/Users/OneDrive/Documents/2023-fastq/vertebrate/cutadapt/filtered/102-12v5f_S270_L001_R1_001.fastq.gz"              
"C:/Users/OneDrive/Documents/2023-fastq/vertebrate/cutadapt/filtered/102-16sVert_S84_L001_R1_001.fastq.gz"  

Any help on what is causing the character format issue would be very helpful. I'm sure it's something super dumb and obvious so sorry if I waste anyone's time. I think I've been staring at this error for too long.

Thanks!

**Comment by benjjneb** [comment]
`file.exists(filtFs)` evalutes as a logical vector, i.e. TRUE/FALSE for each filename.
You just want to call `learnErrors(filtFs, ...)`

**Comment by genesandbones** [comment]
Thanks! That worked
