### ISSUE TITLE
PacBio 16S sequence-reg

### ISSUE THREAD

**Issue by Balakulandai** [benjjneb/dada2#1798]
Hi Benjjneb

I am analysing pacbio 16S sequence (with our adapters and primers), I got error in learn error step
err3 <- learnErrors(drp2, nreads = NULL, qualityType = "Auto", errorEstimationFunction = PacBioErrfun, BAND_SIZE=32, multithread=TRUE)
107424941 total bases in 73433 reads from 2 samples will be used for learning the error rates.
The max qual score of 93 was not detected. Using standard error fitting.
Error rates could not be estimated (this is usually because of very few reads).
Error in getErrors(err, enforce = TRUE) : Error matrix is NULL.
Kindly help to proceed future.

Thank you

**Comment by benjjneb** [comment]
What does the output of `plotQualityProfile` look like?
Have you already performed the primer removal, re-orientation and filtering/trimming steps?

See examples here for our recommended workflow for long-read PacBio 16S data: https://github.com/benjjneb/LRASManuscript
