### ISSUE TITLE
asigntaxonomy command and taxlevels argument

### ISSUE THREAD

**Issue by Guillermouceda** [benjjneb/dada2#1800]
Hello,

I have used the assigntaxonomy command  in the following way:

#### STEP 8. Assigning taxonomy

ITS_2_file <- paste0("databases/ITS2.dada2_format_02_07_2023.fasta.gz")
ITS_2_PLANits_tax_levels <- c("Kingdom","Division", "Class","Order", "Family",
                              "Genus", "Species")

taxa_PLANits <- assignTaxonomy(seqtab.nochim, refFasta = ITS_2_file, taxLevels = ITS_2_PLANits_tax_levels,
                               minBoot = 0, outputBootstraps = TRUE, verbose = TRUE, multithread = TRUE)

I am running dada2 in R version 4.2 (vigorous calisthenics).

My laptop has 8 cores and 16 GB of RAM

The command run smoothly, however when I got the results I had an "NA" colunm next to my assignment to the species levels which had the exact same bootstrap value as species. How Can I solve this issue? My reference database looks like this : 

Viridiplantae;Streptophyta;Jungermanniopsida;Porellales;Lejeuneaceae;Cheilolejeunea;Cheilolejeunea comitans;
CCGACCCACCCACAAAGTCTCTCCTCCTCCTCCTCCTCCTCTTAACTGGGGAGGAGGATCAAGGAGAGTCCAGAGTGCGCGTGGAACTGGTCGTCCGGGAACCCGAACTTTCTCCCTTGCGGAGACGGATTCGAAGGATTCGCGGTTGGCTGAAAAATGGGAGCCGTCCGTCAAGCGCGCGCAGTGGGCAAGGGTGCGTCGCGAGAAGGTGCCGTCCTCTCCTCAGTCTTCGTGACGGGGAGTCGGACGTTCGTAACGAAAGCTTCGTGCCTCCCCTGCGGAGTTCTGTCTTGGCGGATCGGCGGGATACCAAAAACATGGGAACGGGAAGGCTCGGAGACGTCTTCACAGCGCCTCCCTCGCCTCAACAGCGAGGGAGGCGTGTTGGGGGAGATTCCTGCCGGCCTGAACGTGATGTTG
>Viridiplantae;Streptophyta;Bryopsida;Orthotrichales;Orthotrichaceae;Schlotheimia;Schlotheimia jamesonii;
CGCCCCTCACACCGCCGATCCGTCCCGATGACTGCCTCCGGGAGTCCGGGTCGGGTCGAGCGGCAGGTGGCCGTCCCGATGCGTGCGCCGCGTGCTACCACTCGTGTGTTACCTTTTCGGAGCGAAGCGCGTTACCGGTGCGACGGATGCTGATCGGGTCGGCTGAAATGGAGAGAGGGAACTTGGCCGCCGCGGCGACACGGCCCGCGATCGGGTGGATACGAAGACTCTCGAGGGCTCGCTCGCGAGAGCCCCCGGAGTGTGCGTTATGATGCTTTCAAGTGCGCGGTCGCGTCGCCCAGTTCGGCCCCTTTTGCAGTGCGTTCGCCGCATTGCACGGAACCTCGGAGAAAAAGAAAAGCAGGTCCGCGCCGCGCCCGACGACGTGCCAGCCGCGTCGGCGGCGCGCGGCGTGC
>Viridiplantae;Streptophyta;Bryopsida;Orthotrichales;Orthotrichaceae;Schlotheimia;Schlotheimia tecta;
CGCCCCTCACACCGCCGATCCGTCCCGACGGGTCGAGCGGCAGGTGGCCGTCCCGATGCGTGCGTCACCCCGTGCGTGCGCGCGTTGCCTCTTCGGAGCGAAGCGCGTGGCCGGTGCGACGGACGGTGATCGGGTCGGCTGAAATGGAGAGAGAGAGGGAACTTGGCCGCCGTGGCGACACGGCCCGCGATCGGGTGGATACGCACATTCCCGAGGGCTCGCTCGCGAGAGTCCCGGCCGGAGTGTGCGTTATGATGCTTTCAAGTGCGCGGTCGCGCCGCCCAGTTCGGCCCCTTCCGTCGCGTTGCGCTCGCCGCACTGCACGGAGAACCCTCGGAGAAAAGAAGAGAGCAGGTCCGCGCCGCGCCCGATGACGTGCCAGCCGCGTCGGCGGCGCGCGGCGTGC
>Viridiplantae;Streptophyta;Bryopsida;Orthotrichales;Orthotrichaceae;Schlotheimia;Schlotheimia appressifolia;
CGCCCCTCACACCGCCGATCCGTCCCGACGGGTCGAGCGGCAGGTGGCCGTCCCGATGCGTGCGTCACCCCGCGCGTGCGCGCGTTACCTCTTCGGAGCGAAGCGCGTCGCCGGTGCGACGGACGGTGATCGGGTCGGCTGAAATGGAGAGAGAGAGGGAACTTGGCCGCCGTGGCGACACGGCCCGCGATCGGGTGGATACGCACATTCCCGAGGGCTCGCTCGCGAGAGTCCCGACCGGAGTGTGCGTTATGATGCTTTCAAGTGCGCGGTCGCGCCGCCCAGTTCGGCCCCTCCCGTCGCATTGCGCTCGCCGCATTGCGCGGAGGACCTCGGAGAAAAGAAAACAGCAGGTCCGCGCCGCGCCCGACGACGTGCCAGCCGCGTCGGCGGCGCGCGGCGTGC
>Viridiplantae;Streptophyta;Bryopsida;Orthotrichales;Orthotrichaceae;Schlotheimia;Schlotheimia appressifolia;
CGCCCCTCACACCGCCGATCCGTCCCGACGGGTCGAGCGGCAGGTGGCCGTCCCGATGCGTGCGTCACCCCGTGCGTGCGCGCGTTGCCTCTTCGGAGCGAAGCGCGTCGCCGGTGCGACGGACGGCGAACGGGTCGGCTGAAATGGAGAGAGAGAGGGAACTTGGCCGCCGTGGCGACACGGCCCGCGATCGGGTGGATACGCACATTCCCGAGGGCTCGCTCGCGAGAGTCCCGGCCGGAGTGTGCGTTATGATGCTTTCAAGTGCGCGGTCGCGCCGCCCAGTTCGGCCCCTCCCGTCGCATTGCGCTCGCCGCATTGCGCGGAGGACCTCGGAGAAAAGAAAACAGCAGGTCCGCGCCGCGCCCGACGACGTGCCAGCCGCGTCGGCGGCGCGCGGCGTGC
>Viridiplantae;Streptophyta;Magnoliopsida;Proteales;Sabiaceae;Sabia;Sabia swinhoei;
ATTGCGACACTCCGACCCAAACGCTCGATGCGGCGTTTGGACGCGAAGTGGAGATTGGCTTCCCGTGCTCTCTATTGCGCGGTTGGCCTAAAAGCCGGCCCTCGGCGGTGAGCCTCACGATGATTGGTGGTTGATCGAAACCCCTTGGCATTGGTGGAACTTCGGGCCGGTGGTGGGGCCGCCCCCGAACCTTTCATTCCCCTTATGGAACGGTGTCCTAACCACCAACCTTACCCTGGGACCCCCGGGCCAGGGAAAACCCCCCCTTAATTTTAACCTATTCATTAACCGAAGAAAAAAAACTTTACAAGGTTTCCCTTATAACCGCCAAGGGAACCGGGTCCGGCCCACTTGGAAAATCGAACGCCCCGGCCTCCGAATTGGAATCTGAGAAAAGCTCACA

Thank you very much in advance!!

**Comment by benjjneb** [comment]
I would try replacing the spaces in the species names with an underscore in the reference fasta file.

That said, what is the dimension of the `taxa_PLANits$taxa` object after this runs? 7 columns? or 8?

**Comment by Guillermouceda** [comment]
Hello @benjjneb  The dimensions are the following:

> dim(taxa_PLANits$tax)
[1] 718   8

Okay I will try to run it again with the suggested changes and I will go back to you with th results.

Thank you for your help!

**Comment by Dianapthv** [comment]
> Hello,
> 
> I have used the assigntaxonomy command in the following way:
> 
> #### STEP 8. Assigning taxonomy
> ITS_2_file <- paste0("databases/ITS2.dada2_format_02_07_2023.fasta.gz") ITS_2_PLANits_tax_levels <- c("Kingdom","Division", "Class","Order", "Family", "Genus", "Species")
> 
> taxa_PLANits <- assignTaxonomy(seqtab.nochim, refFasta = ITS_2_file, taxLevels = ITS_2_PLANits_tax_levels, minBoot = 0, outputBootstraps = TRUE, verbose = TRUE, multithread = TRUE)
> 
> I am running dada2 in R version 4.2 (vigorous calisthenics).
> 
> My laptop has 8 cores and 16 GB of RAM
> 
> The command run smoothly, however when I got the results I had an "NA" colunm next to my assignment to the species levels which had the exact same bootstrap value as species. How Can I solve this issue? My reference database looks like this :
> 
> Viridiplantae;Streptophyta;Jungermanniopsida;Porellales;Lejeuneaceae;Cheilolejeunea;Cheilolejeunea comitans; CCGACCCACCCACAAAGTCTCTCCTCCTCCTCCTCCTCCTCTTAACTGGGGAGGAGGATCAAGGAGAGTCCAGAGTGCGCGTGGAACTGGTCGTCCGGGAACCCGAACTTTCTCCCTTGCGGAGACGGATTCGAAGGATTCGCGGTTGGCTGAAAAATGGGAGCCGTCCGTCAAGCGCGCGCAGTGGGCAAGGGTGCGTCGCGAGAAGGTGCCGTCCTCTCCTCAGTCTTCGTGACGGGGAGTCGGACGTTCGTAACGAAAGCTTCGTGCCTCCCCTGCGGAGTTCTGTCTTGGCGGATCGGCGGGATACCAAAAACATGGGAACGGGAAGGCTCGGAGACGTCTTCACAGCGCCTCCCTCGCCTCAACAGCGAGGGAGGCGTGTTGGGGGAGATTCCTGCCGGCCTGAACGTGATGTTG
> 
> > Viridiplantae;Streptophyta;Bryopsida;Orthotrichales;Orthotrichaceae;Schlotheimia;Schlotheimia jamesonii;
> > CGCCCCTCACACCGCCGATCCGTCCCGATGACTGCCTCCGGGAGTCCGGGTCGGGTCGAGCGGCAGGTGGCCGTCCCGATGCGTGCGCCGCGTGCTACCACTCGTGTGTTACCTTTTCGGAGCGAAGCGCGTTACCGGTGCGACGGATGCTGATCGGGTCGGCTGAAATGGAGAGAGGGAACTTGGCCGCCGCGGCGACACGGCCCGCGATCGGGTGGATACGAAGACTCTCGAGGGCTCGCTCGCGAGAGCCCCCGGAGTGTGCGTTATGATGCTTTCAAGTGCGCGGTCGCGTCGCCCAGTTCGGCCCCTTTTGCAGTGCGTTCGCCGCATTGCACGGAACCTCGGAGAAAAAGAAAAGCAGGTCCGCGCCGCGCCCGACGACGTGCCAGCCGCGTCGGCGGCGCGCGGCGTGC
> > Viridiplantae;Streptophyta;Bryopsida;Orthotrichales;Orthotrichaceae;Schlotheimia;Schlotheimia tecta;
> > CGCCCCTCACACCGCCGATCCGTCCCGACGGGTCGAGCGGCAGGTGGCCGTCCCGATGCGTGCGTCACCCCGTGCGTGCGCGCGTTGCCTCTTCGGAGCGAAGCGCGTGGCCGGTGCGACGGACGGTGATCGGGTCGGCTGAAATGGAGAGAGAGAGGGAACTTGGCCGCCGTGGCGACACGGCCCGCGATCGGGTGGATACGCACATTCCCGAGGGCTCGCTCGCGAGAGTCCCGGCCGGAGTGTGCGTTATGATGCTTTCAAGTGCGCGGTCGCGCCGCCCAGTTCGGCCCCTTCCGTCGCGTTGCGCTCGCCGCACTGCACGGAGAACCCTCGGAGAAAAGAAGAGAGCAGGTCCGCGCCGCGCCCGATGACGTGCCAGCCGCGTCGGCGGCGCGCGGCGTGC
> > Viridiplantae;Streptophyta;Bryopsida;Orthotrichales;Orthotrichaceae;Schlotheimia;Schlotheimia appressifolia;
> > CGCCCCTCACACCGCCGATCCGTCCCGACGGGTCGAGCGGCAGGTGGCCGTCCCGATGCGTGCGTCACCCCGCGCGTGCGCGCGTTACCTCTTCGGAGCGAAGCGCGTCGCCGGTGCGACGGACGGTGATCGGGTCGGCTGAAATGGAGAGAGAGAGGGAACTTGGCCGCCGTGGCGACACGGCCCGCGATCGGGTGGATACGCACATTCCCGAGGGCTCGCTCGCGAGAGTCCCGACCGGAGTGTGCGTTATGATGCTTTCAAGTGCGCGGTCGCGCCGCCCAGTTCGGCCCCTCCCGTCGCATTGCGCTCGCCGCATTGCGCGGAGGACCTCGGAGAAAAGAAAACAGCAGGTCCGCGCCGCGCCCGACGACGTGCCAGCCGCGTCGGCGGCGCGCGGCGTGC
> > Viridiplantae;Streptophyta;Bryopsida;Orthotrichales;Orthotrichaceae;Schlotheimia;Schlotheimia appressifolia;
> > CGCCCCTCACACCGCCGATCCGTCCCGACGGGTCGAGCGGCAGGTGGCCGTCCCGATGCGTGCGTCACCCCGTGCGTGCGCGCGTTGCCTCTTCGGAGCGAAGCGCGTCGCCGGTGCGACGGACGGCGAACGGGTCGGCTGAAATGGAGAGAGAGAGGGAACTTGGCCGCCGTGGCGACACGGCCCGCGATCGGGTGGATACGCACATTCCCGAGGGCTCGCTCGCGAGAGTCCCGGCCGGAGTGTGCGTTATGATGCTTTCAAGTGCGCGGTCGCGCCGCCCAGTTCGGCCCCTCCCGTCGCATTGCGCTCGCCGCATTGCGCGGAGGACCTCGGAGAAAAGAAAACAGCAGGTCCGCGCCGCGCCCGACGACGTGCCAGCCGCGTCGGCGGCGCGCGGCGTGC
> > Viridiplantae;Streptophyta;Magnoliopsida;Proteales;Sabiaceae;Sabia;Sabia swinhoei;
> > ATTGCGACACTCCGACCCAAACGCTCGATGCGGCGTTTGGACGCGAAGTGGAGATTGGCTTCCCGTGCTCTCTATTGCGCGGTTGGCCTAAAAGCCGGCCCTCGGCGGTGAGCCTCACGATGATTGGTGGTTGATCGAAACCCCTTGGCATTGGTGGAACTTCGGGCCGGTGGTGGGGCCGCCCCCGAACCTTTCATTCCCCTTATGGAACGGTGTCCTAACCACCAACCTTACCCTGGGACCCCCGGGCCAGGGAAAACCCCCCCTTAATTTTAACCTATTCATTAACCGAAGAAAAAAAACTTTACAAGGTTTCCCTTATAACCGCCAAGGGAACCGGGTCCGGCCCACTTGGAAAATCGAACGCCCCGGCCTCCGAATTGGAATCTGAGAAAAGCTCACA
> 
> Thank you very much in advance!!

Hello! How you did ITS2 dada formatted file? In this paper https://academic.oup.com/database/article/doi/10.1093/database/baz155/5722079 i found only qiime formatted files. What command did you use?
