### ISSUE TITLE
ggplot2 issue

### ISSUE THREAD

**Issue by nstrom1** [benjjneb/dada2#1801]
Warning message:
The `<scale>` argument of `guides()` cannot be `FALSE`. Use "none" instead as
of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the dada2 package.
  Please report the issue at <https://github.com/benjjneb/dada2/issues>.

**Comment by benjjneb** [comment]
Fixed in current version https://github.com/benjjneb/dada2/commit/b6ab04f50988e91796453887bd15889f81ee99cb
