### ISSUE TITLE
Losing reads after removing chimera

### ISSUE THREAD

**Issue by osidaksjdmw** [benjjneb/dada2#1802]
Why am I losing so many reads?

input | filtered | denoisedF | denoisedR | merged | nonchim
-- | -- | -- | -- | -- | --
181466 | 168849 | 167603 | 168522 | 155409 | 117662
234405 | 198046 | 196764 | 197234 | 183464 | 151856
178082 | 165036 | 164049 | 164878 | 150686 | 116789
224946 | 198353 | 196276 | 197705 | 175799 | 137858
208946 | 195905 | 195180 | 195684 | 189546 | 159323
215400 | 203697 | 203080 | 203520 | 195979 | 160683
218380 | 206969 | 206560 | 206765 | 200389 | 170952
235340 | 221807 | 221474 | 221690 | 214976 | 187189
220709 | 207558 | 207082 | 207442 | 200309 | 172489
221437 | 208722 | 207757 | 208380 | 201351 | 173869
204066 | 192495 | 192100 | 192365 | 185427 | 147102
204423 | 193139 | 192372 | 192728 | 185481 | 153933
188929 | 177377 | 177027 | 177227 | 171822 | 149336
192627 | 180564 | 179546 | 180367 | 165207 | 127879
194010 | 182382 | 181360 | 182100 | 167380 | 127981
230727 | 218303 | 217126 | 218149 | 201555 | 155343
204629 | 194081 | 192711 | 193702 | 176264 | 128818

Primers used are 515F and 806R which I removed using filter and trim:
```
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(290,220), trimLeft=c(19,20), maxN = 0,
                              maxEE = c(2, 3), truncQ = 2, rm.phix = TRUE, compress = TRUE, multithread = FALSE)
```

**Comment by benjjneb** [comment]
In 90\% of cases, losing too many (>25\%) of reads in most samples is a signal that primer removal was incomplete in some way. When you inspect your raw data, do you see that e.g. the forward primer is there at the start of the R1 reads? In essentially all R1 reads? And without any other variable base-length inserts? Similarly for reverse primer/R2?

The other question then, is are you reading into the other primer and therefore keeping it at the ends of the reads? How long is this sequenced amplicon? Is 290 nts too long a truncation length for the forward reads? You want to truncate the reads before they reach the other primer.

**Comment by osidaksjdmw** [comment]
Thanks, I shortened the truncation length of the forward reads and it's good now!
