### ISSUE TITLE
denoise-ccs for ITS

### ISSUE THREAD

**Issue by Hobgoblin8** [benjjneb/dada2#1803]
Excuse me,
We are using denoise -ccs to denoise a set of ITS full-length PacBio CCS sequences, do you have the suggested p-min-len and p-max-len values ?
Thank you.

**Comment by benjjneb** [comment]
I don't. You will need to consider the expected lengths of the sequence region as defined by your PCR primers.

If this isn't something you already have an idea of, you might consider using a reference database like UNITE or a fungal genome reference database, and performing an in silico PCR and inspecting the distribution of lengths.
