### ISSUE TITLE
errf 

### ISSUE THREAD

**Issue by KOMALSKK** [benjjneb/dada2#1804]
i got following result on running thr code for errf and errR
> errF <- learnErrors(filtFs, multithread=TRUE)
78547440 total bases in 327281 reads from 1 samples will be used for learning the error rates.
> errR <- learnErrors(filtRs, multithread=TRUE)
52364960 total bases in 327281 reads from 1 samples will be used for learning the error rates.

However when I run the next code : 
dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
dadaRs <- dada(filtRs, err=errR, multithread=TRUE) 
 I get error ; Error: object 'errF' not found ( got result for errR)

**Comment by hourfanesohaib** [comment]
u find the solution ?
