### ISSUE TITLE
Error in is(obj, "matrix") : object 'errF' not found

### ISSUE THREAD

**Issue by KOMALSKK** [benjjneb/dada2#1805]
I keep getting this error :Error in is(obj, "matrix") : object 'errF' not found. 
I ran the following code 
errF <- learnErrors(filtFs, multithread=TRUE)
errR <- learnErrors(filtRs, multithread=TRUE)
dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
dadaRs <- dada(filtRs, err=errR, multithread=TRUE)
 
I got following results:
 errF <- learnErrors(filtFs, multithread=TRUE)
144375360 total bases in 601564 reads from 2 samples will be used for learning the error rates.

> errR <- learnErrors(filtRs, multithread=TRUE)
149950880 total bases in 937193 reads from 3 samples will be used for learning the error rates.

> dadaRs <- dada(filtRs, err=errR, multithread=TRUE)
Sample 1 - 327281 reads in 46779 unique sequences.
Sample 2 - 274283 reads in 48547 unique sequences.

However when i get no result for dadaFs and get error :
> dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
Error in is(obj, "matrix") : object 'errF' not found

Kindly note: although i get result for errF, the variable is not visible in R environment.
I had same issue before, however last time I was using R in windows and reinstalling R resolved the issue
however now I m using R on a linux system.

**Comment by benjjneb** [comment]
> the variable is not visible in R environment

Did you reset your R session between running `errF <- learnErrors(...)` and `dada(filtFs, err=errF, ...)`?
Or do something else that caused the `errF` variable to be deleted?

If it's not visible in your session, you'll just have to rerun that step.

**Comment by benjjneb** [comment]
I don't know. This seems to be some fundamental issue with assignment to a variable in your R session, not anything directly related to the dada2 R package.

Maybe try saving errF right after creating it: `saveRDS(errF, "path/to/errF.rds")`. Then you can reload it later with `errF <- readRDS("path/to/errF.rds")`.
