### ISSUE TITLE
The lengths are different between dereps an dadas

### ISSUE THREAD

**Issue by suzywang116** [benjjneb/dada2#1806]
I would like to do the data preprocessing: from fastq to ASV and I faced problem when I conducted merging paired reads.

```{r quality_filtering}
# Load raw fastq files
fastq_files <- c("T_3xTg_AD_HE1_1_R1.fastq", "T_3xTg_AD_HE1_1_R2.fastq")
filt_path <- "C:/Users/Wsh10/Desktop/test"
sample.names <- "T_3xTg_AD_HE1_1"
fnFs <- sort(list.files(filt_path, pattern="_R1.fastq", full.names = TRUE))
fnRs <- sort(list.files(filt_path, pattern="_R2.fastq", full.names = TRUE))
# Place filtered files in filtered/ subdirectory
filtFs <- file.path(filt_path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(filt_path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
names(filtFs) <- "T_3xTg_AD_HE1_1"
names(filtRs) <- "T_3xTg_AD_HE1_1"
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
                     maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, multithread=FALSE, matchIDs=TRUE) # Set multithread=TRUE except on Windows where multithread=FALSE
head(out)
```
```{r denoising}
# Learn the Error Rates
errF <- learnErrors(filtFs, multithread=TRUE)
errR <- learnErrors(filtRs, multithread=TRUE)
plotErrors(errF, nominalQ=TRUE)
# Dereplicate
derepFs <- derepFastq(filtFs, verbose = TRUE)
derepRs <- derepFastq(filtRs, verbose = TRUE)
# Sample Inference
dadaFs <- dada(derepFs, err=errF, multithread=TRUE)
dadaRs <- dada(derepFs, err=errR, multithread=TRUE)

length(dadaFs)
length(derepFs)
```

```{r merging}
# Merge paired reads
mergers_1 <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE)
# Inspect the merger data.frame from the first sample
head(mergers[[1]])
```

**Comment by suzywang116** [comment]
The length of dadaFs is 11 and the length of derepFs is 3. I have no idea why the lengths are different.

**Comment by benjjneb** [comment]
> The length of dadaFs is 11 and the length of derepFs is 3. I have no idea why the lengths are different.

You are processing a single sample here, so `length` is returning the number of parts in a `dada-class` and `derep-class` object, respectively, rather than the number of samples as it would if you were processing multiple samples.

That said, this code should still work with a single sample. What was the problem with the merging step?

**Comment by suzywang116** [comment]
Hey Benjamin,

Thanks for the explanation. When I conducted the mergePairs() function, the
error msg showed Error in FUN(X[[i]], ...) :
Non-corresponding derep-class and dada-class objects. I would like to know
how to fix the problem.
Thanks again for your help.

**Comment by benjjneb** [comment]
I think it's just a typo in the code:

```
dadaRs <- dada(derepFs, err=errR, multithread=TRUE)
```

Try replacing `derepFs` there with `derepRs`.

**Comment by suzywang116** [comment]
Hey Ben,
Thanks for the help. I fix the typo and the function works. However, the
message shows that "0 paired-reads (in 0 unique pairings) successfully
merged out of 68986 (in 14253 pairings) input." The primer used for this
experiment is (341F/805R) designed to target the V3 and V4 regions of 16S
rDNA generate an amplicon about 465 bp in size. The amplified library is
sequenced on a NovaSeq platform with 250 bp paired-end reads mode (2 x 250
bp). What I did for trimming: filterAndTrim(fnFs, filtFs, fnRs, filtRs,
truncLen=c(240,160), maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
compress=TRUE,
multithread=FALSE, matchIDs=TRUE)
Is anything I did wrong? Really appreciate that you reply so quickly~

Suzy

**Comment by benjjneb** [comment]
What is the expected length of the amplicon you sequenced?

**Comment by suzywang116** [comment]
I think it's 465 bp in size.

**Comment by benjjneb** [comment]
For a sequenced amplicon of ~465 bps, a `truncLen=c(240,160)` will cause merging to fail. A forward read truncated at 240bp and a reverse read ttruncated at 160bp will not meet in the middle of a 465bp sequenced amplicon, and so won't be merged.

I would recommend revisting your `truncLen` and aiming for a total (the sum of the two numbers) greater than ~465 plus 16 nts of overlap.

**Comment by suzywang116** [comment]
Hey Ben,

As a new beginner in microbiome analysis, I know my question may be very
basic. The experimental process shows below: The primers (341F/805R)
designed to target the *V3 *and *V4* regions of 16S rDNA generate an
amplicon about 465 bp in size. The amplified library is sequenced on a
NovaSeq platform with *250 bp paired-end reads mode (2 x 250 bp).*
I have tried to modify the truncLen=c(240,160) to c(250, 250). c(260,260)
but the reads.out turn to 0.

Suzy

**Comment by benjjneb** [comment]
Your reads are only 250 nts in length, so trying to enforce a truncation length higher than that (like `truncLen=c(260, 260)`) will cause all reads to be lost.
