### ISSUE TITLE
How long does it take for R to assign fungal taxonomies?

### ISSUE THREAD

**Issue by LordoftheMelons** [benjjneb/dada2#1808]
My issue is similar to MarwaElnaiem's #949 issue in 2020. I'm running on a 16GB RAM computer with a Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz   2.30 GHz processor. My DADA2 package version is 1.29.0.

I've been following your DADA2 ITS workflow and have gotten to the part where I get to assign taxonomies. The command was

taxa <- assignTaxonomy(seqtab.nochim, unite.ref, multithread = TRUE, tryRC = TRUE)

and it says UNITE fungal taxonomic reference detected.

However, it's been running for several hours now. I've assigned taxonomies before for 16S and it didn't take this long.

**Comment by pratyusha2908** [comment]
I have the same issue. DADA2 package version is 1.28.0. The taxonomy assignment is taking a very long time. 
Command: 
taxa_its<- assignTaxonomy(seqtab.nochim_its, unite.ref, multithread = TRUE, tryRC = TRUE)
"UNITE fungal taxonomic reference detected." shows up almost immediately, but then it ran for several hours. What can be done about this?

**Comment by benjjneb** [comment]
You can try to get a better sense of the total running time for your sequence set by running taxonomic assignments on subsets of the data. For exasmple, how long does taxonomic assignment on the first e.g. 5k sequences take?

The second thing is making sure you have enough memory. If `assignTaxonomy` runs out of working memory and has to resort to "swapping", it becomes dramatically slower.

**Comment by pratyusha2908** [comment]
Okay, I'll try these. Thank you for the response!

**Comment by sadia-marjia** [comment]
I am facing this similar issue using dada2 version 1.32
The assignTaxonomy function takes long time leading to crash of Rstudio.

**Comment by jorondo1** [comment]
I might add here, currently running assignTaxonomy on about 20 000 ASVs using the UNITE database for ITS. Using 72 cores, I'm over 1.5 hour and not sure if that's normal. No memory issue, 0 swap going on (there's about 2 terabytes of memory on this system). Is it possible that using too many cores creates problems somehow? Could multithreading overhead be at play with that many cores? I assume each ASV would be treated independently so I'm not sure why that would be the case though.

**Comment by benjjneb** [comment]
@jorondo1 I only ever tested up to 8 cores, but yes -- this is a trivially parallelizable problem so I would expect you'd get near-linear scaling with available cores even up to 72.

What I would want to check though: Which UNITE reference file are you using? I.e. what's the filename?

**Comment by jorondo1** [comment]
currently sh_general_release_dynamic_04.04.2024.fasta, it has about 90k seqs

**Comment by benjjneb** [comment]
That file should work.

Give it some more time? I don't do a lot of ITS analysis so I don't have a mental idea of how long ITS assignment should take. If after, say, 24 hours it's not done, then maybe revisit.

**Comment by jorondo1** [comment]
It ended up finishing in about 1h45. I was just not expecting it to take so long with so many cores. Thanks for your input!
