### ISSUE TITLE
Aborted R session with DADA2 run for a large number of PacBio-sequenced samples

### ISSUE THREAD

**Issue by emankhalaf** [benjjneb/dada2#1809]
Hi,
I have ~650 16S PacBio sequenced samples and am following the DADA2 tutorial for PacBio reads. I successfully used this tutorial with different projects, but given the large number of samples here, every time I run the script, it fails at the dereplication step with the abortion of the R session. I would appreciate your help in dealing with this issue!

Thanks!

**Comment by benjjneb** [comment]
I think this is probably worked around naturally by dropping the explicit dereplication step (as in [the current DADA2 tutorial](https://benjjneb.github.io/dada2/tutorial.html)).

That is, drop the `derepFastq` calls, and replace the `drp` arguments to `learnErrors` and `dada` with the vector of filtered filenames instead (`filts`). This will lead to dereplication being performed "on the fly" one sample at a time, and thus avoid loading all the samples into memory at once.

**Comment by emankhalaf** [comment]
@benjjneb 

Since I have this:
```
filts2 <- file.path(path2, "noprimers", "filtered", basename(fns2))
track2 <- filterAndTrim(nops2, filts2, minQ=3, minLen=1300, maxLen=1600, maxN=0, rm.phix=FALSE, maxEE=2)
track2
```
So, I should use `track2` not `filts `with `learnErrors` and `dada`, correct?

Thanks!

**Comment by benjjneb** [comment]
No, `track2` is just a table showing the numbers of reads for that passed filtering. `filts2` is the vector of filenames. That is what is needed for `learnErrors` and `dada`.

**Comment by benjjneb** [comment]
You won't be able to run this with `pool=TRUE`, as that requires loading all samples into memory, which you don't have enough memory to accomplish.

You can run it with `pool="pseudo"` instead (see more on pseudo-pooling here: https://benjjneb.github.io/dada2/pseudo.html#pseudo-pooling)

**Comment by emankhalaf** [comment]
@benjjneb 
The reason behind using `pool=TRUE` is that I tested both pool=pseudo and pool=TRUE for subsets of samples (each from a genotype) and I found a slight difference in the resultant taxonomy. My project is focused on taxa transmission across tissues. So, when I pooled (`pool=TRUE`) samples from different tissues, I got more taxa in common between these tissues than when using `pool=pseudo`. Does this mean there is no way here but to use `pool=pseudo `to pass the dada step?

**Comment by benjjneb** [comment]
> Does this mean there is no way here but to use pool=pseudo to pass the dada step?

The other option is finding a large memory compute node that can handle loading the entire study into memory.

**Comment by emankhalaf** [comment]
@benjjneb 
Will do! Thanks so much!

**Comment by emankhalaf** [comment]
@benjjneb 
Do you think Colab would work for this big number of samples?

**Comment by benjjneb** [comment]
I don't know what that is. In general, I can't offer much useful guidance on specific cloud/server compute platforms.

**Comment by emankhalaf** [comment]
@benjjneb 
Google Colaboratory "Colab"  is a cloud-based Jupyter notebook environment. Sorry for asking so many questions, and thanks so much for your advice and support.
