### ISSUE TITLE
Parallelization with dada2 big data workflow

### ISSUE THREAD

**Issue by luisymbio** [benjjneb/dada2#1810]
Hello!

I'm trying to use the workflow designed for big data on a HPC using 4 tasks and 9 cpu for tasks.

mergers <- vector("list", length(sample.names))

names(mergers) <- sample.names

cores_per_task <- 9

process_samples <- function(sam) {
for(sam in sample.names) {
  cat("Processing:", sam, "\n")
    derepF <- derepFastq(filtFs[[sam]])
    ddF <- dada(derepF, err=errF, multithread=TRUE)
    derepR <- derepFastq(filtRs[[sam]])
    ddR <- dada(derepR, err=errR, multithread=TRUE)
    merger <- mergePairs(ddF, derepF, ddR, derepR)
    
return(list(sample_name = sam, merged_data = merger))
}
}

# Initialize a parallel cluster with the desired number of CPU cores per task
tasks <- 3  # Number of tasks
total_cores <- tasks * cores_per_task
cl <- makeCluster(total_cores)

# Split the sample names into chunks for parallel processing
sample_chunks <- split(sample.names, ceiling(seq_along(sample.names) / tasks))

# Parallelize the sample processing and store the results
results <- clusterApply(cl, sample_chunks, process_sample)

# Stop the parallel cluster
stopCluster(cl)

# Merge the results into a single list
mergers <- vector("list", length(sample.names))
names(mergers) <- sample.names
for (result in results) {
  mergers[[result$sample_name]] <- result$merged_data
}

rm(derepF); rm(derepR)

# Construct sequence table and remove chimeras
seqtab <- makeSequenceTable(mergers)

output_directory=/bioinf/home/lgallucc/tagseq_deepmining/RData/

save.image(file.path(output_directory, "mergers.RData")

I'm using a SLURM workload manager and after set it on a .sh file and runned the script with sbatch.

Could you provide me a feedback on the setting of the R script for the right use of parallelization?

**Comment by benjjneb** [comment]
Sorry I can't help with how to direct cluster resources from inside the R environment, you would need to look for support from the package that implements e.g. `makeCluster`.

**Comment by luisymbio** [comment]
ok, thank you!

I managed to do it, can you help me with another question?

I'm trying to create a track from the Big data paired end workflow, but running

`track <- cbind(out, sapply(ddF, getN), sapply(ddR, getN), sapply(mergers, getN), rowSums(seqtab.nochim))`

it will give me this output

`track <- cbind(out, sapply(ddF, getN), sapply(ddR, getN), sapply(mergers, getN), rowSums(seqtab.nochim))
Error in getUniques(x) : 
  Unrecognized format: Requires named integer vector, fastq filename, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.`

Do you have a different way in this workflow to obtain the tracking of reads along the pipeline?

**Comment by benjjneb** [comment]
You are probably processing just 1 sample at a time in the script that is producing that error. The line throwing the error just needs to be updated to handle the case of single samples. I think the following should work

```
track.1 <- cbind(out, getN(ddF), getN(ddR), getN(mergers), rowSums(seqtab.nochim))
```

**Comment by luisymbio** [comment]
I managed it, thank you, there was a problem in the object produced during the pipeline with subsequently error!
