### ISSUE TITLE
Remove a cycle without discarding reads

### ISSUE THREAD

**Issue by ajaltomare** [benjjneb/dada2#1811]
Hello,

I am wondering if there is an easy way to ignore a particular cycle from analysis -- it looks like reads with N calls are meant to be discarded entirely. I see that there is an argument maxN in filterAndTrim, but it seems like values greater than zero may not be fully supported. Any plans to support that in the near future? Any advice is appreciated.

Thank you,
Andrew

**Comment by benjjneb** [comment]
The `trimLeft` and `truncLen` steps are applied prior to assessing the number of Ns in a sequence, so if the one-off Ns are at the start or end of the reads, then these are solutions.

You would need to use an external tool to remove a single nucleotide from every read though.

**Comment by ajaltomare** [comment]
My concern is that if we remove a single nucleotide from every read the ASVs will all have an indel. And I don't really want to discard a nucleotide from every read. Is there any plan to allow N in the analysis? I would be willing to contribute a pull request if you think that is a desirable feature.

**Comment by benjjneb** [comment]
We don't intend to support this -- it is not trivial to do so in DADA2 as it requires an extension of the error model to incorporate Ns.
