### ISSUE TITLE
Filtering Phyla that have low feature prevalence

### ISSUE THREAD

**Issue by Ecotone23** [benjjneb/dada2#1813]
Hi Ben @benjjneb ,

I was filtering low-abundance Phyla following your paper: Bioconductor Workflow for Microbiome Data Analysis: from raw reads to community analyses and ended up detecting all my Phyla in very low prevalence before filtering. I wonder if you could assist in pinpointing any issues either with my samples or my R scripts. 

Initially, my samples underwent processing via the DADA2 pipeline, leading to the successful construction of the phyloseq object as follows:
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 1011 taxa and 223 samples ]
sample_data() Sample Data:       [ 223 samples by 4 sample variables ]
tax_table()   Taxonomy Table:    [ 1011 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 1011 tips and 1010 internal nodes ]

Then I followed the R scripts outlined in your paper to filter low-abundance Phyla:

rank_names(ps)
table(tax_table(ps)[, "Phylum"], exclude = NULL)
#filter phyla that only have 1 feature
ps0 <- subset_taxa(ps, !is.na(Phylum) & !Phylum %in% c("Other","FBP", "Gemmatimonadetes", "Nanoarchaeaeota", "Omnitrophicaeota","Spirochaetes","WPS-2","uncharacterized"))
#Prevalence filtering
# Compute prevalence of each feature, store as data.frame
prevdf <- apply(X = otu_table(ps0),
                MARGIN = ifelse(taxa_are_rows(ps0), yes = 1, no = 2),
                FUN = function(x){sum(x > 0)})
# Add taxonomy and total read counts to this data.frame
prevdf <- data.frame(Prevalence = prevdf,
                     TotalAbundance = taxa_sums(ps0),
                     tax_table(ps0))
plyr::ddply(prevdf, "Phylum", function(df1){cbind(mean(df1$Prevalence),sum(df1$Prevalence))})
# and I got a table like this:
![Screenshot 2023-09-11 at 12 32 44 PM](https://github.com/benjjneb/dada2/assets/110413335/821deb73-9d84-458e-8db8-33546e67dd3e)

How to interpret this table, particularly what is the meaning for column 1 and 2? Is it mean all my Phyla have very low prevalence?

#Next, when I plotted the abundance data, I noticed that nearly all of the values were below 0.05, which renders it impractical to filter out phykla instances below this threshold, as was done in the paper. 
# Subset to the remaining phyla
prevdf1 <- subset(prevdf, Phylum %in% get_taxa_unique(ps0, "Phylum"))
# Plot
ggplot(prevdf1, aes(TotalAbundance, Prevalence / nsamples(ps0),color=Phylum)) +
  geom_point(size = 2, alpha = 0.7) +
  geom_hline(yintercept = 0.05, alpha = 0.5, linetype = 2) +
  scale_x_log10() +  xlab("Total Abundance") + ylab("Prevalence [Frac. Samples]") +
  facet_wrap(~Phylum) + theme(legend.position="none")
<img width="1135" alt="Screenshot 2023-09-11 at 12 36 56 PM" src="https://github.com/benjjneb/dada2/assets/110413335/51c85f69-1a3c-4f31-b1b4-441b0cb38c50">

Thank you in advance.

Best regards,
Gabriel

**Comment by Ecotone23** [comment]
These codes are from your paper published on F1000 Research. I was just trying to filter low-abundance phyla using 5% as the prevalence threshold, which may be considered as artifacts or noises. But most of my phyla have lower than 5% prevalence when I ran the the R codes. From the workflow,  I did not see tax_glom is used to collapse phyloseq object into a phyla-level object before calculating the prevalence of phyla. Here is the screen shot from the paper:
<img width="825" alt="Screenshot 2023-09-11 at 3 50 39 PM" src="https://github.com/benjjneb/dada2/assets/110413335/95ec5f7c-fab5-406b-8454-8c2621b57e10">

<img width="816" alt="Screenshot 2023-09-11 at 3 51 01 PM" src="https://github.com/benjjneb/dada2/assets/110413335/222dec6e-a91f-4921-99b6-9c332e4be6ee">

Am I supposed to run tax_glom before calculating the prevalence of phyla? 

Thanks

**Comment by benjjneb** [comment]
The codes you are referencing do not calculate phylum prevalence. They calculate the mean and total prevalence of each "feature" (read as OTU or ASV) that belongs to each phylum. That doesn't sound like what you want to be calculating.

If you `tax_glom` at the phylum level, you will be able to more straightforwardly calculate the prevalence of each phylum.

**Comment by Ecotone23** [comment]
You are right-that's exactly what I wanted to do by following the R codes(I thought it is the same as prevalence of phyla, my bad). I wonder how the mean prevalence of each "feature" (read as OTU or ASV) that belongs to each phylum is calculated by the R codes, so that I can check if there is anything wrong with my samples. Isn't it looking weird that the mean prevalence of ASVs belonging to each phylum is either 1 or 2?

**Comment by Ecotone23** [comment]
I manually calculated the mean and sum of feature prevalence for several phyla and it is the same as the values calculated by  your R codes. The sum of feature prevalence for a phylum is the total counts of the presence of all features(reads>0 counted as presence once) that belong to the phylum, which is the values for column "2"; The mean of feature prevalence for a phylum is the sum divided by the feature abundance(number of different features), which is the values for Column "1". So the higher the mean is, the higher the number of samples share the same features? But is it also common to have most of your samples do not sharing the same features like our data, which is predominately Proteobacteria (Phylum) and Wolbachia (Genus) from Culex mosquitoes?  If it is usual, is it an issue caused by previous data processing? What I can do to enhance the data presentation for downstream diversity analyses.

**Comment by Ecotone23** [comment]
Hi Ben, thanks for the response. The dominant Proteobacteria ASVs belong to the Genus _Wolbachia_. You're right that insect microbiome may be often dominated by a few taxa. This is the case for our studied samples, _Culex_ mosquitoes, which are often reportedly dominated by _Wolbachia_ in terms of both prevalence and relative abundance. So _Culex_ mosquitoes may not be good samples to do bacterial OTU prevalence filtering and microbial diversity analysis because they are constantly donimanted by Proteobacteria-_Wolbachia_. Are there any analytical methods suitable for examining the microbial community composition in these samples?

**Comment by benjjneb** [comment]
The right way to analyze data for specific studies goes beyond the advice I'm comfortable providing, and really beyond the DADA2 method. Vaguely reiterating what I said above, thinking about contamination and what a "microbiome" really means in paucimicrobial systems is worth doing seriously.
