### ISSUE TITLE
issue with qiime dada2 denoise-ccs

### ISSUE THREAD

**Issue by daisykuma22** [benjjneb/dada2#1815]
Hi @benjjneb
I have 24 clean CCS read datasets and i want to get amplicon sequence variants by running dada2.
I got one issue  when running dada2 denoise-ccs with QIIME2.

1.  First, when i am running dada2 in qiime2 with all 24 samples:

The command I used was:
`qiime dada2 denoise-ccs --i-demultiplexed-seqs reads_qza/ccs_reads.qza --p-min-len 1200 --p-max-len 1800 --p-front AGRGTTYGATYMTGGCTCAG --p-adapter RGYTACCTTGTTACGACTT --p-n-threads 40 --o-table dada2_output/table.qza --o-representative-sequences dada2_output/representative_sequences.qza --o-denoising-stats dada2_output/stats.qza --verbose`

The debug for this error is here.
`Running external command line application(s). This may print messages to stdout and/or stderr.
The command(s) being run are below. These commands cannot be manually re-run as they will depend on temporary files that no longer exist.

Command: run_dada.R --input_directory /tmp/qiime2/zcw/data/bc625311-79dd-4d22-b6e8-aefa5e8e080b/data --output_path /tmp/tmpuxwxzmu_/output.tsv.biom --output_track /tmp/tmpuxwxzmu_/track.tsv --removed_primer_directory /tmp/tmpuxwxzmu_/nop --filtered_directory /tmp/tmpuxwxzmu_/filt --forward_primer AGRGTTYGATYMTGGCTCAG --reverse_primer RGYTACCTTGTTACGACTT --max_mismatch 2 --indels False --truncation_length 0 --trim_left 0 --max_expected_errors 2.0 --truncation_quality_score 2 --min_length 1200 --max_length 1800 --pooling_method independent --chimera_method consensus --min_parental_fold 3.5 --allow_one_off False --num_threads 40 --learn_min_reads 1000000 --homopolymer_gap_penalty NULL --band_size 32

R version 4.1.3 (2022-03-10) 
Loading required package: Rcpp
DADA2: 1.22.0 / Rcpp: 1.0.9 / RcppParallel: 5.1.5 
1) Removing Primers
Read in 12234, output 0 (0%) filtered sequences.
Read in 10596, output 0 (0%) filtered sequences.
Error in sapply(match.fwd, end) + 1 : 
  non-numeric argument to binary operator
Execution halted
Traceback (most recent call last):
  File "/home/kuma/miniconda3/envs/qiime2-2022.8/lib/python3.8/site-packages/q2_dada2/_denoise.py", line 410, in denoise_ccs
    run_commands([cmd])
  File "/home/kuma/miniconda3/envs/qiime2-2022.8/lib/python3.8/site-packages/q2_dada2/_denoise.py", line 36, in run_commands
    subprocess.run(cmd, check=True)
  File "/home/kuma/miniconda3/envs/qiime2-2022.8/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['run_dada.R', '--input_directory', '/tmp/qiime2/zcw/data/bc625311-79dd-4d22-b6e8-aefa5e8e080b/data', '--output_path', '/tmp/tmpuxwxzmu_/output.tsv.biom', '--output_track', '/tmp/tmpuxwxzmu_/track.tsv', '--removed_primer_directory', '/tmp/tmpuxwxzmu_/nop', '--filtered_directory', '/tmp/tmpuxwxzmu_/filt', '--forward_primer', 'AGRGTTYGATYMTGGCTCAG', '--reverse_primer', 'RGYTACCTTGTTACGACTT', '--max_mismatch', '2', '--indels', 'False', '--truncation_length', '0', '--trim_left', '0', '--max_expected_errors', '2.0', '--truncation_quality_score', '2', '--min_length', '1200', '--max_length', '1800', '--pooling_method', 'independent', '--chimera_method', 'consensus', '--min_parental_fold', '3.5', '--allow_one_off', 'False', '--num_threads', '40', '--learn_min_reads', '1000000', '--homopolymer_gap_penalty', 'NULL', '--band_size', '32']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kuma/miniconda3/envs/qiime2-2022.8/lib/python3.8/site-packages/q2cli/commands.py", line 339, in __call__
    results = action(**arguments)
  File "<decorator-gen-468>", line 2, in denoise_ccs
  File "/home/kuma/miniconda3/envs/qiime2-2022.8/lib/python3.8/site-packages/qiime2/sdk/action.py", line 234, in bound_callable
    outputs = self._callable_executor_(scope, callable_args,
  File "/home/kuma/miniconda3/envs/qiime2-2022.8/lib/python3.8/site-packages/qiime2/sdk/action.py", line 381, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/home/kuma/miniconda3/envs/qiime2-2022.8/lib/python3.8/site-packages/q2_dada2/_denoise.py", line 419, in denoise_ccs
    raise Exception("An error was encountered while running DADA2"
Exception: An error was encountered while running DADA2 in R (return code 1), please inspect stdout and stderr to learn more.

Plugin error from dada2:

  An error was encountered while running DADA2 in R (return code 1), please inspect stdout and stderr to learn more.

See above for debug info.`

Is it possible caused by the input of the clean reads, since no primers have to be removed?
Can you help me with this?

**Comment by benjjneb** [comment]
We don't support the Q2 plugin in this forum. You'll want to repost this on the QIIME2 forum: https://forum.qiime2.org/
