### ISSUE TITLE
Cutadapt removal of primer

### ISSUE THREAD

**Issue by luigallucci** [benjjneb/dada2#1816]
Hi!

I'm working on different samples which has been sequenced with a particular set of primer, so I'm running your protocols for ITS but with Bacterial 16s sequences.

We notice that differently from the "classical lecture" of the following command line:
```
rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.filtN[[1]]),
FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.filtN[[1]]),
REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.filtN[[1]]),
REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.filtN[[1]]))
```
our sequences give this type of output:

![Screenshot from 2023-09-18 15-13-32](https://github.com/benjjneb/dada2/assets/100836528/92ca10a2-08c8-4147-acbe-e575d581175b)

We know that there is a problem with forward reads and forward primers and we are working with sequencing center to solve it, so the question is:

I followed your suggestion to use REV <- REV.orient[["RevComp"]] for removal of reverse primer in reverse complement orientation but after it we still have primers in its normal orientation.

How we can remove all the primers from the reverse reads?  There is way to give to cutadapt the option to cut it both at the same time in both orientation?

**Comment by luisymbio** [comment]
Yes, we know that there are problems with library and we are managing it.  

I'm asking also to understand if I interpret the output correctly. The REV.ForwardReads and REV.ReverseReads line correspond to the 2 different orientations of the reverse reads, right? If this is correct, I have the Forward orientation of my reverse primer in both the orientation of the reverse reads? and the same for the rev.complement, if this is correct. 

This is obviously a problems with library, and I want to understand in which way I need to address this issue with the sequencing center, the main reason for which I'm asking all these details.

**Comment by luisymbio** [comment]
Ok, perfect, yeah this is more or less what I said. 

I just misunderstand the interpretation of the REV.ForwardReads but now is okay. 

Just to clarify all the things, we notice the problems because basically the FWD primer are completely missing and if we substitute out FWD primer with our used Archaea primer (for which we request different library) we find it. 

So probably the sequencing center, as our interpretation, has done a little bit of confusion in constructing the libraries.

**Comment by luisymbio** [comment]
I received

> I think your interpretation is correct, but I'll just restate it in my own words to make sure (and because there are so many "reverse"s in the terminology its confusing).
> 
> In the REV.ForwardReads line, there are 6016 instances in which the forward orientation of the REV (primer) was detected in the forward (R1) reads, and 1174 times in which the the reverse-complement orientation of the REV (primer) was detected in the forward (R1) reads.
> 
> A similar pattern is observed for the ReverseReads (R2).
> 
> So, both the forward and reverse-complement orientations of the REV primer (only) are being detected in both the forward (R1) and reverse (R2) reads. The FWD primer is essentially never being detected in any of the reads.

Hey @benjjneb 
I received new data from the sequencing center!

Now I have a output similar to the one of issue #1003. So with cu

So seems like 
![image](https://github.com/benjjneb/dada2/assets/100836528/edecaf29-5a54-49c8-9f1f-cd2a7b73901b)

How I could manage this? I read some other issues, but I'm not pretty sure how to do it. Someone suggest that this are mixed oriented reads, someothers to run cutadapt two times. In the issue #1003 you as suggested to use filterAndTrim after the first run with cutadapt, but I'm pretty confused about all these things.

**Comment by benjjneb** [comment]
Issue https://github.com/benjjneb/dada2/issues/938 describes a strategy for dealing with mixed orientation data. Put simply, use cutadapt to remove primers and filter down to those reads that have the FWD primer on R1 and REV primer on R2, then move forward with that data. That will lose the half the reads that are in the opposite orientation, but that's probably OK. If you want to rescue them, you can run use cutadapt to filter down to those reads that have REV primer on R1 and FWD primer on R2 and move those through the dada2 workflow separately, but its not clear the additional complexity will be worth it.

To clarify, "mixed orienation" means the library preparation method used produced reads that are roughly an equal mixture of 5'-3' reads and 3'-5' reads (i.e. the reverse complement orientation).
