### ISSUE TITLE
assignTaxonomy function returned results that are mostly NA

### ISSUE THREAD

**Issue by Canxis** [benjjneb/dada2#1817]
Hi everyone! 
  I am analyzing my COI sequences (Target taxa: invertebrates) , using the function `assignTaxonomy`. But results showed that all taxa were assigned as NA or Arthropoda_6656. It's strange so I have compared those seq to the BLAST database in NCBI, some seq actually can be assigned to species level. I wonder what is happening, and if there is something I can do to solve this issue.
  Here are the things I am using:
  1. environments: R 4.3.1 and dada2 1.28.0
  2. commands: `tax <- assignTaxonomy(ALIBT$V1, paste0(path,"/MIDORI2_UNIQ_NUC_GB257_CO1_DADA2.fasta.gz"), minBoot = 75,
                            taxLevels = c( "Phylum", "Class", "Order", "Family", "Genus", "Species"),
                            outputBootstraps = TRUE, multithread= TRUE, tryRC = TRUE)`
  3. files: see attached

Thanks!
[ALIBT (647 seq).txt](https://github.com/benjjneb/dada2/files/12669055/ALIBT.647.seq.txt)

**Comment by benjjneb** [comment]
I don't have experience with CO1 sequencing, and we don't officially support a C01 reference training set, so I can't provide much guidance. I see you already have `tryRC=TRUE`, so it looks like you are using `assignTaxonomy` properly and so my guess is the issue is related to the reference database. It's possible looking for help from Midori might be more useful.

**Comment by Canxis** [comment]
> I don't have experience with CO1 sequencing, and we don't officially support a C01 reference training set, so I can't provide much guidance. I see you already have `tryRC=TRUE`, so it looks like you are using `assignTaxonomy` properly and so my guess is the issue is related to the reference database. It's possible looking for help from Midori might be more useful.

Thanks for your quick reply! I will contact MIDORI to see if there is something wrong with my reference database.
