### ISSUE TITLE
Single fasta file containing all samples and requences into a usable format for dada2 analysis

### ISSUE THREAD

**Issue by anamariamunizrodriguez** [benjjneb/dada2#1819]
!! Hello, 

I have a single file containing all the samples and the the sequence number (sequential within sample) for each sample. Is there a way to get this file into a format that is usable for dada2 analysis?
[file_samoa_help.pdf](https://github.com/benjjneb/dada2/files/12701789/file_samoa_help.pdf)
 (the file is originally a fasta file but I converted to pdf to be able to upload here)
Thank you for the help!!!!!

**Comment by benjjneb** [comment]
I don't recommend using DADA2 with fasta files, as it uses quality score information in the model. So there isn't a clear way to turn this file into something that would work with DADA2.

Demultiplexing it into per-sample files would still only be fastas.

**Comment by anamariamunizrodriguez** [comment]
Makes sense , thanks so much for the response!!
