### ISSUE TITLE
Inflated taxa counts with DADA2?

### ISSUE THREAD

**Issue by nmshahir** [benjjneb/dada2#182]
I think I'm having a slight problem with the assign taxa function. When I port the dada2 object into phyloseq, I get an object that claims to have 25350 taxa across all the samples, while with the same data processed through QIIME 1.9.0, I get 998 taxa. I used Greengenes for both.

Is this primarily because I had fairly lax filtering for DADA2, (truncQ = 2) or is it something else? These are MiSeq reads.

Thank you in advance.
-N

**Comment by benjjneb** [comment]
That seems high, but hard to know what it means without more details on the size of your study, and what the QIIME protocol you used was.

Did your dada2 workflow include chimera removal?

**Comment by nmshahir** [comment]
I have a little over 500 samples, for QIIME I did closed reference OTU picking, and yes, I included  chimera removal in the workflow.

**Comment by benjjneb** [comment]
It's not surprising that a de novo method will find more variants than a closed-ref method.

It sounds like you want to reduce the number of inferred sequence variants, so I would recommend filtering your sequence table based on prevalence and overall study frequency.

For example, are variants that appear in only 1 or 2 sample important to your analysis? If not, remove all variants that appears in <3 samples. Similarly, removing variants that appear in less than (eg.) 1e-5 total study-wide frequency can be useful.

**Comment by benjjneb** [comment]
Also, I think from your previous posts that you are merging multiple sequence runs together. So you might want to double-check they are merging properly: Are the most common SVs appearing across sequencing runs?

**Comment by nmshahir** [comment]
How/What is the best way to go about that?

**Comment by benjjneb** [comment]
The sequence table is just a matrix in R, so you can manipulate it like a matrix. For example, to remove SVs that appear in fewer than 3 samples:

```
nsam <- colSums(seqtab>0)
st <- seqtab[,nsam>=3]
```

**Comment by benjjneb** [comment]
Assuming fixed, but reopen if needed.
