### ISSUE TITLE
Issue with primer removal step

### ISSUE THREAD

**Issue by anamariamunizrodriguez** [benjjneb/dada2#1820]
Hello!

I am currently working through the pipeline and am having issues at the primer removal step 
<img width="819" alt="Screen Shot 2023-09-26 at 4 04 55 PM" src="https://github.com/benjjneb/dada2/assets/140383865/17cd65eb-0de5-44d0-a4a5-22111a243ec1">

I have c
<img width="950" alt="Screen Shot 2023-09-26 at 4 06 29 PM" src="https://github.com/benjjneb/dada2/assets/140383865/d71d7134-1851-4632-81f8-860e4830931d">
hecked my code and cannot seem to find out where I am inputting something wrong and continuously get the following error

Thank you for the help!

**Comment by benjjneb** [comment]
You should strip out all non-standard characters from your filenames, as they lead to exactly these sorts of parsing errors. That is, no asterisks *, no parentheses (), no spaces, nothing other than alphanumerics and underscores, in directory names or filenames.

**Comment by anamariamunizrodriguez** [comment]
Thank you!
