### ISSUE TITLE
Availability of Greengenes2 database in DADA2 pipeline

### ISSUE THREAD

**Issue by magibc** [benjjneb/dada2#1821]
Dear DADA2 developers.

I am user of your pipeline, and I would like to know if in the next DADA2 version will be available to assign taxonomy and species through the most recent update of Greengenes 2 (https://www.nature.com/articles/s41587-023-01845-1). The authors created a plugin for Qiime2, but now the DADA2 users we want also in DADA2 ;D

In the webpage: 
https://benjjneb.github.io/dada2/training.html
appears the last version of greengenes (13.8).

Thanks on advance for your response,

David.

**Comment by benjjneb** [comment]
See https://github.com/benjjneb/dada2/issues/1680

There are a couple scripts there for creating a DADA2-compatible training fasta for GreenGenes2.
I will get out an official release soon-ish, but that should work for now.

**Comment by magibc** [comment]
Sorry. I did not see.

Thanks
