### ISSUE TITLE
FilterAndTrim for ITS sequences 

### ISSUE THREAD

**Issue by hwangumn** [benjjneb/dada2#1823]
Hi, 
Completely newbie here so please forgive me if I am asking some stupid questions. I am using DADA2 to process some fungal ITS sequences and am following the [ITS tutorial ](https://benjjneb.github.io/dada2/ITS_workflow.html). I understand that I shouldn't use `truncLen` for fungal ITS sequences but my quality score crashed around (250,200) nt. Then if I use the standard paraments for `FilterAndTrim`
```
out <- filterAndTrim(cutFs, filtFs, cutRs, filtRs, maxN = 0, maxEE = c(2, 2), truncQ = 2,
    minLen = 50, rm.phix = TRUE, compress = TRUE, multithread = TRUE)  # on windows, set multithread = FALSE
head(out)
```
most of the sequences were removed (see below). Any suggestions? Should I change the `maxEE` value? What value should I use if I want to keep everything that is above "25%"? 

```
                                reads.in reads.out
WB2P20515_ITS_S882_R1_001.fastq    10660      3289
WB2P20530_ITS_S886_R1_001.fastq    31840      7549
WB2P21114_ITS_S894_R1_001.fastq    24180       738
WB2P21128_ITS_S896_R1_001.fastq    20376      9534
WB2P30515_ITS_S902_R1_001.fastq    17903      9019
WB2P30530_ITS_S906_R1_001.fastq    27019     10986
```

Thanks for your help!!

<img width="865" alt="c4070364-ff72-48a9-8dc6-0f94177d27ec" src="https://github.com/benjjneb/dada2/assets/146417504/4390b675-9789-4f89-aaab-183176164c23">

<img width="865" alt="2b821519-f5ec-43d0-810a-d375e5eeed96" src="https://github.com/benjjneb/dada2/assets/146417504/02d51cf5-3cc6-42e5-b4a6-0bcffbe733ab">

**Comment by benjjneb** [comment]
One thing I would strongly consider is using just the forward reads alone. Merging paired-end reads when length is so variable (as with the ITS region) is its own challenge, and here you clearly also have worse sequencing quality in R2.

There was a paper a few years ago that also suggested they got the best results by using just forward reads for ITS data: https://doi.org/10.1016/j.funeco.2019.03.005

**Comment by hwangumn** [comment]
Thank you so much for getting back to me! I will look into using the forward reads only. 
I also got some warning messages generated when creating these graphs. Should I do anything about them?


Warning messages:
1: In serialize(data, node$con) :
  'package:stats' may not be available when loading
2: In serialize(data, node$con) :
  'package:stats' may not be available when loading
3: The `<scale>` argument of `guides()` cannot be `FALSE`. Use "none" instead as of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the dada2 package.
  Please report the issue at <https://github.com/benjjneb/dada2/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

**Comment by benjjneb** [comment]
You can ignore those warnings.
