### ISSUE TITLE
Denoise step still running after 10 days

### ISSUE THREAD

**Issue by magibc** [benjjneb/dada2#1825]
Hi,

In the past I have analized MiSeq 16S sequenced samples with your general protocol without any problem (https://benjjneb.github.io/dada2/tutorial.html ).

Nevertheless, now I am trying to perform DADA2 with 1000 MiSeq paired end samples... and in the "denoising" discrete step of DADA2 workflow:

dadaFs_pool <- dada(derepFs, err=errF, multithread=T, pool=T, selfConsist = F)
dadaRs_pool <- dada(derepRs, err=errR, multithread=T, pool=T, selfConsist = F)

Using 38 threads and 150 Gb of RAM in a HPC, after ten days is still running... and the denoise process is only using 1 CPU during the majority of the process (which I have read that is usual in an ancient issue).

The last message obtained after the first day of 10 is: 
1000 samples were pooled: 51723077 reads in 12822361 unique sequences.

Then reading the info and your workflow of BigData, I understand that I need move forward to bigdata protocol and abandon the workflow that I follow until now in order to advance the analysis...

Because I have tried using library(doMC)...but I am not be able to success.

Thanks on advance for your advice/hints.

David.

**Comment by benjjneb** [comment]
> and the denoise process is only using 1 CPU

This seems unusual to me, as the core denoising part is multithreaded effectively. Unless by 1 CPU you mean 1 multi-core/multi-thread CPU, such that it is being parallelized across those cores/threads.

That said, `pool=TRUE` becomes less computationally tractable as the number of samples increases. Computational requirements in memory and time scale super-linearly (near quadratic).

An alternative is to use the `pool="pseudo"` mode, which maintains linear scaling of compute time with the number of samples, and nearly flat memory requirements. See here for more info on that: https://benjjneb.github.io/dada2/pseudo.html#pseudo-pooling

**Comment by magibc** [comment]
Hello @benjjneb 

First of all, apologize for the delay.

The denoising process of 1000 samples spended 25 days using HPC with 38 cores and 150 GB minimum of RAM.

Thanks for your recommendation of using pseudo-pooling. Nonetheless, the bigdata tutorial in the part:

```
set.seed(100)
err <- learnErrors(filts, nbases = 1e8, multithread=TRUE, randomize=TRUE)
# Infer sequence variants
dds <- vector("list", length(sample.names))
names(dds) <- sample.names
for(sam in sample.names) {
  cat("Processing:", sam, "\n")
  derep <- derepFastq(filts[[sam]])
  dds[[sam]] <- dada(derep, err=err, multithread=TRUE)
```
} it seems that through FOR,  you process each file one by one... you recommends me to try to use the BigData tutorial for my data of 1000 samples and using the argument pool=T in dada() if it works more fast...

Thanks again for your help,

David.

**Comment by benjjneb** [comment]
The need for the BigData workflow has largely been supplanted by updates to the `dada` function to work directly with files (rather than derep-class objects) that allow it to stream samples, i.e. load them one-by-one rather than all at once. Pooling or psuedo-pooling won't work with the bigData workflow.
