### ISSUE TITLE
Converting DADA2 results to a standard OTU table

### ISSUE THREAD

**Issue by hwangumn** [benjjneb/dada2#1826]
Hi, 
I am wondering if anyone has any suggestions for converting DADA2 results to a standard OTU table? I am using FUNGuild to predict the Fungal function and the input has to be a standard OTU table with the following format:
OTU_ID(tab)sample1(tab)sample2(tab)sample3(tab)taxonomy(return) OTU_10(tab)10002(tab)10004(tab)0(tab)Fungi;Basidiomycota;Agaricales;Cortinariaceae;Cortinarius(return) OTU_20(tab)10003(tab)0(tab)10001(tab)Fungi;Ascomycota;Chaetothyriales;Herpotrichiellaceae;Cladophialophora 

Thanks in advance.

**Comment by magibc** [comment]
Hi,

The file that you finnally obtain: seqtab.nochim_pooling.rds (results saved from remove chimera step) jointly with the file that obtain after adding taxonomy and species you have the tools to have the structure of OTU table... you have only to reorganize a bit...see Bonus: Handoff to phyloseq in the dada2 tutorial....

I hope that could help ,

David.
