### ISSUE TITLE
Addspecies() doesn't add any species

### ISSUE THREAD

**Issue by WJH58** [benjjneb/dada2#1827]
Cheers! 

I have tried dada2 on several public 16s datasets but the same problem occurred to me: AssignTaxonomy() works fine and few NAs were generated, however, the following AddSpecies() add no species at all. The 'Species' column returns **ALL** NAs!! Not 'almost NA', but **ALL** NAs!!

Below is part of my code:
```
vaginal_taxa <- assignTaxonomy(seqtab.prevalence.filtered, "silva_nr99_v138_train_set.fa.gz", tryRC = TRUE)
nrow(vaginal_taxa) # 495 rows
vaginal_taxa[,'Genus'] %>% is.na() %>% sum() #only 2 ASVs were not given a genus
vaginal_taxa_species <- addSpecies(vaginal_taxa, "silva_species_assignment_v138.fa.gz")
```
Then no species were assigned.

I tried to blast some sequences and they are all bacteria. So my data is indeed 16s gene, instead of ITS. For example:
```
>1
ACTTGACCTATGGGGTGCAGCAGTGAGGAATATTGGTCAATGGACGCAAGTCTGAACCAGCCAAGTAGCGTGCAGGATGACGGCCCTATGGGTTGTAAACTGCTTTTATATGGGGATAAAGTGGGGAACGTGTTCCCTTTTGCAGGTACCATATGAATAAGGACCGGCTAATTCCGTGCCAGCAGCCGCGGTAATACGGAAGGTTCGGGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCCGTTTGGTAAGCGTGTTGTGAAATGTAGTAGCTCAACTTCTAGATTGCAGCGCGAACTGTCAGACTTGAGTGCGCACAACGTAGGCGGAATTCATGGTGTAGCGGTGAAATGCTTAGATATCATGAAGAACTCCGATTGCGAAGGCAGCTTACGGGAGCGCAACTGACGCTGAAGCTCGAAGGTGCGGGTATCGAACAGGATTAGATACCCGTGTAGTCCGCTACC
```
This is 97% identical with Prevotella bivia.

I also tried assignSpecies():
```
assignSpecies("ACTTGACCTATGGGGTGCAGCAGTGAGGAATATTGGTCAATGGACGCAAGTCTGAACCAGCCAAGTAGCGTGCAGGATGACGGCCCTATGGGTTGTAAACTGCTTTTATATGGGGATAAAGTGGGGAACGTGTTCCCTTTTGCAGGTACCATATGAATAAGGACCGGCTAATTCCGTGCCAGCAGCCGCGGTAATACGGAAGGTTCGGGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGGCCGTTTGGTAAGCGTGTTGTGAAATGTAGTAGCTCAACTTCTAGATTGCAGCGCGAACTGTCAGACTTGAGTGCGCACAACGTAGGCGGAATTCATGGTGTAGCGGTGAAATGCTTAGATATCATGAAGAACTCCGATTGCGAAGGCAGCTTACGGGAGCGCAACTGACGCTGAAGCTCGAAGGTGCGGGTATCGAACAGGATTAGATACCCGTGTAGTCCGCTACC", refFasta = "silva_species_assignment_v138.fa.gz")
```
And it returned two NAs. Even genus is NA. 

Could you please suggest any solutions?

**Comment by benjjneb** [comment]
If you also include `tryRC=TRUE` in the `assignSpecies` call do the results change?

**Comment by WJH58** [comment]
Sorry for bothering. This time I trimmed the primers before running dada2 and it worked. It seems that primers do interrupt species annotation.
