### ISSUE TITLE
Greengenes2 database not through qiime2

### ISSUE THREAD

**Issue by lcamVz** [benjjneb/dada2#1829]
I wanted to ask if there is a plan of converting the new gg2 database to dada2 R taxonomy format?

**Comment by benjjneb** [comment]
Yes. You can use code here to do it: https://github.com/benjjneb/dada2/issues/1680

 I will cut an official dada2 format in the next month-ish to host on Zenodo like our other officially suported references.

**Comment by benjjneb** [comment]
Closed as redundant with https://github.com/benjjneb/dada2/issues/1680
