### ISSUE TITLE
Learn Error Rates Using a List of Derep Objects

### ISSUE THREAD

**Issue by gblanchard4** [benjjneb/dada2#183]
Here is a modified version of learnErrors that I was working on. It takes a list of derep objects that can be formed using `lapply(filtFs, derepFastq)`. By dereplicating beforehand you gain some efficiency since you don't need to dereplicate the same samples in both the `learnErrors` and running before running `dada` on all samples. 

```
estimateErrorRates <- function(dereps, nreads=1e6, randomize=FALSE, multithread=FALSE, verbose=TRUE){    
  NREADS <- 0
  drps <- vector("list", length(dereps))
  if(randomize){ drps <- sample(drps) }
  for (i in seq_along(drps)){
    NREADS <- NREADS + sum(drps[[i]]$uniques)
    if (NREADS > nreads) { break }
  }
  if (NREADS < nreads) { cat("Total reads less than nreads\n")}
  if (verbose) { cat("Total reads used: ", NREADS, "\n") }
  drps <- dereps[1:i]
  # Run dada in self-consist mode on those samples
  dds <- dada(drps, err=NULL, selfConsist=TRUE, multithread=multithread)
  return(getErrors(dds, detailed=TRUE))
}
```

Do you think this should be a separate function or should `learnErrors` have logic to handle both input types? It would be easy enough to skip the `derepFastq` step with a simple class check.

EDIT: Here it is with a class check
```
learnErrors <- function(fls, nreads=1e6, errorEstimationFunction = loessErrfun, multithread=FALSE, randomize=FALSE) {
  NREADS <- 0
  drps <- vector("list", length(fls))
  if(randomize) { fls <- sample(fls) }
  for(i in seq_along(fls)) {
    if (class(fls[[1]]) == "derep"){
        drps[[i]] <- fls[[i]]
    } else {
        drps[[i]] <- derepFastq(fls[[i]])
    }
    NREADS <- NREADS + sum(drps[[i]]$uniques)
    if(NREADS > nreads) { break }
  }
  drps <- drps[1:i]
  # Run dada in self-consist mode on those samples
  dds <- dada(drps, err=NULL, selfConsist=TRUE, multithread=multithread)
  cat("Total reads used: ", NREADS, "\n")
  return(getErrors(dds, detailed=TRUE))
}
```

**Comment by benjjneb** [comment]
Definitely rolled into `learnErrors` with a class check. Note the internal function `is.list.of(...)` which is the supported way to check if an object is a list of, eg, derep-class objects.

**Comment by gblanchard4** [comment]
Well, that's quite a handy function! I'll start working on a PR

**Comment by benjjneb** [comment]
Added in 22ebd6fe8ce266e4a50cdfda0dc74ca94fc9059e

**Comment by ktmbiome** [comment]
I think this is a great modification! I am curious to know, however, if learnErrors uses the frequency of the sequence to determine the probability of an error. Therefore, if learnErrors receives a list of dereplicated sequences, does it consider the error distribution to be different than if it had received all of the sequences? I am working on testing this question on my own, but I was wondering if it had already been explored/discussed.

Thanks!

**Comment by benjjneb** [comment]
> I am curious to know, however, if learnErrors uses the frequency of the sequence to determine the probability of an error.

Yes it does.

> Therefore, if learnErrors receives a list of dereplicated sequences, does it consider the error distribution to be different than if it had received all of the sequences? 

Yes. A list of `derep-class` objects is interpreted as being from independent samples that are then evaluated independently before error rates from each are averaged. If all the samples are pooled into one `derep-class` object its treated as one big sample.

**Comment by ktmbiome** [comment]
Thank you so much! I realize now that I wasn't exactly clear, in that I intended to ask if providing the list of `derep-class` objects would be different from providing the filtered/trimmed sequences (with dups). Do you read in more unique base changes by providing the `derep-class` object, therefore changing the error distribution? I would assume so, but wanted to check.

Thank you again!

**Comment by benjjneb** [comment]
> Thank you so much! I realize now that I wasn't exactly clear, in that I intended to ask if providing the list of derep-class objects would be different from providing the filtered/trimmed sequences (with dups). Do you read in more unique base changes by providing the derep-class object, therefore changing the error distribution?

Functionally providing the file names or the `derep-class` objects read in from those files will produce identical output. When filenames are provided the first step is to read them in with `derepFastq`. The benefit of being able to provide `derep-class` objects is just computation time, as it allows you to read each file in just once.
