### ISSUE TITLE
How to merge fastq files from NCBI to my data

### ISSUE THREAD

**Issue by AkilaMuthalagu** [benjjneb/dada2#1833]
Hello all,

I have ten samples for which humans are the only source. I have used DADA2 for the analysis. Now, I am trying to download the existing data sets (the Illumina protocol is the same as my sample), such as skin bacteria, oral bacteria etc., from NCBI to run the source tracker program . I noticed I downloaded the paired reads, and that's the only available fastq file. Now I am confused about how to combine these fastq files together. I am thinking of saving my OTU sequences after the merging step. Then save them along with the downloaded sequences and go ahead assigning the taxa using the regular code.

I read issue #446 , and thinking of following the same.

 If anyone has any other ideas, please let me know. Any export advice would be highly helpful as I have been stuck with this for a long.

**Comment by benjjneb** [comment]
I think you might run into a variety of challenges trying to merge ASV-level data from your samples and various other datasets from NCBI. SourceTracker can be run at any taxonomic level, I might consider using a coarser approach like genus-level assignment or an OTU clustering method that won't be as affected by variations in length and processing, and using SourceTracker on that table.

**Comment by AkilaMuthalagu** [comment]
I was thinking of getting absolute abundance data (available for one project) and combining it with mine. Meaning taking common genus/ or species data from both the tables and running a source tracker for the combined table. The problem here is species-wise data is very limited. If I take a common genus, for example Staphylococcus from both the table, it can be any species of staph and I will end up misinterpreting the data. That's why I wanted to extract fastq files from my data after merging and combine it with the already paired data (downloaded from NCBI), and proceed with assigning taxa for this fastq files. If I am able to do this, then ASV names will be given based on similar sequences, and I can get a count also. This is what I wanted to do but looks very complicated and gets a lot of errors in the first step itself, which is reading the fastq files.

**Comment by benjjneb** [comment]
I understand your purpose, and the idea is fine. But there are likely to be substantial technical challenges in getting these datasets to line up precisely enough to use ASV-level resolution on them, which go beyond what I can provide support for. The best I can do is point you to one example of doing this in our recently published meta-analysis paper: https://doi.org/10.1186/s12915-023-01702-2

See the Bioinformatics section, although a lot of details are only in the reproducible analysis scripts in the Github repo associated with the manuscript.

**Comment by AkilaMuthalagu** [comment]
Thanks, Ben, for your response. THe paper is really interesting.
