### ISSUE TITLE
Error in reading fastq file

### ISSUE THREAD

**Issue by apcristi** [benjjneb/dada2#1834]
I'm having issues with a pipeline I have run before when running when trying to run:

> for(i in 1:length(fns_R1)) {
     geom <- fastq.geometry(fns_R1[i])
     df_one_row <- data.frame (n_seq=geom[1], file_name=basename(fns[i]))
     df <- bind_rows(df, df_one_row)
     print(paste("Finished with file", fns[i], ". ", round(i/length(fns)*100, 2), "%", sep=""))
     if(i == length(fns)) {print(paste("Finished"))}

Error in .Call2("fastq_seqlengths", filexp_list, nrec, skip, seek.first.rec,  : reading FASTQ file ./fastq/TAN2101-CTD01-DNA-3_CGAAGG-KGFBK_L001_R1.fastq.gz: "+" expected at beginning of line 26171.

I have reinstalled Biostrings and R Studio and it keeps happening. I tried the script with old fastq files that have been analysed before and got the same error, so I don't think the problem is with the files.

**Comment by benjjneb** [comment]
This doesn't look like it involves the DADA2 package, and I am unfamiliar with the commands you are using. You should look for support from the relevant packages, perhaps Bioconductor if you are using Biostrings or ShortRead packages.
