### ISSUE TITLE
16S rRNA pipeline using DADA2 / 10. Alignment

### ISSUE THREAD

**Issue by MostafaShaban989** [benjjneb/dada2#1835]
Hello, I am trying to run the next command and I get an error.
>  alignment <- AlignSeqs(DNAStringSet(seqs), anchor=NA)

Error:
Error in AlignSeqs(DNAStringSet(seqs), anchor = NA) : 
could not find function "AlignSeqs"

dim(seqtab.nochim)
[1]   119 47006

**Comment by benjjneb** [comment]
`AlignSeqs` is not a dada2 command. Google says it is from the DECIPHER package. You need to load that package to be able to run the function.

**Comment by MostafaShaban989** [comment]
@benjjneb tha

> `AlignSeqs` is not a dada2 command. Google says it is from the DECIPHER package. You need to load that package to be able to run the function.

Thank you very much
