### ISSUE TITLE
16S rRNA pipeline using DADA2 /Construct Phylogenetic Tree

### ISSUE THREAD

**Issue by MostafaShaban989** [benjjneb/dada2#1836]
Hallo, I am trying to run the next command and get an error. 
> treeNJ <- NJ(dm) # Note, tip order != sequence order
Error in nj(x) : cannot allocate memory block of size 134217728 Tb

 when I am trying to run dm <- dist.ml(phang.align) 
It gives in Environment 
dm: length = 1104758515 , size = 16.5GB , value = large dist ( 1104758515 element , 17.7 GB )

but  after that when I run the command  
> dm
Error: cannot allocate vector of size 8.2 Gb

**Comment by benjjneb** [comment]
Please see the issues forum for the F1000 workflow, as this is not a DADA2 package question: https://github.com/spholmes/F1000_workflow/issues

There are several previous issues raised on this topic. IN short, given the size of your data you will probably need to use an alternative/external tree-building approach, but there is more information available there.
