### ISSUE TITLE
exporting sequences after the removal of the chimeras 

### ISSUE THREAD

**Issue by sluitgaarden** [benjjneb/dada2#1837]
Hi,
I am using the dada2 pipeline to fix the sequences from my eDNA diet study. I am trying to extract the sequences from the last step before the taxonomic assignment out of R and still be able to tell which sequence came from which fastq file. Please let me know if you can help me. 
Thank you!

**Comment by benjjneb** [comment]
The sequence table is a sample by ASV matrix in R. So rows are samples (fastq files) and columns are ASVs (sequences).

`seqtab[i,]` selects the ASV counts for sample `i`.

**Comment by sluitgaarden** [comment]
Hi again,

My question has changed slightly. Is there a way to extract a fasta file of the seqtab.nochim results in dada2 in Rstudio. 

Thank you,
Sydney

**Comment by benjjneb** [comment]
The `uniquesToFasta` function will create a fasta file from your sequence table, but to what end? And in what format will that file be?

**Comment by sluitgaarden** [comment]
Essentially I'm trying to get all the sequences from the seqtab.nochim output out of the dada2 pipeline in R so I can run them through a command line blast for taxonomic identification.

**Comment by benjjneb** [comment]
OK. Does `uniquesToFasta` work?
