### ISSUE TITLE
Missing sequence for record beginning on line 69721

### ISSUE THREAD

**Issue by adevries75** [benjjneb/dada2#1838]
I have been following the script for ITS workflow in R, and it worked quite well when I tested it on a subset of four sequences last week. However now that I've scaled up to all of the sequences in my project (106 total), it worked for everything --except for a single read in a single sample, and that was enough to cause errors in the DADA2 step.  Looking at the raw sequences in the fastaq file, it looks like CutAdapt only partially removed this sequence from both forward and reverse reads, and DADA2 didn't simply discard it despite being shorter than minLen = 50.   I've  been able to get around this issue by using Qiime instead of R, but do you have any idea what the original problem was?

Below I've attached a portion of the fastaq sequences before and after trimming (forward read only), using primers GTGAATCATCGARTCTTTG forward, TCCTCCGCTTATTGATATGC reverse.  Line 69721 corresponds to sequence @M04437:1021:000000000-KW8H6:1:2117:17908:7722 1:N:0:ACTCGATC+ATATGCGC.

**Here is what it looked like  before:**
@M04437:1021:000000000-KW8H6:1:2117:24955:7717 1:N:0:ACTCGATC+ATATGCGT
CGTGAATCATCGAATCTTTGAACGCAAATTGCGCTCGAGGCTTCGGCCAAGAGCATGTCTGCCTCAGCGACGGGTTAATACTCGCTCCTAATCTCTCTGGGGATTGGGCCCGGAACTGGCTTTCCCGGCTTGGTTCATTCTAAGCCGGGTCTGCTGAAGTACAGAGGTTGATGCATGGACCCGCTAAAGGGCCTCTACTGGGTAGGCAATTCATTGCTAATGCTTTAGTAGATGGCTTGGGTAGATGCCTG
+
CCCCCGGGGGGFFGGGGGGGAFGGGGGDGGGGGG@BFGG+@EFGEFEEGGGG@FGGGGGGGFGGGGGGG+8FE:FGGGFFDFGG78C+CFGGGGGGGGGGGC+=EFGG,+8@EGGG8AFGGGGGGGGGGGFGGGGFCFFGGGFFGGGGECGGGGGGGGGGGGGGFGGCGGGGGGGGGGGGF@EEFFEFGGGGGGGGGGGGGDGGDFGGGGFFGGGGGGGGGGGGGGGFEGGGGGGFGGGGGGGGGGGGGG0
@M04437:1021:000000000-KW8H6:1:2117:17908:7722 1:N:0:ACTCGATC+ATATGCGC
AGTGAATCATCGAGTCTTTGCATATCAATAAGCGGAGGATAGATCGGAAGAGCACACGTCTGAACTCCAGTCACACTCGATCATCTCGTATGCCGTCTTCTGCTTGAAAAAACAAAAAAACACAACACCACCACCTCATGCCACACATATACGCGCCCTATCGCACTATGGACTCAACCATAAACGCTCACAGCAATGTCATCCTTGATAATTCTCGGTGCCACTGCCGCGCACGTCACTGTGACGACGAC
+
CCCCCGGGGGGGGGGGGGGGGGGFGGGGGGFGGGG:FFGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFFGGGG,:9:,C+>:,,,BF,4++++,:4,:,,:,,,5,++:,,,,,++++++:3,+++@+8,,,3,,8>,,,*,7,@,****42,,,4,,,,,,,5,,4,,,,,6,6,=/*/440,3+5+5**3**9**/**+20**212/)))
@M04437:1021:000000000-KW8H6:1:2117:14675:7741 1:N:0:ACTCGATC+ATATGCGC
AACGCACATTGCGCCCCTCGGTATTCCGTGGGGCATGCCTGTTCGAGCGTCATTTAACCCCTCAAGCTCTGCTTGGTGTTGGGCGTCTGTCCCGCCTCGTGCGCGGACTCGCCTAGAAGACATTGGCAGCGGTCGCGCCAGCTTCTCGCGCAGCACATTGCGCTTCTCGAGGCTCCGGCGGATCAGCGTCCAGCAAGTCCACCCCCAGTTTGACCTCGGATCAGGTAGGGA
+
EGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGFFGGGCFGGGGGGGGEGCGGEEFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG>EFCGFGGGGGGGCDGGGG>EGGG*

 
**And here is what it looked like after trimming.**
@M04437:1021:000000000-KW8H6:1:2117:24955:7717 1:N:0:ACTCGATC+ATATGCGT
AACGCAAATTGCGCTCGAGGCTTCGGCCAAGAGCATGTCTGCCTCAGCGACGGGTTAATACTCGCTCCTAATCTCTCTGGGGATTGGGCCCGGAACTGGCTTTCCCGGCTTGGTTCATTCTAAGCCGGGTCTGCTGAAGTACAGAGGTTGATGCATGGACCCGCTAAAGGGCCTCTACTGGGTAGGCAATTCATTGCTAATGCTTTAGTAGATGGCTTGGGTAGATGCCTG
+
AFGGGGGDGGGGGG@BFGG+@EFGEFEEGGGG@FGGGGGGGFGGGGGGG+8FE:FGGGFFDFGG78C+CFGGGGGGGGGGGC+=EFGG,+8@EGGG8AFGGGGGGGGGGGFGGGGFCFFGGGFFGGGGECGGGGGGGGGGGGGGFGGCGGGGGGGGGGGGF@EEFFEFGGGGGGGGGGGGGDGGDFGGGGFFGGGGGGGGGGGGGGGFEGGGGGGFGGGGGGGGGGGGGG0
@M04437:1021:000000000-KW8H6:1:2117:17908:7722 1:N:0:ACTCGATC+ATATGCGC

+

@M04437:1021:000000000-KW8H6:1:2117:14675:7741 1:N:0:ACTCGATC+ATATGCGC
AACGCACATTGCGCCCCTCGGTATTCCGTGGGGCATGCCTGTTCGAGCGTCATTTAACCCCTCAAGCTCTGCTTGGTGTTGGGCGTCTGTCCCGCCTCGTGCGCGGACTCGCCTAGAAGACATTGGCAGCGGTCGCGCCAGCTTCTCGCGCAGCACATTGCGCTTCTCGAGGCTCCGGCGGATCAGCGTCCAGCAAGTCCACCCCCAGTTTGACCTCGGATCAGGTAGGGA
+
EGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGFFGGGCFGGGGGGGGEGCGGEEFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG>EFCGFGGGGGGGCDGGGG>EGGG*

**Comment by benjjneb** [comment]
I haven't seen that before. This seems like an undesirable output from cutadapt (and possibly incorrectly formatted as a fastq file), but perhaps is something that could be handled more gracefully on the dada2 side.

What step threw an error due to this empty sequence entry? And what was the error message?

**Comment by adevries75** [comment]
The error occurred a minute or so after I activated DADA2.

There was a problem importing /home/aaron/TrapCultures/2022/NGS/ITS/cutadaptITS1/cutadaptITS1ITS2/:


/home/aaron/TrapCultures/2022/NGS/ITS/cutadaptITS1/cutadaptITS1ITS2/20024D-05Q3-177_S0_L001_R1_001.fastq.gz is not a(n) FastqGzFormat file:


Missing sequence for record beginning on line 69721

________________________________

**Comment by adevries75** [comment]
Sorry, it looks like the second half of my reply was cut off.

Upstream of this, I used Cutadapt iteratively to remove two sets of primers (for amplicons ITS1 and ITS2), because the Rstudio script didn't let me trim all four at once.  Basically I copied and pasted the whole procedure, then joined two of them head-to-tail. Admittedly this approach was a bit redundant, as it ended up removing the "N's" twice.

After a little forensic work, I found that the raw read had a peculiar stretch of "NNNNNN" in the middle of the forward reads, but not in the reverse read. This pattern also occurred in several hundred other sequences in the same fastaq file, and is not unique to line 69721, so I'm assuming this is the result of primer mis-pairing.  The first pair of primers for ITS1 were trimmed successfully, and the missing read disappeared while trimming the ITS2 primers.


________________________________

**Comment by benjjneb** [comment]
I see, unfortunately this is not something we can fix within the package then. The fastq format that is being created here is not valid (as per error message) and we rely on an external package (ShortRead) to import fastq files, so its not something we can fix on our end.
