### ISSUE TITLE
Output of Full Sequences from Assign Taxonomy

### ISSUE THREAD

**Issue by rmassoni16** [benjjneb/dada2#1840]
Hello, is it possible to generate an output of the full sequences mapped to when using the assignTaxonomy() function? I am looking to generate predictions of the taxonomy from 16S rRNA data and then use the full genome sequences to generate predictions of relevant coding genes and important pathways. I need the full genome sequence to use Prodigal to determine coding gene sequences and then use Prokka to annotate them, so I was wondering if there is a way to generate them during the DADA2 pipeline?

**Comment by benjjneb** [comment]
There is not. I would recommend using a different tool to get best hits in a reference database to move forward in this fashion. Note that there has been a suite of tools developed for functional prediction from 16S data (e.g. Picrust2) and that the literature on their utility and limitations is worth considering.
