### ISSUE TITLE
Using dada2 to process single sample fasta files

### ISSUE THREAD

**Issue by rowe285** [benjjneb/dada2#1842]
Hello, I recognize from the outset it is not ideal to have fasta files as a starting point given the loss of quality score information. However, is it still possible to work the files through dada2? I have a total of 29 samples, each as its own fasta file, and have started by using dada2:::derepFasta on each individually, such that each is now a derep class object. Is it then possible to filter and trim (using fastqFilter?). If so, should this be done to each derep class object individually, or is there a way to combine them first and then perform filtering and trimming in one step? 

Alternatively, since the derep class objects are fastq with uniform quality scores, is there a way to export those and then bring them back into dada2 using a file path, therefore being more similar to the traditional workflow described?

**Comment by benjjneb** [comment]
> such that each is now a derep class object. Is it then possible to filter and trim (using fastqFilter?). If so, should this be done to each derep class object individually, or is there a way to combine them first and then perform filtering and trimming in one step?

No, `filterAndTrim` works on fastq files, not on drep-class objects.

> Alternatively, since the derep class objects are fastq with uniform quality scores, is there a way to export those and then bring them back into dada2 using a file path, therefore being more similar to the traditional workflow described?

There is no simple command to do that. There may be a way to do this on the fasta files in R using commands in the ShortRead package. However, we don't recommend or support this approach.

**Comment by rowe285** [comment]
Thank you for your help!
