### ISSUE TITLE
plotQualityProfile

### ISSUE THREAD

**Issue by avportal** [benjjneb/dada2#1844]
when using plotQualityProfile(fnFs[1:2]) (dada2 tutorial) I get the following warning message:

The `<scale>` argument of `guides()` cannot be `FALSE`. Use "none" instead as of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the dada2 package.
  Please report the issue at <https://github.com/benjjneb/dada2/issues>

Regards,

Angel

**Comment by harleenkchaggar** [comment]
I have come across the same error-
The `<scale>` argument of `guides()` cannot be `FALSE`. Use "none" instead as of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the dada2 package.
  Please report the issue at <https://github.com/benjjneb/dada2/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated

I tried updating BiocManager and installed dada2 and ggplot2 again and it worked for me.
