### ISSUE TITLE
How to determine the truncation length based on binned quality score profile?

### ISSUE THREAD

**Issue by chenyj8** [benjjneb/dada2#1845]
plotQualityProfile can be used to explore the potential truncation length. However, plotQualityProfile with NovaSeq 6000 data generates binned quality score profile. How to determine the truncation length based on a binned profile?

<img width="679" alt="image" src="https://github.com/benjjneb/dada2/assets/48304249/23b136f7-f82c-41c2-a026-eaf17268c626">

**Comment by benjjneb** [comment]
Keep enough to maintain overlap, but drop the last few bases on each read.
