### ISSUE TITLE
No generated files after using Cutadapt in DADA2 analysis for ITS 

### ISSUE THREAD

**Issue by darjniki** [benjjneb/dada2#1846]
Dear all,

I am using DADA2 tutorial for fungal ITS using the same files from the tutorial (https://benjjneb.github.io/dada2/ITS_workflow.html).

However, after running Cutadapt no files in the cutadapt folder are generated, and afterwards line for checking the presence of primers give me an error:

Error in h(simpleError(msg, call)) :
error in evaluating the argument 'subject' in selecting a method for function 'vcountPattern': error in evaluating the argument 'object' in selecting a method for function 'sread': Input/Output
no input files found
dirPath: C:/Users/Darja/Desktop/Tutorial2/cutadapt/SRR5314314_1.fastq.gz
pattern: character(0)

Maybe you have some ideas why it is happening and how can I solve it?

# Whole script:

library(dada2)
library(ShortRead)
library(Biostrings)

path <- "C:/Users/Darja/Desktop/Tutorial2"  ## CHANGE ME to the directory containing the fastq files.
list.files(path)

fnFs <- sort(list.files(path, pattern = "_1.fastq.gz", full.names = TRUE))
fnRs <- sort(list.files(path, pattern = "_2.fastq.gz", full.names = TRUE))

FWD <- "ACCTGCGGARGGATCA"  ## CHANGE ME to your forward primer sequence
REV <- "GAGATCCRTTGYTRAAAGTT"  ## CHANGE ME...

allOrients <- function(primer) {
  # Create all orientations of the input sequence
  require(Biostrings)
  dna <- DNAString(primer)  # The Biostrings works w/ DNAString objects rather than character vectors
  orients <- c(Forward = dna, Complement = Biostrings::complement(dna), Reverse = Biostrings::reverse(dna),
               RevComp = Biostrings::reverseComplement(dna))
  return(sapply(orients, toString))  # Convert back to character vector
}
FWD.orients <- allOrients(FWD)
REV.orients <- allOrients(REV)
FWD.orients

fnFs.filtN <- file.path(path, "filtN", basename(fnFs)) # Put N-filtered files in filtN/ subdirectory
fnRs.filtN <- file.path(path, "filtN", basename(fnRs))
filterAndTrim(fnFs, fnFs.filtN, fnRs, fnRs.filtN, maxN = 0, multithread = TRUE)

primerHits <- function(primer, fn) {
  # Counts number of reads in which the primer is found
  nhits <- vcountPattern(primer, sread(readFastq(fn)), fixed = FALSE)
  return(sum(nhits > 0))
}
rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.filtN[[1]]), 
      FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.filtN[[1]]), 
      REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.filtN[[1]]), 
      REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.filtN[[1]]))

cutadapt <- "C:/Users/Darja/AppData/Local/Programs/Python/Python312/Lib/site-packages/cutadapt" # CHANGE ME to the cutadapt path on your machine
system2(cutadapt, args = "--version") # Run shell commands from R

path.cut <- file.path(path, "cutadapt")
if(!dir.exists(path.cut)) dir.create(path.cut)
fnFs.cut <- file.path(path.cut, basename(fnFs))
fnRs.cut <- file.path(path.cut, basename(fnRs))

FWD.RC <- dada2:::rc(FWD)
REV.RC <- dada2:::rc(REV)
# Trim FWD and the reverse-complement of REV off of R1 (forward reads)
R1.flags <- paste("-g", FWD, "-a", REV.RC) 
# Trim REV and the reverse-complement of FWD off of R2 (reverse reads)
R2.flags <- paste("-G", REV, "-A", FWD.RC) 
# Run Cutadapt
for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                             fnFs.filtN[i], fnRs.filtN[i])) # input files
}

rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.cut[[1]]), 
      FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.cut[[1]]), 
      REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.cut[[1]]), 
      REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.cut[[1]]))

# Error
Error in h(simpleError(msg, call)) :
error in evaluating the argument 'subject' in selecting a method for function 'vcountPattern': error in evaluating the argument 'object' in selecting a method for function 'sread': Input/Output
no input files found
dirPath: C:/Users/Darja/Desktop/Tutorial2/cutadapt/SRR5314314_1.fastq.gz
pattern: character(0)

# 
Would be very grateful for your help,
BW,
Darja

**Comment by benjjneb** [comment]
What is the output from the cutadapt step?
Is cutadapt even running at all?
And what line is causing that error?

**Comment by darjniki** [comment]
Thank you for the answer! 

# What is the output from the cutadapt step?
R doesn't write any output after running:

 for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                             fnFs.filtN[i], fnRs.filtN[i])) # input files
}

However, if I check fnFs.cut and fnRs.cut R writes location of those files (for instance: C:/Users/Darja/Desktop/Tutorial2/cutadapt/SRR5314314_2.fastq.gz), but if I check it manually I don't see any file in this folder. 

# Is cutadapt even running at all?
Yes, I don't have any errors on cutadapt step.

# And what line is causing that error?

This one:
rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.cut[[1]]), 
      FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.cut[[1]]), 
      REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.cut[[1]]), 
      REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.cut[[1]]))
      
Looking forward hearing from you,
D.

**Comment by benjjneb** [comment]
What is the output in the R console when you run:

```
system2("cutadapt", "--version")
```

**Comment by darjniki** [comment]
benjjneb, it does not give any output (warning /error or message).

**Comment by benjjneb** [comment]
Sorry, I mistyped the previous, it shouldn't have the quotes around cutadapt at the start. What is output of:

```
system2(cutadapt, "--version")
```

Where cutadapt is the variable defined in the session that gives the path to your cutadapt binary. Also, what is `print(cutadapt)` and `file.exists(cutadapt)`?

**Comment by harivenur** [comment]
I am encountering the exact same problem. Any solutions yet?

**Comment by benjjneb** [comment]
@harivenur Can you report the outputs requested in the previous comment https://github.com/benjjneb/dada2/issues/1846#issuecomment-1804746791

**Comment by harivenur** [comment]
> @harivenur Can you report the outputs requested in the previous comment [#1846 (comment)](https://github.com/benjjneb/dada2/issues/1846#issuecomment-1804746791)

system2(cutadapt, "--version") doesn't give any response in R. It runs, though, without outputting any error message.  (when I check the version of cutadapt in the cmd.exe on Windows [py -m cutadapt --version], it gives 4.6)
print(cutadapt) gives the file path to my cutadapt folder in my computer.
file.exists(cutadapt) gives TRUE.
