### ISSUE TITLE
plot quality error Error in UseMethod("depth") :    no applicable method for 'depth' applied to an object of class "NULL"

### ISSUE THREAD

**Issue by murheisa** [benjjneb/dada2#1847]
Hello, I'm trying to plot the forward quality plot, and when I do it, I get the following: 

Error in UseMethod("depth") : 
  no applicable method for 'depth' applied to an object of class "NULL"

The plot does appear, but all the samples have 98 reads and I wonder if this has something to do with it.

I´working with a Mac M1 and R version 4.3.1, dada version 1.28.0

**Comment by benjjneb** [comment]
What is the command you are calling that produces this error? Can you also show the output?
