### ISSUE TITLE
Error rates could not be estimated (this is usually because of very few reads). Error in getErrors(err, enforce = TRUE) : Error matrix is NULL.

### ISSUE THREAD

**Issue by harleenkchaggar** [benjjneb/dada2#1849]
I downloaded 16S amplicons of Thermus thermophilus (n=5 fastq files) from NCBI, these were assembled with Illumina MiSeq. I am running dada2 (first time) and trying to learn about the error rates. However, this is my error:

errF <- learnErrors(filtFs, multithread=TRUE)
46095360 total bases in 192064 reads from 5 samples will be used for learning the error rates.
Error rates could not be estimated (this is usually because of very few reads).
Error in getErrors(err, enforce = TRUE) : Error matrix is NULL.

- Also, I started dada2 with just one fastq file to begin with and got the same error so I increased my samples to five in the hope it would eliminate the possibility of having very few reads. But again same error.

**Comment by benjjneb** [comment]
What does `plotQualityProfile` look like on an example sample?

**Comment by harleenkchaggar** [comment]
Thank you for your reply. I could not even get a plot quality profile; instead had this issue-

when using plotQualityProfile(fnFs[1:2]) (dada2 tutorial) I get the following warning message:

The <scale> argument of guides() cannot be FALSE. Use "none" instead as of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the dada2 package.
Please report the issue at https://github.com/benjjneb/dada2/issues

I am attaching a plot just in case-
[R1_plot.pdf](https://github.com/benjjneb/dada2/files/13335472/R1_plot.pdf)

**Comment by harleenkchaggar** [comment]
Thank you for your help.

**Comment by benjjneb** [comment]
Note: These all Q30 datasets are often coming from downloading via the web interface from SRA. This gives you the "SRAlite" format, which replaces all quality scores with Q30. Using the sra-toolkit to download the data will get the originally quality scores.
