### ISSUE TITLE
Using DADA2 for ITS

### ISSUE THREAD

**Issue by cjburgess** [benjjneb/dada2#185]
I just wanted some clarifications about dada2's ability to process ITS reads.  Has variable length been Incorporated into the error model  decision making or would you recommend trimming all reads to a certain length and just processing the forward or the reserve?

Thanks for the great tool!
Chris

**Comment by benjjneb** [comment]
Right now dada2 requires that all reads are trimmed to the same length, which can make processing ITS data difficult. We are working on removing that requirement (its not necessary, just built into the code at the moment) and progress will appear here: #55

**Comment by cjburgess** [comment]
Thanks! I saw that thread, just wanted to make sure it was the most recent.

**Comment by benjjneb** [comment]
As of version 1.3.3 (cddce98a98894e4a621f6767e61fe9aaed638e06) DADA2 supports ITS. This includes handling variable length amplicons and assigning taxonomy against the UNITE database.

**Comment by gcuster1991** [comment]
If i were to use DADA2 (V>1.3.3) to process ITS data would it require a processing step similar to ITSextract, which extracts the highly variable ITS1 and ITS2 regions?

**Comment by benjjneb** [comment]
Updating this thread with a link to the official [DADA2 ITS workflow](https://benjjneb.github.io/dada2/ITS_workflow.html).
