### ISSUE TITLE
Error: BiocParallel errors 1 remote errors, element index: 1 0 unevaluated and other errors first remote error:

### ISSUE THREAD

**Issue by marwa38** [benjjneb/dada2#1851]
Hi 

I am getting the following error but I am not sure why although for the other set of reads (reverse) I am getting no error.

```
Error: BiocParallel errors
1 remote errors, element index: 1
0 unevaluated and other errors
first remote error:
```

Here is my script 

```
# load libraries ----
library("tidyverse")
library("dada2") 
library("ggplot2")

path <- "./" #create path to the data files we working on (#Let's now set the input directory, where the demultiplexed per-sample fastq files reside) 

# create directories 
dir.create("tables")
dir.create("figures")
dir.create("phyobjects")
dir.create("codes_notes")
dir.create("trees")
dir.create("Robjects")
dir.create("networks")

fileList <- list.files(path) #list all files 

#Assuming the fastq files naming format (forward and reverse): SAMPLENAME_R1.fq.gz and SAMPLENAME_R2.fq.gz we can proceed as follows to group the forward and reverse filenames together:
fnFs <- sort(list.files(path, pattern = "_1.fq.gz", full.names = TRUE)) #create a sorted list of vector for forward reads 
fnRs <- sort(list.files(path, pattern = "_2.fq.gz", full.names = TRUE)) #create a sorted list of vector for reverse reads 

sample.names <- sapply(strsplit(basename(fnFs), "_"), '[', 1) #split the first part before _ and store that to sample.names vector

#Before trimming, it is a good idea to take a look at the quality profile of my data:

# visualise few samples for inspection
# forward 
fplot1 <- plotQualityProfile(fnFs[18:19])
fplot1 +
  scale_x_continuous(breaks=seq(0,300,20)) +
  geom_hline(yintercept=30, color = "blue") +
  ggtitle("Forward QC")

# reverse 
rplot1 <- plotQualityProfile(fnRs[18:19])
rplot1 +
  scale_x_continuous(breaks=seq(0,300,20)) +
  geom_hline(yintercept=30, color = "blue") +
  ggtitle("Reverse QC")

```

some screenshot demonstrations
samples I tried to visualize 
![image](https://github.com/benjjneb/dada2/assets/68851733/eb7f927d-005b-4482-94af-d225555e88a6)
Rstudio error code:
![image](https://github.com/benjjneb/dada2/assets/68851733/75c895fa-bee0-4aa2-8cf1-9447af28c3c4)

> sessionInfo()
R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8   
[3] LC_MONETARY=English_United Kingdom.utf8 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

time zone: Europe/London
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] dada2_1.28.0    Rcpp_1.0.11     lubridate_1.9.2 forcats_1.0.0   stringr_1.5.0   dplyr_1.1.2    
 [7] purrr_1.0.2     readr_2.1.4     tidyr_1.3.0     tibble_3.2.1    ggplot2_3.4.3   tidyverse_2.0.0
[13] knitr_1.43      tinytex_0.46    rmarkdown_2.24

**Comment by benjjneb** [comment]
Can you try running `plotQualityProfile` on one sample at a time? Is there anything in the traceback that helps identify what's going on?

**Comment by marwa38** [comment]
Thanks for your reply @benjjneb 
It worked when I only ran it on one: 
```
> plotQualityProfile(fnFs[18])
Warning messages:
1: In serialize(data, node$con) :
  'package:stats' may not be available when loading
2: Removed 99 rows containing missing values (`geom_tile()`).
```
not sure why I am getting these warnings 
last year used to run on all samples not only two without any error/warning. 
What do you think?

**Comment by benjjneb** [comment]
Something is going on with that second sample. Can you take a look at the output of qa on the sample?

```
library(ShortRead)
fn <- fnFs[19]
report(qa(fn), dest="~/Desktop/qa") # CHANGE ME
# Then open `~/Desktop/qa/index.html` # CHANGE ME
```

Change the files at the appropriate places as needed. What does that report on the file look like? Any clues suggesting something might be unusual about this fastq file?

**Comment by benjjneb** [comment]
It looks like there are missing quality scores in this fastq file?

Was any pre-processing done to this fastq file prior to this? Did you get these files straight from a sequencing provider, or through an intermediary? What sequencing technology was used to generate these?

**Comment by marwa38** [comment]
That is correct; I got them that way straight from the sequencer, where they removed the primers and barcodes.

**Comment by benjjneb** [comment]
What sequencing technology was used to generate these?

**Comment by marwa38** [comment]
We used MiSeq Illumina sequencing in Novogene company
what do you think?

**Comment by benjjneb** [comment]
My guess is still that there is something wrong with the fastq files, although that you got this data directly from a reputable seqeuncing provider does argue against that idea.

To dig in a bit more, what do the first 5 "lines" of the problem fastq file look like? These can be accessed by something like `head -n 5 problem.fastq' in a shell environment. The file will need to be decompressed into plain text format first though.

**Comment by marwa38** [comment]
Thanks for your comment. 
F letter means that the quality is fine. 
![image](https://github.com/benjjneb/dada2/assets/68851733/9a9682f8-41af-4328-95da-33da109826a7)

**Comment by benjjneb** [comment]
What I'd recommend is trying to isolate the record(s) in this fastq file that are breaking the import into R. One way to do this is to create chunks of the file that include only the first X entries (or entries X - X + Y) and identify which chunks are breaking import into R, e.g. that make `readFastq(test_file_X_to_Y.fq)` fail. I'd recommend working with the uncompressed file at this stage to make things easier.

Once the record(s) that are breaking import are identified, diagnosis will be much easier.

**Comment by marwa38** [comment]
In those two issues https://github.com/benjjneb/dada2/issues/1316 & https://github.com/benjjneb/dada2/issues/159
There might be a reason where I have zero sequences in some of the reads!
Although the smallest one is of 10,000 KB (as below), what do you think?
![image](https://github.com/benjjneb/dada2/assets/68851733/3514abf8-d3c6-4a87-a8aa-39303a0a3886)

**Comment by marwa38** [comment]
here is fastqc reports of some reads 
[fatqc reports.zip](https://github.com/benjjneb/dada2/files/13676191/fatqc.reports.zip)

**Comment by benjjneb** [comment]
Yes I think you identified the issue. Not all DADA2 functions gracefully handle zero-length sequences in the fastq file.

That said, I think `filterAndTrim` with a `minLen` argument will remove these zero-length sequences, so that slight tweak to the standard dada2 workflow should suffice to avoid this.

**Comment by marwa38** [comment]
Thanks for your response @benjjneb. changing minLen = 0 would be ok?

**Comment by marwa38** [comment]
@benjjneb Thanks for your response. 

The default of filterAndTrim is that minLen=20, so I did this already. 
![Captuqre](https://github.com/benjjneb/dada2/assets/68851733/bd8b6ff5-b983-4cc5-ad18-2ce6c27e7eab)


But I am getting a drastic loss of reads at in the merging step
![Capture](https://github.com/benjjneb/dada2/assets/68851733/51e71178-fe6d-4530-b95d-589fc22cc2fa)
NovaSeq sequencer 2x250 for V3-V4 region didn't merge well I believe. Have you heard this issue with 2x250 (paried end reads) for NovaSeq before?

**Comment by benjjneb** [comment]
What are your truncation lengths? Did you do any preprocessing using external tools (e.g. cutadapt, trimmomatic or the like) prior to entering the dada2 workflow?

V3V4 typically needs ~460nts of retained reads between forward and reverse to merge effectively.

**Comment by marwa38** [comment]
Novogene NovaSeq 2x250 is barely could be ~460nts
As you can see, they do remove their barcodes and parameters (they don't state their tools they used for trimming), leaving F reads of around 227 nt and R reads of around 224 nt as it is described in here:
https://forum.qiime2.org/t/questions-about-16s-data-from-novogene-uk/26844
