### ISSUE TITLE
Question regarding the computation of the p-value

### ISSUE THREAD

**Issue by pereiramemo** [benjjneb/dada2#1853]
Dear DADA2 developers, 

There is section in the paper that describes how DADA2 works (https://www.nature.com/articles/nmeth.3869), that I am not sure how to interpret. That is, "The abundance p-value" section in the "Online Methods". Here it says:
"Let unique sequence i with abundance ai be in partition j containing nj reads. Then, conditional on i being read at least once, the abundance p- value is the probability of seeing nj or more identical reads (ρpois is the Poisson density function)"

My understanding is that here it should say "the probability of seeing **aj** or more identical reads". 
Could please confirm that the text in the paper is right. 

Many thanks, 

Emiliano

**Comment by benjjneb** [comment]
Yes, that looks like a mistake in our notation. Your suggested fix is mostly correct, except that following our subscript notation it would be "a_i or more identical reads" (not a_j).

**Comment by pereiramemo** [comment]
Yes, a_i. Thanks for the response!

**Comment by benjjneb** [comment]
Agree that the potential error sequences need to be accounted for when defining the parameter of the poisson distribution evaluating whether errors could explain the observed reads.

In dada2 at the algorithimc level, the partition abundance (n) is all the reads that are at that point considered as potentially derived from the partition-defining sequence.

This approach is generally more conservative in calling new ASVs.

**Comment by pereiramemo** [comment]
This clarifies my understanding.
Many thanks for your answer.

Best, 

Emiliano
