### ISSUE TITLE
SRFilterResult error

### ISSUE THREAD

**Issue by Laurco7** [benjjneb/dada2#1854]
Hello, I'm working through the dada2 tutorial and have encountered these two issues - please see below. Thank you! 

> # Extract sample names, assuming filenames have format: SAMPLENAME_XXX.fastq
> sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
> plotQualityProfile(fnFs[1:2])
Warning message:
The `<scale>` argument of `guides()` cannot be `FALSE`. Use "none" instead as of
ggplot2 3.3.4.
i The deprecated feature was likely used in the dada2 package.
  Please report the issue at <https://github.com/benjjneb/dada2/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
generated. 
> plotQualityProfile(fnRs[1:2])
> filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
> filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
> names(filtFs) <- sample.names
> names(filtRs) <- sample.names
> out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
+                      maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
+                      compress=TRUE, multithread=FALSE)
Error in validObject(.Object) : 
  invalid class “SRFilterResult” object: superclass "Mnumeric" not defined in the environment of the object's class

**Comment by benjjneb** [comment]
Please update to a more recent version of the dada2 R package and both these issues should be resolved.
