### ISSUE TITLE
Losing a high percentage of reads after merging AND after chimeras removal.

### ISSUE THREAD

**Issue by NoGaud** [benjjneb/dada2#1857]
Hello,

After some days going through all the issues that seemed pertinent here, i think i need to ask more guidance about my issue. 

In my track, i lose about 60% of my reads after merging, then i lose around 40% of the merged reads after the chimeras removal. 

The sequencing was Illumina 2x300 on the V3-V4 region of the 16S region. I use the primers 341F and 805R (so around 464 bp is expected). There's usually no heterogeneity spacers with this company.

So my out command is:
out.bact1 <- filterAndTrim(fnFs.bact1,filtFs.bact1,fnRs.bact1,filtRs.bact1,truncLen=c(285,235),
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, trimLeft=c(17,21), multithread=TRUE) 

The quality of my files are pretty good also. 
Forward: 
<img width="699" alt="Capture d’écran, le 2023-11-28 à 11 01 04" src="https://github.com/benjjneb/dada2/assets/108941037/84e1f6a1-3141-47d5-bf46-3d414f12ae97">

Reverse:
<img width="699" alt="Capture d’écran, le 2023-11-28 à 11 01 21" src="https://github.com/benjjneb/dada2/assets/108941037/1292c565-fd08-4ced-b4c9-36fcb4ca0d83">

Plot errors doesn't show any red flags:
<img width="699" alt="Capture d’écran, le 2023-11-30 à 11 05 41" src="https://github.com/benjjneb/dada2/assets/108941037/4324560f-374a-47db-b10e-3ad2dc56d1be">

Here is my track: 
[track.bact.1.txt](https://github.com/benjjneb/dada2/files/13504895/track.bact.1.txt)

So, first of all i removed my primers with trimLeft, and i tested that it was really removed with the ITS pipeline to be sure: 
<img width="641" alt="Capture d’écran, le 2023-11-30 à 10 13 18" src="https://github.com/benjjneb/dada2/assets/108941037/654f79fb-c772-4ebb-8011-7d49a93861d5">
<img width="314" alt="Capture d’écran, le 2023-11-30 à 10 40 50" src="https://github.com/benjjneb/dada2/assets/108941037/4c52f987-4147-4209-8ef8-c0b46981cc10">
(I saw somewhere that 200 primers left was okay to not interfere with the analyses so i assume 33 and 66 is okay too).

My overlap should be from 13 to 18 (so >12) in my tests that get the most reads out of the pipeline (TruncLen = 285,235 or 280,235). I tried bigger overlaps (TruncLen (290,250)) to be sure it didn't magically unblock a lot of reads to go through, but it didn't, it only contributed to losing more reads. I read about the bimodal distribution in reads length for V3V4 and i know i still have both of those lengths in my data with the getSequences function (around 403 and 427 right?). 
Making maxEE higher is not really worth it and doesn't change that much the number of reads either.

I'm wondering if there's something that i missed, because i actually have two sequencing runs i need to analyze and the track is so similar for both of them. I know it could be weird because of the sequencing run, but for both of them to be similarly "bad" would be a rare coincidence? (One run is from June 2023, the other from November 2023.)

I was wondering if there's anything more i could have missed, what more i can look at to get less % of reads lost in the process. 

Thanks a lot for your work

**Comment by salix-d** [comment]
Just by looking at the quality plots, I think I would've gone for `TruncLen=250,200`.
The way I was shown was to try and cut before the big noise, unless it prevents overlaps entirely.

**Comment by NoGaud** [comment]
Hello, it's still me, in between i read that i needed to join my two sequencing runs after merging, but before chimeras. In the end i get a result like this:

Identified 44376 bimeras out of 72470 input sequences.
[1]   140 28094
[1] 0.6521404

Since my primers are okay, what else could be the cause of that many chimeras?

**Comment by NoGaud** [comment]
Hello, 

I tried to contact them to know for sure. For now, if i look at my fastq files, after the primers it's not always the same sequence. (Would the same sequence at this position be the heterogeneity spacers? I'm not familiar with them and how they exist.)

Here is some screenshot to be sure, the selected text begins right after the primers. 
<img width="399" alt="Capture d’écran, le 2023-12-08 à 11 16 15" src="https://github.com/benjjneb/dada2/assets/108941037/692c0542-22b6-4525-b665-00ec415d4f95">
<img width="318" alt="Capture d’écran, le 2023-12-08 à 11 17 51" src="https://github.com/benjjneb/dada2/assets/108941037/68c07a79-726d-41f1-bddb-abe7dbd798f7">

**Comment by benjjneb** [comment]
Sorry for the late response, I lost this over the holidays.

I see these 7-mers highlighted in your fastq files, but what does that mean? Are those part of the primers? What part? What are the primers? What does it mean that some of the sequences don't have those 7-mers?
