### ISSUE TITLE
 Couldn't automatically detect the sequence identifier field in the fastq id string

### ISSUE THREAD

**Issue by wygbio** [benjjneb/dada2#1859]
I am also meeting a similar issue with the head of fastq files. They were obtained by Illumina MiSeq, not downloaded from the NCBI SRA database. Is there something wrong with the head that can't be detected?
@HWI-D00433:728:HHHKHBCX2:2:1101:8032:2352.1:N:0--D13a_C25.

**Comment by benjjneb** [comment]
This ID line has 7 colon-delimited fields before a white space. The standard Casava formats have either 4 (old) or 6 (current). This also doesn't look like a standard Casava (i.e. Illumina standard) id line. See examples here: https://knowledge.illumina.com/software/general/software-general-reference_material-list/000002211

It is close though, perhaps it is just some reformatting that was done that combined the post white-space field with the pre-whitespace field? In any case, the dada2 package can't handle non-standard ID fields automatically.

Do you need to use id matching here? If the forward and reverse read files are in matched order, you can just drop that functionality and this issue will go away. If you do have to, you'll have to either reformat the files into a "standard Casava" format, or use the `id.sep` and `id.field` arguments to direct the `matchIDs` argument appropriately.
