### ISSUE TITLE
Efficacy of carrying out error rate learning and sample inference in one step vs sequential steps. 

### ISSUE THREAD

**Issue by JacobRPrice** [benjjneb/dada2#186]
Hi Everyone, 

I'm curious to know if it's appropriate (or beneficial) to carry out simultaneous error rate learning and sequence variant inference vs performing those two steps independently (as found in the walkthrough and big data tutorials). 

For clarity, the example in the walkthrough is as follows:

**Learn the Error Rates**
`dadaFs.lrn <- dada(derepFs, err=NULL, selfConsist = TRUE, multithread=TRUE)`
`errF <- dadaFs.lrn[[1]]$err_out`
`dadaRs.lrn <- dada(derepRs, err=NULL, selfConsist = TRUE, multithread=TRUE)`
`errR <- dadaRs.lrn[[1]]$err_out`

**Followed by infering the sequence variants**
`dadaFs <- dada(derepFs, err=errF, multithread=TRUE)`
`dadaRs <- dada(derepRs, err=errR, multithread=TRUE)`

For "smaller" datasets, either in number of samples or number of reads/sample or total reads, is it ever beneficial/advisable to carry out those to actions simultaneously? Below is an example of what I've been experimenting with.

`dadaFs <- dada(derepFs, err=NULL, selfConsist=TRUE, pool=TRUE, multithread=TRUE,MAX_CONSIST=20)`

The documentation indicates that by setting selfConsist=TRUE dada() will alternate between error rate estimation and sequence inference. 

1. Is there any reason other than computation time that those two steps are explicitly split up?
2. If not, is it reasonable to expect that one approach results in more accurate RSV calling over the other?

**Comment by benjjneb** [comment]
(1) Nope, splitting them up is solely in the interest of saving computation time by learning the error rates from a subset of the data.

(2) In practice the improvement in the accuracy of estimated error rates from reads beyond the first million or two is so small that it becomes inconsequential, but if your total dataset runs in `selfConsist` mode in a reasonable time, that is best.

**Comment by JacobRPrice** [comment]
Thank-you for the clarification!
