### ISSUE TITLE
Error when merging paired end reads

### ISSUE THREAD

**Issue by bdonnelly112493** [benjjneb/dada2#1860]
Hi there,

When i initially ran my code, I did not receive this error, but for some reason, with a larger dataset that I've been working on recently, I keep getting this error when running the mergePairs function. 

Error in FUN(X[[i]], ...) : 
  Non-corresponding derep-class and dada-class objects.

I'm not quite sure what the issue is as the tutorial has been working up until this point. Any advice would be greatly appreciated!

**Comment by bdonnelly112493** [comment]
I thought I solved this issue, but now running the code again with a different data set, I'm still having the same problem. Any help would be appreciated.

**Comment by benjjneb** [comment]
We need more information to be able to help. What is the exact command that is causing this error? What is the exact error? What is basic info about the dataset you are trying to process?
