### ISSUE TITLE
error with FilterAndTrim names

### ISSUE THREAD

**Issue by miguelsemedobb** [benjjneb/dada2#1863]
Hi there, 

I'm running dada2 in R, on a M1 Mac machine, and I'm getting an error message that's new to me and couldn't find any help online. Here is the code and error message:

##### START OF CODE ######

> out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen = 0, 
+                      trimLeft = 0, minLen = 20,
+                      maxN=0, minQ = 0, maxEE=c(2,2), truncQ=2,
+                      rm.phix=TRUE, compress=TRUE, 
+                      multithread=TRUE, verbose = TRUE) # On Windows set multithread=FALSE
Error in names(answer) <- names1 : attempt to set an attribute on NULL
In addition: Warning message:
In mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule,  :
  scheduled cores 1, 2, 3, 4, 5, 6, 7, 8 did not deliver results, all values of the jobs will be affected

##### END OF CODE ######

R version is 4.3.1. and dada2 packageVersion is 1.30.0. It seems that everything is ok with my input data (fnFs and  fnRs), no duplication, matching IDs between Fwd and Rev, file paths, etc. To confirm that this was not an issue with the file names or folders, I tried to run an older code on previously successful data and got the same error message. Could there be any issue with newer dada2 version, R version incompatibility, or M1 processor? I also checked storage space and It looks fine (around 30 GB free on SSD, while the total amount of data is only 1,39 GB). 

Did someone get the same error? What could be the issue here?

Best,
Miguel

**Comment by miguelsemedobb** [comment]
UPDATE: the error disappear using dada2 1.26.0 on R version 4.3.2.

**Comment by benjjneb** [comment]
I'll consider this fixed for now, but if you could try to reproduce the issue you saw with the other dada2 package version, but run it in `multithread=FALSE` mode, it will give a more informative error message.

**Comment by miguelsemedobb** [comment]
Thanks! I actually tried to run it also in `multithread=FALSE`, but R crashed on several trials.
