### ISSUE TITLE
Reads loss during nonchim step.

### ISSUE THREAD

**Issue by hh1985** [benjjneb/dada2#1866]
I applied dada2 to process my reads and received following QC results:
![image](https://github.com/benjjneb/dada2/assets/7053284/93a7beca-8cc0-4b1f-bd0c-08966aae4d01)

Some samples had about one third of the reads removed in the nonchim step. I am not sure if this is reasonable.

__Background__:
The data is paired-end data, and sequenced by BGI machine  (V4, 515F (5’-GTGCCAGCMGCCGCGGTAA-3’) and 806R (5’- GGACTACHVGGGTWTCTAAT-3’)). The primers had been trimmed when I received the data.  I further used trunclenf 180 and trunclenr 150 for the dada2 trimming:
![image](https://github.com/benjjneb/dada2/assets/7053284/deb36e44-a2bd-4455-ad21-34df3c8c4541)

**Comment by benjjneb** [comment]
On the level of raw read fates, what you are seeing is not out of bounds, but it is a high level of chimera-flagged sequences. This is at the upper range of what we see from legitimate amplicon sequencing data, and is usually associated with higher than normal numbers of PCR cycles (30+) or non-standard mixtures of samples prior to PCR.

> The primers had been trimmed when I received the data.

The other reason we see data like this is that the primers weren't really trimmed from the data, or at least not efficiently.
If you are using an ASV method like DADA2, you are almost always best off obtaining the raw untrimmed data and working from that if you can.
