### ISSUE TITLE
Greengenes2 reference database for DADA2 using R

### ISSUE THREAD

**Issue by mutjangee** [benjjneb/dada2#1867]
Recently, we are considering Greengenes2 as reference database for our projects. To assign taxonomy, which database in this website (https://ftp.microbio.me/greengenes_release/current/) should be good for the DADA2 pipeline in R?

**Comment by benjjneb** [comment]
Please see link here: https://github.com/benjjneb/dada2/issues/1680#issuecomment-1724495374

But also consider the discussion at that issue.
