### ISSUE TITLE
Getting Error When assigning taxonomy in R

### ISSUE THREAD

**Issue by wangz14** [benjjneb/dada2#1868]
Hi, I am trying to assign taxonomy for my genetics data in R using the code: 

```{r}
taxa_midas_genus <- assignTaxonomy(seqtab.nochim, "C:/....../MiDAS.fa",
+                                      taxLevels = c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus"),
+                                      verbose = TRUE,
+                                      tryRC = TRUE,
+                                      minBoot = 80) %>%
+     as_tibble(rownames = "sequence")
```
But Every time I run the code, i get the error: 

Error in if ((is.null(names) || any(bad_names <- duplicated(names) | names ==  : 
  missing value where TRUE/FALSE needed

Any thoughts on how to fix this?
Thanks

**Comment by benjjneb** [comment]
First thoughts, `"C:/....../MiDAS.fa"` looks like trouble. Does that work if you try it in `file.exists`? Can you give a less problematic filepath?

**Comment by wangz14** [comment]
Hi Ben, 

```{r}
file.exists 
```
outputs TRUE

**Comment by benjjneb** [comment]
Let's try to isolate the problem as being with the database or the input data.

```
test.sq <- "ACACAGTTAGTCGTATGCACGTCTGATGCACTAGCTAGCATCGATCAGCATCGATTAATATCTGCGGTCATGTATTGGCAT"
test.db <- "path/to/other/reference.fasta" # Download another from the DADA2 reference fastas page
```

Then try your `assignTaxonomy` command with `test.sq` and midas reference, and then with `test.db` and `seqtab.nochim`.

**Comment by wangz14** [comment]
So the test.sq came out and identified the kingdom but had Na for all of the other classes. 
For the test.db, I utilised the GTDB database which outputed all of the sequences and the family the sequence belongs to

**Comment by wangz14** [comment]
Hi Ben, 

So I tried both and both managed to output an result. I am trying to run the code without the ``` as.tibble``` line, but it takes a lot longer to run in comparison to running the code against the GTDB database.

**Comment by benjjneb** [comment]
> So the test.sq came out and identified the kingdom but had Na for all of the other classes.

`test.sq` is a nonsense sequence, we are just testing if the command completes correctly with the MIDAS reference-- looks like it did.

> For the test.db, I utilised the GTDB database which outputed all of the sequences and the family the sequence belongs to

To clarify, if you switch out the reference database from MIDAS to GTDB in the exact command you ran in https://github.com/benjjneb/dada2/issues/1868#issue-2058411904 the error goes away?

**Comment by wangz14** [comment]
Hi Ben, 

Not Quite. I ran

```
test.db <- "C:/Users/zzw18/R/RGeneticAnal/CleanData/GTDB_bac-arc_ssu_r86.fa.gz"
assignTaxonomy(seqtab.nochim, refFasta = test.db) 
```
But I did also run:
```
assignTaxonomy(seqtab.nochim, "C:/Users/zzw18/R/RGeneticAnal/CleanData/MiDAS.fa",
                                     taxLevels = c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus"),
                                     verbose = TRUE,
                                     tryRC = TRUE,
                                     minBoot = 80) 
```
without the ```as_tibble``` and it outputted all of the sequence so it seems to be an tibble/tidyverse issue. I'm just not quite sure what the problem is yet

**Comment by wangz14** [comment]
I found the issue. It was to do with some of the names in the database. 

This is the code that works: 
```
taxa_midas_genus <- assignTaxonomy(seqtab.nochim, "C:/Users/zzw18/R/RGeneticAnal/CleanData/MiDAS.fa", 
                   taxLevels = c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus"),
                   verbose = TRUE,
                   tryRC = TRUE,
                   minBoot = 80) %>% 
    as_tibble(rownames="sequence", missing = 0,  .name_repair = "minimal")
```

Thank you so much for the help Ben
