### ISSUE TITLE
Cutadapt leaving a set of primers 

### ISSUE THREAD

**Issue by Jiayonglai123** [benjjneb/dada2#1869]
Hi Prof,
I tried the ITS mock community from the tutorial and it works very well.
with the same script, I put in my data for cutadapt under system2
result shows there is 1 pair of primers left within and was not removed
![image](https://github.com/benjjneb/dada2/assets/141197608/f35be183-7915-469f-a811-afa082225a38)
I tried using plotQualityProfile to determind which samples, but it shows:
Error: BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error:
Error in density.default(qscore): 'x' contains missing values
In addition: Warning message:
In serialize(data, node$con) :
  'package:stats' may not be available when loading
  
  I am not sure what the error message means....
  Great apprieciation for the help in advance

**Comment by benjjneb** [comment]
What is the exact command you called? What is the exact error?

The figure you show suggests removal of primers was fully effective (one residual read means nothing), but may also indicate that it failed by throwing everyting away. How many reads are in the post-cutadapt fastqs?

**Comment by Jiayonglai123** [comment]
Thanks for your prompt reply prof,
here's a screenshot of the console
![image](https://github.com/benjjneb/dada2/assets/141197608/24abbbe7-17bd-4112-bb63-17558a367ba2)
I tried skipping the plotquality and proceed with filtering without truncating (as mentioned in the tutorial)
the result is pretty good I would say for the 1st 5 samples 
![image](https://github.com/benjjneb/dada2/assets/141197608/caa72343-bddb-4e25-8d91-7933b028acc2)
it means that cutadapt did not remove everything....but the question is plotquality is not working currently....

**Comment by benjjneb** [comment]
The `head(out)` command is probably showing the results of `filterAndTrim`, not that of cutadapt?

Is it possible that some of the files post cutadapt have no (or very few) reads left in them?

Quick ways to look in R are `file.exists(cutFs)`, and `ShortRead::countFastq(...)`

**Comment by Jiayonglai123** [comment]
Thanks Prof for the quick reply,
it seems all fastq file are good except one which is 1 magnitude differ from others
![image](https://github.com/benjjneb/dada2/assets/141197608/326d6b76-8760-4312-b445-25543e614478)
![image](https://github.com/benjjneb/dada2/assets/141197608/e527175a-b22e-445f-8c1b-9b4faff336dd)
I don't think it is too low though....for samples 14-20....

**Comment by benjjneb** [comment]
The read retention stats and the lack of unremoved primers all look fine here.

I don't understand what is going on with `plotQualityProfile`, but that is something that can simply be worked around, for example by using an external tool to like fastQC or many others to look at the quality profiles.
