### ISSUE TITLE
One sample versus multiple samples

### ISSUE THREAD

**Issue by NextGenSeek** [benjjneb/dada2#1875]
Hi,

When I run one sample only, the dada() function creates a Formal class dada object, however, when running multiple samples it creates a List. Is there a way to solve this, as this complicates the analysis further down the line?

Thank you for any input you might have.

**Comment by benjjneb** [comment]
Sadly, no. While this is not uncommon behavior in R (an object format singly, and a vector/list format in multiples) it is still annoying. It requires handling code for general purpose scripts that might encounter either situation.
