### ISSUE TITLE
problem with Sample Inference

### ISSUE THREAD

**Issue by Danyang1111** [benjjneb/dada2#1883]
Hi, I am trying to do the Sample Inference step, when I type code: dadaFs <- dada(derepFs, err=errF, multithread=TRUE), I got error messages: some samples are 0 reads. How can I deal with that?

**Comment by adrientaudiere** [comment]
Hi @Danyang1111, It seems that (at least) one of your dereplicated samples doesn't contain any reads. You can see the number of dereplicated reads using the code below to identify the problematic sample(s).

```r
lapply(derepFs, function(x){length(getUniques(x))})
```
