### ISSUE TITLE
TruncQ parameter not correlating with reads out

### ISSUE THREAD

**Issue by chung-wingko** [benjjneb/dada2#1884]
Hi, I'm running the dada2 script for 16S and during the filtering step, we came across an interesting problem. We adjusted the truncq parameter a few times, using truncq = 2, truncq = 10, and truncq = 11, and we got a different number of resulting reads that doesn't correlate with this adjustment (for example, 140508, 200554, and 172147, respectively). We should expect the number of reads.out to decrease as truncq increases, but this is not the pattern. I have attached a photo of this issue below. 

Could you help explain why these adjustments don't correlate? We have not adjusted any other parameter between these tests. 
![truncq](https://github.com/benjjneb/dada2/assets/98294353/cfc056d1-95f6-4f72-8a0b-28adc521bf3b)

**Comment by benjjneb** [comment]
First, we recommend against using `truncQ`. Introducing length variation into the data makes DADA2 less sensitive. It is better to use `truncLen` and `maxEE`. Or `minQ` is also preferable to `truncQ`.

The non-monotonicity is coming from the interactions between `truncQ`, `minLen` and `maxEE`. Setting higher `truncQ` will lead to more reads passing the expected errors filter, but less reads passing the `minLen` filter. So it can increase or decrease the number of reads being filtered out.
