### ISSUE TITLE
questions of Dereplication

### ISSUE THREAD

**Issue by Danyang1111** [benjjneb/dada2#1885]
Hi, I am trying to do the first step of Dereplication, I type: derepFs <- derepFastq(filtFs, verbose=TRUE), it shows:
> derepFs <- derepFastq(filtFs, verbose=TRUE)
Error in derepFastq(filtFs, verbose = TRUE) :
  Not all provided files exist.
How to fix it ?

**Comment by Danyang1111** [comment]
Thanks for the answering.
I now stuck at :names(derepFs) <- sample.names
Error in names(derepFs) <- sample.names :
  'names' attribute [60] must be the same length as the vector [51]
How should I deal with this ?

________________________________

**Comment by benjjneb** [comment]
The issues you are running into here are not really dada2 issues, they are R issues. I bring that up to say that if you have someone in your local network that is comfortable in R, they can probably solve many of these issues.

> How should I deal with this ?

Similarly to how you subset down `filtFs`, you also need to subset down `sample.names` to match.
That said, I would recommend just skipping this step -- the dada2 functions will automatically assign sample names from the filenames, and this is much less prone to error.

**Comment by Danyang1111** [comment]
Thanks for your reply. That's helpful.
I followed your advise to skip the name step and the following step moved smoothly.
I am now in the last step:Assign taxonomy.
I downloaded the general released data and renamed as fungaldatabase.
unite.ref <- "/home/dh23063/fungaldatabase.tgz"
>  taxa <- assignTaxonomy(seqtab.nochim, unite.ref, multithread=TRUE, tryRC = TRUE)
Error in .Call2("fasta_index", filexp_list, nrec, skip, seek.first.rec,  :
  reading FASTA file /home/dh23063/fungaldatabase.tgz: ">" expected at beginning of line 1
Why is that? What should I do?
________________________________

**Comment by benjjneb** [comment]
I'm not sure that the ShortRead package (which dada2 uses to read in fastq files) understand .tgz format. Try decompressing the file first.
