### ISSUE TITLE
Demultiplex error

### ISSUE THREAD

**Issue by Hellomissgabby** [benjjneb/dada2#1888]
Hi, I'm still relatively new to R and I'm struggling to get my files to demultiplex. 
path <-("C:/Users/andring/Documents/spring_data_research")
setwd(path)
file_paths <- as.character(list.files(path, full.names = TRUE))
trunc_len <- c(200,200)
trunc_q <- 2
max_n <- 0 
max_ee <- c(2,2)
filtered_data <- filterAndTrim(file_paths, truncLen = trunc_len , truncQ = trunc_q, 
                               maxN = max_n, maxEE = max_ee, filt = c(TRUE, TRUE))
Error in filterAndTrim(file_path, truncLen = trunc_len, truncQ = trunc_q,  : 
  File paths must be provided as character vectors.

I keep getting this error and can't figure out how to fix it. Anything helps!

**Comment by adrientaudiere** [comment]
Hi @Hellomissgabby, 
Can you give the result of the command: 

```{r}
file_paths
```

**Comment by Hellomissgabby** [comment]
@adrientaudiere it returns the name of the path.

**Comment by benjjneb** [comment]
@Hellomissgabby 
First a note, what you are doing here is filtering and trimming the sequencing data, not demultiplexing (which is the separation of data from the sequencer into per-sample fastq files).

`filterAndTrim` has two required arguments, the file paths of the files you want to filter, and file paths to the new location to which the filtered fastq files should be written. You haven't provided that second set of file paths. See [the  dada2 tutorial](https://benjjneb.github.io/dada2/tutorial.html) for an example, and you can always look at the documentation for any R function via `?filterAndTrim`.

**Comment by Hellomissgabby** [comment]
@benjjneb 
What approach would be appropriate to demultiplex in R. I'm struggling to follow the tutorial for the demultiplexing aspect.

**Comment by benjjneb** [comment]
I don't know of any functionality in R for demultiplexing. Are you sure you need it? Typically sequencing data these days is already demultplexed into per-sample fastq files. You just have one big fastq files with multiple samples in it?

See the first question on [the dada2 FAQ](https://benjjneb.github.io/dada2/faq.html) for some demultiplexing suggestions.

**Comment by Hellomissgabby** [comment]
@benjjneb I multiple files but some of my files are really large and when I do the Dada2 procedure it tells me that some of my forwards and reverses don't match in length. So my assumption was that they still needed to be demultiplex in order to make the length of them shorter.
