### ISSUE TITLE
Readcounts in plotQualityProfile 

### ISSUE THREAD

**Issue by gblanchard4** [benjjneb/dada2#189]
Should the `plotQualityProfile` have an option to include readcounts on the plot? 

I ran into an issue where I had a sample that looked really noisy when trying choose my filtering parameters. It turns out it was just low readcounts. I have a branch with a kwarg `readcounts` that will add the readcounts under the sample name. 
![readcount](https://cloud.githubusercontent.com/assets/1793818/22844646/f016b0ee-efa4-11e6-882f-2b4be524e2b9.png)

**Comment by benjjneb** [comment]
Yeah that could be useful. I wouldn't bother making an argument for it though, just add the "22 Reads" in somewhere, maybe even on the y-axis label? "Quality Score (n=22)"?

**Comment by benjjneb** [comment]
Added in 7cae992469ae7d6d83742983bb5b42bd5877d613 thanks to @gblanchard4
