### ISSUE TITLE
ASVs are assigned different when using SILVA 138.1 database versus using NCBI blast

### ISSUE THREAD

**Issue by MadsBjornsen** [benjjneb/dada2#1895]
Hi,

I have come into an issue regarding the classification of ASVs.
My dataset comprises Ilumina MiSeq 16S rRNA V3-V4 region microbial samples from different places in the gastrointestinal tract of a wild bird species. Interestingly, I found about 20 ASVs assigned to the Helicobacter genera and wanted to see if I could find out what species it was if I did a BLAST through NCBI. However, when I did that, only one ASV was identified as Helicobacter, whereas the others were identified as Acinobacter 99.77%, Flavonifractor 93.61%, Staphylococcus 100%, and others. 

Do you guys have an idea where the error could be?

**Comment by benjjneb** [comment]
Blasting against NCBI-nt or rrn is using a different database and method, so some differences in results are to be expected. But having *Helicobacter* be assigned by `assignTaxonomy` when the ASV is a 100\% match to *Staphylococcus* is unusual.

What is the exact command you are using to `assignTaxonomy`?
Is there any re-arranging of the taxonomy table of ASV table in R that might be breaking the concordance between the ASVs and the taxonomic assignments?

Making a simplified example could also be helpful. Like, define a variable that contains that one ASV that is Helico/Staph and the `assignTaxonomy` command, so that the whole observation could be reproduced by someone else.

**Comment by MadsBjornsen** [comment]
Thank you for the response!

I am using this command:
#Assign Taxanomy
taxa_Com <- assignTaxonomy(seqtab.nochim_Com, "silva_nr99_v138.1_train_set.fa.gz", tryRC=T, multithread=TRUE)
taxa_Com <- addSpecies(taxa_Com,"silva_species_assignment_v138.1.fa.gz",tryRC=T, verbose=TRUE)

#giving to seq headers more manageable names (ASV_1, ASV_2...)
asv_seqs <- colnames(seqtab.nochim_Com)
asv_headers <- vector(dim(seqtab.nochim_Com)[2], mode="character")

for (i in 1:dim(seqtab.nochim_Com)[2]) {
  asv_headers[i] <- paste(">ASV", i, sep="_")}

#making and writing out a fasta of our final ASV seqs:
asv_fasta <- c(rbind(asv_headers, asv_seqs))
write(asv_fasta, "ASVs_Com_v2.fa")

#tax table:
asv_tax <- taxa_Com
row.names(asv_tax) <- sub(">", "", asv_headers)
write.table(asv_tax, "ASVs_taxonomy_species_Com_v2.tsv", sep="\t", quote=F, col.names=NA)

**Comment by benjjneb** [comment]
Can you pull out and post the ASV sequence that is being assigned as *Helicobacter* by `assignTaxonomy` but is 100% hit to *Staphylococcus* in BLAST? Any other good examples also welcome.

**Comment by benjjneb** [comment]
For ASV298, I get the following:

```
sq298 <- "TAGGGAATCTTCCGCAATGGGCGAAAGCCTGACGGAGCAACGCCGCGTGAGTGATGAAGGTCTTCGGATCGTAAAACTCTGTTATTAGGGAAGAACAAATGTGTAAGTAACTATGCACGTCTTGACGGCACCTAATCAGAAAGCCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGCGCGCGTAGGCGGTTTTTTAAGTCTGATGTGAAAGCCCACGGCTCAACCGTGGAGGGTCATTGGAAACTGGAAAACTTGAGTGCAGAAGAGGAAAGTGGAATTCCATGTGTAGCGGTGAAATGCGCAGAGATATGGAGGAACACCAGTGGCGAAGGCGACTTTCTGGTCTGTAACTGACGCTGATGTGCGAAAGCGTGGGGATCAAACAGG"
tax <- assignTaxonomy(sq298, "~/tax/silva_nr99_v138.1_train_set.fa.gz")
unname(tax)
```

>    [,1]       [,2]         [,3]      [,4]               [,5]                [,6]            
> [1,] "Bacteria" "Firmicutes" "Bacilli" "Staphylococcales" "Staphylococcaceae" "Staphylococcus"

This matches the BLAST result. The Comamonas ASV also is assigned Comamonas by `assignTaxonomy`.  Is the match between taxonomic assignments and ASVs getting lost at some step in your code, maybe by an unexpected re-ordering?

**Comment by MadsBjornsen** [comment]
That might be the reason, is there a quick way to check for that?

**Comment by benjjneb** [comment]
We just did check, and the check failed?

Within the dada2 R package, this is the reason why we carry through the ASV sequences into output objects, even though they are annoying to print to the screen. Maybe that could be added to your code?

**Comment by MadsBjornsen** [comment]
That make sense.
My code looks like this from assigning taxa to writing files:

#Assign Taxanomy
taxa_Com <- assignTaxonomy(seqtab.nochim_Com, "silva_nr99_v138.1_train_set.fa.gz", tryRC=T, multithread=TRUE)
taxa_Com <- addSpecies(taxa_Com,"silva_species_assignment_v138.1.fa.gz",tryRC=T, verbose=TRUE)
saveRDS(taxa_Com, "taxa_combined.RData")

#Inspect the taxonomic assignments:
taxa_Com.print <- taxa_Com # Removing sequence rownames for display only
rownames(taxa_Com.print) <- NULL
head(taxa_Com.print)

#Extracting the standard goods from DADA2
#Write out tables for further processing}
#giving to seq headers more manageable names (ASV_1, ASV_2...)
asv_seqs <- colnames(seqtab.nochim_Com)
asv_headers <- vector(dim(seqtab.nochim_Com)[2], mode="character")

for (i in 1:dim(seqtab.nochim_Com)[2]) {
  asv_headers[i] <- paste(">ASV", i, sep="_")}

#making and writing out a fasta of our final ASV seqs:
asv_fasta <- c(rbind(asv_headers, asv_seqs))
write(asv_fasta, "ASVs_Com_v2.fa")

#count table:
asv_tab <- t(seqtab.nochim_Com)
row.names(asv_tab) <- sub(">", "", asv_headers)
write.table(asv_tab, "ASVs_counts_Com_v2.tsv", sep="\t", quote=F, col.names=NA)

#tax table:
asv_tax <- taxa_Com
row.names(asv_tax) <- sub(">", "", asv_headers)
write.table(asv_tax, "ASVs_taxonomy_species_Com_v2.tsv", sep="\t", quote=F, col.names=NA)

And sorry for asking again, but just want to be sure.
Would you proceed without naming them ASV1, ASV2 etc then just keep the ASV sequence for the further processing instead. 

And thank you so much for the help and quick response!

**Comment by benjjneb** [comment]
A code comment, you re-assign the asv "names" three different times. I don't immediately see where the different orderings are happening, but that is a foreseeable problem from that kind of code. When setting an ID variable, it should happen once in the code.

> Would you proceed without naming them ASV1, ASV2 etc then just keep the ASV sequence for the further processing instead.

We did it that way in the dada2 R package for a reason.

**Comment by MadsBjornsen** [comment]
That make sense, once again thank you for the feedback. I will do my analysis again, but this time without assigning them ASV1 etc. 

It is a code I have recieved from someone else, so will advise them to recheck their work too. 

Best,
Mads
