### ISSUE TITLE
truncQ and maxEE - Archaea 16s V3-V5

### ISSUE THREAD

**Issue by luigallucci** [benjjneb/dada2#1896]
Hi there!

I'm working with bacteria and archaea 16S (MiSeq sequencing).

More in specific I'm dealing now with the Archaea one (V3-V5) region. 

I was reading different issues (both open and closed) about truncQ quality and I want to address the following question:

1) when use truncQ or not at all? in the latter case, is ok to rely only on maxEE?

2) I'm dealing with filter and trim step with the following set:

`out <- filterAndTrim(
    fwd = file.path(pathF, fastqFs),
    filt = file.path(filtpathF, fastqFs),
    rev = file.path(pathR, fastqRs),
    filt.rev = file.path(filtpathR, fastqRs),
    truncLen = c(255, 235),
    maxEE = c(2,4),
    truncQ = 1,
    maxN = 0,
    rm.phix = TRUE,
    compress = TRUE,
    verbose = TRUE,
    multithread = parallel::detectCores() 
  )`

and output
`[1] 0.5686554
               reads.in reads.out
3_R1.fastq.gz    143071    104526
30_R1.fastq.gz   196103    116851
31_R1.fastq.gz   166056    102550
32_R1.fastq.gz   124818     76052
33_R1.fastq.gz   124614     74477
34_R1.fastq.gz   207634    115110`

The amplified region is supposed to be around 540-550, but the quality scores of the reverse sequences is leading to a wide trim of those. What I notice, is that increasing the x value for c(x,235) is leading to a major loss of reads, decreasing is leading to an increase of reads out from trim. If I understood correctly this is due to truncQ=2, linked to my previous question. What you can suggest to improve the yield after the trim?

**Comment by benjjneb** [comment]
> when use truncQ or not at all? in the latter case, is ok to rely only on maxEE?

We do not recommend using `truncQ`. `maxEE` is preferred and sufficient on its own for read quality filtering.

> What I notice, is that increasing the x value for c(x,235) is leading to a major loss of reads, decreasing is leading to an increase of reads out from trim. If I understood correctly this is due to truncQ=2, linked to my previous question.

Probably not related to `truncQ` but rather to `maxEE`. As you are keeping a longer portion of the lower quality tail, the expected errors (which is calculated over the whole read after trimming) is increasing, and then being removed by the `maxEE` filter.

> What you can suggest to improve the yield after the trim?

You can relax `maxEE` some, but I'd also think about whether improving yield through `filterAndTrim` is actually something you want to focus on. In the end, the total number of reads doesn't matter, as the parameters we are measuring are relative abundances. If you keep more reads, but they are worse quality, could you be ending up with worse measurements of the relative abundance (e.g. proportions) at the end?

**Comment by luisymbio** [comment]
@benjjneb thank you for your reply!

Yes, of course. So, improving `filterandTrim` giving a look to the quality Plot is your suggestion, as I understood well, right? 
About that, if my targeted region is wide, is that a problem if the `truncLen` sum are less than the targeted? Probably archaea, as more person told me, as a lower yield if compared to bacteria at the end in number of reads. 

About `truncQ`, so you suggest to set it as `truncQ=0`?

**Comment by luisymbio** [comment]
Yes, this is what I'm finding after the merging. 

So, ideally, the solution will be to not giving so much importance at the percentage after the `filterandTrim` but rely more on quality plot and the targeted region lenght, if I understood correctly.

**Comment by benjjneb** [comment]
> So, ideally, the solution will be to not giving so much importance at the percentage after the filterandTrim but rely more on quality plot and the targeted region lenght, if I understood correctly.

Sounds right to me.

**Comment by luisymbio** [comment]
Hi @benjjneb,

adjusting a little bit the code, and with the following setting:

```
out <- filterAndTrim(
    fwd = file.path(pathF, fastqFs),
    filt = file.path(filtpathF, fastqFs),
    rev = file.path(pathR, fastqRs),
    filt.rev = file.path(filtpathR, fastqRs),
    truncLen = c(280, 230),
    maxEE = c(3,5),
    maxN = 0,
    truncQ = 0,
    rm.phix = TRUE,
    compress = TRUE,
    verbose = TRUE,
    multithread = parallel::detectCores() 
  )
```

I'm able to get a nice 60% of reads up to the merging point...while the things changes at the chimeric step. 

With this `truncLen` set, I'm able to hit the right targeted region length (with a peak at 510) but after chimeric removal, my reads drop to a value among 1-11%. Do you have an opinion about why that could happen? If informations are missing feel free to ask, I'm sorry but is my first time working with Archaea. I know that the peak is at that length (~510 bp).

**Comment by luisymbio** [comment]
Set for chimeric removal:

`seqtab.nochim <- removeBimeraDenovo(seqtab, minFoldParentOverAbundance = 8, method="consensus", multithread= parallel::detectCores(), verbose=TRUE)`

**Comment by benjjneb** [comment]
> With this truncLen set, I'm able to hit the right targeted region length (with a peak at 510) but after chimeric removal, my reads drop to a value among 1-11%. Do you have an opinion about why that could happen? If informations are missing feel free to ask, I'm sorry but is my first time working with Archaea. I know that the peak is at that length (~510 bp).

You are truncating your reads too much and they are failing to merge as a result.

By default `mergePairs` requires 20 nucleotides of overlap between forward and reverse reads. So, if your amplicon is 510 nts, the total length of the forward and reverse reads must be >= 530 in order to be successfully merged. But that doesnt account for biological length variation -- some archaea will have longer or shorter amplified regions. In the 16S gene this length variation is not massive, but it can be impactful (a well known example is the 20nt variation in the V3-V4 region in bacteria).

**Comment by luisymbio** [comment]
I agree with that, so I changed the clipping values to `truncLen = c(280, 260)`.

The problem at the base is that the reverse quality is really bad, coupled with the length that I need...this doesn't allow me to have a big spaces for improvement if I'm correct. Now at the end I have a recover of reads among 29-45 % with most of them under 40%. Do you think that reducing `mergePairs` value to 12 nucleotides, could a be good move or is better to stay on this value? Do you have other suggestions? Thank you for your patience.

**Comment by benjjneb** [comment]
Reducing to `minOverlap=12` should be fine, but that is a minor modification.

Something to consider, if your reverse reads are the impediment here, is using the higher quality forward reads alone. More but lower quality data often isn't helpful. This depends on your specific study aims, but given your amplicon design which has very little overlap, the reverse reads are not adding anything in terms of error-correction, and may be coming at a significant detriment to accurate ASV identification, especially for lower abundance ASVs. Using forward reads alone could be preferable.
