### ISSUE TITLE
learnErrors DADA2

### ISSUE THREAD

**Issue by rosauraalfaro** [benjjneb/dada2#1897]
I'm working with 16S amplicon sequences from rhizosphere soil and to process my data I'm using the DADA2 version 1.30.0 pipeline in R.

When calculating the error rate of my reverse sequences with the learnErrors function, which is a step before calculating the ASVs, I get the error message on the image. 

![Error](https://github.com/benjjneb/dada2/assets/157749962/954032e5-4896-4fb5-be8b-86e2d07d46ae)

With my forward sequences I didn't have this problem and I have already been able to calculate the error rates.

These images are of the quality of my reverse sequences.

![000010](https://github.com/benjjneb/dada2/assets/157749962/d2a7395e-832e-4d4c-b3ce-f46e394d164e)
![000012](https://github.com/benjjneb/dada2/assets/157749962/4ad3b166-edaf-4eab-85c6-54c966b75030)

**Comment by benjjneb** [comment]
Can you show the output of `plotErrors` for your forward read error model?

And can you also provide a `plotQualityProfile` for the forward reads, so we can compare that to what you showed above for the reverse reads that aren't working.

**Comment by rosauraalfaro** [comment]
Hi! thanks for you reply, I'll answer to your questions.

> Can you show the output of `plotErrors` for your forward read error model?

>
![plotError_Fwd](https://github.com/benjjneb/dada2/assets/157749962/9773d934-69b5-43c6-9ba9-195ed1703d5a)
 

> And can you also provide a `plotQualityProfile` for the forward reads, so we can compare that to what you showed above for the reverse reads that aren't working.

>
![plotQualityProfile_FWD](https://github.com/benjjneb/dada2/assets/157749962/b0a43354-9f56-485e-9f74-7301a4758752)
![plotQualityProfile_FWD2](https://github.com/benjjneb/dada2/assets/157749962/ebccce50-c61e-4abe-94d8-39954b773bff)
 
> ps: Also, what is the specific sequencing tech you are using? And what is your `filterAndTrim` command?
The sequencing tech that we used is Illumina.
The "filterandTrim" command was: out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,200), maxEE=c(2,2), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE, maxN = c(0,0))

**Comment by benjjneb** [comment]
It's not clear to me why `learnErrors` would be working on your forward reads but not reverse.

What amplicon are you sequencing? What is the primer set? Is the primer being sequenced?
