### ISSUE TITLE
Different number of ASVs

### ISSUE THREAD

**Issue by ThibauldMichel** [benjjneb/dada2#1898]
I have been running DADA2 version 1.16.0 on a set of 95 samples using the Silva database with more Eukaryotes accession (https://zenodo.org/records/1447330). 

I have noticed that the number of ASVs produced with slightly different scripts (script_DADA2.R and script_DADA2.Rmd) and even with identical script vary from one run to the other. Here is the number of ASVs produced during four runs:
Exp1    Script_DADA2_1.R     6338
Exp2    Script_DADA2_1.R     6651
Exp3    Script_DADA2_2.Rmd     6837
Exp4    Script_DADA2_2.Rmd     6841

My hypothesis to explain this variable number of ASV would be that the random sampling in the error-learning part of the pipeline cause variability in the results, but I am not sure if it is correct. Is it something that has been observed before?
[script_DADA2_1.zip](https://github.com/benjjneb/dada2/files/14464163/script_DADA2_1.zip)
[script_DADA2_2.zip](https://github.com/benjjneb/dada2/files/14464164/script_DADA2_2.zip)

**Comment by benjjneb** [comment]
Can you say a bit more about what the "slight differences" in the scripts are?

The difference in numbers of ASVs looks quite modest -- numbers of ASVs is a metric highly sensitive to the rarest and least prevalent ASVs, which are the most difficult to correctly ID and the most affected by even small parameter choices, but also the least important in most analyses.

**Comment by ThibauldMichel** [comment]
The two scripts are only different for one is written only in R code, the other in R markdown. Also the processing of the output are a bit different in the R markdown script, just to make nice tables to summarize the run at the end.
Eventually, there is no difference in the way the data are processed between the two scripts and the parameters are the same, so I was expecting the same results.

You mention that the number of ASVs is sensitive to small parameter choices. Is it likely that this number differ for two runs with strictly identical parameters?

**Comment by benjjneb** [comment]
If there is no difference, then you should be able to force identical outputs (aside from `assignTaxonomy` results) by setting the random number seed at the start of the script. `set.seed(100)` (or whatever number you want to pick).
