### ISSUE TITLE
Method to get sequences that fail denoising?

### ISSUE THREAD

**Issue by cjfields** [benjjneb/dada2#1899]
Just a general question.  We're testing using DADA2 for PacBio amplicon data to compare it with other methods for allele and copy number analysis.  During troubleshooting I did find there was a large read dropout (50% or more) during `dada` denoising with a handful of samples.  I wanted to check which reads these may belong to so we can see what is being dropped (pretty sure it's OMEGA_C), but I didn't see an easy way to get the original sequence that was dropped.  Is this possible?

(as an aside: this _almost_ works but I suspect there may be amplicon issues in this case, which is one reason I'd like to check the sequence data)

**Comment by benjjneb** [comment]
Read-fate tracking is there up through denoising, but requires a bit of custom R code to actually implement.

The key is the `$map` vectors recorded in `dada-class` and `derep-class` objects, as described here https://github.com/benjjneb/dada2/issues/354#issuecomment-339662233

> `derepFastq`: The output of this function contains the $map of each read to the index of its corresponding dereplicated unique sequences.
> 
> `dada`: The output of this function contains a $map of each input dereplicated unique sequence to the index of its correponding denoised sequence variant.

When unique sequences fail denoising, they get a corresponding `$map` value of NA, so by tracing back the NAs in the output of denoising, they can be linked back to the set of reads.

`help("derep-class")` and `help("dada-class")` have a bit more information about the `$map` vectors. But this functionality is not wrapped up nicely, so I'm happy to assist further.

**Comment by cjfields** [comment]
Thx @benjjneb , I can have a look to see if I can sus it out.
