### ISSUE TITLE
adapters 16s

### ISSUE THREAD

**Issue by murheisa** [benjjneb/dada2#1904]
Hello, I´m working with some 16S  v3-v4 sequences with Miseq 300pb, 200k reads per library. The sequencing service says they do not process de sequences for adapter removal. I checked with fastqc and apparently there are no adapters (Nextera), and after dada2, I checked for primer removal and indeed the primer was removed, but what about the adapters? One of my samples appear to have too many ASVs and overrepresented sequences with no hit in fastqc, so I thought that could be the adapter even if it does not appear in fastqc. Also in that sample, half of the reads were removed as chimeras, and still has a lot of ASVs.
I tried trimmomatic to remove adapters in case there where but I'm not sure if it makes sense to do it.
 I don't know how to proceed, please help. 

These are the parameters I used for filter and trim :
filterAndTrim(fnFs,filtFs,fnRs,filtRs,
truncLen=c(270,210),maxN=0,trimLeft=c(10,10), maxEE=c(2,2), truncQ=2, rm.phix=TRUE,compress=TRUE, multithread=TRUE) # 

[rarf_2.pdf](https://github.com/benjjneb/dada2/files/14504586/rarf_2.pdf)
<img width="1514" alt="Captura de pantalla 2024-03-04 a la(s) 16 44 33" src="https://github.com/benjjneb/dada2/assets/145282851/ef25141f-79d2-4a9c-bc38-e92bace8a9c5">
[rarf_2.pdf](https://github.com/benjjneb/dada2/files/14504054/rarf_2.pdf)
<img width="1497" alt="Captura de pantalla 2024-03-05 a la(s) 17 30 42" src="https://github.com/benjjneb/dada2/assets/145282851/f5908cb6-e01e-49af-afb7-7cf3a506c387">

**Comment by benjjneb** [comment]
The most common V3V4 library prep sequences the primers. Unremoved primers are the reason for very high chiimera removal later on in 9/10 or more cases.

If you go back to your raw reads, before any fastqc or trimmomatic, and open one up in a text editor -- do you see the primers at the start of the reads? If so, removing them will probably fix your issue, and the recommended way to remove them is to use `filterAndTrim(..., trimLeft=c(FWD_PRIM_LEN, REV_PRIM_LEN, ...)`.

**Comment by murheisa** [comment]
Before DADA2 and trimmomatico the primer does appear, after dada2 (without trimmomatic), the primer isn´t there anymore, so the primers are gone, what about the adapters? I thought about using trimmomatic for the adapters but the adapters are not present according to fastqc, even tough the macron says they didn't removed them.

**Comment by benjjneb** [comment]
To restate, when primers are at the start of the read and a constant length, we don't recommend using trimmomatic (or other external software), our recommendation is to use `filterAndTrim(..., trimLeft=c(FWD_PRIM_LEN, REV_PRIM_LEN, ...)`.

> what about the adapters?

In almost all amplicon library preparations I'm familiar with, the adapters are before the primers on the DNA molecules that go on the sequencer, so if you've removed the primers, there isn't any adapter in the reads.

**Comment by murheisa** [comment]
I have used DADA2 with raw sequences, and the primers are gone after filterAndTrim, but not the nextera adapters.

These are the parameters I used for filter and trim :
filterAndTrim(fnFs,filtFs,fnRs,filtRs,
truncLen=c(270,210),maxN=0,trimLeft=c(10,10), maxEE=c(2,2), truncQ=2, rm.phix=TRUE,compress=TRUE, multithread=TRUE) 

<img width="689" alt="Captura de pantalla 2024-03-07 a la(s) 14 34 28" src="https://github.com/benjjneb/dada2/assets/145282851/d0964d61-fa4e-4b3a-a8e7-c1151f047f1b">

**Comment by benjjneb** [comment]
You shouldn't be reading into the adapters in V3V4 amplicons at all here, as the sequenced region is 400+ nts. My guess is that the adapter content you are seeing is due to off-target amplification of some shorter gene region, maybe from mito/chloroplast or eukaryotic genomes in the sample, or possibly incomplete PCR fragments.

I would probably check on the fraction of sequences the Nextera adapter is detect across your sampled to get a handle on how big a problem this is. If it's mostly in just a few samples, and at low abundances in most, then you can use trimmomatic to truncate reads at the point that the adapter is detected, or possibly even just completely toss sequences with adapters detected.
