### ISSUE TITLE
related to issue #132

### ISSUE THREAD

**Issue by tobiasgf** [benjjneb/dada2#191]
I tried to reopen #132, but couldn't. So this is a doublicate of my last post on that closes issue, sorry.

My problem:
I try to filter (pair) paired reads in R1/R2 files using this command:

for(i in seq_along(fnFs)) {
  fastqPairedFilter(c(fnFs[i], fnRs[i]), c(filtFs[i], filtRs[i]),
                    matchIDs=TRUE)
}

When I do that I often get an error:

Calls: fastqPairedFilter -> [
In addition: Warning messages:
1: In max(which(idsF %in% idsR)) :
  no non-missing arguments to max; returning -Inf
2: In max(which(idsR %in% idsF)) :
  no non-missing arguments to max; returning -Inf
Execution halted
I think I have found out that this is happening when I try to process R1/R2 files with no matching reads. This will often be the case for controls and samples with very few reads. I can of course avoid the error by deleting those files beforehand, but they (R1/R2 with no matching reads) are difficult to spot as the files are not empty.

Is there some way to run the pairing command without stopping on encountering R1/R2 with no matches? (Or maybe a way to identify and exclude those before?)

Kind regards
Tobias

**Comment by benjjneb** [comment]
Fixed the edge case of zero matched IDs in 864f20fb396caeaf4236acd0e8cd32ba1718220e

Should work gracefully (no errors, no output files) with that new version.
