### ISSUE TITLE
depreciated function in plotQualityProfile

### ISSUE THREAD

**Issue by brikw** [benjjneb/dada2#1910]
Hi,
There is a consistent warning coming from the plotQualityProfile function in DADA2. I believe it relates to the underlying changes to ggplot2 package in recent years, with needing to include guides(colour == 'none') not FALSE (insert for colour: linetype, fill, shape, etc).

Here is the warning message.

The `<scale>` argument of `guides()` cannot be `FALSE`. Use "none" instead as of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the dada2 package.
  Please report the issue at <https://github.com/benjjneb/dada2/issues>.

thanks!

**Comment by benjjneb** [comment]
This has been fixed in the current version of DADA2: https://github.com/benjjneb/dada2/commit/b6ab04f50988e91796453887bd15889f81ee99cb
