### ISSUE TITLE
Reporting Pipeline Stats for all samples(not just first 6)

### ISSUE THREAD

**Issue by okortenkamp** [benjjneb/dada2#1912]
So I am working on some AMPLICON sequences but we are having a problem with the quality of some of the DNA extractions mostly based on A260/A230 spec ratios. I am trying to see if bad DNA extraction quality at all correlates with poor # of reads. After running the DADA2 pipeline I am reporting the stats for input, filtered, denoising, merge, and non-chim however I cannot figure out how to get these statistics for all 50 samples I have in this set. My code and all the tutorial codes online only report the first 6 samples. I have pasted my code below, if anyone knows what I have to change to get the pipeline stats for all 50 samples please reply below.

getN <- function(x) sum(getUniques(x))
track <- cbind(out, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers, getN), rowSums(seqtab.nochim))
colnames(track) <- c("input", "filtered", "denoisedF", "denoisedR", "merged", "nonchim")
rownames(track) <- sample.names
head(track)

**Comment by benjjneb** [comment]
The `head` command reports the first `n` entries or rows of the object, with `n=6` by default. Drop the `head` and the whole table will be displayed. I.e. just enter `track` instead.
