### ISSUE TITLE
TrnL misassignement using assignTaxonomy with custom database

### ISSUE THREAD

**Issue by SarahP4** [benjjneb/dada2#1913]
Hi Ben!

I am using assignTaxonomy for trnL sequences with a custom database. We are currently working on getting the databse to work properly, so I used a test version with only three sequences with the taxonomy identification to see if the code worked. The test database looks like this:

>Viridiplantae;Streptophyta;Magnoliopsida;Asparagales;Orchidaceae;Lyperanthus;Lyperanthus suaveolens
AACAATCGGTAGACGCTACGGACTTGATTGGATTGAGCCTTGGTATG...
>Viridiplantae;Streptophyta;Magnoliopsida;Gentianales;Rubiaceae;Feretia;Feretia apodanthera
AGAAATCGGTAGACGCTACGGACTTAATTGAATTGAGCCTTGGTATG...
>Viridiplantae;Streptophyta;Magnoliopsida;Malpighiales;Violaceae;Viola;Viola reichenbachiana
AGAGGGACTTGAACCCTCACGATTTAAAAAGTCGACGGATTTTCCTC...

It worked, but the problem is, it assigned every single sequence in my samples to one of the three sequences in the database. Some were even assigned to the species. I verified one of those with blast on NCBI and it was completely wrong. 

Here is the code: `taxaTrnL <- assignTaxonomy(seqtab.nochimTrnL,"databaseTest.fa", multithread = TRUE)`

I have tried this way as well: `taxaTrnL <- assignTaxonomy(seqtab.nochimTrnL,"databaseTest.fa", multithread = TRUE, tryRC = TRUE)`, but it doesn't change much, if anything.

I also had this problem previously with a different custom databse for trnL sequences, which is why we are working on a new one that hase more sequences now.

Do you know why it would do this and how to fix it?
Any help is appreciated!

**Comment by benjjneb** [comment]
`assignTaxonomy` is a re-implementation of a long-standing algorithm in the field, the naive Bayesian classifier: https://doi.org/10.1128/AEM.00062-07

The behavior you are seeing is a known potential weakness of this method. The method starts by finding a best match in the database, and then subsets the query sequence to check if those subsets also find the same best match. If those subsets find the same best match (at the taxonomic level) at a high enough percentage, then assignment is made. There is no check for overall sequence similarity to the best match, just relative similarity via the above approach.

In your 3-sequence database, there are no other competing sequences for the subsets to potentially match, thus everything is getting assigned even though the queries barely resemble the reference. In practice, the database is critically important for effectively using `assignTaxonomy` -- the database should be complete enough to provide "outgroups" that can attract the query subsets to prevent this kind of spurious taxonomic assignment.

If working with a very limited set of references, a different approach might be warranted. `IdTaxa` in the DECIPHER package is one such approach.

**Comment by SarahP4** [comment]
Thank you for your answer!

I tried with my full trnL database, that has 18,958 sequences. It was made from NCBI sequences.
I tested some of the sequences from my samples by BLASTing them on the NCBI website, but for most of my tests, the taxonomy given by assignTaxonomy was wrong up to the Class level.

I wanted to try DECIPHER, but there does not seem to have a training set for trnL sequences. I have only found them for 18S, 16S and ITS.

**Comment by benjjneb** [comment]
Yes, for DECIPHER you would have to build your own trnL training object for the `IdTaxa` command. This functionality is included in the DECIPHER R package, but I personally am not familiar with it. The creator of DECIPHER is @digitalwright (Eric Wright at Pitt) who might have some insight, but the best place to start would be the documentation for IdTaxa and friends.

**Comment by digitalwright** [comment]
Indeed, this is the predominant failure mode addressed by IDTAXA. That is, reference sequence databases are rarely comprehensive. Even for the 16S rRNA gene, there are typically sequences in a sample that are unrepresented by a labeled sequence in the training set. In these cases most classifiers will assign taxonomy with too high of confidence. This failure mode is typically called "over classification," and you can see in the IDTAXA paper how prevalent it is in typical datasets.

Your three reference sequence case is an extreme example for its unusually small size. It is probably best to simply align to each of the three sequences and set a similarity cutoff. You could also try IDTAXA – it should work fine but probably isn't worth the effort to compare with only three sequences. I recommend adding more reference sequences if possible.
