### ISSUE TITLE
Error: Memory allocation failed.

### ISSUE THREAD

**Issue by acosta91** [benjjneb/dada2#1914]
Good day, I hope you are all well.

I'm opening this issue because I'm encountering the error "Error: Memory allocation failed." when running the following dada2 command:

`taxa <- assignTaxonomy(seqtab.nochim, "UNITE_public_25.07.2023.fasta", multithread=TRUE)`
Despite finding several threads about similar issues, I couldn't find a solution.

My initial R and F fastq files weigh around 100MB each
The database weighs around 4.24GB.

Here are some values from my sample (which is a single sample):

```
input filtered denoisedF denoisedR merged nonchim
N1 203675 192741 192455 191723 187832 185189
```

table(nchar(getSequences(seqtab)))

```
55 58 83 98 103 105 106 107 111 116 154 156 159 186 200 201 208 214 222 260 266 268 269 278 280 
1 1 1 6 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 
286 289 291 292 294 295 296 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 314 315 316 
1 1 2 3 2 4 4 4 1 55 1 2 3 2 1 2 3 7 1 7 4 2 3 4 1 
317 318 319 320 321 324 325 327 328 329 330 331 333 334 335 336 338 339 340 341 342 344 345 346 347 
5 1 1 2 3 2 1 1 1 2 1 1 1 1 1 1 4 2 1 1 1 1 2 1 1 
348 349 350 351 352 353 354 357 358 359 360 361 363 365 371 372 373 375 377 378 381 382 391 393 396 
2 1 1 2 1 1 1 3 1 1 1 1 1 1 1 3 2 1 1 1 3 17 1 2 1 
399 400 404 406 414 425 
3 1 4 1 1 2 

```

seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=FALSE, verbose=TRUE)
Identified 56 bimeras out of 253 input sequences.

```
dim(seqtab.nochim)
[1] 1 197
```

I've tried this on two different computers, one with 32GB of RAM and the other more powerful one with 220GB of RAM, but encountered exactly the same error.

Any assistance would be appreciated.

**Comment by acosta91** [comment]
Interestingly, the error occurs even though there is plenty of available RAM. Attached image
![Memory allocation failed](https://github.com/benjjneb/dada2/assets/66858561/5923dc49-caa1-4f51-8462-4485992cf47d)

**Comment by MargaGF** [comment]
Hi!!

I am having the same issue, with the latest version of UNITE for all eucaryotes (https://doi.plutof.ut.ee/doi/10.15156/BIO/2959331). My computer has 16GB RAM. I tryed to do the whole process with only 2 samples (four fastq files). Could it be due to my RAM memory?

Cheers,

**Comment by benjjneb** [comment]
From [the UNITE resources page](https://unite.ut.ee/repository.php) you should be using the "General FASTA release" section of files which contain representative sequences. I believe you've downloaded the "Full "UNITE+INSD" dataset" file, which is too large to use with `assignTaxonomy`.

**Comment by MargaGF** [comment]
Hi,

I did a small test, only with four samples and it ran for over 12 hours (I had to stop it at that point so I did not see the outcome), which makes me think that something is not working. I am using the most standard procedure, and all the previous steps seem to be working. Could it be something on the code I'm using in the function:

taxa <- assignTaxonomy(seqtab.nochim, "C:/Users/Mag/Documents/GHAP/data/UNITE_public_all_21.04.2024.fasta.gz", multithread = T)

**Comment by acosta91** [comment]
The problem is not your dataset, but the database against which you are comparing your dataset. For taxonomic assignment analysis with `AssignTaxonomy`, you should use the general database available at https://unite.ut.ee/repository.php., as indicated by benjjneb. 

If I'm not mistaken, you are using the "All Eukaryotes" database. If you pay attention, you are using https://doi.plutof.ut.ee/doi/10.15156/BIO/2959331, but you should be using https://doi.plutof.ut.ee/doi/10.15156/BIO/2959334.

I hope this helps. Best regards,

**Comment by MargaGF** [comment]
Hi,

How embarrasing, I copied the old line of code. I did download the file from the link you mentioned. This is the actual code I used: 
taxa <- assignTaxonomy(seqtab.nochim, "C:/Users/Mag/Documents/GHAP/data/data_small/sh_general_release_dynamic_all_04.04.2024.fasta", multithread = T)

I apologise for that.

**Comment by benjjneb** [comment]
Might you have access to a machine with more memory? I just tested the same reference file, and on my machine (with 32GB) it ran fine, but the OS did report ~16GB of memory being allocated to the R session, so it is possible that the memory allocation is being constrained by the available memory on your machine.

**Comment by MargaGF** [comment]
Thanks for letting me know! I'll try to access a 32 GB machine :)
