### ISSUE TITLE
filterAndTrim returns error " 'names' attribute [81] must be the same length as the vector [33]" although fnFs, filtFs, fnRs and filtRs have the same length 

### ISSUE THREAD

**Issue by jorgeamaya** [benjjneb/dada2#1915]
I'm running DADA2 version 1.20.0. I'm encountering the following error upon reaching filterAndTrim()

```
Error in names(answer) <- names1 : 
  'names' attribute [81] must be the same length as the vector [33]
Calls: filterAndTrim -> mcmapply
In addition: Warning message:
In mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule,  :
  scheduled cores 2, 4, 5, 6, 8, 9, 11 did not deliver results, all values of the jobs will be affected
Execution halted

```
I verified that fnFs, filtFs, fnRs and filtRs have the same length (81 files) and they do. Interestingly, the program runs ok with certain subsets of files. So I ran the program and progressively removed files until I found an offending file. If run this file individually, it runs ok. Thus, I don't know for sure what is inside this file that is offending to the program. Has this error occurred before? If so, how to approach it?

**Comment by benjjneb** [comment]
This error has arisen before.

In https://github.com/benjjneb/dada2/issues/370 the error was resolved by fixing multithreading code on their end, and in https://github.com/benjjneb/dada2/issues/1863 the error resolved after updating the dada2 R package.

In neither case was it clear what went wrong exactly, but it seems like the first thing to try is to update dada2 and the associated package, and maybe update the parallel package as well.
