### ISSUE TITLE
too long in removing chimeras

### ISSUE THREAD

**Issue by Karelynz** [benjjneb/dada2#1916]
I've running the dada2 protocol for 20 samples, and I always have problem with the chimera removal.
I have access to a cluster, so I ask for a lot of memory and cpu, but I have a time limit (20 days) and it never finishes in that time. 
It seems that using only 1 cpu and ~18GB of memory, no matter how much memory I ask for.

In my script always multithread is True. I have already checked with the cluster people and this was their response:
"I can see from the servers you're running on, that the software is not taking advantage of the resources you've requested. I'll paste the command output below, but the summary is that you seem to be using only 1 cpu and ~18GB of memory.
You may need to check the documentation of the software you're using to see if/how you can get it to use multiple CPUs and or more memory."

#finding what nodes your jobs are on
$ squeue -u kn766
JOBID PARTITION NAME USER ST TIME NODES NODELIST(REASON)
7496952 core seq_per_ kn766 R 3-16:19:07 1 cn17
7374748 core seq_per_ kn766 R 12-14:43:58 1 cn10
7374744 core seq_per_ kn766 R 12-14:45:17 1 cn6

#checking the load; the 1.02, 1.04, 1.00 means that (over different time-period averages) you're using only 1 cpu.
$ ssh cn17 w
08:21:41 up 17 days, 23:24, 0 users, load average: 1.02, 1.04, 1.00
USER TTY FROM LOGIN@ IDLE JCPU PCPU WHAT

#Check free memory; the columns here don't format well in service now, but it shows "used" 18Gi; which is roughly the same as 18GB (it's just a difference of counting base-1000 vs base-1024.

$ ssh cn17 free -h
total used free shared buff/cache available
Mem: 250Gi 18Gi 228Gi 1.4Gi 4.2Gi 227Gi

Any suggestions on how I can improve this?

**Comment by benjjneb** [comment]
`multithread=TRUE` tries to autodetect the number of cores available, which may be failing.

First thing to try would be to set `multithread=N`, where N is the number of threads you want the program to use, and see if that successfully turns on multithreading.

It is important to note that our implementation of multithreading will only take advantage of cores/threads available on a single CPU -- it will not parallelizes across multiple distinct CPUs. But standard CPUs on a compute cluster these days have 8+ threads/cores available, and in almost all cases at least more than 1.
