### ISSUE TITLE
Need helping solving error during inserting a loop of parameters inside the filterandtrim command

### ISSUE THREAD

**Issue by akspat** [benjjneb/dada2#1923]
I am trying to insert a list of parameters for arguments of the filterAndTrim function in the DADA2 pipeline.

Here is the R script I am using:

`# Load packages`
`library(dada2)`

`# Filtering and Trimming Parameters`
`truncation_length_forward <- c(220,230, 240, 250)`
`truncation_length_reverse <- c(220,230, 240, 250)`
`maxEE_F <- c(1, 2, 3)`
`maxEE_R <- c(1, 2, 3)`
`truncQ <- c(2, 5, 10)`
`min_length <- c(200, 220, 240)`

`# Generate a data frame of all combinations`
`combinations <- expand.grid(
  truncLen = c(truncation_length_forward, truncation_length_reverse),
  maxEE = c(maxEE_F, maxEE_R),
  truncQ = truncQ,
  min_length = min_length)`

`# Get arguments passed by bash command`
`args <- commandArgs(trailingOnly=TRUE)`

`# Check if arguments are passed`
`if (length(args) == 0) {
  stop("No arguments provided yet. Please provide the index of the parameter set.")
}`

`# Define a default parameter index`
`param_index <- as.integer(args[1])`

`# Adjust the index to start from 1`
`adjusted_index <- param_index - 1`

`# Error handling for parameter selection`
`tryCatch({
  param_set <- combinations[param_index,]
}, error = function(e) {
 stop("Error selecting parameter set: ", conditionMessage(e))
})`

`#### Set path to data`
`path <- "/scratch/tmp/fastq/"`

`# Set correct filenames format for forward and reverse reads`
`fnFs <- sort(list.files(path, pattern="_trimmed_1.fastq", full.names = TRUE))`
`fnRs <- sort(list.files(path, pattern="_trimmed_2.fastq", full.names = TRUE))`

`# Extract sample names`
`sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)`

`# Iterate over each row of the combinations data frame`
 ` # Extract the arguments for this combination`
`  # Adjusted to include parameter values in the filenames`
`# filtFs and filtRs are output file paths, so removing any exisitng filtered files from previous trial runs`
    `# Proceed with filterAndTrim for this iteration`
 ` # Call filterAndTrim with these arguments`

`for (i in 1:nrow(combinations)) {
  truncLen <- combinations$truncLen[i]
  maxEE <- combinations$maxEE[i]
  truncQ <- combinations$truncQ[i]
  min_length <- combinations$min_length[i]
   filtFs <- file.path(path, "filtered", paste0(sample.names, "_", truncLen, "_", maxEE, "_", truncQ, "_", min_length, "_1_filt.fastq.gz"))
  filtRs <- file.path(path, "filtered", paste0(sample.names, "_", truncLen, "_", maxEE, "_", truncQ, "_", min_length, "_2_filt.fastq.gz"))
  
  names(filtFs) <- sample.names
  names(filtRs) <- sample.names
    
  for (j in seq_along(filtFs)) {
    if (file.exists(filtFs[j]) || file.exists(filtRs[j])) {
      file.remove(filtFs[j])
      file.remove(filtRs[j])
    }
  }
    tryCatch({
    out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=truncLen,
                         maxN=0, maxEE=maxEE, truncQ=truncQ, rm.phix=TRUE,
                         compress=TRUE, multithread=TRUE) 
  }, error = function(e) {
    stop("Error in filterAndTrim: ", conditionMessage(e))
  })
}
tryCatch({
  errF <- learnErrors(filtFs, multithread=TRUE)
  errR <- learnErrors(filtRs, multithread=TRUE)
}, error = function(e) {
  stop("Error learning error rates: ", conditionMessage(e))
})`

`out <- list("filtFs" = filtFs,
            "filtRs" = filtRs,
            "errF" = errF,
            "errR" = errR)`

`# Error handling for saving results`
`tryCatch({
  saveRDS(out, paste0("/scratch/tmp/res_mod1/", "_", param_set$truncLen, "_", param_set$maxEE, "_", param_set$truncQ, "_", param_set$min_length, ".RDS"))
}, error = function(e) {
  stop("Error saving results: ", conditionMessage(e))
})`

############################################
# The Error I am having: 

The filter removed all reads: /scratch/tmp/fastq//filtered/ERR2730212_220_1_2_200_1_filt.fastq.gz and /scratch/tmp/fastq//filtered/ERR2730212_220_1_2_200_2_filt.fastq.gz not written.
The filter removed all reads: /scratch/tmp/fastq//filtered/ERR2730254_220_1_2_200_1_filt.fastq.gz and /scratch/tmp/fastq//filtered/ERR2730254_220_1_2_200_2_filt.fastq.gz not written.
The filter removed all reads: /scratch/tmp/fastq//filtered/ERR3040011_220_1_2_200_1_filt.fastq.gz and /scratch/tmp/fastq//filtered/ERR3040011_220_1_2_200_2_filt.fastq.gz not written.
The filter removed all reads: /scratch/tmp/fastq//filtered/ERR2730340_220_1_2_200_1_filt.fastq.gz and /scratch/tmp/fastq//filtered/ERR2730340_220_1_2_200_2_filt.fastq.gz not written.

Error in value[[3L]](cond) :
  Error in filterAndTrim: These are the errors (up to 5) encountered in individual cores...
Error : UserArgumentMismatch
  file '/scratch/tmp/fastq//filtered/ERR2730148_220_1_2_200_1_filt.fastq.gz' exists, but mode is not 'a'
Error : UserArgumentMismatch
  file '/scratch/tmp/fastq//filtered/ERR2730149_220_1_2_200_1_filt.fastq.gz' exists, but mode is not 'a'
Error : UserArgumentMismatch
  file '/scratch/tmp/fastq//filtered/ERR2730150_220_1_2_200_1_filt.fastq.gz' exists, but mode is not 'a'
Error : UserArgumentMismatch
  file '/scratch/tmp/fastq//filtered/ERR2730151_220_1_2_200_1_filt.fastq.gz' exists, but mode is not 'a'
Error : UserArgumentMismatch
  file '/scratch/tmp/fastq//filtered/ERR2730152_220_1_2_200_1_filt.fastq.gz' exists, but mode is not 'a'

**Comment by benjjneb** [comment]
Error messages suggest you are running into situations where no reads passed the filter. My first guess is that some of your `filterAndTrim` argument combinations are leading to no reads passing the filter and terminating your script. `min_length` of 240 with `truncation_length_forward` of less than that are a good first guess.

Perhaps considering rewriting this script to be robust to the situation when no reads pass the filter? (those wouldn't be good parameter set choices!)
