### ISSUE TITLE
Error in add(bin) : internal: buf != <newline> in Sample Inference

### ISSUE THREAD

**Issue by Jiayonglai123** [benjjneb/dada2#1924]
Dear Prof. Ben,

I have been trying to run my Illumina Novaseq NGS V4V5 primer samples with DADA2 in R all scripts run well,
but it shows Error in add(bin) : internal: buf != <newline> when running sample inference for 
dadaRs <- dada(filtRs, err = errR, multithread = TRUE)
![image](https://github.com/benjjneb/dada2/assets/141197608/ea9fd04a-f072-46af-9c1b-3140198e458b)
the dataset encounter the same issue in #1869 , where it is unable to plot for quality, where i skip truncating.

Thanks in advance Prof Ben and team

**Comment by benjjneb** [comment]
To start, can you make this error smaller and more reproducible?
In this case I would say: Can you identify one sample that reproducibly causes this error?
We can then look more closely at that sample/file.

**Comment by Jiayonglai123** [comment]
A quick update with the error....
I tried separating the samples and run in small batches, it works
![Screenshot 2024-04-11 182258](https://github.com/benjjneb/dada2/assets/141197608/30ee8535-934c-4f2d-88df-dc30d74522fb)

it also work for plotQuality where #1869 error when run in small batches, 
![Screenshot 2024-04-11 174532](https://github.com/benjjneb/dada2/assets/141197608/34bb918c-547c-4422-8c3e-7d55eb073408)
thus solving all issues.

Thanks for the help and support,
great fan of DADA2 and Prof Ben
