### ISSUE TITLE
mergeSequenceTables - trim nt to the same length?

### ISSUE THREAD

**Issue by m-ocejo** [benjjneb/dada2#193]
Hi!!
I would like to merge two sequence tables from different runs with `mergeSequenceTables`.
From issue #95 I understand that we need to trim the sequences to the same length first, but this issue was before the function mergeSequenceTables is implemented. Do I need to perform trimming before merging the tables or does the function take this into account and automatically fix it?

Sometimes I have a sequence length distribution like this. Do you suggest trimming to the same length? Won´t we lose information?
```
table(nchar(colnames(seqtab.nochim)))

200  224  247  251  252  253  254  259  264  269  270  271  273  274  275  278  298 
  1    1    1    1  303 1475   64    1    1    2    8    4    4   11    8    1    1 
```
Thanks!

**Comment by benjjneb** [comment]
The biological variation in length you are seeing (looks like V4?) is normal. As long as you are (1) using the same primers in both runs and (2) trimmed the same during filtering for both runs, then you are OK to merge the runs using `mergeSequenceTables`.

To double-check, look at the `table(nchar...` in both tables before merging, it should look very similar (eg. strongly peaked at 253).

**Comment by m-ocejo** [comment]
Yes, you are right, it is V4 region.
Those reads of 253 length will be considered in the same columns as 252nt after merging the tables? I am asking this die to the issue #95. Should I make any corrections like you suggest there?

**Comment by benjjneb** [comment]
If you are using merged reads with the same primers and same trimming parameters, just go ahead and merge the tables. You should not do any further trimming.

If that **isn't** the case (as in #95) then it gets a bit more complicated, and you might need to truncate to a fixed length first. But it sounds like that's not a concern for you.

**Comment by m-ocejo** [comment]
OK Ben! 👍 
Many thanks!!
