### ISSUE TITLE
AIUTO file parsing 

### ISSUE THREAD

**Issue by chiaragiovannetti11111** [benjjneb/dada2#1931]
Ciao, io sto eseguendo uno script ma sono alle prime armi, quindi ho abbastanza dubbi. Quando eseguo questo comando mi si creano delle cartelle vuote => fastqfsq e fastqrsq = character(empty). cambiando anche il nome del pattern non riesco a inidivduare i miei campioni. 
# File parsing
pathF <- "reads/cutadapt" # THE DIRECTORY WITH THE FORWARD READS
pathR <- "reads/cutadapt" # THE DIRECTORY WITH THE REVERSE READS
fastqFsq <- sort(list.files(pathF, pattern="1_R1.fastq.gz", full.names=TRUE)) # ADJUST TO FIT THE FILENAMES
fastqRsq <- sort(list.files(pathR, pattern="2_R2.fastq.gz", full.names=TRUE)) # ADJUST TO FIT THE FILENAMES

**Comment by benjjneb** [comment]
Ciao. Unfortunately we only provide support in English.
