### ISSUE TITLE
Don't know if singletons are being removed or not

### ISSUE THREAD

**Issue by migfejo** [benjjneb/dada2#1934]
I have always understood that dada2 does not take singletons into account. In fact, I have verified that `DETECT_SINGLETONS == FALSE`. However, when I finish the analysis and build the phyloseq object (named `ps`), when I do `otu_table(ps)` I get many OTUs with abundance equal to 1, and only present in one of the samples. Is this not a singleton? 

I appreciate in advance your help, if anyone knows what is going on here.

**Comment by benjjneb** [comment]
Singletons can arise during the `mergePairs` step. There are no singletons in the individually denoised forward or reverse reads, but when they merge, sometimes there is a unique pair of denoised forward/reverse ASVs that passes merging and yields a singleton.

**Comment by migfejo** [comment]
Understood. In that case, I can guess that the correct decision is to keep them from this point forward, because the problematic singletons have been removed previously at denoising step. 
Thank you!
