### ISSUE TITLE
Taxonomy assignment

### ISSUE THREAD

**Issue by SRC151** [benjjneb/dada2#1938]
Hello Dr. Callahan, 
As per the instructions, I downloaded the SILVA database (training set) and placed them in the directory containing the fastq files. Ran the command line: taxa <- assignTaxonomy(seqtab.nochim, "~/tax/silva_nr_v132_train_set.fa.gz", multithread=TRUE). But it does not work. I also tried the same with SILVA version 138.1, Could you please help me out with this matter? Is there something wrong on my part?

**Comment by benjjneb** [comment]
The filepath `"~/tax/silva_nr_v132_train_set.fa.gz"` needs to be replaced with the file path to the location of the training fastq file on your computer.

Where is the downloaded silva training set file on your computer?

**Comment by SRC151** [comment]
Hello Dr. Callahan,
I replaced the "~" with the file path. It still shows an input/output error like this-

Error: Input/Output
  no input files found
  dirPath: C:/Users/rc_sa/Downloads/MiSeq_SOP/tax/silva_nr_v132_train_set.fa.gz
  pattern: character(0)

________________________________
From: Benjamin Callahan ***@***.***>
Sent: 29 April 2024 10:55
To: benjjneb/dada2 ***@***.***>
Cc: Sayantan Roy Choudhury ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [benjjneb/dada2] Taxonomy assignment (Issue #1938)


The filepath "~/tax/silva_nr_v132_train_set.fa.gz" needs to be replaced with the file path to the location of the training fastq file on your computer.

Where is the downloaded silva training set file on your computer?

**Comment by benjjneb** [comment]
What is the output of the following?

```
ref_file <- "C:/Users/rc_sa/Downloads/MiSeq_SOP/tax/silva_nr_v132_train_set.fa.gz"
file.exists(ref_file)
```

**Comment by SRC151** [comment]
Dr. Callahan,
It was a minor error I fixed it. I also ran the commands sent by you. The output is 'True'. Everything works fine. Thank you very much.
Regards,
Sayantan.
________________________________
From: Benjamin Callahan ***@***.***>
Sent: 30 April 2024 15:57
To: benjjneb/dada2 ***@***.***>
Cc: Sayantan Roy Choudhury ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [benjjneb/dada2] Taxonomy assignment (Issue #1938)


What is the output of the following?

ref_file <- "C:/Users/rc_sa/Downloads/MiSeq_SOP/tax/silva_nr_v132_train_set.fa.gz"
file.exists(ref_file)
