### ISSUE TITLE
mergeSequenceTables - fix duplicate names

### ISSUE THREAD

**Issue by m-ocejo** [benjjneb/dada2#194]
Hi again!
I have seqtables from 2 RProj so firstly I wrote the data frame to txt files:
`write.table(seqtab.nochim,"seqtab1.txt", sep="\t")`
`write.table(seqtab.nochim,"seqtab2.txt", sep="\t")`
Then I imported the two seqtables from txt.files:
```
seqtab1 <- read.table("seqtab1.txt", sep = "\t", header = TRUE)
seqtab2 <- read.table("seqtab2.txt", sep = "\t", header = TRUE)
```
To merge the seqtables I got this error:
```
> merged_seqtabnochim <- mergeSequenceTables(seqtab1, seqtab2, orderBy = "abundance")
Error in mergeSequenceTables(seqtab1, seqtab2,  : 
  At least two valid sequence tables, and no invalid objects, are expected.
```

I then realized that perhaps I should import the data to R as an object, so from both RProj I saved the seqtab.nochim and load them to my current R session:
```
save(seqtab.nochim, file = "seqtab1.rda")
save(seqtab.nochim, file = "seqtab2.rda")
load("seqtab1.rda")
load("seqtab2.rda")
```
Retried seqtables merging:
```
> merged_seqtabnochim <- mergeSequenceTables(seqtab1, seqtab2, orderBy = "abundance")
Error in mergeSequenceTables(broiler_seqtabnochim, lumagorri_seqtabnochim,  : 
  Duplicated sample names detected in the rownames.
```
seqtable1´s rownames are Sample01 to Sample 80, while seqtable 2 Sample 01-Sample 70. I would like to name them as Sample001-Sample 150.
I tried to rename the rows of each seqtable but the output is not in the same characteristics as the tables before the renaming. So again, the error message was: 

> Al least two valid sequence tables......

Can you tell me an easy way to rename the rownames so that the output is in the same  matrix as the output of makeSequenceTable?

**Comment by benjjneb** [comment]
Can you try the following:

```
saveRDS(seqtab.nochim, file="seqtab1.rds") # First table
saveRDS(seqtab.nochim, file="seqtab2.rds") # Second table
st1 <- readRDS("seqtab1.rds")
st2 <- readRDS("seqtab2.rds")
```

And then merge. I think that will fix the issues come from the save/load protocols, which are changing the type of the seqtab object (its a matrix not a data.frame).

**Comment by m-ocejo** [comment]
Thanks ben!
The error of duplicated names still comes up.
Should I rename the rownames? Mi idea was to rename the sampled so that seqtab1: Sample001 until Sample080
Seqtab2: Sample081 until Sample150?

**Comment by benjjneb** [comment]
Are they different samples?
Ideally you should name them something interpretable, but yes - each different sample needs a unique name.

**Comment by m-ocejo** [comment]
It worked!!
Yes, they are different samples.
Many thanks Ben,


All the best!
