### ISSUE TITLE
dada2 reference database for eukaryotes

### ISSUE THREAD

**Issue by eunicetan** [benjjneb/dada2#1943]
Hi, may I know what dada2 formatted reference database you would advise to use for COI for arthropods? Thank you!

**Comment by benjjneb** [comment]
I don't work with arthropods, so I can't give any educated guidance.

This page lists the available references for `assignTaxonomy` that we maintain or that folks have submitted: https://benjjneb.github.io/dada2/training.html

There is also a description of the reference file format that can be used to create custom databases.
