### ISSUE TITLE
Filtering ITS sequences

### ISSUE THREAD

**Issue by giriarteS** [benjjneb/dada2#195]
I was filtering my fungal ITS paired Illumina reads (2x300) without trimming adapters through dada2 (see quality plots):
fastqPairedFilter(
    c(names_fps$fnFs[i], names_fps$fnRs[i]),
    c(filtFs[i], filtRs[i]),
    truncLen = c(200, 200),
    maxN = 0,
    maxEE = 2.5,
    truncQ = 2,
    compress = TRUE,
    verbose = TRUE)

after filtering they were the same length:
"Read in 184431 paired-sequences, output 124320 filtered paired-sequences."

and the adapters were trimmed before using mergePairs. I got decent results, I was able to assign taxonomy and built the tree.

Then I trimmed the adapters with cut adapt and I followed your example here: #55
fastqPairedFilter(
    c(names_fps$fnFs[i], names_fps$fnRs[i]),
    c(filtFs[i], filtRs[i]),
    minLen=50,    
    maxN = 0,
    maxEE = 2,
    truncQ = 2,
    rm.phix=TRUE,
    compress = TRUE,
    verbose = TRUE)

But this time I got this:
Read in 184431 paired-sequences, output 1569 filtered paired-sequences.

[qualplot_Celaya1_F.pdf](https://github.com/benjjneb/dada2/files/775645/qualplot_Celaya1_F.pdf)
[qualplot_Celaya1_R.pdf](https://github.com/benjjneb/dada2/files/775644/qualplot_Celaya1_R.pdf)

Also the primer.fwd option (primer.fwd = "TCGATGAAGAACGCAGCG ") didn't work. I got the following error:
[1] "1 of 78"
Error in .Call2("solve_user_SEW", refwidths, start, end, width, translate.negative.coord,  : 
  solving row 53782: 'allow.nonnarrowing' is FALSE and the supplied end (18) is > refwidth
Calls: <Anonymous> ... narrow -> narrow -> solveUserSEW -> .Call2 -> .Call

Any help will be appreciated!!

**Comment by benjjneb** [comment]
Filtering parameters are enforced **after** trimming and truncation. Take a look at your reverse quality profile -- it falls off a cliff at around 200nts. In your first filtering command, the read are truncated at 200nt, and most reverse reads have EE<2 over those 200nts. However, in your second filtering command, you don't truncate the reverse reads, and so `maxEE` is compared against the whole read, including all that low quality sequence at the end, which I'm guessing is what is causing most reads to be filtered out. What I'd recommend, given the qualities here, is to truncate the reverse reads at 200 (assuming 500nt is safely spanning your amplicon) and see if most reads are now passing the filter.

On `primer.fwd`, this is bleeding-edge functionality that is not ready for general use (may be removed before our next release). For now you still need to remove adapters and primers before starting the dada2 workflow. The bug report is useful though!

**Comment by giriarteS** [comment]
Thanks! I ran the usearch -fastq_eestats2 on the trimmed reads to decide which truncLen and maxEE to use. Here you can see the results for R1 and R2:
usearch9 -fastq_eestats2 pooled_R1.fq -output R1.eestats2.txt -ee_cutoffs 2.0,2.5,3.0 -length_cutoffs 200,300,5

Length         MaxEE 2.00         MaxEE 2.50         MaxEE 3.00
------   ----------------   ----------------   ----------------
   200   11847182( 90.3%)   12085515( 92.1%)   12280154( 93.6%)
   205   11759914( 89.6%)   12005517( 91.5%)   12203740( 93.0%)
   210   11667416( 88.9%)   11922139( 90.8%)   12126504( 92.4%)
   215   11582109( 88.3%)   11845784( 90.3%)   12056156( 91.9%)
   220   11492009( 87.6%)   11766729( 89.7%)   11983778( 91.3%)
   225   11390069( 86.8%)   11676487( 89.0%)   11901268( 90.7%)
   230   11261458( 85.8%)   11566083( 88.1%)   11802821( 89.9%)
   235   11140561( 84.9%)   11462299( 87.3%)   11710689( 89.2%)
   240   10978938( 83.7%)   11327063( 86.3%)   11592906( 88.3%)
   245   10843705( 82.6%)   11213410( 85.4%)   11494344( 87.6%)
   250   10618739( 80.9%)   11028025( 84.0%)   11336940( 86.4%)
   255   10437789( 79.5%)   10876698( 82.9%)   11207262( 85.4%)
   260   10204642( 77.8%)   10683904( 81.4%)   11044451( 84.2%)
   265    9957718( 75.9%)   10475830( 79.8%)   10868821( 82.8%)
   270    9628818( 73.4%)   10198359( 77.7%)   10637102( 81.1%)
   275    9192138( 70.0%)    9827996( 74.9%)   10323159( 78.7%)
   280    8894894( 67.8%)    9565363( 72.9%)   10092416( 76.9%)
   285    8396846( 64.0%)    9126990( 69.5%)    9712269( 74.0%)
   290    7952525( 60.6%)    8720414( 66.4%)    9347318( 71.2%)
   295    7540760( 57.5%)    8342711( 63.6%)    9003295( 68.6%)
   300    6991913( 53.3%)    7831483( 59.7%)    8533003( 65.0%)

usearch9 -fastq_eestats2 pooled_R2.fq -output R2.eestats2.txt -ee_cutoffs 2.0,2.5,3.0 -length_cutoffs 200,300,5
Length         MaxEE 2.00         MaxEE 2.50         MaxEE 3.00
------   ----------------   ----------------   ----------------
   200    9572862( 72.9%)   10114834( 77.1%)   10558190( 80.5%)
   205    9303720( 70.9%)    9874003( 75.2%)   10339539( 78.8%)
   210    8998151( 68.6%)    9604842( 73.2%)   10098433( 77.0%)
   215    8600005( 65.5%)    9271281( 70.6%)    9810624( 74.8%)
   220    8153682( 62.1%)    8880091( 67.7%)    9462798( 72.1%)
   225    7498312( 57.1%)    8320403( 63.4%)    8975130( 68.4%)
   230    6822395( 52.0%)    7760805( 59.1%)    8499312( 64.8%)
   235    6133438( 46.7%)    7149621( 54.5%)    7960193( 60.7%)
   240    5528169( 42.1%)    6583481( 50.2%)    7436439( 56.7%)
   245    4898106( 37.3%)    5996924( 45.7%)    6900583( 52.6%)
   250    4081237( 31.1%)    5244303( 40.0%)    6223196( 47.4%)
   255    3265337( 24.9%)    4455138( 33.9%)    5498286( 41.9%)
   260    2512971( 19.1%)    3654943( 27.9%)    4719333( 36.0%)
   265    1791600( 13.7%)    2829543( 21.6%)    3876627( 29.5%)
   270    1178102(  9.0%)    2061132( 15.7%)    3046606( 23.2%)
   275     780056(  5.9%)    1491270( 11.4%)    2364020( 18.0%)
   280     439390(  3.3%)     944443(  7.2%)    1644828( 12.5%)
   285     247783(  1.9%)     586483(  4.5%)    1112714(  8.5%)
   290     120917(  0.9%)     319180(  2.4%)     666504(  5.1%)
   295      65691(  0.5%)     187552(  1.4%)     422726(  3.2%)
   300      38112(  0.3%)     115270(  0.9%)     275565(  2.1%)

Finally, I decided to choose:
fastqPairedFilter(
c(names_fps$fnFs[i], names_fps$fnRs[i]),
c(filtFs[i], filtRs[i]),
truncLen = c(280, 215),
minLen=210, 
maxN = 0,
maxEE = 2.5,
truncQ = 2,
rm.phix=TRUE,
compress = TRUE,
verbose = TRUE)

I choose minLen=210 because the adapter + primer length is ~90 (300-90=210). I blasted the reads with length <= 200 and I didn't get any good hit.

**Comment by benjjneb** [comment]
Looks good. That EE stats read-out might be worth adding as a function in the R package.

**Comment by giriarteS** [comment]
I have another question about ITS, what band size did you use with ITS sequences?

**Comment by benjjneb** [comment]
We currently recommend `BAND_SIZE=32` for ITS data.

In our testing the default (`BAND_SIZE=16`) has worked just fine, but because indel rates are so much higher in ITS and we don't have as much experience with it, the larger band size is prudent. The only cost is that run-time will be about 1.5x longer.
