### ISSUE TITLE
Cluster ASVs to OTUs with DECIPHER

### ISSUE THREAD

**Issue by Danyang1111** [benjjneb/dada2#1950]
Hi, 
I am trying to cluster obtained ASVs to OTUs using DECIPHER, the code is as follows:
`
asv_sequences <- colnames(seqtab_nochim_subset)
sample_names <- rownames(seqtab_nochim_subset)

dna2 <- Biostrings::DNAStringSet(asv_sequences)

aln <- DECIPHER::AlignSeqs(dna2, processors = nproc)
d <- DECIPHER::DistanceMatrix(aln, processors = nproc)

clusters <- DECIPHER::TreeLine(
  myDistMatrix=d, 
  method = "complete",
  cutoff = 0.03, # use `cutoff = 0.03` for a 97% OTU 
  processors = nproc)

merged_seqtab <- seqtab_nochim_subset %>% 
  t %>%
  rowsum(clusters$cluster) %>%
  t
`
and I got error like this:

`
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 't': incorrect length for 'group'
`

what should I do?

**Comment by sigrik92** [comment]
Hi, I encountered the same issue and solved it by adding type = "clusters" (else the output is a dendrogram): 

clusters <- DECIPHER::TreeLine(
  myDistMatrix=d, 
  method = "complete",
  type = "clusters",
  cutoff = 0.03
  processors = nproc)

**Comment by adrientaudiere** [comment]
Hi @Danyang1111 and @sigrik92,
You may be interested in the function [asv2otu()](https://adrientaudiere.github.io/MiscMetabar/reference/asv2otu.html) from the [MiscMetabar](https://adrientaudiere.github.io/MiscMetabar/) package.
