### ISSUE TITLE
Is denoising required for kraken analysis?

### ISSUE THREAD

**Issue by BrinthaVP** [benjjneb/dada2#1952]
> Would it be best to use the discarded reads for **this** or reads still present at the end of the Dada2 pipeline?

If "this" means the analysis I proposed above, ASVs refer to the output of DADA2. Kraken would be used on the raw reads.

_Originally posted by @benjjneb in https://github.com/benjjneb/dada2/issues/1721#issuecomment-1515405061_

Could you please point out to any relevant material on "Why denoising not required for kraken analysis"

**Comment by benjjneb** [comment]
I'm not sure what you are asking here?

**Comment by BrinthaVP** [comment]
Currently I assume that kraken can be ran on raw reads and does not require any denoising as the output of DADA2 is actually ASV's. Still it is possible that we can take the denoised sequences and ran Kraken on them. 

I saw one of your comments also saying that Kraken is used on raw reads. It is only referring to that comment, I requested to point out to any relevant material on "Why denoising not required for kraken analysis?". 

I am just wondering whether Kracken+Bracken performance be similar to Dada2+Qiimeclassifier.

**Comment by benjjneb** [comment]
> I requested to point out to any relevant material on "Why denoising not required for kraken analysis?".

The paper proposing using Kraken for 16S profiling ran Kraken on reads, not ASVs. https://doi.org/10.1186/s40168-020-00900-2

> I am just wondering whether Kracken+Bracken performance be similar to Dada2+Qiimeclassifier.

When I have tried them, metagenomic classifiers like Kraken produce very high numbers of false positive taxa from 16S data.

**Comment by BrinthaVP** [comment]
Thanks for your reply. I will look into it.
