### ISSUE TITLE
Trimming/ derep error

### ISSUE THREAD

**Issue by tobaiasbama** [benjjneb/dada2#1953]
Hi, am running 16s Hifi demultiplexed analysis, after running the last line of code in this chunk: 
meta_ana <- "~/Users/oluwatobifijabi/Downloads/Elijah/Metagenomics Results 2"
path.out <- "Figures/"
path.rds <- "RDS/"
fns1 <- list.files(meta_ana, pattern="fastq.gz", full.names=TRUE)
F27 <- "AGRGTTYGATYMTGGCTCAG"
R1492 <- "RGYTACCTTGTTACGACTT"
rc <- dada2:::rc
theme_set(theme_bw())
nops1 <- file.path(meta_ana, "noprimers", basename(fns1))
**prim1 <- removePrimers(fns1, nops1, primer.fwd=F27, primer.rev=dada2:::rc(R1492), orient=TRUE)** ; i got this
warning message:
In removePrimers(fns1, nops1, primer.fwd = F27, primer.rev = dada2:::rc(R1492),  :
  No reads passed the primer detection.

**Comment by benjjneb** [comment]
No reads are passing primer detection. This means that the `removePrimers` function is not finding any reads that contain both the primers you provided, and thus is not creating an output file, at least for some samples.

Can you say more about what type of data you are working with? Is this amplicon sequencing data? if so, what are the primers being used? What is the sequencing technology? Have you confirmed the primers are on the reads?

**Comment by tobaiasbama** [comment]
[Metagenomics Workflow 16S rRNA (1).docx](https://github.com/benjjneb/dada2/files/15300341/Metagenomics.Workflow.16S.rRNA.1.docx)
here is a link to the data(https://drive.google.com/file/d/1SWwLXrwoilnrKvuZ8-tm62rZcTiStRoj/view?usp=drivesdk)

**Comment by benjjneb** [comment]
I would start by confirming that the expected primers are actually on the reads you are working with. The identify primers section of the dada2 tutorial for ITS data shows an example of this: https://benjjneb.github.io/dada2/ITS_workflow.html#identify-primers

**Comment by elipowel** [comment]
I'm having a similar problem (with data I got via a Library beta test from Zymo sequences via PacBio Kinnex).  The data showed up from their sequencing run already demultiplexed with primers removed. I see that Qiime2 users are having this issue as well.

**Comment by benjjneb** [comment]
@elipowel If the data have already had primers removed and been oriented in the forward direction, then you can just skip the `removePrimers` step.
