### ISSUE TITLE
High chimera rate: +80%

### ISSUE THREAD

**Issue by Mx-nene** [benjjneb/dada2#1957]
Hi. 

I am doing microbiome Research on chicken stool.

I have ran to a problem with my analysis. I have ran DADA2 on Illumina MiSeq 2x150bp 16S rRNA sequence data, and obtained a chimera percentage of 83% which is problematic. I did use the primers 341f (CCTACGGGNGGCWGCAG) and 785r (GACTACHVGGGTATCTAATCC) for trimming but I have the 83% chimeric sequences.

Could you please provide you valuable insight on such a a problem, because, I should be submitting my dissertation and article publications soon and this error is hindering me.

I hope my request receives favourable consideration.

**Comment by benjjneb** [comment]
Is this the percent of the ASVs in the data? Or the percent of the reads in the data? Quoting [the dada2 tutorial section on chimera removal](https://benjjneb.github.io/dada2/tutorial.html#remove-chimeras):

> Considerations for your own data: Most of your **reads** should remain after chimera removal (it is not uncommon for a majority of **sequence variants** to be removed though).

**Comment by Mx-nene** [comment]
When looking for the abundance of merged reads, 83% are considered as chimeras.

The R code was: 

sum(seqtab.nochim) / sum(seqtab)

**Comment by benjjneb** [comment]
If the result of `sum(seqtab.nochim)/sum(seqtab)` is ~0.83, it means that 83% of your reads are non-chimeras (so 17% are being removed as chimeras).

**Comment by Mx-nene** [comment]
That's perfect.

Thank you very much, Dr Callahan.
