### ISSUE TITLE
what happens with staggered reads when using mergePairs

### ISSUE THREAD

**Issue by tobiasgf** [benjjneb/dada2#196]
Hello

I am using DADA2 for regions that often vary a lot in length between organisms (for example ITS region). That means that some amplicons may have forward and reverse reads (R1/R2) with an overlap of 20 bp, whereas others may have fully overlapping amplicon regions but also a tail/overhang of (reverse complementary) primer and adapter at the 3' (so called staggered reads - e.g. http://drive5.com/usearch/manual/merge_stagger.html).

I am wondering what DADA2 does during merging (mergePairs) with these short amplicons where both forward and reverse reads contain overhangs of sequencing primer site and adapter (and possibly also amplification primer and tag) at the 3' end. Are the overhangs trimmed off (which would be preferable), or is the merging not carried out, or?

NB: My reads do not contain primer sequences or tags at the 5', as these have been trimmed during demultiplexing.

**Comment by benjjneb** [comment]
Right now `mergePairs` simply merges reads that go past the start of the other read ("stagger") without any further trimming. Therefore, if you are dealing with ITS reads (for example) in which variation may cause the reads to read into the other primer, that other primer also needs to be trimmed.

It would be easy enough to add an option to trim off the "stagger" though, would that be a useful feature?

**Comment by tobiasgf** [comment]
My main worry was that they might not be merged at all.
However, it would be amazing with an option to trim those overhangs during merging! :-)
Thanks!

**Comment by tobiasgf** [comment]
Just a note, you are probably already aware.
When trimming the overhangs during merging, different reads/OTUs may become identical as their only differences were in the trimmed region.
Looking forward to the implemented solution :-)

**Comment by tobiasgf** [comment]
One question more in this relation - looking for an ad hoc solution until a option is implemented in DADA2:
Would it be possible to trim the stagger (reverse complement primer/adapter remains) from the "raw" R1 and R2 reads before running the dada2 commands (`fastqPairedFilter` and `dada`)?
(I guess not. For one thing, the fastqPairedFilter may contain a `truncLen` option that is longer than the trimmed read, resulting in an error(?))

**Comment by benjjneb** [comment]
Added the `trimOverhang` option to `mergePairs` in d0fb14a11e04d61f52727f595a9139c44e62e51e

This will trim off "overhangs" in the merged sequence: i.e. remove that part of the merged sequence where the reverse read extended beyond the start of the forward read, and vice-versa (if it exists).

Merging of subsequently identical sequences happens in the `makeSequenceTable` step.

Note: This is not the recommended usage of the dada2 workflow. Best results are still obtained by trimming off **both** primers prior to starting the dada2 workflow. This is because when overhanging reads extend into the opposite primer (and/or random nt) regions, they do not dereplicate together, which reduces the statistical power to detect biological variants.

**Comment by tobiasgf** [comment]
x

**Comment by tobiasgf** [comment]
Great! :-)
But, you recommend to trim off both primers before starting dada2 workflow.
However - referring to my question above - this approach, would cause reads of very different lengths, when dealing with ITS, trnL or other regions with vary different amplicon lengths. Is that perfectly OK for the dada2 algorithm? Wouldn't it make the `fastqPairedFilter` give an error when using a `truncLen` option on reads that have been trimmed shorter than the selected threshold?

**Comment by benjjneb** [comment]
@tobiasgf 

As of the recent commit cddce98a98894e4a621f6767e61fe9aaed638e06 the dada algorithm handles variable length amplicons, meaning you can run it without enforcing `truncLen`, which is probably the right way to do it for common ITS primer sets such as you are describing.

See here for more discussion: https://github.com/benjjneb/dada2/issues/55#issuecomment-279080098
