### ISSUE TITLE
ONT error model [question]

### ISSUE THREAD

**Issue by ccrinconc** [benjjneb/dada2#1969]
Dear Ben and Team,

It is my impression that ONT reads have (in the most recent chemistries) reached a level of quality that may be sufficient to be used within dada2, I may be too optimistic. If this is indeed the case, is there any ongoing work/plan to have an ONT error model available for dada2?

Thanks

**Comment by benjjneb** [comment]
We are looking at ONT Duplex reads, but regular ONT reads are definitely not accurate enough to use with DADA2.

**Comment by ccrinconc** [comment]
Thanks for the answer. Looking forward for these developments on duplex reads.
Cheers
