### ISSUE TITLE
Keeping missing data / Ns in the reads

### ISSUE THREAD

**Issue by ThomePauline** [benjjneb/dada2#1970]
Hello, 

is there any way to run dada() on data that still includes missing values (N bases)? I can keep a certain percentage of Ns using the maxN flag in filterAndTrim(), but why is this option there if I can only continue the pipeline if I set it to 0?

I don't want to resolve the community to species/ASV level but a higher taxonomic level is enough for my purposes, so I would prefer to keep more reads at the expense of taxonomic resolution.

Thanks in advance!

**Comment by benjjneb** [comment]
No there isn't. See previous brief discussion here: https://github.com/benjjneb/dada2/issues/1811#issuecomment-1716162695
