### ISSUE TITLE
The deprecated feature was likely used in the dada2 package.

### ISSUE THREAD

**Issue by sar515** [benjjneb/dada2#1972]
> plotQualityProfile(fnFs[1:1])
Warning messages:
1: In serialize(data, node$con) :
  'package:stats' may not be available when loading
2: The `<scale>` argument of `guides()` cannot be `FALSE`. Use
"none" instead as of ggplot2 3.3.4.
ℹ The deprecated feature was likely used in the dada2
  package.
  Please report the issue at
  <https://github.com/benjjneb/dada2/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where
this warning was generated.

**Comment by benjjneb** [comment]
This is the 17th time this warning has been reported: https://github.com/benjjneb/dada2/issues?q=is%3Aissue+%22The+%3Cscale%3E+argument+of+guides%28%29+cannot+be+FALSE%22

It has been fixed for some time: https://github.com/benjjneb/dada2/commit/b6ab04f50988e91796453887bd15889f81ee99cb. 

If you want this warning to go away, update to a current release of dada2.
