### ISSUE TITLE
AssignTaxanomy- from phyloseq class

### ISSUE THREAD

**Issue by cjburgess** [benjjneb/dada2#198]
Is it possible/practical to take a phyloseq::refseq() object and assign taxonomy to it using assignTaxonomy() on it or is it just easier to use tools outside of dada2 to do it. 

> head(refseq(nrcsbac))
  A DNAStringSet instance of length 6
    width seq                                               names       
[1]   253 TACGTAGGCAGCAAGCGTTGTTC...CGAAAGCGTGGGTAGCAAACAGG OTU_45703
[2]   253 TACGTAGGCAGCAAGCGTTGTTC...CGAAAGCGTGGGGAGCAAACAGG OTU_21743
[3]   253 TACGTAGGCAGCAAGCGTTGTTC...CGAAAGCGTGGGGAGCAAACAGG OTU_7984
[4]   253 TACGTAGGCAGCAAGCGTTGTTC...CGAAAGCGTGGGTAGCAAACAGG OTU_13379
[5]   253 TACGTAGGCAGCAAGCGTTGTTC...CGAAAGCGTGGGTAGCAAACAGG OTU_1986
[6]   253 TACGTAGGCAGCAAGCGTTGTTC...CGAAAGCGTGGGTAGCAAACAGG OTU_607
> str(refseq(nrcsbac))
Formal class 'DNAStringSet' [package "Biostrings"] with 5 slots
  ..@ pool           :Formal class 'SharedRaw_Pool' [package "XVector"] with 2 slots

**Comment by benjjneb** [comment]
If it is a DNAStringSet, then you can just coerce the DNAStringSet to a character vector first.

```
tax <- assignTaxonomy(as(refseq(nrcsbac), "character"), "path/to/ref.fa.gz")
```

Does that work? 

We ought to just support DNAStringSet natively...

**Comment by cjburgess** [comment]
So it took the coerced vector; however, the names in the tax object became the sequence itself instead of the OTU identifier.  The OTU identifier was preserved in the name of the row name of tax .  I think I figured out a workaround to change the row.names back to the OTU identifier.  Thanks for the help!

-Chris

> head(tax, n=1)
                                                                                                                                                                                                                                                              Kingdom
TACGTAGG...AAACAGG "Bacteria"
                                                                                                                                                                                                                                                              Phylum
TACGTAGGC...TAGCAAACAGG "Acidobacteria"
...

> head(row.names(tax), n=1)
                                                                                                                                                                                                                                                   OTU_45703
"TACGTAGGC...GTAGCAAACAGG"

> str(row.names(tax))
 Named chr [1:22984] "TACGTAGGCAGCAAGCGTTGTTCGGAGTTACTGGGCGTAAAGGGTGTGTAGGCGGTTGTTTAAGTTTGGTGTGAAATCTCCCGGCTCAACTGGGAGGGGGCGCCGAATACTGAATGACTAGAGTGCG"| __truncated__ ...
 - attr(*, "names")= chr [1:22984] "OTU_45703" "OTU_21743" "OTU_7984" "OTU_13379" ...

> head(names(row.names(tax)))
[1] "OTU_45703" "OTU_21743" "OTU_7984"  "OTU_13379" "OTU_1986"  "OTU_607"

> row.names(tax) <- names(row.names(tax))
> head(tax)
          Kingdom    Phylum          Class               Order Family Genus
OTU_45703 "Bacteria" "Acidobacteria" "Acidobacteria_Gp3" NA    NA     NA
OTU_21743 "Bacteria" "Acidobacteria" "Acidobacteria_Gp3" "Gp3" NA     NA
OTU_7984  "Bacteria" "Acidobacteria" "Acidobacteria_Gp3" "Gp3" NA     NA
OTU_13379 "Bacteria" "Acidobacteria" "Acidobacteria_Gp3" "Gp3" NA     NA
OTU_1986  "Bacteria" "Acidobacteria" "Acidobacteria_Gp3" "Gp3" NA     NA
OTU_607   "Bacteria" "Acidobacteria" "Acidobacteria_Gp3" "Gp3" NA     NA

**Comment by benjjneb** [comment]
Looks good. And yes, dada2 will name everything by the sequences themselves, so you do have to do that manual renaming by the "OTUXXX" nomenclature to get it back into the phyloseq object.
