### ISSUE TITLE
Are these error plots okay?

### ISSUE THREAD

**Issue by biadelbianco** [benjjneb/dada2#1980]
Just want to know if these plots are fine or if is there any issue that need to be fixed.

[errorplot.pdf](https://github.com/user-attachments/files/16073363/errorplot.pdf)

Here the quality plots as well

[qualplot.pdf](https://github.com/user-attachments/files/16073378/qualplot.pdf)

My code for filterAndTrim

filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(270,240), trimLeft=c(17,21), 
              maxN=0, maxEE=c(2,5), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=TRUE)

**Comment by benjjneb** [comment]
Those error plots look fine.

**Comment by biadelbianco** [comment]
Thank you, benjjneb!
