### ISSUE TITLE
Merging two datasets trimmed with different criteria

### ISSUE THREAD

**Issue by andrebolerbarros** [benjjneb/dada2#1992]
Hey everyone,

I do not have a concrete example but, I was wondering if merging two datasets, each from its sequencing run (in this scenario, I am running dada2 separately for each run), this could not impact the ASV. Specifically in the process of merging ASVs.

Thanks,

**Comment by andrebolerbarros** [comment]
Thanks @benjjneb 

So, for single-end data, merging datasets from different runs, for example, may be problematic. In that sense, is it preferable to run both datasets merged and just include the batch information downstream? But this may lead, worst case scenario, of having very different community structures solely by differences in trimming criteria. What should one do to solve this issue?

**Comment by benjjneb** [comment]
Truncating both sets of reads at the same position is the preferred solution. This is straightforward for single-end data deriving from the same starting primer -- just truncate the longer ASV table at the length of the shorter ASV table. Then you can use the `collapseNoMismatch` function on the merged table to clean up any variants that used to differ only in the positions that have been truncated away.

**Comment by andrebolerbarros** [comment]
Perfect, amazing! Thank you @benjjneb
