### ISSUE TITLE
Consensus Sequences

### ISSUE THREAD

**Issue by mjrosen** [benjjneb/dada2#2]
Consensus sequences are not updated dynamically (during clustering) as of the most recent version of the matlab code -- don't know if Ben has changed this with the C. In practice it only matters for very small clusters with singletons and doubletons. Otherwise, the ad hoc procedure of using the most abundant sequence should essentially always be identical with the result of any true consensus sequence update. 

Although Susan is right that in general EM converges, the reason it is not guaranteed to result in convergence is to do with with fact that alignments, which produce the new consensus sequences, do penalize indels, but the error model, which is responsible for the reshuffling of sequences between clusters, depends only on substitutions. So they're sort of operating under different likelihoods

Specifically, what may happen is: some singleton joins a cluster. In so doing, it pushes the consensus sequence towards itself (in terms of alignment score), which results in many fewer indels but, occasionally, MORE substitutions. These substitutions are all that matters to the error model, so now it decides to move back to its original cluster, after which the consensus sequence goes back to its original value. I have a painfully detailed documentation of one such event from a couple years ago if anyone is interested.

**Comment by benjjneb** [comment]
The updating of the cluster center is turned off during the running of the algorithm for stability and performance reasons.

A final consensus step is implemented as an option (FINAL_CONSENSUS = FALSE/TRUE). This is off by default, and in non-extensive testing it has not been an improvement.
