### ISSUE TITLE
Class definitions for uniques and dada-output

### ISSUE THREAD

**Issue by joey711** [benjjneb/dada2#20]
Please comment your preferences on the class names O:-)... I was thinking `"uniques"` and `"dada"` would work. 

This solves at least two problems:
- Make sure user understands what their `uniques` list or `dada` list is, control some aspects about what to do with it
- When these objects get printed to screen, it currently "explodes" the console because there's so much good stuff in there. Need to summarize that good stuff in a useful way

**Comment by benjjneb** [comment]
dada return is classed "dada", derepFastq is classed "derep"

Joey, how do we implement print.dada and print.derep?

**Comment by joey711** [comment]
Great, so I assume this means these have formal class definitions now?
`print.derep` is the old "S3" way of doing it, which BioC won't like.
We'll need to define new "print" and "show" S4 methods that extend the S4 base generics for same.

**Comment by benjjneb** [comment]
No just S3 style (class(return.val) <- dada).

Will BioC accept S3 classes even if it doesn't like them?

**Comment by joey711** [comment]
If there is a standard S4 approach, and there is in this case, then they would kick it back and ask you to change it. I can tackle this. I'll migrate whatever you have currently for printing to the S4 method.

**Comment by benjjneb** [comment]
I added nothing except class(dada.return) <- "dada" and
class(derepFastq.return) <- "derep"

Adding a stub print function would be great, can fill in later.

**Comment by joey711** [comment]
Yeah, those are not S4 classes either. No worries. I can get this up to snuff.

**Comment by benjjneb** [comment]
How difficult is basic inspection and use of S4 classes going to be?

One of the nice things about these objects is that they are a simple
inspectable list. S4 classes seem to be more unwieldy generally.

**Comment by spholmes** [comment]
inspection?
function
str
is a workaround
otherwise you need to know the slots....


On Thu, Aug 6, 2015 at 4:34 PM, benjjneb <notifications@github.com> wrote:

> How difficult is basic inspection and use of S4 classes going to be?
>
> One of the nice things about these objects is that they are a simple
> inspectable list. S4 classes seem to be more unwieldy generally.
>
> On Thu, Aug 6, 2015 at 2:14 PM, Paul J. McMurdie <notifications@github.com
> >
> wrote:
>
> > Yeah, those are not S4 classes either. No worries. I can get this up to
> > snuff.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/benjjneb/dada2/issues/20#issuecomment-128463368>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benjjneb/dada2/issues/20#issuecomment-128499437>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by benjjneb** [comment]
I would rather not add S4 structure if we don't have to.

The only things we want from classing these returns is (1) being able to
pass them to dada2 functions, and (2) being able to have a generic print
function that doesn't spam the user to death.

**Comment by joey711** [comment]
I agree, let's avoid killing users via accidental spam.

It's straightforward to extend the "list" class as a new S4 object. Since downstream functions interact with the typical `$` operator, I don't think it would require any other code changes.

I agree that converting each top-level list element to a formal slot feels like overkill in this case, and I'll try to do what I just proposed as a simple lightweight workaround.

**Comment by joey711** [comment]
@benjjneb The "S4-migrate" branch linked above shows this very light-weight S4 method. I also narrowed the namespace to `@importFrom pacakge method` in all cases except ggplot2.

To focus on the show method, look at the `show-methods.R` file, and also the `allClasses.R` file.
The `derepFastq` and `dada` functions were trivially modified to return the respective S4 object (which is really just a list, but don't tell BioC ;-) )

**Comment by joey711** [comment]
p.s. let me know if you like this and I'll merge into the master (or you can). Feel free to modify the show method further. I didn't really do anything to summarize the `"dada"` object yet. The `"derep"` object has a pretty nice summary though.
