### ISSUE TITLE
(Apparent) Negative Phred Scores - Justification

### ISSUE THREAD

**Issue by andrebolerbarros** [benjjneb/dada2#2002]
Hey everyone,

Just as a note (don't know if someone has noticed this) but, with binned quality scores such as NovaSeq, some positions seem to have negative quality scores (the `plotQualityProfile` function produces some alerts regarding not showing some entries, with this warning solved by reorganizing the `ylim`).

 
![image](https://github.com/user-attachments/assets/9d85ca22-cf3b-42a6-840e-2926f74364a9)

This happens due to the way how `geom_tile()` calculates the dimensions of general tiles. In this case, the quality scores are classified as 2, 11, 25 and 37. The smallest difference across levels is 9 (11-2) - so the tile height is 9 (4.5 above 2, 4.5 below 2). This means the lowest limit of tiles in this case is -2.5. 

This is more of a heads up than an active issue.

**Comment by benjjneb** [comment]
Thank you for this very informative report!

**Comment by andrebolerbarros** [comment]
Thank you!

As a suggestion, locking the height in geom_tile() in a value like 1 could solve the problem.

However, for binned quality scores, the visualization with larger tiles is indeed helpful.
