### ISSUE TITLE
Can dada2 take my combined sequences .fna file and run the workflow? 

### ISSUE THREAD

**Issue by slvrshot** [benjjneb/dada2#201]
I use other programs like Geneious and Trimmomatic to do merging, trimming and quality filtering, then I add unique qiime labels to all of my .fasta files to produce one .fna file. Usually I feed the combined_seqs.fna to Qiime's pick_open_reference_otus.py workflow. I am wondering if those combined sequences can also be passed directly into dada2. I should mention these sequences are 16S amplicons sequenced on a MiSeq.

**Comment by benjjneb** [comment]
The dada2 workflow requires that each sample have its own input file.

The bigger problem here is that we do not currently support fasta files, you need the fastq files so that the quality information can be used to better identify errors from real variation.

**Comment by slvrshot** [comment]
So basically I would need to go back and use the raw paired-end sequences? That's fine I suppose.

Do you guys have any benchmarks? Typically it takes about 5-6 hrs to process 3.5 Gb of sequence data using the pick_open_reference_otus.py workflow on our lab computer....OSX El capitan/Mac Pro 2008/24 GB of DDR2 RAM, 2 x 2.8 GHz Quad Core Intel Xeon. 

I'm curious what run times would look like for dada2.

Thanks!

**Comment by benjjneb** [comment]
It depends quite a bit on how complex the community is and how deep your individual samples are, but you shouldn't have much trouble processing data of that size on that machine.

Run say 10 samples to get an idea. Samples are processed independently, so run time scales linearly with sample number.

**Comment by benjjneb** [comment]
Closing as assumed that the split sample workflow is working. Feel free to reopen if new problems arise.
