### ISSUE TITLE
Formatting RDP version 19 taxonomic database for DADA2

### ISSUE THREAD

**Issue by jheiman06** [benjjneb/dada2#2014]
I am working on processing bacterial 16S rRNA sequences with DADA2. I would like to classify these sequences with the newest update of the RDP database (version 19), but I have yet to find it formatted for DADA2. I have found the code to format it myself, and this was successful for the "assignTaxonomy" function, but I have not been able to format the species file correctly. I think this is because I cannot find the unaligned bacteria file as the RDP site at Michigan State is no longer working. 
Has this database (RDP version 19) been formatted for DADA2? If not, do you know where I could find the unaligned bacteria file in order to format the species file correctly?

**Comment by benjjneb** [comment]
> Has this database (RDP version 19) been formatted for DADA2?

Nope, on the to-do list now though.

> If not, do you know where I could find the unaligned bacteria file in order to format the species file correctly?

Not sure, but I will look into this more later this month.

**Comment by nvwinsen** [comment]
Is it possible to format the RDP v19 database including species instead of a separate species table?
This way bootstrapping can be included for species with RDP (which now is only possible with Silva).

**Comment by benjjneb** [comment]
`assignTaxonomy` compatible references for the RDP v19 release are now available: https://doi.org/10.5281/zenodo.14168770

> Is it possible to format the RDP v19 database including species instead of a separate species table?
This way bootstrapping can be included for species with RDP (which now is only possible with Silva).

There are two versions of the reference available. One that goes only to the genus level as before (`rdp_19_toGenus_trainset.fa.gz') and one that also has species level information ('rdp_19_toSpecies_trainset.fa.gz').
