### ISSUE TITLE
How to use 16S-ITGDB database in dada2?

### ISSUE THREAD

**Issue by benhardestevao** [benjjneb/dada2#2016]
I'm having trouble using the 16S-ITGDB database (https://github.com/yphsieh/16S-ITGDB) to assign taxonomy. Could someone give me some insight into the subject and how to format or correctly use this database for my analyses?

**Comment by benjjneb** [comment]
The reference file format for `assignTaxonomy` is described here: https://benjjneb.github.io/dada2/training.html#formatting-custom-databases

You'll need to convert the ITGDB files into that format to use it with `assignTaxonomy`.
