### ISSUE TITLE
Collapsing ASVs into OTUs?

### ISSUE THREAD

**Issue by marinachen** [benjjneb/dada2#2021]
Hi DADA2 developer,

I have a high-level conceptual question - I've seen people clustering ASVs into OTUs at certain similarity threshold for various purposed. How is that different from directly using traditional OTU clustering methods? Is it just giving more confidence in the sequences being clustered after dada2 denoising?

Thank you for your insight!

**Comment by benjjneb** [comment]
I think people do those for two reasons. First is that the DADA2 step is being considered an error-correction/removal step (there were a lot of issues with insufficient error removal in previously popular OTU piepelines). The second is that people are analyzing their data at multiple levels of taxonomic resolution. So they start at the ASV level as that is the highest resolution possible, and then "coarse-grain" that data by OTU clustering to also look at other levels of taxonomic resolution.
