### ISSUE TITLE
removeBimeraDenovo not possible to multithread on windows (R)

### ISSUE THREAD

**Issue by gianINTERN** [benjjneb/dada2#2022]
hello everyone, 
I'm here to try to use removeBimeraDenovo() function on windows but with multithread=TRUE, the console give me this error:
`Error in mclapply(mc.indices, loopFun, unqs.loop = unqs.int, allowOneOff = allowOneOff,  : 
  'mc.cores' > 1 is not supported on Windows`
I even tried parallel:
`parallel::parLapply(cl,  tab_seq_all ,removeBimeraDenovo(tab_seq_all) )    
`
or:
`ll <- parallel::clusterApply(cl=cl,  x=tab_seq_all ,fun=removeBimeraDenovo )`

but it is not working. The first one gives the error of dada that do not recognise the object class, and the second gives me an error from n=number of reads in the object nodes that return the error of dada as in the previous function.
Now here on issues of github, on 2021, there was stated that with the default method "consensus" it should work, but apparently not for me... please help!

here the code i used:

`library(dada2)
library("Biostrings")

b_fasta_c = readDNAStringSet("16S_asv_rep_seq_CLEAN.fasta")

now I create the dataset suitable for the function with the count table

df_all<-as.data.frame(b_fasta_c)
rownames(df_all)<- b_fasta_c@ranges@NAMES
df_all_counts<- cbind(df_all, bact2[which(bact2[,"Feature.ID"] %in% b_cleaned),] )

seq_tab_all<- data.frame(sequence= df_all_counts[,1], #df_all_counts[,-c(1,2)] ,
                abundance= rowSums(df_all_counts[,3:62])  )

so i transform all in a vector named object:
tab_seq_all<-getUniques(seq_tab_all)
library(parallel)
cl <- makeCluster(getOption("cl.cores", 10))
registerDoParallel(cl, cores=10)
clusterExport(cl, list( "removeBimeraDenovo", "tab_seq_all") )
ll <- parallel::clusterApply(cl=cl,  x=tab_seq_all ,fun=removeBimeraDenovo )   
ll <- c(parallel::parLapply(cl, tab_seq_all ,removeBimeraDenovo ))    

stopCluster(cl)

and of course i tried the following:
prova<- removeBimeraDenovo(tab_seq_all, method="consensus", multithread=TRUE , verbose=TRUE)`

Thank to everybody for the precious efforts of building and maintain dada2!

**Comment by benjjneb** [comment]
`mclapply` uses forking for multiprocessing, but forking is not supported on windows. Hence the error message you are seeing (nothing to do with dada2). The second set of errors from `parallel::clusterApply` look again to be an issue with the multithreading approach you are using, not with dada2 itself.

Multithreading is built in to `removeBimeraDenovo` in a way that will work on any platform including windows. Instead of wrapping `removeBimeraDenovo` inside on of the multi-threaded apply functions, just call `removeBimeraDenovo(..., multi=TRUE)`, and the function will use its internal multithreading implementation.

**Comment by gianINTERN** [comment]
thank you for the answer!
But maybe I'm doing something wrong, because it keep giving me the same error:

`> removeBimeraDenovo(tab_seq_all, method="consensus", multi=TRUE, verbose=TRUE)
Error in mclapply(mc.indices, loopFun, unqs.loop = unqs.int, allowOneOff = allowOneOff,  :
  'mc.cores' > 1 is not supported on Windows`

**Comment by gianINTERN** [comment]
sorry, i noticed that i closed the issue... i didn't mean that sorry

**Comment by benjjneb** [comment]
The error is from `mclapply`. Don't use `mclapply` -- it doesn't work on windows.

**Comment by gianINTERN** [comment]
I've managed in another way as you said, thanks a lot!
