### ISSUE TITLE
Error rates "error"

### ISSUE THREAD

**Issue by Kachn42** [benjjneb/dada2#2025]
Hi, I am trying to learn the error rates using DADA 2, i was able to do it for forward sequence, unfornutaly, fot reversed it always shows 

"Error rates could not be estimated (this is usually because of very few reads).
Error in getErrors(err, enforce = TRUE) : Error matrix is NULL."

I am working with metagenomic data. 

Thank you for any help :)

**Comment by benjjneb** [comment]
> I am working with metagenomic data.

If you are working with shotgun metagenomic data, DADA2 is not an appropriate method.

**Comment by Kachn42** [comment]
I am working with Ilumina amplicon sequencing data, 16S 515f and 926 primers, in previous dataset, the pipeline work perfectly, unfortunatelly this error  always pop up ...
