### ISSUE TITLE
assigntaxonomy 

### ISSUE THREAD

**Issue by UniAlberta** [benjjneb/dada2#2026]
Hi, I used https://doi.plutof.ut.ee/doi/10.15156/BIO/2959334 for ITS taxonomic assignment. I run taxa <- assignTaxonomy(seqtab.nochim, unite.ref, multithread = FALSE, tryRC = TRUE) and get an error of Error in .Call2("fasta_index", filexp_list, nrec, skip, seek.first.rec,  : 
  reading FASTA file E:/RDAR_raw_seq_amplicon_2023/Breton_ITS_2023/sh_general_release_all_04.04.2024.tgz: ">" expected at beginning of line 1.
Do you know how I can fix it?

**Comment by UniAlberta** [comment]
Thanks for your reply! I did so. It`s a fast file. I attached the 2 files in the zipped folder downloaded from UNITE here.
![image](https://github.com/user-attachments/assets/a0473222-6d9c-45e0-bfc7-3c120cf83b59)

**Comment by HitMonk** [comment]
Yea looks like its good. The command should work when you replaced the zipped file with the unzipped file?

**Comment by UniAlberta** [comment]
unite.ref <- "~/sh_general_release_all_04.04.2024.tgz"  
taxa <- assignTaxonomy(seqtab.nochim, unite.ref, multithread = FALSE, tryRC = TRUE)
Error in .Call2("fasta_index", filexp_list, nrec, skip, seek.first.rec,  : 
  reading FASTA file E:/RDAR_raw_seq_amplicon_2023/Breton_ITS_2023/sh_general_release_all_04.04.2024.tgz: ">" expected at beginning of line 1

**Comment by HitMonk** [comment]
`unite.ref <- "~/sh_general_release_all_04.04.2024.tgz"`

This command should be the unzipped fasta file. Not the zipped file. It should read like this:

`unite.ref <- "~/sh_general_release_04.04.2024/sh_general_release_dynamic_04.04.2024.fasta`

**Comment by UniAlberta** [comment]
Thanks for your help. I combined the 2 fasta files that were in the zipped folder and worked!
