### ISSUE TITLE
Reads Loss during DADA2 run

### ISSUE THREAD

**Issue by mentorwan** [benjjneb/dada2#2027]
We ran a full-length Pacbio DADA2 analysis. Here is a question we encountered during the process:
There is some minor read loss during the DADA2 process. For example, in one sample, stats.tsv shows 24,049 non-chimera reads, but the DADA2-generated biom file or qzv file or taxonomy table shows only 24,025 reads—a loss of 24 reads.

I previously thought the number of reads would match the number of non-chimera reads after QC. Although this read loss is minimal, I checked other samples: some show no loss while others have very few lost reads.

Maybe it’s not a significant issue. Could you clarify our understanding or provide any related information we might be missing? Thanks.

**Comment by benjjneb** [comment]
> For example, in one sample, stats.tsv shows 24,049 non-chimera reads, but the DADA2-generated biom file or qzv file or taxonomy table shows only 24,025 reads

Can you clarify what workflow you are using and how these different numbers are being generated?

**Comment by mentorwan** [comment]
The workflow we use is HiFi Full length 16S workflow: https://github.com/PacificBiosciences/HiFi-16S-workflow

The number is generated by output from this pipeline. 
Here is table in stats.tsv related to this sample:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/wany/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/wany/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">


sample-id | input | filtered | denoised | non-chimeric | percentage of   input non-chimeric
-- | -- | -- | -- | -- | --
SC830317 | 39431 | 24600 | 24132 | 24049 | 60.99



</body>

</html>


But in DADA2_table.qzv file, we can see that for this sample, only 24025 reads assigned. There are 24 reads differences.

**Comment by mentorwan** [comment]
Is it possible to check why non-chimeric reads more than biom file reads for this particular sample? If you need anything, I can provide.

**Comment by benjjneb** [comment]
We can't answer that here, as this appears to involve some step in the curated Q2 workflow you are using that is outside of the DADA2 R package. I would suggest raising an issue at the workflow GH site.

**Comment by mentorwan** [comment]
Thanks. Just want to make sure, for the standard DADA2 package, the number should be equal. Is that right?

**Comment by benjjneb** [comment]
In the dada2 R package workflow (https://benjjneb.github.io/dada2/tutorial.html) there is not a standard step after chimera removal that would remove reads.

There are lots of legitimate reasons to remove ASVs/reads at that stage (e.g. size selection, contaminant removal...), but they go beyond our standard workflow.
