### ISSUE TITLE
filterAndTrim returns no reads with least restrictive parameters

### ISSUE THREAD

**Issue by HaigBishop** [benjjneb/dada2#2029]
Hello!

First time running some 454 16S sequencing through DADA2. Zero reads from all 40 samples passthrough the filterAndTrim function with my optimal parameters. So, of course I adjusted the parameters until I go to the least restrictive parameters (see below) still with no reads making it through.

I tried reinstalling all packages and using R 4.4.1 and 4.4.0.

Quality scores are low, but that could just be a 454 thing? Besides I have tried not using filters on quality.

The raw files are available on SRA under the project ID PRJNA287742. Not my data.

Hopefully it's a stupid mistake, any ideas?

```
filter_summary <- filterAndTrim(
    fwd = forward_reads,          # Input forward reads file(s)
    filt = filtered_forward_reads, # Output filtered forward reads file(s)
    compress = TRUE,               # Compress output
    truncQ = 0,                    # No truncation based on quality score
    truncLen = 0,                  # No truncation based on length
    trimLeft = 0,                  # No trimming from the left
    trimRight = 0,                 # No trimming from the right
    maxLen = Inf,                  # No maximum length restriction
    minLen = 0,                    # No minimum length restriction
    maxN = Inf,                    # Allow any number of ambiguous base calls (Ns)
    minQ = 0,                      # No minimum quality threshold
    maxEE = Inf,                   # No filtering based on expected errors
    rm.phix = FALSE,               # Do not remove phiX sequences
    rm.lowcomplex = 0,             # Do not remove low complexity sequences
    orient.fwd = NULL,             # No orientation check
    matchIDs = FALSE,              # No ID matching between paired reads
    id.sep = "\\s",                # Default ID separator (space)
    id.field = NULL,               # Automatic ID field detection
    multithread = FALSE,           # No multithreading
    n = 1e+05,                     # Default chunk size
    OMP = TRUE,                    # Use OMP multithreading
    qualityType = "Auto",          # Auto-detect quality encoding
    verbose = TRUE                # No verbose output
)
```

End snippet of console output:
```
Read in 7196, output 0 (0%) filtered sequences.
The filter removed all reads: D:\metagenome_datasets\unprocessed_datasets\16S_40_Wiggles\fastqs\filtered\SRR2082758_filtered.fastq.gz not written.
Warning message:
In filterAndTrim(fwd = forward_reads, filt = filtered_forward_reads,  :
  No reads passed the filter. Please revisit your filtering parameters.
```
  
 
![image](https://github.com/user-attachments/assets/dc67dc83-6681-4abc-bae3-cf8f23ed5bbd)
![image](https://github.com/user-attachments/assets/335339bc-eb52-49fb-be66-9e6d7ccddbc7)

**Comment by SagarChandra07** [comment]
install this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by HaigBishop** [comment]
> install this
> 
> https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA Archive codepass: changeme If you don't have the c compliator, install it.(gcc or clang)

Not suspicious at all. At least could I have an explanation? @SagarChandra07

**Comment by benjjneb** [comment]
What is the output of `plotQualityProfile` on the original fastq files?

**Comment by HaigBishop** [comment]
@benjjneb They all look like this. Is this typical for 454 data?

![image](https://github.com/user-attachments/assets/d3d19fc5-1f01-4870-9052-663dfa0b8c96)

**Comment by HaigBishop** [comment]
@benjjneb Do you think this could be an issue with the quality scores?

**Comment by benjjneb** [comment]
> Do you think this could be an issue with the quality scores?

Yes. What do plaintext quality scores look like for the first couple reads? That could help diagnose.

**Comment by HaigBishop** [comment]
@benjjneb 

> Yes. What do plaintext quality scores look like for the first couple reads? That could help diagnose.

Thank you for your reply. They all look like this:
![image](https://github.com/user-attachments/assets/23fc6eac-9fc9-40b3-86d3-e2320eb9bc09)
Does this make this data unusable with DADA2?

**Comment by benjjneb** [comment]
Those are not real quality scores from 454 sequencing. The real quality scores have all been replaced with "!".

DADA2 is not appropriate for this kind of data. I would recommend a clustering method that does not care about sequence quality.

**Comment by HaigBishop** [comment]
Thank you for the confirmation!
