### ISSUE TITLE
Creating a DADA2 Error Model from PacBio data with low levels of sequence replication

### ISSUE THREAD

**Issue by brandon-osullivan** [benjjneb/dada2#2032]
Hi,

I am working with a long amplicon called StrainID that includes the entire 16S rRNA gene, ITS region, and a portion of the 23S rRNA gene (~2,500 bp long), and sequenced with PacBio platforms. With my samples, I typically don't see very high levels of replication. Some examples of what I see from the dereplication step are as follows:

`Encountered 13350 unique sequences from 13610 total sequences read.`
`Encountered 27129 unique sequences from 27396 total sequences read.`
`Encountered 22910 unique sequences from 23135 total sequences read.`
`Encountered 3296 unique sequences from 3325 total sequences read.`
`Encountered 18308 unique sequences from 18751 total sequences read.`

The resulting error model (using the PacBio setting) looks like this:

![OldErrorModel](https://github.com/user-attachments/assets/10634c3a-86c0-4c83-8eba-65c3c8ea2735)

However, I also had multiple samples on the run from ZYMO community standards. While these also showed low level of replication within samples (i.e. 14682 unique out of 14979 total, 9682 unique out of 10153 total), the samples themselves had the same composition, meaning there was likely a high degree of replication _between_ the samples. When generating an error model _only_ from the positive controls, the resulting error model looks like this:

![NewErrorModel](https://github.com/user-attachments/assets/93163726-d5d4-4434-8fb4-96583a591827)

Based on the responses to Issue #1877, I know that a level of duplication is needed, and as a rule of thumb this should be at least 10%. I really have two questions. First, is it appropriate to restrict the error model generation to specifically look at samples that should have higher levels of replication (ie mock communities), or even replicates of the same sample, and apply that error model to the entire sequencing run? Second, does the result of doing that with my dataset appear to be effective in terms of improving the error model to a point where DADA2 could be appropriate to use with this dataset?

Thank you for any feedback in advance.

Edit: I would also add that the samples themselves are all human saliva samples from children in one of two locations, so we expect to see some level of duplication between samples for those as well, and we use pooled settings for ASV calling, which generally seems to work pretty well.

**Comment by benjjneb** [comment]
> First, is it appropriate to restrict the error model generation to specifically look at samples that should have higher levels of replication (ie mock communities), or even replicates of the same sample, and apply that error model to the entire sequencing run?

Yes, that is even preferred _assuming_ that the mock communities (or other high replication samples) were measured in the same way, i.e. PCR and sequencing protocol.

> Second, does the result of doing that with my dataset appear to be effective in terms of improving the error model to a point where DADA2 could be appropriate to use with this dataset?

The new error model looks substantially better.
