### ISSUE TITLE
Combining Runs of Different Quality for Analysis. 

### ISSUE THREAD

**Issue by DCHed** [benjjneb/dada2#2033]
Hello,
I am losing a lot of reads at the filtering step of dada2 for one of my runs. After reading issue #1133 it seems this is okay. 
However, I want to analyse two runs together. One run loses a lot of reads, the other is of better quality. An example of the read tracker is below, where first number is input and second number is filtered:

Good run: 22856	15284
Poor run: 17345	7245
Quality plots for the reverse reads of each run is below:

![Fiona_genewizimages_reverse](https://github.com/user-attachments/assets/a6c831d0-3cbf-4f7d-8e78-7fa92ded3f1c)

My question is can I analyse these datasets together or will the quality difference cause huge abnormalities?
Thank you for your time.

**Comment by benjjneb** [comment]
> My question is can I analyse these datasets together or will the quality difference cause huge abnormalities?

You'll need to account for differences in read depth in your analyses (should do this anyway) and it's advised to also consider the "batch effect" of the run in your statistical testing. But no, this isn't expected to cause any intractable abnormalities.
