### ISSUE TITLE
why do I find forward primers in forward reads but very few reverse primers in reverse reads (illumina)?

### ISSUE THREAD

**Issue by haigthey** [benjjneb/dada2#2035]
I am analysing Illumina sequencing data (pair end) of amplicons for bacteria 16S rRNA (V3-V4). I have looked at the sequences and found the forward primer sequence in all forward sequences but almost no reverse primer sequence in the reverse sequences.. Should that be expected and what would be the explanation? 

Also, another question.. some of my samples have two or more primer sequences in tandem.. Just to explain: I have done a pre-amplification step with the same primers  and sent the amplicons for sequencing.. is possible that something wrong happened during the adaptors ligation? Or there is any other explanation?

Thanks in advance!!

**Comment by benjjneb** [comment]
The forward reads start at the forward primer, so they will always be present. The forward reads also aren't long enough to reach the reverse primer in the V3V4 amplicon which is 440-460nts long (including the primers).
