### ISSUE TITLE
filterandTrim step removing >90% of NovaSeq reads

### ISSUE THREAD

**Issue by Anto007** [benjjneb/dada2#2037]
Hi,

I just received a new Illumina NovaSeq dataset (2x250bp) that was generated using the 16S primer-pair 338F/806R. While I've analyzed many NovaSeq read datasets before, I'm unable to understand why I'm losing >90% of the reads at the dada2 `filterAndTrim` step (despite using maxEE=6). I've just got 11 libraries and below is the code that I used. I've also provided below the forward & reverse quality profile plots from running `plotQualityProfile` (and I'm unable to see any major problems there). Any inputs here will be very much appreciated.
```
filtered_out <- filterAndTrim(forward_reads, filtered_forward_reads,
                reverse_reads, filtered_reverse_reads, maxEE=c(6,6),
                maxN=0, minLen=200, truncQ=2, multithread=TRUE)
class(filtered_out)
dim(filtered_out)
filtered_out
[1] "matrix" "array" 
[1] 11  2
                  reads.in reads.out
M0093_R1.fastq.gz   384217     39814
M0094_R1.fastq.gz   439992     18059
M0095_R1.fastq.gz   240934     14542
M0096_R1.fastq.gz   393428     16472
M0097_R1.fastq.gz   342428     14603
M0098_R1.fastq.gz   515858     21686
M0099_R1.fastq.gz   451932     19083
M0100_R1.fastq.gz   277354     67085
M0101_R1.fastq.gz   518826     52428
M0102_R1.fastq.gz   296702     70999
M0103_R1.fastq.gz   212049     12894    
```

![image](https://github.com/user-attachments/assets/12cbc5a0-dd21-442c-a4a2-3798b1ea4bbc)

![image](https://github.com/user-attachments/assets/6632f2f7-78f8-4533-96a7-877d82e33b40)

**Comment by benjjneb** [comment]
> I'm unable to understand why I'm losing >90% of the reads at the dada2 filterAndTrim step (despite using maxEE=6).

It seems that ~90% of the reads in all your libraries are only ~10 nucleotides long, and thus are being lost (appropriately) to the `minLen=200` filter.

In the `plotQualityProfile` plots, the red line shows the proportion of reads that are as long or longer than that nucleotide position. The sharp drop off early in the red line shows that the large majority of reads only extend a few bases.

This is either the result of a mostly failed library preparation step, or there is some sort of pre-processing that happened before you got these sequences that created this.

**Comment by Anto007** [comment]
Many thanks @benjjneb for your clear explanation of the problem. I've now received a newer release of sequence data for the same libraries from the sequencing company and this problem seems to have gone away. Thanks a zillion again for taking the time to respond.
