### ISSUE TITLE
Flat and "gappy" error model for PacBio Revio Kinnex 16S 

### ISSUE THREAD

**Issue by mgabriell1** [benjjneb/dada2#2041]
Hi,
First of all thanks for developing and maintaining DADA2!
I want to analyze the 16S rRNA sequences obtained from a PacBio Revio machine which were prepared using the Kinnex library preparation (the sequencing center provided me with already the demultiplexed fastq files). 

I'm testing the workflow following the https://benjjneb.github.io/LRASManuscript/LRASms_fecal.html tutorial and using DADA2 v1.30.0 and a random subset of samples subsampled to 20K reads. 

Even though the average Phred score is above 20 in >95% of the reads, the filtering step imposing `maxEE=2` removes approximately 55% of the reads which is similar to what seen in https://github.com/benjjneb/dada2/issues/2013 . That still leaves duplication rates between 20. and 50% (i.e., unique reads/total reads).

When I move to the error model estimation I find these profiles (convergence was obtained after 6 rounds). What I see "odd" is:
- The profiles are mostly "flat"
- Most points are at 0 with only few ones at greater values
- A big "hook" is present in all transitions
- Not visible in the picture, but the procedures gives a warning regarding `The max qual score of 93 was not detected. Using standard error fitting.` which I believe is due to the fact that the fastq files do not have a constant and maximum Phred score, but actual values

Are any of those points "worrisome"?
![image](https://github.com/user-attachments/assets/73806713-188f-48eb-8655-6eb33cefa334)

Playing with the parameters, I noticed that setting `nbases=1e9` (10 times more than default) gives similar profiles, but there seem to be more points not equal to 0 (especially in the 30-40 quality score range. 
Would this suggest that I need to increase the value of `nbases` even more to "fill" the curves?
![image](https://github.com/user-attachments/assets/ecbe1e3b-a889-41c2-bd96-3cfc6ad31fd9)

Finally, I saw that it was suggested the possibility to enforce monotonicity to the error profiles in cases hooks are present (https://github.com/benjjneb/dada2/issues/975). How would that be possible?

Thanks in advance for the support!
Cheers,

Marco

**Comment by mgabriell1** [comment]
Sorry for the double posting, but I realized that I missed this (https://github.com/benjjneb/dada2/issues/1892) issue and I've tried the error function mentioned there.

So my the Phred scale in my Revio data extends only to to Q40 (as highlighted by the warning in the post above).

The error profiles that I obtain are the following. The points are still quire "gappy" with a lot of 0s (increasing `nbases` again helps), but the profiles are less flat than before (even though the points can be quite flat as in `G2C` the estimated profile has a negative trend)
![image](https://github.com/user-attachments/assets/0100e29a-7778-4d66-afed-3a80af6912b2)

I hope this is useful!

**Comment by cjfields** [comment]
We've found the same if your sequencing facility is providing quality binned data from the Revio (default); in fact this seems to be generally better for any FASTQ binned data (Illumina or PacBio).  If your facility is using full quality ranges, which can be set in SMRTLink, then you'd need to use the standard PacBio model.

**Comment by mgabriell1** [comment]
Thanks for sharing your experiences!
I guess one option at this point would be to include `mod4` among the available error functions with in the R package.

**Comment by cjfields** [comment]
@mgabriell1 note that @benjjneb just released a new error model for binned quality data in the master branch, might be worth a try
