### ISSUE TITLE
Increase sensitivity towards rare clades

### ISSUE THREAD

**Issue by mgabriell1** [benjjneb/dada2#2042]
Hi,
Thanks again for maintaining DADA2!
I have a question regarding the sensitivity of the pipeline, especially in the case there are clades of specific interest which might be rare.

From what I have understood here (https://github.com/benjjneb/dada2/issues/315) relaxing the `OMEGA_A` threshold to get more rare ASVs might not be the best approach as this would potentially generate more false positives than other. Correct?

Another option would be to pool or pseudo-pool the samples to rescue rare ASVs from samples in which they have low read counts.

I wonder if in addition to this it makes sense to include as priors the 16S sequences of the species of the clade of interest (similar to what shown here [https://benjjneb.github.io/dada2/pseudo.html], but with multiple sequences).
Do you expect that this would be a problem in case of a large (e.g., 50-100) number of priors?
Also, extending this even further, what would be the outcome to introduce as prior the sequences from an entire (dereplicated) database? 

Theoretically this would provide a mix between a denovo and a reference-guided approach, but I don't know whether a high number of priors will impact the detection of ASVs not included in those priors.
What is your opinion?

Thanks for the support!

Marco

**Comment by benjjneb** [comment]
What you are describing is close to the vision we had when introducing the `prior` argument. I almost completely support what you are suggesting. The one caveatI would make is that I think it usually make more sense to use as priors a more limited set of sequences than a bacteria-wide reference database like Silva. Instead it should be something environment-specific. "Pseudo-pooling" is basically an implementation of that idea: The set of priors is the set of sequences detected in other samples from the same study at least twice.

Also note the `DETECTS_SINGLETONS=TRUE` option. This will improve sensitivity to rare per-sample variants, but at the cost of more cruft getting through (lots of chimeras appear in the singleton class).

**Comment by mgabriell1** [comment]
Thanks for sharing your thoughts!
I will try setting as `prior` the dereplicated sequences from a clade of interest and compare the results without this.
Indeed, the idea to use a database was something that came up only while opening the issue, but didn't really think to do this.
Thanks again!

Marco
