### ISSUE TITLE
Dereplication

### ISSUE THREAD

**Issue by gabrieltedone** [benjjneb/dada2#2043]
Hi! I am back again running a dada2 script again after some time and I have questions regarding the dereplication step. 

The scripts I have run in the past followed these steps: filtering and trimming > learn error rates > dereplication > sample inference ... 

However, I have seen the most recent dada2 pipeline tutorial (https://benjjneb.github.io/dada2/tutorial.html) completely skips the dereplication step (with the derepFastq() function) while older tutorials do implement dereplication (https://benjjneb.github.io/dada2/tutorial_1_8.html).

I wonder now: should I dereplicate? Is this step indispensable? The dada() function documentation says that dada() needs dereplicated .fastq reads as input. Is dereplication skipped in the newer tutorial due to how the function averages quality scores? Also, I have noticed that excecuting derepFastq() is straining the machine's RAM memory. 

Thanks in advance,

Gabriel

**Comment by benjjneb** [comment]
See https://github.com/benjjneb/dada2/issues/1095#issuecomment-671333174

> I wonder now: should I dereplicate? Is this step indispensable?

No. Since about 5 years now `dada` and `learnErrors` dereplicate on-the-fly, which is a major advantage in memory usage.
