### ISSUE TITLE
Assign taxonomy error 

### ISSUE THREAD

**Issue by DimitraIoli** [benjjneb/dada2#2046]
Hi!
I am working on 18S data from marine samples. I used Miseq2x300 and I am using the Silva database v138.1.
I am comparing two different datasets and for this, I need to acquire the taxonomy based on the 138.1 version. 

[SILVA_138.1_SSURef_NR99_tax_NO_ID_EUK_silva.fasta.gz](https://github.com/user-attachments/files/17555784/SILVA_138.1_SSURef_NR99_tax_NO_ID_EUK_silva.fasta.gz), downloaded from silva archive. I kept only eukaryotes in SILVA.

However, I encounter the following error:
Error in C_assign_taxonomy2(seqs, rc(seqs), refs, ref.to.genus, tax.mat.int,  : 
  Invalid map from references to genus.
Calls: assignTaxonomy -> C_assign_taxonomy2
In addition: Warning messages:
1: In .Call2("fasta_index", filexp_list, nrec, skip, seek.first.rec,  :
  reading FASTA file path/SILVA_138.1_SSURef_NR99_tax_NO_ID_EUK_silva.fasta.gz: ignored 26602763 invalid one-letter sequence codes
2: In matrix(unlist(strsplit(genus.unq, ";")), ncol = td, byrow = TRUE) :
  data length [684651] is not a sub-multiple or multiple of the number of rows [34233]

I looked at similar issues (#1429, #691), but they don't correspond to my problem.

Here is the script that I used in a Linux server:
#!/usr/bin/env Rscript
###Assign taxo
library(dada2)
setwd("path")
seqtab_nochim<-readRDS("path/2410_seqtabnochim.rds")
taxa <- assignTaxonomy(seqtab_nochim, "path/SILVA_138.1_SSURef_NR99_tax_NO_ID_EUK_silva.fasta.gz",
                       multithread=T,taxLevels = c("Domain","Kingdom","Supergroup","Division","Class","Order","Family","Genus","Species"))
head(seqtab_nochim)
# giving our seq headers more manageable names (ASV_1, ASV_2...)
asv_seqs <- colnames(seqtab_nochim)
asv_headers <- vector(dim(seqtab_nochim)[2], mode="character")

for (i in 1:dim(seqtab_nochim)[2]) {
  asv_headers[i] <- paste(">ASV", i, sep="_")
}

# making and writing out a fasta of our final ASV seqs:
asv_fasta <- c(rbind(asv_headers, asv_seqs))
write(asv_fasta, "path/2410_ASVs_.fa")

# count table:
asv_tab <- t(seqtab_nochim)
row.names(asv_tab) <- sub(">", "", asv_headers)
write.table(asv_tab, "path/2410_ASVs_counts.txt", sep="\t", quote=F)

# tax table:
asv_tax <- taxa
row.names(asv_tax) <- sub(">", "", asv_headers)
write.table(asv_tax, "path/2410_ASVs_taxonomy.txt", sep="\t", quote=F)
#!/usr/bin/env Rscript

Thanks in advance for your help and all your work for DADA2.
Best wishes,
Ioli

**Comment by benjjneb** [comment]
The file you downloaded is not formatted to work with `assignTaxonomy`.

You can find appropriately formatted versions of Silva here: https://benjjneb.github.io/dada2/training.html

**Comment by DimitraIoli** [comment]
Dear Benjamin,
Thank you for getting back to me. The 138.1  versionin dada2 focuses on prokaryotes, but I'm interested in Eukaryotes, and there is no info for species. I am wondering if it is possible to customize this version [SILVA_138.1_SSURef_NR99_tax_NO_ID_EUK_silva.fasta.gz](https://github.com/user-attachments/files/17555784/SILVA_138.1_SSURef_NR99_tax_NO_ID_EUK_silva.fasta.gz), in dada2 for eukaryotes.
Thank you!

**Comment by benjjneb** [comment]
There are Eukaryote friendly versions of Silva 132 and 128 available from our taxonomic training reference page.

You can re-run the code we use to digest Silva to the `assignTaxonomy` compatible format with some different choices to generate a Eukaryote appropriate version. The code is here: https://github.com/benjjneb/dada2/blob/master/R/taxonomy.R#L501

The two sections to modify are the part where the data is subsetted to the Bacteria and Archaea: https://github.com/benjjneb/dada2/blob/master/R/taxonomy.R#L518

And the part where we add back in 100 random Euks to be an outgroup to the Bact/Archaea: https://github.com/benjjneb/dada2/blob/master/R/taxonomy.R#L580
