### ISSUE TITLE
trimLeft and trimRight documentation?

### ISSUE THREAD

**Issue by gerverska** [benjjneb/dada2#2050]
Hello @benjjneb,

@aneat and I were going through the documentation of `filterAndTrim`, and we noticed that the entries for `trimLeft` and `trimRight` do not indicate that a two-part vector can be supplied as an argument (as mentioned in #863) for separate trimming of paired reads:

> (Optional). Default 0. The number of nucleotides to remove from the end of each read. If both truncLen and trimRight are provided, truncation will be performed after trimRight is enforced.

As written, it seems like only a single-length argument is accepted and applied to both forward and reverse reads. Additionally, the provided examples are only single-length. If other options besides `trimLeft` and `trimRight` accept two-part vectors as arguments, it'd probably be good to include these too (I assume all quality/trimming arguments have this capacity?).

**Comment by benjjneb** [comment]
If you look at the docmentation `filterAndTrim` there is "header" text after the compress argument:

```
FILTERING AND TRIMMING PARAMETERS ———

Note: When filtering paired reads... If a length 1 vector is provided, the same parameter value is used for the forward and reverse reads. If a length 2 vector is provided, the first value is used for the forward reads, and the second for the reverse reads.
```

It's not very elegant, but this is the attempt to explain that all of the arguments in the subsequent block have this length-2 option.

**Comment by gerverska** [comment]
Thanks @benjjneb -- honestly, that description's sufficient. I think I was just being thick! Sorry for false alarm--no issue here.
