### ISSUE TITLE
trnL through ITS pipeline : variable and sometimes significant loss of sequences upon merging

### ISSUE THREAD

**Issue by jorondo1** [benjjneb/dada2#2051]
Hi,
I am using the ITS pipeline to process 220 trnL amplicon samples. As with ITS, trnL are quite variable in length (something like 300 to 700bp) across plants. We used 300bp paired-end samples, but several samples are loosing a high proportion of samples during merging (see figure for the distribution of % reads lost per sample). From reading through as many threads as I could find here, this is to be expected, because we won't be able to merge reads from trnLs that are over ~500 bp if we account for 20bp primers and trimming.  

![bildschirmfoto_2024-11-10_um_11 45 19___am](https://github.com/user-attachments/assets/02fadc12-6f6d-4b83-80b1-32a54029317b)

In a previous thread you pointed to [this article](https://doi.org/10.1016/j.funeco.2019.03.005) where the authors suggest using forward reads only with ITS sequences, to resolve this problem. Since we don't want to throw away half our sequences, I was wondering if it could be a good idea to simply salvage the reads that do not merge and use their forward sequences only, in addition to the sequences that did merge. I'm not sure yet how to do this, but before figuring it out, I'd love to get your opinion on this.

Thanks in advance,
Jonathan

**Comment by jorondo1** [comment]
I found this issue #1464 where you advise against. Sorry for the duplicate issue, I'll do a better search next time before posting! I understand that you do not recommend to returnRejects because this could introduce biases downstream. 

I'm trying to understand how justConcatenate would interact with assignTaxonomy. If my sequences have 10 N's between the f-r, does assignTaxonomy expect there to be 10 nt between these two sequence segments?

**Comment by benjjneb** [comment]
> I'm trying to understand how justConcatenate would interact with assignTaxonomy. If my sequences have 10 N's between the f-r, does assignTaxonomy expect there to be 10 nt between these two sequence segments?

The downstream functions in the dada2 R package handle the 10-N region gracefully. `assignTaxonomy` simply ignores it and performs classification using the rest of the sequence (the underlying algorithm "shreds" the sequence into 8-mers, and the 8-mers with Ns are dropped).

**Comment by jorondo1** [comment]
Thanks a lot Ben! Cheers
