### ISSUE TITLE
running the pipeline with reverse reads only (only R2 available)?

### ISSUE THREAD

**Issue by gabrielet** [benjjneb/dada2#2056]
to keep it short, we performed a sequencing run with both bacteria and fungal dna, but fungal R1 turned out extremely weird. we can see a drop in quality, almost a vertical drop, at around 120bp (half the amplicon) with quality decreasing from a normal range within 30-40 to around 20. never seen anything similar and we don't know yet what happened. other libraries in the same run turned out perfectly normal.

question is: if i want to run dada2 on the reverse reads only, do i need to reverse complement the fastq files and treat them as forward reads? i run the analysis as-is treating them as they were R1, i.e. forward, reads. the only detail is that when assigning the taxonomy is to tell the function to try the reverse complement, i suppose. in that case all should be fine. am i correct?

thanks!

**Comment by benjjneb** [comment]
> question is: if i want to run dada2 on the reverse reads only, do i need to reverse complement the fastq files and treat them as forward reads? i run the analysis as-is treating them as they were R1, i.e. forward, reads. the only detail is that when assigning the taxonomy is to tell the function to try the reverse complement, i suppose. in that case all should be fine. am i correct?

Yep. Just run the reverse reads as they are, and include `tryRC=TRUE` in the taxonomic assignment calls.
