### ISSUE TITLE
question about using derepFastq function

### ISSUE THREAD

**Issue by danielsangarci** [benjjneb/dada2#2059]
Hi @benjjneb 

I am using dada2 to perform my 16S V3-V4 bioinformatics. I read you advice using derepFastq to reduce the computational time, it actually works very well. However, I was also said derepFastq reduce the accuracy. Is it actually true?

Thank you so much in advance,
Dani

**Comment by benjjneb** [comment]
Calling `derepFastq` yourself won't have any impact on your results. If you don't call it yourself, the `dada` and `learnErrors` functions call it themselves anyway.

The memory savings of not calling `derepFastq` yourself are almost always preferred over the small gain in computation time. The current recommended workflow (no `derepFastq` call) is on our tutorial: https://benjjneb.github.io/dada2/tutorial.html

**Comment by danielsangarci** [comment]
Thank you so much for your answer. Alright, I will not call derepFastq in that case.
