### ISSUE TITLE
Should I trim the primers for dada2 workflow?

### ISSUE THREAD

**Issue by danielsangarci** [benjjneb/dada2#2060]
Hi @benjjneb 

I am using dada2 to perform my 16S V3-V4 bioinformatics. I read dada2 require trimming the primers for a correct workflow, but I was said not trimming the primers is better because you have extra information in the sequences. Is it actually correct if I leave the primers in my sequences? If not I will remove them using Cutadapt.

Thank you so much in advance,
Dani

**Comment by benjjneb** [comment]
Yes you should trim primers if they are present on the sequencing reads. They are not extra information -- the primer sequences are put in by the experimenter, they do not come from the sample.

If, as is usual, primers are at the start of your reads and a fixed length, `filterAndTrim(..., trimLeft=c(FWD_PRIMER_LEN, REV_PRIMER_LEN))` is the recommended way to remove them. cutadapt is a fine alternative though.

**Comment by danielsangarci** [comment]
Thank you so much for your answer.

Not only 16S but I also have ITS amplicons, so I will use cutadapt to remove the primers from both of them to be consistent with the workflow.
