### ISSUE TITLE
reads lost in sample inference procedure 

### ISSUE THREAD

**Issue by Yiqihao** [benjjneb/dada2#207]
Hi, 
We are using DADA2 to analyse CF lung microbiome data, 16S sequences from illunima platform.

My understanding is, the sample inference procedure is to assign every read (all of which are of high-quality after filtering) into OTUs,

But we found that we lost lots and lots of reads in sample inference step. For example, we have around 70,000 number of sequences in a certain sample (after filtering and trimming), after error learning and sample inference, there are only 36,000 number of sequences in the final OTU table.

I am really confused, where are half of our reads gone? Please see the command we use below.

library(dada2); packageVersion("dada2")
library(ShortRead);

filtpath <- "~/data/LAB/New_Batch/filtered/" 
fns <- list.files(filtpath, full.names = TRUE)
filts <- fns[grepl("fastq.gz$", fns)] # CHANGE if different file extensions   sample.names <- sapply(strsplit(basename(filts), ".f"), `[`, 1) # Assumes           filename = samplename_XXX.fastq.gz
names(filts) <- sample.names

#------------------------------------------------

set.seed(100)
filts.learn <- sample(filts, 25) 
drp.learn <- derepFastq(filts.learn)
dd.learn <- dada(drp.learn, err=NULL, selfConsist=TRUE, multithread=TRUE)
err <- dd.learn[[1]]$err_out
rm(drp.learn);rm(dd.learn)

# Sample inference
dds <- vector("list", length(sample.names))
names(dds) <- sample.names
for(sam in sample.names) {
  cat("Processing:", sam, "\n")
  derep <- derepFastq(filts[[sam]])
  dds[[sam]] <- dada(derep, err=err, multithread=TRUE)
}
rm(derep)
# Construct sequence table and remove chimeras
seqtab <- makeSequenceTable(dds)
seqtab <- removeBimeraDenovo(seqtab, multithread=TRUE)
saveRDS(seqtab, "~/data/LAB/New_Batch/filtered/DADA_246.rds")
uniquesToFasta(seqtab, "~/data/LAB/New_Batch/filtered/New_DADA2_246.fasta")
seqtab <- t(seqtab)#transpose the table
seqtab <- cbind('#OTUID' = rownames(seqtab), seqtab)
write.table(seqtab, "~/data/LAB/New_Batch/filtered/dada2_OTU_table_246.txt", sep='\t', row.names=FALSE, quote=FALSE)

Many thanks for your help!

**Comment by benjjneb** [comment]
Probably the reads are getting removed in the chimera removal step.
Could you report the results for the following:

```S
seqtab <- makeSequenceTable(dds)
seqtab.nochim <- removeBimeraDenovo(seqtab, multithread=TRUE, verbose=TRUE)
summary(rowSums(seqtab)/rowSums(seqtab.nochim))
```

Also, the following (this code assumes dada2 version 1.3.4):
```S
seqtab.noconc <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
summary(rowSums(seqtab)/rowSums(seqtab.noconc))
```

If you have a <1.3.4 version of dada2, change `method` to `tableMethod` (and the multithreading won't work, but won't harm anything).

**Comment by kkapuria3** [comment]
Hello,

I am writing in context with issue posted by Yiqihao. We are currently using dada2 version 1.3.0.

I am posting the following results for commands mentioned above,

`seqtab.nochim <- removeBimeraDenovo(seqtab, verbose=TRUE)`
Identified 3266 bimeras out of 4153 input sequences.

`summary(rowSums(seqtab.nochim)/rowSums(seqtab))`
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.3954  0.4835  0.5273  0.6056  0.7230  0.9719




`seqtab.noconc <- removeBimeraDenovo(seqtab, tableMethod="consensus", verbose=TRUE)`
Identified 2711 bimeras out of 4153 input sequences.

`summary(rowSums(seqtab.noconc)/rowSums(seqtab))`
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.3954  0.4835  0.5273  0.6056  0.7230  0.9719

**Comment by benjjneb** [comment]
Can you post the output of the following:

```
dada2:::pfasta(head(colnames(seqtab)))
```

Also, can you double-check the posted output of `summary(rowSums(seqtab.noconc)/rowSums(seqtab))`, as it shouldn't be identical to the output when using `seqtab.nochim`.

**Comment by kkapuria3** [comment]
I have checked with the results of second run and this time, the most number of reads are surviving, i.e for,

`seqtab.noconc <- removeBimeraDenovo(seqtab, tableMethod="consensus", verbose=TRUE) `

If we talk in context with the particular sample that was giving out low reads, out of ~75,000 sequences; 72,200 sequences are inferred this time. But number of OTU's are almost twice as inferred before. 

I was wondering if you can explain me happening between these two different methods.

Many Thanks ! 👍

**Comment by kkapuria3** [comment]
Hello,

I am so sorry for that. Here is the updated reply,

`seqtab.nochim <- removeBimeraDenovo(seqtab, verbose=TRUE)`
Identified 3266 bimeras out of 4153 input sequences.
`
summary(rowSums(seqtab.nochim)/rowSums(seqtab))`
Min. 1st Qu. Median Mean 3rd Qu. Max.
0.3954 0.4835 0.5273 0.6056 0.7230 0.9719

`seqtab.noconc <- removeBimeraDenovo(seqtab, tableMethod="consensus", verbose=TRUE)`
Identified 2711 bimeras out of 4153 input sequences.

`summary(rowSums(seqtab.noconc)/rowSums(seqtab))`
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.7651  0.9023  0.9429  0.9323  0.9616  0.9927

**Comment by benjjneb** [comment]
The default chimera removal method pools all reads together, and then removes chimeras that can be made from two more abundant parents in the pool. We are starting to see, at least in some communities and particularly in sequencing large datasets that spans multiple V-regions, that there are a significant number of FP chimeras from this approach. These FPs are due to real variants that can be constructed as exact chimeras from other real variants.

The "consensus" method identifies chimeras in each sample individually, and then makes a consensus decision on whether each variant was identified in a high enough fraction of samples to indicate that it is chimeric. This appears to be performing significantly better on the problematic datasets, as real variants that are flagged in the pool are not flagged in enough individual samples to be classified as chimeric. In essence we are using more information, the distribution of abundances across samples.

We will be recommending "consensus" chimera detection as the default method in our next release (coming in a month or so) but there is no reason to wait for it here.

**Comment by kkapuria3** [comment]
Thank you so much for your help. My issue is resolved here. 

Much Thanks
