### ISSUE TITLE
dada2 error model clarification

### ISSUE THREAD

**Issue by ramiroricardo** [benjjneb/dada2#208]
Dear all,

I have been running dada2 on a dataset that I had previously analysed with Qiime and then using phyloseq to compare the "otu" tables, with different metrics. All seems to be running smoothly, but I would like to understand a bit better the algorithm, particularly the error correction model. As I have a basic knowledge of bioinformatics, it is unclear to me from the paper if the model discards reads that are plausible to have sequencing errors or if the algorithm aims to correct those errors. Could someone please clarify?

Thanks for any help,

Ramiro

**Comment by benjjneb** [comment]
Discarding reads only happens in filtering/merging/chimera-removal steps. The sequence inference step (the `dada` call) will assign all reads to an error-corrected sequence.

**Comment by ramiroricardo** [comment]
thanks @benjjneb for your reply.  So, if I am understanding the paper well, if the abundance p-value is above a certain value, it indicates that those reads could contain errors. How will the `dada` call then correct for these errors?

**Comment by benjjneb** [comment]
The p-value is testing how plausible it is for reads to have been produced as errors by the center of the partition they are in. If the abundance p-value is non-significant, those reads are corrected by replacing them with the sequence at the center of their partition.

**Comment by benjjneb** [comment]
Feel free to reopen if you have more questions.
