### ISSUE TITLE
Primer Removal before DADA2

### ISSUE THREAD

**Issue by Ran0109** [benjjneb/dada2#209]
The DADA2 workflow assumes that primers have been removed from the FASTQs. I currently use the trimLeft = <no of bases of the primer> to remove my PCR primers from the demultiplexed FASTQs at the filtering stage. What do others do?

**Comment by benjjneb** [comment]
`trimLeft` is an appropriate way to remove primers, as long as you know the length of your primer.

We recommend trimmomatic and cutadapt, as those programs are more feature-rich, but for standard setups `trimLeft` will get the job done.

**Comment by fanli-gcb** [comment]
We use the EMP protocol for V4 (http://www.earthmicrobiome.org/protocols-and-standards/16s/) so the primers are actually never sequenced.
