### ISSUE TITLE
Duplicate sequences in merged output.

### ISSUE THREAD

**Issue by bashma** [benjjneb/dada2#213]
Hi,
I'm running dada2 according to the SOP, except that I removed primers using cutadapt. When running dada
```{r}
mergers <- vector("list", length(sample.names))
names(mergers) <- sample.names
for(sam in sample.names) {
  cat("Processing:", sam, "\n")
    derepF <- derepFastq(filtFs[[sam]])
    ddF <- dada(derepF, err=errF, multithread=8)
    derepR <- derepFastq(filtRs[[sam]])
    ddR <- dada(derepR, err=errR, multithread=8)
    merger <- mergePairs(ddF, derepF, ddR, derepR)
    mergers[[sam]] <- merger
}
rm(derepF); rm(derepR)
```
I get the following output:

```
Processing: P009 
Sample 1 - 46402 reads in 20600 unique sequences.

Sample 1 - 46402 reads in 10970 unique sequences.

Duplicate sequences in merged output.
Processing: P010 
Sample 1 - 57524 reads in 29250 unique sequences.

Sample 1 - 57524 reads in 16924 unique sequences.

Duplicate sequences in merged output.
Processing: P011 
Sample 1 - 64301 reads in 33825 unique sequences.

Sample 1 - 64301 reads in 18654 unique sequences.

Processing: P012 
Sample 1 - 55623 reads in 27345 unique sequences.

Sample 1 - 55623 reads in 14995 unique sequences.

Processing: P013 
Sample 1 - 69922 reads in 41237 unique sequences.

Sample 1 - 69922 reads in 22596 unique sequences.

Processing: P014 
Sample 1 - 72424 reads in 41253 unique sequences.

Sample 1 - 72424 reads in 22365 unique sequences.

Duplicate sequences in merged output.
```
Can I ignore this? when I don't remove primers I don't get this warning

**Comment by benjjneb** [comment]
You should be able to ignore that. The duplicate sequences will be combined when you call `makeSequenceTable` later.

I'm curious as to what is going on though, would you mind sharing the post-cutadapt fastq files for one sample?

**Comment by bashma** [comment]
I ran cutadapt using the following code:
```{r}
#enter primer sequences
fwdp <-"GTGYCAGCMGCCGCGGTAA" #forward
revp <-"GGACTACNVGGGTWTCTAAT" #reverse

cat("#!/bin/bash \n",file="cutadapt.sh")
cat("\nexport _JAVA_OPTIONS=\"-Xmx16G\"\n",file="cutadapt.sh",append=TRUE)
cat("\nfor FWD in $(ls *R1*); do",file="cutadapt.sh",append=TRUE)
cat("\n\tBASE=$(echo $FWD | cut -d \"_\" -f1);",file="cutadapt.sh",append=TRUE)
cat("\n\tREV=$(echo $FWD | sed 's/R1/R2/g');",file="cutadapt.sh",append=TRUE)
cat("\n\tcutadapt -g ", fwdp, " -G ",revp, " -o $BASE\"_P1.fastq.gz\" -p $BASE\"_P2.fastq.gz\" $FWD $REV;",file="cutadapt.sh",append=TRUE)
cat("\ndone",file="cutadapt.sh",append=TRUE)

```

'cutadapt.sh' should contain following lines:

```{r}
file.show("cutadapt.sh")
```
```
#!/bin/bash

export _JAVA_OPTIONS="-Xmx16G"

for FWD in $(ls *R1*); do
	BASE=$(echo $FWD | cut -d "_" -f1);
	REV=$(echo $FWD | sed 's/R1/R2/g');
	cutadapt -g GTGYCAGCMGCCGCGGTAA -G GGACTACNVGGGTWTCTAAT -o $BASE"_P1.fastq.gz" -p $BASE"_P2.fastq.gz" $FWD $REV;
done
```
where -g contains forward and -G the reverse primer sequence.
```{r, results='hide'}
x <- "sh cutadapt.sh"
system(x)
```

I ran the workflow without prior primer removal and the `sum(seqtab.nochim)/sum(seqtab)` ratio was at 0.4667. After I primer removal I got only 0.151788. 
you're right. during the `makeSequenceTable` step I got:
```
Duplicate sequences detected and merged.
The sequences being tabled vary in length.
```
I emailed you the post-cutadapt files. 

Thanks a lot for providing such a great tool and support!

**Comment by benjjneb** [comment]
There is a problem here, you still have primer sequence on your sequencing reads.

The issue is that your **300nt** reads are longer than the gene region you are sequencing (~250nts), thus the reads are extending past the target sequence and into the opposite primer. The cutadapt command you ran removed the primer sequence at the start of the F/R reads, but did not remove the primer sequences at the end of the F/R reads.

The easiest way to fix this is to truncate your cutadapted reads at a length shorter than the amplicon. The following worked quite well on the sample you shared as an example:

```
fastqPairedFilter(c(fnF, fnR), c(filtF, filtR), maxEE=2, truncLen=c(245, 230), rm.phix=TRUE)
```

There is probably also be a way to remove the primers at the ends of the reads with cutadapt itself, but I don't know it off hand.

**Comment by bashma** [comment]
thank you for the fast response. I'll give it a try!

Cutadapt offers trimming on both sides using `-b` and `-B` instead of `-g` and `-G`, respectively!

**Comment by bashma** [comment]
I reran the analysis and even with the suggested filter/trimming options, `sum(seqtab.nochim)/sum(seqtab)` ratio is 0.6670231 (the best ratio for all tested parameters). That means that 33% of my reads are chimeric. Isn't that too much?

**Comment by benjjneb** [comment]
Q1: Are we 100% sure that all primers are now gone? (You cutadapted the starting primers, and then filtered with `truncLen=c(245,230)`?)

Q2: Can you try the following:

```
seqtab.noconc <- removeBimeraDenovo(seqtab, tableMethod="consensus")
sum(seqtab.noconc)/sum(seqtab)
```

**Comment by bashma** [comment]
Q1: Yes. I ran cutadapt followed by `truncLen=c(245,230)`

Q2: 
```
> seqtab.noconc <- removeBimeraDenovo(seqtab, tableMethod="consensus")
Identified 6030 bimeras out of 7015 input sequences.
> sum(seqtab.noconc)/sum(seqtab)
[1] 0.6823825
```

**Comment by benjjneb** [comment]
It looks like you have a very high chimera rate, to the best of our ability to detect. I would just use the chimera filtered data.

Chimera rates vary dramatically based on your PCR protocols and community composition. 30% chimeras is not impossible, although it is very high.

In future experiments I would recommend extending the elongation time in your PCR protocol and reducing the number of cycles, which should bring down chimera formation rates. Additionally, make sure you don't exhaust any components of your reagents prior to PCR finishing.
