### ISSUE TITLE
per-sample chimera filtering

### ISSUE THREAD

**Issue by fanli-gcb** [benjjneb/dada2#218]
My understanding is that chimeras come from incomplete extension during the PCR step(s). Since each sample is generally PCR'ed separately in triplicate, it seems that only sequences from a particular sample should be considered in the pool of possible parents.

The 'consensus' method for removeBimeraDenovo implements this but then uses a consensus approach (a sequence flagged in a sufficient percentage of the samples gets removed) to remove entire sequences. Would it make more sense to instead zero-out sequences flagged on a per-sample basis? 

In other words, is it possible that an identical sequence could be chimeric in one sample but not in another? I think in general for bimeras derived from two unrelated species, we can safely say no, but here is an example where I had a sequence get flagged as chimeric from two very similar parents:

```
seq <- "AAGTAGAACGCTGAGAACTGGTGCTTGCACCGGTTCAAGGAGTTGCGAACGGGTGAGTAACGCGTAGGTAACCTACCTCATAGCGGGGGATAACTATTGGAAACGATAGCTAATACCGCATAAGAGAGACTAACGCATGTTAGTAATTTAAAAGGGGCAATTGCTCCACTATGAGATGGACCTGCGTTGTATTAGCTAGTTGGTGAGGTAAAGGCTCACCAAGGCGACGATACATAGCCGACCTGAGAGGGTGATCGGCC"
parent1 <- "AAGTAGAACGCTGAGAACTGGTGCTTGCACCGGTTCAAGGAGTTGCGAACGGGTGAGTAACGCGTAGGTAACCTACCTCATAGCGGGGGATAACTATTGGAAACGATAGCTAATACCGCATAAGAGAGACTAACGCATGTTAGTAATTxAAAAGGGGCAATTGCTCCACTATGAGATGGACCTGCGTTGTATTAGCTAGTTGGTGAGGTAAAGGCTCACCAAGGCGACGATACATAGCCGACCTGAGAGGGTGATCGGCCA"
parent2 <- 
"AAGTAGAACGCTGAGAACTGGTGCTTGCACCGGTTCAAGGAGTTGCGAACGGGTGAGTAACGCGTAGGTAACCTACCTCATAGCGGGGGATAACTATTGGAAACGATAGCTAATACCGCATAAAAGAGACTAACGCATGTTAGTAATTTAAAAGGGGCAATTGCTCCACTATGAGATGGACCTGCGTTGTATTAGCTAGTTGGTGAGGTAAAGGCTCACCAAGGCGACGATACATAGCCGACCTGAGAGGGTGATCGGCC"
isBimera(seq, c(parent1,parent2)) # TRUE

```
`parent1` has a deleted T at position 149 relative to `seq`. `parent2` has an A->G mismatch at position 124 relative to `seq`.

**Comment by benjjneb** [comment]
Chimera removal is not a completely solved problem. Robert Edgar has posted an article on the difficulties related to chimera removal for methods that resolves sequences exactly (like DADA2). While these methods trivialize the calling of chimeras between reasonly well-separated sequences, they also reveal the larger numbers of chimears between closely related sequences.

> is it possible that an identical sequence could be chimeric in one sample but not in another?

It is possible. We know that some real sequences can be constructed as chimeras of other real sequences, which could lead to this situation. In general, I believe this is a relatively minor issue though, and the best choice is to treat sequence variants uniformly across your study.

However, if you want to remove chimeras from each sample individually, you certainly can, yo will just have to do a bit of R coding. Just loop through each sample, call `isBimeraDenovo` on the sample (after removing the zero entries) and then zero out the abundances of the flagged SVs.

I don't generally recommend that approach, but it is an option, and in some special circumstances it could even be the best option.

**Comment by fanli-gcb** [comment]
> While the accuracy of DADA2 trivializes the calling of chimeras between reasonably well-separated sequences, it also reveals the larger numbers of chimears between closely related sequences that were previously hidden by lumping OTUs.

Agree completely - it is the latter situation that I'm dealing with right now. And thanks for pointing out the preprint. I'm still amazed that 'perfect fakes' are a majority!

> In general, I believe this is a relatively minor issue though, and the best choice is to treat sequence variants uniformly across your study.

I understand that it is generally a minor issue, but I can see edge cases where for example a sequence that dominates its sample could be flagged as chimeric due to its parents being more abundant in all other samples.

> However, if you want to remove chimeras from each sample individually you can, but you will have to do a bit of R coding. Loop through each sample, call isBimeraDenovo on the sample (after removing the zero entries) and then zero out the abundances of the flagged SVs in that sample.

Yeah, I don't think it's too much R coding - I'll put in a PR when I have a chance. 

> I don't generally recommend that approach, but it is an option, and in some special circumstances it could even be the best option.

Why isn't per-sample chimera removal more "correct" in the sense that it recapitulates the PCR setup?

**Comment by benjjneb** [comment]
> Why isn't per-sample chimera removal more "correct" in the sense that it recapitulates the PCR setup?

This is something of a practical observation: We have seen some sequences that are flagged as chimeric in some samples, but not others, and in most cases these seem to be real sequences that have abundances that fluctuate between being higher than their putative "parents" and lower than their parents, leading to the inconsistent chimeric assignment.

In that case, it is better to take the consensus call of "not a chimera" than to remove the sequences on a sample-by-sample basis.

I admit that this intuition derives from my experience working mostly with longitudinal data. In data where every sample is different, sample-wise chimera removal might make more sense.

**Comment by joey711** [comment]
@benjjneb I think I would probably modularize this. That is, the intuitive per-sample chimera identification by @fanli-gcb is a reasonable default for essentially all cases, and easy to implement in large data situations where samples are also the atomic data unit for parallelizing computation. The key is to classify the sequences as chimera or not, without throwing them out (do the filtering lazily only when filtered sequences are needed). Then your recommended cross-sample consensus chimera can still be applied, optionally, if it is warranted by the experimental design. It will be interesting to define the scenarios in which the consensus filtering is, or is not, appropriate. My first guess is that the requirement is consensus among technical replicates from the same sample that are amplified-and-sequenced independently. A stable time-series approximates this, perhaps well enough to chimera filtering, but one could imagine unstable communities where that is not the case. The technical requirement is that the set of real sequences is mostly the same among the samples in the consensus. Right? Otherwise why would the consensus be helpful?
