### ISSUE TITLE
Determining Reasonable Run times on AWS

### ISSUE THREAD

**Issue by steviep42** [benjjneb/dada2#219]
Hello, this is more of an observational post as opposed to an issue or problem. As we run on Amazon I'm trying to get a sense of what a "good" run time is and if there are opportunities for improvement. We are currently using the recommended pipleine for processing a large number of reads 5,222,553, 1,622,281 unique sequences, which represents 38 samples. We are implementing the flow described here http://benjjneb.github.io/dada2/tutorial.html and are also adding in the Species Assignment as described at http://benjjneb.github.io/dada2/assign.html#species-assignment.

As we have a larger read set than is used in the demonstration and training material we have experienced much longer processing times which is of course understandable. We have employed multi threading where supported by the command(s) to improve performance and have most recently used a m4.16xlarge instance on AWS which offers 64 vCPUs and 256Gib. We experience a total run time of around 5 hours. Interestingly this is not much quicker than using a slightly smaller instance (or a larger one). The breakdown in time is represented below. These are timing figures derived during actual execution as opposed to estimates. The numbers are hours or fractions thereof. One can see that the Species (i.e. taxa.plus <- addSpecies) takes the longest time and it doesn't seem to be responsive to more memory. The question here is can we improve further upon any of these as we anticipate processing larger sets of data. Note I don't know that this is a problem just that this represents a benchmark on a "larger" machine. Does this seem reasonable in terms of response time and/or are there ways to improve this run time ?  Thanks,

FILTER: 0.4735
DEREP: 0.0387
DEREPFS: 1.0075
DEREPRS: 0.566
SAMPLE INFERENCE: 0.2813
MERGE: 0.0254
REMOVE CHIMERA: 0.8846
TAXONOMY: 0.1402
SPECIES: 1.5368

**Comment by benjjneb** [comment]
I believe there are some major speedups you can make to this workflow, both by adopting a couple recommendations from our [Big Data Workflow](http://benjjneb.github.io/dada2/bigdata.html) and by using the expanded multithreading we have been working on in the current devel version of the package on github (which will become the new `1.4` release in about a month).

In devel version: `filterAndTrim` is a new filtering function. It simply wraps `fastqFilter` and `fastqPairedFilter` while handling multithreading. So you can properly multithread the filtering with `filterAndTrim(..., multithread=TRUE)`

In Big Data workflow: I believe your DEREPFS and DEREPRS steps include the learning of the error rates? Assuming that is the case, the big data workflow shows how you can use a subset of the data to learn the error rates. Furthermore, there is a new convenience method for this in the devel version: `learnErrors(filtFs, nread=1000000, multithread=TRUE)`

In Big Data workflow: Unlike in the tutorial workflow, the big data workflow runs sample inference in a "streaming" fashion, i.e. processes each sample w/in a loop. This will keep memory requirements very low.

In devel version: `removeBimeraDenovo(..., method="consensus", multithread=TRUE)` now has working multithreading, and `method="consensus"` will be our official recommendation in the new release.

In devel version: `assignTaxonomy(..., multithread=TRUE)` now works.

The bad news: the `addSpecies` function remains poorly implemented from a performance standpoint, it is multithreaded and relies on R's grep function.

When you put all that together, the compute time on all the time-consuming steps except for SPECIES should decrease, and should continue to speed up reasonaly well with increasing processors to at least 32 cores (perhaps further, but I haven't tested beyond that). Memory requirements should remain essentially flat, and there will be little advantage (perhaps no advantage?) to memory beyond 32GB for most datasets.

Making `addSpecies` performant is a high priority, but I wouldn't expect that until after our next release.

**Comment by benjjneb** [comment]
A new, much faster `assignSpecies` implementation is now in.

> The reimplemented assignSpecies is now much, much faster 042a817. The performance gains scale up with more sequences being assigned, but it is now ore than 100x faster when assigning genus-species binomials to thousands of sequences.
