### ISSUE TITLE
BLAST, either interface, or detailed vignette using external dependency

### ISSUE THREAD

**Issue by joey711** [benjjneb/dada2#22]
For low numbers of denoising-results, the following might work (against NR database)

```S
annotate::blastSequences 
```

For larger datasets with hundreds or thousands of species-genotypes, this might not be feasible or even dangerous, as 16S classification is usually done with more specialized approaches -- like Naïve Bayes on a custom reference database.

**Comment by benjjneb** [comment]
I've not found annotate::blastSequences to work well.

I'm closing this for now. The general question of taxonomic assignment within R remains an open question, but is a major additional feature.

**Comment by joey711** [comment]
Agree on all counts.
I can explain offline how we're currently doing this in production. I think usearch and pplacer are good off-the-shelf options here, but this probably means a data exchange with non-R software.
