### ISSUE TITLE
Trimming dada2 taxonomy training set to corresponding to primer region

### ISSUE THREAD

**Issue by Nick243** [benjjneb/dada2#220]
Hi Ben,

Given dada2 can resolve differences of as little as 1 nucleotide, we were interested in determining the set of unique sequences that might be able to be mapped to a taxonomy training set for a given primer set. Knowing which taxa we might be able to better discern by targeting say the V4 (515F/806R) versus V1/V2 (28F/388R) regions might be one factor contributing to our choice of primers.  

For example, would it make sense to:
- trim the silva_species_assignment_v123.fa.gz training set to include only the sequences corresponding to the primer region
- extract each unique sequence 
- append the taxonomy labels associated with each unique sequence…
- and if we wanted to know the set of reads in which we could map to unambiguous labels,  I suppose this would just be the set with only a single label?

If this makes sense, is trimming the training set to correspond to a specific primer region (say V4 versus V1/V2) using R something you have done (or have as a dada2 function)?  

Any thoughts you might have on the utility of this approach, and if reasonable, how we might consider going about it would be much appreciated!

**Comment by benjjneb** [comment]
That is a very useful exercise. We do not have a dada2 function to do this.

I haven't done this in R myself, but the `trimLRPatterns` function in the `Biostrings` package might do what you want here. Another place to look is in the `DECIPHER` package, which has several tools for designing primers.

**Comment by Nick243** [comment]
Thanks for the quick and extremely helpful advice.  We will take a look at these functions and see if we can put something together.  If we get it worked out I'll be sure to post it should it be of use to others and for any comments.

**Comment by Nick243** [comment]
Unfortunately, I didn't make any progress here using R.  I am not sure if the trimLRPatterns requires anchored primers (or simply better R programming), but the trimming seemed doable using cutadapt.  I was interested in the following V4 primers and the silva_species_assignment_v123.fa.gz training set,...so ran the following code to trim to the region of interest (forcing no errors in the primer sequences).

cutadapt -g GTGYCAGCMGCCGCGGTAA silva_species_assignment_v123.fa -e 0.0 --discard-untrimmed > v4_f_trim.fasta 2> v4_f_trim_report.txt

cutadapt -a ATTAGAWACCCBNGTAGTCC v4_f_trim.fasta -e 0.0 --discard-untrimmed > v4_fr_trim.fasta 2> v4_r_trim_report.txt


I then read the seqs into R and attempted to filter to the reads to those with a length in the range we have seen in our data and remove duplicate seqs and genus.species names. My thought being that these would be the set of unique seqs that could be unambiguously assigned.  I used some tidyverse functions to do this (apologies in advance if base R is preferred) and came to 8924 seqs.  The code ran was:

library(Biostrings); packageVersion("Biostrings")        #2.42.0
library(tidyverse); packageVersion("tidyverse")          #1.0.0
library(stringr); packageVersion("stringr")                  #1.1.0
library(dada2); packageVersion("dada2")                   #1.2.0

#Reading in trimmed fasta (515F/806R primers)
(v4_trim = readDNAStringSet("mypath/v4_fr_trim.fasta", "fasta"))


#Converting to data.frame and filtering
width_names <- data.frame(v4_trim@ranges)[,4:5]                #extract name and width from DNAStringSet
v4_seqs <- data.frame(v4_trim)                                              #extract seqs
mydata <- cbind(v4_seqs, width_names)

mydata <- mydata %>%
  rename(seq = v4_trim) %>%
  separate(names, c("silva_id", "genus", "species", "misc"), "\\s+", extra = "merge", fill= "right") %>%       
  mutate(genus_species = paste(genus, species, sep = ".")) %>%
  select(-misc) %>%
  filter((width > 249 & width < 258))                    #filtering to seqs of 250 to 257 bp

#Obtaining unique sequences (will retain only the first ID)
unique_seq <-  distinct(mydata, seq, .keep_all = TRUE)       

#Obtaining unambiguous genus.species (ignores seq length)
unambiguous_genus_species  <- distinct(unique_seq, genus_species, .keep_all = TRUE)

However, when I try to map these back to the full training set I can only unambiguously map 7253 of the 8924 seqs?  I suspect I am missing something here or made an error (coding or thinking).  The code I ran is here:

seqs <- unambiguous_genus_species$seq
genus.species <- assignSpecies(seqs, "mypath/silva_species_assignment_v123 (1).fa.gz")
unname(genus.species)  


This may be getting a bit far of field for an issue, but if anyone has any thoughts they would be much appreciated.  Trimming the training set to the primer region targeted also greatly speeded up the time it took to run the assignSpecies function, thus I assume this might be helpful for those attempting to map a large number of reads.

**Comment by benjjneb** [comment]
@Nick243 

On the 7253/8924 issues: That may be caused by sequence that exactly match multiple reference sequences. By default, `assignSpecies` will only return assignments of seqs that match just one reference sequence. You can test that easily by trying `assignSpecies(..., allowMultiple=TRUE)`, in which case all assignments will be returned when there are multiple exact hits.

**Comment by Nick243** [comment]
Yep, I was getting multiple hits.  Seems better to run `assignSpecies(..., allowMultiple=TRUE)` on the trimmed ref seqs against the full training set to see which would map unambiguously if they were present in a sample. 

Thanks again for your help!
