### ISSUE TITLE
assignTaxonomy is unkillable

### ISSUE THREAD

**Issue by rec3141** [benjjneb/dada2#221]
Like Sean Hannity, assignTaxonomy is uninterruptible once it gets going, and you have to kill R to get your CPU back. I don't know if this is true for other functions but this is the one I've had difficulties with.

**Comment by benjjneb** [comment]
Well when you put it that way!

This probably happened when I added the multithreaded code. Will try to get a fix in before the upcoming release.

**Comment by benjjneb** [comment]
`assignTaxonomy(..., multithread=TRUE)` is now user-interruptible: 529fbdb4ff4a84245822ab2b19e16d94cc1a8eaa
