### ISSUE TITLE
DNAStringSet  is not available (for R version 3.3.3)

### ISSUE THREAD

**Issue by sachasuca** [benjjneb/dada2#224]
FYI, just updated R to version 3.3.3. The following code comes back with the warning:
`taxa <- assignTaxonomy(seqtab.nochim, "rdp_train_set_14.fa")`

"Error in .Primitive("c")(<S4 object of class "DNAStringSet">) : could not find symbol "recursive" in environment of the generic function"

Do you suggest I use the previous version of R until this repair can be made?

**Comment by joey711** [comment]
I think you just need to install Biostrings:

```r
## try http:// if https:// URLs are not supported
source("https://bioconductor.org/biocLite.R")
biocLite("Biostrings")
```

**Comment by sachasuca** [comment]
So I installed Biostrings as per your recommendations but I am getting the same error. I also updated my version of Bioconductor and reinstalled all packages. Any other suggestions?

**Comment by sachasuca** [comment]
Never mind, I went back and specified type = "source" and it seems to have worked. Thanks for your help.

**Comment by fanli-gcb** [comment]
For reference:
https://support.bioconductor.org/p/93347/#93373
