### ISSUE TITLE
Performant assignSpecies implementation

### ISSUE THREAD

**Issue by benjjneb** [benjjneb/dada2#225]
As discussed in #219 the current implementation of `assignSpecies` (and `addSpecies`) is slow, as it is both single-threaded and reliant on the R `grepl` implementation. It would be nice for this to be a lot faster, and is certainly possible as the underlying functionality is just exact substring matching.

**Comment by joey711** [comment]
This one is something we might want to chat about. There's some need on our end, and we've been tinkering with taxonomy classification methods. We would also like something as performant as UTAX, but less heuristic.

It does get application (target) specific. Is it better to have it in a new package? Possibly with supporting DB packages for the most popular targets? (e.g. 16S, ITS, etc)?

**Comment by benjjneb** [comment]
The reimplemented `assignSpecies` is now much, much faster. The performance gains scale up with more sequences being assigned, but it is now ore than 100x faster when assigning genus-species binomials to thousands of sequences.

Computation time is no longer a barrier to using `addSpecies` to extend taxonomy assignment down the species level where appropriate.
