### ISSUE TITLE
Questions about DADA2 Sequence Variants which only appear in one sample

### ISSUE THREAD

**Issue by mentorwan** [benjjneb/dada2#226]
Appreciated for your help. I can run DADA2 on our project successfully. The pipeline reports several sequence variants (if I call correctly) happen only in one sample (prevalence = 1). We don't know why it causes those one sample only SVs since our project has two duplicate samples for each case.  Attach 38 SV with their taxonomy assigned by SILVA database. Can you share some thoughts on my problem? In general, how do you recommend dealing with SVs with prevalence = 1?  

I didn't search your past issues extensively. If the similar question was already answered, can you point to me? Thanks.

[problem_taxa.txt](https://github.com/benjjneb/dada2/files/922844/problem_taxa.txt)

One additional unrelated question: In building database, how do you define a training set for databases such as SILVA and RDP database? Do you have any documents on that process?

**Comment by benjjneb** [comment]
There are a couple reasons why taxa might appear in only one sample, even with your duplicates. Obviously very low abundance samples might just be detected in one duplicate and not the other by chance. But what we have seen is a big driver of this is contamination, and looking at your list of "problem taxa" it has a bunch of the contaminants greatest hits list (eg. Pseudomonas, Sphingomonas, Bradyrhizobium, Leptotrichia) that have been identified as contaminants in multiple other studies.

In general, we remove SVs seen in only 1 sample before most analyses, in part for this reason.

On the taxonomic DB question, see our [page on taxonomic reference data](http://benjjneb.github.io/dada2/training.html):

> Note that currently species-assignment training fastas are only available for the Silva and RDP databases. In addition to thanking the folks at RDP, Silva and GreenGenes for making these datasets available, we also want to thank Pat Schloss and the mothur team for making cleaner versions of the Silva and RDP training set available. To be specific, we created the dada2-compatible training fastas from the mothur-compatible Silva.nr_v123 files (described here, and license here), the mothur-compatible 16S rRNA reference (RDP) (described here), and the GreenGenes 13.8 OTUs clustered at 97%.

**Comment by mentorwan** [comment]
Do you have a reference (paper or web) to tell which bacteria are contaminants? Is removing SVs only shown in one sample good to apply to standard procedure for all microbiome projects? Thanks

**Comment by benjjneb** [comment]
There have been a few papers that look at contaminants in particular, see for example [Salter et al](https://bmcbiol.biomedcentral.com/articles/10.1186/s12915-014-0087-z) and references within.

Removing SVs in one sample depends on the scientific question you are asking and the confidence you would have in the one-sample SVs you kept being real non-contaminants. In most cases, the scientific question does not depend on one-sample SVs and the confidence in one-sample SVs is low, so removing them is good practice. But we can't make a universal procedure for every single study.

**Comment by mentorwan** [comment]
Hi Ben,
I am still interested in single sample SVs reported by DADA2 pipeline. Based on your suggestions, I removed contaminated bacteria from OTU table. The result is improved.  But I still get a lot of one-sample SVs. Although those one-sample SVs have very few reads. (The maximum is 145 in my case). I blast on top 11 hits. I found almost half with no blast hits. And their taxonomy shows as NA values. Can you tell me where is the problem? Thanks a lot.
single_hit

**Comment by mentorwan** [comment]
[single_hit.xlsx](https://github.com/benjjneb/dada2/files/971053/single_hit.xlsx)

Attach file again.

**Comment by benjjneb** [comment]
Those filtering parameters look fine. We now recommend `trimLeft=0` (assuming your primers have been removed) but `trimLeft=10` is not wrong.

It's hard to explain every single-sample SV. Some might be real sequences at low frequency that only got picked up in 1/2 replicates. Some might still be contaminants. The ones that aren't hitting anything are probably technical sequencing artefacts. It looks like they have the Illumina linker (TATGGTAATTGT) + 515F primer (GTGCCAGCMGCCGCGGTAA) as the first 31 nts of those sequences. You can test for sequences containing linker DNA like so:

```
linker <- "TATGGTAATTGT"
has.linker <- grepl(linker, my.sqs)
starts.w.linker <- grepl(paste0("^", linker), my.sqs)
```

**Comment by mentorwan** [comment]
You are right. All NA assignment related to this linker at top. Does it mean that trimleft=10 still not removing linker? Do you have recommendations on that? Can I trimleft=22 to get rid of that?

I also checked in my 922 single-sample OTUs, only 49 SVs starts with linker, 56 SVs contain linker.
