### ISSUE TITLE
V3-V4

### ISSUE THREAD

**Issue by camila10** [benjjneb/dada2#227]
Do you have any suggestion to run DADA2 using  V3-V4 (with less-overlap than V4)?

**Comment by benjjneb** [comment]
Two suggetions:

1) When truncating the F/R reads, you have to ensure that enough overlap remains between them for them to be merged later. This may mean that the quality filtering needs to be relaxes (eg. 'maxEE') especially on the reverse read. As a rough rule of thumb, you need `truncLenF + truncLenR > ampliconLength + 25`, and pushing the overlap length higher is better if possible, to account for biological length variation in amplicon length.

2) Use the `consensus` chimera filtering method, we are seeing this method perform quite a bit better on multi-V-region amplicons: `removeBimeraDenovo(..., method="consensus")`. This will be the default in our next release later this month.

**Comment by camila10** [comment]
Thanks for your answer! . Should I also reduce the minOverlap (default is 20)?

**Comment by camila10** [comment]
Thanks for your answer!, Should I also change the minOverlap ?

**Comment by benjjneb** [comment]
If sequence quality on the R read is bad enough that you can't get to 20nts of overlap you can reduce `minOverlap` to make up for that. I wouldn't go below `minOverlap=8` though, to avoid spurious merging.
