### ISSUE TITLE
Hand-off to phyloseq

### ISSUE THREAD

**Issue by joey711** [benjjneb/dada2#23]
After class definition for dada output is defined, can define a hand-off method for phyloseq. Will need to need to figure out what part needs to be defined in dadac, and what part needs to be defined in phyloseq.

On first thought, the conversion to an "OTU_table"-like count matrix with a corresponding vector of reference sequences might already be sufficient.

**Comment by benjjneb** [comment]
The tutorial (http://benjjneb.github.io/dada2/R/tutorial.html) has a handoff from dada2 to phyloseq at the end, along with using phyloseq to make a couple basic plots.

No tree and no taxonomy at this point, but is that good enough for now?

**Comment by spholmes** [comment]
It's nice to see the phyloseq handoff, in the past Joey had written a
script to find the tree for sequences we didn't have reads for, but you'd
need the blast output and then map those `otu` ids to greengenes for
instance.
Another route could just be to use the cleaned sequences and compute a tree
de nuovo with some of the tree building algorithms interfaced to phangorn
or ape...



On Fri, Aug 28, 2015 at 8:34 AM, benjjneb <notifications@github.com> wrote:

> The tutorial (http://benjjneb.github.io/dada2/R/tutorial.html) has a
> handoff from dada2 to phyloseq at the end, along with using phyloseq to
> make a couple basic plots.
>
> No tree and no taxonomy at this point, but is that good enough for now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benjjneb/dada2/issues/23#issuecomment-135807942>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by benjjneb** [comment]
We of course have the inferred sequences, so in principle making a tree
should just be a question of sticking those in the right algorithm. I'm not
familiar with the tree-building tools in R myself, so suggestions on that
are welcome. Ideally the method should scale reasonably well with the
number of sequences, although we can start with what works and deal with
the scaling issues later.

Taxonomy assignment is still the missing piece for a complete R workflow
though?

**Comment by benjjneb** [comment]
I'm going to close this for now, with a reference to the https://github.com/benjjneb/dada2/issues/22 on taxonomy assignment.

We need better tax assignment in R, but that's outside the scope of this package.

**Comment by joey711** [comment]
Agreed!  The `makeSequenceTable` function seems to be a relevant enough hand-off function, and the [DADA2 pipeline tutorial](http://benjjneb.github.io/dada2/R/tutorial.html) shows how to do this at the end of the multiple sample denoising. LGTM

http://benjjneb.github.io/dada2/R/tutorial.html
