### ISSUE TITLE
Losing Sample names in Forming the sequence table 

### ISSUE THREAD

**Issue by girishVjayant** [benjjneb/dada2#234]
Hey guys, 

I am going through the SOP and I am trying to form a sequence table. I've run mergepairs and my forward and reverse reads merge without issue. I was also able to form the sequence table, but the sample names for my merged pairs dont show up in my environment. 

There should be 12b or 13b and so on in the environment but they are not there. This issue was preventing me from forming the sequence table until I just ran the whole program again and it somehow worked. However the names still don't show up in environment. Does anyone know why this is? Thanks!

<img width="1280" alt="screen shot 2017-04-27 at 9 14 42 am" src="https://cloud.githubusercontent.com/assets/28101464/25484948/097bca54-2b2a-11e7-8334-6f29411a5354.png">

**Comment by benjjneb** [comment]
I'm not quite sure what is missing. Are there no sample names on the sequence table? There is a specific step in the tutorial where sample names are added:

```S
# Name the derep-class objects by the sample names
names(derepFs) <- sample.names
names(derepRs) <- sample.names
```

What are the results of the following commands for your data?
```S
head(names(dadaFs))
head(names(mergers))
head(rownames(seqtab))
```

**Comment by jsan4christ** [comment]
Hi Ben,

I see you closed this, 

Having a similar glitch, 
Both 
# Name the derep-class objects by the sample names
names(derepFs) <- sample.names
names(derepRs) <- sample.names
and 

# Name the derep-class objects by the sample names
names(derepFs) <- sampleNames
names(derepRs) <- sampleNames

Give the error;
Error in as.character(function (...)  : 
  cannot coerce type 'closure' to vector of type 'character'

And
head(names(dadaFs)) returns NULL,

Any idea how to fix this??

Thanks,

**Comment by benjjneb** [comment]
What do `class(sample.names)` and `class(sampleNames)` return?

**Comment by jsan4christ** [comment]
> class(sample.names)
[1] "function"
> (sampleNames)
function (...) 
{
    .Deprecated("sample_names", package = "phyloseq")
    return(sample_names(...))
}
<environment: namespace:phyloseq>

**Comment by benjjneb** [comment]
@jsan4christ 

That indicates that `sample.names` and `sampleNames` are functions, i.e. that they have not been previously defined. You need to first define the `sample.names` to be equal to a character vector of the sample names, and then it should work fine.

**Comment by jsan4christ** [comment]
Yes,  this is what I was missing:
sample.names <- sapply(strsplit(basename(filtFs), "_"), `[`, 1)

or 

sampleNames <- sapply(strsplit(basename(filtFs), "_"), `[`, 1)

respectively, above the lines.

Thanks
