### ISSUE TITLE
Versioning of 1.4

### ISSUE THREAD

**Issue by brwnj** [benjjneb/dada2#235]
It looks like you may have created your Github release of 1.4 before updating DESCRIPTION. The version in the .tar.gz is 1.3.5. Any chance you can create a new release from that branch?

**Comment by benjjneb** [comment]
Yep. Added new release v1.4.0 with the version number updated (same code as release v1.4 outside the DESCRIPTION file though).

https://github.com/benjjneb/dada2/releases/tag/v1.4.0
