### ISSUE TITLE
Paired end joining

### ISSUE THREAD

**Issue by akknight** [benjjneb/dada2#237]
Hi, 

I am working with paired end reads and had a couple of questions about how dada2 handles them. 

1. At what point do reads not align? (Quality too poor? Overlap minimal?)
2. When there is a difference in the base calls, how does dada2 chose which one to use? (Does it just go with the one with the higher quality score?)

Best,

Anna

**Comment by benjjneb** [comment]
DADA2 merges reads a bit differently than other pipelines -- reads are merged *after* denoising. That is, the sequence variants in the forward reads and reverse reads are inferred independently, and then merging is performed.

By default, no mismatches are allowed (denoising is expected to have removed substitution errors), and a minimum overlap of 20nts is required (although that can be modified with the `minOverlap` parameter of the `mergePairs` function).
