### ISSUE TITLE
How to remove samples that result in zero counts after DADA2?

### ISSUE THREAD

**Issue by sachasuca** [benjjneb/dada2#238]
Is there an easy way to remove samples with zero (or very few) counts/reads from my seqtab.nochim object? I am having downstream issues with DESeq2 and I believe the problem is that some of my samples have zero reads.

I've entered the following code:
`diagdds = phyloseq_to_deseq2(ps, ~Subject)
diagdds = estimateSizeFactors(diagdds, type=c("poscounts"))`

and get the following error:
"Error: all(!is.na(value)) is not TRUE"

From what I understand, this error is related to missing data. I know some of my samples had very few reads after running the DADA2 algorithm. I suspect that after filtering out chimeras, some samples ended up with zero reads. Do you think this could be the problem?

**Comment by benjjneb** [comment]
Removing samples with zero reads is definitely recommended as they will interfere with downstream analysis methods.

This is easy to do, either at the dada2 stage or at the phyloseq stage:

```
# Remove samples with less than MINREADS from sequence table (which is just an R matrix)
st <- seqtab[rowSums(seqtab) >= MINREADS,]
# Remove samples with less than MINREADS from phyloseq object
ps <- prune_samples(sample_sums(ps) >= MINREADS, ps)
```

**Comment by sachasuca** [comment]
Thanks so much for the code, I really appreciate your help!
