### ISSUE TITLE
Big Data Pipeline - Subsample to estimate error rates

### ISSUE THREAD

**Issue by durrantmm** [benjjneb/dada2#240]
Hello, I'm working with around ~300 samples and we expect more samples to become available over time. All of the samples will be processed by the same laboratory at different times.

I want to make sure that I'll be addressing possible batch effects in generating my error rates. The big data tutorial mentions that I should use around 1-2 million reads to estimate error rates. Does it make sense to use ~60 samples to produce these estimates, or should I try sampling a few reads from all of the samples? Should I estimate error rates on the different batches independently?

If you do recommend that I some reads from every sample, how could I do this in a computationally efficient way? I'd like to avoid recalculating the error rates every time a new batch comes in.

Thank you.

**Comment by benjjneb** [comment]
For best results:

(1) Do not subsample reads from samples. Use complete samples.

(2) Re-estimate the error rates for each new "batch" (most often a sequencing run, but can be any batch in which the PCR/sequencing error rates may have changed).

Also, are you using the 1.4 package version, and the corresponding [1.4 version of the Big Data tutorial](http://benjjneb.github.io/dada2/bigdata.html)? The recommended way to perform error estimation now is with the `learnErrors` function, which you can run no each batch and easily specify the number of reads to use for estimation (remember to specify the `multithread` parameter if running large datasets!)

**Comment by durrantmm** [comment]
Thank you, this was very helpful. I'm not using the 1.4 package version yet. Is that going to be available through anaconda soon?

**Comment by benjjneb** [comment]
Yep. Version 1.4.0 is available through bioconda now: https://bioconda.github.io/recipes/bioconductor-dada2/README.html

**Comment by durrantmm** [comment]
Great, thank you.
