### ISSUE TITLE
Can't install dada2 package. Used to work pefectly.

### ISSUE THREAD

**Issue by zippymimosa** [benjjneb/dada2#242]
Hi all, I was using dada2 perfectly fine a month ago on 2 computers. But now everytime I want to load the dada2 package it gives me this error message on either computer. I am using windows. I have tried every method to reinstall the package like from a source, from local file etc., but still won't work. The other packages such as ggplot2 are working fine so it feels like a dada2 specific problem. Can anyone help please?

Error message as below:

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
Error: package or namespace load failed for ‘dada2’

**Comment by benjjneb** [comment]
Did you try the Bioconductor install route? That's the best way to ensure all the dependencies are up-to-date:

```S
source("http://bioconductor.org/biocLite.R")
biocLite()
biocLite("dada2")
```

If that isn't working, could you report the output of the following:

```{r}
R.version
packageVersion("BiocInstaller")
packageVersion("ShortRead")
```

**Comment by zippymimosa** [comment]
Yes. I tried install dada2 like from biocLite, from local file, and from the packages tab from R etc., 

I'll try your suggestion now. Thanks!

**Comment by zippymimosa** [comment]
> R.version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          4.0                         
year           2017                        
month          04                          
day            21                          
svn rev        72570                       
language       R                           
version.string R version 3.4.0 (2017-04-21)
nickname       You Stupid Darkness  



> packageVersion("BiocInstaller")
[1] ‘1.26.0’


I don't have the shortread package. Do I need that?

**Comment by benjjneb** [comment]
> I don't have the shortread package. Do I need that?

Yes. So the `biocLite` route isn't working I gather, but you have the current installer...
What is the output you are getting when you run the following?

```S
source("http://bioconductor.org/biocLite.R")
biocLite()
biocLite("dada2")
```

**Comment by zippymimosa** [comment]
It unpack a lot of things and tell me package ‘dada2’ successfully unpacked and MD5 sums checked
The downloaded source packages are in
        ‘C:\Users\zippy_000\AppData\Local\Temp\Rtmp6zNPr1\downloaded_packages’

And I can install from this local source using "installpackage(), dependency as TRUE". But still when I load it with the library("dada2") it gives me the above error message.

**Comment by benjjneb** [comment]
@zippymimosa 

Could you copy the output of `biocLite("dada2")` and post the entire thing here?

**Comment by zippymimosa** [comment]
> biocLite("dada2")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.5 (BiocInstaller 1.26.0), R 3.4.0 (2017-04-21).
Installing package(s) ‘dada2’
also installing the dependencies ‘matrixStats’, ‘colorspace’, ‘lambda.r’, ‘futile.options’, ‘DelayedArray’, ‘RColorBrewer’, ‘dichromat’, ‘munsell’, ‘labeling’, ‘stringi’, ‘magrittr’, ‘futile.logger’, ‘snow’, ‘bitops’, ‘SummarizedExperiment’, ‘RCurl’, ‘GenomeInfoDbData’, ‘XVector’, ‘gtable’, ‘plyr’, ‘scales’, ‘tibble’, ‘lazyeval’, ‘stringr’, ‘BiocParallel’, ‘Rsamtools’, ‘GenomicAlignments’, ‘GenomeInfoDb’, ‘GenomicRanges’, ‘hwriter’, ‘zlibbioc’, ‘latticeExtra’, ‘Biostrings’, ‘ggplot2’, ‘data.table’, ‘reshape2’, ‘ShortRead’, ‘RcppParallel’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/matrixStats_0.52.2.zip'
Content type 'application/zip' length 1622821 bytes (1.5 MB)
downloaded 1.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/colorspace_1.3-2.zip'
Content type 'application/zip' length 448307 bytes (437 KB)
downloaded 437 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/lambda.r_1.1.9.zip'
Content type 'application/zip' length 90384 bytes (88 KB)
downloaded 88 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/futile.options_1.0.0.zip'
Content type 'application/zip' length 16999 bytes (16 KB)
downloaded 16 KB

trying URL 'https://bioconductor.org/packages/3.5/bioc/bin/windows/contrib/3.4/DelayedArray_0.2.2.zip'
Content type 'application/zip' length 726445 bytes (709 KB)
downloaded 709 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/RColorBrewer_1.1-2.zip'
Content type 'application/zip' length 26965 bytes (26 KB)
downloaded 26 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/dichromat_2.0-0.zip'
Content type 'application/zip' length 147907 bytes (144 KB)
downloaded 144 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/munsell_0.4.3.zip'
Content type 'application/zip' length 133832 bytes (130 KB)
downloaded 130 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/labeling_0.3.zip'
Content type 'application/zip' length 40849 bytes (39 KB)
downloaded 39 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/stringi_1.1.5.zip'
Content type 'application/zip' length 14289534 bytes (13.6 MB)
downloaded 13.6 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/magrittr_1.5.zip'
Content type 'application/zip' length 155884 bytes (152 KB)
downloaded 152 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/futile.logger_1.4.3.zip'
Content type 'application/zip' length 94245 bytes (92 KB)
downloaded 92 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/snow_0.4-2.zip'
Content type 'application/zip' length 65502 bytes (63 KB)
downloaded 63 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/bitops_1.0-6.zip'
Content type 'application/zip' length 37218 bytes (36 KB)
downloaded 36 KB

trying URL 'https://bioconductor.org/packages/3.5/bioc/bin/windows/contrib/3.4/SummarizedExperiment_1.6.1.zip'
Content type 'application/zip' length 2927458 bytes (2.8 MB)
downloaded 2.8 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/RCurl_1.95-4.8.zip'
Content type 'application/zip' length 2870687 bytes (2.7 MB)
downloaded 2.7 MB

trying URL 'https://bioconductor.org/packages/3.5/bioc/bin/windows/contrib/3.4/XVector_0.16.0.zip'
Content type 'application/zip' length 797937 bytes (779 KB)
downloaded 779 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/gtable_0.2.0.zip'
Content type 'application/zip' length 58085 bytes (56 KB)
downloaded 56 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/plyr_1.8.4.zip'
Content type 'application/zip' length 1188183 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/scales_0.4.1.zip'
Content type 'application/zip' length 677917 bytes (662 KB)
downloaded 662 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/tibble_1.3.0.zip'
Content type 'application/zip' length 627507 bytes (612 KB)
downloaded 612 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/lazyeval_0.2.0.zip'
Content type 'application/zip' length 138774 bytes (135 KB)
downloaded 135 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/stringr_1.2.0.zip'
Content type 'application/zip' length 148390 bytes (144 KB)
downloaded 144 KB

trying URL 'https://bioconductor.org/packages/3.5/bioc/bin/windows/contrib/3.4/BiocParallel_1.10.1.zip'
Content type 'application/zip' length 1360536 bytes (1.3 MB)
downloaded 1.3 MB

trying URL 'https://bioconductor.org/packages/3.5/bioc/bin/windows/contrib/3.4/Rsamtools_1.28.0.zip'
Content type 'application/zip' length 8782878 bytes (8.4 MB)
downloaded 8.4 MB

trying URL 'https://bioconductor.org/packages/3.5/bioc/bin/windows/contrib/3.4/GenomicAlignments_1.12.1.zip'
Content type 'application/zip' length 3257796 bytes (3.1 MB)
downloaded 3.1 MB

trying URL 'https://bioconductor.org/packages/3.5/bioc/bin/windows/contrib/3.4/GenomeInfoDb_1.12.0.zip'
Content type 'application/zip' length 7070132 bytes (6.7 MB)
downloaded 6.7 MB

trying URL 'https://bioconductor.org/packages/3.5/bioc/bin/windows/contrib/3.4/GenomicRanges_1.28.1.zip'
Content type 'application/zip' length 3000817 bytes (2.9 MB)
downloaded 2.9 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/hwriter_1.3.2.zip'
Content type 'application/zip' length 139177 bytes (135 KB)
downloaded 135 KB

trying URL 'https://bioconductor.org/packages/3.5/bioc/bin/windows/contrib/3.4/zlibbioc_1.22.0.zip'
Content type 'application/zip' length 750306 bytes (732 KB)
downloaded 732 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/latticeExtra_0.6-28.zip'
Content type 'application/zip' length 2068917 bytes (2.0 MB)
downloaded 2.0 MB

trying URL 'https://bioconductor.org/packages/3.5/bioc/bin/windows/contrib/3.4/Biostrings_2.44.0.zip'
Content type 'application/zip' length 27202206 bytes (25.9 MB)
downloaded 25.9 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/ggplot2_2.2.1.zip'
Content type 'application/zip' length 2783806 bytes (2.7 MB)
downloaded 2.7 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/data.table_1.10.4.zip'
Content type 'application/zip' length 1573743 bytes (1.5 MB)
downloaded 1.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/reshape2_1.4.2.zip'
Content type 'application/zip' length 572023 bytes (558 KB)
downloaded 558 KB

trying URL 'https://bioconductor.org/packages/3.5/bioc/bin/windows/contrib/3.4/ShortRead_1.34.0.zip'
Content type 'application/zip' length 10513693 bytes (10.0 MB)
downloaded 10.0 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/RcppParallel_4.3.20.zip'
Content type 'application/zip' length 3378570 bytes (3.2 MB)
downloaded 3.2 MB

trying URL 'https://bioconductor.org/packages/3.5/bioc/bin/windows/contrib/3.4/dada2_1.4.0.zip'
Content type 'application/zip' length 4442346 bytes (4.2 MB)
downloaded 4.2 MB

package ‘matrixStats’ successfully unpacked and MD5 sums checked
Warning: unable to move temporary installation ‘C:\Program Files\R\R-3.4.0\library\file488c605830a\matrixStats’ to ‘C:\Program Files\R\R-3.4.0\library\matrixStats’
package ‘colorspace’ successfully unpacked and MD5 sums checked
package ‘lambda.r’ successfully unpacked and MD5 sums checked
package ‘futile.options’ successfully unpacked and MD5 sums checked
package ‘DelayedArray’ successfully unpacked and MD5 sums checked
package ‘RColorBrewer’ successfully unpacked and MD5 sums checked
package ‘dichromat’ successfully unpacked and MD5 sums checked
package ‘munsell’ successfully unpacked and MD5 sums checked
package ‘labeling’ successfully unpacked and MD5 sums checked
package ‘stringi’ successfully unpacked and MD5 sums checked
Warning: unable to move temporary installation ‘C:\Program Files\R\R-3.4.0\library\file488c1c895230\stringi’ to ‘C:\Program Files\R\R-3.4.0\library\stringi’
package ‘magrittr’ successfully unpacked and MD5 sums checked
package ‘futile.logger’ successfully unpacked and MD5 sums checked
package ‘snow’ successfully unpacked and MD5 sums checked
package ‘bitops’ successfully unpacked and MD5 sums checked
package ‘SummarizedExperiment’ successfully unpacked and MD5 sums checked
package ‘RCurl’ successfully unpacked and MD5 sums checked
Warning: unable to move temporary installation ‘C:\Program Files\R\R-3.4.0\library\file488c5e627a44\RCurl’ to ‘C:\Program Files\R\R-3.4.0\library\RCurl’
package ‘XVector’ successfully unpacked and MD5 sums checked
package ‘gtable’ successfully unpacked and MD5 sums checked
package ‘plyr’ successfully unpacked and MD5 sums checked
package ‘scales’ successfully unpacked and MD5 sums checked
package ‘tibble’ successfully unpacked and MD5 sums checked
package ‘lazyeval’ successfully unpacked and MD5 sums checked
package ‘stringr’ successfully unpacked and MD5 sums checked
package ‘BiocParallel’ successfully unpacked and MD5 sums checked
package ‘Rsamtools’ successfully unpacked and MD5 sums checked
Warning: unable to move temporary installation ‘C:\Program Files\R\R-3.4.0\library\file488c597c3e37\Rsamtools’ to ‘C:\Program Files\R\R-3.4.0\library\Rsamtools’
package ‘GenomicAlignments’ successfully unpacked and MD5 sums checked
Warning: unable to move temporary installation ‘C:\Program Files\R\R-3.4.0\library\file488c6cd014a0\GenomicAlignments’ to ‘C:\Program Files\R\R-3.4.0\library\GenomicAlignments’
package ‘GenomeInfoDb’ successfully unpacked and MD5 sums checked
package ‘GenomicRanges’ successfully unpacked and MD5 sums checked
Warning: unable to move temporary installation ‘C:\Program Files\R\R-3.4.0\library\file488c2d305a4e\GenomicRanges’ to ‘C:\Program Files\R\R-3.4.0\library\GenomicRanges’
package ‘hwriter’ successfully unpacked and MD5 sums checked
package ‘zlibbioc’ successfully unpacked and MD5 sums checked
Warning: unable to move temporary installation ‘C:\Program Files\R\R-3.4.0\library\file488c260d70ab\zlibbioc’ to ‘C:\Program Files\R\R-3.4.0\library\zlibbioc’
package ‘latticeExtra’ successfully unpacked and MD5 sums checked
package ‘Biostrings’ successfully unpacked and MD5 sums checked
package ‘ggplot2’ successfully unpacked and MD5 sums checked
package ‘data.table’ successfully unpacked and MD5 sums checked
package ‘reshape2’ successfully unpacked and MD5 sums checked
package ‘ShortRead’ successfully unpacked and MD5 sums checked
Warning: unable to move temporary installation ‘C:\Program Files\R\R-3.4.0\library\file488c5a0f30bb\ShortRead’ to ‘C:\Program Files\R\R-3.4.0\library\ShortRead’
package ‘RcppParallel’ successfully unpacked and MD5 sums checked
Warning: unable to move temporary installation ‘C:\Program Files\R\R-3.4.0\library\file488c3bdd7e5\RcppParallel’ to ‘C:\Program Files\R\R-3.4.0\library\RcppParallel’
package ‘dada2’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\zippy_000\AppData\Local\Temp\Rtmp6zNPr1\downloaded_packages
installing the source package ‘GenomeInfoDbData’

trying URL 'https://bioconductor.org/packages/3.5/data/annotation/src/contrib/GenomeInfoDbData_0.99.0.tar.gz'
Content type 'application/x-gzip' length 16238792 bytes (15.5 MB)
downloaded 15.5 MB

* installing *source* package 'GenomeInfoDbData' ...
** data
** inst
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (GenomeInfoDbData)

The downloaded source packages are in
        ‘C:\Users\zippy_000\AppData\Local\Temp\Rtmp6zNPr1\downloaded_packages’

**Comment by benjjneb** [comment]
>Warning: unable to move temporary installation ‘C:\Program Files\R\R-3.4.0\library\file488c3bdd7e5\RcppParallel’ to ‘C:\Program Files\R\R-3.4.0\library\RcppParallel’

The installer is failing to move the installed packages from the temporary directory into the proper R directory. This indicates a permissions issue, that you don't have permission to write to that directory as currently logged in.

Have to admit I am not a Windows user so I can't give you step-by-step on this, but this should be fixed if you can run this as "admin" or "root" or whatever the super-user is called on Windows.

**Comment by zippymimosa** [comment]
Yes I did tried run as admin and I have tried to install from the RGui package tab. What's very confusing is that some of the other packages are loading fine such as the ggplot2 but not dada2.

**Comment by zippymimosa** [comment]
The dada2 is already in the package tab from the RGui. It's just when I run library("dada2"), it says
Error: package or namespace load failed for ‘dada2’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):

**Comment by benjjneb** [comment]
According to [here](http://stackoverflow.com/questions/30308639/r-cran-install-library-rcpp-fails-after-r3-2-upgrade) you may want to try the install again with no packages loaded (i.e. restart R and run the Bioconductor install in that fresh session).

Does that work?

**Comment by zippymimosa** [comment]
No.. I actually tried fresh sections, or reinstall R many times, and on 2 computers I got the same issue. I just tried to unzip the dada2 pacakge and mannually paste it into the library it still give me that error message.

Now I feel it seems a loading issue rather than an install issue??

**Comment by benjjneb** [comment]
If some necessary packages, like `ShortRead` are failing to install, then you won't be able to load `dada2`.

I'm not sure. Googling also suggests [turning off your anti-virus](http://stackoverflow.com/questions/5700505/windows-7-update-packages-problem-unable-to-move-temporary-installation) while performing the install, as some can interfere with the copying of files from temporary locations.

A last alternate suggestion is `devtools::install_github("benjjneb/dada2")` (you may have to install the `devtools` package first if you don't already have it).

**Comment by zippymimosa** [comment]
I guess that's the issue that I have misssing some other packages. Now it seems working as I mannually download the binary files for a dozen packages, unzip and paste them into the library folder. Yeah!! Thanks for your time and all suggestions!

**Comment by benjjneb** [comment]
Great, glad it is working. Windows is definitely the platform with the most weird installation issues.
