### ISSUE TITLE
plotProfileQuality error

### ISSUE THREAD

**Issue by gk-bioin4m8x** [benjjneb/dada2#243]
Hi @benjjneb ,
I am interested to filter and trim my several paired-end RNA-Seq samples (HiSeq 3000) using `fastqPairedFilter` , so I am trying `dada2` on one sample. I am trying to inspect the quality before filtering and trimming, but it gives me error while using `plotQualityProfile`.

```
# Installed packages
>library("ShortRead")
>library("dada2")

# Read fastq files
>N_R1 = readFastq("N_R1_001.fastq.gz")			
>N_R2 = readFastq("N_R2_001.fastq.gz")

>filt_N_R1 <- tempfile(fileext=".fastq.gz")
>filt_N_R2 <- tempfile(fileext=".fastq.gz")

# Inspect the quality of data before filtering and trimming
>plotQualityProfile(N_R1)
**Error: UserArgumentMismatch
  'lane' must be 'character(1)**

>plotQualityProfile(N_R2)
**Error: UserArgumentMismatch
  'lane' must be 'character(1)**
```

Kindly guide.
Thanks!

**Comment by benjjneb** [comment]
`plotQualityProfile` expects filepaths rather than fastq files that have already been read in via `readFastq`. If you just replace `N_R1` with the file path it should work as expected.

**Comment by gk-bioin4m8x** [comment]
It worked. Thanks!
