### ISSUE TITLE
get "replicated" demultiplexed merged sequences 

### ISSUE THREAD

**Issue by aparada** [benjjneb/dada2#245]
Hello,
I would like to export a fasta file that has all the merged dada2 sequences that belong to all samples in the dataset with the name of the sample in  the header and unique sequence identifier, like you could get from mothur or qiime i.e. >WaterColumnS1_334580   I don't want just the unique sequences per sample but rather all of the sequences with the proper headers, either all in one fasta file or individual fasta files. I've seen similar previous posts, but either no clear solution or other's solution doesn't seem to be working for me.  I'd like to be able to use the dada2 filtered and merge sequences in other tools to run some comparisons, but I haven't been able to figure out how to get the merged sequences out of dada2 with the sample names in the headers. Any suggestions?

**Comment by benjjneb** [comment]
That is doable by using functions available in the ShortRead package. Basically you're going to want to create a "re-replicated" ShortRead object, and then use the `writeFasta` file to save it.

Depending on your familiarity with R you may be able to do that yourself (you can look at the code for `uniquesToFasta` to see the basic idiom), but I am happy to help as well. However, you would need to be more specific on exactly what you want to do.

An example of being specific: Take the output of `makeSequenceTable` and create a re-replicated (one entry per read) fasta file containing all samples, and with the id line of each read being `>SampleName_XXX` where XXX is the number of the read in that sample.
