### ISSUE TITLE
Multithreading for sample inference step

### ISSUE THREAD

**Issue by adityabandla** [benjjneb/dada2#249]
Hi 

Although, the multithreading option is enabled for all the computationally intensive steps, can the computations scale across multiple nodes or are they restricted to threads available on a single compute node?

Best,

**Comment by benjjneb** [comment]
The multithreading built into the functions will only take advantage of the threads available within that compute node. However, you can also run subsets of your data on independent nodes (data parallelism) and then just combine the saved outputs into a final sequence table at the end.

I commonly do this with multiple sequencing runs (send each run to its own node), but you can break things up more than that depending on your compute environment and your job submission facilities.

**Comment by adityabandla** [comment]
Thanks Ben! 

The error learning step seems to be taking quite a while (24h+), when I pool all my reads (approx. 10M reads). Is it still valid, if I merge all my samples together, then generate random subsets of 1M, 5M etc and then run the error learning step on these subsets?
 
On another note, as a first time user of DADA2, I found the tutorials a bit confusing, largely due to the inconsistency in the sequence of steps detailed (for instance, the dereplication step is sometimes before the error learning step while its after the error learning steps in others, although it has nothing to do with the error learning step).

I finally figured out the individual steps, common to all the workflows. Although trivial, it would be great to organize all the workflows, so that they contain the same sequence of steps

**Comment by benjjneb** [comment]
Yes you can learn error rates from a subset of the data. For best results, you should learn error rates for each run though, in case the runs differed significantly.

The subsetting is taken care of by default by the `learnErrors` function. What version of the tutorial are you using? The [tutorial for the current release (1.4)](http://benjjneb.github.io/dada2/tutorial.html) and the [Big Data tutorial for 1.4](http://benjjneb.github.io/dada2/bigdata.html) both use `learnErrors` and should be consistent with each other.

The 1.2 versions might not be quite so consistent, so I'd recommend using the updated workflows and the current release of the package.

**Comment by fanli-gcb** [comment]
Is there any difference in running `learnErrors` on `filtFs` versus `derepFs`? Or will they do the exact same thing?

**Comment by benjjneb** [comment]
> Is there any difference in running learnErrors on filtFs versus derepFs? Or will they do the exact same thing?

Same thing, just a convenience to be able to provide either input format.

**Comment by adityabandla** [comment]
Hi Ben

Thanks for the super useful pointers thus far. I have been running DADA2 with different parameters to see how they affect the run time. As you have mentioned in the tutorials, that run time scales quadratically with depth, is there an alternate approach to circumvent this for high depth and highly diverse samples, such as soil?

Currently, I have close to 200K sequences per sample and 27 of them, DADA2 takes 24+ to churn through them. I pooled all my samples for the error estimation step

**Comment by adityabandla** [comment]
Hi Ben

Apologies for not thoroughly reading the issues that have been closed. I have a much better understanding of how to deal with this now

Best,
Aditya
