### ISSUE TITLE
Potential false convergence?

### ISSUE THREAD

**Issue by adityabandla** [benjjneb/dada2#254]
Hi Benjamin

This pertains to the same dataset I mentioned in #253 

I first tried running the error learning step on a subset `(n=9)` of my samples. The error model converged after 8 rounds

I then tried it using all the samples `(n=27)`. Surprisingly, the error model did not converge after 10 rounds. I was expecting it to converge in less than or equal to 8 rounds. Not sure whats going on here

Regards,
Aditya

**Comment by benjjneb** [comment]
There's no reason to think that more samples will cause the error model to converge faster.

While exact convergence usually happens before 10 rounds, there is no guarantee, and we know that cases/datasets exist where complete convergence is very slow. But, don't worry about it. As long as you are close to convergence, that is fine -- you are still getting an error model that fits your data far better than any pre-trained error model ever could.

If you want to compare what you got from the subset of 9, and all the samples after 10 rounds, you can do that too. Try `plotErrors(err9, nominalQ=TRUE)` and likewise for `err27`. I would be surprised if the two trained error models are not nearly identical.

You can also inspect the error models themselves, they are just matrices.

**Comment by adityabandla** [comment]
Thanks Ben!

**Comment by adityabandla** [comment]
Hi Ben

The error model failed to converge after 10 rounds and following is the plot

![image](https://cloud.githubusercontent.com/assets/17331245/26818352/e0519d76-4acc-11e7-9352-43cacb4d93f3.png)

**Comment by benjjneb** [comment]
The black lines (the model) are fitting the points (the observations) well, error rates are decreasing w/ increasing quality as expected, and the absolute difference in the error model is orders of magnitude smaller at the end than at the start (1e-4 vs. 4e1 and 8e-1).

Looks good to me, I'd go ahead and use it.

**Comment by adityabandla** [comment]
Thanks Ben for the pointers!
