### ISSUE TITLE
multiple sequencing runs for one study

### ISSUE THREAD

**Issue by demmitba** [benjjneb/dada2#257]
Hello,

Thank you for this great program and detailed tutorials!  My study consists of of 3000 samples randomized over 5 miseq  runs.   I have run my data to dada2 (including merging the reads) following the tutorial and it seems to have run well.  I did this by processing each of my sequencing runs separately, and then can combine the sequence tables. However it seems alternatively I can use the "pool" option in the dada function to run all of my samples together. My understanding is that while both methods are valid, if I use "pool" I may better identify the very rare reads. Is that correct?  

If that is accurate and I do decide to "pool" all samples, would I just list all of the 5 sets of forwards reads as the input to the line below of the tutorial (and then same for the reverse), an altered example shown below.

derepFs <- derepFastq(filtFs, verbose=TRUE)  #one miseq 
derepFs <- derepFastq(fls=c('filtFs1','filtFs2','filtFs3','filtFs4','filtFs5',), verbose=TRUE) #all 5 misses

Thank you so much for your help!

Brittany

**Comment by benjjneb** [comment]
> My understanding is that while both methods are valid, if I use "pool" I may better identify the very rare reads. Is that correct?

Yep, that's right. The cost though is (potentially substantially) increased computation time when pooling samples. As a rule of thumb, pooling is reasonable up to about 1 Miseq run worth of data (although other factors such as diversity/chimera-rate/error-rate/filtering/read-number etc. play into the cutoff).

> If that is accurate and I do decide to "pool" all samples, would I just list all of the 5 sets of forwards reads as the input to the line below of the tutorial (and then same for the reverse), an altered example shown below.

That should work (but remove the apostrophes in the second line). As said above though, pooling 5 Miseq runs will challenge your computational resources. Additionally, you will want to check that the error models from each run are giving basically the same result. If the different runs have different error models, we don't recommend pooling them together (although you can as long as you use the highest run-specific error model for the pool).

Pooling on a per-run basis might make more sense for you. That avoids any issues with run-to-run variation in error rates, and it will still help you pick up more rare variants if that is important. Right now (assuming you are following the tutorial or Big Data workflow) each *sample* is being processed individually. Pooling all the samples in each run will still increase power to detect low-frequency variants.

**Comment by demmitba** [comment]
Thank you so much for your comment, that is very helpful!  I will definitely process the sequencing runs separately as you suggest. If I understand correctly, if I follow the big data work flow and process each sequence run separately through the sample inference script even if the error models are different between sequencing runs that is “ok” since they are processed separately. The runs can then be combined, as in the tutorial, before chimera removal.

Just a quick question, when you reference comparing the error models do you mostly do that by comparing the plots?  plotErrors(errF, nominalQ=TRUE)

Thank you so much for your help!

**Comment by benjjneb** [comment]
>  If I understand correctly, if I follow the big data work flow and process each sequence run separately through the sample inference script even if the error models are different between sequencing runs that is “ok” since they are processed separately. The runs can then be combined, as in the tutorial, before chimera removal.

Yes that is OK.

> when you reference comparing the error models do you mostly do that by comparing the plots? plotErrors(errF, nominalQ=TRUE)

That would be my first step. If I want to get more into the weeds, the error models are just matrices that I can manipulate and compare using standard R commands.

**Comment by demmitba** [comment]
Great, thank you!
