### ISSUE TITLE
High abundance low prevalence sequence variants 

### ISSUE THREAD

**Issue by benjamfield** [benjjneb/dada2#258]
Hello,

I have approximately 100 samples gathered from the oral microbiome, with around 2800 denoised sequence variants across all samples. Plotting prevalence against total abundance shows the following pattern of many DSVs having a reasonably high abundance while not being very prevalent. 

![prevalence_plot](https://user-images.githubusercontent.com/11425618/27085883-7307df56-5048-11e7-838b-eea5d8f057c6.png)

I'm hoping to identify DSVs associated with various sample conditions. If I trim DSVs that occur in less than 5% of samples I am left with around 600 DSVs. I have the following thoughts:

* Given the abundance of many of these low-prevalence DSVs I think I am observing true biological variation rather than noise 
* The low prevalence suggests there is a low overlap of DSVs across samples 
* If I am looking for consistent markers of conditions it would be sensible to trim DSVs with a prevalence between 0-10% 
* However, trimming these DSVs would probably bias diversity estimates and differential abundance tests

Overall I am unsure if trimming is a good idea, and there is probably no correct answer, but I don't want to throw away useful data containing real biological variation.  I'd appreciate any input you might have. 

Also, thanks for making dada2, it's a great piece of software.

Cheers,
Ben

**Comment by benjjneb** [comment]
Hi Ben,
The type of filtering you do should take into account the subsequent analysis you will perform, and you may want to consider different filtering stringencies for different analyses.

For example, if testing differential abundance, low prevalence taxa will never have enough statistical evidence to be called significant, so all they do is cost power by increasing the number of hypotheses. Therefore it makes sense to do an independent filtering step that removes all low-prevalence taxa.

However, as you mentioned, low-prevalence taxa still contribute to estimates of diversity, so independent filtering should be limited before performing those estimates.

In my own analysis I typically perform an initial filtering step of all taxa that appear in <2 or <3 samples (based on study size) before all analyses, as we know that many single-sample taxa are in fact contaminants (although this loses real taxa as well). Then I may filter more stringently before other analyses as warranted. But there is no one right answer!

-Ben

**Comment by benjamfield** [comment]
That makes sense, thank you for the input. These sorts of questions are always awkward!
