### ISSUE TITLE
"OTU" like table

### ISSUE THREAD

**Issue by alias200** [benjjneb/dada2#260]
I have followed this tutorial (see link below) to process my raw data but I am not sure how I can generate a file in the similar format of an OTU table

Variant   Sample1   Sample2 Sample 3       Taxonomy 
1
2
3

http://benjjneb.github.io/dada2/tutorial.html

**Comment by benjjneb** [comment]
We don't have a custom function for this, but you can use the standard R tools for outputting tabular files, in particular `write.table` (more flexible) or `write.csv` (easier to import into Excel).

If doing just the sequences table the following should get you about what you want:
```
write.table(t(seqtab),  "path/to/seqtab.tsv") 
# t() transposes the dada2 sequence table which has samples as rows
```

If you want an expanded table with the taxonomy levels as well (and doing csv this time):
```
write.csv(cbind(t(seqtab), taxa), "path/to/seqtab.csv", quote=FALSE)
```

Depending on the exact format you want (i.e. what software you want to import into) it may be worth looking at the options in `write.table`, in particular `col.names` and `sep` and `quote`.
