### ISSUE TITLE
filtering process

### ISSUE THREAD

**Issue by alias200** [benjjneb/dada2#261]
I used this command to filter my data

out <- filterAndTrim(fnFs,filtFs,fnRs,filtRs, truncLen=c(290,190), trimLeft=c(17,21),
              maxN=c(0,0), maxEE=c(2,2), truncQ=c(2,2), rm.phix=c(TRUE,TRUE), 
              compress=TRUE, multithread=TRUE)

As a test, I am using 2 samples

When I do:  print(derepFs), I get the following

$`L-mono`
derep-class: R object describing dereplicated sequencing reads
$uniques: 94527 reads in 14072 unique sequences
  Sequence lengths: min=273, median=273, max=273
$quals: Quality matrix dimension:  14072 273
  Consensus quality scores: min=7, median=37, max=38
$map: Map from reads to unique sequences:  2 1 1 19 1 ...

$`LLNL-NTC`
derep-class: R object describing dereplicated sequencing reads
$uniques: 191 reads in 98 unique sequences
  Sequence lengths: min=273, median=273, max=273
$quals: Quality matrix dimension:  98 273
  Consensus quality scores: min=7, median=38, max=38
$map: Map from reads to unique sequences:  2 1 1 72 31 ...

> print(derepRs)
$`L-mono`
derep-class: R object describing dereplicated sequencing reads
$uniques: 94527 reads in 7496 unique sequences
  Sequence lengths: min=169, median=169, max=169
$quals: Quality matrix dimension:  7496 169
  Consensus quality scores: min=8, median=37, max=38
$map: Map from reads to unique sequences:  2761 1 32 1 1 ...

$`LLNL-NTC`
derep-class: R object describing dereplicated sequencing reads
$uniques: 191 reads in 82 unique sequences
  Sequence lengths: min=169, median=169, max=169
$quals: Quality matrix dimension:  82 169
  Consensus quality scores: min=8, median=37, max=38
$map: Map from reads to unique sequences:  2 1 1 1 7 ...

As you can see, there are a lot of reads that I have in my L-mono sample, the NTC is a negative control

When I do merge, I get this output
53 paired-reads (in 2 unique pairings) successfully merged out of 94527 (in 16 pairings) input.
136 paired-reads (in 5 unique pairings) successfully merged out of 191 (in 12 pairings) input.

L-mono
  abundance forward reverse nmatch nmismatch nindel prefer accept
4        36       3       3     46         0      0      2   TRUE
5        17       6       1    169         0      0      2   TRUE

And my sequence table has under 100 reads

My samples overlap, but I am wondering if I should be using the "fastqPairedFilter" command instead of "FilterandTrim" however when I run  that command I get this error message

Command:

fastqPairedFilter(fnFs,filtFs,fnRs,filtRs, truncLen=c(290,190), trimLeft=c(17,21),
              maxN=c(0,0), maxEE=c(2,2), truncQ=c(2,2), rm.phix=c(TRUE,TRUE), matchIDs = TRUE
              compress=TRUE, multithread=TRUE)

error message: Error in isPhiX(as(sread(fqF), "character"), ...) : 
  unused argument (multithread = TRUE)

When I removed matchIDs from the command, I got this error message
Error in fastqPairedFilter(fnFs, filtFs, fnRs, filtRs, truncLen = c(290,  : 
  Mismatched forward and reverse sequence files: 167839, 428.

Thanks

**Comment by benjjneb** [comment]
`fastqPairedFilter` uses a different input format than `filterAndTrim` for the unfiltered and filtered file-names, so that is the problem you are having there.

Most commonly when few reads are being merged it is because the trimmed F/R reads aren't overlapping anymore. What amplicon are you sequencing (with what primer set)?

**Comment by alias200** [comment]
I am using V3-V4 primers and a 2x300 paired end run
I have truncated the Forward reads after 290 and the reverse reads after 180bp so I should still have enough overlap. 
Since the setting is for zero mismatches in the overlap region, perhaps there is too many mismatches between the forward and reverse reads?  Would you recommend relaxing the parameters for that or would that defeat the quality control purpose of that step. 
I have checked the forward and reverse reads separately and they are hitting the expected organisms (I am testing on our positive control) with accuracy and excellent matches

**Comment by benjjneb** [comment]
I don't think I've ever seen a dataset where the overlap mismatches needed to be relaxed -- its almost always too little total length to get enough overlap for merging (20 nts of overlap or more required).

Can you try longer lengths on the test files, like `truncLen=c(290, 240)`, and see if that solves the issue? If not, can you share the fastqs for the F/R reads for a single sample?
