### ISSUE TITLE
could not find the function "filterAndTrim"

### ISSUE THREAD

**Issue by rahulnccs** [benjjneb/dada2#262]
I am analyzing sequencing data but at trimming step its showing this error could not find the function"filterAndTrim" 
plz do help.

**Comment by benjjneb** [comment]
The `filterAndTrim` function was introduced in the 1.4 release of the package. If you have an earlier packager version (`packageVersion("dada2")`) you either need to update to the current release, or follow [the previous version of the tutorial](http://benjjneb.github.io/dada2/tutorial_1_2.html).

**Comment by rahulnccs** [comment]
Thanks I tried following previous version tutorial, but I stuck here, 
# Filter
for(i in seq_along(fnFs)) {
  fastqPairedFilter(c(fnFs[i], fnRs[i]), c(filtFs[i], filtRs[i]),
                    truncLen=c(240,160), 
                    maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                    compress=TRUE, verbose=TRUE)
}

what is mean by i here. after running this command it says, "two paired input file name required" though I've followed the same commands and proper file path. thanks in advance.

**Comment by benjjneb** [comment]
Can you clarify a couple things: What kind of data are you working with (eg. sequencing tech, paired or single-read)? What is the `packageVersion("dada2")` that you have? What is the output of `R.version`?

**Comment by rahulnccs** [comment]
I followed the previous version of the tutorial. Ir worked.
Thank you.
