### ISSUE TITLE
filterAndTrim -  colnames error - ShortReads depends on sf which depends on gdal 2.x

### ISSUE THREAD

**Issue by bioinfonm** [benjjneb/dada2#264]
In a closed issue I updated to the new Bioconductor and tried to upgrade ShortReads. 

Running filterAndTrim  now give this error message:
`Error in `colnames<-`(`*tmp*`, value = c("042116DN27F_full.fastq", "072216DN27F2_full.fastq",  : 
  attempt to set 'colnames' on an object with less than two dimensions
In addition: Warning message:
In mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule,  :
  all scheduled cores encountered errors in user code`

I then install gdal 2.1 by way of http://www.kyngchaos.com/software/frameworks

Then this again
`biocLite("ShortRead", suppressUpdates = FALSE)
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.5 (BiocInstaller 1.26.0), R 3.4.0 (2017-04-21).
Installing package(s) ‘ShortRead’
trying URL 'https://bioconductor.org/packages/3.5/bioc/bin/macosx/el-capitan/contrib/3.4/ShortRead_1.34.0.tgz'
Content type 'application/x-gzip' length 4884355 bytes (4.7 MB)`

and this hot mess of sf
`There is a binary version available but the source version is later:
   binary source needs_compilation
sf  0.4-3  0.5-0              TRUE

Do you want to install from sources the package which needs compilation?
y/n: y
installing the source package ‘sf’

trying URL 'https://cran.rstudio.com/src/contrib/sf_0.5-0.tar.gz'
Content type 'application/x-gzip' length 4071488 bytes (3.9 MB)
==================================================
downloaded 3.9 MB

* installing *source* package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
configure: CC: clang
configure: CXX: clang++
checking for gdal-config... /usr/local/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 1.11.3
checking GDAL version >= 2.0.0... no
configure: error: sf is not compatible with GDAL versions below 2.0.0
ERROR: configuration failed for package ‘sf’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/sf’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/sf’

The downloaded source packages are in
	‘/private/var/folders/sz/c8lxp6kj6yq89fhnzt2nxqhc0000gn/T/RtmpB8ejbe/downloaded_packages’
Warning message:
In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘sf’ had non-zero exit status`

**Comment by bioinfonm** [comment]
Ok so I gutted the old gdal 1.11 and then new gdal 2. I re-installed redal 2 by using homebrew. Per instructions here:
https://www.karambelkar.info/2016/10/gdal-2-on-mac-with-homebrew/

Then back to R and re-installed rgdal and sf. Then ShortReads.
`biocLite("ShortRead", suppressUpdates = FALSE)
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.5 (BiocInstaller 1.26.0), R 3.4.0 (2017-04-21).
Installing package(s) ‘ShortRead’
trying URL 'https://bioconductor.org/packages/3.5/bioc/bin/macosx/el-capitan/contrib/3.4/ShortRead_1.34.0.tgz'
Content type 'application/x-gzip' length 4884355 bytes (4.7 MB)
==================================================
downloaded 4.7 MB`

So far so good. 

Then the colnames error again.
`out <- filterAndTrim(fn, filt, truncLen=c(240,160),
+ maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
+ compress=TRUE, multithread=TRUE)
Creating output directory:./Miseq//filtered
Error in `colnames<-`(`*tmp*`, value = c("042116DN27F_full.fastq", "072216DN27F2_full.fastq",  : 
  attempt to set 'colnames' on an object with less than two dimensions
In addition: Warning message:
In mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule,  :
  all scheduled cores encountered errors in user code`
`

**Comment by bioinfonm** [comment]
UPDATE:

Found an issue with my `path <-`

I have that solved so I am back to this error:
`Creating output directory:/Users/ara/Desktop/tor_cry/Miseq//filtered
Error in `colnames<-`(`*tmp*`, value = basename(fwd)) : 
  attempt to set 'colnames' on an object with less than two dimensions
In addition: Warning message:
In mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule,  :
  all scheduled cores encountered errors in user code`

**Machine stats**
OS X 10.11.6
Latest XCode

**gdal-config --version**
2.1.3

**R version**
$version.string
[1] "R version 3.4.0 (2017-04-21)"

$nickname
[1] "You Stupid Darkness"

**Bioconductor**
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.5 (BiocInstaller 1.26.0), R 3.4.0 (2017-04-21).

**ShortReads**
1.34.0

**Comment by benjjneb** [comment]
Can you run with `multithread=FALSE` and `verbose=TRUE`?

That should print out the actual error message (rather than the opaque `all schedule cores encountered errors in user code` that you get from errors within `mclapply`).

**Comment by bioinfonm** [comment]
@benjjneb Will do!

`out <- filterAndTrim(fn, filt, truncLen=c(240,160),
                     maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, multithread=FALSE, verbose=TRUE)`

**Here is the output**
`Error in .Call2("solve_user_SEW", refwidths, start, end, width, translate.negative.coord,  : 
  solving row 3417: 'allow.nonnarrowing' is FALSE and the supplied end (240) is > refwidth
In addition: Warning messages:
1: In if (end < start) { :
  the condition has length > 1 and only the first element will be used
2: In if (!is.na(end)) { :
  the condition has length > 1 and only the first element will be used`

**Comment by benjjneb** [comment]
That suggest that your reads are shorter than 240 nucleotides, so its failing (not very gracefully!) on the step where its trying to truncate the reads to 240.

Can you check the length of your reads? What kind of data is this (eg. 454/illumina)?

Since your fastq files were converted form .qual files, can you run `plotQualityProfile` on one of your files to see if you get a reasonable output?

**Comment by bioinfonm** [comment]
I think I see one problem! Looks like it's a problem on my end. 

I was given this data set without much information about it. Let me close this and see if I can gather up everything about these samples.
