### ISSUE TITLE
A DADA2 workflow for Big Data (1.4)

### ISSUE THREAD

**Issue by rahulnccs** [benjjneb/dada2#266]
Hello,
I was using DADA2 Pipeline Tutorial (1.4), but I realized it is taking too much of time and my sequencing data had more than 60M+ reads. Thus After filterAndTrim I shifted to dada2 workflow for big dada. Here in the beginning part, it is mentioned that the workflow required demultiplexed and the primer-free forward reads. In my case, the folder contains output from filterAndtrim (both forward and reverse reads). I am dereplication step. Plz, guide I'm going in the right direction?

**Comment by benjjneb** [comment]
That sounds fine. The filtering performed in the two workflows is functionally identical, so you can use your already filtered data.
