### ISSUE TITLE
Typo in Silva training fasta

### ISSUE THREAD

**Issue by benjjneb** [benjjneb/dada2#269]
Escherichia/Shigella is mispelled as Eschericha/Shigella (missing a).

**Comment by benjjneb** [comment]
Created updated version of the Silva training fasta (with typo fixed), available [via the web site](https://benjjneb.github.io/dada2/training.html) or directly from Zenodo: https://zenodo.org/record/824551#.WWE6MdPyvzU

**Comment by janetw** [comment]
I realize that this is for dada2 issues but do you know if there is a way to correct the taxa name in a phyloseq object that has already been created with the output from dada2 before the fix? Or should I repost in the phyloseq forum? Thanks!

**Comment by janetw** [comment]
I figured it out. Thanks!
