### ISSUE TITLE
plotErrors

### ISSUE THREAD

**Issue by rahulnccs** [benjjneb/dada2#270]
During plotting error rates I am getting 

Warning message:
Transformation introduced infinite values in continuous y-axis
 Though I've got following results for 

> errF <- learnErrors(filtR1, multithread=TRUE)
Initializing error rates to maximum possible estimate.
Sample 1 - 587711 reads in 402742 unique sequences.
Sample 2 - 613348 reads in 427810 unique sequences.
   selfConsist step 2
   selfConsist step 3
   selfConsist step 4
   selfConsist step 5
   selfConsist step 6
   selfConsist step 7
   selfConsist step 8
Convergence after  8  rounds.
Total reads used:  1201059

Thanks in advance.

**Comment by benjjneb** [comment]
Ignore that warning, it is normal and expected (it means that some specific Q score substitution combinations weren't observed in your data, which is fine).
