### ISSUE TITLE
data merging 

### ISSUE THREAD

**Issue by rahulnccs** [benjjneb/dada2#271]
Hello, Previously I had small sequencing data that worked fine with dada2 (version1.4). This time I am facing problem at dereplication step due to huge sequence data, thus I divided data into two halves, and running half sample at a time. During merging of paired ends, I am planning to use whole sequence data to construct OTU table. Does this affects the error learning or other parameters? will it be right?

**Comment by benjjneb** [comment]
The tutorial dataset is small enough to easily load into memory. If your dataset exceeds available RAM, it is preferable to process samples one-by-one in a streaming fashion: see the [DADA2 Workflow on Big Data](https://benjjneb.github.io/dada2/bigdata.html) for an example.

**Comment by rahulnccs** [comment]
Hi benjjneb, DADA2 Workflow on big data requires primer free forward reads only. Then what is the use of reverse reads?
 I am new to DADA2, spent more than 20 days but its not working for me. Thanks for the help.

**Comment by benjjneb** [comment]
There is a link in the big data workflow to a [paired-end version](https://benjjneb.github.io/dada2/bigdata_paired.html).
