### ISSUE TITLE
Sequence Variants commonly sample singletons

### ISSUE THREAD

**Issue by benkraj** [benjjneb/dada2#275]
Hi-

I'm just curious how often we would expect each sequence variant to be only present in a single sample? In my dataset of 2155 SVs across 53 samples, only 167 SVs are present in more than one sample (i.e. 1988 are only present in one sample). These are all from the same general sample type. I see in the bioconductor dataset only 2 SVs of 389 are sample singletons.

Have you seen this issue, and is this likely indicating a problem in my data processing or a quirk of my samples?

Thanks,
Ben

**Comment by benkraj** [comment]
Edit. I should have searched better. I see this has been brought up before here:
https://github.com/benjjneb/dada2/issues/258
and
https://github.com/benjjneb/dada2/issues/226

**Comment by benkraj** [comment]
Actually I guess this question has a bit more nuance in that it seems more severe than in other cases. Does having 92.3% of my SVs being seen in only one sample indicate a greater issue with my upstream processing?

**Comment by benjjneb** [comment]
> Does having 92.3% of my SVs being seen in only one sample indicate a greater issue with my upstream processing?

That seems really high. What fraction of all reads do those 1-sample SVs account for?

Given what you've said (the sample are all of the "same type") I would be somewhat concerned this might have an artefactual source. Is there any share characteristic of the single-sample SVs (eg. how are they classified taxonomically?).

One thing to consider for 454 sequences is adding a `maxLen` filters, which will throw away very long 454 sequences which were shown in the past to be associated with errors. No idea if that would help with this issue though.

**Comment by benkraj** [comment]
Hey Ben-

I tried shortening the read length, didn't seem to change things really, 2175 of 2408 reads have a prevalence of 1 (numbers did change a bit as I switched to the Silva 128 database from 123).

The abundance of the sample singletons is 29.2% of the total reads (80513 of 275690 total).

I'll give the maxLen flag a shot. Would this just be something like truncLen=300, maxLen=500?

I'm a bit unclear on how maxLen functions in relation to truncLen---I thought this made it so everything is a length of 300? Does maxLen act first so it discards any long reads and then only reads shorter than 500 are then truncated to 300?

There's no obvious trend to the 1-sample SVs in terms of taxonomic classification (i.e. most are classified to varying degrees, many to genus). I can provide tables if this is easier to parse.

Thanks,
Ben

**Comment by benkraj** [comment]
Also, when I mention they are the "same type," to clarify further, they are all whole mosquito samples from wild sources. So there may be a fair amount of variability in the samples, but I'm just making sure I didn't misstep somewhere.

Also, I ran with the truncLen=300, maxLen=500 and found no strong differences from before.

**Comment by benjjneb** [comment]
At this point I think it is simply hard to say what these single-sample SVs are. Some of them are real -- SVs that appear in single samples happen. The rate that you are seeing is higher than in the datasets I look at, but I also mostly analyze longitudinal data so it isn't really comparable. We just don't know what the true number of single-mosquito (w/in these 53 samples) SVs is.

It is a good sign that a majority of reads are in the multi-sample SVs.

My thought for further analysis, is to consider both the full communities and communities with single-sample SVs removed, with the expectation that the full community data would be the "real analysis" but the single-sample-free data serving as a check. But that's just a thought.

**Comment by benkraj** [comment]
Ok great. I think that's a good plan moving forward. In the bit I'd done with abundance testing having them or not didn't change things dramatically.

I haven't yet checked ordination/etc, but it shouldn't be too hard to keep/drop them and compare.

Thanks for your help.

**Comment by km4htc** [comment]
Hi  @benkraj --
I'm curious if you were ever able to resolve your problem. I have 6 samples that I ran through qiime2 using dada2: 3 are biological replicates of storage roots, and another 3 are biological replicates of fibrous roots (the two sample types coming from the same three plants). Given that all my samples are roots are taken from the same host plant species and that they're coming from a greenhouse, I would expect most/many of the ASVs to be similar between all the samples, or at least within sample types. However, a first pass through dada2 had ~97% of my ASVs being found in just one sample; a second pass, in which I shortened the truncation lengths to accommodate a shorter overlap (to try to ditch a few more lower quality bases) ended up with 98% sample-specific ASVs. Fewer than 10 of my ~1200 ASVs were found in more than 2 samples; none were found in 3 or more. I can provide more details if helpful--I'm just curious if you found a way to resolve the issue. 
Thanks!!

**Comment by benkraj** [comment]
Hi km4htc-

In my case I didn't resolve this per se, but explained it through a few things. One was that I was using 454 data, so I expected my sampling coverage wasn't as deep as it could have been--and maybe some of these rare singletons would have better representation with illumina or deeper coverage. Another is that I found most of the reads were in the non-singleton sequence variants (68.0% of reads were in non-singleton samples), so functionally it didn't matter that much for differential abundance testing through DESeq2 etc.

My prevalence certainly wasn't as limited as yours, i.e. in my 57 samples (2057 sequence variants), the highest prevalence SV was in 39 samples, but of the 2057 variants only 41 were in greater than 3 samples.

I'd double check that you've removed primer sequences, and also you could (although it kind of gets around the point of dada2) try to agglomerate at a certain similarity level with the tip_glom command in phyloseq to see if maybe a bunch of your SVs are only different by one base or something.

Hope this helps, and maybe @benjjneb has other suggestions.

**Comment by benjjneb** [comment]
@km4htc That sounds extreme. In most cases, these sorts of patterns are caused by technical issues. In particular, are you sure the exact same region was amplified in each sample? Are you sure you removed your primers? Did you use heterogeneity spacers? Was each sample processed in the same sequencing run?

As @benkraj suggested, it is also worth checking the fraction of reads that are in the shared SVs, as that could be high even if there are lots of very low-abundance unshared SVs.

I'm happy to look more closely at your data as well if you are still stuck.

**Comment by LuffyLuffy** [comment]
May be you forgot remove the barcode of your samples.
