### ISSUE TITLE
454 datasets with dada2

### ISSUE THREAD

**Issue by Sofie8** [benjjneb/dada2#278]
Hi, 

I still have few 454 datasets which I would like to to analyse using dada2 in R. But I am getting core dump and segmentation fault when I run dada2 with the function (see also threat https://github.com/benjjneb/dada2/issues/29):

> #Dada inference
> dadaFs <- dada(derepFs, err=errF, HOMOPOLYMER_GAP_PENALTY=-1, BAND_SIZE=32, USE_QUALS=FALSE, multithread=TRUE)
The errorEstimationFunction argument is ignored when USE_QUALS is FALSE.
Sample 1 - 7756 reads in 6337 unique sequences.
 
*** caught segfault ***
address (nil), cause 'memory not mapped'
 
Traceback:
1: .Call("dada2_dada_uniques", PACKAGE = "dada2", seqs, abundances,     err, quals, score, gap, use_kmers, kdist_cutoff, band_size,     omegaA, max_clust, min_fold, min_hamming, use_quals, final_consensus,     vectorized_alignment, homo_gap, multithread, verbose)
2: dada_uniques(names(derep[[i]]$uniques), unname(derep[[i]]$uniques),     err, qi, opts[["SCORE_MATRIX"]], opts[["GAP_PENALTY"]], opts[["USE_KMERS"]],     opts[["KDIST_CUTOFF"]], opts[["BAND_SIZE"]], opts[["OMEGA_A"]],     if (initializeErr) {        1    } else {        opts[["MAX_CLUST"]]    }, opts[["MIN_FOLD"]], opts[["MIN_HAMMING"]], opts[["USE_QUALS"]],     FALSE, opts[["VECTORIZED_ALIGNMENT"]], opts[["HOMOPOLYMER_GAP_PENALTY"]],     multithread, opts[["VERBOSE"]])
3: dada(derepFs, err = errF, HOMOPOLYMER_GAP_PENALTY = -1, BAND_SIZE = 32,     USE_QUALS = FALSE, multithread = TRUE)
An irrecoverable exception occurred. R is aborting now ...
 
I don’t know what to change, do you have any suggestions for me?
@joey711 did you try other criteria than HOMOPOLYMER_GAP_PENALTY=-1, BAND_SIZE=32, USE_QUALS=FALSE, and yes any improved suggestions to try?

output: [testdada2.txt](https://github.com/benjjneb/dada2/files/1123926/testdada2.txt)
error: [error.txt](https://github.com/benjjneb/dada2/files/1123927/error.txt)

**Comment by benjjneb** [comment]
Can you retry with `USE_QUALS=TRUE`?

We now recommend `USE_QUALS=TRUE` for 454 data as well (there is a smaller but non-zero increase in substitution rates with lower quality in 454 data). And this should fix the core dump problem, as the `USE_QUALS=FALSE` code is no longer working on all platforms and is planned for removal in the next release.

**Comment by Sofie8** [comment]
Thank you @benjjneb!

Indeed no error when putting USE_QUALS=TRUE.
I ran now with selfCONSIST=TRUE. I don't see changes in read number after denoising using this option.
I will also try err=errF to see what happens.

> #Track reads through the pipeline
> getN <- function(x) sum(getUniques(x))
> track <- cbind(out, sapply(dadaFs, getN), rowSums(seqtab), rowSums(seqtab.nochim))
> colnames(track) <- c("input", "filtered", "denoised", "tabled", "nonchim")
> rownames(track) <- sample.names
> head(track)
    input filtered denoised tabled nonchim
B01  8391     7756     7756   7756    7731
B02  8595     7965     7965   7965    7923
B03  7880     7291     7291   7291    7269
B11 10664    10025    10025  10025    9706
B12  9411     9021     9021   9021    8434
B13  8147     7747     7747   7747    7644

My output:
[test2dada2.txt](https://github.com/benjjneb/dada2/files/1125288/test2dada2.txt)

**Comment by benjjneb** [comment]
That is normal. Read numbers won't change during denoising (unless you are using non-standard options) as dada2 corrects errors rather than throwing them away.

**Comment by rahulnccs** [comment]
@benjjneb @Sofie8 
I successfully analyzed Ion torrent PGM data but now stuck with data generated by **454 GS FLX Titanium platform **
When I ran filterAndtrim as per recommendation I am getting empty output files (without filtered reads). Details are as follow:
command:
_filterAndTrim(file.path(path,fns), file.path(filtpath,fns), 
              truncLen=240, maxEE=1, truncQ=11, rm.phix=TRUE,
              compress=TRUE, verbose=TRUE, multithread=FALSE,  **maxLen=250**)_

& the error is : The filter removed all reads: path\filtered\SRRxxxxxx_4.fastq not written.
Some input samples had no reads pass the filter.

I also tried, 
filterAndTrim(file.path(path,fns), file.path(filtpath,fns), 
               maxLen=200)
but getting the same error.

I'm attaching figure of sequence quality if you can suggest some parameter changes. Thanks
[qualityplot_prjna203810.pdf](https://github.com/benjjneb/dada2/files/2593114/qualityplot_prjna203810.pdf)
