### ISSUE TITLE
Error in getUniques(x) when running sapply(dadaFs, getN)

### ISSUE THREAD

**Issue by xinbaiusc** [benjjneb/dada2#280]
I am going to Track reads through the pipeline but there is an error running
track <- cbind(out, sapply(dadaFs, getN), sapply(mergers, getN), rowSums(seqtab),rowSums(seqtab.nochim))
Error in getUniques(x) : 
  Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.
I just get dadaFs and mergers as instructed. I do not know why I can not run sapply(dadaFs, getN) and sapply(mergers, getN)

**Comment by benjjneb** [comment]
How many samples are you processing? Just one?

**Comment by xinbaiusc** [comment]
Yes, just one. Does this program do not support the case of one sample?
I will try to process more samples to see if this error occurs again.
Thanks for your help.

**Comment by benjjneb** [comment]
The package commands should all work with one sample, but the `sapply` command that is failing is failing because it is not handling a single sample gracefully. It should work if you have 2+ samples, or you can use a single-sample version of the command:

```
track1 <- cbind(out, getN(dadaFs), getN(mergers), rowSums(seqtab), rowSums(seqtab.nochim))
```

**Comment by benjjneb** [comment]
@bashirshir 

Something along the lines of: `cbind(out, rowSums(seqtab),rowSums(seqtab.nochim))` will work for the Big Data workflow as well. This tracks reads lost from input, filtering, merging, and chimera removal. It won't track reads lost in denoising or table construction, but by default no reads are lost in those steps so it's unnecessary unless you are messing with unusual algorithm options.

**Comment by bashirshir** [comment]
Thank you @benjjneb

**Comment by Aircus** [comment]
Hi!

I got the same error with by dataset and it is not a single sample. 
And I find the error is come from sapply(dadaFs, getN)
Here is how I create dadaFs (ddF, in my case):

mergers <- vector("list", length(sample.names))
names(mergers) <- sample.names
for(sam in sample.names) {
  cat("Processing:", sam, "\n")
    derepF <- derepFastq(filtFs[[sam]])
    ddF <- dada(derepF, err=errF, multithread=TRUE)
    derepR <- derepFastq(filtRs[[sam]])
    ddR <- dada(derepR, err=errR, multithread=TRUE)
    merger <- mergePairs(ddF, derepF, ddR, derepR, verbose=TRUE)
    mergers[[sam]] <- merger
}


could you help me to check my code if you have time?


Thanks a lot!

Best regards!

**Comment by benjjneb** [comment]
@Aircus 

Your loop overwrites `ddF`/`ddR` each time through, there's no list of them all at the end.
I suggest just leave out the `getN(ddF)` part of the tracking matrix. It's not necessary.

**Comment by Aircus** [comment]
I see now.....Thanks a lot!
