### ISSUE TITLE
Retrieving accession number from Sequence Variants

### ISSUE THREAD

**Issue by Ran0109** [benjjneb/dada2#282]
I am developing a specialized pipeline using DADA2 where I apply the algorithm separately on my R1 and R2 reads (which have no overlap). I would like to be able to connect the two reads after SVs are formed, based on accession id of the original FASTAs. For example, I want to assign to each sequence an R1 SV id and R2 SV id.

Is there a way to be able to do this? I can give details of the application if anyone is interested.

**Comment by benjjneb** [comment]
Have you tried `mergePairs(..., justConcatenate=TRUE)`? That will "merge" non-overlapping F/R reads by just concatenating them (with NNNNNNNNNN in the middle by default).

That does assume that the input F/R files were in matched order though, as it matches the reads based on their position in the file, not accession in the fasta/q id-line. If the input files are not in matched order, take a look at the `dada2:::mergePairsByID` function.

**Comment by Ran0109** [comment]
Thanks for the quick response. My goal is not to merge the reads at all, since they are two different reads (16S and ISR). I was wondering if there is a way to be able to map the sequence variants generated independently from processing the forward and reverse reads, based on the original accession ids.

**Comment by benjjneb** [comment]
> map the sequence variants
> based on the original accession ids

Can you clarify what you mean there? The "accession id" is the Illumina ID in the fastq file of the sequencing reads? Or... something else?

**Comment by Ran0109** [comment]
So the accession ID is the unique identifiable tag on each of the fasta sequences inside the FASTQ file. For example it looks something like this: @M01470:107:000000000-AYKU3:1:1101..... 
Can I email you about this?

**Comment by benjjneb** [comment]
Feel free to email me, the solution you want will likely take a little bit of R and the `$map` bits of the `dada-class` and `derep-class` objects. 

The following may do  what you want (this gets the id string associated with each read that was assigned to the first output sequence variant):

```
filt <- "foo.fastq"
drp <- derepFastq(filt)
dd <- dada(drp, err=tperr1) # Should learn error rates from real data
library(ShortRead)
ids <- as.character(id(readFastq(filt)))
svs <- dd$map[drp$map]
ids1 <- ids[svs==1]
```
