### ISSUE TITLE
Error in plotQualityProfile

### ISSUE THREAD

**Issue by yannmean** [benjjneb/dada2#284]
Hi, there. 

Recently I am re-running some codes that I wrote awhile ago. Used the same data, the same directory. When I plotted out the quality profile for the forward readings, everything worked out well, but when plotted the quality profile for reverse reads the following error popped out:

closing unused connection 3 (directory/F1604426_S1_L001_R2_001.fastq)
Error: internal: buf != <newline>

Here are my codes:
Sort forward and reverse reads, make sure they are in the same order, using the same naming convention.

```{r sort forward and reverse reads}
fnFs <- sort(list.files(path, pattern = "_R1_001.fastq"))
fnRs <- sort(list.files(path, pattern = "_R2_001.fastq"))
```

Extract sample names, and specify the full path to the fnFs and fnRs

```{r sample names}
sample.names <- sapply(strsplit(fnFs, "_"), `[`, 1)
fnFs <- file.path(path, fnFs)
fnRs <- file.path(path, fnRs)
```

Plot out quality profiles of forward and reverse reads.

```{r quality}
plotQualityProfile(fnFs[1:2])
plotQualityProfile(fnRs[1:2]) 
```

Operating System is OS X El Capitan 10.11..6
R version is 3.4.1 Single Candle
Dada2 version is 1.4

Thank you very much for your time and attention! 

Yann

**Comment by benjjneb** [comment]
Hi Yann,
Did the command still complete? The message about "closing unused connection 3 (directory/F1604426_S1_L001_R2_001.fastq)" is just a warning that can be ignored if the command completes.

**Comment by yannmean** [comment]
Hi Ben,

Thank you for your kind response. 
The command didn't complete. After the warning, there is an error saying
> "Error: internal: buf != <newline>

Thank you..

**Comment by yannmean** [comment]
Hi, Ben,

Ever since I re-decompressed the data, and redo all the analysis, this issue has never occurred again. 
Can close this thread as well. 

Thank you again for everything. 
Yann
