### ISSUE TITLE
DADA2: Change in convergance/Non-convergance

### ISSUE THREAD

**Issue by eile0001** [benjjneb/dada2#288]
Hi, 
I'm running dada2 (v 1.40) on 11 samples from one MiSeq run, targeting 16S. After quality trimming steps, each sample contains 100 000 unique reads on average. For the reverse reads files (250bp long), dada2 took 8 rounds until convergence, while for the forward reads files (250bp long), dada2 converged after 9 rounds. Now when I'm redoing the DADA2 (starting witht the raw data) I get the same results as before BUT the forward read files automatically terminate after 10 rounds of error estimation.

How is it they converge on the first go and not on the second?
Should I look at increasing covergment rounds? Is it worrying that the number of rounds needed to converge may change?
Many thanks.

**Comment by benjjneb** [comment]
There is nothing magical about the exact number of rounds it takes to reach convergence, so if it shifts a little bit that is not something to worry about.

See the discussion about this on our FAQ: https://benjjneb.github.io/dada2/faq.html#what-if-the-self-consistency-loop-terminated-before-convergence

**Comment by eile0001** [comment]
Ok, thanks!
