### ISSUE TITLE
How does merge paired read works after sample Inference?

### ISSUE THREAD

**Issue by ZeweiSong** [benjjneb/dada2#289]
Hi, 

First I want to thank you for creating this tool!

I am having difficulties in understand how the merging of paired reads works after the sample inference.

Since the partitions are found separately for forward and reverse reads, it is high possible that sequences in forward and reverse being partitioned differently, right?

For example, you can five sequences that partition into two sample sequences in forward reads, but three sample sequences in reverse reads.

So how does your program handle such inconsistence?

Thanks!

Zewei

**Comment by benjjneb** [comment]
`mergePairs` is actually merging on a per-read basis, not on a per-sequence-variant (or partition) basis. This is why you need to give it the `derep-class` object as well as the `dada-class` object, as the `derep-class` object has a `$map` between each read and the inferred sequence-variant.

So in your example, `mergePairs` would recover 5 input sequences, by tracking the connection between the reads in the 2 forward (A/B) and 3 reverse (X/Y/Z) partitions, yielding e.g. AX, AY, BX, BY, BZ output sequences.

**Comment by ZeweiSong** [comment]
So the final sample sequences are determined by mergePairs?

For example if I have forward sequences assigned as: A A B B B, and reverse sequences assigned as X X Y Y Z, what I get in the final sequence table after mergePairs should be: AX BY BZ, three sample sequences.

Am I get this right?

Thanks!

**Comment by benjjneb** [comment]
Yep. With the abundances as well, so in your example you'd get...

AX: 2
BY: 2
BZ: 1
