### ISSUE TITLE
454/Pyrosequencing functionality

### ISSUE THREAD

**Issue by benjjneb** [benjjneb/dada2#29]
Currently 454 data is not properly supported because the homopolymer gapping option is still unimplemented and the singleton p-value is broken.

**Comment by spholmes** [comment]
Not a priority in the current landscape: less than 5% using 454 now???

On Thu, Aug 6, 2015 at 10:25 AM, benjjneb <notifications@github.com> wrote:

> Currently 454 data is not properly supported because the homopolymer
> gapping option is still unimplemented and the singleton p-value is broken.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benjjneb/dada2/issues/29>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by joey711** [comment]
I agree this is not a priority for new datasets, but there are a lot of "old" datasets based on 454. Not a complete waste of time. I'm not holding my breathe for it, but I think we would prob use it if it were there.

**Comment by tardigrade2** [comment]
Hi, is there any progress in the 454 data support? I have "old" 454 datasets that I would like to analyze with dada2.

**Comment by joey711** [comment]
@benjjneb I promise @tardigrade2 is not a bot or pawn working on my behalf O:-) ... That is to say, we also have quite a few old 454 datasets that we'd like to refresh. Happy to discuss offline what might be required to move the needle on this... and for completeness, I agree with @spholmes sentiment. We're not about to go dust off old 454 machines any time soon, but we're also not about to re-do some of these published experiments that used 454.

**Comment by benjjneb** [comment]
https://github.com/tardigrade2 
https://github.com/joey711

We are now officially supporting 454 functionality with the dada2 package, as of version 0.10.7 (c0a9c14e6a00c8274caa5de0b28139803e9c0ff5).

Note that the default dada(...) parameters are chosen for Illumina sequencing, so we recommend using a different set of parameter choices for 454 sequences. In particular, the following parameters should be passed to the dada function:

HOMOPOLYMER_GAP_PENALTY=-1
BAND_SIZE=32
USE_QUALS=FALSE

We also recommend initializing the error model with err=NULL when running in selfConsist mode, as we don't yet have empirical 454 error models to provide.

These parameter changes largely follow the suggestions from the 2011 DADA1 paper. I'll note that while I did test these choices on 454 data, and dada(...) is certainly working for such data, I haven't tested as extensively as I have on Illumina data. If any intrepid soul more carefully tunes those suggested 3 parameters, I'd love to hear about it!

**Comment by joey711** [comment]
Great!

On Friday, March 25, 2016, benjjneb <notifications@github.com> wrote:

> https://github.com/tardigrade2
> https://github.com/joey711
>
> We are now officially supporting 454 functionality with the dada2 package,
> as of version 0.10.7 (c0a9c14
> <https://github.com/benjjneb/dada2/commit/c0a9c14e6a00c8274caa5de0b28139803e9c0ff5>
> ).
>
> Note that the default dada(...) parameters are chosen for Illumina
> sequencing, so we recommend using a different set of parameter choices for
> 454 sequences. In particular, the following parameters should be passed to
> the dada function:
>
> HOMOPOLYMER_GAP_PENALTY=-1
> BAND_SIZE=32
> USE_QUALS=FALSE
>
> We also recommend initializing the error model with err=NULL when running
> in selfConsist mode, as we don't yet have empirical 454 error models to
> provide.
>
> These parameter changes largely follow the suggestions from the 2011 DADA1
> paper. I'll note that while I did test these choices on 454 data, and
> dada(...) is certainly working for such data, I haven't tested as
> extensively as I have on Illumina data. If any intrepid soul more carefully
> tunes those suggested 3 parameters, I'd love to hear about it!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/benjjneb/dada2/issues/29#issuecomment-201441455>
>


-- 
---
---
"Joey"
Paul J. McMurdie II
Sent from Gmail

**Comment by tardigrade2** [comment]
Thank you for implementing the 454 support! I'm looking forward to try it out. I have a question concerning the version numbers: Do I have to get this particular version (0.10.7) for 454 analysis or are the changes also already in the current default version (1.0.3)? (I have some trouble installing version 0.10.7)
Thank you for your help

**Comment by benjjneb** [comment]
The 454 features are in the release version (1.0.3).

The 1.0 release includes everything from the 0.x.y devel versions.

**Comment by tardigrade2** [comment]
Great, thank you!
