### ISSUE TITLE
Can I leave the sequences in different length?

### ISSUE THREAD

**Issue by ZeweiSong** [benjjneb/dada2#291]
Sorry for bugging with questions!

I'm testing using ITS data, and learnError noticed me that:

    Not all sequences were the same length.

Am I violate any assumption for not truncate the sequences? The Error plot I got looks normal though.

Zewei

**Comment by benjjneb** [comment]
Yep, we support variable lengths since version 1.4, but didn't update all the warnings yet. You can safely ignore that message as long as it was expected.
