### ISSUE TITLE
assignTaxonomy with concatenated reads

### ISSUE THREAD

**Issue by rmm257** [benjjneb/dada2#292]
Hi Ben and thank you very much for the interactive help forum.  I had a technical question about using concatenated reads in the assignTaxonomy portion of dada2.  In order for assignTaxonomy to accept concatenated reads, I have to remove the 10 Ns so that the sequence is only ACTG in order to get past the internal check step in assignTaxonomy.  However, I'm wondering what impact this has on the calculation of taxonomies.  Essentially, am I introducing a series of kmers across the concatenated region that's now artificial sequence (because the two ends didn't meet, therefore, when I remove the Ns, I get something that looks continuous but really wasn't)?  Or does assignTaxonomy somehow have the information that there's a break in the sequence there and picks up the kmers after the discontinuity?

For example:
5' ACGTACGTACNNNNNNNNNN**AAATTTCCCGGG** 3'  becomes
5' ACGTACGTAC**AAATTTCCCGGG** 3'  when I remove the Ns.

If I were breaking it into kmers for the classifier, is it seeing:
Option 1:
[ACGTACGT CGTACGTA GTACGTAC TACGTAC**A** ACGTAC**AA**  ..... etc]

or Option 2: 
[ACGTACGT CGTACGTA GTACGTAC **AAATTTCC** **AATTTCCC** ...etc]

and given that the 'artificial' kmers in Option 1 are not going to match sequence, how much do they influence the Taxonomic assessment if that's what dada2 is actually using?

Thanks,
Rebecca

**Comment by benjjneb** [comment]
What version of the package are you using (`packageVersion("dada2")`)? `assignTaxonomy` should accept Ns in the input sequences, in which case it ignores the kmers which contain an N.

That is the right way to use it for exactly the reason you point out, because you don't want to add "artificial" kmers which span the non-overlapping reads.

**Comment by rmm257** [comment]
I'm using 1.4.0.  The place where I have to remove the Ns is actually to
get past the removal of chimeras: 'removeBimeraDenovo' calls
'isBimeraDenovoTable'

Which gives an error in:

 if (!(is.matrix(seqtab) && is.integer(seqtab) && !is.null(sqs) &&
        all(sapply(sqs, C_isACGT)))) {
        stop("Input must be a valid sequence table.")
    }

If I hand check the data lines, the "C_isACGT" appears to be why I end up
with the "input must be a valid sequence table" error.



On Mon, Jul 24, 2017 at 2:46 PM, Benjamin Callahan <notifications@github.com

**Comment by benjjneb** [comment]
Hm, well, thats a bug that needs to be fixed.

What I'd recommend for now is the following work-around: Remove the Ns to run chimera removal, and then add them back in before `assignTaxonomy`. This should be easy to do if your reads are all the same length:

```{r}
# st.nochim is your sequence table after Ns were removed and chimeras removed
st <- st.nochim
sqs <- colnames(st)
NF <- 150 # Replace 150 with the length of your forward sequences after trimming/truncation
colnames(st) <- paste0(substr(sqs, 1, NF), "NNNNNNNNNN", substr(sqs, NF+1, nchar(sqs)))
tax <- assignTaxonomy(st, "path/to/trainingfasta.fa.gz", multithread=TRUE)
```

Let me know if that works or not!

**Comment by rmm257** [comment]
My sequences are not the same length because I needed to do some upfront
quality trimming in prinseq (long story), but I can add a string of "CCCC"
or something easily identifiable and then flip that back to Ns as long as
it doesn't trip the chimera removal.

Will I have better luck skirting the chimera detection if I input di/tri
nucleotide repeats instead of a string of a single character?



On Mon, Jul 24, 2017 at 3:17 PM, Benjamin Callahan <notifications@github.com

**Comment by benjjneb** [comment]
Yes your workaround should be OK, i.e. switching the 10Ns to like 20Cs for chimera removal, and then switch them back later. The chimera removal is relying on exact matching between the "parent" and "child" DNA subsegments, and there won't be any real DNA w/ 20Cs in a row, so all should be well.

**Comment by rmm257** [comment]
Thanks! I'll give it a try.

On Mon, Jul 24, 2017 at 3:42 PM, Benjamin Callahan <notifications@github.com

**Comment by benjjneb** [comment]
Removed the ACGT check from `isBimeraDenovoTable` in 5831a5d1a1c60309b8186f5775897584e5147433

Should now handle sequences with Ns from concatenation.

**Comment by rmm257** [comment]
Success, thanks!
