### ISSUE TITLE
sequence table dimensions unintuitive

### ISSUE THREAD

**Issue by slschnorr** [benjjneb/dada2#295]
I'm trying dada2 with my own data after following the tutorial, but in both the tutorial and my data, the resulting seqtab from makeSequenceTable has column dimensions that far exceed the number of "sample sequences inferred from input unique sequences". Can someone explain this to me and what I'm missing about the table format? If I want to work with this table without taxonomy assignment, can I directly transfer the table object to a text file for downstream analysis? Example?

Tutorial: 
dadaFs[[1]] ## 128 sample sequences were inferred from 1979 input unique sequences.
dim(seqtab) ## [1]  20 288

My data:
dadaA[[1]] ## 374 sample sequences were inferred from 15308 input unique sequences.
dim(seqtab) ## [1] 12 1328

**Comment by benjjneb** [comment]
The sequence table has a row for each sample, and a column for each unique sequence variant across **all** of the samples it contains. Thus it will always have more columns than the number of sequence variants in a single sample (which is what you are looking at with e.g. `dadaA[[1]]`, the first sample).

And yes, you can use the sequence table as input to `assignTaxonomy` and `removeBimeraDenovo` etc.

**Comment by slschnorr** [comment]
Thanks for the prompt reply. I had forgotten that I was working from individual sample files instead of a combined dataset, makes sense now!
