### ISSUE TITLE
LearnError using different number of samples

### ISSUE THREAD

**Issue by mentorwan** [benjjneb/dada2#297]
Hi,

  I am using 1.4.0 DADA2. I tried to use LearnError functions on some of samples. Here is the commands:

    errF <- learnErrors(filtFs[81:130], multithread=TRUE)
    errR <- learnErrors(filtRs[81:130], multithread=TRUE)

My understanding is that it will use 50 samples to estimate error. But my log message told me it only uses first 16 samples such as:

    Initializing error rates to maximum possible estimate.
Sample 1 - 67762 reads in 13268 unique sequences.
.....
Sample 16 - 65909 reads in 13618 unique sequences.
   selfConsist step 2 
   ....

Do you know why the number difference? 16 vs 50. Thanks.

**Comment by benjjneb** [comment]
'learnErrors' uses (at least) a number of reads defined by the `nreads` parameter, which by default is 1M. In this case, there were 1M total reads in the first 16 samples you passed it, so it didn't use any further samples.

If you want to use all 50, just set `nreads=Inf` and `learnErrors` will use all the input samples.

**Comment by mentorwan** [comment]
Thanks for so quick answer. Related questions: How do I know error estimation from independent samples are very similiar so that I don't need to adjust independent samples or number of samples?

Thank you very much.

**Comment by benjjneb** [comment]
Not sure I follow your question, but if it helps you can either use `plotErrors` to visualize the estimated error rates, or look at the matrix directly in the `$err_out` of the return from `learnErrors`

**Comment by mentorwan** [comment]
Let me clarify what I said.

For my case, $error_out is 16*41 based on sample 81 to 96. Excuse for my knowledge, I don't understand where 41 comes from.
If I use sample 101 to 150.  Suppose it will generate another matrix of 16*41. Should I check distance between those two matrix? If the distance for those two matrix is very small, then I can say error matrix is converged? Just want to know more about this process. Thanks!

**Comment by benjjneb** [comment]
The 16x41 matrix is the learned error rates for the 16 transitions (eg. A->A, A->C,...) and 41 quality scores (0...40). You can `plotErrors` it to see what it looks like.

Yes you can compare the differences between two matrices (e.g. from one set of samples versus another) to see if there is any meaningful difference in inferred error rates.

**Comment by mentorwan** [comment]
Thanks for replying so quickly. You can close the ticket.
