### ISSUE TITLE
taxa table at genus level has missing value 

### ISSUE THREAD

**Issue by yannmean** [benjjneb/dada2#298]
Hi, there, 

I noticed that there is one missing value in my taxa table, one sequence was categorized as Lachnospiraceae at the family level, but the genus level is N/A, since this sequence has relatively high abundance, so I want to find out what genus it actually belongs to. Is there a way to do it? 

Thank you very much!  

Yann

**Comment by benjjneb** [comment]
An `NA` entry indicates that the sequence couldn't be classified to a specific genus at that level with sufficient bootstrap confidence (you can read more about this in the paper that introduced the method we are implementing: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1950982/

If you are particularly interested in this sequence variant, you can try to perform a classification by hand, which can be more accurate than any automated general-purpose method. I sometimes do this by BLAST-ing sequences against nt via [NCBI's web interface](https://blast.ncbi.nlm.nih.gov/Blast.cgi?PROGRAM=blastn&PAGE_TYPE=BlastSearch&LINK_LOC=blasthome) (usually excluding uncultured).

**Comment by yannmean** [comment]
Hi, Ben, 
Thank you very much for your kind response. 
I just BLAST-ed the sequences and replaced NA in the taxa table. 

Thank you again for your help. 
Best,
Yann
