### ISSUE TITLE
retraining classifier

### ISSUE THREAD

**Issue by rmm257** [benjjneb/dada2#299]
Hi Ben,

This may be a somewhat naive question, but I am running the bioconductor pathway in parallel to the QIIME2 pathway to get a sense of where the programs differ.  Am I correct in seeing that there's no way to train a classifier in dada2? I can download a pretrained one, but can I train my own? What did you use to train the available ones?

Best wishes,
Rebecca

**Comment by benjjneb** [comment]
Everytime you call `assignTaxonomy` the classifier is "retrained" based on the reference fasta file you give it. So you just need to choose the reference database you want to use (and have it in the dada2-compatible format) and then you are good to go.

**Comment by rmm257** [comment]
Ah, gotcha, so  I just need to trim to the region of 16S that works with my
sequences for each database I want to test.

**Comment by benjjneb** [comment]
Yep. 

I usually don't even bother doing the trimming, as assignment works pretty well with full-length 16S sequences, but trimming does make things a bit more precise so its not a bad idea.

**Comment by rmm257** [comment]
I've been using them without trimming, but since the qiime2 pathway has a
trimming option built in,  to compare the two, I am thinking the
most-robust-to-criticism route is to trim both...

Thanks again!

**Comment by benjjneb** [comment]
> I've been using them without trimming, but since the qiime2 pathway has a
trimming option built in,  to compare the two, I am thinking the
most-robust-to-criticism route is to trim both...

Makes sense!
