### ISSUE TITLE
loading DADA2

### ISSUE THREAD

**Issue by spholmes** [benjjneb/dada2#30]
Error in unloadNamespace(package) : 
  namespace ‘S4Vectors’ is imported by ‘GenomeInfoDb’, ‘Biostrings’, ‘AnnotationDbi’, ‘IRanges’, ‘DESeq2’, ‘XVector’, ‘GenomicRanges’ so cannot be unloaded

**Comment by benjjneb** [comment]
How did this error come up? Loading dada2?

**Comment by spholmes** [comment]
Sorry, yes, it was at my first load ofthe package.

**Comment by benjjneb** [comment]
Joey, any wisdom to share on this issue?

**Comment by spholmes** [comment]
Here are a few more details, also require(dada2) loaded the package and load(dada2) doesn't.

* DONE (dada2)
> load(dada2)
Error in load(dada2) : object 'dada2' not found
> load("dada2")
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'dada2', probable reason 'No such file or directory'
> require("dada2")
Loading required package: dada2
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following object is masked from ‘package:stats’:

    xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, as.vector, cbind,
    colnames, do.call, duplicated, eval, evalq, Filter, Find,
    get, intersect, is.unsorted, lapply, Map, mapply, match,
    mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rep.int, rownames, sapply,
    setdiff, sort, table, tapply, union, unique, unlist,
    unsplit

Loading required package: Biostrings
Loading required package: S4Vectors
Loading required package: stats4
Loading required package: IRanges

Attaching package: ‘IRanges’

The following object is masked from ‘package:phyloseq’:

    distance

Loading required package: XVector
Loading required package: Rcpp
Warning messages:
1: package ‘Biostrings’ was built under R version 3.2.1 
2: package ‘S4Vectors’ was built under R version 3.2.1 
3: package ‘IRanges’ was built under R version 3.2.1 
4: replacing previous import by ‘data.table::tables’ when loading ‘dada2’

**Comment by benjjneb** [comment]
Load won't work, but library(dada2) and require(dada2) should work.

So it did successfully load after the above output (albeit with the listed
complaints?) Or it failed to load?

**Comment by spholmes** [comment]
It loaded...

On Thu, Aug 6, 2015 at 11:34 AM, benjjneb <notifications@github.com> wrote:

> Load won't work, but library(dada2) and require(dada2) should work.
>
> So it did successfully load after the above output (albeit with the listed
> complaints?) Or it failed to load?
>
> On Thu, Aug 6, 2015 at 11:27 AM, spholmes <notifications@github.com>
> wrote:
>
> > Here are a few more details, also require(dada2) loaded the package and
> > load(dada2) doesn't.
> >
> > - DONE (dada2) > load(dada2) Error in load(dada2) : object 'dada2' not
> > found > load("dada2") Error in readChar(con, 5L, useBytes = TRUE) :
> cannot
> > open the connection In addition: Warning message: In readChar(con, 5L,
> > useBytes = TRUE) : cannot open compressed file 'dada2', probable reason
> 'No
> > such file or directory' > require("dada2") Loading required package:
> dada2
> > Loading required package: BiocGenerics Loading required package: parallel
> >
> > Attaching package: ‘BiocGenerics’
> >
> > The following objects are masked from ‘package:parallel’:
> >
> > clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
> > clusterExport, clusterMap, parApply, parCapply, parLapply,
> > parLapplyLB, parRapply, parSapply, parSapplyLB
> >
> > The following object is masked from ‘package:stats’:
> >
> > xtabs
> >
> > The following objects are masked from ‘package:base’:
> >
> > anyDuplicated, append, as.data.frame, as.vector, cbind,
> > colnames, do.call, duplicated, eval, evalq, Filter, Find,
> > get, intersect, is.unsorted, lapply, Map, mapply, match,
> > mget, order, paste, pmax, pmax.int, pmin, pmin.int,
> > Position, rank, rbind, Reduce, rep.int, rownames, sapply,
> > setdiff, sort, table, tapply, union, unique, unlist,
> > unsplit
> >
> > Loading required package: Biostrings
> > Loading required package: S4Vectors
> > Loading required package: stats4
> > Loading required package: IRanges
> >
> > Attaching package: ‘IRanges’
> >
> > The following object is masked from ‘package:phyloseq’:
> >
> > distance
> >
> > Loading required package: XVector
> > Loading required package: Rcpp
> > Warning messages:
> > 1: package ‘Biostrings’ was built under R version 3.2.1
> > 2: package ‘S4Vectors’ was built under R version 3.2.1
> > 3: package ‘IRanges’ was built under R version 3.2.1
> > 4: replacing previous import by ‘data.table::tables’ when loading ‘dada2’
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/benjjneb/dada2/issues/30#issuecomment-128410481>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benjjneb/dada2/issues/30#issuecomment-128411905>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by joey711** [comment]
I will update my version and run a package check. Is it safe to say we're in the "prepare for BioC" mode?
