### ISSUE TITLE
Memory error during dereplication step

### ISSUE THREAD

**Issue by shashank-KU** [benjjneb/dada2#308]
I am working on approximately 7200 samples (Illumina paired end) (~424943746 Reads), to investigate the microbial community among them using the dada2 pipeline. While running the dada2 pipeline on R, it crashes during the step of dereplication with a memory error.

I am working on Windows host with 8 cores and 32 GB Ram. I understand memory is an issue while working on R but any advice on how to fix this would be greatly appreciated.

I am using dada2 v1.4.0

**Comment by benjjneb** [comment]
Could you give us some more information, in particular what workflow are you running? The tutorial workflow won't work on such a large dataset as it tries to load everything into memory at once, but the Big Data workflow should work: http://benjjneb.github.io/dada2/bigdata.html

For such a large number of samples I would recommend saving intermediate objects along the way, for example the `dada-class` or `merger` objects for each sample (single-read or paired-read respectively), so as to keep your progress if the job gets interrupted somehow.

**Comment by shashank-KU** [comment]
Thanks for the information. Now it's working and I guess it will take a couple of more days to complete the entire steps. 
I will let you know if I encounter any error.

**Comment by benjjneb** [comment]
Great! Please re-open if new issues arise.
