### ISSUE TITLE
R aborted when running "learnErrors"

### ISSUE THREAD

**Issue by moltzau** [benjjneb/dada2#309]
Hello, 

I am following the tutorial for DADA2 BIG DATA paired-end (1.4) using my own data. 
Everything works fine up through filtering. However, when I run the command to learn the error rates:
errF <- learnErrors(filtFs, nread=2e6, multithread=TRUE)
This cause the following error:
R session aborted. R encountered a fatal error. The session was terminated. 

Any help is highly appreciated!

**Comment by benjjneb** [comment]
That's the extent of the output when it quits?

Hm... that's not a dada2 specific error. Could you give us more information on your setup, including the output of `R.version`, `packageVersion("dada2")`, `packageVersion("Rcpp")`, packageVersion("ShortRead")` and also the type of machine you are running on including available memory?

**Comment by moltzau** [comment]
Yes, that's all I get before it force closes and restarts. 
I have 40 samples (80 fastq.gz files). Reads.out post filtering indicated that 1 FWD fastq.gz had 2918348.
I am using:
ubuntu 16.10
memory 7,5 GiB
processor Intel Core i5-5200U CPU 2.20GHz x 4
graphics Intel HD Graphics 5500 (Broadwell GT2)
OS type 64-bit
Disk 475,3 GB

> R.version
               _                          
platform       x86_64-pc-linux-gnu        
arch           x86_64                     
os             linux-gnu                  
system         x86_64, linux-gnu          
status                                    
major          3                          
minor          4.1                        
year           2017                       
month          06                         
day            30                         
svn rev        72865                      
language       R                          
version.string R version 3.4.1 (2017-06-30)
nickname       Single Candle              
> packageVersion("dada2")
[1] ‘1.5.2’
> packageVersion("Rcpp")
[1] ‘0.12.12’
> packageVersion("ShortRead")
[1] ‘1.34.0’

**Comment by benjjneb** [comment]
That all looks fine. Could you post the output of `print(out)` (assuming `out <- filterAndTrim(...)`).

Could you also try the following:
```
errF.test <- learnErrors(filtFs, nread=1000, multithread=FALSE)
```

**Comment by moltzau** [comment]
I tried running errF.test, but again my PC froze and the program crashed. I cannot print(out) results from filterAndTrim without apparently running it again and copying over the filt.fastq.gz files.

**Comment by benjjneb** [comment]
Could you see if the filtered files can be read in at all?

```
drp.test <- derepFastq(filtFs[1:5], verbose=TRUE)
```

**Comment by moltzau** [comment]
> drp.test <- derepFastq(filtFs[1:5], verbose=TRUE)
Dereplicating sequence entries in Fastq file: ~/Desktop/NOD2//filtered/F00492-L3_F_filt.fastq.gz
..Encountered 2275080 unique sequences from 2497355 total sequences read. 
Dereplicating sequence entries in Fastq file: ~/Desktop/NOD2//filtered/F00493-L3_F_filt.fastq.gz
..Encountered 2520724 unique sequences from 2654403 total sequences read. 
Dereplicating sequence entries in Fastq file: ~/Desktop/NOD2//filtered/F00494-L3_F_filt.fastq.gz
..Encountered 2539314 unique sequences from 2842927 total sequences read. 
Dereplicating sequence entries in Fastq file: ~/Desktop/NOD2//filtered/F00495-L3_F_filt.fastq.gz
..Encountered 2279333 unique sequences from 2399448 total sequences read. 
Dereplicating sequence entries in Fastq file: ~/Desktop/NOD2//filtered/F00496-L3_F_filt.fastq.gz
Error in add(bin) :
      'Calloc' could not allocate memory (100000074 of 1 bytes)
>



After this my PC froze again.

**Comment by benjjneb** [comment]
I see two issues here. The first is the one preventing you from moving forward: You are running out of memory.

The second is leading to the first: Almost all of the post-filtered reads in your data are unique >90%. This is not expected in amplicon data in almost any normal circumstance. Could you clarify what amplicon/environment you are sequencing? I suspect something artefactual is going on.

What is your sequencing chemistry and quality profile? Could you share the output of `plotQualityProfile(fnFs[1:2])` and the filtering parameters you used?

**Comment by moltzau** [comment]
library prep was performed using NexteraXT. 16S V3-V4 region was sequenced on Illumina HiSeq2500 with a coverage of 2x150bp.  

I used cutadapt to first remove adapters. T

hen in dada2:
# Filter
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, trimLeft=13, truncLen=c(124,124),
                     maxN=0, maxEE=c(2,2), truncQ=11, rm.phix=TRUE,
                     compress=TRUE, verbose=TRUE, multithread=TRUE) 

![rplotf](https://user-images.githubusercontent.com/30862035/29186566-2f20f4ec-7e0d-11e7-9de5-7b2dc38a8611.png)
![rplotr](https://user-images.githubusercontent.com/30862035/29186567-2f280f7a-7e0d-11e7-889d-85fd87af61f1.png)

**Comment by benjjneb** [comment]
That all looks very normal...

I don't know. Is it possible to share a portion of one of the samples, e.g. the output of `head -n 40000 sample1_FWD.fastq > share.fastq` (in the shell)? I'd be interested to take a look, because I don't understand why nearly all your reads would be unique given what you've shown here.

The only other advice I have right now is to move to a machine with more memory (32+ GB) that can handle the size of this data (memory reqs scale w/ the number of unique sequences).

**Comment by moltzau** [comment]
I have sent it to your email.

**Comment by benjjneb** [comment]
So when I BLAST the first 25 sequences against nt, 20 of them have no hit at all. They appear to be just random DNA.

I'm not sure how that came to be, but it would certainly explain the super-high rate of unique sequences in your data.

**Comment by moltzau** [comment]
ok. that's helpful. I will revise everything from the beginning and try again. Thanks again for all your help!
