### ISSUE TITLE
Real data?

### ISSUE THREAD

**Issue by spholmes** [benjjneb/dada2#31]
I don't seem to find real data examples , and the data should also be explicitly named, not just example1, example2...
I was able to load "test-nonunique.fastq.gz", but there needs to be the data that appear in the paper
in the package...

**Comment by joey711** [comment]
I like this. We will probably need to host the original data (fastq.gz) somewhere separately, as it will be much larger than the typical package size limit of 2 MB.

There are a couple of options here. Public databases like SRA, or simply host it at Stanford or Amazon, etc. Once you've decided on hosting, we can setup a reproducible example workflow that points to it.

**Comment by benjjneb** [comment]
Yes, it would be nice to host the three test datasets, but they are all way
too big to have in the package itself.
I am also removing the files currently in inst/extdata, they are not very
helpful for current use.

It might be worth adding a small fastq (100kb) within the package as well
though.

**Comment by joey711** [comment]
I agree about in-package inclusion. Downsample from an existing dataset?

**Comment by benjjneb** [comment]
Added downsampled versions of Extreme as sam1F.fastq.gz, sam1R.fastq.gz and sam2F.fastq.gz. They each contain 1000 reads.
