### ISSUE TITLE
plotErrors expected error rates red line (nominalQ)

### ISSUE THREAD

**Issue by igor25** [benjjneb/dada2#310]
Hi Benjamin,

I am going over the dada2 pipeline (I think your error model is really cool) tutorial and examples, before I apply it to my own data and have several questions that I'll split into different threads.

DADA2 Nat Meth paper SI, Fig. 8 shows an output of plotErrors. In the caption it says the red line should reflect Q = -10 log_10 (p_err), or inverting the equation log_10 (p_err) = - Q / 10. Then, for example, if log_10 (p_err) = -2  =>  Q = 20. But the line does not cross that point – for Q = 20, the y value is -2.5 instead of 2? So the equation used is not this...

Thank you!

Igor

**Comment by benjjneb** [comment]
Hi Igor,
The Q score is supposed to reflect the likelihood of the base being misread as another, but that misread base can be 1 of 3 possibilities, hence there is a factor of 3 difference between the nominal def of the Q score, and the naive probability of a specific (eg. A->C) error, hence 10^-2.5 ~= 1/3 * 10^-2 at Q=20.

**Comment by igor25** [comment]
You're right, got it. The plots show specific errors e.g. p(A->C) and not p(A->notA).
