### ISSUE TITLE
fastqFilter vs fastqPairedFilter vs filterAndTrim

### ISSUE THREAD

**Issue by igor25** [benjjneb/dada2#311]
Concerning filtering and trimming sequences, I see that there are (at least) 3 functions that are used for this, `fastqFilter`, `fastqPairedFilter` and `filterAndTrim`. The documentation states that `fastqPairedFitler` applies filters in both directions (while `fastqFilter` in just one?) and the results can change dramatically. For example, in the [R code](https://stacks.stanford.edu/file/druid:mh194vj6733/Extreme_Final.html) where you analyzed the Extreme data set, this code:

```
fastqFilter(fnF, filtFO, maxN=0, maxEE=2, truncQ=2, truncLen=240, trimLeft=20, compress=T, verbose=T)
Read in 2040485, output 1431321 (70.1%) filtered sequences.
derepFO = derepFastq(filtFO, verbose=T)
dadaFO = dada(derepFO, err=inflateErr(tperr1, 3), selfConsist=T, OMEGA_A=1e-40, multithread=T)
dadaFO
dada-class: object describing DADA2 denoising results
77 sample sequences were inferred from 184343 input unique sequences.
Key parameters: OMEGA_A = 1e-40, BAND_SIZE = 16, USE_QUALS = TRUE
```

results in 77 sample sequences. Alternatively, while, using `fastqPairedFilter`:
```
fastqPairedFilter(c(fnF, fnR), c(filtF, filtR), maxN=0, maxEE=2,
                  truncQ=2, truncLen=c(240, 200), trimLeft=c(20, 20),
                  compress=T, verbose=T, rm.phix=c(T, T))
Read in 2040485 paired-sequences, output 1178835 (57.8%) filtered paired-sequences.
derepF  = derepFastq(filtF, verbose=T)
dadaF  = dada(derepF,  err=inflateErr(tperr1, 3), selfConsist=T, OMEGA_A=1e-40, multithread=T)
dadaF
dada-class: object describing DADA2 denoising results
38 sample sequences were inferred from 118208 input unique sequences.
Key parameters: OMEGA_A = 1e-40, BAND_SIZE = 16, USE_QUALS = TRUE
```
results in 38 sample sequences, so about half less. The third function `filterAndTrim` seems like its a wrapper for `fastqFilter` (or the other way around).

The code filters out any reads containing Ns, any reads with less than 2 expected errors, any reads that have one or more quality scores <= 2, truncates the lengths to 240 and 200 nts, trims 20 nts from the left and removes phiX sequences. 

- So which part exactly is applied to both directions? Does that for `fastqPairedFilter` mean that both forward and reverse reads are discarded even if e.g. only one of them has N or maxEE > 2, etc.?

Thank you!

**Comment by benjjneb** [comment]
> So which part exactly is applied to both directions? Does that for fastqPairedFilter mean that both forward and reverse reads are discarded even if e.g. only one of them has N or maxEE > 2, etc.?

Correct, each read is tested independently, and if either fails the whole pair is thrown out. Note that you can provide different parameters to the F/R reads, e.g. `trucnLen=c(200, 150)` truncates the F reads at 200 and the R reads at 150.

`filterAndTrim` is indeed just a more convenient wrapper for `fastqFilter` and `fastqPairedFilter`: It is "R-vectorized" and also handles multithreading for you if you want it to.

**Comment by benjjneb** [comment]
Also, the lower number of sequence variants inferred from the merged Extreme reads, vs. the F reads alone, is a somewhat separate issue from the filtering. See the text below that was from our response to a reviewer asking about this during the publication process:

> Finally, the reviewer points out the reduction of Exact low frequency variants in the merged reads relative to the forward-only reads, and reasonably concludes that this might indicate that those low-frequency forward-only Exact sequences were errors. However, this is not the case, this phenomenon was caused by the combination of the lower quality of reverse reads and the dependence of DADA2 (and UPARSE, and to some extent other methods) on repeated observations of the same sequence in order to infer its presence.
> 
> In the Extreme dataset, there are ~810k error-free reads in the forward-only dataset. In the paired dataset there are ~720k error-free forward reads (filtering on both forward and reverse means less sequences) and ~480k error-free reverse reads (lower quality). For DADA2 to identify rare sequences from overlapping paired-end data, it must identify those sequences in both the forward and reverse reads, and therefore requires repeated observation of the error-free forward and reverse sequence to do so. Thus, a number of rare true-positive contaminants were lost when merging because they were not identified in both forward and reverse (the median output sequence lost in the merged Extreme output had just 3 error-free reads in the forward-only dataset!).
> 
> We have expanded the discussion about how DADA2’s reliance on repeated observations constrains its sensitivity to rare variants in Supplementary Note 1.

**Comment by igor25** [comment]
Wow, thank you so much for posting the reply to a referee and pointing out the SI Note 1 (I missed it). I found that the filtering can make a big difference, so I am exploring couple of different things on my own. I thought it was interesting that with this "paired-filter" from DADA2 for the Extreme data set, even other pipelines you tested in the DADA2 paper (UPARSE, MED, Mothur, QIIME) produce low number of sequences (or OTUs)! 

If I run QIIME with default settings and its own filter, which I am guessing is what a lot (most?) people do, then instead of the 36 total OTUs for the merged extreme data, I get over 500.
