### ISSUE TITLE
filtering with MiniSeq data

### ISSUE THREAD

**Issue by fanli-gcb** [benjjneb/dada2#312]
I've been playing around with some amplicon data that came off a MiniSeq instrument, which apparently reports 8-level binned Q scores. Trying to understand whether we need to treat the filtering/trimming parameters differently.

Here is a sample run:
[DADA2.qualityProfiles.pdf](https://github.com/benjjneb/dada2/files/1219109/DADA2.qualityProfiles.pdf)

Note the very discretized nature of the quality scores. They seem to correspond to the 8 bins in this Illumina white paper:
https://www.illumina.com/content/dam/illumina-marketing/documents/products/technotes/technote_understanding_quality_scores.pdf

Based on the above quality profile, I chose to not trim the forward read, and trim the reverse read to 145 bases, with a maximum of one expected error:
`filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(150,145), maxN=0, maxEE=c(1,1), truncQ=2, rm.phix=TRUE,compress=TRUE, matchIDs=TRUE, verbose=TRUE, multithread=ncores.filter)`

Here is the quality profile afterwards (using FastQC):
Forward:
![miniseq_filtered_f](https://user-images.githubusercontent.com/4511762/29232461-8b045dce-7ea0-11e7-9b4a-538dadc3b8b6.png)
Reverse:
![miniseq_filtered_r](https://user-images.githubusercontent.com/4511762/29232460-8b01d91e-7ea0-11e7-8d80-304522671b36.png)

To me, this seems like there are still significant quality issues towards the 3' end of both reads. I also observe a very low rate of dereplication in these samples:
```
Sample 1 - 158666 reads in 30718 unique sequences.
Sample 2 - 481091 reads in 74111 unique sequences.
Sample 3 - 1430190 reads in 1036169 unique sequences.

```
which makes the subsequent error modeling quite slow. I can think of two options:
1) Proceed with current data, lower the `nreads` parameter in `learnErrors` to decrease run time. However, this may lead to ineffective denoising I would imagine.

2) Use `truncQ` aggressively, perhaps at 28 or something and live with the loss of data. Any read pair that gets truncated will likely no longer overlap, so will be discarded at the `mergePairs` step.

This is my first experience with MiniSeq data, so any guidance or suggestions would be much appreciated. Thanks!

**Comment by benjjneb** [comment]
Unfortunately I cannot give you much guidance as I have no experience with Miniseq data, but am very much interested in developing useful guidance for people using that platform. You're reactions to what you are seeing seem reasonable to me, but I can't say much more than that.

What you've posted here is really useful though and we would love to hear more about what you encounter! The 8-bin Q scores is a definite change. In principle the dada2 error model should handle it, but in practice tweaks to error estimation or the like might improve performance.

**Comment by fanli-gcb** [comment]
> The 8-bin Q scores is a definite change. In principle the dada2 error model should handle it, but in practice tweaks to the error estimation method might improve performance.

Agree in principle, but I guess theoretically you could have over/under-estimation of errors. For example, scores 25-29 are binned to 27. So bases that had a "raw" score of 25 might contain slightly more errors than those with a raw score of 29. But my completely uneducated guess is that this is probably a case of splitting hairs.

As an update, I tried option 1. No go, as the same run time issue pops up again during the inference step (`dada`). 

Option 2 seems to be better, as a lot more sequences were then filtered out and I was able to get to a sequence table. I'd still like to go back and understand better why sequences were filtered out, as this shouldn't really happen with `truncQ` with the default `minLen=20`, unless there were bases near the 5' end that had low Q scores?
