### ISSUE TITLE
assignSpecies with reverse complement data

### ISSUE THREAD

**Issue by ohnoplus** [benjjneb/dada2#313]
I have data that, when I use the assignTaxonomy function, need tho have tryRC=TRUE set, otherwise nothing seems to assign. I see that the assignSpecies function does not have a tryRC flag associated with it. Is there an easy (or hard) way to tell addSpecies to look at reverse complements of my data?

**Comment by benjjneb** [comment]
We don't have the `tryRC` flag added to `assignSpecies` yet (but we should!).

For now you can just reverse-complement your sequences by hand:
```
sqs.rc <- dada2:::rc(getSequences(myseqtab))
spec <- assignSpecies(sqs.rc, "path/to/species_assignment.fa.gz")
```

**Comment by benjjneb** [comment]
`tryRC` flag added to `assignSpecies` in 3271207eb8f0a5987cc5edea8cc966ab5e17a158
