### ISSUE TITLE
Can I leave off truncLen when just using FWD reads?

### ISSUE THREAD

**Issue by gzahn** [benjjneb/dada2#314]
Looking at ITS amplicons (with decent length variation) between 12 different Illumina runs. Most of these runs are paired-end, but some are only forward reads. I'd like to use the "Big data" workflow, or at least just use the forward reads from all of these, but noticed this suggestion in the tutorial: "Single-reads must also be truncated to the same length (this is not necessary for overlapping paired-reads, as truncLen doesn’t affect the region covered by the merged reads)." 
Since we will be learning the error profiles for each run separately, and these are ITS, is it possible to leave off the truncLen flag (for ITS) but still use just the forward reads, and then merge the tables downstream?

**Comment by benjjneb** [comment]
What is important is that the same biological variant will be trimmed/truncated to the same length in your different runs. If that is not the case, when the ASV tables from different runs are combined, the differently trimmed variants will not be recognized as being the same biological variant, and instead will become separate entries in the cross-study table.

So the answer to your question depends on whether your amplicon sequencing and pre-processing of the data will lead to identical lengths for the same variant in each run. As an example, if you have truncated the reads at the reverse primer (when present) then you should be OK -- independent of run, reads from a particular biological variant will end either at the fixed end of the read, or at the start of the reverse primer.

**Comment by gzahn** [comment]
Got it.  Thanks for the clarification!
