### ISSUE TITLE
Retrieving all reads for a Sequence Variant

### ISSUE THREAD

**Issue by jjscarpa** [benjjneb/dada2#316]
Hi, not an issue, just a question. 

Is it possible to get all reads from an individual sequence variant or a group on SVs? My understanding is that within a SV there is still a small amount of difference--i.e., all the reads are not identical--or am I mistaken? If I missed another discussion on this  could someone please point me to that thread.

Thanks a bunch
Jarrod

**Comment by benjjneb** [comment]
Yep you can do that. If `dd1` and `drp1` are the `dada-class` and `derep-class` objects for sample 1, respectively, then `dd1$map[drp1$map]` is a vector of the sequence variant to which each input read in the fastq file was assigned.

So to get the indices of each read assigned to the first sequence variant: `which(dd1$map[drp1$map] == 1`

You can then look up each read in the fastq file, and dig in more deeply if you are interested.

**Comment by jjscarpa** [comment]
Excellent. Thanks so much. I will give this a whirl
