### ISSUE TITLE
DADA2 assignTaxonomy Error

### ISSUE THREAD

**Issue by hm0306** [benjjneb/dada2#326]
I'm using DADA2 R/Bioconductor package for 16s microbiome analysis. 
There was no problem when I run assignTaxonomy function with provided training sets including SILVA and RDP. I made two customized silva reference fasta files containing either V3 region or V4 region. I successfully run assignTaxonomy function with the V4 silva reference fasta file. However, the function didn't work with the V3 reference file. I attached error message and few lines of my V3 training file.

![capture](https://user-images.githubusercontent.com/31780552/30231028-04461e30-94b7-11e7-9537-013a71275d6f.JPG)

#### V3 training fasta file ####
>Bacteria;Bacteroidetes;Flavobacteriia;Flavobacteriales;Flavobacteriaceae;Chryseobacterium
GAGGAATATTGGACAATGGGTGAGAGCCTGATCCAGCCATCCCGCGTGAAGGACGACGGCCCTATGGGTTGTAAACTTCTTTTGTATAGGGATAAACCTTTCCACGTGTGGAAAGCTGAAGGTACTATACGAATAAGCACCGGCTAACTCCGTG
>Bacteria;Chlamydiae;Chlamydiae;Chlamydiales;Simkaniaceae;Candidatus Rhabdochlamydia
CGAGAATCTTTCGCAATGGGCGAAAGCCTGACGAAGCGACGCTGCGTGAGTGATGAAGGCTTTCGGGTTGTAAAACTCTTTCGCGCAAGAGCAAAGTGTGTTAGTGAATAACTGATACGTATGAGAGTACTGCGTAAAGAAGCACCGGCTAACTCCGTG
>Bacteria;Proteobacteria;Alphaproteobacteria;Rickettsiales;Rickettsiales Incertae Sedis;Candidatus Lariskella
GGGGAATATTGGACAATGGGCGAAAGCCTGATCCAGCGACGCCGCGTGAGTGAAGAAGGCCTTCGGGTTGTAAAGCTCTTTCGGTAGGGAAGATAATGACGGTACCTACAAAAGAAGCTCCGGCTAACTTCGTG
>Bacteria;Bacteroidetes;Cytophagia;Cytophagales;Flammeovirgaceae;Roseivirga
AGGGAATATTGGTCAATGGGCGAGAGCCTGAACCAGCCATGCCGCGTGCAGGAAGACGGCCTTCTGGGTTGTAAACTGCTTTTGTACGGGAAGAAAATGCCCTTGCGAGGGAAATTGCCGGTACCGTACGAATAAGCACCGGCTAACTCCGTG
>Bacteria;Chlamydiae;Chlamydiae;Chlamydiales;cvE6;Thalassiosira rotula
CGAGAATCTTTCGCAATGGGCGCAAGCCTGACGAAGCGACGCCGTGTGAACGAAGAAGGCCTTAGGGTTGTAAAGTTCTTTCGCCGGGGAACAAGAGAGGTTGGCTAATATCCAGCCGATTTGATGGTACTCGGTAAAGAAGCACCGGCTAACTCCGTG

**Comment by cresil** [comment]
Did you forget to put the prompt (>) in the fasta header?

**Comment by hm0306** [comment]
>Bacteria;Bacteroidetes;Flavobacteriia;Flavobacteriales;Flavobacteriaceae;Chryseobacterium
GAGGAATATTGGACAATGGGTGAGAGCCTGATCCAGCCATCCCGCGTGAAGGACGACGGCCCTATGGGTTGTAAACTTCTTTTGTATAGGGATAAACCTTTCCACGTGTGGAAAGCTGAAGGTACTATACGAATAAGCACCGGCTAACTCCGTG

**Comment by hm0306** [comment]
No, I put the prompt in the fasta header like this.

![image](https://user-images.githubusercontent.com/31780552/30240505-89d7275a-953f-11e7-8cd5-4e8fc9ce58ba.png)

**Comment by benjjneb** [comment]
This error very likely comes from some formatting issue in the training fasta file, but I can't see anything in this header.

Could you share the whole file, and I'll see if I can reproduce the error locally?

**Comment by hm0306** [comment]
I generated two files in the same manner; one is for V3 region and the other is V4 region. The program worked with V4 fasta file but not with V3 file. I attached two files. Thank you.


[SILVA_128_SSURef_Nr99_tax_silva_full_align_trunc.pcr.noEuk.V3.fasta.zip](https://github.com/benjjneb/dada2/files/1296664/SILVA_128_SSURef_Nr99_tax_silva_full_align_trunc.pcr.noEuk.V3.fasta.zip)
[SILVA_128_SSURef_Nr99_tax_silva_full_align_trunc.pcr.noEuk.V4.fasta.zip](https://github.com/benjjneb/dada2/files/1296668/SILVA_128_SSURef_Nr99_tax_silva_full_align_trunc.pcr.noEuk.V4.fasta.zip)

**Comment by benjjneb** [comment]
The problem here is that in the V3 file, there are a number of sequences that are very short (<8nts) which is shorter than the kmer length, and is causing the function to break when it tries to build the kmer-profile for those sequences.

You can fix this by removing all short sequences from the V3 file. I'm also flagging this as a bug as the `assignTaxonomy` function should check for this and skip short input sequences (with a user warning).

**Comment by hm0306** [comment]
Awesome! I got it. Thank you so much.

**Comment by benjjneb** [comment]
Fixed in 4613be2f9f051beace534f6a6f2080f874d334e0
