### ISSUE TITLE
Species vs Inferred sequence variants

### ISSUE THREAD

**Issue by nmshahir** [benjjneb/dada2#329]
Hey,

This is more of a broad question contrasting inferred sequence variants vs species.
I've run DADA2 on 525 samples and got 23314 inferred sequence variants returned. When I remove everything that did not get assigned a species, I get around 800 or so inferred sequence variants and lose of 60% of my data.
My question is, it right to assume that each of the 23314 sequence variants correspond to a distinct species and they've just not been annotated yet? Or is it something else?

Thank you,
Nur

**Comment by jnesme** [comment]
No. There is documented evidence of bona fide species (ie. based on DDH 70% cut-off ) having 100% identical 16S rRNA gene over the entire length of the sequence. Sequence variant are sequence variants, OTU are OTU and species are species as defined by the had-hoc comitee on bacterial species delineation: cf. Stackerbrandt et al. 

Envoyé de mon iPhone

**Comment by benjjneb** [comment]
> My question is, it right to assume that each of the 23314 sequence variants correspond to a distinct species and they've just not been annotated yet? 

Definitely not. As @jnesme has described, species is a hard concept in bacteria, and it does not map 1-1 onto 16S sequence variants, or even full-length 16S sequences.

If using `assignSpecies(..., allowMultiple=TRUE)`: The ASVs with no species assignment do not exactly match an observed and annotated species in the database you've used.

If using `assignSpecies(..., allowMultiple=FALSE)`: The ASVs with no species assignment do not exactly match an observed and annotated species in the database you've used, or match multiple such species.

If using `assignTaxonomy`: The ASVs with no species assignment do not match the same species in over 50% of the bootstrap replicate kmer-based assignments (see Wang et al. 2007 for more info on the naive Bayesian classifier method).
