### ISSUE TITLE
Dada2 filterAndTrim error

### ISSUE THREAD

**Issue by drish91** [benjjneb/dada2#333]
I’m a new dada2 user, on a windows machine, with latest versions of both R and Bioconductor. I’m working my way through the tutorial (the one with Big Data gz files) on some of my data and was hoping you could help me with some errors I’ve been getting.

I was looking at some of the github issues and the one that resembles mine would be the issue with multithreading. I have the latest version of ShortRead, which was one of the earlier issues #263, when I tried running filterAndTrim(), but this is a new one. I set multithreading to False, based on this suggestion #273, but even after that, I end up with this error:

> filterAndTrim(file.path(path,fns), file.path(filtpath,fns), truncLen = 240, maxEE = 1, truncQ =11, rm.phix=TRUE, compress=TRUE, verbose=TRUE, multithread=TRUE)
Error in `colnames<-`(`*tmp*`, value = basename(fwd)) :
  attempt to set 'colnames' on an object with less than two dimensions
In addition: Warning message:
In mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule,  :
  all scheduled cores encountered errors in user code
>
> packageVersion("ShortRead")
[1] ‘1.34.1’
>
> packageVersion("dada2")
[1] ‘1.5.2’
>
> filterAndTrim(file.path(path,fns), file.path(filtpath,fns), truncLen = 240, maxEE = 1, truncQ =11, rm.phix=TRUE, compress=TRUE, verbose=TRUE, multithread=FALSE)
Error in C_matchRef(seqs, sq.phix, wordSize, nonOverlapping) :
  std::bad_alloc

> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.4 (Final)

locale:
[1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
[3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
[5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
[7] LC_PAPER=en_US.UTF-8       LC_NAME=C
[9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
[1] dada2_1.5.2                Rcpp_0.12.12
[3] ShortRead_1.34.1           GenomicAlignments_1.12.2
[5] SummarizedExperiment_1.6.3 DelayedArray_0.2.7
[7] matrixStats_0.52.2         Biobase_2.36.2
[9] Rsamtools_1.28.0           GenomicRanges_1.28.4
[11] GenomeInfoDb_1.12.2        Biostrings_2.44.2
[13] XVector_0.16.0             IRanges_2.10.2
[15] S4Vectors_0.14.3           BiocParallel_1.10.1
[17] BiocGenerics_0.22.0

loaded via a namespace (and not attached):
[1] compiler_3.4.1          RColorBrewer_1.1-2      plyr_1.8.4
[4] bitops_1.0-6            tools_3.4.1             zlibbioc_1.22.0
[7] tibble_1.3.3            gtable_0.2.0            lattice_0.20-35
[10] rlang_0.1.1             Matrix_1.2-11           GenomeInfoDbData_0.99.0
[13] hwriter_1.3.2           stringr_1.2.0           grid_3.4.1
[16] data.table_1.10.4       latticeExtra_0.6-28     magrittr_1.5
[19] ggplot2_2.2.1           reshape2_1.4.2          scales_0.4.1
[22] colorspace_1.3-2        stringi_1.1.5           RCurl_1.95-4.8
[25] lazyeval_0.2.0          RcppParallel_4.3.20     munsell_0.4.3

I’m not sure how to fix this. Is this simply a memory issue, since I’m not running it on my local machine.
Thanks!

**Comment by benjjneb** [comment]
My first guess is that you are applying `filterAndTrim` to a single sample? If so, that is probably the cause of that error, and it should work if you use two samples.

If that's not it, can you try using `fastqPairedFilter` on an individual sample or two? That way we can see the errors printed to screen, rather than just the non-specific `scheduled cores encountered errors in user code`

**Comment by drish91** [comment]
Its not on a single sample since,
> length(fns)
[1] 36

and its accessing the right path for them, I checked. But yes, I'll try fastqPairedFilter and let you know what happens.

**Comment by drish91** [comment]
I used fastqPairedFilter but that resulted in the same error. 
> for (i in seq_along(fnFs)){
+ fastqPairedFilter(c(fnFs[i], fnRs[i]), c(filtFs[i], filtRs[i]), truncLen=c(240,160), maxN=0, maxEE=                                            Error in C_matchRef(seqs, sq.phix, wordSize, nonOverlapping) :
  std::bad_alloc

Would this not run on gzipped fastq files? I'm trying to try it on a couple of unzipped files now.

**Comment by benjjneb** [comment]
It should work with gzipped files just fine. And I've never seen that error before.

What is the memory available on your machine, and is the amount available to R restricted in some way? You said it was a windows machine, but the R session is saying CentOS, is this w/in some virtual machine?

If you could share a single file that causes this error I can also try to reproduce the error locally.

**Comment by drish91** [comment]
Its a memory issue, yes, but I'm not sure why. I'm running R on linux server on a windows machine. I don't think there's any restriction to R regarding the memory allocation, it says Inf when I check memory limits in R.

I've sent you two files on email, let me know if you need anything else.

**Comment by drish91** [comment]
So, I checked the filter.R script, and it seems like there's an issue with how the "isPhiX()" function is being called on my sequences. I turned that off and the fastqPairedFilter() threw no errors.

> Error in C_matchRef(seqs, sq.phix, wordSize, nonOverlapping):
std::bad_alloc

**Comment by benjjneb** [comment]
> So, I checked the filter.R script, and it seems like there's an issue with how the "isPhiX()" function is being called on my sequences. I turned that off and the fastqPairedFilter() threw no errors.

??? Hm... Can you check if maybe the phiX genome file included with the package was somehow corrupted?

```
library(ShortRead)
phi <- as(sread(readFasta(system.file("extdata", "phix_genome.fa", package="dada2"))), "character")
dada2:::C_isACGT(phi)
nchar(phi)
```

I mean, if it works now w/o the phiX filtering then maybe that is good enough, but I don't understand what is happening here at all.

**Comment by drish91** [comment]
hmm, strange. The phiX genome file seems fine:
> phi <- as(sread(readFasta(system.file("extdata", "phix_genome.fa", package="dada2"))), "character")
> dada2:::C_isACGT(phi)
[1] TRUE
> nchar(phi)
[1] 5386

I tried it running it again, after this check, with rm.phix() as true, but it still didn't work! 
Oh well, its good for now!
