### ISSUE TITLE
Merge and split datasets

### ISSUE THREAD

**Issue by NinaKons** [benjjneb/dada2#337]
Hi Ben,

I am new to manipulating DADA2 and Phyloseq objects, but need to merge and split **2 16S datasets**: 
- DNA (showing bacterial abundance) 
- cDNA (bacterial activity)
- Some samples are **shared** and some **unique** to each dataset

I need to assign the **same** RSVs from **both** dataset with the SAME bacterial taxa, so as I do not have duplicates or inconsistencies during the feature selection process. ie, the **sequences** of the most abundant RSVs in each group (control, case) of the two datasets (DNA, cDNA) need to be unique.  

Ultimate aim is to visualize the 2 datasets **separately** in respect to bar charts, ordinations and most abundant RSVs between the cases and controls in each dataset, DNA and cDNA, in respect of **all** and **shared samples**, with **phyloseq**, after processing the reads in **DADA2**. 

Therefore, I have 3 questions:
# **1. When do you suggest to merge the 2 datasets?** Tried the following: 
### Merge multiple runs 
st1 <- readRDS("/home/ubuntu/work/run1/trimmed/seqtab.rds")
st2 <- readRDS("/home/ubuntu/work/cDNA/trimmed/seqtab.rds")
st.all <- mergeSequenceTables(st1, st2)
### Remove chimeras
seqtab.nochim <- removeBimeraDenovo(st.all, method="consensus", multithread=TRUE) # But takes ~ overnight
### Assign taxonomy
tax <- assignTaxonomy(seqtab.nochim, "~/databases/dada2/gg_13_8_train_set_97.fa.gz", multithread=TRUE)

### Subset
And think to subset the RSV and tax tables of each dataset based on metadata sample_ID, then to use the subsetted RSV table to map the taxa (based on RSVs):
seqtab.nochim_DNA <- subset(seqtab.nochim, rownames(seqtab.nochim) %in% DNA_mt$NGS_ID) # RSV table
tax_DNA <- tax[, rownames(tax) %in% colnames(seqtab.nochim_DNA)] # Tax table
### Reduce sparcity of RSVs
seqtab.nochim_DNA_sp <- seqtab.nochim_DNA[ colSums(counts(seqtab.nochim_DNA)) > 1, ]
### Load metadata for Phyloseq 
DNA_mt <- read.csv(file="DNA_metadata.csv", header=TRUE)
### Phyloseq object
ps_DNA <- phyloseq(otu_table(seqtab.nochim_DNA_sp, taxa_are_rows = FALSE), 
                   tax_table(tax_DNA),
                   sample_data(DNA_mt))

# **2. OR do you think merging** (not sure how, yet) and **subsetting **phyloseq objects** of 2 separately DADA2 processed datasets (up to taxonomy assignment) are more efficient?**

### Subset DNA and cDNA with the same samples
sub_ps_DNA = subset_samples(ps_DNA, Short_name = ps_cDNA$Short_name)

# **3. Can you suggest which command(s) to use in order to select the most abundant RSVs between the control and case in each dataset, DNA and cDNA?**
- Operation on DADA2 RSV or Phyloseq object?
- Normalize number of RSVs ?
- foldchange = 2
- q < 0.05

Many thanks in advance!

**Comment by benjjneb** [comment]
I would proceed as in your example 1, with one change: I would do the sample subsetting and taxa pruning **after** I had loaded the data into a phyloseq object (see the `subset_samples` and `subset_taxa` or `prune_taxa` commands in phyloseq).

What you are doing isn't wrong, but phyloseq is particularly adept at making sure all the different types of data stay consistent when you subset/merge, so if you are using phyloseq anyway I would move that part into phyloseq.

On 3, I may not completely understand the question, but here is some code to pick out the most abundant RSV in DNA samples from controls (modify variable names as necessary):

```
ps_DNA_control <- subset_samples(ps, Condition == "Control" & Type == "DNA")
ps_DNA_control_freq <- transform_sample_counts(ps_DNA_control, function(x) x/sum(x))
freq.total <- taxa_sums(ps_DNA_control_freq)
i.most_frequent <- which.max(freq.total)
```

You can also do this from a sequence table matrix directly using regular R commands.

ps: Can you clarify, do the DNA and cDNA sequences cover the same gene region, i.e. the F/R primers are the same for each?

**Comment by NinaKons** [comment]
Thank you very much, it makes sense now :). 
Yes, DNA and cDNA were amplified using the same primer sets, so as they are comparable.
