### ISSUE TITLE
Error in Sample Inference

### ISSUE THREAD

**Issue by pdobrano** [benjjneb/dada2#340]
Hi,

I'm running 94 samples through dada2 [1.4.0] in R [3.4.1] in Windows.
In the Sample Inference section, dadaFs <- dada(derepFs, err=errF, multithread=TRUE) runs fine, but the following reverse read command gives me this error:

**Error in dada(derepRs, err = errR, multithread = TRUE) : 
     object 'errR' not found**

Is there a solution to this?

Thanks,
Peter

**Comment by benjjneb** [comment]
Hi Peter,
Are you running [the tutorial workflow](https://benjjneb.github.io/dada2/tutorial.html)?

If so, it looks like maybe you skipped the second command in the Learn Error Rates section that learns the reverse error rates, and hence have no `errR` object defined. If so, you can fix this problem by running that command:

```
errR <- learnErrors(filtRs, multithread=TRUE)
```

**Comment by pdobrano** [comment]
That was my mistake! Thanks for your insight.

Peter
