### ISSUE TITLE
What to do if error profile from learnErrors doesn't look good?

### ISSUE THREAD

**Issue by janetw** [benjjneb/dada2#341]
Hello,
I realize this really isn't a DADA2 issue but I am hoping you can give me some suggestions on what to try next or where I might be running into problems.

I have run the learnErrors function using both nreads = 1e6 and 2e6. However, the error rate profiles don't look much different. I think they both look bad. (This is also the first time that I am running things using DADA2 1.4 but I am guessing that it doesn't have anything to do with that.) Generally  the black line with dots decreases as quality score increases. (See pdf 'dd_learnF_plotErrors_6-5-17.pdf')
[dd_learnF_plotErrors_6-5-17.pdf](https://github.com/benjjneb/dada2/files/1335350/dd_learnF_plotErrors_6-5-17.pdf)

This time, I don't see that same pattern or it's not decreasing as much as previous error rate profiles that I have been seeing.
See pdfs 'plotErrors_errF_nread_1e6.pdf' and 'plotErros_errF_nread_2e6.pdf'.
[plotErrors_errF_nread_2e6.pdf](https://github.com/benjjneb/dada2/files/1335351/plotErrors_errF_nread_2e6.pdf)
[plotErrors_errF_nread_1e6.pdf](https://github.com/benjjneb/dada2/files/1335352/plotErrors_errF_nread_1e6.pdf)

The code between the first one and the two others is slightly different. This is the code that I ran previously:
drp.learnF <- derepFastq(sample(filtFs, NSAM.LEARN)) # with NSAM.LEARN being the number of samples estimated to contain about 1e6 reads
dd.learnF <- dada(drp.learnF, err=NULL, selfConsist=TRUE, multithread=TRUE)
errF <- dd.learnF[[1]]$err_out
pdf("dd_learnF_plotErrors_6-5-17.pdf")
plotErrors(dd.learnF[[1]], nominalQ=TRUE)
dev.off()

The current code is as follows:
errF <- learnErrors(filtFs, nread=1e6, multithread=TRUE)
pdf("plotErrors_errF_nread_1e6.pdf")
plotErrors(errF, nominalQ = TRUE)
dev.off()

These are from two different runs and different sample types so I realize that makes them different.  But am I missing something doing something else? Thoughts on how I can improve the learning on the error rates? 

Any insight or suggestions would be greatly appreciated.

Thanks,
Janet

**Comment by benjjneb** [comment]
What I'm seeing is that the error rate estimation looks fine, as the black line (the model) fits the black points (observed) well, but that the error rates unexpectedly don't decrease with higher quality. This looks more like 454 data than Illumina data.

What sequencing instrument was used there? Were there other potential differences in the wet-lab protocol, e.g. PCR or gene region?

You are probably OK to just use this fitted error model, but I would do an extra sanity check on the output sequence variants - for example confirm the taxonomies of the abundant ones make sense.

**Comment by janetw** [comment]
Thanks! They are both from the same MiSeq instrument with amplicons generated from primers targeting the V1-V3 16S rRNA region using extraction protocols that we have used before.
I will continue to move forward with this and as you suggest, continue to keep a check on things to see if they look odd.
Thanks again!
