### ISSUE TITLE
Short reads remain after DADA2 processing

### ISSUE THREAD

**Issue by NinaKons** [benjjneb/dada2#342]
Hi Ben,
I processed raw reads in DADA2 with the following length and 31 bases overlap with 0 mismatch. 
R1: 243
R2: 214  
However, there were many shorter sequences maintained after filtering and merging, see the attached distribution of read length.
![screen shot 2017-09-28 at 9 24 52 am](https://user-images.githubusercontent.com/29718191/30978277-f0a4e32a-a42e-11e7-8506-172da7d7f0d0.png)
I checked these short sequences and they align to the human mitochondria.

Why do you think this is happening and how can I proceed for better analyses?
1. Remove sequences with less than 380 bases
filtered_RSV_table <- nchar(colnames(otu_table(physeq)) > 380 (is this going to do the job?)

2. Filter out mitochondria
physeq<- physeq %>%
  subset_taxa(
    Kingdom == "Bacteria" &
    Family  != "mitochondria" &
    Class   != "Chloroplast"
  )

3. Apply both (1,2)
4. Do nothing, operate on all the sequences
5. Other

Many thanks in advance.

**Comment by benjjneb** [comment]
If you've checked that the <380 length sequences are not what you want, I would go ahead and remove them (as we suggest in the tutorial). This is like "cutting a band" in silico, and is a valid way to focus in on the sequences you care about.

If there are still mitochondrial sequences in the table, you could also remove those, but I'd probably start with the length filtering.

ps: If working with a phyloseq object...

```
filtered_physeq <- prune_taxa(nchar(taxa_names(physeq)) > 380, physeq)
```

**Comment by NinaKons** [comment]
Ohh, thank you so much for a prompt reply, saves time :), will follow your suggestions, cheers!
