### ISSUE TITLE
filterAndTrim output only shows forward reads?

### ISSUE THREAD

**Issue by quangnguyen1995** [benjjneb/dada2#343]
Hi!

I want to track the number of reads that pass the filtration in filterAndTrim() of the reverse reads as well as the forward reads. However, the "out" matrix that exists as an output of filterAndTrim() only shows it for the reverse reads. Is there any way that I can access this matrix for the reverse reads as well, given that I want to see how different maxEE parameters for impacts the number of reverse reads that pass the filter. 

I might totally be misreading the matrix or there is no difference between how much reverse and forward reads went through filtration?

Thanks!

**Comment by benjjneb** [comment]
> there is no difference between how much reverse and forward reads went through filtration?

This. If running `filterAndTrim` on paired reads, the filter acts on pairs of reads, i.e. it requires **both** the forward and reverse reads to pass, or **both** are filtered out.

You can set different thresholds for the F/R reads (e.g. `maxEE=c(1,2)`), but paired filtering will always act on the pairs.

**Comment by quangnguyen1995** [comment]
Awesome. Thank you very much for your response!
