### ISSUE TITLE
plotQualityProfile aggregate issue

### ISSUE THREAD

**Issue by bashirshir** [benjjneb/dada2#344]
Dear Benjamin,
I'm running dada2 1.4.0 on R 3.4.1. 

Previously, I've used the aggregate argument within plotQualityProfile within the same build version (although different installed instance). 

Was the "aggregate" recently removed? I don't see it on documentation for 1.4.0 but to my understanding it was previously present on same version?
```
> forwardplot <- plotQualityProfile(fnFs[1:53], aggregate=T)
Error in plotQualityProfile(fnFs[1:53], aggregate = T) : 
  unused argument (aggregate = T)
```

Removal of "aggregate" allows the code to run, producing 53 plots, which is not the desired outcome. I've also reinstalled dada2 again, same as previously biocLite. 

Any assistance would be appreciated.

Thanks,

Bashir

**Comment by benjjneb** [comment]
Hi Bashir,
The `aggregate` option wasn't added until the 1.5.0 package version, and thus isn't a part of the 1.4 release version on Bioconductor. You can get that option by installing the dev version from github, or it will be part of our next release (1.6) on Bioconductor in late Oct.

**Comment by bashirshir** [comment]
Thank you for the response, Ben. I've checked 1.5.0 and you are correct.
