### ISSUE TITLE
mergeSequenceTables Error in if (!(all(sapply(tables, is.sequence.table))))

### ISSUE THREAD

**Issue by srosales712** [benjjneb/dada2#345]
Hi 
I'm attempting to combine two sequencing runs with dada2 version 1.5.2.  One run labeled "seqtab_M.rds"  is a MiSeq run (with paired-ends merged) and the other labled "seqtab_H.rds" is a Hi-seq run (with only the foward reads). To do this I'm using mergeSequenceTables like so:

# Merge multiple runs
st1 <- readRDS("Google Drive/CRCP/seqtab_M.rds")
st2 <- readRDS("Google Drive/CRCP/seqtab_H.rds")
st.all <- mergeSequenceTables(st1, st2)
When I run mergeSequenceTables I get an error that reads:
Error in if (!(all(sapply(tables, is.sequence.table)))) { : 
  missing value where TRUE/FALSE needed

Any idea why I'm getting this error?

Thanks,

Steph

**Comment by benjjneb** [comment]
Could you post the output of these commands?

```
class(st1); mode(st1); dim(st1)
class(st2); mode(st2); dim(st2)
```

**Comment by srosales712** [comment]
> class(st1); mode(st1); dim(st1)
[1] "matrix"
[1] "numeric"
[1]    87 24220
> class(st2); mode(st2); dim(st2)
[1] "matrix"
[1] "numeric"
[1]   22 4324

**Comment by benjjneb** [comment]
That looks as expected. Can you try to run the validation method on the tables directly?

```
dada2:::is.sequence.table(st1)
dada2:::is.sequence.table(st2)
```

**Comment by srosales712** [comment]
> dada2:::is.sequence.table(st1)
[1] NA
> dada2:::is.sequence.table(st2)
[1] TRUE

**Comment by benjjneb** [comment]
Something's up with `st1`. Can you check that `rownames(st1)` and `colnames(st1)` are as expected, i.e. the sample names and DNA sequences respectively?

Also, `any(is.na(st1))`

**Comment by srosales712** [comment]
any(is.na(st1))
[1] FALSE
There are lots of NA's in the row names.
[21] "SRR3633449" "SRR3633451" NA           NA           NA          
[26] NA           NA           NA           NA           NA          
[31] NA           NA           NA           NA           NA          
[36] NA           NA           NA           NA           NA          
[41] NA           NA           NA           NA           NA          
[46] NA           NA           NA           NA           NA          
[51] NA           NA           NA           NA           NA          
[56] NA           NA           NA           NA           NA          
[61] NA           NA           NA           NA           NA          
[66] NA           NA           NA           NA           NA          
[71] NA           NA           NA           NA           NA          
[76] NA           NA           NA           NA           NA          
[81] NA           NA           NA           NA           NA          
[86] NA           NA   

The col names that were printed looked ok
[1000] "TACGGAGGGTGCGAGCGTTAATCGGAATTACTGGGCGTAAAGCGCATGCAGGTGGTTCGTTAAGTCAGATGTGAAAGCCCGGGGCTCAACCTCGGAACTGCATTTGAAACTGGCGGACTAGAGTACTGTAGAGGGGGGTAGAATTTCAGGTGTAGCGGTGAAATGCGTAGAGATCTGAAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACAGATACTGACACTCAGATGCGAAAGCGTGGGGAGCAAACAGG"

BTW thanks for helping so quickly

**Comment by benjjneb** [comment]
The function is failing because of the NA rownames, it expects that all rows are named by a unique sample name. Can you add the sample names back to the table? i.e. `rownames(st1) <- my.list.of.samples`? If you get rid of the NA rownames, it should solve this probelm.

Be careful that the samples are in the same order as the sample names you assign though!

**Comment by srosales712** [comment]
Do you know why the row names were stripped away and how I can potentially prevent it in the future?

**Comment by benjjneb** [comment]
> Do you know why the row names were stripped away and how I can potentially prevent it in the future?

I don't. If you'd like to post the code you used to generate `st1` I could take a look. The tutorial and Big Data workflows should propagate sample names (or file names) through to the table.

**Comment by srosales712** [comment]
I think I found the error
names(derepF_M) <- sample.names
names(derepR_M) <- sample.names
names(derepF_H) <- sample.names ( I should name this one something different!)

**Comment by benjjneb** [comment]
That looks like it! Maybe `sample.names_M` and `sample.names_H` to avoid any mixups.

Mislabeled samples = huge headaches later on!

**Comment by srosales712** [comment]
Thanks again! It was a silly error but I probably would not have caught it with the help!

**Comment by cmmertz** [comment]
Hi! It seems I am also having this issue but my error simply says 

Error in mergeSequenceTables(st1, st2, st3) : 
  could not find function "mergeSequenceTables"

The seqtab.rds files were made using "seqtab <- makeSequenceTable(mergers)" for 3 separate runs. Now I want to combine samples from each of those 3 runs. 

Here is all of the troubleshooting I have done so far, thank you for your help!! 


> st1 <- readRDS("/Users/connermertz/Documents/Sequence Analysis/E1_E2_All_Samples/GUTS_Danny_run2021/seqtab.rds")
> st2 <- readRDS("/Users/connermertz/Documents/Sequence Analysis/E1_E2_All_Samples/GUTS_Fred_run2022/seqtab.rds")
> st3 <- readRDS("/Users/connermertz/Documents/Sequence Analysis/E1_E2_All_Samples/GUTS_Bonnie_run2022/seqtab.rds")
> class(st1); mode(st1); dim(st1)
[1] "matrix" "array" 
[1] "numeric"
[1]   6 894
> class(st2); mode(st2); dim(st2)
[1] "matrix" "array" 
[1] "numeric"
[1]  212 8542
> class(st3); mode(st3); dim(st3)
[1] "matrix" "array" 
[1] "numeric"
[1]   96 5431
> dada2:::is.sequence.table(st1)
[1] TRUE
> dada2:::is.sequence.table(st2)
[1] TRUE
> dada2:::is.sequence.table(st3)
[1] TRUE
> any(is.na(st1))
[1] FALSE
> any(is.na(st2))
[1] FALSE
> any(is.na(st3))
[1] FALSE
> ##repeat for each dataset sequenced separately
> st.all <- mergeSequenceTables(st1, st2, st3)
Error in mergeSequenceTables(st1, st2, st3) : 
  could not find function "mergeSequenceTables"
> 

> #Try making tables first?
> input_tables <- list(st1, st2, st3)
> mergetab <- mergeSequenceTables(tables=input_tables) # list of sequence tables
Error in mergeSequenceTables(tables = input_tables) : 
  could not find function "mergeSequenceTables"
> #Try mnaking files first?
> files <- c(st1, st2, st3)
> mergetab <- mergeSequenceTables(tables=files) # vector of filenames
Error in mergeSequenceTables(tables = files) : 
  could not find function "mergeSequenceTables"
>

**Comment by benjjneb** [comment]
@cmmertz Did you load the dada2 library first? `library(dada2); packageVersion("dada2")`

**Comment by cmmertz** [comment]
Oh my gosh, yes I forgot to load dada2 before starting my analysis. So sorry! Thank you for the prompt response!
