### ISSUE TITLE
Issue with filterAndTrim

### ISSUE THREAD

**Issue by Biancabrown** [benjjneb/dada2#346]
Hi All, 

I've been trying to run dada2 1.4 on my dataset, but I've been encountering an error on, at least I think it is, the filternAndTrim step.
I am usin the standard code from your website: 
# Sort ensures forward/reverse reads are in same order
fnFs <- sort(list.files(path, pattern="_R1_001.fastq"))
fnRs <- sort(list.files(path, pattern="_R2_001.fastq"))
# Extract sample names, assuming filenames have format: SAMPLENAME_XXX.fastq
sample.names <- sapply(strsplit(fnFs, "_"), `[`, 1)
# Specify the full path to the fnFs and fnRs
fnFs <- file.path(path, fnFs)
fnRs <- file.path(path, fnRs)

filt_path <- file.path(path, "filtered") # Place filtered files in filtered/ subdirectory
filtFs <- file.path(filt_path, paste0(sample.names, "_F_filt.fastq"))
filtRs <- file.path(filt_path, paste0(sample.names, "_R_filt.fastq"))

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(220,220),
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=TRUE) 
saveRDS(out, "out.rds")  

If I set it with multithread= TRUE I get the following error:

Error in `colnames<-`(`*tmp*`, value = c("BB1_ATCGGCGTTACA_L001_R1_001.fastq",  : 
  attempt to set 'colnames' on an object with less than two dimensions
Calls: filterAndTrim -> colnames<-
In addition: Warning message:
In mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule,  :
  all scheduled cores encountered errors in user code
Execution halted

I saw that in another thread, someone suggested upgrading the ShortRead version. I'm currently using version [1] ‘1.34.1’. 

If I set it with multithread= FALSE I get the following error:

Error in .Call2("fasta_index", filexp_list, nrec, skip, seek.first.rec,  : 
  function '_append_string_to_CharAEAE' not provided by package 'S4Vectors'
Calls: filterAndTrim ... FUN -> .read_XStringSet -> fasta.index -> .Call2 -> .Call
Execution halted

Do have any opinions about fixing this issue? 

Please keep in mind that I ran this with the older version of dada2, and everything runs fine. However, while using the older version, I realized that when I set the code to mulithread=TRUE, it still only uses a single core. If you have any suggestions on how to use the multithread option in the older version that would be appreciated.

**Comment by benjjneb** [comment]
Can you try upgrading your Bioconductor installation as a whole:

```
## try http:// if https:// URLs are not supported
source("https://bioconductor.org/biocLite.R")
biocLite()
## Update all/some/none? [a/s/n]: Enter a
```

If that doesn't work, can you report `R.version` and also the version of Bioconductor you are using (the `biocLite` command will print it out).

**Comment by Biancabrown** [comment]
Hey Benjj, 

Updating the biocunductor as a whole worked. Thank you.

I finally got it to run. However, when I got to the error correcting stage

errF <- learnErrors(filtFs, multithread=TRUE) 

ionly ran 12 of my 576 samples. Is this normal?  I didn't have this error with the older version. Any thoughts?

**Comment by benjjneb** [comment]
Did you get an error? Or just a report that it only used 12 samples.

That is normal, as of 1.4 at least, `learnErrrors` will by default only use enough samples to exceed 1M total reads, as that is almost always sufficient to learn the error model.

**Comment by Biancabrown** [comment]
Hi Benjj, 

I didn't get an error. It's still going thanks. Another rather nuanced question for you. My 576 samples are separated over roughly 3 distinct sequencing run using the same primers and sequencing technology(Illumina MiSeq). Does it matter if I process them all together or would it be best to process each sequence run separately using dada2 then merge output table?

**Comment by benjjneb** [comment]
We generally recommend learning error rates from each run, as error rates can vary substantially between different machines etc, and then processing each run with that run's error rates.

However, if these were all done on the same machine, its probably fine to use the same error rates for all the samples.

**Comment by Biancabrown** [comment]
Hi, 

Thank you. Everything seems to be running great, and this was good advice. You have fully resolved all the issues I've been having today.
