### ISSUE TITLE
Processing Miseq and Hiseq data simultaneously 

### ISSUE THREAD

**Issue by srosales712** [benjjneb/dada2#347]
Hi, I went through the DADA2 tutorial for a project that sequenced 16S rRNA amlicons on both a Miseq and Hiseq. Thus the project contains varying sequence lengths. I plotted the DADA2 results with phyloseq, ordinate(ps, method="NMDS", distance="bray") and the ordination plot showed all the Hiseq on one end of the plot and all the Miseq on the other end with the warning: In metaMDS(veganifyOTU(physeq), distance, ...) : Stress is (nearly) zero - you may have insufficient data. 
I think this might be because of the variation in sequence length of the datasets. The Miseq run was merged but for the Hiseq only the forward reads were processed. So I like to know if there are any suggestions on how to process both Miseq and Hiseq sequences at the same time?  Perhaps by making them the same sequence length? Although I don't know at which step this can be done.
Thanks!

**Comment by benjjneb** [comment]
In order to meaningfully merge datasets, they need to cover the same genetic region. Are you using the same primer set in both cases? If so, you can truncate the merged Miseq reads to the length of the forward Hiseq reads you used, and they will then be able to be meaningfully merged. 

Basically, if you get `ACGTA` from one platform, and `ACGTACGT` from the other, from the same biological sequence, those are treated as different sequence variants. So you need to reduce the longer-read to the same length as the shorter ones.

**Comment by srosales712** [comment]
Thank you for responding! Yes, the same primers were used to generate the data. My rationale was also to trim the Miseq reads after merging. Below  are the steps that I took. I wasn't successful, but I wanted to know if I was on the right track.
seqtabMiseq <- makeSequenceTable(mergers)
get_merged <- getSequences(seqtabMiseq, collapse = FALSE, silence = TRUE)
head(get_merged)
[1] "TACGTAGGTGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGCGCGCGCAGGCGGTCTCTTAAGTCTGATGTGAAAGCCCACGGCTCAACCGTGGAGGGTCATTGGAAACTGGGAGACTTGAGTGCAGGAGAGAAAAGTGGAATTCCACGTGTAGCGGTGAAATGCGTAGAGATGTGGAGGAACACCAGTGGCGAAGGCGGCTTTTTGGCCTGTAACTGACGCTGAGGCGCGAAAGCGTGGGGAGCAAACAGG"
[2] "TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGTGCGTAGGCGGCCTTTTAAGTTGGATGTGAAAGCCCCGGGCTTAACCTGGGAACGGCATCCAAAACTGAGAGGCTCGAGTGCGGAAGAGGAGTGTGGAATTTCCTGTGTAGCGGTGAAATGCGTAGATATAGGAAAGAACACCAGTGGCGA

path_trim <-("Google Drive/CRCP/")
out_trim <- file.path(path_trim, "trim")
Trim_merged <- filterAndTrim(get_merged,out_trim, truncLen=c(130), compress=TRUE, multithread=TRUE) 

-Error in filterAndTrim(get_merged, path_trim, truncLen = c(130), compress = TRUE,  : 
  Every input file must have a corresponding output file.

Thanks again for the help!
