### ISSUE TITLE
Workaround for memory allocation? assignTaxonomy

### ISSUE THREAD

**Issue by yjhila** [benjjneb/dada2#349]
Hi @benjjneb ,
I had previously run my data through an earlier version of your pipeline and was able to assign taxonomy, but with the newer version, I keep getting a memory allocation error whenever I try to run this line:

> taxa <- assignTaxonomy(seqtab.nochim[,1:5], "C:/Users/.../16S Reads/rdp_species_assignment_16.fa.gz", multithread=TRUE)
Error in C_assign_taxonomy2(seqs, rc(seqs), refs, ref.to.genus, tax.mat.int,  : 
  Memory allocation failed.

(I am abbreviating the file path here for privacy purposes)

I use Windows 7 and have 16 GB of RAM and have tracked the memory use on my Resource Monitor, where it doesn't show R as even approaching the 45% mark on my physical memory. I use RStudio Version 1.0.153, R version 3.4, and dada2 1.4.0. 

Within R, I have tried setting the memory limit to my max physical size using: memory.limit(size=16384) and have also tried memory.limit(size=NA) and size=50000 (something I saw worked for someone else). No matter what I do, I get the Memory allocation failed error. Every other intensive step prior worked without a problem. My seqtab matrix is 18.4 Mb and the seqtab.nochim is only 4.8Mb

I have also tried using each of the different taxonomy sets (gg, rdp, SILVA) and have also tried multithread=FALSE

Do you have any workarounds for how I can get this step to work? 

Thank you

**Comment by benjjneb** [comment]
Can you report the output of the following:

```
packageVersion("dada2")
R.version
```

Could you also try upgrading your Bioconductor installation to the most recent version (and report your Bioconductor version from first command below):

```
source("https://bioconductor.org/biocLite.R")
biocLite()
biocLite("dada2")
```

Can you double-check that the memory issue remains after upgrading the BioC packages (and reinstalling dada2 from BioC)?

**Comment by yjhila** [comment]
Hi @benjjneb, here is my output:

> packageVersion("dada2")
[1] ‘1.4.0’
> R.version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          4.2                         
year           2017                        
month          09                          
day            28                          
svn rev        73368                       
language       R                           
version.string R version 3.4.2 (2017-09-28)
nickname       Short Summer                
> source("https://bioconductor.org/biocLite.R")
Bioconductor version 3.5 (BiocInstaller 1.26.1), ?biocLite for help

I'm working on rerunning everything, but I had just updated all of these yesterday before starting the analysis with the latest dada2 version. I will see if anything changes, but it takes several hours to get to that point where I can attempt to assignTaxonomy again.
Thank you!

**Comment by benjjneb** [comment]
OK let me know if anything changes. If not, we'll troubleshoot some more.

Also, I would recommend looking into the `save.image` and `saveRDS` functions. They very easily let you save the entire workspace or specific objects (respectively) along the way, so that you can reload from those points should anything crash.

**Comment by yjhila** [comment]
Thank you.

So, I tried the command again, attempting multithread=TRUE and FALSE, and it still didn't work for the "species assignment" taxonomy database.
HOWEVER, it worked for the rdp training set?!
Does this mean I am locked into only being able to classify my sequences with the smaller dataset? What implications does this have in terms of the quality of the training set vs. the species assignment or GG or SILVA databases that are much larger but don't seem to work for me?
(I have read https://benjjneb.github.io/dada2/assign.html )

**Comment by benjjneb** [comment]
> So, I tried the command again, attempting multithread=TRUE and FALSE, and it still didn't work for the "species assignment" taxonomy database.
> HOWEVER, it worked for the rdp training set?!

That probably answers what is happening here.

There are two types of formatted training files: the `_train_set` files, which are used with `assignTaxonomy`, and the `_species_assignment` files, which are used with `assignSpecies` or `addSpecies`.

If you give `assignTaxonomy` one of the `_species_assignment` files, it's going to break, which it sounds like is what is happening. Can you confirm?

If so, you should still be able to use the Silva and GG databases for `assignTaxonomy`, you just need to use the right file format, e.g. `assignTaxonomy(myseqs, "path/to/silva_nr_v128_train_set.fa.gz")`

**Comment by yjhila** [comment]
That certainly explains a lot :-) 
Worked beautifully with the Silva training set now too.
I don't think that was entirely clear to me when I was going through that step. I assumed the species_assignment files were more robust and therefore I could use them in this process. Maybe us rookies need a big fat disclaimer on that step in the tutorial telling us to make sure we use training sets only!
I really appreciate the help, and the new features in the pipeline to track reads, etc. so thank you for being so responsive!

**Comment by benjjneb** [comment]
Great, glad it works! Am revising the tutorial right now for our upcoming release, so I'll see if there is a good place to add that disclaimer.
