### ISSUE TITLE
fastqPairedFilter 'Error: could not find function "encoding"'

### ISSUE THREAD

**Issue by luhugerth** [benjjneb/dada2#35]
Possibly a typo for Encoding in the core base?

**Comment by benjjneb** [comment]
Not a typo, but yes an error in the code. The call is to the ShortRead::encoding function, and that function was not being properly imported by the fastqPairedFilter function. It worked if you had loaded the full ShortRead package, but was failing as you described if you hadn't.

Thanks for bringing this to our attention! The fastqPairedFilter and fastqFilter functions have been updated and pushed to github. If you download and install the updated package they should work now, but let us know if not.

**Comment by joey711** [comment]
I see in the quick-fix for this prefixes ShortRead:: to encoding() even though this is now specifically imported from ShortRead. Typically this will generate a warning (or note?), and BioC will ask you to remove these if they are not necessary. Is there some name collision you are try to avoid? E.g. some other encoding method that we have also imported in dada2?

**Comment by joey711** [comment]
Along these lines, is there some example code to reference to reproduce this issue? I can add a unit test and check if the `@importFrom ShortRead encoding` still solves this issue or if the `ShortRead::` is really necessary, while also protecting against this issue resurfacing in the future.
