### ISSUE TITLE
Filtering process from QIIME

### ISSUE THREAD

**Issue by nice-scientist** [benjjneb/dada2#351]
I'm following the tutorial for DADA2 (v. 1.4) for the filtering process of my data. Right now, I'm currently stuck with the issue of transferring my filtered QIIME data (in the format of sequence_id.fastq.fasta) over into the the format that is suggested in the tutorial/manual of it being .fastq.gz.  

For context, I have been using the Juniata College qiime pipeline to process my data and is currently am on the current step of 1.4_fastq_filter.sh after merging the pairs. 

Would I have to run split_libraries_fastq.py in order to get my data to the appropriate format?

**Comment by nagasridhar** [comment]
I am assuming your filtered QIIME file, i.e., sequence_id.fastq.fasta is in the FASTA format. 

DADA2 requires your input file to be in FASTQ format. If you do not have a FASTQ file as an output after split_libraries_fastq.py, you will need to re-run it with the --store_qual_scores to get both the FASTA and QUAL file. You can then run the make_fastq.py with the .fna and .qual file to receive the FASTQ output file which can be used as an input file in DADA2.

**Comment by nice-scientist** [comment]
Hi @nagasridhar, thank you for your comment! 

When I receive the data, it is already demultiplexed. I ran it through Juniata College's pipeline that includes merging the pair reads, checking the stats of the reads and then filtering it. When I use DADA2's tutorial data, it already with the demultiplexed data along with "filtered" data (as noted in the filtered folder). I guess my confusion is from how to obtain the data filtered from QIIME.

**Comment by nice-scientist** [comment]
It seems that I have fixed it. I ran into a bunch of other errors. My assumption of the filtered.fastq.gz format was because that is what I thought the files needed to be in. Instead, I assumed that the files that I ran the plotQualityProfile script on would be the ones I would run the filterAndTrim script on. 

Thank you so much for the help!
