### ISSUE TITLE
Remove dada() hard-coded maximum quality score

### ISSUE THREAD

**Issue by igor25** [benjjneb/dada2#355]
Hi. I noticed that the core dada() function has a hard-coded maximum allowed quality score (dada2.R, lines 191-196):

```R
if(qmax > 45) {
    if(qmax > 62) {
      stop("derep$quals matrix has an invalid maximum Phred Quality Scores of ", qmax) 
    }
    warning("derep$quals matrix has Phred Quality Scores >45. For Illumina 1.8 or earlier, this is unexpected.")
}
 ```

Would it be possible to perhaps make this step optional, say by having an argument to dada() like qmaxThreshold=62 by default, but user-settable (or an option to disable it)?

Thank you!

**Comment by benjjneb** [comment]
...

Why do we even have a maximum quality score?

**Comment by benjjneb** [comment]
Bumped qmax to 250, which should handle any reasonable Q score, while avoiding any 1-byte indexing issues on the C side.

**Comment by rflance** [comment]
So, I am working in Version 1.6.0 and getting the error "derep$quals matrix has an invalid maximum Phred Quality Scores of 76." Are there some underlaying data issues that could result in such high scores? I know I keep getting alerts that "Not all sequences were the same length." Is there a fix or work around that will allow me to move on to the dada function? Big thanks if you can help out.

**Comment by benjjneb** [comment]
@rflance The devel-version of dada2 handles higher quality scores (up to 93). The easiest thing to do is probably to install that version and see if it solves your problem.

```
library(devtools)
devtools::install_github("benjjneb/dada2")
```
