### ISSUE TITLE
Judging Results from dada2

### ISSUE THREAD

**Issue by jrdohert** [benjjneb/dada2#356]
[ghouse_bac_tech2_track_seqs.xlsx](https://github.com/benjjneb/dada2/files/1431664/ghouse_bac_tech2_track_seqs.xlsx)

[gh_bac_quality_fwd.pdf](https://github.com/benjjneb/dada2/files/1431628/gh_bac_quality_fwd.pdf)
[Gh_bac_quality_rev.pdf](https://github.com/benjjneb/dada2/files/1431629/Gh_bac_quality_rev.pdf)

Hello

I am new to dada2 and I am confused as to how to interpret my output from the general workflow for paired-end reads in dada2. I have amplicon sequences obtained from a 2x300 paired-end run on the MiSeq platform. The overall run quality was good with about 90% of reads passing quality. The 2x300 run sequenced pooled 16S and ITS amplicons from foliar and rhizosphere microbiome samples.

Starting this technical replicate I had about 508,000 sequences, and after filterAndTrim I was left with about 9,700 sequences.  I used `truncLen=c(150,100)` and `maxEE=c(2,2)` I know a large fraction of my sequences are short, but this is typical for all my technical replicates. When increasing maxEE=c(4,6) there was only an additional 2 or 3 sequences kept per sample.

When having a large number of short reads, could the following command be appropriate for trying to allow paired-ends to join prior to length filtering? `out_minlen_100 <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(0,0), maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE, matchIDs=TRUE, minLen=100)`

I have included a spreadsheet of my tracked sequence reads and wanted to know if these patterns typical for running data through dada2? 

I do plan to pool my technical replicates together following the construction of seq tables. When combining seq tables from different sequencing runs of the same samples do the sample IDs need to be identical? Currently I have an additional item in the sample ID to separate them (i.e. 1-1-2A-1, 1-1-2A-2, 1-1-2A-3, where the final -1,-2,-3 refers to the sequencing run).

I am very used to QIIME1 and the number of sequences per sample I have gotten there, so these numbers are throwing me off and making me think there is something wrong in my process.

**Comment by benjjneb** [comment]
What I'm seeing from your quality profile plots is that most of your reads are very short, like <30nts short. As a result, all of those short reads are getting lost when you set `truncLen`, as reads that are short than `truncLen` are filtered out.

Can you say more about why your data looks like this? Was it prefiltered/pretrimmed somehow? I'm not sure how <30nt reads are going to merge in the end.

**Comment by jrdohert** [comment]
I am not sure why this is the case though. When I analyzed my data originally in QIIME1, I had joined reads through the join_paired_ends.py script and had only 10% of my total reads be <30nts. It could possibly be a result of improper processing prior to importing my sequences in dada2. To prepare my sequences I used a script that was given to me to separate the bacterial 16S amplicons from the fungal ITS amplicons and remove non-biological sequences (primers and adapters through cutadapt), and I ran the script separately for the fwd and rev reads. I have attached both scripts in case there is a glaring error I missed when modifying the script to have a script to run on fwd and rev sequence files.

When analyzing my data in QIIME1 I joined the paired ends, ran the extract reads script I was given (which uses cutadapt) on the joined sequences to separate the bacterial and fungal amplicons.

I imported a single fastq file from my QIIME1 analysis into dada2 to check the quality profile on the joined paired-ends I analyzed in QIIME1 and have attached it as well.  From what I can tell this is much better and what I would hope to see. If I renamed the joined paired-end files from my QIIME1 analysis to match the convention for dada2, could I utilize dada2 for the analysis? 

[gh_bac_joined_paired_ends_from_qiime1.pdf](https://github.com/benjjneb/dada2/files/1434396/gh_bac_joined_paired_ends_from_qiime1.pdf)


[read2_extract_reads.txt](https://github.com/benjjneb/dada2/files/1434357/read2_extract_reads.txt)
[read1_extract_reads.txt](https://github.com/benjjneb/dada2/files/1434358/read1_extract_reads.txt)

**Comment by jrdohert** [comment]
I believe I may have found my problem. I did not realize cutadapt could go through paired-end files simultaneously. I had it run through all the forward files, and then I changed the listed primers for the reverse and ran cutadapt on the reverse files. I am going to change my cutadapt usage to be more appropriate for paired-end reads and hope that fixes my problem. 

I was given the script and told it was ready to go, just place it in the appropriate directory and run with it. It worked perfectly for joined reads, but needing to change it for paired-end was something I (nor the person I was working with) had any experience with. So we did what we thought was appropriate. So much for that.

**Comment by jrdohert** [comment]
Running cutadapt with the correct options has solved my problem. I will likely try trimming the reverse reads around 100-125 at the `trimAndFilter` step.

Thanks, and i apologize for taking up time with a problem related to my ignorance and not your program. 

[bac_gh_proper_cutadapt.pdf](https://github.com/benjjneb/dada2/files/1434813/bac_gh_proper_cutadapt.pdf)

**Comment by benjjneb** [comment]
No worries, glad you fixed that problem!

If you run into more problems later, feel free to open a new issue.
