### ISSUE TITLE
Exporting OTU table #DADA2/phyloseq

### ISSUE THREAD

**Issue by IrshadUlHaq1** [benjjneb/dada2#357]
How do get the OTU table as an output file that I can open in an excel sheet? 

ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE), sample_data(samdf), tax_table(taxa))

phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 8555 taxa and 111 samples ]
sample_data() Sample Data:       [ 111 samples by 4 sample variables ]
tax_table()   Taxonomy Table:    [ 8555 taxa by 6 taxonomic ranks ]

**Comment by benjjneb** [comment]
The `write.csv` function is probably what you want, or the more flexible `write.table`. For example:

```
write.csv(seqtab.nochim, "path/to/seqtab.csv", col.names=NA)
write.csv(samdf, "path/to/samdf.csv", col.names=NA)
```

I'm not sure there is a way to do this with a phyloseq object directly, as a phyloseq object is not necessarily rectangular.
