### ISSUE TITLE
Feature Request: Concatenate Paired reads

### ISSUE THREAD

**Issue by zachcp** [benjjneb/dada2#36]
Hi Team Dada,

I like the approach of Dada2 and have followed through your tutorial. It looks very promising even if I don't have my head quite wrapped around the error/partition decision (its less intuitive than clustering).

I have a feature request that concerns paired-end reads that cannot be joined - say from 700bp amplicons on a 2x300 MiSeq run. This might not be a great decision on primer design but its data I have and i'd like to treat the concatenated pairs as a single sequence. It seems that I should be able to run the error model and then simply concatenate the reads instead of merging them. Are there any plans to include this feature? I would be happy to take a stab at it if you like.

thanks,
zach cp

**Comment by joey711** [comment]
I've seen this done before by inserting some number of "N"s in between each read direction. In this case, you'd only take reads that pass both directions, and then the final dereplication of denoised, concatenated reads would represent your "strains".

You'd have to be careful about taxonomy, most likely by performing taxonomic classification separately for each read direction, and then merging the consensus taxonomy, similar to how `merge_taxa` in phyloseq would handle this task (stopping before the highest-level disagreement).

Sounds good? If you send a PR we can evaluate/test it together.

Thanks for the feedback. I think this is not an uncommon use case, so I'd be in favor of adding it.

**Comment by benjjneb** [comment]
Feature added, use justConcatenate flag in mergePairs: cd0f615f1504a054cbba8c067471e68a671df9ba
