### ISSUE TITLE
Low ITS tax assignment

### ISSUE THREAD

**Issue by mvannuland** [benjjneb/dada2#361]
I've been (cautiously) running an ITS workflow and come across an issue I haven't seen addressed yet. When I assign taxonomy (using UNITE), only ~30% of SVs have phylum assigned, and very few have any assignments beyond that (essentially none have species-level assignments). I don't think the reads are in the opposite orientation to the UNITE database because nearly all SVs have Kingdom = Fungi. 

I've attached a small sample set to see if the issue can be replicated. Any help would be greatly appreciated!
[TestITS.zip](https://github.com/benjjneb/dada2/files/1443608/TestITS.zip)

**Comment by nagasridhar** [comment]
I ran your dataset and ran into similar issues as you mentioned. 

On further investigating your dataset, I blasted the dataset and assigned taxonomy using Silva database and I see they are being assigned as bacteria. It seems like the files you shared are 16s rRNA data, could you check and see if you are working with the right dataset.

**Comment by mvannuland** [comment]
There are supposedly both 16S and ITS reads in the samples. I made the test file with just the first 1000 lines of 3 samples, so I guess it could be possible those were all 16S reads? I've made another test file with the last 5000 lines to see if they also BLAST as bacteria. Will check on my end as well. 

[TestITS_2.zip](https://github.com/benjjneb/dada2/files/1444186/TestITS_2.zip)

**Comment by nagasridhar** [comment]
I tested the provided dataset and this seems like it only has 16S data. The sequence variants obtained through them get assigned as bacteria.

**Comment by mvannuland** [comment]
Same on my end. Not sure why they said both types of reads would be in these data...thanks for the double sanity check!
