### ISSUE TITLE
Processing 454 Sequencing Data

### ISSUE THREAD

**Issue by ireceptor** [benjjneb/dada2#363]
Hi,

I'm new to DADA2. Usually I analyze Illumina data with DADA, but recently I was given a 454 dataset to analyze. I only have a fasta file as sequencing data and a qual file as quality score file. I don't know where to start with DADA2 now. Should I go directly to dada function and skip the filter and dereplication? Thanks very much for the help.

**Comment by nagasridhar** [comment]
I am not sure of the dataset, but to get a good understanding of the sequence, I would create a FASTQ file from them, understand the dataset and then run through from the initial step in the DADA2 pipeline.

**Comment by benjjneb** [comment]
Agree with @nagasridhar that first step should be to create a fastq file out of the fasta and qual files, there are a few tools that can do that, e.g. QIIME1 and I think usearch as well.

After that, it's just the pipeline as usual, with small modifications for absolute best performance on 454 data: http://benjjneb.github.io/dada2/faq.html#can-i-use-dada2-with-my-454-or-ion-torrent-data

**Comment by ireceptor** [comment]
@nagasridhar @benjjneb Thanks very much for the help!
