### ISSUE TITLE
assignTaxonomy and Eukaryotes in Silva128_NR

### ISSUE THREAD

**Issue by handibles** [benjjneb/dada2#366]
Heyo devs,

   Thanks for the great library. 

   I'm assigning identities to 16S mi-seq reads which should have some coverage of Eukarya as predicted by in-silico PCR (SILVA). My assigned taxonomies (using the supplied Silva_128 reference set) include ~130 sequences (SVs!) assigned to Kingdom:Eukaryota but to no further taxon. Blasting these SVs only gives hits for ~20: mainly bacterial, but some mitochondrial from _m. musculus_, phage, an organism called 'human',  etc. The length for these sequences varies strongly: 200-400 bp (dataset median: 373) so I'm not very surprised by questionable assignments.

   From reading the [mothur processing steps](http://blog.mothur.org/2017/03/22/SILVA-v128-reference-files/) detailed on the [DADA2 reference set page](http://benjjneb.github.io/dada2/training.html), it sounds like Eukaryotes have been excluded from release S_128: is this correct? I see in a [previous issue](https://github.com/benjjneb/dada2/issues/70) that assignment to Eukarya was possible though this might have been because S_123 was used in that case.

   [1]   Am I correct in thinking that  the DADA formatted release has only Bact/Arch 16S sequences?

   [2]   If so, how and why did assignTaxonomy() attribute the above reads to Eukaryota?

   [3]   Similarly, how is membership of 'NA' decided, and what differentiates NA and Eukaryota?   (i.e. Archaea/Bacteria/Eukaryota/NA)

much thanks

**Comment by benjjneb** [comment]
1. Eukaryotes are included, although some Eukaryotic Silva sequences were lost as part of the screening process in producing the reference dataset.

2. See (1)

3. `NA` is decided when taxonomic assignment at that level is supported by less than `minBoot` bootstrap replicates across 100 bootstrap trials. `minBoot=50` by default. That is, the assignments of the bootstrap replicates did not agree often enough.

However, I'd strongly recommend trying again, but with the `tryRC=TRUE` option, that tells `assignTaxonomy` to also consider the reverse complement of the sequence for assignment. If your reads were in the opposite direction of the reference db, then it is common to see a bunch of Eukaryota NA NA NA... assignments, as I guess the Eukaryotes are the closest kingdom to a reverse complemented 16S gene.

**Comment by handibles** [comment]
Thanks benjjneb,
   I wouldn't have thought to reverse the compliment as it was only a handful of reads out of kilter!  However reassigning taxonomies with trRC=TRUE only reduces the Euk 'NA' set by 10 SVs. 
   Can you think of any other possible avenues I could try? This is quite a low-level query, so feel free to  attribute this to scatty reads/identities within the NA threshold but not otherwise assigned, and close the issue.
[Also, found the Eukaryotic assignments in the training set's fasta headers - must have checked the wrong fasta - thanks]

**Comment by benjjneb** [comment]
Other than `tryRC` I'm not sure what else you can try w/in the package. I would probably do what it sounds like you've done, BLAST them against the wider nt database and try to diagnose what to do next from what they are hitting (is it non-16S/18S sequence?)
