### ISSUE TITLE
Merging sequencinq from technical replicates?

### ISSUE THREAD

**Issue by mesnage** [benjjneb/dada2#367]
I have sequenced 189 samples on 3 MiSeq lanes in order to have a good number of reads. This gives me 3 technical replicates. I am wondering which strategy I should use for my analysis. Should I:

1/ Concatenate the fastq of the replicates, like "cat *R1_run1.fastq *R1_run2.fastq  *R1_run3.fastq"?
2/ Process them individually, then merge the sequence variant tables using mergeSequenceTable in order to work with only one sequence table per sample?
3/ Keep the 3 technical replicates separately during the whole analysis and work with 3 sequence tables per sample?

I will be happy to have more insights as it is not clear to me if mergeSequenceTable would apply here. Thanks in advance.

Robin.

**Comment by benjjneb** [comment]
You almost certainly should process the runs separately to account for the possibility of variation between the error profiles in different runs (the exception, if they are all run more-or-less consecutively on the same machine, you can get away with `cat`-ing them together).

As for 2/3, it depends on what kind of analysis you want to perform downstream. Your technical replicates give you a measurement of technical variability. 

Are you planning on explicitly accounting for technical variability from amplicon sequencing in your analysis? If so, keep the samples separate, although you could merge them into one total table. If not, then merging the samples together will at least reduce technical variability by effectively averaging over the technical replicates. See the `repeats` argument for details about how to control the behavior of `mergeSequenceTables` when the same sample names are found in separate tables.

**Comment by jrdohert** [comment]
I also have technical replicates, and upon trying to utilize the `repeats = "sum"` I still get the error `Duplicated samples names detected in the rownames`.  The full command is `st.all <- mergeSequenceTables(st1, st2, st3, repeats = "sum"`.  

I did get an output that appears to be all three sequence tables merged together, but still got the message as if `repeats = "error"` was passed.  Just wanted to check if this was similar to getting the warning that sequences were not the same length although DADA2 has been able to handle them.

**Comment by mesnage** [comment]
Thanks for your reply. I don't plan to take into account the technical variability, the different runs were performed on the same machine in the same week. I also checked and there is not much technical variability. I will thus merge my data using the repeats argument.
