### ISSUE TITLE
Check for chimeras separately between runs or after merging

### ISSUE THREAD

**Issue by adriaaula** [benjjneb/dada2#368]
For chimera verification, in the tutorial for big data the approach is to check for chimeras *after* merging the tables through `mergeSequenceTables`. In other tutorials like the examples by  [Suelshaq](https://github.com/SueIshaq/Examples-DADA2-Phyloseq/blob/master/DADA2_BigData_contigs_2runs_Ishaq_example.R) the removal is done separately and afterwards the merging is done. 

The chimera removal with the whole run improves the chimera detection? I would be interested by using the method of `consensus` in `removerBimeraDenovo`.

 
Thank you for your time :-)

**Comment by benjjneb** [comment]
I generally recommend performing chimera removal on the final table, because the `"consensus"` method gains from having more samples to inform the consensus classification.

**Comment by adriaaula** [comment]
Even if they don't come from the same origin//situation isn't it. 

Thank you for the fast answer.
