### ISSUE TITLE
Error when running fastqPairedFilter 

### ISSUE THREAD

**Issue by geralt1986** [benjjneb/dada2#369]
In response to: 
for(i in seq_along(fnFs)) {fastqPairedFilter(c(fnFs[[i]],fnRs[[i]]),c(filtFs[[i]],filtRs[[i]]),trimLeft = 10, truncLen = c(250,250),maxN = 0,maxEE = 2,truncQ = 2,compress = TRUE)}

Error in validObject(.Object) : 
  invalid class “SRFilterResult” object: superclass "Mnumeric" not defined in the environment of the object's class

I made the same script, with same samples and all identical in a fellow PC and it works.

**Comment by benjjneb** [comment]
Can you report the output of the following:

```
packageVersion("dada2")
R.version
```

Could you also try upgrading your Bioconductor installation to the most recent version (and report your Bioconductor version from first command below):

```
source("https://bioconductor.org/biocLite.R")
biocLite()
biocLite("dada2")
```

I believe if you update Bioconductor to the current version this error should go away.

**Comment by geralt1986** [comment]
Hi,
Version of package dada2 is 1.2.2
And R version is R version 3.3.2

Regarding to try to install with biocLite, i was made with it. And now I remove and reinstall package with your commands and try again to do this script and report de same error.

**Comment by benjjneb** [comment]
The 1.2.2 version is a year old now, were you able to update to 1.6 (the current release) or at least 1.4 (the last release)?

You should also try specifically updating the ShortRead package to its current version.

**Comment by geralt1986** [comment]
I had 1.6 version and had the same error. Then I used BiocLite to install it as you propose, and 1.2.2 is the version that auto-install. I re-installed now the 1.6 version and it continue failing. And I try to do the script only with dada2 active, for if some incompatibility with other package give the mistake, but failure again

**Comment by geralt1986** [comment]
Ok, seems, that the problem was the R version. I update to the latest one and seems to work fine. Thanks anyway.

**Comment by benjjneb** [comment]
Great. Yeah that error has popped up a time or two before and always appears to be due to old versions of R or some other package.
