### ISSUE TITLE
Issues with filterandTrim

### ISSUE THREAD

**Issue by mentorwan** [benjjneb/dada2#370]
Hi,

Hope this is not a duplicate message.
My DADA2 version is 1.6.0. I have problem to run filterandTrim with option multithread=TRUE. 

If multithread is TRUE, I have the following errors appearing running in the cluster.
Error in names(answer) <- names1 :
  'names' attribute [191] must be the same length as the vector [119]
It seems this is related to issue https://github.com/benjjneb/dada2/issues/273

I also have the following error even multithread is FALSE.

Error in filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen = c(240, 200),  :
  These are the errors (up to 5) encountered in individual cores...
Error : UserArgumentMismatch
  file './filtered/DZ35306_0094_F_filt.fastq.gz' exists, but mode is not 'a'
Do you know what are issues?

Here are logs:
Read in 21390 paired-sequences, output 13657 (63.8%) filtered paired-sequences.
Overwriting file:./filtered/VY_2207_0002_F_filt.fastq.gz
Overwriting file:./filtered/VY_2207_0002_R_filt.fastq.gz
Read in 61813 paired-sequences, output 40461 (65.5%) filtered paired-sequences.
Read in 103848 paired-sequences, output 65650 (63.2%) filtered paired-sequences.
Error: UserArgumentMismatch
  file './filtered/VY_0159_0002_F_filt.fastq.gz' exists, but mode is not 'a'
Execution halted

It only happens when it runs on cluster. For my local machine, I have not seen this error.

Thanks,
mentorwan

**Comment by mentorwan** [comment]
Seems to be our cluster threading issue. Not DADA2 issue. Still checking.

**Comment by mentorwan** [comment]
I do have a different question related to DADA2 results. We have generated a large number Sequence Variant by DADA2 (more than 100000). Looking into each sequence and found majority SVs appear less than 1000 times (more than 90000). 

I blasted some of them in low number of SVs. For example, sequence AGAGTTTGATCCTGGCTCAGATTGAACGCTGGCGGCATGCTTTACACATGCAAGTCGAACGGCAGCACAGAGAAGCTTGCTTCTTGGGTGGCGAGTGGCGAACGGGTGAGTAATATATCGGAACGTACCGAGTAATGGGGGATAACTAATCGAAAGATTAGCTAATACCGCATATTCTCTGAGGAGGAAAGCAGGGGACCTTCGGGCCTTGCGTTATTCGAGCGGCCGATATCTGATTAGCTAGTTGGTGGGGTAAAGGCCTACCAAGGCGACGATCAGTAGCGGGTCTGAGAGGATGATCCGCCACACTGGGACTGAGACACGGCCCAGACTCCTACGGAAGGCAGCAGTGGGGAATTTTGGACAATGGGCGCAAGCCTGATCCAGCCATGCCGCGTGTCTGAAGAAGGCCTTCGGGTTGTAAAGGACTTTTGTCAGGGAAGAAAAGGCTGTTGCTAATATCGACAGCTGATGACGGTACCTGAAGAATAAGCACCGGCTAACTACGTGCCAGCAGCCGCGGTAAT

appeared 267 times.  Blast only show 99% identity with one base pair difference. I also checked related sequence with 100% identify is also appearing 190640 times. 

Do you have any suggestions on how to deal with SVs with low number of reads counts? Filtering them and keeping them or clustering together? Thanks a lot for great tool.

**Comment by benjjneb** [comment]
First, you really should remove your primers sequences. It looks like you have the V1V3 primers (27F/534R) on your reads. Those aren't biological nucleotides, and should be removed.

Second, independent filtering based on prevalence of frequency thresholds is a valid thing to do prior to most subsequent analysis. Not if your trying to estimate richness (but you pretty much can't validly estimate richness form this kind of data anyway) but for most other analyses. In large datasets I will often filter at a prevalence thresholds of 2 or 3 samples, and a frequency threshold that cuts off the extreme tail.

**Comment by mentorwan** [comment]
Thanks Ben for reply. After testing on our samples,I have general questions about filterandTrim. For example in 2*250 pair ends, I use 240 as trimming parameters for both forward and reverse reads. The results are different from forward 240 and reverse 200. Sometimes I don't know which results are better since you mention that you can always filter using prevalence threshold of 2 samples after generating feature table.

How about sequence feature unique to only one sample? I found some of features have a lot of read counts (>100). Do you suggest to remove it or keep it?  When I use Blast to those features with low number of read count (<100). I got 100% coverage and 99% identity. Only one base pair mismatch. Do you think it is novel or sequence noise? Is Blast results a good test for quality in sequence features generated?

Sorry for so many questions. Thanks a lot of help.

**Comment by benjjneb** [comment]
Typically you want to trim off post-quality-crash read tails, while maintaining overlap between the reads.

There isn't one answer for filtering that is the right one for all datasets. I typically do filter out ASVs found only in a single sample, because they aren't important for my downstream analysis, but you should consider what your subsequent analysis should be.

BLAST is useful, but databases are incomplete, so it's not going to give you an exact answer no what is real or not for all sequences.

**Comment by mentorwan** [comment]
Thanks for insights. How confident for DADA2 for reporting sequence with one base off? Is that case by case determination? I understand Blast is incomplete. I check multiple ASVs showing only in one sample. There are several one base off situations.  

I checked that filtering using 240(f) and 200(r) did generate more ASVs than 240(f) and 240(r) in my case. But just like you said, it might not matter for downstream analysis. Since the differences are in low quality read tails.  Thanks.

**Comment by benjjneb** [comment]
> Thanks for insights. How confident for DADA2 for reporting sequence with one base off? Is that case by case determination? I understand Blast is incomplete. I check multiple ASVs showing only in one sample. There are several one base off situations.

Our benchmarking suggests that, as a rule, the results are quite accurate including ASVs that might be one-off a reference database. That said, no method is perfect, nor is DADA2, so FPs can happen.

My suggestion would be to not worry about trying to dive into every individual ASV at the start. If you find some ASV that is picked out by your later analysis, you can go back and double-/triple-check that particular ASV to convince yourself its real.
