### ISSUE TITLE
Few paired ends merging

### ISSUE THREAD

**Issue by jrdohert** [benjjneb/dada2#371]
Hi
I am working with some bacterial 16S V3-V4 amplicons sequenced on a 2x300 paired end MiSeq run. I am having issues with a loss of sequences after filtering and a minimal amount of remaining sequences merging after pairing.  I have attached images of my quality profiles for F and R reads as well as a table tracking reads through the pipeline.  

The primers I used were the Ba9/Ba515 pair, which from what I have gathered results in an amplicon that would be around 525 bp. Using the default parameters of `mergePairs` I would need a total length of 545bp for successful merging, correct? 
 
I have a feeling there are 2 issues and want to have my sanity checked.

1. Loss of sequences at `filterAndTrim` is due to sequences being shorter than my minimum length I specified. My command I used was `out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, minLen=c(200,200), maxN=0, maxEE=c(10,10), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE, matchIDs=TRUE)` I have tried several iterations of this command changing `truncQ=0` to see if it was a quality issue for the loss of reads, it was not. Increasing and decreasing `maxEE` provided minor variations in either direction depending on whether I loosened or tightened it. Dropping `minLen` to 150 each provided negligible increases. I chose `minLen` so I could keep all the longest sequences while discarding short sequences that would not merge down the line anyway.

2. Minimal merging is due to lack of length. I thought I remember reading in a different post on here that 2x300 is not always that good (and of course I try to find it again and it eludes me)? Changing the overlap to 8 bp only added a few more successful merges.

If my ideas are correct then I believe my problem is the primer pair is a bit ambitious for a 2x300 sequencing run. I was given the primer pair by my committee and was told to use them. Is it possible to utilize just the forward reads (if so would I just remove the reverse option from all commands and skip the merging step)? I thought I saw that recommendation on here as well, and yet again I cannot find the post where I saw that. I know that would severely limit my ability to assign any semblance of taxonomy with how short the reads would be. Or would `justConcatenate` be a viable option?

[Gh_bac_tech1_fwd_quality.pdf](https://github.com/benjjneb/dada2/files/1476870/Gh_bac_tech1_fwd_quality.pdf)
[Gh_bac_tech1_rev_quality.pdf](https://github.com/benjjneb/dada2/files/1476871/Gh_bac_tech1_rev_quality.pdf)

[gh_bac_tech1_read_tracking.xlsx](https://github.com/benjjneb/dada2/files/1476873/gh_bac_tech1_read_tracking.xlsx)

**Comment by benjjneb** [comment]
It sounds like you have a pretty good handle on things.

> Using the default parameters of mergePairs I would need a total length of 545bp for successful merging, correct?
> If my ideas are correct then I believe my problem is the primer pair is a bit ambitious for a 2x300 sequencing run.

Yes on both counts. Looking at your quality profiles, you have about 250nts of good quality forward sequences, and on the reverse reads around 200nts before quality crashes. But that's not enough to  merge. So you either have to keep a lot of very low quality bases, which hurts SV inference, or use just the forward reads. This is the problem amplicons over 450nts, it is the rare sequencing center that gets 2x300 nts of all quality bases!

Given your data, I would probably just use the forward reads. You can truncate them at 250-275nts. You will lose much less taxonomic resolution than you might be imagining, as resolution does not double when length doubles, and my guess is that your analysis will still be quite successful. But there will be some groups, especially those that vary more in the V3 region than the V1 region, you will lose resolution on.

**Comment by jrdohert** [comment]
Thank you very much @benjjneb!! 

Glad to know that my analysis will no be completely ruined by only using the forward reads.
