### ISSUE TITLE
inflateErr :: usage question

### ISSUE THREAD

**Issue by AdvancedBiomeasurementsResearchGroup** [benjjneb/dada2#372]
Hi,

Happy user of dada2 here, so I have a question rather than an issue.

My question is as follows: at what step is the function "inflateErr" used, or needs to be used. Following for example the workflow in tutorial DADA2 Pipeline Tutorial (1.6), this function seems not used. Would it be possible to clarify this, probably basic, question?

As another, and more general question, I was wondering how dada2 identifies correct sequences to learn errors. I guess more abundant sequences are assumed to be correct but is there any cut-off for that? I may be misunderstanding the details of internals of dada2 in that respect though.

Thank you in advance for your time and developing this great tool.

Dieter.

**Comment by benjjneb** [comment]
`inflateErr` isn't really needed for anything anymore. It used to be used to initialize the learning of error rates, when you want to start w/ error rates that are too high, but now we just automatically determined and initialize with the maximum possible error rates instead. It still has niche uses for conservative ASV inference over multiple runs, but not something you'll normally use.

A core assumption in the DADA2 agorithm is that the error-free sequences will be repeatedly seen more than any other specific error*. Thus more abundant sequences are assumed to be real, and other sequences with abundance low enough to be consistent with errors are corrected to that more abundance sequence.

*: Note, this is not the same as saying that the error-free sequence is more abundant than errors in total, but that total errors will be spread out amongst many possible error-containing sequences, and no specific one will be more abundant than the error-free sequences.

**Comment by AdvancedBiomeasurementsResearchGroup** [comment]
Great, thank you very much for your prompt and clarifying response.
