### ISSUE TITLE
Error with low read samples during the filterAndTrim step

### ISSUE THREAD

**Issue by limey-bean** [benjjneb/dada2#375]
I run dada2 in an automated pipeline, and I follow the steps outlined in the tutorial at https://benjjneb.github.io/dada2/tutorial.html.  Recently though I noticed something strange with the new version (1.7) that I did not notice with the previous versions (1.4 and 1.6).  

I include negative controls, and samples with low numbers of reads in my dada2 analyses and I have started to get the following errors after the following commands:

>filt_path <- file.path(path, "filtered") # Place filtered files in filtered/ subdirectory
>filtFs <- file.path(filt_path, paste0(sample.names, "_F_filt.fastq.gz"))
>filtRs <- file.path(filt_path, paste0(sample.names, "_R_filt.fastq.gz"))

Creating output directory: /paired/12S/filtered
The filter removed all reads: /paired/12S/filtered/12S_PPM6mo-F26_F_filt.fastq.gz and /paired/12S/filtered/12S_PPM6mo-F26_R_filt.fastq.gz not written.
The filter removed all reads: /paired/12S/filtered/12S_PPM6mo-F52_F_filt.fastq.gz and /paired/12S/filtered/12S_PPM6mo-F52_R_filt.fastq.gz not written.
Some input samples had no reads pass the filter.
Warning messages:
1: In file.remove(fout[[1]]) :
  cannot remove file '/paired/12S/filtered/12S_PPM6mo-F52_F_filt.fastq.gz', reason 'No such file or directory'
2: In file.remove(fout[[2]]) :
  cannot remove file '/paired/12S/filtered/12S_PPM6mo-F52_R_filt.fastq.gz', reason 'No such file or directory'

>out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, minLen = 70,
                     maxN=0, maxEE=c(2,2), truncQ=0, rm.phix=TRUE,
                     compress=F,matchIDs=TRUE, multithread=F) 

Dereplicating sequence entries in Fastq file: /paired/12S/filtered/12S_11A1_F_filt.fastq.gz
Encountered 20 unique sequences from 20 total sequences read.
Dereplicating sequence entries in Fastq file: /paired/12S/filtered/12S_PPEXT_F_filt.fastq.gz
Encountered 2 unique sequences from 2 total sequences read.
...
...
... for many samples
Dereplicating sequence entries in Fastq file: /paired/12S/filtered/12S_PPM6mo-F26_F_filt.fastq.gz
Error in open.connection(con, "rb") : cannot open the connection
Calls: derepFastq ... FastqStreamer -> FastqStreamer -> open -> open.connection
In addition: Warning message:
In open.connection(con, "rb") :
  cannot open file '/paired/12S/filtered/12S_PPM6mo-F26_F_filt.fastq.gz': No such file or directory
Execution halted

At this point the script aborts.
Do you have any ideas to work around this?  Is this a dada2 issue or an issue with my data?

Thank you for your help!
Emily

**Comment by benjjneb** [comment]
Hi Emily,
I think you are just seeing something which normally occurs when you have very low read-number samples mixed in (like negative controls) -- in a couple of samples no reads pass the filter, raising the warning you saw.

This turns into an error when you try to dereplicate those missing filtered files later. The workaround here is to just check if each filtered file exists, and then only perform further processing fort the ones that do exist:

```{r}
exists <- file.exists (filtFs) & file.exists(filtRs)
filtFs <- filtFs[exists]
filtRs <- filtRs[exists]
```

**Comment by limey-bean** [comment]
Fantastic!  Thank you very much!

**Comment by rachaelantwis** [comment]
Hi,

thanks for this. This has solved the same problem I was having, however now I get the following error:

> names(derepFs) <- sample.names
Error in names(derepFs) <- sample.names : 
  'names' attribute [934] must be the same length as the vector [925]

The problem being the sample.names I assigned earlier was for all the samples, but now some have been stripped out. Do you know how I can reassign sample.names using the new filtFs object, or strip out samples that are missing?

Many thanks in advance

**Comment by dswan** [comment]
`names(derepFs) <- sample.names[exists]`

I think, see solution in #488

**Comment by rachaelantwis** [comment]
Ah thanks! I actually also found this from the big data pipeline that might also work:

```{r}
sample.names <- sapply(strsplit(basename(filtFs), "_"), `[`, 1)
```

**Comment by rachaelantwis** [comment]
Your solution is tidier so I'll go with that - many thanks
