### ISSUE TITLE
dada2-additional material_foundation

### ISSUE THREAD

**Issue by oresendis** [benjjneb/dada2#376]
Is there any place to get additional material to understand in detail the foundation of the algorithm, especially the statistical mid-steps before revealing the community profile?

**Comment by joey711** [comment]
Do you mean beyond the two journal articles published on the dada algorithm?

**Comment by oresendis** [comment]
yes.

**Comment by joey711** [comment]
Can you be more specific about what you are asking for help to understand?

**Comment by oresendis** [comment]
I have found this nice talk. I will write you if I need specific help, thank you

https://youtu.be/yLP3BIu2zBY
