### ISSUE TITLE
Variable merge rates

### ISSUE THREAD

**Issue by adityabandla** [benjjneb/dada2#378]
Hi Benjamin

I am working with standard Illumina MiSeq 300bp paired-end amplicon data. The merge rates after denoising seems to span a broad spectrum, right from 96% all the way to 36% for some samples. 

If 96% of reads in some samples successfully get merged, I dont think read length trimming is an issue. I also played around with the maxEE parameters for the forward and reverse, but the same trend plays out, so I am bit confused as to whats going on

Regards,
Aditya

**Comment by benjjneb** [comment]
Are these all the same amplicon region (e.g. 16S v3v4)?

We just checked in updated merging defaults into the devel branch and I wonder if they might help here. Can you install the current devel version from github, and try merging again?

**Comment by adityabandla** [comment]
Yes, they all span the v4v5 region

I will give it a try with the updated package and post the results here

**Comment by adityabandla** [comment]
Hi Benjamin

I just realized that I was already using dada2 from the devel branch. Just to double check, I reinstalled it again from the devel branch, ran it and ended up with the exact same results.

Regards,
Aditya

**Comment by benjjneb** [comment]
Could you post a bit more info, in particular, what do the quality scores look like (i.e. `plotQualityProfile`), what were your trimming params, and what are your read depths?

If you are willing to share fastq files of (perhaps a subset) of reads from one high-merging and one low-merging sample, I would take a look, as in general I don't think your merge fraction should vary that much.

**Comment by adityabandla** [comment]
I have a total of 120 samples. Median read depth is 35,752 (Min: 248, Max: 67568). MaxEE was 3 and 4 for forward and reverse reads respectively. Both reads were trimmed to 225 bp using truncLen

Can I perhaps email a link to these files?

**Comment by benjjneb** [comment]
Sure. benjamin DOT j DOT callahan AT gmail DOT com

Also, what environment are you sampling?

**Comment by adityabandla** [comment]
Just sent the files over. These are from sediments

**Comment by jnesme** [comment]
If your sequencing center is incorporating variable length heterogeneity spacer typically from 3 to 10 bases + primer. This is used to reduce phix % per run and still get correct signal to noise ratio for first cycles. When stripped together with primers, you can easily drop below your minOverlap set threshold because well, long or short adapter, the same number of cycles are performed on the machine. Hence for specific samples (depending on indexing pairs) the number of "usable" sequence can be shorter by as much as 14bp (2x maxDiff between heterogeneity adapter length in my specific case with 3 to 10 bases long heterogeneity adapters...).

I hope what I said make sense and it may not but your situation at all but I typically end up in your case: I have a large distribution of merged pairs % for samples from the same environment, in the same run, only differing by index pairs 'cause we're greedy and want to sequence V3V4 with 500 cycles...

**Comment by adityabandla** [comment]
Thanks Joseph! I have taken note of this point and it completely makes sense. I would assume though that this spacer gets trimmed when we strip off the primers. But I end with the merging issue, with overlap lengths (calculated) ranging from 120bp to 70bp, i.e. I varied the trimming lengths just to see if it made a difference

**Comment by benjjneb** [comment]
I took a look at the two samples, and I didn't see anything obviously wrong. The first sample has about 58% merging, and the second one 96%. But the diagnostics in sample one look fine (e.g. `$birth_qave`, `$birth_ham`) and the results of assigning taxonomy on the successful mergers look reasonable. I didn't find phiX or low-complexity contaminants.

I'm open to more ideas, but right now I can't offer an explanation. The output seems to look OK though, at least at the very rough level of assigning taxonomy.

**Comment by adityabandla** [comment]
Is it advisable to relax the number of mismatches while merging?

**Comment by adityabandla** [comment]
Not sure if something weird is going on with the mergePairs function. I just digged a bit deeper. In this case, I had a look at the sample which had a merge rate of 58%. When I retained the reads that were rejected `returnRejects = TRUE`, there was no variant which had nmismatch >1. If I understood this correctly, it means none of the rejected reads have more than one mismatch. If thats the case, not sure why relaxing maxMismatch = 1 is not increasing the number of merged reads by the extent one would expect

**Comment by adityabandla** [comment]
I wonder if the merge issue crops in samples where there is a mismatch in the order of paired-reads.  This can arise from the trimming steps. I could see that there is a mergePairsByID function, however seems like its not usable at the moment. Is there anyway that I could give this a try?

**Comment by adityabandla** [comment]
Update: Just did a sanity check by merging reads using bbmerge, without quality filtering, setting mismatches = 0. For both samples, 80% reads merged

**Comment by adityabandla** [comment]
I tried different ways of troubleshooting this issue, including using mergePairsByID and examining sequences which failed to merge. The only plausible explanation which I can think of is that these samples possibly had a high rate of PCR chimeras. I am out of ideas as of now

**Comment by cresil** [comment]
Are you sure your meeting the minimum overlap requirement. There is
biological variation in the length of the amplicons.
Our v3v4 range from 400 to 430 (excluding primers), so we need at least 450
total size to cover all and meet the minimum 20 overlap requirement.
Some of your V45 amplicons (including primers?) might just fail to meet the
overlap (you've trimmed at 2x225).

What was the length distribution of the bbmerge output? Those should be
less than 430.
You could relax your minOverlap = 10 while merging and see if things
improve.

**Comment by adityabandla** [comment]
I dont think its an issue with the overlap length. I just gave minOverlap=10 a try, but makes no difference.

For the sample with a merge rate of 56% (dada2), the corresponding merge rate with bbmerge (defaults) is 78%, length of the 10th percentile of merged reads is 370bp, which is around the expected number

**Comment by cresil** [comment]
could you check if your most abundant asv is being merged?

sapply(mergers, function(x) x$accept[x$reverse==1 & x$forward==1])

**Comment by adityabandla** [comment]
The most abundant ASV happens to be forward=2 and reverse=1, the second most abundant one corresponds to forward=1, reverse=1, but seems to be rejected as the nmatch=1

**Comment by adityabandla** [comment]
On a related note, I could also observe that multiple forward reads with the same index (say forward$1) seem to merge with different reverse reads resulting in different valid ASVs, which is quite confusing
