### ISSUE TITLE
plotQualityProfile error 

### ISSUE THREAD

**Issue by gputzel** [benjjneb/dada2#380]
Running `plotQualityProfile` (with any FASTQ file I have tried, compressed or not) gives me the following error:

```
Error in apply(strip_mat, 1, max_height) : 
  dim(X) must have a positive length
```

For example, I get this when I run 

`plotQualityProfile('F3D0_S188_L001_R1_001.fastq.gz')`

I get this error with `dada2` versions 1.4 and 1.6, but not with version 1.2.

I'm running R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree" on x86_64-apple-darwin15.6.0 (64-bit). My OS version is 10.11.6 (El Capitan).

**Comment by benjjneb** [comment]
My guess is that is a `ggplot2` error, can you try updating to the current version of the `ggplot2` package? If that doesn't work, can you report the output from `packageVersion("ggplot2")`?

**Comment by gputzel** [comment]
I have version 2.2.1.9000 of `ggplot2`, which I believe is the latest. On the other hand, I just upgraded my Mac OS X from El Capitan to High Sierra and now `plotQualityProfile` works fine.
