### ISSUE TITLE
SRA IDs for data used in manuscript

### ISSUE THREAD

**Issue by audy** [benjjneb/dada2#381]
Is the data used in the manuscript on NCBI SRA (sorry, I can't check right now because paywall) or on an FTP somewhere? I am comparing to some in-house libraries and am trying to eliminate some sources of variation.

**Comment by benjjneb** [comment]
Which data are you looking for exactly? The sequencing data for the mock communities in the DADA2 manuscript? Or something else?

**Comment by audy** [comment]
Oops. I wasn't clear. I meant the fastq files for the mock communities

**Comment by audy** [comment]
I just realized I had a copy of the paper on my desk and that the data are here: https://purl.stanford.edu/mh194vj6733. Derp 🙄

**Comment by audy** [comment]
I'm looking for the raw reads for the mock communities.

**Comment by benjjneb** [comment]
From the Methods:

> The Balanced data set was downloaded from http://www.ebi.ac.uk/ena/data/view/PRJEB6244, and its construction was described in ref. 16, where it is identified as data set DS 35.

> The HMP data set was downloaded from http://www.mothur.org/MiSeqDevelopmentData.html, and its construction was described in ref. 17, where it is identified as the MOCK1 sample in run 130403.

> The Extreme data set is available under SRA accession number SRX1478507.

**Comment by audy** [comment]
Thanks @benjjneb!
