### ISSUE TITLE
SILVA_132 taxonomy update?

### ISSUE THREAD

**Issue by GeoMicroSoares** [benjjneb/dada2#382]
Hello there,

SILVA_132 was [just released](https://www.arb-silva.de/documentation/release-132/).

Just wondering what people's opinions are with regards to the huge taxonomic changes mostly within Proteobacteria.

@joey711 @benjjneb are you currently thinking of implementing the update in the DADA2 pipeline?

Cheers,
André

**Comment by benjjneb** [comment]
I'm agnostic to the taxonomy changes, as that's not my area of expertise. If this is a major change though, we should probably look into making a suitable v132 reference fasta file available.

**Comment by ianpgm** [comment]
We could definitely use an update Silva 132 database so I'll second that - we're doing work with candidate genera Electrothrix and Electronema, and with the archaeal phylum Asgardaeota, which appear for the first time or are significantly enhances in release 132. I haven't heard about the changes within Proteobacteria, but I'd be curious to know what the changes are.

**Comment by adityabandla** [comment]
@benjjneb On a related note, why are SILVA taxonomy training sets for dada2 being generated from the NR99 database, rather than the unclustered version?

**Comment by benjjneb** [comment]
> On a related note, why are SILVA taxonomy training sets for dada2 being generated from the NR99 database, rather than the unclustered version?

This is for memory reasons, and because the naive Bayesian classifier method can give inappropriate classification confidences when certain taxa are highly over-represented in the database, which is remedied by clustering at 99%.

The silva file for `assignSpecies`, which uses exact matching not the nBc method, uses the full dataset.

**Comment by ycl6** [comment]
What are the issues taken into consideration when generating a training set as oppose to a straightforward file format conversion of the sequences retrived from Silva?

If I am to use the SSURef Nr99 alignment file (SSURef_Nr99_tax_silva_full_align_trunc.fasta.gz) and taxmap file downloaded from Silva website to generate a sequence file compatible with dada2, will this be appropriate for taxonomy assignment?

**Comment by benjjneb** [comment]
@ycl6 

In our online docs we cover a bit of this: https://benjjneb.github.io/dada2/training.html#formatting-custom-databases

The specific R code we used for converting the mothur-formatted Silva training files into dada2 format is in the taxonomy.R file, and there is a link there to the pre-processing done on the mothur side as well.

**Comment by ianpgm** [comment]
I ended up writing [a script to format the Silva-produced FASTA files for dada2](https://github.com/ianpgm/silva_to_dada2) and using it on version 132 of the Silva database.

Reflecting on this, I'm not sure that using the mothur-formatted Silva database as a starting point for a dada2 database is necessary, or even desirable. Mothur uses its database for more than just taxonomic classification - it also uses it to align and screen sequences earlier in the pipeline, so short or poorly aligned sequences are [removed from the database](http://blog.mothur.org/2017/03/22/SILVA-v128-reference-files/) to make for a better alignment. This means that a lot of shorter sequences, especially archaeal sequences, are removed, when these would still be perfectly useful for classification in dada2.

It would be interesting to hear other thoughts about this approach - is just taking the raw Silva database, truncating the excessive taxonomic levels (mostly amongst the eukaryotes), and then formatting for dada2 enough, or should there be further filtering steps we should be considering?

**Comment by benjjneb** [comment]
> Reflecting on this, I'm not sure that using the mothur-formatted Silva database as a starting point for a dada2 database is necessary, or even desirable. Mothur uses its database for more than just taxonomic classification - it also uses it to align and screen sequences earlier in the pipeline, so short or poorly aligned sequences are removed from the database to make for a better alignment. This means that a lot of shorter sequences, especially archaeal sequences, are removed, when these would still be perfectly useful for classification in dada2.

That seems right to me!

> It would be interesting to hear other thoughts about this approach - is just taking the raw Silva database, truncating the excessive taxonomic levels (mostly amongst the eukaryotes), and then formatting for dada2 enough, or should there be further filtering steps we should be considering?

There are a few technical formatting things that come to mind. 

1) Do the first six taxonomic levels here correspond to Kingdom...Genus? I think they might not, especially in Eukaryotes, where they often add in intermediate levels (e.g. super-/sub-family) that require an auxiliary taxonomic definition file to parse.

2) For the official training fastas we've adopted a convention of using "Escherichia/Shigella" as the genus name across databases, whereas the previous Silva release used "Escherichia-Shigella"

3) Are there any "uncultured" taxonomic levels? Previous Silva releases had that in some entries, whereas for `assignTaxonomy` it is better to simply have nothing.

Other than that, it would be nice to have an R script for reformatting silva132 to include in the package (as we currently do as dada2:::makeTaxonomyFasta_Silva for v128), but that's something I could adapt from the Julia code.

**Comment by ianpgm** [comment]
> Do the first six taxonomic levels here correspond to Kingdom...Genus? I think they might not, especially in Eukaryotes, where they often add in intermediate levels (e.g. super-/sub-family) that require an auxiliary taxonomic definition file to parse.

No - eukaryotes definitely cause issues here. That's OK for my purposes (only using bacteria or archaea-specific primers) but for other users using eukaryotic or universal primers that wouldn't work. I'm sure some people who do more work with eukaryotes must have some ideas for the best way of dealing with this issue.

> For the official training fastas we've adopted a convention of using "Escherichia/Shigella" as the genus name across databases, whereas the previous Silva release used "Escherichia-Shigella"

Silva 132 still lists these as "Escherichia-Shigella", so I've added some code to my script to fix that.

>Are there any "uncultured" taxonomic levels? Previous Silva releases had that in some entries, whereas for assignTaxonomy it is better to simply have nothing.

Yes, there's a whole lot of "uncultured", "uncultured_bacterium", and "uncultured_archaeon". I've added an algorithm to the script that starts at the rightmost taxon and clips off any taxa that start with the word "uncultured" until it reaches a taxon that doesn't start with "uncultured". I think this should do the trick...

**Comment by ycl6** [comment]
mothur has Silva Release 132 available:
https://www.mothur.org/wiki/Silva_reference_files#Release_132

**Comment by benjjneb** [comment]
Silva 132 training fastas now available for `assignTaxonomy` and `assignSpecies`: https://zenodo.org/record/1172783#.WodChxPwZBw

**Comment by GeoMicroSoares** [comment]
First thing I can say is that this update makes the whole thing a lot more computationally strenuous.
addSpecies() crashed the R session after a while on a dataset with ~70k SVs, 120 samples.

**Comment by benjjneb** [comment]
@GeoMicroSoares 

Copied your comment over to the thread on the memory scaling of our taxonomy methods: https://github.com/benjjneb/dada2/issues/239

**Comment by sudeep71** [comment]
Hi,

Where can i get the silva132 formatted files?
the link below does not work for me.
https://zenodo.org/record/1172783#.WodChxPwZBw

**Comment by benjjneb** [comment]
@sudeep71 All of Zenodo is down at the moment. You can see their progress on getting back up and running at their main site: https://zenodo.org/

I'd probably just try back tomorrow.
