### ISSUE TITLE
Subsetting ASV Table 

### ISSUE THREAD

**Issue by kholt1992** [benjjneb/dada2#383]
Hi, I want to know if there is a way to subset my ASV table into two groups. I have 10 samples, and I want to find all sequences present at least twice in 5 of my samples (group x in mapping file), and not found in any of the other 5 samples (group y in mapping file). There may also be a way to do this in phyloseq by subsetting the phyloseq object by the two conditions I am investigating, but I have not figured out how to do this. I am interested in finding unique taxa shared across specific groups in my mapping file. 

Thank you for the help!

**Comment by kholt1992** [comment]
To clarify, I want to find sequences **present in at least 2 out of the 5 samples** (group x), and not at all in other 5 samples (group y)

**Comment by benjjneb** [comment]
You can use base R operations on data.frames and matrices to do anything you want. Eg.

```
patab <- seqtab>0  # presence/absence
prevalence.C1 <- colSums(patab[samdf$Condition == "C1",])
prevalence.C2 <- colSums(patab[samdf$Condition == "C2",])
which(prevalence.C1 >= 2 & prevalence.C2 == 0)
```

**Comment by joey711** [comment]
These days I think dplyr is a preferred tool for subsetting:

https://stackoverflow.com/questions/24319747/how-to-use-or-and-in-dplyr-to-subset-a-data-frame

I'm also a big fan of data.table:
https://github.com/Rdatatable/data.table/wiki
but it has a bit steeper learning curve, and differs from several common conventions in R.

**Comment by benjjneb** [comment]
Those wouldn't be sample names, those are the sequences that appear >=twice in C1 and not at all in C2.

You can get them using R subsetting commands. i.e. `getSequences(seqtab)[which(prevalence.C1 >= 2 & prevalence.C2 == 0)]`
