### ISSUE TITLE
detect SV out of frame

### ISSUE THREAD

**Issue by matbarret** [benjjneb/dada2#385]
Hi,
We are currently using a portion of a protein-coding gene (gyrB) for analysing our bacterial assemblages. Since this is a protein-coding gene, we can not only remove sequences that are shorter or longer than expected but also remove sequences that are out of frame (and then probably sequencing artefact).
Here are my questions :
1- how to remove those SV based on their sequence lengths : table(nchar(getSequences(gyrB))) ? 
2- how to perform in silico translation of these SV, detect stop codons and removed SV containing stop codons in R ? I wrote a small perl script for doing that but if you have any recommendations for doing that directly within R that will be more straightforward since we would be able to import the SV tables directly into phyloseq
Best,
Matthieu

**Comment by benjjneb** [comment]
On 1, you can just use base R commands to remove columns from the sequence table outside of your targeted length. There's a little code snippet to do this in the tutorial, expanded slightly here:

```
seqlens <- nchar(getSequences(seqtab))
keep <- seqlens >= MINLEN & seqlens <= MAXLEN
seqtab2 <- seqtab[,keep]
```

On 2, the dada2 package can't do that for you. But other packages in R can. For example the Biostrings package:

```
library(Biostrings)
dna <- DNAStringSet(getSequences(seqtab))
aa <- translate(dna)
```

*`translate` will assume that you have the sequences in frame*

I think the DECIPHER package may also have some facilities for this, perhaps @digitalwright knows.

**Comment by digitalwright** [comment]
If you only want to remove sequences that have stop codons, you can use Biostrings:
```
v <- vcountPattern("*", aa)
aa <- aa[v==0] # keep sequences with zero stops (*)
```

If you want to correct frameshifts in the nucleotide sequences, this can be done with [DECIPHER](http://DECIPHER.codes).  See the examples in the `CorrectFrameshifts` help page:

`?CorrectFrameshifts`

I hope that helps!

**Comment by matbarret** [comment]
Thanks for these suggestions. That works perfectly ! Many thanks again for your inputs
