### ISSUE TITLE
454+Illumina datasets

### ISSUE THREAD

**Issue by ctseto** [benjjneb/dada2#389]
I have some MiSeq data I've run through DADA2, but am interested in looking at some older data run on the 454 platform.

Both target the amplicon region (357F-926R), and was interested in seeing how they look together. In the case of Illumina, reads overlap and can be merged together. 

The plan is to learn errors separately, then merge them together as if they were different MiSeq runs. I am curious how to control for read length of the 454 run and the MiSeq run such that they are equivalent and capable of being merged.

**Comment by benjjneb** [comment]
You're going to need to truncate the 454 reads at the reverse primer, to get them to have exactly the same starting and ending points as the Illumina reads. Then they can be simply merged.

We don't have functionality for truncating based on a detected primer in this package, but outside programs can be used for that purpose (e.g. cutadapt).
