### ISSUE TITLE
package ‘missing_package_1’ is not available (for R version 3.2.2) 

### ISSUE THREAD

**Issue by IsabelFE** [benjjneb/dada2#39]
Hello,

missing_package_1 and 2 are not available for the new R version. How can I fix this? (I am really new to R)

Thanks a lot

**Comment by benjjneb** [comment]
Could you specify what packages? And are you using install.packages from
CRAN to try and get them?

That message is unfortunately misleading most of the time. Usually it means
that the package is not in the repository you are trying to install it
from. Several of the packages dada2 needs are from Bioconductor, not CRAN,
and should be installed in the following way:

source("http://bioconductor.org/biocLite.R")
biocLite("missing_package_1")

Let us know if that doesn't work (or does work)!

**Comment by IsabelFE** [comment]
Yes I am doing:

source("http://bioconductor.org/biocLite.R")
biocLite("missing_package_1")

**Comment by benjjneb** [comment]
What packages are you trying to install that are failing?

**Comment by IsabelFE** [comment]
I think that the package "vegan" is the one having problems

**Comment by IsabelFE** [comment]
Warning messages:
1: package ‘missing_package_1’ is not available (for R version 3.2.1) 
2: In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘vegan’ had non-zero exit status

**Comment by joey711** [comment]
I have R version 3.2.1 and vegan installed very fast and painlessly. Binaries are available.

**Comment by joey711** [comment]
Maybe it is a different package that is the problem?

**Comment by IsabelFE** [comment]
I was using first R version 3.2.2. Now I have changed to 3.2.1 and I am having the same problem

**Comment by joey711** [comment]
Were you able to install any packages?

**Comment by IsabelFE** [comment]
I am trying to follow the instruction here:
http://benjjneb.github.io/dada2/R/dada-installation.html

When I do 

install.packages("path/to/dada2",
                 repos = NULL,
                 type = "source",
                 dependencies = c("Depends", "Suggests","Imports"))

I am getting:

Installing package into ‘/Users/EscapaJuarez/Library/R/3.2/library’
(as ‘lib’ is unspecified)
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
ERROR: dependency ‘data.table’ is not available for package ‘dada2’
* removing ‘/Users/EscapaJuarez/Library/R/3.2/library/dada2’
Warning in install.packages :
  installation of package ‘/Users/EscapaJuarez/Desktop/benjjneb-dada2-56d2e61.tar’ had non-zero exit status

**Comment by benjjneb** [comment]
It sounds like you are missing the data.table package then.
Did install.packages("data.table") fail?

**Comment by IsabelFE** [comment]
OK,
I did install.packages("data.table") 
And then again:
install.packages("path/to/dada2",
repos = NULL,
type = "source",
dependencies = c("Depends", "Suggests","Imports"))

I think it worked!

packageVersion("dada2")
[1] ‘0.9.5’

**Comment by IsabelFE** [comment]
Not it did not work...
If I do library("dada2") I have and error in R studio:
![captura de pantalla 2015-09-25 a las 12 45 46 pm](https://cloud.githubusercontent.com/assets/7309296/10106566/711a3f30-6383-11e5-820f-a0386f5222cf.png)

**Comment by benjjneb** [comment]
Good on the intall, not on the crash.

Could you type R.version into a new R session and post the output here?

**Comment by IsabelFE** [comment]
platform       x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          2.1                         
year           2015                        
month          06                          
day            18                          
svn rev        68531                       
language       R                           
version.string R version 3.2.1 (2015-06-18)
nickname       World-Famous Astronaut

**Comment by IsabelFE** [comment]
OK, now library("dada2") don't crash everything. I am just getting this:
Loading required package: Rcpp
Creating a generic function for ‘nchar’ from package ‘base’ in package ‘S4Vectors’
Warning message:
package ‘Rcpp’ was built under R version 3.2.2 

Should I install R version 3.2.2 again?

**Comment by benjjneb** [comment]
R 3.2.1 works fine.

It might not be a bad idea to reinstall the Rcpp library though (I'm
assuming you installed it previously when you had R 3.2.2).

**Comment by IsabelFE** [comment]
Ok, I've done that. 

Now it crashes again every time I attempt 
library("dada2")

**Comment by benjjneb** [comment]
Let's try the easier install option (I need to add this to install
instructions) and see if this solves the problem. Perform the following 4
commands:

install.packages("devtools")
library("devtools")
devtools::install_github("benjjneb/dada2")
library("dada2")

**Comment by IsabelFE** [comment]
Let's see. I am using two computers (both mac):
Desktop: R studio is crashing now all the time. Again with library("devtools")
Laptop: 
devtools::install_github("benjjneb/dada2")
Downloading GitHub repo benjjneb/dada2@master
Installing dada2
Error in loadNamespace(name) : there is no package called 'BiocInstaller

**Comment by benjjneb** [comment]
OK, let's try from the ground up on the laptop. We'll install the base
Bioconductor packages first, then do the dada2 install:

source("http://bioconductor.org/biocLite.R")
biocLite()
install.packages("devtools")
library("devtools")
devtools::install_github("benjjneb/dada2")
library("dada2")

When running the biocLite() command it will probably prompt you about
installing some packages, just go ahead and install them all.

**Comment by IsabelFE** [comment]
OK, I think that everything is OK in the laptop (I went down to 3.2.1 version there too). Not idea why R studio in the desktop is crashing every time I try library(""). I think that dada2 is installed (it is on the right panel packages), but I must have other problems there... I will try to fix this problem later

Thanks a lot for your help. I am an R newbie :)

**Comment by benjjneb** [comment]
Great, glad to hear it installed on the laptop! 

The crashes on the desktop might be beyond the scope of this package, so I'm going to close this issue, but feel free to reopen if needed.
