### ISSUE TITLE
assignTaxonomy memory allocation failed

### ISSUE THREAD

**Issue by jack1120** [benjjneb/dada2#390]
This issue seems to be related to issue [#239](https://github.com/benjjneb/dada2/issues/239) and possibly also to [#17](https://github.com/benjjneb/dada2/issues/17).

I am attempting to assign taxonomies to the sequences in my seqtab.nochim table with dimensions of 72 samples by 1959 sequence variants, a total of 141,048 elements and 1.2 Mb size using the latest UNITE INSD database that contains 777,113 sequences and is ~55Mb when gzipped (~515Mb unzipped). I also added 12 sequences (with headers formatted properly) to the database file that correspond to a mock community. I am continually getting 'memory allocation failed' errors when running assignTaxonomy(seqtab.nochim, "path_to_db_file", multithread=FALSE). 

I am running R (v3.4.3) on a 64-bit system (pc) with 20Gb of RAM and have ensured that my memory.limit() in R is maxed out. I think I am also using the latest bioconducter (v3.6) and DADA2 (v1.6) packages. It's odd because I have monitored my memory usage while running the process and it barely moves the needle, so I am wondering if there is some other bug involved. I have also tried running the same process on my laptop (64-bit, 8Gb RAM) unsuccessfully. Unfortunately, my university's cluster isn't allowing me to install the bioconductor packages necessary to run the latest version of DADA2, so I haven't been able to try it on a system with more than 20Gb memory. 

All of the sequences that I am attempting to assign taxonomies to are from the fungal ITS2 region (MiSeq, 250bp, PE). As suggested in issue #239, I extracted my region of interest from the database file using [ITSx](http://microbiology.se/software/itsx/) to reduce the file size. I noticed that some sequences that were extracted were just 6bp or so and many contained a lot of Ns, so I used vsearch --fastxfilter to eliminate all sequences in the new UNITE_ITS2_Only database file that contained less than 20bp or any Ns. This reduced UNITE database file now contains 582,812 sequences, is ~183Mb unzipped and ~20Mb when gzipped. However, I am still getting the memory allocation failed error and am at a bit of a loss when thinking of ways to overcome this hurdle. I assume that the problem is still related to the database file size or an internal bug, as my seqtab.nochim table isn't too huge.

If I split my database file into chunks of 50,000 seqs or so, is it possible to assign taxonomies to my seqtab.nochim table iteratively, or will this cause additional problems as the same sequence in seqtab.nochim could be matched up to different sequences in the database throughout the process? 

So, instead of:

Taxa <- assignTaxonomy(seqtab.nochim, "path_to_complete_db", multithread=FALSE)

It would look like:

Taxa1 <- assignTaxonomy(seqtab.nochim, "path_to_db_chunk_1", multithread=FALSE)
Taxa2 <- assignTaxonomy(seqtab.nochim, "path_to_db_chunk_2", multithread=FALSE)
TaxaN<- assignTaxonomy(seqtab.nochim, "path_to_db_chunk_N", multithread=FALSE)

Then, Taxa1, Taxa2, ..., TaxaN would be concatenated into a final Taxa list.

Hmmm, this doesn't seem likely to work. I appreciate any help you can offer and suspect that a solution will help many users down the road. Thank you!

**Comment by benjjneb** [comment]
The problem isn't the number of sequences you are trying to assign taxonomy to, it is the number of sequences in the reference dataset. As in #239 you are running into memory trouble at 500k+ training sequences.

The ideal solution here would probably be to revisit our implementation of `assignTaxonomy` and improve the memory scaling characteristics. I'm going to add #239 (as the tracking issue) to the 1.8 release milestone, however I'm not sure just when I will have time to get to this.

A couple workarounds: With enough memory you should be able to handle that many reference sequences, I estimated in #239 that about 64GB should work for their similarly sized reference. And clustering the reference at a high level of identity (e.g. 99+%) would reduce the number of reference sequences with not too much cost to assignment accuracy.

**Comment by jack1120** [comment]
Quick update: I was able to successfully run assignTaxonomy on my seqtab.nochim matrix using an ITS2-only version of the UNITE INSD database (582,812 sequences) by allocating 256GB of memory on my university's cluster. It only took about an hour to run. The process failed when I attempted to run it using 62GB, 126GB and 200GB of memory prior to that.

Whole new issue here, but are there any plans to accommodate UNITE-formatted database files for assignSpecies or addSpecies in the near future?

**Comment by benjjneb** [comment]
Thanks for the update!

> Whole new issue here, but are there any plans to accommodate UNITE-formatted database files for assignSpecies or addSpecies in the near future?

There aren't right now, but no reason it couldn't be done. I've shied away from it in part because I didn't want to make a mistake doing so, as I know almost nothing about fungal taxonomy.
