### ISSUE TITLE
dada2 requires Biostrings 2.42.1

### ISSUE THREAD

**Issue by drdee255** [benjjneb/dada2#391]
I am trying to install dada2 - 
R version - 3.4.3
steps followed - 
- library(devtools)
- install_github("benjjneb/dada2")

Error message - 
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘Biostrings’ 2.38.4 is being loaded, but >= 2.42.1 is required
ERROR: lazy loading failed for package ‘dada2’
* removing ‘/home/drdee/R/x86_64-pc-linux-gnu-library/3.4/dada2’

I had tried to install Biostrings by biocLite("Biostrings") but by default Biostrings2.38.4 get installed

**Comment by benjjneb** [comment]
It sounds like you have an out of date version of Bioconductor, as Biostrings 2.38 is 2+ years old at this point. This is easy to remedy:

```
## try http:// if https:// URLs are not supported
source("https://bioconductor.org/biocLite.R")
biocLite("BiocUpgrade")     ## R version 2.15 or later
```

Reinstall Biostrings again via `biocLite` after that if necessary. More details here: https://www.bioconductor.org/install/#update-bioconductor-packages

**Comment by drdee255** [comment]
Done...
Thank you...
I uninstalled old version of bioconductor and upgraded to 3.6.
