### ISSUE TITLE
Data preparation for DADA2- How to make contigs and demultiplex sequences with various barcode lengths 

### ISSUE THREAD

**Issue by memoll** [benjjneb/dada2#393]
Hi,

I'd like to use DADA2 to analyze my data from 16S and 18S amplicon sequencing. I've used bbduk to trim illumina adapters and then Mothur to make contigs and demultiplex. The problem is that I've had barcodes with various lengths and as I know Qiime doesn't still treat those barcodes. On the other hand, Mothur gives me fasta files as results, which I can not use for DADA2. Do you have any suggestion so I can deal with my sequences in a way I get fastq files to continue analyzing them with DADA2?

**Comment by jack1120** [comment]
Have you tried [cutadapt](http://cutadapt.readthedocs.io/en/stable/guide.html)? It's easy to trim any sequence and output as fastq files using this tool.

**Comment by memoll** [comment]
Hi @jack1120 Thanks for your response, which made me understand I didn't explain my question as I wished. So as you see now, the actual issue is not trimming but how to deal with those barcodes.

**Comment by jack1120** [comment]
You can also demultiplex with cutadapt and the length of the barcode doesn't matter. There is a section on this in the link that I sent previously. Scroll down about 3/4 of the page.

**Comment by memoll** [comment]
@jack1120 great. I'll check it. Thanks.
