### ISSUE TITLE
Data preparation for DADA2- How to extract barcodes with various length?

### ISSUE THREAD

**Issue by memoll** [benjjneb/dada2#394]
Hi,

I'd like to use DADA2 to analyze my data from 16S and 18S amplicon sequencing. I've used bbduk to trim illumina adapters and then Mothur to make contigs and demultiplex. The problem is that I've had barcodes with various lengths and as I know Qiime doesn't still treat those barcodes. On the other hand, Mothur gives me fasta files as results, which I can not use for DADA2. Do you have any suggestion so I can deal with my sequences in a way I get fastq files to continue analyzing them with DADA2?

**Comment by benjjneb** [comment]
Doesn't make.contigs also output quality scores?

**Comment by memoll** [comment]
It does, but since the sequences and quality scores are separated into 2 files (fasta and qual), I'm not sure how to use them. Should I remake fastq files out of them, because I thought it might not be a good idea!

**Comment by benjjneb** [comment]
Sure, you can just merge them back together into fastq files and work with those.

**Comment by memoll** [comment]
Hi Benjamin!

It absolutely works! But now that I'm looking more through DADA2 I see that I shouldn't have make contigs at the beginning, since DADA2 will merge sequences later, after quality control. So I'd like to change my question to: how to extract barcodes with various lengths in a way that the output will be compatible with DADA2.

**Comment by benjjneb** [comment]
TBH I don't know all the demultiplexing options out there. But doesn't the QIIME script allow variable length barcodes? http://qiime.org/scripts/split_libraries.html

Looks like `variable_length` is an option to pass to the `-b` flag.

Basically you want to demultiplex your fwd/reverse files separately, with all filtering turned off, and then it should be good to go w/ dada2. See our FAQ: http://benjjneb.github.io/dada2/faq.html#how-can-i-demultiplex-my-fastq-files

**Comment by memoll** [comment]
That should be exactly what I was looking for. I knew about the -b argument, I cannot believe I haven't seen the variable_length option!! Sorry and thanks a lot.

**Comment by memoll** [comment]
Hi, 
A very late update to this issue: finally what helped me to deal with various length barcodes was using [https://cutadapt.readthedocs.io/en/stable/guide.html](cutadapt). I had it installed and used it directly, but the [https://docs.qiime2.org/2018.2/plugins/available/cutadapt/demux-paired/](q2-cutadapt plugin) should do the same job!
