### ISSUE TITLE
Dealing with files containing 0 reads

### ISSUE THREAD

**Issue by elsherbini** [benjjneb/dada2#396]
I'm using dada2 in an automated pipeline. Sometimes after demultiplexing and trimming primers, there are files with 0 reads.

When I have a file with 0 reads, the following rule fails:

```
library(dada2)

derep <- derepFastq(snakemake@input[["filtered"]])
saveRDS(derep, snakemake@output[["derepped"]])
```

```
Error in rep(seq(length(uniques)), tab[tab > 0]) : 
  invalid 'times' argument
Calls: derepFastq -> qtables2
Execution halted
```

Instead, I'd rather it save an empty derep object. That way the whole pipeline would continue, and at then end I'd simply have a row in my sequence table with all 0s, indicating that there were no reads in that sample that made it through the pipeline.

**Comment by elsherbini** [comment]
Related, if i make my own "empty" derep object like so:
```
derepO <- list(uniques=setNames(as.integer(c(0)), as.character(c(""))), quals=matrix(0), map=c())
derepO <- as(derepO, "derep")
```

and then try to call `dada()` on it with an error matrix i get an error:
```
err_matrix <- readRDS("pipeline/18S/proc/1umP1/3.learnError.f.Rds")
denoised <- dada(derepO, err=err_matrix)
Sample 1 - 0 reads in 1 unique sequences.
Error in dada_uniques(names(derep[[i]]$uniques), unname(derep[[i]]$uniques),  : 
  basic_string::resize
```
Where I think the result of applying `dada()` to an empty derep object should be an empty dada object.

This behavior would be convenient for my use case where I want to be able to demultiplex a file, run individual samples through the pipeline independently, and then combine the sequence tables at the end.

**Comment by benjjneb** [comment]
You've struck on why we haven't done this, it needs functionality added to the whole workflow to handle empty objects (`derepFastq`, `dada`, `mergePairs`) and testing on others as well (`isBimera` and so forth).

Right now we recommend capturing the filtering failure at that step, by checking the return value of `filterAndTrim` of by checking `file.exists` for the output file, and then substituting alternate behavior as needed.
