### ISSUE TITLE
assignTaxonomy - additional column adding (e.g. species hypothesis ID SH)

### ISSUE THREAD

**Issue by jgrzadziel** [benjjneb/dada2#397]
Hello :)
I wonder if there is any possibility to add another column to the results of `assignTaxonomy`?

For example while working with ITS sequences I want to see not only taxonomy assignments (Kingdom, Phylum (...) Species ) but also a chosen sequence ID  (Species Hypothesis ID = SH).

This is how UNITE reference fasta headers look like:

 `>Flagelloscypha_japonica|LC146734|SH497095.07FU|reps_singleton|k__Fungi;p__Basidiomycota;c__Agaricomycetes;o__Agaricales;f__Tricholomataceae;g__Flagelloscypha;s__Flagelloscypha_japonica
 AGGTGAACCTGCGGAAG(...)`

So It would be perfect if the final `taxa.csv` included also **SHXXXXXXXX.FU** column. 
Have anyone know the solution ?

Thanks

**Comment by benjjneb** [comment]
The function doesn't return the best hit ID right now.

Philosophically I'm a bit opposed to doing so -- best hit is a notoriously bad way to assign taxonomy, yet is still widely used, so I don't like mixing taxonomic assignment with that.

**Comment by jgrzadziel** [comment]
I agree with that and Im far from using best hit.
But my question is, if there is a possibility to catch Species Hypothesis ID of each classified fungi using dada2 function assignTaxonomy ? It is included in each taxa header, so the solution should be simple.

Currently it is highly demanded to enclose SH of each fungi taxa, as well as it's DOI (from UNITE database) while publishing ITS-based publications.  This problem comes from the idea, that the taxonomy of fungi is changing rapidly, but DOI of each sequence is permanent.

**Comment by benjjneb** [comment]
> But my question is, if there is a possibility to catch Species Hypothesis ID of each classified fungi using dada2 function assignTaxonomy ? It is included in each taxa header, so the solution should be simple.

Which Species Hypothesis ID? The SH of the best hit? Isn't that the same thing as best hit assignment?

> Currently it is highly demanded to enclose SH of each fungi taxa, as well as it's DOI (from UNITE database) while publishing ITS-based publications. This problem comes from the idea, that the taxonomy of fungi is changing rapidly, but DOI of each sequence is permanent.

I get that concern. Is a lack of SH IDs from taxonomy assignment a straight barrier to being published? The issue is that the best hit SH is not enough to know if taxonomy assignment should change later. What if the SH ID of taxa B changes, causing the confidence on the assignment of sequence X, which best matched taxa A (near to taxaB) to drop below the assignment threshold? It's not captured by the SH ID of taxa B.

In the dada2 ASV approach, the sequence itself is supposed to be the durable future-proof identifier (unlike OTUs).

**Comment by jgrzadziel** [comment]
Thank you for your response. You are completely right, and answering to :

> Is a lack of SH IDs from taxonomy assignment a straight barrier to being published?

generally it's not a problem at all, however I had an issue with one reviewer who definitely demanded SH and DOI of each assigned taxa.  I always take under concern this kind of criticism and I'm glad that you explained me the problem very well.

Thank you :)
