### ISSUE TITLE
mergeSequenceTables with sequences from justConcatenate=TRUE

### ISSUE THREAD

**Issue by elsherbini** [benjjneb/dada2#399]
I am processing a sequencing run with reads that don't overlap. I am unable to merge the resulting sequence tables.

```
library(dada2)

sessioninfo()
...
other attached packages:
[1] dada2_1.6.0          Rcpp_0.12.15         BiocInstaller_1.28.0
...
seqtab1 <- readRDS("seqtab1.Rds")
seqtab2 <- readRDS("seqtab2.Rds")
mergeSequenceTables(seqtab1, seqtab2)

Error in mergeSequenceTables(seqtab1, seqtab2) : 
  At least two valid sequence tables, and no invalid objects, are expected.
```

when I look at the individual sequence tables, they look normal except for the Ns. If I remove the Ns, the sequences do merge:

```
colnames(seqtab1) <- gsub("N", "", colnames(seqtab1))
colnames(seqtab2) <- gsub("N", "", colnames(seqtab2))

mergeSequenceTables(seqtab1, seqtab2) # works
```

[seqtabs.zip](https://github.com/benjjneb/dada2/files/1649948/seqtabs.zip)

**Comment by benjjneb** [comment]
Should work now, but let me know if not. Had an overzealous ACGT check in there.

**Comment by elsherbini** [comment]
Works great, thanks!
