### ISSUE TITLE
Diagnostic Scripts

### ISSUE THREAD

**Issue by mjrosen** [benjjneb/dada2#4]
My original post was: "There should be a set of diagnostic scripts that compare error distributions computed from DADA's error model (and inferred parameters) with the inferred error distributions from the clustering itself. These could include for a start one and two-away abundances."

I actually think this could be one of coolest features of an R package, given the nice plotting and ability to interface with other packages. To spell it out a bit more clearly, DADA produces two things: (1) and error model, and (2) a clustering of the data. Because this is a fully generative error model, we can go forward and ask whether the clustered data really looks typical in various ways of what the error model should produce. A simple example is to ask, under the error model, how many sequences with one error and r reads do we expect. We then plot this against a histogram of the actual numbers of errors called by the clustering with one error and r reads. We then do the same with two-aways. We can then switch and ask for errors with two reads, how many do we expect for various ranges of \lambda under the error model, and plot this against the observed number in the clustered data. Looking at a bunch of plots of this kind  allows users to see if the error model is working, and where deviations may be occurring, so it's a powerful diagnostic, which I _think_ isn't even possible under any other denoising tools out there. I'm happy to help brainstorm other useful plots we could include at some point.

**Comment by benjjneb** [comment]
Closing as old.

**Comment by joey711** [comment]
Did we do much of this? I think the plot of error model satisfies a lot of it (Q v. Err Freq for each substitution). Was there anything else in mind here that is missing, and should spin-out a separate issue?

**Comment by mjrosen** [comment]
I haven't been keeping up with DADA2, so maybe there are some plots that address what I meant. But Q vs. Err Freq, while useful as a consistency check, doesn't assess the underlying error model in the way I had in mind. This would mainly involve looking at distributions that should be Poisson but may not be, either due to non-independence between reads (early-stage PCR) or non-independence between errors.

Another extremely useful feature I've used is to look at dn/ds for putative error-containing sequences, which can reveal the presence of false negatives. Could be nice at some point.

**Comment by benjjneb** [comment]
I think the plots Mike are suggesting are useful for understanding and potentially at some point further improving the error model, but I don't think there is much if any desire for them from users of the software.

At the point that we redevelop the error model it might be worth creating and exposing those plots, but until then I don't think we need them.
