### ISSUE TITLE
Identical pool, multiple runs - when to merge?

### ISSUE THREAD

**Issue by fanli-gcb** [benjjneb/dada2#404]
Hi all,

We're planning to sequence a set of ~200 samples in a single pool across two MiSeq runs. Would it be better to:
A) Merge the raw FASTQ files, then run DADA2
or
B) Process each run independently, then merge the sequence tables

I know the recommendation is to do the latter, but that seems to be generally for the case where the samples are distinct on each run. Does this advice change if we are resequencing the same pool? 

Thanks!
Fan

**Comment by benjjneb** [comment]
The reason we recommend processing runs separately, is that different runs can have (surprisingly) different error profiles. So I would still recommend processing the runs separately, unless they are runs from say the same machine, in which case you can expect the same error profile for each run.

**Comment by fanli-gcb** [comment]
> So I would still recommend processing the runs separately, unless they are runs from say the same machine, in which case you can expect the same error profile for each run.

Oh, I was not aware that runs from the same machine would be considered to have the same error profile. We run our own 16S libraries on a single MiSeq. Is there any downside to processing runs independently, other than runtime?

So in the case above (the same pool sequenced across two runs on the same machine probably within a day or two of each other, same operator, etc.), would we be better off still processing them separately?

**Comment by benjjneb** [comment]
> Is there any downside to processing runs independently, other than runtime?

If you combine the replicate samples across your two runs, you get a marginally increased ability to detect rare variants (similar to doubling depth). But that's pretty minor.

**Comment by fanli-gcb** [comment]
Alright, thanks!
