### ISSUE TITLE
filtered fastq.gz files from Pipeline Tutorial (1.6) for apired end big data analysis

### ISSUE THREAD

**Issue by microbod** [benjjneb/dada2#406]
Hi Benjjneb,
We performed 'filtering and trimming' by using DADA2 pipeline tutorial (1.6) and created filtered fastq.gz files. Now, we realized a DADA2 workflow for Big Data (Paired-end) is suitable for our study. I am curious to know whether we could use those 'filtered_trimmed' files for DADA2 big data workflow (from Infer Sequence Variants step). It would save our time .

**Comment by benjjneb** [comment]
That would be fine. The filter/trim steps are functionally identical.

**Comment by microbod** [comment]
Thanks.
