### ISSUE TITLE
Removing Chimeras: removeBimeraDenovo

### ISSUE THREAD

**Issue by rahulnccs** [benjjneb/dada2#407]
Hey Benjjneb, We have executed script for removing chimera, now its been more than 30hrs and is yet to finish.
As we would be performing closed reference OTU picking using trained data set, is there a possibility that OTU picking step would exclude chimeric sequences and will give hit only for true sequences?
If the answer is 'yes' we can skip removing chimera step.

Thank you

**Comment by benjjneb** [comment]
That's surprising that it would be taking that long. Did you turn on `removeBimeraDenovo(..., multithread=TRUE)`?

What is the size of the input sequence table, and what mode are you using (i.e. `consensus` or `pooled`)? Also, which `packageVersion("dada2")`?

**Comment by rahulnccs** [comment]
Yes 'multithread=TRUE'  sequence table has 1118984 reads. We are using consensus mode and  DADA2 version 1.4.

**Comment by benjjneb** [comment]
What is `dim(st)`? In particular the number of ASVs (rather than reads)?

And what is the computational hardware you are using in terms of memory/processor?

**Comment by rahulnccs** [comment]
output put of dim(seqtab) is 102 1118984. 
we are using 32GB RAM computational power

**Comment by benjjneb** [comment]
That is a lot (~1M) ASVs, but I'm still surprised its taking that long. In response to your first question though:

> As we would be performing closed reference OTU picking using trained data set, is there a possibility that OTU picking step would exclude chimeric sequences and will give hit only for true sequences?

Unfortunately, no. Chimeras commonly get assigned to closed-reference databases, and majorly inflate the number of output closed-ref OTUs.

**Comment by benjjneb** [comment]
PS: Are you sure there are no primers hanging out on these sequences? That can inflate the number of output ASVs a lot.

**Comment by rahulnccs** [comment]
By cutadapt we've removed primers we are sure about that.
