### ISSUE TITLE
R Crashing During assignTaxonomy

### ISSUE THREAD

**Issue by NoelatPitt** [benjjneb/dada2#410]
R is crashing for me when I run
taxa <- assignTaxonomy(seqtab.nochim, "/Users/noelbritton/Desktop/ALIR ITS FASTQ FILES COPY 2 4/filtered/UNITE_public_10.10.2017.fasta", multithread=TRUE)
Any insights?
Thanks!

**Comment by jgrzadziel** [comment]
What do you mean crashing ? Some error message? 
Maybe there is one of these reasons
1) Not enough RAM
2) Try remove spaces in directory name: ALIR ITS FASTQ FILES COPY 2 4/,
to something like this: ALIR_ITS_FASTQ_FILES_COPY_ 2_4/

Generally try avoiding spaces in directories when using R.

**Comment by NoelatPitt** [comment]
By crash, I mean I get an error message that says "R session aborted. R encountered a fatal error. The session was terminated." 

I changed the spacing in the file directory, should I assume it's a RAM issue?

**Comment by benjjneb** [comment]
What version of the dada2 package are you using? `packageVersion("dada2")`
And what system/OS/R-version are you on? `R.version`

**Comment by NoelatPitt** [comment]
![screen shot 2018-02-07 at 10 31 22 am](https://user-images.githubusercontent.com/36218450/35924811-1769169a-0bf2-11e8-88af-66bb0370ea1e.png)
![screen shot 2018-02-07 at 10 31 09 am](https://user-images.githubusercontent.com/36218450/35924813-1858cbae-0bf2-11e8-8382-783a58863afc.png)

**Comment by benjjneb** [comment]
Is that the "General Fasta Release" file from UNITE? https://unite.ut.ee/repository.php
If it's one of the other file formats, the parsing will break and crashes are likely.

**Comment by NoelatPitt** [comment]
Thanks. That was the issue!
