### ISSUE TITLE
Assign Taxonomy error

### ISSUE THREAD

**Issue by zardfg** [benjjneb/dada2#411]
Hi Ben,

I am new user of DADA2 and trying to do tutorial. I am struggling with the following error for a while:
> taxa <- assignTaxonomy(seqtab.nochim, "Training/silva_nr_v128_train_set.fa.gz", multithread=TRUE)

Error: Input/Output
no input files found
dirPath: silva_nr_v128_train_set.fa.gz
pattern: character(0)
I tried full Path as "/Users/zg/Desktop//MiSeq_SOP/silva_nr_v123_train_set.fa.gz", but still same problem.
I would greatly appreciate if you help me with that.
Zahra

**Comment by benjjneb** [comment]
Hi Zahra,
You need to replace the file path in the tutorial (`""Training/silva_nr_v128_train_set.fa.gz"`) with the correct file path on your machine, that points to the location of the silva file on your local machine.

**Comment by zardfg** [comment]
Thanks for quick response
I downloaded the silva file in desktop 
taxa <- assignTaxonomy(seqtab.nochim, "/Users/zgeraylo/Desktop/silva_nr_v123_train_set.fa.gz", multithread=TRUE)
But it didn't work

**Comment by benjjneb** [comment]
Can you double-check the path, and the filename? Did you download v123 or v128?

**Comment by zardfg** [comment]
I downloaded v128 in my desktop and file name is correct(silva_nr_v128_train_set.fa.gz)
taxa <- assignTaxonomy(seqtab.nochim,"/Users/zgeraylo/Desktop/silva_nr_v128_train_set.fa.gz", multithread=TRUE)
now worked, I set working directory to Desktop and worked.
Thanks
