### ISSUE TITLE
Ion torrent sequences produce strange error models

### ISSUE THREAD

**Issue by ssphsant** [benjjneb/dada2#413]
Hi 

I am a rather new user of dada2 but have tried to run it on some of my MiSeq sequences. 

Now, I am working with some samples that were sequenced with Ion torrent. The amplicon is V4 region that I truncated to 240 bps based on the quality scores. When I plot the error models they seem mostly fine, but the observed errors compare poorly to the model when the consensus quality score is > 38 (see attached figure). I have seen this with other Iontorrent data but not with MiSeq. Can I still continue with the analysis or should I first make some changes?

Thank you in advance, Tina 

[Rplot3.pdf](https://github.com/benjjneb/dada2/files/1720303/Rplot3.pdf)

**Comment by benjjneb** [comment]
Huh, that is interesting. I suspect that there are probably very few Q=35+ reads in this data, but a quick way to check...

Can you post the output of `plot(colSums(err$err_out)))`

**Comment by ssphsant** [comment]
Thanks for the fast reply!

Here is the output...

[Rplot4.pdf](https://github.com/benjjneb/dada2/files/1720521/Rplot4.pdf)

**Comment by benjjneb** [comment]
Ah, sorry, that was the wrong plot, meant to be:

`plot(colSums(err$trans))`

**Comment by benjjneb** [comment]
> So I guess that the discrepancy between the model and errors at high values is not that important?

For the most part, although I'm gonna keep this in mind. Wonder if there is a better way to handle edge behavior when there is very little data there than the loess fitting we do.

**Comment by ssphsant** [comment]
Ok, I will keep my eyes open for any updates on this! 

I have another question: I would like to compare these data to some MiSeq sequences following the big data protocol. Miseq sequences cover V3-V4 region so there is an overlap with the Ion torrent sequences, but the sequence length are very different. Ion torrent sequences are truncated to 240 bp, and Miseq sequences are mostly 400-430 bp after I merge the pair-end reads. Should I expect some problem due to the different sequence length of each library?

**Comment by benjjneb** [comment]
> I have another question: I would like to compare these data to some MiSeq sequences following the big data protocol. Miseq sequences cover V3-V4 region so there is an overlap with the Ion torrent sequences, but the sequence length are very different. Ion torrent sequences are truncated to 240 bp, and Miseq sequences are mostly 400-430 bp after I merge the pair-end reads. Should I expect some problem due to the different sequence length of each library?

To directly compare the sequences, you are going to have to trim them to cover exactly the same region. 

Do they both use the same forward primer? If so its pretty straightforward, you just truncate each at the same number of bases after the forward primer and can directly merge the tables.

**Comment by ssphsant** [comment]
Hej Ben, I am sorry for the late reply. 
Thanks for the advice, I really appreciate the help! 
They have almost the same reverse primer. So I will try to merge them by just taking the reverse reads of the MiSeq sequences and the whole Ion torrent. They are roughly the same length.

**Comment by benjjneb** [comment]
> They have almost the same reverse primer. So I will try to merge them by just taking the reverse reads of the MiSeq sequences and the whole Ion torrent. They are roughly the same length.

That approach should work. You'll want to truncate them to exactly the same length though for simple merging (probably to whichever is shorter).
