### ISSUE TITLE
assignSpecies : no taxonomic assignation

### ISSUE THREAD

**Issue by JackouilleS** [benjjneb/dada2#415]
Hello, I am fairly novice to dada2 and when I used your pipeline on the MiSeq_SOP data it went pretty smoothly but on my own data it appears to be quite different. Indeed, I am encountering some problems using the assignSpecies command. 

I extracted a database specific to Phytophthora species (Phytophthora-ID-ITS.fasta) from an online database (http://phytophthora-id.org/seq-id.html), placed it in my file where my Fastq files are, zipped it. However, when I try to assign species to my sequences (assignSpecies(seqtab.nochim, "Phytophthora-ID-ITS.fasta.gz", verbose =TRUE), the result is that "0 out of 101 were assigned to the species level.".

I tried the same command line with a formated database : taxa<-assignTaxonomy(seqtab.nochim, "silva_nr_v128_train_set", verbose =TRUE) and then unname(taxa), I get a taxonomic assignation "Eukaryota", but the rest is "NA". Even when I try to implement my Phytophthora-ID-ITS.fasta.gz database, using addSpecies, it doesn't work.

Would you know what could be the problem ? 

Thank you for you help!

**Comment by benjjneb** [comment]
How are the id lines of the fasta you created formatted? Do they follow the requirements for formatting custom databses to use w/ dada2?

https://benjjneb.github.io/dada2/training.html#formatting-custom-databases

**Comment by JackouilleS** [comment]
Hello, thank you for answering !

Actually the ID lines appear to follow the requirement for custom database, they look like that : >AB217671.1 Phytophthora cactorum 
CCACACCTAAAAACTTTCCACGTGAACCGTTTCAAACCAAATAGTTGGGGGTCTTGTCTGGTGGCGGCTGCTGG...
When I blast my contigs to the online database, it actually works by the way ...

**Comment by benjjneb** [comment]
It may be that `assignSpecies` is not the right tool for you here.

`assignSpecies` requires exact matching to make species assignments, and that if multiple reference sequences are exactly matched, that they are all of the same species. The primary use case is in 16S sequencing, where exact matching is an appropriate way to do species-level assignemt, but that may be too stringent for the ITS region.

You can check if there are any exact matches being found with `assignSpecies(..., allowMultiple=TRUE)`. If there are still no (ambiguous) assignments, then you probably need a different, fuzzier method to do Phytophthora species assignment.

**Comment by JackouilleS** [comment]
Hi, 

I tried as you said, and it still does not work. I will find to try another way to assign species. 

Thank you for your time.

**Comment by kaastengel1** [comment]
Hi @JackouilleS, I was wondering what you ended up doing for your taxonomy assignment of Phytophthora? I am in a similar position in having trouble with assigning taxonomy to my ASV table. 

Thank you!
