### ISSUE TITLE
Quality plots and trimming

### ISSUE THREAD

**Issue by sentryone** [benjjneb/dada2#416]
I am a relatively new dada2 user. Per some suggestions, I used cutadapt to trim adapters and then I did quality plots to get an idea of truncation parameters. Original reads were 250bp, and after trimming are 225bp.  1) Why are the trimmed plots graphed out to x = 250 when the reads are 225bp? 2) Are the noticeably worse quality scores at the ends just artifacts, and where does that data come from? 

Samples of original and post cutadapt FWD plots are shown. You can see the dips in the original scores shifted left in the cut version. I also did a character count on the cut fastq files to make sure that the reads are indeed a shorter length. Thanks for your help!
[FwdQprofile.raw.pdf](https://github.com/benjjneb/dada2/files/1737516/FwdQprofile.raw.pdf)
[FwdQprofile.cut.pdf](https://github.com/benjjneb/dada2/files/1737517/FwdQprofile.cut.pdf)

**Comment by benjjneb** [comment]
A minority of the post cutadapt reads still extend to 250 nts.

Could be reads in which the adapter/primer wasn't present and hence untrimmed?

**Comment by sentryone** [comment]
Oh, thank you so much. I saved the character count for an entire file and never saw the smaller values. Below is a frequency table, prompted by your input. I think the default adapter match overlap is 3 ; would you recommend making it be longer, say 10? In which case, this would cut out the 247, 248 entries.

> t <- read.csv(file="lctALL.cut.1YS31739_R1.txt", header=FALSE)
> table(t)
t
     1     52     53     54    212    217    218    222    224    225    226    227    247    248 
211714  12109  86779 112826      2      2      2      4    700 417922   4746      6     12     32

**Comment by benjjneb** [comment]
A lot of ways to skin that cat. 

You could also just filter out those that didn't get cutadapted to the expected length with `maxLen=225`.

**Comment by sentryone** [comment]
Thanks for. your input!
