### ISSUE TITLE
documentation for Conda install

### ISSUE THREAD

**Issue by wdwvt1** [benjjneb/dada2#417]
I use `conda` to manage my environments and getting `DADA2` installed in an environment managed by `conda` takes some tweaking. I wanted to document this somewhere in case it is helpful for other people/to makes it way into the documentation. Below is the best explanation I have for the odd errors I've encountered trying to get a working `DADA2` install with `conda`. 

`conda` versions before 5.0 rely on the system compilers (`gcc` etc.) for compiling packages that are installed. `conda` versions 5.0 and greater rely on `Anaconda` supplied compilers which are packages managed by `conda`. 

**However, even when `conda` versions less than 5.0 are installed, and `conda` is used to install `R` (`conda install R=3.4.2`), the `Makeconf` file that gets installed contains references to the `Anaconda` specific `gcc`.**

So, for me, here was the sequence of installation events:

```bash

conda --version
>conda 4.3.30 
# Good, we are on an old version of conda so we shouldn't need the special compilers.

# Use conda to create a full python stack that we'll use along with DADA2
conda create -n dada2 python=3 anaconda 
source activate dada2
conda install R=3.4.2
R
>source("https://bioconductor.org/biocLite.R")
>biocLite("dada2")
>...A bunch of installation errors...
>...The critical line...
> make: /home/wdwvt/anaconda3/envs/dada2/bin/x86_64-conda_cos6-linux-gnu-cc: Command not found
```

At this point I was confused because I expected `make` to be using the system wide `/usr/bin/gcc` and instead the configured `Makeconf` included the flag:

`'CC=/home/wdwvt/anaconda3/envs/dada2/bin/x86_64-conda_cos6-linux-gnu-cc'`

instead of the expected (and what is found for `/usr/lib/R/etc/Makeconf`)

`'CC=gcc -std=gnu99'`

So, for some reason, with `conda < 5.0` installed, R is still generating `Makefile`'s that contain references to a compiler that is not be default installed. 

**To remedy this and get a fully working `DADA2` install you must install the expected compilers using:**
```
source activate dada2
conda install gxx_linux-64
R
>source("https://bioconductor.org/biocLite.R")
>biocLite("dada2")
```

Hopefully this helps people who are having trouble. Also if anyone more knowledgable about what `BioConductor` or `make` is doing being the scenes wants to comment that would be tremendously helpful.

**Comment by benjjneb** [comment]
Thanks, very helpful!

**Comment by benjjneb** [comment]
An additional note: In @wdwvt1 instructions here, a conda environment is set-up for dada2, but the installation of dada2 in that environment is through Bioconductor, i.e. `biocLite("dada2")`.

There is a pre-built version of dada2 that is directly conda-installable by a `conda` command via the bioconda channel. **HOWEVER**, the bioconda build of dada2 is 2x-10x slower: https://github.com/qiime2/q2-dada2/issues/74

For that reason, we recommend that those using conda to manage their environment still use the `biocLite` installation method for the dada2 package itself described here, rather than installing the bioconda version of dada2 _(at least until those speed issues are remedied)_.

**Comment by abalter** [comment]
I've had trouble using **bioconda** as well. It seems that bioconda recipes are not kept up with Bioconductor packages. So I tend to run into conflicts between bioconda and the rest of conda. I've also gone over to explicitly blocking the bioconda channel, and using `biocLite` (after sourcing it) for all bioconductor packages.

However, I make sure to use the `suppressUpdates=TRUE` option to make sure that the updates don't pollute my conda environment.

I'm hoping for a day when R, Bioconductor, and conda all work more cooperatively.
