### ISSUE TITLE
mergePairs() not working

### ISSUE THREAD

**Issue by drish91** [benjjneb/dada2#419]
Hi Ben!
I'm relatively new to dada2 but I've run it successfully in the past. The read filtering and trimming works fine, dereplication works fine, but for some reason when I try to merge the fwd and rev read pairs, it gives me empty dataframes. I don't get any errors, but when I check the elements of the list, they're all of length 0. 

I have 37 paired end samples. I've tried running it as a part of the loop specified on the Readme, but that gives me the same result.

Please see attached snippet:
> mergers = mergePairs(ddF, derepF, ddR, derepR)
>
> length(mergers)
[1] 37
>
> names(mergers)
 [1] "CCE1706001" "CCE1706002" "CCE1706003" "CCE1706004" "CCE1706005"
 [6] "CCE1706006" "CCE1706007" "CCE1706008" "CCE1706009" "CCE1706010"
[11] "CCE1706011" "CCE1706012" "CCE1706013" "CCE1706014" "CCE1706015"
[16] "CCE1706016" "CCE1706017" "CCE1706018" "CCE1706019" "CCE1706020"
[21] "CCE1706021" "CCE1706022" "CCE1706023" "CCE1706024" "CCE1706025"
[26] "CCE1706026" "CCE1706027" "CCE1706028" "CCE1706029" "CCE1706030"
[31] "CCE1706031" "CCE1706032" "CCE1706033" "CCE1706034" "CCE1706035"
[36] "CCE1706036" "CCE1706037"
>
> names(mergers$CCE1706001)
[1] "sequence"  "abundance" "forward"   "reverse"   "nmatch"    "nmismatch"
[7] "nindel"    "prefer"    "accept"
> length(mergers$CCE1706001$sequence)
[1] 0
> length(mergers$CCE1706001$abundance)
[1] 0

> length(cce.ddF) ; length(cce.ddR); length(derepF); length (derepR)
[1] 37
[1] 37
[1] 37
[1] 37
They're all lists and I've checked the elements for all of the above, and they seem correct.

> packageVersion("dada2")
[1] ‘1.4.0’
> packageVersion("ShortRead")
[1] ‘1.34.1’

Would it be more helpful to send you the script I'm running, or is the remedy fairly straightforward?

Looking forward to your response,
Drishti

**Comment by benjjneb** [comment]
My guess would be that your reads aren't overlapping after truncation.

Can you post the filtering command you used? And the expected length of the amplicon you are sequencing?

**Comment by drish91** [comment]
Thanks for your prompt response! Here's the filtering command I'm using:
filterAndTrim(fwd=cce.fnFs, filt=cce.filtFs,rev=cce.fnRs, filt.rev=cce.filtRs,truncLen=c(200,200), maxEE=5, truncQ=11, maxN=0, rm.phix=TRUE,compress=TRUE, verbose=TRUE, multithread=TRUE)

I tried using a truncLen of 240 too, but that didn't seem to improve anything. And I think the expected amplicon length is ~400bp.

**Comment by benjjneb** [comment]
> I tried using a truncLen of 240 too, but that didn't seem to improve anything. And I think the expected amplicon length is ~400bp.

It is critical to understand the length of your expected amplicon in order to choose truncation parameters that allow the reads to overlap. See more here: https://benjjneb.github.io/dada2/faq.html#why-arent-any-of-my-reads-being-successfully-merged

Can you clarify what primers you are using, and whether the primers are on your reads or not?

**Comment by drish91** [comment]
They're V4-V5 primers so there's fair amount of overlap there, and that's validated by the dereplicated fwd and rev sequences as well. And the primers are still on the reads, but why would that contribute towards the overlap issue? Would you recommend I use the justConcantenate parameter with mergePairs?
Thanks for the link! It also suggested that the quality of data might be bad, but that is not the case with this dataset, I checked the taxonomy for a few and that seemed to give me results with fairly high identity.

**Comment by benjjneb** [comment]
In order for mergePairs to work you need 20nts of overlap (plus some padding for biological length variation). This is why you need to know the length of your amplicon, to know what the minimum total truncated lengths of your reads need to be. What is the expected length in nucleotides of the sequenced amplicon (which includes primers)?

The primers matter for two reasons. First, if they are on your reads, the sequence amplicon is longer. Second, primers usually have ambiguous nucleotides that interfere with denoising, merging and chimera removal. They must be removed.

You probably need to increase `truncLen`, and you must remove the primers. If you know their lengths, and know they are on the starts of the reads, you can do that with `trimLeft=c(fwd.primer.len, rev.primer.len)`

**Comment by drish91** [comment]
The expected length of the sequenced amplicon would be 400bp in this case, which is why I decided to target ~200-240bp as truncLen. I'll try to increase the truncLen to 300, perhaps that'll help.

I still don't get why mergePairs wouldn't be able to merge any of the reads though. There's certainly scope for read overlap, even with 200bp right? so why were there no results?

**Comment by benjjneb** [comment]
> I still don't get why mergePairs wouldn't be able to merge any of the reads though. There's certainly scope for read overlap, even with 200bp right? so why were there no results?

`mergePairs` requires 20nts of overlap by default. So if your `truncLen` is 200 for forward and reverse, and the sequenced amplicon is 400 nts, none will merge because they don't get to 20nts of overlap.

Furthermore, your _sequenced amplicon_ may be more than the 400 nts you are expecting, because it includes the primers, thus you need to keep more of the reads for overlap. Diagram below...

```
READ1------------------------------
PRIMERxxxxxxxxxxxxxxxxxxxxxxx400ntsxxxxxxxxxxxxxxxxxxPRIMER
                        ------------------------------READ2
```

**Comment by drish91** [comment]
Thankyou for breaking this down for me. Seems like truncLen = 225 was the magic number. Its weird bc I think I tried 240nt before and that didn't work.

Just one last question. Is it feasible to run this as a script? I'm trying to make this into a script so the user doesn't need to meddle with the parameters and can keep a track of the log as well.

Thanks for all your help again! this makes a lot more sense now.

-Drishti

**Comment by cresil** [comment]
I've used the following to test the amplicon length and adjust trimming
parameters accordingly.

library(ShortRead)

fqf <- "XXX_R1_001.fastq.gz"
fqr <- "XXX_R2_001.fastq.gz"

numreads <- 1000

barplot(
  table(
    nchar(
      mapply(nwalign,
             as.character(readFastq(fqf)@sread[1:numreads]),

 as.character(reverseComplement(readFastq(fqr)@sread[1:numreads])))[1,])
    )
  ,las=2
  )

**Comment by benjjneb** [comment]
> Just one last question. Is it feasible to run this as a script? I'm trying to make this into a script so the user doesn't need to meddle with the parameters and can keep a track of the log as well.

Yep. You'll want to take a look at the `Rscript` command that runs R files from the command line.

Here is an example of a dada2 workflow script, although probably more elaborate than is necessary for your purposes: https://github.com/qiime2/q2-dada2/blob/master/q2_dada2/assets/run_dada_single.R

**Comment by drish91** [comment]
Thanks again. I'll check it out!
