### ISSUE TITLE
Allow Q scores > 40

### ISSUE THREAD

**Issue by benjjneb** [benjjneb/dada2#42]
Right now the dada(...) function can only handle Q scores from 0 to 40. It would be preferable to allow the range of Q scores to be user definable, as Q scores > 40 come up in various protocols.

**Comment by benjjneb** [comment]
The dada(...) function now handles Q scores over 40, many thanks to @cd-mcfarland for making this happen.

Error matrices have one column for each integer Q-score from 0 to QMAX, where we most often have QMAX=40. Now, if the maximum Q in the provided data exceeds QMAX, the matrix is extended by repeating the last column until their are enough columns.

Also, I added a new functionality to initialize the error matrix from the data itself. If err=NULL and selfConsist=TRUE, the initial error matrix is estimated by assuming all the reads are sequencing errors away from one true read (this initialization was described in Rosen et al 2012).

**Comment by cd-mcfarland** [comment]
Thanks!

Chris

On Tue, Jan 12, 2016 at 4:56 PM, benjjneb <notifications@github.com> wrote:

> The dada(...) function now handles Q scores over 40, many thanks to
> @cd-mcfarland <https://github.com/cd-mcfarland> for making this happen.
>
> Error matrices have one column for each integer Q-score from 0 to QMAX,
> where we most often have QMAX=40. Now, if the maximum Q in the provided
> data exceeds QMAX, the matrix is extended by repeating the last column
> until their are enough columns.
>
> Also, I added a new functionality to initialize the error matrix from the
> data itself. If err=NULL and selfConsist=TRUE, the initial error matrix is
> estimated by assuming all the reads are sequencing errors away from one
> true read (this initialization was described in Rosen et al 2012).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benjjneb/dada2/issues/42#issuecomment-171115862>.
>



-- 
Christopher McFarland
(518) 860-2834
