### ISSUE TITLE
DADA2: Metadata file and OTU table

### ISSUE THREAD

**Issue by kruttikaphalnikar** [benjjneb/dada2#420]
Hi all,

I am very new to DADA2/phyloseq, and have some very very basic queries, I apologise in advance!. 
I’m familiar with QIIME 1 analysis, however I want to run DADA2 as well.

I have 16s Miseq data, 250 Paired end. V3-V4 16S
I read the entire tutorial for DADA2 which is very nicely written, thank you!, I could follow most of it. 

Q1: how do I insert metadata? for example, i have 3 insect developmental stages, 5 samples each stage, total 15 samples. how and where do I insert this information? In the MiSeqSOPdata I can see a mouse.dpw. metadata file, but I can't figure out how to insert my own metadata. My entire dataset is actually much more than 15 samples, It would be extremely convenient to use a metadata file.

Q2: How do i get OTU table? or Taxa table?

When I define "ps" and run the command, i get 

phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 2230 taxa and 15 samples ]
tax_table()   Taxonomy Table:    [ 2230 taxa by 7 taxonomic ranks ]

I tried running otu_table(ps) and taxa_table(ps) but i get nucleotide sequences and not the names of taxa
I went through these threads (https://github.com/joey711/phyloseq/issues/407)(https://github.com/benjjneb/dada2/issues/260), but couldn't replicate the output

I also want to know, how to get a simple OTU table with relative abundances and sample names? something like a biom table? Can I import DADA2 output in QIIME1 (not 2)?

Thank you
Kruttika

I run these commands to get to "ps"
library("devtools")
library(dada2)
library(phyloseq); packageVersion("phyloseq")
library(ggplot2); packageVersion("ggplot2")

fnFs <- sort(list.files(pattern="_R1.fastq", full.names = TRUE))
fnRs <- sort(list.files(pattern="_R2.fastq", full.names = TRUE))
sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
sample.names

plotQualityProfile(fnFs[1:2]) 
plotQualityProfile(fnFs[1:2])

filt_path <- file.path("filtered") # Place filtered files in filtered/subdirectory
filtFs <- file.path(filt_path, paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(filt_path, paste0(sample.names, "_R_filt.fastq.gz"))

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
                     maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, multithread=TRUE) # On Windows set multithread=FALSE
head(out)

derepFs <- derepFastq(filtFs, verbose=TRUE)
derepRs <- derepFastq(filtRs, verbose=TRUE)
names(derepFs) <- sample.names
names(derepRs) <- sample.names
names(derepFs)
names(derepRs) 

errR <- learnErrors(filtRs, multithread=TRUE)
errF <- learnErrors(filtFs, multithread=TRUE)

plotErrors(errF, nominalQ=TRUE)

dadaFs <- dada(derepFs, err=errF, multithread=TRUE)
dadaRs <- dada(derepRs, err=errR, multithread=TRUE)

dadaFs[[1]]

mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE)
# Inspect the merger data.frame from the first sample
head(mergers[[1]])

seqtab <- makeSequenceTable(mergers)
dim(seqtab)
table(nchar(getSequences(seqtab)))

seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
dim(seqtab.nochim)

sum(seqtab.nochim)/sum(seqtab)

getN <- function(x) sum(getUniques(x))
track <- cbind(out, sapply(dadaFs, getN), sapply(mergers, getN), rowSums(seqtab), rowSums(seqtab.nochim))
# If processing a single sample, remove the sapply calls: e.g. replace sapply(dadaFs, getN) with getN(dadaFs)
colnames(track) <- c("input", "filtered", "denoised", "merged", "tabled", "nonchim")
rownames(track) <- sample.names
head(track)

taxa <- assignTaxonomy(seqtab.nochim, "gg_13_8_train_set_97.fa.gz", multithread=TRUE)
taxa <- addSpecies(taxa, "rdp_species_assignment_14.fa.gz")

taxa.print <- taxa # Removing sequence rownames for display only
rownames(taxa.print) <- NULL
head(taxa.print)

ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE), 
               sample_names(samdf), 
               tax_table(taxa))

**Comment by benjjneb** [comment]
> Q1: how do I insert metadata? for example, i have 3 insect developmental stages, 5 samples each stage, total 15 samples. how and where do I insert this information? In the MiSeqSOPdata I can see a mouse.dpw. metadata file, but I can't figure out how to insert my own metadata. My entire dataset is actually much more than 15 samples, It would be extremely convenient to use a metadata file.

For this you'll want to read the metadata file into R. Most commonly metadata is in some sort of comma-separated or tab-separated format, and you'll want to use the `read.table` or `read.csv` R functions. That will return a data.frame, that you can then add to the phyloseq object.

Q2: How do i get OTU table? or Taxa table?

The commands you are using are correct, but the output is being overwhelmed by the long real sequence names being used. For visual inspection, it is often useful to rename the sequence variants to something much shorter. For example (if the phyloseq obejct currently has full sequence names):

```
new.names <- paste0("ASV", seq(ntaxa(ps))) # Define new names ASV1, ASV2, ...
seqs <- taxa_names(ps) # Store sequences
names(seqs) <- new.names # Make map from ASV1 to full sequence
taxa_names(ps) <- new.names # Rename to human-friendly format
```

You can always convert back to the full sequences later using `seqs`. For example, `seqs["ASV1"]` will return the full sequence that was renamed ASV1.
