### ISSUE TITLE
dsrA amplicon analisys with DADA2

### ISSUE THREAD

**Issue by DanielC-G** [benjjneb/dada2#421]
Dear benjjneb.
I used DADA2 to process amplicons of dsrA genes, but I am not sure if DADA2 is suitable for it. The preliminary results look good but I want to take advise from you about to use DADA2 for different marker genes.

Regards.

**Comment by joey711** [comment]
There is nothing about DADA2 (the algorithm) implemented in dada2 (the package) that is specific to the gene target. The dada2 package does include some support for tasks that are 16S-specific, but these are independent downstream convenience functions, and are in no way required.

The best way to convince yourself is to sequence a control sample(s) where you know the correct answer(s) for the exact sequence(s), and evaluate how well dada2 did in returning the correct result.

**Comment by DanielC-G** [comment]
Thank you for you replay joey711, I will consider your advice.

**Comment by vfonti** [comment]
@DanielC-G 
I am considering to do something similar. How have you prepared the libraries and sequenced them?

**Comment by DanielC-G** [comment]
@vfonti 
We used the protocol of this paper [https://sfamjournals.onlinelibrary.wiley.com/doi/10.1111/1462-2920.13139](url), but using dada2: [https://link.springer.com/article/10.1007%2Fs00248-020-01631-5](url)
