### ISSUE TITLE
Dada2 learn errors

### ISSUE THREAD

**Issue by Alpacman** [benjjneb/dada2#423]
Hi everyone,
I have single end data from illumina Miseq. I have 30 samples ( so 30 fastq files). I use dada2 to analyse my datas.
I trimmed them and filtered them, no problem about that but where it comes to the learnErrors, i don't understand why it treats only 4 samples then do the convergence loop and doesn't even converge after 10 loops.
On my 30 samples, why does it only cares about 4 ?? And why it doesn't converge either ?? 
Thanks you for your answers !

**Comment by benjjneb** [comment]
`learnErrors` by default only uses up to 1 million reads, as adding more reads beyond that doesn't really change the error model at all so is unnecessary. It sounds like your samples are pretty deeply sequenced, and hence 4 samples had >1 million reads.

Non-convergence can almost certainly be safely ignored, read more in our FAQ: https://benjjneb.github.io/dada2/faq.html#what-if-the-self-consistency-loop-terminated-before-convergence

**Comment by Alpacman** [comment]
Thank you for your answer ! 
Indeed with my first four samples, I exceed 1 millions reads.
Sample 1 - 223646 reads in 154535 unique sequences.
Sample 2 - 367032 reads in 226270 unique sequences.
Sample 3 - 392117 reads in 241947 unique sequences.
Sample 4 - 306425 reads in 211496 unique sequences.
==> Thus, i don't have any error with my error model ?

**Comment by benjjneb** [comment]
> Thus, i don't have any error with my error model ?

You're good to go.

**Comment by Alpacman** [comment]
Thank you !
