### ISSUE TITLE
trimRight in filterAndTrim?

### ISSUE THREAD

**Issue by maxfarrell** [benjjneb/dada2#424]
Hi,
I'm putting together my first dada2 pipeline, and have done MiSeq 250x2 runs to amplify the V3-V4 region of 16S. This means that I'm left with very little excess length to remove during the filter and trim step.

Since both V3 and V4 have biological length variability, I'm worried whether it makes sense to use a hard length cutoff for trimming and filtering. 

In my case I think it might be best to remove very short reads (would I do this with the minLen argument?), and to remove a certain number of base pairs from the right side of the reads (ideally maybe 5 from each forward read, and 10 from each reverse read.

In order to remove some low quality basepairs from the end of the reverse read, I wonder if there is a function to trimRight, rather than trimLeft, or if I could easily augment the function to do this?

Any thoughts on how best to do this, or whether it makes sense would be greatly appreciated!

**Comment by benjjneb** [comment]
There isn't a whole lot of length variability in V3V4, but you are right to leave some wiggle room. 20+15nts total length (between the F/R reads) more than your expected amplicon length should be good enough though. More is fine too.

The parameter you are probably looking for is `truncLen`. This will remove all reads less than `truncLen`, and also truncate the reads at `truncLen`.

As long as your 250nts reads won't read all the way through past the other primer (they won't in this case) this approach will get you where you want to go.

**Comment by maxfarrell** [comment]
Thanks Ben!

I already removed my primers, but I worry about using tuncLen because I do observe some variability in the reads. I ran the pipeline without any trimming and find a bimodal distribution of paired lengths with peaks around 402bp and 425bp (also slightly bimodal in itself).

With truncLen, I understand that this truncates sequences at this length, but also removes any sequences not this length, therefore if I use it to try to remove the final 10bp I'm not sure at what length to really do this without either removing some potentially useful shorter reads or losing potentially informative sections of the longer reads.

I hope I'm being clear! Looking at the quality profiles there isn't a clear dropoff in quality across samples, but the final few basepairs are always really wonky...

**Comment by benjjneb** [comment]
`truncLen` is enforced on the F/R reads before merging. You'll still get that length variation after merging, you'll just want to make sure that your total `truncLen` is at least 445 (to have 20nts overlap on the longest merged amplicon). Diagram (F:Forward read, R:Reverse read, M: merged sequence):

```
FFFFFFFFF240FFFFFFFF
          RRRRRRRRR240RRRRRRRR
MMMMMMMMM402-425MMMMMMMMMMMMMM
```

**Comment by maxfarrell** [comment]
Great, I ended up truncating the forward reads to 230 bp, and the reverse reads to 220bp. I don't seem to loose too many when attempting to merge, however I notice now that the number of ASVs has shit up considerably:  from ~2700 before performing length truncation to ~3500 ASVs resulting from the pipeline with length truncation. Inspecting both, just under 2000 of the ASVs are identical among the two pipelines.

I was under the impression that removing excess length and reads should typically decrease perceived diversity. Maybe I should open a new thread, but is this normal behaviour?

**Comment by benjjneb** [comment]
> I was under the impression that removing excess length and reads should typically decrease perceived diversity. Maybe I should open a new thread, but is this normal behaviour?

Yep it is expected, although counter-intuitive on first glance.

The low-quality ends of the reads cause the error-free fraction of reads to be lower, which lowers the algorithms sensitivity to rare variants. When you trimmed those off, you got higher sensitivity to rare variants, which you are seeing in your table.

It's a good thing!
