### ISSUE TITLE
Merge paired ends

### ISSUE THREAD

**Issue by cmaietta** [benjjneb/dada2#425]
Hi folks,

I am working through the dada2 pipeline for the first time and I cannot resolve a problem with the mergePairs step.  

`mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE, maxMismatch = 2, minOverlap = 10)`
`head(mergers[[1]]) `

As you can see in the table below, very few sequences are successfully merging.  

#sample     input      filtered   denoised   merged
#CEM01     46554    44619    44619        97            
#CEM02     38805    37307    37307        10       
#CEM03     60761    58398    58398        23           
#CEM04     62226    60004    60004      229         
#CEM05     60304    57954    57954       89           
#CEM06     55714    53428    53428       69      

Background: I amplified the 16S region using the F515/R806 primers from 24 soil samples.  All of the sequences were generated on a MiniSeq platform using Illumina's 300 cycle kit (2 x 150).  I am processing the demultiplexed fastq files on my Mac using R 3.4.3 and the latest version of dada2 (1.6.0). I have attached a copy of my code (heavily annotated) and results from the various steps.

I have tried several approaches to resolve this error (e.g., relaxing the maxMismatch, minOverlap, maxEE, and turncLeng parameters), but nothing seems to influence the mergePairs output.  At one point I was concerned that the 300 cycle kit did not produce sufficient overlap; however, based on my conversations with Illumina, readings (ref 1 and 2 attached), and discussions with my colleagues, I have come to the conclusion that there should be a 46 bp overlap between the forward and reverse reads.  I am further convinced that there should be sufficient overlap because another individual is processing different samples from this run in QIIME (version 1.9.1), and she did not run into issues joining the 16S forward/reverse paired ends using the multiple_joined_paired_ends.py script. I have considered switching to the QIIME platform, but I would like to understand and resolve this problem in dada2.  

Any thoughts about the underlying problem and some suggestions on how to resolve this issue would be appreciated.

Thanks for reading!

- Christine

[R Code for DADA2 (Mar 3 2018).docx](https://github.com/benjjneb/dada2/files/1777774/R.Code.for.DADA2.Mar.3.2018.docx)
[Quality Profile for fnFs (4).pdf](https://github.com/benjjneb/dada2/files/1777775/Quality.Profile.for.fnFs.4.pdf)
[Quality Plot for fnRs (4).pdf](https://github.com/benjjneb/dada2/files/1777777/Quality.Plot.for.fnRs.4.pdf)
[Error Plot for ErrF .pdf](https://github.com/benjjneb/dada2/files/1777778/Error.Plot.for.ErrF.pdf)
[Error plot for errR.pdf](https://github.com/benjjneb/dada2/files/1777779/Error.plot.for.errR.pdf)
[DerepFs.docx](https://github.com/benjjneb/dada2/files/1777780/DerepFs.docx)
[derepRs.docx](https://github.com/benjjneb/dada2/files/1777781/derepRs.docx)
[dadaFs with convergence check .docx](https://github.com/benjjneb/dada2/files/1777782/dadaFs.with.convergence.check.docx)
[dada$s with convergence check.docx](https://github.com/benjjneb/dada2/files/1777784/dada.s.with.convergence.check.docx)

**16S Amplicon Overlap (ref 1)** 
[appnote_miseq_16S.pdf](https://github.com/benjjneb/dada2/files/1777740/appnote_miseq_16S.pdf)
**16S Amplicon Overlap (ref 2)**
[journal.pone.0176716.pdf](https://github.com/benjjneb/dada2/files/1777742/journal.pone.0176716.pdf)

**Comment by benjjneb** [comment]
Looking at that output, everything looks like its working great until merging...

Two guesses: The sequencing center returned reads not in the expected orientation (e.g. they already reverse-complemented the reverse reads), or your primers are included on your reads (hence ~7nts of overlap instead of 46).

Could you share the output of the following?

```
head(dadaFs[[1]]$clustering)
head(dadaRs[[1]]$clustering)
head(mergers[[1]])
```

**Comment by cmaietta** [comment]
Thank you for your response. Here is the information you requested (+ our primer sequences):

Christine

F515 (adapter-loci): TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG-GTGCCAGCMGCCGCGGTAA
R806 (adapter-loci): GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG-GGACTACVSGGGTATCTAAT

`head(dadaFs[[1]]$clustering)`

sequence
1 GTGCCAGCAGCCGCGGTAATACGTAGGGGGCGAGCGTTGTCCGGAGTTACTGGGCGTAAAGCGCCCGCAGGCGGTCGGTCGCGTTTGAGGTAACAGCTCCTGGCTTACCTGGGAGAGCGTCTCAAAGACGGGCTGACTTGAGGACCAGAG
2 GTGCCAGCAGCCGCGGTAAGACGAACCGTGCGAACGTTATTCGGAATCACTGGGCTTAAAGCGCGTGTAGGCGGATGGGAACGTCGGATACTGAAAGCCCCCGGCTCAACCGGGGAAGTGGTTCCGAAACGACCTGTCTGGAGGGACGTA
3 GTGCCAGCAGCCGCGGTAATACGTAGGAGGCGAGCGTTGTCCGGAGTTACTGGGCGTAAAGTGCACGCAGGCGGTCTGTTAAGTTCACGGTGACAGTCATCAGCTTAACTGGTGAAGTGTCTTGAAAACTGACGGACTTGAGGGCCAGAG
4 GTGCCAGCCGCCGCGGTAATACGTAGGGGGCGAGCGTTGTCCGGAGTTACTGGGCGTAAAGCGCCCGCAGGCGGTCGGTCGCGTTTGAGGTAACAGCTCCTGGCTTACCTGGGAGAGCGTCTCAAAGACGGGCTGACTTGAGGACCAGAG
5 GTGCCAGCAGCCGCGGTAATACCAGCTCCCCGAGTGGTTGGGACGATTATTGGGTCTGAAGCGTCCGTAGCCGGCCGGAAAAGTTCCCCGTTAAATCTGGCGATCCAATCGTTGGGCTGCGGGGAATACTCTTCGGCTTGGGGGCGAGGG
6 GTGCCAGCCGCCGCGGTAAGACGAACCGTGCGAACGTTATTCGGAATCACTGGGCTTAAAGCGCGTGTAGGCGGATGGGAACGTCGGATACTGAAAGCCCCCGGCTCAACCGGGGAAGTGGTTCCGAAACGACCTGTCTGGAGGGACGTA
  abundance   n0       n1      nunq     pval     birth_type    birth_pval    birth_fold       birth_ham    birth_qave
1      2101        1251    186     789     NaN          I               NA                        NA                 NA         NA
2      1341         997    217     256       0            A                 0                 1.192910e+90      40        35.91453
3       882         616    160      195       0           A                 0                5.446393e+49      22        35.94864
4       682         542     73       129       0          A                  0                  1.410888e+01       1         36.86973
5       608         462     85      131        0          A                   0                 1.181285e+122    51        36.00483
6       568         437     78      120        0          A                   0                  1.679788e+02      1        36.62019
 
`head(dadaRs[[1]]$clustering)`

sequence
1 GGACTACGGGGGTATCTAATCCCGTTCGCTCCCCTAGCTTTCGCCCCTGAGCGTCAGGTACCAGCCAGGACACTGCCTGCGCCTTCGGTGTTCCTCCGGATATCTACGCATTTCACCACTCCACCCGGAATTCCGTGTCC
2 GGACTACGGGGGTATCTAATCCGGTTCGCTCCCCCAGCTTTCACCCCTCACCGTCGAGCGCGTTCTGGCGGACCGCCTTCGCCACTGGTGGTCTTCCGCGGATCAAAGGATTTTACCCCTACACGCGGAGTACCGTCCGC
3 GGACTACAGGGGTATCTAATCCGGTTCGCTCCCCCAGCTTTCACCCCTCACCGTCGAGCGCGTTCTGGCGGACCGCCTTCGCCACTGGTGGTCTTCCGCGGATCAAAGGATTTTACCCCTACACGCGGAGTACCGTCCGC
4 GGACTACGGGGGTATCTAATCCCGTTTGCTCCCCTAGCTTTCGCGTCTCAGCGTCAGCAGACGTCCAGGACCTCGCTTTCGCCACGGGCGTTCCTTCCGATCTCAACGCATTTCACCGCTCCACCGGAAGTTCCAGATCC
5 GGACTACCGGGGTATCTAATCCGGTTCGCTCCCCCAGCTTTCACCCCTCACCGTCGAGCGCGTTCTGGCGGACCGCCTTCGCCACTGGTGGTCTTCCGCGGATCAAAGGATTTTACCCCTACACGCGGAGTACCGTCCGC
6 GGACTACACGGGTATCTAATCCGGTTCGCTCCCCCAGCTTTCACCCCTCACCGTCGAGCGCGTTCTGGCGGACCGCCTTCGCCACTGGTGGTCTTCCGCGGATCAAAGGATTTTACCCCTACACGCGGAGTACCGTCCGC

  abundance  n0    n1      nunq    pval     birth_type     birth_pval   birth_fold            birth_ham    birth_qave
1       835      448   107     325          0          I                        NA              NA                NA               NA
2       594.    439   106      116          0          A                        0        2.941974e+66    28                35.28364
3       517      403    66        92          0          A                        0        3.900230e+01      1                36.21608
4       485     335   101        93          0          A                        0        1.182142e+55     24               35.14129
5       414      330    48        75          0          A                        0        3.891273e+01       1               36.59816
6       434     326    67         81          0          A                        0        7.432397e+01       1               36.87692

`head(mergers[[1]])`

  sequence abundance forward reverse nmatch nmismatch nindel prefer accept
1                             485       1            1              63        39            12      1         FALSE
2                             305       2           4              70        30            19      1         FALSE
3                             284       1          30             66        37            14      1         FALSE
4                             247       2            8             69        31            19      1         FALSE
5                             237       1           43            63        39            11      1         FALSE
6                             229       1             9            62        41             10      1        FALSE

**Comment by benjjneb** [comment]
Yep, so the problem here is (2), your primers are on your reads hence you have very little overlap between the reads. The amplicon overlap ref (1) you shared calculates the overlap on the assumption that the primers themselves are not on the reads, as is the case in some but not all library preps. However, in yours, the primers are on the reads (see code below) hence you have 39 less nts of overlap (the length of th primers) than you expected, or 7 total bases of overlap. And you've trimmed off the last 10nts of the R read, so you actually have no overlap -- hence no merging.

The dada2 R package isn't set up by default to handle such small overlap, but here is how you can probably get it to work.

First, you have to truncate both F and R reads at 150nts, can't cut anything off the end. Second, you'll need to install the current development version of the dada2 R package which has an updated `mergePairs` that handles this edge case better. Then use the following command for merging:

```
# Easiest way to install devel-version of dada2
library(devtools)
devtools::install_github("benjjneb/dada2")
# Now merge with low minOverlap
`mergePairs(ddF, drpF, ddR, drpR, minOverlap=4) 
# Or possibly minOverlap=5, but need to account for some biological variation in amplicon length
```

Let me know if that works!

**Comment by cmaietta** [comment]
It worked!

`packageVersion("dada2") #verify installment
[1] ‘1.7.7’
mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE, minOverlap = 5)`
...
`head(track)`
 Sample   input       filtered   denoised merged  tabled   nonchim
CEM01    46554    39899    39899     34083   34083   23585
CEM02    38805    31027    31027       27824   27824   18801
CEM03   60761    50543    50543      41259   41259   28642
CEM04    62226    55839    55839     45210   45210   31308
CEM05   60304    51416    51416       42443   42443   30025
CEM06    55714    45485    45485      38067  38067   27134

Thank you for taking a look and for providing a solution.  I will compare the merged, forward, and reverse read datasets to validate the taxonomic assignments and patterns. I will post an update in the next week or two.

**Comment by benjjneb** [comment]
Great!

One important thing I forgot to mention: You really, really should remove the primers on these reads at the start. 

DADA2 detects even single-nucleotide variation, and your primers have some ambiguous nucleotides in them, that will falsely appear to the algorithm as if there is real variation at those positions.

You can remove them with dedicated external programs like cutadapt, or with the `trimLeft` parameter in the `filterAndTrim` function:

```
filterAndTrim(..., trimLeft=c(19,20)) # Forward primer is 19nts, Reverse is 20nts
```

*this should further improve the fraction of reads that merge and that pass the chimera check*

**Comment by benjjneb** [comment]
Please re-open as needed for updates or further concerns.

**Comment by Aircus** [comment]
Hi, Benjjneb,
I also had a similar problem that lost 90% of the reads at the merge step. I went through your suggestion, then I changed my code from (Suggested by Figaro):

truncLen=c(282,240), maxEE=c(1,2), truncQ=2, maxN=0, rm.phix=TRUE,
compress=TRUE, verbose=TRUE, multithread=TRUE);
...
 merger <- mergePairs(ddF, derepF, ddR, derepR, verbose=TRUE)
    mergers[[sam]] <- merger

_to:_

truncLen=c(282,240), **maxEE=c(2,5), trimLeft=c(21,21)**, truncQ=2, maxN=0, rm.phix=TRUE,
compress=TRUE, verbose=TRUE, multithread=TRUE);
...
 merger <- mergePairs(ddF, derepF, ddR, derepR, **minOverlap = 5, maxMismatch = 0,** verbose=TRUE)
    mergers[[sam]] <- merger

I used to use cutadaptor to remove the adaptors but I usually leave the 16s primers (F304/R806) there. Now I also removed them by adding the code trimLeft=c(21,21). Now I can get almost around 50% of my input reads. 
See below:
> head(track);
           input filtered and denoised merged tabled nonchim
VB1-C1-0-1 22122                 20869   9343   9343    8910
VB1-C1-1-3 20581                 19165   7253   7253    6704
VB1-C2-0-1 24049                 22265   9286   9286    8618
VB1-C2-1-3 26744                 25205  12360  12360   11694

What do you think I can do to make it better?
Thanks in advance! Have a nice weekend!

Tong

**Comment by benjjneb** [comment]
The V3V4 region has a substantial bimodality in its length distribution in nature, with the longer mode about 20nts longer than the shorter mode. You are sequencing a roughly 500nt amplicon based on the primer names, and only keeping ~520nts of sequence after `truncLen`. My guess is that you are losing the longer V3V4 sequences. You can test that by increasing `truncLen` to sum up to ~545.

**Comment by Aircus** [comment]
> The V3V4 region has a substantial bimodality in its length distribution in nature, with the longer mode about 20nts longer than the shorter mode. You are sequencing a roughly 500nt amplicon based on the primer names, and only keeping ~520nts of sequence after `truncLen`. My guess is that you are losing the longer V3V4 sequences. You can test that by increasing `truncLen` to sum up to ~545.

Hi!
Thanks a lot for your reply!
I just tried the change trancLen to c(295, 250) but it didn't improve the result. For some samples, the nonchinm reads even reduced a bit. Are there any other possibilities?

**Comment by Aircus** [comment]
> 

Thanks a lot for your suggestions! really helpful! I will give a try!
Have a nice day! :)

**Comment by srishti8724** [comment]
Hi Benjjneb,
I am working with DADA 2 for the first time. I am facing problem with Merging command which I am not able to resolve. 
mergers <- mergePairs (dadaFs, filtFs, dadaRs, filtRs, verbose=TRUE, maxMismatch = 2, minOverlap = 5) 
As you can see in the table below, very few sequences are successfully merging.
abundance forward reverse nmatch nmismatch nindel prefer accept
187         82     797    1199      5         0      0      1   TRUE
7310         2     570     305      5         0      0      2   TRUE
7451         2     526    1379      6         0      0      1   TRUE
7497         2    1141     395      5         0      0      2   TRUE
7709         2    1011     305      5         0      0      2   TRUE
8527         2     617     571     87         0      0      1   TRUE

I amplified the 16S region V3-V4 region of 9 soil samples. All of the sequences were generated using Illumina's  MiSeq 2 x 300. I am processing these fastq files on using the latest version of dada2 (1.28). I have tried several approaches to resolve this error (e.g., relaxing the minOverlap), but there is no change in the mergePairs output. 
Can you please suggest how to solve it? 
16s amplicon Forward primer-5'TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTACGGGNGGCWGCAG3’
16s amplicon Reverse Primer 5'GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGGACTACHVGGGTATCTAATCC3’
