### ISSUE TITLE
Problem with "track"

### ISSUE THREAD

**Issue by JackouilleS** [benjjneb/dada2#426]
Hello!

I used the tutorial dada2 on my samples, and I was looking at my track table to see if the pipeline went correctly, and I saw something unexpected. Here is a table which sums the total number of sequences in all samples for each step : 

Input | Cleaned | denoised | tabled | Merged | non-chimeras
805126 | 773172 | 773416 | 766676 | 766676 | 763711

As you can see, the number of total reads after denoising is higher than the number of reads cleaned, which strikes me as weird. 

I looked in detail at my track, and it showed that (I highlighted in colors the  numbers that are similar from one line to another, and it looks like there was some overlap from one line to another)
![track](https://user-images.githubusercontent.com/36447484/36988806-1010fa6c-20a0-11e8-8be8-889a178d17d7.JPG)

It starts at the sample "26-1-S8-L001_R1-001.fastq" and keeps going to the end of the track. I feel it is important to mention I had to used the "exist" command, because all the samples did not pass the filter I used (and it actually stop at the 26-1 sample). Maybe you would be able to tell me what happened here ?

Also, I get this message when I do the track command : 
>track<-cbind(out, sapply(dadaF, getN), sapply(mergers, getN), rowSums(seqtab), rowSums(seqtab.nochim))
Warning message:
In cbind(out, sapply(dadaF, getN), sapply(mergers, getN), rowSums(seqtab),  :
  number of rows of result is not a multiple of vector length (arg 2) 

Thank you and have a good day :)

**Comment by benjjneb** [comment]
That warning was caused by the files lost during filtering, and is causing the problem you're seeing. The `out` matrix has rows for the samples that failed to pass the filter, the other vectors don't, and its giving you a misaligned final matrix.

You can fix this by first setting `out <- `out[file.exists(filtF),]`, to throw away the rows that were lost during filtering.

**Comment by JackouilleS** [comment]
It worked thank you very much !

**Comment by mochirba** [comment]
> That warning was caused by the files lost during filtering, and is causing the problem you're seeing. The `out` matrix has rows for the samples that failed to pass the filter, the other vectors don't, and its giving you a misaligned final matrix.
> 
> You can fix this by first setting `out <- `out[file.exists(filtF),]`, to throw away the rows that were lost during filtering.

I'm having a very similar problem, I'm running the dada2 1.8 pipeline & after filtering a bunch of my controls were causing problems during the dereplicating step, but with your help I was able to tell it to only use samples that exists after filtering. Now, I'm trying to track & create csv file with cbind, but I'm getting the same error. I think after I'm losing samples after merging & creating issue with unequal row. Do you know how I can fix this? I tried the suggestion above, but it didn't work. 

"In cbind(out3, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers,  :
  number of rows of result is not a multiple of vector length (arg 2)"
