### ISSUE TITLE
Extraction of ITS region prior to taxonomic assignemnt

### ISSUE THREAD

**Issue by gcuster1991** [benjjneb/dada2#428]
Using DADA2 is it necessary to extract the ITS region using something like ITSx( http://microbiology.se/software/itsx/) prior to taxonomic assignment? If so how would one go about this?

**Comment by nagasridhar** [comment]
You can use the standard DADA2 workflow and at the taxonomic assignment step, you can point it to UNITE database. That will help you assign taxonomy to your dataset.

**Comment by gcuster1991** [comment]
Hi @nagasridhar,
Thank you for the response.  I have used the UNITE database but I'm trying to understand how ITS taxonomic assignment via DADA2 (without ITSx) compares to other methods that first extract the ITS region.  

Is there something in the DADA2 pipeline that replaces this or does the same function?

thanks

**Comment by benjjneb** [comment]
@gcuster1991 I saw that you posted on another issue, did you get this issue resolved?

**Comment by gcuster1991** [comment]
It appears others are using ITSx to safely remove sequences which haven't assigned to K__Fungi.  I believe this answers my question. Thank you.
