### ISSUE TITLE
Importing a seqtab from qiime2

### ISSUE THREAD

**Issue by Rae309** [benjjneb/dada2#430]
I have processed my data using qiime2::dada2, but I would like to use the feature --collapse-no-mismatch which is not available for the qiime2 plug-in.  Is there a way to import the qiime2 output into R in the correct seqtab format to use this feature without re-processing everything?

**Comment by benjjneb** [comment]
QIIME2 "artfeacts" are in fact zip files with a custom file extension. First you'll want to unzip the file, then take a look in the "data" directory inside.

There should either be a Q1 style sequence table (probably a tsv) or a biom file in there. Can you tell us what you find? Both types of files can be imported into R, but in different ways.

**Comment by Rae309** [comment]
When I export the qiime2 artifacts, the feature table and rep seqs are exported separately so I have a .biom feature table and a .fasta rep seqs file.  Right now the feature IDs are the md5 hashes of the rep seqs, so I’m not sure how to collapse the rep-seqs and then be able to apply that info back to collapsing the feature table.

**Comment by benjjneb** [comment]
Hm... I'm sure it can be done, but we probably need to investigate more to figure out just how to do it.

Does Q2 have an export to biom function by chance? That doesn't leave you stuck with the hash IDs instead of the sequences?

**Comment by Rae309** [comment]
I've only generated a dada2 feature table using qiime2, so I'm not really sure what kind of information needs to be included or what kind of format I'm aiming for.  Is it something like below where the feature "name" is actually the ASV sequence?  I could generate that in either .biom or .tsv format, whichever is easier to import as a seqtab.

Feature | Sample1 | Sample2 | Sample3
TGAGGA...| 2 | 14 | 25
TCGAGA... | 54 | 36 | 44
TCGGGA...| 13 | 75 | 8

**Comment by benjjneb** [comment]
Yeah, if you can make a tsv table w/ the seq names, or a biom (v1, json format), those can be readily imported into R.

I'd probably make a tsv, and then use `read.table` to get it into R. You might have to mess with a few of the function parameters (`header`, ...) depending on exactly how the tsv is formatted. See `?read.table`

**Comment by Rae309** [comment]
Importing the data in the format below as a .tsv allowed me to collapseNoMismatch.  Thanks for your help.

              | TGAGGA...|TCGAGA...|TCGGGA..
Sample1 | 2 | 54 | 13 |
Sample2 | 14 | 36 | 75 |
Sample3 | 25 | 44 | 8 |

**Comment by benjjneb** [comment]
Great! If you have the chance to post what you did in a little more detail, I'm sure other folks would benefit later.
