### ISSUE TITLE
HOMD taxonomic training data 

### ISSUE THREAD

**Issue by mdavrandi** [benjjneb/dada2#431]
Hi, 

I am working with oral samples and I would like to use human oral microbiome database (HOMD, HOMD_16S_rRNA_RefSeq_V15.1) for taxonomy/species assignments. However, I am having trouble with the formatting and I was wondering if I can get some help with this.

Thanks

**Comment by benjjneb** [comment]
We don't have HOMD training fastas pre-made, but the format requirements are described here:

https://benjjneb.github.io/dada2/training.html#formatting-custom-databases

**Comment by ad-robins** [comment]
Hi benjjneb,

I am also using the HOMD for a different pipeline and comparing the results to dada2. I was able to format the HOMD library correctly for dada2, however I'm not sure if it is comparable to using silva or gg. The HOMD fasta has a set of 16S sequences that are specific to species. Would it make sense to run assignTaxonomy() and then addSpecies() using two files formatted appropriately for the commands, but with the same species-specific sequences? Or should assignTaxonomy() only be used for higher-level taxa reference? Thank you for this great tool

**Comment by benjjneb** [comment]
> Would it make sense to run assignTaxonomy() and then addSpecies() using two HOMD reference files formatted appropriately for the commands, but both containing the same species-specific sequences? Or should assignTaxonomy() only be used for higher-level taxa reference? Thank you for this great tool

This is a big question that goes beyond the dada2 package: When is species-level assignment appropriate from partial 16S data?

`assignSpecies` only assigns species when matching is exact, as suggested by some recent publications (e.g. https://doi.org/10.1093/bioinformatics/bty113). However, it often is appropriate to assign species at more fuzzy thresholds when you have a curated environment-specific database that you think is fairly complete, as in the case of HOMD.

So, I don't have a definitive answer for you. I might start with `assignTaxonomy` down to species.

**Comment by ad-robins** [comment]
Thank you for your fast response, this was helpful. I can understand a little better how assignTaxonomy() and assignSpecies() differ. Best

**Comment by sklucas** [comment]
Hi @ad-robins,
Did you have luck with the HOMD database? Would you be interested in sharing your formatted database?

**Comment by fconstancias** [comment]
I would also be interested ...

**Comment by fconstancias** [comment]
@ad-robins, @sklucas were you able to format HOMD to be used with dada2?

**Comment by fconstancias** [comment]
@ad-robins , @sklucas , @mdavrandi  and oral microbiome folks, 
You can find the latest eHOMD database formated for dada2 (i.e. `dada2::assignTaxonomy(seqs, "eHOMD_RefSeq_dada2_V15.22.fasta.gz"` and `dada2::addSpecies(taxa, "eHOMD_RefSeq_dada2_assign_species_V15.22.fasta.gz", verbose=TRUE)`  [here](https://github.com/fconstancias/metabaRpipe/tree/master/databases)

**Comment by otaviolovison** [comment]
> @ad-robins , @sklucas , @mdavrandi and oral microbiome folks, You can find the latest eHOMD database formated for dada2 (i.e. `dada2::assignTaxonomy(seqs, "eHOMD_RefSeq_dada2_V15.22.fasta.gz"` and `dada2::addSpecies(taxa, "eHOMD_RefSeq_dada2_assign_species_V15.22.fasta.gz", verbose=TRUE)` [here](https://github.com/fconstancias/metabaRpipe/tree/master/databases)

Thank you so much! 'Starred'!
