### ISSUE TITLE
Integer Overflows

### ISSUE THREAD

**Issue by cd-mcfarland** [benjjneb/dada2#432]
Hi Ben, 

On very large datasets, I encounter an integer overflow warning. Its hard to pinpoint the location based on the warning:

`1: In f(init, x[[i]]) : NAs produced by integer overflow`

The size of this dataset would exceed 32-bits in, at minimum, the derep transition matrix. Is it possible for DADA2 to support 64-bit integers? 

Chris

**Comment by benjjneb** [comment]
Can you clarify exactly what command is generating this error? And how many reads are in a sample or study that is causing this? Narrowing this down will help a lot in deciding where action is needed.

Background: Integers in R are 32-bit, so scale up to 2147483648 (2 billion). I assume that your dataset must have >2B reads you are processing together (i.e. not by sample). However, in practice numbers of reads well beyond 2B should work, provided that no specific sequences is repeatedly observed >2B times. It is possible though that there is a "bug" in the way we've coded things that overflows when just total reads hits the 2B limit...

Notes to self: An option for really large datasets would be switching to doubles (supported natively by R), but that's not a totally trivial change to make as the C-side code uses 32-bit integers for read counts throughout. If changing the reads type C-side, care needs to be taken wrt the call back into R to calculate the p-value, which uses the reads variable.

**Comment by cd-mcfarland** [comment]
My apologies for not creating a minimal reproducible example, but it sounds like the issue is that I'm using close to 2B reads of the same sequence. The potentially-relevant commands that generates this error in R version 3.4.3 and ShortRead version 1.34.2:
```R
setDadaOpt( 
            MIN_HAMMING=2,  
            MIN_FOLD=2,
            USE_QUALS=TRUE, 
            BAND_SIZE=4,
            VECTORIZED_ALIGNMENT=FALSE, 
            USE_KMERS=TRUE,
            MAX_CONSIST=200)      

dadas <- dada(  dereps,
                OMEGA_A=1e-300,
                selfConsist=TRUE,
                err=NULL,
                MAX_CONSIST=200,
                multithread=TRUE)
```

In my case, I'm simply using DADA2 to estimate a read-error model from segments of amplicon reads that are all expected to be the same sequence. DADA2 still runs in <5 minutes on 80 samples when >99% of reads fall within one cluster, but I can nevertheless split these samples apart to avoid this issue if its hardwired into R. I'm actually only using ~1.2B reads of the same sequence, but I imagine the transition matrix exceeds 2B for certain entries, e.g. A2A rates of a common PHRED score, as there are 50 nucleotides per read. 

I still want to estimate a single read-error model from all 80 samples, but ```loessErrfun``` seems to work on transition matrices that I coerce into double-precision floating point values (and will raise this interger overflow warning otherwise).

**Comment by benjjneb** [comment]
> I'm actually only using ~1.2B reads of the same sequence, but I imagine the transition matrix exceeds 2B for certain entries, e.g. A2A rates of a common PHRED score, as there are 50 nucleotides per read.

Ah, yep, that's probably it. And that should be much easier to fix, basically by changing to double/numeric for the trans output matrix (as in your workaround). Would need to also do in the C-side function that constructs that matrix for competeness...

Adding this as enhancement, but not sure when I will get to it. I think your workaround (run individually, coerce `$trans` to numeric, sum, run `loessErrfun` on each) will probably work for now, but let me know if not.

**Comment by cd-mcfarland** [comment]
Thanks! The workaround I'm doing seems to work fine.
