### ISSUE TITLE
learnErrors step in dada2 workflow - source of errors to be modeled

### ISSUE THREAD

**Issue by mhibberd** [benjjneb/dada2#434]
My group is very interested in the dada2/ASV approach to 16S analysis, but I have a conceptual hangup that I've been unable to clarify for myself based on my lit searches to date. In particular, I'm interested in the sources of error that the dada2 approach seeks to account for in the "learnErrors" step of the R workflow. This becomes important in our specific (perhaps not unique) case because our amplification strategy creates libraries that can be sequenced in either orientation - i.e. the F OR the R primer can be incorporated into the Illumina R1 (or R2) read during sequencing. Thus, simply reorienting reads so they're all in the same orientation could introduce some R1/R2 bias if the "learnErrors" step is targeted toward the sequencer-based error. Otherwise, if the error modeled in this step is intrinsic to the sequences themselves then it's not an issue to simply reorient the reads.

Any guidance is appreciated!

**Comment by benjjneb** [comment]
In our recommended workflow, we suggest learning the error model individually for the forward reads and the reverse reads. In many (most) cases this isn't necessary, because the F/R error models are essentially identical (it's the same machine and same run after all) but we recommend it because we have observed some cases in which they are not the same.

In your case I would recommend the following. Run `learnErrors` on the F and R reads separately, before correcting orientations. Compare the resulting models, which are 16x41 matrices of the error rates for each of the 16 transitions (e.g. A2A, A2C...) and Q scores (0-41). Visually you can do that with `plotErrors(errF)` and `plotErrors(errR)` or you can get more quantitative by pulling out the raw error matrices (`errF$err_out`) and working on them in R.

If they are very similar, as is likely, I recommend the following procedure:

Define a new error matrix with entries that is the maximum of the two, i.e. `errM <- pmax(errF, errR)`.
Define a truncation length that is the same for the F/R reads, i.e. `truncM <- 225`
Reorient your reads (will need an external program for that).
Filter and trim, using `truncM` for both F/R.
Denoise w/ dada2 using `errM` for both F/R.

This is a pretty defensive strategy, and things probably will work quite well if you don't bother, but this protects against the possibility of slightly different error models in the F/R reads leading to false positives after the reorientation mixes them together.

Hope that helps! If the error models learned from the F/R reads are very different, then maybe a different approach is better, but that probably won't be the case.

**Comment by benjjneb** [comment]
Feel free to reopen as necessary.

**Comment by boopsboops** [comment]
Just a quick follow up to this somewhat related question: 

I'm also trying to deal with the issue of reads in mixed orientations in paired-end Illumina output. My first attempt was to: (1) merge R1 and R2 in PEAR; (2) reorientate the reads to the same direction; (3) trim off primers with cutadapt; and (4) run the dada2 workflow as a single-end dataset. 

However, the typical quality profile I get is nothing like the error model is expecting (see below)? Is this a problem? Can dada2 estimate errors effectively this way on merged reads? Is there a better way?

![rplot](https://user-images.githubusercontent.com/5559735/46810985-bc58da80-cd69-11e8-9758-9ac0e2684689.png)

Thanks, and great software by the way!

**Comment by benjjneb** [comment]
We do not recommend merging reads with PEAR prior to running dada2, and have speficially seen that this commonly causes problems. The issue is that the quality scores assigned by PEAR are not equivalent to those assigned by the sequencer (as suggested by your plot).

**Comment by eolesin** [comment]
Hi @benjjneb, 

I've been struggling for quite awhile now with a mixed orientation dataset produced by vendor Mr. DNA. The R1 and R2 files have a mixture of orientations of reads. I have asked the vendor for a directional version of the dataset, though the outcome of that request was not correct. I have demultiplexed and primer trimmed using Sabre and bbduk, respectively, first running each program in one orientation and then the other, which produces four total directional files (R1=F, R2=R, R1=R, R2=F) to import to dada2.  Do you think it's better for me to stay this course, and just join tables later downstream in dada2, or is it best to reorient the reads during preprocessing? I'm worried that reverse-complementing reads will mess with error rates. Thank you for any advice you can give, I'm a bit of a newbie to dada2 and I've been stalling on creating this post for some time.

**Comment by benjjneb** [comment]
> I've been struggling for quite awhile now with a mixed orientation dataset produced by vendor Mr. DNA. 

Ah Mr. DNA and their infamous random orientation amplicon datasets.

> Do you think it's better for me to stay this course, and just join tables later downstream in dada2, or is it best to reorient the reads during preprocessing? I'm worried that reverse-complementing reads will mess with error rates.

I think probably just due as you suggest, and run different orientations through the dada2 pipeline separately before merging. My concern is that the pairing has been messed up by the re-orientation though...

**Comment by eolesin** [comment]
Hi @benjjneb, 

I have run the different orientations separately then merged. I don't think the pairing has been an issue when I perform it this way... rather there remain a few contaminant sequences that are still in the wrong orientations.

Full dataset after demultiplexing with Sabre:
                 Forward Complement Reverse RevComp
FWD.ForwardReads    6245          0       0       0
FWD.ReverseReads       2          0       0    5962
REV.ForwardReads       1          0       0    6111
REV.ReverseReads    5894          0       1       0

When I use either cutadapt or bbduk to separate orientations, the primers sometimes remain when they should not. When I perform primer checking after primer trimming, I still see a handful of sequences that contain the primers... 

I'm really grateful for the addition of the primer presence QC section in the ITS pipeline for dada2, by the way.

First orientation of primer-trimmed reads, trimmed using bbduk:
                 Forward Complement Reverse RevComp
FWD.ForwardReads       0          0       0       0
FWD.ReverseReads       0          0       0      30
REV.ForwardReads       0          0       0      30
REV.ReverseReads       0          0       0       0

Second orientation of primer-trimmed reads, trimmed using bbduk:
                 Forward Complement Reverse RevComp
FWD.ForwardReads       0          0       0       2
FWD.ReverseReads       0          0       0      49
REV.ForwardReads       0          0       0      23
REV.ReverseReads       0          0       0       0

I wouldn't be as particular about this if at the end of the day I could just map everything to the same species/genus, however, my research  concerns interspecies variability, where a couple base pair changes are significant. What happens at the end of my dada2 pipeline is I have a dataset I trust for the most part, except that there are a couple of sequences that map to separate ASVs that are the EXACT same sequence only their reverse-complement, creating synthetic diversity. Is there any way to collapse these sequences into one ASV?

**Comment by benjjneb** [comment]
> except that there are a couple of sequences that map to separate ASVs that are the EXACT same sequence only their reverse-complement, creating synthetic diversity. Is there any way to collapse these sequences into one ASV?

You can, but it will take a bit of by-hand R code to do it. You can identify those by creating a reverse-complemented set of sequences and looking for duplicates:

```
sq <- getSequences(st)
sq.rc <- dada2:::rc(sq)
rcdupes <- which(sq.rc %in% sq)
```

Then you can eithrer remove those columns, or merge them in with the forward version:
```
# REmove
st <- st[,!rcdupes] 
# Merge (may require devel version of dada2, not sure if 1.8 collapseNoMismatch will work)
colnames(st)[rcdupes] <- dada2:::rc(colnames(st)[rcdupes])
stm <- collapseNoMismatch(st)
```

At least I think that code should work...

> is there a way for me to identify which reads still have primer on them, to just eliminate them because there are so few

You can also use the `Biostrings::vmatchPattern` functions to get the indices of which sequences match primers in R, just like in the ITS workflow function:

```
nhits <- vcountPattern(primer, DNAStringSet(getSequences(st)))
has.primer <- which(nhits > 0)
```

At that point point the above removal approach would work on the table.
