### ISSUE TITLE
Dada2 file.remove(fout) in fastqFilter

### ISSUE THREAD

**Issue by ralsallaq** [benjjneb/dada2#436]
I am having an issue of running fastqFilter on RStudio. I am getting the following error:

Error in fastqFilter("workdirectory/post.fna", filtered, trimLeft = 5,  maxEE = 1, truncLen = 300,  : 
  Failed to overwrite file:workdirectory/filtered
In addition: Warning message:
In file.remove(fout) :
cannot remove file 'workdirctory/filtered', reason 'Permission denied' 

where work directory is where I am trying to save the filtered sequences under an existing directory with the name filtered
If I removed the directory I get the following error:
Read in 0, output 0 (NaN%) filtered sequences.
The filter removed all reads: workdirectory/filtered not written.
Warning message:
In file.remove(fout) :
  cannot remove file 'workdirectory/filtered', reason 'No such file or directory'

**Comment by benjjneb** [comment]
My first guess is that this is a file permissions issue. 

Are you an administrator on this machine? Is Rstudio running as a user or an administrator? What are the read/write permissions to `workdirectory/`?

**Comment by ralsallaq** [comment]
​Many thanks Ben for your quick reply. I thought so too so I ran RStudio as an administrator and also I checked whether I am the owner of the folder and it seems so but the problem persisted. So I do have write and read permissions. Not sure what to check further.
Thanks much!
Ramzi

**Comment by benjjneb** [comment]
Can you post a minimal example of the code that is causing this error? E.g on a singe sample, including the definition of the raw and filtered sample names, and the `fastqFilter` command.

**Comment by ralsallaq** [comment]
Sure. Please see below:
path1<-"./workdirectory"
fastafile<-file.path(path1, "post.fna") #raw sequences from one sample
filtered<-file.path(path1, "filtered") #filtered 
fastqFilter(fastafile, filtered, trimLeft=5, maxEE=1, truncLen=300, truncQ=2, maxN=0, verbose=TRUE, compress=FALSE)

**Comment by benjjneb** [comment]
I think the problem is that `filtered` is pointing at a directory, which can't be overwritten. It should be a filename, e.g: `filtered<-file.path(path1, "filtered", "post_filt.fa")` is the `post_filt.fa` file in the `filtered/` subdirectory.

Does that fix the issue?

**Comment by ralsallaq** [comment]
I am still getting an error. I also got the chance to try it on another computer and still get the same error. Here is the code I applied:

path1<-"./workdirectory"
fastafile<-file.path(path1, "post.fna") #raw sequences from one sample
filtered<-file.path(path1, "filtered","post_filt.fa") #filtered
fastqFilter(fastafile, filtered, trimLeft=5, maxEE=1, truncLen=300, truncQ=2, maxN=0, verbose=TRUE, compress=FALSE)

Here is the error I get:

Read in 0, output 0 (NaN%) filtered sequences.
The filter removed all reads: ./workdirectory/filtered/post_filt.fa not written.
Warning message:
In file.remove(fout) :
  cannot remove file './workdirectory/filtered/post_filt.fa', reason 'No such file or directory'


please note that I am expecting dada2 to output post_filt.fa, in the above code and the directory "filtered" was created by me as a user. I tried to put an empty post_filt.fa file into "filtered" and it was removed after applying the fastqFilter utility but the above error still shows up following that. The same error also shows up when the same code is applied but without creating a "filtered" directory and expecting fastqFilter to create the directory and the output file.

**Comment by benjjneb** [comment]
> Read in 0, output 0 (NaN%) filtered sequences.
> The filter removed all reads: ./workdirectory/filtered/post_filt.fa not written.

Sorry, I should have caught this earlier. The filter is removing everything, that is the problem. Probably your reads are not 300nts long and you need to change `truncLen` to something that is shorter than your read lengths.

**Comment by ralsallaq** [comment]
Many thanks Ben. Indeed the filter did not retain any sequences. I fixed my parameters and now I am getting the filtered output.
