### ISSUE TITLE
assign taxonomy replace NA

### ISSUE THREAD

**Issue by alexthibodeau** [benjjneb/dada2#437]
Hello!

I wonder if it is possible to have multiple features for the taxonomic assignation.

I would like to have the option to replace in the tax table the "NA" by "last_classified_phyla_unclassified". For example, if I have an "NA" as the genus for a Lachnospiraceae, I would like it to be replaced by "Lachnospiraceae_unclassified" and so for each other phyla.

I can probably do that in R but I am afraid that this will impair further analysis in phyloseq.

Thank you very much and keep up the good work!

I am just learning Dada2 and find it quite insightful.

Cheers!

**Comment by benjjneb** [comment]
The way to do this would be through R. This should do the trick:

```
for(col in seq(2,ncol(tax))) {
  propagate <- is.na(tax[,col]) & !is.na(tax[,col-1])
  tax[propagate,col:ncol(tax)] <- paste(tax[propagate,col-1], "unclassified", sep="_")
}
```

**Comment by alexthibodeau** [comment]
Many thanks
