### ISSUE TITLE
454 data (.sff files) and dada2

### ISSUE THREAD

**Issue by TamaraRR** [benjjneb/dada2#439]
I am trying to analyze Roche 454 pyrosequencing data with dada2, but I haven't been able to adapt the code available in the tutorial (https://benjjneb.github.io/dada2/tutorial_1_2.html), although I followed author's recommendations (https://benjjneb.github.io/dada2/faq.html#can-i-use-dada2-with-my-454-or-ion-torrent-data).
My doubt is how to adapt the code for reading only one .sff file (instead of 2 .fastq files)? where should I start the analysis?

It would be really really useful if someone could share the adapted script.

Thank you so much in advance!
Best regards,

**Comment by benjjneb** [comment]
The key step here is that you need to convert from the sff file format into the fastq file format, as that is the file format used by DADA2.

The dada2 R package does not have an sff conversion function, but external programs like QIIME and mothur (and others) are able to perform that conversion. I think that Roche's software can also output fna + qual files, which can be combined together into a fastq file.

**Comment by TamaraRR** [comment]
Thank you!!
I was finally able to convert my .sff files into fastq file format, obtaining one fastq file per sample, so I assum I can ejecut the code using only "F" lines (avoiding "R" code lines). But now, I am stucked in the step "mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE)", needed for the following steps.
Thanks again

**Comment by benjjneb** [comment]
That all sounds right. And you just skip the mergers step, and run the `makeSequenceTable` command on the dada objects themselves. I.e:

```
seqtab <- makeSequenceTable(dadaFs)
```

The rest is all the same.

**Comment by TamaraRR** [comment]
ah, ok! I got it, thank you so much!
Best regards
