### ISSUE TITLE
Length variation in the dada2 output

### ISSUE THREAD

**Issue by jeffkimbrel** [benjjneb/dada2#44]
First off, dada2 is great... I love software that just works with easy installation, and with a clear pipeline as outlined in the tutorial.

Second, sorry if this is the wrong place for this, since it isn't necessarily a software issue, but I have a question about results interpretation.

In the tutorial, there was a very tight spread in the lengths of sequences returned, and it mentions...

>large length differences in the 16S region, especially after merging, are typically caused by alternate priming from non-specific primers. If this is not controlled for, this can produce false variation in the output.

Below is my output, and there is a very large variation in length, although most of the sequences are between 230-235nt.

```
table(nchar(colnames(seqtab)))
## 
## 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 
## 329   9  10 386  12  12   7   5   9   7   4   3  10   6  11   8  16   7 
## 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 
##   9   2   8   4  10  11   9   4   6   9  11   7   8   6   4   9   6   7 
## 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 
##  14   6   7  10   5   7   7   9   7  16   9   7   8   8  12   8   7   5 
## 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301 
##   9  13   7   9  10   6  12  10  11   7   7  11  12   8   7  16  12  11 
## 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 
##  13   8  11   9   8  14  10  12  10  11  11  17  13  14  12  12  11  11 
## 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 
##   7  21  21  13  20  28  17  16  15  18  12  12  18  13  18  12  14  11 
## 338 339 340 341 342 343 344 345 346 347 348 349 
##  14  16  18  15  13  22  10  12  16  15  19  19
```

I am wondering how do you recommend controlling or correcting for this potential variation? Should I just ignore all sequences greater than ~235? My quality assessments were similar to those in the tutorial, and I trimmed to 10-240 for the forward, and 10-150 for the reverse sequences.

Thanks,

Jeff

**Comment by jeffkimbrel** [comment]
After digging around some more, most of the long sequences belong to a fungal contaminant (my data should be only 16S). 

Given that dada2 doesn't rely on "fuzzy" matching, can I just remove this sequences from the results? Or, should I remove them from the raw reads? It seems like sequence clustering shouldn't be affected by the presence of these, if I understand the dada2 algorithm, and I can simply remove them from my resulting list of denoised, merged, and de-chimera'd sequences. 

Thanks,

Jeff

**Comment by benjjneb** [comment]
The standard way to deal with this sort of length variation in other pipelines is to simply define a length window and throw out merged sequences outside that window. That is completely valid to do with dada2 results as well.

That said, it is worth taking a look at the "long" sequences to get an idea of what they are. I've seen such sequences arise because of contamination (as you are suggesting is the case here) but also because of primers that hit more than one location on bacterial 16S sequence, in which case they have some useful information.

One other thing to check, just to make sure that these long sequences really are a minority of your sequence data as expected, is to check the number of reads associated with each length as well, eg. tapply(colSums(seqtab), nchar(colnames(seqtab)), sum).

**Comment by jeffkimbrel** [comment]
A large majority of the sequences are between 233-235nt long, so you're right, I can probably get away with just trimming everything above that length. I assume I do that when making the sequence table? Can the following code be modified by adding a length filtering parameter to remove those larger than 235?

```
seqtab <- makeSequenceTable(mergers[names(mergers) != "Mock"])
```

Or would you remove them at another step?

**Comment by benjjneb** [comment]
I would keep them through the makeSequenceTable step, and then remove those columns with lengths outside the window you want. Eg.

```
seqlens <- nchar(colnames(seqtab))
seqtab.filt <- seqtab[, (seqlens <= MAXLEN) & (seqlens >= MINLEN)]
```

**Comment by jeffkimbrel** [comment]
Excellent, I really appreciate the help!

Jeff

**Comment by benjjneb** [comment]
Closing this issue, but feel free to reopen if any more questions.

Also going to rename to "Length variation in the dada2 output" as that is probably a better description for people who run into the same issue later.

**Comment by jeffkimbrel** [comment]
Also, this code may help people with plotting the lengths. I had trouble figuring out how to convert `tapply` output to something useful. This code can be used to plot both the OTU count per sequence length, and the total number of reads per sequence length.

```
library(ggplot2)
table <- as.data.frame(table(nchar(colnames(seqtab.filt))))
colnames(table) <- c("LENGTH","COUNT")

ggplot(table,aes(x=LENGTH,y=COUNT)) + 
  geom_histogram(stat="identity") + 
  ggtitle("Sequence Lengths by OTU Count") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5,size=10)) +
  theme(axis.text.y=element_text(size=10))

table2 <- tapply(colSums(seqtab.filt), nchar(colnames(seqtab.filt)), sum)
table2 <- data.frame(key=names(table2), value=table2)

colnames(table2) <- c("LENGTH","ABUNDANCE")

ggplot(table2,aes(x=LENGTH,y=ABUNDANCE)) + 
  geom_histogram(stat="identity") + 
  ggtitle("Sequence Lengths by OTU Abundance") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5,size=10)) +
  theme(axis.text.y=element_text(size=10))
```
