### ISSUE TITLE
Files are in reverse complement orientation.

### ISSUE THREAD

**Issue by SaiPrabhas** [benjjneb/dada2#441]
Hello! The files which I am using to run the pipeline show a steep decline in read quality for the first 50 base pairs so I believe that they are in reverse orientation. Is there a way to correct them in DADA2, I believe there is an option in QIIME for such reads. Thank you very much.

**Comment by benjjneb** [comment]
You can use the ShortRead package to read in and write out reversed (or reverse complemented) fastq files.

```
library(ShortRead)
fn <- "path/to/file_to_reverse.fq"
fq <- readFastq(fn)
fq <- reverse(fq) # or reverseComplement
fout <- "path/to/file_reversed.fq"
writeFastq(fq, fout)
```

Alternatively you can just run the pipeline on the reads as is, the algorithm doesn't care what orientation they are in (for single-end at least, merging cares).

**Comment by SaiPrabhas** [comment]
How exactly can I do that? Because I have tried assign taxonomy without any modifications and only one genus was identified in the whole data. So I don't think its the right.

**Comment by benjjneb** [comment]
The best way to look into that is to use the documentation. `?assignTaxonomy` will have a description of the different options, including `tryRC`

**Comment by SaiPrabhas** [comment]
That worked. Thank you very much.

**Comment by SaiPrabhas** [comment]
Hello! I have a question regarding abundancies of the sequences. I know that the sequences are arranged based on abundances but is there a way to quantify those abundances? Like knowing the percentage as in QIIME? Thank you.

**Comment by benjjneb** [comment]
Did you make a sequence table? The entries in that matrix are the abundances of each sequence-variant in each sample. You can also get that value from the `dada-class` object in the `dadaOut$clustering` data.frame, which has an `$abundance` column.
