### ISSUE TITLE
nbases parameter?

### ISSUE THREAD

**Issue by adityabandla** [benjjneb/dada2#443]
Hi Benjamin 

I am using the devel version. I see that nreads has been replaced by nbases in the learnerrors function. After my first run, I could see only 0.5 M reads being used for this step, but amounting to 0.11 Gb.

Is there a cutoff you would recommend for the minimum amount of bases to be used?

Regards,
Aditya

**Comment by benjjneb** [comment]
The new default is 100Mb (`nbases = 1e8`), and that should do the job in normal circumstances.

This value is equivalent to the previous default of 1M reads for 100bp reads, which is how that number was chosen. But going to `nbases` more accurately focuses on the important quantity, as it really is the number of bases that is critical to estimating the error model.
