### ISSUE TITLE
using dada2 starting from extended fragments instead of raw reads

### ISSUE THREAD

**Issue by flacchy** [benjjneb/dada2#446]
Dear Dr. Benjamin Callahan,

I am trying to  run the dada2 pipeline on same samples I was provided. Unfortunately  I only have access to the merged reads (extended fragments). Would it be possible to have an advise on the best way forward? So far I have managed to do the follow: 
```
miseq_path <-("mypath/")
list.files(miseq_path)
extendedfragments <- sort(list.files(miseq_path, pattern=".fastq"))
extendedfragments <- file.path(miseq_path, extendedfragments)
sampleNames <- sapply(strsplit(extendedfragments, ".extendedFrags.fastq"), `[`, 1) 
plotQualityProfile(extendedfragments[1:1])
err_extendedfrag <- learnErrors(extendedfragments, multithread=TRUE)
plotErrors(err_extendedfrag, nominalQ=TRUE)
derep_exten <- derepFastq(extendedfragments, verbose=TRUE)
names(derep_exten) <- sampleNames
dada_ext <- dada(derep_exten, err=err_extendedfrag, multithread=TRUE)
dada_ext[[1]]
mergers <- mergePairs(extendedfragments, derep_exten, verbose=TRUE)
```
of course the mergePairs won't work so I was wondering if there was another way to load my data already merged. 

Thank you in advance for any help, 
F.

**Comment by benjjneb** [comment]
The issue with pre-merged reads is that the empirical relationship between the quality scores and the error rates on the forward-only, overlapping, and reverse-only subsegments of the merged reads may be different, and the algorithm doesn't know about those different subsegments. The outcome can be false positives.

If this is the only data you have, you can run it through the workflow. I'd recommend adding one additional conservative step to account for the issue described above:

```
err_extendedfrag <- learnErrors(extendedfragments, multithread=TRUE)
err_extendedfrag <- inflateErr(getErrors(err_extendedfrag), 3)
```

Then continue as normal. Basically this is a crude way of dealing with the heretogeneity between the 3 subsegments by telling the algorithm to assume the error rates are 3x higher than it estimated from the extended fragments.

**Comment by flacchy** [comment]
Thank you vary much for the advise.
Unfortunately this is the only data I have available, I usually ask for the raw reads but in this case I am not able to obtain them. 
This might be a weird question but I am honestly curious on the outcomes of both using the conservative step (in case of merge reads provided by companies) vs the raw reads, it's a shame  I will not been able to find out with this dataset but do you know what will be the false positive rates when using data  merged using different tools? Are there higher differences based on the tools used for the merging?

**Comment by benjjneb** [comment]
> Are there higher differences based on the tools used for the merging?

Yes. The issue is that read merger programs redefine the quality scores, and in quite different ways.

The conservative approach we recommend above should largely avoid that issue though.

**Comment by flacchy** [comment]
thank you that make sense. 
Just one more question and apology if this is very stupid but how do I go from there would you advise the following steps? 
derep_exten <- derepFastq(extendedfragments, verbose=TRUE)
names(derep_exten) <- sampleNames
dada_ext <- dada(derep_exten, err=err_extendedfrag, multithread=TRUE)
seqtab <- makeSequenceTable(dada_ext)

or should I merge the dada_ext, derep_exten using a general R function? 
Again thank you for your time

**Comment by flacchy** [comment]
thank you that was a silly question on my side. 
Again thank you very much for your time and support.
