### ISSUE TITLE
how to assign Sample IDs to taxonomy

### ISSUE THREAD

**Issue by Untrach** [benjjneb/dada2#448]
Hi

New user here doing my first ever illumina run, so I apologize for the simplicity of this question. I've worked through the DADA2 tutorial for my data, getting to the point of assigning taxonomies. I have a large matrix of ASVs called 'seqtab.nochim' and another large matrix called 'taxa' that contains all my sequences and their taxa assignments. What I don't understand, is how to append the sample names to my taxa list and/or my ASV so that I can see what sample each OTU belongs to. I've tried a few basic attempts, but nothing has worked so far. Can anyone give me advice or direct me to where I can find the answer? I've tried searching through the issues here but couldn't find the answer.

Thank you very much!

**Comment by benjjneb** [comment]
`seqtab.nochim` is a matrix. Each row is a sample. Each column is a sequence (ASV). The entries of the matrix in row i, column j are the abundance of ASV j in that sample i. ASVs (or OTUs) don't belong to samples, as the same ASVs (or OTUs) can and often do appear in multiple samples.

Does that help?

**Comment by Untrach** [comment]
Thank you for elaborating on the format of seqtab.nochim, that does help me to understand it. So that means that my seqtab.nochim matrix tells me which samples contain which ASVs and with what frequency. While the taxa matrix tells me the taxa assignment of each ASV only. 

I feel like it would be useful to combine these, so I can know which taxa exist within each sample and with what frequency. Is there a simple way to do this? Or is this something I should be doing via phyloseq package instead?

**Comment by benjjneb** [comment]
> Or is this something I should be doing via phyloseq package instead?

This. The phyloseq package is built to do just what you're talking about, which is combine different types of information (ASV table, sample metadata, taxonomy, phylogeny) in a usable way.

**Comment by Untrach** [comment]
OK, thank you so much for your prompt and useful feedback. I will proceed to learning how to use the phyloseq package now!
