### ISSUE TITLE
Comparing OTU assignments to DADA2 assignments: considerably fewer identifications

### ISSUE THREAD

**Issue by aminards** [benjjneb/dada2#449]
I am learning to use DADA2 and am comparing identifications (read counts) between an OTU method (LotuS) and  DADA2.  I am getting considerably fewer identifications using DADA2.  I suspect I am misinterpreting things or have missed something in my analysis.  The maximum number of exact sequence variants I am getting from a sample seems to be 187 with the mean being around 19 ESVs.  
This is normal sediment/soil samples so I am expecting a lot more identifications for the majority of samples.  Running these samples through the LotuS pipeline produces large read counts per OTU.  I understand that they will not be the same results but I believe I am misinterpreting the DADA2 results or may have done something wrong.  I used the paired end big data pipeline on 368 samples.  

These are 16S V3/V4, paired end 300x300, using these primers:  F: CCTACGGGNBGCASCAG    R: GACTACNVGGGTATCTAATCC.

Here is the filterAndTrim command I used:

`out <- filterAndTrim(fwd=file.path(pathF, fastqFs), filt=file.path(filtpathF, fastqFs),
              rev=file.path(pathR, fastqRs), filt.rev=file.path(filtpathR, fastqRs),
              truncLen=c(210,100), maxEE=c(2,5), truncQ=11, maxN=0, rm.phix=TRUE,
              compress=TRUE, verbose=TRUE, multithread=TRUE, trimLeft = c(17, 21))`

I am also attaching my seqtab.nochim.rds file and my quality profile plots for reference.
![qualityprofile_forward](https://user-images.githubusercontent.com/13107141/39246345-d36791e4-4885-11e8-9de2-e978d836a063.jpg)
![qualityprofile_reverse](https://user-images.githubusercontent.com/13107141/39246346-d3846ae4-4885-11e8-9285-6c3105672001.jpg)

In the end, I need to produce a table from DADA2 that is like the OTU table from other pipelines where samples are columns, rows are identifications and the data are counts of reads.  I will also need to produce a taxonomy table that provides the taxonomic lineage for each ESV along with the read count for that organism.  I have assigned taxonomy using the rdp training set.  How will I associate read counts with the taxonomies?

[seqtab.nochim_final.zip](https://github.com/benjjneb/dada2/files/1946952/seqtab.nochim_final.zip)

**Comment by benjjneb** [comment]
You have probably truncated too much for your reads to overlap and are losing most of the reads in the merger step. Also have you removed the primers from these reads? The standard Illumina protocol leaves the primers on the reads, and those need to be removed. A good way to sanity check is by tracking the read counts through the pipeline. See example in the tutorial: https://benjjneb.github.io/dada2/tutorial.html#track-reads-through-the-pipeline

Also, this previous post will help explain some of this more: https://github.com/benjjneb/dada2/issues/442#issuecomment-380795350

**Comment by aminards** [comment]
I thought that including  `trimLeft = c(17, 21)`  would remove the primers.  Does this not remove the primers?

**Comment by benjjneb** [comment]
> I thought that including trimLeft = c(17, 21) would remove the primers. Does this not remove the primers?

Ah I didn't catch that, yes you should be OK on primers. So you just need to increase your `truncLen` so that the total length after truncation is ~465 nts (for this amplicon) to allow merging.

**Comment by aminards** [comment]
I followed your advice to truncate less of my reads and I now have read counts that make more sense.  I changed my truncLen parameter to `truncLen=c(260,240)`.  
Thank you very much.
