### ISSUE TITLE
Random read direction after merge seq tables from different runs

### ISSUE THREAD

**Issue by GaelleQ** [benjjneb/dada2#451]
Hi Benji, 
First of all thank you so much for this amazing resource, it saved me from tricky enigmas several times. I have quite a similar issue to miamynta #167 with random read direction in MiSeq data. The tryRC option in assignTaxonomy helped me solve the misassignment I was seeing. However, I am now running multiple runs and after merging the seqtab using mergeSequenceTables, I end up with a seqtab in which sequences and reverse complement are present and considered as different ASV even though they are the same. 

My script:
seqtab <- mergeSequenceTables(seqtab_run1, seqtab_run2)
seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
taxa <- assignTaxonomy(seqtab.nochim, "silva_nr_v128_train_set.fa", multithread=TRUE)

Example of ASV present in the final table:
>OTU46
CGGAGTTAGCCGGGGTTTCTTTACCAGGTACTGTCATTATCATCCCTGGCGAAAGAGCTTTACGACCCTAGGGCCTTCGTCACTCACGCGGCATGGCTAGATCAGGCTTTCGCCCATTGTCTAAGATTCCCCACTGCTGCCTCCCGTAGGAGTCTGGGCCGTGTCTCAGTCCCAGTGTTGCTGATCATCCTCTCAAACCAGCTATGGATCGTAGGCTTGGTAGGCCATTACCCCACCAACTACCTAATCCAACGCGGGCTAATCCAAAGGCGATAAATCTTTCCCCCGAAGGGCACATACGGTATTACTCTCCGTTTCCAGAGGCTATTCCGTACCTTTGGGCATATTCCCACGCGTTACTAACCCGTCCGCCGCTCACCCGAAGGTGCGCTCGACTTGCATGTGTTAGGCCTGCCGCCAGCGTTCGT

>OTU225
ACGAACGCTGGCGGCAGGCCTAACACATGCAAGTCGAGCGCACCTTCGGGTGAGCGGCGGACGGGTTAGTAACGCGTGGGAATATGCCCAAAGGTACGGAATAGCCTCTGGAAACGGAGAGTAATACCGTATGTGCCCTTCGGGGGAAAGATTTATCGCCTTTGGATTAGCCCGCGTTGGATTAGGTAGTTGGTGGGGTAATGGCCTACCAAGCCTACGATCCATAGCTGGTTTGAGAGGATGATCAGCAACACTGGGACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCAGTGGGGAATCTTAGACAATGGGCGAAAGCCTGATCTAGCCATGCCGCGTGAGTGACGAAGGCCCTAGGGTCGTAAAGCTCTTTCGCCAGGGATGATAATGACAGTACCTGGTAAAGAAACCCCGGCTAACTCCG

OTU46 is only present in samples from run 1 and OTU225 is only present in samples from run 2. 

In your reply to myaminta #167, you offered to use nwhamming as a solution: nwhamming(dada2:::rc(sq), sqs.all, vec=TRUE) but to be fair, as I am new to all this, I don’t really understand how and when I am supposed to use it. I also don’t really understand the solution proposed by rec3141 edited in March last year. 

Your help with this would be highly appreciated! 
Cheers
Gaëlle

**Comment by benjjneb** [comment]
We don't have an automated solution to reorienting mixed-orientation sequences right now.

The idea that can be used is to compare each sequence and its reverse complement to a reference sequence(s) in the right orientation, and then choose the orientation that minimizes that distance. That's basically what the solution posted by @rec3141 did.

It's not a bad idea to implement such a method that, which would be pretty easy as it would just reuse code from `assignTaxonomy`...

**Comment by benjjneb** [comment]
I've updated the `orient.fwd` parameter in `filterAndTrim` to reorient both single-end and paired-end fastq data: https://github.com/benjjneb/dada2/commit/db05f161b8750254b1213aa9797ed27f85cbb6db

It's not perfect, but I think it gets the job done in most situations.
