### ISSUE TITLE
Low number of reads

### ISSUE THREAD

**Issue by iyang5** [benjjneb/dada2#457]
Hello!  I am a newbie to microbiome data analysis and am learning, so please forgive me if this is a stupid question.  I am on the filtering and trimming step of the workflow and am concerned at the low number of reads I'm seeing in my quality plot profile visualization (only seeing 114 reads). It also seems very odd to me that I am seeing exactly the same number of reads for each of my samples. I'm fairly confident that I've read in my sample names correctly. Would you have any advice for me?

**Comment by benjjneb** [comment]
That suggests that there are 114 reads prior to starting the dada2 workflow, and I agree it is very odd that there would be the same number of reads in each file.

A first check I would do is to confirm that there are 114 reads in each file by another method. An easy way in the shell sould be `wc -l my_sample.fastq` and then divide by 4 (there are 4 lines per read in fastq files).

**Comment by iyang5** [comment]
Thank you!  Turns out something went wonky when I downloaded the fastq files.  Redownloaded and it is all making much  more sense now!
