### ISSUE TITLE
dada2 save intermediate files in correct format for phyloseq

### ISSUE THREAD

**Issue by DidemnumVex** [benjjneb/dada2#458]
First, I'm new to dada and R, though I am very familiar with Python and Qiime.  So, I am still figuring out R syntax, objects, and data structures.

Basically, my issue is that I went through the first portion of the pipeline and have the variables that are ready to go to phyloseq (let's call them taxa and seqtab.nochim, as in your tutorial). However, I didn't realize that phyloseq wasn't properly installed, so I was able to install it but need to close the environment containing my variables (analyzed data).   I tried writing to csv with 
write.csv(taxa, file="taxa.csv")

and importing into the new environment, but I got an error when I tried to make an OTU table in the new window.  I checked the documentation, but couldn't see how best to export or import this data type.  
 
Thank you in advance for your help.  The data set is quite large so it would be a shame to have to reanalyze everything.

**Comment by benjjneb** [comment]
The easiest way is to use the general purpose R commands for saving/loading R objects: `saveRDS` and `readRDS`. Eg,

```
saveRDS(taxa, "path/to/taxa.rds")
# Restart as necessary
taxa <- readRDS("path/to/taxa.rds")
```

**Comment by DidemnumVex** [comment]
Thank you so much!
