### ISSUE TITLE
plotQualityProfile Error

### ISSUE THREAD

**Issue by alrami02** [benjjneb/dada2#460]
Hi,
I am running into a problem when trying to visualize the quality profile of the forward and reverse reads.
I followed all the instructions in the tutorial, but I have not be able to fix this problem:

> plotQualityProfile(fnFs[1:2])
Error in `$<-.data.frame`(`*tmp*`, "minScore", value = Inf) : 
  replacement has 1 row, data has 0
In addition: Warning message:
In min(anndf$minScore) : no non-missing arguments to min; returning Inf

Thanks
Ale

**Comment by benjjneb** [comment]
My first guess is that one of those files is empty, or is a fasta file not a fastq file. Can you check the following?

```
library(ShortRead)
foo1 <- readFastq(fnFs[[1]])
foo1
quality(foo1)
# And again for fnFs[[2]]
```

**Comment by darmeyer21** [comment]
Thanks - something was messed up with my path. Can't believe I missed that.

**Comment by saranyacgl** [comment]
Hi,
I ran microbiome analysis from raw reads in R,  plotQualityProfile(fnFs[1:2])
Warning messages:
1: In serialize(data, node$con) :
  'package:stats' may not be available when loading
2: In serialize(data, node$con) :
  'package:stats' may not be available when loading
3: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 

I even updated my R version, changed the path variable of my file location, still employed with the same error. Please can any one help me to sort this out.

**Comment by saranyacgl** [comment]
IHi,
I ran microbiome analysis from raw reads in R, 

In the step of plotQualityProfile(fnFs[1:2]) I got the below popping of error message ; 
Warning messages:
1: In serialize(data, node$con) :
'package:stats' may not be available when loading
2: In serialize(data, node$con) :
'package:stats' may not be available when loading
3: guides(<scale> = FALSE) is deprecated. Please use guides(<scale> = "none") instead.

 To solve this ,I even updated my R version, changed the path variable of my file location, still employed with the same error. Please can any one help me to sort this out.

**Comment by benjjneb** [comment]
@saranyacgl Those look like warnings, not errors. Was the plot created? If so, you can just ignore the warnings.

**Comment by saranyacgl** [comment]
Sir,
Still plot not created sir, I attached the jpeg format file for your reference. please help me to sort this out. 
sir i even changed path  and file location
but still the same issue prevails.
![file1](https://user-images.githubusercontent.com/76244843/189119333-623c24f8-6df9-4e35-8caf-66c153cd9aba.JPG)
M
![Capture1](https://user-images.githubusercontent.com/76244843/189119321-0f8029ee-c305-4ada-90ec-9d9ee15b85b3.JPG)
![Capture 2](https://user-images.githubusercontent.com/76244843/189119306-ceeadbe2-8e34-4715-9f4f-21a221b1db38.JPG)

**Comment by benjjneb** [comment]
I'm not sure what is going on, but the issue involves something outside the dada2 package code. Googling the error message shows that other people have run into this same error in a variety of packages, and suggest that it is related to a combination of multithreading (perhaps in the implementation of `readFastq` called by `plotQualityProfile`?) and environment handling.

I would suggest updating R, doing a fresh Bioconductor install of the needed packages, and also updating Rstudio. Then give it another shot, and hopefully this issue will go away.
