### ISSUE TITLE
Bimodal distribution length of ASVs for 16S illumina MiSeq 2*300 bp

### ISSUE THREAD

**Issue by skbhtt** [benjjneb/dada2#461]
I have used DADA2 to analyze 16S  Illumina MiSeq 2* 300 bp data (Primers removed).  Using  following filtering parameters , and pooling all the samples(pool = TRUE) together, I arrived at the seq table.
filterAndTrim(fwd=fnFS_path, filt=filtFS,
              rev=fnRS_path, filt.rev=filtRS,
              truncLen=c(300,250), maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=cores)

 By looking at the distribution of different length of ASVs,, I  couldn't understand  the separation of two distribution by 20 nt.  Is this normal? What is causing this ?
![distribution_sv](https://user-images.githubusercontent.com/13259417/39538110-b28bd92e-4e09-11e8-996f-03c031396648.png)

**Comment by benjjneb** [comment]
Is this V3V4? There is a bimodal length distribution for that region.

Not sure why (anyone?) but it is to be expected.

**Comment by skbhtt** [comment]
It is V3-V4 region.

**Comment by FMKerckhof** [comment]
Sorry for reopening this issue but I have a related one on V3-V4 (adapated Klindwordth _et al._ (2013) primer set (Bakt_341F and 758Rmod (close to Bakt_805R/pB-3845) primers). Primers have been trimmed (trimmomatic), and I get a _trimodal_ (not bimodal) ASV length distribution, following the SOP (except for `pool="pseudo"` and some adapatations in the lenght triming). 
![image](https://user-images.githubusercontent.com/2431458/52506368-add2e080-2bee-11e9-8318-9af9ed24763f.png)
In a violin plot with the actual observed ASV lengths jittered on it, it becomes even more clear:
![image](https://user-images.githubusercontent.com/2431458/52506677-921c0a00-2bef-11e9-8dfa-d9ef114efeeb.png)

Maybe it it supposed to be expected? As a point of reference, I have ran the Mothur MiSeq SOP on the same data, and indeed, after alignment-based filtering (right before the pre.cluster step), and also a trimodal distribution can be observed (albeit less clearly):
![image](https://user-images.githubusercontent.com/2431458/52506941-62213680-2bf0-11e9-9d73-d3ffd0dd61f5.png)

What are your thoughts? Should I move ahead with a ~30 bp-wide ASV length difference range?

**Comment by benjjneb** [comment]
> What are your thoughts on the (biological or technical?) reason(s) for this distribution?
> Should I move ahead with a ~30 bp-wide ASV length difference range?

There's a real (i.e. natural) bimodal length distribution in the V3V4 region, so yes you should keep the data.
