### ISSUE TITLE
regarding independent vs pooled in evolutionay studies

### ISSUE THREAD

**Issue by odo1977** [benjjneb/dada2#462]
Hello, and thanks for the resource and the comprehensive tutorials etc.

I´m using dada2 to analyse ITS variants between grasshopper individuals. The goal is to observe evolutionary trends, i.e. which individuals have which variants, and how the variants are moving between populations.

In this sense I would better need a precise representation of what´s in each sample.

For instance, with one of the samples if y do the independent assessment I get 5 sample sequences, and if I go pooled=TRUE I get 24. From your tutorials etc I gather that 24 should be correct, although I´m not so sure....maybe I´m inflating the number of sequences do to the existance of common erroneous sequences through the dataset, any comments?

Also, I´m assuming that down the pipeline there may be a chimera removing step which I understand why it needs to be included, however I worry about removing true sequences arising from recombination (the grasshopper have ca. 1000 copies of the ITS!), any comments here as well?

Finally, my sequences do not overlap, so I´m going to trim them and concatenate them (finally I need haplotypes, not complete sequenceS). I assume that the concatenation step will reverse-complement one of the sequences before paste sequences together, and later I will get a file with the concatenation variants and their relative abundance per sample, right?

again many many thanks!

**Comment by benjjneb** [comment]
> From your tutorials etc I gather that 24 should be correct, although I´m not so sure....maybe I´m inflating the number of sequences do to the existance of common erroneous sequences through the dataset, any comments?

It's a combination of factors, but yes you are inflating numbers with common erroneous sequences. In particular, pooling is quite good at identifying chimeras and contaminants, in addition to rare variants, as chimeras and contaminants are "real" sequences that often appear in very low frequencies but in multiple samples. The perfect answer is hard when it gets to really rare stuff, and depends a bit on what's important to your scientific questions. 

> however I worry about removing true sequences arising from recombination (the grasshopper have ca. 1000 copies of the ITS!), any comments here as well?

You're asking the right questions! When chimera identification goes wrong it is usually on recombinant intragenomic variants. The default have been set based on testing in bacteria, which have 1-15 16S genes, not on 1000-copy ITS genomes. I would consider varying the `minFoldParentOverAbundance` parameter, and seeing if there are meaningful changes as a result. This parameter controls how much more (in folds) potential chimera "parents" must be than the sequence being tested for chimerism. In your case, it may be worth increasing that number (from 2 to 8? 16?) which will guard against identifying intragenomic variants as chimeras except in the most extreme cases.

> I assume that the concatenation step will reverse-complement one of the sequences before paste sequences together,

Correct. Also, we don't recommend non-overlapping amplicons, but if that's what you have we recommend upgrading to the new 1.8 version as it does a bit better with them.

> later I will get a file with the concatenation variants and their relative abundance per sample, right?

Technically you'll get the sequence table as an R matrix, but it can be written out to a file if that's what you want.

**Comment by odo1977** [comment]
Many thanks!
