### ISSUE TITLE
Far fewer dada SVs than QIIME OTUs 

### ISSUE THREAD

**Issue by sgriffi** [benjjneb/dada2#463]
Hi there,

I’m running my data (2 x 250 bp MiSeq, 16S V4 amplicon sequencing) through the standard dada2 tutorial pipeline.  I’ve previously run it through QIIME, where I got thousands of 99% OTUs per sample, but in dada2 I’m only getting hundreds of SVs. For the two samples below, QIIME assigned just over 13,000 OTUs to each of them, but dada2 found less than 300 SVs. 

> dadaFs[[1]]
> dada-class: object describing DADA2 demonising results
> 290 sample sequences were inferred from 27570 input unique sequences.
> Key parameters: OMEGA_A = 1e-40, BAND_SIZE = 16, USE_QUALS = TRUE
> 
> dadaRs[[1]]
> dada-class: object describing DADA2 denoising results
> 262 sample sequences were inferred from 20436 input unique sequences.
> Key parameters: OMEGA_A = 1e-40, BAND_SIZE = 16, USE_QUALS = TRUE
> 
> dadaFs[[2]]
> dada-class: object describing DADA2 denoising results
> 286 sample sequences were inferred from 26160 input unique sequences.
> Key parameters: OMEGA_A = 1e-40, BAND_SIZE = 16, USE_QUALS = TRUE
> 
> dadaRs[[2]] 
> dada-class: object describing DADA2 denoising results
> 258 sample sequences were inferred from 18515 input unique sequences.
> Key parameters: OMEGA_A = 1e-40, BAND_SIZE = 16, USE_QUALS = TRUE

> table(nchar(getSequences(seqtab)))
> 200 256 257 258 259 260 
>   7   1 453  27   2   1

The samples that I have I would expect to be in line with the QIIME values, as these organisms host very diverse microbiomes. 

The sequence quality is pretty good and I am not losing a major number of reads at any stage:

> input filtered denoised merged tabled nonchim
> AC7 530686   523333   523333 519250 519197  500680
> AC8 379797   371110   371110 367439 366873  361190

Do you have any ideas about why there are so few SVs? I would be really grateful for your insight.

Thanks so much.

**Comment by benjjneb** [comment]
My first guess is that you're mostly observing a lower false-positive rate. It's known that some of the OTU methods used in QIIME1 were prone to substantially overestimating sample richness (eg: https://peerj.com/articles/3889/), and DADA2 controls those sorts of errors much better (eg: https://benjjneb.github.io/dada2/SotA.html).
