### ISSUE TITLE
How to gather average quality for each sample in big data pipeline?

### ISSUE THREAD

**Issue by aminards** [benjjneb/dada2#464]
I have been learning how to use the DADA2 software for my 16S/ITS analysis.  One value I need to report is the average quality after trimming/filtering for the reads in each sample.  I am following the BIG data pipeline looping over every sample in a multiplexed run (around 380 samples per run).  I know that the dada class has quality per position.  How can I get average quality per sample?

**Comment by benjjneb** [comment]
Do you want the average quality score(?) before filtering? Or after filtering?

**Comment by aminards** [comment]
I need the average quality score after filtering.
