### ISSUE TITLE
generating a ASV table without the mergePairs file?

### ISSUE THREAD

**Issue by colinaverill** [benjjneb/dada2#465]
Hello, I ran through the dada2 tutorial [here](https://benjjneb.github.io/dada2/tutorial.html) and everything worked great, I love the pipeline. I would really love to generate the amplicon sequence table from a raw fasta file however, without quality scores. Some data have been provided to me that have already been quality filtered and trimmed. An example file can be accessed using the below R code:

```
cur.dir <- 'path/to/test_dir/' #specify a directory to download data to.
mgm.id <- 'mgm4788103.3'
mgrast.link <- paste0('http://api.metagenomics.anl.gov/1/download/',mgm4788103.3,'?file=050.1')
cmd <- paste0('curl ',mgrast.link,' > ',cur.dir,'/',mgm.id,'.fasta')
system(cmd)
```
I would like to turn this fasta file into a dereplicated amplicon sequence variant (ASV) table, where the rownames are the sample names (in this case there is only one sample, `mgm4788103.3`), are the column names are the sequences of the unique sequences in the `.fasta` file, and the entries in the table are the number of each unique sequence observed in each sample. This is the output of the `makeSequenceTable` function of dada2. Unfortunately, generating this table in dada2 requires me to start from unpaired reads that have not been quality filtered, which I don't have.

Is there a way to generate the sequence variant table from a fasta file where reads have already been paired and quality filtered?

**Comment by benjjneb** [comment]
This can be done, but it isn't officially supported, as quality scores are a very important covariate with a major impact on error rates. False positives are likely to be generated from low-quality bases when quality scores aren't available.

If you want to try anyway, you will need to build a `derep-class` object by hand from the fasta file. This isn't that hard. Step 1 is to construct a "uniques" vector of the integer counts of each unique sequences, and named by the sequences, call that `unq`. Then you need to make a fake `quals` matrix, then combine them into a `derep-class` object. It will look about like this...

```
# Code to make unq vector, which depends on your input type
quals <- matrix(0, nrow=length(unq), ncol=max(nchar(names(unq))))
drp <- list(uniques=unq, quals=quals)
class(drp) <- "derep"
```

You can then run the pipeline, with the modification that `USE_QUALS=FALSE` should be provided at the `learnErrors` and `dada` steps. I also recommend inflating the learned error rate to try to guard to some degree against the unknown low quality bases, e.g.

```
err <- learnErrors(drp, USE_QUALS=FALSE, multi=T)
err <- inflateErr(err, 3)
dd <- dada(drp, err=err, USE_QUALS=FALSE, multi=T)
```

**Comment by colinaverill** [comment]
Thanks, this is super helpful. I was able to build the ASV table, with the column names as the unique sequences and the rownames as the sample names. It was important to convert the entries in the ASV table to integer from numeric to play well with the dada2 chimera script. Appreciate it!
