### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by doctorbird** [benjjneb/dada2#467]
Can anyone help with this installation error please  - 
R Version 3.5.0 - GCC Version 4.9.3- OS = CentOS7

> install.packages("dada2-1.6", repos= NULL, type="source", dependencies = c("Depends", "suggests","Imports"))
* installing *source* package 'dada2' ...
** libs
g++ -std=gnu++11 -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/include" -DNDEBUG  -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/Rcpp/include" -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/RcppParallel/include" -I/gpfs/software/curl/7.54.0/gcc/include   -fpic  -g -O2 -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/include" -DNDEBUG  -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/Rcpp/include" -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/RcppParallel/include" -I/gpfs/software/curl/7.54.0/gcc/include   -fpic  -g -O2 -c Rmain.cpp -o Rmain.o
g++ -std=gnu++11 -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/include" -DNDEBUG  -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/Rcpp/include" -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/RcppParallel/include" -I/gpfs/software/curl/7.54.0/gcc/include   -fpic  -g -O2 -c chimera.cpp -o chimera.o
g++ -std=gnu++11 -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/include" -DNDEBUG  -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/Rcpp/include" -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/RcppParallel/include" -I/gpfs/software/curl/7.54.0/gcc/include   -fpic  -g -O2 -c cluster.cpp -o cluster.o
g++ -std=gnu++11 -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/include" -DNDEBUG  -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/Rcpp/include" -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/RcppParallel/include" -I/gpfs/software/curl/7.54.0/gcc/include   -fpic  -g -O2 -c error.cpp -o error.o
g++ -std=gnu++11 -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/include" -DNDEBUG  -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/Rcpp/include" -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/RcppParallel/include" -I/gpfs/software/curl/7.54.0/gcc/include   -fpic  -g -O2 -c evaluate.cpp -o evaluate.o
g++ -std=gnu++11 -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/include" -DNDEBUG  -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/Rcpp/include" -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/RcppParallel/include" -I/gpfs/software/curl/7.54.0/gcc/include   -fpic  -g -O2 -c filter.cpp -o filter.o
g++ -std=gnu++11 -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/include" -DNDEBUG  -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/Rcpp/include" -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/RcppParallel/include" -I/gpfs/software/curl/7.54.0/gcc/include   -fpic  -g -O2 -c kmers.cpp -o kmers.o
g++ -std=gnu++11 -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/include" -DNDEBUG  -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/Rcpp/include" -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/RcppParallel/include" -I/gpfs/software/curl/7.54.0/gcc/include   -fpic  -g -O2 -c misc.cpp -o misc.o
g++ -std=gnu++11 -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/include" -DNDEBUG  -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/Rcpp/include" -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/RcppParallel/include" -I/gpfs/software/curl/7.54.0/gcc/include   -fpic  -g -O2 -c nwalign_endsfree.cpp -o nwalign_endsfree.o
g++ -std=gnu++11 -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/include" -DNDEBUG  -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/Rcpp/include" -I"/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/RcppParallel/include" -I/gpfs/software/curl/7.54.0/gcc/include   -fpic  -g -O2 -c nwalign_vectorized.cpp -o nwalign_vectorized.o
nwalign_vectorized.cpp: In function 'char** nwalign_vectorized2(const char*, const char*, int16_t, int16_t, int16_t, int16_t, int)':
nwalign_vectorized.cpp:110:22: error: 'INT16_MIN' was not declared in this scope
   int16_t fill_val = INT16_MIN - MIN(MIN(mismatch, gap_p), MIN(match, 0));
                      ^
make: *** [nwalign_vectorized.o] Error 1
ERROR: compilation failed for package 'dada2'
* removing '/gpfs/software/R/3.5.0/gcc/mellanox/lib64/R/library/dada2'
Warning message:
In install.packages("dada2-1.6", repos = NULL, type = "source",  :
  installation of package 'dada2-1.6' had non-zero exit status

Many thanks

**Comment by benjjneb** [comment]
No idea myself, but a google search of "error: 'INT16_MIN' was not declared in this scope" suggests this is some library issue that has cropped up in a lot of random situations in the past.

One suggestion on a fix here: https://github.com/dellytools/svprops/issues/1#issuecomment-143726679
