### ISSUE TITLE
DADA2 failing to compile on Windows 7/Ubuntu 14.04.3

### ISSUE THREAD

**Issue by feargalr** [benjjneb/dada2#47]
Hello, 

I've been trying to install DADA2 but running into the same issue on both my own 64 bit desktop running windows 7, and a Ubuntu machine we have here. That issue being 

g++ -m32 -I"C:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG    -I"C:/Program Files/R/R-3.2.2/library/Rcpp/include" -I"d:/RCompile/r-compiling/local/local320/include"  -Rpass=loop-vectorize -Rpass-analysis=loop-vectorize   -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
g++.exe: error: unrecognized option '-R'
g++.exe: error: unrecognized option '-R'
make: *** [RcppExports.o] Error 1

I haven't seen this same issue in either the open or closed ones here. 

Thanks

**Comment by benjjneb** [comment]
My mistake, I merged the devel-only Makevars file (which sets certain compiler flags) into the main branch.

Two ways to fix:
1) Delete the file Makevars in /path/to/dada2/src
2) Re-download the just-updated package version

That should do the trick, but let me know, and reopen, if not!
