### ISSUE TITLE
Merging multiple runs with merged and unmerged fasta files: Add trimRight

### ISSUE THREAD

**Issue by GaelleQ** [benjjneb/dada2#471]
Hi all,

I am running multiple runs on 16S rRNA gene amplicons of the V1-V3 region from marine algae samples. I have four sets of data that were sent to different sequencing platforms hence the idea of merging the four seqtabs obtained in multiple runs using mergeSequenceTables.

This was supposed to be easy only, I did not find the original R1 and R2 fasta files for one of the data set (Run 1). For those samples, I only have the merged fasta files. 

What I did:
I considered that those fasta were just forward reads and ran Dada2 using the forward-only workflow. For the three other data sets, I ran the normal Dada2 workflow. I obtained four seqtabs and made sure to keep the same reads length range for each using:

>seqtab [,nchar(colnames(seqtab)) %in% seq(422,497)]

Problem:
In the final ASVs table, it appears that samples from Run 1 do not share any ASVs with the three others. And I know they should.

Question:
I believe this question is somehow related to #331 but I thought I would first ask what you thought of my approach (i.e running the forward workflow on the merged fasta files) as it probably explains the final results observed in the ASVs table. Is there a way to analyse and merge the data from Run 1?

Any suggestion would be great.
Cheers

Example:
ASVs sequences present only in Run 1 :
>GATGAACGCTGGCGGTATGCCTAACACATGCAAGTCGAACGAAAGTGTAAACTTTAGTGGCGGACGGGTGAGTAAAGCATGAGAATCTACCCTCAGGAGAGGAATAACAATTGGAAACGATTGCTAATACCTCGTATGCTACTCGTAGTCAAAGGAGTAATCCGCCTGAGGACGAGCTCATGTCTGATTAGCTAGTTGGTAGGGTAAAAGCCTACCAAGGCAACGATCAGTAGCTGGTTTGAGAGGACGATCAGCCACACTGGGACTGAGACACGGCCCAGACTTCTACGGAAGGCAGCAGTGGGGAATTTTCCGCAATGGGCGCAAGCCTGACGGAGCAATACCGCGTGAGGGAAGAATGCCTGAGGGTTGTAAACCTCTTTTTTTAGGAAAGAAGAACTGACGGTACCTAAAGAATAAGCATCGGCTAACTCCGTGCCAGCCGCCGCCGTAACAC

>AACGAACGCTGGCGGCAGGCCTAACACATGCAAGTCGAGCGCACCTTCGGGTGAGCGGCGGACGGGTTAGTAACGCGTGGGAACGTGCCCTTCTCTAAGGAATAGCCTCTGGAAACGGAGAGTAATACCTTATACGCCCTTCGGGGGAAAGATTTATCGGAGAAGGATCGGCCCGCGTTGGATTAGGTAGTTGGTGAGGTAACGGCTCACCAAGCCGACGATCCATAGCTGGTTTGAGAGGATGATCAGCAACACTGGGACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCAGTGGGGAATCTTAGACAATGGGGGAAACCCTGATCTAGCCATGCCGCGTGAGTGATGAAGGCCCTAGGGTCGTAAAGCTCTTTCGCCAGGGATGATAATGACAGTACCTGGTAAAGAAACCCCGGCTAACTCCGTGCCAGCCGCCGCCGTAACAC

ASVs sequences present in the three other runs:
>ATGAACGCTGGCGGTATGCCTAACACATGCAAGTTGTACGAAAGTTTATACTTTAGTAGCGGACGGGTGAGTAACACGTGAGAATCTACCTTTGGGAGGGGAATAACAATTGGAAACGACTGCTAATACCCCATATGCTTAAGAGTGAAAAGATTCATCTGCCCGAAGATGAGCTCACGCCTGATTAGCTAGTTGGTAAGGTAAAAGCTTACCAAGGCGACGATCAGTAGCTGGTTTGAGAGGATGATCAGCCACACTGGGACTGAGACACGGCCCAGACTTCTACGGAAGGCAGCAGTGGGGAATTTTCCGCAATGGGCGGAAGCCTGACGGAGCAATACCGCGTGAGGGAAGAATGCCTGTGGGTTGTAAACCTCTTTTTTTAGGGAAGAAGATATGACGGTACCTAAAGAATAAGCATCGGCTAACTCCG

**Comment by benjjneb** [comment]
The key consideration is that the merged amplicon needs to be trimmed in the same way in both runs.

What were the `trimLeft` parameters you used in each case? Was any trimming performed outside of dada2 (e.g. removing primers) in either pipeline?

The runs probably can be merged, but the sequences will need to be trimmed to exactly the same genetic region, and for that we need to know precisely what trimming was performed in each case.

**Comment by GaelleQ** [comment]
Hi @benjjneb,
Thanks for your quick response. 

My primers are: 
F: AGRGTTTGATCMTGGCTCAG
R: GWATTACCGCGGCKGCTG

The fasta files I used look like this (primers and extra nucleotides are in bold):

Run 1: merged fasta ( ~ 440 nucletoides)
**CTATTCAGAGGGTTTGATCCTGGCTCAG**AATGAACGCTATTAGTTAACCTAACACATGCAAGTCAATTTAAAAGTTATCTTTAGTTTTTAAACGGCGTACGGGTGAGTATAACATAAAAATTTACCTTTTTATTTATTAGTTTGATTAATAAATAGAAAGAAAAATTTATGAAAGATTAAGTAGTTGATTCAAAAAAACCATCAAGCTTATGATCTTTAGTTGATCTGTGAGGATGACCAGCCACATTGGAACTGAGACAAGGTCCAAACTTCTAAAAGAAGGCAGCAGTGGGGAATATTGGACAATGAGCGAAAGCTTGATCCAGTTAAACTAAATGTATGAAGAAAATGTTTAATTGTAAAATACGTCAAAAATTTGAACAATGATCAAATTTTTCTCAGTTCTGGCTAATTTTGTGCCAGCAGCCGCGGTAAAAC

Run 2, 3, 4: R1 (300 nucletotides)
**AGGGTTTGATCCTGGCTCCG**AATGAACGCTAGTACTTAACCTTTCTCCTGCACTTTCACCTCTATAGATGAGCAAACGGGTGTTTATCACTTATCTATTTACCTTTTTTGCAAACAAAAAAGAAGAGTTTATGTATGATTAAGTAATTTGCCTAAAAACTAGTCCAGCTAACAATCTTTAGTTTATCTGTGAGGATGACCAACCACATTGGAACTGAGATAGGTCCAAACTTCTATAAGAATGCTGCAGTTGGTATTATTTGACAATGAGCGAATGCTTGTTCCTGTTAAATTACATGTA

Run 2, 3, 4: R2 (300 nucleotides)
**GTATTACCGCGTCGGCTG**GCACGGAGTTAGCCGGTGTTTCTTTACCAGGTACTGTCATTATCATCCCTGGCGACAGAGCTTTACCACCCTCGGCCCTTCGTCACTCACGCGGCCTTGCTAGCTCAGCCTTTCCCCCATTTTCTAAGATTCCCCTCTGCTGCCTCCCCTAGGATTCTGTGCCGTGTCTCATTCCCAGTGTTGCTTTTCTTCCTCTCAAACCCCCTATGGATCTTATCCTTGGTAGGCCTTTTCACCACCACCTACCTATGCACACCCCTCCTAATCCATTTCCGCGCCAT

Trimming was performed in Dada2 only using the following parameters:

>Run_1 <- filterAndTrim(fnFs, filtFs, trimLeft=28, maxN=0, maxEE=2, truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE)

>Run_2 <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, trimLeft=c(21,21), truncLen=c(280,280), maxN=0, maxEE=c(2,5), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE)

>Run_3 <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, trimLeft=c(21,21), truncLen=c(280,250), maxN=0, maxEE=c(2,5), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE)

>Run_4 <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, trimLeft=c(21,21), truncLen=c(260,280), maxN=0, maxEE=c(2,5), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE)

I used a different trimming for Run 1 only. Do you think that could explain the absence of shared ASVs in the final table between Run 1 and the rest or does the problem lie elsewhere?

**Comment by benjjneb** [comment]
> Do you think that could explain the absence of shared ASVs in the final table between Run 1 and the rest or does the problem lie elsewhere?

Yes, that is the reason why there is no overlap. Consider the following

```
AAACGTACGTACGTG # Run 1
--ACGTACGTACGT- # Run 2/3/4
```

They aren't overlapping between Run1 and the rest because the same sequences have been trimmed to different specific genetic locations.

Step 1 to fix this would be to use `trimLeft=21` in Run 1, but that doesn't fix the "end point" mismatch on the 3' part of the sequence. What would be ideal here would be a `trimRight` parameter in `filterAndTrim`...

**Comment by GaelleQ** [comment]
Hi @benjjneb,
A trimRight option would indeed be ideal as I would need to remove 21 base pairs from the right side of the reads. Unfortunately, this option doesn't exist, does it? @maxfarrell in #424 had the same issue and you suggested to use truncLen. However, in my case I am afraid the length variation problem remains.. What would be your suggestion?

**Comment by benjjneb** [comment]
Until we add `trimRight` you can use the following workaround.

Reprocess Run 1 with `trimLeft=21`, to equalize the start positions of all the sequences. Then you can do a by-hand trimming of 21 bases of the right of the Run 1 sequences.

First, make the Run1 sequence table: `st1`
Then, cut off the last 21 nts of each sequences: 
```
sq1 <- colnames(st1)
sq1.trim <- substr(sq1, 1, nchar(sq1)-21)
colnames(st1) <- sq1.trim
```

Then you'll need to collapse the duplicate sequences that (may) have arisen after this truncation step. The code to do this is borrowed from #459 

```
sq1 <- colnames(st1)
unq1 <- unique(sq1)
st1.trim <- matrix(0L, nrow=nrow(st1), ncol=length(unq1))
rownames(st1.trim) <- rownames(st1)
colnames(st1.trim) <- unq1
for(col in seq(ncol(st1))) {
    sq <- sq1[col]
    st1.trim[,sq] <- st1[,sq] + st1.trim[,col]
}
# Sanity check
identical(rowSums(st1), rowSums(st1.trim)) # Should be TRUE
```

At that point, `mergeSequenceTables(st1, ...)` should be fine!
But let me know. 

*Note to self: The "collapseIdentical" step above should be added as a function in the package.*

**Comment by GaelleQ** [comment]
Hi @benjjneb,

Thanks for your help and for the solution you’ve come up with. 

Quick update:
Before I got your last post, I thought about another option. I used the program “cutadapt” to cut off the last 21 nts of each sequence. It did a great job and ran super quickly.

I then reprocessed Run 1 using `trimLeft=29` and not `trimLeft=21` in the forward-only workflow. If you look at my first post, you can see that in order to equalize the start positions of all the sequences, I need to remove 29 nts and not 21 from the Run 1 sequences. 

> out <- filterAndTrim(fnFs, filtFs, trimLeft=29, maxN=0, maxEE=2, truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE)

Question: Do you agree on that or is there something I did not understand correctly regarding the overlap and the trimming?

I then merged the four runs using mergeSequenceTables and obtained a final ASVs table which looks fine! It looks like using cutadapt did the job. But it would be great to have a trimRight option anyway!

**Comment by benjjneb** [comment]
Looks good! Yeah I should have thought about the 3rd party software solution.

Going to leave this issue open as an enhancement request to add a `trimRight` option.
