### ISSUE TITLE
ASVs of different lengths obtained after merging paired-end reads in multiple sequencing runs

### ISSUE THREAD

**Issue by katharing** [benjjneb/dada2#472]
Hi Ben,

I'm performing paired end V4 sequencing with 515F-806R primers.  Primer + barcode sequences are removed during initial splitting (using QIIME's split_libraries_fastq.py ), so I don't use trimLeft. 

When I combine seqtabs from multiple sequencing runs, I found some ASVs in one run that had ASV counterparts in another run that were identical except for an additional 2 nucleotides.   Because of the  additional two nucleotides, these ASVs are not collapsed.   As this is timecourse data across many samples, I know that ASV1 in run 1 corresponds biologically to ASV2 in run 2.

I am using paired end reads and set truncLenF and truncLenR like this:
**Run 1 (the run with shorter ASVs)**
truncLenF: 200
truncLenR: 150

**Run 2 (the run with longer ASVs)** 
truncLenF: 255
truncLenR: 200

I reran the filtering and trimming on Run 2 with more conservative parameters:
truncLenF: 245
truncLenR: 165

And the longer ASVs disappear.  

Do you know why I'm getting longer ASVs at all?  I figured I was giving  my reads enough overlap with my truncLens..

**Comment by benjjneb** [comment]
> truncLenF: 255

The average length of your amplicons is 253 nts, so the forward reads actually extended 2 nts (on avreage) into the reverse primer. This can be cleaned up by turning on the `trimOverhang` parameter, `mergePairs(..., trimOverhang=TRUE). But best practices is what you did actually -- truncating before reading into the other primer to avoid any issues with ambiguous nucleotides (so `truncLenF=250` or less for this amplicon).
