### ISSUE TITLE
problems on assign taxonomy for fungi

### ISSUE THREAD

**Issue by sicencecat** [benjjneb/dada2#474]
I used DADA2 to filter and use "assignTaxonomy" to assign taxonomy for fungi. I used the General Fasta release files from the UNITE ITS database and found it does not work. When I open the database, I found something like this:
>Agaricomycetes_sp|KX857804|SH641340.07FU|reps|k__Fungi;p__Basidiomycota;c__Agaricomycetes;o__unidentified;f__unidentified;g__unidentified;s__Agaricomycetes_sp
TGCGGAGGATCATTAT...(note: In "silva_nr_v128_train_set", it is: >Bacteria;Bacteroidetes;Sphingobacteriia;Sphingobacteriales;NS11-12_marine_group;
ATGAACGCTAGCGGCAGGC...)

Is the format right ? If it is not right, where can I found the right references?

**Comment by benjjneb** [comment]
Can you clarify what "it does not work" means? 
Is `assignTaxonomy` failing with an error? Or just not giving the results you expected?

Also, what version of the dada2 package are you using? `packageVersion("dada2")`

UNITE support was added in the 1.4 release I think, and when you run `assignTaxonomy` with the UNITE db you should get the message `UNITE fungal taxonomic reference detected.`.

**Comment by sicencecat** [comment]
> packageVersion("dada2")
[1] ‘1.8.0’
> seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
Identified 25 bimeras out of 445 input sequences.
> taxa <-assignTaxonomy(seqtab.nochim, "d:/Biov/sh_general_release_dynamic_s_01.12.2017.fasta",minBoot = 50, tryRC = FALSE,
+   outputBootstraps = FALSE, taxLevels = c("Kingdom", "Phylum", "Class",
+   "Order", "Family", "Genus", "Species"), multithread = FALSE,
+   verbose = FALSE)
UNITE fungal taxonomic reference detected.
Error in C_assign_taxonomy(seqs, rc(seqs), refs, ref.to.genus, tax.mat.int,  : 
  Memory allocation failed.

**Comment by benjjneb** [comment]
How much memory (RAM) do you have available?

**Comment by sicencecat** [comment]
4.0 GB; 3.16GB available.

**Comment by benjjneb** [comment]
My guess is that it is failing due to a lack of available RAM, and the issue has cropped up for you recently because you're using a newer version of the UNITE db that has more sequences in it.

Can you access a compute environment w/ 8GB of RAM? That's what I am using, and the UNITE db runs fine.

The memory scaling of `assignTaxonomy` is something that has been brought up before: #239
