### ISSUE TITLE
Problems building on ARM based servers 

### ISSUE THREAD

**Issue by olewsaa** [benjjneb/dada2#475]
We have an ARM based server for bioinformatics running Ubuntu with a lot of debian-med packages.
A request for dada2 triggered the installation, but very soon run into trouble. The source code should compiler, but there are x86 specific code in the source. 
The errors are missing cpuid.h etc. 

g++ -march=armv8-a+crc+crypto  -mcpu=cortex-a72 -c Rmain.cpp -o Rmain.o
Rmain.cpp:7:10: fatal error: cpuid.h: No such file or directory
 #include <cpuid.h>
      
As ARM based servers are ramping up in this segment I would like to raise the issue here and ask for a fix so that it will build on ARM systems, preferable Ubuntu. 

Regards,
Ole W. Saastad 
University of Oslo.
olews@usit.uio.no

**Comment by terjekv** [comment]
I'm running into this problem now. I'll have to dig a bit into the code and see if we can `ifdef` ourselves out of the problem on `__aarch64__` and keep `cpuid.h` around for x86_64.

**Comment by benjjneb** [comment]
This was fixed a little after the M1 Macbooks came out. Package builds fine on ARM now.
