### ISSUE TITLE
Losing all reads after merging

### ISSUE THREAD

**Issue by katharing** [benjjneb/dada2#476]
Hi Ben,
I'm having some issues where I am losing all of my reads after merging.  Any  ideas what could be happening? My TruncLens are (245,150) for one run and (245,200) for the other run, so primers shouldn't be in either read. Here is the head for the forward and reverse for one of the filtered .fastq files:

**Forward reads:**
@3300_522 M00738:32:000000000-BNMDV:1:1101:15027:1926 1:N:0:1 orig_bc=AAGGAGCGCCTT new_bc=AAGGAGCGCCTT bc_diffs=0
TACGTAGGTGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGAGCGCGCAGGTGGTTAATTAAGTCTGATGTGAAAGCCCACGGCTTAACCGTGGAGGGTCATTGGAAACTGATTGACTTGAGTGCAGAAGAGGGAAGTGGAATTCCATGTGTAGCGGTGAAATGCGTAGAGATATGGAGGAACACCAGTGGCGAAGGCGGCTTACTGGTCTGCAACTGACACTGAGGCGCGAAAGCGTGGGGAG
+
B@C@CFGGGGGGGGGGGGGFGFGGGGGGGGGGGGGGGGGGGGGGGGGGDGGGAGGGDCFFGGGGGGGGDEFGEGGGGGGGGGGGGGEGGGFGGGGGGGGGGFGGGGG<FGGG9AFEGGGGGGGGFCFGFGGGGGG6@CBEGG?EGGG=FFGGGDGGDGGE6,EDFDDEA557+=+?CF7C>6D>6DE@@CCF>>>A*:AEDBBD);AFCA7C13+A@E13=7EF@AFF(679BFBFFF?<5C(49
@3300_527 M00738:32:000000000-BNMDV:1:1101:11886:1927 1:N:0:1 orig_bc=AAGGAGCGCCTT new_bc=AAGGAGCGCCTT bc_diffs=0
TACGTAGGATGCGAGCGTTATCCGGAATTACTGGGTGTAAAGGGAGCGCAGGCGGGACTGCAAGTTGGATGTGAAATGCCGCAGCTTAACTGCGGAGCTGCATCCAAAACTGTAGTTCTTGAGTGGAGTAGAGGCAAGCGGAATTCCGAGTGTAGCGGTGAAATGCGTAGATATTCGGAGGAACACCAGTGGCGAAGGCGGCTTGCTGGGCTCTAACTGACGCTGAGGCTCGAAAGTGTGGGGAG
+
CBCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGFFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFEFFGGGGGGGGGG6FGGGGGCDGGGFGCFGGFGGGDC?*DE:=F5ADAEFCFGFGG:DD=CF,BEFDGF;>>>A3AFGCFBEEFFGGB??BBFE>92A20:BFFFFF::9>F:>AFFBDDB<9
@3300_674 M00738:32:000000000-BNMDV:1:1101:10135:1955 1:N:0:1 orig_bc=AAGGAGCGCCTT new_bc=AAGGAGCGCCTT bc_diffs=0
TACGTAGGTGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGAGCGCGCAGGTGGTTAATTAAGTCTGATGTGAAAGCCCACGGCTTAACCGTGGAGGGTCATTGGAAACTGGTTGACTTGAGTGCAGAAGAGGGAAGTGGAATTCCATGTGTAGCGGTGAAATGCGTAGAGATATGGAGGAACGCCAGTGGCGAAGGCGGCTTCCTGGTCTGCAACTGACACTGAGGCGCGAAAGCGTGGGGAG

**Reverse reads**:
@3300_522 M00738:32:000000000-BNMDV:1:1101:15027:1926 1:N:0:1 orig_bc=AAGGAGCGCCTT new_bc=AAGGAGCGCCTT bc_diffs=0
TACGTAGGTGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGAGCGCGCAGGTGGTTAATTAAGTCTGATGTGAAAGCCCACGGCTTAACCGTGGAGGGTCATTGGAAACTGATTGACTTGAGTGCAGAAGAGGGAAGTGGAATTCCATG
+
B@C@CFGGGGGGGGGGGGGFGFGGGGGGGGGGGGGGGGGGGGGGGGGGDGGGAGGGDCFFGGGGGGGGDEFGEGGGGGGGGGGGGGEGGGFGGGGGGGGGGFGGGGG<FGGG9AFEGGGGGGGGFCFGFGGGGGG6@CBEGG?EGGG=FF
@3300_527 M00738:32:000000000-BNMDV:1:1101:11886:1927 1:N:0:1 orig_bc=AAGGAGCGCCTT new_bc=AAGGAGCGCCTT bc_diffs=0
TACGTAGGATGCGAGCGTTATCCGGAATTACTGGGTGTAAAGGGAGCGCAGGCGGGACTGCAAGTTGGATGTGAAATGCCGCAGCTTAACTGCGGAGCTGCATCCAAAACTGTAGTTCTTGAGTGGAGTAGAGGCAAGCGGAATTCCGAG
+
CBCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGFFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFEFFGGGGGGGGGG6FGGGGGCDGGGFGC
@3300_674 M00738:32:000000000-BNMDV:1:1101:10135:1955 1:N:0:1 orig_bc=AAGGAGCGCCTT new_bc=AAGGAGCGCCTT bc_diffs=0
TACGTAGGTGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGAGCGCGCAGGTGGTTAATTAAGTCTGATGTGAAAGCCCACGGCTTAACCGTGGAGGGTCATTGGAAACTGGTTGACTTGAGTGCAGAAGAGGGAAGTGGAATTCCATG
 

Any advice would be much appreciated!

**Comment by benjjneb** [comment]
What primer set/gene region are you sequencing?

**Comment by benjjneb** [comment]
It looks like your reverse reads were reverse-complemented (by the seqencing center?). This causes merging to fail, as `mergePairs` is trying to stitch the reads together in mismatched orientations.

Can they be rc-ed back to the expected orientation?

**Comment by katharing** [comment]
Thanks so much Ben! It turns out I split on the forward reads twice. Really appreciate the help!
