### ISSUE TITLE
V3-V4 : denoise-paired suggestion 

### ISSUE THREAD

**Issue by shashankx** [benjjneb/dada2#477]
I am trying to do the analysis for V3-V4 region, I am little confused about the "deniose-paired" step. I mean which parameter is good enough for this data.

Currently I am using-
qiime dada2 denoise-paired --i-demultiplexed-seqs demux-paired-end.qza 
--o-table table --o-representative-sequences rep-seqs 
--p-trim-left-f 6 --p-trim-left-r 6 
--p-trunc-len-f 0 --p-trunc-len-r 0 
--p-n-threads 20

I am attaching the data for visualization
[V3-V4.pdf](https://github.com/benjjneb/dada2/files/2047830/V3-V4.pdf)

The parameter I am using for this kind of data is good enough or should I use other parameters?

Best,
S

**Comment by shashankx** [comment]
I have already removed the primer.

Secondly, if I use **truncLen=c(270, 220)**, that will remove all the bases from other reads which might have good bases as well, please correct me if I am wrong.

In this case, should I first use other tools like **trimmomatic** or **cutadapt** which will first remove the bad quality bases from the end of the reads and then I proceed further with dada2?

**Comment by benjjneb** [comment]
Oh if you've already removed the primer then you have more wiggle room on truncation (the amplicon is ~425nts w/o primers), and I would cut off a bit more of the tail. Maybe `truncLen=c(260, 200)`.

> In this case, should I first use other tools like trimmomatic or cutadapt which will first remove the bad quality bases from the end of the reads and then I proceed further with dada2?

No. Ragged trimming based on quality score will give you worse results. This is because dada2 is fundamentally relying on repeated observations of the same read to distinguish biological sequences. Truncating to a fixed length (or to encountering a reverse primer) is the correct way to proceed.

**Comment by shashankx** [comment]
thanks for the information

**Comment by Mayomiski** [comment]
> I am trying to do the analysis for V3-V4 region, I am little confused about the "deniose-paired" step. I mean which parameter is good enough for this data.
> 
> Currently I am using-
> qiime dada2 denoise-paired --i-demultiplexed-seqs demux-paired-end.qza
> --o-table table --o-representative-sequences rep-seqs
> --p-trim-left-f 6 --p-trim-left-r 6
> --p-trunc-len-f 0 --p-trunc-len-r 0
> --p-n-threads 20
> 
> I am attaching the data for visualization
> [V3-V4.pdf](https://github.com/benjjneb/dada2/files/2047830/V3-V4.pdf)
> 
> The parameter I am using for this kind of data is good enough or should I use other parameters?
> 
> Best,
> S

Why do you put **20** to the **--p-n-threads** parameter? I saw people use different numbers for this parameter but I don understand why. Thank you a lot for your answer in advance.

**Comment by benjjneb** [comment]
> Why do you put 20 to the --p-n-threads parameter? I saw people use different numbers for this parameter but I don understand why. Thank you a lot for your answer in advance.

This relates to the number of threads you want the algorithms to use (and is specified by e.g. `multithread=20` in the R package). Typically, the best speedup is obtained with a number of threads equal to the number available on your machine, and that varies a lot. For example, modern desktops/laptops often have 4-8 threads available, while servers typically have more.

You can also set `multithread=TRUE`, in which case the software automatically detects how many threads are available, and uses that number.
