### ISSUE TITLE
pool mode in big data workflow

### ISSUE THREAD

**Issue by yhuang15** [benjjneb/dada2#479]
Hello.  Thanks for the great tutorials!  In the Big Data workflow, I assumed the pooling mode (pool = TRUE" or pool="pseudo") wouldn't work during ASV inference since the samples are processed sequentially using a for-loop - am I correct or am I missing something?

**Comment by benjjneb** [comment]
Correct. Pseudo-pooling can still be done by hand w/in the Big Data workflow quite easily though if you are interested in that approach (and that's what I do now for most datasets).

**Comment by yhuang15** [comment]
Would you mind sharing your approach?  It would be much appreciated!

**Comment by benjjneb** [comment]
Basically run the Big Data workflow through to the final table. Then select the variants from that table that you want to "pseudo-pool" with. Usually I select all over some prevalence threshold that depends on just how big the data I'm working with is (e.g. if thousands of samples, maybe present in at least 6 samples). e.g.

```
priors <- getSequences(seqtab)[colSums(seqtab>0) >= PREVALENCE_THRESHOLD]
```

Then just redo the denoising a second time, but with those priors provided:

```
# Infer sequence variants W/ PRIORS
dds <- vector("list", length(sample.names))
names(dds) <- sample.names
for(sam in sample.names) {
  cat("Processing:", sam, "\n")
  derep <- derepFastq(filts[[sam]])
  dds[[sam]] <- dada(derep, err=err, multithread=TRUE, priors=priors)
}
# Construct sequence table and write to disk
seqtab <- makeSequenceTable(dds)
saveRDS(seqtab, "path/to/run1/output/seqtab_priors.rds") # CHANGE ME to where you want sequence table saved
```

And finish by making the new full sequence table and removing chimeras as before, but this time with high sensitivity (down to singleton level) to all the sequences in your list of priors. In total, that is the `pool="pseudo"` worfklow, just split into a loop so samples only are loaded into memory one at a time.

**Comment by yhuang15** [comment]
@benjjneb Awesome!  Thanks so much!

**Comment by pooranis** [comment]
How would you modify this for paired end data?

**Comment by benjjneb** [comment]
> How would you modify this for paired end data?

Just run F/R reads separately, all the way through the generation of F/R sequence tables to get priors, then use those priors to run the workflow as normal (including merging).

**Comment by pooranis** [comment]
I was thinking along those lines, but wasn't sure.  Thanks so much for a fast response!
