### ISSUE TITLE
How to Separate 16s and 18s amplicons for Individual Taxonomic analysis in Paired-end Reads

### ISSUE THREAD

**Issue by compbiolover** [benjjneb/dada2#481]
I am currently working with two different primer sets that each amplify slightly different regions of the 16s gene. One of these primer sets has been reported to be able to also amplify eukaryotic DNA (i.e.- fungi). I have used Dada2 in Qiime2 and have been really impressed, but have been unable to figure out how to solve this particular problem. Any help is welcome! Thanks so much!

**Comment by compbiolover** [comment]
Hi @benjjneb, 
Sorry for the slow response. My lab is currently moving to another building. Thank you so much for the help. I will try this out soon and report back with what happens.

**Comment by benjjneb** [comment]
Feel free to reopen as needed.

**Comment by compbiolover** [comment]
I forgot to update this and say that I found a way to separate the reads. This workflow from Mike Lee (https://twitter.com/AstrobioMike) was immensely helpful.

**Comment by benjjneb** [comment]
Great thanks for update, and to @AstrobioMike for his workflows!
