### ISSUE TITLE
Combining Datasets

### ISSUE THREAD

**Issue by Philippa36** [benjjneb/dada2#482]
I want to combine a small set of old data with a larger set of new data, and am wondering what is the best approach to take?

I thought the error rates between the 2 datasets would vary, so I wouldn't be able to combine before learning errors, and maybe instead should combine the seqtab.nochim tables? Would this work? I would then covary for place of sequencing etc later on.

On the other hand, are the names of the ASVs specific to the dataset (and therefore diffcult to combine across datasets), or according to a reference (and therefore possible to combine)?

I would apppreciate any advice
Thank you

**Comment by benjjneb** [comment]
The last section of the Big Data workflow might help: https://benjjneb.github.io/dada2/bigdata.html#merge-runs-remove-chimeras-assign-taxonomy

Basically treat the old dat and new data as separate runs. Process each into sequence tables. Then merge the sequence tables, and remove chimeras on the total table.

As long as the datasets are from amplifying the same gene region, they can be simply merged (i.e. the ASVs will be consistent across the datasets).

**Comment by Philippa36** [comment]
That's great - thank you!

**Comment by Fedorov113** [comment]
But what should I do, if the datasets are processed with different `truncLen `parameters?

**Comment by benjjneb** [comment]
> But what should I do, if the datasets are processed with different truncLen parameters?

It it is paired end data that was then merged together, you still end up with the same gene region in the end, irrespective of the `truncLen` on the forward/reverse reads, and can merge the datasets as usual.

If it's single-read data, you need to truncate the longer dataset down to the length of the shorter dataset, and then you can merge the datasets together.

**Comment by fullertonhe** [comment]
Why should chimeras be removed after merging the two datasets?

**Comment by benjjneb** [comment]
> Why should chimeras be removed after merging the two datasets?

It guarantees that exactly the same sequences are flagged as chimeric in both datasets.
