### ISSUE TITLE
150bp vs 250bp reads, and using both in the same dataset?

### ISSUE THREAD

**Issue by Philippa36** [benjjneb/dada2#483]
Please could you give me some advice: if 2 datasets needed to be combined for analysis, where 1 used 150bp reads and the other 250, would this cause a difficulty, e.g with differences in the learning error rates?

Thank you.

**Comment by benjjneb** [comment]
The standard recommendation would be to process each dataset independently after trimming them to a constant gene region. Then they will be simply mergeable.

Did both datasets use the same primer set?

**Comment by Philippa36** [comment]
Thanks for your quick reply.

We haven't sequenced the second dataset yet (the potential 150bp one) - I was wondering if this would be one good reason not to use 150bp. Both sets are using the same primers though.

**Comment by benjjneb** [comment]
Is this paired end data? Will 2x150 overlap sufficiently to merge? If so, you'll be OK.

Although, all else equal, using the same sequencing tech as before will be the safest option if comparing the two datasets is of utmost importance.
