### ISSUE TITLE
Update Bioconda's DADA2 to 1.8.0

### ISSUE THREAD

**Issue by zefrieira** [benjjneb/dada2#486]
The version of DADA2 in Bioconda is still 1.6.0. Are there any plans on the developer's side to update it's recipe?

**Comment by benjjneb** [comment]
Yes it will be updated, but probably not til late June or July. 

You can read more here about the process of bioconda's Biodonductor updates here: https://github.com/bioconda/bioconda-recipes/issues/8947

**Comment by zefrieira** [comment]
Thank you for your answer! This slowness is due to the package being older or because of bioconda's build system?

**Comment by benjjneb** [comment]
> This slowness is due to the package being older or because of bioconda's build system?

Yes. They use a very old version of gcc and compile to a universal architecture, which substantially slows down the core denoising algorithm, especially on large datasets. If computation time is an issue for you, I would strongly recommend installing from Bioconductor.

> Should we expect performance improvements in 1.8.0?

Yes, but only about a 1.5x to 3x speedup.
