### ISSUE TITLE
assignTaxonomy NA handling

### ISSUE THREAD

**Issue by alexthibodeau** [benjjneb/dada2#487]
It would be great to have the option to have "NA" be replace by "xxx_unclassified" where xxx is the last classification level obtained.

Cheers!

**Comment by benjjneb** [comment]
It's not automatically supported, but it would be pretty easy to hack something up to do that. This might work?

```
propagate_tax <- function(tax) {
  col.prefix <- substr(colnames(tax), 1, 1) # Assumes named Kingdom, ...
  for(col in seq(2, ncol(tax))) {
    prop <- is.na(tax[,col]) & !is.na(tax[,col-1])
    newtax <- tax[prop,col-1]
    needs.prefix <- !grepl("^[A-z]__", newtax)
    newtax[needs.prefix] <- paste(col.prefix[col-1], newtax[needs.prefix], sep="__")
    tax[prop,col] <- newtax
  }
  tax
}
```

**Comment by alexthibodeau** [comment]
Thanks for the reply.

I saved the tax table in csv and changed it in libre office and imported it as tax file for phyloseq.

Thanks for the hack!
