### ISSUE TITLE
error in names(derepFs) <- sample.names

### ISSUE THREAD

**Issue by TamarBGU** [benjjneb/dada2#488]
Hey,
I am a new user with DAD2.
I am running a large dataset using only R1 reads (forward).
 getting to derepFs <- derepFastq(filtFs, verbose=TRUE)
i have encountered an error and the command stopped. 
I have solved it by using the following commands:
	exists <- file.exists(filtFs)
        filtFs <- filtFs[exists]
After which derepFs <- derepFastq(filtFs, verbose=TRUE) worked fine.
I then moved to names(derepFs) <- sample.names.
I now get the following error:
 'names' attribute [1849] must be the same length as the vector [1838]
I understand that some samples were removed for insufficient number of reads in the samples therefore they were not filtered and do not exist in the derepFs.
How can i solve this issue in order to continue?
I tried to re-use the commands i have before but derepFs is not a file.

Thanks!
Tamar

**Comment by benjjneb** [comment]
You can use the `exists` vector you defined to get the right names:

```
names(derepFs) <- sample.names[exists]
```

**Comment by DCrosbie1** [comment]
Hey I'm having a similar problem but when I try to dereplicate it tells my that 'not all files exist'. I defined the exist vector but now when I try to add names I get this warning message:
Warning message:
In `names<-`(`*tmp*`, value = "file.name") :
  derep-class objects cannot be renamed.

**Comment by benjjneb** [comment]
> In names<-(*tmp*, value = "file.name") :
> derep-class objects cannot be renamed.

This error indicates you only have a single sample that has passed filtering. How many samples did you start with? You may want to revisit your filtering parameters if having just a single sample remaining is unexpected.

**Comment by DCrosbie1** [comment]
I realise the path folder had a rogue file throwing everything off so it's all good now.
Thanks  for the quick response

**Comment by DCrosbie1** [comment]
I realised I had a rogue file in the path that was throwing everything off. All sorted now.
Thanks for the quick reply
