### ISSUE TITLE
Error when installing Tax4Fun

### ISSUE THREAD

**Issue by emankhalaf** [benjjneb/dada2#490]
Hi,

I try to download Tax4Fun package using its readme doc. I use
R CMD INSTALL Tax4Fun_0.3.1.tar.gz

Then I got this error:
* installing to library ‘/home/eman/anaconda3/lib/R/library’
ERROR: dependencies ‘qiimer’, ‘biom’ are not available for package ‘Tax4Fun’
* removing ‘/home/eman/anaconda3/lib/R/library/Tax4Fun’

So, I installed qiimer, (biomformat is already installed), then I repeated the command but still get the same error.

Swift help is much appreciated.
Thanks
Eman

**Comment by benjjneb** [comment]
Did you install qiimer and biom packages in that conda environment? I.e. if you open an R session in that conda environment, can you load those packages? Also, biom would be a different package than biomformat.

Other than that, you might have to ask the Tax4Fun people for help, I haven't actually used that package.

**Comment by emankhalaf** [comment]
I repeated installation from R console, but this time the error include biom package. I have biomformat as Biom has been deprecated. I will try to contact people of Tax4Fun.
Thanks

**Comment by emankhalaf** [comment]
Yes, it is solved. Create a conda environment, then install Tax4Fun and its dependencies in it. You can install biom packge (deprecated) in the environment. Then you can see the package installed in Rstudio, ready for loading.
Let me know if it works or not.
Good luck

**Comment by SantanuMBLab** [comment]
Hello  Emankhalaf,
I am also having the same problem in Installing Tax4Fun. Can you please guide me on how to successfully install Tax4Fun in R?

**Comment by ylock** [comment]
hi ,I have salve this problem by installed with source code,like this:
download the qiimer and biom source code (https://cran.r-project.org/src/contrib/Archive/qiimer/),(https://cran.r-project.org/src/contrib/Archive/biom/),for this two R packages you need to install tow dependence (pheatmap)(RJSONIO),and then you can install Tax4Fun. log like this :
> install.packages("qiimer_0.9.4.tar.gz")
Installing package into '/usr/local/lib/R/site-library'
(as 'lib' is unspecified)
inferring 'repos = NULL' from 'pkgs'
ERROR: dependency 'pheatmap' is not available for package 'qiimer'
* removing '/usr/local/lib/R/site-library/qiimer'
Warning message:
In install.packages("qiimer_0.9.4.tar.gz") :
  installation of package 'qiimer_0.9.4.tar.gz' had non-zero exit status
> install.packages("pheatmap")
Installing package into '/usr/local/lib/R/site-library'
(as 'lib' is unspecified)
^[[Ctrying URL 'https://cloud.r-project.org/src/contrib/pheatmap_1.0.12.tar.gz'
Content type 'application/x-gzip' length 15071 bytes (14 KB)
==================================================
downloaded 14 KB

* installing *source* package 'pheatmap' ...
** package 'pheatmap' successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (pheatmap)

The downloaded source packages are in
        '/tmp/RtmpUhX232/downloaded_packages'
> install.packages("qiimer_0.9.4.tar.gz")
Installing package into '/usr/local/lib/R/site-library'
(as 'lib' is unspecified)
inferring 'repos = NULL' from 'pkgs'
* installing *source* package 'qiimer' ...
** package 'qiimer' successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (qiimer)
----------------------------------------------------------------------------
> install.packages("biom_0.3.12.tar.gz")
Installing package into '/usr/local/lib/R/site-library'
(as 'lib' is unspecified)
inferring 'repos = NULL' from 'pkgs'
ERROR: dependency 'RJSONIO' is not available for package 'biom'
* removing '/usr/local/lib/R/site-library/biom'
Warning message:
In install.packages("biom_0.3.12.tar.gz") :
  installation of package 'biom_0.3.12.tar.gz' had non-zero exit status
> install.packages("RJSONIO")
Installing package into '/usr/local/lib/R/site-library'
(as 'lib' is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/RJSONIO_1.3-1.4.tar.gz'
Content type 'application/x-gzip' length 1166882 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

* installing *source* package 'RJSONIO' ...
** package 'RJSONIO' successfully unpacked and MD5 sums checked
** using staged installation
Trying to find libjson.h header file
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
USE_LOCAL = ""
Minor Version: 6
Using local libjson code. Copying files from src/libjson/Source
/tmp/RtmpHFsU1e/R.INSTALL4adb712859ef/RJSONIO
JSONAllocator.cpp
JSONChildren.cpp
JSONDebug.cpp
JSONIterators.cpp
JSONMemory.cpp
JSONNode.cpp
JSONNode_Mutex.cpp
JSONPreparse.cpp
JSONStream.cpp
JSONValidator.cpp
JSONWorker.cpp
JSONWriter.cpp
internalJSONNode.cpp
libjson.cpp
configure: creating ./config.status
config.status: creating src/Makevars
config.status: creating tools/cleanup
** libs
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I. -Ilibjson -Ilibjson/Source -DNEW_JSON_NEW_STREAM -DNDEBUG=1  -DJSON_VALIDATE -DJSON_STREAM=1 -DJSON_READ_PRIORITY=1 -DJSON_LIBRARY=1 -DJ
SON_ISO_STRICT    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-k1TtL4/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c ConvertUTF.c -o ConvertUTF.og++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I. -Ilibjson -Ilibjson/Source -DNEW_JSON_NEW_STREAM -DNDEBUG=1  -DJSON_VALIDATE -DJSON_STREAM=1 -DJSON_READ_PRIORITY=1 -DJSON_LIBRARY=1 -
DJSON_ISO_STRICT    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-k1TtL4/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c JSONAllocator.cpp -o JSONAllocator.og++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I. -Ilibjson -Ilibjson/Source -DNEW_JSON_NEW_STREAM -DNDEBUG=1  -DJSON_VALIDATE -DJSON_STREAM=1 -DJSON_READ_PRIORITY=1 -DJSON_LIBRARY=1 -
DJSON_ISO_STRICT    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-k1TtL4/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c JSONChildren.cpp -o JSONChildren.og++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I. -Ilibjson -Ilibjson/Source -DNEW_JSON_NEW_STREAM -DNDEBUG=1  -DJSON_VALIDATE -DJSON_STREAM=1 -DJSON_READ_PRIORITY=1 -DJSON_LIBRARY=1 -
DJSON_ISO_STRICT    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-k1TtL4/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c JSONDebug.cpp -o JSONDebug.og++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I. -Ilibjson -Ilibjson/Source -DNEW_JSON_NEW_STREAM -DNDEBUG=1  -DJSON_VALIDATE -DJSON_STREAM=1 -DJSON_READ_PRIORITY=1 -DJSON_LIBRARY=1 -
DJSON_ISO_STRICT    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-k1TtL4/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c JSONIterators.cpp -o JSONIterators.og++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I. -Ilibjson -Ilibjson/Source -DNEW_JSON_NEW_STREAM -DNDEBUG=1  -DJSON_VALIDATE -DJSON_STREAM=1 -DJSON_READ_PRIORITY=1 -DJSON_LIBRARY=1 -
DJSON_ISO_STRICT    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-k1TtL4/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c JSONMemory.cpp -o JSONMemory.og++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I. -Ilibjson -Ilibjson/Source -DNEW_JSON_NEW_STREAM -DNDEBUG=1  -DJSON_VALIDATE -DJSON_STREAM=1 -DJSON_READ_PRIORITY=1 -DJSON_LIBRARY=1 -
DJSON_ISO_STRICT    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-k1TtL4/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c JSONNode.cpp -o JSONNode.og++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I. -Ilibjson -Ilibjson/Source -DNEW_JSON_NEW_STREAM -DNDEBUG=1  -DJSON_VALIDATE -DJSON_STREAM=1 -DJSON_READ_PRIORITY=1 -DJSON_LIBRARY=1 -
DJSON_ISO_STRICT    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-k1TtL4/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c JSONNode_Mutex.cpp -o JSONNode_Mutex.og++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I. -Ilibjson -Ilibjson/Source -DNEW_JSON_NEW_STREAM -DNDEBUG=1  -DJSON_VALIDATE -DJSON_STREAM=1 -DJSON_READ_PRIORITY=1 -DJSON_LIBRARY=1 -
DJSON_ISO_STRICT    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-k1TtL4/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c JSONPreparse.cpp -o JSONPreparse.og++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I. -Ilibjson -Ilibjson/Source -DNEW_JSON_NEW_STREAM -DNDEBUG=1  -DJSON_VALIDATE -DJSON_STREAM=1 -DJSON_READ_PRIORITY=1 -DJSON_LIBRARY=1 -
DJSON_ISO_STRICT    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-k1TtL4/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c JSONStream.cpp -o JSONStream.og++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I. -Ilibjson -Ilibjson/Source -DNEW_JSON_NEW_STREAM -DNDEBUG=1  -DJSON_VALIDATE -DJSON_STREAM=1 -DJSON_READ_PRIORITY=1 -DJSON_LIBRARY=1 -
DJSON_ISO_STRICT    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-k1TtL4/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c JSONValidator.cpp -o JSONValidator.og++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I. -Ilibjson -Ilibjson/Source -DNEW_JSON_NEW_STREAM -DNDEBUG=1  -DJSON_VALIDATE -DJSON_STREAM=1 -DJSON_READ_PRIORITY=1 -DJSON_LIBRARY=1 -
DJSON_ISO_STRICT    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-k1TtL4/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c JSONWorker.cpp -o JSONWorker.og++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I. -Ilibjson -Ilibjson/Source -DNEW_JSON_NEW_STREAM -DNDEBUG=1  -DJSON_VALIDATE -DJSON_STREAM=1 -DJSON_READ_PRIORITY=1 -DJSON_LIBRARY=1 -
DJSON_ISO_STRICT    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-k1TtL4/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c JSONWriter.cpp -o JSONWriter.ogcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I. -Ilibjson -Ilibjson/Source -DNEW_JSON_NEW_STREAM -DNDEBUG=1  -DJSON_VALIDATE -DJSON_STREAM=1 -DJSON_READ_PRIORITY=1 -DJSON_LIBRARY=1 -DJ
SON_ISO_STRICT    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-k1TtL4/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c JSON_parser.c -o JSON_parser.ogcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I. -Ilibjson -Ilibjson/Source -DNEW_JSON_NEW_STREAM -DNDEBUG=1  -DJSON_VALIDATE -DJSON_STREAM=1 -DJSON_READ_PRIORITY=1 -DJSON_LIBRARY=1 -DJ
SON_ISO_STRICT    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-k1TtL4/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RJSON.c -o RJSON.ogcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I. -Ilibjson -Ilibjson/Source -DNEW_JSON_NEW_STREAM -DNDEBUG=1  -DJSON_VALIDATE -DJSON_STREAM=1 -DJSON_READ_PRIORITY=1 -DJSON_LIBRARY=1 -DJ
SON_ISO_STRICT    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-k1TtL4/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.og++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I. -Ilibjson -Ilibjson/Source -DNEW_JSON_NEW_STREAM -DNDEBUG=1  -DJSON_VALIDATE -DJSON_STREAM=1 -DJSON_READ_PRIORITY=1 -DJSON_LIBRARY=1 -
DJSON_ISO_STRICT    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-k1TtL4/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c internalJSONNode.cpp -o internalJSONNode.og++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I. -Ilibjson -Ilibjson/Source -DNEW_JSON_NEW_STREAM -DNDEBUG=1  -DJSON_VALIDATE -DJSON_STREAM=1 -DJSON_READ_PRIORITY=1 -DJSON_LIBRARY=1 -
DJSON_ISO_STRICT    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-k1TtL4/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c libjson.cpp -o libjson.ogcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I. -Ilibjson -Ilibjson/Source -DNEW_JSON_NEW_STREAM -DNDEBUG=1  -DJSON_VALIDATE -DJSON_STREAM=1 -DJSON_READ_PRIORITY=1 -DJSON_LIBRARY=1 -DJ
SON_ISO_STRICT    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-k1TtL4/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c rlibjson.c -o rlibjson.ogcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I. -Ilibjson -Ilibjson/Source -DNEW_JSON_NEW_STREAM -DNDEBUG=1  -DJSON_VALIDATE -DJSON_STREAM=1 -DJSON_READ_PRIORITY=1 -DJSON_LIBRARY=1 -DJ
SON_ISO_STRICT    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-k1TtL4/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c rparser.c -o rparser.og++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o RJSONIO.so ConvertUTF.o JSONAllocator.o JSONChildren.o JSONDebug.o JSONIterators.o JSONMemory.o JSONNode.o
 JSONNode_Mutex.o JSONPreparse.o JSONStream.o JSONValidator.o JSONWorker.o JSONWriter.o JSON_parser.o RJSON.o init.o internalJSONNode.o libjson.o rlibjson.o rparser.o -L/usr/lib/R/lib -lRinstalling to /usr/local/lib/R/site-library/00LOCK-RJSONIO/00new/RJSONIO/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (RJSONIO)

The downloaded source packages are in
        '/tmp/RtmpSngcef/downloaded_packages'
> install.packages("biom_0.3.12.tar.gz")
Installing package into '/usr/local/lib/R/site-library'
(as 'lib' is unspecified)
inferring 'repos = NULL' from 'pkgs'
* installing *source* package 'biom' ...
** package 'biom' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Creating a generic function for 'nrow' from package 'base' in package 'biom'
Creating a generic function for 'ncol' from package 'base' in package 'biom'
Creating a generic function for 'rownames' from package 'base' in package 'biom'
Creating a generic function for 'colnames' from package 'base' in package 'biom'
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (biom)
-----------------------------------------------------------------------------
> install.packages("Tax4Fun_0.3.1.tar.gz" ,repos = NULL, type = "source")
Installing package into '/usr/local/lib/R/site-library'
(as 'lib' is unspecified)
* installing *source* package 'Tax4Fun' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (Tax4Fun)

**Comment by FilipeMatteoli** [comment]
This is much easier now using https://rdrr.io/github/nick-youngblut/Tax4Fun/. qiimer still has to be installed from source though.
