### ISSUE TITLE
plotQualityProfile() warning 

### ISSUE THREAD

**Issue by RachelRodgers** [benjjneb/dada2#493]
Hi,

A minor issue, I think, but may be worth noting.  Passing a path to multiple fastq files to plotQualityProfile() returns warning "the condition has length > 1 and only the first element will be used."  Plot still generates but it's hard to tell if the warning is meaningful.  

I believe the error comes from the if statement on line 162 of plot-methods.R:
```
if (rc >= n) 
```
rc can be a vector greater than length 1 if passing in multiple files causing the if() to throw a warning.  This probably isn't what you intended?  Maybe it should be replaced with:
```
if (any(rc >=n))
```
?

I think this only impacts the plot labeling.

Thanks so much!

Rachel

**Comment by benjjneb** [comment]
Can you post the exact command you are running, and the commands you used to create the list of files that sparks this error? Also, `packageVersion("dada2")`?

**Comment by RachelRodgers** [comment]
I'm using dada2_1.6.0 on Ubuntu 16.04.  The code for this function looks similar to the current version.  Here's my commands:
```
# inputDir contains 36 fastq files
inputDir <- "../data/demultiplexed/split_samples"
rawQualPlot <- plotQualityProfile(inputDir, aggregate = TRUE)
rawQualPlot
```
Thank you!

**Comment by benjjneb** [comment]
There was a bug (that the warning was hinting at) that mattered if you had length variation in your input sequences. The warning should go away and calling `plotQualityProfile` on a directory containing fastq files should work as expected in 2df8c693563c4a3a09913d56ff03453b8b5a40ed
