### ISSUE TITLE
No read is lost during denoising

### ISSUE THREAD

**Issue by zefrieira** [benjjneb/dada2#494]
In every example run of DADA2 that I've seen, some reads were lost during the denoising step. So I find it weird that all my reads were kept after this step:

```
track %>% as.data.frame() %>% rownames_to_column("sample") %>% mutate(percentage = nonchim / input * 100) %>% head()

   sample  input    filtered  denoisedF  denoisedR  merged   nonchim  percentage
1  A       146249   138856    138856     138856     123599   119521   81.72432
2  B       196609   185896    185896     185896     168159   160783   81.77805
3  C       166757   157215    157215     157215     141142   136574   81.90001
4  D       155681   146165    146165     146165     130685   125865   80.84802
5  E       207764   195437    195437     195437     173501   168329   81.01933
6  F       172789   162608    162608     162608     144211   138918   80.39748
```

This happened to all my 84 samples (16S V4). As far as I know, DADA2 only discards singletons from the analysis (I used true pooling, not pseudo). Does this mean that there wasn't a single singleton in my entire set of pooled reads?

Thank you for your attention.

**Comment by benjjneb** [comment]
In version 1.6 and earlier, the `dada(...)` function attempts to correct every read in the dataset. If a read is miscorrected (e.g. perhaps a singleton) it is typically removed at the merging step.

As of 1.8, `dada(...)` corrects most, but not all, reads by default.  You will see a loss of some reads at the denoising step when using 1.8.

You can read more on that new functionality here: https://benjjneb.github.io/dada2/ReleaseNotes_1_8.html
