### ISSUE TITLE
Error rates could not be estimated. Error in err[c(1, 6, 11, 16), ] <- 1 :    incorrect number of subscripts on matrix

### ISSUE THREAD

**Issue by mlin11** [benjjneb/dada2#495]
Hi,

I am using DADA2(V1.8.0) with R 3.5.0 on my own simulation data. I got this error when I ran LearErrors:

> errF <- learnErrors(filtFs, multithread=TRUE)
239040 total bases in 996 reads from 1 samples will be used for learning the error rates.
Initializing error rates to maximum possible estimate.
Error rates could not be estimated.
Error in err[c(1, 6, 11, 16), ] <- 1 : 
  incorrect number of subscripts on matrix

Could you please give me some suggestions?

Thanks!

**Comment by benjjneb** [comment]
How are the simulated reads being generated? In particular, how are quality scores being assigned?

"Pathological" simulated quality scores (i.e. just 20 or 40) can cause the standard error-rate estimation method to fail, which might be what is causing this error.

**Comment by mlin11** [comment]
Simulated reads were generated using Grinder. The quality scores were assigned 30 and 10, where  good residues are given a specified good score (e.g. 30) and residues that are the result of an insertion or substitution are given a specified bad score (e.g. 10).

**Comment by mlin11** [comment]
Thanks. I will regenerate the simulated data with more realistic quality scores and run through DADA2.

**Comment by benjjneb** [comment]
OK. Feel free to re-open if the problem persists.

**Comment by glickmac** [comment]
Hi,

Can you provide an example of the input into the learnErrors function that incorporates a simple linear fit in the error estimation step? What are the variables in the function we are incorporating into errorEstimationFunction? 

Thanks!
