### ISSUE TITLE
Error in plotQualityProfile and filterAndTrim

### ISSUE THREAD

**Issue by msnyder424** [benjjneb/dada2#497]
Hello,

I have a large group of samples that when I try to process with Dada2 I get errors in a couple places early in the pipeline. When I try to run plotQualityProfile on the forward FastQs I get an error that says:
`Error: internal: buf != <newline>`
And when I try to run the filterAndTrim function I get a similar error that says:
`Error in add(bin) : internal: buf != <newline>`

There are 45 samples but I found by running plotQualityProfile on individual samples that not every sample has this problem. I have zipped and attached the trimmed FastQs from one sample that is causing this error so you can see what I am talking about. I verified that the error still happens when you run the pipeline on smaller subsets of these samples or on individual samples. Also, as you might expect the filterAndTrim function stops during the first file that has this issue. This error does not happen for other groups of samples that I run through the pipeline.

I saw in an older thread that this issue happened in the past due to corruption of decompressed FastQ files so I re-decompressed them and that did not help. I then re-downloaded the zip files from BaseSapce and decompressed them, and it still did not help. Is there any way to know why this sample is causing this error? If I can figure that out, maybe the same will be true for other samples that cause this error.

Thanks for making such a great and useful program and for any help you can provide on this issue.

Matt

[9BKP05_XXXX_R2_001.zip](https://github.com/benjjneb/dada2/files/2116702/9BKP05_XXXX_R2_001.zip)

**Comment by benjjneb** [comment]
Hi Matt,
It appears that some of these fastq files are malformed, specifically in the forward fastq files provided one of the entries has a different number of ACGTs than it does quality scores. See code below:

```
fn <- "~/Desktop/9BKP05_XXXX_R2_001/9BKP05_XXXX_R1_001.fastq"
foo <- readLines(fn)
seqlens <- sapply(foo[seq(2,length(foo),4)], nchar)
quallens <- sapply(foo[seq(4,length(foo),4)], nchar)
table(seqlens); table(quallens)
## seqlens
##    52    53 
##     1 92076 
## quallens
##    53 
## 92077 
which(seqlens != quallens)
## CGTCGGCAGCGTCAGATGTGAATTGGAGGAACACCCTCGTACATCTAGTACG 
##                                                44082 
```

This is causing the error your seeing. I'm not sure why this happened, but it will need to be rectified to use dada2 as the fastq functions all check and fail on malformed fastqs.

**Comment by msnyder424** [comment]
That is strange. Other groups of samples I have processed with the same trimming method ended up OK. 
Now I know the problem, thanks to you. Just have to figure out how to fix it. Thanks for your help!
