### ISSUE TITLE
tracing amplicons through dada2

### ISSUE THREAD

**Issue by ralsallaq** [benjjneb/dada2#498]
I am trying to evaluate the effect of dada2 on individual amplicons as they are processed into various steps in the pipeline. Specifically, if say I have a sample of 4000 forward and 4000 reverse reads and each read has an identifier (same one in both the reverse and forward reads), I want to be able to follow each read through its identifier after denoising, merging, chimera removing, and taxa assignment. Is that possible in dada2? I appreciate a working example, if possible. Many thanks for your time.

**Comment by benjjneb** [comment]
Unfrotunately no, right now there is no easy way to track individual reads through the entire workflow.. This is a feature we would like to add, and progress towards this will be recorded at #354
