### ISSUE TITLE
verbose = FALSE option in `dada`... and maybe option to save to a log file?

### ISSUE THREAD

**Issue by joey711** [benjjneb/dada2#5]
Printing them necessarily to std out is kind of annoying, and will convolute the vignette I was going to add because I'll need to do all this `cat` or `sink` type wrapping.

FYI, best practice in R is to throw these types of messages using the `message` function as an `if(verbose){}` protected expression.

If they are C-derived messages making their way to standard out... maybe need to optionally-wrap the C call with something like `sink`?

**Comment by benjjneb** [comment]
VERBOSE flag is implemented, and is FALSE by default.

The remaining printf messaging still needs to be fixed for packaging reasons, but closing this issue.
