### ISSUE TITLE
searching for unclassified sequences

### ISSUE THREAD

**Issue by cgarr017** [benjjneb/dada2#500]
I'm sure there's multiple ways to do this, but I'm still a novice to R and hoping you might know of an easy way. I'd like to search through the output ASV's for sequences of an unclassified bacteria, of which I know the 16s sequence (I have an isolate species that is not in the silva database). I'd like to get counts of the isolate for each sample. Alternatively, I'm thinking I could make a custom blast database of the output ASV's and blast the isolate, but I also am not sure how to export the ASV's into .fasta files, ideally with separate files for each sample. Thanks for listening.
-Cody

**Comment by benjjneb** [comment]
If you know the full 16S sequence, you can search for exact (or near-exact) matches to that sequence using the `vmatchPattern` function in the Biostrings package. This is a pretty powerful interface to several fast exact and near-exact string matching algorithms.

**Comment by cgarr017** [comment]
Great thanks! Can you also provide some insight on how to export the DADA2 output ASV's into text files, ideally with separate files for each sample?

**Comment by benjjneb** [comment]
There are R facilities to output into just about any file format you want. What are you trying to create, a fasta file? See: `uniquesToFasta` or `writeFasta`.

Something else? See for example `writeLines`.
