### ISSUE TITLE
Losing too many sequences after chimera removal

### ISSUE THREAD

**Issue by Philippa36** [benjjneb/dada2#503]
I am losing a high proportion of sequences after chimera removal, output:

Identified 1424 bimeras out of 2566 input sequences.

I thought the issue might be primers still attached, but I had included trimLeft c(12,12) in the filterandTrim step and thought this would remove the primers, I've tried increasing this up to 20 and still get the same issue.

I ran:
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, trimLeft = c(12,12), truncLen=c(240,160),
                     maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, multithread=TRUE)

Please help! Thank you.

**Comment by benjjneb** [comment]
> Considerations for your own data: Most of your **reads** should remain after chimera removal (it is not uncommon for a majority of **sequence variants** to be removed though). If most of your reads were removed as chimeric, upstream processing may need to be revisited. In almost all cases this is caused by primer sequences with ambiguous nucleotides that were not removed prior to beginning the DADA2 pipeline.
 
What fraction or your reads were removed? As noted in the above, it is not uncommon to see half (or even more) of sequences flagged as chimeric as you are seeing.

**Comment by Philippa36** [comment]
Thanks for replying so quickly, I'm losing around 55% reads, so it sounds like this is normal after all?

**Comment by benjjneb** [comment]
> I'm losing around 55% reads

Did you get this number from `1424/2566`? That is the fraction of **sequence variants** you lost, not **reads**.

If you follow the tutorial, to get the fraction of sequence variants you lost: `sum(seqtab.nochim)/sum(seqtab)`

**Comment by Philippa36** [comment]
Ah yes I was, sorry, for sum(seqtab.nochim)/sum(seqtab) I get 0.8994429.

**Comment by benjjneb** [comment]
Looks good. 10% chimeric reads is common and not a cause for concern here.

**Comment by Philippa36** [comment]
Great - thank you!

**Comment by spixar** [comment]
Hi. I have the same issue, except that I get 0.8004616 reads after removing the chimeras. Is this normal for the V4 region sequencing results? I see most tutorials results are around 0.95. Thanks a lot.

**Comment by benjjneb** [comment]
@spixar That is high-ish for V4 but not out of the normal range across studies. Chimera rates vary greatly depending on your PCR protocol.

**Comment by spixar** [comment]
Thank you. We have followed the EMP 16s rDNA sequencing protocol, and still don't know why the chimera is so high... Glad to know the quality is acceptable:)
