### ISSUE TITLE
Species Assignments - less than expected?

### ISSUE THREAD

**Issue by Philippa36** [benjjneb/dada2#504]
For the species assignment step, I thought that around 50% should be assigned unambiguously, but I seem to have much less than that:

taxa.sp <- addSpecies(taxa, "silva_species_assignment_v132.fa.gz", verbose=TRUE)

158 out of 1134 were assigned to the species level.
Of which 142 had genera consistent with the input table.

Please could you let me know if this is normal or not?

**Comment by benjjneb** [comment]
That's normal. Relatively few of the lower abundance stuff is going to be assigned to the species level.

Species level assignment is hard on 16S fragments. Our approach is conservative (requires exact matching) but [recent analyses suggest it is the only appropriate way to make species-level assignments on this kind of data](https://doi.org/10.1093/bioinformatics/bty113). Fuzzy matching will give you tons of false positives.

**Comment by Philippa36** [comment]
Ok great - thank you!
