### ISSUE TITLE
fastqPairedFilter not working

### ISSUE THREAD

**Issue by Philippa36** [benjjneb/dada2#505]
I am having to use an older version of dada2 at the moment and am therefore using fastqPairedFilter instead of filterandTrim, I can't seem to get it to work. Please could you have a look?
input:
out <- fastqPairedFilter(c(fnFs, fnRs), c(filtFs, filtRs), trimLeft = c(12,12), truncLen=c(240,160), maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE, compress=TRUE, verbose=TRUE)

output:
Error in fastqPairedFilter(c(fnFs, fnRs), c(filtFs, filtRs), trimLeft = c(12,  : 
  Two paired input file names required.

**Comment by benjjneb** [comment]
`fastqPairedFilter` has a clunkier interface than `filterAndTrim`, it can only filter one set of paired files at a time. You'll need to wrap it in a loop to go through all your files. You can see an example in the 1.2 version of the tutorial: https://benjjneb.github.io/dada2/tutorial_1_2.html#perform-filtering-and-trimming

**Comment by Philippa36** [comment]
Ah I see. Thank you again.
