### ISSUE TITLE
Option to choose Reverse reads with fastqFilter

### ISSUE THREAD

**Issue by mestaki** [benjjneb/dada2#510]
Is there a way to instruct fastqFilter to only use the Reverse reads of paired-end data instead of the default forward? I understand the reverse reads are almost always less quality than the forwards, but I recently saw data from 2 separate Illumina runs that had reverse reads with better overall quality than the forward reads.  This is just a convenience/enhancement suggestion as I could just import the reverse reads by themselves first in an extra step.

**Comment by benjjneb** [comment]
Sure, it's very easy actually. Just pretend that the reverse reads are the forward reads and run the workflow as you would with single-end reads (i.e. drop the `mergePairs` step).

**Comment by mestaki** [comment]
Thanks @benjjneb, sorry I should have been way more clear about my intent and after re-reading the documentations I think I figured it out anyways. I had the function of fastqFilter completely wrong in my head:P
My end goal was related to a q2-dada2 suggestion and I just wanted to clarify something before I raised an issue on the q2 page. So currently q2-dada2 can take in PairedEnd data and perform denoise-single, and by default would just drop the reverse. I wanted to see if it was possible to allow the option to drop the forwards instead, but wasn't sure if this needed to be done via dada2 or q2. After re-reading the tutorials, its pretty obvious that dada2 treats the reads separately right up till merging so this is something specific to q2, and so I'll raise an issue there. Thanks!

**Comment by alexthibodeau** [comment]
On this subject, sometimes you do not know, using MiSeq, which of R1 or R2 is the forward or reverse read. This could help I think. I guess it could be important when you are pooling different sequencing runs in the same analysis so you don't get ASV that are the reverse complement of others. Or I am wrong?
