### ISSUE TITLE
Fewer ASVs after pooling compared to pseudo pooling and not pooling

### ISSUE THREAD

**Issue by hegartybr** [benjjneb/dada2#511]
Hi @benjjneb, 

@ap2274 and I tried running the dada2 pipeline using the pool = T, F, and "pseudo" option for dada(). As expected, "pseudo" gives us more ASVs than pool = F (slightly more: 6028 for "pseudo" and 5978 for pool = F). However, when we run pool = T, we have significantly fewer ASVs (4510). I was wondering what might be making this happen.

For a little bit of background, we have 189 samples and sequenced the ITS region. 

We used the following filtering step for all three versions:
`out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, maxN = 0, maxEE = c(3,5), truncQ = 2, rm.phix = T,
                     compress = T, multithread = T)`

Here are the commands that we ran:
original run (no pooling):
`dadaFs <- dada(derepsFs, err = errF, multithread = T)`
`dadaRs <- dada(derepsRs, err = errR, multithread = T)`

pseudo-pooling
`dadaFs_pseudo <- dada(derepsFs, err = errF, multithread = T, pool = "pseudo")`
`dadaRs_pseudo <- dada(derepsRs, err = errR, multithread = T, pool = "pseudo")`

pooling
`dadaFs <- dada(derepsFs, err = errF, multithread = T, pool = T)`
`dadaRs <- dada(derepsRs, err = errR, multithread = T, pool = T)`

We then merged the sequences, constructed the ASV table, and removed chimeras as in the tutorial.

As expected from the differing numbers of ASVs we get each time, the number of reads surviving through chimera removal is highest for pooling = "psuedo" (57% vs 53% for pooling = F and 50% for pooling = T). 

Any insight would be greatly appreciated!

**Comment by benjjneb** [comment]
The results you are reporting are strongly suggesting to me that there are still primers on at least some of these reads.

Can you describe further what trimmning/truncation (if any) was done prior to dada2? Which ITS region are you sequencing, and what sequencing technology? Is it possible that some of your reads are reading through into the reverse primer?

**Comment by hegartybr** [comment]
Thanks for getting back to me! We sequenced using MiSeq, 2x250bp reads. The primers we're using were ITS2 (White eta al 1990) and ITS1-F (Gardes and Bruns, 1993).

We didn't do any filtering prior to what I mentioned in the first post. However, I did try repeating the pipeline after having run cutadapt to check both the 3' and 5' ends for my specific primers (there were some primers removed), but I got very similar results:
pooling=F: 5978 ASVs, 52% of reads surviving (before 5978 ASVs, 53% of reads surviving)
pooling=pseudo: 6025 ASVs, 57% (before 6028 ASVs, 57%)
pooling=T: 4561 ASVs, 48% (before 4510 ASVs, 50%)

Also, while almost all the ASVs in the pooling = T strategy are found in the set of ASVs from pooling = F or pseudo, not all of them are, so using pooling = T is giving some new ASVs (which would be expected). Is it possible that there are more ASVs in the pooling = F and pseudo instances because for different replicates different sequence variants are being selected as the ASV (but when pooling = T they are all being combined)?

Something else that concerns me is that for some of my replicates I'm losing over 99% of my reads upon merging (kind of like the issue here, but worse: #378 ). For instance, this is the head table of the reads surviving after each step for the pooling = T workflow (the numbers are very similar for the other two pooling strategies):
![screen shot 2018-07-09 at 11 07 41 am](https://user-images.githubusercontent.com/17277813/42458742-597462fe-8368-11e8-8e5a-3275774f63ad.png)

and this is a heatmap with the percent of reads surviving after each step, showing how for some samples (rows) the number of reads remaining drops precipitously after merging (and that some are just overall poor quality):
![image](https://user-images.githubusercontent.com/17277813/42458970-e7aea1b0-8368-11e8-95eb-d30a3f789d2b.png)

Any other suggestions would be greatly appreciated. Thanks!

**Comment by benjjneb** [comment]
Would you be able to share the raw fastqs from a sample or two?
Perhaps ideal would be one of the samples in which 90%+ reads are lost, and another where that doesn't happen.

My email address is benjamin DOT j DOT callahan AT gmail DOT com if you would prefer to not make the data accessible through this public forum.

Also, can you post the primer sequences?

**Comment by hegartybr** [comment]
I'll email you those files. Thanks for your help!

Also, here are the primer sequences:
ITS2: GCTGCGTTCTTCATCGATGC
ITS-1F: CTTGGTCATTTAGAGGAAGTAA

**Comment by benjjneb** [comment]
Thanks, received the files. Will take a closer look, but may be a few days until I get to it.

**Comment by benjjneb** [comment]
Woops, forgot about this. Will try to get back to this soon.
