### ISSUE TITLE
Reformat Silva fasta to refFasta for assignTaxonomy help

### ISSUE THREAD

**Issue by rachelwright8** [benjjneb/dada2#514]
Hi- I'm working on an 18S sequencing project in dada2 using a reference fasta file download from [Silva](https://www.arb-silva.de/browser/). I've copied an example of a read in the fasta file that Silva provides below. 

I've tried removing the line breaks in the sequence region, removing the accession number before the taxonomic string, adding a semicolon after the final taxonomic level... everything I try to do to match the file format to the format anticipated by the `assignTaxonomy` function fails with various errors (invalid map from reference to genus, invalid one-letter sequence codes, matrix length problems...).

Am I missing a built-in function in dada2 that reformats the Silva file format into what is expected by `assignTaxonomy` or do I need to keep manipulating the reference file myself? If I need to keep doing it myself, any hints on what other issues may be lingering after I make the changes described above?

Thanks!

>AF004127.1.302 Eukaryota;Amoebozoa;Archamoebae;Incertae Sedis;Rhizomastix;Caryedon pallidus
GCUAAAUGAUUAAUAGUUAUGUUCUUUAAAGUUAAAGAAUUUGGCGGUAUUUUAGUCUUUUCAGAGGAACCUGUUCUGUA
AUCGAUAGUCCACGAUAAAUAGAUACUUUAAUUUUUAACUUGCAUAUCGUUGUAGUUAGAAUAUUUUAUAAGAAAGAUAA
UGUUCAAGAUUUUAAAUUAAAAUUUAAAUCAAAUCAAGGUGUAGUCUAUAUUAAAGUAGAAAUGGGUUACAAUAAUAAUA
AAAUUAAGGAUUAUUUUUUUUAAAGGAAUUUGAAUAUGGAUUUGAAAGUAAUUUUAUUAAUU

**Comment by benjjneb** [comment]
Have you taken a look at our page on taxonomic reference data? https://benjjneb.github.io/dada2/training.html

See the section on formatting custom files at the bottom. Also note that `assignTaxonomy` assumes that the (e.g.) 3rd level is the same for everyone, which I'm not sure is always the case in the raw Silva files, as some taxonomies get extra level (e.g. superfamily). You'll also need to convert form ACGU to ACGT.

The R code used to format the officially supported Silva fasta file is also in the package: https://github.com/benjjneb/dada2/blob/master/R/taxonomy.R#L486

**Comment by rachelwright8** [comment]
Hi, we had seen the training page and tried using the code from the taxonomy.R script. Something still isn't being caught. I'll keep working on it. Thanks!

**Comment by derele** [comment]
Sorry for posting in a closed issue, but maybe have a look here: 
https://zenodo.org/record/1219106#.W1YowT2xVhE

I  uploaded this, as it could help others now (and to enhance reproducibility of a long published manuscript). Some ugly hacks were involved when I created this (over a year ago) to make eukaryotes work in Silva123 for dada2.
