### ISSUE TITLE
Discrepancy between ASVs and de-novo OTUs

### ISSUE THREAD

**Issue by Philippa36** [benjjneb/dada2#515]
We generated ASVs and OTUs (denovo in Qiime using default parameters) on the same data and found that the OTUs correlate much better with frailty than ASVs (which showed no correlation). On the other hand ASVs correlated better with BMI. 

Do you know why this may be?

Thanks!

**Comment by benjjneb** [comment]
I don't know.

**Comment by alexthibodeau** [comment]
If you look at the genus level? 

You may have multiple ASV in the same OTU so to me it appears to me that some correlations made between some OTU and ASV won't be the same. Apart from correlation, do you get the same results between OTU and SAV?
