### ISSUE TITLE
Problem with reads failed in merging step

### ISSUE THREAD

**Issue by balathl** [benjjneb/dada2#517]
Hi,

I am having a following issue with my dataset analyzed with dada2:
> mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE)
0 paired-reads (in 0 unique pairings) successfully merged out of 2923 (in 749 pairings) input.
0 paired-reads (in 0 unique pairings) successfully merged out of 8558 (in 2076 pairings) input.

I looked at the processed reads and the issue is due to the trimming of bad quality reads at the end of the reads which made the reads losing its overlap reads. Also, i noticed that it is mainly because of the dataset targeting different region of 16S than normal primers and having very less overlap of just 25 reads without preprocessing.340F-915R is the primer region targeted for this dataset.

One easy way is to just stick to R1 reads and proceed. But before i proceed, i like to check with dada2 team whether they have an option to align the processed reads(both R1 and R2 reads) extracted from "dadaFs, derepFs, dadaRs, derepRs objects" to the greengenes 16S full length template and fill the gap with "N" between the R1 and R2 reads and then proceed. With this approach, i get longer reads and better taxonomic classification. However, i dont know whether dada2 can support this. Let me know how to approach this!

Thanks in advance!

Bala

**Comment by benjjneb** [comment]
> because of the dataset targeting different region of 16S than normal primers and having very less overlap of just 25 reads without preprocessing

Yep that would be the issue. In order to merge these, you would have to keep the entire reads (i.e. no truncation at all).

> i like to check with dada2 team whether they have an option to align the processed reads(both R1 and R2 reads) extracted from "dadaFs, derepFs, dadaRs, derepRs objects" to the greengenes 16S full length template and fill the gap with "N" between the R1 and R2 reads and then proceed.

You can use `mergePairs(..., just Concatenate=TRUE)`. That will simply concatenate the F/R reads with 10Ns in between them. There is GG alignment involved, but that could done later presumably.

**Comment by balathl** [comment]
Thanks for your answer! Instead of no truncation, i choose c(270,270) and truncQ=0 as below:

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(270,270),maxN=0, truncQ=0, rm.phix=TRUE, compress=TRUE, multithread=TRUE)

It helped to merge approximately 30% of reads as below:
mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE)
12282 paired-reads (in 182 unique pairings) successfully merged out of 44602 (in 4660 pairings) input.
6466 paired-reads (in 145 unique pairings) successfully merged out of 19502 (in 2251 pairings) input.

However, I need to concatenate the rest of 70% using mergePairs(..., just Concatenate=TRUE) as you mentioned in the above post. How to identify and extract the 70% of reads failed in merging step? Is there any option to concatenate the reads failed to merge in the same function mergePairs and in the same run? If i need to run the failed reads seperately then how to combine the two objects say "mergers1" with default merging and "mergers2" obtained with mergePairs(..., just Concatenate=TRUE). Any insights will be very helpful! 

Thanks for your suggestions so far!

Best Regards,
Bala

**Comment by benjjneb** [comment]
> But it was a surprise as my target region length is 575bp (340F-915R) and with just 270F+270R=540bp, i am bit suspicious about this merging done by mergePairs function with dada2. Or i might be completely wrong too. Please clarify!

Are your primers included on the reads? If not, then the sequenced amplicon will be ~40nts shorter than you are expecting (the total length of the primers, which start at those positions). Plus, there is biological length variation in 16S regions. For example, the V3/V4 amplicon has two length modes about 20 nts different from each other.

> If the merging is fine then, I still need to concatenate the rest of 70% using mergePairs(..., just Concatenate=TRUE) as you mentioned in the above post. How to identify and extract the 70% of reads failed in merging step? Is there any option to concatenate the reads failed to merge in the same function mergePairs and in the same run? If i need to run the failed reads seperately then how to combine the two objects say "mergers1" with default merging and "mergers2" obtained with mergePairs(..., just Concatenate=TRUE). Any insights will be very helpful!

You'll want to look at the `returnRejects=TRUE` option. You can run `mergePairs` twice, once normally (`-> merger`) and once with `justConcatenate=TRUE` (`-> concat`). Then create a hybrid data.frame with the rows from normal merging if `merger$accept == TRUE`, and the rows from concatenation if `merger$accept == FALSE`.

**Comment by balathl** [comment]
Yeah! you are right about the primers. It was not included in the sequence and it makes sense now with the 30% merging. Thank you!


Regarding merging of failed reads, i am using the below code from your other post in the issue and it seems like the dataframe is missing and i wonder why. I get the below error:

> mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, returnRejects=TRUE,verbose=TRUE)
12282 paired-reads (in 182 unique pairings) successfully merged out of 44602 (in 4660 pairings) input.
Duplicate sequences in merged output.
6466 paired-reads (in 145 unique pairings) successfully merged out of 19502 (in 2251 pairings) input.
Duplicate sequences in merged output.
> concat <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, justConcatenate=TRUE,verbose=TRUE)
44602 paired-reads (in 4660 unique pairings) successfully merged out of 44602 (in 4660 pairings) input.
19502 paired-reads (in 2251 unique pairings) successfully merged out of 19502 (in 2251 pairings) input.
> mergers[!mergers$accept,] <- concat[!mergers$accept,]
**Error in !mergers$accept : invalid argument type**

**Comment by balathl** [comment]
It worked very well! Thanks a lot. 

Bala
