### ISSUE TITLE
collapsnomissmatch question

### ISSUE THREAD

**Issue by alexthibodeau** [benjjneb/dada2#518]
Hello again and thank you so much for this great tool.

I have a question concerning the collapseNoMismatch option minoverlap, set by default to 20.

My comprehension is that if you have a 250 pb ASV, if 2 ASV are 100% correctly aligned for at least 20 nucleotides, they will be merged together regardless of total length.

I probably do not understand this option, since to me it means that ASV that are 10% similar will be merge, which is probably not what's happening. 

Could someone please explain this option/command to me? What is the effect of increasing minoverlap value?

many thanks!

**Comment by benjjneb** [comment]
In order for sequences to be collapsed together, they have to have zero mismatches after performing an optimal alignment. `minOverlap=20` sets the minimum length of the aligned parts of the sequences, but doesn't effect the requirement that the optimal alignment have no gaps or mismatches (end gaps are allowed).

So `minOverlap=20` is a low default threshold that you may want to raise. But spurious collapses are very rare unless you are dealing with sequences with repetitive elements, as finding the exact same 20-mer at the start and end (e.g.) of two sequences is highly unlikely.

**Comment by alexthibodeau** [comment]
Thank you so much for the time you took to answer my question! It will be much easier to teach dada2 with all these supplemental explanations. Much appreciated.

Cheers!
