### ISSUE TITLE
Error: input/output no input files found

### ISSUE THREAD

**Issue by Mdrexel2018** [benjjneb/dada2#519]
Hello,

I am quite new to programming and I am using the DADA2 Pipeline Tutorial (1.8). So far it has worked great so thank you for that, but I have run into an issue. I found a few of your other threads with similar issues but none of those solutions worked for my situation. I am using a PC with windows 10 so maybe that's it? Side note: (I had gotten a previous error where it could not find the seqtab.nochim so I had to add the '_' around it and that solved the issue but then this new error was generated). Like I said I tried the other solutions like: adding a ~ inside the parentheses, adding a C:/, tried adding a /, adding a ~/, changing all of the / -> \ and then I got a different error so maybe it worked(edit: it didn’t). The error is included below:

taxa <- assignTaxonomy('seqtab.nochim', "Users/x x/Desktop/Drexel 2018/Step1_FASTQ/Reference_Databases/silva_nr_v123_train_set.fa.gz")
	Error: Input/Output
 	 no input files found
	 dirPath: Users/x x/Desktop/Drexel 2018/Step1_FASTQ/Reference_Databases/silva_nr_v123_train_set.fa.gz
	Pattern: character(0)

Thank you in advance!

**Comment by benjjneb** [comment]
That's probably a path issue, i.e. the path you have given is not being resolved to the file.

Try the following to check for exactly that issue:

```{r}
fn <- "Users/x x/Desktop/Drexel 2018/Step1_FASTQ/Reference_Databases/silva_nr_v123_train_set.fa.gz"
file.exists(fn)
```

Probably the problem is that your path is unrooted, i.e. it[ is a relative path rather than an absolute path](https://en.wikipedia.org/wiki/Path_(computing)). R will try to look from your path from its current working directory. Much more fool-proof are absolute paths, which on windows usually begin with e.g. "C:/".

*Actually, do they? I haven't use a windows machine in years now.*

**Comment by Mdrexel2018** [comment]
Thank you for getting back to me. When I input that command it gave back: [1] FALSE. Because of this I am assuming that you are correct and the file path is wrong. I did include the C:/ which also worked. 
 EDIT: ok so the reason that it was not working was because I had the '.gz' part at the end and the file that I was trying to open was not a zip file. Once I removed the '.gz' it worked. Then to see if it would work with the zip file I directed it to the zip file using the '.gz'. This worked!! Thank you for your help :)

**Comment by nafsa2021** [comment]
Hi, I have the same error as Mdrexel2018 had. I put the command taxa <- assignTaxonomy(seqtab.nochim, "I:/R/silva_nr_v132_train_set.fa/tax/silva_nr_v132_train_set.fa", multithread=FALSE) and I receive no inputs error. 

Thank you in advance
