### ISSUE TITLE
Errors when following DADA2 tutorial after sample inference

### ISSUE THREAD

**Issue by pck0** [benjjneb/dada2#52]
Hello!

When following the dada2 pipeline tutorial after sample inference when inspecting dadaFs and dadaRs, I do not get the expected info on inferred sample sequences etc. but rather a list of unique sequences and their respective number. When then trying to plot errors, I get the error message 
> Error in dq$trans : $ operator is invalid for atomic vectors

and no plots. When then trying to infer chimeras, I get a further error

> Identified 3 bimeras out of 130 input sequences.
> Identified 3 bimeras out of 130 input sequences.
> Error in getUniques(unqs) : 
> Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a  data.frame with $sequence and $abundance columns.

and bimFs and bimRs are not created. The only prior error I get is when creating the initial error plots
> Error: Input/Output
  no input files found
  dirPath: /users/Desktop/test/NA
  pattern: character(0) 

but this does not seem to hamper plot drawing or any other downstream operations up until the point mentioned above.
I'm using R 3.2.2., RStudio 0.99.473, dada2 0.10.1, ShortRead 1.26.0 and ggplot 2.0.0

Do you have any idea what might be going wrong?
Thanks
Paul

**Comment by benjjneb** [comment]
Hi Paul,

I'm not 100% sure, but you might have an extraneous name included in your list of files, which propagates along and causes problems later. Could you post the output of 'print(fnFs)' and 'print(fnRs)'? They should be lists of 20 filenames each, with names corresponding to those on the tutorial web page.

That you get an Input/Output error earlier on for accessing "/users/Desktop/test/NA" suggests an NA has snuck in there at some stage. All might then be solved by removing that NA and making sure the original list of files is correct.

Let me know if that doesn't work though.

**Comment by pck0** [comment]
It actually seems to be a problem with the list of files. I initially removed all but a single read pair to speed up computation for the tutorial, which apparently caused the errors. I do not get any errors when I have 2 or more read pairs. Not sure if this is intentional or a bug.

Thank you very much for your help and for developing this program!

**Comment by benjjneb** [comment]
Well, technically that is a bug, as the pipeline should fail with a better error message when being given files with a single read, but that's definitely a very unexpected edge case.

Glad its working now, and the full tutorial should run in a few minutes on reasonably modern computers without reducing any of the file sizes.
