### ISSUE TITLE
Error in assignTaxonomy

### ISSUE THREAD

**Issue by SantanuMBLab** [benjjneb/dada2#523]
Hello,
I am having the following problem in assigning taxonomy. 
> taxa <- assignTaxonomy(seqtab.nochim, "E:/R_workspace/MiSeq_sequences/filtered/tax/silva_nr_v128_train_set.fa.gz", multithread=TRUE)
Error: Input/Output
  no input files found
  dirPath: E:/R_workspace/MiSeq_sequences/filtered/tax/silva_nr_v128_train_set.fa.gz
  pattern: character(0)

**Comment by SantanuMBLab** [comment]
Thank you. I guess that is an issue with my machine.

**Comment by JohnsonEdwards** [comment]
Hello

I am actually having the same problem however it says true when I use file.exists. 

The error file reads as follows: 

Loading required package: Rcpp
Error: Input/Output
  no input files found
  dirPath: SRR11458561_R1_001.fastq.gz
  pattern: character(0)
Execution halted
srun: error: wcl001: task 0: Exited with exit code 1

I also have noticed that the "dirPath" aspect of the error only lists the first file in the path (SRR11458561_R1_001.fastq.gz) and not the actual path itself.

Any help would be appreciated :) .

**Comment by benjjneb** [comment]
> I also have noticed that the "dirPath" aspect of the error only lists the first file in the path (SRR11458561_R1_001.fastq.gz) and not the actual path itself.

You probably should give a full path to the file. Either that or set your working directory (`setwd`) to be the directory containing the fastq files.
