### ISSUE TITLE
creating and plotting graphs from Workflow for Microbiome data

### ISSUE THREAD

**Issue by Mdrexel2018** [benjjneb/dada2#525]
Hello!
I am new to coding and I am using the 'Bioconductor Workflow for Microbiome Data Analysis: from raw reads to community analyses'. I am trying to go through the section under creating and plotting graphs. In order to work it out on my computer (windows 10)before I use my own data just to make sure that I can do it correctly. I am using the sample data ps and running thorough the code. I am currently stuck on this part of it. I am able to successfully got through the first 5 lines but as soon as I get to the `V(net)`... portion I get an error message (seen below). I am not sure what it means and how to move forward. 

> library("phyloseqGraphTest")
>library("igraph")
>library("ggnetwork")
>net <- make_network(ps, max.dist=0.35)
sampledata <- data.frame(sample_data(ps))
V(net)$id <- sampledata[names(V(net)), "host_subject_id"]
V(net)$litter <- sampledata[names(V(net)), "family_relationship"]

> Error in `V<-`(`*tmp*`, value = 1:4) : invalid indexing

Thanks.

**Comment by benjjneb** [comment]
The F1000 Workflow has its own github page and issues Forum, can you repost this there? That's a better place, since it will ping all the authors of the paper rather than just me.

https://github.com/spholmes/F1000_workflow/issues
