### ISSUE TITLE
Using a large number of samples for error estimation

### ISSUE THREAD

**Issue by adityabandla** [benjjneb/dada2#527]
Hi Benjamin

In ultra small 16S datasets, say composed of 10-12 samples in a single MiSeq run, in case I choose nbases such that reads from 10 samples are used for error estimation, should I be concerned about overfitting the error model?

In a dataset I was handled recently, after maxEE filtering, the cumulative number of reads across 8 samples was about 1.3 M. Since I chose nbases to sample atleast 1 M reads, 7 out of 8 samples were chosen for error estimation, hence my concern

Regards,
Aditya

**Comment by benjjneb** [comment]
> should I be concerned about overfitting the error model?

No, overfitting is not a concern.

**Comment by adityabandla** [comment]
Thanks, Ben
