### ISSUE TITLE
Filtering paired-end sequences from Illumina

### ISSUE THREAD

**Issue by Vani-Maguire** [benjjneb/dada2#528]
Hello! I want to denoise and filter my paired-end 16S sequences from Illumina implementing the DADA2 workflow in R. I begin with almost 90000 sequences and after passing the script I get only 7! Almost all my sequences were eliminated. I relaxed the filtering parameters but I still get very few sequences. What do I have to do?

Thank you

**Comment by Vani-Maguire** [comment]
Yes, I have followed the tutorial. I am amplifying the primers 926F and 1392R. There are 6 soil samples. I used the Power Soil Isolation Kit.

First, I have 6 soil samples. I sequenced 16S for assessing bacterial community.
# Forward and reverse fastq filenames have format: SAMPLENAME_R1_001.fastq and
SAMPLENAME_R2_001.fastq
fnFs <- sort(list.files(path, pattern="_R1_001.fastq", full.names = TRUE))
fnRs <- sort(list.files(path, pattern="_R2_001.fastq", full.names = TRUE))
# Extract sample names, assuming filenames have format: SAMPLENAME_XXX.fastq
sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
# Plot Quality Profiles:
plotQualityProfile(fnFs[1:2])
QUALITY SCORES FORWARD (I decided to cut the forward sequences at 200 bp)
QUALITY SCORES REVERSE (I decided to cut the sequences at 140 bp)
# Filter and Trim: Place filtered files in filtered/ subdirectory
filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(200,140),maxN=0, maxEE=c(2,4), truncQ=2,
rm.phix=TRUE, compress=TRUE, multithread=FALSE) # On Windows set multithread=FALSE
> head(out)
reads.in reads.out
M1_S1_L001_R1_001.fastq 95936 85137
M2_S13_L001_R1_001.fastq 100048 88881
M3_S25_L001_R1_001.fastq 109868 97849
R1_S37_L001_R1_001.fastq 71477 63554
R2_S49_L001_R1_001.fastq 108257 97414
R3_S60_L001_R1_001.fastq 115617 103661
> errF <- learnErrors(filtFs, multithread=FALSE)
Initializing error rates to maximum possible estimate.
Sample 1 - 85137 reads in 42713 unique sequences.
Sample 2 - 88881 reads in 44215 unique sequences.
Sample 3 - 97849 reads in 48404 unique sequences.
Sample 4 - 63554 reads in 33315 unique sequences.
Sample 5 - 97414 reads in 47558 unique sequences.
Sample 6 - 103661 reads in 49723 unique sequences.
selfConsist step 2
selfConsist step 3
selfConsist step 4
selfConsist step 5
selfConsist step 6
selfConsist step 7
selfConsist step 8
selfConsist step 9
selfConsist step 10
Self-consistency loop terminated before convergence.
Total reads used: 536496
> errR <- learnErrors(filtRs, multithread=FALSE)
Initializing error rates to maximum possible estimate.
Sample 1 - 85137 reads in 33084 unique sequences.
Sample 2 - 88881 reads in 32775 unique sequences.
Sample 3 - 97849 reads in 35898 unique sequences.
FORWARD REVERSE
Sample 4 - 63554 reads in 26107 unique sequences.
Sample 5 - 97414 reads in 36214 unique sequences.
Sample 6 - 103661 reads in 37480 unique sequences.
selfConsist step 2
selfConsist step 3
selfConsist step 4
selfConsist step 5
selfConsist step 6
selfConsist step 7
selfConsist step 8
selfConsist step 9
Convergence after 9 rounds.
Total reads used: 536496
> dadaFs[[1]]
dada-class: object describing DADA2 denoising results
1272 sample sequences were inferred from 42713 input unique sequences.
Key parameters: OMEGA_A = 1e-40, BAND_SIZE = 16, USE_QUALS = TRUE
> dadaRs[[1]]
dada-class: object describing DADA2 denoising results
879 sample sequences were inferred from 33084 input unique sequences.
Key parameters: OMEGA_A = 1e-40, BAND_SIZE = 16, USE_QUALS = TRUE
$M1
sequence
4877
CCTACGGGTGGCTGCTCAAGTCAGGCGTGAAAGGCCTGGGCTCAACCCGGGAATTGCGCTTGAGACTGGGCT
GGCTTGAGTGCGGGAGAGGATGGTGGAATTCCCAGTGTAGAGGTGAAATTCGTAGATATTGGGAAGAACAC
CGGTGGCGAAGGCGGCCATCTGGACCGCAACTGACGCTGAGGCGCGAAAGCGTGGGGAGCAAACAGGATT
AGATACCCTTGTAGTC
6400
CCTACGGGTGGGGCAAGCGTTGTTCGGAATTACTGGGCGTAAAGGGTGCGTAGGCGGTGCTCTAAGTCGGA
TGTGAAAACTCTGGGCTCAACCCAGAGCCTGCATCCGAAACTGGAGTGCTAGAGTTCTGGAGGGGGTAGCGG
AATTCCTGGTGTAGCGGTGAAATGCGTAGATATCAGGAGGAACACCGGTGGCGAAGGCGGCTACCTGGACA
GAAACTGACGCTGAGGCACGAAAGCTAGGGGAGCAAACAGGATTAGATACCCTGGTAGTC
8753
CCTACGGGTGGCTGCTCAAGTCAGGCGTGAAAGGCCTGGGCTCAACCCGGGAATTGCGCTTGAGACTGGGCT
GGCTTGAGTGCGGGAGAGGATGGTGGAATTCCCAGTGTAGAGGTGAAATTCGTAGATATTGGGAAGAACAC
CGGTGGCGAAGGCGGCCATCTGGACCGCAACTGACGCTGAGGCGCGAAAGCGTGGGGAGCAAACAGGATT
AGATACCCCGGTAGTC
abundance forward reverse nmatch nmismatch nindel prefer accept
4877 4 401 71 111 0 0 2 TRUE
6400 2 494 91 66 0 0 2 TRUE
8753 1 401 781 111 0 0 2 TRUE
$M2
sequence
6304
CCTACGGGGGGAGCAAGCGTTGTTCGGATTTACTGGGCGTAAAGGGCGCGTAGGCGGCCAGCGCAAGTCAG
TTGTGAAATCTCCGGGCTTAACTCGGAAAGGTCAACTGATACTGCGCGGCTAGAGTGCGGAAGGGGCAACTG
GAATTCTCGGTGTAGCGGTGAAATGCGTAGATATCGAGAGGAACACCTGCGGCGAAGGCGGGTTGCTGGGC
CGACACTGACGCTGATGTGCGAAAGCCAGGGGAGCGAACGGGATTAGATACCCTTGTAGTC
7730
CCTACGGGGGGTGCGAGCGTTGTCCGGAATCACTGGGCGTAAAGGGCGCGTAGGTGGTTTGATAAGGGTGT
GGTGAAAGCCCGGGGCTCAACCCCGGGTCTGCCGTGCCGACTGTCAAACTCGAGGGCTGTAGAGGCAGACG
GAATTCCGGGTGTAGCGGTGGAATGCGTAGAGATCCGGAGGAAGACCGGTGGCGAAGGCGGTCTGCTGGG
CAGTTTCTGACACTGATGCGCGACAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTC
8204
CCTACGGGGGGAGCAAGCGTTGTTCGGATTTACTGGGCGTAAAGGGCGCGTAGGCGGCCAGCGCAAGTCAG
TTGTGAAATCTCCGGGCTTAACTCGGAAAGGTCAACTGATACTGCGCGGCTAGAGTGCGGAAGGGGCAACTG
GAATTCTCGGTGTAGCGGTGAAATGCGTAGATATCGAGAGGAACACCTGCGGCGAAGGCGGGTTGCTGGGC
CGACACTGACGCTGATGCGCGAAAGCCAGGGGAGCGAACGGGATTAGATACCCGTGTAGTC
9038
CCTACGGGGGGAGCAAGCGTTGTTCGGATTTACTGGGCGTAAAGGGCGCGTAGGCGGCCAGCGCAAGTCAG
TTGTGAAATCTCCGGGCTTAACTCGGAAAGGTCAACTGATACTGCGCGGCTAGAGTGCGGAAGGGGCAACTG
GAATTCTCGGTGTAGCGGTGAAATGCGTAGATATCGAGAGGAACACCTGCGGCGAAGGCGGGTTGCTGGGC
TGACACTGACGCTGATGCGCGAAAGCCAGGGGAGCGAACGGGATTAGATACCCGTGTAGTC
10137
CCTACGGGGGGTGCGAGCGTTGTCCGGAATCACTGGGCGTAAAGGGCGCGTAGGTGGTTTGATAAGGGTGT
GGTGAAAGCCCGGGGCTCAACCCCGGGTCTGCCGTGCCGACTGTCAAACTCGAGGGCTGTAGAGGCAGGCG
GAATTCCGGGTGTAGCGGTGGAATGCGTAGAGATCCGGAGGAAGACCGGTGGCGAAGGCGGCCTGCTGGG
CAGTTACTGACACTGATGCGCGACAGCGTGGGGAGCAAACAGGATTAGATACCCTTGTAGTC
10877
CCTACGGGGGGAGCAAGCGTTGTTCGGATTTACTGGGCGTAAAGGGCGCGTAGGCGGCCAGCGCAAGTCAG
TTGTGAAATCTCCGGGCTTAACTCGGAAAGGTCAACTGATACTGCGCGGCTAGAGTGCGGAAGGGGCAACTG
GAATTCTCGGTGTAGCGGTGAAATGCGTAGATATCGAGAGGAACACCTGCGGCGAAGGCGGGTTGCTGGGC
TGACACTGACGCTGATGCGCGAAAGCCAGGGGAGCGAACGGGATTAGATACCCTTGTAGTC
abundance forward reverse nmatch nmismatch nindel prefer accept
6304 3 412 424 65 0 0 2 TRUE
7730 2 414 609 66 0 0 2 TRUE
8204 1 412 711 65 0 0 2 TRUE
9038 1 412 221 65 0 0 2 TRUE
10137 1 414 76 65 1 0 2 TRUE
10877 1 412 483 65 0 0 2 TRUE
$M3
sequence
6415
CCTACGGGTGGCTGATCCGTCAGTTCCTCCTGAGAAAGTGTGCAGCAGCAGGTAATCACCCGAACTTTCAACC
TGGTACACCACGCCGCAGCCCAGGCTGCAAGCGGCGTTTACCTTTCCTCCGAAGTACGTTGTACCAACCATGTT
TCCGGCGAAATTTAATAGTGCGCCTGAGGGCTGCTGCCCGTCGCCCGCCTGGATGGCAAATCTATGGAGCAC
AGTTTCGATACCCCAGTAGTC
abundance forward reverse nmatch nmismatch nindel prefer accept
6415 3 467 486 100 0 0 1 TRUE
$R1
sequence
4356
CCTACGGGTGGCTGCTCAAGTCAGGCGTGAAAGGCCTGGGCTCAACCCGGGAATTGCGCTTGAGACTGGGCT
GGCTTGAGTGCGGGAGAGGATGGTGGAATTCCCAGTGTAGAGGTGAAATTCGTAGATATTGGGAAGAACAC
CGGTGGCGAAGGCGGCCATCTGGACCGCAACTGACGCTGAGGCGCGAAAGCGTGGGGAGCAAACAGGATT
AGATACCCTTGTAGTC
6463
CCTACGGGTGGCTGCTCAAGTCAGGCGTGAAAGGCCTGGGCTCAACCCGGGAATTGCGCTTGAGACTGGGCT
GGCTTGAGTGCGGGAGAGGATGGTGGAATTCCCAGTGTAGAGGTGAAATTCGTAGATATTGGGAAGAACAC
CGGTGGCGAAGGCGGCCATCTGGACCGCAACTGACGCTGAGGCGCGAAAGCGTGGGGAGCAAACAGGATT
AGATACCCTGGTAGTC
abundance forward reverse nmatch nmismatch nindel prefer accept
4356 2 281 134 111 0 0 2 TRUE
6463 1 281 421 111 0 0 2 TRUE
$R2
sequence
7676
CCTACGGGGGGCGAGTGCAACAGCGCGGCTGCTTTCCCGGTGATGCAGAGCCTGGCAGTCACCCTCAGCCCT
ACAACCGGTGGCGGGCGCTGGCTGCACCGGTAAGGGCAAAGCGACAGTTATTTGAAGTGCGGGATAACCTG
CTCCGCGAGCAAGCGGATAGAATGCACCACCCGATCATAGGGAAGCTGTCCACCGGGATTCATGTCCAGCGA
TACCCGTGTAGTC
abundance forward reverse nmatch nmismatch nindel prefer accept
7676 2 463 371 112 0 0 1 TRUE
$R3
sequence
5528
CCTACGGGTGGCTGCTCAAGTCAGGCGTGAAAGGCCTGGGCTCAACCCGGGAATTGCGCTTGAGACTGGGCT
GGCTTGAGTGCGGGAGAGGATGGTGGAATTCCCAGTGTAGAGGTGAAATTCGTAGATATTGGGAAGAACAC
CGGTGGCGAAGGCGGCCATCTGGACCGCAACTGACGCTGAGGCGCGAAAGCGTGGGGAGCAAACAGGATT
AGATACCCTGGTAGTC
6817
CCTACGGGGGGAGCAAGCGTTGTTCGGATTTACTGGGCGTAAAGGGCGCGTAGGCGGCCAGCGCAAGTCAG
TTGTGAAATCTCCGGGCTTAACTCGGAAAGGTCAACTGATACTGCGCGGCTAGAGTGCAGAAGGGGCAACTG
GAATTCTCGGTGTAGCGGTGAAATGCGTAGATATCGAGAGGAACACCTGCGGCGAAGGCGGGTTGCTGGGC
TGACACTGACGCTGATGCGCGAAAGCTAGGGGAGCGAACGGGATTAGATACCCTTGTAGTC
7550
CCTACGGGGGGAGCAAGCGTTGTTCGGATTTACTGGGCGTAAAGGGCGCGTAGGCGGCCAGCGCAAGTCAG
TTGTGAAATCTCCGGGCTTAACTCGGAAAGGTCAACTGATACTGCGCGGCTAGAGTGCAGAAGGGGCAACTG
GAATTCTCGGTGTAGCGGTGAAATGCGTAGATATCGAGAGGAACACCTGCGGCGAAGGCGGGTTGCTGGGC
TGACACTGACGCTGATGCGCGAAAGCCAGGGGAGCGAACGGGATTAGATACCCTTGTAGTC
8132
CCTACGGGGGGAGCAAGCGTTGTTCGGATTTACTGGGCGTAAAGGGCGCGTAGGCGGCCAGCGCAAGTCAG
TTGTGAAATCTCCGGGCTTAACTCGGAAAGGTCAACTGATACTGCGCGGCTAGAGTGCAGAAGGGGCAACTG
GAATTCTCGGTGTAGCGGTGAAATGCGTAGATATCGAGAGGAACACCTGCGGCGAAGGCGGGTTGCTGGGC
CGACACTGACGCTGATGCGCGAAAGCCAGGGGAGCGAACGGGATTAGATACCCCTGTAGTC
8958
CCTACGGGGGGAGCAAGCGTTGTTCGGATTTACTGGGCGTAAAGGGCGCGTAGGCGGCCAGCGCAAGTCAG
TTGTGAAATCTCCGGGCTTAACTCGGAAAGGTCAACTGATACTGCGCGGCTAGAGTGCAGAAGGGGCAACTG
GAATTCTCGGTGTAGCGGTGAAATGCGTAGATATCGAGAGGAACACCTGCGGCGAAGGCGGGTTGCTGGGC
TGACACTGACGCTGATGCGCGAAAGCTAGGGGAGCGAACGGGATTAGATACCCGAGTAGTC
10058
CCTACGGGGGGAGCAAGCGTTGTTCGGATTTACTGGGCGTAAAGGGCGCGTAGGCGGCCAGCGCAAGTCAG
TTGTGAAATCTCCGGGCTTAACTCGGAAAGGTCAACTGATACTGCGCGGCTAGAGTGCAGAAGGGGCAACTG
GAATTCTCGGTGTAGCGGTGAAATGCGTAGATATCGAGAGGAACACCTGCGGCGAAGGCGGGTTGCTGGGC
TGACACTGACGCTGATGCGCGAAAGCCAGGGGAGCGAACGGGATTAGATACCCTGGTAGTC
10156
CCTACGGGGGGAGCAAGCGTTGTTCGGATTTACTGGGCGTAAAGGGCGCGTAGGCGGCCAGCGCAAGTCAG
TTGTGAAATCTCCGGGCTTAACTCGGAAAGGTCAACTGATACTGCGCGGCTAGAGTGCAGAAGGGGCAACTG
GAATTCTCGGTGTAGCGGTGAAATGCGTAGATATCGAGAGGAACACCTGCGGCGAAGGCGGGTTGCTGGGC
CGACACTGACGCTGATGTGCGAAAGCTAGGGGAGCGAACGGGATTAGATACCCGGGTAGTC
10514
CCTACGGGGGGAGCAAGCGTTGTTCGGATTTACTGGGCGTAAAGGGCGCGTAGGCGGCCAGCGCAAGTCAG
TTGTGAAATCTCCGGGCTTAACTCGGAAAGGTCAACTGATACTGCGCGGCTAGAGTGCAGAAGGGGCAACTG
GAATTCTCGGTGTAGCGGTGAAATGCGTAGATATCGAGAGGAACACCTGCGGCGAAGGCGGGTTGCTGGGC
TGACACTGACGCTGAAGCGCGAAAGCTAGGGGAGCGAACGGGATTAGATACCCTGGTAGTC
10960
CCTACGGGTGGCTGCTCAAGTCAGGCGTGAAAGGCCTGGGCTCAACCCGGGAATTGCGCTTGAGACTGGGCT
GGCTTGAGTGCGGGAGAGGATGGTGGAATTCCCAGTGTAGAGGTGAAATTCGTAGATATTGGGAAGAACAC
CGGTGGCGAAGGCGGCCATCTGGACCGCAACTGACGCTGAGGCGCGAAAGCGTGGGGAGCAAACAGGATT
AGATACCCGAGTAGTC
11642
CCTACGGGGGGAGCAAGCGTTGTTCGGATTTACTGGGCGTAAAGGGCGCGTAGGCGGCCAGCGCAAGTCAG
TTGTGAAATCTCCGGGCTTAACTCGGAAAGGTCAACTGATACTGCGCGGCTAGAGTGCAGAAGGGGCAACTG
GAATTCTCGGTGTAGCGGTGAAATGCGTAGATATCGAGAGGAACACCTGCGGCGAAGGCGGGTTGCTGGGC
TGACACTGACGCTGATGCGCGAAAGCTAGGGGAGCGAACGGGATTAGATACCCTAGTAGTC
abundance forward reverse nmatch nmismatch nindel prefer accept
5528 4 475 48 111 0 0 2 TRUE
6817 3 481 268 65 0 0 2 TRUE
7550 2 481 28 65 0 0 2 TRUE
8132 2 481 404 65 0 0 2 TRUE
8958 1 481 945 65 0 0 2 TRUE
10058 1 481 305 65 0 0 2 TRUE
10156 1 481 466 65 0 0 2 TRUE
10514 1 481 283 65 0 0 2 TRUE
10960 1 475 830 111 0 0 2 TRUE
11642 1 481 940 65 0 0 2 TRUE
> seqtab <- makeSequenceTable(mergers)
The sequences being tabled vary in length.
> dim(seqtab)
[1] 6 21
> table(nchar(getSequences(seqtab)))
228 229 240 274 275
1 4 1 3 12
> seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE,
verbose=TRUE)
Identified 1 bimeras out of 21 input sequences.
> dim(seqtab.nochim)
[1] 6 20
> sum(seqtab.nochim)/sum(seqtab)
[1] 0.9756098
> seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=FALSE,
verbose=TRUE)
Identified 1 bimeras out of 21 input sequences.
> dim(seqtab.nochim)
[1] 6 20
> sum(seqtab.nochim)/sum(seqtab)
[1] 0.9756098
> getN <- function(x) sum(getUniques(x))
> track <- cbind(out, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers, getN),
rowSums(seqtab.nochim))
> colnames(track) <- c("input", "filtered", "denoisedF", "denoisedR", "merged", "nonchim")
> rownames(track) <- sample.names
> head(track)
input filtered denoisedF denoisedR merged nonchim
M1 95936 85137 85137 85137 7 7
M2 100048 88881 88881 88881 9 9
M3 109868 97849 97849 97849 3 3
R1 71477 63554 63554 63554 3 3
R2 108257 97414 97414 97414 2 2
R3 115617 103661 103661 103661 17 16

FORWARD:
![image](https://user-images.githubusercontent.com/41649467/43291681-b76c1426-9108-11e8-902d-20eaa2f4b92a.png)
REVERSE:
![image](https://user-images.githubusercontent.com/41649467/43291794-2e6727e6-9109-11e8-937f-6a8fb85fa0dd.png)


FORWARD:
![image](https://user-images.githubusercontent.com/41649467/43291703-cf29c7c0-9108-11e8-95e4-86cf58113e4f.png)

REVERSE:
![image](https://user-images.githubusercontent.com/41649467/43291716-df386554-9108-11e8-911f-911a68edef7f.png)

**Comment by benjjneb** [comment]
>  926F and 1392R

Your sequence amplicon is ~ 1392-926 = 470 nts if primers are included, and ~440 if not. (rough values, I don't know the real length distro of this amplicon)

> out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(200,140),maxN=0, maxEE=c(2,4), truncQ=2,
rm.phix=TRUE, compress=TRUE, multithread=FALSE) # On Windows set multithread=FALSE

After truncation you only have 340 nts of sequence left. There's no overlap, and you lose everything during merging.

Your forward and reverse truncation lengths need to be long enough to overlap with each other. The basic formula is truncLen-F + truncLen-R >= AMPLICON_LENGTH + 20 + BIO.LENGTH.VARIATION.
