### ISSUE TITLE
Add Species with Stitched Reads

### ISSUE THREAD

**Issue by adityabandla** [benjjneb/dada2#529]
Hi Ben

I was wondering if the add species function can be modified to support stitched reads? Would it be possible to autodetect the longer read (forward or reverse) and use that for exact matching?

Regards,
Aditya

**Comment by benjjneb** [comment]
You mean reads that were merged with `justConcatenate=TRUE`?

It's possible but not a high priority. Pretty easy to workaround though. You can just run `assignSpecies` on the first reads:

```
sq.R1 <- substr(getSequences(seqtab), 1, R1_READ_LEN)
gen.spc <- assignSpecies(sq.R1, "path/to/species_assignment.fa")
## To duplicate addSpecies functionality
same.genus <- gen.spc[,"Genus"] == tax[,"Genus"]
same.genus[is.na(same.genus)] <- FALSE
tax <- cbind(tax, Species = rep(NA, nrow(tax))
tax[same.genus, "Species"] <- gen.spc[same.genus, "Species"]
```

Most of that should work I think! Might need a line or two fiddled with though.

**Comment by adityabandla** [comment]
Thanks Ben! I will give this a try as modify as required

Are there downsides to stitching reads and using such stitched reads for taxonomic assignment? I would assume given the increase in sequence information, there should be an improvement in taxonomic assignment

Further, I gather that 10N's are used as spacers as default. In cases where the gap between the forward and reverse are more than 10bp, is it advisable to increase the spacers to get a realistic stitched sequence?

**Comment by benjjneb** [comment]
> Are there downsides to stitching reads and using such stitched reads for taxonomic assignment?

For `assignTaxonomy` not really, as that method is based on shredding the reads into kmers anyway. Unless they overlap though, then its better to merge them properly to not double up.

> In cases where the gap between the forward and reverse are more than 10bp, is it advisable to increase the spacers to get a realistic stitched sequences?

That won't have an impact on dada2 package functions. Maybe its useful for outside software? I don't know.
