### ISSUE TITLE
Taxonomy assignment

### ISSUE THREAD

**Issue by benjjneb** [benjjneb/dada2#53]
Would be nice for people to be able to do their taxonomy assignment within R, and since its not available perhaps it should be added to the dada2 package.

**Comment by benjjneb** [comment]
The dada2 package now includes the assignTaxonomy(...) function, which implements the RDP classifier's taxonomic assignment method (Wang 2007): a3992a47443e4c118db34000d190ae3d3abee392

Still need to clean some things up and make a couple basic reference files available before closing this issue, but the functionality is there now.

**Comment by mfrisch** [comment]
I threw together a modified version of Schoss' SILVA reference file, but get an error: "could not find function "C_assign_taxonomy"". I'm guessing this is occurring at line 47 of R/taxonomy.R

**Comment by benjjneb** [comment]
Hi Michael,
The function is working right now for me, are you using the most recent package version? A couple bug fixes went in after the commit a3992a47443e4c118db34000d190ae3d3abee392 that originally introduced the function. Right now the assignment <- C_assign_taxonomy(seqs, refs, ref.to.genus, tax.mat.int) call is on line 49 of taxonomy.R (not 47) so there might be a difference.

This function needs a little bit more polish as well, and is doing very little checking of the input format. Here is the reference file I'm using at the moment (also a modified version of Schloss''s SILVA reference file - bacteria only): https://www.dropbox.com/s/xippijyryaasi2y/silva.bac.train.fa?dl=0

Not sure why that would make C_assign_taxonomy visible, but one less variable to troubleshoot on anyway

-Ben

**Comment by mfrisch** [comment]
Thanks Ben. I think I had something interfering from GlobalEnv - a fresh R session solved the issue.
