### ISSUE TITLE
Multithreading Options

### ISSUE THREAD

**Issue by anamailyan** [benjjneb/dada2#530]
Hi Ben,
Is it possible for users to specify  number of threads and number of cores used with multithread option? If not, can this be added?
Thank you.

**Comment by benjjneb** [comment]
Yes. For example, `multithread=3` will use 3.

**Comment by anamailyan** [comment]
Thank you. Is it 3 threads or 3 cores?

**Comment by benjjneb** [comment]
threads. If you look at the help function for `?dada`, it has a section on the `multithread` parameter that describes usage and options. From the help:

>If an integer is provided, the number of threads to use is set by passing the argument on to setThreadOptions.

**Comment by anamailyan** [comment]
Great! Thank you. I should have looked at help. Is there a way to limit number of cores or not?

**Comment by benjjneb** [comment]
ncores will always be less than nthreads, so indirectly by limiting the number of threads.

**Comment by anamailyan** [comment]
Thank you very much!
