### ISSUE TITLE
Trouble using rpy

### ISSUE THREAD

**Issue by anamailyan** [benjjneb/dada2#531]
I am having trouble when using rpy2 to call dada2::learnErrors function. Do rpy2 and python 2.7 work well with dada2 functions? Would you recommend to use rpy2?

Error I am getting is
File "/usr/local/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in open.connection(con, "rb") : cannot open the connection

Thank you for any advise.

**Comment by benjjneb** [comment]
No idea about potential interactions with rpy2. But that error message suggests a failure to open a file ("connection"), i.e. one of the file-paths you are giving `learnErrors` doesn't exist.

**Comment by anamailyan** [comment]
Thank you, Ben.
