### ISSUE TITLE
filterAndTrim differences between versions

### ISSUE THREAD

**Issue by jarrodscott** [benjjneb/dada2#533]
Hi. 

It's me again, old v1.4 guy. 

Mac osx 10.13.5
R: 3.5.0
DADA2 v1.4, 1.8

Maybe I should have posted this to issue [#532](https://github.com/benjjneb/dada2/issues/532)

I had a question about the behavior of `filterAndTrim` across v1.4 and v1.8 and wondering which one is "correct". 

I am running this command in both cases:
`out_Y2 <- filterAndTrim(fnFs_Y2, filtFs_Y2, fnRs_Y2, filtRs_Y2, truncLen=c(270,200), maxN=0, maxEE=c(2,5), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE)`

In `v.1.4` `filterAndTrim` trims off the first 10 bps from both reads. In the NEWS file included in the DADA2 v.1.8 package there is this statement under "CHANGES IN VERSION 1.3.1"...BUG FIXES"

    "trimLeft is now enforced before any filtering is performed"

But it looks like in `v.1.8` this is no longer the case? Is this correct? I couldn't find any other documentation 

I added the `trimLeft = 10` flag to the above command in v.1.8 and was able to get the same trimmed reads as before, although the total number per sample in v.1.8 left after filtering in lower. 

I attached an example fasta file comparing a single paired end read including the original sequence and the two trimmed versions for F and R.
[filterAndTrim.txt](https://github.com/benjjneb/dada2/files/2251443/filterAndTrim.txt)

**Comment by benjjneb** [comment]
I'm not sure I follow one point, it was never the case that the first 10 bases were automatically removed, that always required `trimLeft=10` to cause to happen.

On the change
> "trimLeft is now enforced before any filtering is performed"

This just changed the order in which different filteringAndTrim parameters were enforced. Now, the trimming/truncation is performed before anything else (like checking for Ns or enforcing `maxEE`) whereas before some of the filtering steps (checking for Ns for sure) happened before trimming, which isn't ideal, sequences with all the Ns removed by trimming ought to pass the filter.
