### ISSUE TITLE
Track reads through the pipeline "DADA2 workflow for Big Data: Paired-end"

### ISSUE THREAD

**Issue by AgustinPardo** [benjjneb/dada2#534]
I am using the pipeline "A DADA2 workflow for Big Data: Paired-end", and I can not find the way to carry out the "Track reads through the pipeline" at the end of using it. Is there any way to implement it?

**Comment by benjjneb** [comment]
If you look at the tutorial workflow (https://benjjneb.github.io/dada2/tutorial.html) you can see how read tracking is peformed. Right now, we don't integrate read tracking into the Big Data workflow, so you'll have to add some parts, especially saving the output of `filterAndTrim`, and counting total reads after denoising, merging and chimera removal.

**Comment by cjfields** [comment]
@AgustinPardo it's a little tricky but possible, you just need to persist the data and join when needed.  See [this link](https://github.com/uct-cbio/16S-rDNA-dada2-pipeline) for a Nextflow-based pipeline using dada2, based off the Big Data strategy

**Comment by AgustinPardo** [comment]
# Thanks. Just a little change in the original script and I solve it. Here is the example:
Also, I add remove chimera. In the pipeline It is the comment "# Construct sequence table and remove chimeras", but it doesn't take away the chimeras really. I think this is confusing because the chimeras are removed in the next step, when the runs are merged, but I decided to remove chimeras to each run.
```
  temporada="Spring2014"
  pathF=paste("/16S-CuartelV/FullDemux_",temporada,"/FWD/",sep = "")
  print(pathF)
  pathR=paste("/16S-CuartelV/FullDemux_",temporada,"/REV/",sep = "")
  # File parsing
  # pathF <- "/16S-CuartelV/FullDemux_Otoño2016/FWD/" # CHANGE ME to the directory containing your demultiplexed forward-read fastqs
  # pathR <- "/16S-CuartelV/FullDemux_Otoño2016/REV/" # CHANGE ME ...
  filtpathF <- file.path(pathF, "filtered") # Filtered forward files go into the pathF/filtered/ subdirectory
  filtpathR <- file.path(pathR, "filtered") # ...

  fastqFs <- sort(list.files(pathF, pattern="fastq"))
  fastqRs <- sort(list.files(pathR, pattern="fastq"))
  
  # path <- "/16S-CuartelV/FullDemux_Primavera2017/REV/"
  # fnFs <- sort(list.files(path, pattern="_R1.fastq", full.names = TRUE))
  # fnRs <- sort(list.files(path, pattern="_R2.fastq", full.names = TRUE))
  # plotQualityProfile(fnFs[1:10])
  # plotQualityProfile(fnRs[1:10])
  
  # Filtro calidad
  if(length(fastqFs) != length(fastqRs)) stop("Forward and reverse files do not match.")
  # Filtering: THESE PARAMETERS ARENT OPTIMAL FOR ALL DATASETS
  out = filterAndTrim(fwd=file.path(pathF, fastqFs), filt=file.path(filtpathF, fastqFs),
                      rev=file.path(pathR, fastqRs), filt.rev=file.path(filtpathR, fastqRs),
                      truncLen=c(270,240),maxN=0, maxEE=c(6,6),rm.phix=TRUE,
                      compress=TRUE, verbose=TRUE, multithread=TRUE,matchIDs=TRUE)
  head(out)
  
  #Infer Sequence Variants
  # File parsing
  filtpathF=paste("/16S-CuartelV/FullDemux_",temporada,"/FWD/filtered/",sep = "")
  filtpathR=paste("/16S-CuartelV/FullDemux_",temporada,"/REV/filtered/",sep = "")
  # filtpathF <- "/16S-CuartelV/FullDemux_Otoño2016/FWD/filtered/" # CHANGE ME to the directory containing your filtered forward fastqs
  # filtpathR <- "/16S-CuartelV/FullDemux_Otoño2016/REV/filtered/" # CHANGE ME ...
  filtFs <- list.files(filtpathF, pattern="fastq", full.names = TRUE)
  filtRs <- list.files(filtpathR, pattern="fastq", full.names = TRUE)
  sample.names <- sapply(strsplit(basename(filtFs), "\\."), `[`, 1) # Assumes filename = samplename_XXX.fastq.gz
  sample.names <- (gsub('.{3}$', '', sample.names))
  sample.namesR <- sapply(strsplit(basename(filtRs), "\\."), `[`, 1) # Assumes filename = samplename_XXX.fastq.gz
  sample.namesR <- (gsub('.{3}$', '', sample.namesR))
  if(!identical(sample.names, sample.namesR)) stop("Forward and reverse files do not match.")
  names(filtFs) <- sample.names
  names(filtRs) <- sample.names
  set.seed(100)
  
  # Learn forward error rates
  errF <- learnErrors(filtFs, nbases=1e8, multithread=TRUE)
  # Learn reverse error rates
  errR <- learnErrors(filtRs, nbases=1e8, multithread=TRUE)
  plotErrors(errF, nominalQ=TRUE)
  plotErrors(errR, nominalQ=TRUE)
  
  # Sample inference and merger of paired-end reads
  mergers <- vector("list", length(sample.names))
  names(mergers) <- sample.names
  for(sam in sample.names) {
    cat("Processing:", sam, "\n")
    derepF <- derepFastq(filtFs[[sam]])
    ddF <- dada(derepF, err=errF, multithread=TRUE)
    derepR <- derepFastq(filtRs[[sam]])
    ddR <- dada(derepR, err=errR, multithread=TRUE)
    merger <- mergePairs(ddF, derepF, ddR, derepR, maxMismatch = 8)
    mergers[[sam]] <- merger
  }
  rm(derepF); rm(derepR)
  
  # Construct sequence table and remove chimeras
  seqtab <- makeSequenceTable(mergers)
  
  # Remove chimeras
  seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
  dim(seqtab.nochim)
  sum(seqtab.nochim)/sum(seqtab)
  
  # Track
  getN <- function(x) sum(getUniques(x))
  track <- cbind(out,sapply(mergers, getN), rowSums(seqtab.nochim))
  # If processing a single sample, remove the sapply calls: e.g. replace sapply(dadaFs, getN) with getN(dadaFs)
  colnames(track) <- c("input", "filtered", "mergers", "nonchim")
  rownames(track) <- sample.names
  head(track)
  
  out_path=paste("/16S-CuartelV/out_DADA2_BigData/seqtab_",temporada,".rds",sep = "")
  saveRDS(seqtab.nochim, out_path) # CHANGE ME to where you want sequence table saved
  out_track=paste("/16S-CuartelV/out_DADA2_BigData/track_",temporada,".txt",sep = "")
  write.table(track, out_track, sep="\t")
```

**Comment by girouxem** [comment]
I was able to get all the tracking of the reads for big data by capturing the dadaForward and dadaReverse outputs the same way the mergers were captured:
`
mergers <- vector("list", length(sampleNames))
names(mergers) <- sampleNames

# Do the same to capture all the ddF and ddR outputs
ddFs <- vector("list", length(sampleNames))
names(ddFs) <- sampleNames
ddRs <- vector("list", length(sampleNames))
names(ddRs) <- sampleNames
`
Then I run the derep, dada, and mergePairs, as in the Big Data example, but add the lines to collect the ddFs and ddRs as well:
`for(sam in sampleNames) {
  cat("Processing:", sam, "\n")
    derepF <- derepFastq(filtFs[[sam]])
    ddF    <- dada(derepF, err = errF, multithread = TRUE, verbose = TRUE)
    ddFs[[sam]] <- ddF # Added this for all ddFs
    derepR <- derepFastq(filtRs[[sam]])
    ddR    <- dada(derepR, err = errR, multithread = TRUE, verbose = TRUE)
    ddRs[[sam]] <- ddR # Added this for all ddRs
    merger <- mergePairs(ddF, derepF, ddR, derepR, 
                         maxMismatch = 1, verbose = TRUE)
    mergers[[sam]] <- merger
}
rm(derepF); rm(derepR)
`
Then when tracking the reads throughout the process, I can get all the columns:
`
# Set a simple function:
GetN <- function(x) sum(getUniques(x))

# Generate a simple table for tracking:
summaryTbl <- data.frame(row.names = sampleNames, # Okay
                         input = trimOut[,1], # Okay
                         filtered = trimOut[,2], # Okay
                         dadaF = sapply(ddFs, GetN),  # Now this works
                         dadaR = sapply(ddRs, GetN),  # Now this works
                         merged = sapply(mergers, GetN), 
                         nonchim = rowSums(seqTab), 
                         finalPercReadsKept = round(rowSums(seqTab)/trimOut[,1]*100, 1))

rownames(summaryTbl) <- sampleNames
head(summaryTbl)
`

**Comment by sfeds** [comment]
Hi, 
trying to get this also to work...
@girouxem , in your summaryTbl, where do you get trimOut from?
thanks!
