### ISSUE TITLE
Error model: convergence issue

### ISSUE THREAD

**Issue by shreyaskumbhare** [benjjneb/dada2#535]
Hi Ben,
I am currently working on the HiSeq 2x250 V4 region amplicon data. I trimmed the forward reads using the following (based on the quality profile):

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
compress=TRUE, multithread=TRUE)

[batch1_quality_plot_F.pdf](https://github.com/benjjneb/dada2/files/2257857/batch1_quality_plot_F.pdf)

And have generated the error model, which self-terminated after the default 10th self-consist step. The error model plot for the same is as follows:
[batch1_errF_plot.pdf](https://github.com/benjjneb/dada2/files/2257898/batch1_errF_plot.pdf)

The convergence for the same is as follows:
dada2:::checkConvergence(errF)
 [1] 52.320006739  1.527508267  0.037511536  0.007328744  0.004234083
 [6]  0.002049031  0.004547451  0.003684809  0.005130620  0.005210326

I am unable to understand that from the quality plots the data looks completely fine, however the error model generated has not able to capture the best fit. Can you please comment on this? Thanks!

**Comment by benjjneb** [comment]
@shreyaskumbhare Is this miniSeq data? Or some other platform that uses coarse-grained quality scores (i.e. just 8 quality scores are used instead of 0-40)?

**Comment by shreyaskumbhare** [comment]
@benjjneb I am not sure though but from the quality profile even with other tools like Fastqc I am getting an impression that the quality score binning has been used. I wish to know how exactly this binning factor affects the error modelling? And of course I seek a solution/suggestion :)

**Comment by benjjneb** [comment]
GIven that those are binned quality scores, that fit is probably quite good, as it is fitting well at the points where there are lots of observations (the binned scores) and the scatter is at the other quality scores which arise very rarely (as averages over reads with different binned scores). That isn't shown well in that plot, but something to consider would be for us to add scaling of the size of the points by the number of observations supported by that point. 

If you'd like to try it yourself, this will give a cruder version of that: `plotErrors(...) + aes(size=tot)`

On the non-convergence thing,  wouldn't worry about it. See more here: https://benjjneb.github.io/dada2/faq.html#what-if-the-self-consistency-loop-terminated-before-convergence

**Comment by shreyaskumbhare** [comment]
Hi @benjjneb , based on your suggestion, here is the plot:

[Rplot01_batch1.pdf](https://github.com/benjjneb/dada2/files/2262621/Rplot01_batch1.pdf)

I would really appreciate if you could help me in interpreting this plot. Thanks!

**Comment by shreyaskumbhare** [comment]
Hi @benjjneb , based on your suggestion I have re-plotted the error model:

[Rplot01_batch1.pdf](https://github.com/benjjneb/dada2/files/2262632/Rplot01_batch1.pdf)

I will really appreciate, if you can help me in interpreting this plot. Thanks!

**Comment by benjjneb** [comment]
The points that stray above the black line (fitted model) are in principle the ones that could be concerning, as those are Q scores at which the observed error rates is higher than the fitted error rate. But those are all the smallest possible points, indicating they are supported by very few observations and so could just be noise.

Shorter version, you should be fine using the fitted error model.
