### ISSUE TITLE
Sequence table merge error

### ISSUE THREAD

**Issue by Philippa36** [benjjneb/dada2#536]
I am getting an error on trying to merge some of my sequence tables, most have merged successfully but 2 produce the error:

Error in if (!(all(sapply(tables, is.sequence.table)))) { : 
  missing value where TRUE/FALSE needed

I tried re-running using the same filterandtrim() cutoffs for all runs, but Im still getting the same problem with the same 2 sequence tables.

Thank you in advance.

**Comment by benjjneb** [comment]
Can you post the command that gives that error? And give us more an idea of what you are doing? Following the... tutorial workflow? Etc.

**Comment by Philippa36** [comment]
Thank you for your quick reply.

The command was:
st.batch1 <- mergeSequenceTables(st1, st2, st3, st4, st5, st6, st7, st8, st9, st10, st11, st12, st13, st14, st15, st16)

I'm following the tutorial workflow for big data, paired end reads.

**Comment by benjjneb** [comment]
What do the following give for one of the two tables which is causing the merge failure:

```{r]
class(st)
dim(st)
st[1:3, 1:3]
```

**Comment by Philippa36** [comment]
I get:

> class(st9)
[1] "matrix"
> dim(st9)
[1]   89 6317
> st9[1:3, 1:3]
                GAGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAGATGGATGTTTAAGTCAGTTGTGAAAGTTTGCGGCTCAACCGTAAAATTGCAGTTGATACTGGATATCTTGAGTGCAGTTGAGGCAGGCGGAATTCGTGGTGTAGCGGTGAAATGCTTAGATATCACGAAGAACTCCGATTGCGAAGGCAGCCTGCTAAGCTGCAACTGACATTGAGGCTCGAAAGTGTGG
Plate9.1.fastq                                                                                                                                                                                                                                      0
Plate9.10.fastq                                                                                                                                                                                                                                  2002
Plate9.15.fastq                                                                                                                                                                                                                                     0
                AAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGCAGGCGGTGCGGCAAGTCTGATGTGAAAGCCCGGGGCTCAACCCCGGTACTGCATTGGAAACTGTCGTACTAGAGTGTCGGAGGGGTAAGCGGAATTCCTAGTGTAGCGGTGAAATGCGTAGATATTAGGAGGAACACCAGTGGCGAAGGCGGCTTACTGGACGATAACTGACGCTGAGGCTCGAAAGCGTGG
Plate9.1.fastq                                                                                                                                                                                                                                     38
Plate9.10.fastq                                                                                                                                                                                                                                   753
Plate9.15.fastq                                                                                                                                                                                                                                     0
                AAGCGTTGTCCGGAATAATTGGGCGTAAAGGGCGCGTAGGCGGCTCGGTAAGTCTGGAGTGAAAGTCCTGCTTTTAAGGTGGGAATTGCTTTGGATACTGTCGGGCTTGAGTGCAGGAGAGGTTAGTGGAATTCCCAGTGTAGCGGTGAAATGCGTAGAGATTGGGAGGAACACCAGTGGCGAAGGCGACTAACTGGACTGTAACTGACGCTGAGGCGCGAAAGTGTGG
Plate9.1.fastq                                                                                                                                                                                                                                   2271
Plate9.10.fastq                                                                                                                                                                                                                                  1180
Plate9.15.fastq                                                                                                                                                                                                                                     0

It looks like I have no reads left in some samples and this may be the problem?

Thank you

**Comment by benjjneb** [comment]
How about:

```
any(is.na(st))
any(is.na(colnames(st)))
any(is.na(rownames(st)))
```

**Comment by Philippa36** [comment]
I get:

> any(is.na(st9))
[1] FALSE
> any(is.na(colnames(st9)))
[1] FALSE
> any(is.na(rownames(st9)))
[1] TRUE

**Comment by benjjneb** [comment]
> any(is.na(rownames(st9)))
> [1] TRUE

There's the problem. Some of your rows have NA names, and `mergeSequenceTables` needs all the rows (i.e. samples) to be named.

**Comment by Philippa36** [comment]
Ah, thank you!

I had a look at the cause and I seem to be gaining 'samples' on the dereplication step for some reason.. It goes from 81 until the filtering step (as expected), to 204.

**Comment by Philippa36** [comment]
sorry I think i am getting confused.

Please could you help work out what is going wrong with the pipeling for this sequence table?

**Comment by benjjneb** [comment]
What are the extra files that you are reading in at the dereplication step that aren't getting names? 

You need to diagnose what they are, and whether there is some path issue leading to too many files being read in, or a naming issue where you need to generate sample names for the those files that currently are unnamed.

**Comment by Philippa36** [comment]
Sorry for the slow reply.

This has worked now although I don't think I fixed the original issue. I deleted the lowest quality samples and after this things seemed to run smoothly again.
