### ISSUE TITLE
merge and concatenation

### ISSUE THREAD

**Issue by shyamrallapalli** [benjjneb/dada2#537]
There seem to be studies with border line read lengths that are resulting in some or most of the de-replicated pairs not merging, like the study i am dealing with.

So I set out to do both merging and concatenation of read pairs and found two pervious issues
#279 and #517 

It could be a good approach, considering you could add species to concatenated reads as well (as mentioned in #529 )

After a bit of thought I came up with following approach, 
Where I use `mergePairs` three times 
* merging with default strict no mismatches
* merging with mismatches and 
* concatenation.

Reason for two types of merging is, default merging in dada2 uses nwalign with higher penalty for mismatch and gap (-64), while with `mismatch > 0` merging uses lower penalty for mismatch and gap (-8)

two example cases where mismatch align does give decent match with 1 mismatch 
(second line in the diff below is mismatch merge data)
```diff
##sequences	abundance	forward	reverse	nmatch	nmismatch	nindel	prefer	accept
< 	2	29	11	2	0	0	2	FALSE
---
> GACGAACGCTGG.....TAACTACGTG	2	29	11	41	1	0	2	TRUE
```

```diff
##sequences	abundance	forward	reverse	nmatch	nmismatch	nindel	prefer	accept
< 	4	1	26	0	0	0	1	FALSE
---
> ATTGAACGCTGGC...CTAACTTCGTG	4	1	26	49	1	0	1	TRUE
```

then apply following filtering to replace 'no merges' in strict merge data frames with either mismatch merges  or concatenation

```R

# maxMismatch=0 has higher penalty for mismatch and gap for nwalgin (-64)
cat("\n\nperfect match merging....\n")
mergedData <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, maxMismatch=0, trimOverhang=TRUE, returnRejects=TRUE, verbose=TRUE)
# maxMismatch > 0 has lower penalty for mismatch and gap for nwalgin (-8)
cat("\n\nmismatch allowed merging....\n")
mismatch_mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, maxMismatch=4, trimOverhang=TRUE, returnRejects=TRUE, verbose=TRUE)
cat("\n\nconcatenation merging....\n")
concats <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, justConcatenate=TRUE, verbose=TRUE)

# save sample merge dfs for diff comparisions
sapply(names(mergedData), function (x) write.table(mergedData[[x]], file=paste(x, "strict_mergers.txt", sep="_"),
 sep="\t", row.names=FALSE, quote=FALSE) )

sapply(names(mismatch_mergers), function (x) write.table(mismatch_mergers[[x]], file=paste(x, "loose_mergers.txt", sep="_"),
 sep="\t", row.names=FALSE, quote=FALSE) )

# converting concat df to matrix to overcome error of - unimplemented type 'list' in 'EncodeElement' 
sapply(names(concats), function (x) write.table(as.matrix(concats[[x]]), file=paste(x, "all_concats.txt", sep="_"),
 sep="\t", row.names=FALSE, quote=FALSE) )

# replace mismatched or concatenated ASVs in the main mergedData
for(i in names(mergedData)) {
	# store row index to drop certain ASVs later
	rowsToDelete = vector()

	mergedDf = mergedData[[i]]
	cat(i, "Out of total", sum(mergedDf$abundance), "paired-reads (in", nrow(mergedDf), "unique pairings), retained ")
	mismatchDf = mismatch_mergers[[i]]
	rownames(mismatchDf) = paste(mismatchDf$forward, mismatchDf$reverse, sep="_")
	concatDf = concats[[i]]
	rownames(concatDf) = paste(concatDf$forward, concatDf$reverse, sep="_")

	for (row in 1:nrow(mergedDf)) {
		# skipping rows that are good to go from default analysis
		if (mergedDf[row,]$accept) { next }

		uniquePairID = paste(mergedDf[row,]$forward, mergedDf[row,]$reverse, sep="_")

		# if match length is less than 12 then good to go with concatenation
		if (mismatchDf[uniquePairID,]$nmatch <= 12) {
			mergedDf[row,] = concatDf[uniquePairID,]
		}
		# ignoring ASVs with many mismatches with long overlap
		else{
			misMatchIndels = mismatchDf[row,]$nmismatch + mismatchDf[row,]$nindel
			cutOff = 0
			if ( mismatchDf[uniquePairID,]$nmatch > 12 && mismatchDf[uniquePairID,]$nmatch <= 50 ) {
				cutOff = 1
			}
			else if ( mismatchDf[uniquePairID,]$nmatch > 50 && mismatchDf[uniquePairID,]$nmatch <= 100 ) {
				cutOff = 2
			}
			else if (mismatchDf[uniquePairID,]$nmatch > 100) {
				cutOff = 3
			}
			# check if mismatches are below cut off
			if (misMatchIndels <= cutOff) {
				mergedDf[row,] = mismatchDf[uniquePairID,]
			} 
			# discard if mismatches are high in longer than 100bp match 
			# else if (cutOff==3 && misMatchIndels > 3) {
			# 	rowsToDelete = c(rowsToDelete, row)
			# }
			# concatenate if mismatches are high in overlap region remove reverse read part of the overlap region 
			else {
				trimLength = mismatchDf[uniquePairID,]$nmatch
				concatDf[uniquePairID,]$sequence = gsub(paste0("N{10}[A-z]{", trimLength, "}"), "NNNNNNNNNN", concatDf[uniquePairID,]$sequence)
				mergedDf[row,] = concatDf[uniquePairID,]
			}
		}
	}

	if (length(rowsToDelete) == 0){
		mergedData[[i]] = mergedDf
	} else {
		mergedData[[i]] = mergedDf[-rowsToDelete,]
	}
	cat(sum(mergedData[[i]]$abundance), "paired-reads (in", nrow(mergedData[[i]]), "unique pairings)\n")
}

```

And assignSpecies to all sequences with following code modified from #529 
`taxa` is the matrix from `assignTaxonomy` step

```R
# trim concatenated sequences from "NNNN" onwards and assign species
asvSeqs <- gsub("N{10}[A-z]*", "", getSequences(seqtab.filter))
asgnSpecs <- assignSpecies(asvSeqs, "path/to/species_assignment.fa")

# transfer species annotation to same genus ASVs else "NA"
same.genus <- asgnSpecs[,"Genus"] == taxa[,"Genus"]
same.genus[is.na(same.genus)] <- FALSE
taxa <- cbind(taxa, Species = rep(NA, nrow(taxa)))
taxa[same.genus, "Species"] <- asgnSpecs[same.genus, "Species"]

```

As you can see I am trimming overlap region in the second read when concatenating.
As second reads tend to carry low quality data at the ends, trimming them off to decrease ambiguity in taxa assignment.

Although I have included code to drop ASVs with large overlap and mismatches (>3), but i haven't used in my current analysis.

Any feedback anyone could give would be of great help, such as any issues or considerations i have overlooked or any improvements

**Comment by benjjneb** [comment]
I didn't evaluate your code line-by-line, but the overall logic and `mergePairs` calls all seem sound to me. I do think that the following is going to be important:

> Although I have included code to drop ASVs with large overlap and mismatches (>3), but i haven't used in my current analysis.

That is something that you should do, to avoid spurious concatenated sequences that really represent uncorrected errors that should be filtered out by the merge step.

At a higher level, anytime there is a mixture of merging and concatenation, you are introducing some bias between the long/short amplicons. Hence, one should avoid such amplicon setups where possible. However, once one has such data, it is far more of a bias to throw away everything that doesn't overlap, for example, so I think the approach you are taking is sound given the data you are working with.

Hope that helps! Let me know if any more specific questions, but you seem to have a pretty good handle on things based on your code above.

**Comment by shyamrallapalli** [comment]
thank you @benjjneb, for your comments and suggestion about uncorrected errors.
thanks a million for dada2 development and maintenance.
