### ISSUE TITLE
Learn the Error Rates don't fit

### ISSUE THREAD

**Issue by AgustinPardo** [benjjneb/dada2#539]
I'm running the "Learn the Error Rates" of the dada2 pipeline and the error plot don't fit well. I tried changing the nbases parameters as it says in the tutorial pipeline, but is still the same result. I tried nbases=1e8, and nbases=1e10. Do I have to increase more the nbases parameter? Are another considerations to take into account?

**Comment by AgustinPardo** [comment]
I also receive the next message after execution:
```
Warning message:
In dada(drps, err = NULL, errorEstimationFunction = errorEstimationFunction,  :
  nbases is not a valid DADA option.
```

**Comment by benjjneb** [comment]
Can you post the output of `plotErrors` that visualizes the fitted error rates?

What is `packageVersion("dada2")`?

**Comment by AgustinPardo** [comment]
- packageVersion("dada2") = ‘1.6.0’
- Forward error plot
![foward_error](https://user-images.githubusercontent.com/14830537/43912259-2051b584-9bd8-11e8-99eb-9f8867c8b0d1.png)
- Reverse error plot
![reverse_error](https://user-images.githubusercontent.com/14830537/43912332-4b5fe610-9bd8-11e8-954f-819640a85146.png)

**Comment by benjjneb** [comment]
That fit looks very good. I would use those error rates w/ confidence. What is your concern?

**Comment by AgustinPardo** [comment]
Thank you. I think I have to understand it a little better. Where can I find more information about error rates?

**Comment by benjjneb** [comment]
The help files for `?learnErrors` might help, and the section on the tutorial might help a bit too: https://benjjneb.github.io/dada2/tutorial.html#learn-the-error-rates

In those plots, the black line is the error model, and it closely fits the black points, which are the observed error rates, indicating all is well.
