### ISSUE TITLE
error with USE_QUALS = FALSE

### ISSUE THREAD

**Issue by luhugerth** [benjjneb/dada2#54]
I noticed a weird pattern on the error estimation sample of some of my samples and decided to compare estimating the substitution rates considering or not the Phred scores (the reasoning being that, if the vast majority of substitutions happen in PCR and not during sequencing, the Phred score is irrelevant). However, I get the following error:

> dadas <- dada(derep, err=inflateErr(tperr1,3), USE_QUALS=FALSE)

Sample 1 - 40323 reads in 21169 unique sequences.

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .Call("dada2_dada_uniques", PACKAGE = "dada2", seqs, abundances,     err, quals, score, gap, use_kmers, kdist_cutoff, band_size,     omegaA, use_singletons, omegaS, max_clust, min_fold, min_hamming,     use_quals, qmin, qmax, final_consensus, verbose)
 2: dada_uniques(names(derep[[i]]$uniques), unname(derep[[i]]$uniques),     err, qi, opts[["SCORE_MATRIX"]], opts[["GAP_PENALTY"]], opts[["USE_KMERS"]],     opts[["KDIST_CUTOFF"]], opts[["BAND_SIZE"]], opts[["OMEGA_A"]],     opts[["USE_SINGLETONS"]], opts[["OMEGA_S"]], opts[["MAX_CLUST"]],     opts[["MIN_FOLD"]], opts[["MIN_HAMMING"]], opts[["USE_QUALS"]],     opts[["QMIN"]], opts[["QMAX"]], opts[["FINAL_CONSENSUS"]],     opts[["VERBOSE"]])
 3: dada(derep, err = inflateErr(tperr1, 3), USE_QUALS = FALSE)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

**Comment by benjjneb** [comment]
Hi Luisa,
Clearly there's a bug in there, but I haven't been able replicate this
behavior. When I run the same command: `dada(derep,
err=inflateErr(tperr1,3), USE_QUALS=FALSE)` one some of my own data, the
algorithm is working as expected.

Could you post the version of the dada2 package you are using, and which
version of R and the OS you are on?

-Ben

**Comment by luhugerth** [comment]
Hi, 

This was observed on R 3.2.3 on an Scientific Linux cluster running DADA2 0.9.5 with Rcpp 0.12.1. 

I got the same behaviour on R 3.2.2 on Ubuntu 14.04, running running DADA2 0.9.4 with Rcpp 0.12.2.

**Comment by benjjneb** [comment]
Hi Luisa,

I still can't get the crash behavior with the 0.9.6 version of DADA2, which
is the last 0.9 version I've kept. Could you try pulling the current
version of dada2 and check if that fixes the problem? There has been some
significant under-the-hood work and code cleanup between 0.9.5 and today
(0.10.1).

If that doesn't work, could you share share the specific data file that is
causing this issue (if that is possible)? There may be something particular
about that data file that is feeding into this issue.

-Ben

**Comment by luhugerth** [comment]
Looks like this message didn't go through, trying again with a smaller file
sample.

As a work around, would it work to artificially set the same quality value
for all bases?


2016-01-25 14:30 GMT+01:00 Luisa W. Hugerth <luisa.hugerth@scilifelab.se>:

> Hi Ben,
>
> The update to 0.10.1 didn't solve it :/
>
> I'm attaching one of my fastq files, though it's hard to believe the fault
> is there, considering that DADA2 runs normally when USE_QUALS=TRUE. I'm
> also attaching my R script.
>
> /Luisa
>
> 2016-01-22 23:15 GMT+01:00 benjjneb <notifications@github.com>:
>
>> Hi Luisa,
>>
>> I still can't get the crash behavior with the 0.9.6 version of DADA2,
>> which
>> is the last 0.9 version I've kept. Could you try pulling the current
>> version of dada2 and check if that fixes the problem? There has been some
>> significant under-the-hood work and code cleanup between 0.9.5 and today
>> (0.10.1).
>>
>> If that doesn't work, could you share share the specific data file that is
>> causing this issue (if that is possible)? There may be something
>> particular
>> about that data file that is feeding into this issue.
>>
>> -Ben
>>
>> On Fri, Jan 22, 2016 at 2:04 AM, Luisa Hugerth <notifications@github.com>
>> wrote:
>>
>> > Hi,
>> >
>> > This was observed on R 3.2.3 on an Scientific Linux cluster running
>> DADA2
>> > 0.9.5 with Rcpp 0.12.1.
>> >
>> > I got the same behaviour on R 3.2.2 on Ubuntu 14.04, running running
>> DADA2
>> > 0.9.4 with Rcpp 0.12.2.
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/benjjneb/dada2/issues/54#issuecomment-173867144>.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/benjjneb/dada2/issues/54#issuecomment-174070251>.
>>
>
>
>
> --
> Luisa W. Hugerth
> PhD Student
>
> Environmental genomics lab
> School of Biotechnology
> Royal Institute of Technology (KTH)
> Science for Life Laboratory
> Stockholm - SWEDEN
>
> *luisa.hugerth@scilifelab.se <luisa.hugerth@scilifelab.se>*
>



-- 
Luisa W. Hugerth
PhD Student

Environmental genomics lab
School of Biotechnology
Royal Institute of Technology (KTH)
Science for Life Laboratory
Stockholm - SWEDEN

*luisa.hugerth@scilifelab.se <luisa.hugerth@scilifelab.se>*

**Comment by benjjneb** [comment]
Hi Luisa,

Thanks for sending me the data file that caused this crash. Unfortunately I still can't replicate the crash. When I run the following code: 

```
derep <- derepFastq("runE_247_cat.fq.gz")
test.dada <- dada(derep, err=inflateErr(tperr1,3), USE_QUALS=FALSE)
```

The algorithm functions as expected, both with dada2 version 0.10.1 and 0.9.6.

This may indicate an issue arising at the compilation stage (as the core parts of the algorithm are written in C and compiled at the user end). When you build the dada2 package, the specific compilation flags should be echoed to screen. Could you repost one of those echoed commands lines? And assuming gcc is being called, also query the gcc version being called?

**Comment by benjjneb** [comment]
Since its hard for me to fix the crash bug without being able to replicate it, I'm providing a work-around that does what you want. The dada(...) function accepts a user-input function to estimate error rates from the observed transitions. The default is loessErrfun but anything that takes the 16x41 matrix of observed transitions, and returns a 16x41 matrix of observed error rates can work. Here I modified loessErrfun to return error rates estimated without taking into account quality scores:

```
noqualErrfun <- function(trans) {
  # Init matrix to record the estimated transition probabilities
  est <- matrix(0, nrow=0, ncol=ncol(trans))
  for(nti in c("A","C","G","T")) {
    for(ntj in c("A","C","G","T")) {
      if(nti != ntj) {
        row.name <- paste0(nti,"2",ntj)
        # Estimate transition rate by aggregating across all quality scores
        tot.trans <- sum(trans[row.name,])
        tot.init.nt <- sum(trans[paste0(nti,"2",c("A","C","G","T")),])
        est <- rbind(est, rep(tot.trans/tot.init.nt, ncol(trans)))
      } # if(nti != ntj)
    } # for(ntj in c("A","C","G","T"))
  } # for(nti in c("A","C","G","T"))
    
  # Expand the err matrix with the self-transition probs
  err <- rbind(1-colSums(est[1:3,]), est[1:3,],
               est[4,], 1-colSums(est[4:6,]), est[5:6,],
               est[7:8,], 1-colSums(est[7:9,]), est[9,],
               est[10:12,], 1-colSums(est[10:12,]))
  rownames(err) <- paste0(rep(c("A","C","G","T"), each=4), "2", c("A","C","G","T"))
  colnames(err) <- colnames(trans)
  # Return
  return(err)
}

test.dada <- dada(derep, err=inflateErr(tperr1,3), errorEstimationFunction=noqualErrfun)

plotErrors(test.dada)
```

The plotErrors graphs show how well (or not) estimating without quality information does. You can use this function as part of the selfConsist=TRUE mode as well.

**Comment by luhugerth** [comment]
Hi Ben,
Thanks for the noqualErrfun, it works like magic!

The gcc version is 4.8.4. If you're still interested in the output on the build, this is it:

	> devtools::install_github("benjjneb/dada2")
	Downloading GitHub repo benjjneb/dada2@master
	from URL https://api.github.com/repos/benjjneb/dada2/zipball/master
	Installing dada2
	'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD  \
	  INSTALL '/tmp/RtmpsDaokP/devtools3cac5724a586/benjjneb-dada2-87b6295'  \
	  --library='/usr/local/lib/R/site-library' --install-tests 

	* installing *source* package ‘dada2’ ...
	** libs
	g++ -I/usr/share/R/include -DNDEBUG   -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
	g++ -I/usr/share/R/include -DNDEBUG   -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c Rmain.cpp -o Rmain.o
	g++ -I/usr/share/R/include -DNDEBUG   -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c cluster.cpp -o cluster.o
	g++ -I/usr/share/R/include -DNDEBUG   -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c error.cpp -o error.o
	g++ -I/usr/share/R/include -DNDEBUG   -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c evaluate.cpp -o evaluate.o
	g++ -I/usr/share/R/include -DNDEBUG   -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c misc.cpp -o misc.o
	g++ -I/usr/share/R/include -DNDEBUG   -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c nwalign_endsfree.cpp -o nwalign_endsfree.o
	g++ -I/usr/share/R/include -DNDEBUG   -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c nwalign_vectorized.cpp -o nwalign_vectorized.o
	g++ -I/usr/share/R/include -DNDEBUG   -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c pval.cpp -o pval.o
	g++ -I/usr/share/R/include -DNDEBUG   -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c strmap.cpp -o strmap.o
	g++ -I/usr/share/R/include -DNDEBUG   -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c taxonomy.cpp -o taxonomy.o
	g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o dada2.so RcppExports.o Rmain.o cluster.o error.o evaluate.o misc.o nwalign_endsfree.o nwalign_vectorized.o pval.o strmap.o taxonomy.o -L/usr/lib/R/lib -lR
	installing to /usr/local/lib/R/site-library/dada2/libs

**Comment by homopolymer** [comment]
Hi Luisa,

How to solve this problem? I encounter an issue looks like your issue.

 *** caught segfault ***
address (nil), cause 'memory not mapped'

Traceback:
 1: .Call("dada2_dada_uniques", PACKAGE = "dada2", seqs, abundances,     err, quals, score, gap, use_kmers, kdist_cutoff, band_size,     omegaA, max_clust, min_fold, min_hamming, use_quals, final_consensus,     vectorized_alignment, homo_gap, multithread, verbose)
 2: dada_uniques(names(derep[[i]]$uniques), unname(derep[[i]]$uniques),     err, qi, opts[["SCORE_MATRIX"]], opts[["GAP_PENALTY"]], opts[["USE_KMERS"]],     opts[["KDIST_CUTOFF"]], opts[["BAND_SIZE"]], opts[["OMEGA_A"]],     if (initializeErr) {        1    } else {        opts[["MAX_CLUST"]]    }, opts[["MIN_FOLD"]], opts[["MIN_HAMMING"]], opts[["USE_QUALS"]],     FALSE, opts[["VECTORIZED_ALIGNMENT"]], opts[["HOMOPOLYMER_GAP_PENALTY"]],     multithread, opts[["VERBOSE"]])
 3: dada(derepF, err = tperr1, USE_QUALS = FALSE, selfConsist = TRUE)
An irrecoverable exception occurred. R is aborting now ...
