### ISSUE TITLE
Accuracy evaluation 

### ISSUE THREAD

**Issue by Bhamal** [benjjneb/dada2#541]
Hi,

I recently got into 16S amplicon data analysis and have been learning with DADA2 pipeline tutorial (https://benjjneb.github.io/dada2/tutorial.html). Right now I am trying to evaluate accuracy of the data and I have following problem,

In the tutorial, "mock community" has 20 known strains and all 20 are inferred by DADA2.
In my data, the "mock community" has 7 known strains. However, DADA2 infers 103 sequences. After assigning taxonomy, I get 9 unique genus level taxa which are correct. However, I wonder if I am doing something wrong as I do not get 7 sequences inferred by DADA2 as in the tutorial.

I would appreciate for any help/suggestions . I attach the error plots of forward and backward sequences which look normal to me as compared to the plots presented in the tutorial.

![errormodelr](https://user-images.githubusercontent.com/38923810/44027352-d7b0d434-9efe-11e8-80a0-43b651ac7d3f.png)
![errormodelf](https://user-images.githubusercontent.com/38923810/44027353-d7c9856a-9efe-11e8-89a1-1d647bc88be7.png)

best wishes,
krishna

**Comment by benjjneb** [comment]
In my experience, the most common reason for this would be contamination, i.e. sequences deriving from the lab environment or reagents, or sequences that "cross-contaminate" from other samples on the same sequencing run, for example by index switching. One way to try to diagnose this is to look at the distribution of assigned taxonomies. What are the results of, say, the following?

```
table(tax[,"Kingdom"])
table(tax[,"Order"])
```

Second, the `dada` function produces a lot of very useful diagnostics, that can help identify if something else is going wrong, as part of the `$clustering` data.frame. You can read the help fucntion `?dada` for some more details on that. What are the results of the following?

```
# Assuming ddF is the result of dada-denoising the forward reads from the mock files
ddF$clustering[,-1]
```

**Comment by Bhamal** [comment]
Thanks a lot! That was very helpful.
