### ISSUE TITLE
Confusion between learnErrors and dada(selfConsist=T)

### ISSUE THREAD

**Issue by polypay123** [benjjneb/dada2#543]
I'm trying to understand your [demo pipeline](https://benjjneb.github.io/dada2/tutorial.html) and the tuning parameters that are available in the different functions. In the demo you suggest...

```
errF <- learnErrors(filtFs, multithread=TRUE)
errR <- learnErrors(filtRs, multithread=TRUE)
```

After some dereplication steps, you suggest...

```
dadaFs <- dada(derepFs, err=errF, multithread=TRUE)
dadaRs <- dada(derepRs, err=errR, multithread=TRUE)
```

Looking at the `dada` documentation I see the `selfConsist` parameter. If I were to use `selfConsist=TRUE` in `dada` would I still need to run `learnErrors` (I could set `err=NULL` in `dada`)? It seems like `learnErrors` and `dada(selfConsist=TRUE)` are doing the same thing.

**Comment by benjjneb** [comment]
> It seems like learnErrors and dada(selfConsist=TRUE) are doing the same thing.

They mostly are. `learnErrors` calls `dada(..., selfConsist=TRUE)` to learn the error rates. 

The main purpose of `learnErrors` is that it speeds things up by learning the error rates over an appropriate subset of large datasets, set by the `nbases` parameter (or `nreads` in earlier version).

**Comment by polypay123** [comment]
Thanks - so if I do `learnErrors` there's no reason to do use `selfConsist=TRUE`?

**Comment by benjjneb** [comment]
Correct. You run `learnErrors` and then use that estimated error rate in the subsequent `dada` call as is (i.e. no more `selfConsist=TRUE` loops).
