### ISSUE TITLE
"DADA2 workflow for Big Data: Paired-end" Assign Taxonomy use a lot of RAM

### ISSUE THREAD

**Issue by AgustinPardo** [benjjneb/dada2#548]
Hello,
I am running the pipeline "A DADA2 workflow for Big Data: Paired-end", and I have an issue in the step "Assign Taxonomy".  From the previous steps I got 6 ".rds" files . The total size of the 6 files is 19 Mb.
Then I run:
```
library(dada2); packageVersion("dada2")
# Merge multiple runs (if necessary)
st1 <- readRDS("/16S-CuartelV/out_DADA2_BigData/seqtab_Invierno2017.rds")
st2 <- readRDS("/16S-CuartelV/out_DADA2_BigData/seqtab_Otoño2015.rds")
st3 <- readRDS("/16S-CuartelV/out_DADA2_BigData/seqtab_Otoño2016.rds")
st4 <- readRDS("/16S-CuartelV/out_DADA2_BigData/seqtab_Primavera2014.rds")
st5 <- readRDS("/16S-CuartelV/out_DADA2_BigData/seqtab_Primavera2016.rds")
st6 <- readRDS("/16S-CuartelV/out_DADA2_BigData/seqtab_Primavera2017.rds")

st.all <- mergeSequenceTables(st1, st2, st3, st4, st5, st6)
# Assign taxonomy
taxa <- assignTaxonomy(st.all, "/16S-CuartelV/silva_nr_v132_train_set.fa.gz", multithread=TRUE)
taxa <- addSpecies(taxa, "/16S-CuartelV/silva_species_assignment_v132.fa.gz")
# Write to disk
saveRDS(seqtab, "/16S-CuartelV/out_DADA2_BigData/seqtab_final.rds") # CHANGE ME to where you want  sequence table saved
saveRDS(taxa, "/16S-CuartelV/out_DADA2_BigData/tax_final.rds") # CHANGE ME ...
```
The problem is that the "assignTaxonomy" step takes 25 Gb of RAM. It run for a few days, and then R got an error execution.

**Comment by benjjneb** [comment]
The memory scaling of `assignTaxonomy` can be a problem for very large datasets, see #239 

What version of the package are you using? The memory scaling of `addSpecies` was dramatically improved in version 1.8, so an update to that version will fix things if that's the piece that is the problem.

If it's `assignTaxonomy` that's the problem, I would recommend a workaround where you do assignment on chunks of the sequences at a time, e.g. 

```
sq <- getSequences(st.all)
t1 <- assignTaxonomy(sq[1:1000], ...)
t2 <- assignTaxonomy(sq[1001:2000],...)
# Probably loop through in chunks like this
taxa <- rbind(t1, t2, ...)
```

Sorry for the headache, the memory scaling should be better but I've just not had time to get back to this. You could also consider another taxonomic assignment solution in R, such as the `IDTaxa` tool in the DECIPHER package.

**Comment by benjjneb** [comment]
One other thing, I'd recommend removing chimeras from `st.all` before tax assignment if you haven't, as that will probably cut the number of sequences down a lot and then things might just work normally.
