### ISSUE TITLE
Using assignTaxonomy with sequences from an external FASTA file

### ISSUE THREAD

**Issue by zefrieira** [benjjneb/dada2#550]
I've received a FASTA file containing ASVs obtained using DADA2. I need to assign taxonomy to these sequence variants, but I don't have the original dada2 object.

How should I read the file and input the sequences to `assignTaxonomy`?

Thank you!

**Comment by nagasridhar** [comment]
To assign taxonomy to a fasta file, you can read in the fasta file into R using the ShortRead bioconductor package. 

Once you have installed the ShortRead package, you can read in the fasta file, and then assign taxonomy using the DADA2 assignTaxonomy function.

You can follow the steps as below:

`<
library(ShortRead)  ## Package for reading in fasta file
library(dada2)
fasta.file <- as.character(sread(readFasta("/pathtofastafile"))) ## Loading the fasta file
taxa.for.fasta <- assignTaxonomy(fasta.file, "/pathtotaxonomydatabase")
>`

**Comment by zefrieira** [comment]
Thank you!
