### ISSUE TITLE
inflateError - incorrect number of dimensions

### ISSUE THREAD

**Issue by casett** [benjjneb/dada2#551]
I am running dada2 v 1.9.1 with R 3.5.0 on PEAR pre-merged ITS data.

I estimated errors using:
`err <- learnErrors(filts, multithread = TRUE, randomize = TRUE, nbases = 1e9)`

I then wanted to inflate the errors because of the issues with the quality scores when using pre-merged PEAR reads (and then I am hoping to compare the resulting ASV table to one where reads are merged in dada2, etc, for my dataset of interest), but when I ran the following I got an error. Please advise.

`err3 <- inflateErr(err, 3)`
Error in err[t_errs, ] : incorrect number of dimensions

**Comment by benjjneb** [comment]
Does this solve the error? `err3 <- inflateErr(getErrors(err), 3)`

**Comment by casett** [comment]
Yes! Thanks so much!

**Comment by benjjneb** [comment]
Reopening and marking as a bug, as this should be fixed w/in `inflateErr`
