### ISSUE TITLE
problems installing dada2: /usr/lib/R/etc/Makeconf:168: recipe for target 'kmers.o' failed make: *** [kmers.o] Error 1 ERROR: compilation failed for package ‘dada2’

### ISSUE THREAD

**Issue by thidmuld** [benjjneb/dada2#552]
I have already successfully installed dada2 on other ubuntu platforms. But on this desktop, I always end up with the same error message (see below). 
Any ideas on how to solve this?

BioC_mirror: https://bioconductor.org
Using Bioconductor 3.6 (BiocInstaller 1.28.0), R 3.4.4 (2018-03-15).
Installing package(s) ‘dada2’
trying URL 'https://bioconductor.org/packages/3.6/bioc/src/contrib/dada2_1.6.0.tar.gz'
Content type 'application/x-gzip' length 1767703 bytes (1.7 MB)
==================================================
downloaded 1.7 MB

* installing *source* package ‘dada2’ ...
** libs
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG  -I"/home/avecom/R/i686-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/avecom/R/i686-pc-linux-gnu-library/3.4/RcppParallel/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-738gYq/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG  -I"/home/avecom/R/i686-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/avecom/R/i686-pc-linux-gnu-library/3.4/RcppParallel/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-738gYq/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c Rmain.cpp -o Rmain.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG  -I"/home/avecom/R/i686-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/avecom/R/i686-pc-linux-gnu-library/3.4/RcppParallel/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-738gYq/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c chimera.cpp -o chimera.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG  -I"/home/avecom/R/i686-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/avecom/R/i686-pc-linux-gnu-library/3.4/RcppParallel/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-738gYq/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c cluster.cpp -o cluster.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG  -I"/home/avecom/R/i686-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/avecom/R/i686-pc-linux-gnu-library/3.4/RcppParallel/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-738gYq/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c error.cpp -o error.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG  -I"/home/avecom/R/i686-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/avecom/R/i686-pc-linux-gnu-library/3.4/RcppParallel/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-738gYq/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c evaluate.cpp -o evaluate.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG  -I"/home/avecom/R/i686-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/avecom/R/i686-pc-linux-gnu-library/3.4/RcppParallel/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-738gYq/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c filter.cpp -o filter.o
g++ -std=gnu++11 -I/usr/share/R/include -DNDEBUG  -I"/home/avecom/R/i686-pc-linux-gnu-library/3.4/Rcpp/include" -I"/home/avecom/R/i686-pc-linux-gnu-library/3.4/RcppParallel/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-738gYq/r-base-3.4.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c kmers.cpp -o kmers.o
kmers.cpp: In function ‘double kmer_dist_SSEi(uint16_t*, int, uint16_t*, int, int)’:
kmers.cpp:37:34: warning: SSE vector return without SSE enabled changes the ABI [-Wpsabi]
   __m128i vsum = _mm_set1_epi16(0);
                                  ^
In file included from kmers.cpp:3:0:
/usr/lib/gcc/i686-linux-gnu/7/include/emmintrin.h:647:1: error: inlining failed in call to always_inline ‘__m128i _mm_set1_epi16(short int)’: target specific option mismatch
 _mm_set1_epi16 (short __A)
 ^~~~~~~~~~~~~~
kmers.cpp:37:34: note: called from here
   __m128i vsum = _mm_set1_epi16(0);
                                  ^
In file included from kmers.cpp:3:0:
/usr/lib/gcc/i686-linux-gnu/7/include/emmintrin.h:1382:1: error: inlining failed in call to always_inline ‘__m128i _mm_min_epi16(__m128i, __m128i)’: target specific option mismatch
 _mm_min_epi16 (__m128i __A, __m128i __B)
 ^~~~~~~~~~~~~
kmers.cpp:42:42: note: called from here
     __m128i kmin = _mm_min_epi16(kk1, kk2);
                                          ^
In file included from kmers.cpp:3:0:
/usr/lib/gcc/i686-linux-gnu/7/include/emmintrin.h:700:1: error: inlining failed in call to always_inline ‘__m128i _mm_loadu_si128(const __m128i_u*)’: target specific option mismatch
 _mm_loadu_si128 (__m128i_u const *__P)
 ^~~~~~~~~~~~~~~
kmers.cpp:41:51: note: called from here
     __m128i kk2 = _mm_loadu_si128( (__m128i*) kv2 );
                                                   ^
In file included from kmers.cpp:3:0:
/usr/lib/gcc/i686-linux-gnu/7/include/emmintrin.h:700:1: error: inlining failed in call to always_inline ‘__m128i _mm_loadu_si128(const __m128i_u*)’: target specific option mismatch
 _mm_loadu_si128 (__m128i_u const *__P)
 ^~~~~~~~~~~~~~~
kmers.cpp:40:51: note: called from here
     __m128i kk1 = _mm_loadu_si128( (__m128i*) kv1 );
                                                   ^
In file included from kmers.cpp:3:0:
/usr/lib/gcc/i686-linux-gnu/7/include/emmintrin.h:1021:1: error: inlining failed in call to always_inline ‘__m128i _mm_add_epi16(__m128i, __m128i)’: target specific option mismatch
 _mm_add_epi16 (__m128i __A, __m128i __B)
 ^~~~~~~~~~~~~
kmers.cpp:43:10: note: called from here
     vsum = _mm_add_epi16(vsum, kmin);
     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from kmers.cpp:3:0:
/usr/lib/gcc/i686-linux-gnu/7/include/emmintrin.h:718:1: error: inlining failed in call to always_inline ‘void _mm_storeu_si128(__m128i_u*, __m128i)’: target specific option mismatch
 _mm_storeu_si128 (__m128i_u *__P, __m128i __B)
 ^~~~~~~~~~~~~~~~
kmers.cpp:45:20: note: called from here
   _mm_storeu_si128 ((__m128i*) &dst, vsum);
   ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/R/etc/Makeconf:168: recipe for target 'kmers.o' failed
make: *** [kmers.o] Error 1
ERROR: compilation failed for package ‘dada2’
* removing ‘/home/avecom/R/i686-pc-linux-gnu-library/3.4/dada2’

The downloaded source packages are in
	‘/tmp/RtmpNNT57u/downloaded_packages’
installation path not writeable, unable to update packages: MASS, Matrix, mgcv,
  nlme, survival
Warning message:
In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘dada2’ had non-zero exit status

**Comment by benjjneb** [comment]
Could you tell us a bit more about the hardware of this desktop? The errors here seem to be coming from the SSE code. Does this machine potentially have a non Intel/AMD processor? What's the C comipler being called?

**Comment by thidmuld** [comment]
hei benjjneb,
The desktop runs with an intel core i7-8700 CPU @3.20GHzx8 processor and  intell HD Graphics (Coffeelake 3x8 GT2) x86/MMX/SSE2. The OS-type is 32-bit and it has 31.5 GiB of memory. Further, ubuntu 18.04.1 LTS is installed with default C-compiler: gcc (ubuntu 7.3.0-16 ubuntu3).

**Comment by benjjneb** [comment]
TBH I'm not sure. This https://github.com/mxe/mxe/issues/406 suggests that while your machine has SSE, the compiler flags are not including sse, and that adding the `-msse2` flag would perhaps solve the problem.

Can you try adding `-msse2` to your `~/.R/Makevars` file and see if that solves this issue?

https://stackoverflow.com/questions/10921153/c-compilation-flags-from-r

But why is it happening on this specific machine and not others?

**Comment by benjjneb** [comment]
> Should I use other FLAGS variable, or how should I proceed? (Sorry I don't know much about C and C++ and even less about their flags)

If you look at the compiler commands that are run when the package is installing (they should be echoed to stdout) is the -msse2 flag included? If it is, then `CXXFLAGS` worked, if not then you can try the other ones until it shows up, e.g. `CFLAGS`, although I think `CXXFLAGS` is the right one to use.
