### ISSUE TITLE
Construct phylogenetic tree error

### ISSUE THREAD

**Issue by AgustinPardo** [benjjneb/dada2#567]
Hello, I'm trying to run the next command and I get an error.

> seqs <- getSequences(seqtab.nochim)
> names(seqs) <- seqs # This propagates to the tip labels of the tree
> alignment <- AlignSeqs(DNAStringSet(seqs), anchor=NA)

Error:
> Determining distance matrix based on shared 7-mers:
>   |                                                                                                                                     |   0%Error: cannot allocate vector of size 227.4 Gb

**Comment by benjjneb** [comment]
How many sequences are in your table? `dim(seqtab.nochim)`

**Comment by AgustinPardo** [comment]
dim(seqtab.nochim)

> [1]    125 174698

**Comment by benjjneb** [comment]
Yeah, that is too many sequences for `AlignSeqs` to handle (it scales up to ~40k I think) and even if you could align them, it would take forever to build an ML tree with phangorn.

Either you need to cut down your table, for example by a prevalence of minimum abundance filter, or you're going to need to use some external software to make a tree from that many sequences. The obvious candidates are RaxML and FastTree. For RaxML, the `ips` package helps interface with it from R.

**Comment by AgustinPardo** [comment]
**Hello, I'm trying to do this:**

_seqs <- getSequences(seqtab.nochim)
alignment <- AlignSeqs(DNAStringSet(seqs), anchor=NA)_

**But from the otu table. So I run:**

_ps_out_table = otu_table(ps)
seqs <- getSequences(ps_out_table )_

**And I get this error:**
> Error in getUniques(object, collapse = collapse, silence = silence) : 
>   Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.

**Do you know how to solve it?**

**Comment by AgustinPardo** [comment]
**Hello, I'm trying to do this:**

_seqs <- getSequences(seqtab.nochim)
alignment <- AlignSeqs(DNAStringSet(seqs), anchor=NA)_

**But from the otu table. So I run:**

_ps_out_table = otu_table(ps)
seqs <- getSequences(ps_out_table )_

**And I get this error:**
> Error in getUniques(object, collapse = collapse, silence = silence) : 
>   Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.

**Do you know how to solve it?**

**Comment by benjjneb** [comment]
Please see this issue where this was discussed previously: https://github.com/benjjneb/dada2/issues/88

Especially comments/workflow posted by @giriarteS
