### ISSUE TITLE
Retaining samples with one sequence in dada object

### ISSUE THREAD

**Issue by carlopacioni** [benjjneb/dada2#57]
Currently `dada` stops with an error when a sample contains only one sequence (even when `derep$Quals` has been coerced to a matrix – see issue #56). As mentioned in my pull request (#56), an example where this happens is when NGS is used to detect different strains of pathogens using species (pathogen)-specific primer sets. If some samples (individuals) don’t have a mixed infection, often only one sequence (of the targeted length) is returned when I run `fastqFilter`. Clearly I can add a couple of lines in my script to pass to `dada` only samples that have more than 1 sequence. I understand it makes no sense to try to estimate an error rate from one sequence only, but there might be reasons why one may want to retain (or merge later) a sample with only one sequence in a dada object. An obvious one that comes to mind is that downstream analyses will be starting from the dada object, but the ‘offending’ sample will be left out. In my example this is not desirable because the sequence was (possibly) not an error, but caused by an individual not having a mixed infection. Also, if the offending sample is retained in the dada object it is possible to pass the dada object to `makeSequenceTable` and easily verify whether the strain in the offending sample is present in other samples and/or conduct other analyses. 
Ideally, one would like for `dada` to process the samples issuing a warning that samples x, y…z had only one sequence and no inference was possible, but these were retained in the dada object.

Assuming that the sequence obtained in the samples with n=1 is actually a real sequence, I can see a practical work around, which is to remove from the obtained derep object the samples with n=1, run `dada`, and then re-run `dada` with the full derep object (i.e. containing samples with n=1 sequence) passing to `err` the previously estimated error matrix and setting `selfConsist=FALSE`, but I find.  
Alternatively, I could generate two dada objects, one with the samples with n>1 and properly estimated error rate, and a second with samples with n=1 passing a zero error matrix and then find a way to merge the two dada objects (which I have not yet properly investigated).

I thought to check in to know whether you see a scope to include the change I’m suggesting to `dada` and your opinion on a temporary work around if possible.

Thanks!

**Comment by carlopacioni** [comment]
Sorry, my bad. Just realised that it is indeed possible to create a list of mixed dada_class and derep_class elements and pass this to `makeSequenceTable` from which to start further analyses without the need for all samples to be of one or the other class.

My apolgy, I got ahead of myself.

**Comment by benjjneb** [comment]
Hi Carlo,
I agree dada(...) should deal gracefully with the edge case of 1 sequence. After checking in the fix to your derepFastq issue https://github.com/benjjneb/dada2/pull/56 it appears to be doing so for me now. I.e., when I run

```
foo <- derepFastq(1seq.fq)
bar <- dada(foo, err=tperr1)
```

I'm getting the expected output, a dada-class object with one output sequence. Can you see if the derep fix also fixed this issue for you?

**Comment by carlopacioni** [comment]
Yep! All good. I tried submitting one sample with one sequence only passing `err=tperr1` and a list of samples where one had one sequence only and the rest had multiples (with `err=inflateErr(tperr1,3), errorEstimationFunction=loessErrfun, selfConsist = TRUE`) and it worked just fine! 

I can see that your fix with `drop=FALSE` for #56 is a much better way to go ;-)

Cheers,
carlo
