### ISSUE TITLE
Failed Merger

### ISSUE THREAD

**Issue by as703** [benjjneb/dada2#573]
I've got a large dataset of paired V3 16S reads that are 150bp. I've trimed them marginally (F 140, R 130) and dereplicated them with out issue.

Learning errors seems to go ok 
e.g. "errF <- learnErrors(derepFs, multithread=TRUE, MAX_CONSIST = 25)"

but when I apply the error matrix to the dada command I get the following error:

The supplied error matrix does not extend to maximum observed Quality Scores in derep (41).
  Extending error rates by repeating the last column of the Error Matrix (column 41).
  In selfConsist mode this should converge to the proper error rates, otherwise this may not be what you want.

The command completes anyway but when I try to merge the paired reads, none are completed successfully. 

e.g. 0 paired-reads (in 0 unique pairings) successfully merged out of 1084418 (in 15788 pairings) input.

I've used my script successfully for other projects (but with 250bp V1-2 sequencing) and not had any issues so I'm unclear about where I'm going wrong with this analysis.

If anyone has any suggestions they'd be very gratefully received.

Many thanks in advane.

**Comment by benjjneb** [comment]
How long is the sequenced amplicon expected to be? I'm not familiar with V3 sequencing.
Failure to merge like that is usually due to the reads not overlapping after processing, which would be the case if the sequenced amplicon is 260+ bps.

**Comment by as703** [comment]
Apologies - I meant V4 reads. 515F and 806R. I thought the amplicon length would be about 255bp so would be covered. Perhaps I cut it a bit tight. If I just trimleft by 10 (as per the tutorial) then hopefully 140 each way will be enough.

Many thanks

**Comment by as703** [comment]
Think I'm using the latest version. I ran:

library(devtools)
devtools::install_github("benjjneb/dada2")

The primers have been remoced from the sequences so hopefully will work.

Thank you for your help.

Best wishes.
