### ISSUE TITLE
DADA2 for demultiplexed primer-less PacBio reads

### ISSUE THREAD

**Issue by LisaStinson** [benjjneb/dada2#577]
I'm trying to follow the "DADA2 + PacBio: Fecal Samples" tutorial to process my PacBio data. I have CCS reads in fastq.zip format (a separate file for each sample). These sequences are already demultiplexed with primers and barcodes removed.

The first step of the tutorial is to remove primers. Since my primers are already removed this step yields an empty folder for me. Subsequent steps appear to require the output from this step as their input. I'm not sure how to get around this.

Any ideas for what to do? 

Thanks!

**Comment by benjjneb** [comment]
Just skip the `removePrimers` step. If you've already done that part with other software, you are ready to move on to the `filterAndTrim` step.
