### ISSUE TITLE
 installation failed -non-zero exit status

### ISSUE THREAD

**Issue by yugi1001** [benjjneb/dada2#58]
I am trying to install DADA2 on Rstudio v 0.99.467. I got the following message
" installation of package ‘C:/Users/yugandhar.reddybs/Documents/R/dada2/dada2-master’ had non-zero exit status". I had downloaded the zip file ad unzipped into a folder and specified the path to the dada2-master.

Can someone kindly point out how to solve thsi.

Thanks.

**Comment by benjjneb** [comment]
I recommend using the devtools installation method if it is possible:

```
install.packages("devtools")
library("devtools")
devtools::install_github("benjjneb/dada2")
```

Could you try that method and see if you still get the same error? If not,
could you provide the package version of Rcpp you have installed, and your
R version:

```
packageVersion("Rcpp")
R.version
```

**Comment by yugi1001** [comment]
Thanks for the quick response. I did try that approach initially and got the below message/error
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached

**Comment by yugi1001** [comment]
Rcpp version is ‘0.12.3’
R version 3.2.1

**Comment by yugi1001** [comment]
Rcpp version is ‘0.12.3’
R version 3.2.1

**Comment by benjjneb** [comment]
My first guess is that the path/to/dada2 you've entered is not quite right. When you provide an incorrect path, you get that "installation of package ‘/Users/benj/Desktop/test’ had non-zero exit status" error.

Can you double-check that its unzipped, and that the path is correctly pointing to the dada2-master directory?

**Comment by yugi1001** [comment]
Hi, I think the path is right an it did recognise but then again ran into error. please see below

install.packages("C:/Users/yugandhar.reddybs/Documents/R/dada2/dada2-master", repos = NULL, type = "source", dependencies = c("Depends", "Suggests", "Imports"))
Installing package into ‘C:/Users/yugandhar.reddybs/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
* installing *source* package 'dada2' ...
** libs

*** arch - i386
Warning: running command 'make -f "C:/PROGRA~1/R/R-32~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-32~1.1/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="dada2.dll" OBJECTS="RcppExports.o Rmain.o cluster.o error.o evaluate.o misc.o nwalign_endsfree.o nwalign_vectorized.o pval.o strmap.o taxonomy.o"' had status 127
ERROR: compilation failed for package 'dada2'
* removing 'C:/Users/yugandhar.reddybs/Documents/R/win-library/3.2/dada2'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.1/bin/i386/R" CMD INSTALL -l "C:\Users\yugandhar.reddybs\Documents\R\win-library\3.2" "C:/Users/yugandhar.reddybs/Documents/R/dada2/dada2-master"' had status 1
Warning in install.packages :
  installation of package ‘C:/Users/yugandhar.reddybs/Documents/R/dada2/dada2-master’ had non-zero exit status

**Comment by benjjneb** [comment]
Have you installed Rtools?

Unfortunately right now the package is only available as source, which means it must be compiled on your machine. On windows, that means that you need to have downloaded and installed the Rtools toolchain (unless you're installing each piece yourself). You can get Rtools here: https://cran.r-project.org/bin/windows/Rtools/

**Comment by yugi1001** [comment]
No, I do not have Rtools and Rstudio cannot find the package either. my R version is 3.2.1

**Comment by benjjneb** [comment]
Rtools is not a package, it is a set of programs needed by R to compile packages from source. To install Rtools you need to go to this website: https://cran.r-project.org/bin/windows/Rtools/

Install the latest version (Rtools33.exe) and then you should be able to compile the package (you'll also need to restart Rstudio after installing Rtools).

**Comment by aweaver5** [comment]
Hi I'm having the same problem while trying to install the same package dada2. I have a mac computer, so do I still need to install Rtools to be able to install the package? How did you get it to install?

**Comment by nagasridhar** [comment]
Can you check if you have Xcode installed?

You can check by running this command on the terminal window,

xcode-select -p

If it is not installed, you can install it by entering the following command on the terminal,

xcode-select --install

Also, are you trying to install DADA2 through Rstudio? Or what is the route you are following to install?

**Comment by aweaver5** [comment]
I didn't have xcode installed but I just installed it an hour ago an I am still getting the same errors. I can't get dada2 from this code:
 biocLite("devtools")
library("devtools")
devtools::install_github("benjjneb/dada2")

or from this code:
install.packages("path/to/dada2",
                 repos = NULL,
                 type = "source",
                 dependencies = c("Depends", "Suggests","Imports"))

Yes I am using Rstudio

**Comment by nagasridhar** [comment]
What is the error you get when you run the installation? 
What is the output of the below command:

`packageVersion("Rcpp")
R.version`

**Comment by aweaver5** [comment]
When I try to install it using the github location I get an error that says 
installing to /Library/Frameworks/R.framework/Versions/3.4/Resources/library/dada2/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Warning: package ‘Rcpp’ was built under R version 3.4.3
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘GenomeInfoDbData’
ERROR: lazy loading failed for package ‘dada2’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/dada2’
Installation failed: Command failed (1)

When I try to use the downloaded file I get
Warning: invalid package ‘/Users/Monique/Documents/R_files/dada2’
Error: ERROR: no packages specified
Warning in install.packages :
  installation of package ‘/Users/Monique/Documents/R_files/dada2’ had non-zero exit status

and when I ran the command 
packageVersion("Rcpp") R.version, I got the output ‘0.12.15’


I think the second error message is probably because of the path. I have it going to the outermost directory, but I'm not sure if I'm supposed to go into another folder. I'm not sure why the first code that downloads it directly from github isn't working.

**Comment by nagasridhar** [comment]
> 

> ‘/Users/Monique/Documents/R_files/dada2’

Is this path pointing to the zip file you downloaded or are you pointing to the folder where the dada2 zip file is located? If you are not pointing to the zip file, can you try pointing to the zip file and see if that works.

**Comment by aweaver5** [comment]
That path is pointing to the zip file. The file is the dada2, the one I downloaded.

**Comment by nagasridhar** [comment]
Along with installing xcode, it seems xcode command line tools is also needed for the installation. 

Also, what is the R version you are running,

`R.version`
