### ISSUE TITLE
Formatting custom databases

### ISSUE THREAD

**Issue by Sebastian-Mynott** [benjjneb/dada2#581]
Thank you very much for dada2! It is my new favourite method for working with MiSeq reads!

I do environmental metabarcoding so I need to create custom databases for community analysis. Would you have any tips/instructions/tutorial on how to download and format custom databases within R?

Many thanks!

**Comment by benjjneb** [comment]
Glad it's helpful for you!

Have you seen the [formatting custom databases](https://benjjneb.github.io/dada2/training.html#formatting-custom-databases) entry on our web site?

Does that answer your question? Or is it something not covered there?

**Comment by Sebastian-Mynott** [comment]
Yes, I've seen that entry. On that same page you have links to collections for SILVA and others. I'm looking for instructions on formatting data from other sources, such as NCBI and BOLD, for example.
