### ISSUE TITLE
Eukaryota assignment to 16s data

### ISSUE THREAD

**Issue by Philippa36** [benjjneb/dada2#582]
Hi,

For one of our sequencing runs, all of the taxa assignments are coming up as eukaryota. It's 16s data, V4 region.

Please could you help?

Thank you

**Comment by Philippa36** [comment]
Thank you,  I just tried that now, I'm getting an error:
 unused argument (RC = TRUE)

**Comment by benjjneb** [comment]
If you use `?assignTaxonomy` you should get help documentation that includes all the arguments for that function (or any other R function). The correct name of the argument is `tryRC`.
