### ISSUE TITLE
pseudo pooling not running

### ISSUE THREAD

**Issue by rebelwebster** [benjjneb/dada2#583]
Hi 

When I try to run the dada command with `pool="pseudo"`, it throws an error saying it's not interpretable as a logical variable. It's not a logical variable but this is how it is outlined to use in the tutorial...

Thank you in advance

Rose

**Comment by benjjneb** [comment]
Hi Rose,
What version of the R package are you running? `packageVersion("dada2")`

**Comment by benjjneb** [comment]
Feel free to re-open as needed, but I think that this error will go away if you update to version 1.8 or later of the package.
