### ISSUE TITLE
about removing primer on the right end of sequences, since they are not pair end reads

### ISSUE THREAD

**Issue by ZZZZZsd** [benjjneb/dada2#584]
After sequencing, the company had already merged the pair end reads and they send me the fastq file according to sample name, so I only have one fastq file for each sample, not pair end reads.

Then I find the sequences contains barcode (12bp) and both primers  20bp left and 22bp right...
How can I remove primers on the right end...I know filterAndTrim , trimLeft can remove primers on the left, is there something like trimRight?
I see the truncLen argument, but sequences vary from 250bp to 270bp, it is difficult to set a value to truncate the right primer....
since I only have one fastq file , not pair end reads......

**Comment by ZZZZZsd** [comment]
@benjjneb yes, it works , thank you!
And another problem.....

![default](https://user-images.githubusercontent.com/44023677/46785950-f2945b00-cd65-11e8-8247-004cc4ee8902.png)

the learnerrors plot is not very well when quality score is high.....from the plot I can see  a small arc at right end ...
Am I too serious? I have already make nbase from 1e8 to 1e9,  try 1e10?

errF <- learnErrors(filtFs, multithread=4,nbases = 1e9,randomize = T,MAX_CONSIST = 25)

**Comment by benjjneb** [comment]
Does this data have binned quality scores?

Yeah, I am not loving that dip at the end of each. Here is a workaround, that will set each value to the Q40 value if it is below it.

```
errF <- getErrors(errF, detailed=FALSE)
errF.qmax <- matrix(errF[,ncol(errF)], nrow=nrow(errF), ncol=ncol(errF))
errF2 <- pmax(errF, errF.qmax)
```

You can check it did as expected with `plotErrors(errF2)`.

**Comment by ZZZZZsd** [comment]
emmmmmmm
@benjjneb 
Thats code I use.. the files input are all fastq with quality score.

```
out <- filterAndTrim(fnFs, filtFs, trimLeft=32,maxLen=299,trimRight = 22,
              maxN=0, maxEE=2, truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=F) 
errF1 <- learnErrors(filtFs[1:80], multithread=4,nbases = 2e8,randomize = T,MAX_CONSIST = 15)
plotErrors(errF1, nominalQ=TRUE)
```
And  I think it is more reasonable that higher quality score is of lower error rate.

Thank you for answering my questions.....
