### ISSUE TITLE
how large a sample size to determine error rates | does sample matrix matter?

### ISSUE THREAD

**Issue by ympiceno** [benjjneb/dada2#585]
Two questions
1) If there are samples from multiple projects on one sequencing run (e.g., one Illumina NextSeq run with ~ 500 samples), is it advised to process them all together to get the best understanding of error in that seq run or can they be processed as separate projects (each run through DADA2 separately), even if one of those projects has only, say, 30 samples and another has 300 samples?

2) If in one seq run there are samples from saliva and others from stool, is there any reason to/not to process them as a batch through DADA2 (i.e., should samples of one matrix type be processed by themselves)?

Thank you!

**Comment by benjjneb** [comment]
The DADA2 method is modeling and removing the errors that arise from PCR and sequencing. Thus, if projects used the same PCR + sequencing protocols, you are OK to process them in one workflow, and may even be advisable if one small project has too few reads to estimate the error rates well within it alone. 

This also means that the sample matrix isn't a concern for DADA2, as it is only removing the errors that arise after DNA extraction, at which point the sample matrix has been removed from the samples.

**Comment by ympiceno** [comment]
Many thanks!
