### ISSUE TITLE
Filtering Consistency

### ISSUE THREAD

**Issue by adityabandla** [benjjneb/dada2#587]
We sequenced 131 samples twice, for more depth. Is it ok to filter these two datasets using different maxEE, but the same truncLen?

The second run had approx. 2M more reads (10M total) compared to the first one. Using pooling this is taking far too long, hence would like to know if I can filter more stringently

**Comment by benjjneb** [comment]
Yes that is fine, and a good way to reduce computation time.

**Comment by adityabandla** [comment]
Thanks Ben!
