### ISSUE TITLE
Corrupted FASTQ Files after filterAndTrim

### ISSUE THREAD

**Issue by ktmbiome** [benjjneb/dada2#588]
Hi,

We have some samples that were processed on the MiSeq for ITS2. They look normal before filterAndTrim, but when brought through filterAndTrim, the files become corrupted (they are primarily comprised of wingdings and non-sense characters that are unusable in the learnErrors function). filterAndTrim doesn't produce any errors while it's running and I have tried turning multithreading off to see if that would improve things (I saw a potentially-similar thread elsewhere  that suggested multithreading may be the culprit).

Any thoughts would be appreciated, and let me know if additional information would be helpful.

Best,
--Katie

**Comment by benjjneb** [comment]
`compress=TRUE` by default, which means the files output are gzipped, hence the wingdings when viewing it as text. `filterAndTrim(..., compress=FALSE)` will give uncompressed fastq files if that is what you prefer.

**Comment by ktmbiome** [comment]
Ah, of course! For the compressed 16S/NextSeq files, the file names are followed by a .gz and are still readable through vim so I thought that would still be the case with the ITS2/MiSeq data.


Many thanks!

--Katie

________________________________

**Comment by brndnsf** [comment]
I've been working with these files and can confirm that setting compress to FALSE fixed the problem. I assume this is because it's been a while since we've updated cutadapt (we're on v1.11). Thanks for the info.
