### ISSUE TITLE
Combine/Align short read to long read datasets of the same samples

### ISSUE THREAD

**Issue by FFoQS90** [benjjneb/dada2#591]
Hello,

I am working on a dataset with the 16S of the same samples sequenced with Illumina MiSeq V3-V4 and with Pacbio SMRT Sequel (full-length) and both processed with dada2. Since the sequencing depth of the Pacbio dataset is very low I was wondering whether it would be feasible to align the Illumina reads to the pacbio reads essentially combining the two datasets. Or in other words use the Pacbio dataset as kind of a database to classify the Illumina reads.
That way I could increase sequencing depth of the long reads or improve classification of the shorter reads. 

I am aware that the shorter reads would most likely fit to multiple longer reads but it should work for cases for which I have a single 100% identity hit right? 

I would be very happy to hear opinions of other people about this. Do you think this is feasible? Or are there any issues with this that I am not aware of?

**Comment by benjjneb** [comment]
It's an interesting idea. The PacBio reads are sort of a reference for the Illumina reads generated from the data itself. One thing I would potentially be worried about is that if the PacBio data is really shallow, it won't have all the variants captured in the Illumina data, and you could end up mapping short reads to the wrong long-read reference. That will be minimized but not eliminated by the 100% identity requirement...

I think its worth trying!

**Comment by FFoQS90** [comment]
Great, thank you very much for the input. You make a good point that is definitely a concern. I will keep it in mind and give it a try!
