### ISSUE TITLE
relax parameters for fungal ITS

### ISSUE THREAD

**Issue by sghignone** [benjjneb/dada2#592]
Hello!
I'm sorry if the topic has already been considered, an probably I am still too attached to former Qiime work flow. Applying the  ITS DADA2 workflow on my sample (fungal ITS 2) I get, for eample, 5 sequences that match the same entry using `assignTaxonomy` and the UNITE ITS database (release 7.2). 
This is the MView output of the alignment of those sequences:

![image](https://user-images.githubusercontent.com/7242651/47343662-ee8e0480-d6a6-11e8-8dd1-1a027739ad60.png)

I am wondering which parameters I should relax (meaning lowering the stringency) to get those sequences considered as the same ASV. In other words, how can I get into the same ASV sequences differing at least 3% ?
Thanks

**Comment by benjjneb** [comment]
> I am wondering which parameters I should relax (meaning lowering the stringency) to get those sequences considered as the same ASV. In other words, how can I get into the same ASV sequences differing at least 3% ?

The short answer is that you don't. ASVs represent exact sequences, they do not represent clustered groups of sequences.

The longer answer is that if what you want to work with is OTUs clustered at some similarity threshold, you can use the ASVs generated by DADA2 as an error-correction step, and then cluster the resulting ASVs at the desired threshold. That would require another tool though - DADA2 is an ASV method not an OTU method. In R, you should consider the DECIPHER package, specifically the IdClusters command implemented in that package.
