### ISSUE TITLE
error with reverse reads

### ISSUE THREAD

**Issue by amitpande74** [benjjneb/dada2#595]
Hi,
I am getting an error when I type this
> plotQualityProfile(fnRs[1:2])
Error: internal: buf != <newline>
dada 2 version is 1.9.3
Can someone help please

**Comment by benjjneb** [comment]
What is the output from the following?

```
fnRs[1:2]
file.exists(fnRs[1:2])
```

**Comment by amitpande74** [comment]
> fnRs[1:2]
[1] "/home/moloy/dada2/SAE1903_demux_R2.fq" "/home/moloy/dada2/SAE2000_demux_R2.fq"
> file.exists(fnRs[1:2])
[1] TRUE TRUE

**Comment by amitpande74** [comment]
Now it shows me this error:
Error: internal: buf != <newline>
In addition: Warning message:
In switch(deparse(x[[1L]])[1L], `(` = "(", "call") :
closing unused connection 3 (/home/moloy/dada2/SAE1903_primer_trimmed_R2.fq)

**Comment by amitpande74** [comment]
Hi Ben,
I found this string for the error I am having from the forum and ran these functions to see whether I can understand the output
https://github.com/benjjneb/dada2/issues/497

> fn <- "/home/moloy/dada2/SAE1903_primer_trimmed_R2.fq"
> foo <- readLines(fn)
> seqlens <- sapply(foo[seq(2,length(foo),4)], nchar)
> quallens <- sapply(foo[seq(4,length(foo),4)], nchar)
> table(seqlens); table(quallens)
seqlens
    0   268   269   270   271   272   273   274   275   276   277   278   279
21642     7    83    13    90  7116 11902 13347 12361  7150   344  4336 80395
  280
82735
quallens
    0   268   269   270   271   272   273   274   275   276   277   278   279
18190     7    97    14    94  7524 12802 14267 13054  7662   344  4336 80395
  280
82735
> fn <- "/home/moloy/dada2/SAE1903_primer_trimmed_R1.fq"
> foo <- readLines(fn)
> seqlens <- sapply(foo[seq(2,length(foo),4)], nchar)
> quallens <- sapply(foo[seq(4,length(foo),4)], nchar)
> table(seqlens); table(quallens)
seqlens
   262    264    266    267    268    269    270    271    272    273    274
     1      1      1      1     12     43    162    714  99722 140313      2
   275    276    277
     4    239    306
quallens
   262    264    266    267    268    269    270    271    272    273    274
     1      1      1      1     12     43    162    714  99722 140313      2
   275    276    277
     4    239    306

When I ran this for the reverse_R2 file, it says:
> which(seqlens != quallens)
                                                                            
   188    223    303    325    327    402    746   1016   1027   1074   1094
                                                                            
  1272   1297   1371   1390   1410   1430   1436   1485   1486   1574   1594
                                                                            
  1603   1781   1833   1850   1903   2017   2104   2143   2235   2284   2823
                                                                            
  3014   3016   3060   3062   3074   3077   3126   3127   3149   3218   3224
                                                                            
  3274   3324   3409   3598   3614   3706   3785   3794   3836   3840   3847
                                                                            
  3955   4264   4292   4294   4374   4432   4536   4543   4578   4614   4664
                                                                            
  4674   4731   4840   4896   4902   4919   4928   5004   5020   5028   5192
                                                                            
  5292   5297   5323   5327   5344   5403   5454   5456   5502   5538   5558
                                                                            
  5704   5735   5739   5741   5771   5807   5809   5877   5881   5978   6037
                                                                            
  6134   6222   6252   6261   6270   6312   6351   6384   6410   6412   6460
                                                                            
  6465   6486   6561   6593   6623   6679   6682   6724   6760   6824   6838
                                                                            
  6854   6996   7047   7080   7082   7113   7235   7254   7258   7283   7335
                                                                            
  7357   7376   7470   7498   7543   7610   7651   7688   7700   7714   7776
                                                                            
  7795   7809   7953   8563   8676   8780   8789   8834   8851   8869   8911
                                                                            
  8960   9015   9155   9160   9199   9226   9228   9229   9240   9269   9335
                                                                            
  9346   9381   9435   9465   9473   9493   9520   9601   9623   9680   9693
                                                                            
  9747   9765   9790   9811   9858   9873   9883   9988  10008  10037  10064
                                                                            
 10147  10181  10199  10230  10264  10266  10299  10402  10407  10435  10453
                                                                            
 10497  10520  10595  10607  10609  10612  10717  10814  10868  11010  11054
                                                                            
 11086  11106  11154  11192  11305  11346  11480  11497  11506  11530  11542
                                                                            
 11620  11642  11643  11664  11665  11717  11754  11767  11789  11834  11871
                                                                            
 11885  11887  11914  11949  12004  12048  12076  12490  12684  12810  12904
                                                                            
 12930  12951  12954  12971  12997  13061  13096  13118  13157  13179  13216
                                                                            
 13240  13250  13412  13428  13491  13507  13518  13656  13716  13771  13837
                                                                            
 13902  13939  13969  14040  14101  14159  14168  14321  14335  14398  14472
                                                                            
 14493  14510  14590  14598  14644  14719  14748  14816  14821  14828  14835
                                                                            
 14950  14968  15014  15047  15048  15076  15106  15108  15136  15145  15153
                                                                            
 15167  15169  15172  15178  15202  15206  15246  15336  15343  15390  15420
                                                                            
 15445  15466  15488  15496  15503  15506  15541  15593  15595  15626  15638
                                                                            
 15648  15655  15660  15668  15672  15696  15780  15865  15918  15958  15983
                                                                            
 16076  16119  16237  16274  16438  16452  16494  16495  16497  16535  16536
                                                                            
 16650  16660  16706  16769  16883  16887  16911  16964  16990  17010  17243
                                                                            
 17254  17572  17710  17826  17860  17863  17871  17915  17927  17945  17951
                                                                            
 18032  18046  18103  18142  18302  18334  18387  18428  18477  18510  18608
                                                                            
 18666  18675  18714  18717  18724  18767  18825  18855  18899  18919  18939
                                                                            
 18990  19042  19081  19083  19096  19115  19139  19167  19255  19265  19275
                                                                            
 19296  19360  19373  19382  19386  19394  19410  19417  19430  19433  19451
                                                                            
 19489  19514  19539  19551  19571  19596  19627  19638  19648  19722  19757
                                                                            
 19776  19781  19808  19846  19866  19872  19875  19902  19913  19945  19946
                                                                            
 19955  19967  19988  20232  20243  20280  20347  20351  20449  20479  20540
                                                                            
 20569  20582  20632  20698  20763  20810  20844  20850  20916  20944  20992
                                                                            
 21002  21100  21128  21156  21250  21281  21289  21307  21401  21411  21434
                                                                            
 21436  21560  21574  21623  21725  21750  21791  21799  21810  21848  21870
                                                                            
 21913  21932  21963  21971  21991  21992  22058  22067  22109  22129  22136
                                                                            
 22179  22195  22329  22334  22372  22380  22401  22429  22460  22485  22506
                                                                            
 22526  22539  22560  22572  22591  22599  22646  22675  22681  22718  22730
                                                                            
 22753  22772  22844  22862  22866  22875  22948  22953  22980  23218  23445
                                                                            
 23696  23800  23857  23893  23925  23939  23958  24052  24055  24071  24116
                                                                            
 24152  24153  24160  24206  24207  24232  24403  24468  24485  24519  24677
                                                                            
 24745  24753  24794  24807  24862  24905  24947  24957  24960  24973  24979
                                                                            
 24987  25025  25043  25047  25155  25156  25170  25194  25210  25233  25252
                                                                            
 25254  25300  25353  25367  25369  25375  25395  25412  25472  25537  25557
                                                                            
 25574  25587  25588  25596  25647  25768  25818  25842  25861  25890  25901
                                                                            
 25907  25912  25983  25996  26044  26122  26236  26260  26295  26304  26392
                                                                            
 26398  26421  26437  26444  26445  26472  26476  26524  26536  26543  26648
                                                                            
 26658  26685  26789  26799  26820  26892  26921  26930  26951  26990  26995
                                                                            
 27075  27083  27114  27208  27214  27222  27237  27260  27316  27330  27358
                                                                            
 27361  27476  27546  27600  27663  27670  27674  27680  27761  27798  27805
                                                                            
 27854  27929  27941  27952  27986  28008  28045  28058  28094  28101  28130
                                                                            
 28253  28273  28291  28309  28318  28349  28407  28421  28719  28840  28927
                                                                            
 28955  29043  29198  29373  29394  29427  29468  29503  29510  29537  29548
                                                                            
 29558  29589  29659  29670  29700  29729  29854  29881  30019  30022  30030
                                                                            
 30099  30104  30170  30182  30296  30326  30342  30373  30483  30587  30602
                                                                            
 30615  30625  30630  30657  30710  30723  30815  30842  30881  30892  30909
                                                                            
 30917  30943  30999  31058  31067  31108  31133  31204  31208  31213  31224
                                                                            
 31268  31319  31354  31360  31396  31408  31434  31440  31453  31464  31481
                                                                            
 31520  31559  31583  31593  31644  31664  31691  31751  31760  31767  31770
                                                                            
 31794  31810  31822  31827  31869  31891  31956  31991  32017  32172  32331
                                                                            
 32357  32365  32367  32388  32413  32466  32490  32511  32555  32575  32623
                                                                            
 32624  32647  32681  32686  32704  32731  32782  32785  32786  32820  32832
                                                                            
 32840  32885  32918  33042  33079  33107  33116  33123  33151  33184  33292
                                                                            
 33316  33362  33366  33369  33374  33376  33459  33510  33511  33513  33544
                                                                            
 33580  33628  33714  33797  33969  34013  34033  34075  34095  34112  34142
                                                                            
 34269  34350  34379  34384  34492  34507  34702  34704  34757  34793  34910
                                                                            
 35161  35268  35423  35517  35550  35599  35613  35654  35668  35745  35765
                                                                            
 35839  35845  35851  35929  35946  36137  36142  36165  36224  36254  36265
                                                                            
 36280  36297  36311  36344  36345  36373  36400  36429  36443  36502  36547
                                                                            
 36572  36587  36603  36691  36716  36723  36749  36900  36907  36913  36940
                                                                            
 37007  37200  37258  37285  37399  37402  37440  37500  37561  37574  37576
                                                                            
 37585  37591  37623  37630  37638  37640  37698  37789  37835  37857  37891
                                                                            
 37949  38014  38032  38094  38100  38169  38170  38197  38201  38239  38240
                                                                            
 38257  38268  38355  38378  38477  38505  38524  38595  38622  38663  38761
                                                                            
 38984  39019  39050  39051  39060  39068  39094  39109  39212  39224  39225
                                                                            
 39267  39342  39357  39370  39388  39456  39460  39462  39467  39509  39527
                                                                            
 39529  39532  39540  39543  39565  39574  39588  39597  39694  39717  39726
                                                                            
 39738  39759  39766  39771  39798  39856  39917  40001  40040  40075  40095
                                                                            
 40118  40183  40207  40226  40345  40354  40437  40449  40452  40561  40633
                                                                            
 40771  40983  41045  41100  41112  41115  41137  41158  41177  41223  41230
                                                                            
 41300  41372  41405  41413  41429  41433  41447  41465  41505  41553  41634
                                                                            
 41636  41685  41731  41798  41893  41897  41931  41964  41969  42019  42033
                                                                            
 42049  42075  42104  42214  42215  42250  42278  42281  42342  42369  42398
                                                                            
 42419  42440  42478  42492  42514  42523  42550  42666  42727  42762  42818
                                                                            
 42837  42849  42866  42868  42875  42890  42911  42939  43026  43073  43122
                                                                            
 43132  43153  43154  43209  43224  43273  43304  43566  43652  43687  43689
                                                                            
 43798  43805  43806  43812  43820  43839  43896  43943  43971  43975  44043
                                                                            
 44057  44088  44133  44176  44190  44193  44237  44245  44269  44272  44276
                                                                            
 44283  44287  44418  44487  44534  44565  44634  44646  44672  44693  44750
                                                                            
 44764  44783  44785  44826  44889  44947  44959  44995  45020  45105  45205
                                                                            
 45261  45264  45281  45314  45330  45355  45401  45425  45513  45516  45517
                                                                            
 45537  45558  45613  45615  45658  45700  45789  46156  46192  46502  46670
                                                                            
 46715  46723  46814  46906  46926  46945  46955  46964  46985  47051  47093
                                                                            
 47094  47104  47196  47211  47212  47217  47262  47295  47413  47453  47485
                                                                            
 47511  47512  47621  47630  47801  47848  47864  47913  48003  48081  48093
                                                                            
 48097  48128  48233  48295  48564  48621  48664  48716  48755  48771  48804
                                                                            
 48839  48860  48868  48885  48891  48904  48935  48942  48977  49051  49056
                                                                            
 49063  49145  49195  49198  49221  49225  49293  49325  49348  49352  49353
                                                                            
 49370  49399  49409  49441  49458  49489  49502  49514  49592  49639  49688
                                                                            
 49710  49714  49733  49739  49748  49760  49774  49832  49833  49872  49885
                                                                            
 49922  49923  49978  49983  50045  50066  50087  50098  50136  50166  50169
                                                                            
 50170  50193  50264  50307  50394  50530  50597  50599  50614  50689  50742
                                                                            
 50831  50909  50966  50993  51030  51237  51249  51250  51313  51332  51344
                                                                            
 51351  51357  51429  51437  51481  51495  51554  51641  51689  51699  51702
                                                                            
 51716  51720  51776  51868  51953  51967  51996  52058  52133  52280  52369
                                                                            
 52370  52389  52848  52995  53151  53153  53167  53202  53223  53253  53291
                                                                            
 53323  53357  53380  53411  53655  53663  53715  53767  53877  53882  53913
                                                                            
 53932  53948  53971  53993  54042  54052  54198  54226  54267  54293  54328
                                                                            
 54349  54362  54435  54545  54548  54594  54737  54746  54822  54901  54910
                                                                            
 54979  55055  55187  55227  55233  55260  55290  55310  55317  55340  55374
                                                                            
 55390  55422  55424  55431  55477  55539  55574  55591  55595  55623  55657
                                                                            
 55673  55692  55734  55747  55775  55809  55828  55838  55844  55865  55873
                                                                            
 55875  55904  55965  55981  56001  56008  56026  56126  56137  56149  56152
                                                                            
 56233  56278  56283  56328  56333  56395  56415  56453  56467  56531  56543
                                                                            
 56639  56722  56738  56740  56758  56776  56842  56866  56882  57045  57048
                                                                            
 57116  57157  57161  57256  57272  57280  57402  57414  57425  57483  57563
                                                                            
 57602  57634  57722  57731  58013  58017  58290  58383  58391  58560  58625
                                                                            
 58678  58755  58766  58793  58804  58841  58857  58859  58916  58919  58934
                                                                            
 58986  58992  59045  59085  59107  59115  59122  59206  59366  59370  59452
                                                                            
 59574  59593  59633  59665  59704  59735  59807  59822  59834  59920  59935
                                                                            
 59995  60051  60065  60076  60100  60116  60145  60169  60275  60324  60345
                                                                            
 60378  60403  60574  60653  60658  60736  60765  60780  60800  60841  60844
                                                                            
 60869  60886  60903  60976  61023  61036  61067  61135  61144  61178  61247
                                                                            
 61280  61434  61495  61520  61600  61607  61637  61815  61841  61884  61901
                                                                            
 61930  61984  62028  62057  62065  62104  62123  62169  62189  62211  62293
                                                                            
 62353  62366  62442  62446  62450  62493  62578  62690  62702  62764  62802
                                                                            
 62822  62826  62827  62845  62907  62926  62939  62986  62993  63043  63050
                                                                            
 63055  63095  63166  63213  63389  63404  63671  63677  63687  63700  64000
                                                                            
 64204  64288  64307  64356  64414  64426  64435  64483  64530  64566  64591
                                                                            
 64659  64684  64688  64797  64896  64954  64977  64989  64992  65014  65015
                                                                            
 65045  65065  65069  65093  65118  65234  65269  65328  65331  65354  65361
                                                                            
 65367  65392  65454  65465  65489  65520  65550  65573  65578  65661  65671
                                                                            
 65696  65739  65923  66021  66068  66084  66088  66132  66137  66161  66185
                                                                            
 66205  66235  66281  66310  66326  66332  66377  66439  66454  66474  66528
                                                                            
 66649  66663  66723  66739  66762  66775  66778  66785  66801  66817  67019
                                                                            
 67035  67049  67102  67116  67133  67141  67199  67247  67250  67260  67282
                                                                            
 67322  67381  67416  67465  67550  67567  67599  67642  67645  67651  67675
                                                                            
 67690  67702  67726  67743  67822  67868  67886  67894  67895  67913  67940
                                                                            
 67964  67985  68003  68023  68062  68091  68492  68570  68605  68701  68756
                                                                            
 68880  68910  68938  68970  68973  69093  69145  69181  69199  69219  69267
                                                                            
 69276  69309  69374  69395  69480  69525  69546  69557  69559  69586  69588
                                                                            
 69592  69726  69743  69779  69834  69892  69902  69934  69973  70061  70111
                                                                            
 70125  70167  70235  70252  70306  70323  70329  70344  70357  70368  70375
                                                                            
 70379  70469  70492  70493  70542  70572  70586  70732  70757  70793  70816
                                                                            
 70838  70911  70912  70940  70998  71015  71052  71102  71255  71289  71306
                                                                            
 71308  71328  71401  71414  71471  71537  71542  71551  71614  71647  71649
                                                                            
 71653  71722  71752  71762  71770  71795  71861  71884  71889  71919  71955
                                                                            
 71983  72015  72028  72216  72257  72316  72349  72354  72374  72397  72428
                                                                            
 72443  72457  72461  72501  72561  72597  72637  72685  72686  72702  72741
                                                                            
 72754  72772  72810  72819  72848  72962  72963  73050  73079  73086  73163
                                                                            
 73215  73216  73245  73314  73346  73367  73461  73519  73550  73586  73780
                                                                            
 73962  74266  74275  74312  74323  74371  74390  74402  74508  74590  74606
                                                                            
 74741  74753  74759  74877  74916  74953  75033  75037  75058  75113  75125
                                                                            
 75255  75515  75519  75694  75696  75706  75749  75767  75917  75927  75988
                                                                            
 76015  76064  76091  76163  76183  76288  76312  76318  76329  76362  76387
                                                                            
 76388  76459  76506  76535  76537  76584  76603  76628  76665  76750  76786
                                                                            
 76804  76854  76885  76961  77029  77121  77155  77164  77181  77202  77249
                                                                            
 77258  77299  77346  77368  77374  77388  77428  77476  77497  77512  77523
                                                                            
 77545  77550  77556  77566  77631  77690  77793  77794  77803  77819  77870
                                                                            
 77915  77938  77983  78021  78067  78068  78090  78097  78134  78162  78203
                                                                            
 78205  78330  78366  78429  78458  78505  78513  78546  78600  78631  78778
                                                                            
 78831  78845  78866  78886  78928  79139  79238  79270  79303  79326  79362
                                                                            
 79385  79407  79437  79471  79481  79510  79559  79578  79664  79666  79672
                                                                            
 79762  79784  79794  79795  79847  79849  79854  80037  80038  80049  80065
                                                                            
 80077  80111  80140  80151  80182  80205  80255  80289  80307  80313  80323
                                                                            
 80340  80409  80459  80477  80566  80597  80631  80644  80714  80750  80829
                                                                            
 80833  80866  80896  80951  80956  80978  81009  81026  81059  81116  81148
                                                                            
 81151  81152  81170  81183  81199  81202  81206  81248  81267  81280  81313
                                                                            
 81340  81381  81383  81616  81647  81684  81709  81766  81815  81843  81878
                                                                            
 81894  81897  81942  81972  81980  81989  82007  82054  82072  82103  82130
                                                                            
 82133  82136  82139  82151  82152  82168  82200  82206  82223  82307  82313
                                                                            
 82374  82396  82406  82448  82478  82510  82542  82546  82627  82661  82698
                                                                            
 82740  82825  82890  82923  82934  83133  83369  83555  83567  83571  83580
                                                                            
 83612  83677  83713  83719  83732  83736  83750  83788  83804  83817  83916
                                                                            
 83988  84157  84184  84234  84292  84458  84484  84513  84578  84580  84598
                                                                            
 84622  84671  84737  84752  84760  84762  84800  84801  84971  85078  85088
                                                                            
 85227  85287  85356  85370  85435  85453  85485  85495  85500  85501  85539
                                                                            
 85597  85598  85611  85622  85625  85635  85691  85712  85722  85725  85805
                                                                            
 85854  85856  85906  85920  86027  86107  86143  86149  86203  86246  86254
                                                                            
 86317  86318  86340  86389  86567  86688  86911  87172  87228  87257  87315
                                                                            
 87369  87467  87493  87530  87578  87613  87616  87641  87763  87790  87809
                                                                            
 87814  87885  87927  87958  87990  88029  88032  88042  88055  88100  88115
                                                                            
 88186  88204  88249  88260  88322  88324  88349  88394  88414  88442  88472
                                                                            
 88610  88631  88661  88772  88850  88944  89019  89046  89061  89081  89264
                                                                            
 89281  89296  89318  89319  89338  89391  89400  89420  89425  89454  89531
                                                                            
 89714  89729  89782  89813  89841  89849  89886  89923  89933  89949  90019
                                                                            
 90113  90176  90193  90219  90231  90276  90325  90375  90695  90725  90735
                                                                            
 90742  90782  90798  90838  90865  90866  90872  90874  90992  91001  91014
                                                                            
 91033  91067  91132  91195  91223  91233  91250  91264  91281  91358  91472
                                                                            
 91511  91512  91533  91601  91613  91695  91718  91719  91775  91873  91967
                                                                            
 92211  92293  92552  92553  92610  92763  92802  92812  92861  92893  92903
                                                                            
 92918  92921  92958  93024  93072  93088  93169  93182  93212  93264  93460
                                                                            
 93469  93483  93520  93577  93649  93698  93700  93760  93802  93809  93852
                                                                            
 93905  93917  93920  93967  93972  93998  94005  94121  94132  94168  94172
                                                                            
 94208  94220  94226  94234  94244  94255  94357  94371  94376  94377  94409
                                                                            
 94410  94418  94460  94499  94525  94566  94623  94646  94661  94732  94738
                                                                            
 94782  94905  94947  95047  95113  95126  95182  95246  95279  95285  95310
                                                                            
 95329  95347  95413  95428  95449  95457  95478  95485  95500  95529  95536
                                                                            
 95583  95603  95627  95720  95785  95815  95851  95859  95922  95928  95932
                                                                            
 95950  96008  96075  96136  96166  96168  96172  96173  96201  96222  96259
                                                                            
 96273  96286  96344  96367  96395  96399  96451  96486  96587  96602  96632
                                                                            
 96640  96648  96769  96864  96878  96892  96895  96940  97257  97262  97368
                                                                            
 97381  97465  97484  97521  97550  97565  97600  97635  97674  97681  97697
                                                                            
 97813  97816  97849  97875  97936  98116  98182  98255  98293  98314  98408
                                                                            
 98707  98723  98837  98909  98940  98946  98991  99073  99112  99170  99264
                                                                            
 99317  99331  99456  99861  99891  99950  99974  99983 100115 100185 100204
                                                                            
100279 100327 100362 100392 100411 100429 100458 100476 100506 100523 100536
                                                                            
100574 100579 100652 100663 100691 100731 100736 100770 100802 100808 100857
                                                                            
101016 101059 101091 101160 101274 101290 101315 101318 101424 101428 101436
                                                                            
101486 101555 101566 101574 101580 101600 101619 101621 101638 101686 101705
                                                                            
101777 101809 101810 101817 101859 101869 101900 101940 101943 102019 102020
                                                                            
102091 102129 102139 102159 102196 102211 102239 102266 102269 102317 102330
                                                                            
102375 102469 102720 102746 102752 102753 102787 102805 102840 102846 102858
                                                                            
102867 102905 102921 102967 102992 103046 103060 103061 103078 103140 103144
                                                                            
103148 103199 103222 103247 103253 103287 103300 103314 103375 103377 103429
                                                                            
103465 103470 103480 103509 103525 103576 103582 103631 103640 103644 103710
                                                                            
103882 104022 104108 104139 104147 104266 104274 104321 104336 104377 104491
                                                                            
104499 104530 104542 104556 104701 104761 104784 104853 105004 105008 105073
                                                                            
105149 105169 105261 105303 105320 105434 105453 105518 105538 105572 105615
                                                                            
105629 105678 105680 105780 105852 105963 106102 106165 106168 106176 106298
                                                                            
106454 106496 106499 106502 106520 106600 106689 106719 106726 106727 106819
                                                                            
106838 106952 106977 107009 107044 107074 107078 107136 107154 107181 107237
                                                                            
107256 107269 107278 107307 107515 107522 107568 107578 107603 107631 107638
                                                                            
107639 107686 107687 107719 108102 108145 108216 108223 108316 108349 108390
                                                                            
108393 108417 108440 108473 108499 108518 108532 108572 108626 108642 108683
                                                                            
108701 108718 108764 108795 108875 108885 108923 108954 108955 109021 109044
                                                                            
109066 109148 109164 109388 109393 109396 109403 109478 109526 109698 109701
                                                                            
109766 109790 109821 109846 109920 109940 109981 110019 110057 110095 110111
                                                                            
110119 110191 110226 110230 110262 110325 110337 110339 110370 110414 110480
                                                                            
110536 110798 110841 110844 110889 110931 111006 111038 111078 111112 111197
                                                                            
111230 111261 111387 111417 111420 111548 111567 111576 111615 111738 111866
                                                                            
111871 111874 111877 111910 111957 111984 111993 112013 112083 112229 112310
                                                                            
112316 112371 112398 112412 112492 112521 112531 112540 112556 112572 112581
                                                                            
112638 112649 112653 112697 112706 112754 112835 112897 112925 112958 113029
                                                                            
113056 113105 113141 113244 113254 113281 113289 113290 113342 113404 113411
                                                                            
113425 113440 113469 113471 113481 113489 113490 113517 113653 113689 113707
                                                                            
113718 113729 113765 113798 113818 113829 113844 113876 113898 113902 113924
                                                                            
113930 113946 113963 113995 114034 114048 114057 114062 114101 114141 114228
                                                                            
114241 114270 114331 114363 114364 114387 114395 114526 114546 114560 114597
                                                                            
114628 114651 114657 114783 114787 114996 115065 115122 115184 115238 115253
                                                                            
115297 115320 115323 115372 115407 115444 115458 115460 115534 115542 115548
                                                                            
115631 115677 115703 115738 115748 115829 115863 115870 115899 115951 116004
                                                                            
116013 116030 116050 116095 116124 116155 116174 116177 116212 116307 116350
                                                                            
116402 116453 116607 116655 116688 116705 116706 116724 116727 116733 116747
                                                                            
116782 116851 116870 116983 116993 116995 117001 117016 117124 117141 117174
                                                                            
117181 117222 117240 117295 117316 117332 117341 117378 117396 117440 117457
                                                                            
117569 117847 117914 117945 117952 117978 118009 118011 118055 118064 118078
                                                                            
118098 118130 118194 118250 118312 118379 118435 118496 118504 118505 118523
                                                                            
118586 118627 118686 118717 118753 118888 118890 118892 118970 118974 118975
                                                                            
119006 119024 119036 119045 119120 119149 119222 119270 119273 119276 119287
                                                                            
119381 119383 119404 119459 119472 119481 119538 119597 119605 119659 119704
                                                                            
119731 119769 119792 119794 119873 119882 119902 120036 120063 120100 120112
                                                                            
120132 120144 120151 120177 120209 120231 120288 120416 120449 120494 120502
                                                                            
120538 120546 120548 120550 120627 120657 120675 120694 120719 120745 120758
                                                                            
120789 120811 120820 120829 120869 120918 120954 120975 121048 121052 121056
                                                                            
121081 121093 121162 121383 121572 121583 121603 121636 121690 121692 121798
                                                                            
121801 121824 121835 121866 121867 121898 121956 121962 121986 122021 122079
                                                                            
122105 122223 122226 122264 122366 122381 122406 122422 122432 122451 122461
                                                                            
122495 122536 122542 122546 122557 122611 122618 122619 122623 122660 122691
                                                                            
122737 122762 122807 122834 122835 122859 122872 122927 122931 122996 123019
                                                                            
123026 123032 123085 123191 123449 123533 123565 123585 123618 123620 123673
                                                                            
123687 123702 123703 123748 123789 123877 123895 123943 123951 124004 124017
                                                                            
124024 124039 124041 124076 124087 124090 124101 124153 124194 124323 124362
                                                                            
124427 124432 124461 124462 124511 124544 124585 124810 124817 124825 124838
                                                                            
124894 124945 124978 125070 125153 125182 125206 125233 125263 125391 125406
                                                                            
125431 125435 125451 125679 125727 125756 125787 125790 125806 125856 125911
                                                                            
125959 126080 126091 126128 126133 126168 126170 126229 126260 126362 126379
                                                                            
126387 126428 126455 126500 126580 126644 126646 126656 126685 126695 126721
                                                                            
126752 126753 126773 126777 126797 126805 126828 126858 126894 126965 126988
                                                                            
127035 127048 127049 127091 127144 127170 127215 127278 127587 127628 127641
                                                                            
127697 127709 127711 127735 127743 127755 127874 127919 128048 128065 128073
                                                                            
128121 128164 128183 128243 128302 128351 128358 128363 128379 128402 128412
                                                                            
128445 128460 128469 128470 128497 128526 128536 128539 128590 128785 128882
                                                                            
128940 128960 128972 129004 129009 129060 129061 129077 129101 129110 129112
                                                                            
129135 129137 129139 129145 129204 129208 129232 129233 129254 129285 129388
                                                                            
129438 129456 129470 129526 129545 129555 129586 129617 129628 129703 129795
                                                                            
129805 129873 129885 129986 130067 130188 130209 130227 130239 130254 130257
                                                                            
130303 130338 130358 130366 130418 130432 130486 130552 130662 130687 130716
                                                                            
130722 130748 130785 130868 130901 130926 130956 130993 131033 131079 131115
                                                                            
131123 131128 131161 131299 131309 131331 131447 131648 131669 131716 131795
                                                                            
131835 131865 131869 131886 131916 131933 131958 132020 132023 132036 132077
                                                                            
132137 132194 132230 132257 132290 132323 132366 132376 132387 132403 132441
                                                                            
132444 132471 132520 132540 132565 132606 132674 132685 132751 132791 132825
                                                                            
132854 132960 132998 133020 133105 133170 133222 133225 133230 133278 133328
                                                                            
133332 133351 133393 133406 133444 133505 133582 133592 133640 133656 133770
                                                                            
133791 133794 133813 133956 134045 134111 134123 134299 134446 134489 134531
                                                                            
134585 134587 134617 134650 134652 134678 134681 134836 134924 134942 134959
                                                                            
134972 135019 135074 135148 135242 135271 135280 135297 135306 135351 135378
                                                                            
135470 135474 135542 135548 135553 135556 135581 135624 135633 135652 135659
                                                                            
135704 135767 135800 135852 135857 135870 135925 135985 136003 136008 136018
                                                                            
136043 136064 136072 136172 136184 136224 136252 136331 136387 136441 136543
                                                                            
136552 136602 136624 136671 136732 136756 136844 136863 136915 136943 136959
                                                                            
136962 137006 137032 137051 137083 137117 137161 137239 137264 137300 137305
                                                                            
137316 137373 137376 137379 137410 137451 137469 137548 137554 137569 137585
                                                                            
137599 137630 137657 137691 137694 137714 137834 137846 137847 137922 137929
                                                                            
138081 138096 138153 138224 138326 138385 138509 138536 138641 138647 138699
                                                                            
138729 138780 138803 138853 138859 138860 138876 138877 138886 138896 138900
                                                                            
138952 138954 138960 139056 139059 139269 139286 139381 139384 139548 139579
                                                                            
139626 139642 139643 139645 139711 139715 139718 139765 139766 139767 139781
                                                                            
139817 139848 139871 139928 139929 139930 139950 139955 139990 140009 140048
                                                                            
140120 140176 140188 140266 140340 140380 140388 140424 140426 140463 140549
                                                                            
140562 140563 140602 140620 140718 140720 140733 140734 140756 140775 140799
                                                                            
140851 140882 140918 140931 140975 140984 141008 141027 141029 141059 141081
                                                                            
141111 141117 141122 141123 141138 141166 141182 141210 141221 141240 141258
                                                                            
141281 141321 141322 141328 141334 141346 141358 141371 141407 141449 141480
                                                              
141503 141512 141522 141543 141552 141555 141579 141588 141622

But for R1.fq file it says-
> which(seqlens != quallens)
named integer(0)

Is there an issue with the quality of the R2 files ?. Kindly help.

**Comment by benjjneb** [comment]
Yes that indicates a problem with the R2 files. Many of the entries have a number of quality scores that is different than the number of bases.

Did you preprocess these fastq files in some way? If so, what programs did you use? If not, what sequencing provider gave you these files?
