### ISSUE TITLE
Performance question/issue

### ISSUE THREAD

**Issue by dkaplan65** [benjjneb/dada2#596]
Hi,

I am running the regular DADA2 pipeline (not the big data pipeline) almost exactly on a large remote server and it is taking an extremely long time (5 days and it has not finished). I've tried looking other places online for answers and I keep on finding conflicting answers.

Computing resources:
16 cores
450 gb RAM

Data:
1410 samples
~115 million reads
Average depth: ~82000
16S V4 region
Data produced over 5 different runs - the quality scores for each of the runs seem nearly identical

The bottleneck seems to be running dada on the reverse reads. 
`dadaRs <- dada(derepRs, err=ddR[[1]]$err_out, pool=TRUE, multithread = TRUE)`

Is this normal performance for a dataset this large? Since the data was produced over 5 different runs, should I run dada separately on each run and then merge the outputs together, or merge the data together and then run dada once on the whole set?

I have attached my code as a txt file.

[customDADA2.txt](https://github.com/benjjneb/dada2/files/2520104/customDADA2.txt)

Any help is welcome.

Thanks!

**Comment by benjjneb** [comment]
>1410 samples
>~115 million reads
> Is this normal performance for a dataset this large?

Yes. Pooled computation time scales quadratically with the total number of reads, and in practice pooled inference seems to work out to about Miseq scales (~10M reads) and be difficult to scale beyond that.

My first thought would be, have you tried pseudo-pooling? https://benjjneb.github.io/dada2/pseudo.html#pseudo-pooling

This was introduced to allow for near-pooled sensitivity while maintaining the linear computational scaling of independent sample inference. I think this it the way to go for your study, especially if multiple runs are involved, as that approach lets you use the run-specific error models as appropriate.

**Comment by dkaplan65** [comment]
Hi,

Thank you for the response. I have not tried pseudo-pooling but I am going to do it now. 

Thank you for your help.
