### ISSUE TITLE
Reproducibility Issue

### ISSUE THREAD

**Issue by adityabandla** [benjjneb/dada2#599]
Hi Ben

I upgraded DADA2 from v1.9.0 (running in R 3.5.0) to v1.9.3 (R 3.5.1). I ran some benchmarks to see if the new installation was working as expected. I ran the same dataset and code through the new version, however there seems be a minor discrepancy in terms of the total reads after the denoising step

`sum(track$denosied)
[1]  1658452`
`sum(track$denosied)
[1]  1656388`

Not sure what would explain this

**Comment by adityabandla** [comment]
Is the devel branch behind the current bioconductor release?

**Comment by adityabandla** [comment]
Since the switch, I have been getting highly inconsistent results with the dada function with `pool = TRUE`. Surprisingly, only about 50% of the reads merge with pooling, while about 75% merge with `pool = "pseudo"`

With previous versions (<=1.9.0), I was consistently getting >90% merge rates with `pool = TRUE` for the same dataset

**Comment by benjjneb** [comment]
> Is the devel branch behind the current bioconductor release?

No I just haven't updated versioning to the next release cycle on the main github repo. Should happen later this week. But 1.10 from BioC is the same as the current devel version 1.9.3

**Comment by benjjneb** [comment]
> Hi Ben
> 
> I upgraded DADA2 from v1.9.0 (running in R 3.5.0) to v1.9.3 (R 3.5.1). I ran some benchmarks to see if the new installation was working as expected. I ran the same dataset and code through the new version, however there seems be a minor discrepancy in terms of the total reads after the denoising step
> 
> `sum(track$denosied) [1] 1658452`
> `sum(track$denosied) [1] 1656388`
> 
> Not sure what would explain this

There was a minor fix to the weighting of the loess fit in the error estimation code that could cause small changes like that: https://github.com/benjjneb/dada2/commit/b944cdff1433e70feb2716e3c4600999d68db57b#diff-fceda1a58bed3cd2c398712c94d6d503

**Comment by benjjneb** [comment]
> Since the switch, I have been getting highly inconsistent results with the dada function with `pool = TRUE`. Surprisingly, only about 50% of the reads merge with pooling, while about 75% merge with `pool = "pseudo"`
> 
> With previous versions (<=1.9.0), I was consistently getting >90% merge rates with `pool = TRUE` for the same dataset

That seems unexpected. Can you make a minimal example (e.g. w/ like 4 samples) that still shows this behavior?

**Comment by adityabandla** [comment]
> > Since the switch, I have been getting highly inconsistent results with the dada function with `pool = TRUE`. Surprisingly, only about 50% of the reads merge with pooling, while about 75% merge with `pool = "pseudo"`
> > With previous versions (<=1.9.0), I was consistently getting >90% merge rates with `pool = TRUE` for the same dataset
> 
> That seems unexpected. Can you make a minimal example (e.g. w/ like 4 samples) that still shows this behavior?

Hi Ben

Following are the results with `pool = TRUE` and `pool = "psuedo"` for 4 samples

|       pool = TRUE                                       |  input| filtered| denoised| merged|
|:--------------------------------------------|------:|--------:|--------:|------:|
|JLRo1_TAAGGCGA-AAGGAGTA_L001_R1_001.fastq.gz | 165934|    30246|    28032|  14883|
|PRRo4_TAAGGCGA-ACTGCATA_L001_R1_001.fastq.gz | 133718|    23602|    22223|  18911|
|SKRo1_CGTACTAG-AAGGAGTA_L001_R1_001.fastq.gz | 112642|    17647|    15498|  11776|
|YPRo4_CGTACTAG-ACTGCATA_L001_R1_001.fastq.gz | 123749|    21899|    20015|  13737|

|   pool = "pseudo"                                                                        |  input| filtered| denoised| merged|
|:------------------------------------------------------|------:|--------:|--------:|------:|
| JLRo1_TAAGGCGA-AAGGAGTA_L001_R1_001.fastq.gz | 165934|    30246|    29089|  22426|
| PRRo4_TAAGGCGA-ACTGCATA_L001_R1_001.fastq.gz | 133718|    23602|    23084|  20627|
| SKRo1_CGTACTAG-AAGGAGTA_L001_R1_001.fastq.gz  | 112642|    17647|    17204|   1230|
| YPRo4_CGTACTAG-ACTGCATA_L001_R1_001.fastq.gz  | 123749|    21899|    21089|  16295|                                                                                         

I have emailed you a Dropbox link to the files. Primers have already been trimmed using cutadapt and checked using the code in the ITS workflow. 

Filtering parameters I used were maxEE = 5, truncLen = c(260,220), since its 466 bp amplicon

**Comment by adityabandla** [comment]
> > Hi Ben
> > I upgraded DADA2 from v1.9.0 (running in R 3.5.0) to v1.9.3 (R 3.5.1). I ran some benchmarks to see if the new installation was working as expected. I ran the same dataset and code through the new version, however there seems be a minor discrepancy in terms of the total reads after the denoising step
> > `sum(track$denosied) [1] 1658452`
> > `sum(track$denosied) [1] 1656388`
> > Not sure what would explain this
> 
> There was a minor fix to the weighting of the loess fit in the error estimation code that could cause small changes like that: [b944cdf#diff-fceda1a58bed3cd2c398712c94d6d503](https://github.com/benjjneb/dada2/commit/b944cdff1433e70feb2716e3c4600999d68db57b#diff-fceda1a58bed3cd2c398712c94d6d503)

But these issues I encountered were using v 1.9.3, it was completely fine when using v 1.9.0, which is after the change I guess (v 1.8)

**Comment by llrs** [comment]
It might be related to #610?

**Comment by benjjneb** [comment]
Presuming this was fixed by 4dff4237da08c015f05dae3ab641c22092cf6979
