### ISSUE TITLE
Pooling samples for chimera detection

### ISSUE THREAD

**Issue by pck0** [benjjneb/dada2#60]
I was wondering if you are planning on adding the option of pooling all samples for chimera detection after denoising (I'm going by Robert Edgar's suggestion of pooling as per http://drive5.com/usearch/manual/uchime_pool.html). Alternatively, is there already a way to do this?
I'm not sure denoised samples can currently be pooled manually without messing up later merging steps, and pooling all samples before going through the dada pipeline results in exceedingly long run times. 

cheers

**Comment by benjjneb** [comment]
Yes you can remove chimeras on the full sequence table at the end, which is the equivalent of pooling samples and then removing chimeras.

That is, go through denoising and merging but don't remove chimeras. Then (schematically):
```
seqtab <- makeSequenceTable(merged.samples)
bims <- isBimeraDenovo(seqtab)
seqtab.nochim <- seqtab[,!bims]
```

**Comment by pck0** [comment]
Oh, that was embarrassingly simple! Thank you for helping out an R-impaired person!
