### ISSUE TITLE
git tags for release versions?

### ISSUE THREAD

**Issue by nhoffman** [benjjneb/dada2#600]
Would it be possible to tag all (or at least major) release versions? This allows one to identify the appropriate commit when installing directly from the git repo, and also can assist in understanding changes between releases. Looks like the most recent tag is for v1.8

Thanks for considering!
Noah

**Comment by benjjneb** [comment]
Sorry I am a bit behind and haven't got to the 1.10 release on the main github repo yet.
Should happen later this week.

**Comment by benjjneb** [comment]
Just spun out the 1.10 release on github: https://github.com/benjjneb/dada2/releases/tag/v1.10

Tag is `v1.10`

**Comment by lecorguille** [comment]
Can you create a tag for the `v1.12`?
You are using it within your website:

```
install.packages("devtools")
library("devtools")
devtools::install_github("benjjneb/dada2", ref="v1.12") # change the ref argument to get other versions
```

Thanks

**Comment by benjjneb** [comment]
@lecorguille Woops! Thanks for letting me know. v1.12 release should be there now.
