### ISSUE TITLE
Problem in merging PE reads of 16s V3-4 reads 

### ISSUE THREAD

**Issue by nimhong** [benjjneb/dada2#603]
Hello, 
    I am using dada2 to analyse my data about 16s V3 and V4 region. I got the sequence without barcode, primers and so on. But I get some weird results. I plotted the prevalence and total abundance and like this. 
![prevalence_totalabundance](https://user-images.githubusercontent.com/43361509/48037494-7d227b80-e1a7-11e8-8b85-a0d9f8b3cb40.png)
To resolve this problem, I tried to use different parameters. But it is still there. 
First, because my sequence had been filtered by the company. So it doesn't contain N reads, low-quality reads, and barcode. And I deleted "truncLen= , maxN= , maxEE= " on filterAndTrim function. 
Second, I set pool=T in function dada. 
Third, I add "minOverlap = 20,maxMismatch=0" in function mergePairs. 
Fourth, I respectively used two reference dataset, gg_13_8_train_set_97.fa.gz and rdp_train_set_16.fa.gz.gz.
But it doesn't work. So I think the problem is merging. I think maybe V3-4 region sequence need to handle in different ways. 
Below is my code. Besides, I sent my codes with attachment. If that's all right, I can send you 5 fastq files. And could you give me some advice? Thank you so much. 
`setwd("D:/201805sequence data")
library(dada2)
library(phangorn)
library(DECIPHER)
library(BiocStyle)
library(ggplot2)
library(gridExtra)
library(phyloseq)

seq_path <- "D:/201805sequence data/5clean_reads_10samples"
list.files(seq_path)

fnFs <- sort(list.files(path = seq_path, pattern = "_1_paired.fq.gz",full.names = T))
fnRs <- sort(list.files(path = seq_path, pattern = "_2_paired.fq.gz",full.names = T))
fnFs[1]

i = 0
i = i + 1
plotQualityProfile(rbind(fnFs[i],fnRs[i]))

filt_path <- file.path(getwd(), "filtered")
if(!file_test("-d",filt_path)) dir.create(filt_path)
dir.create(paste(filt_path,"/fs",sep = ""))
dir.create(paste(filt_path,"/fr",sep = ""))

filtFs <- paste(filt_path, "/fs/",
                sort(list.files(path = seq_path, pattern = "_1_paired.fq.gz",full.names = F)),
                sep = "")
filtRs <- paste(filt_path, "/fr/",
                sort(list.files(path = seq_path, pattern = "_2_paired.fq.gz",full.names = F)),
                sep = "")

set.seed(sample(1:999,1))
system.time(
  out <- filterAndTrim(fnFs, filtFs,
                     fnRs, filtRs,
                     truncQ = 2, rm.phix = T,
                     compress = T, multithread = F))
system.time(
  derepFs <- derepFastq(filtFs,verbose = T))
derepRs <- derepFastq(filtRs,verbose = T) names(derepFs) <- sub("_1_paired.fq.gz","",
                      sort(list.files(path = seq_path, pattern = "_1_paired.fq.gz",full.names = F)))
names(derepRs) <- sub("_2_paired.fq.gz","",
                      sort(list.files(path = seq_path, pattern = "_2_paired.fq.gz",full.names = F)))

system.time(errF <- learnErrors(filtFs, multithread = T))
errR <- learnErrors(filtRs, multithread = T)
system.time(
dadaFs <- dada(derepFs, err = errF, multithread = T))
dadaRs <- dada(derepRs, err = errR, multithread = T)
system.time(
  mergers <- mergePairs(dadaF = dadaFs, derepF = derepFs,
                        dadaR = dadaRs, derepR = derepRs,
                        minOverlap = 20,maxMismatch=0))
seqtabAll <- makeSequenceTable(mergers)
table(nchar(getSequences(seqtabAll)))

system.time(seqtabNoC <- removeBimeraDenovo(seqtabAll))
table(nchar(getSequences(seqtabNoC)))

fastaRef <- "D:/201805sequence data/2dataset/greengene/gg_13_8_train_set_97.fa.gz"
file.exists("D:/201805sequence data/2dataset/greengene/gg_13_8_train_set_97.fa.gz")

set.seed(1000)

system.time(
  taxname <- assignTaxonomy(seqs = seqtabNoC,
                          refFasta = fastaRef,
                          multithread = T,
                          tryRC = T))
unname(head(taxname))

seqs <- getSequences(seqtabNoC)
names(seqs) <- seqs
system.time(
  datalignment <- AlignSeqs(DNAStringSet(seqs), anchor = NA, verbose = F))
phangAlign <- phyDat(as(datalignment,"matrix"),
                     type = "DNA")
system.time(
  dm <- dist.ml(phangAlign))
system.time(
  treeNJ <- NJ(dm))
fit = pml(treeNJ, data = phangAlign)
fitGTR <- update(fit, k=4, inv=0.2)
system.time(
  fitGTR <- optim.pml(fitGTR, model = 'GTR',optInv = T, optGamma = T,
                    rearrangement = "stochastic",
                    control = pml.control(trace = 0)))

samdf <- read.csv("D:/201805sequence data/201805sample information_10samples.csv",
                  header = T)

A <- list.files(path = "D:/201805sequence data/filtered/fr")
A <- sub("_split_2_paired.fq.gz", "", A)
row.names(seqtabNoC) <- A

row.names(samdf) <- samdf$sample_ID

ps <- phyloseq(otu_table(seqtabNoC, taxa_are_rows = F),
               sample_data(samdf),
               tax_table(taxname),
               phy_tree(fitGTR$tree))

rank_names(ps)
table(tax_table(ps)[,"Phylum"], exclude = NULL)

ps <- subset_taxa(ps, !is.na(Phylum) & !Phylum %in% c("","uncharacter"))

prevdf <- apply(X = otu_table(ps),
                MARGIN = ifelse(taxa_are_rows(ps),
                                yes = 1, no = 2),
                FUN = function(x){sum(x > 0)})

prevdf <- data.frame(Prevalence = prevdf, 
                     TotalAbundance = taxa_sums(ps),  
                     tax_table(ps))

plyr::ddply(prevdf, "Phylum", function(df1){
cbind(mean(df1$Prevalence),sum(df1$Prevalence))  
})

ps1 <- subset_taxa(ps, !Phylum %in%
                     c("Euryarchaeota","Cloacimonetes"))
ps1

prevdf1 <- subset(prevdf, Phylum %in%
                    get_taxa_unique(ps1, "Phylum"))

ggplot(prevdf1, aes(TotalAbundance,
                    Prevalence / nsamples(ps),
                    color=Phylum)) +
  geom_hline(yintercept = 0.05, alpha = 0.5, linetype = 2) + 
  geom_point(size = 2, alpha = 0.7) + 
  scale_x_log10() + 
  xlab("TotalAbundance") +
  ylab("Prevalence [Frac. Samples]") +
  facet_wrap(~Phylum) +
  theme(legend.position = "none")
`

Thanks. 

[code.zip](https://github.com/benjjneb/dada2/files/2551375/code.zip)

**Comment by benjjneb** [comment]
That certainly looks problematic.

> First, because my sequence had been filtered by the company. So it doesn't contain N reads, low-quality reads, and barcode.

TBH this is the most likely cause of the problem. Do you know how they did this filtering? Can you get the raw data instead?


What are the outputs of the following:
```
dim(seqtabNoC)
summary(colSums(seqtabNoC))
summary(colSums(seqtabNoC>0))
summary(rowSums(seqtabNoC))
```

**Comment by nimhong** [comment]
I will get the raw sequence from the company. And the company used Trimmomatic V0.33 to filter N reads, low-quality reads (<20) and short reads (<150nt). The paired-end reads were merged by FLASH V1.2.11 according to the relationship of the overlap between the paired-end reads when at least 10 of the reads overlap the read generated from the opposite end of the same DNA fragment, the maximum allowable error ratio of the overlap region of 0.1. And the sequences were assigned to each sample based on their unique barcode and primer using Mothur V1.35.1. And then, the barcodes and primers were removed. The maximum allowable error ratio of the barcode and primer are 2 and 3. 
Besides, the report from the company looked good. 
I checked the output and showed below. 
![image](https://user-images.githubusercontent.com/43361509/48161125-cba15880-e314-11e8-904d-171cc2dd2b1f.png)
It looked unnormal. Could you give me more advice? Thanks

**Comment by benjjneb** [comment]
> >summary(colSums(seqtabNoC>0))

The output you are getting from that is all 1s. That indicates that every ASV in your dataset is only present in one sample (i.e. zero sharing between samples), which explains the 1/10th prevalence for every ASV.

I don't understand why based on what you described, but the pre-processing has resulted in sequences in each sample that are different from the other samples. Perhaps due to different length trimming, or leaving on sample barcodes, I don't know.

You could inspect the length distribution for ASVs in each sample, and look for primer or barcode sequences, but the easiest thing is probably to request the raw data from the company, preferably demultiplexed, and then proceed as normal from there.

**Comment by nimhong** [comment]
Yes, I should get the raw data. It is so strange for the distribution of ASVs. As you say, maybe the problem is the trimming or the barcodes. I will preprocess the sequence by myself and then use dada2. Thanks.

**Comment by benjjneb** [comment]
Feel free to re-open if the problem persists with the raw data.
