### ISSUE TITLE
Pooling across restricted set of samples, possible enhancement?

### ISSUE THREAD

**Issue by adityabandla** [benjjneb/dada2#604]
Is it possible to restrict full pooling to a restricted set of samples within a big dataset. In my case, we often collect samples from different regions within a city and then sequence them together.

Pooling all samples doesn't make much sense in this context (I maybe wrong?). It might be useful, in this case, to restrict pooling to replicates that were taken from the same region. It might also help reduce false positive detection, as singleton ASV's detected across few replicates, but across many regions are likely to be contaminants

**Comment by benjjneb** [comment]
Yes I agree this would be a reasonable enhancement.

However, you can do this by hand pretty easily right now. Just run a loop over the groups and `dada(drp[group.i], pool=TRUE)` on each group. Then make sequence  tables for each group and `mergeSequenceTables` them all into the final table.

**Comment by benjjneb** [comment]
Closing this as unlikely to be added to the package. I think this is solved easily enough by simple R code (i.e. running the pooled inference over the samples in each pool), that it is not worth the complication of adding to the package code.
