### ISSUE TITLE
mergePairs produces strangely named dataframe when mergers are from only one sample

### ISSUE THREAD

**Issue by derele** [benjjneb/dada2#606]
I just created a pull request for a small issue when only one sample had mergers. See: 
https://github.com/benjjneb/dada2/pull/605

I hope this is minimally invasive ;-). 
But I wonder why the list of mergers for each samples needs to be simplified at all when you have only one sample.

**Comment by benjjneb** [comment]
Fixed by 9ef5a3be0c86c940082d84a8ebbe47b988cb2e1b
