### ISSUE TITLE
Getting error in derep step

### ISSUE THREAD

**Issue by ngarud** [benjjneb/dada2#61]
Hi Ben,
I'm running DADA2 and have a problem with the dereplication step. All steps before it ran fine except for the trimming of 2 of the paired end files (not the one listed below in the error). Any thoughts on what might be happening? I ran the Mi_seq tutorial and this step ran fine. 
Thanks,
Nandita
 
> derepFs <- lapply(filtFs, derepFastq, verbose=TRUE)
Dereplicating sequence entries in Fastq file: /netapp/home/ngarud/shattuck/chaz/unfiltered/01_ATCCATG-GTCATCC_L002_R1_001_filt.fastq.gz

Error in rep(seq(length(uniques)), tab[tab > 0]) : 
  invalid 'times' argument

**Comment by benjjneb** [comment]
Huh... I've never seen that error before. I'm not sure.

Could you share the file causing it? Email is fine if its small enough.

**Comment by ngarud** [comment]
Hi Ben,

Thanks very much for taking a look into this -- I really appreciate it. I'm
looking forward to running DADA2 on this data set. Here is a dropbox link
for the forward and reverse files for the first sample. Unfortunately the
files are large (2.1GB compressed and 4.2 uncompressed). I'm running DADA2
on someone else's data, so I didn't generate this data myself. If there is
any issue with the data, let me know and I can ask the person to fix it.

https://www.dropbox.com/sh/hporqn7ngpfo40n/AAAiYPoaHaQGXSLksPFktYwpa?dl=0

Thanks, and sorry for taking up your time!

Nandita

**Comment by benjjneb** [comment]
Hi Nandita,
I successfully dereplicated the forward reads using the following 2 commands:

```
fastqFilter(fn, filt, trimLeft=5, maxEE=1, truncLen=130, truncQ=2, maxN=0, verbose=TRUE)
drp <- derepFastq(filt, verbose=TRUE)
```

This was quite memory intensive, as this appears to be a single sample (?) sequenced to a depth of 13M reads, in which 87% of the sequences are unique!! The large memory requirements of loading 10M unique sequences and associated qualities into memory may have sparked the error you saw.

That is highly alarming, real sequencing data should see many repeated sequences, and the problematic nature of this data is confirmed by looking at the top 20 most abundant sequences in the sample:

```
1:ACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAAC 18273 
2:GTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGT 10489 
3:TGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTG 5567 
4:CAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACA 2168 
5:AACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAA 1901 
6:TTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTTGTT  875 
7:AAACAAAACAAAACAAAACAAAACAAAACAAAACAAAACAAAACAAAACAAAACAAAACAAAACAAAACAAAACAAAACAAAACAAAACAAAACAAAACAAAACAAAACAAAACAAAACAAAACA 279 
8:GTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTTGTTTT 247 
9:ACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACACA 92 
10:ATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGATAGA 91 
11:AAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACAAACA 88 
12:TATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCT 83 
13:TTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGTTTGT 78 
14:GCAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAAC 69 
15:ACAGCAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAAC 68 
16:TCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTATCTAT 67 
17:ACAACAACAACAACAACAACAACAAAAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAAC 61 
18:AACAACAAACAACAAACAACAAACAACAAACAACAAACAACAAACAACAAACAACAAACAACAAACAACAAACAACAAACAACAAACAACAAACAACAAACAACAAACAACAAACAACAAACAAC 59 
19:ACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTACTAC 58 
20:ACAACAGCAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAACAAC 53 
```
This is bad. Even the non-repeated sequences appear to have significant repetitive chunks in them:

```
10492620:TTTTTTTTCTATGAAATATTGATCAAATTGTCTTTGATTGTTAAAATTAATAAATTCATATAAGAGTTTACTTAGTCATTAAATTGTCTTCTTTAAAAGAATTAATTTATTAAATTGATATCCAT 1 
10492621:TTTTTTTTGGAAAGAATCCGGGGCTGGTCAAAGGAAGGGTGATCCAGTTCCGGGAAACATTCCGCGATTGCGCGGGCGGATTGGTCAATCGCAGCACGAACATCTCCTGGAAGAACGGCGCGTAT 1 
10492622:TTTTTTTTGGTTTTTTTCTCTTTTCTTTTCGTTTCTTTTTATTCTTCATCATTTCTTTTTCTTTTCCTAATTACCCATCTTTGCATGAACGCACGACTTGCCTCTTGAGGTGTGTCTCGTGTCTC 1 
10492623:TTTTTTTTGTTTGTCATCATTTGGTTTCTTTAATTAAAATAAAAGCGCCTTCTAATTCATCGCAAGCTTGAGAACAAACGTTTTCGAGCTGTAAAACCAATGTCTGTAATTCCTCAGGGTTCTGT 1 
10492624:TTTTTTTTTACTTCGCTGAAGTTTTGTTGAACAGGAAAAAGGGCCCTTTTGAGGCCCTTTTATCAAAAAATATAAGAATATATTATTCTGCTGAATATTTCAGCACTTTGCCGGCACCCAGACGG 1
```

To me this data looks completely unusable.

**Comment by ngarud** [comment]
Wow, thank you so much for doing this for me! Yes, I agree the data looks
unusable.

Nandita

**Comment by CaraFiore** [comment]
Hello,
If I may ask about getting the same error in learnError and derep ? 

However my sequences are not bad (at least the forwards reads look fine), here is an example from the fastq file:
CDF1<1=>1D1FGGFGFHHHFGFFCCG@ED0G<GACDCA:;CCBC00CAAF99FDACFGFE?B?-.;@-@DD/FFBB/A9.;/B9BFF
@M00780:232:000000000-C8GKG:1:1101:11512:1979 1:N:0:CATTGGTTGCAC
TACAGAGGTCTCAAGCGTTGTTCGGAATCACTGGGCGTAAAGCGTGCGTAGGCTGTTTCGTAAGTCGTGTGTGAAAGGCGCGGGCTCAACCCGCGGACGGCACATGATACTGCGAGACTAGAGTAATGGAGGGGGAACCGGAATTCTCGGTGTAGCAGTGAAATGCGTAGATATCGAGAGGAACACTCGTGGCGAAGGCGGGTTCCTGGACATTAACTGA

This is what I get when I run learnError or try derepelication, here it is with the learnError. I have tried no multithread, I have also tried setting nbases to 1e5, 1e7, 1e8):

>errF <- learnErrors(filtFs, multithread = TRUE)

Error in rep(seq(length(uniques)), tab[tab > 0]) : 
  invalid 'times' argument

Thank you for your time.
