### ISSUE TITLE
Pseudo-pooling fails for dada()

### ISSUE THREAD

**Issue by masumistadler** [benjjneb/dada2#612]
Hello Benjamin,

I've run dada on our 650 samples on a sample by sample basis by following your big data tutorial without a problem.

We realised though, that we are losing a lot of the rare bacteria, which we are interested in. For now, I have pooled the samples (per sequencing plate) for the `learnErrors` step which worked well.

However, the `dada` step fails when pseudo-pooling 95 samples (shallowly sequenced). We also have 9 deeply sequenced samples that we would like to pseudo-pool to recover more of the rare bacteria (3 million sequences per sample).

I tried to pool the shallow samples on a server with 300 GB RAM and 10 cores, but it failed... So I didn't even bother to try the deep sequences for now.

Before I submit another job and waiting for a long time until being disappointed again, do you have any advice on how to calculate how much RAM, CPU and time the dada step needs for pseudo-pooling such a data set?

Any input is greatly appreciated!
Thank you in advance.

Best,
Masumi

**Comment by benjjneb** [comment]
I'm rather surprised that you had trouble with `pool="pseudo"` if you are doing just 90 samples. I would expect that to be achievable on far less than 300GB of RAM. Are you sure you are getting access to that much RAM when you submit your job?

The long-term answer though is to do the pseudo-pooling by hand, so you can run the Big Data workflow. That workflow streams through the samples independently. What you want to do is to run that workflow once, get a sequence table, identify ASVs in greater than X samples, and then run through each sample individually with dada(..., `priors=seqs.in.more.than.X.samples`). That is what pseudo-pooling does, but by doing it that way everything is done in streaming fashion keeping memory costs fixed.

**Comment by masumistadler** [comment]
Hello Benjamin,

Thank you for the fast answer.
I'll check with the server provider and thanks for the other manual option, that's a really good idea.

Best,
Masumi

**Comment by masumistadler** [comment]
The failing on the server seemed to have been a bug in the code. I could run the `pool = 'pseudo'` for a maximum of 95 shallow samples on a PC with 30GB RAM and 24 cores without any problem. It was also successful for pooling 3 deeply sequenced samples without having to run the pseudo-pooling by hand.
Thank you for the help!
