### ISSUE TITLE
Error in err[c(1, 6, 11, 16), ] <- 1 :    incorrect number of subscripts on matrix

### ISSUE THREAD

**Issue by mdpankau** [benjjneb/dada2#614]
Hi,
I am trying to use:

 errR <- learnErrors(filtRs, multithread=TRUE) 

to generate an error model for my filtered reverse reads.  When I run the code on the filtered forward reads it generates the error model just fine.  The only issue is with the reverse reads.  I have tried more stringent parameters during filtering to increase quality of the reverse reads but the error:

Error in err[c(1, 6, 11, 16), ] <- 1 : incorrect number of subscripts on matrix

persists.  

Using R version 3.5.1 and dada2 version 1.10.0

[QIgG_R_filt.fastq.gz](https://github.com/benjjneb/dada2/files/2591263/QIgG_R_filt.fastq.gz)

**Comment by mmclaren42** [comment]
Running `learnErrors` in verbose mode
```{r}
errR <- learnErrors("QIgG_R_filt.fastq.gz", verbose=2)
```
gives
```
56400 total bases in 188 reads from 1 samples will be used for learning the error rates.
Initializing error rates to maximum possible estimate.
C0LU:
ALIGN: 186 aligns, 0 shrouded (186 raw).
Error rates could not be estimated (this is usually because of very few reads).
Error in err[c(1, 6, 11, 16), ] <- 1 :
  incorrect number of subscripts on matrix
```
This suggests 188 reads isn't enough for the error rates to be estimated, and when estimation fails the line in the code fails, yielding the rather cryptic error message.

You might want to revisit your filtering to see why you have so few reads.

**Comment by mdpankau** [comment]
When I run the forward reads through (the same number) the learnErrors function calculates the error model just fine.  I have tried less stringent parameters to allow for more reads and the same error occurs.   I filtered to so few reads just to have a fastq that was rather small and easy to process while I am troubleshooting.

**Comment by mdpankau** [comment]
`131675700 total bases in 438919 reads from 1 samples will be used for learning the error rates.
Initializing error rates to maximum possible estimate.`

`ALIGN: 438910 aligns, 0 shrouded (438910 raw).
Error rates could not be estimated (this is usually because of very few reads).
 Show Traceback
Error in err[c(1, 6, 11, 16), ] <- 1 : incorrect number of subscripts on matrix`

**Comment by benjjneb** [comment]
That is unusual. Since you are using just one sample now, what is the output of the following:

```
derepFastq(fnF, verbose=TRUE) # where fnR is the FORWARD filename of the one sample
derepFastq(fnR, verbose=TRUE) # where fnR is the REVERSE filename of the one sample 
```

Also, can you post the full workflow up to this point that you are running on your end?

**Comment by mdpankau** [comment]
The R code that I'm running is taken from the tutorial:

`fnFs <- sort(list.files(path, pattern="_R1_001.fastq", full.names = TRUE))`
`fnRs <- sort(list.files(path, pattern="_R2_001.fastq", full.names = TRUE))`

`sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)`
`filt_path <- file.path(path, "filtered") # Place filtered files in filtered/ subdirectory`
`filtFs <- file.path(filt_path, paste0(sample.names, "_F_filt.fastq.gz"))`
`filtRs <- file.path(filt_path, paste0(sample.names, "_R_filt.fastq.gz"))`
`out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs,
                     rm.phix=TRUE,
                     compress=TRUE,
                     multithread=TRUE,  
                     matchIDs = TRUE,
                     maxEE = c(2,2),
                     minLen = c(200,200))`



`errF <- learnErrors(filtFs, multithread=TRUE)`
`errR <- learnErrors(filtRs, multithread=TRUE, verbose = 2)`

When I run: 
`derepFastq(filtFs, verbose=TRUE) `
`derepFastq(filtRs, verbose=TRUE) `

I get:
`Encountered 188 unique sequences from 188 total sequences read.
derep-class: R object describing dereplicated sequencing reads
$uniques: 188 reads in 188 unique sequences
  Sequence lengths: min=300, median=300, max=300
$quals: Quality matrix dimension:  188 300
  Consensus quality scores: min=9, median=38, max=38
$map: Map from reads to unique sequences:  168 180 164 161 139 ...`

and 

`Encountered 186 unique sequences from 188 total sequences read.
derep-class: R object describing dereplicated sequencing reads
$uniques: 188 reads in 186 unique sequences
  Sequence lengths: min=300, median=300, max=300
$quals: Quality matrix dimension:  186 300
  Consensus quality scores: min=7, median=38, max=38
$map: Map from reads to unique sequences:  74 77 9 76 66 ...`


I've also tried applying the forward error model to the reverse reads.  In that case all the bases become "G" .

**Comment by benjjneb** [comment]
> Encountered 188 unique sequences from 188 total sequences read...

> Encountered 186 unique sequences from 188 total sequences read...

This is the problem. There are essentially no repeated sequences in the filtered data you are analyzing, which is causing the dada2 algorithm to essentially fail, as it relies on repeated observations of the same sequence to distinguish biological variation from errors.

Typically, this is the result of poor sequencing, especially if you don't remove any of the low quality tails. I noticed you haven't used `truncLen`, is there a reason for that? If not, I would recommend doing so, and using it to cut off the portion of your reads after quality crashes (keeping in mind enough must be kept for them to overlap sufficiently for merging later on). You can use the `plotQualityProfile` function to inspect the quality profiles.

**Comment by benjjneb** [comment]
> Is there a reason why the dada2 algorithm works on the forward reads, which are all unique sequences, but does not on the reverse reads? Is it that the quality of the reverse reads is that much poorer?

Given the almost complete lack of repeated sequence observations in both F and R reads, I wonder if its really working well in either case.

The distro of sequence complexities also looks unusual to me. Although the complexities are in the normal range (above 11) there is not usually a bimodal distribution like that. I wonder what a few example sequences in the high and low modes look like, for example when you BLAST them agaisnt nt.

**Comment by maracashay** [comment]
Hi there, I am also having an issue with the learnErrors command on the reverse sequences. My data is ITS amplicon sequences from Illumina 150X150 bp sequencing. I have tried playing around with the truncLen(120-100, 110-90), truncQ (2/3), and maxEE(2-5,2-5) to see if I could find a 'sweet' spot that would allow my sequences to pass through the reverse learnError step but I have not had any luck. 

Here are my quality profiles:

![ForwardRead_QualityProfile](https://user-images.githubusercontent.com/28305326/54174960-57f88f00-445f-11e9-800d-3be76457bb0f.jpeg)

![ReverseRead_QualityProfile](https://user-images.githubusercontent.com/28305326/54174973-63e45100-445f-11e9-9daa-d6c34ed1cb6e.jpeg)


Do you have any suggestions about how I should proceed with DADA2? 

Thanks!

**Comment by benjjneb** [comment]
That complexity plot shows that you have a lot of reads with repetitive sequences in them, which is probably what is causing the problem with learning the error model.

One possibility would be to proceed with just the forward reads, although you will still want to remove low-complexity sequences there as well after denoising.

Another approach would be to remove read pairs with low-complexity. I haven't done this myself (because I haven't run into data like this) so I can't tell you exaclty how to do it, but I know tools for that exist. For example, I think the fastp program can do that: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6129281/

**Comment by maracashay** [comment]
BJ, thank you!!!!!!!!!! That was exactly what I needed.

I filtered my samples with fastp (which was really easy to use) using the low_complexity_filter and used the resulting filtered fastq files in DADA2 with no problems.
