### ISSUE TITLE
filterAndtrim giving empty output for sequencing data generated by 454 GS FLX data

### ISSUE THREAD

**Issue by rahulnccs** [benjjneb/dada2#615]
@benjjneb @Sofie8 
I successfully analyzed Ion torrent PGM data but now stuck with data generated by **454 GS FLX Titanium platform **
When I ran filterAndtrim as per recommendation I am getting empty output files (without filtered reads). Details are as follow:
command:
_filterAndTrim(file.path(path,fns), file.path(filtpath,fns), 
              truncLen=240, maxEE=1, truncQ=11, rm.phix=TRUE,
              compress=TRUE, verbose=TRUE, multithread=FALSE,  **maxLen=250**)_

& the error is : The filter removed all reads: path\filtered\SRRxxxxxx_4.fastq not written.
Some input samples had no reads pass the filter.

I also tried, 
filterAndTrim(file.path(path,fns), file.path(filtpath,fns), 
               maxLen=200)
but getting the same error.

I'm attaching figure of sequence quality if you can suggest some parameter changes. 
[qualityplot_prjna203810.pdf](https://github.com/benjjneb/dada2/files/2593114/qualityplot_prjna203810.pdf).

Finally, when I tried the standard  (Illumina) tutorial, it worked,
command:
_filterAndTrim(file.path(path,fns), file.path(filtpath,fns), 
              truncLen=240, maxEE=1, truncQ=11, rm.phix=TRUE,
              compress=TRUE, verbose=TRUE)_
output: Overwriting file: path\SRRxxxx_4.fastq
Read in 9633, output 8577 (89%) filtered sequences.

**Comment by benjjneb** [comment]
The `maxLen` parameter you set is removing all the reads. From the help:

> maxLen | (Optional). Default Inf (no maximum). Remove reads with length greater than maxLen. maxLen is enforced **before** trimming and truncation.

You want to set `maxLen` to something like `400-500` (based on your quality plots) just to remove those very long reads that you sometimes find in 454 data.

**Comment by rahulnccs** [comment]
Thanks, It worked. 
But  in the output of taxonomy assignment, 100% of the reads remained unassigned, 
_head(taxa.print)_
    Kingdom Phylum Class Order Family Genus
[1,] NA      NA     NA    NA    NA     NA   
[2,] NA      NA     NA    NA    NA     NA   
[3,] NA      NA     NA    NA    NA     NA   
[4,] NA      NA     NA    NA    NA     NA   

Here is complete tutorial I followed for 454 data:
outF <- filterAndTrim(fnFs, filtFs, truncLen=240,
              maxN=0, maxEE=2, truncQ=2, rm.phix=TRUE,
        compress=TRUE, multithread=FALSE, **maxLen=400**)

errF <- learnErrors(filtFs, multithread=F)
dadaFs <- dada(derepFs, err=errF, multithread=FALSE, **HOMOPOLYMER_GAP_PENALTY=-1, BAND_SIZE=32)**
```{r}
seqtab <- makeSequenceTable(dadaFs)
table
```{r}
seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=FALSE, verbose=TRUE)
```{r}
taxa <- assignTaxonomy(seqtab.nochim, "/Users/m201407/Downloads/**hitdb_v1.00.fa.gz",** multithread=FALSE)
taxa.print <- taxa 
rownames(taxa.print) <- NULL
head(taxa.print)
    Kingdom Phylum Class Order Family Genus
[1,] NA      NA     NA    NA    NA     NA   
[2,] NA      NA     NA    NA    NA     NA   
[3,] NA      NA     NA    NA    NA     NA   
[4,] NA      NA     NA    NA    NA     NA   


Any suggestions?

**Comment by benjjneb** [comment]
From the tutorial assign taxonomy section https://benjjneb.github.io/dada2/tutorial.html#assign-taxonomy

> Considerations for your own data: If your reads do not seem to be appropriately assigned, for example lots of your bacterial 16S sequences are being assigned as Eukaryota NA NA NA NA NA, your reads may be in the opposite orientation as the reference database. Tell dada2 to try the reverse-complement orientation with assignTaxonomy(..., tryRC=TRUE) and see if this fixes the assignments.

**Comment by rahulnccs** [comment]
YES ! it worked, Thank you very much.
 I'm closing this issue.
