### ISSUE TITLE
Merging .txt files with DADA2 outputs

### ISSUE THREAD

**Issue by Marielis24** [benjjneb/dada2#616]
Hello,

I am new using DADA2 and R. I did everything is suggested on the tutorial to get the ASVs tables and assign taxonomy. Now I want to plot my data according to the metadata. I am importing the .txt file but I do not know how to merge the file with the DADA2 taxonomic tables.

This the Code:

metadata <- read.table("Data//Sampled Data for R//1_MappingFile_BIT477_Fall2018_SampledData.txt", header=TRUE, sep = "")
print(metadata)

MD <-merge_phyloseq(seqtab.nochim,metadata) 

This is the output:

> metadata <- read.table("Data//Sampled Data for R//1_MappingFile_BIT477_Fall2018_SampledData.txt", header=TRUE, sep = "")
> print(metadata)
   SampleID              ForwardFastqFile              ReverseFastqFile TreatmentGroup
1       1-1  1-1_S61_L001_R1_001.fastq.gz  1-1_S61_L001_R2_001.fastq.gz        Group_1
2       1-2  1-2_S51_L001_R1_001.fastq.gz  1-2_S51_L001_R2_001.fastq.gz        Group_1
3       1-3  1-3_S41_L001_R1_001.fastq.gz  1-3_S41_L001_R2_001.fastq.gz        Group_1
4       1-4  1-4_S32_L001_R1_001.fastq.gz  1-4_S32_L001_R2_001.fastq.gz        Group_1
5       1-5  1-5_S24_L001_R1_001.fastq.gz  1-5_S24_L001_R2_001.fastq.gz        Group_1
6       1-7  1-7_S17_L001_R1_001.fastq.gz  1-7_S17_L001_R2_001.fastq.gz        Group_1
7       1-8   1-8_S9_L001_R1_001.fastq.gz   1-8_S9_L001_R2_001.fastq.gz        Group_1
8      1-10  1-10_S1_L001_R1_001.fastq.gz  1-10_S1_L001_R2_001.fastq.gz        Group_1
9      1-12 1-12_S62_L001_R1_001.fastq.gz 1-12_S62_L001_R2_001.fastq.gz        Group_1
10     1-15 1-15_S52_L001_R1_001.fastq.gz 1-15_S52_L001_R2_001.fastq.gz        Group_1
11     1-16 1-16_S42_L001_R1_001.fastq.gz 1-16_S42_L001_R2_001.fastq.gz        Group_1
                        Description
1                  Tucker_Hall_Sink
2                          Sullivan
3                    North_Res_Hall
4                1402_Varsity_Drive
5  Tompkins_Hall_Women_BR_2nd_floor
6                       Leazar_Hall
7                    Owen_Hall_Sink
8                      Carroll_Hall
9                  Campus_Edge_sink
10           Tucker_Hall_Sink_drain
11                      Bragaw_Hall
> 
> MD <-merge_phyloseq(seqtab.nochim,metadata)
Error in arglist[sapply(arglist, is.component.class)] : 
  invalid subscript type 'list'
> enprint

I have "dada2" version ‘1.8.0’ and my R version is:

platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.1                         
year           2018                        
month          07                          
day            02                          
svn rev        74947                       
language       R                           
version.string R version 3.5.1 (2018-07-02)
nickname       Feather Spray 

Thank you!

**Comment by alexiscarter** [comment]
Hi,

Not sure I understand well your question but to create your phyloseq object (that contains sequence table + taxonomic table + metadata) you can use this code as shown at the end of the tutorial:
`ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE), 
               sample_data(samdf), 
               tax_table(taxa))
`
Here, the sequence table is `seqtab.nochim`, the taxonomic table is `taxa` and the metadata is `samdf`

Hope it helps,
Ciao

**Comment by benjjneb** [comment]
Thanks @alexiscarter 
I agree that the next step you want is to move into phyloseq. DADA2 is focused on the initial processing of the amplicon sequencing data into a feature (and taxonomy) table, but at that point a tremendous number of analysis options become available through phyloseq: https://joey711.github.io/phyloseq/tutorials-index.html

**Comment by Marielis24** [comment]
Thank you for your help! I already solved the problem.

I actually wanted to load my metadata and merged that with the results from DADA2 in phyloseq. The problem was that the samples name on my metadata file did not match with the samples name in the ASVs tables from DADA2. I solved adding row.names=1 to assign my first column on the metadata as the sample name. Here is the code I use:

library("phyloseq"); packageVersion("phyloseq")

library(ggplot2); packageVersion("ggplot2")

theme_set(theme_bw())

#Import Metadata 
metadata <- read.table("Data//Sampled Data for R//1_MappingFile_BIT477_Fall2018_SampledData.txt", header=TRUE, sep = "", row.names = 1)
print(metadata)

#Convert Metadata in a Phyloseq Object
MD <-phyloseq(sample_data(metadata))

#Check if sample names match with your sequencing data
sample_names(MD)

#Create Phyloseq Object combining metadata, ASVs Tables, and Taxonomy Assigned
ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE), tax_table(taxa), MD)
ps
