### ISSUE TITLE
denoisedF and denoisedR filter too much2

### ISSUE THREAD

**Issue by AgustinPardo** [benjjneb/dada2#619]
Referring to https://github.com/benjjneb/dada2/issues/554
I review the dada2 tutorial. Maybe the problem of to much denoise is in the Learn the Error Rates step. 
My plotError of R1 is:
![erro1](https://user-images.githubusercontent.com/14830537/48915440-6a719d00-ee5d-11e8-88d2-1cdb32405a33.png)

I'm using DADA2 over samples that came from differents sequencing runs.
Is it okay to use the DADA2 pipeline using samples of differents runs?

The error rates are calculate for each sample independently?
If the error rates are calculated by a portion of all the data ( mixing data from samples of the differents runs), the calculation of errors should not be done by sample?
What do you think about it?

_Originally posted by @AgustinPardo in https://github.com/benjjneb/dada2/issue_comments#issuecomment-441083397_

**Comment by benjjneb** [comment]
Closing in favor of keeping it in the prevously posted issue.
