### ISSUE TITLE
dada2 very slow

### ISSUE THREAD

**Issue by lmanchon** [benjjneb/dada2#621]
--Hi,

I use qiime2 and started dada2 analysis, the program has been running for 2 days, I use 40 cores, the program is frozen at this stage:
R version 3.4.1 (2017-06-30)
Loading required package: Rcpp
DADA2 R package version: 1.6.0

    Filtering …
    Learning Error Rates
    Not all sequences were the same length.
    Not all sequences were the same length.
    2a) Forward Reads
    Initializing error rates to maximum possible estimate.
    Sample 1 - 6451496 reads in 5919870 unique sequences.

is there a way to make it faster ?

thank you --

**Comment by ebolyen** [comment]
Hi @lmanchon, we try to avoid crossposting the same question as it ends up being more work for everyone. Let's keep the discussion over here: https://forum.qiime2.org/t/dada2-very-slow-step/7136
