### ISSUE TITLE
PacBio functional gene amplicon ( bssA) seq data analysis with DADA2? - primers not removed

### ISSUE THREAD

**Issue by zinuska** [benjjneb/dada2#625]
Hello,

I have a project where I have paralelly sequenced 16S and the functional gene bssA (for anaerobic toluene degradation) amplicons in various microbial communities. I am developing a workflow to analyze my data. So far I had a mixed workflow combining mothur (to correct the mixed orientation) and qiime1. As I understand, DADA2 would be a much better option for me in combination with SMRTLink.
Before I go deeper into DADA2, I have a question:

My bssA in-house database has been created in ARB and contains aligned sequences of very different formats: some full operons, and many sequences of the alpha-subunit of my gene (what I actually target myself), where many amplicon sequences were obtained with different primers. Therefore, it was my PIs decision to not cut the primers off of the sequences (for traceability and whatsoever). 
This would disqualify my data for DADA2 as I understand.
Is there still a way to overcome this issue?
If I remove the primers from my current dataset, than assigning taxonomy using my in-house database would not give an exact match, right?.

Regards,
Anna

**Comment by benjjneb** [comment]
> it was my PIs decision to not cut the primers off of the sequences (for traceability and whatsoever). This would disqualify my data for DADA2 as I understand.

Do the primers you are working with contain ambiguous nucleotides? If so, then yes that will be a problem with DADA2. If not, then it is fine to carry them along.

> If I remove the primers from my current dataset, than assigning taxonomy using my in-house database would not give an exact match, right?.

I don't see why that will alter your ability to assign against your reference database. You can still have an exact match over the portion sequenced, even if a little bit (e.g. the primer region) is different at the beginning or end, and that will be equally effective for assigning taxonomy.

**Comment by zinuska** [comment]
Thank your for you answer, it was very helpful! 
Yes, I have unfortunately highly degenerate primers, but as I understand from the second part of your answer, I can just trim them off and then it won`t be a problem anymore. 
I am trying to modify now (just started) the LRAS Manuscript`s Fecal Samples Rmd to make it work on my samples. I have read that a PacBio tutorial is planned for the future, will it maybe soon available?

**Comment by zinuska** [comment]
Dear bejjneb,, 

as I was going through the pipeline, I got stuck at assign taxonomy and got this error message:  Incorrect reference file format for assignTaxonomy.
So I guess the problem is with my database. I have read the documentation to this command and it says the database should be formatted as >Kingom;Phylum;Class;Order;Family;Genus; ACGAATGTGAAGTAA. But catabolic/non-phylogenetic marker gene databases don`t have this kind of resolution. 
Do you have any suggestions how to deal with this, how to reformat my database correctly?
Do I at all need an aligned reference database if I work with ASVs or just a list of reference sequences are fine? I am sorry to ask such a basic question.  

Best,
Anna

**Comment by benjjneb** [comment]
> Do I at all need an aligned reference database if I work with ASVs or just a list of reference sequences are fine?

Yes, just use a list of sequences. In fact, they shouldn't be aligned.

> Do you have any suggestions how to deal with this, how to reformat my database correctly?

Can you show what your ID lines currently look like? What level of taxonomic ranking do you have for your sequences?
