### ISSUE TITLE
fastqPairedFilter Error : Error in add(bin) : internal: buf != <newline>

### ISSUE THREAD

**Issue by Zander22** [benjjneb/dada2#63]
Hi guys,

I am really enjoying your great software. I have processed one set of samples on dada2 and it worked great. With a second set of samples from a different sequencing run I get an error when running fastqPairedFilter. I am thinking that it might be some format issues with my fastq files (used an external demultiplexing tool), but I have checked them and they seem fine. The headers and quality information still seems okay.

Any ideas?

Thanks,
Zander

**Comment by Zander22** [comment]
The problem is definitely with my FASTQ files. Samples from previous runs work fine and the error persisted with fastqFilter with individual files. Will demultiplex the samples in a different way and try it again.

Thanks,
Zander

**Comment by benjjneb** [comment]
Closing, but feel free to re-open if problem persists. This sounds like a problem outside the scope of the dada2 package though, especially since dada2 relies on the ShortRead package for parsing fastq files via `ShortRead::FastqStreamer`.

**Comment by joey711** [comment]
are there any low-weight diagnostics we could include to help inform users who run into the same problem? Do we have an idea of what the problem is other than happening during `FastqStreamer`?
