### ISSUE TITLE
Combining 454 and Illumina data sets: different sequence coverage

### ISSUE THREAD

**Issue by lgulmann** [benjjneb/dada2#633]
Hello –
 I have a question about combining different sequencing runs, specifically illumina and 454 runs.

For reference -  Samples Include:
•	Hydrothermal vent marine samples, time series over 10 years
•	DNA:sequenced region: 16S rRNA V1+2+3  PRIMERS 27F/519R (region length: ~453 bases; with primers removed)

I have 3 separate sequencing runs: 2 with 454 and 1 with Illumina MiSeq, each with primer set 27F/519R. 

I wanted to ask for advice on the best way to combine the results from these three run.

With the Illumina PE run – I’ll have all 453 bp covered (entire fragment, primers removed).  
With the 454.26.10 runs – I’ve trimmed to 375 bp (maintaining a quality score ~30)
With the 454.CS.11.14 runs – I’ll trim to 325 bp (to maintain a quality score of ~25)

I plan to use the script
mergeSequenceTables
mergetab <- mergeSequenceTables(seqtab1, seqtab2, seqtab3) 

But do I need to cut all sequences to the shortest fragment size (325bp) to compare across runs? 
Or is there a better approach to avoid discarding sequence data?

(Also - would you suggest running removeBimeraDenovo() on the combined table?)

Thank you very much for your time and help!

(The Quality profiles are identified as Illumina.4901.pdf; 454.CS.11.14; 454.26.10)
(I've Also included error plots from 454.26.10 run)
[Illumina.4901.pdf](https://github.com/benjjneb/dada2/files/2658388/Illumina.4901.pdf)
[454.CS.11.14.pdf](https://github.com/benjjneb/dada2/files/2658390/454.CS.11.14.pdf)
[454.26.10.pdf](https://github.com/benjjneb/dada2/files/2658391/454.26.10.pdf)
[ERRORplots_2610only_375bp_MaxEE_2.pdf](https://github.com/benjjneb/dada2/files/2658392/ERRORplots_2610only_375bp_MaxEE_2.pdf)

Here is a subset of the pipeline scripts run for 454.26.10 data
> filtered_out <- filterAndTrim(forward_reads, filtered_forward_reads, maxEE=c(2), rm.phix=TRUE, multithread=TRUE, minLen=225, truncLen=c(375))

> dada_forward <- dada(derep_forward, err=NULL, HOMOPOLYMER_GAP_PENALTY=-1, BAND_SIZE=32, selfConsist=TRUE, USE_QUALS=TRUE, multithread=TRUE)
Initializing error rates to maximum possible estimate.
selfConsist step 1 ......
   selfConsist step 2
   selfConsist step 3
   selfConsist step 4
   selfConsist step 5
   selfConsist step 6
   selfConsist step 7
Convergence after  7  rounds.
> seqtab <- makeSequenceTable(dada_forward, orderBy = "abundance")
> seqtab.nochim <- removeBimeraDenovo(seqtab, multithread=T, verbose=T)
Identified 15 bimeras out of 1073 input sequences.
> sum(seqtab.nochim)/sum(seqtab)
[1] 0.981973

**Comment by benjjneb** [comment]
> But do I need to cut all sequences to the shortest fragment size (325bp) to compare across runs?

Yes, for the ASVs from each different sequencing run to merge appropriately when using `mergeSequenceTables` they must cover exactly the same genetic locus, which means starting at the same position (probably enforced by your primers) and extending for the same length.

> Or is there a better approach to avoid discarding sequence data?

I don't think there is, at least not without introducing biases between the resolution afforded by runs with different sequence lengths. One can always drill down a bit more into the data from the longer runs, but for cross-run analyses it is almost always the right choice to make the data as consistent as possible.

**Comment by yuranz4** [comment]
Hello, I have a follow up question:

I have data from two sequencing runs: one run on MiSeq using primers 515F/926R, and the other run on 454 using primers 515F/806R. Samples sequenced in the two runs are different. 

Now I'd like to compare the samples in the two runs (i.e. analyze beta diversity among these samples) and use distance metric like Unifrac to quantify similarity between samples. So it seems like I should process the sequences from the two runs all together using dada2 workflow, construct phylogenetic tree, then calculate Unifrac distance.

Now my questions is: from this post it seems like I should trim my MiSeq sequences (515F/926R) to the same length as the 454 sequences (515F/806R), before processing all data together. Could I get some suggestions on how to do that? Should I just assume all my MiSeq (515F/926R) sequences will contain the 806R reverse primer region, and maybe use cutadapt to trim them with 806R primer? 

Thanks in advance!!

**Comment by nhungdoan1905** [comment]
Hi, guys!
Now I am analyzing 454 data set, which was converted in to fastq to follow dada2. However, when I used filterandtrim function, my output file contained all symbol, not sequences and/or ASCII character. I try to process these files individually, the results still be like that. 
e.g 13.TCA.454Readss.fastq reads.in 36044 reads.out 26822 and the filtered file contain symbols like this  ¬ã        ÏΩÈÇ‰∂Õ6˙ˇªï3”›U•}ß(â™ƒÒ €Â8Œ˝_»¡ Pµ‘“”›3ˆ
How can I solve this problem?

**Comment by benjjneb** [comment]
@nhungdoan1905 The output files are gzipped by default. If you want uncompressed fastq files, set `compress=FALSE` when calling `filterAndTrim`. You can see more information in the help documentation for the function: `?filterAndTrim`

**Comment by nhungdoan1905** [comment]
@benjjneb Thank you so much!!! It worked!

**Comment by Balakulandai** [comment]
@lgulmann  Hi i am very new to dada2,  and working with 454 amplicon sequences, can you share the command lines for 454 amplicon sequence in dada2.
