### ISSUE TITLE
mergePairs breaks when no reads remain from denoising

### ISSUE THREAD

**Issue by ChristophSchmid** [benjjneb/dada2#636]
Hello there,

I just finished debugging our institute's DADA2 pipeline. Two of my colleagues had negative controls which had a very low amount of reads and (accordingly) bad read quality in these control samples. While this is probably a good thing, it turns out that the mergePairs() function breaks with the following error:

> Error in `$<-.data.frame`(`*tmp*`, nmatch, value = 0) :
  replacement has 1 row, data has 0

I traced it back to the dada() function obviously removing all the sequences from the samples and thereby breaking mergePairs().

I remember that DADA2 used to work with those kind of negative samples. In any way, I think the function should return something reasonable and not throw an error. A 0 reads sample later on in the sequence table, maybe with a warning message, would be in my opinion be the better solution.

Cheers,
Christoph

**Comment by benjjneb** [comment]
What version are they using? An bug in that zero-read case was introduced in 1.8, but should be fixed in the new release 1.10.

**Comment by ChristophSchmid** [comment]
Thanks for the quick reply!

Yes, indeed the pipeline is still at version 1.8, since I first need to find the time to check if our code works completely with the new version. 

Ok, thanks. Problem solved :)
