### ISSUE TITLE
learnErrors

### ISSUE THREAD

**Issue by lmanchon** [benjjneb/dada2#637]
--Hi,

I have big paired-end data (80 samples 150bp long) and I am following workflow, i have run learnErrors directly from R with: errF <- learnErrors(filtFs, nbases=1e6, multithread=TRUE)
it's take very long time, it's running  since 3 hours and not yet finished.

Do you think i need to run dada2 analysis on each sample (80) and them merge tables ?

thank you --

**Comment by benjjneb** [comment]
The `learnErrors` step can be the longest step for some datasets. Are you seeing any output over time (e.g. `selfConsiste step 3` and such)? If so, I would just let it finish.

**Comment by lmanchon** [comment]
yes, i have this message:
Initializing error rates to maximum possible estimate.
Sample 1 - 5924254 reads in 5126107 unique sequences.
   selfConsist step 2

but it's frozen since 1 day.

**Comment by benjjneb** [comment]
I see, the issue is that this one sample has a very high number of unique sequences in it (>5M).
This is unusual for 150bp data. Have you performed any filtering, or possibly truncation of low quality tails on this data? What does the `plotQualityProfile` output look like?

**Comment by lmanchon** [comment]
yes, i have already filtered and trimmed reads with cutadapt.
Which parameters are usually used for 150bp paired-end in denoising step because i have no idea:
--p-trim-left-f ? --p-trim-left-r ? --p-trunc-len-f ? --p-trunc-len-r ?

**Comment by benjjneb** [comment]
It depends on the length of the amplicon you are sequencing. The priorities are first to ensure that after truncation the reads still overlap enough to merge, and that second bad quality bases at the tails are removed.

Which amplicon are you sequencing/what is its expected length? What are the quality profiles of the F/R reads?

**Comment by lmanchon** [comment]
--Hi,
you can check the quality profiles of my libraries here: https://forum.qiime2.org/t/dada2-very-slow-step/7136/13
see demux.qzv file.
It's before trimming step.
As i have 80 big samples, do you think it will be more appropriate to run dada2 in a for-loop statement to treat each sample separately ? Because the learning errors step takes too much time with 80 samples.
thank you --

**Comment by benjjneb** [comment]
What amplicon are you sequencing, and what is the setup (i.e. were primers included)?
Can you post just the figure of the quality profiles?

**Comment by lmanchon** [comment]
I just know it's amplicon 16s RNA but I don't know its size.
I received 80 samples sequenced in 2x150bp paire-end using the Nextera XT kit with these adapters:

>PrefixNX/1
AGATGTGTATAAGAGACAG
>PrefixNX/2
AGATGTGTATAAGAGACAG
>Trans1
TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG
>Trans1_rc
CTGTCTCTTATACACATCTGACGCTGCCGACGA
>Trans2
GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG
>Trans2_rc
CTGTCTCTTATACACATCTCCGAGCCCACGAGAC

see in attachment quality profiles of raw data.
![quality_profile](https://user-images.githubusercontent.com/3015749/50307831-c1d54e00-0499-11e9-890e-337edefcddef.png)

As I have already said, the best way would be for me to send you a sample of sequences.
I tried 2 versions of qiime2 with a dada2 and deblur analysis, and it takes a lot of time (2 days to process a single library). I also tried the dadaR package directly, and  same problem. I don't understand why.

**Comment by benjjneb** [comment]
The most useful thing you can do at this point is to go back to your collaborator and get the full information on: what amplicon was sequenced including the primers used, whether primers were included in the sequenced amplicon, and any other particularities about the library prep or amplicon sequencing setup (e.g. were heterogeneity spacers possibly used)? Furthermore, some idea of what environment these are coming from would be helpful.

That information is invaluable in trying to diagnose what is going on. Your data is very deep, but more importantly has a very high fraction of unique sequences, which is unusual for short 16S data with quality scores as high as shown in that plot. I suspect there is something else going on here, and that information requested above would go a long way towards figuring that out.

**Comment by lmanchon** [comment]
I know DNA were extracted and amplified by PCR using specific primers targeting hypervariable regions of the 16S rRNA gene. DNA are provided by 80 Swab samples (intestinal biopsy).
An example of a library (the smallest) here: https://filesender.renater.fr/?s=download&token=c2384bea-636b-674d-4bb9-7ea4a20df996
