### ISSUE TITLE
dereplication asv sequences after merging multiple seqtabs

### ISSUE THREAD

**Issue by yunha** [benjjneb/dada2#638]
I have data from multiple sequencing runs and I merged the seqtabs using mergeSequenceTables() following the tutorial. However, I am seeing that the resulting ASVs have duplicates/triplicates because the ASV determining step for each sample came before mergeSequenceTables() and the same ASVs don't seem to have been merged at the mergeSequenceTables() step. Is this an expected behaviour? and if so, how can I fix it so that only unique ASVs remain in the merged table? (with the respective abundances summed)

**Comment by benjjneb** [comment]
dereliction sounds bad!

What is the output of the following: `table(table(getSequences(st.all))`?

**Comment by yunha** [comment]
> table(table(getSequences(st.all)))
        1 
11239

**Comment by benjjneb** [comment]
That indicates there are no duplicated ASVs in `st.all`. What suggests to you that there are?

**Comment by yunha** [comment]
Oh, you are right, now that I look more closely they are actually different! and I meant dereplication oops, dereliction does sound bad!
