### ISSUE TITLE
How to exclude plant 16S DNA

### ISSUE THREAD

**Issue by nimhong** [benjjneb/dada2#639]
Hi,
    When I used dada2 to analyse my data, and don't know how to filter chloroplast and mitochondria sequences. And I found some scripts in qiime2, it is quite easy to filter. Should I use qiime2 to do that? Or I missed something in the dada2 tutorial?  

   Thanks.

**Comment by jgrzadziel** [comment]
Using phyloseq plugin you can filter out any data.
For example (when using RDP trainset):

```
run16S = subset_taxa(run16S, 
                   Family  != "mitochondria" &
                     Class   != "Chloroplast")
```

**Comment by nimhong** [comment]
The question looks so stupid. I am a beginner. Anyway, thank you so much!!
