### ISSUE TITLE
Confusion of the results

### ISSUE THREAD

**Issue by zhouyunyan** [benjjneb/dada2#640]
Hi,
I have been using dada2 to produce a FeatureTable based on the Qiime2 platform. The total number of feature is 19,530, 
![default](https://user-images.githubusercontent.com/42016367/50323784-51204700-0516-11e9-86c6-4cfab640f5c5.png)

Then further filtering features that show up in only one or a few samples with a  threshold value of 5%, there are only 233 features left,  
![default](https://user-images.githubusercontent.com/42016367/50328672-fa733700-052e-11e9-8548-79df1a9b2677.png)

From 19,530 to 233 ,I am not sure whether this result is right or not, and most of them only observed in a small sample. This results in a large number of zero in the abundance table,  I am not sure if such a table can be used for GWAS.
![default](https://user-images.githubusercontent.com/42016367/50328807-a2890000-052f-11e9-8cd2-0cf8f72f3fb3.png)
Are there any parameters that can be adjusted to improve the results?
Thanks! any thoughts are appreciated!

**Comment by benjjneb** [comment]
I'm not sure if there is a problem here. You've filtered to only include features that appear in >X samples at >5% of the sample? That will of course greatly reduce the number of features (ASVs)...

Is there an issue I am not seeing? At first glance I am not that surprised at what you have reported.

**Comment by zhouyunyan** [comment]
the most abundant feature only observed in 149 samples, most of features are observed in less than 50 samples. The total number of samples is 633, I think there are many core bacteria in the gut,it shouldn't be so few common bacteria  between samples. I wonder if there is something wrong with my input file. the sequence that forward and reversed reads have been assembled and primers, adapters are trimmed.
I used it as a single ended sequence for analysis and for Dada2 chose --p-trim-left 0 and --p-trunc-len 0, (don't make any trim). Is this an acceptable way of using this data for analysis?

**Comment by benjjneb** [comment]
Sorry for the delay, was off for the holidays.

> I used it as a single ended sequence for analysis and for Dada2 chose --p-trim-left 0 and --p-trunc-len 0, (don't make any trim). Is this an acceptable way of using this data for analysis?

Yes, but...

> I wonder if there is something wrong with my input file. the sequence that forward and reversed reads have been assembled and primers, adapters are trimmed.

Given that you are doing no trimming/truncation in DADA2, it is critical that the trimming/truncation done upstread was identical for each sample. Is it possible that some samples were trimmed or truncated at different positions? One thing that would be worth looking at is the distribution of ASV lengths, i.e. `table(nchar(getSequences(seqtab.nochim)))`. If some samples were trimmed differently than others, they will not be identical in the final table.

> the most abundant feature only observed in 149 samples, most of features are observed in less than 50 samples. The total number of samples is 633, I think there are many core bacteria in the gut,it shouldn't be so few common bacteria between samples.

To be honest I'm not really sure how core different gut ASVs would be. My "gut feeling" is that there should be some that would appear at least in a large majority of samples, but maybe that's not the case. There certainly are much more core genera, for example, but could there be a lot of ASV-level variation w/in those genera and person-to-person?

**Comment by zhouyunyan** [comment]
Thank you for you reply. But I still don't fully understand it.
The length of sequences are different in the result. 
![default](https://user-images.githubusercontent.com/42016367/50718589-2ca69c00-10cc-11e9-8559-0e48bc1fd28c.png)
It is QC plot that forward and reversed reads have been assembled .
![default](https://user-images.githubusercontent.com/42016367/50718619-72636480-10cc-11e9-86c0-7a293b947778.png)
But if the length was trimmed to the same length with minimum length, It loses a lot of sequences.
Whether all sequences must be trimmed  to the same length?

**Comment by benjjneb** [comment]
How have you pre-processed these reads? The recommended DADA2 pipeline processes the F/R reads independently, and only merges them after denoising. Am I correct in thinking you have pre-merged the reads before using DADA2?

**Comment by zhouyunyan** [comment]
Yes, the reads have been pre-merged before using DADA2. Pre-processed include remove barcode and primers , then quality control, merge F/R reads, these are completed by company.  Can the merged reads and after QC be analysis using DATA2?

**Comment by benjjneb** [comment]
I would recommend that you get the raw data from the sequencing provider. 

Demultiplexing is fine, but it is recommended to work with the data before it has been merged or QC-ed in unknown ways by the sequencing provider, so I think this is your best course of action at this point.

**Comment by zhouyunyan** [comment]
ok, thank very much. So the sequencing company only needs to remove the barcode and primers, Then I can import directly the data to DATA2 pipeline for analysis.

**Comment by benjjneb** [comment]
Yep. Primer removal is OK, but you can even easily remove primers yourself. To run through DADA2 you just want the demultiplexed (i.e. split into per sample files) fastq files with minimal if any additional processing.

**Comment by liquidambar** [comment]
@zhouyunyan I am dealing with the same condition you met. Many of my reads only found in a few samples. Did you find the problem and resolution for it?
