### ISSUE TITLE
dada2 execution halted

### ISSUE THREAD

**Issue by lmanchon** [benjjneb/dada2#641]
--Hi,

dada2 failed after one week with:
Creating output directory: /home/QIIME/RAW_DATA/FWD/filtered
Creating output directory:/home/QIIME/RAW_DATA/REV/filtered
498459920 total bases in 6230749 reads from 1 samples will be used for learning the error rates.
467306175 total bases in 6230749 reads from 1 samples will be used for learning the error rates.
Processing: lib-1
Sample 1 - 6230749 reads in 5379391 unique sequences.
Sample 1 - 6230749 reads in 5537794 unique sequences.
Error in table(pairdf$forward, pairdf$reverse) :
  attempt to make a table with >= 2^31 elements
Calls: mergePairs -> lapply -> FUN -> table
Execution halted

One week to process only 1 library and it failed.  I have 80 libraries to process.

this is the script i used:

#!/usr/bin/env /usr/bin/R-3.5.1/Rscript
library(dada2)
pathF <- "/home/QIIME/RAW_DATA/FWD"
pathR <- "/home/QIIME/RAW_DATA/REV"
filtpathF <- file.path(pathF, "filtered")
filtpathR <- file.path(pathR, "filtered")
fastqFs <- sort(list.files(pathF, pattern="_R1.fastq.gz"))
fastqRs <- sort(list.files(pathR, pattern="_R2.fastq.gz"))
if(length(fastqFs) != length(fastqRs)) stop("Forward and reverse files do not match.")
filterAndTrim(fwd=file.path(pathF, fastqFs), filt=file.path(filtpathF, fastqFs), rev=file.path(pathR, fastqRs), filt.rev=file.path(filtpathR, fastqRs), minLen=75, truncLen=c(80,75), maxN=c(0,0), maxEE=c(5,5), truncQ=11, rm.phix=c(TRUE, TRUE), compress=TRUE, verbose=TRUE, multithread=TRUE)
filtFs <- list.files(filtpathF, pattern="_R1.fastq.gz", full.names = TRUE)
filtRs <- list.files(filtpathR, pattern="_R2.fastq.gz", full.names = TRUE)
sample.names <- sapply(strsplit(basename(filtFs), "_"), `[`, 1)
sample.namesR <- sapply(strsplit(basename(filtRs), "_"), `[`, 1)
if(!identical(sample.names, sample.namesR)) stop("Forward and reverse files do not match.")
names(filtFs) <- sample.names
names(filtRs) <- sample.names
set.seed(100)
errF <- learnErrors(filtFs, nbases=1e4, multithread=TRUE)
errR <- learnErrors(filtRs, nbases=1e4, multithread=TRUE)
mergers <- vector("list", length(sample.names))
names(mergers) <- sample.names
for(sam in sample.names) {
  cat("Processing:", sam, "\n")
    derepF <- derepFastq(filtFs[[sam]])
    ddF <- dada(derepF, err=errF, multithread=TRUE)
    derepR <- derepFastq(filtRs[[sam]])
    ddR <- dada(derepR, err=errR, multithread=TRUE)
    merger <- mergePairs(ddF, derepF, ddR, derepR)
    mergers[[sam]] <- merger
}
rm(derepF); rm(derepR)
seqtab <- makeSequenceTable(mergers)
saveRDS(seqtab, "/home/QIIME/seqtab.rds")

I work on computer with 64G of RAM and 16 cores.

**Comment by lmanchon** [comment]
--Hi, 

as i already said I just know it's amplicon 16s RNA but I don't know its size.
I received 80 samples sequenced in 2x150bp paired-end using the Nextera XT kit with these adapters:

    PrefixNX/1
    AGATGTGTATAAGAGACAG
    PrefixNX/2
    AGATGTGTATAAGAGACAG
    Trans1
    TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG
    Trans1_rc
    CTGTCTCTTATACACATCTGACGCTGCCGACGA
    Trans2
    GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG
    Trans2_rc
    CTGTCTCTTATACACATCTCCGAGCCCACGAGAC

You can try with one library (the smallest) here: 
https://filesender.renater.fr/?s=download&token=c2384bea-636b-674d-4bb9-7ea4a20df996

**Comment by benjjneb** [comment]
19/20 sequences I tried mapped to the human genome. The one other sequence mapped to a non-16S part of a bacteria.

This isn't 16S data. I'm guessing it is shotgun data from human samples. You need to go back to your provider or collaborator and understand what this data actually is, or you're not going to make any progress.

**Comment by lmanchon** [comment]
maybe it's a peculiarity of this library, but it's strange.
That's why there are so many unique sequences in Learning Error Rates step , isn't it?

**Comment by benjjneb** [comment]
yes
