### ISSUE TITLE
Concerns in error rate estimation with "learnErrors"

### ISSUE THREAD

**Issue by Wizardren** [benjjneb/dada2#645]
Hi Ben,
I was using DADA2 for Illumina Hiseq 250 pair-end sequence analysis. I have 49 samples which were sequenced bacteria 16s v3-v4 region.(Primer 515F & 907R) The sequence error rate estimation with function _**learnErrors**_ seemed unsual. While modled errors fit well with actural errors, the overall error rate didn't decline clearly with increased Quality. And most error rates were above 0.01.
      I continued the subsequent analysis, which gets about 600 ASVs per sample, and a total of 10,000s ASVs. The samples were from paddy soil from one same region, so I think they should't be distantly ditributed. I wonder there might be some problems in the error rate estimation. 
     Should I accept the result or turn to alternate pipeline? Thank you very much!

**Comment by benjjneb** [comment]
Did you solve this issue?

If not and you are still interested in help, could you post the `plotErrors` graphs so I can see your results? It would be also useful to know the number of unique sequences per sample for a couple of your samples (e.g. the printed output of `derepFastq(fnF)`).
