### ISSUE TITLE
PCA looks bizarre

### ISSUE THREAD

**Issue by piquan64** [benjjneb/dada2#647]
Hi Ben,

I've run the dada2 pipeline on raw .fastq files; everything runs ok but the subsequent PCA plots I create from the phyloseq object are highly suspect. I've tried running the pipeline multiple times with different parameters for trimming and truncating. I've also tried doing a PCA with normalized (via metagenomeSeq) otu values. I end up with the same (or similar) plot:

![image](https://user-images.githubusercontent.com/38793753/50848313-2fee9180-1331-11e9-9e71-70a414856820.png)

Everyone I've shown this to agrees something is wrong, but can offer no reasons why.

here is the code I used to create the object:
##############################
library(dada2)
library(phyloseq)
library(phangorn)
library(ggplot2)
library(DECIPHER)

path<-"/rsgrps/ledith/data/LEO_iTag/water/splitfiles/splitall"

fnFs <- sort(list.files(path, pattern = "-1.fastq", full.names = TRUE))
fnRs <- sort(list.files(path, pattern = "-2.fastq", full.names = TRUE))

sample.names <- sapply(strsplit(basename(fnFs), "-"), `[`,1)

filt_path <-file.path(path, "filtered")

filtFs <- file.path(filt_path, paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(filt_path, paste0(sample.names, "_R_filt.fastq.gz"))

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen = c(250,225), trimLeft = c(24,23), maxN = 0, maxEE = c(2,2), truncQ = 2, rm.phix = TRUE, compress = TRUE, multithread = TRUE)

errF <- learnErrors(filtFs, multithread = TRUE)
errR <- learnErrors(filtRs, multithread = TRUE)

plotErrors(errF, nominalQ = TRUE)
ggsave(file.path(getwd(), 'errF.pdf'))
plotErrors(errR, nominalQ = TRUE)
ggsave(file.path(getwd(), 'errR.pdf'))

derepsFs <- derepFastq(filtFs, verbose = TRUE)
derepsRs <- derepFastq(filtRs, verbose = TRUE)

names(derepsFs) <- sample.names
names(derepsRs) <- sample.names

dadaFs <- dada(derepsFs, err=errF, multithread=TRUE)
dadaRs <- dada(derepsRs, err=errR, multithread=TRUE)

mergers <- mergePairs(dadaFs, derepsFs, dadaRs, derepsRs, verbose=TRUE)

seqtabw <- makeSequenceTable(mergers)

seqtab.nochimw <- removeBimeraDenovo(seqtabw, method="consensus", multithread=TRUE, verbose=TRUE)

taxaw <- assignTaxonomy(seqtab.nochimw, "~/downloads/silva_nr_v132_train_set.fa.gz", multithread=TRUE)
taxaw <- addSpecies(taxaw, "~/downloads/silva_species_assignment_v132.fa.gz")

saveRDS(seqtab.nochimw, file = "seqtab.nochimw.rds")
saveRDS(taxaw, file = "taxaw.rds")

seqw<- readRDS("/home/u16/yorman/downloads/seqtab.nochimw.rds")
taxw<- readRDS("/home/u16/yorman/downloads/taxaw.rds")
samdfw <- read.table("/home/u16/yorman/downloads/mapfilereducedw.txt",header=TRUE)
rownames(samdfw) <- samdfw$SampleID
identical(rownames(seqw), rownames(samdfw))
ps1w <- phyloseq(otu_table(seqw, taxa_are_rows=FALSE), tax_table(taxw),sample_data(samdfw))
saveRDS(ps1w, file = "ps1w")
    
seqsw <- getSequences(seqw)
names(seqsw) <- seqsw
    
alignmentw <- AlignSeqs(DNAStringSet(seqsw), anchor=NA)
saveRDS(alignmentw, file = "alignmentw.rds")
    
phang.alignw <- phyDat(as(alignmentw, "matrix"), type="DNA")
saveRDS(phang.alignw, file = "phang.alignw.rds")

dmw <- dist.ml(phang.alignw)
saveRDS(dmw, file = "dmw.rds")

phang.alignw<- readRDS("/home/u16/yorman/downloads/phang.alignw.rds")
dmw<- readRDS("/home/u16/yorman/downloads/dmw.rds")

treeNJw <- NJ(dmw)
saveRDS(treeNJw, "tree")

fitw = pml(treeNJw, data=phang.alignw)

fitGTRw <- update(fitw, k=4, inv=0.2)

fitGTRw <- optim.pml(fitGTRw, rearrangement = "stochastic", ratchet.par = list(iter = 10L, maxit = 10L, prop = 1/3))
detach("package:phangorn", unload=TRUE)
saveRDS(fitGTRw, "fit")

ps2w <- phyloseq(otu_table(seqw, taxa_are_rows=FALSE), tax_table(taxw),sample_data(samdfw), phy_tree(fitGTRw$tree))
saveRDS(ps2w, "ps2w")

######################
Here are the error rates:
[test.pdf](https://github.com/benjjneb/dada2/files/2737876/test.pdf)
[test1.pdf](https://github.com/benjjneb/dada2/files/2737877/test1.pdf)

And after filtering
[errF.pdf](https://github.com/benjjneb/dada2/files/2737878/errF.pdf)
[errR.pdf](https://github.com/benjjneb/dada2/files/2737879/errR.pdf)

Any troubleshooting ideas you have would be greatly appreciated. I'm sure I'm messing something up in the pipeline...

Thanks.

**Comment by benjjneb** [comment]
That looks to me like three different batches of samples that do not overlap at all (i.e. have no ASVs in common).

Are there multiple processing batches in your data? E.g. sequencing runs? Are there multiple sample types in your data? e.g. water and stool?

What is the output of `summary(colSums(seqw>0)/ncol(seqw))`?

**Comment by piquan64** [comment]
There are 2 sequence runs. There is a column in the mapping file called "replicate" with 3 level. All sample types are from water discharge. However, if I subset the phyloseq object by any of these variables, the PCA is largely unchanged. Perhaps I need to rerun the pipeline with the fastq files subset by sequence run or something?

The output of summary(colSums(seqw>0)/ncol(seqw)) yields:

    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
4.84e-05 4.84e-05 9.67e-05 3.17e-04 3.87e-04 2.13e-03 

Thanks!

**Comment by benjjneb** [comment]
What is the size of your `seqw`? i.e. `dim(seqw)`?

I am confused by the output of `summary(colSums(seqw>0)/ncol(seqw))`. This should be telling us about the fraction of samples that each ASV is present in, and the highest value is 0.002...

Actually, is `seqw` oriented so that the samples are rows? Or are the ASVs the rows?

**Comment by piquan64** [comment]
Output below

> dim(seqw)
[1]   163 20680
> 

Here is a look at otu_table from the phyloseq object (adjusted for NAs)

> OTU Table:          [10 taxa and 10 samples]
                     taxa are columns
                      Seq1 Seq2 Seq3 Seq4 Seq5 Seq6 Seq7 Seq8 Seq9 Seq10
1_168_Nov11_1530_E_1     0    0   35    0 1356    0    0    0    0     0
10_161_Nov18_1610_E_1    0  434    0    0    0  452    0    0    0     0
100_153_Dec8_2100_E_1    0 1028    0    0    0 1714    0    0    0     0
101_146_Dec8_2100_W_1    0    0    0    0    0    0 7235 4804    0     0
103_116_Dec8_2100_E_2    0 9908    0    0    0 5770    0    0    0     0
104_227_Dec8_2100_W_2    0    0    0    0    0    0 6444 1973    0     0
105_188_Dec8_2100_C_2    0    0    0    0    0    0 4681 6565    0     0
106_129_Dec8_2100_E_3    0    0 2273    0 1341    0    0    0    0   745
107_150_Dec8_2100_W_3    0    0    0    0    0    0 6323 2264    0     0
109_202_Dec9_0800_E_1    0 3031    0    0    0 2803    0    0    0     0
>

**Comment by piquan64** [comment]
Oddly if I do: 
summary(colSums(otu_table(ws1)>0/ncol(otu_table(ws1))))

I get 

Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  0.000   1.000   2.000   6.458   8.000  40.000 

This should be the same as seqw, right?

And just to be super sure, we wanted the print out for seqw, not seqsw, right?

**Comment by benjjneb** [comment]
Actually `seqtabw` is different in different parts of your code, so I think that might be causing some confusion. Can you just go back to `seqtab.nochimw` instead? In particular, what are the results of:

```
dim(seqtab.nochimw)
summary(colSums(seqtab.nochimw))
summary(colSums(seqtab.nochimw>0))
```

**Comment by benjjneb** [comment]
Thanks that is useful. So, the ASV that is most widely shared amongst all samples is present in only 44/163 samples. Typically that is very low if all these samples are of the same type, and it makes me suspect there may be batch issues related to the processing/merging of these samples.

Can you post the results of `dada2:::pfasta(getSequences(seqtab.nochimw)[1:10])`?

**Comment by benjjneb** [comment]
The issue is that you have essentially identical sequences that are being split apart because they vary slightly in length due to some batch or sample-specific aspect of your processing. For example:

```
# sq <- c(the sequences above)
nwhamming(sq[[1]], sq[[3]])
```

> [1] 0

```
nwalign(sq[[1]], sq[[3]])
```

>[1] >"TACGGAGGGTGCGAGCGTTGTCCGGAATCACTGGGCGTAAAGGGCGCGTAGGTGGTTCGATAAGTGTGTGGTGAAAGCCCGGGGCTCAACCCCGGGTCTGCCGTGCAAACTGTCGGACTGGAGGACTGCAGAGGCAGGTGGAATTCCGGGTGTAGCGGTGGAATGCGTAGAGATCCGGAAGAAGACCGGTGGCGAAGGCGACCTGCTGGGCAGTTTCTGACACTGAGGCGCGACAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGGGCACTAGGTCTCTGGGGGAGCGACCCCCTGGGGGCCGACGCAAACGCATGAAGTGCCCCGCCTGGGGAGTACGGCCGCAAGGCT"
>[2] >"TACGGAGGGTGCGAGCGTTGTCCGGAATCACTGGGCGTAAAGGGCGCGTAGGTGGTTCGATAAGTGTGTGGTGAAAGCCCGGGGCTCAACCCCGGGTCTGCCGTGCAAACTGTCGGACTGGAGGACTGCAGAGGCAGGTGGAATTCCGGGTGTAGCGGTGGAATGCGTAGAGATCCGGAAGAAGACCGGTGGCGAAGGCGACCTGCTGGGCAGTTTCTGACACTGAGGCGCGACAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGGGCACTAGGTCTCTGGGGGAGCGACCCCCTGGGGGCCGACGCAAACGCATGAAGTGCCCCGCCTGGGGAGTACGGCCGCAAGGC-"

They are identical except for the first sequence has one more base than the third sequence.

You need to identify where in your processing this is happening. This is probably due to how you truncated/trimmed the data. Did you do filtering/trimming outside of DADA2? Or entirely within it? Did you use the same trimming/truncation parameters throughout? In particular, `trimLeft`? Did you use the exact same primers for each sample?

You can also use `collapseNoMismatch` on your sequences table to largely fix this issue (it will collapse together ASVs that differ only by terminal gaps), but it's a good idea to understand where in your processing this came up.

**Comment by piquan64** [comment]
Wow, very helpful.

All processing was done in dada2, with trimLeft = c(24,23) in the above code. 

itags were 2x250bp sequencing on Miseq with 16S-V4-V5 primers on all samples:
FW (515F-Y): 5'-GTGYCAGCMGCCGCGGTAA-3’
RV (926R): 3’-CCGYCAATTYMTTTRAGTTT-5' (revcomp 5’-AAACTRAAAMYAATTYGCGG-3') 

The documentation for collapseNoMismatch looks rather straightforward, so I'll try that out and see what the plot looks like. Anything else I should consider? Could my reads be backwards or something?

Thanks for all your help!

**Comment by piquan64** [comment]
Yay! 

![image](https://user-images.githubusercontent.com/38793753/51938721-0b835380-23cb-11e9-87d2-349c58390d62.png)
