### ISSUE TITLE
concatenating reads

### ISSUE THREAD

**Issue by ggloor** [benjjneb/dada2#65]
Is it possible to concatenate reads in the instance where the forward and reverse reads do not overlap?

**Comment by benjjneb** [comment]
Yes, there is a `justConcatenate` option in the `mergePairs(...)` function. This will concatenate the reads, inserting 10Ns between the concatenated reads. If you wish to remove the inserted Ns, you can `gsub` them away in the output sequences, or replace them with a separator of your choice. Eg.

```
foo <- mergePairs(dadaF, derepF, dadaR, derepR, justConcatenate=TRUE)
foo$sequence <- gsub("NNNNNNNNNN", "sep-string", foo$sequence)
```

**Comment by ggloor** [comment]
thank you. Missed that option
