### ISSUE TITLE
filterAndTrim issue

### ISSUE THREAD

**Issue by ntromas** [benjjneb/dada2#651]
Hi,

I got this error several times (but not all the time...This is where it is weird, sometimes it works without any pb) when I run filterAndTrim() (all previous steps from the tutorial worked well)

filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(250,200),maxN=0, maxEE=c(2,6), rm.phix=TRUE, compress=TRUE, multithread=FALSE)

Error in x$yield(...) : 
  _DNAencode(): invalid DNAString input character: 'F' (byte value 70)

packageVersion("dada2")
[1] ‘1.10.1’

Any idea? 

Thanks!

Nico

**Comment by benjjneb** [comment]
I think this is suggesting that your fastq file you are trying to filter has some "F" characters in the DNA lines. Is that possible?

**Comment by ntromas** [comment]
Mojave 10.14.2 (18C54)
R version 3.5.2

**Comment by benjjneb** [comment]
I don't know and never seen or heard about this error before...

If you can find a way to reproduce it I would be very interested.

**Comment by ntromas** [comment]
The pb is to reproduce it as it seems random!
