### ISSUE TITLE
low reads counts after makeSequenceTable

### ISSUE THREAD

**Issue by lucaz88** [benjjneb/dada2#652]
Ciao,
I am using dada2 on PacBio sequences for the first time and I got a weird result after running the `makeSequenceTable` function. I got only 10,000 reads mapped to the detected ASVs (`sum(seqtab)`) while I had 0.8M (dereplicated) reads as input for the `dada` function. Why?
I cannot figure out what I did wrong or how to solve the issue.. here is the code I am running:

```
drp <- derepFastq(filt, verbose=T)
err <- learnErrors(drp, errorEstimationFunction=PacBioErrfun, BAND_SIZE=32, multithread=ncore, nbases=2e8, randomize=T, verbose=T)
# error plot looks very nice
dd <- dada(drp, err=err, BAND_SIZE=32, multithread=ncore, pool=T, verbose=T)
seqtab <- makeSequenceTable(dd)
```

Thanks in advance for any advice!

**Comment by benjjneb** [comment]
PacBio functionality is newer, and it would help if you would give us a bit more information:

Which PacBio sequencing instrument/chemistry are you using?
What amplicon are you sequencing and what is its expected length?
What quality filtering did you preform (e.g. the `filterAndTrim` call) and what fraction of reads passed?
Also if you could post the `plotErrors` plot that would help too.

**Comment by lucaz88** [comment]
Sure! so going with order:

> Which PacBio sequencing instrument/chemistry are you using?

Sequencing libraries were built using the SMRTbell Template Prep Kit 1.0‐SPv3. DNA template libraries were bound to the Sequel polymerase 2.0 using the Sequel Binding Kit 2.0 (Pacific Biosciences, USA). Samples were run in a single Sequel SMRT Cell 1M v2 with 600 min movie time on the Sequel Sequencing Plate 2.0 (Pacific Biosciences, USA).

> What amplicon are you sequencing and what is its expected length?

We sequenced the full 16S rRNA gene and the expected length is ~1500 bp.

> What quality filtering did you preform (e.g. the filterAndTrim call) and what fraction of reads passed?

I did it on my own using cutadapt and checking with FastQC. >90% of reads passed the quality filtration step.

> Also if you could post the plotErrors plot that would help too.

![image](https://user-images.githubusercontent.com/13884965/51118391-8f0c4480-1810-11e9-8433-7350c9197b00.png)

**Comment by benjjneb** [comment]
Two more Qs: What environment are you sequencing?
And what is the output printed out by the `derep-class` objects? e.g. `derepFs[c(1,5,10)]`

**Comment by lucaz88** [comment]
> Two more Qs: What environment are you sequencing?

Urban freshwater and lakes.

> And what is the output printed out by the derep-class objects? e.g. derepFs[c(1,5,10)]

```
$`ccs.0_0-ALL.fastq`
derep-class: R object describing dereplicated sequencing reads
$uniques: 13368 reads in 13362 unique sequences
  Sequence lengths: min=1393, median=1474, max=1500
$quals: Quality matrix dimension:  13362 1500
  Consensus quality scores: min=2, median=93, max=93
$map: Map from reads to unique sequences:  11579 11480 6223 7079 8583 ...

$`ccs.102_102-ALL.fastq`
derep-class: R object describing dereplicated sequencing reads
$uniques: 7944 reads in 7941 unique sequences
  Sequence lengths: min=1387, median=1470, max=1500
$quals: Quality matrix dimension:  7941 1500
  Consensus quality scores: min=2, median=93, max=93
$map: Map from reads to unique sequences:  4870 5963 5964 1886 6670 ...

$`ccs.107_107-ALL.fastq`
derep-class: R object describing dereplicated sequencing reads
$uniques: 8021 reads in 8017 unique sequences
  Sequence lengths: min=1393, median=1471, max=1500
$quals: Quality matrix dimension:  8017 1500
  Consensus quality scores: min=2, median=93, max=93
$map: Map from reads to unique sequences:  4567 533 1194 4588 4870 ...
```

**Comment by benjjneb** [comment]
> $uniques: 13368 reads in 13362 unique sequences
> $uniques: 7944 reads in 7941 unique sequences
> $uniques: 8021 reads in 8017 unique sequences

This is the problem. There is virtually no repeated observations of any reads in your data. DADA2 relies on the error-free reads appearing as a decent fraction of the data, and therefore yielding repeated observations of the true sequences that separate them from non-repeated errors. That isn't happening in your dataset. Unfortunately I think you will have to use another tool here that works at a lower-resolution.

This begs the question though of why, as we've had good success with the Sequel 2/2 chemistry, seeing upwards of 30% error-free 16S reads. One possible culprit could be your PCR, as PCR contributes errors just like sequencing. A second thing to consider if you haven't tried it is to do primer trimming using the `dada2:::removePrimers` function in our PacBio workflow, just to rule out the possibility of this being caused by an issue with that pre-processing step.

**Comment by lucaz88** [comment]
I tried quite some tools to remove the adaptors but nothing... when I run the `derepFastq` I always get only a few replicated reads. However, if I extract only a subregion of the whole 16S (like 357F-1391R) I start to get at least ~1% of replicated sequences. What would be a min replication value to safely use dada2?

**Comment by benjjneb** [comment]
You really want to have a good fraction of repeated reads, perhaps 20% and up, otherwise you are very restricted on your ability to detect ASVs outside of the most abundant variants.
