### ISSUE TITLE
ASVs are too identical

### ISSUE THREAD

**Issue by phumNewen** [benjjneb/dada2#653]
Hi everybody!
Thanks to developers for great pipeline!
I faced a following problem: ASVs generating by DADA2 on my dataset are really numerous and similar.
The data is really big: about 200 paired-end 16S samples with the coverage of 100k reads.
I have tested pooling and `OMEGA_A` value changing.
I checked some resulting ASV sequences against nr/nt NCBI Blast collection and I found that two different ASVs are 99% identical to the same strain from the collection. Moreover two ASVs can be 99% identical to a number of same strains.
How can I make my ASVs more specific?
Or sholud I use some additional tool for clustering ASVs?

**Comment by phumNewen** [comment]
Some bacteria have more then one 16S rRNA operons and it may cause a problem if their sequences are not completely identical because two sequence from one bacteria can be reffered to distinct ASVs oru OTUs. Isn't it?
But my problem is different. Negative controls removing seems ineffective because of multiple extremely similar ASVs: some of them are presented innegatives, some -- in samples.
They don't match and don't remove with negatives subtraction. But they are so similar that are 99% identical to the same large list of strains from NCBI collection from which I suppose this two sequences belong to one organism.
In my idea if two sequences can be associated with a number of the same strains, how can we divide them between each other? Why they appear separately?
Or may be I don't understand the sense of ASVs? Is ASV some general representation of multiple very similar sequences?

**Comment by benjjneb** [comment]
> Is ASV some general representation of multiple very similar sequences?

ASVs are our best attempt at reconstructing the true sequences that were in the sample. That's it, they aren't trying to be a representation of anything other than what they are, DNA sequences.

16S ASVs can serve very well as tags or barcodes of various microbial taxa, but they aren't an attempt to recapitulate species. If there are many distinguishable variants of, say, _F. prauznitsii_ in your samples, you will see many distinct ASVs from that species. You can read more on ASVs [in this paper](https://doi.org/10.1038/ismej.2017.119).

> But my problem is different. Negative controls removing seems ineffective because of multiple extremely similar ASVs: some of them are presented innegatives, some -- in samples.
They don't match and don't remove with negatives subtraction. 

In my experience you should not remove ASVs from your true samples that did not (at a minimum) appear in the negative controls. Having a similar ASV in the negative controls is not a good reason to remove. And you should be very wary of cross-contamination between samples as a mechanism by which true taxa appear in negative controls. [We have a recent paper on the contamination issue](https://doi.org/10.1186/s40168-018-0605-2) which might be helpful.
