### ISSUE TITLE
Error in add(bin) : internal: buf != <newline> when plotting Quality profile and filtering.

### ISSUE THREAD

**Issue by colinaverill** [benjjneb/dada2#654]
This error has come up in several threads, I think most recently summarized here (issue [#497](https://github.com/benjjneb/dada2/issues/497)).

I've copied an issue file, but all my files have this problem. Files are de-multiplexed per sample 454 data, which seem to have primers, barcodes and adapters already trimmed. When I load files I get a warning that there is no end of file character, however, if I go in and add a line to end of the file I still get the below errors (either adding a blank new line or adding `\n` on the new line). I have also re-downloaded raw files, errors remain. Here is some example code to reproduce the errors:

[example.txt](https://github.com/benjjneb/dada2/files/2756451/example.txt)
(this .fastq renamed to .txt so I could upload directly here)

```
seq.file <- 'path/to/example.txt' 
output.path <- 'path/to/filtered.txt'

plotQualityProfile(seq.file)
Error: internal: buf != <newline>

out <- filterAndTrim(seq.file, output.path, maxN = 0, maxEE = 2, 
                     truncQ = 2, minLen = 50, rm.phix = TRUE, compress = TRUE, multithread = F)
Error in add(bin) : internal: buf != <newline>

```
Check that the number of characters in sequence vs. qual lines is the same.
```
foo <- readLines(seq.file)
seqlens <- sapply(foo[seq(2,length(foo),4)], nchar)
quallens <- sapply(foo[seq(4,length(foo),4)], nchar)
table(seqlens); table(quallens)
table(seqlens) == table(quallens)
```

**Comment by colinaverill** [comment]
This is super helpful, thanks Ben. Surprised I didn't catch it when I did my own comparison of sequence vs. quality line lengths.

**Comment by benjjneb** [comment]
Thanks for the well described error case. I think this will be helpful, because you are right this has popped up multiple times and we never figured it out before. I suspect this was probably the issue in all those previous instances.

**Comment by syaliny** [comment]
Hi @benjjneb , I am having a similar issue with the filterandTrim

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(140,150),
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=FALSE, matchIDs=TRUE) 

but my error message is slightly different : Error in add(raw()) : internal: buf != <newline>

Could you please help me with this ?

Thanks

**Comment by benjjneb** [comment]
Can you follow the approach followed earlier in this issue thread to try to hone in on what is causing the error?
