### ISSUE TITLE
issue with writefasta command

### ISSUE THREAD

**Issue by Hanif82** [benjjneb/dada2#655]
Hello, 

      I am trying develop a fasta file of a single taxonomic group so that I may use it for an alignment in another package (ex. msa or DECIPHER). However whenever I use the writeFasta command, I return the error: 
Error in writeFasta(mollps, "molluscseq.fasta") : 
  could not find function "writeFasta"
mollps is my phyloseq formal class

i have also tried to do this using the write.FASTA command in the ape package with this error:
Error in write.FASTA(mollps, "molluscseq.fasta") : 
  data are apparently neither DNA nor AA sequences

i have also tried to do this using the following set of code
## making and writing out standard output files:
# giving our seq headers more manageable names (ASV_1, ASV_2...)
asv_seqs <- colnames(seqtab.nochim)
asv_headers <- vector(dim(seqtab.nochim)[2], mode="character")

for (i in 1:dim(seqtab.nochim)[2]) {
  asv_headers[i] <- paste(">ASV", i, sep="_")
}

# fasta:
asv_fasta <- c(rbind(asv_headers, asv_seqs))
write(asv_fasta, "ASVs.fasta")
head(asv_fasta)

# count table:
asv_tab <- t(seqtab.nochim)
row.names(asv_tab) <- sub(">", "", asv_headers)
write.table(asv_tab, "ASVs_counts.txt", sep="\t", quote=F)

# tax table:
asv_tax <- alltaxa
row.names(asv_tax) <- sub(">", "Veneroida", asv_headers)
write.table(asv_tax, "ASVs_taxonomy.txt", sep="\t", quote=F)

for (i in $(awk '$2 == "Veneroida"' ASVs_taxonomy.txt | cut -f1); \
     grep -A1 ">$i" ASVs.fasta); \
done

all work except for the final step where i get the error messages"
for (i in $(awk '$2 == "Veneroida"' ASVs_taxonomy.txt | cut -f1); \
Error: unexpected '$' in "for (i in $"
>      grep -A1 ">$i" ASVs.fasta); \
Error: unexpected string constant in "     grep -A1 ">$i""

so my questions are? 
why isnt the DADA2 command writeFasta not working?
how do I fix the for loop in the last code to make it work?
Is there a better or more straight forward way of doing this? At the end of the day and in the future, I would like to be able to have Fasta files of taxa of interest. 

Thanks

**Comment by benjjneb** [comment]
The dada2 R package doesn't have a function `writeFasta`. There is a function `uniquesToFasta` that migth do what you want.

But maybe you want the function `writeFasta` in the ShortRead package? Something like this probably does what you want:

```
library(ShortRead)
writeFasta(object = ShortRead(sread = DNAStringSet(seqs),
                                id = BStringSet(ids))
```
