### ISSUE TITLE
Processing MiSeq data together with 454 data -different primer coverage

### ISSUE THREAD

**Issue by yuranz4** [benjjneb/dada2#656]
Hello, I have a follow up question regarding issue #633 :

I have data from two sequencing runs: one run on MiSeq using primers 515F/926R, and the other run on 454 using primers 515F/806R. Samples sequenced in the two runs are different.

Now I'd like to compare the samples in the two runs (i.e. analyze beta diversity among these samples) and use distance metric like Unifrac to quantify similarity between samples. So it seems like I should process the sequences from the two runs all together using dada2 workflow, construct phylogenetic tree, then calculate Unifrac distance.

**Now my questions is:** from post #633  it seems like I should trim my MiSeq sequences (515F/926R) to the same length as the 454 sequences (515F/806R), before processing all data together. Could I get some suggestions on how to do that? Should I just assume all my MiSeq (515F/926R) sequences will contain the 806R reverse primer region, and maybe use cutadapt to trim them with 806R primer? 

Thanks in advance!!

**Comment by benjjneb** [comment]
> it seems like I should trim my MiSeq sequences (515F/926R) to the same length as the 454 sequences (515F/806R)

Yep.

> Could I get some suggestions on how to do that?

We have not developed tools for this specific problem. What you want to do is to match the 806R primer against the Miseq data, and cut where it starts. There are certainly multiple ways out there to do that, including command line programs like cutadapat, but also R packages such as DECIPHER.

**Comment by yuranz4** [comment]
> We have not developed tools for this specific problem. What you want to do is to match the 806R primer against the Miseq data, and cut where it starts. There are certainly multiple ways out there to do that, including command line programs like cutadapat, but also R packages such as DECIPHER.

Thanks a lot for your suggestion. I just tried looking at my MiSeq reverse read raw fastq files (926R). I opened the file with TextEdit and tried simply searching for primer sequences to get an idea of whether a primer sequence is really there. 

**However**, although I was able to find 926R primer sequence at the start of every reverse read (which make sense), I was NOT able to locate a significant number (i.e. >1,000 out of 48,000+ reads) of 806R primer sequences or even just partial 806R sequence in the fastq file. Nor do the partial 806R sequence matches show up at expected location (i.e. 926 - 806 =  ~120bp downstream the start of a reverse read). Anyone has an idea why this is the case? I suspect cutadapt won't work if the 806R sequence doesn't even show up much in the files.

Can I maybe just process my MiSeq PE250 pair-end reads as normal --learn error, quality filter, merge, etc., then after I get the merged amplicon sequences, simply trim off the last 120bp?

Thanks a lot!

**Comment by yuranz4** [comment]
Quick update (issue still not resolved): 
I tried cutadapt using 806R primer sequence to trim my MiSeq(515F/926R) reverse reads. As suspected, it did not work. There are just not many 806R sequences in the reverse read. See below screenshot of cutadapt run summary:
<img width="395" alt="screen shot 2019-01-16 at 2 23 05 pm" src="https://user-images.githubusercontent.com/13951229/51282625-74fe6d80-199a-11e9-8a81-2b74b1617e59.png">
which makes me wonder, for any given 16S amplicon that contains other primer sequence(s) within its coverage, will the "other primer sequence" really be present in most amplicon reads? (say, 806R sequence in a 515F/926R amplicon; or, 515F sequence in a 341F/806R amplicon)  In theory it seems they should, because we are talking about universal primers whose sequences should be present in every microbe 16S, but I wonder in reality whether we are really able to see this in the sequence reads?

**Back to my original problem... In my previous comment I asked if I could simply trim off 120bp from the right after merging the MiSeq(515F/926R) paired end reads, however after reading #424 I realize that will not account for variability in 16S amplicon length, hence not necessarily cover exactly 515-806 region. Is that still okay?? (I eventually plan to do `mergeSequenceTables` on the 454(515F/806R) reads and trimmed MiSeq(515F/926R)reads, and learned from #633  that I need to first make sure the sequences to be combined by `mergeSequenceTables` target exactly the same 16S region)**

If there's a better way to do this please feel free to suggest. Thanks in advance!!

**Comment by benjjneb** [comment]
Probably the easiest approach would be to truncate all your sequences, from both read techs, at a fixed length from their beginning. This is because they both start at the same place: 515F.

As you pointed out, trimming off bases from the end doesn't quite work because of variability in amplicon length, but truncating to a common fixed length from a fixed start position is valid. And the V4 amplicon has highly conserved length, so truncating at say 250nts will lose very little information (natural length distro is ~252-255 nts).

**Comment by yuranz4** [comment]
Thanks very much for you suggestion! Is there a function in R with which I could truncate (merged) sequences in a sequence table to a certain length?  

It seems that truncating sequences in a sequence table (if possible) may also affect the relative abundance. How should I deal with that?

**Comment by benjjneb** [comment]
Truncate to a fixed length:

```
sq.100 <- substr(getSequences(seqtab), 1, 100)
```

Assign fixed length sequences to sequence table:

```
seqtab.100 <- seqtab
colnames(seqtab.100) <- sq.100
```

Collapse now identical ASVs together:

```
seqtab.100 <- collapseNoMismatch(seqtab.100)
```

**Comment by yuranz4** [comment]
Thanks so much for your help @benjjneb !!

Previously I mentioned:

>  I was NOT able to locate a significant number (i.e. >1,000 out of 48,000+ reads) of 806R primer sequences or even just partial 806R sequence in the fastq file. Nor do the partial 806R sequence matches show up at expected location (i.e. 926 - 806 = ~120bp downstream the start of a reverse read). Anyone has an idea why this is the case? 

It turned out that I put in the wrong 806R sequences... When I put the correct 806R sequences things worked out nicely. Stupid mistake:/

I will follow your initial suggestion and trim the reverse reads with 806R. Then continue from there. Thanks again!

**Comment by dadahan** [comment]
Ran into this and didn't see the commands to fix it. This worked for me. Posting for posterity sake:

```
~/user_data/software/bbmap/bbduk.sh in=R1.fastq in2=R2.fastq out=trimmed_R1.fastq out2=trimmed_R2.fastq literal=TTACCGCGGCKGCTGRCAC,ATTAGAWACCCBNGTAGTCC k=19 mink=10 edist=3 edist2=3 maxns=0 tbo ktrim=l rcomp=t copyundefined=t -da
```
