### ISSUE TITLE
dada2 big data: Error in rval[sapply(rval, is.character)] : invalid subscript type 'list'

### ISSUE THREAD

**Issue by TseWue** [benjjneb/dada2#659]
Hi there
I am trying to run the dada2 big data pipeline because I encounter an

_Error in add(bin) : 
  'Calloc' could not allocate memory (61676591 of 1 bytes)_

when trying to dereplicate the reverse reads in the standard pipeline. However, altough I follow the big data tutorial (https://benjjneb.github.io/dada2/bigdata_paired.html) I seem to get a type error. See the following code for description of the problem:

General info:
R.version:              
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.1                         
year           2018                        
month          07                          
day            02                          
svn rev        74947                       
language       R                           
version.string R version 3.5.1 (2018-07-02)
nickname       Feather Spray
    
### Big data pipeline:
library(dada2); packageVersion("dada2")
[1] ‘1.10.0’
 #### File parsing
pathF <- "C:/.../forward_reads"
pathR <- "C:/.../reverse_reads" 
filtpathF <- file.path(pathF, "filtered") 
filtpathR <- file.path(pathR, "filtered")
fastqFs <- sort(list.files(pathF, pattern="fastq.gz"))
fastqRs <- sort(list.files(pathR, pattern="fastq.gz"))
if(length(fastqFs) != length(fastqRs)) stop("Forward and reverse files do not match.")

#### Filtering:
out <- filterAndTrim(fwd=file.path(pathF, fastqFs), filt=file.path(filtpathF, fastqFs),
               rev=file.path(pathR, fastqRs), filt.rev=file.path(filtpathR, fastqRs),
               truncLen=c(240,170),trimLeft = c(20,22), maxEE=2, truncQ=10, maxN=0, rm.phix=TRUE,
               compress=TRUE, verbose=TRUE, multithread=FALSE)

Then the following error message ocurrs:

**Error in rval[sapply(rval, is.character)] : invalid subscript type 'list'**

Do you know how I could edit the script to avoid the type list?

Thanks a bunch!
Best,
Tse

**Comment by benjjneb** [comment]
This is happening because your filtering is throwing errors. What are the outputs of the following:

```
head(file.path(pathF, fastqFs))
head(file.path(filtpathF, fastqFs))
```

Also, what is the output when you try running the filtering on a single sample?

**Comment by TseWue** [comment]
Oh no I am so sorry, just realized that I forgot to adjust the parameter pattern= in the beginning... So sorry to have wasted your time! But thank you anyway!
