### ISSUE TITLE
Tree construction with DADA output files

### ISSUE THREAD

**Issue by jellyfish1111** [benjjneb/dada2#660]
Hi,

I am trying to construct a tree and using the workflow with with RAxML as suggested by geriarteS in this forum but I find the alignment after the conversion of dada output files is taking for ever compared to the raw DADA files. Could any one tell me if this is normal?  Why should the alignement take longer with the modification of the files if it is aligning the same sequences?

Thanks a lot for you help!!!!

This is the workflow: 

install.packages("devtools")
devtools::install_github("leffj/mctoolsr")
library(mctoolsr)
install.packages("seqinr")
library(seqinr)

seqtab.nochim1 <- seqtab.nochim
colnames(seqtab.nochim1) <- paste0("SV", 1:ncol(seqtab.nochim1))

taxtab <- assignTaxonomy(seqtab.nochim, "silva_nr_v132_train_set.fa.gz", minBoot = 50, tryRC = TRUE,
                         outputBootstraps = FALSE, taxLevels = c("Kingdom", "Phylum", "Class",
                                                                 "Order", "Family", "Genus", "Species"), multithread = TRUE,
                         verbose = TRUE)

taxtab1 <- taxtab
rownames(taxtab1) <- paste0("SV", 1:nrow(taxtab1))

#The SV table and SV sequences were exported also:
export_taxa_table_and_seqs<- function(seqtab.nochim, file_seqtab, file_seqs) {
  seqtab.t = as.data.frame(t(seqtab.nochim))
  seqs = row.names(seqtab.t)
  row.names(seqtab.t) = paste0("SV", 1:nrow(seqtab.t))
  outlist = list(data_loaded = seqtab.t)
  mctoolsr::export_taxa_table(outlist, file_seqtab)
  seqs = as.list(seqs)
  seqinr::write.fasta(seqs, row.names(seqtab.t), file_seqs)
}

export_taxa_table_and_seqs(seqtab.nochim,"SV_table.txt",
                           "SV_seqs.fa")

#Finally you can load your SV fasta file and align the sequences with DECIPHER:
fas <- "SV_seqs.fa"
seqs <- readDNAStringSet(fas)
seqs <- OrientNucleotides(seqs) ## I found duplicated SVs after I reoriented the sequences
alignment <- AlignSeqs(seqs, anchor=NA)

**Comment by benjjneb** [comment]
Can you clarify what is happening here. When is RaxML being called? What is the DECIPHER part doing? How did you determine that RaxML(?) is taking longer with the DADA2 denoised sequences than the original reads?

**Comment by jellyfish1111** [comment]
Sorry, I started from the beginning from a new R session and the alignment with DECIPHER worked properly.  However, I am waiting for the construction of the tree with RaxmML for more than 4 days already. I have 24000 sequences and I am running it on a Windows I5 with 32 Gb RAM. Could anyone tell me how long should I expect to wait. The CPU load is at 99% but it seems is not stuck for the moment... 

Many thanks for the help!!!!!

**Comment by jellyfish1111** [comment]
Finally I got access to a server and at least is progressing...
