### ISSUE TITLE
Different run same platoform

### ISSUE THREAD

**Issue by rahulnccs** [benjjneb/dada2#662]
Hey,
I've  sequencing data, sequenced in **two** MiSeq runs (same platoform). Do I need to process those separately and then merge as 
# Merge multiple runs (if necessary)
st1 <- readRDS("path/to/run1/output/seqtab.rds")
st2 <- readRDS("path/to/run2/output/seqtab.rds")

OR, Should I go combined analysis?

**Comment by benjjneb** [comment]
Our general recommendation is to process each run separately and then merge the tables.

**Comment by rahulnccs** [comment]
thanks
