### ISSUE TITLE
Use more explicit quality model in PacBio .bam format

### ISSUE THREAD

**Issue by brendanf** [benjjneb/dada2#664]
Apparently the  [.bam format output by Sequel](https://github.com/PacificBiosciences/PacBioFileFormats/blob/3.0/BAM.rst) includes separate quality values for substitution, deletion, insertion, and homopolymer length ("merge") errors, as well as alternate base calls for possible substitution and deletion errors. It would potentially be useful to use this more complex error model when calculating the probability that a PacBio read belongs to a given ASV.

**Comment by benjjneb** [comment]
Interesting to consider I did not know about that.
