### ISSUE TITLE
454 data processing

### ISSUE THREAD

**Issue by cwshin** [benjjneb/dada2#667]
Hello, I recently got 454 data (.sff) and trying to use a dada2 pipeline (https://benjjneb.github.io/dada2/tutorial.html), but have a problem.

I converted .sff to .fastq files using "R453Plus1Toolbox::sff2fastq". But the start point of dada2 tutorial recommends demultiplexed files without non-biologic nucleotides primers / linkers / etc..
So, I think I should pre-process my converted .fastq files, but I could not find out any manuals or programs for it.

I'm not a biologist and it's my first time to analyze the amplicon data, so I beg for your kind consideration and help.

Thank you.

**Comment by benjjneb** [comment]
The dada2 R package doesn't have a dedicated primer/adapter removal function. I would recommend taking a look at trimmomatic or cutadapt for that purpose.

**Comment by cwshin** [comment]
Thank you for your answer. I will check the programs for the pre-processing.
