### ISSUE TITLE
Not retaining very rare ASVs through DADA2

### ISSUE THREAD

**Issue by ntmarshall406** [benjjneb/dada2#668]
Hi all,

I have a question relating to the possible loss of rare ASVs in a dataset when run through DADA2.  To briefly explain my problem, I have a known ASV that is in 2 out of 13 samples in a dataset and at ~40 reads/sample and the entire dataset has ~700,000 reads.  If I run DADA2 on those two samples individually, the rare ASV stays within the dataset.  However, if I run DADA2 on all 13 samples simultaneously, the rare ASV is lost.  So that implies to me that it is so rare within the compete dataset (i.e., 80/700,000 reads), that DADA2 removes it.  This rare ASV sequence is not very close to any of the other ASVs (closest ASV is 19 bps different over 280bps), so I'm not sure why it is being thrown out.  Also it might be important to note, their are many ASVs that vary in size within this dataset, from 150-280 bps.

I am trimming the forward and reverse reads before running DADA2.  Here are two commands I use for DADA2, I have loosened many of the settings.  But these parameters do not appear to be the issue, since the rare ASV stays within the data if run on only the two samples it is in.

filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(165,165), maxN=5, maxEE=c(20,20), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=FALSE)

mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE, maxMismatch=20)

Please let me know if anyone has an idea on this issue.  

Thanks,
Nate

**Comment by benjjneb** [comment]
Are you using pooling or pseudo-pooling? If not, I don't understand why it would be thrown out either, as the samples should be being processed essentially identically if you are using the default independent-by-sample processing.

Are you performing chimera-checking? Is it possible the sequence is being removed as a chimera in the larger dataset?
