### ISSUE TITLE
Feature Request: Ion Torrent PGM

### ISSUE THREAD

**Issue by lefebvrf** [benjjneb/dada2#67]
Hi,  would you have a suggestion on how to tune dada2 for the PGM in a manner similar to 454 (issue #29 )

Thanks

**Comment by benjjneb** [comment]
Right now we do not have suggestions for Ion Torrent data. The defaults probably work OK, however it would be great to develop more specific parameter suggestions, especially as we have had requests to support Ion Torrent functionality from a couple other people as well.

I don't have any experience with Ion Torrent data, so what we need to move forward is (1) some expert knowledge about the structure of errors on that platform, and (2) Ion Torrent mock community datasets (or even amplicon-sequences clones) to test the tuned parameters.

**Comment by benjjneb** [comment]
Several Ion Torrent mock community datasets in this paper: http://bmcmicrobiol.biomedcentral.com/articles/10.1186/s12866-016-0738-z

The data is not yet public on SRA, but hopefully soon.

**Comment by benjjneb** [comment]
The Ion Torrent mock community data is now available: http://trace.ncbi.nlm.nih.gov/Traces/study/?acc=SRP071776

I've run two of the datasets through dada2 with default settings and evaluated them. 

Accuracy is good, but not as good as on Illumina data. In particular, the Ion Torrent data seems to sometimes make mistakes on two consecutive bases, which is sometimes inferred as a real variant by dada2. There also seem to be serious issues with the early bases, therefore I would strongly recommend trimming at least he first 5, and probably the first 15 bases of Ion Torrent data.

**Comment by benjjneb** [comment]
Closing this with the official recommendation of **trimming the first 15 bases** of Ion Torrent data. Otherwise the standard (Illumina) parameters work well for IT.
