### ISSUE TITLE
learnErrors output

### ISSUE THREAD

**Issue by lara-whoi** [benjjneb/dada2#672]
Hi Ben
One issue: when I run:  
  > err_forward_reads <- learnErrors(filtered_forward_reads, multithread=TRUE)

108052380 total bases in 400194 reads from 10 samples will be used for learning the error rates.

Output indicates that there are 400194 reads from 10 samples, but the dataset has 16 samples and ~  900,000.

Is it expected for fewer samples/reads to be used for learning error rates?

  thank you!

**Comment by lara-whoi** [comment]
Just wanted to refine my question - I dug deeper and found that learnErrors uses only up to 1 million reads, but why did my run cut out at 400194 reads?   Is anything gained by overriding the 1 million read limit?  Thank you!

**Comment by benjjneb** [comment]
> I dug deeper and found that learnErrors uses only up to 1 million reads, but why did my run cut out at 400194 reads?

We updated `learnErrors` in the most recent release to use a defined number of bases, which is 100 million by default. This scales better with different sequencing techs with different lengths. It looks like you reached 100 million bases with just those 400k reads.

You can increase this, but in typical cases we see negligible improvement in the error model with more data. However, there is no cost to increasing the amount of data used other than waiting a bit longer for the command to finish.
