### ISSUE TITLE
Problem in assingTaxonomy() ->  Expecting a string vector: [type=NULL; required=STRSXP]

### ISSUE THREAD

**Issue by TseWue** [benjjneb/dada2#677]
Hi Ben

Since I tried to use my handmade database on the paired-end big data dada2 pipeline the assignTaxonomy() function does not perform anymore (see here for history: https://github.com/benjjneb/dada2/issues/622). Anyhow, in the mean time I deinstalled and reinstalled R and RStudio and I also updated all the necessary packages (dada version 1.10.0,  R version 3.5.2). I am trying to run the pipeline just as described in the tutorial, with the identical silva db. Yet I still get the same peculiar error message:

_tax <- assignTaxonomy(seqtab, "C:/Illumina_DADA2/silva_nr_v132_train_set.fa.gz", multithread=FALSE)_
**Error in C_assign_taxonomy(seqs, rc(seqs), refs, ref.to.genus, tax.mat.int,  : 
  Expecting a string vector: [type=NULL; required=STRSXP].**

Do you have any idea on what I could do to avoid this error message? To me it looks like a type error but somehow the STRSXP originates from C language and I have no clue about that or how to change it... I also downloaded the silva db freshly, in case the file was manipulated but that didn't solve the problem either. 
Thank you for your support.

**Comment by benjjneb** [comment]
Can you post the output of `sessionInfo()` after loading the dada2 R package?

Also, what are the parameters of the compute environment you are using. Is this on a server? How much memory is available?

**Comment by TseWue** [comment]
Hi

For now I was running dada2 locally on my computer, however, I might change to the cluster later on. Anyway, as it worked once already (with the same input files) I was just a bit confused why it wouldn't work again with the same settings and parameters.

Here is the output of sessionInfo():
_> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=German_Switzerland.1252  LC_CTYPE=German_Switzerland.1252   
[3] LC_MONETARY=German_Switzerland.1252 LC_NUMERIC=C                       
[5] LC_TIME=German_Switzerland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rcpp_1.0.0

loaded via a namespace (and not attached):
[1] compiler_3.5.2 tools_3.5.2    gtable_0.2.0   yaml_2.2.0     grid_3.5.2_ 

Unfortunately we are a Windows institute (!nothing against it - just think that Linux based is handier for bioinformatics!) and I sometimes find it difficult to understand how I have to do things properly on this OS. However, we are currently having some reorganization of our IT division, do you think it would be worthy trying to run it on another OS / disconnected from the Institute server?

Thanks for your help!

**Comment by benjjneb** [comment]
I'll be honest, I really don't understand what is going on here, especially since its working sometimes and not others. My suggestion would be to try to run it on a unix based system (which includes Mac OSX). In general, windows does have more weird errors pop up, and I don't have a windows system to test on so they are harder for me to debug as well.

Sorry for the unsatisfying diagnosis, and let us know if it keeps happening on a non-windows system.

**Comment by saharbagheri** [comment]
@TseWue I have the same problem. Could you figure it out?

**Comment by TseWue** [comment]
@saharbagheri I switchet do Mac OS and it worked very fine. If you don't have one try to get access to a Linux-based cluster (many Universities offer that). I really don't get Windows at times... :-)

Good luck,
Tse
