### ISSUE TITLE
version update issues

### ISSUE THREAD

**Issue by ekarlsenayala** [benjjneb/dada2#679]
I am unable to get dada2 to install in the terminal. I've tried nearly every way to install it and its not working. The latest thing I tried was 

conda install bioconductor-dada2 

It downloaded dada2 but not the v1.3.3

I've also tried 
source("http://bioconductor.org/biocLite.R")
biocLite(suppressUpdates = FALSE)

which gives me the following error message:
1: In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘igraph’ had non-zero exit status
2: In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘stringi’ had non-zero exit status

Let me know if there is a better way to try to download the newest version of dada2

**Comment by benjjneb** [comment]
Have you looked at the dada2 installation page? https://benjjneb.github.io/dada2/dada-installation.html

For the current version:

> To install this package, start R (version "3.5") and enter:

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("dada2", version = "3.8")
```

You can see more here: https://www.bioconductor.org/packages/release/bioc/html/dada2.html

An alternative is to install from GitHub:

```
library(devtools)
devtools::install_github("benjjneb/dada2", ref="v1.10")
```

**Comment by ekarlsenayala** [comment]
Yes when I tried the

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("dada2", version = "3.8")

As you mentioned it gives me this message:


Warning messages:
1: In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘BiocParallel’ had non-zero exit status
2: In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘igraph’ had non-zero exit status
3: In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘stringi’ had non-zero exit status

Elena Karlsen-Ayala
Ph.D. Student
Dept of Plant Pathology - University of Florida
ekarlsenayala@ufl.edu<mailto:ekarlsenayala@ufl.edu>





On Feb 14, 2019, at 4:12 PM, Benjamin Callahan <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you looked at the dada2 installation page? https://benjjneb.github.io/dada2/dada-installation.html<https://urldefense.proofpoint.com/v2/url?u=https-3A__benjjneb.github.io_dada2_dada-2Dinstallation.html&d=DwMFaQ&c=pZJPUDQ3SB9JplYbifm4nt2lEVG5pWx2KikqINpWlZM&r=KLojKydH7_coxmozqg-uNwI82WAqUscDeEpdlFGDvFs&m=EwjyPcpEGeANL3jSR0CH043ciOrwfb-tTb1HY7bA9-c&s=RL0r_GifjU6d18bu7ZFJy8vuY19M-PvXFmbE8Gzgsbg&e=>

For the current version:

To install this package, start R (version "3.5") and enter:

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("dada2", version = "3.8")


You can see more here: https://www.bioconductor.org/packages/release/bioc/html/dada2.html<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.bioconductor.org_packages_release_bioc_html_dada2.html&d=DwMFaQ&c=pZJPUDQ3SB9JplYbifm4nt2lEVG5pWx2KikqINpWlZM&r=KLojKydH7_coxmozqg-uNwI82WAqUscDeEpdlFGDvFs&m=EwjyPcpEGeANL3jSR0CH043ciOrwfb-tTb1HY7bA9-c&s=j_O7UZSbN_SbmRT09HDU8AksTsQrIxwAim8wI_-GhbU&e=>

An alternative is to install from GitHub:

library(devtools)
devtools::install_github("benjjneb/dada2", ref="v1.10")

**Comment by benjjneb** [comment]
Do you just get warnings, or does the installation fail? What happens when you try `library("dada2")`?

Also, can you provide info on your R installation: `R.version`

**Comment by wlokhorst** [comment]
I encountered the same error message for the stringi package when installing the latest version of dada2.

However, I also found that this is an issue for more people trying to install stringi ([https://github.com/gagolews/stringi/issues/431](https://github.com/gagolews/stringi/issues/431)). 
It was recently patched, so stringi can now be installed via calling the following command from within R:
`devtools::install_github("gagolews/stringi")`
Source: [https://github.com/gagolews/stringi/issues/431#issuecomment-840380805](https://github.com/gagolews/stringi/issues/431#issuecomment-840380805)
