### ISSUE TITLE
Merging sample pairs gives 0 rows

### ISSUE THREAD

**Issue by marcomtzmtz** [benjjneb/dada2#681]
When I try to merge sample pairs I obtained 0 rows, I send the process. Thank you in advance..

[microbioma.pdf](https://github.com/benjjneb/dada2/files/2882251/microbioma.pdf)

**Comment by benjjneb** [comment]
You've truncated your reads too short for them to overlap, so all are being lost in merging.

To be honest, the quality of your reverse reads looks to be so poor (what kind of Illumina machine is this?) that I think I would just toss them and use the forward reads alone.

**Comment by marcomtzmtz** [comment]
Thank you for your help. I will try using only forward reads.
