### ISSUE TITLE
Error in add(bin) : record does not start with '@'

### ISSUE THREAD

**Issue by dcastaneda5** [benjjneb/dada2#686]
Hello,

I am currently having a problem when trying to filter my fastq files. When I run this command (as shown in the tutorial), I get this:

```
> out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
+                      maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
+                      compress=TRUE, multithread=TRUE)
Error in filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen = c(240, 160),  : 
  These are the errors (up to 5) encountered in individual cores...
Error in add(bin) : record does not start with '@'
Error in add(bin) : record does not start with '@'
Error in add(bin) : record does not start with '@'
Error in add(bin) : record does not start with '@'
Error in add(bin) : record does not start with '@'
In addition: Warning message:
In mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule,  :
  scheduled cores 3 encountered errors in user code, all values of the jobs will be affected
```

I made sure that I have the same number of lines for nucleotides and ASCII code for quality (see issue#685), and I also made sure that I had '@' in every read. Still the problem persists. Any ideas of what the problem might be?

Thanks a lot for your help!

**Comment by benjjneb** [comment]
Please don't open multiple issues for the same problem. This would be a useful additional post to the issue you already opened #685
