### ISSUE TITLE
Error:Filtering Error in filterAndTrim

### ISSUE THREAD

**Issue by zhouyunyan** [benjjneb/dada2#689]
I performed DADA2 on Qiime2 pipeline ,then it has a problem. 

qiime dada2 denoise-paired --i-demultiplexed-seqs paired-end-demux.qza --p-trim-left-f 0 --p-trim-left-r 0 --p-trunc-len-f 265 --p-trunc-len-r 230 --p-n-threads 0 --o-representative-sequences rep-seqs.qza --o-table table.qza --o-denoising-stats stats-dada2.qza

![default](https://user-images.githubusercontent.com/42016367/53158218-14e49200-35fe-11e9-826a-5f14a9e24ca9.png)

It is a big dada, a total of more than 5,300 samples, is this problem caused by this?

**Comment by benjjneb** [comment]
How did you preprocess your input fastq files? Previously this error arose because preprocessing steps resulted in fastq files with mismatched DNA and quality score lengths. See #654

**Comment by zhouyunyan** [comment]
The input fastq files just remove the barcodes and primers, it is done by company.  
This is the quality plot. I set the parameters : --p-trim-left-f 0 --p-trim-left-r 0 --p-trunc-len-f 265 --p-trunc-len-r 230,then generate the error message like that.
![default](https://user-images.githubusercontent.com/42016367/53179011-e383ba80-362d-11e9-9a87-543d77a9572c.png)

**Comment by benjjneb** [comment]
What I'd suggest is to identify a single sample that when processed throws this error, and then we can inspect that sample for potential issues.

**Comment by zhouyunyan** [comment]
I selected two subsets to analyze separately, one is finished successfully, the another generate the error message mentioned above. So that is caused by some files in this error subset. but why? 
how to solve problem.

**Comment by benjjneb** [comment]
> So that is caused by some files in this error subset. but why?

Once we narrow it down to a specific file that causes the issue we will probably be able to figure that out! Until then though it would just be guessing.

**Comment by zhouyunyan** [comment]
but there are too many samples,  how to find the specific error file?

**Comment by benjjneb** [comment]
Let's say samples 1-16 throw the error. Then try samples 1-8. If samples 1-8 throw the error, try samlpes 1-4, else if samples 1-8 don't throw the error, then a sample in 9-16 must, so try samples 9-12. And so forth follwoing that halving logic until you identify a sample that throws the error.

**Comment by zhouyunyan** [comment]
According your suggestion, the error sample was found, it is because of this sample that all samples cannot run successfully. But I am not sure which sequence caused the error, forward sequence  or reverse sequence. Then how to check the cause of the error.

**Comment by benjjneb** [comment]
The first thing to check is whether there is any mismatch between the sequence lines and ID lines, especially in their lengths, as such a length mismatch was what caused this error in the past.

I can take a look but you'll need to put the two files somewhere I can get them (I can't get them from the Baidu links since I can't read it). Can you email them to me? benjamin DOT j DOT callahan AT gmail DOT com

**Comment by zhouyunyan** [comment]
ok, the files have emailed to you, yunyanzhou@hotmail.com, Sample's name is 4900M,can you receive it?

**Comment by benjjneb** [comment]
No I don't think they went through.

**Comment by zhouyunyan** [comment]
Sorry, maybe I filled in wrong email address , I have sent it again.

**Comment by benjjneb** [comment]
There is one character missing from the quality scores in line 128204:

```
fnR <- "4990M.2.fq"
lines <- readLines(fnR)
lens <- nchar(lines)
seqlens <- lens[seq(2,length(lines), 4)]
quallens <- lens[seq(4,length(lines), 4)]
which(seqlens-quallens != 0)
```

> [1] 32051

```
cat(lines[(32051*4-3):(32051*4)], sep="\n")
```

> @M01929:275:000000000-AVFBR:1:1116:18153:20317 2:N:0:CACCGG
>ATCCTGTTTGCTCCCCCGACTTTCGCGCCTCAGCGTCAGTGCCGTTCAAGGAATCCGCCTTCGCCTCCGGTGTTCTATAGGATATCAACGCATTTCACCGCTACACCCTATATTCCGATTCCCTCTCCCAGACTCGAGTCCCGTAGTTTCAGACGCACTTTCCGGGTTGAGCCCGGAGATTTCACATCTGACACGCAAGACCGCCTACGCGCCCTTTACGCCCAGTAAATCCGAACAACGCTTGCGACCTCTGTATTACCGCGGCTGCTGGCACCAT
>+
>GDGGGGGDFGGFGGGEGGGGGGGGGGGGGGGGGGGGDGGGGGGGGFFGGGGGGGGGG4CFGGGDGGGGGFGGGGGGFGDFGGGGGGGGGGGGGGGGGGGGGGEGGFFDGDEEFCFGGGGC@DGGGGGFFGECCFGD9FFGGGGGGFACDDEGGG6CCEGGGGGGECFGGGGGGFGGGGGGGGGFFFFFC9BFFGGG7CEG4A>D=AC7CEGC5FEF+?CCEFF@FFFF=CGGDFE;4(8>FF7)7<..4?BF?49AAF009(996B?D(7)#####

No idea what would have caused that, but that is causing the error because mismatched length between the sequence and the quality string makes for a malformed fastq file. So either remove that entry from this sample or just drop this sample and you'll be OK.

**Comment by zhouyunyan** [comment]
Thank you for your help.
