### ISSUE TITLE
Error in assignTaxonomy using any reference database

### ISSUE THREAD

**Issue by drdee255** [benjjneb/dada2#691]
`taxa <- assignTaxonomy(seqs=seqtab.nochim,refFasta="silva_nr_v132_train_set.fa.gz",multithread=T,verbose=T,tryRC=F)
`
This command returning 

> Finished processing reference fasta.Error in C_assign_taxonomy2(seqs, rc(seqs), refs, ref.to.genus, tax.mat.int,  : 
  negative length vectors are not allowed

I am working on Linux machine with 24 cores and 128 GB RAM. It does not seem to me a memory problem.

**Comment by benjjneb** [comment]
Can you post the `sessionInfo()` just prior to the error?
Also, how did you install dada2 on this machine?

**Comment by drdee255** [comment]
Here is the output of sessionInfo()
`[1] RColorBrewer_1.1-2          pillar_1.3.1               
 [3] compiler_3.5.2              plyr_1.8.4                 
 [5] GenomeInfoDb_1.18.2         XVector_0.22.0             
 [7] bitops_1.0-6                tools_3.5.2                
 [9] zlibbioc_1.28.0             lattice_0.20-38            
[11] tibble_2.0.1                gtable_0.2.0               
[13] pkgconfig_2.0.2             rlang_0.3.1                
[15] Matrix_1.2-15               DelayedArray_0.8.0         
[17] parallel_3.5.2              GenomeInfoDbData_1.2.0     
[19] stringr_1.4.0               hwriter_1.3.2              
[21] dplyr_0.8.0.1               Biostrings_2.50.2          
[23] S4Vectors_0.20.1            IRanges_2.16.0             
[25] stats4_3.5.2                grid_3.5.2                 
[27] tidyselect_0.2.5            glue_1.3.0                 
[29] Biobase_2.42.0              R6_2.4.0                   
[31] BiocParallel_1.16.6         latticeExtra_0.6-28        
[33] reshape2_1.4.3              ggplot2_3.1.0              
[35] purrr_0.3.0                 magrittr_1.5               
[37] Rsamtools_1.34.1            scales_1.0.0               
[39] matrixStats_0.54.0          BiocGenerics_0.28.0        
[41] GenomicRanges_1.34.0        GenomicAlignments_1.18.1   
[43] ShortRead_1.40.0            assertthat_0.2.0           
[45] SummarizedExperiment_1.12.0 colorspace_1.4-0           
[47] stringi_1.3.1               RCurl_1.95-4.11            
[49] lazyeval_0.2.1              RcppParallel_4.4.2         
[51] munsell_0.5.0               crayon_1.3.4          `

I have installed dada2 using following commands:
`source("http://bioconductor.org/biocLite.R")
 biocLite("")`

**Comment by benjjneb** [comment]
> Here is the output of sessionInfo()

I'm not seeing dada2 or Rcpp? Maybe you need to `library(dada2)` before running `sessionInfo()`. Also, what is `R.version` output?

**Comment by drdee255** [comment]
Sorry the upper part of sessionInfo() output was this:
locale:
 [1] LC_CTYPE=en_IN       LC_NUMERIC=C         LC_TIME=en_IN       
 [4] LC_COLLATE=en_IN     LC_MONETARY=en_IN    LC_MESSAGES=en_IN   
 [7] LC_PAPER=en_IN       LC_NAME=C            LC_ADDRESS=C        
[10] LC_TELEPHONE=C       LC_MEASUREMENT=en_IN LC_IDENTIFICATION=C 

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dada2_1.10.1 Rcpp_1.0.0  

Output of R.version:
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          5.2                         
year           2018                        
month          12                          
day            20                          
svn rev        75870                       
language       R                           
version.string R version 3.5.2 (2018-12-20)
nickname       Eggshell Igloo

**Comment by benjjneb** [comment]
A little googling suggests that

> negative length vectors are not allowed

could be coming from an integer overflow. but why in your case and not usually when using `assignTaxonomy` and the silva database?

Can see if this works when you use the smaller RDP training fasta? https://benjjneb.github.io/dada2/training.html

**Comment by drdee255** [comment]
Yes I got to know it is something about memory an then I tried using HitDB
it shows same error.

**Comment by benjjneb** [comment]
Quick question: Does this error persist with `multithread=FALSE`?

**Comment by drdee255** [comment]
I will check that.
But I have repeated analysis with some stringent trimming which results in a lower number of ASVs than earlier. I was able to assign the taxonomy to this new sequence table.

**Comment by benjjneb** [comment]
> But I have repeated analysis with some stringent trimming which results in a lower number of ASVs than earlier. I was able to assign the taxonomy to this new sequence table.

What is the size of the table when it fails? I.e. what was `dim(seqtab.nochim)` just before the error was triggered?

**Comment by soluna1** [comment]
Hi, I posted my problem here rather to open a new one as it is also related to the AssignTaxonomy function. 
I'm trying to assign the taxonomy to a seqtab.nochim containing the seqs of 5 samples (dim = 5   1625), and using "pr2_version_4.11.1_dada2.fasta.gz" as reference database, with a MacBook Pro 8gb ram i5 4 cores. The seqs are from the v9 region of 18S, so they range between 100-125 bp.
I've run the following command:
`taxa <- assignTaxonomy(seqtab.nochim, "pr2_version_4.11.1_dada2.fasta", multithread=T, tryRC=T, taxLevels = c("Kingdom","Supergroup","Division","Class","Order","Family","Genus","Species"))`

But the run doesn't end after several mins (fans working) so I stopped it. Doing the same with the silva database ""rdp_train_set_16.fa" it works fine. So, I can't guess which should be the problem.
Any idea?

Thanks

**Comment by benjjneb** [comment]
@soluna1 It is probably a memory issue, given that the smaller rdp database runs fine. Do you have access to a machine with more memory?

**Comment by soluna1** [comment]
Yes, I thought about that possibility. I could try with a cluster but as I'm doing some training it is easy to work with my computer. Some tutorials, like the one from astrobiomike.github.io, 
are able to assign the taxonomy in a laptop similar to mine. In addition, I found that several taxon and the corresponding sequences are repeated. Is there any reason for that? 
I'm thinking about creating a shorter version of the database with eukaryotic plankton groups only. Could it make sense too you?
Many thanks for your answer

**Comment by benjjneb** [comment]
> I'm thinking about creating a shorter version of the database with eukaryotic plankton groups only. Could it make sense too you?

Yes that makes sense if that is the group you are interested in. The one important consideration is that you will want to keep a (much-reduced) set of sequences from the non-eukaryotic-plankton to serve as outgroups, which will prevent spurious taxonomic assignment to non-target organisms that can occur in a taxonomically restricted database.

**Comment by benjjneb** [comment]
Closing this thread in favor of the main thread on memory issues with `assignTaxonomy`: #239

**Comment by divyachikoo** [comment]
Hi
I am facing the same issue as above, I am working on my local system and want to assign taxonomy to FUNGAL ITS region data. And I don't have access to any cluster memory , so if anyone can help me in this step to assign taxonomy on my own system.

**Comment by benjjneb** [comment]
@divyachikoo Have you tried the alternative taxonomy assignment methods `IdTaxa` implemented in the DECIPHER package? It controls memory better than `assignTaxonomy` and also has a UNITE reference database training file available here: http://www2.decipher.codes/Downloads.html

See how to use `IdTaxa` as a drop-in replacement for `assignTaxonomy` in the green box of the dada2 tutorial section on taxonmic assignment: https://benjjneb.github.io/dada2/tutorial.html#assign-taxonomy

**Comment by SharonOrtiz** [comment]
Hi, I am using Galaxy DADA2 and I am getting this error, could someone help me?

Error in C_assign_taxonomy2(seqs, rc(seqs), refs, ref.to.genus, tax.mat.int, :
Memory allocation failed.
Calls: assignTaxonomy -> C_assign_taxonomy2
In addition: Warning message:
In .Call2("fasta_index", filexp_list, nrec, skip, seek.first.rec, :
reading FASTA file /galaxy-repl/main/files/059/949/dataset_59949784.dat: ignored 8 invalid one-letter sequence codes
Execution halted

**Comment by benjjneb** [comment]
The error message "Memory allocation failed." is being given by the DADA2 program because it was unable to allocate enough memory to create one of the objects needed for this step. How much memory is available to the Galaxy instance running your command?

Also, what reference database/file are you using?

**Comment by vinya04** [comment]
i have used 138 and 132 but error is same for me ,what should i do with this ,any idea ?
 taxa <- assignTaxonomy(seqtab.nochim, "raw_files/tax/silva_nr_v132_train_set.fa.gz", multithread=20)

Error in C_assign_taxonomy2(seqs, rc(seqs), refs, ref.to.genus, tax.mat.int,  : 
  negative length vectors are not allowed

**Comment by benjjneb** [comment]
@vinya04 

What is the size of your query dataset? `ncol(seqtab.nochim)`

Are there any short sequences in your query sequences?

```
sq <- getSequences(seqtab.nochim)
nchar(sq) |> summary()
```

Does this error go away with a much smaller reference database, like RDP?
