### ISSUE TITLE
.fastq files after chimera removal?

### ISSUE THREAD

**Issue by dcastaneda5** [benjjneb/dada2#692]
Hi,

I was just wondering if DADA2 saves any .fastq files (with the quality score) after removing the chimeras and merging the sequences? Or is it just the object with the sequences as output?

Thanks!

Daniel

**Comment by benjjneb** [comment]
No fastq files are created after the filtering/trimming steps.

Furthermore, the concept of quality score after denoising isn't really the same anymore. The quality scores are used in the error model of the DADA2 algorithm. The output of `dada` does provide a `$quality` matrix of the average quality scores at each position for each output denoised sequence, but those aren't the same as predicted error rates. In fact, the error rates post-denoising will be far lower than suggested by those average quality scores, they are just there as a potential diagnostic.

**Comment by dcastaneda5** [comment]
I see, that actually makes sense. Thanks a lot!
