### ISSUE TITLE
Help debugging cutadapt issue

### ISSUE THREAD

**Issue by morien** [benjjneb/dada2#693]
I'm working with some MiSeq 2x250bp data (18s V9 region), and while it's not as variable in length as the ITS region, the ITS pipeline should be the right choice for primer removal, because the forward and reverse reads will both contain the entire construct (insert, barcode, primer, etc).

I've followed carefully the primer removal procedure in the dada2 ITS sample guide, and done some additional trimming because the first 60bp of my R2s had some sequencing run issues that make that data unreliable. I did a conservative trim at the 5' end of my reads as well. Nothing past 200bp should be real sequence, or if it is, it is primer/barcode/adapter and not insert.

I have no technical errors, but I still have primer and construct in my merged sequence table. See here a file with 100 or so of my sequences post chimera removal.
[V9_merged_sequences.txt](https://github.com/benjjneb/dada2/files/2903489/V9_merged_sequences.txt)

These are my primers:
FWD <- "GTACACACCGCCCGTC"
REV <- "TGATCCTTCTGCAGGTTCACCTAC"

If I grep for my RC forward primer, it's in every sequence in that file:
$ grep GTAGGTGAACCTGCAGAAGGATCA V9_merged_sequences.txt | wc -l
     100

Also see here my primer removal code, and filter and trim command. Do the developers have any idea why I still have primer in my merged dereplicated sequences?
[dada2_primer_removal_code_for_devs.txt](https://github.com/benjjneb/dada2/files/2903511/dada2_primer_removal_code_for_devs.txt)

Thanks in advance for help/advice.

**Comment by benjjneb** [comment]
What is the output of the initial primer presence and orientation check? i.e. the output of:

```
rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.filtN[[1]]), 
      FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.filtN[[1]]), 
      REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.filtN[[1]]), 
      REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.filtN[[1]]))
```

**Comment by morien** [comment]
It shows I have reverse-complemented forward and reverse primers, but no
forward orientation primers present. To be more precise, the right hand
column of the table generated has primer counts in the second and third
rows. There are no other identified primer orientations or positions at
this step.

I don't have the output on hand but I can paste in a reply later if need be.

**Comment by benjjneb** [comment]
> I don't have the output on hand but I can paste in a reply later if need be.

When you get the chance it will help to see the full set of numbers.

**Comment by morien** [comment]
Here's two examples. This might or might not be relevant but there are
always more FWD.ReverseReads than REV.ForwardReads

> > rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn =
> fnFs.filtN[[1]]),
> +       FWD.ReverseReads = sapply(FWD.orients, primerHits, fn =
> fnRs.filtN[[1]]),
> +       REV.ForwardReads = sapply(REV.orients, primerHits, fn =
> fnFs.filtN[[1]]),
> +       REV.ReverseReads = sapply(REV.orients, primerHits, fn =
> fnRs.filtN[[1]]))
>                  Forward Complement Reverse RevComp
> FWD.ForwardReads       0          0       0       0
> FWD.ReverseReads       0          0       0      24
> REV.ForwardReads       0          0       0     544
> REV.ReverseReads       0          0       0       0
> > rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn =
> fnFs.filtN[[60]]),
> +       FWD.ReverseReads = sapply(FWD.orients, primerHits, fn =
> fnRs.filtN[[60]]),
> +       REV.ForwardReads = sapply(REV.orients, primerHits, fn =
> fnFs.filtN[[60]]),
> +       REV.ReverseReads = sapply(REV.orients, primerHits, fn =
> fnRs.filtN[[60]]))
>                  Forward Complement Reverse RevComp
> FWD.ForwardReads       0          0       0       0
> FWD.ReverseReads       0          0       0     828
> REV.ForwardReads       0          0       0   21460
> REV.ReverseReads       0          0       0       0

**Comment by benjjneb** [comment]
I don't know? That output indicates there shouldn't be any reverse-complemented forward primer in your merged reads at the end?

You could try just the standard 16S strategy of using just `trimLeft` and `truncLen` instead of cutadapt. That is, if your (insert, barcode, primer) is a constant length, just use those lengths for `trimLeft = c(FWD.IBC.len, REV.IBC.len)` and then set `truncLen` so that it is long enough for the reads to overlap, but short enough that you don't read into the opposite primer.

**Comment by morien** [comment]
I figured out the issue here. First I'd made a mistake in the code, and I inadvertently used my filtered but not primer trimmed files as input for my filterAndTrim command. With that sorted, I then had issues with low read retention, which I was able to resolve with more aggressive truncation. I have a question about that, though:

For a given fastq set - say the R1s - is there a reason why no truncation would return an order of magnitude (or more) reads after filterAndTrim compared to a truncation of say, 5bp, but that a truncation of 30bp would give comparable or better numbers than no truncation at all? So a dummy example would look like
truncation:    notrunc     trunc5bp     trunc30bp
reads_retained:     20000     1000     19000

Here's a typical quality plot after cutadapt is finished with my fastq files.
![v9_r1_qualplot_example](https://user-images.githubusercontent.com/7683151/53525953-d59fc080-3a97-11e9-9ec6-56ce6c1e00b7.png)

**Comment by benjjneb** [comment]
`truncLen` does two things: It truncates reads to the defined length AND it removes reads that don't reach the truncation length. 

So using no truncation you lose no reads that way. When you trancate at say 145 nts you lose most of your reads that don't reach that far. And when you truncate to say 120 you keep most reads, since most reads reach that far.

**Comment by morien** [comment]
Great thank you. That makes sense now. Appreciate your time!
