### ISSUE TITLE
A comparison of results between running separately and running together

### ISSUE THREAD

**Issue by zhouyunyan** [benjjneb/dada2#694]
if there are many samples, can I devide them into multiple subsets according to different groups, then merge these feature results. Is that the same as all samples running together.

**Comment by benjjneb** [comment]
> if there are many samples, can I devide them into multiple subsets according to different groups, then merge these feature results.

Yes.

> Is that the same as all samples running together.

Essentially yes if you are doing the default sample-by-sample processing (instead of pooled processing).

**Comment by zhouyunyan** [comment]
Which command can set this parameter? If merged with commond "qiime feature-table merge" on qiime2,
--p-overlap-method use default error_on_overlapping_sample, right?
![default](https://user-images.githubusercontent.com/42016367/53458112-c9077200-3a6f-11e9-8e0f-d5d1f8c5017a.png)

**Comment by benjjneb** [comment]
For QIIME2 support you will need to go to the QIIME2 forum: https://forum.qiime2.org/

**Comment by zhouyunyan** [comment]
I see, Thank you!
