### ISSUE TITLE
Consensus or majority taxonomy SILVA v132

### ISSUE THREAD

**Issue by Sofie8** [benjjneb/dada2#695]
Hi Benji,

I am using the dada2 pipeline for a while now. Thanks for maintaining it so well!

I have a question that a reviewer pointed me to, in a recent manuscript, and it's related to whether I am using the consensus or majority taxonomy files of SILVA v132.. I had to read into this, but now it is more clear to me: "A user of the Silva119 data pointed out that the taxonomy with the SILVA119 release is based only upon the taxonomy string of the representative sequence for the cluster of reads, which could lead to incorrect confidence in taxonomy assignments at the fine level (genus/species). To address this, I have endeavoured to create taxonomy strings that are either consensus (all taxa strings must match for every read that fell into the cluster) or majority (greater than or equal to 90% of the taxonomy strings for a given cluster). If a taxonomy string fails to be consensus or majority, then it becomes ambiguous, moving up the levels of taxonomy until consensus/majority taxonomy strings are met."

I am using the silva_nr_v132_train_set.fa, from dada2 data repository. How is the naming done in this file, based on majority or consensus?

Thanks already,
Sofie

**Comment by benjjneb** [comment]
The dada2 Silva reference fasta is basically a format conversion from the reference put together by the mothur team. You can read how they did that here: http://blog.mothur.org/2018/01/10/SILVA-v132-reference-files/

Hope that answers the question!
