### ISSUE TITLE
How to format output for Tax4Fun

### ISSUE THREAD

**Issue by owenNewcastle** [benjjneb/dada2#696]
I'm investigating biofilms living on plastic debris. I want to find out if there is differential expression of certain KEGG Orthologs (KO) at week 0 and week 7 of my microcosm experiment (as well as between different treatments - all of which are variables in my phyloseq object.

I am trying to work from this tutorial: https://cran.r-project.org/web/packages/themetagenomics/vignettes/thematic_structure.html
(see sections titled Preprocessing and Functions)

How would I convert my dada2 output (or phyloseq object) into a format similar to the DAVID dataset mentioned in this tutorial??

**Comment by benjjneb** [comment]
The sequence table and taxonomy tables output by the dada2 workflow are already in the format they want. Then you just need to enter in or read in your sample metadata as a data.frame, make sure the rownames (the sample names) match those in the dada2-generated sequence table, and you will be good to go.

**Comment by owenNewcastle** [comment]
Thanks for the reply.
My sequence table and taxonomy tables both have the full sequences within them. Should I remove them?

Either way, I am getting the error Error in tax_table[, g] : subscript out of bounds

**Comment by owenNewcastle** [comment]
I should have clarified I am getting that from this line of code:

`CLEAN <- prepare_data(otu_table=seqtab.nochim,
                      rows_are_taxa=FALSE,
                      tax_table=taxa,
                      metadata=meta,
                      formula=~Conditions + s(Time_.weeks.),cn_normalize=FALSE,
                      drop=TRUE)`

**Comment by benjjneb** [comment]
This is really a question for the `themetagenomics` package people as that is what is causing trouble here. In a quick test, it appears they have hard-coded in an expectation that taxonomy goes from Kingdom to Species, and if you don't have a 7th Species column it throws the error you are seeing. You could try adding a 7th column of all NAs, or use `addSpecies` to add a species column using dada2.

**Comment by EOMAK91** [comment]
@owenNewcastle have you had any luck with the package? I've had problems running it recently.
