### ISSUE TITLE
(Too) many ASVs after Chimera removal

### ISSUE THREAD

**Issue by AliceSommer** [benjjneb/dada2#698]
I'm working with a data set with 2,185 fecal samples. The amplicon is V3-V4 and hiseq 2x250 was used. I truncated the forward reads to 245 bps and the reverse reads to 230 bps.

I have two questions:

1) I am a little worried because after filtering and trimming, dereplication, and merge of pair reads my sequence table has 229,482 ASVs (before chimera removal) and 80,083 ASVs (after chimera removal). Does this large amount of ASVs seem normal?

2) I was told that the primers were removed but I would like to double check it. 
Can I do that with dada2?

**Comment by dswan** [comment]
If the sequencing was 2x250, and you're truncating 250bp reads, I don't think the primers have been removed. You might want to look at #571 which sounds like a similar situation.

**Comment by benjjneb** [comment]
How did the number of reads change? In large datasets like it is not uncommon to identify 2/3rds of the ASVs as chimeric, but they should only represent a much smaller fraction (<25%) of total reads.

The DADA2 ITS workflow goes through the process of checking for primers in your data: https://benjjneb.github.io/dada2/ITS_workflow.html

You will need to know your primer sequences though.

**Comment by AliceSommer** [comment]
Thank you for the suggestions !

After using cutadapt to remove the primers, I am left with 1,981 samples. 
Why did some samples get deleted in the process?

Now my sequence table has 23,391 ASVs (before chimera removal) and 12,235 ASVs (after chimera removal). Chimeras account for 1% of the merged sequence reads. 
Isn't the amount of ASVs still high?

**Comment by benjjneb** [comment]
> After using cutadapt to remove the primers, I am left with 1,981 samples.

I don't know, perhaps those samples had no reads left after cutadapt + filtering?

> Isn't the amount of ASVs still high?

The number of ASVs you should expect depends greatly on what environment you are looking at and the number of samples you have. Given the large number of samples in your study I'm not that surprised at the numbers you are seeing. Probably a large fraction of reads are in a relatively small subset of those 12,235 ASVs though.
