### ISSUE TITLE
Error in mergePairs; 0 paired-reads for all samples run

### ISSUE THREAD

**Issue by rmsegnitz** [benjjneb/dada2#699]
Hi all, I apologize for double posting but I hadn't realized that I'd posted this in a closed thread (https://github.com/benjjneb/dada2/issues/512).

I am encountering an issue of having no pairs merge in the mergePairs() step.

I am working through the dada2 workflow to process a run of fungal ITS data.
These are paired-end reads, 2X300 , and as it is ITS the amplicons are variable length.

I have used cutadapt to remove primers, and the dada2 suggested "primerHits" function to confirm that no primer or adapter sequences are found in the reads. The following output are from a subset of 6 samples I am using to try to work out the following issue.

Everything in the suggested ITS workflow goes smoothly and seems reasonable until I reach the merging step, where zero reads are paired and I receive the following errors.

0 paired-reads (in 0 unique pairings) successfully merged out of 549 (in 17 pairings) input.
0 paired-reads (in 0 unique pairings) successfully merged out of 12373 (in 29 pairings) input.
0 paired-reads (in 0 unique pairings) successfully merged out of 6729 (in 11 pairings) input.
0 paired-reads (in 0 unique pairings) successfully merged out of 13039 (in 15 pairings) input.
0 paired-reads (in 0 unique pairings) successfully merged out of 15056 (in 22 pairings) input.
0 paired-reads (in 0 unique pairings) successfully merged out of 10728 (in 17 pairings) input.

No matter what I have tried, I cannot seem to get around this error.

The quality profiles look pretty good and error rates seem to fitted quite well.
[Example_Qplots_F.pdf](https://github.com/benjjneb/dada2/files/2933720/Example_Qplots_F.pdf)
[example_Qplots_R.pdf](https://github.com/benjjneb/dada2/files/2933722/example_Qplots_R.pdf)
[dada2_ErrPlot.pdf](https://github.com/benjjneb/dada2/files/2933724/dada2_ErrPlot.pdf)
[dada2_ErrPlot_rev.pdf](https://github.com/benjjneb/dada2/files/2933725/dada2_ErrPlot_rev.pdf)

Here is some sample output from the denoising step prior to merging (I have seen this requested in other threads).

dadaFs[4]
$143
dada-class: object describing DADA2 denoising results
15 sequence variants were inferred from 6050 input unique sequences.
Key parameters: OMEGA_A = 1e-40, OMEGA_C = 1e-40, BAND_SIZE = 16

dadaRs[4]
$143
dada-class: object describing DADA2 denoising results
15 sequence variants were inferred from 6050 input unique sequences.
Key parameters: OMEGA_A = 1e-40, OMEGA_C = 1e-40, BAND_SIZE = 16

I have tried the various approaches suggested in similar threads, but nothing has seemed to correct the issue. I am using the latest relase, v. 1.8.0, but have also tried to use the current devel version with no luck.

Any help or direction would be much appreciated!
Thanks very much in advance for your time.

**Comment by benjjneb** [comment]
The fact that you are seeing the same things:

> 15 sequence variants were inferred from 6050 input unique sequences.

in your forward and reverse `dada-class` objects makes me suspect that there may have been a mixup in your workflow and you are processing the forwards reads twice (or the reverse reads twice).

What is the output of this?

```
sum(dadaFs[[4]]$sequence %in% dadaRs[[4]]$sequence)
```

**Comment by rmsegnitz** [comment]
Thanks very  much for the help, Ben.

> dadaFs[4]
$`143`
dada-class: object describing DADA2 denoising results
17 sequence variants were inferred from 6050 input unique sequences.
Key parameters: OMEGA_A = 1e-40, OMEGA_C = 1e-40, BAND_SIZE = 16

> sum(dadaFs[[4]]$sequence %in% dadaRs[[4]]$sequence)
[1] 17

I see what you are getting at.

**Comment by rmsegnitz** [comment]
I can't find anywhere in my script where the paths seem to be misspecified or where there is an "fnFs" for "fnRs" substitution or anything like that. 

When I searching for primers before using cutadapt to remove them, I find the forward and reverse primers in the expected orientations as below:

Forward Complement Reverse RevComp
FWD.ForwardReads    12473          0       0       0
FWD.ReverseReads             0          0       0    5858
REV.ForwardReads              0          0       0    5891
REV.ReverseReads      12420          0       0       0


This would suggest that if there is a mixup in the workflow such that the forward or reverse reads are being processed twice, it would have to be somewhere downstream of that, right?

**Comment by benjjneb** [comment]
> This would suggest that if there is a mixup in the workflow such that the forward or reverse reads are being processed twice, it would have to be somewhere downstream of that, right?

Yep seems that way to me. Having done this myself in the past, it an be annoyingly hard to see those mixups sometimes.

**Comment by rmsegnitz** [comment]
Ok, I will give a more thorough vetting. If all else fails will copy the script from the published workflow again to double-check. Your explanation makes perfect sense, and would be such a simple fix. 

If the problem persists (and I am more sure that I haven't goofed), I will return!

Thanks so much, you're a hero.
