### ISSUE TITLE
Getting few (66) ASVs in ASV table.

### ISSUE THREAD

**Issue by rahulnccs** [benjjneb/dada2#700]
We changed almost every parameters (ltruncLen=c(240,160), assignTaxonomy(..., tryRC=TRUE), etc)
but every time we are ending up getting only 60 or 90 ASVs in ASV table. We also tried pre-trimming using third party tool (cutadapt).
 I am providing you raw data files and run quality profile. Could you please look at the data and provide some more information. 

[SRR6885533_1.fastq.gz](https://github.com/benjjneb/dada2/files/2933687/SRR6885533_1.fastq.gz)
[SRR6885533_2.fastq.gz](https://github.com/benjjneb/dada2/files/2933688/SRR6885533_2.fastq.gz)

![quality](https://user-images.githubusercontent.com/26318456/53846279-e35eb580-3f71-11e9-8338-b22e90b006aa.png)
![revquality](https://user-images.githubusercontent.com/26318456/53846280-e48fe280-3f71-11e9-950f-20b633a67b9f.png)

**Comment by benjjneb** [comment]
Is this your data? Do you know what region was sequenced and what primer set was used? When are reads lost in the pipeline: at merging? This is crucial information to diagnose what could be happening.

**Comment by benjjneb** [comment]
Taking a quick look: The 341F forward primer is in both the forward and the reverse reads (not good). The most abundant forward reads map to a different bacterial species than the most abundant reverse reads (not good). And the first 5 nts of the forward reads and the last 100 nts may be junk, as they are removed when blasting these sequences against nt.

I would be hesitant to use this data, but if I was set on using it I would give up on pairing the reads, as they don't seem to be paired correctly, and use just the forward reads, probably from starting with the 341F primer region and going until BLAST says I'm no longer matching sequences correcltly (about position 150).

**Comment by rahulnccs** [comment]
I was losing reads during merging. I would go with forwards reads, (truncLen= would be based on BLAST-ing).
Thanks a lot.
