### ISSUE TITLE
Which UNITE data set to chose

### ISSUE THREAD

**Issue by bernt-matthias** [benjjneb/dada2#702]
I'm currently working on integrating the wonderful DADA2 package for the use in the Galaxy server. While creating a data manager for downloading the reference sets I stumbled over UNITE. For each release there seem to be two data sets (essentially one larger and one smaller), e.g. for release 8.0 there are (after download): 

- sh_general_release_dynamic_02.02.2019.fasta and
- sh_general_release_dynamic_s_02.02.2019.fasta

I'm wondering which of the two should be used, or if both are fine, how to document them. I couldn't find anything. 

If you are interested in my progress on the Galaxy wrappers: 

https://github.com/bernt-matthias/mb-galaxy-tools/tree/topic/dada2/data_managers/data_manager_dada2

https://github.com/bernt-matthias/mb-galaxy-tools/tree/topic/dada2/tools/dada2

There are still a few things missing (eg documentation and citations).

**Comment by dswan** [comment]
If I recall, they have the same reference sequences (RefS), but the larger dataset contains singleton 'representative sequences' (RepS). It's a bit obtuse on the website, I admit. The FAQ gives more information: https://unite.ut.ee/faq.php

However the clearest difference is probably shown at the DOI endpoints:

https://plutof.ut.ee/#/doi/10.15156/BIO/786343 : "Abstract: This release consists of a single FASTA file: the RepS/RefS of all SHs, adopting the dynamically use of clustering thresholds whenever available."

and

https://plutof.ut.ee/#/doi/10.15156/BIO/786353 : "Abstract: This release consists of a single FASTA file: the RepS/RefS of all SHs, adopting the dynamically use of clustering thresholds whenever available. Includes global and 97% singletons."

**Comment by benjjneb** [comment]
> I'm currently working on integrating the wonderful DADA2 package for the use in the Galaxy server. 

That sounds like a great project and thanks for taking that on. I can't help on the Galaxy side of things, but please feel free to ask more questions here as needed.

> there seem to be two data sets (essentially one larger and one smaller), e.g. for release 8.0 there are (after download):
>
> * sh_general_release_dynamic_02.02.2019.fasta and
> * sh_general_release_dynamic_s_02.02.2019.fasta
> I'm wondering which of the two should be used, or if both are fine, how to document them. I couldn't find anything.

@dswan described what these are. As far as guidance, we do not have any on which to use at this time. They both work. I usually use the non-singleton version, but not for any very good reason, just because its a bit smaller. We have not any rigorous testing comparing the two.

**Comment by bernt-matthias** [comment]
Thanks for the explanations @dswan and @benjjneb .

For the fungi UNITE db (v8) everything seems to work fine. 

But for the eukaryote DB I got:

```
UNITE fungal taxonomic reference detected. Fatal error: Exit code 1 () Error in C_assign_taxonomy2(seqs, rc(seqs), refs, ref.to.genus, tax.mat.int, : Memory allocation failed. Calls: assignTaxonomy -> C_assign_taxonomy2 Execution halted
```

Any idea how I could debug this? Could also be limited memory resources on my local computer.

**Comment by benjjneb** [comment]
The only UNITE database we currently support is the fungal one. The others would have to be formatted into DADA2-format to be used.

This page lists all of the officially supported reference dbs (Silva,RDP, GG, UNITE-fungal) and links to the appropriate files to use with `assignTaxonomy`. There are also links to some other appropraitely formatted files for other databases that have been contributed by people using dada2.

https://benjjneb.github.io/dada2/training.html

**Comment by bernt-matthias** [comment]
OK - thanks. Then I will just remove the eukaryote option.

**Comment by termithorbor** [comment]
You can use the eukaryote version as well. Just open the fasta file an delete all the non-taxonomica stuff in the beginning of the document, which is basically only information about the version.

**Comment by termithorbor** [comment]
Does anyone know what the difference between those two unite data sets is?

sh_general_release_dynamic_04.04.2024.fasta
sh_general_release_dynamic_04.04.2024_dev.fasta

Thanks in advance.
