### ISSUE TITLE
 learnErrors issues

### ISSUE THREAD

**Issue by rebbec** [benjjneb/dada2#703]
I used this command to estimate error:

errF <- learnErrors(filtFs, nbases=1e8, multithread=TRUE)

Even I set the nbases parameters, I think the program still used all the bases in my fastq file to estimate error, this is the output line:

3787446000 total bases in 15781025 reads from 1 samples will be used for learning the error rates.

Did anyone encounter the same issue and could help me with this?  Thanks.

**Comment by benjjneb** [comment]
See comment here: https://github.com/benjjneb/dada2/issues/680#issuecomment-464462118

Basically, `nbases` just controls the number of samples used, but does not break up samples.
