### ISSUE TITLE
Classifying is single-threaded?

### ISSUE THREAD

**Issue by wolfgangrumpf** [benjjneb/dada2#705]
I noticed that once dada2 begins classifying reads that the thread drops to just one....seems like there should be a way of splitting the reads and classifying them in parallel, but I can't figure out how to make that happen.  Help?

**Comment by benjjneb** [comment]
Did you turn on `multithread=TRUE` in `assignTaxonomy`?

**Comment by wolfgangrumpf** [comment]
I did!  I typically comment the bejeezus out of my scripts, so I'm able to tell exactly what stage I'm in:

#############################################################
# Assign Taxonomy
#############################################################
cat(c("\n", "===== Classifying Sequences ===== ", "\n"))

taxa <- assignTaxonomy(seqtab.nochim, "silva_nr_v132_train_set.fa.gz", multithread=TRUE)
taxa <- addSpecies(taxa, "silva_species_assignment_v132.fa.gz")


After I saw the "Classifying Sequences" message, R went to a single thread.....

**Comment by benjjneb** [comment]
> After I saw the "Classifying Sequences" message, R went to a single thread.....

Ah, I think you are just catching the initial stage in which the training fasta is being read in and parsed and stored as kmers. That part is still just single-threaded.

However, the assignment stage should be multithreaded. If you turn `verbose=TRUE` on the function will output a message after reading/parsing/storing the training fasta is done. If you check threads after that it should be using >1 if all is well.

**Comment by wolfgangrumpf** [comment]
Sounds good - thanks!!!!

**Comment by wolfgangrumpf** [comment]
Quick followup question - is addSpecies single threaded, or could I set multithread=TRUE for that as well?

**Comment by benjjneb** [comment]
`addSpecies` is single-threaded only

**Comment by wolfgangrumpf** [comment]
Thanks!
