### ISSUE TITLE
Assigning taxonomy after merging two different runs

### ISSUE THREAD

**Issue by miguensblanco** [benjjneb/dada2#706]
I merged two different MiSeq runs following the big data protocol [(https://benjjneb.github.io/dada2/bigdata.html)], across the script I have few problems due to samples with number of reads.

After Trim the second of my runs two of the samples were removed giving the next error when I try to carry on with the script:

> Error in open.connection(con, "rb") : cannot open the connection
In addition: Warning message:
In open.connection(con, "rb") :
  cannot open file '/home/ubuntu/dada2/Zhigang/Zhigang_35R/filtered/DUC3_R_filt.fastq.gz': No such file or directory

I got in one of the previous issues the next code to overcome this error:

``> exists <- file.exists(filtFs) & file.exists(filtRs)
> filtFs <- filtFs[exists]
> filtRs <- filtRs[exists]
> derepFs <- derepFastq(filtFs, verbose=TRUE)

Afterwards everything looks more or less smooth until I try to assign the taxonomy to seqtab.nochin:

``> st1 <- readRDS("/home/ubuntu/dada2/Zhigang/Merged_runs/seqtab34.rds")
> st2 <- readRDS("/home/ubuntu/dada2/Zhigang/Merged_runs/seqtab35R2.rds")
> st.all <- mergeSequenceTables(st1, st2)
> seqtab.nochim <- removeBimeraDenovo(st.all, method="consensus", multithread=TRUE, verbose=TRUE)
Identified 3255 bimeras out of 6659 input sequences.
> dim(seqtab.nochim)
[1]  404 3404
> taxa_silva <- assignTaxonomy(seqtab.nochim, "/home/ubuntu/dada2/Zhigang/Merged_runs", multithread=TRUE)
Error in .Call2("fasta_index", filexp_list, nrec, skip, seek.first.rec,  : 
  reading FASTA file /home/ubuntu/dada2/Zhigang/Merged_runs/seqtab34.rds: ">" expected at beginning of line 1
> seqtab.nochim <- removeBimeraDenovo(st.all, method="consensus", multithread=TRUE, verbose=TRUE)
Identified 3255 bimeras out of 6659 input sequences.
> dim(seqtab.nochim)
[1]  404 3404
> taxa_silva <- assignTaxonomy(seqtab.nochim, "/home/ubuntu/dada2/Zhigang/Merged_runs", multithread=TRUE)
Error in .Call2("fasta_index", filexp_list, nrec, skip, seek.first.rec,  : 
  reading FASTA file /home/ubuntu/dada2/Zhigang/Merged_runs/seqtab34.rds: ">" expected at beginning of line 1

The same mistake was find before [(https://github.com/benjjneb/dada2/issues/223)] and answer given, but in my case, after looking all the possibilities presented in the links of the answers I continue at the same point, I would appreciate any help, cheers!

**Comment by benjjneb** [comment]
`"/home/ubuntu/dada2/Zhigang/Merged_runs"` is not a valid file path to the taxonomy training fasta file. Did you [download the silva training fasta](https://benjjneb.github.io/dada2/training.html)? What is the file path to the downloaded training fasta on your machine? It should be called `silva_nr_v132_train_set.fa.gz` (or some different version number).

**Comment by miguensblanco** [comment]
Sorry, I did copy very badly that bit, yes I had the pathway properly write but actually the problem was with the silva file, I downloaded it again and it worked alrght, thanks!!

*Sorry, to have not checked this before
