### ISSUE TITLE
.call() error

### ISSUE THREAD

**Issue by yugi1001** [benjjneb/dada2#71]
Hi Ben, sorry to bother with these kind of errors. 
When I am trying to use some of my data on this package, i am getting the below error when in call dadaFs <- dada(derepFs, err=inflateErr(tperr1,3), selfConsist = TRUE).

Error in .Call("dada2_C_isACGT", PACKAGE = "dada2", seqs) : 
  "dada2_C_isACGT" not available for .Call() for package "dada2"

I am not an expert on R and I did look up on stackoverflow for any clues on what I am doing wrong. But could not find any clues.

Details of R that I am usinga re below.
platform       i386-w64-mingw32            
arch           i386                        
os             mingw32                     
system         i386, mingw32               
status                                     
major          3                           
minor          2.3                         
year           2015                        
month          12                          
day            10                          
svn rev        69752                       
language       R                           
version.string R version 3.2.3 (2015-12-10)
nickname       Wooden Christmas-Tree

**Comment by benjjneb** [comment]
What version of the dada2 package are you using?

```
packageVersion("dada2")
```

**Comment by yugi1001** [comment]
> packageVersion("dada2")
[1] ‘0.99.10’

**Comment by benjjneb** [comment]
Can you try installing the 1.0 release from Bioconductor and see if that solves the issue?

```
source("https://bioconductor.org/biocLite.R")
biocLite("dada2")
```

**Comment by yugi1001** [comment]
I am getting the following message

> biocLite("dada2")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.2 (BiocInstaller 1.20.3), R 3.2.3 (2015-12-10).
Installing package(s) ‘dada2’
Warning message:
package ‘dada2’ is not available (for R version 3.2.3)

**Comment by benjjneb** [comment]
Oh right, dada2 is only available with the newest Bioconductor release, which requires R 3.3

Can you try either pulling the latest version of the package (1.0.0) from github and reinstalling, or upgrading to R3.3 and installing via Bioconductor?

**Comment by yugi1001** [comment]
That worked. Thanks Ben!

A minor query on the status report coming when running 'dada'. It reads like below:

Sample 1 - 7124 reads in 1563 unique sequences. 

should it instead be saying "Sample 1 - 1563 unique sequences in 7124 reads'

**Comment by benjjneb** [comment]
Maybe? I'm not sure what is the better grammar, as it's a shorthand status message anyway.

The info is that there were 7124 reads, among which 1563 unique sequences were found.
