### ISSUE TITLE
Track Seqs: I have more resulting reads than input reads

### ISSUE THREAD

**Issue by emilyjunkins** [benjjneb/dada2#710]
Hello, I am running dada2 v1.8.

When I track my sequences, I end up having more final reads than input reads. My data consists of forward reads from a 2x250 (reverse reads were poor). Adapters were removed and sequences demultiplexed with adapterremoval.

`filt_path <- file.path(path, "filtered")`
`if(!file_test("-d", filt_path)) dir.create(filt_path)`
`filtFs <- file.path(filt_path, paste0(sample.names, "_F_filt.fastq"))`

`out <- filterAndTrim(fnFs, filtFs, 
              truncLen=220, maxN=0, maxEE=2, truncQ=2, rm.phix=TRUE,
              compress=TRUE, verbose=TRUE, multithread=TRUE)`

`errF <- learnErrors(filtFs, multithread=TRUE)`
#some reads did not pass filter, so I removed them
`exists <- file.exists(filtFs)`
`exists`
`filtFs <- filtFs[exists]`
`filtFs`

`derepFs <- derepFastq(filtFs, verbose=TRUE)`
#Encountered 1699 unique sequences from 2680 total sequences read.

`dadaFs <- dada(derepFs, err=errF, selfConsist = TRUE)`
`seqtab <- makeSequenceTable(dadaFs)`
`dim(seqtab)`
`table(nchar(getSequences(seqtab)))`

#here is where I start to find my problem:
`getN <- function(x) sum(getUniques(x))`
`track <- cbind(out, sapply(dadaFs, getN), rowSums(seqtab.nochim))`
`track` 
#subset of examples
                         reads.in reads.out            
output_demux.1.fastq        39464     32620 31785 31035
output_demux.10.fastq       30687     21589 20978 20060
output_demux.100.fastq         19        12     1     1
output_demux.101.fastq         54        35     6     6
output_demux.102.fastq        835       639   545   545
output_demux.2.fastq            0         0 19793 18238 
output_demux.206.fastq          5         0     5     5
output_demux.91.fastq        1137       924  1056  1045
output_demux.92.fastq        4273      3457  1368  1368
output_demux.93.fastq        1895      1414  1387  1387

Can anyone help isolate my problem?

**Comment by benjjneb** [comment]
Some of the files were removed because of zero reads after filtering, hence the matrix you've set up now has a mismatch between the number of rows in the `out` oibject, and the length of the other vectors you've cbinded to it.

I think if you just add change `out` to `out[exists]` in the `cbind` statement then it should match up correctly.

**Comment by emilyjunkins** [comment]
I tried applying that during `cbind`,
`getN <- function(x) sum(getUniques(x))`
`track <- cbind(out[exists], sapply(dadaFs, getN), rowSums(seqtab.nochim))`
but still had the same issue.

 I found that I couldn't get through `derepFastq` without doing either `filtFs <- filtFs[exists]` or directly remove them from the objects  `sample.names <- sample.names[-119]` and  `filtFs <- filtFs[-119]`.  When I do that, I can get through the dereplication. I then applied `[exists]` again during `cbind` and it altered the dimension of that track table. So that instead of the four columns I thought I would get ( in, out, denoisedF, and nochim) I got three columns and doubled my rows with some elements repeated.

Following the first sample of 217 (row 1) to where it loops over to row 218
> track
        [,1]  [,2]  [,3]
  [1,] 39464 32164 31536
  [2,] 30687 21274 20542
  [3,]    19     1     1
.....
[218,] 32916 32164 31536
[219,] 21825 21274 20542
[220,]    12     1     1
 

I know this is more of an R issue with me organizing the data, but I am unsure how to handle dropped files/samples in my defined paths.

**Comment by benjjneb** [comment]
I think you just need to change `out[exists]` to `out[exists,]` and it will work.

Basically it is just getting the samples matched up between filtering stats, which includes the zero-read samples that are removed, and the subsequent steps that don't have those samples in them.

**Comment by emilyjunkins** [comment]
That's the fix. Thank you!
