### ISSUE TITLE
Dada2  - Error during derep & renaming dereps to sample names

### ISSUE THREAD

**Issue by mochirba** [benjjneb/dada2#711]
Hi - I'm having an issue during the dereplication step on the 1.8 pipeline. During my filterAndTrim step, based on my parameters- I have negatives that have 0 sequences & thus when I run the  **derepFs <- derepFastq(filtFs, verbose=TRUE)** line - it is unable to find the file/directory for that samples, because it has been filtered out (Error in open.connection(con, "rb") : cannot open the connection. Warning: In addition...No such file or directory). This causes downstream issues as I am unable to run **names(derepFs) <- sample.names** and gives me the following error message (Error in names(derepFs) <- sample.names : object 'derepFs' not found). Do you have a code that I can use to work around this error, but still be able to keep original sample file (for possible filter changes)?

**Comment by benjjneb** [comment]
Yep, just check if the file exists after filtering, and only use ones that do, i.e.:

```
exists <- file.exists(filtFs)
derepFs <- derepFastq(filtFs[exists], verbose=TRUE)
derepRs <- derepFastq(filtRs[exists], verbose=TRUE)
names(derepFs) <- sample.names[exists]
names(derepRs) <- sample.names[exists]
```

And you should be good to go after that.

**Comment by mochirba** [comment]
Thank you so much!
