### ISSUE TITLE
filterAndTrim is not appending '.gz' to the compressed *.fastq files

### ISSUE THREAD

**Issue by pdcountway** [benjjneb/dada2#712]
Hi - I'm running dada2 v1.10 under R 3.5.1 on our HPC cluster. I believe that dada2 was installed using the bioconda environment and I'm aware that people have had issues with running dada2 using this type of installation.  That said, I have worked through the DADA2 ITS Pipeline Tutorial Workflow (1.8) to trim primers from the 31 pairs of compressed (*.fastq.gz) fungal ITS files and have confirmed that the primers were removed using cutadapt, v.2.0 with Python 3.6.8.  When I performed this same procedure on my own data (62 pairs of non-compressed 18S *.fastq files) the cutadapt procedure failed saying... FastqFormatError: Error in FASTQ file at line 1: Line expected to start with '@', but found '\x1f'. This prompted me to take a look at the *.fastq files in the filtN folder. Every single file was represented in the folder but the files were filled with nonsense characters. The really odd thing is that primerHits, which presumably uses the filtered *.fastq files and is run after filterAndTrim in the workflow, returned numbers of sequences that made sense for the FWD and REV primers.  Thanks in advance for any suggestions you might have!
-Pete

**Comment by benjjneb** [comment]
`filterAndTrim` outputs gzipped files by default, which will look like nonsense in a standard text editor. You can turn that off and get flat fastq files with the `filterAndTrim(..., compress=FALSE)` option.

**Comment by pdcountway** [comment]
Thanks for the tip. Is it normal for the files in filtN to be written as *.fastq? They weren't compressed to *.gz when I ran the command from the tutorial:
filterAndTrim(fnFs, fnFs.filtN, fnRs, fnRs.filtN, maxN = 0, multithread = TRUE)

**Comment by benjjneb** [comment]
The filenames are just whatever are defined in the R session. Do your `fnFs.filtN` have the .gz extension? If not it's a good idea to add it to help clarify the file format. Or just turn compression off and work with the flat fastq files.

**Comment by pdcountway** [comment]
It doesn't look like the filtered sequences were given the *.gz extension by filterAndTrim when the default, compress=TRUE, was used, however they were in fact compressed based on the file sizes, but retained the *.fastq extension. I re-ran filterAndTrim with compress=FALSE and cutadapt completed with no errors on the flat fastq files. You are correct that I specified that that my input sequences were flat *.fastq files at the outset of the R session - I guess I thought that filterAndTrim would append the *.gz extension when  compressing the filtered *.fastq files. Thanks for your help!
