### ISSUE TITLE
Dada2 suddenly not finding built-in functions

### ISSUE THREAD

**Issue by khp1** [benjjneb/dada2#713]
Hello,

I've recently been using Dada2 for sequence analysis. The pipeline you provided has been very helpful. I analyzed some data last week , and everything worked fine. But today, R can't seem to find the builtin functions! 

For example, I got "Error in filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen = c(151, 151),  : 
  could not find function "filterAndTrim"
 and 
Error in plotQualityProfile(fnFs[1:2]) : 
  could not find function "plotQualityProfile"

Since it was working fine last week, and I did not update anything (I turned off the laptop over the weekend), I don't understand how anything changed. 
Other functions before this, that only use R commands, work fine. So it must something with dada2.
What should I do?

My dada2 version is 1.9.2 and R version is 3.5.1 (2018-07-2).

I would appreciate any help.

Thanks,

**Comment by benjjneb** [comment]
Did you reload the dada2 package after turning R off?

`library(dada2); packageVersion("dada2")`

If you do that, do the functions work again? If not, what is the result of this (after loading the dada2 package):

```
search()
```

**Comment by khp1** [comment]
Yes, that worked! I hadn't loaded the dada2 library. That was such a stupid mistake. Thanks a lot!
