### ISSUE TITLE
error with makeSequenceTable : Unrecognized format:

### ISSUE THREAD

**Issue by fconstancias** [benjjneb/dada2#714]
Dear Benjamin,
Thanks a lot for developing dada2.

I am running dada2 on 7 Miseq runs using the bigdata pair-ended strategy.

After initial filtering, I used the following loops -see below - to i) learn error rates from the different runs and  ii) infer ASV according to run-specific error profiles. Then, I am using the makeSequenceTable function to get ASV tables from the different run using the following loop (that I planned to merge using mergeSequenceTables in the next step).

```
for(run in c("BP", "DD", "IB", "II", "LU", "MC", "CP"))
{
seqs <- makeSequenceTable((get(paste0("mergers_run_",run))))
assign(paste0("seqs_", run), seqs)
rm(seqs)
}
```

I got the following error for only **one** of the t run ("CP")

> Error in FUN(X[[i]], ...) : 
>   Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.
> 

According to previous reported 'errors' I have checked the followings :

> print(run)
> [1] "CP"

> names(get(paste0("mergers_run_",run)))==names(filtered_forward_reads[grep(run,filtered_forward_reads)])
> [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
>  [23] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
>  [45] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
>  [67] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
>  [89] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> [111] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> [133] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> [155] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> [177] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> [199] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> [221] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> [243] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
> [265] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

> class(get(paste0("mergers_run_",run)))
> [1] "list"

> sapply(get(paste0("mergers_run_",run)), class)

> CP100_S206    CP101_S218    CP102_S230    CP103_S242    CP104_S254    CP105_S266    CP106_S278    CP107_S195 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>    CP108_S207    CP109_S219      CP10_S14    CP110_S231    CP111_S243    CP112_S255    CP113_S267    CP114_S279 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>    CP115_S196    CP116_S208    CP117_S220    CP118_S232    CP119_S244      CP11_S26    CP120_S256    CP121_S268 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>    CP122_S280    CP123_S197    CP124_S209    CP125_S221    CP126_S233    CP127_S245    CP128_S257    CP129_S269 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>      CP12_S38    CP130_S281    CP131_S198    CP132_S210    CP133_S222    CP134_S234    CP135_S246    CP136_S258 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>    CP137_S270    CP138_S282    CP139_S203      CP13_S50    CP140_S215    CP141_S227    CP142_S239    CP143_S251 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>    CP144_S263    CP145_S275    CP146_S287    CP147_S204    CP148_S216    CP149_S228      CP14_S62    CP150_S240 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>    CP151_S252    CP152_S264    CP153_S276    CP154_S288    CP155_S289    CP156_S301    CP157_S313    CP158_S325 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>    CP159_S337      CP15_S74    CP160_S349    CP161_S361    CP162_S373    CP163_S290    CP164_S302    CP165_S314 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>    CP166_S326    CP167_S338    CP168_S350    CP169_S362      CP16_S86    CP170_S374    CP171_S291    CP172_S303 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>    CP173_S315    CP174_S327    CP175_S339    CP176_S351    CP177_S363    CP178_S375    CP179_S292       CP17_S3 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>    CP180_S304    CP181_S101    CP182_S102    CP183_S103    CP184_S104    CP185_S105    CP186_S106    CP187_S107 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>    CP188_S108    CP189_S113      CP18_S15    CP190_S114    CP191_S115    CP192_S116    CP193_S117    CP194_S118 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>    CP195_S119    CP196_S120    CP197_S125    CP198_S126    CP199_S127      CP19_S27        CP1_S1    CP200_S128 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"        "list"  "data.frame" 
>    CP201_S129    CP202_S130    CP203_S131    CP204_S132    CP205_S137    CP206_S138    CP207_S139    CP208_S140 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>    CP209_S141      CP20_S39    CP210_S142    CP211_S143    CP212_S144    CP213_S149    CP214_S150    CP215_S151 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>    CP216_S152    CP217_S153    CP218_S154    CP219_S155      CP21_S51    CP220_S156    CP221_S161    CP222_S162 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>    CP223_S163    CP224_S164    CP225_S165    CP226_S166    CP227_S167    CP228_S168    CP229_S173      CP22_S63 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>    CP230_S174    CP231_S175    CP232_S176    CP233_S177    CP234_S178    CP235_S179    CP236_S180    CP237_S185 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>    CP238_S186    CP239_S187      CP23_S75    CP240_S188    CP241_S189    CP242_S190    CP243_S191    CP244_S192 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>    CP245_S293    CP246_S294    CP247_S295    CP248_S296    CP249_S297      CP24_S87    CP250_S298    CP251_S299 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>    CP252_S300    CP253_S305    CP254_S306    CP255_S307    CP256_S308    CP257_S309    CP258_S310    CP259_S311 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>       CP25_S4    CP260_S312    CP261_S317    CP262_S318    CP263_S319    CP264_S320    CP265_S321    CP266_S322 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>    CP267_S323    CP268_S324    CP269_S329      CP26_S16    CP270_S330      CP27_S28      CP28_S40      CP29_S52 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>       CP2_S13      CP30_S64      CP31_S76      CP32_S88       CP33_S5      CP34_S17      CP35_S29      CP36_S41 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>      CP37_S53      CP38_S65      CP39_S77       CP3_S25      CP40_S89       CP41_S6      CP42_S18      CP43_S30 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>      CP44_S42      CP45_S54      CP46_S66      CP47_S78      CP48_S90      CP49_S11       CP4_S37      CP50_S23 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"        "list"  "data.frame" 
>      CP51_S35      CP52_S47      CP53_S59      CP54_S71      CP55_S83      CP56_S95      CP57_S12      CP58_S24 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>      CP59_S36       CP5_S49      CP60_S48      CP61_S60      CP62_S72      CP63_S84      CP64_S96      CP65_S97 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>     CP66_S109     CP67_S121     CP68_S133     CP69_S145       CP6_S61     CP70_S157     CP71_S169     CP72_S181 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>      CP73_S98     CP74_S110     CP75_S122     CP76_S134     CP77_S146     CP78_S158     CP79_S170       CP7_S73 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>     CP80_S182      CP81_S99     CP82_S111     CP83_S123     CP84_S135     CP85_S147     CP86_S159     CP87_S171 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>     CP88_S183     CP89_S100       CP8_S85     CP90_S112     CP91_S193     CP92_S205     CP93_S217     CP94_S229 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>     CP95_S241     CP96_S253     CP97_S265     CP98_S277     CP99_S194        CP9_S2  CPMOCK1_S136  CPMOCK2_S328 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>  CPMOCK3_S332   CPNTC1_S124   CPNTC2_S316   CPNTC3_S331  LUNTCP1_S192 LUNTCP22_S288  LUNTCP2_S384  LUNTCP32_S96 
>  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame"  "data.frame" 
>  LUNTCP3_S192 LUNTCP42_S372  LUNTCP4_S371 
>  "data.frame"  "data.frame"  "data.frame"
> 

Some samples appear as lists :
> class(mergers_run_CP["CP1_S1"])
> [1] "list"

> str(mergers_run_CP["CP1_S1"])
> List of 1
>  $ CP1_S1:List of 2
>   ..**$ CP1_S1**      :'data.frame':	836 obs. of  9 variables:
>   .. ..$ sequence : chr [1:836] "TCGGGAATTTTGGGCAATGGGCGAAAGCCTGACCCAGCAACGCCGCGTGAAGGATGAAATCCTTCGGGATGTAAACTTCGCAAGAACGGGAAGAATAAGTAAGGGTTAATA"| __truncated__ "TCGGGAATTTTGGGCAATGGGCGAAAGCCTGACCCAGCAACGCCGCGTGAAGGATGAAATCCCTCGGGATGTAAACTTCGCAAGAACGGGAAGAATAAGTAGGGGACAATA"| __truncated__ "TGGGGAATATTGGACAATGGGCGCAAGCCTGATCCAGCCATGCCGCGTGAGTGATGAAGGCCCTAGGGTTGTAAAGCTCTTTTGTGCGGGAAGATAATGACGGTACCGCAA"| __truncated__ "TGGGGAATATTGCACAATGGGCGAAAGCCTGATGCAGCGACGCCGCGTGAGGGATGACGGCCTTCGGGTTGTAAACCTCTTTCAGCAGGGAAGAAGCGAAAGTGACGGTAC"| __truncated__ ...
>   .. ..$ abundance: int [1:836] 250 103 99 75 68 66 63 60 54 54 ...
>   .. ..$ forward  : int [1:836] 1 2 3 4 240 16 12 217 9 299 ...
>   .. ..$ reverse  : int [1:836] 1 3 2 5 4 7 29 183 4 1 ...
>   .. ..$ nmatch   : int [1:836] 23 24 46 42 42 23 42 42 42 23 ...
>   .. ..$ nmismatch: int [1:836] 0 0 0 0 0 0 0 0 0 0 ...
>   .. ..$ nindel   : int [1:836] 0 0 0 0 0 0 0 0 0 0 ...
>   .. ..$ prefer   : num [1:836] 1 1 2 1 2 2 1 1 2 2 ...
>   .. ..$ accept   : logi [1:836] TRUE TRUE TRUE TRUE TRUE TRUE ...
>   ..**$ LUNTCP1_S192**:'data.frame':	1459 obs. of  9 variables:
>   .. ..$ sequence : chr [1:1459] "TGAGGAATATTGGACAATGGGTGGAAGCCTGATCCAGCCATCCCGCGTGTAGGACGACTGCCTTATGGGTTGTAAACTACTTTTATCTGGGGATAAACCTACTCACGTGTG"| __truncated__ "TGGGGAATATTGCACAATGGGCGAAAGCCTGATGCAGCAACGCCGCGTGAGGGATGACGGCCTTCGGGTTGTAAACCTCTTTTAGTAGGGAAGAAGCGAAAGTGACGGTAC"| __truncated__ "TGGGGAATATTGCACAATGGGGGAAACCCTGATGCAGCCATGCCGCGTGTGTGAAGAAGGCCTTCGGGTTGTAAAGCACTTTCAGCGGGGAGGAAGGGAGCAGGGTTAATA"| __truncated__ "TAGGGAATCTTCCGCAATGGACGAAAGTCTGACGGAGCAACGCCGCGTGAGTGATGAAGGTTTTCGGATCGTAAAACTCTGTTGTTAGGGAAGAACAAGTACCGTTCGAAT"| __truncated__ ...
>   .. ..$ abundance: int [1:1459] 2591 2561 1924 1671 1311 929 919 912 870 743 ...
>   .. ..$ forward  : int [1:1459] 3 2 5 6 8 7 9 10 11 15 ...
>   .. ..$ reverse  : int [1:1459] 2 4 8 6 7 1 3 6 15 7 ...
>   .. ..$ nmatch   : int [1:1459] 27 42 21 21 21 22 21 21 46 21 ...
>   .. ..$ nmismatch: int [1:1459] 0 0 0 0 0 0 0 0 0 0 ...
>   .. ..$ nindel   : int [1:1459] 0 0 0 0 0 0 0 0 0 0 ...
>   .. ..$ prefer   : num [1:1459] 2 2 2 2 2 2 2 2 2 2 ...
>   .. ..$ accept   : logi [1:1459] TRUE TRUE TRUE TRUE TRUE TRUE ...
> 

Somehow, some mergers have information of more than one sample. Writing this issue helped me to figure out ... I think I need to check my loop... 

loops to i) learn error rates from the different runs
```
system.time(
  for(run in c("BP", "CP", "DD", "IB", "II", "LU", "MC"))
{
# Learn forward error rates
errF <- learnErrors(filtered_forward_reads[grep(run,filtered_forward_reads)], 
                    nbases=1e+10, multithread=TRUE, MAX_CONSIST = 20, randomize = T) #nbases = 1e+08, MAX_CONSIST = 10
assign(paste0("errF_", run), errF)
rm(errF)

plotErrF <- plotErrors(get(paste0("errF_", run)), nominalQ=TRUE)
assign(paste0("plotErrF_", run), plotErrF)
rm(plotErrF)
plot(get(paste0("plotErrF_", run)))

graph2png(file=paste0("plotErrors_errF_",run,"_plots",".png")
          ,width=9,aspectr=sqrt(2))

errR <- learnErrors(filtered_reverse_reads[grep(run,filtered_reverse_reads)], 
                    nbases=1e+10, multithread=TRUE, MAX_CONSIST = 20, randomize = T) #nbases = 1e+08, MAX_CONSIST = 10
assign(paste0("errR_", run), errR)
rm(errR)

plotErrR <- plotErrors(get(paste0("errR_", run)), nominalQ=TRUE)
assign(paste0("plotErrR_", run), plotErrR)
rm(plotErrR)
plot(get(paste0("plotErrR_", run)))

graph2png(file=paste0("plotErrors_errR_",run,"_plots",".png")
          ,width=9,aspectr=sqrt(2))
}
)

```

ii) infer ASV according to run-specific error profiles
```
set.seed(100)
for(run in c("BP", "CP", "DD", "IB", "II", "LU", "MC"))
{
  # Sample inference and merger of paired-end reads
  sample_run <- filtered_forward_reads[grep(run,filtered_forward_reads)]
  length(names(sample_run)) == length(unique(names(sample_run)))
  
  mergers_run <- vector("list", length(sample_run))
  
  names(mergers_run) <- names(sample_run)
  names(mergers_run)==names(sample_run)
  
  filtered_forward_reads_tmp=filtered_forward_reads[grep(run,filtered_forward_reads)]
  filtered_reverse_reads_tmp=filtered_reverse_reads[grep(run,filtered_reverse_reads)]

  
for(sam in names(sample_run))
  {
  cat("Processing:", sam," RUN ",run, "\n")
  
  derepF <- derepFastq(filtered_forward_reads_tmp[grep(sam,filtered_forward_reads_tmp)])
  
  ddF <- dada(derepF, err=get(paste0("errF_", run)), multithread=TRUE)
  assign(paste0("ddF_", sam), ddF)
  
  derepR <- derepFastq(filtered_reverse_reads_tmp[grep(sam,filtered_reverse_reads_tmp)])
  
  ddR <- dada(derepR, err=get(paste0("errR_", run)), multithread=TRUE)
  assign(paste0("ddR_", sam), ddR)
  
  merger <- mergePairs(ddF, derepF, ddR, derepR,
             minOverlap = 15, maxMismatch = 0, # default  minOverlap = 20
             returnRejects = FALSE, 
             justConcatenate = FALSE, trimOverhang = FALSE, verbose = FALSE)
  
  mergers_run[[sam]] <- merger
  rm(derepF,ddF,derepR,ddR, merger)
}
    rm(filtered_forward_reads_tmp, filtered_reverse_reads_tmp)
    assign(paste0("mergers_run_", run), mergers_run)
    rm(mergers_run, sample_run)
}
```

**Comment by benjjneb** [comment]
> Somehow, some mergers have information of more than one sample. Writing this issue helped me to figure out ... I think I need to check my loop...

Agree that you've found the proximate cause, but I'm not seeing right away why that is happening in those two samples.

One possible clue? The two samples joined together into that list are named `**CP1_S1**` and `LUNT**CP1_S1**92`

**Comment by fconstancias** [comment]
Thanks for your prompt reply.
I have modified my grep run selection using grep(paste0("/",run) to make sure that it selects samples starting with run (i.e., after /), e.g. :
"dada_trimmed//CP74_S110_R1_filtered.fastq.gz"

If you have a smarter trick which also takes care that some samples might be lost during filtering section, I will be happy to improve.

Thanks again, cheers
