### ISSUE TITLE
Error with unequal rows after merging (dada2 pipeline 1.8) 

### ISSUE THREAD

**Issue by mochirba** [benjjneb/dada2#715]
>That warning was caused by the files lost during filtering, and is causing the problem you're seeing. The out matrix has rows for the samples that failed to pass the filter, the other vectors don't, and its giving you a misaligned final matrix.
>
>You can fix this by first setting out <- out[file.exists(filtF),]`, to throw away the rows that were lost during filtering.

I'm having a very similar problem, I'm running the dada2 1.8 pipeline & after filtering a bunch of my controls were causing problems during the dereplicating step, but with your help I was able to tell it to only use samples that exists after filtering. Now, I'm trying to track & create csv file with cbind, but I'm getting the same error. I think after I'm losing samples after merging & creating issue with unequal row. Do you know how I can fix this? I tried the suggestion above, but it didn't work.

"In cbind(out3, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers, :
number of rows of result is not a multiple of vector length (arg 2)"

**Comment by benjjneb** [comment]
Can you post the output of the following:

```
nrow(out3)
length(dadaFs)
length(dadaRs)
length(mergers)
```

**Comment by mochirba** [comment]
I was able to do out3a = out3[exists,] and this worked to get rid/filter out the sample, so that it doesn't interfere with the cbinding step & has correct number of rows.
