### ISSUE TITLE
Can DADA2 pipeline process MinION whole 16S single read fastq files?

### ISSUE THREAD

**Issue by row2x** [benjjneb/dada2#718]
Is it possible to use DADA2 to process whole 16S single read fastq files generated by Nanoporetech MinION? The reads are on average 1500nt in length, and forward and reverse reads are interleaved in the same file. Thanks for your input.

**Comment by benjjneb** [comment]
Nope, not sensibly anyway. Nanopore error rates are way too high to meet DADA2's assumption that at least some complete error-free reads exist in the data.

**Comment by row2x** [comment]
Thanks for confirming that so quickly!
