### ISSUE TITLE
Removing Chloroplast sequences, update in Chloroplast taxonomic assignement in SILVA_v132? 

### ISSUE THREAD

**Issue by wasimbt** [benjjneb/dada2#719]
Hi, 
I saw the previous posts about how to remove the chloroplast from dataset.  Such as this one, 
subset_taxa(GlobalPatterns, (Class!="Chloroplast") | is.na(Class))

However, in my dataset (generated by using SILVA_v132) i see that the Chloroplast is an Order but not Class. Thus I am wondering, is it a recent update in SILVA_v132 or somehow I got wrong assignment for chloroplast reads?  
And considering this should I better use , 
subset_taxa(GlobalPatterns, (Order!="Chloroplast") | is.na(Order))
to remove the chloroplast from my dataset. 

Thank you!

best, 
Wasim

**Comment by benjjneb** [comment]
It's probably due to Silva changes. You can read about the v132 taxonomy changes in Silva here: https://www.arb-silva.de/documentation/release-132/
