### ISSUE TITLE
0 paired-reads (in 0 unique pairings) successfully merged

### ISSUE THREAD

**Issue by ngarud** [benjjneb/dada2#72]
Hi Ben,

I'm running DADA2 on 16S data and cannot get any output for merging reads. Here's a sample message for a test input: 0 paired-reads (in 0 unique pairings) successfully merged out of 1346 (in 66 pairings) input. 

I noticed with QIIME that I had to reverse complement reads in order to get any merging. I tried feeding the reverse complemented data (generated using seqtk) to DADA2, but still got 0 mergings. Here are the files I am using: https://www.dropbox.com/sh/8p7lezm42hziuy2/AAA6hVyo9eDF1eOQqxaVe2-ka?dl=0

Is there a command within DADA2 that does the reverse complementing? Or, do you have any alternative suggestions?

Thanks!
Nandita

**Comment by benjjneb** [comment]
It looks like your reads don't overlap. That is, the primers were separated by too much for this 2x150 sequencing to meet in the middle. What primers were you using?

(You also have a lot of chloroplasts in your data.)

**Comment by ngarud** [comment]
Thanks for taking a look. Do you think the trimming had anything to do with
this lack of merging? When I used join_paired_ends.py from the QIIME
package, I got a small fraction of reads marging, so I was surprised that I
did not get any merging with DADA2. Or, it is possible that the overlaps
identified with join_paired_ends.py were spurious?

As an alternative to merging, is it possible to run DADA2 on non-merged
reads? For example, could I assign taxonomy by just using a single read?

Also, how were you able to assess that there are a lot of chloroplasts in
the data? Thanks for pointing this out!

Nandita

**Comment by benjjneb** [comment]
There may be a small fraction of stuff that barely overlaps, or it may be spurious merging, but I wouldn't use that either way.

You can just use the forward reads. I saw the chloroplasts by running `assignTaxonomy(...)` on the dada output from the forward reads alone.

You can also "merge" in dada2 by just concatenating the reads with a NNNNNNNNNN spacer in between. This isn't handled gracefully downstream though so I don't recommend it.

**Comment by ngarud** [comment]
Thank you!

**Comment by montoyah** [comment]
Hi Ben,

I've a related question: How can I add the minimum number of overlapping bp when merging the F and R reads?

**Comment by benjjneb** [comment]
`mergePairs(..., minOverlap=20)`

By default the function requires 20 nucleotides of overlap, but you can adjust that by specifying the `minOverlap` parameter yourself.

**Comment by frannasc** [comment]
Hi Ben,
I want to start by thanking you for DADA2 and it's very important contribution to the field!
I have a similar problem as ngarud described, where my reads do not overlap and I am considering my options. Could you perhaps expand on the downstream  problems  in handling merged pair-reads using the justConcatenate=T function? I found that the addspecies function might not work,but are there any other steps that become problematic?

If using only single reads for the taxonomy assigment, can /should I run the removeBimeraDenovo on only the forward reads?
Thank you in advance!
Francisco

**Comment by benjjneb** [comment]
@frannasc

The main downstream steps, `makeSequenceTable`, `removeBimeraDenovo` and `assignTaxonomy` should all work on concatenated reads. The one caveat is that chimera removal has not been tested much on concatenated reads, so its efficacy is less certain.

If using single reads you can follow the same workflow, just without the `mergePairs` step. So you run `makeSequenceTable` on the `dadaFs` list, and then go from there.

**Comment by frannasc** [comment]
Hi Ben, 
Thanks for the quick and helpful reply!
Best
Francisco
