### ISSUE TITLE
Issue with assignTaxonomy

### ISSUE THREAD

**Issue by miraSantos** [benjjneb/dada2#720]
Hello,

I have removed chimeras from my data and I'm trying to run the following:
**taxa <- assignTaxonomy(seqtab.nochim, "C:/Users/mps48/Documents/1111AAA_2019_Spring/Capstone/Sequencing/silva_nr_v128_train_set.fa", multithread=FALSE)**

But I keep getting this error: 
**Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'finalize_filexp' not found**

I'm not sure what is causing this. Would you know what the problem is?

**Comment by benjjneb** [comment]
A little bit of googling suggests that this might be related to Rstudio, are you using Rstudio? If so I'd recommend resinstalling the latest version and seeing if that helps. If not, could you give us more information on your installation:

```
library(dada2)
sessionInfo()
file.info("C:/Users/mps48/Documents/1111AAA_2019_Spring/Capstone/Sequencing/silva_nr_v128_train_set.fa")
```

**Comment by miraSantos** [comment]
Yes, I got it to work! Thanks for your feedback!

I tried running the addspecies() function next and I get this error:
**Error: cannot allocate vector of size 2.3 Gb**

What does this mean?

**Comment by benjjneb** [comment]
> I tried running the addspecies() function next and I get this error:
Error: cannot allocate vector of size 2.3 Gb

The `addSpecies` algorithm has a pretty large up-front memory cost. That message is telling you it is failing to allocate the amount of memory it needs (2.3Gb). Are you on a 32 bit OS, or a machine with 4GB of memory or less? Typically if you have 8GB of memory or more it should work fine, but 4Gb of memory or less can lead to problems like this.

**Comment by miraSantos** [comment]
Ah, okay. My system is 64 bit with 8GB of RAM.  I tried deleting large data objects in R and closing other applications, but I still get the same error when I run it again. Perhaps, I should try this on computer with more memory?

**Comment by benjjneb** [comment]
> Perhaps, I should try this on computer with more memory?

I would recommend trying that if you have that option. If it is a non-windows machine that could help too, windows is the system that is most likely to throw up unique errors.

**Comment by miraSantos** [comment]
Okay, I will try that. Thank you so much for your quick and helpful responses!
