### ISSUE TITLE
LearnErrors results, can I proceed with this Error model?

### ISSUE THREAD

**Issue by rikku1983** [benjjneb/dada2#722]
Hi
I am dealing with V4 region 150x2 sequencing data from Nextseq. After filterAndTrim(), I have forward reads at 124 bps and reverse reads at 114 bps. And most of the samples have 2 million read pairs. Because of the high number of reads in each sample. If I use default parameters, learnErrors will end up using reads from 1 sample. So I used a 'normal' sample (pretty arbitrary, just pick a sample that no majority of reads were discarded). Then I have following plots for estimated errors.
![Screen Shot 2019-04-02 at 4 15 33 PM](https://user-images.githubusercontent.com/8211874/55433090-9e26a700-5562-11e9-8eb6-c67390f61e2f.png)
 
So my question:
1. If each sample has more bases than nbase parameter (1e8 by default), can I use certain number of reads from each sample, or I have to use up all reads from 1 sample and then go to next? Does it matter to use just one sample to estimate errors? I think if the sample used is good (no contaminations and normal in every aspects), it should be OK, is that right?

2. As you see in the plot above, the loess curves are not consistently going down. It picks some "weird" variations in the middle and to the end that it goes up temporarily (I observed this on multiple runs from Nextseq). I think probably the loess curve is picking up some noise. If I changing the "span" parameter of loess() function used in loessErrfun() to 2 (default=0.75), most of the curves would be monotonically decreasing (see below). Do you think it is necessary or even justified to use smoother loess curve? 
![Screen Shot 2019-04-02 at 4 23 40 PM](https://user-images.githubusercontent.com/8211874/55433627-b64af600-5563-11e9-856a-96e32c98fb4f.png)

Above all, I tried use the error estimates with default values (1e8 bases from 1 sample) to proceed, and later steps look OK (most reads merged and got genera assigned (85% and above)). Do you think it is OK go proceed with this error estimates (first plot), or do you have any suggestions? My main concerns come from the surprise that the error estimates are not going down consistently as the one you showed in dada2 tutorial.

Thanks,

Li

**Comment by benjjneb** [comment]
The issue is that NextSeq outputs binned quality scores, which are not as gracefully handled by the default `loess` error model fitting.

Your approach might work well, I am a bit concerned that the fitted model (black line) is below the observations (points) at a lot of q-values. Did yo include a pseudocount in your loess error fitting?

What I have done before with binned quality scores is to use the default loess fitting, but to then enforce monotonicity, i.e. set each error rate to the max detected from that or a higher quality score for that transition. I haven't tested that extensively, but in the one dataset I looked at it seemed to give acceptable results.

Hope that makes sense! If you have any results on binned quality scores we'd be happy to hear more. There was a previous issue on this from MiniSeq (which also uses binned quality scores) that we never really resolved: https://github.com/benjjneb/dada2/issues/312

**Comment by rikku1983** [comment]
Thank you for your quick reply. As you said, my quality scores are binned. So most of the weights are on those 8 scores. I tried to use sqrt(tot) as weights in loess fitting to lower the impact of uneven weights, in this case, it will  pick the increase after quality score 14. Because the score right after 14 (15,16,17) have lowest counts. But I still don't know why the error rate of there scores tend to be higher than that of quality score 14. Please see below plot.
<img width="666" alt="Screen Shot 2019-04-02 at 11 21 55 PM" src="https://user-images.githubusercontent.com/8211874/55450736-2a09f480-559e-11e9-8eab-4b29eee1044a.png">
BTW, do you think fit a straight line (lm) of these points using weights (or not) would be a terrible idea? I can tell that the slope is going down.

**Comment by benjjneb** [comment]
> But I still don't know why the error rate of there scores tend to be higher than that of quality score 14. Please see below plot.

I'm not sure I would worry too much about that, as it could be explained by noise and the far lower number of such observations.

> BTW, do you think fit a straight line (lm) of these points using weights (or not) would be a terrible idea? I can tell that the slope is going down.

It could be OK. I still think I would stick with the loess and just force monotonicity afterwards, but multiple approaches can work. The one thing to keep in mind is that usually overestimating error rates a bit is less bad than significantly underestimating error rates.

**Comment by rikku1983** [comment]
Thank you for your explanation. I will try loess curve fitting with monotonicity enforced. Thank you again!
