### ISSUE TITLE
Function "plotQualityProfile" not found

### ISSUE THREAD

**Issue by Nathhub** [benjjneb/dada2#723]
Hi,

I have been following the steps in the dada2 tutorial. When I try to use the function "plotQualityProfile", I receive that error message: 

Error in plotQualityProfile(fnFs[1:2]) : 
  could not find function "plotQualityProfile" 

I am using  R version 3.5.3 on windows 10
> packageVersion("dada2")
[1] ‘1.10.1’

Do you have an idea what could be the problem?
Thanks in advance for your help,
Nathan

**Comment by benjjneb** [comment]
Have you tried restarting R and reloading the dada2 package?
It's not finding the function name in the paths its searching, and that is probably the first thing to try.

**Comment by Nathhub** [comment]
Hi Benjamin,

Thank you for your answer. 
I have restarted R and when reloading dada2 I have been asked to install package Rcpp. 
It is working now! 
Thank you very much
