### ISSUE TITLE
ASV table to phyloseq object

### ISSUE THREAD

**Issue by LenaLapidot** [benjjneb/dada2#724]
Hello,
I'm relatively new to the phyloseq and DADA2 pipeline.
I have an ASV table that contains the taxonomy and the metadata.
I have to transform it to a phyloseq object, to visualize the relative abundance and plot nMDS.

How can I transform such a table to a phyloseq object? In the tutorials, It's done separately for the OTU table, the taxonomy and metadata and then merged together.. 

Thank you!
![image](https://user-images.githubusercontent.com/23721527/55486434-fcbc5580-5634-11e9-8300-9cf247bb8aa2.png)

**Comment by benjjneb** [comment]
This is better posted to the phyloseq issues forum, as the question here is on how to import (mothur?) data into a phyloseq object: https://github.com/joey711/phyloseq/issues

One thing for sure is that you are going to want to separate the taxonomy from the ASV table. The ASV table should be a matrix with values equal to the counts, and rows/columns named by the samples/ASVs.

**Comment by LenaLapidot** [comment]
Thank you, I'll post it in the phyloseq forum.
