### ISSUE TITLE
Error with Encoding of DNA Files

### ISSUE THREAD

**Issue by compbiolover** [benjjneb/dada2#725]
Hi everyone,
I have recently encountered a problem while trying to plot the quality profiles of my reads in DADA2 version 1.10.1 using R 3.5.2 on Ubuntu 18.04.1. After successfully loading in my files I encounter the following error: Error in x$yield(...) : 
  _DNAencode(): invalid DNAString input character: '1' (byte value 49).
I have done some research and it appears that this is an encoding problem with the file. Unfortunately, when looking at my raw .fastq.gz files in a text editor they appear to be formatted correctly. Would really appreciate some feedback on what may be causing this problem. I am willing to share the files if that would be helpful. Thanks!

**Comment by benjjneb** [comment]
If you are comfortable with a little bit of shell and R scripting, the ideal way to diagnose this is to identify which line is causing the issue. A hacky but straightforward way to do this is to first identify which file is causing problems, then look at subsets of the reads until you find the read/line that is causing the problem. There are 4 lines per read in fastq files, so after un-gzipping to a flat fastq format, you can use `head -n 400 trouble.fastq > test.fastq` to create a file with the first 100 reads. Then try `readFastq("test.fastq")` and see if this error arises (load the ShortRead library in R first). You can use that approach to narrow down what line is causing the error and then take a look.

If that is too much we can also take a look at the file, but please identify one example file first that is causing this issue.

**Comment by compbiolover** [comment]
@benjjneb Thanks for the help! I will use this approach and track down which line is causing the error and post again once it is resolved.

**Comment by compbiolover** [comment]
@benjjneb It looks like I found my problem. Thanks so much for pointing me towards the ShortRead library. It was helpful in solving the problem.
