### ISSUE TITLE
filter and trim samples separately

### ISSUE THREAD

**Issue by bernt-matthias** [benjjneb/dada2#727]
Is there a difference of calling 

`filterAndTrim(c(sample1,sample2), filtFs=c(filtSample1, filtSample2), ... )`

and calling 

```
filterAndTrim(c(sample1), filtFs=c(filtSample1), ... )
filterAndTrim(c(sample2), filtFs=c(filtSample2), ... )
```

I implemented the latter one in the Galaxy wrapper, since its faster (when run independently).

**Comment by benjjneb** [comment]
Nope, same output either way.

**Comment by bernt-matthias** [comment]
Thanks a lot.
