### ISSUE TITLE
Heterogeneity spacers and variable starting positions

### ISSUE THREAD

**Issue by paalmbj** [benjjneb/dada2#728]
We are using a protocol which introduces heterogeneity spacers of length 1-7 (https://microbiomejournal.biomedcentral.com/articles/10.1186/2049-2618-2-6). We demultiplex the reads and remove barcodes and spacers using a custom tool. Now the fastq file for reads with spacer length 0 start at cycle 12 of sequencing, while reads with spacer length 7 start at cycle 19. (We also use a trimLeft of 20 to remove the primer).

Is there any way to compensate for this shift when training the error model? Should I only process samples with the same spacer length in read 1 and read 2 together?

**Comment by benjjneb** [comment]
The spacers are removed by your custom tool? You should be good to go, no issue with the error model at all. The error model is already assuming a consistent relationship between quality scores and error rates across nucleotides, so this shift isn't affecting any assumptions of the error model.

**Comment by benjjneb** [comment]
Feel free to reopen if any further questions.

**Comment by paalmbj** [comment]
Thanks for the clear explanation!
