### ISSUE TITLE
Sequencing fungi using 5 different forward and 2 reverse primers with the same index

### ISSUE THREAD

**Issue by Vilchez-Vargas** [benjjneb/dada2#730]
Hello,

Thanks a lot for your great program for data analysis.

Due to the lack of having an unique pair of primers to amplify "all" fungi, I decided to amplify the same sample with a pool of different primers but only one barcode. My question is, how can I change the commands "FWD <-  and REV <-"  to indicate that I have several sequences.

Thank you in advanced for your considerable help

Kind Regards

Ramiro

**Comment by benjjneb** [comment]
Can you clarify what you are trying to modify? Are you working from the ITS tutorial and trying to detect and remove the multiple primer sequences?

**Comment by Vilchez-Vargas** [comment]
Yes, indeed.

in the ITS tutorial only is detected one forward primer and one reverse primer. I would need to detect and remove five different forward primers and two different reverse primers

**Comment by benjjneb** [comment]
Is it 10 total primer combinations?
You might just need to run through the primer detection/removal part for each primer combination. There is probably a way to do everything at once, but you'd have to look into the cutadapt documentation to see as I haven't tried to remove multiple primer variants at once with that tool.

**Comment by Vilchez-Vargas** [comment]
Thanks!, I will do so.

Greetings

Ramiro
