### ISSUE TITLE
Get quality score values beyond the plot

### ISSUE THREAD

**Issue by mrocafort** [benjjneb/dada2#732]
Hello,
I am trying to get the values that the QualityPlotProfile uses to plot the data, so I can automatically detect when the first low quality occurs (e.g. quality <20) and up to what length the high quality are maintained and set it automatically for the FilterandTrim process without need to check on the plot since I am running dada2 in the terminal without "human intervention".

I have been able to access the gg but I do not fully understand what Data.Cycle, Data.Score and Data.Count means, sorry,

Thank you,
Muntsa

**Comment by benjjneb** [comment]
`plotQualityProfile` returns a ggplot object, so you can just access the `$Data` data.frame from that object to get the data used in the plot.

`$Cycle` is the nucleotide position in the read, `$Score` is the quality score, and `$Count` is the number of times that quality score was observed at that nucloetide position.

**Comment by benjjneb** [comment]
Feel free to reopen if any further questions.

**Comment by dikiprawisuda** [comment]
Hi, may I know how to do that? How to know exact sequence length that the base going bad. Or even, how to change the plot? It is an amazing plot but I am wondering for other kind of plot with similar data. Also how to add more both x and y label for more details, for example.

**Comment by benjjneb** [comment]
@dikiprawisuda Same as described above https://github.com/benjjneb/dada2/issues/732#issuecomment-481917540

All the data in the plot is in the data.frame that you can just extract from the plot. Then you can remake and revise the plot as you wish using ggplot2.

**Comment by dikiprawisuda** [comment]
Hi, is there a way to visualize the plotqualityprofile to become like this? 
> Forward read
> ![image](https://cloud.githubusercontent.com/assets/1048569/25510483/3eccf96c-2b75-11e7-9f2d-07fd784c8cab.png)
> Reverse read
> ![image](https://cloud.githubusercontent.com/assets/1048569/25510491/508feb00-2b75-11e7-8b9d-7fef14ea583c.png)

These are my best attempt, is there something that I missed out?
`dataplotqualityFwd <- plotQualityProfile(fnFs[1:3])
dataplotqualityRev <- plotQualityProfile(fnRs[1:3])

fwdData <- dataplotqualityFwd$data
revData <- dataplotqualityRev$data

fwdPlotData  <- fwdData %>% 
                group_by(Cycle) %>% 
                summarise(meanScore = mean(Score))
as_tibble(fwdPlotData)
ggplot(fwdPlotData, aes(Cycle, meanScore)) +
  geom_boxplot()`

Thank you very much.

**Comment by benjjneb** [comment]
It's possible to almost completely recreate that plot using various ggplot2 commands, but it would be a fair amoutn of work due to some of the non-standard elements (e.g. different quality binning for early bases and later bases).

But... if that's the exact plot you want, and I believe that's the one MultiQC produces(?), why not just use MultiQC to make that plot?

**Comment by dikiprawisuda** [comment]
Hi, I am so sorry for my last reply.
Yes, for individual plot or graphics it was generated by FastQC, but, probably, for disclosing both reverse and forward correspond to the plot above, MultiQC are required.

Thank you.
