### ISSUE TITLE
Crashing when assigning species in large dataset

### ISSUE THREAD

**Issue by as703** [benjjneb/dada2#733]
I'm encountering a persistent error when trying to assign species level taxonomy in dada2. I'm assigning taxonomy to a large dataset: 611 samples with 48000 SVs. I'm using dada2 v 1.10.1. I've run "assignTaxonomy" without issue but when trying to run "addSpecies" R persistently crashes (no error in the code). 

I've tried taking "n" down to 1000 without effect. I'm presuming this is a memory issue as I've not had problems with smaller datasets but I'm using a bioinformatics server with 8 quad-core CPUs and 64gb of RAM. Is there any way around this issue?

Many thanks in advance for your help.

**Comment by benjjneb** [comment]
Could you test the workaround of splitting the taxonomy matrix into chunks of say 4000 rows, running `addSpecies` on each, and then rbinding them back together? We'd love to hear if that works or doesn't either way.

Also, what is `R.version` here?

**Comment by as703** [comment]
Thanks for the advice - I'll give that a go. Using R version 3.5.0. Do you think updating would make a significant difference?

**Comment by benjjneb** [comment]
> Using R version 3.5.0. Do you think updating would make a significant difference?

I don't think so, you are pretty up-to-date. I would try the workaround.

**Comment by as703** [comment]
I did as you suggested, borrowing some code form a similar thread:

`chunk.size <- 4000
chunks <- split(c(1:nrow(taxtab)),
                sort(c(1:nrow(taxtab))%%ceiling(nrow(taxtab)/chunk.size)))

chunks.species <- lapply(chunks,
                         function(x){
                           return(addSpecies(taxtab[x,],
                                             refFasta = species_fasta, verbose = TRUE))
                         })
taxtab.species <- do.call(rbind, chunks.species)`

It worked nicely. Out of interest, why did assignTaxonomy run ok while assignSpecies didn't?

Many thanks for your assistance.

**Comment by benjjneb** [comment]
Glad it worked, but this workaround really shouldn't be needed, we need to fix this.

> Out of interest, why did assignTaxonomy run ok while assignSpecies didn't?

The algorithms and more importantly the data structures used by each method are totally different and have different memory and time scaling properties.

**Comment by benjjneb** [comment]
I think this is fixed now by adding explicit removal and garbage collection of the `PDict` objects within the loop in `assignSpecies`, but any new reports on this are welcome as I have struggled to really understand memory usage of the exact string matching algorithm we are using.

**Comment by apascualgarcia** [comment]
Dear Benjamin,

I am experiencing the same issue in `R 3.6` and dada2 `1.16`, and my collaborator @befriendabacterium in the latest version of both R and dada2, with the same dataset. 

I've been able to run it splitting the taxonomy matrix into chunks, as you suggested.

You mentioned you were including an explicit removal and garbage collection of the `PDict` objects within the loop in `assignSpecies`, but I realized that it will only work if `tryRC == TRUE`. Might be the case that `gc` and `rm` should be outside the if structure?

Thanks for the great work.

**Comment by benjjneb** [comment]
@apascualgarcia 
I think this code https://github.com/benjjneb/dada2/blob/master/R/taxonomy.R#L272 should work regardless of `tryRC`, the `if` statement with no curly braces will just apply to the rest of the line it appears on.

That said, does this memory issue resolve if `tryRC=TRUE`? Or is it the same.

Is there any way for you to observe the amount of peak memory being requested when. you run the function on the whole dataset or in chunks?

**Comment by apascualgarcia** [comment]
You are right about the `if`, I'm sorry for that (I have a different indentation and I messed up with the brackets). Indeed, with `tryRC=TRUE` it also crashes.

When I run the function the memory increases in a step-wise manner: it remains constant for a period until there is an increase, and these increases are roughly the same (consistent with the for loop behaviour, this is why I ended up having a look at the loop).  On the other hand, running it in chunks the memory remains constant. So it looks that for some reason the `gc` within the loop has no effect. I've seen that R has some problems of [fragmentation](https://stackoverflow.com/questions/14580233/why-does-gc-not-free-memory) when running string/regexp operations.

**Comment by benjjneb** [comment]
@apascualgarcia To be honest, this is probably a `wontfix` for now, as long as there is a straightforward workaround. I didn't understand the ins and outs of PDict memory usage and R gc last time I looked into this sufficiently that I have much confidence I would be able to fix what is going on. I welcome any input from those better versed in R memory allocation and gc if they have advice though!

**Comment by apascualgarcia** [comment]
Yeap, I can totally see that it doesn't worth more effort, I am sorry I can't be of more help. Including the split of the taxonomy matrix into chunks is  the only straightforward workaround I can see, admittedly not an elegant one.

**Comment by Doznkekz** [comment]
I do have the same Issue (Ubuntu, R v4.1.2, DADA2 v1.22.0). The workaround works well!
