### ISSUE TITLE
learnErrors -- higher error rates at Q40 vs Q30?

### ISSUE THREAD

**Issue by Johnson-Stephen** [benjjneb/dada2#734]
Hi,

I'm trying to process some low biomass V3-V5 data (2x250, Miseq, trimmed to c(230, 230)) and I'm concerned about some behavior:
```
110032460 total bases in 478402 reads from 8 samples will be used for learning the error rates.
110032460 total bases in 478402 reads from 8 samples will be used for learning the error rates.
Processing: BT_145_S3 
Dereplicating sequence entries in Fastq file: BT_145_S3_R1.filt.fastq.gz
Encountered 6977 unique sequences from 67087 total sequences read.
Sample 1 - 67087 reads in 6977 unique sequences.
Dereplicating sequence entries in Fastq file: BT_145_S3_R2.filt.fastq.gz
Encountered 8886 unique sequences from 67087 total sequences read.
Sample 1 - 67087 reads in 8886 unique sequences.
65990 paired-reads (in 1013 unique pairings) successfully merged out of 65990 (in 1013 pairings) input.
Processing: BT_146_S4 
Dereplicating sequence entries in Fastq file: BT_146_S4_R1.filt.fastq.gz
Encountered 7424 unique sequences from 89134 total sequences read.
Sample 1 - 89134 reads in 7424 unique sequences.
Dereplicating sequence entries in Fastq file: BT_146_S4_R2.filt.fastq.gz
Encountered 10434 unique sequences from 89134 total sequences read.
Sample 1 - 89134 reads in 10434 unique sequences.
87733 paired-reads (in 1111 unique pairings) successfully merged out of 87733 (in 1111 pairings) input.
Processing: BT_147_S5 
Dereplicating sequence entries in Fastq file: BT_147_S5_R1.filt.fastq.gz
Encountered 2699 unique sequences from 59506 total sequences read.
Sample 1 - 59506 reads in 2699 unique sequences.
Dereplicating sequence entries in Fastq file: BT_147_S5_R2.filt.fastq.gz
Encountered 4351 unique sequences from 59506 total sequences read.
Sample 1 - 59506 reads in 4351 unique sequences.
59173 paired-reads (in 318 unique pairings) successfully merged out of 59173 (in 318 pairings) input.
Processing: BT_148_S6 
Dereplicating sequence entries in Fastq file: BT_148_S6_R1.filt.fastq.gz
Encountered 5687 unique sequences from 67901 total sequences read.
Sample 1 - 67901 reads in 5687 unique sequences.
Dereplicating sequence entries in Fastq file: BT_148_S6_R2.filt.fastq.gz
Encountered 7349 unique sequences from 67901 total sequences read.
Sample 1 - 67901 reads in 7349 unique sequences.
67062 paired-reads (in 754 unique pairings) successfully merged out of 67062 (in 754 pairings) input.
Processing: BT_149_S7 
Dereplicating sequence entries in Fastq file: BT_149_S7_R1.filt.fastq.gz
Encountered 7352 unique sequences from 75979 total sequences read.
Sample 1 - 75979 reads in 7352 unique sequences.
Dereplicating sequence entries in Fastq file: BT_149_S7_R2.filt.fastq.gz
Encountered 9681 unique sequences from 75979 total sequences read.
Sample 1 - 75979 reads in 9681 unique sequences.
74926 paired-reads (in 953 unique pairings) successfully merged out of 74926 (in 953 pairings) input.
Processing: BT_150_S8 
Dereplicating sequence entries in Fastq file: BT_150_S8_R1.filt.fastq.gz
Encountered 10098 unique sequences from 84352 total sequences read.
Sample 1 - 84352 reads in 10098 unique sequences.
Dereplicating sequence entries in Fastq file: BT_150_S8_R2.filt.fastq.gz
Encountered 12891 unique sequences from 84352 total sequences read.
Sample 1 - 84352 reads in 12891 unique sequences.
82712 paired-reads (in 1366 unique pairings) successfully merged out of 82712 (in 1366 pairings) input.
Processing: Mock_community_S2 
Dereplicating sequence entries in Fastq file: Mock_community_S2_R1.filt.fastq.gz
Encountered 2788 unique sequences from 31283 total sequences read.
Sample 1 - 31283 reads in 2788 unique sequences.
Dereplicating sequence entries in Fastq file: Mock_community_S2_R2.filt.fastq.gz
Encountered 4129 unique sequences from 31283 total sequences read.
Sample 1 - 31283 reads in 4129 unique sequences.
31042 paired-reads (in 1025 unique pairings) successfully merged out of 31042 (in 1025 pairings) input.
Processing: NTC_S1 
Dereplicating sequence entries in Fastq file: NTC_S1_R1.filt.fastq.gz
Encountered 422 unique sequences from 3160 total sequences read.
Sample 1 - 3160 reads in 422 unique sequences.
Dereplicating sequence entries in Fastq file: NTC_S1_R2.filt.fastq.gz
Encountered 610 unique sequences from 3160 total sequences read.
Sample 1 - 3160 reads in 610 unique sequences.
3059 paired-reads (in 93 unique pairings) successfully merged out of 3059 (in 93 pairings) input.
Table dimentions: [1]    8 4652
```
When I plot the errors, I notice a lot of the models have a "hook" showing higher error rates at, say Q40 compared to Q30. Is this something to be particularly concerned with? If so, what's the best way to deal with it?

Errors for R1:
![R1errors](https://user-images.githubusercontent.com/17412934/56444201-5c656280-62bd-11e9-8c24-fe0bae531099.png)

Errors for R2:
![R2errors](https://user-images.githubusercontent.com/17412934/56444260-96ceff80-62bd-11e9-9921-64cfa0978353.png)

Any assistance you can provide will be greatly appreciated. Thank you for your time!

**Comment by benjjneb** [comment]
Typically I would not worry about this. It is not that uncommon to get a bit of a "hook", often when there are relatively few maximum quality scores in the dataset (our visualization does a poor job of conveying how many data points are there at each quality score).

The "hook" in your reverse reads is bigger than I usually see though. I probably wouldn't worry about it anyway, but you can try to do things like enforce monotonicity on the error rates if you want, to see if anything materially changes. The error model is just a matrix and is easy to modify.

**Comment by soluna1** [comment]
Hi, 
I would appreciate some comments on these error plots. It surprises me the 'hook' between CQS 30-40, but mostly the errors showed in A2A, C2C... transitions. This are 18s -v9 (2x 150) Ilumina sequences, truncLen= c(100, 80), MaxEE= c(1,2), rm.phix=T, compress=R, multithread=T. Thanks in advance.
![image](https://user-images.githubusercontent.com/16171059/60873586-ed9e0280-a236-11e9-9ca2-50ff2afda4e9.png)

![image](https://user-images.githubusercontent.com/16171059/60873643-fee70f00-a236-11e9-90bf-2f76fea5f61f.png)

**Comment by benjjneb** [comment]
@soluna1 Typically the sort of discrepancies you are highlighting are caused by there being very few observations at the quality scores where the estimated error rates deviate from the model. The model fitting procedure weights the number of observations, while our plot doesn't do a good job of showing that, as a point supported by 10 observations looks the same as one supported by 10,000.

**Comment by soluna1** [comment]
Thanks @benjjneb for your answer. So, I understand that I shouldn't worry about these deviations. What surprises me that all samples of 18s amplicons show this pattern but not the reads from 16s amplicons.

**Comment by soluna1** [comment]
Hi, reading about similar cases, I found out that the weird behaviour in my error plots can also be due to the use of binned scores #722 . Then, I set the argument  qualityType =  "FastqQuality" in learnerror function (plot 1).  However, I did see a great different with the normal error-plot.
plot_1
<img width="847" alt="image" src="https://user-images.githubusercontent.com/16171059/61931756-e2aad800-af81-11e9-9d59-6e1fda069602.png">
Plot_2
<img width="848" alt="image" src="https://user-images.githubusercontent.com/16171059/61931803-0110d380-af82-11e9-9fe2-3bada1d49093.png">

So, my questions are:
1. How can I be sure that the error model fitting is ok to proceed with the dada function or it requieres some adjustments?
2. In #722 appears this option "What I have done before with binned quality scores is to use the default loess fitting, but to then enforce monotonicity, i.e. set each error rate to the max detected from that or a higher quality score for that transition." But, I don't know how to implement it, could you give some hints please?

Thanks in advance for your help.

**Comment by benjjneb** [comment]
> How can I be sure that the error model fitting is ok to proceed with the dada function or it requieres some adjustments?

In general checking on the error model profiles is more of a sanity check to see if anything has gone horribly wrong. The goal is to have a good error model, not a perfect one. These profiles don't look great, but they haven't gone horribly wrong either.

> In #722 appears this option "What I have done before with binned quality scores is to use the default loess fitting, but to then enforce monotonicity, i.e. set each error rate to the max detected from that or a higher quality score for that transition." But, I don't know how to implement it, could you give some hints please?

Basically here you could set each error rate that is below the model value at the max Q score to the model value at that max Q score. The error model is just a matrix, so the following code will do that:

```
err.mat <- getErrors(err) # Forces the error model into standard matrix format
# Force all error model rates that to be at least as high as the error model value of the max Q score
for(trans in c("A2C", "A2G", "A2T", "C2A", "C2G", "C2T", "G2A", "G2C", "G2T", "T2A", "T2C", "T2G")) {
  err.mat[trans,] <- pmax(err.mat[trans,], err.mat[trans,ncol(err.mat)])
}
plotErrors(err.mat)
```

**Comment by soluna1** [comment]
Thanks a lot for your answer and the suggestions. I will try the code to see if the error plots improve a bit. I think, as you commented, that it won't change so much the resulting ASVs. Still, perhaps some "fitting parameter", together with the plot, would help to know how well the model has gone. One clear thing to me is that, as happens with all models anyway, binned scores are not the best option as they provide less data for the calculation, so the adjustment will be clearly poorer. It is not a dada2 problem itself, but something that perhaps could be improved. Thanks again.
