### ISSUE TITLE
R Error in memory.limit(size = 8000) : 

### ISSUE THREAD

**Issue by Manan555** [benjjneb/dada2#736]
I am keep getting error for increase memory.
> memory.limit(size=8000)
Error in memory.limit(size = 8000) : 
  don't be silly!: your machine has a 4Gb address 
>
Error: cannot allocate vector of size 290.9 Mb

#I have 8Gb ram, still affecting.

**Comment by benjjneb** [comment]
What is the output of `R.version`?

I think you probably are running a 32 bit version of R or a 32 bit OS.

**Comment by benjjneb** [comment]
Feel free to re-open as necessary.
