### ISSUE TITLE
Mismatched forward and reverse reads

### ISSUE THREAD

**Issue by emilyjunkins** [benjjneb/dada2#737]
Hello,

I am getting the following error:
`Error in fastqPairedFilter(c(fnFs[i], fnRs[i]), c(filtFs[i], filtRs[i]),  : 
  Mismatched forward and reverse sequence files: 7483, 3490.`

I used q1 to demultiplex my reads using the suggested parameters. I added the `_R1` or `_R2` to each file.
The following is my dada2 script: 
`path <- "/home/ocho/RC2PWPCR_ASVs/qiimedemux"
fns <- list.files(path)`

`fastqs <- fns[grepl(".fastq$", fns)]
fastqs <- sort(fastqs)`

`fnFs <- fastqs[grepl("_R1", fastqs)]
fnRs <- fastqs[grepl("_R2", fastqs)]`
`sample.names <- sapply(strsplit(fnFs, "_"), `[`, 1)`

`fnFs <- file.path(path, fnFs)
fnRs <- file.path(path, fnRs)`

`filt_path <- file.path(path,"filtered")
if(!file_test("-d", filt_path)) dir.create(filt_path)`
`filtFs <- file.path(filt_path, paste0(sample.names, "_F_filt.fastq"))
filtRs <- file.path(filt_path, paste0(sample.names, "_R_filt.fastq"))`

#i need to remove the barcode (12) + the linkerprimer (37) AND the R primer (20)
#because there is only 9bp overlap here, I cannot truncate

`for(i in seq_along(fnFs)) {
  fastqPairedFilter(c(fnFs[i], fnRs[i]), c(filtFs[i], filtRs[i]),
                    trimLeft = c(49, 20), truncLen = c(239, 251),
                    maxN = 0, maxEE = 2, truncQ = 2,
                    verbose = TRUE)`

And I received the above error message. I am not quite sure the issue as I have prepared sequences this way before (using q1 demultiplexing algorithm). To verify, I also used adapter removal's demultiplex algorithm as well and it was the same error. The files that it gets hung on are are also the first in the lists (samples `10A_R1.fastq` and `10A_R2.fastq`). 

I have seen this problem mentioned [here](https://github.com/benjjneb/dada2/issues/261) but couldn't fit the solutions to my issue and also on q2 where it seemed to be a file naming [issue](https://forum.qiime2.org/t/dada2-mismatched-fwd-and-rev-reads/2133). 

Thanks!

**Comment by benjjneb** [comment]
Did you try setting `matchIDs=TRUE` in `fastqPairedFilter`? That is intended for this situation (I think) and will rematch paired-end reads by their ID.

Also, the extremely short overlap between your sequences will cause all reads to merge when running default `mergePairs`. You'll need to look at the options for that function, specifically `minOverlap`, and you may also want to consider truncating off the end of the reverse reads if they are particularly bad quality and just concatenating the F/R reads instead of merging them.

**Comment by emilyjunkins** [comment]
Thanks!
`matchIDs = TRUE` fixed that issue. They now are not passing the filter, but I think I have some particularly bad R reads. I have a deep spike in quality around 50-75 bp with I plot the quality as well as the usually poor quality ends. In these situations, I usually drop the R reads as a whole and proceed with my ~180-200 bp F read for analysis. But if I truncate a large portion and concatenate them instead of merging, do I do this in dada2 or will I need process them another way?  

My concern is that spike introducing some highly variable, low quality basecalls that would affect ASVs inference.

Thanks!

**Comment by benjjneb** [comment]
> I have a deep spike in quality around 50-75 bp with I plot the quality as well as the usually poor quality ends. In these situations, I usually drop the R reads as a whole and proceed with my ~180-200 bp F read for analysis.

That sounds like the way to go in this case to me.

> But if I truncate a large portion and concatenate them instead of merging, do I do this in dada2 or will I need process them another way?

You could do that in dada2, with `mergePairs(..., justConcatenate=TRUE)`. But based on what you've said about this specific dataset I would lean towards just using the forward reads.

**Comment by emilyjunkins** [comment]
Great! I am definitely proceeding with out my reverse reads, but appreciate the `mergePairs` info. Thanks again!

**Comment by benjjneb** [comment]
Sound good, please reopen if new questions arise.

**Comment by mfave29** [comment]
Hello,
I have a similar error : 

```{r}
filtFs <- file.path(path, "filtered", paste0(sample.names, "_1_filt.fastq.gz"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_2_filt.fastq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names
```

```{r}
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,240),
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE, multithread=TRUE) 
head(out)
```

Error in filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen = c(240, 240), : These are the errors (up to 5) encountered in individual cores... Error in (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0, : Mismatched forward and reverse sequence files: 100000, 21935. Error in (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0, : Mismatched forward and reverse sequence files: 100000, 21935. Error in (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0, : Mismatched forward and reverse sequence files: 100000, 21935. Error in (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0, : Mismatched forward and reverse sequence files: 100000, 21935. Error in (function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0, : Mismatched forward and reverse sequence files: 100000, 21935.

What can I do ? 
 
Thanks,

Marie

**Comment by benjjneb** [comment]
@mfave29 The error message is indicating you have a different number of reads in your forward fastq files (100000) than in your reverse fastq file (21935). How could that have happened? Given that the same numbers are popping up every time, it also suggests your looking at the same files over and over.

I'd start by inspecting your `fnFs` and `fnRs` vectors of filenames to see if there is something malformed there.

**Comment by mfave29** [comment]
I have the same number of reads;whether for reverse or for forward as indicated by : 


```{r}
plotQualityProfile(fnFs[1:2])
```

and 


```{r}
plotQualityProfile(fnRs[1:2])
```


127371 for Forward and 113081 for Reverse


I am so disappointed...

Thanks

**Comment by benjjneb** [comment]
I'd inspect the read numbers for the whole set of `fnFs` and `fnRs` then to see if any discrepancies come up.

```
library(ShortRead)
cound.reads <- function(fn) {
  length(readFastq(fn))
}
nreadF <- sapply(fnFs, count.reads)
nreadR <- sapply(fnRs, count.reads)
table(nreadF == nreadR)
```

**Comment by mfave29** [comment]
When I do

```{r}
library(ShortRead)
library(seqbias)
cound.reads <- function(fn) {length(readFastq(fn))}
nreadF <- sapply(fnFs, count.reads)
nreadR <- sapply(fnRs, count.reads)
table(nreadF == nreadR)
```

I have : Error in is(I, "GRanges") : argument "I" is missing, with no default

**Comment by benjjneb** [comment]
Is it from the `cound.reads` type?

**Comment by mfave29** [comment]
I replace the "d" of "cound" by "d". 
Now, when my request is : 

```{r}
library(ShortRead)
library(seqbias)
count.reads <- function(fn) {length(readFastq(fn))}
nreadF <- sapply(fnFs, count.reads)
nreadR <- sapply(fnRs, count.reads)
table(nreadF == nreadR)
```

I have : 

Error: Input/Output file(s): /home/rstudio/Controle_continu_3/Data_CC3/SRR1586342_2.fastq.gz message: IncompatibleTypes message: invalid class “ShortReadQ” object: some sread and quality widths differ

Is it because my files are in fastq.gz ? 

Thanks

**Comment by benjjneb** [comment]
No it will autodetect gzipped files.

> some sread and quality widths differ

This suggests that your sequence files have been previously preprocessed in a way that did not maintain matching between quality scores and bases. This has come up before as a problematic consequence of some (older) fastq trimming software.

Can you get the original fastq files prior to this preprocessing?

**Comment by mfave29** [comment]
In fact, I downloaded data on NCBI with accession numbers and I obtain this fastq files

**Comment by benjjneb** [comment]
> In fact, I downloaded data on NCBI with accession numbers and I obtain this fastq files

Yes, this is the most common way people encounter this problem these days (as more modern fastq trimming softwares don't create this error).

There's no requirement to submit the original raw data to NCBI. In this case, it seems that pre-processed fastq files were uploaded that have this mismatch between bases and quality scores as a result.

**Comment by mfave29** [comment]
Thanks for thèse explanations.

So, how resolve this problem ? Is there a solution ?

Thanks

**Comment by benjjneb** [comment]
You can try contacting the study authors for the original fastq files, if they still have them.

You can also just convert the files to fasta and use an OTU method that doesn't need quality scores.

**Comment by mfave29** [comment]
Ho...
Thank you for everything.
Marie
