### ISSUE TITLE
reads can not merge

### ISSUE THREAD

**Issue by chloelulu** [benjjneb/dada2#739]
Hi，developer, 
Thanks for developing such amazing software. The biological sequences make much more sense. I really like the theory behind dada2, since I am also a machine learning fan. 
May I please ask two questions?

(1) How can I achieve more biological reads retained, but not removed. I have the data like this, which is produced from 515F-806R primer. It is my first time to meet this situation. I have successfully run more than 4 batches of data in DADA2. But this time, failed. 
![image](https://user-images.githubusercontent.com/28763565/56585120-2ff66280-65ab-11e9-93de-e0fb142e0adb.png)
I have tried the forward reads run, and results show that nearly 100% reads can hit reference. So I tried to use the method tutorial described. 
![image](https://user-images.githubusercontent.com/28763565/56585353-a8f5ba00-65ab-11e9-96e6-daeda09ef4dc.png)
But I got an error in the next procedure. 
![image](https://user-images.githubusercontent.com/28763565/56585630-3802d200-65ac-11e9-891e-b24bcd84858b.png)
May I please have the help? 

(2) Previously, I used QIIME2-DADA2 run my data. QIIME2 can merge multiple run results. Can I merge multiple runs in DADA2-R? Since my former 4 run are finished in QIIME2-DADA2, and I need all these 4 batches data analysis together. Shall I need to re-run all the sequencing batches in R, I am afraid? 

Looking forward to your suggestions. 
Sincerely.

**Comment by benjjneb** [comment]
What version of the package are you using? `packageVersion("dada2")`

I would be concerned by the low number of reads merging given that you are using the 515/806 primer set that almost completely overlaps before any trimming/truncation.

Can you also provide the full filtering command you used on your data, and perhaps also the `plotQualityProfile` plots from the F/R reads?

**Comment by chloelulu** [comment]
Hi, @benjjneb ,
Thanks for the reply. Appreciate it!
![image](https://user-images.githubusercontent.com/28763565/56663587-719f1000-6674-11e9-8b3c-7c2cdc00b66e.png)
Reads quality I plotted in QIIME2. 
![image](https://user-images.githubusercontent.com/28763565/56665292-c1330b00-6677-11e9-8202-e3984c0fad93.png)
It seems that reads can not merge. But I want to continue use DADA2, since all my data are analyzed in DADA2. So, here I want to give some insert for my R1-R2 to merge. 

Thanks so much.  :-)

**Comment by chloelulu** [comment]
Hi, @benjjneb 
I see the reason now. It was caused by the version. I tried version 1.10.1. Now works. 
![image](https://user-images.githubusercontent.com/28763565/56684971-d0797f00-669e-11e9-9042-a4816083a016.png)
However, I have another question. I analyzed the reads in DADA2 step by step. It seems that raw R1-R2 can merge, but after dada, most R1-R2 are changed, and they can not merge anymore. Some even do not have any overlaps. 
Does that's true? OR dada may over-estimate the error? Since if I only include the R1 in dada, result shows that all most all the raw clean reads can hit reference. For R2, except for 10% reads in sample L51, others all can hit reference database. If they can hit the reference, it means they are biological sequences. 
I am so confusing. May I have your suggestion? 
Enclosed I attach my samples.
Looking forward to your suggestions. 
Thanks a lot. 
[Archive.zip](https://github.com/benjjneb/dada2/files/3113924/Archive.zip)

**Comment by benjjneb** [comment]
> It seems that raw R1-R2 can merge, but after dada, most R1-R2 are changed, and they can not merge anymore. Some even do not have any overlaps.

I don't understand, the read-tracking stats you posted show ~90% of reads successfully merging?

Is that not correct? If not, can you show the stats for when reads are not merging? Also can you show the exact filtering command you are using? It is important, because your 2x150 reads don't overlap a lot for this primer set ( I was assuming you were using 2x250 before). Are your primers included on your reads?

**Comment by chloelulu** [comment]
Hi, @benjjneb, 

This figure shows the result from `mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE,justConcatenate =TRUE)`
![image](https://user-images.githubusercontent.com/28763565/56702427-0126dc00-66d2-11e9-8240-e279fa157831.png)
But If not concatenate, with code `mergers <- mergePairs(dadaFs, derepFs, dadaRs, derepRs, verbose=TRUE)`, it will be as below,
![image](https://user-images.githubusercontent.com/28763565/56702517-67136380-66d2-11e9-881c-12538ae4b971.png)
Primers have been removed from reads, I am always using 151bp pair-ended 515f-806r. It always success in my last several batches, while this time is different. 

This this the quality plot, then I trim with code
`out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(150,150), maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE)`
![image](https://user-images.githubusercontent.com/28763565/56702552-a6da4b00-66d2-11e9-88ab-f7fb5f871562.png)
Appreciate your help.

**Comment by chloelulu** [comment]
Hi, @benjjneb ,
I also tried to increase the mismatches to 2, while there is no effect on the merge. Enclosed I attach the two pdf show the detailed output from R. 
[dada2-0mismatch.pdf](https://github.com/benjjneb/dada2/files/3116998/dada2-0mismatch.pdf)
[dada2-2mismathces.pdf](https://github.com/benjjneb/dada2/files/3116999/dada2-2mismathces.pdf)
I also tried DADA2-with R1 only, DADA2-R2 only, DADA2-R1+R2, and traditional OTU method. It seems that the OTU method is the most close to DADA2 with only R1. 
![image](https://user-images.githubusercontent.com/28763565/56740121-4c76d400-673e-11e9-8650-b85e2f2077a6.png)
May I please hear some suggestions from you? 
Sincere thanks.

**Comment by benjjneb** [comment]
The problem with sample L51 is that the forward and reverse sequence files you provided for that sample are identical. The forward fastq file was at some point copied and overwritten on top of the reverse fastq file for that sample (you can confirm this by inspecting the fastq id lines, where `L51_S14_L001_R2_001.fastq` has `1:N:0:14` at the end, where 1 indicates the forward read).

You can also see this as the quality profiles from the F/R reads from that sample are identical.

I'd suggest reviewing the provenance of your files, and any manipulations that may have led to this sort of issue.

**Comment by chloelulu** [comment]
Hi, @benjjneb ,
Thanks. You are right. After checked that, I found there still a large amount of reads can not be merged. May I have more suggestions on how to deal with unmerged reads? I do not think they were not biological sequences since R1 and R1 all match well independently on the database. 
Thanks so much. 
`> head(track)
    input filtered denoisedF denoisedR merged nonchim
L15 11622    10951      9370      9663   4618    4581
L20 15212    14668     12881     13280   6008    5632
L51 13222    12809     11216     11497   6296    5947`

**Comment by benjjneb** [comment]
I'm not sure, but if you want the `maxMismatch` parameter to be effective, you need to relax the default alignment parameters. Something like this may be more effective:

```
foo <- mergePairs(ddF, drpF, ddR, drpR, match=4, mismatch=-5, gap=-5, maxMismatch=2)
```

**Comment by chloelulu** [comment]
Hi, @benjjneb 
I tried. It improved a little bit. But still in a bad situation. 

`input filtered denoisedF denoisedR merged nonchim

L15 11622    10951      9370      9663   5667    5164

L20 15212    14668     12881     13280   8565    7168

L51 13222    12809     11216     11497   7501    6493`

Is there a possibility that DADA2 may over error correct the sequences? Any possible way to check the error rate or some parameters that can show the errors? My raw sequences merged are all 253 bp. And in my former several sequence batches runs, they all merged around 253 bp.
I really appreciate your time.

**Comment by benjjneb** [comment]
If you follow the tutorial there are several places where sanity checks are performed to see if things are progressing as expected.

> How can I achieve more biological reads retained, but not removed. I have the data like this, which is produced from 515F-806R primer. **It is my first time to meet this situation. I have successfully run more than 4 batches of data in DADA2. But this time, failed.**

However I think in your case your best bet is to compare to what you saw in the multiple previous runs that proceeded as expected. At the least, there is a strong suggestion that something unusual is going on with this run in particular, and there are lots of different ways a sequencing run can end up less than ideal.

**Comment by chloelulu** [comment]
Hi @benjjneb,
I see. Thanks for the suggestions along the way. :-)
Hope you a great week!
