### ISSUE TITLE
fastqFilter

### ISSUE THREAD

**Issue by carlopacioni** [benjjneb/dada2#74]
[DAFWA#11.fastq.gz](https://github.com/benjjneb/dada2/files/272027/DAFWA.11.fastq.gz)
In dada2 v1.1.0, fastqFilter doesn't write an empty fastq file (i.e. a file with no sequences) when no reads are retained as it used to do before (v0.99), but it issues a warning:
`Warning message:
In min(qs, na.rm = TRUE) : no non-missing arguments to min; returning Inf`
Is it possible to revert to previous behaviour?

I have attached a file to replicate this problem when using the following code:
`fastqFilter("DAFWA#11.fastq.gz", 
            "DAFWA#11_filtered.fastq.gz", 
            maxN=0, 
            maxEE=3,
            truncQ=2, 
            truncLen=141, 
            compress=TRUE, 
            verbose=TRUE)`

Thanks,
carlo

**Comment by benjjneb** [comment]
I had misremembered, and this new behavior or not writing an empty file when zero sequences make it through the filter was an intentional change, because empty files break downstream import with derepFastq. 

I'm now uncertain about what the best behavior in this edge case is. Thoughts?

**Comment by carlopacioni** [comment]
Hi Ben,
the only thing I can think of is to add a check in derepFastq that would discard empty files before processing them, but it would probably also cause a loss of efficiency, which is undesirable. Besides, the current behaviour makes logical sense and I reckon I should change my approach to programmatically handle the exception when no sequence makes it through the filter rather than you modify either fastqFilter or derepFastq. Feel free to close the issue if you agree.

thanks.

**Comment by benjjneb** [comment]
From Diana Proctor via email:

> If you have very low sequencing depth per sample to begin with (e.g., extraction controls) and all the sequences are of poor quality no sequences may be written to an output file subsequent to the filtration step. If this is the case, you need to use some linux command to do something like I did at the bottom of this note to update filtF/filtR in order for de-replication to proceed as desired (or find some other solution, but this caused a number of my lanes to fail, and took some time for me to figure out)

Re-opening because filtering leading to zero sequence files is a legitimate annoyance that is tripping people up. I'm still not sure what the right behavior is though...

**Comment by carlopacioni** [comment]
Hi Ben,
Sorry if this suggestion arrives late (I have been on leave), but the solution I have found is quite straight forward. I have appended a suffix to the file names that are filtered (say "_filt.fastq.gz"). After filtering, I have read in the file names with `list.files()` and subset them with `sub()`. For people who are not familiar with regular expression in R, they can simply redirect the output from `fastqFilter` to an empty folder and then read the names of the retained files with, e.g.,  `filt_files <- list.files()`. These are then passed to downstream analysis (e.g. `lapply(filt_files, derepFastq)` ). 
I think all you have to do is to add a point to this end in the help file (possibly in both, `?fastqFilter` and `?derepFastq`, to make sure that people don’t miss it).

Hope this is of some help.

Cheers,
Carlo

**Comment by benjjneb** [comment]
The "big data" workflow now implements @carlopacioni suggestion of reading the filtered files back in before proceeding.

There is also an appropriate message shown when all reads are filtered out and no filtered output file is created: 94fbe215242f80fc95b76b04b8229f0064e7ea7c
