### ISSUE TITLE
ITS primers cannot be removed completely

### ISSUE THREAD

**Issue by dreamerfuwei** [benjjneb/dada2#740]
![image](https://user-images.githubusercontent.com/46585709/56598296-d764ab00-6626-11e9-80a3-fe0fb74f7b5e.png)
![image](https://user-images.githubusercontent.com/46585709/56598327-e51a3080-6626-11e9-824c-b4f2fe2655d7.png)
Hi, I cannot trim all the ITS primers with the default settings (see the picture above), I think its maybe because the reads I have, and I have no idea if this problem will do harm to my downstream analysis, many THANKS for helping me!

**Comment by benjjneb** [comment]
I probably wouldn't worry about it too much, you've remove the vast majority of primer sequences (99.9%).

**Comment by dreamerfuwei** [comment]
Many thanks for your help~
