### ISSUE TITLE
assignTaxonomy - running for 16+ hours and counting

### ISSUE THREAD

**Issue by pdcountway** [benjjneb/dada2#741]
Hi - I cannot tell if assignTaxonomy is actually doing anything.  It's been running for 16+ hours and just showing a blinking cursor. I have a collection of 1.5M filtered/non-chimeric sequences and am using the pr2 database as a taxonomic reference.  I launched the command per the tutorial...
taxa <- assignTaxonomy(seqtab.nochim, "~/path_to_my_working_dir/pr2_version_4.11.1_dada2.fasta.gz, multithread=16)
Any ideas for what is going on?
Thanks!

**Comment by benjjneb** [comment]
How much memory do you have?
pr2 is known to require more memory to run efficiently, and if you are running into memory constraints (e.g. 8GB of RAM) then swapping will begin and things can get really slow.

If possible I would highly recommend running this task on a machine with 32GB+ of memory available, and any progress in improving the memory efficienty of our taxonomic assignment will show up here: #239

**Comment by pdcountway** [comment]
Hi Ben,
I launched the job with 32Gb of memory but can dial it up as needed, 64Gb? I'll check out issue #239.
Thanks,
Pete

**Comment by benjjneb** [comment]
I would try it if you can, but also with 1.5M sequences it may just take a while. Remember to turn on multithreading.

**Comment by pdcountway** [comment]
Hi Ben, Just to be really clear...by "turn on multithreading", you mean simply specifying multithread=16 (or whatever). There's not a separate "on" command, right?

**Comment by benjjneb** [comment]
Yep. And I see now that you included `mulitithread=16` in the original command you posted, so disregard that comment of mine!

**Comment by pdcountway** [comment]
I left the original assignTaxonomy process (multithread=16, with 32Gb of memory assigned) running over the weekend and it's still just giving me the blinking cursor.  Is there any way to tell if something is happening - or if it's just stuck in some kind of endless processing loop?

**Comment by benjjneb** [comment]
What kind of machine are you on? If a unix-like you can use the `ps` command to check on the process. On OSX you can use the Activity Monitor. On windows I'm sure there is something similar as well.

Another thinig to consider is to run `assignTaxonomy` on a subset of your data, e.g. the first 50k sequences, and record how long that takes. Then multiply that out to the time expected for the full dataset. That will help set expectations on how long it should take if something doesn't go wrong.

**Comment by pdcountway** [comment]
We just checked and the process is still running (on our linux HPC cluster) but it's reporting that it's using 1600% of the CPU. Does that imply that the process is not multithreading?

**Comment by benjjneb** [comment]
16 + 100% = 1600%. That's what 16 threads running at full CPU capacity looks like.

So the process is still running. It's just taking a while. Possibly it would be faster with more memory to avoid swapping issues, but presumably it will finish eventually.

I'd try the "experiment" I suggested above (do just the first 50k sequences or so) on another node if available to get a sense for what running time should be on the full 1.5M sequence dataset.

**Comment by pdcountway** [comment]
@benjjneb @vaulot @kguay  I restarted my dada2 analysis of 3768 ASVs (from 1.5M sequences) using 32 cores and 64 Gb of RAM with the full pr2 reference database (v. 4.11.1). The assignTaxonomy step finally completed sometime last night in <64 hours. I don't really understand why it takes so long but am glad to be moving on!

**Comment by benjjneb** [comment]
> The assignTaxonomy step finally completed sometime last night in <64 hours. I don't really understand why it takes so long but am glad to be moving on!

Glad it worked! But I don't understand why it took that long either.

Closing this thread as resolved, but linking it again to our main Issue on the computational scaling of the tax assignment methods #239 as something to think about when we finally get back to revisiting those scaling issues.
