### ISSUE TITLE
Transformation introduced infinite values in continuous y-axis

### ISSUE THREAD

**Issue by ArneClaeys** [benjjneb/dada2#742]
With this code:
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, maxN = 0, maxEE = c(2, 2), 
    truncQ = 2, minLen = 50, rm.phix = TRUE, compress = TRUE, multithread = TRUE)  # on windows, set multithread = FALSE
head(out)
Followed by:
errF <- learnErrors(filtFs, nread=1e6, multithread=TRUE, MAX_CONSIST = 10)
I get this error in this code: plotErrors(errF, nominalQ=TRUE)
==> Transformation introduced infinite values in continuous y-axis

**Comment by ArneClaeys** [comment]
With this code:
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, maxN = 0, maxEE = c(2, 2), 
    truncQ = 2, minLen = 50, rm.phix = TRUE, compress = TRUE, multithread = TRUE)  # on windows, set multithread = FALSE
head(out)
Followed by:
errF <- learnErrors(filtFs, nread=1e6, multithread=TRUE, MAX_CONSIST = 10)
I get this error in this code: plotErrors(errF, nominalQ=TRUE)
==> Transformation introduced infinite values in continuous y-axis

**Comment by benjjneb** [comment]
This isn't an error, just a message from the plotting function to let you know that there were some zero values in the data plotted (which turn into infinities on the log-scale). That is completely expected, it results from the fact that not every combination of error type (e.g. A->C) and quality score (e.g. 33) is observed in your data which is normal.

**Comment by frankluo149** [comment]
I got the same question too. It said that: Transformation introduced infinite values in continuous x-axis. But sadly, my graph cannot be a good figure. I don't know how to fix this problem.
![image](https://user-images.githubusercontent.com/119115060/204101629-b41b3716-e177-4b35-9ad4-4b2042ff4209.png)
