### ISSUE TITLE
No selfConsist ouput during learnErrors

### ISSUE THREAD

**Issue by buzuddha** [benjjneb/dada2#743]
I have a dataset with good quality for R1 and R2. I have created a fileset for filtering and trimming and generated using:

`fnFs <- sort(list.files(path, pattern="_R1_001.fastq", full.names = TRUE))`
`fnRs <- sort(list.files(path, pattern="_R2_001.fastq", full.names = TRUE))`
`sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)`
`filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))`
`filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))`
`out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,180),
                     maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, multithread=TRUE)`

So I'm just following the tutorial directions exactly at this point.

`head(out)` gives:
                                                           `reads.in reads.out`
`1-1Neg_S75_L001_R1_001.fastq.gz   163229    144897`
`1-1Pos_S57_L001_R1_001.fastq.gz   204197    176577`
`1-2Neg_S76_L001_R1_001.fastq.gz    86246     75491`
`1-2Pos_S58_L001_R1_001.fastq.gz    53050     45688`
`1-3Neg_S77_L001_R1_001.fastq.gz    64627     57394`
`1-3Pos_S59_L001_R1_001.fastq.gz      452       121`

So there's one bad sample in there, but that's it. Everything else looks pretty good.

When I go to use `learnErrors()` command, I get:

`> errF <- learnErrors(filtFs, multithread = TRUE)`
`108449985 total bases in 442653 reads from 4 samples will be used for learning the error rates.`
`> errR <- learnErrors(filtRs, multithread = TRUE)`
`100009400 total bases in 500047 reads from 5 samples will be used for learning the error rates.`
`Warning messages:`
`1: In UseMethod("depth") :`
` no applicable method for 'depth' applied to an object of class "NULL"`
`2: In UseMethod("depth") :`
  `no applicable method for 'depth' applied to an object of class "NULL"`
`3: In UseMethod("depth") :`
  `no applicable method for 'depth' applied to an object of class "NULL"`
`4: In UseMethod("depth") :`
  `no applicable method for 'depth' applied to an object of class "NULL"`
`> plotErrors(errF, nominalQ=TRUE)`
`Warning messages:`
`1: Transformation introduced infinite values in continuous y-axis `
`2: Transformation introduced infinite values in continuous y-axis`

What happened to the `selfConsist()` steps? Is there anything I'm doing incorrectly? Any help would be much appreciated.

Thanks
[Read1_Quality.pdf](https://github.com/benjjneb/dada2/files/3128640/Read1_Quality.pdf)
[Read2_Quality.pdf](https://github.com/benjjneb/dada2/files/3128641/Read2_Quality.pdf)

**Comment by benjjneb** [comment]
I haven't seen the `no applicable method for 'depth' applied to an object of class "NULL"` warning message before, but it is just a warning not an error.

What does the output of `plotErrors` look like?

**Comment by buzuddha** [comment]
I get:
`> plotErrors(errF, nominalQ=TRUE)`
`Warning messages:`
`1: Transformation introduced infinite values in continuous y-axis `
`2: Transformation introduced infinite values in continuous y-axis `

Thoughts?

**Comment by buzuddha** [comment]
And it doesn't plot anything

**Comment by buzuddha** [comment]
i take it back! it did plot!

**Comment by buzuddha** [comment]
in fact it looks ok! Sorry, newb here!
[plotErrors.pdf](https://github.com/benjjneb/dada2/files/3128712/plotErrors.pdf)

**Comment by buzuddha** [comment]
Thanks for the quick response!
