### ISSUE TITLE
Installing 1.10 problem

### ISSUE THREAD

**Issue by ArneClaeys** [benjjneb/dada2#744]
I'm doing an internship and am very new to programming in general. On my personal laptop I have been able to install the latest version of dada2 (1.10), but I'm trying to do the same on a work desktop, but don't seem to be succeeding. The current version is 1.8. R is 3.5.2. The R version on my laptop is 3.5.1 which seems to be okay for dada2 1.10. I've also tried 3.5.1 on the work desktop but it doesn't seem to be working. I also tried installing through devtools but gives an error: could not find tools necessary to compile a package. Then tried manually from source but get an error: warning in system(cmd): 'make' not found.
Someone know a solution?

**Comment by benjjneb** [comment]
How are you trying to install the package, via Bioconductor and devtools?

Parts of dada2 are written in C/C++ so you need to be able to compile that code to install from source (e.g. via devtools) and Windows does not typically have the R toolchain installed by default.

See the windows Rtools: https://cran.r-project.org/bin/windows/Rtools/

**Comment by ArneClaeys** [comment]
> How are you trying to install the package, via Bioconductor and devtools?
> 
> Parts of dada2 are written in C/C++ so you need to be able to compile that code to install from source (e.g. via devtools) and Windows does not typically have the R toolchain installed by default.
> 
> See the windows Rtools: https://cran.r-project.org/bin/windows/Rtools/

I tried both Bioconductor and devtools, it just seems weird it would work on my laptop and not the desktop (both are windows).
