### ISSUE TITLE
Combining ASVs from technical duplicates BUT as an intersection not union

### ISSUE THREAD

**Issue by andreea-waltmann** [benjjneb/dada2#745]
Hello!

Thank you in advance for any help with this. I have technical duplicates (i.e. two independent 16S amplicons from the same DNA sample) and would like to merge the ASVs to obtain a combined set of ASVs per sample. I want to do this by keeping only the ASVs observed in both technical replicates whilst excluding the ones seen in only one of them. In other words, I'd like to perform an intersection of ASVs by sample id to obtain a new ASVs table. I would also then like this to be reflected in the relative abundances afterwards, since some rads will be excluded during this operation.

I have already denoised my raw fastq sequences and merged the forward and reverse reads of each technical replicate and currently have one ASV table containing data from both duplicates for each of all of my samples in the dataset.

 I don't think the mergeSequenceTables is appropriate here (but maybe I am missing something??). Is there another function and argument I could take advantage of? And if so, should it be used at the denoising step or afterwards on the ASVs table? 

Thanks again!

Andreea

**Comment by benjjneb** [comment]
There isn't currently a standalone function that will do exactly what you are describing, but it should be reasonably straightforward to implement using array/matrix operations and a bit of logic in R.

For example, if I assume that in your common ASV table the first 1:N rows are the sample from the first replicate, and that rows N+1:2*N are the second replicate samples (in exactly the same order) then something like the following will approximate what you are wanting:

```
stintersect <- st[1:N,] + st[(N+1):2N,]
stintersect[st[1:N,]==0 | st[(N+1):2N,]==0] <- 0
```

Although double-checking that works as expected isn't a bad idea!

**Comment by mikemc** [comment]
How will you be analyzing your data afterwards? E.g., in phyloseq? In that case you might also consider treating the full dataset as your output of DADA2 to be saved / version controlled and used as input e.g. to phyloseq, and then doing the merging and filtering in phyloseq. That also makes it easier to check useful statistics like the average overlap between replicates. In any case, it is a good idea to save the output of DADA2 before doing the filtering and merging, in case you want to try a different strategy later on. Also, for some analyses it can be useful to have the replicates unmerged, since this provides extra information about the degree of noise in your experiment; though many analyses may not be able to easily handle them in which case filtering and merging makes sense.

@benjjneb didn't mention this, but I think he would agree that what you did so far is preferable to merging first: Treat the replicates like independent samples while following the DADA2 workflow, and then merge and filter as desired.

**Comment by andreea-waltmann** [comment]
Thanks for all the helpful advice. 
@mikemc -  I was going to continue analysis with QIIME2. But in your opinion would phyloseq be better in terms of replicate concordance analyses?

@benjjneb-  thank you so much for suggesting that function in R, I think it would work nicely. The merging will need to have the samples in the same order for both replicates and achieve the following: 1) it will need to ignore ASVs found in only one replicate and not the other; and 2) it will sum the absolute counts of ASVs seen in both. I think that function achieves 1), but to achieve 2) some extra creativity may be needed. In the past when analyzing replicates with QIIME1, we used a helpful function from @timthirion (see below) on a genus-level biom.table of abs counts + taxonomy to merge replicates. The output was the table with a new variable (sum_count) which is the sum of the absolute counts per OTU per sample ID.

Is there any reason why we couldn't adapt this to be used on an ASV feature table (which by default contains frequencies), provided we can convert it to absolute counts (how would we do that by the way)? Would that be a valid approach?

Thanks again for your inputs! Hope to see this kind of function more readily available, as more of us lab peeps are moving towards using PCR technical replicates.

def main(argv):
    if len(argv) != 3:
        sys.exit("./count_bacteria.py input.csv output.csv")
    input = argv[1]
    output = argv[2]

    summed_rows = {}
    with open(input, mode='r') as infile:
        # Read the whole csv into memory
        reader = csv.reader(infile)

        # Dictionary keys are the first row
        fieldnames = next(reader)

        # Dictionary for summed rows
        for row in reader:
            # Use id in column 7
            _id = row[6]

            # Bacteria counts are in column 9 and later
            # For each remaining count, convert it to an int
            # Use zero if there's no value in the column
            counts = [int(count) if count else 0 for count in row[8:]]

            #
            if _id in summed_rows:
                summed_rows[_id]['Assignedbarcode'] += '+' + row[4]
                old_counts = summed_rows[_id]['bacteria_counts']
                summed_counts = [x + y for x, y in zip(counts, old_counts)]
                summed_rows[_id]['bacteria_counts'] = summed_counts
                summed_rows[_id]['sum_count'] += 1
            else:
                summed_rows[_id] = {
                    '#SampleID': _id,
                    'BarcodeSequence': row[1],
                    'LinkerPrimerSequence': row[2],
                    'Assignedbarcode': row[4],
                    'Description': row[5],
                    'visit': row[7],
                    'bacteria_counts': counts,
                    'sum_count': 0
                }

    # Write the output
    with open(output, mode='w') as outfile:
        writer = csv.writer(outfile)

        # Fix the headers
        del fieldnames[3] # group
        del fieldnames[6] # id
        fieldnames[5] = 'visit'
        fieldnames = fieldnames

        writer.writerow(fieldnames)
        for key, d in summed_rows.items():
            if d['sum_count'] == 0:
                continue

            # Form the row correctly
            row = [
                d['#SampleID'],
                d['BarcodeSequence'],
                d['LinkerPrimerSequence'],
                d['Assignedbarcode'],
                d['Description'],
                d['visit']
            ]
            row.extend(d['bacteria_counts'])
            writer.writerow(row)

if __name__ == "__main__":
    main(sys.argv)

**Comment by benjjneb** [comment]
> The merging will need to have the samples in the same order for both replicates and achieve the following: 1) it will need to ignore ASVs found in only one replicate and not the other; and 2) it will sum the absolute counts of ASVs seen in both. I think that function achieves 1), but to achieve 2) some extra creativity may be needed. In the past when analyzing replicates with QIIME1, we used a helpful function from @timthirion (see below) on a genus-level biom.table of abs counts + taxonomy to merge replicates. The output was the table with a new variable (sum_count) which is the sum of the absolute counts per OTU per sample ID.

I think the function does (1) and (2)? It is summing the absolute counts between the replicates for sure. It does depend as you note on having the samples be in the same order in each replicate though.

**Comment by mikemc** [comment]
> @mikemc - I was going to continue analysis with QIIME2. But in your opinion would phyloseq be better in terms of replicate concordance analyses?

I couldn't say; I only asked to know what the starting point would be and what R packages you are familiar with before hazarding some code to help with the filtering and merging.

**Comment by mikemc** [comment]
I don't think this problem is a good reason on its own to use phyloseq. But I figure I may as well post this code for how you might do it with phyloseq. It assumes you're starting with a phyloseq object `ps` that has the ASV count table with taxa as columns and samples as rows, as you would have if following the DADA2 tutorial. It also assumes that `sample_data(ps)` has a column called `Specimen` that we want to merge by---samples with the same `Specimen` value are considered technical replicates. There is an extra sample variable `Lab` that you can ignore; it is included for this example because there is a bug in phyloseq that requires sample_data(ps) to have at least 2 variables for the `merge_samples` function to work.
```r
library(phyloseq)
library(dplyr) # Loaded for the pipe %>%

ps
#> phyloseq-class experiment-level object
#> otu_table()   OTU Table:         [ 269 taxa and 6 samples ]
#> sample_data() Sample Data:       [ 6 samples by 2 sample variables ]
sample_data(ps)
#>          Specimen Protocol
#> B1_188_1    9_Q_B        Q
#> B1_029     15_W_B        W
#> B1_187      9_Q_B        Q
#> A1_047_1    1_Q_A        Q
#> B1_039_1   15_W_B        W
#> A1_082_1    1_Q_A        Q
otu_table(ps)[, 1:5]
#> OTU Table:          [5 taxa and 6 samples]
#>                      taxa are columns
#>          ASV1 ASV2 ASV3 ASV4 ASV5
#> B1_188_1    0    2    1  408    1
#> B1_029      8    5    1  177    0
#> B1_187      4    6    1  358    1
#> A1_047_1    0    4    6   43    8
#> B1_039_1    5    2    1   92    1
#> A1_082_1    2    4    3   66    4

# Merge the samples that have the same Specimen.
ps.merged <- ps %>%
    merge_samples(group = "Specimen")
# Create a matrix of 0s and 1s indicating whether the taxon count should be
# allowed, or should be set to 0.
ps.merged.ok <- ps %>%
    transform_sample_counts(function (x) (x > 0) * 1) %>%
    merge_samples(group = "Specimen") %>%
    transform_sample_counts(function (x) (x == 2) * 1)
# Multiply the counts by the 0-1 matrix
newotu <- otu_table(ps.merged) * otu_table(ps.merged.ok)
# The otu_table objects get turned into matrices when you multiply them, so we
# need to turn newotu back into an otu_table and update the otu_table of
# ps.merged
otu_table(ps.merged) <- otu_table(newotu, taxa_are_rows = FALSE)
otu_table(ps.merged)[, 1:5]
#> OTU Table:          [5 taxa and 3 samples]
#>                      taxa are columns
#>        ASV1 ASV2 ASV3 ASV4 ASV5
#> 1_Q_A     0    8    9  109   12
#> 15_W_B   13    7    2  269    0
#> 9_Q_B     0    8    2  766    2
```
