### ISSUE TITLE
GTDB and RefSeq+RDP parsed for addSpecies

### ISSUE THREAD

**Issue by antonioggsousa** [benjjneb/dada2#746]
Hi, 

This is not necessarily a issue. Anyway, going to the point...I've parsed the GTDB and RefSeq+RDP (available at: https://zenodo.org/record/2541239#.XMlj3iOZPOQ) for the addSpecies() function. I don't know if these two databases would be interesting for others. If they are I can share both databases and the python code that I've used to parse them with the developers, that can release them in the oficial repositories. 

Cheers, 
António

**Comment by benjjneb** [comment]
I think those databases are very interesting for other people. Anecdotally, I know several reserachers moving towards GTDB recently at least.

The `assignTaxonomy` reference files for GTDP and Refseq+RDP at that Zenodo link you provided have been added to our contributed reference databases list: https://benjjneb.github.io/dada2/training.html

We'd love to add such a link and publicize similar fastas formatted for `assignSpecies`. Our two requirements are that the files are deposited in a doi-able repository such as Zenodo, and that they pass my informal test of successfully running on a test dataset and giving non-crazy results.

**Comment by antonioggsousa** [comment]
Ok! Before adding any of the parsed databases to Zenodo, I would like to explain the python code and the difference between databases versions, how many sequences were lost during the parsing steps and so on. 

For instance, GTDB has a lot of sequences that only contains the accession number of the reference sequences at Species level. Therefore, I considered this as 'unclassified species'. Even after this, I was getting sequences like 'uncultured gammaproteobacteria'. Therefore, I made another version and also exclude assignments/seqs like this. Even after all these work, I still was not confident about the quality of the parsed database, because I found some sequences that were short and with ambiguous nucleotides, e.g., N. So, I created another version where I trimmed all these. 

I think it is good to explain all these before sharing anything. Perhaps before the next week I've finished the tutorial that I'm preparing in my GitHub repository. 

Cheers, 
António

**Comment by antonioggsousa** [comment]
Hi @benjjneb, 
you can find the tutorial explaining how I parsed GTDB and RefSeq-RDP databases for addSpecies function at: https://github.com/antonioggsousa/GTDB-RefSeq-RDP-assign-spp-dada2

I've used the two databases GTDB_dada2_TRIM_CLASS_SPP.fa and RefSeq-RDP_dada2_TRIM_CLASS_SPP.fa (build in the tutorial mentioned before) to upload them to the Zenodo repository at: https://zenodo.org/record/2658728#.XM2aKCOZPOQ

Let me know if you have any question!

BTW, I did you said "Anecdotally, I know several reserachers moving towards GTDB recently at least"?

**Comment by benjjneb** [comment]
Thanks @antonioggsousa this looks great. I did a sanity check on the results and it looks good, we'll add these to our contributed datasets page and make an announcement on twitter.

The sanity check code and results:

```
library(dada2); packageVersion("dada2")
sq <- getSequences("~/Desktop/test/HMP_MOCK.v35_reduced.fasta.gz")
table(dada2:::C_isACGT(sq)) # All TRUE

fnGTDB <- "~/tax/GTDB_dada2_assignment_species.fa.gz"
specGTDB <- assignSpecies(sq, fnGTDB)
cbind(unname(specGTDB), names(sq))
```

>  [1,] "Acinetobacter"  "baumannii"    "A.baumannii.1"    
>  [2,] "Actinomyces"    "B"            "A.odontolyticus.1"
>  [3,] "Bacillus"       "A"            "B.cereus.1"       
>  [4,] NA               NA             "B.vulgatus.1"     
>  [5,] "Clostridium"    "beijerinckii" "C.beijerinckii.1" 
>  [6,] NA               NA             "D.radiodurans.1"  
>  [7,] "Enterococcus"   "faecalis"     "E.faecalis.1"     
>  [8,] NA               NA             "E.coli.1"         
>  [9,] "Helicobacter"   "pylori"       "H.pylori.1"       
> [10,] "Lactobacillus"  "gasseri"      "L.gasseri.1"      
> [11,] "Listeria"       NA             "L.monocytogenes.1"
> [12,] "Neisseria"      "meningitidis" "N.meningitidis.1" 
> [13,] NA               NA             "P.acnes.1"        
> [14,] "Pseudomonas"    "aeruginosa"   "P.aeruginosa.1"   
> [15,] "Porphyromonas"  "gingivalis"   "P.gingivalis.1"   
> [16,] "Rhodobacter"    "A"            "R.sphaeroides.1"  
> [17,] NA               NA             "S.aureus.1"       
> [18,] "Staphylococcus" NA             "S.epidermidis.1"  
> [19,] "Streptococcus"  "agalactiae"   "S.agalactiae.1"   
> [20,] "Streptococcus"  "mutans"       "S.mutans.1"       
> [21,] "Streptococcus"  "pneumoniae"   "S.pneumoniae.1"   

```
fnRefRDP <- "~/tax/RefSeq-RDP_dada2_assignment_species.fa.gz"
specRefRDP <- assignSpecies(sq, fnRefRDP)
cbind(unname(specRefRDP), names(sq))
```

>  [1,] "Acinetobacter"        "baumannii"    "A.baumannii.1"    
>  [2,] NA                     NA             "A.odontolyticus.1"
>  [3,] NA                     NA             "B.cereus.1"       
>  [4,] NA                     NA             "B.vulgatus.1"     
>  [5,] NA                     NA             "C.beijerinckii.1" 
>  [6,] NA                     NA             "D.radiodurans.1"  
>  [7,] "Enterococcus"         "faecalis"     "E.faecalis.1"     
>  [8,] "Escherichia/Shigella" NA             "E.coli.1"         
>  [9,] "Helicobacter"         "pylori"       "H.pylori.1"       
> [10,] "Lactobacillus"        "gasseri"      "L.gasseri.1"      
> [11,] "Listeria"             NA             "L.monocytogenes.1"
> [12,] "Neisseria"            "meningitidis" "N.meningitidis.1" 
> [13,] "Propionibacterium"    "acnes"        "P.acnes.1"        
> [14,] "Pseudomonas"          "aeruginosa"   "P.aeruginosa.1"   
> [15,] "Porphyromonas"        "gingivalis"   "P.gingivalis.1"   
> [16,] "Rhodobacter"          NA             "R.sphaeroides.1"  
> [17,] "Staphylococcus"       NA             "S.aureus.1"       
> [18,] "Staphylococcus"       NA             "S.epidermidis.1"  
> [19,] "Streptococcus"        "agalactiae"   "S.agalactiae.1"   
> [20,] "Streptococcus"        "mutans"       "S.mutans.1"       
> [21,] "Streptococcus"        "pneumoniae"   "S.pneumoniae.1"   

> BTW, why did you said "Anecdotally, I know several reserachers moving towards GTDB recently at least"?

Just thinking aloud about how I think this will be used by people!

[HMP_MOCK.v35_reduced.fasta.gz](https://github.com/benjjneb/dada2/files/3145618/HMP_MOCK.v35_reduced.fasta.gz)

**Comment by benjjneb** [comment]
Thanks again for your help here!
