### ISSUE TITLE
"Invalid derep$uniques vector. Must be integer valued." when running "dada()"

### ISSUE THREAD

**Issue by montoyah** [benjjneb/dada2#75]
Hi Ben,

I get the following error when running the dada() function on a MiSeq paired-end sample (only one sample):
"Error in dada(derepFs, err = inflateErr(tperr1, 3), selfConsist = TRUE) : 
  Invalid derep$uniques vector. Must be integer valued."

I apologize if I'm missing something very basic, but I just can't figure it out. 
This is the output of derepFs and derepRs

derepFs <- derepFastq(filtFs, verbose=TRUE)
Dereplicating sequence entries in Fastq file: /home/oscar/Desktop/sandra/raw_paired_end_fastq/Well49_F_filt.fastq.gz
Encountered 24770 unique sequences from 39714 total sequences read.
derep-class: R object describing dereplicated sequencing reads
$uniques: 39714 reads in 24770 unique sequences
  Sequence lengths: min=240, median=240, max=240
$quals: Quality matrix dimension:  24770 240
  Consensus quality scores: min=7, median=36, max=38
$map: Map from reads to unique sequences:  15742 5983 6652 15220 19162 ...

derepRs <- derepFastq(filtRs, verbose=TRUE)
Dereplicating sequence entries in Fastq file: /home/oscar/Desktop/sandra/raw_paired_end_fastq/Well49_R_filt.fastq.gz
Encountered 22862 unique sequences from 39714 total sequences read.
derep-class: R object describing dereplicated sequencing reads
$uniques: 39714 reads in 22862 unique sequences
  Sequence lengths: min=190, median=190, max=190
$quals: Quality matrix dimension:  22862 190
  Consensus quality scores: min=7, median=36, max=38
$map: Map from reads to unique sequences:  13323 8983 8717 22834 6572 ...

and these are my filtering/trimming parameters:

for(i in seq_along(fnFs)) {
  fastqPairedFilter(c(fnFs[i], fnRs[i]), c(filtFs[i], filtRs[i]),
                    trimLeft=c(10, 10),truncLen=c(250,200), 
                    maxN=0, maxEE=4, truncQ=2, 
                    compress=TRUE, verbose=TRUE)
}

Thanks in advance for any help.

Oscar.

**Comment by benjjneb** [comment]
What do you get from the following commands?

```
length(fnFs)
length(derepFs)
length(derepRs)
min(sapply(derepFs, length))
```

**Comment by montoyah** [comment]
> length(fnFs)
[1] 1
> length(derepFs)
[1] 3
> length(derepRs)
[1] 3
> min(sapply(derepFs, length))
[1] 24770

**Comment by benjjneb** [comment]
Oh.

derepFs is just a single derep-class object, not a list of such objects. Don't loop over it, just call dada on that object (rename to derepF to be less confusing maybe when its just one derep):

```
derepF <- derepFs # cosmetic renaming
dada(derepF, err=NULL, selfConsist=TRUE)
```

**Comment by montoyah** [comment]
Got it. Thanks for your time, Ben.

**Comment by josemseoane** [comment]
Hi Ben,

Please excuse for reopening this question again but I have encountered exactly the same issue when running a single sample and I am a little bit confused. I have removed the loop on the filtering but I still get 

length(fnFs)
[1] 1
> length(derepFs)
[1] 3
> length(derepRs)
[1] 3
> min(sapply(derepFs, length))
[1] 28246

Thank you very much in advance for any help!

**Comment by benjjneb** [comment]
I think your problem is probably answered in #119

We are working on a better implementation to avoid this issue, but for now just don't name your derep-class/dada-class objects when running a single sample.

**Comment by josemseoane** [comment]
perfect, again thanks a lot!
