### ISSUE TITLE
writing and transforming output files?

### ISSUE THREAD

**Issue by pdcountway** [benjjneb/dada2#754]
Hi - I'm a longtime user of mothur and accustomed to the automatic generation of output files from each step in the pipeline.  I'd like to be able to generate a fasta file with the sequences from the seqtab.nochim file and I'd also like to be able to transpose these data into samples(X) vs. ASVs(Y) for the same file.  I can write.csv in R to capture the output files but that isn't a particularly useful format for downstream application. A couple people have suggested that I should be using dada2 in QIIME2 but it seems like a user should be able to perform everything they need to do in R.
Thanks for any suggestions!

**Comment by benjjneb** [comment]
You can create an output file in any format you can imagine using R, but you may need a little bit of know-how to get there. Can you be more precise on the output format you want?

Two possibly useful options are the convenience functions in the dada2 package: `dada2:::seqtab_to_mothur` and `dada2:::seqtab_to_qiime`. Both functions accept a sequence table and a filename, and output the sequence table in the mothur shared file format, or the qiime1 flat text otu table format. E.g.

```
dada2:::seqtab_to_mothur(seqtab.nochim, "path/to/myseqtab.shared")
```

> I'd also like to be able to transpose these data into samples(X) vs. ASVs(Y) for the same file

Not totally sure what you mean here, but you can always transpose a sequence table with the `t` funciton, i.e. flip the rows/columns: `st.trans <- t(st)`

**Comment by pdcountway** [comment]
Hi Ben,

To clarify, I'd like to generate a standard fasta text file for all of the ASVs from the seqtab.nochim file, without all of the sequence count data. E.g., 
>ASV00001
ACGTACGTACGT.....etc
>ASV00002
ACGTACGTACGT.....etc

Regarding transposing the sequence table, the 't' function sounds like it's exactly what I was looking for, so that ASVs can populate the row names, and Samples can populate the column headers.

Thanks

**Comment by pdcountway** [comment]
Thanks for the tips Ben!

**Comment by pdcountway** [comment]
Thanks for the tips Ben!
