### ISSUE TITLE
Access to merged paired read files

### ISSUE THREAD

**Issue by cmaggior** [benjjneb/dada2#756]
Hello,

I'm wondering if it's possible to access the merged paired read files generated from the "mergers" command, prior to running the "seqtab <- makeSequenceTable(mergers)" command to get the ASV table. I have tried making a file.path in the mergers command with no luck.

Conversely, if this is not possible, can you recommend a method for combining a low quality dataset with a high quality dataset in such a way that the high quality dataset isn't affected by the low quality parameters (larger truncLen, etc)?

Cheers!

**Comment by benjjneb** [comment]
> I'm wondering if it's possible to access the merged paired read files generated from the "mergers" command, prior to running the "seqtab <- makeSequenceTable(mergers)" command to get the ASV table.

Certainly. If you want that data as a fasta file, you can use the `uniquesToFasta` function. If dealing with multiple samples, it would look something like:

```
for(i in seq_along(mergers)) {
    uniquesToFasta(mergers[[i]], file.path(outpath, paste0(names(mergers)[[i]], ".fa")))
}
```

That will write out a fasta file for each merged sample, with the file name corresponding to the name of that sample in the `mergers` list.

**Comment by benjjneb** [comment]
> can you recommend a method for combining a low quality dataset with a high quality dataset in such a way that the high quality dataset isn't affected by the low quality parameters (larger truncLen, etc)?

Not 100% sure what you mean here. Are you trying to combine different datasets? Then is `mergeSequenceTables` what you are looking for? Or is the issue much lower quality in the reverse reads?

**Comment by cmaggior** [comment]
> > can you recommend a method for combining a low quality dataset with a high quality dataset in such a way that the high quality dataset isn't affected by the low quality parameters (larger truncLen, etc)?
> 
> Not 100% sure what you mean here. Are you trying to combine different datasets? Then is `mergeSequenceTables` what you are looking for? Or is the issue much lower quality in the reverse reads?

Not the reverse reads, a separate sequencing run from the same samples. I see the instructions here for combining big data (https://benjjneb.github.io/dada2/bigdata_paired.html) but am wondering if there's a way to combine the data with different maxEE and maxN values for the different datasets.

**Comment by benjjneb** [comment]
> am wondering if there's a way to combine the data with different maxEE and maxN values for the different datasets

Sure, those different `maxEE` and `maxN` parameters aren't really a problem. What is critical is that you sequenced the same amplicon, and trimmed down to the same region. Most importantly then (assuming you used the same primers) is that you use the same `trimLeft` on each dataset, the other filtering parameter can vary and not affect merge-ability.

**Comment by cmaggior** [comment]
Great! If I want to merge final ASV tables (taxonomy and count tables) from multiple runs after putting each run through the dada2 workflow, how would you recommend I got about doing so?

**Comment by benjjneb** [comment]
If you used the same primer set for each study, and the same `trimLeft` parameters, then you can do it very easily with the `mergeSequenceTables` function. That won't merge the taxonomy tables, but you could just rerun `assignTaxonomy` on the merged table.
