### ISSUE TITLE
Learnerrors difference 1.6 vs 1.10

### ISSUE THREAD

**Issue by ArneClaeys** [benjjneb/dada2#757]
I'm using both the 1.6 version on a server (will be updated in a few months) and locally version 1.10. I've already noticed the use of nbases instead of nreads in learnErrors. But I'm wondering, on the server with 1.6 when doing learnErrors it takes a very long time and it showed the amount of rounds before convergence. With the 1.10 version locally it's a lot faster, like seriously a lot. It also doesn't show the rounds. Should I be concerned that something is going wrong? Or is this normal?

**Comment by benjjneb** [comment]
It's probably normal. For longer Illumina reads (e.g. 250 or 300 nts) the new `nbases` default will use less data than the old `nreads` default, and hence will be faster.

But the way to check if things are looking normal is to look at the output of `plotErrors`.
