### ISSUE TITLE
Loss of a lot of data for fungi

### ISSUE THREAD

**Issue by ArneClaeys** [benjjneb/dada2#758]
I'm using DADA2 to process some fungi sequencing data. 
This is my code for the filtering step:
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, maxN = 0, maxEE = c(3,5), 
    truncQ = 2, minLen = 50, rm.phix = TRUE, compress = TRUE, multithread = TRUE)
I lose about 50% of my sequences, which is a lot and I'm wondering if it's something I did wrong in my code or if fungi data isn't processed well in DADA2.

**Comment by benjjneb** [comment]
If you are following the tutorial more or less, could you post the results of the `head(track)` command that shows the reads retained at each step?

50% retained reads through the total pipeline is probably fine, but a big drop at certain steps could indicate a problem.

**Comment by ArneClaeys** [comment]
> If you are following the tutorial more or less, could you post the results of the `head(track)` command that shows the reads retained at each step?
> 
> 50% retained reads through the total pipeline is probably fine, but a big drop at certain steps could indicate a problem.

I lose already 50% on average after just the filtering. Then I lose about 10% more after the other steps.

**Comment by benjjneb** [comment]
> I lose already 50% on average after just the filtering. Then I lose about 10% more after the other steps.

OK. that is totally fine then and no cause for concern. A sizable drop at the filtering step is OK, it just reflects that there is a decent amount of low quality sequence in your data.

**Comment by ArneClaeys** [comment]
> > I lose already 50% on average after just the filtering. Then I lose about 10% more after the other steps.
> 
> OK. that is totally fine then and no cause for concern. A sizable drop at the filtering step is OK, it just reflects that there is a decent amount of low quality sequence in your data.

Alright, thank you.
