### ISSUE TITLE
High memory usage and slow running speed in taxonomy

### ISSUE THREAD

**Issue by dreamerfuwei** [benjjneb/dada2#760]
Hi, Ben,

I have been running DADA2 using my Windows computer for a while, the memory usage is kept low in almost all steps, but whenever I run into the taxonomy step, the memory usage is climbing up to 90% more and it will take about 2 h to complete the step, I think this is a bug. I using the latest version of R in Rstudio, my computer have 24 GB of memory, the table have 5 K unique ITS sequences.
![Sketch](https://user-images.githubusercontent.com/46585709/57621806-f8357600-75be-11e9-942b-fdb588b3782b.png)

Regards,
Wei Fu

**Comment by benjjneb** [comment]
Thanks for the report. 
What version of the dada2 package are you using, i.e. `packageVersion("dada2")`
And can you provide the exact command you are running that causes this behavior?

**Comment by dreamerfuwei** [comment]
Hi, my dada2 version is 1.10.1

Command:
## Assign taxonomy with UNITE database
unite.ref <- "D:/EDH2017/sh_general_release_dynamic_s_all_02.02.2019.fasta"  
taxa <- assignTaxonomy(seqtab.nochim, unite.ref, multithread = TRUE, tryRC = TRUE)

I use the All eukaryotes release (88.9 MB) of the UNITE database, which is larger than the database in the tutorial (39.3 MB).

**Comment by benjjneb** [comment]
OK I'm linking this thread to the main one on the memory scaling issues with `assignTaxonomy`, especially as database sizes get beyond UNITE/Silva sizes: #239 

Progress will show up first there, and I think we're getting to a sufficient number of reports to finally dig into it for this next release.
