### ISSUE TITLE
Cannot reproduce Cutadapt/DADA2 ITS Pipeline 

### ISSUE THREAD

**Issue by Debora6991** [benjjneb/dada2#762]
Hi, 
I have reproduced the cutadapt part of the DADA2 workflow for ITS, to remove primers,  but at the very end this happens

![Immagine 1](https://user-images.githubusercontent.com/50614431/57680180-4ed99900-762d-11e9-8889-595362967798.png)

I've tryed to change paths but nothing changed.
What do you thing the problem is?

**Comment by benjjneb** [comment]
My error indicates that the filenames you've provided don't exist. Do they?

`file.exists(fnFs.cut[[1]])`?

What do you see in the `ITS/cutadapt` when you inspect that directory in the file system?

**Comment by Debora6991** [comment]
it seems to exist according to the "file path" (as it is in the screenshot), but no file was in the folder.

**Comment by Debora6991** [comment]
![Immagine 2](https://user-images.githubusercontent.com/50614431/57702239-f078de80-765d-11e9-81c2-ba93d7e477d1.png)

**Comment by benjjneb** [comment]
The file doesn't exist which suggests that the cutadapt command did not successfully process your files. Are you able successfully to call cutadapt from your R session? What is the output from: `system2(cutadapt, args== "--version")`?

**Comment by Debora6991** [comment]
![image](https://user-images.githubusercontent.com/50614431/57754602-1dc19d00-76ef-11e9-9a10-28eb692076af.png)
this is the output. It just seems to execute the command, with no warning message.

**Comment by benjjneb** [comment]
Your assignment to `cutadapt <-` isn't right. You need to give it the path to the cutadapt command, i.e it should look something like this: `cutadapt <- "path/on/my/machine/cutadapt"`.

Right now you've given it a path to a directory, not the command itself, hence the cutadapt command is never being called.

**Comment by Debora6991** [comment]
[image: image.png]

I changed the path to the right one, but it is not working yet.
I believe it is still a problem of communication between R and cutadapt.
May it be a "Windows" related problem?



Il giorno mer 15 mag 2019 alle ore 20:20 Benjamin Callahan <
notifications@github.com> ha scritto:

**Comment by benjjneb** [comment]
> I believe it is still a problem of communication between R and cutadapt.
> May it be a "Windows" related problem?

It is possible. It certainly should be able to work on Windows but I don't use Windows so I can't really say for sure. The marker for success here would be getting the expected output from the original cutadapt version invocation, i.e. 

```
> cutadapt <- "/Users/bcallah/miniconda3/bin/cutadapt"
> system2(cutadapt, args="--version")
```
> 1.15

Doesn't have to be 1.15, but you should be seeing the version of your cutadapt output there. If not, there is something going wrong in trying to call cutadapt from R. A workaround would be to just work with cutadapt on the command line directly.
