### ISSUE TITLE
extract sequence data?

### ISSUE THREAD

**Issue by rachaelantwis** [benjjneb/dada2#763]
Hi Ben,

I am getting a lot of mitochondrial and chloroplast reads in my data, so I'd like to design a blocking primer. Is there a way to extract the sequence data from these reads in dada2 so I can see if I can figure out a suitable region to use as a blocker? (Or do you know a better way of figuring this out?).

Many thanks

**Comment by benjjneb** [comment]
>Is there a way to extract the sequence data from these reads in dada2

DADA2 is using the sequence as the name of each ASV, so you can just access the sequences directly. The `getSequences` function can be convenient for that purpose as it handles almost any dada2-created object. For example,

```
getSequences(obj)[1:5]
```

will get you the first 5 sequences from a fasta file, a dada-class object, a sequence table or other (see `?getSequences` for more info).

**Comment by rachaelantwis** [comment]
Thanks Ben. I'm getting an error message though, as follows:


> mito <- subset_taxa(final.data.reduced, Family == "Mitochondria")
> mito

phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 11 taxa and 155 samples ]
sample_data() Sample Data:       [ 155 samples by 9 sample variables ]
tax_table()   Taxonomy Table:    [ 11 taxa by 6 taxonomic ranks ]

> getSequences(mito)[1:11]
Error in getUniques(object, collapse = collapse, silence = silence) : 
  Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.
> getSequences(mito)
Error in getUniques(object, collapse = collapse, silence = silence) : 
  Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.

The example mentions making a dereplicated object. Do you know how to do this?

Many thanks

**Comment by benjjneb** [comment]
Oh you are using phyloseq rather than dada2 here. Did you store the sequence information in the phyloseq obejct? What is the output of `head(taxa_names(mito))`?

**Comment by rachaelantwis** [comment]
Ah ok, how can I used getSequences in dada2? Unload the phyloseq package?

The output is:
> head(taxa_names(mito))

[1] "SV 158" "SV 173" "SV 238" "SV 327" "SV 373" "SV 390"

**Comment by benjjneb** [comment]
At some point you renamed your ASVs with those "SV XXX" labels, and now no longer have the sequence information in the phyloseq object. You'll need to go back to the original data before that happened to extract the sequences.

**Comment by rachaelantwis** [comment]
Ah ok, I see. For the next person (where tt is the object you assignTaxonomy to):

> sequences <- tax_table(tt)
> write.csv(sequences, file='sequences.csv')

**Comment by rachaelantwis** [comment]
Sorry, one more question - is it possible to search these sequences for alignment with a reference sequence? My pathogen of interest is not in UNITE so it's not showing up in the taxonomy. I have sequenced a pure culture of the pathogen, so I have the correct sequence for this primer pair, but I need to check if any of my SV sequences match/are similar to this. Currently attempting an individual BLAST approach but do you know if there is something quicker and/or R based?
Many thanks

**Comment by benjjneb** [comment]
Are you trying to align against the full genome of the pathogen? In that case BLAST or other alternatives like BWA or bowtie2 would make sense. In R you could take a look at the `pairwiseAlignment` function in the `Biostrings` package, using `type="local"` for this case.

Otherwise if you are aligning against your target gene or genetic locus, you can use various options in R, including `nwalign` or `nwhamming` in dada2, or `pairwiseAlignment(..., type="global")` in Biostrings.

**Comment by rachaelantwis** [comment]
Thanks very much

**Comment by shreyaskumbhare** [comment]
Hi, @benjjneb I am using a phyloseq object to extract the sequences and reconstruct a phylo tree. From the above thread, I got to know that I can't use the getSequences function as it is for the sequence table in DADA2. However, I am trying to use the refseq function to extract the sequences from the phyloseq object for alignment, I am receiving the following error:

Error in access(physeq, "refseq", errorIfNULL) : refseq slot is empty. 

My Phyloseq object still contains the sequence information (confirmed using the head(taxa_names) ). Is there a way I can deal with this?

**Comment by benjjneb** [comment]
@shreyaskumbhare If you have your sequence info as the `taxa_names` you can just use that function to extract the sequences. The `refseq` slot is an alternative way to store the sequence information.
