### ISSUE TITLE
question on error model

### ISSUE THREAD

**Issue by aistBMRG** [benjjneb/dada2#765]
Hi,

I have a 16S-seq run with multiple primer sets, each targeting different regions of the 16S rRNA gene and with some primer sets only having a few samples on this run. Now, I was wondering if it would be a valid approach to use the primer set with most samples (and reads) to learn the error model and then apply that model to denoise reads from primers sets with only few samples? Seems to me that based on the assumptions that errors are independent that should be valid -- would it be possible to clarify? 

Regards,

Dieter.

**Comment by benjjneb** [comment]
That is probably OK, _if_ you used the same PCR conditions for each primer set. In that case, the expectation of a consistent error model across PCR primer sets should hold up reasonably well.

If you used different PCR primer conditions for different primer sets, then I'd recommend learning the error model for each independently. More samples is good, but error model learning is usually pretty decent even on just a few samples.
