### ISSUE TITLE
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : object 'finalize_filexp' not found

### ISSUE THREAD

**Issue by ArneClaeys** [benjjneb/dada2#766]
I get this error doing the following command:

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, maxN = 0, truncLen=c(263,225), maxEE = c(2,2), 
    truncQ = 2, minLen = 50, rm.phix = TRUE, compress = TRUE, multithread = TRUE)
head(out)

I changed nothing to it and it worked before with no problems. Version is 1.10.1

**Comment by benjjneb** [comment]
Can you try "turning it off and then on again", aka restarting R?
These kind of environment errors are often fixed that way.

**Comment by ArneClaeys** [comment]
> Can you try "turning it off and then on again", aka restarting R?
> These kind of environment errors are often fixed that way.

Still getting the error.

**Comment by benjjneb** [comment]
See https://github.com/benjjneb/dada2/issues/720

The solution that worked there was reinstalling Rstudio.

**Comment by ArneClaeys** [comment]
> See #720
> 
> The solution that worked there was reinstalling Rstudio.

Reinstalled R, still the same error.

**Comment by ArneClaeys** [comment]
This is the error in more detail:

Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : object 'finalize_filexp' not found
18.
get(name, envir = asNamespace(pkg), inherits = FALSE)
17.
XVector:::finalize_filexp
16.
.finalize_filexp_list(filexp_list)
15.
fasta.index(filepath, nrec = nrec, skip = skip, seek.first.rec = seek.first.rec, seqtype = seqtype)
14.
.read_XStringSet(filepath, format, nrec, skip, seek.first.rec, use.names, "DNA", with.qualities)
13.
FUN(X[[i]], ...)
12.
lapply(src, readDNAStringSet, nrec = nrec, skip = skip)
11.
lapply(src, readDNAStringSet, nrec = nrec, skip = skip)
10.
readFasta(system.file("extdata", "phix_genome.fa", package = "dada2"))
9.
readFasta(system.file("extdata", "phix_genome.fa", package = "dada2"))
8.
sread(readFasta(system.file("extdata", "phix_genome.fa", package = "dada2")))
7.
.class1(object)
6.
as(sread(readFasta(system.file("extdata", "phix_genome.fa", package = "dada2"))), "character")
5.
isPhiX(as(sread(fqF), "character"), ...)
4.
(function (fn, fout, maxN = c(0, 0), truncQ = c(2, 2), truncLen = c(0, 0), maxLen = c(Inf, Inf), minLen = c(20, 20), trimLeft = c(0, 0), trimRight = c(0, 0), minQ = c(0, 0), maxEE = c(Inf, Inf), rm.phix = c(TRUE, TRUE), matchIDs = FALSE, orient.fwd = NULL, ...
3.
mapply(FUN = FUN, ..., MoreArgs = MoreArgs, SIMPLIFY = SIMPLIFY, USE.NAMES = USE.NAMES)
2.
mcmapply(fastqPairedFilter, mapply(c, fwd, rev, SIMPLIFY = FALSE), mapply(c, filt, filt.rev, SIMPLIFY = FALSE), MoreArgs = list(truncQ = truncQ, truncLen = truncLen, trimLeft = trimLeft, trimRight = trimRight, maxLen = maxLen, minLen = minLen, maxN = maxN, minQ = minQ, ...
1.
filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen = c(263, 225), maxN = 0, maxEE = c(3, 3), truncQ = 2, rm.phix = TRUE, compress = TRUE, multithread = TRUE)

**Comment by benjjneb** [comment]
> Reinstalled R, still the same error.

Did you reinstall Rstudio (not R)? That is the solution that worked before, and seemingly for other people using other random packages when I google the error message.

**Comment by ArneClaeys** [comment]
> > Reinstalled R, still the same error.
> 
> Did you reinstall Rstudio (not R)? That is the solution that worked before, and seemingly for other people using other random packages when I google the error message.

I reinstalled RStudio.

**Comment by benjjneb** [comment]
I don't know then. It's an error stemming from a different package (ShortRead/Biostrings) that dada2 is calling a function from. You could try reinstalling those packages. Or you could try to workaround it by turning off the phiX filtering, `filterAndTrim(..., rm.phix=TRUE)`.

**Comment by ArneClaeys** [comment]
Reinstalling the biostrings package solved the problem.
