### ISSUE TITLE
On ASVs in diet studies

### ISSUE THREAD

**Issue by Melirax** [benjjneb/dada2#770]
Hi, 

My question is not directly to the use of DADA2 but more to the interpretation of results.
I am using DADA2 to process sequences obtained from predator (spiders) gut contents (invertebrate preys).
In some cases, for the same spider, I get several ASVs corresponding to the same prey species. I was wondering if there is a way to determine if 2 ASVs corresponding to the same prey species (in the gut of the same spider) correspond to two different individuals?

Thank you

**Comment by benjjneb** [comment]
This depends on the biology of the marker-gene you are using. Could there be variation in that gene within an individual? If not, then those multiple ASVs probably represent different individuals.

But if so, then interpretation should be a bit more careful. I would suggest mapping the different same-species ASVs from a couple of example spiders against references (e.g. by BLAST) and getting some guidance from that. Do those ASVs hit different genomes? Do they have multiple matches in the genomes they hit?

**Comment by Melirax** [comment]
I am using a 403bp sector of the Folmer region (COI). Is there a built in function in dada2 to get distance between ASVs? I did not see one in the manual...

Best

**Comment by benjjneb** [comment]
> Is there a built in function in dada2 to get distance between ASVs?

`nwhamming`

**Comment by Melirax** [comment]
Great! Thank you.

Le jeu. 23 mai 2019 à 13:38, Benjamin Callahan <notifications@github.com> a
écrit :
