### ISSUE TITLE
ITS pipeline for forward reads only

### ISSUE THREAD

**Issue by R3bk** [benjjneb/dada2#771]
Hi!

I am analyzing only forward reads due to poor quality of reverse reads. How do I skip the mergePairs step and continue to the makeSequenceTable step without merging the pairs? 

Thanks!

**Comment by benjjneb** [comment]
Just skip it, then create the seuqence table out of the forward dada objects, i.e. `makeSequenceTable(dadaFs)`

**Comment by R3bk** [comment]
Okay, thank you very much for the quick answer!
