### ISSUE TITLE
Merge pairs number of mismatches

### ISSUE THREAD

**Issue by sgavril** [benjjneb/dada2#772]
Hello,

Forgive me if this is the wrong area to post this, but I'm not sure where to ask. The default value for the maximum number of mismatches in the overlap region using the mergePairs function is 0. I was wondering how DADA2 handles a non-zero maximum number of mismatches. Does it simply take the base with the higher quality score versus the other? How would this handle cases where the quality scores are the same?

Thank you for taking the time to read this.

**Comment by benjjneb** [comment]
>  I was wondering how DADA2 handles a non-zero maximum number of mismatches.

Those pairs of reads are discarded (by default). 

This is because in the DIADA2 pipeline, merging is done after correcting errors, rather than on the raw reads as is typical in other pipelines.

**Comment by sgavril** [comment]
Thank you for the answer. Just as an aside, if I set the maximum number of mismatches to say 1 and the paired reads have 1 mismatch between them, what happens in that scenario?

**Comment by benjjneb** [comment]
The read will be merged, and the base from the forward or reverse read that was supported by the larger number of raw reads will be chosen as the correct base.

**Comment by sgavril** [comment]
I see now, thanks again.

**Comment by ClementineFrancois** [comment]
Hello,

Sorry to reopen this thread, I am also considering to set the maximum number of mismatches to 1, but I am not sure to understand how it's handled by dada2.
According to your answer, I get that, at the mismatch position (eg position 231 in R1), the base with the highest proportion at position 231 in all R1 reads of the dataset will be chosen ?
I may have missed something, but I don't understand the rationale behind this choice, as the most common base at this position for the whole dataset is not supposed to be the 'right' base for this sequence ? 
Does it mean that the quality score is not considered for resolving a mismatch ? 

Thanks very much for your help !
Best
Clémentine Francois

**Comment by benjjneb** [comment]
> the base with the highest proportion at position 231 in all R1 reads of the dataset will be chosen ?

Not the whole datasets, just the reads that are being potentially merged in this pair.

> Does it mean that the quality score is not considered for resolving a mismatch ?

No it is not. Every read contributing to the pair of ASVs proposed to be merged gets equal voting weight.

**Comment by ClementineFrancois** [comment]
Thank very much for the answer, and sorry for the late reply. 
Just to be sure that I understand correctly your explanation : say that a given R1 read is to be merged with its corresponding R2, and there is a mismatch at position N. Then for all R1 reads belonging to the partition of this R1 read, and for all R2 reads belonging to the partition of its R2 corresponding read, the bases at position N are counted and the most abundant is chosen to resolve the mismatch ? 
Is that correct ? 

Thanks again !

**Comment by benjjneb** [comment]
Yes that is what I said, but I just checked the code and it's not quite right. The "winner" at the mismatch position that decides the nucleotide output by `mergePairs` is that which has the most error-free representatives in the data. So if the given R1 ASV had 7 error-free reads supporting it (out of 10 total), and the associated R2 ASV that is being merged had 5 error-free reads supporting it (out of 10 total), then the base in the R1 read would "win" and be output by `mergePairs`.

**Comment by ClementineFrancois** [comment]
Ok, thanks for this explanation ! 
Best
