### ISSUE TITLE
question regarding input and output fastq phred scores

### ISSUE THREAD

**Issue by bernt-matthias** [benjjneb/dada2#773]
Just want to be sure: 

- I understand that dada2 decides on the input phred encoding using the shortreads package. 
- What is the phred encoding of the output (in case of filterAndTrim)? Is it the same as the input or always a specific one?

**Comment by benjjneb** [comment]
> I understand that dada2 decides on the input phred encoding using the shortreads package.

Yes, although you can now manually specify the encoding as well due to a contribution by @brendanf . See the `qualityType` argument.

> What is the phred encoding of the output (in case of filterAndTrim)? Is it the same as the input or always a specific one?

Good question... I'm 95% that it will be the same as the input, as the code is reading in a ShortReadQ object and outputting that same object, which should maintain the encoding. However, I've never tested it.

**Comment by bernt-matthias** [comment]
Thanks for the answer.

> > I understand that dada2 decides on the input phred encoding using the shortreads package.
> 
> Yes, although you can now manually specify the encoding as well due to a contribution by @brendanf . See the `qualityType` argument.

I guess this applies for the latest release (I'm using 1.10.0).

> > What is the phred encoding of the output (in case of filterAndTrim)? Is it the same as the input or always a specific one?
> 
> Good question... I'm 95% that it will be the same as the input, as the code is reading in a ShortReadQ object and outputting a filtered version of that same object, which should maintain the encoding. However, I've never tested it.

Then I will go for the 95% :)
