### ISSUE TITLE
combining the seqtab and taxa tables

### ISSUE THREAD

**Issue by ganiatgithub** [benjjneb/dada2#774]
Hi, 

I want to investigate the relative abundance of 5 genera, over 5 time points.
I've adopted the dada2 tutorial to analyze my own data, and have generated the seqtab.nochim (5 rows, 3587 cols) and also taxa (3587 rows, 6 cols).

Intuitively I wish to obtain a table that contains information from both seqtab.nochim and taxa, how can I do that?

Alternatively, is there a way to select only 5 genera over 5 time points, and plot the relative abundance?

Kind regards.

**Comment by benjjneb** [comment]
> Intuitively I wish to obtain a table that contains information from both seqtab.nochim and taxa, how can I do that?

I think `cbind(seqtab.nochim, taxtab)` will do it.

> Alternatively, is there a way to select only 5 genera over 5 time points, and plot the relative abundance?

Yes, lots of ways to do that in R. What is your familiarity with working in R? Whether familiar or not, you ay want to look into [the phyloseq package](https://joey711.github.io/phyloseq/) which has been built to help do the analysis of microbiome data (that dada2 package is focused on turning the bioinformatics of processing the raw sequencing data).
