### ISSUE TITLE
assignTaxonomy doesn't work with lowercase sequences

### ISSUE THREAD

**Issue by dswdejonge** [benjjneb/dada2#775]
Hi there!
Quick bug: the assignTaxonomy algorithm doesn't work if you provide it a lowercase sequence. It will report the error:
"Error in C_assign_taxonomy(seqs, rc(seqs), refs, ref.to.genus, tax.mat.int,  : 
  Sequences must have at least 40 valid kmers to classify."
If the exact same sequence is used in uppercase it works fine.

**Comment by benjjneb** [comment]
An easy workaround would be to run a `toupper` call on your sequences before assigning taxonomy. But that would also be easy to do within the function itself, so we might want to add that.
