### ISSUE TITLE
dada2 : quality of data and derep argument error

### ISSUE THREAD

**Issue by hasninhz** [benjjneb/dada2#776]
Hi Dr Benjamin,

I'm stuck with the script provided in the tutorial, need your opinion and help on this.

1.  I'm using dada2 version 1.10. I've managed to follow thru tutorial with data from MiSeq, everything went well. Now I'm implemented it on my data, but I got error. I repeated it with MiSeq data, it also generated the same error, which didn't happened last time.

![error](https://user-images.githubusercontent.com/50934421/58528595-b1c05800-8209-11e9-8665-42e9574d9178.png)

2.  Based on quality score for forward and reverse sequence, I decided to set truncLen=c(0,0), means I didn't do any trimming. Is this correct?

![Forward_qualityScore](https://user-images.githubusercontent.com/50934421/58528645-efbd7c00-8209-11e9-8738-8b71f3437efe.png)
![Reverse_qualityScore](https://user-images.githubusercontent.com/50934421/58528656-f8ae4d80-8209-11e9-90f8-c7bd7174420e.png)

3.	For error rates graph, is my sequencing data showed good error rate?

![Forward_errorRates](https://user-images.githubusercontent.com/50934421/58528717-4925ab00-820a-11e9-9ce3-ae1df00c3660.png)
![Reverse_errorRates](https://user-images.githubusercontent.com/50934421/58528724-52af1300-820a-11e9-8438-6a3b19e99ecc.png)

Looking forward to hear from you soon.
Thank you!

**Comment by benjjneb** [comment]
To fix the derep-class error, you either need to [update to package version 1.12](https://benjjneb.github.io/dada2/dada-installation.html), or use [the prior version of the tutorial (1.8)](https://benjjneb.github.io/dada2/tutorial_1_8.html). There was a change in tutorial syntax with 1.12 that doesn't work with earlier versions of the package.

Depending on your amplicon length, I probably would truncate off the last 10-20 bases in your reads, as quality really drops there. But only if your amplicon is short enough that the truncated reads would still overlap.
