### ISSUE TITLE
Ezbiocloud database?

### ISSUE THREAD

**Issue by mhmism** [benjjneb/dada2#778]
I would like to know whether do you recommend using the Ezbiocloud database for assigning taxonomy? I have not seen any posts for it here despite that it is a famous one.
I have already formatted a custom dada2 database for it according to the published protocol, but I'm not sure if I did it the right way. Is there an already made trusted one that I can use?
 
Thanks in advance!

**Comment by benjjneb** [comment]
We have not generated an Ezbiocloud reference fasta ourselves. If you've done so, we'd be happy to add it to the contributed databases on our website upon confirming it works and if you deposit it in a doi-able repostiry (we use Zenodo).

**Comment by dswan** [comment]
Probably worth noting that even if generated, this would be limited to non-profit/academic usage. The database cannot be used in a commercial context and this is made explicit when you download it. It would be good to avoid cases like this: https://github.com/tseemann/abricate/issues/48

**Comment by mhmism** [comment]
I think you are right @dswan, the publically available Ezbiocloud database is only limited to non-profit/academic usage.

**Comment by benjjneb** [comment]
Closing this. We are happy to link to a dada2-formatted EzBioCloud database, w/ appropriate licensing information also linked, but given those license issues and the recent termination of the development of the publicly available EzBioCloud database, we are not going to pursue this ourselves.
