### ISSUE TITLE
File format

### ISSUE THREAD

**Issue by fionnualamary** [benjjneb/dada2#78]
Hi,

The only files I have been given to analyze are in Fasta format. Does the quality score in the Fastq files in Dada2 have a huge significance, or could I potentially convert the Fasta files to Fastq using a fake quality score, and do some analysis then? 

Thanks for any help!

**Comment by benjjneb** [comment]
For Illumina sequencing the quality score is very important. If this is 454 sequencing you can go ahead without the quality scores without much worry as those are not very informative, but I do not recommend doing so if it was Illumina data.

If you do want to try it w/o quality, you will have to add fake quality scores (our import function only imports fastq files) but you can then run the inference algorithm while ignoring the qualities: `dada(dereps, ..., USE_QUALS=FALSE)`

**Comment by fionnualamary** [comment]
That's fantastic, thanks for your help!

Regards,
Fionnuala
