### ISSUE TITLE
Multithreading causes memory errors and core dump

### ISSUE THREAD

**Issue by phlatphish** [benjjneb/dada2#780]
specifying multithread=TRUE or multithread=16 or multithread is causing learnErrors() to throw memory errors.  It does not do it consistently. For example, following the examples in your tutorial, multithread=16 works OK with R1 but not with R2.

I redirected STDERR to a file, which is attached.

[errorlog.txt](https://github.com/benjjneb/dada2/files/3241935/errorlog.txt)

This is my system:
uname -a
Linux mescalero.ncgr.org 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I am using a conda environment:

r-base                    3.5.1             he45234b_1005    conda-forge
bioconductor-dada2        1.10.0           r351hf484d3e_0    bioconda

**Comment by benjjneb** [comment]
We think this issue was fixed in conda build 1001 and later of rcppparallel. See this thread for more info: https://github.com/benjjneb/dada2/issues/684#issuecomment-483854212

**Comment by phlatphish** [comment]
Very good, thanks. I'll see if that fixes my issue.

**Comment by phlatphish** [comment]
That fixed it, thanks.
