### ISSUE TITLE
losing reads in dada2 qiime2

### ISSUE THREAD

**Issue by dixi06** [benjjneb/dada2#782]
Hello sir,

 @benjjneb 

I am using qiime2 dada2 denoise-paired-end command for 16S rRNA sequences from Illumina Miseq 2x300 run with primer 515F & 806R. I used trunclen=c(240, 180) and many others and still losing 35% of reads. 
How much % read loss is ok after denoising paired-end sequences? 

Thanks a lot.

Dixi

**Comment by benjjneb** [comment]
You've lost 35% of your total reads over the entire pipeline? That is quite normal.

What you want to check for is if there is any single step associated with a large (>30%) loss of reads, as that indicates problems. Except for filtering, where is it OK to filter out higher fractions of reads if you choose.

**Comment by dixi06** [comment]
>
> What you want to check for is if there is any single step associated with a large (>30%) loss of reads, as that indicates problems. Except for filtering, where is it OK to filter out higher fractions of reads if you choose.

It looks like this. More reads are lost in merging. 

![Screen Shot 2019-06-01 at 10 36 16 AM](https://user-images.githubusercontent.com/21266374/58751832-24734280-8459-11e9-9204-9f8e9fc80d02.png)

**Comment by benjjneb** [comment]
It's probably OK. You might be able to get more reads through the pipeline using one fo the pooling options, but those aren't available in the Q2 plugin yet (next release hopefully).
