### ISSUE TITLE
dada2 get stuck after filterAndTrim

### ISSUE THREAD

**Issue by nstarkloff** [benjjneb/dada2#783]
Hi there, 

I recently worked with a dataset with 480 samples and it ran for hours and did not produce an output. So I reran it with just 10 and debugging commands before every command, and it has been stuck after filterAndTrim for 2 hours. It only has 10 samples! Additionally it is only using 1 sample for error rate calculations: 

847549745 total bases in 5617260 reads from 1 samples will be used for learning the error rates. 

Please help.

**Comment by benjjneb** [comment]
What sequencing tech and amplicon are you using? Is the typical depth of your samples 5M+ reads?

Can you post your workflow up to `learnErrors`. Also, what is the output of `derepFastq(filFs[[1]], verbose=TRUE)`, or whatever your first filtered sampel would be.
