### ISSUE TITLE
Mock community with too many variants 

### ISSUE THREAD

**Issue by adriaaula** [benjjneb/dada2#784]
Hello there,

For our analysis we performed a mock community consisting on 3 samples with hypothetically 12 variants and 3 more samples with 27 variants. But our preliminar results with dada2 presented way more variants than we expected (a total of 70!). 

We didn't have a proper explanation of why did this happen. 

#### Important parameters in the DADA2 run 
- V4 V5 region (~370 bp). 
- Primers removed with cutadapt. 
- Trunclength (left/right): 230,210
- maxEE: 0.3, 0.3
- chimera detection mode: consensus 
- Dada2 ver: dada2_1.12.1

The parameters were quite conservative, so maybe the errors come from downstream processes? 

Our exploratory analysis of the results: 
[mock_analysis.html.zip](https://github.com/benjjneb/dada2/files/3248684/mock_analysis.html.zip)

The mock community FASTQ (primers trimmed already): 
https://zenodo.org/record/3237823#.XPY_DdP7RTY

What could be the origin of these variants? 
Some of them are appearing in only one or two samples, whereas others appear in at most 6 samples. 
The clones were sequence-checked through Sanger before the whole procedure. If this information is useful I can obtain it.

**Comment by benjjneb** [comment]
My first suspicion would be that these represent contaminants, either of the mock itself, from other reagents, or possibly cross-contamination from other samples. The fact that they are at low abundances is at least consistent with that hypothesis, as well as the fact that they are quite distant from the expected sequences that were detected.

The html doesn't have the full sequences so I couldn't blast them myself, but what do you get when you BLAST those unexpected ASVs againt nt? If they are contaminants, they will likely closely if not exactly hit previously observed sequences.

**Comment by adriaaula** [comment]
I attach the seqtable! 

The most abundant possible contaminants/unknown origin variants (238,221 and 189 reads) had exact hits with other Euryarchaeota both from nt and SILVA (v132) or close matches. So I guess that this solves a little the mistery (the variants are true biological contamination coming from who knows where). 

Arguing therefore that they are real biological variants, and knowing that we had presumably clean clones (there was a Sanger step for checking clone purity), we could think that they come from cross-contamination from the other samples in the run? A weird thing is that some of the variants appear in all the 6 samples. Is this normal? I really wish we had a negative control as the one you specify in the `decontam` package. 

If I wanted a conservative dada2 run, what should I change as parameter to filter out variants at least  backed up by 50 sequences? To filter out doubletons and similar variants. Or usually we filter out these variants once we have the seqtab?  Thanks for your time! 

[mock_seqtab_final.rds.zip](https://github.com/benjjneb/dada2/files/3262211/mock_seqtab_final.rds.zip)

**Comment by benjjneb** [comment]
> Arguing therefore that they are real biological variants, and knowing that we had presumably clean clones (there was a Sanger step for checking clone purity), we could think that they come from cross-contamination from the other samples in the run?

Cross-contamination is possible. It's hard to say definitively though, especialy when you have just a few samples.

> A weird thing is that some of the variants appear in all the 6 samples. Is this normal? 

It's not unusual at least for contaminants to repeatedly arise in each sample. Reagent contaminants are known to do that, and cross-contaminants can as well especially if the cross-contaminant is very abundant in other samples on the run. Laboratory contamination is something to think about as well, are these contaminating Euks possibly in some other samples/experiments you've worked with in the lab?

> If I wanted a conservative dada2 run, what should I change as parameter to filter out variants at least backed up by 50 sequences? To filter out doubletons and similar variants. Or usually we filter out these variants once we have the seqtab? 

Yes I would recommend performing further filtering on the sequence table. Independent filtering is a valid strategy prior to further analysis and can improve statistical power among other things, as it can reduce the number of hypotheses tested. Common strategies are to filter based on prevalence (i.e. number of samples in which a variant is present, perhaps above some threshold frequency) or based on overall frequency in the dataset. There is no one answer on a perfect independent filtering threshold though.

**Comment by adriaaula** [comment]
Never said thanks :) 
Thanks a lot :))
