### ISSUE TITLE
assignTaxonomy() assigns species even when using taxLevels option

### ISSUE THREAD

**Issue by antonioggsousa** [benjjneb/dada2#786]
Hi, 
I don't know what I'm doing wrong, but when I use assignTaxonomy() function to assign taxonomy until genus level by setting `taxLevels=c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus")`, I still get species level assignments, with the column name "NA" (see the code below). 

`tax_gtdb <- assignTaxonomy(ASV_tbl, "database/GTDB_bac-arc_ssu_r86.fa.gz", taxLevels=c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus"), multithread=50)`

I know that the "GTDB_bac-arc_ssu_r86.fa.gz" database has sequences with full taxonomy until species level, but the option `taxLevels=c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus")` should not avoid these assignments with the RDP classifier algorithm? 

Then, when I assign taxonomy at species level with addSpecies, it creates another column with the column name "Species" (see the code below). So, I get two species assignments, one with RDP classifier and another using 100% matches.  

`tax_gtdb_spp <- addSpecies(tax_gtdb, "database/GTDB_dada2_TRIM_CLASS_SPP.fa.gz")
saveRDS(tax_gtdb_spp, "ASV_tax_gtdb.rds")`

So, I don't know what I'm doing wrong here! 
Thanks in advance, 
António

**Comment by benjjneb** [comment]
The `taxLevels` argument isn't intended to define the levels that will be assigned, its just there to name the columns in the output matrix, and is most useful when dealing with reference dbs that have non-standard levels like "superfamily" and such in them. If you don't want the last column (the species column) just remove it from the output matrix. Something like:

```
tax <- assignTaxonomy(ASV_tbl, "database/GTDB_bac-arc_ssu_r86.fa.gz")
tax <- tax[,-7] # Where the 7th column is the species column
```

That table just has the assignments down to the genus level, and running `addSpecies` on top of that table should act as desired.

**Comment by antonioggsousa** [comment]
Thanks @benjjneb!
