### ISSUE TITLE
Using DADA2 for sanger sequences (ITS region)

### ISSUE THREAD

**Issue by carolinapinapaez** [benjjneb/dada2#787]
Is it possible to use DADA2 to process ITS (~800 bp) Sanger sequences with variable length? This is the whole region, ITS1-5.8-ITS2. I want to assign an identity to my sequences.

**Comment by benjjneb** [comment]
In theory you can, but I'm not sure you want to. How many Sanger sequences are you obtaining from each sample? If it's just a few per-sample, or even just a few dozen, I wouldn't recommend using DADA2 denoising, as the error-correction is relying on seeing more than one repeat of biological samples, which is an assumption that makes more sense as the number of reads scales into the many hundreds and above.

If you just want to assign taxonomy to your Sanger sequences, you can use `assignTaxonomy` as is though.

**Comment by carolinapinapaez** [comment]
I have a good number of sequences per sample (~100) but not for all the samples.  Is there a way to generate a ESV table with this data? Thanks for your response.

**Comment by benjjneb** [comment]
If you really want to try, I would recommend truncating all your reads to a common length first, and then running the algorithm in pooled mode, i.e. using `pool=TRUE` for both `learnErrors` and `dada`.

However, I would urge caution here. I think that the total number of reads you have is less than recommended and what the algorithm has been tested on.
