### ISSUE TITLE
DADA2 removePrimers function removes about half of all sequences

### ISSUE THREAD

**Issue by aldendirks** [benjjneb/dada2#788]
I'm processing ~1,500 base pair rDNA amplicon data from arbuscular mycorrhizal communities. DADA2 has been the most accessible software for handling PacBio data for me so far, so thanks for your great work!

One concern I have with my data that might be applicable to others is in the `removePrimers` step I lose almost half of my sequences or more (ranging from only 48% to approximately 70% passing filtering, with most hovering a little above 50%). From the tutorial, I expected to lose only about 2%. I understand every dataset is different, but 50% makes me think something is going wrong with the filtering of reverse complement sequences. I've done some manual checks such as: 

- Searching and counting the number of occurrences of my forward and reverse complement primers to see if they add up to close to the total number of sequences for a subset of FASTQ files. Checks out.
- Adding `verbose=TRUE` and watching the output. The function recognizes and says it is reverse-complementing sequences. 
- Trying different combinations of the `primer.rev` parameter. All other inputs failed – which I expected given they are kind of silly - like `primer.rev=wSSUmCf`, `primer.rev=dada2:::rc(wSSUmCf)`, and `primer.rev=wLSUmBr`.

So I am left wondering why so many sequences are being removed in this step and whether this is a general issue or a just-me-and-my-data issue? Any help would be so great appreciated. Thanks!

These are my primers: 

`wSSUmCf <- "GCAGTCGAACATGTAGCTGACTCAGGTCACTATYGYTCTTNAACGAGGAATC"`
`wLSUmBr <- "TGGATCACTTGTGCAAGCATCACATCGTAGAACACTCGCAYAYATGYTAGA"`

This is my input: 

`prim <- removePrimers(fns, nops, primer.fwd=wSSUmCf, primer.rev=dada2:::rc(wLSUmBr), orient=TRUE, verbose=TRUE)`

This is a sample of the verbose output from the function:

```4346 sequences out of 10634 are being reverse-complemented.
Read in 10634, output 6200 (58.3%) filtered sequences.
Multiple matches to the primer(s) in some sequences. Using the longest possible match.
Multiple matches to the primer(s) in some reverse-complement sequences. Using the longest possible match.
1989 sequences out of 5185 are being reverse-complemented.
Read in 5185, output 2977 (57.4%) filtered sequences.
Multiple matches to the primer(s) in some sequences. Using the longest possible match.
Multiple matches to the primer(s) in some reverse-complement sequences. Using the longest possible match.
2502 sequences out of 5851 are being reverse-complemented.
Read in 5851, output 3769 (64.4%) filtered sequences.
Multiple matches to the primer(s) in some sequences. Using the longest possible match.
Multiple matches to the primer(s) in some reverse-complement sequences. Using the longest possible match.
4287 sequences out of 11585 are being reverse-complemented.
Read in 11585, output 5969 (51.5%) filtered sequences.
Multiple matches to the primer(s) in some sequences. Using the longest possible match.
Multiple matches to the primer(s) in some reverse-complement sequences. Using the longest possible match.```

**Comment by aldendirks** [comment]
The primers include the PacBio universal primer sequence as well as the AMF-specific primer. I wonder if something about reverse complementing the wobble primer is throwing it off. Maybe if I just use the standard PacBio forward and reverse primers (without the variable sites) it will work. I'll try this and report back.

**Comment by aldendirks** [comment]
It worked a lot better! This makes wonder even more if there is some sort of bug with removing the reverse complement of wobble primers...

Primers
`wSSUmCf <- "GCAGTCGAACATGTAGCTGACTCAGGTCAC"`
`wLSUmBr <- "TGGATCACTTGTGCAAGCATCACATCGTAG"`

Output: 

```
Creating output directory: data/pacbio/fastq/amf_mod//noprimers
Multiple matches to the primer(s) in some sequences. Using the longest possible match.
Multiple matches to the primer(s) in some reverse-complement sequences. Using the longest possible match.
3760 sequences out of 8372 are being reverse-complemented.
Read in 8372, output 7094 (84.7%) filtered sequences.
Multiple matches to the primer(s) in some sequences. Using the longest possible match.
Multiple matches to the primer(s) in some reverse-complement sequences. Using the longest possible match.
5105 sequences out of 10945 are being reverse-complemented.
Read in 10945, output 9355 (85.5%) filtered sequences.
Multiple matches to the primer(s) in some sequences. Using the longest possible match.
Multiple matches to the primer(s) in some reverse-complement sequences. Using the longest possible match.
1621 sequences out of 3491 are being reverse-complemented.
Read in 3491, output 2945 (84.4%) filtered sequences.
Multiple matches to the primer(s) in some sequences. Using the longest possible match.
Multiple matches to the primer(s) in some reverse-complement sequences. Using the longest possible match.
4602 sequences out of 9333 are being reverse-complemented.
Read in 9333, output 8175 (87.6%) filtered sequences.
```

**Comment by aldendirks** [comment]
To add to the conversation, I processed 48 CCS FASTQ files specifying either full primers (PacBio universal sequence and AMF-specific sequence) or specifying reduced primers (PacBio universal sequence only) in pretty much the same way (only adjusting `minLen` and `maxLen` in the `filterAndTrim` step) with very different results. The first method resulted in large sequence loss in the removal of primers, the latter did not. However, the latter resulted in large sequence loss in denoising (almost completely trashing many sequences), while the latter did not. 

## Specified primers - full primers

seq | ccs | primers | filtered | denoised
-- | -- | -- | -- | --
ccs_lbc1.fastq | 8372 | 4377 | 2730 | 1888
ccs_lbc10.fastq | 10945 | 5502 | 3295 | 2323
ccs_lbc11.fastq | 3491 | 2005 | 1196 | 762
ccs_lbc12.fastq | 9333 | 4897 | 3459 | 3020
ccs_lbc13.fastq | 9582 | 4864 | 3383 | 2456
ccs_lbc14.fastq | 10350 | 5344 | 3180 | 2332
ccs_lbc15.fastq | 9980 | 5663 | 3569 | 2908

## Specified primers - PacBio universal primer only

seq | ccs | primers | filtered | denoised
-- | -- | -- | -- | --
ccs_lbc1.fastq | 8372 | 7094 | 3930 | 239
ccs_lbc10.fastq | 10945 | 9355 | 4831 | 2
ccs_lbc11.fastq | 3491 | 2945 | 1582 | 1
ccs_lbc12.fastq | 9333 | 8175 | 5213 | 1921
ccs_lbc13.fastq | 9582 | 8215 | 5074 | 1946
ccs_lbc14.fastq | 10350 | 8959 | 4617 | 54
ccs_lbc15.fastq | 9980 | 8796 | 4851 | 18

**Comment by benjjneb** [comment]
Thanks for these reports, they are very useful as we are still building our knowledge base about PacBio sequencing "in the wild" given that this is a relatively new functionality in the package.

> However, the latter resulted in large sequence loss in denoising (almost completely trashing many FASTQ files), while the prior ultimately retained many more sequences.

The latter, i.e. removing the PacBio universal primers but not the PCR primers, is not going to be effective because it will leave the ambiguous (or wobble) nucleotides on the reads. The variants of these ambiguous nucleotides will be interpreted as biological variation by the `dada` algorithm, as it assumes that all artificial sequence variation has been removed, and thus denoising will either perform poorly or even basically fail as you see here.

So, your initial strategy of removing the full primer is the right one, and the question is how to do that while retaining more of the overall reads. I might try two things: First, just remove the PCR primer sequences (the universal primers will get removed automatically since they will be outside the region between the PCR primers). Second, try increasing the `max.mismatch` paremeter, perhaps as high as 4, when calling `removePrimers`. This will allow more mismatches between the provided primer sequence and the reads while still retaining the read.

> I wonder if something about reverse complementing the wobble primer is throwing it off. 

This shouldn't be a problem, but if the above suggestions don't work might have to look into possible buggy behavior. I haven't tested primers with Ns, just Ys and the like, before.

**Comment by aldendirks** [comment]
@benjjneb 

Thanks for the feedback and suggestions. I tried both suggestions simultaneously and this is a comparison of my output to the table I printed above. There is about a 4-5% increase in number of sequences retained through denoising when changing `max.mismatch` in `removePrimers` from 2 to 4. 

I of course want to get rid of the low quality sequences. Since I really don't have a comparison to establish what is normal, it is difficult to say whether my results so far are good enough of if good data are being dropped. Compared to 2% loss for 16s data, 20-40% loss in the `removePrimers` step still seems like a lot. Maybe there are frequent indels in my primer region so these sequences are being dropped? 

I guess my question is do you have any sense of whether my newly observed loss of sequences in the `removePrimers` step seems like too many?

Thanks so much for your prompt help!
Alden

## Specified primers - AMF primers
`wSSUmCf <- "TATYGYTCTTNAACGAGGAATC"`
`wLSUmBr <- "AACACTCGCAYAYATGYTAGA"`
`prim <- removePrimers(fns, nops, primer.fwd=wSSUmCf, primer.rev=dada2:::rc(wLSUmBr), orient=TRUE, verbose = TRUE, max.mismatch = 4)`

seq | ccs | primers | filtered | denoised | retained
-- | -- | -- | -- | -- | --
ccs_lbc1.fastq | 8372 | 5651 | 3173 | 2213 | 26.4%
ccs_lbc10.fastq | 10945 | 7212 | 3867 | 3092 | 28.3%
ccs_lbc11.fastq | 3491 | 2511 | 1383 | 846 | 24.2%
ccs_lbc12.fastq | 9333 | 6279 | 4049 | 3525 | 37.8%
ccs_lbc13.fastq | 9582 | 6440 | 4074 | 2954 | 30.8%
ccs_lbc14.fastq | 10350 | 6859 | 3658 | 2705 | 26.1%
ccs_lbc15.fastq | 9980 | 7150 | 4093 | 3372 | 33.8%

## Specified primers - full primers
`wSSUmCf <- "GCAGTCGAACATGTAGCTGACTCAGGTCACTATYGYTCTTNAACGAGGAATC"`
`wLSUmBr <- "TGGATCACTTGTGCAAGCATCACATCGTAGAACACTCGCAYAYATGYTAGA"`
`prim <- removePrimers(fns, nops, primer.fwd=wSSUmCf, primer.rev=dada2:::rc(wLSUmBr), orient=TRUE, verbose = TRUE, max.mismatch = 2)`

seq | ccs | primers | filtered | denoised | retained
-- | -- | -- | -- | -- | --
ccs_lbc1.fastq | 8372 | 4377 | 2730 | 1888 | 22.6%
ccs_lbc10.fastq | 10945 | 5502 | 3295 | 2323 | 21.2%
ccs_lbc11.fastq | 3491 | 2005 | 1196 | 762 | 21.8%
ccs_lbc12.fastq | 9333 | 4897 | 3459 | 3020 | 32.4%
ccs_lbc13.fastq | 9582 | 4864 | 3383 | 2456 | 25.6%
ccs_lbc14.fastq | 10350 | 5344 | 3180 | 2332 | 22.5%
ccs_lbc15.fastq | 9980 | 5663 | 3569 | 2908 | 29.1%

**Comment by benjjneb** [comment]
What machine (RSII or Sequel) and what chemistry did you do your sequencing on? 
Also, what was your initial ccs curation parameters? Especially `minPasses` and `minPredictedAccuracy`?

**Comment by aldendirks** [comment]
Hi @benjjneb 

These samples were sequenced on a PacBio Sequel machine using a Sequel Sequencing Kit 3.0 (is this the chemistry information you asked about?)

The sequencing center created ccs files using the default parameters of ccs 3.4.1, that is `minPasses = 3`, but I'm not sure what the default for `minPredictedAccuracy` is. 

I converted the ccs BAM files to FASTQ files using the `reformat.sh` script from BBMap 38.50.

I took it from there with DADA2.

**Comment by benjjneb** [comment]
Hm... right now we don't have a better solution for the primer step unfortunately, but I agree that seems like a high fraction of reads to be losing at that step.

What I'd recommend for now is to try to retain more reads at the other steps. Perhaps relax the filtering parameters a little bit, and run the `dada` step with `pool="pseudo"`. I might even try `pool=TRUE` if true pooling doesn't take too long. That will help pick up some more rare stuff in each sample (e.g. singletons).

If you don't mind sharing a sample I would be interested to take a closer look at the primer behavior, although that probably won't happen for a bit.

**Comment by aldendirks** [comment]
Hi there, 

I was able to retain more reads by relaxing various parameters (hopefully not too much):

- `removePrimers(..., max.mismatch = 4)`
- `filterAndTrim(..., minQ = 2, maxEE = 5)`
- `dada(..., pool = TRUE)`

seq | ccs | primers | filtered | denoised | retained
-- | -- | -- | -- | -- | --
ccs_lbc1.fastq | 8372 | 5651 | 4329 | 3075 | 36.7%
ccs_lbc10.fastq | 10945 | 7212 | 5654 | 4748 | 43.4%
ccs_lbc11.fastq | 3491 | 2511 | 1636 | 1274 | 36.5%
ccs_lbc12.fastq | 9333 | 6279 | 4804 | 4340 | 46.5%
ccs_lbc13.fastq | 9582 | 6440 | 5129 | 4247 | 44.3%
ccs_lbc14.fastq | 10350 | 6859 | 5399 | 4286 | 41.4%
ccs_lbc15.fastq | 9980 | 7150 | 4681 | 4104 | 41.4%

I just emailed you some FASTQ files. Thanks for your help!

**Comment by benjjneb** [comment]
Some progress here in 68d1f87bed9452a5e7acb4f5caa99af248921935

In this commit, I added the ability to allow indels when matching primer sequences using `removePrimers`. This significantly increases the number of reads in your data that pass that intial step, to >90%. There is a cost, as allowing indels means that a slower pattern matching function must be run, so `removePrimers` is about 4x slower.

I am still looking into the relatively significant number of reads failing to get through denoising. Almost certainly one factor is the seemingly higher error rate in this dataset than in the ones I had investigated. I'd estimate that only ~10% of reads are error-free due to about a 5x higher error rate than what I saw in previous PacBio Sequel amplicon data, which makes denoising more difficult.

**Comment by aldendirks** [comment]
@benjjneb Thanks so much for sharing your work and communicating with me. I'm excited to give this another try!

**Comment by kfgibson** [comment]
> I am still looking into the relatively significant number of reads failing to get through denoising. Almost certainly one factor is the seemingly higher error rate in this dataset than in the ones I had investigated. I'd estimate that only ~10% of reads are error-free due to about a 5x higher error rate than what I saw in previous PacBio Sequel amplicon data, which makes denoising more difficult.

Any update on this? I am having this problem with my PacBio data - many reads are failing to get through the denoising step. I think the error rate in my reads is also quite high as I had to relax the maxEE parameter substantially to get most of them to survive filtration.

**Comment by benjjneb** [comment]
> Any update on this? I am having this problem with my PacBio data - many reads are failing to get through the denoising step. I think the error rate in my reads is also quite high as I had to relax the maxEE parameter substantially to get most of them to survive filtration.

There is a level of noise at which the dada2 denoising approach will fail. As a rule of thumb, if the fraction of error-free reads (after filtering) is dropping below 10%, denoising will be signiificanlty degraded, and if it is below 1% it is not an advisable approach in most cases.

Depending on the specifics of your PacBio data, it may have error rates that are too high to work effectivley with DADA2. For example, the older RS2 chemistries mostly don't have high enough accuracy, it was with the third-gen RS2 chemistry and really with the newer "HiFi" chemistry and CCS base calling that accuracy got consistently high enough for the DADA2 approach.

**Comment by fanhuan** [comment]
I am facing the same problem and I realized that it was because removePrimers will drop the reads without the reverse primer at the end if primer.rev was set. I wish there was an option that would allow me to set primer.rev without dropping the reads with the forward primer only. Or is there a reason for dropping those reads?

Thank you.

**Comment by benjjneb** [comment]
@fanhuan To be honest, we know that the functionality of `removePrimers` could be extended in various ways, but we want to avoid piling too many options into it for reasons of long-term maintenance.

There are more dedicated software solutions with very rich feature sets that can be used to do primer removal, such as cutadapt or trimmomatic among others.

**Comment by fanhuan** [comment]
@benjjneb Thank you for your response. Understand. I'm using cutadapt as suggested in your pipeline.
