### ISSUE TITLE
https link does seem to work

### ISSUE THREAD

**Issue by gregcaporaso** [benjjneb/dada2#79]
I'm trying to install dada2 using the install instructions in the README, and the ``https`` link doesn't work but converting it to an ``http`` link does work. I'm not sure if this is something that's possible for you to address (other than by changing the install instructions to pull from ``http``).

**Comment by benjjneb** [comment]
An annoyance that we can't entirely fix, https: links just aren't supported on all R installs.

Should have the suggestion to use http: in the readme though, thanks for pointing that out. Fixed in 7f57cde8f0f82c8650f8e211c857095e40c75e52
