### ISSUE TITLE
Application of dada2 to non-overlapping reads

### ISSUE THREAD

**Issue by JoelSEspinoza** [benjjneb/dada2#790]
Hello, I have been tasked with assigning taxonomy to insect sequences for a certain project. The forward and reverse reads are 250bp long, however, the amplicons I am looking at are about 600bp long so there is no overlap. I think DADA2 can be very useful if applied in this manner as it would save much time and from having to download multiple software to manipulate these sequences. I am aware that DADA2 has the "justConcatenate" argument for this purpose, but I have a few questions I was wondering if you could answer.

1) Is there anything I should keep in mind when trying to merge non overlapping forward and reverse reads (other than about justConcatenate)?
2) If I use justConcatenate, then will I need to edit the distance between the forward and reverse reads of my reference sequences? If so, do you have a recommended method of doing this?
3) Can the “assignTaxonomy” function be used with reference data sequences of any species, not specific to micro-organisms?

**Comment by benjjneb** [comment]
> 1. Is there anything I should keep in mind when trying to merge non overlapping forward and reverse reads (other than about justConcatenate)?

Nope, that's about it. I guess note that a string of 10Ns will be added in between the concatenated forward/reverse reads, unless you change that default in `mergePairs`.

> 2. If I use justConcatenate, then will I need to edit the distance between the forward and reverse reads of my reference sequences? If so, do you have a recommended method of doing this?

It depends on what you want to do next. You don't need to edit anything to continue using those concatenated reads within the dada2 package (e.g. with `assignTaxonomy`), but maybe you do for some outside software? You'd have to specify what you want to do exaclty.

> 3. Can the “assignTaxonomy” function be used with reference data sequences of any species, not specific to micro-organisms?

Yes. The algorithm itself is agnostic to what kind of species you are looking at, the reference database is what determines that. You can see the reference databases we have already compiled here: https://benjjneb.github.io/dada2/training.html

There are also instructions there for formatting new databases that work with `assignTaxonomy` that could represent any other organismal group.

**Comment by JoelSEspinoza** [comment]
According to issue #403, there are currently no plans to add a functionality to the assignSpecies function to work with Ns resulting from the justConcatenate argument. Would it potentially be a good idea to edit the reference sequences by manually deleting the bps between the first and last 250 bps of the ITS region (I'm working with the ITS region), and merging these with a sequence of 10 nucleotides and then replacing the Ns in our sample reads with the same 10bp bucleotide sequence? That way we could retain the forward and reverse reads when comparing to our reference data.

**Comment by benjjneb** [comment]
> Would it potentially be a good idea to edit the reference sequences by manually deleting the bps between the first and last 250 bps of the ITS region (I'm working with the ITS region), and merging these with a sequence of 10 nucleotides and then replacing the Ns in our sample reads with the same 10bp bucleotide sequence?

This seems like a tricky/dangerous approach. What I'd recommend instead is to run `assignSpecies` using just the forward read data, i.e. whatever is in front of the inserted Ns. That should still do what you want, and avoid the challenges that you might encounter trying to refactor the sequence assignment database the way you are proposing.

**Comment by JoelSEspinoza** [comment]
Okay, that makes sense. I saw something similar on issue #529 and #65. I attempted to do the recommended gsub, but when I used: 
mergers$`1_CGMB7.1.AGGCAGAA_ACTGCATA.` <- gsub("NNNNNNNNNN", "AAAAAAAAAA", mergers$`1_CGMB7.1.AGGCAGAA_ACTGCATA.`)
I received this as the output for seqtab <- makeSequenceTable(mergers):
Error in FUN(X[[i]], ...) : Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns. 
And just to verify, when I used:

mergers$sequence <- gsub("NNNNNNNNNN", "AAAAAAAAAA", mergers$sequence)

I get the same error when using "makeSequenceTable(mergers)":
Error in FUN(X[[i]], ...) : Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.

Would you still recommend using this workaround from #529?
sq.R1 <- substr(getSequences(seqtab), 1, R1_READ_LEN)
gen.spc <- assignSpecies(sq.R1, "path/to/species_assignment.fa")
and if so, would R1_READ_LEN just be the length of my forward read before merging?

**Comment by benjjneb** [comment]
> Would you still recommend using this workaround from #529?
> sq.R1 <- substr(getSequences(seqtab), 1, R1_READ_LEN)
> gen.spc <- assignSpecies(sq.R1, "path/to/species_assignment.fa")
> and if so, would R1_READ_LEN just be the length of my forward read before merging?

Yes, that should still work, as long as your forward reads are all a constant length. If they are different lengths we can do something more clever.
