### ISSUE TITLE
merging learnErrors in technical duplicates of separate Pacbio SMRT cell runs

### ISSUE THREAD

**Issue by pneumowidow** [benjjneb/dada2#793]
Hello Ben,
I just wanted to run a quick technical question by you. If I had 2 technical duplicates (same mock community) that I sequenced in separate runs i.e 2 different SMRT cells and I wanted to take advantage of their combined read abundance to detect low abundance strains, how would I go about that in DADA2?

I understand that I **should not** combine the reads of different runs prior to learning errors. However, I was wondering if I could apply a suggestion you made in post #434 by learning the errors separately for both runs (err_run1 & err_run2) and then defining a new matrix using the maximum of both errors `errM <- pmax(err_run1, err_run2)` . Afterwards combining the reads of both runs and using this new err model to learn the errors of the combined Pacbio run?

Would this be a sensible step to take? 
Many thanks in advance.

**Comment by benjjneb** [comment]
Yeah that would be sensible. I would just clarify that you will use the `errM` error model to perform sample inference (or "denoise") the combined PacBio run, not learn the errors again.

**Comment by pneumowidow** [comment]
Oh yes, sorry that was a typo. I meant what you said. Thank you!
