### ISSUE TITLE
ITS2 Tutorial Input/Output files

### ISSUE THREAD

**Issue by JoelSEspinoza** [benjjneb/dada2#794]
Hello,
I am working through the ITS2 tutorial and for some reason when I use:
rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.cut[[1]]), 
    FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.cut[[1]]), 
    REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.cut[[1]]), 
    REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.cut[[1]]))
This is being returned as the output *note that I wrote (INSERT REST OF PATH HERE)*
Error: Input/Output no input files found dirPath: C:\Users(INSERT REST OF PATH HERE)
\ENSData/cutadapt/SRR5314314_1.fastq.gz pattern: character(0)

This path is different from where I loaded cutadapt, and I think it was created using these lines:
path.cut <- file.path(path, "cutadapt")
if(!dir.exists(path.cut)) dir.create(path.cut)
fnFs.cut <- file.path(path.cut, basename(fnFs))
fnRs.cut <- file.path(path.cut, basename(fnRs))

However, the cutadapt directory is empty when I look in it, and nothing has the name fnFs.cut or fnRs.cut despite that it shows up in my environment without any errors.

Also, when setting up the path to cutadapt using this:
cutadapt <- "C:\\Users\\(INSERT REST OF PATH)\\cutadapt"
system2(cutadapt, args = "--version")
This is the output I get:
[1] 127
Do you have any ideas as to why I might be encountering this issue? Does it have to do with my original path where cutadapt is located?

Thank you in advance for the help!

**Comment by benjjneb** [comment]
It would appear that cutadapt is not succesfully being called. Are you comfortable opening up a shell? Can you enter `"C:\Users\(INSERT REST OF PATH)\cutadapt" -- version` in your shell and see what output is given?

Another issue may be permissions. Does your R session have permission to write to the directory you want the cutadapted files in?

**Comment by JoelSEspinoza** [comment]
I ended up removing and reinstalling cutadapt, and it after defining a specific path for it and running that in R, everything appeared to work. Thank you!
