### ISSUE TITLE
Maximum sequence length error

### ISSUE THREAD

**Issue by aldendirks** [benjjneb/dada2#798]
Hi @benjjneb ,

I'm inquiring into the maximum sequence length allowed for DADA2 1.12.1 analysis. According to your 2019 PacBio paper, the maximum sequence length allowed is 3000 nucleotides. In the sequence filtering step, I set `maxLen = 3000` for amplicons up to 1000 nucleotides (total ribosomal DNA amplicons). Later in the denoising step, I am receiving the following error: "Input sequences exceed the maximum allowed string length." Could you please clarify if the maximum sequencing length is up to 3000 nucleotides inclusive, or less than 3000 nucleotides? 

Best,
Alden

**Comment by benjjneb** [comment]
As of 1.12.1 it is <3000 nucleotides allowed (strictly less than). That maximum length should be extended significantly in the next release though.

**Comment by aldendirks** [comment]
To clarify, I have amplicons up to 10,000 nucleotides, not 1,000 as I wrote above. 

Thanks for the information. Do you have any estimates of when the next release will happen? If you expect to release it by September or so, I can look forward to using it to analyze the longer amplicons before publishing. Otherwise I'll stick with 1.12.1.

Thanks!

**Comment by benjjneb** [comment]
The next release won't be until Fall (see the Bioconductor release schedule for details as they become available). I will probably relax the max length to 9999 this summer though in the devel branch, the only reason not to do it is because I haven't thoroughly evaluated any potential impacts on memory usage yet.

**Comment by tiagojp** [comment]
Dear Benjamin,

Just wondering if this feature has been added to the newest version of dada2 (1.28).

I am playing with some PacBio data for eukaryotes ~ 4000 bp long (Rplot01) which covers most of the rDNA repeat (18S to D3 domain of the 28S). When implementing the learnErrors though, I get the error message "Error: Input sequences exceed the maximum allowed string length." I did reduced the sequence length to max 3000 pb during the filterAndTrim step, but this will drop out most 100% of the sequences as the size variation is minimal in my dataset.

Still, with the few sequences left (29 reads, 19 unique sequences) I was able to run the learnErrors step (of course the plot doesn't look great with so few sequences, Rplot02).

I am hoping to implement dada2 on this dataset, so I am looking forward to hear what updates you may have on this matter.

Sincerely,

Tiago

**Comment by benjjneb** [comment]
The maximum sequence length got bumped to 9999 many versions ago: https://github.com/benjjneb/dada2/commit/52fa6dbb1392a0867f2627495713f290a3739fae

Can you double-check your package version (using `packageVersion("dada2")`), and clarify the exact command and error message?

**Comment by benjjneb** [comment]
1. It shouldn't make any meaningful difference in the (typically) rate-limiting steps of `learnErrors` and `dada`.
2. `filterAndTrim` is our recommended interface to that functionality in the package. It ultimately calls `fastqFilter` or `fastqPairedFilter` as appropriate, but has a bit more polish in terms of documentation and effective error messages.
3. Yep
