### ISSUE TITLE
minLen in filterAndTrim removing almost all sequences

### ISSUE THREAD

**Issue by KarenBell** [benjjneb/dada2#799]
I'm using dada2 to analyse some plant ITS2 sequences, run on 2x300bp Illumina MiSeq.

Initially, I was running filterAndTrim as follows:

ITS_out <- filterAndTrim(ITS_cutFs, ITS_filtFs, ITS_cutRs, ITS_filtRs, trimLeft = c(10,10), truncLen=c(275,175), maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE)

For the most part this worked well, but certain species were consistently undetected from my mock communities (and presumably also from my test samples), because their sequences are too short to pass the filter.

I tried decreasing the truncLen but then had the issue that species with longer sequences are lost at the merge step.

I notice in the ITS recommendations you suggest using minLen rather than truncLen, so I tried the following:

ITS_out_temp2 <- filterAndTrim(ITS_cutFs, ITS_filtFs_temp2, ITS_cutRs, ITS_filtRs_temp2, trimLeft = c(10,10), minLen = 50, maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE)

This removes more than 99% of my sequencing reads. To me this doesn't make sense as truncLen=c(275,175) removed 20-50% of reads for most samples. I would expect that minLen=50 would filter out fewer sequences than truncLen=c(275,175) as the threshold of sequence length to keep them in is lower. Any ideas why this would be happening?

**Comment by benjjneb** [comment]
That doesn't make sense to me either...

Can you post the `plotQualityProfile` graphs from some forward reads and another from revere reads?

**Comment by KarenBell** [comment]
Thank you for your help.

Here are the forward reads of the first two samples:
![image](https://user-images.githubusercontent.com/10533862/60150536-b594c980-980b-11e9-8d9b-60aec9719cb2.png)

Here is one from a single species with short ITS2 sequence:
![image](https://user-images.githubusercontent.com/10533862/60150592-e543d180-980b-11e9-81cd-42f4f9d453a6.png)

Here is one from a single species with long ITS2 sequence:
![image](https://user-images.githubusercontent.com/10533862/60150740-7dda5180-980c-11e9-96d9-b0d55992dcec.png)

Here are the reverse reads for the same four samples:
![image](https://user-images.githubusercontent.com/10533862/60150794-b7ab5800-980c-11e9-9435-a8bfc779a867.png)
![image](https://user-images.githubusercontent.com/10533862/60150843-df022500-980c-11e9-8aaa-8c2e680b3cb7.png)
![image](https://user-images.githubusercontent.com/10533862/60150865-f6411280-980c-11e9-8b00-29ee45398ab8.png)

It looks like there could be a lot of reads that are short PCR artefacts, but not 99% of samples (and why wouldn't these also be eliminated by truncLen?)

**Comment by benjjneb** [comment]
Have you followed [our ITS workflow](https://benjjneb.github.io/dada2/ITS_workflow.html) and removed primers from both the start **and** the end of your forward and reverse reads?

My guess is that you haven't trimmed off the primers towards the ends of the reads (and the adapter/junk DNA after them) and this is explaining what you are seeing. The workflow linked above shows how to do this using cutadapt, and how to verify everything was removed correctly. Once you do that, I think your `minLen` based filtering will work as expected.

**Comment by KarenBell** [comment]
I had a closer look at your ITS workflow, and made a few changes to the way I was implementing cutadapt. This doesn't seem to have made much difference.

I still find that >99% of sequences are removed when I use minLen, and the output is identical whether I use minLen=20, minLen=50, or minLen=100.

e.g. 

ITS_out_temp3 <- filterAndTrim(ITS_cutFs, ITS_filtFs_temp3, ITS_cutRs, ITS_filtRs_temp3, trimLeft = c(10,10), minLen = 50, maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE)

In comparison, a lot more reads are retained when I use truncLen=c(275,125).

e.g. 

ITS_out <- filterAndTrim(ITS_cutFs, ITS_filtFs, ITS_cutRs, ITS_filtRs, trimLeft = c(10,10), truncLen=c(275,175), maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE, compress=TRUE, multithread=TRUE)

**Comment by benjjneb** [comment]
Did you confirm the presence of FWD and rc(REV) primers on the forward reads and that they were removed by cutadapt? And likewise for the reverse reads? That is, what was the output from the `primerHits` results in the ITS workflow, before and after cutadapt?

If the primers are correctly being removed I don't understand the filtering results you are getting.

**Comment by KarenBell** [comment]
I think that may be where the problem is. This is the output before trimming from the single species sample with the short ITS2 sequence (other samples have much lower numbers, some are all 0 before trimming):

> rbind(FWD.ForwardReads = sapply(ITS_FWD.orients, primerHits, fn = ITS_fnFs[[100]]), 
+     FWD.ReverseReads = sapply(ITS_FWD.orients, primerHits, fn = ITS_fnRs[[100]]), 
+     REV.ForwardReads = sapply(ITS_REV.orients, primerHits, fn = ITS_fnFs[[100]]), 
+     REV.ReverseReads = sapply(ITS_REV.orients, primerHits, fn = ITS_fnRs[[100]]))
                 Forward Complement Reverse RevComp
FWD.ForwardReads       0          0       0       0
FWD.ReverseReads       0          0       0      13
REV.ForwardReads       0          0       0      39
REV.ReverseReads       0          0       0       0

After trimming all goes to 0. 

Do these numbers seem quite low? I found a sequence on NCBI for this species, and the length between the primers is 270bp. So I would expect that with 2x300bp sequencing, most reads would have a primer sequence. Also, does it seem odd that the number of forward and reverse primers is different? And exactly 3x?

**Comment by benjjneb** [comment]
Yes those numbers might be low, but it's hard to know for sure without knowing the biological length distribution of this locus. It's not too surprising to see fewer FWD primer hits on the reverse sequences than FWD primer hits on the reverse sequences, just because the quality at the ends of the reverse reads will be lower.

**Comment by KarenBell** [comment]
The known species in my mock communities (or the most closely related species with sequence on NCBI) range in length from 270-364bp for the region between the primers. I don't know exactly what to expect in the unknown samples, but at least for the sample that only contains the species with 270bp sequence I would expect more than 13 and 39. I tried increasing the error rate in cutadapt to 0.2 (since the error rate is expected to be more for 2x300bp Illumina), there were one-two more sequences retained at the filtering step for most files, but still more than 99% being removed.
