### ISSUE TITLE
seqtab merge: Reorient ASVs

### ISSUE THREAD

**Issue by betsyalf** [benjjneb/dada2#801]
Hi Ben et al.,
When combining seqtabs, I am noticing both forward and the reverse complement in my combined table.  Can you recommend R code to identify forward and reverse complement pairs and then reorient and combine them on the final seqtab? 

Cheers,
Betsy

**Comment by benjjneb** [comment]
Sorry for slow response I've been on vacation.

We've gotten this request a couple times now, so this functionality seems worth adding to the `collapseNoMismatch` function.
