### ISSUE TITLE
Error in getSequences(seqtabNoC) : could not find function "getSequences"

### ISSUE THREAD

**Issue by DanCJ91** [benjjneb/dada2#802]
As in Title - that is what comes up when I try to do the Tree. 

I assume a package hasn't been downloaded correctly? Any help would be very much appreciated. 

All I want to do is cluster my reads that have been generated from the taxonomy step in DADA2  :(

**Comment by benjjneb** [comment]
Are you sure the package is loaded?

Can you enter `library(dada2); packageVersion("dada2")` and report the results, and then try the `getSequences(seqtabNoC)` call again?
