### ISSUE TITLE
Trying to read unzipped FASTQ file using shortRead package and readFastq function

### ISSUE THREAD

**Issue by doraga** [benjjneb/dada2#804]
I am trying to read the fastq files using following function:
readFastq('C://Users//Durdona//Documents//BAL_1_S3_L001_I1_001', pattern=character(0))
However it showing up the following output: 
Error: Input/Output
  no input files found
  dirPath: C://Users//Durdona//Documents//BAL_1_S3_L001_I1_001
  pattern: character(0)

I double checked the pathway, tried to move the file and change the directory pathway, still the same thing. How could I read FAST Q file just to see the output?

**Comment by benjjneb** [comment]
R is not finding the filenames you gave. Might your files have extensions (e.g. `.fastq`) that you didn't include in the filename?
