### ISSUE TITLE
assignTaxonomy - monitoring progress?

### ISSUE THREAD

**Issue by pdcountway** [benjjneb/dada2#805]
Hi - I'm repeating a dada2 processing run that I've already completed once, through the assignTaxonomy step and using the PR2 18S reference sequences. This second time through it seems like the process is stuck with a message that says "Finished processing reference fasta", and a blinking cursor. I can enter text at the blinking cursor but nothing happens, suggesting that the job is still moving along, but who knows? Is there any way to monitor the percent of the ASVs that have been processed? I'm multithreading with 32 cores and gave the job 64 Gb of RAM. It's been running for 30+ hours. 
The command I used to launch assignTaxonomy (same as the first run) is:

`> taxa <- assignTaxonomy(seqtab.nochim, refFasta = "/path_to_pr2/pr2_version_4.11.1_dada2.fasta", taxLevels = PR2_tax_levels, minBoot = 0, outputBootstraps = TRUE, verbose = TRUE, multithread = 32) `

Thanks for any suggestions!

**Comment by benjjneb** [comment]
You can check to see if the job is still running on whatever machine you are using to run this script. The exact commands to do that will depend on what sort of system you are using though. If it's on a server, you may want to ask the IT support how to check on job status to see if they are still running.

Also, PR2 needs more memory because it is a larger database. You may want to see if you can allocate more memory to to jobs using PR2, as that will probably help the speed of that step by avoiding swapping.

**Comment by pdcountway** [comment]
Hi Ben,
Yes, I can <qstat job#> to check that the job is still running (which I think it is), and yes, PR2 is big so I get that it takes longer. I can increase the memory from 64 Gb but I guess I'm wondering if some kind of progress bar can be implemented as described here: https://www.r-bloggers.com/tracking-progress-in-r/.
Thanks,
Pete

**Comment by benjjneb** [comment]
Yeah this is actually a long-standing request, see #215 

The reason we haven't done it yet relates to uncertainty about the stability of output from multithreaded C code within R. There are nice solutions like the ones in that post, but unfortunately all the code in dada2 that needs progress reporting is running in C and is multithreaded.

**Comment by pdcountway** [comment]
OK, thanks Ben. The assignTaxonomy script just completed in ~ 60 hours for ~3850 18S-based ASVs using the PR2 database as a reference.

**Comment by benjjneb** [comment]
Linking to #239 as another example of why we should improve the memory scaling of `assignTaxonomy`. That shouldn't take that long.
