### ISSUE TITLE
Trimming parameter optimization for long reads

### ISSUE THREAD

**Issue by michael-weinstein** [benjjneb/dada2#807]
I have developed a script that I believe can help with finding optimal, reproducible trimming parameters when needed (especially when running long amplicons like V3-V4).

In brief, it will develop an exponential regression model for the accumulation of expected error along reads, then simulate the trim and filter process to look at rates of read retention.  Its ultimate goal is to find trimming parameters between the forward and reverse reads that will allow the maximum number of reads to pass filtering while allowing a minimal amount of expected error.

This script runs in a Docker (Dockerfile included) or in Python 3.6.  It is pretty performant generally adds little time to the pipeline (about 45 seconds on my laptop).

https://github.com/Zymo-Research/figaro

**Comment by benjjneb** [comment]
Thanks for working on this! Guidance on truncation lengths is probably the number-one question we get, so this could be really useful to people.

Todo for me: Test on a few datasets, including V3V4, V4V5 and V1V3.

**Comment by benjjneb** [comment]
Added a mention and linkout to Figaro under an "Extensions" box in the `filterAndTrim` section.

**Comment by michael-weinstein** [comment]
Thanks.  I just taught the DADA2 pipeline in a UCLA workshop.  I will be adding a feature to the program to automatically output a set of trimming parameters that can be directly pasted into the R command and will include a leftTrim based upon the given primer lengths to ensure it is not forgotten.
