### ISSUE TITLE
Low taxonomic resolution ITS

### ISSUE THREAD

**Issue by k-vincent** [benjjneb/dada2#808]
I'm getting really low taxonomic resolution with my ITS dataset and am reaching out to see if someone might have ideas on how to increase it. I've searched through related issues and can't seem to figure out what is going on with my data. Thanks in advance for any help/ advice! 

Issue: only ~58% of the ASVs are identified to Phylum; some of the top ten most abundant aren't identified below Kingdom. Also, weirdly many of the sequences with poor resolution don't have a significant match in BLAST. 

Here is a truncated sample of the table with assigned taxonomy and sequences: (https://docs.google.com/spreadsheets/d/1NP8ZMLX9vwQAib8V5VpLua8YcH-_0xpGUPD0fkmTxI4/edit?usp=sharing)

Database: UNITE database, "sh_general_release_dynamic_02.02.2019.fasta" 
Environment: high elevation freshwater lakes (~3,000m USA). I suppose it's possible that these taxa are simply not worked out yet, but it still seems awfully low.
2x250bp 
Primers: ITS1-F and ITS2 
filtering settings: maxEE = c(1, 1), truncQ = c(10, 10) and trimLeft = c(25, 25), trimRight = c(30, 50), minLen = 50
primers removed with cutadapt and chimeras removed with removeBimeraDenovo

pre-filtering quality plot- 
forward reads
![F_prefilt_qualplots](https://user-images.githubusercontent.com/52165980/61090022-4cf84000-a3fa-11e9-8b8a-4e34bdd3d540.png)

reverse reads
![R_prefilt_qualplots](https://user-images.githubusercontent.com/52165980/61090036-5da8b600-a3fa-11e9-9fb3-16ccdb0a43b0.png)

post-filtering quality plot- 
forward reads
![F_postfilt_qualplots](https://user-images.githubusercontent.com/52165980/61090133-b0826d80-a3fa-11e9-9761-e1584772b4bb.png)

reverse reads
![R_postfilt_qualplots](https://user-images.githubusercontent.com/52165980/61090422-d0fef780-a3fb-11e9-8337-918aafcc1b66.png)

Error rates- forward reads
![errF](https://user-images.githubusercontent.com/52165980/61090435-da885f80-a3fb-11e9-8177-aa567ab75fab.png)

Tracking reads through pipeline: 
![Tracking Reads](https://user-images.githubusercontent.com/52165980/61085676-187e8700-a3ee-11e9-85f0-3389c5812276.png)

Let me know what other information would be helpful. The help is much appreciated.

**Comment by benjjneb** [comment]
Have you tried `assignTaxonomy(..., tryRC=TRUE)`? That will help if some of the ASVs are in the reverse complement orientation, which happens with some kinds of library preps.

> Also, weirdly many of the sequences with poor resolution don't have a significant match in BLAST.

If that's the issue, then it's a data quality problem not an algorithm problem. ASVs with no match in BLAST are probably artefacts of some sort.

**Comment by k-vincent** [comment]
Thanks for the response, @benjjneb. Much appreciated. 
I did run assignTaxonomy with tryRC = TRUE, alas. 
Would you recommend filtering out more reads by increasing truncQ to get rid of artifacts, or might you have other tricks up your sleeve? Thanks again.

**Comment by benjjneb** [comment]
> How would you best recommend to get rid of artifacts? Can I lower maxEE below 1, or increase truncQ, or might you have other tricks up your sleeve?

I don't think the issue here is going to be solved by quality filtering. My guess is that these are high quality sequence reads, but the sequences themselves are artefacts of some sort.

Another thing you can try is to inspect the distribution of sequence complexities to determine if you have issues with low-complexity sequences. Try `hist(seqComplexity(seqtab), 100)` and see what the distribution looks like. You can also use `plotComplexity` on your initial files as well.

If low-complexity infiltration isn't the culprit, then you can also just remove the ASVs that don't assign to expected phylogenetic groups (e.g. don't assign to `Fungi` or don't assign past the Phylum level). That effectively removes sequences that are far away from the ITS database.

**Comment by k-vincent** [comment]
Thanks so much, @benjjneb. 
Here is what I get with hist(seqComplexity(seqtab), 100): 
![complexity_plot](https://user-images.githubusercontent.com/52165980/61185878-72b05f80-a61b-11e9-9922-139abe0565d2.png)

What am I expecting if I have an issue with low-complexity sequences?

**Comment by benjjneb** [comment]
> I am not seeing a bimodal distribution. Does that mean there isn't an issue with low-complexity?

Yeah, that plot is not showing evidence of a significant role for low complexity sequences.

I would probably proceed with excluding sequences that don't get assigned to anything (either at Kingdom or Phylum level) in UNITE then.

**Comment by k-vincent** [comment]
Thanks so much for your time and suggestions. I really appreciate it.
