### ISSUE TITLE
Error in taxa assignment

### ISSUE THREAD

**Issue by Jasmine84** [benjjneb/dada2#809]
Hello

I have a problem with this code in taxa assignment:
taxa <- assignTaxonomy(seqtab.nochim_test, "L:/LovbeskyttetMapper/Microbiom/Data first run/Eye_project_1_2PCR-137933803/Test/silva_nr_v132_train_set.fa.gz", multithread=TRUE)
Error in tax[[1]] : subscript out of bounds

Looking into the other issues: one solution could be to exclude samples with low abundance. I tried to only include 4 samples with 423 merged reads (earlier 118 samples) but I got the same error. Another solution is to upgrade DADA2, but I have 1.12.1 version.

Can you help me to solve the above issue?

Best regards,
Jasmine

**Comment by benjjneb** [comment]
What is the output you get when you run the following?

```
dim(seqtab.nochim_test)
summary(colSums(seqtab.nochim_test))
sample(getSequences(seqtab.nochim_test), 10)
```

**Comment by Jasmine84** [comment]
![image](https://user-images.githubusercontent.com/52818733/61201510-0ac64b80-a6e5-11e9-96b7-d48f28be3c01.png)

**Comment by benjjneb** [comment]
Hmm... that all looks normal.
Can you share the 4-sample seqtab that is causing this error with me?
My email is benjamin DOT j DOT callahan AT gmail DOT com

**Comment by Jasmine84** [comment]
Hello again

The Decipher method worked on my data. So I am sticking to that method in stead. 
Thanks for the help!

Best regards, Jasmine

**Comment by AMCMC** [comment]
I ran into this error today and was able to trace it to a corrupted database file.
