### ISSUE TITLE
Grouping samples collected from different body sites and stored the same FASTQ folder

### ISSUE THREAD

**Issue by nasiegel88** [benjjneb/dada2#810]
My microbiome samples are collected from the lung and the mouth. I am having trouble running the analysis using dada2 with both sample groups being analyzed at the same time.  When I sort by forward and reverse reads (as in the dada2 pipeline) I notice that samples have the same taxa present at the same abundance.

# Sort FASTQ files
```
fnRs <- sort(list.files(path, pattern = "_1.fastq", full.names = TRUE))
fnFs <- sort(list.files(path, pattern = "_2.fastq", full.names = TRUE))
```
![image](https://user-images.githubusercontent.com/50184544/61177507-1c481000-a58c-11e9-80d4-3ea8786d6207.png)

This output seems completely incorrect.

When I sort the groups individually (i.e. by BAL(bronchial alveolar lavage) and oral) I get abundances that make much more sense.

# Sorting FASTQ files by BAL
```
fnRs <- sort(list.files(path, pattern = "BAL_1.fastq", full.names = TRUE))
fnFs <- sort(list.files(path, pattern = "BAL_2.fastq", full.names = TRUE))
```
# Taxa abundance in the lung
![image](https://user-images.githubusercontent.com/50184544/61177534-bdcf6180-a58c-11e9-9e27-20f4cdc44fa8.png)

# Sorting FASTQ files by Mouth
```
fnRs <- sort(list.files(path, pattern = "Swab_1.fastq", full.names = TRUE))
fnFs <- sort(list.files(path, pattern = "Swab_2.fastq", full.names = TRUE))
```
# Taxa abundance in the mouth
![image](https://user-images.githubusercontent.com/50184544/61177548-0d159200-a58d-11e9-9a66-526abb8b7610.png)

Is there a way to build a data frame using dada2 and phyloseq that will accurately compare the difference in abundance and taxa between these two samples groups?

Thank you in advance,

Noah

**Comment by benjjneb** [comment]
Were these different runs? That is very weird the results you are getting at first.

It seems like when you run the BAL and mouth samples separately things turn out appropriately, so maybe just do that? You can combine them into a common phyloseq object afterwards using the `merge_phyloseq` function: https://joey711.github.io/phyloseq/merge.html

**Comment by nasiegel88** [comment]
They are from different runs. Do you think it may have something to do with the amount of bacterial content collected at sites? Is it possible, for example, that there were more bacteria collected in the mouth than in the lung and because of this the results for abundance comes back weird?

When looking at the graphs side by side and with samples being run through the pipeline at the same time there is a slight difference in the outputs. The difference can be observed slightly in sample 43880.

![image](https://user-images.githubusercontent.com/50184544/61178223-65549000-a59d-11e9-9f16-c011b313520b.png)
![image](https://user-images.githubusercontent.com/50184544/61178225-6980ad80-a59d-11e9-841d-2f3ec1a5bac6.png)

I am trying to get the abundance graphs on the same graph for easy comparison between collection sites. Should I only be merging otu tables to keep the different samples separate during the analysis?

**Comment by benjjneb** [comment]
If they are different runs, you should do the dada2 processing on each run individually. This is because the error profiles are often different between runs.

After dada2 processing, you can then merge them together into one phyloseq object. But processing different runs, especially those that may have also had different PCR amplification parameters, is not a good idea with dada2, as those runs will have a different rate and type of errors.

**Comment by nasiegel88** [comment]
Alright, thank you!
