### ISSUE TITLE
Sample inference error

### ISSUE THREAD

**Issue by megan-h** [benjjneb/dada2#814]
Hi, I am running through the DADA2 tutorial with my 16S data. It has worked up to and including learnErrors and plotErrors, but when I run dadaFs I get the following:

> dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
Error in dada(filtFs, err = errF, multithread = TRUE) : 
  The derep argument must be a derep-class object or list of derep-class objects.

I am not sure what I am doing wrong. Any suggestions? Thank you
Megan

**Comment by benjjneb** [comment]
As of package version 1.12 the `dada` command works directly with filenames. However, this didn't work prior to 1.12.

So, you should either upgrade to the most recent release of dada2 (https://benjjneb.github.io/dada2/dada-installation.html) or use the version of the tutorial corresponding to earlier packages versions, e.g. [tutorial version 1.8](https://benjjneb.github.io/dada2/tutorial_1_8.html).

**Comment by megan-h** [comment]
Ah, thank you! This worked. Much appreciated.
