### ISSUE TITLE
sample inference error: object qmax not found when USE_QUALS=FALSE

### ISSUE THREAD

**Issue by nextgenusfs** [benjjneb/dada2#816]
I'm getting an error during sample inference and not quite sure why.  This is a script I've used for awhile in my `amptk` package to run dada2, just created a new Conda environment and in my tests I keep getting the following error:
```
dadaSeqs <- dada(derepSeqs, err=NULL, selfConsist=TRUE, pool=FALSE, HOMOPOLYMER_GAP_PENALTY=-1, BAND_SIZE=32, USE_QUALS=FALSE, multithread=1)
Error in matrix(1, nrow = 16, ncol = max(41, qmax + 1)) : 
  object 'qmax' not found
```
However, if I change the call to `USE_QUALS=TRUE` then it completes.  Did something change in more recent versions?  Should I be using `USE_QUALS=TRUE`??  I don't recall why I had set it to FALSE.  This is what we had for Ion Torrent data, so perhaps that was why?  But these options were something @benjjneb you helped with more than a year ago (maybe 2 years!) when we were initially looking at fungal ITS data.

**Comment by benjjneb** [comment]
I would recommend `USE_QUALS=TRUE` for Ion Torrent data now. 

We had older guidance to set that to false for pyrosequencing data, but we've updated our recommendation there. If you do want to use an error model that ignores quality scores, we recommend instead providing `errorEsimationFunction=noqualErrfun` as an argument.

It looks like this is a bug though. There was an update in how maximum quality scores were handled in the last release which seems to have broken `USE_QUALS=FALSE`.

**Comment by nextgenusfs** [comment]
Okay thanks for the quick reply, appreciated!

**Comment by benjjneb** [comment]
Note to self, I think I'm going to deprecate `USE_QUALS=FALSE` in favor of the `noqualErrfun` approach, as that is easier to support.

**Comment by nextgenusfs** [comment]
So for future compatibility, should I just remove `USE_QUALS=TRUE` from the `dada2` call?  I'm assuming that is now the default and so no reason to explicitly declare it?

**Comment by benjjneb** [comment]
Yep that makes sense.
