### ISSUE TITLE
Error in dada(filtFs, err = errF, multithread = TRUE) : 

### ISSUE THREAD

**Issue by nbutyrate** [benjjneb/dada2#819]
Hi i am following this  tutorial

https://benjjneb.github.io/dada2/tutorial.html

and getting following error

dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
Error in dada(filtFs, err = errF, multithread = TRUE) : 
  The derep argument must be a derep-class object or list of derep-class objects.

please let me know if you need further information

**Comment by benjjneb** [comment]
You'll need to update to version 1.12 of the dada2 R package (the current release) to run version 1.12 of the tutorial. Alternatively there are links to previous versions of the tutorial at the top of the tutorial that will work with whatever older package version you currently have.
