### ISSUE TITLE
seqtab.nochim modifications

### ISSUE THREAD

**Issue by miguensblanco** [benjjneb/dada2#820]
Hi! More than an issue is a question due to my ignorance. I have finish to run DADA2 an I would like to make a tree using phangorn package but before I need to get the sequences from seqtab.nochim using DECIPHER package. My issue is that I want to make different trees (different tissues in the sequencing run), but if I downloaded and modify seqtab.nochim (taking off the samples I do not need) when I try to upload the dataset again I get again and again the message:
```
_Error in getUniques(object, collapse = collapse, silence = silence) : 
  Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns_
```
There is an alternative or better way to get the sequences from my modify seqtab.nochim file and create the tree, I normally do the tree with phangorn package. 

If not the alternative is select the samples before and run three different times DADA2 and later on make the trees, but this would take a long time.

Sorry if it is a silly question, but I did not find a similar question among the issues and thank you very much!

**Comment by benjjneb** [comment]
How are you removing samples from `seqtab.nochim`?

If you are doing this in R (i.e. by removing the rows corresponding to the samples you want to remove) everything should continue working as expected. Are you removing samples in an outside program or via some other means?

**Comment by MeghannThai** [comment]
Hi @miguensblanco,

You need to remove the sample name column prior to re-uploading the data. Your mapping file should have your sample names and will readd the sample names back into the `data.frame`. 
```
seqtab <- read.csv2("sequence table file location", header = TRUE, sep = ",", fill = TRUE)
rownames(seqtab) <- Maps$X.SampleID
```
Then convert the `data.frame` into a `matrix` using;
```
seqtab.matrix <- as.matrix(seqtab)
```
From there, you should be able to continue with `getSequences`

Hope this helps,
Kind Regards,
Meghann

**Comment by miguensblanco** [comment]
Sorry guys, I am having trouble with the server and I cannot follow your answers (I just write this to thanks your answers). As Benjamin suggests I was removing the columns on Excel and when I upload again the file it is when I got the problem. I suppose that if I do it on R should work, hopefully I can try today or tomorrow.

Thank you guys, 

Jesus

**Comment by benjjneb** [comment]
@miguensblanco 

In R, matrices are addressed in this format: `mymat[rows, cols]`.
So the command you gave is confusing R, because you didn't tell it whether rows or columns were being addressed since there is no comma.
To remove certain rows, what you want is: `seqtab.nochim <- seqtab.nochim[-c(50,65,67),]`
Just an added comma, but makes all the difference!

**Comment by miguensblanco** [comment]
And all the difference was made, I totally bypass the columns issue. Sorry about that and thanks a lot!
