### ISSUE TITLE
Mapping file on dada2 from Ion torrent files

### ISSUE THREAD

**Issue by venturajoao** [benjjneb/dada2#822]
Hi! 
I’m trying use the Dada2 to process My seqs from ION Torrent (format fastq, single read, one file fastq ). 
So I can not identify which seqs  came from the sample by the barcodes identification. Is it possible do this on dada2?  
Thank a lot!

**Comment by benjjneb** [comment]
Are the reads split into fastq files for each sample already? (i.e. "demultiplexed").

If not., you will need to do that with some outside software program. If so, you can use the dada2 pipeline as is.
