### ISSUE TITLE
Starting with merged reads

### ISSUE THREAD

**Issue by ttanvitaparia** [benjjneb/dada2#823]
Hello,

I am aware that the dada2 workflow starts with demultiplexed and unmerged reads. However, I have some older amplicon sequenced data, from which the raw reads are not available anymore. So I only have merged reads archived. Is is possible to use the ASV approach in this case?

**Comment by benjjneb** [comment]
You can, but you will be prone to more false-positive ASVs in this case unless they were completely overlapping reads (e.g. V4 2x250).
