### ISSUE TITLE
Duplicate sequences 

### ISSUE THREAD

**Issue by Jasmine84** [benjjneb/dada2#825]
Hello

I have a problem with duplicate sequences when running DADA2. There is no error, I just receive the message when running DADA2. When I look at the taxonomy I wonder if something has gone wrong with which sequences belonging to which sample, as it does not make sense that some of the bacteria in the control samples, also appear in the "real" samples. Where should I look for solutions to this problem? I was thinking about the reads being to long as mentioned in another issue or with primer still on. I am going to try trimming at 30-250. I am using V3-V4 16S region. 

Thanks fpr the help in advance!
Best regards,
Jasmine

**Comment by benjjneb** [comment]
At which step do you get the message that duplicate sequences were detected?
Can you post the exact command that produces that message?

**Comment by Jasmine84** [comment]
It was at:
>seqtab <- makeSequenceTable(mergers)
Duplicate sequences detected and merged

**Comment by benjjneb** [comment]
This isn't necessarily a problem, as the duplicate merged sequences are being combined at that step. We usually don't see this message from Illumina data though, at least when running the tutorial pipeline. Did you have any non-standard steps, such as allowing mismatches during merging, or running some quality trimming program on your sequences prior to DADA2?
