### ISSUE TITLE
dada2 input files

### ISSUE THREAD

**Issue by Nuisance33** [benjjneb/dada2#826]
Can you use dada2 to generate an ASV table from fasta (.fa) files?

**Comment by benjjneb** [comment]
We don't recommend it, as the quality scores provide important information about the likelihood of errors.

If you must, you can run a fasta file through dada2. Replace `derepFastq` with `dada2:::derepFasta`, and when calling `learnErrors` and `dada`, include the argument `errorEstimationFunction=noqualErrfun`.

**Comment by Nuisance33** [comment]
Thanks!
