### ISSUE TITLE
mergeSequenceTables - only taking info from the first table 

### ISSUE THREAD

**Issue by alices0701** [benjjneb/dada2#827]
Hello I am trying to merge 4 sequence tables together (V4 region, same filtering parameters used) but after using the mergeSequenceTables function the merged table is just a replicate of the first ASV table (st_A). 

Here is the script I used: 

library(dada2); packageVersion("dada2")
#run A 
path_A <- "/pathto/run_A" # CHANGE ME to the directory containing the fastq files after unzipping.
list.files(path_A)
# Forward and reverse fastq filenames have format: SAMPLENAME_R1_001.fastq and SAMPLENAME_R2_001.fastq
fnFs_A <- sort(list.files(path_A, pattern="_R1_001.fastqsanger", full.names = TRUE))
fnRs_A <- sort(list.files(path_A, pattern="_R2_001.fastqsanger", full.names = TRUE))
# Extract sample names, assuming filenames have format: SAMPLENAME_XXX.fastq
sample.names_A <- sapply(strsplit(basename(fnFs_A), "_"), `[`, 1)
plotQualityProfile(fnFs_A[7:8])
plotQualityProfile(fnRs_A[7:8])
# Place filtered files in filtered/ subdirectory
filtFs_A <- file.path(path_A, "filtered", paste0(sample.names_A, "_F_filt.fastq.gz"))
filtRs_A <- file.path(path_A, "filtered", paste0(sample.names_A, "_R_filt.fastq.gz"))
names(filtFs_A) <- sample.names_A
names(filtRs_A) <- sample.names_A
out_A <- filterAndTrim(fnFs_A, filtFs_A, fnRs_A, filtRs_A, truncLen=c(275,270), trimLeft=c(19,20),
                       maxN=0, maxEE=2, truncQ=2, rm.phix=TRUE,
                       compress=TRUE, multithread=FALSE, verbose=TRUE) 
head(out_A) 
errF_A <- learnErrors(filtFs_A, multithread=TRUE, verbose=TRUE)
errR_A <- learnErrors(filtRs_A, multithread=TRUE, verbose=TRUE)
plotErrors(errF_A, nominalQ=TRUE)
dadaFs_A <- dada(filtFs_A, err=errF_A, multithread=TRUE)
dadaRs_A <- dada(filtRs_A, err=errR_A, multithread=TRUE)
dadaFs_A[[1]]
mergers_A <- mergePairs(dadaFs_A, filtFs_A, dadaRs_A, filtRs_A, verbose=TRUE)
# Inspect the merger data.frame from the first sample
head(mergers_A[[1]])
seqtab_A <- makeSequenceTable(mergers_A)
dim(seqtab_A)
saveRDS(seqtab_A, "/pathto/seqtab_A.rds") 
# To view it in R
st_A <- readRDS("/pathto/seqtab_A.rds")

#run B
path_B <- "/pathto/run_B/"
list.files(path_B)
# Forward and reverse fastq filenames have format: SAMPLENAME_R1_001.fastq and SAMPLENAME_R2_001.fastq
fnFs_B <- sort(list.files(path_B, pattern="_R1_001.fastqsanger", full.names = TRUE))
fnRs_B <- sort(list.files(path_B, pattern="_R2_001.fastqsanger", full.names = TRUE))
# Extract sample names, assuming filenames have format: SAMPLENAME_XXX.fastq
sample.names_B <- sapply(strsplit(basename(fnFs_B), "_"), `[`, 1)
plotQualityProfile(fnFs_B[7:8])
plotQualityProfile(fnRs_B[7:8])
# Place filtered files in filtered/ subdirectory
filtFs_B <- file.path(path_B, "filtered", paste0(sample.names_B, "_F_filt.fastq.gz"))
filtRs_B <- file.path(path_B, "filtered", paste0(sample.names_B, "_R_filt.fastq.gz"))
names(filtFs_B) <- sample.names_B
names(filtRs_B) <- sample.names_B
out_B <- filterAndTrim(fnFs_B, filtFs_B, fnRs_B, filtRs_B, truncLen=c(275,270), trimLeft=c(19,20),
                       maxN=0, maxEE=2, truncQ=2, rm.phix=TRUE,
                       compress=TRUE, multithread=FALSE, verbose=TRUE) 
head(out_B) 
errF_B <- learnErrors(filtFs_B, multithread=TRUE, verbose=TRUE)
errR_B <- learnErrors(filtRs_B, multithread=TRUE, verbose=TRUE)
plotErrors(errF_B, nominalQ=TRUE)
dadaFs_B <- dada(filtFs_B, err=errF_B, multithread=TRUE)
dadaRs_B <- dada(filtRs_B, err=errR_B, multithread=TRUE)
dadaFs_B[[1]]
mergers_B <- mergePairs(dadaFs_B, filtFs_B, dadaRs_B, filtRs_B, verbose=TRUE)
# Inspect the merger data.frame from the first sample
head(mergers_B[[1]])
seqtab_B <- makeSequenceTable(mergers_B)
dim(seqtab_B) 
saveRDS(seqtab_B,"/pathto/run_B/seqtab_B.rds") 
# To view it in R
st_B <- readRDS("/pathto/run_B/seqtab_B.rds")

#run C
path_C <- "/pathoto/run_C" 
list.files(path_C)
# Forward and reverse fastq filenames have format: SAMPLENAME_R1_001.fastq and SAMPLENAME_R2_001.fastq
fnFs_C <- sort(list.files(path_C, pattern="_R1_001.fastqsanger", full.names = TRUE))
fnRs_C <- sort(list.files(path_C, pattern="_R2_001.fastqsanger", full.names = TRUE))
# Extract sample names, assuming filenames have format: SAMPLENAME_XXX.fastq
sample.names_C <- sapply(strsplit(basename(fnFs_C), "_"), `[`, 1)
plotQualityProfile(fnFs_C[7:8])
plotQualityProfile(fnRs_C[7:8])
# Place filtered files in filtered/ subdirectory
filtFs_C <- file.path(path_C, "filtered", paste0(sample.names_C, "_F_filt.fastq.gz"))
filtRs_C <- file.path(path_C, "filtered", paste0(sample.names_C, "_R_filt.fastq.gz"))
names(filtFs_C) <- sample.names_C
names(filtRs_C) <- sample.names_C
out_C <- filterAndTrim(fnFs_C, filtFs_C, fnRs_C, filtRs_C, truncLen=c(275,270), trimLeft=c(19,20),
                       maxN=0, maxEE=2, truncQ=2, rm.phix=TRUE,
                       compress=TRUE, multithread=FALSE, verbose=TRUE) # On Windows set multithread=FALSE
head(out_C) 
errF_C <- learnErrors(filtFs_C, multithread=TRUE, verbose=TRUE)
errR_C <- learnErrors(filtRs_C, multithread=TRUE, verbose=TRUE)
plotErrors(errF_C, nominalQ=TRUE)
dadaFs_C <- dada(filtFs_C, err=errF_C, multithread=TRUE)
dadaRs_C <- dada(filtRs_C, err=errR_C, multithread=TRUE)
dadaFs_C[[1]]
mergers_C <- mergePairs(dadaFs_C, filtFs_C, dadaRs_C, filtRs_C, verbose=TRUE)
# Inspect the merger data.frame from the first sample
head(mergers_C[[1]])
seqtab_C <- makeSequenceTable(mergers_C)
dim(seqtab_C)
saveRDS(seqtab_C, "/pathto/run_C/seqtab_C.rds") 
# To view it in R
st_C <- readRDS("/pathoto/run_C/seqtab_C.rds")

#run D
path_D <- "/pathoto/run_D" 
list.files(path_D)
# Forward and reverse fastq filenames have format: SAMPLENAME_R1_001.fastq and SAMPLENAME_R2_001.fastq
fnFs_D <- sort(list.files(path_D, pattern="_R1_001.fastqsanger", full.names = TRUE))
fnRs_D <- sort(list.files(path_D, pattern="_R2_001.fastqsanger", full.names = TRUE))
# Extract sample names, assuming filenames have format: SAMPLENAME_XXX.fastq
sample.names_D <- sapply(strsplit(basename(fnFs_D), "_"), `[`, 1)
plotQualityProfile(fnFs_D[7:8])
plotQualityProfile(fnRs_D[7:8])
# Place filtered files in filtered/ subdirectory
filtFs_D <- file.path(path_D, "filtered", paste0(sample.names_D, "_F_filt.fastq.gz"))
filtRs_D <- file.path(path_D, "filtered", paste0(sample.names_D, "_R_filt.fastq.gz"))
names(filtFs_D) <- sample.names_D
names(filtRs_D) <- sample.names_D
out_D <- filterAndTrim(fnFs_D, filtFs_D, fnRs_D, filtRs_D, truncLen=c(275,270), trimLeft=c(19,20),
                       maxN=0, maxEE=2, truncQ=2, rm.phix=TRUE,
                       compress=TRUE, multithread=FALSE, verbose=TRUE) # On Windows set multithread=FALSE
head(out_D) 
errF_D <- learnErrors(filtFs_D, multithread=TRUE, verbose=TRUE)
errR_D <- learnErrors(filtRs_D, multithread=TRUE, verbose=TRUE)
plotErrors(errF_D, nominalQ=TRUE)
dadaFs_D <- dada(filtFs_D, err=errF_D, multithread=TRUE)
dadaRs_D <- dada(filtRs_D, err=errR_D, multithread=TRUE)
dadaFs_D[[1]]
mergers_D <- mergePairs(dadaFs_D, filtFs_D, dadaRs_D, filtRs_D, verbose=TRUE)
# Inspect the merger data.frame from the first sample
head(mergers_D[[1]])
seqtab_D <- makeSequenceTable(mergers_D)
dim(seqtab_D)
saveRDS(seqtab_D, "/pathto/seqtab_D.rds") 
# To view it in R
st_D <- readRDS("/pathto/run_D/seqtab_D.rds")

# merge sequencing runs 
st.all <- mergeSequenceTables(st_A,st_B,st_C,st_D)

Any advice would be greatly appreciated, thanks in advance!

Alice

**Comment by rachaelantwis** [comment]
Hi Alice, how did you manage to solve this? I've created three sequence tables on a server and I need to merge them. I've exported them as rds objects and imported these into the local R environment, and now I need to merge them. Many thanks in advance

**Comment by benjjneb** [comment]
@rachaelantwis Did you try using the `mergeSequenceTables` function?

**Comment by rachaelantwis** [comment]
Hi Ben, thanks for the reply. I have got it working now thanks. I got a bit confused by the ?mergeSequenceTables guidance and used:
seqtab <- mergeSequenceTables(table1 = seqtab1, table2 = seqtab2, table3 = seqtab3)

But I see I needed to use
seqtab <- mergeSequenceTables(seqtab1, seqtab2, seqtab3)

I’m just trying to track down a computer with enough power to run it now!

Many thanks
