### ISSUE TITLE
##What to do with bad sequencing results?

### ISSUE THREAD

**Issue by mcamarareis** [benjjneb/dada2#828]
I'm a new dada2 user and I've been struggling with 2 datasets 2x300 amplified using primers 27F and 519R. The samples are from microbiome of algal cultures.
The reverse reads are quite bad quality, but I cannot trim too much without loosing overlap.
Example of quality profiles here:

[quality_profile_R2.pdf](https://github.com/benjjneb/dada2/files/3510740/quality_profile_R2.pdf)
[quality_profile_R1.pdf](https://github.com/benjjneb/dada2/files/3510741/quality_profile_R1.pdf)

I've managed to merge my reads using the following parameter for filtering:

out=filterAndTrim(fwd=file.path(pathF, fastqFs), filt=file.path(filtpathF, fastqFs), rev=file.path(pathR, fastqRs), filt.rev=file.path(filtpathR, fastqRs), trimLeft =c(20,18), truncLen=c(280,275), maxEE=c(5,5), truncQ=0, maxN=0, rm.phix=TRUE, compress=TRUE, verbose=TRUE, multithread=FALSE)

But, at the end of the pipeline I had 31% of the initial number of reads for one dataset and 51% for the other one. 
The number of reads at each step were:

               | Input reads | Filtering | Denoising | Chimera removal
dataset1    | 7796277 | 4577903 | 3782421 | 2460444
dataset2   | 16527704 | 12539345 | 11712760 | 8575743

But, even loosing so many reads, I still have a reasonable number of reads to work on (46000 in average). 

I run also the pipeline using just the forward reads, which keep 80% of the initial number of reads (in average 134000 per sample)

I this case I trimmed the left to remove the primer (20nt) and the last 30 nt to remove bad quality tail.

My question is: Which solution would be the best one?
The first one, where I loose many reads, but I still have more then enough to analyze or the second one, where I keep a lot of reads but I use genetic information coming from only 250 nt?

Thank you in advance!

**Comment by benjjneb** [comment]
Using just forward reads, or pushing forward with the merged reads and accepting the higher numbers you will lose through the pipeline. I am slightly concerned with the high chimera fraction you are detecting (almost 30%), but that is on the boundary of what is seen normally.

Is there a critical need for you to keep the full V1V3 amplicon? For example, does the V3 region provide discrimination of certain important taxa that you don't get with V1V2?

If not, I'd go with just the forward reads myself.

**Comment by mcamarareis** [comment]
Thank you very much for your prompt answer.

The number of reads is not a main issue for me, since I keep a reasonable number for both datasets.
My main concern is if I push too much to be able to merge and I end up with bad quality results.

I'll use these results to compare microbiomes from different organisms coming from different datasets. Since I have different sets of primers for some of the datasets, I'll process them separately using dada2 then classify taxonomy using vsearch and work with taxonomic information. I'm aware that this will make me loose the resolution of ASVs but otherwise I have no way to compare them (the primers do not overlap). I've performed procrustes analysis to be sure that the ASV table and the taxonomic information table are correlated.

So it seems to me that would be better to keep as most information as I can (which means using forward and reverse reads) since I'll already have this drop in resolution at the end. But again, I want to be sure that I can trust in the results that I obtain using both reads.

I would like to hear your opinion about that. 
Thank you again.

**Comment by benjjneb** [comment]
Merged sequences will gain some taxonomic resolution over just the forward reads, but less than you might think: it will mostly give the same results except for certain families/genus that are particularly variable in the V3.

Merged seuqences will lose some sensitivity to rarer taxa, both by having lower read numbers but also by having higher total error rates over the whole merged read, which makes it harder to detect low-frequency stuff, but the moderate to high frequency stuff should be detected just the same.

So, I think you just have to choose which you care more about, higher tax resolution in some bacterial Families, or higher sensitivity to rarer variants, and go with the appropriate approach.

In all likelihood, given what you've described either way will work well though.

**Comment by mcamarareis** [comment]
Hi, 
Thank you very much, that was a very clear explanation. Now everything makes more sense to me.

Just a last question, actually in one of the datasets I had a chimera detection of 34% (dataset1). I've checked if any primer sequence was left, but actually the sequences already came without primers. 
Is there any other possible reason for this high loss as chimera?

**Comment by benjjneb** [comment]
> Just a last question, actually in one of the datasets I had a chimera detection of 34% (dataset1). I've checked if any primer sequence was left, but actually the sequences already came without primers.
> Is there any other possible reason for this high loss as chimera?

I'm not sure. The one thing I would check is whether adjusting the `minFoldParentOverabundance` parameter makes a large difference. We think that the consensus approach works pretty well, but there has been some literature suggesting that the default value of `minFoldParentOverAbundance=2` could be too low in some circumstances, so try changing that to something like 8 and see what the results are like. If it's still a high fraction of chimeric reads, i think you just go with the data.
