### ISSUE TITLE
stack imbalance warning with fastqPairedFilter

### ISSUE THREAD

**Issue by johnchase** [benjjneb/dada2#83]
I am receiving a stack imbalance warning when running `fastqPairedFilter`. I am running this with the tutorial data and the tutorial commands. Everything seems to work fine other than the warning. I have tried reinstalling dada2 with no luck. 

```{r}
for(i in seq_along(fnFs)) {
     fastqPairedFilter(c(fnFs[i], fnRs[i]), c(filtFs[i], filtRs[i]),
                       trimLeft=c(10, 10), truncLen=c(240,160),
                       maxN=0, maxEE=2, truncQ=2,
                       compress=TRUE, verbose=TRUE)
 }

Warning: stack imbalance in '.Call', 133 then 132
Warning: stack imbalance in '<-', 131 then 130
Warning: stack imbalance in '{', 128 then 127
```
R version 3.2.5 (2016-04-14)
DADA2 1.1.1
Ubuntu 12.04.2 LTS

**Comment by benjjneb** [comment]
Hi John,
I haven't seen this error before, and I suspect it may have to do with compiler differences. Could you test whether turning off the openMP multi-threading in the filtering function eliminates this warning?

```
nthreads <- .Call(ShortRead:::.set_omp_threads, 1L)
# Offending code
.Call(ShortRead:::.set_omp_threads, nthreads))
```

**Comment by johnchase** [comment]
@benjjneb This morning I realized that this warning is not always generated, running it with the default workflow on a small dataset generates the error ~50% of the time.  

Running the code with openMP multi-threading turned off I have not seen the error after re-running the code 15 or so times. 

Sounds like this is a good workaround for the time being?

Thanks

**Comment by benjjneb** [comment]
@johnchase Yes that's what I recommend for now.

The fastq file input is the one major part of the codebase that relies on an outside implementation, and there are some known issues with openMP and R that can crop up depending on platform/compiler.

Long-term I'd like to write our own streaming fastq input function, but for now this workaround should avoid this problem.

**Comment by benjjneb** [comment]
Please re-open if this problem crops up again, but going to close it as solved by the workaround for now.
