### ISSUE TITLE
inference on derelicated reads or filtered reads

### ISSUE THREAD

**Issue by naarkhoo** [benjjneb/dada2#834]
I am curious which one is recommended

```
dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
dadaRs <- dada(filtRs, err=errR, multithread=TRUE)

dadaFs <- dada(derepFs, err=errF, multithread=TRUE)
dadaRs <- dada(derepRs, err=errR, multithread=TRUE)
```

where 

```
derepFs <- derepFastq(filtFs, verbose=TRUE)
derepRs <- derepFastq(filtRs, verbose=TRUE)
```

**Comment by benjjneb** [comment]
They will give identical results. 

`dada(filtFs,...)` will require less memory, as it only loads on sample into memory at a time.
`derepFastq(filtFs,...); dada(derepFs,...)` gives a bit more diagnostic information on the fraction of unique sequences to total reads.

I usually just use `dada(filtFs,...)` to avoid any memory issues, it lets you process huge datasets with little memory requirement (just need enough memory to load the largest sample into memory).
