### ISSUE TITLE
R crashes when using removeBimeraDenovo function

### ISSUE THREAD

**Issue by HBAMBER** [benjjneb/dada2#835]
I am using this DADA2 Pipeline tutorial for the first time: https://benjjneb.github.io/dada2/tutorial.html

I am a complete novice (MSc biotechnology student) learning to conduct a microbiota analysis using DADA2 in R, and then Phyloseq.

I have trimmed and filtered my fastq data, learned the error rates, applied the core sample inference algorithm to the filtered and trimmed sequence data, merged the paired reads...

However, after constructing the sequence variant table, I try to remove chimeras using this input:

seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
dim(seqtab.nochim)
R crashes every time.

I have never used any coding software before. This is my first attempt at writing code.

I really would appreciate simplified and overly informative answers.

Thank you!

**Comment by benjjneb** [comment]
Thanks for the report. Can you give us a bit more information by running the commands below, and posting their output?

```
library(dada2); packageVersion("dada2")
dim(seqtab)
summary(nchar(getSequences(seqtab)))
```

Also, what OS are you using? And did you try running `removeBimeraDenovo(..., multithread=FALSE)` to check if multithreading could be a culprit?
