### ISSUE TITLE
normalize seqtable

### ISSUE THREAD

**Issue by bashma** [benjjneb/dada2#84]
Hi all,
In the [tutorial](http://benjjneb.github.io/dada2/tutorial.html) you input  taxa and seqtab.nochim to phyloseq without prior normalization/subsampling. Does that mean that we don't need to normalize the output files before analysis?

best, Mina

**Comment by joey711** [comment]
@bashma 

Definitely not. This would be structuring your analysis workflow to throw away information. Any transformation, normalization should be done in a way that it is easy to substitute and reproduce. The phyloseq package already provides many means for transforming your data as-needed.

You mentioned "subsampling". AKA rarefying. Don't do that, especially not upstream of the documented part of your analysis workflow. But anyway, there's no need to rarefy. DADA2 actually does a pretty good job addressing one of the major artifacts the motivates people to rarefy in the first place -- spurious OTUs resulting in richness that is strongly correlated to sequence depth. This effect is much attenuated in DADA2 output for a lot of datasets I've looked at, and in these cases, rarefying would then just be a noisy, badly-principled version of relative abundance with a dollop of minimum value filtering.

See [Waste Not, Want Not: Why Rarefying Microbiome Data Is Inadmissible](http://dx.doi.org/10.1371/journal.pcbi.1003531) for some helpful further details on why you shouldn't be doing the subsampling...

**Comment by benjjneb** [comment]
@bashma 

The handoff to phyloseq in the tutorial is just meant as a demonstration of how the data from dada2 can be easily moved into phyloseq. In your further analysis, you should normalize as appropriate.

As @joey711 mentioned, simply subsampling right off the bat is not the best approach, however.
