### ISSUE TITLE
Parsing step is not adapted to the idtaxa output.

### ISSUE THREAD

**Issue by tizioto** [benjjneb/dada2#840]
Dear all,

The parsing step seems to be not adapted to the DECIPHER idtaxa output.

Please see more details below:
I am trying to use DAIRYdb to IDTAXA in DADA2 pipeline as described here https://benjjneb.github.io/dada2/tutorial.html.

dna <- DNAStringSet(getSequences(seqtab.nochim))

load("~/DAIRYDB/DAIRYdb_v1.2.0_20190222_IDTAXA.RData") ##https://github.com/marcomeola/DAIRYdb

ids <- IdTaxa(dna, trainingSet, strand="both", processors=16, verbose=FALSE)
ranks <- c("type", "domain", "phylum", "class", "order", "family", "genus", "species")
taxid <- t(sapply(ids, function(x) {
m <- match(ranks, x$rank)
taxa <- x$taxon[m]
taxa[startsWith(taxa, "unclassified_")] <- NA
taxa
}))
colnames(taxid) <- ranks; rownames(taxid) <- getSequences(seqtab.nochim)

Please see how my ids object looks like:

head(ids)
A test set of class 'Taxa' with length 6
confidence name taxon
[1] 72.4% ASV_1 Root; Bacteria; Firmicutes; Bacilli; Lact...
[2] 96.9% ASV_2 Root; Bacteria; Proteobacteria; Gammaprot...
[3] 94.2% ASV_3 Root; Bacteria; Firmicutes; Bacilli; Lact...
[4] 98.4% ASV_4 Root; Bacteria; Actinobacteria; Actinobac...
[5] 97.1% ASV_5 Root; Bacteria; Proteobacteria; Gammaprot...
[6] 100.0% ASV_6 Root; Bacteria; Proteobacteria; Gammaprot...

Howerver, taxid is all NA´s for all levels.

Thank you
Best Regards,

Polyana Tizioto

**Comment by benjjneb** [comment]
@digitalwright Has the format of IDTaxa output changed recently in ways that might break the parsing above from the DADA2 tutorial?

@tizioto Can you provide the ids object that is failing to parse? Probably in RDS format: `saveRDS(ids, "ids.rds")`

**Comment by digitalwright** [comment]
@benjjneb The IDTaxa output format has not changed. Please provide the `ids` object and I will take a look.

**Comment by tizioto** [comment]
Dear all,

[ids.zip](https://github.com/benjjneb/dada2/files/3623786/ids.zip)
Thanks for the quick response.
Please find it attached

**Comment by digitalwright** [comment]
@tizioto The `ids` object that you provided was trained without rank level information (i.e., domain, phylum, etc.). Hence, indexing on `rank` does not work.

However, it looks like your `ids` have 8 fixed rank levels, so you can substitute `taxid <- ...` in your code above with:
`taxid <- t(sapply(ids, "[[", "taxon"))`

**Comment by tizioto** [comment]
@digitalwright  @benjjneb Thank you.
This work perfectly.
