### ISSUE TITLE
DADA2 and SAR11

### ISSUE THREAD

**Issue by KevPurves** [benjjneb/dada2#842]
(forwarded onto the GitHub Forum as requested)

Hello,

I've been using the DADA2 pipeline to analyse changes in the microbial community in coastal marine samples and have found that the relative abundance of SAR11 is significantly less (<1%) than it is typically reported to be in the same and other marine studies, and relative proportions of other groups seemed to be as expected. I initially assumed this could be a result of inter-annual variability at the sampling location. However, i have also used spare DNA samples from a past study where SAR11 has been determined to make up 11-24% of the community, but by using the DADA2 pipeline, i still find that SAR11 is still much less represented in sequences than i would expect it to be, so to me this indicates the difference is likely derived from the methodology*. SAR11 is potentially a very important bacterial group in my field, so this could be deal breaker if this pipeline isn't appropriate for some reason, which would be a shame.

So I was wondering if you know of any reason why there may be under-representation of certain bacterial groups in the community, such as SAR11, and if this could be a result of using this pipeline? Perhaps you've had similar reports previously? 

Kind regards,
Kevin

*Approach recommended by the Earth Microbiome Project (16S V4 and MiSeq etc.), where they specifically state that the primers have degeneracy added to mitigate known biases against SAR11.

**Comment by benjjneb** [comment]
The issue with metabarcoding/metagenomics in which different methodologies are differently sensitive to various taxa is a fundamental problem in the field, without a clear solution yet (see [our new paper on this here](https://elifesciences.org/articles/46923)).

My guess it that the issue that you are seeing is not computational, but is more likely at the wet lab stage. I know the EMP improved their primer set to better detect SAR11, but that doesn't mean it will detect it equally well as your previous method.

However, if you want to investigate the pipeline specifically, you could consider running one non-denoised sample through taxonomic assignment, even via another method like Kraken or something, and see if significantly more SAR11 shows up. If it does, then it indicates something is off in the pipeline, if not then its the wet lab side and not fixable by tweaking computational parameters.
