### ISSUE TITLE
Losing >50% of reads after removing chimeras, possibly due to issue with mergePairs

### ISSUE THREAD

**Issue by LijMeh** [benjjneb/dada2#843]
I’ve been having some issues analyzing my most recent data, I’ll try to include as much detail as possible below, but just let me know if there is anything else I should add. 

## Details:
* Reads are 300bp from a Mi-Seq v3 600 cycle
* Primers are 515F, 806R, amplicon should be ~390bp
* Read quality is mostly as expected, with some samples exhibiting significant drops, see below
* I'm trimming at 280 for F and R reads, I previously tried cutting the R reads down to 200, but then I lost most of them during `mergePairs` 

### Forward
<img width="1204" alt="Screen Shot 2019-09-19 at 10 44 02 AM" src="https://user-images.githubusercontent.com/50337970/65638533-2d08ff00-df9b-11e9-9941-e3947fd3c4f6.png">

### Reverse
<img width="1204" alt="Screen Shot 2019-09-19 at 10 49 25 AM" src="https://user-images.githubusercontent.com/50337970/65638570-401bcf00-df9b-11e9-8701-a9a7f45ba644.png">

## Issue:
When running `seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=FALSE, verbose=TRUE)` followed by `sum(seqtab.nochim)/sum(seqtab)` it looks like I am losing more than 50% of the reads (the output is `[1] 0.4513951`). Later on, most of my sequences are being categorized as `"Eukaryota" NA NA etc.` regardless of if I set `tryRC=TRUE` or not. 

I believe the issue might be caused during the `mergePairs` step, as the majority of my merged sequences are in the mid to high 400bp range (~440-480), and, if I’m understanding this correctly, they should be closer to the 390 that is the amplicon. 
<img width="683" alt="Screen Shot 2019-09-25 at 1 53 45 PM" src="https://user-images.githubusercontent.com/50337970/65638890-eb2c8880-df9b-11e9-8837-d7bda986c549.png">

**Comment by LijMeh** [comment]
I wasn’t the one who set up the PCR and sequencing for these samples, and I just learned that the primers might have actually been v3-v4 (341F/785R), which would explain the merged lengths and why they wouldn’t merge when they were trimmed more. I’m still not sure why I’m losing so many samples as chimeras though. 

(Thanks for the help and for taking the time to create/maintain this awesome program by the way)

**Comment by benjjneb** [comment]
>I wasn’t the one who set up the PCR and sequencing for these samples, and I just learned that the primers might have actually been v3-v4 (341F/785R), which would explain the merged lengths and why they wouldn’t merge when they were trimmed more. I’m still not sure why I’m losing so many samples as chimeras though.

Did you remove the primers? I.e. by adding `fastqPairedFilter(..., trimLeft=c(FWD_PRIM_LEN, REV_PRIM_LEN) or by using an outside program?

If not, then the primers will cause lots of reads to be removed as chimeras due to the ambiguous nucleotides in the primers.

**Comment by LijMeh** [comment]
Thanks, our sequencing facility usually removes the primers before sending us the sequences, but in this case it turns out they hadn't. I'll try running it again with them removed. 

Thanks for the help!

**Comment by LijMeh** [comment]
Ok, removing the primers worked, I was able to make it through the rest of the pipeline without loosing a huge amount of reads at any step, thanks so much!
