### ISSUE TITLE
Harmonizing OTU IDs of different runs from MICCA

### ISSUE THREAD

**Issue by CJD26** [benjjneb/dada2#844]
Hello,

I have been accumulating wheat rhizosphere microbiome data from different greenhouse experiments for the last two years. I did sequence processing and OTU-picking (Greengenes) in MICCA separately for each dataset over the years. Now we wanted to make a direct comparison of abundance of differential OTUs  among 6 different datasets but could not move forward because of different OTU IDs per run. Is there a way in R/pyhton to harmonize different OTU IDs accross different datasets linked to same Greengenes reference sequence without re-doing OTU picking of all datasets again in MICCA? 

Example:
>Greengenes_OTU3
AGAGTTTGATCCTGGCTCAG...........AG

>Dataset1_OTU1                      ----> Rename Dataset1_OTU1 to Greengenes_OTU3 in OTU table
AGAGTTTGATCCTGGCTCAG...........AG

>Dataset2_OTU2                     ----> Rename Dataset2_OTU2 to Greengenes_OTU3 in OTU table
AGAGTTTGATCCTGGCTCAG...........AG

 Thanks!

**Comment by benjjneb** [comment]
Are all these OTUs created by mapping the same way against the same database? If so, it may be possible, but why are the ID lines different then?

If you have a map of the differnt ID lines assigned in each dataset to the others, then you could combine them together, but is that available?

**Comment by CJD26** [comment]
Hi Benjamin,

The OTUs were picked via open reference method separately before for all 6
datasets using same database reference. I have OTUID file for each
individual which indicates which Reference OTU corresponds to which new OTU
name for each individual run. Though I can rename the OTU names across all
6 datasets for the reference OTUs, how can I harmonize the DENOVO OTUs? For
example, DENOVO OTU1 in Dataset1 might have same sequence as DENOVO OTU34
in Dataset2.

Thanks,
Jade

**Comment by benjjneb** [comment]
> how can I harmonize the DENOVO OTUs?

You can't. De novo OTUs are not directly comparable between differently processed datasets, because the way the algorithms group the sequences into OTUs is different in each dataset.
