### ISSUE TITLE
running dada2 missing output files

### ISSUE THREAD

**Issue by Devinaseeruttun** [benjjneb/dada2#845]
Got the following WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /Users/devina/16S-rDNA-dada2-pipeline/work/singularity
[1d/58298c] NOTE: Missing output file(s) `Dog29_fastqc/*.zip` expected by process `runFastQC (rFQC.Dog29)` -- Execution is retried (1)
[f0/35fac1] NOTE: Missing output file(s) `Dog2_fastqc/*.zip` expected by process `runFastQC (rFQC.Dog2)` -- Execution is retried (1)
executor >  local (6)
[08/1f52e3] process > runFastQC (rFQC.Dog2)        [ 67%] 4 of 6, failed: 4
[-        ] process > runMultiQC                   -
[-        ] process > filterAndTrim                -
[-        ] process > runFastQC_postfilterandtrim  -
[-        ] process > runMultiQC_postfilterandtrim -
[-        ] process > mergeTrimmedTable            -
[-        ] process > LearnErrorsFor               -
[-        ] process > LearnErrorsRev               -
[-        ] process > SampleInferDerepAndMerge     -
[-        ] process > mergeDadaRDS                 -
[-        ] process > SequenceTable                -
[-        ] process > ChimeraTaxonomySpecies       -
[-        ] process > AlignAndGenerateTree         -
[-        ] process > BiomFile                     -
[-        ] process > ReadTracking                 -
Pulling Singularity image docker://quay.io/cbio/16s-rdna-dada2-pipeline [cache /Users/devina/16S-rDNA-dada2-pipeline/work/singularity/quay.io-cbio-16s-rdna-dada2-pipeline.img]
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /Users/devina/16S-rDNA-dada2-pipeline/work/singularity
[1d/58298c] NOTE: Missing output file(s) `Dog29_fastqc/*.zip` expected by process `runFastQC (rFQC.Dog29)` -- Execution is retried (1)
[f0/35fac1] NOTE: Missing output file(s) `Dog2_fastqc/*.zip` expected by process `runFastQC (rFQC.Dog2)` -- Execution is retried (1)
executor >  local (6)
[09/8a4e6f] process > runFastQC (rFQC.Dog1)        [100%] 6 of 6, failed: 6
[-        ] process > runMultiQC                   -
[-        ] process > filterAndTrim                -
[-        ] process > runFastQC_postfilterandtrim  -
[-        ] process > runMultiQC_postfilterandtrim -
[-        ] process > mergeTrimmedTable            -
[-        ] process > LearnErrorsFor               -
[-        ] process > LearnErrorsRev               -
[-        ] process > SampleInferDerepAndMerge     -
[-        ] process > mergeDadaRDS                 -
[-        ] process > SequenceTable                -
[-        ] process > ChimeraTaxonomySpecies       -
[-        ] process > AlignAndGenerateTree         -
[-        ] process > BiomFile                     -
[-        ] process > ReadTracking                 -
Pulling Singularity image docker://quay.io/cbio/16s-rdna-dada2-pipeline [cache /Users/devina/16S-rDNA-dada2-pipeline/work/singularity/quay.io-cbio-16s-rdna-dada2-pipeline.img]
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /Users/devina/16S-rDNA-dada2-pipeline/work/singularity
[1d/58298c] NOTE: Missing output file(s) `Dog29_fastqc/*.zip` expected by process `runFastQC (rFQC.Dog29)` -- Execution is retried (1)
[f0/35fac1] NOTE: Missing output file(s) `Dog2_fastqc/*.zip` expected by process `runFastQC (rFQC.Dog2)` -- Execution is retried (1)
WARN: Killing pending tasks (2)
executor >  local (6)
[09/8a4e6f] process > runFastQC (rFQC.Dog1)        [100%] 6 of 6, failed: 6
[-        ] process > runMultiQC                   -
[-        ] process > filterAndTrim                -
[-        ] process > runFastQC_postfilterandtrim  -
[-        ] process > runMultiQC_postfilterandtrim -
[-        ] process > mergeTrimmedTable            -
[-        ] process > LearnErrorsFor               -
[-        ] process > LearnErrorsRev               -
[-        ] process > SampleInferDerepAndMerge     -
[-        ] process > mergeDadaRDS                 -
[-        ] process > SequenceTable                -
[-        ] process > ChimeraTaxonomySpecies       -
[-        ] process > AlignAndGenerateTree         -
[-        ] process > BiomFile                     -
[-        ] process > ReadTracking                 -
Pulling Singularity image docker://quay.io/cbio/16s-rdna-dada2-pipeline [cache /Users/devina/16S-rDNA-dada2-pipeline/work/singularity/quay.io-cbio-16s-rdna-dada2-pipeline.img]
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /Users/devina/16S-rDNA-dada2-pipeline/work/singularity
[1d/58298c] NOTE: Missing output file(s) `Dog29_fastqc/*.zip` expected by process `runFastQC (rFQC.Dog29)` -- Execution is retried (1)
[f0/35fac1] NOTE: Missing output file(s) `Dog2_fastqc/*.zip` expected by process `runFastQC (rFQC.Dog2)` -- Execution is retried (1)
WARN: Killing pending tasks (2)
Error executing process > 'runFastQC (rFQC.Dog29)'

Caused by:
  Missing output file(s) `Dog29_fastqc/*.zip` expected by process `runFastQC (rFQC.Dog29)`

Command executed:

  mkdir Dog29_fastqc
  fastqc --outdir Dog29_fastqc     Dog29_R1.fastq.gz     Dog29_R2.fastq.gz

Command exit status:
  0

Command output:
  (empty)

Work dir:
  /Users/devina/16S-rDNA-dada2-pipeline/work/6b/6eaae0ddccb5e47c0f9c22d9b5ff1b

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line.
`please help thank you

**Comment by benjjneb** [comment]
This appears to be a path issues with this singularity invocation, not an issues with the package.
