### ISSUE TITLE
ASVs length distribution changes according to truncLen parameter

### ISSUE THREAD

**Issue by wasimbt** [benjjneb/dada2#846]
Hi, 

I have been using dada2 (1.10.1) and recently realized that decision for truncLen parameter can influence the length distribution of ASVs, atleast in my case. For example (using primer pair 515F-806R),   

(i) P3_out <- filterAndTrim(fwd=file.path(subF.fp, fastqFs), filt=file.path(filtpathF, fastqFs), rev=file.path(subR.fp, fastqRs), filt.rev=file.path(filtpathR, fastqRs), truncLen=c(**192**,170), maxEE=c(2, 2), truncQ=7, maxN=0, minLen=150, rm.phix=TRUE, compress=TRUE, verbose=TRUE, multithread=TRUE)

and following scripts, learnErrors, derepFastq, dada, mergePairs and makeSequenceTable gave me the ASVs distribution

table(nchar(getSequences(P3_seqtab)))

192  193  195  199  209  211  222  231  246  247  250  251  252  253  254  255  256  257  298  300 
10       1      1      1      1      1      1      2      1      1      1     3   84   3523  491   40    3      2      1      1 

(ii) while only changing the truncLen=c(**200**,170) and keeping rest of the downstream scripts parameter as it is, gave me different ASVs distribution

table(nchar(getSequences(P3_seqtab2)))

200  209  211  222  229  231  246  247  250  251  252  253  254  255  256  257  298  300 
  12      1    1      1      1      2      1      1      1      3    81  3479  489   42      3     2      1      1

Can someone please explain me, what is happening here and if i am doing something wrong?

Although, I can keep the range of ASVs based on length filter at next step, my second question is, how one can decide the range for such filter and not missing out real ASVs?

Many thanks!

Wasim

**Comment by benjjneb** [comment]
Hi Wasim,
My guess is that you are using the V4 primer set here. The length of the target amplicons is 251-256 (depending on exact primers used). The lengths of those amplicons are not affected by `truncLen` choices. 

It is only the very short amplicons, which are off-target amplicification typically, and probably should be filtered out anyway. For example, the smallest lengths are 192 and 200, which is the smalles possible lengths given the truncation of your forward reads.

**Comment by wasimbt** [comment]
Hi Benjamin, 

Thank you for your time and reply! Yes, I am amplifying the V4 region with the primer pair 515F-806R. 

Here, is it not the case that by deciding the trimming length for forward read, I am getting the ASVs till that limit. Which means if i go lower with that limit, i will have more shorter length ASVs (which can influence the downstream processing such as alpha diversity calculation). This is surprising to me as after forward and reverse reads merging, the ASVs length should be remain same (regardless of set limit of forward read trimming). Here it seems to me that for shorter ASVs, reverse read is not merging and only forward read trimming limit is deciding the ASV length? is it possible? Could you please explain.

Also is there any recommended amplification range for V4 (515F-806R), so that one can stick to that and not missing out real ASVs. 

Thank you!

Best, 
Wasim

**Comment by benjjneb** [comment]
Almost none of your ASVs are changing length. The vast vast majority of your ASVs are of length 252-255, as expected, and don't change length in either dataset.

The very small number changing lengths are the off-target amplicons that have very low lengths, and should be excluded anyway.

**Comment by wasimbt** [comment]
Thanks for your comments!!

**Comment by soluna1** [comment]
Hi, 
I have a doubt too related to the trunclen parameter but in this case for v9 18s region, which can vary from 87 to 186 bp. My samples come from a 150x2 illumina run, so I've been using trunclen = c(100,90) or c(110,100) as the QS is good enough for this trimming. But I've just realised what @wasimbt said before, that the smallest merge pairs coincide with the trunclen limit. 

e.g.
![image](https://user-images.githubusercontent.com/16171059/81595636-18ab3280-93c3-11ea-9627-3af0fe5f471f.png)


So, I wonder if during the filterAndTrim process I'm loosing some short sequences. Is there a way to keep all reads from 80 to 100 bps (forward and reverse) with the filterAndTrim function, so later allowing an overlap of 30 the shorter sequences can be retrieved?

thank you so much!!

Soluna

**Comment by benjjneb** [comment]
> in this case for v9 18s region, which can vary from 87 to 186 bp

Unfortunatley this is just not amenable to straight length trucnation, since the shortest region is less than half the longest region.

You're going to need to use an outside preprocessing solution like cutadapt to remove primers (forward and reverse on R1 and R2). The [dada2 ITS tutorial](https://benjjneb.github.io/dada2/ITS_workflow.html) should help, as that was created for the same fundamental challenge of a gene region that varies greatly in length.

**Comment by soluna1** [comment]
Yes, I've already used cutadapt on this samples to remove primers, so perhaps I can use the same tool to trim the endings (low QS) in F and R reads, to move later to filterAndTrim function without the trunclen parameter, yep. This could work. I'll have a look to the ITs tutorial. Thanks so much!!!
