### ISSUE TITLE
Output error-corrected reads for each sample

### ISSUE THREAD

**Issue by qinglong89** [benjjneb/dada2#848]
Hi Benjamin,

Just wanna to know any commands to output error-corrected reads for each sample (either single-end or paired-end reads) after learnErrors function?

Qinglong

**Comment by benjjneb** [comment]
Output in what format?

And the reads are error-corrected in the `dada` step, the `learnErrors` step just fits the error model.

**Comment by qinglong89** [comment]
> Output in what format?
> 
> And the reads are error-corrected in the `dada` step, the `learnErrors` step just fits the error model.

**Comment by qinglong89** [comment]
I mean the sample-level output of fastq or fasta file after dada step.
Thanks.

**Comment by benjjneb** [comment]
Sure, you can use `uniquesToFasta` function to write the sequences from a `dada-class` object to a fasta file.
