### ISSUE TITLE
Chimeric RSVs

### ISSUE THREAD

**Issue by naarkhoo** [benjjneb/dada2#85]
I wonder, given the underlying idea of dada2, could still a few RSV, be found chimeric even after "removeBimeraDenovo" ?

Because, It seems, even after using "removeBimeraDenovo", there exists some chimeric RSVs. I have used uchime and the gold database and have found 80 chimeric RSV out of 1200.

**Comment by joey711** [comment]
@naarkhoo it is possible. The DADA2 algorithm itself does not perform chimera removal at all. I don't have any theoretical or empirical reason to believe that `removeBimeraDenovo` is perfect at removing chimeras. If your analysis is sensitive to a small percentage of chimeras escaping the dada2-package-included chimera filter, and you have an additional chimera-removal tool at your disposal that you trust, I think it is reasonable to make use of it.

I'm not speaking for @benjjneb on this point, but on my own datasets I've found similar levels of chimera filter improvement using the `usearch` suite after `removeBimeraDenovo`. 

I think eventually the goal would be to improve chimera detection to the point that an external, closed-source tool is not needed. In the mean time, I would recommend that you include this added filter that you're comfortable with.

**Comment by benjjneb** [comment]
@naarkhoo Chimera removal is a separate step from the main sequence inference algorithm. We cover a bit of benchmarking on our chimera removal method in the paper (see Supplementary Note 2), it does well especially for DADA2's exact output but it probably deserves its own paper. Weirdly everyone other than Robert Edgar gave up on chimera methods post-2011, and inadequate chimera detection is one of the main culprits for the large numbers of FP OTUs output by the mothur/qiime pipelines.

That said, perhaps the additional sequences being flagged by uchime-ref are chimeras, and perhaps they are not. It's totally reasonable to add uchime-ref as a second chimera removal method, but if it was me I would take a look at a subset of the sequences being flagged (probably by BLASTing them vs. nt) and decide if they are really chimeric or not.

**Comment by naarkhoo** [comment]
@benjjneb Thanks for your comments - Do you happen know why people have gave up ? and isn't chimera identification, simply blasting against a high-quality database and see if there is any high identical entries ? Or, are there other criteria that I don't know ?

i have blasted, chimeric ones against ncbi 16srna database through https://blast.ncbi.nlm.nih.gov/Blast.cgi . Seems all queries have hits with ~ 85% identity; so I agree, they could still be real taxa not chimeric ;

**Comment by joey711** [comment]
@naarkhoo by definition, *de novo* chimera detection does not use a reference database. `removeBimeraDenovo` is looking within your data and attempting to detect two more abundant denoised sequences that would explain the current sequence-in-question as a chimeric product of the two.

One could equivalently describe this as *unsupervised* classification of chimeras. The reference database approach you described would be called a *supervised classification* via sequence alignment.

**Comment by naarkhoo** [comment]
@benjjneb can you elaborate on _"if it was me I would take a look at a subset of the sequences being flagged (probably by BLASTing them vs. nt) and decide if they are really chimeric or not."_ I am sure, there would are valuable lessons for users like me :-)

**Comment by benjjneb** [comment]
@naarkhoo In general, at least if you are in a reasonably well studied environment (eg. human gut) a large majority of the 16S variants called by dada2 will exactly match previously observed sequences. Chimeras on the other hand will be exact matches at a much lower rate.

This is a rough test, as ground-truthing this kind of data is tricky, but what I would do is BLAST ~20 of the uchime-ref called chimeras, and then BLAST ~20 random sequences that weren't called by uchime-ref. If the uchime-ref chimeras are exactly matching as much as the others, then I'd probably keep them under the assumption they are spurious calls. If they are mostly non-exact matches, than uchime-ref is usefully picking up chimeras that `removeBimeraDenovo` missed.
