### ISSUE TITLE
Understanding minOverlap setting in mergePairs()

### ISSUE THREAD

**Issue by janetw** [benjjneb/dada2#852]
Hello,
First of all, thank you once again for this software. I apologize that this is not necessarily an issue but trying to understand how the value on minOverlap is used. Sorry if this is not the correct place to ask this or if this has been addressed somewhere else.

Is the overlap region always at the end of each read?

If I set the minOverlap to "12" and keep the default of "0" for the maxMismatch in the mergePairs function and have some forward and reverse reads that have an overlap of 25, do all 25 still have to be an exact match?

Another example, if I set the minOverlap to "5" and keep the default of "0" for the maxMismatch in the mergePairs function and have some forward and reverse reads that have an overlap of 20, once again do all 20 still have to be an exact match? 

Thank you for any insight into how this works.

Best regards,
Janet

**Comment by benjjneb** [comment]
> Is the overlap region always at the end of each read?

In the vast majority of amplicon libraryies, yes, but it doesn't have to be. Its wherever the overlap in the alignment of the forwards and (revcomped) reverse reads happens.

> If I set the minOverlap to "12" and keep the default of "0" for the maxMismatch in the mergePairs function and have some forward and reverse reads that have an overlap of 25, do all 25 still have to be an exact match?

Yes, those two requirements are enforced independently.

> Another example, if I set the minOverlap to "5" and keep the default of "0" for the maxMismatch in the mergePairs function and have some forward and reverse reads that have an overlap of 20, once again do all 20 still have to be an exact match?

Yes.

**Comment by janetw** [comment]
Thank you!
Janet

**Comment by Jolvii85** [comment]
Hi，

Based on the discussion above, Do you think set the maxMismatch threshold to the percentage is more reasonable? If the fragment length is very different from each other in the library, set the maxMismatch to specific values would cause the function to keep longer reads, and thus could cause some bias in the final results?

Best,

Wei
