### ISSUE TITLE
Unable to install dada2 on mint

### ISSUE THREAD

**Issue by berkell** [benjjneb/dada2#855]
I'm trying to install dada2 by running the following:

source("http://bioconductor.org/biocLite.R")
biocLite()
biocLite("dada2")

A lot of stuff happens that then end with:

The downloaded source packages are in
	‘/tmp/Rtmp0Q4Lxr/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning messages:
1: In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘cluster’ had non-zero exit status
2: In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘Matrix’ had non-zero exit status
3: In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘nlme’ had non-zero exit status
4: In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘mgcv’ had non-zero exit status

This then ultimately leads to not being able to load the library.

This is the setup I'm running:

> R.version
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          4.4                         
year           2018                        
month          03                          
day            15                          
svn rev        74408                       
language       R                           
version.string R version 3.4.4 (2018-03-15)
nickname       Someone to Lean On          
> packageVersion("BiocInstaller")
[1] ‘1.28.0’

Any pro tips that will enable the installation?

**Comment by benjjneb** [comment]
I'd love to help you, but installation trouble on different Linux distros is not my forte.

I think that you will get better and more knowledgeable support on this by posting to the Bioconductor support forums: https://support.bioconductor.org/

Especially because the underlying issue seems to be that the Bioconductor dependencies are not successfully installing.

**Comment by dswan** [comment]
> Any pro tips that will enable the installation?

That's not the recommended method for installing BioConductor packages anymore. If you look at https://www.bioconductor.org/install/ then BiocManager is the preferred route. R 3.4.4 is 7 releases out of date as well..
