### ISSUE TITLE
error in pyloseq::ordinate when following DADA2 tutorial

### ISSUE THREAD

**Issue by James-Kitson** [benjjneb/dada2#856]
Hello Benjamin,

I'm attempting to analyse some fungal ITS sequences following the main DADA2 tutorial and the ITS tutorial. Everything seems to run fine until I get to:
```
# Transform data to proportions as appropriate for Bray-Curtis distances
ps.prop <- transform_sample_counts(ps, function(otu) otu/sum(otu))
ord.nmds.bray <- ordinate(ps.prop, method="NMDS", distance="bray")
```
At this point, I get the error:
```
Error in if (autotransform && xam > 50) { : 
  missing value where TRUE/FALSE needed
```
Looking at `ps.prop@otu_table@.Data`, there appears to be 'NaN' values in there that are not present in `ps@otu_table@.Data`. So I think there's something going on in `transform_sample_counts()`.

Do you have any idea of the sort of conditions that would lead to this happening so I can troubleshoot this?

Many Thanks,

James

**Comment by benjjneb** [comment]
You should probably post this on the phyloseq forum rather than here.
If I'm guessing though, I'd say some of your samples have zero counts, so you get NaNs when transforming to proportions. If that's the case, removing zero-count samples first should solve the issue.

**Comment by James-Kitson** [comment]
Thanks for replying, 

I thought it might be something like that and I had looked at the `out` object created by `filterAndTrim` to see if all the 'reads.out' were positive. I've just checked the entirety of the `track` object and some samples haven't made it through either merging or chimera removal. I hope that solves it.

Many Thanks,

James
