### ISSUE TITLE
Assign Taxonomy warning!!

### ISSUE THREAD

**Issue by DanieleDeco** [benjjneb/dada2#859]
Hi, 
I get this warning when I try to assign the Taxonomy of my reads;

Warning message:
In matrix(unlist(strsplit(genus.unq, ";")), ncol = td, byrow = TRUE) :
  data length [949] is not a sub-multiple or multiple of the number of rows [119]

I created my own database (fasta file attached) as I am working with a functional gene
[Database.fas.zip](https://github.com/benjjneb/dada2/files/3729583/Database.fas.zip)

.

Thanks!!!

**Comment by benjjneb** [comment]
It indicates you have an inconsistency in your id lines.
A quick scan shows that line 2302 is lacking a terminal semicolon, unlike all the other id lines.

``` >Bacteria;Proteobacteria;Gammaproteobacteria;sulfur_oxidizing_symbionts;Bathymodiolus_thermophilus
```

Line 3504 too.

**Comment by DanieleDeco** [comment]
Thanks, now I don't get any warning.
