### ISSUE TITLE
My Samples Aren't Seperated

### ISSUE THREAD

**Issue by thecrobe** [benjjneb/dada2#861]
Hi! 

Im new to DADA2 and was following the tutorial (https://benjjneb.github.io/dada2/tutorial.html) and It was going peachy until I started to try and analyze data. For some reason my seqtab.nochim is a data frame with (1 x 328) when it should be (9 x 328). So I don't know why my samples are seemingly merged. 

Any help is appreciated

**Comment by benjjneb** [comment]
Did you start out with separate fastqs for each sample? That is the format expected by dada2.

**Comment by thecrobe** [comment]
No, my samples were in one file but I thought the barcodes were what separated them from each other.

**Comment by benjjneb** [comment]
> I thought the barcodes were what separated them from each other.

Not in dada2-land. You will need to separate the reads into one fastq file per sample (or two if they are paired reads). This is the normal format that comes of Illumina sequencing these days. It sounds like you might have older data that needs to be "demultiplexed".

**Comment by thecrobe** [comment]
Okay i Can figure this out then. This is my first foray into dada2 from qiime1. 

Thank you, you lovely apricot.

**Comment by benjjneb** [comment]
I think the QIIME1 command `split_libraries_fastq.py` will do what you want. Make sure to use the `--store_demultiplexed_fastq` flag though, to get fastq files as output.
