### ISSUE TITLE
installing DADA2

### ISSUE THREAD

**Issue by clapixi** [benjjneb/dada2#862]
Hi, I am trying to install Dada2 according to the instructions and got the following message: 
Error: Failed to install 'dada2' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

I would appreciate any help. Thanks!

**Comment by benjjneb** [comment]
Can you provide the exact commands you are using to try to install dada2?

Also, installing from GitHub is not the recommended method. We recommend installing via Bioconductor, especially if you aren't familiar with installing packages from source.

**Comment by clapixi** [comment]
Hi! thank you very much for your answer. I have followed all the instructions from https://benjjneb.github.io/dada2/dada-installation.html <https://benjjneb.github.io/dada2/dada-installation.html> (from source). Altough I am not an expert, I use to install packages from source or at least I try… 
So, you recommend me to install it via Bioconductor using R ? 
best regards
claudia


 
Dra. Claudia Piccini
Departamento de Microbiología
IIBCE
Avenida Italia 3318, Montevideo 11600
Uruguay

**Comment by clapixi** [comment]
that´s what I did and got warnings and the error message.. 


Dra. Claudia Piccini
Departamento de Microbiología
IIBCE
Avenida Italia 3318, Montevideo 11600
Uruguay

**Comment by clapixi** [comment]
Now I could install it using Bioconductor and R!! thank you
best regards
claudia


Dra. Claudia Piccini
Departamento de Microbiología
IIBCE
Avenida Italia 3318, Montevideo 11600
Uruguay
