### ISSUE TITLE
Removing primers in pipeline

### ISSUE THREAD

**Issue by codespop** [benjjneb/dada2#863]
I was using the standard DADA2 pipeline and getting species-level detection. However, the new fastq files I received contain the following primers: 
515F:GTGCCAGCMGCCGCGGTAA  
806R:GGACTACHVGGGTWTCTAAT

Now, my species results all read N/A. 

I need to remove the primers, but I'm not sure if I'm doing it correctly. 
When I tried this, I was able to detect 2 species. 

What is the correct way to use filterAndTrim? I am not sure how much to truncate. 

```
# Forward and reverse fastq filenames have format: SAMPLENAME_R1_001.fastq and SAMPLENAME_R2_001.fastq
fnFs <- sort(list.files(pattern="_1.fq", full.names = TRUE))
fnRs <- sort(list.files(pattern="_2.fq", full.names = TRUE))

#REMOVING PRIMERS
library(ShortRead)
packageVersion("ShortRead")
library(Biostrings)
packageVersion("Biostrings") 

FWD <- "GTGCCAGCMGCCGCGGTAA"  ## CHANGE ME to your forward primer sequence
REV <- "GGACTACHVGGGTWTCTAAT"  ## CHANGE ME..

trimLeft = c(FWD, REV) 

out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, #truncLen=c(225,225),
                     maxN=0, maxEE=c(2,5), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, multithread=TRUE, trimLeft = c(FWD_PRIMER_LEN, REV_PRIMER_LEN)) # On Windows set multithread=FALSE
```

**Comment by codespop** [comment]
Update:

Receive this: 
```
> FWD.orients
              Forward            Complement               Reverse               RevComp 
"GTGCCAGCMGCCGCGGTAA" "CACGGTCGKCGGCGCCATT" "AATGGCGCCGMCGACCGTG" "TTACCGCGGCKGCTGGCAC" 
> fnFs.filtN <- file.path("filtN", basename(fnFs)) # Put N-filterd files in filtN/ subdirectory
> fnRs.filtN <- file.path("filtN", basename(fnRs))
> filterAndTrim(fnFs, fnFs.filtN, fnRs, fnRs.filtN, maxN = 0, multithread = TRUE)
Warning messages:
1: In isTRUE(disabled) :
  closing unused connection 4 (cutadapt/116S1_2.fq.gz)
2: In isTRUE(disabled) :
  closing unused connection 3 (cutadapt/116S1_1.fq.gz)
> primerHits <- function(primer, fn) {
+   # Counts number of reads in which the primer is found
+   nhits <- vcountPattern(primer, sread(readFastq(fn)), fixed = FALSE)
+   return(sum(nhits > 0))
+ }
> rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.filtN[[1]]), 
+       FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.filtN[[1]]), 
+       REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.filtN[[1]]), 
+       REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.filtN[[1]]))
                 Forward Complement Reverse RevComp
FWD.ForwardReads  339735          0       0       0
FWD.ReverseReads       0          0       0      21
REV.ForwardReads       0          0       0      22
REV.ReverseReads  418324          0       0       0
> # Forward and reverse fastq filenames have the format:
> cutFs <- sort(list.files(path.cut, pattern = "_1.fq", full.names = TRUE))
> cutRs <- sort(list.files(path.cut, pattern = "_2.fq", full.names = TRUE))
> # Extract sample names, assuming filenames have format:
> get.sample.name <- function(fname) strsplit(basename(fname), "_")[[1]][1]
> sample.names <- unname(sapply(cutFs, get.sample.name))
> head(sample.names)
[1] "116S1"
> plotQualityProfile(cutFs[1:2])
Error in data.frame(sequence = names(freqtbl$top), count = as.integer(freqtbl$top),  : 
  arguments imply differing number of rows: 0, 1
> plotQualityProfile(cutRs[1:2])
Error in data.frame(sequence = names(freqtbl$top), count = as.integer(freqtbl$top),  : 
  arguments imply differing number of rows: 0, 1
> filtFs <- file.path(path.cut, "filtered", basename(cutFs))
> filtRs <- file.path(path.cut, "filtered", basename(cutRs))
> out <- filterAndTrim(cutFs, filtFs, cutRs, filtRs, maxN = 0, maxEE = c(2, 5), 
+                      truncQ = 2, minLen = 50, rm.phix = TRUE, compress = TRUE, multithread = TRUE)  # on windows, set multithread = FALSE
The filter removed all reads: cutadapt/filtered/116S1_1.fq.gz and cutadapt/filtered/116S1_2.fq.gz not written.
Warning messages:
1: In file.remove(fout[[1]]) :
  cannot remove file 'cutadapt/filtered/116S1_1.fq.gz', reason 'No such file or directory'
2: In file.remove(fout[[2]]) :
  cannot remove file 'cutadapt/filtered/116S1_2.fq.gz', reason 'No such file or directory'
3: In filterAndTrim(cutFs, filtFs, cutRs, filtRs, maxN = 0, maxEE = c(2,  :
  No reads passed the filter. Please revisit your filtering parameters.
> head(out)
              reads.in reads.out
116S1_1.fq.gz        0         0
```

No final reads? Not sure what to change in the filtering step..

**Comment by benjjneb** [comment]
> What is the correct way to use filterAndTrim? I am not sure how much to truncate.

You are close, but you need to replace the dummy values `FWD_PRIMER_LEN` and `REV_PRIMER_LEN` with the lengths of your forward and reverse primers. It looks like yours are 19 and 20. So...

```
filterAndTrim(..., trimLeft=c(19,20))
```

I wouldn't bother with the cutadapt approach, the `trimLeft` approach is easier and will do what you want in this case.

**Comment by codespop** [comment]
Thanks, that seemed to work!

**Comment by Apanphil** [comment]
Hi,

I am running the ITS version of dada2 1.14. I have reached at a stage of removing the primers and have got an error. See below. I do not how to solve the error. Any help?
primerHits <- function(primer, fn) {
+ nhits <- vcountPattern(primer, sread(readFastq(fn)), fixed = FALSE)
+ return(sum(nhits > 0))
+ }
> rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.filtN[[1]]),
+ FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.filtN[[1]]),
+ REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.filtN[[1]]),
+ REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.filtN[[1]]))
Error in sread(readFastq(fn)) : could not find function "sread"
> rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.filtN[[1]]),
+ FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.filtN[[1]]),
+ REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.filtN[[1]]))
Error in sread(readFastq(fn)) : could not find function "sread"

**Comment by benjjneb** [comment]
You need to load the ShortRead library that implements the sread function: `library(ShortRead)`

**Comment by Apanphil** [comment]
Hi
I tried to install the shortread software but it seems it failed.

On loading the library, I’m getting the error below:

Error in value[[3L]](cond) :
  Package ‘ShortRead’ version 1.44.0 cannot be unloaded:
Error in unloadNamespace(package) : namespace ‘ShortRead’ is imported by ‘dada2’ so cannot be unloaded

How do I proceed with this?

Godfrey Philliam Apangu
PhD Student
National Pollen and Aerobiology Research Unit/School of Science and the Environment
Office: St Johns Campus, Binyon North, BN1003 | Website: www.worcester.ac.uk<http://www.worcester.ac.uk/>
[University of Worcester]
Follow us on Facebook<https://www.facebook.com/UniversityOfWorcester>, Instagram<https://www.instagram.com/worcester_uni/>, Twitter<https://twitter.com/worcester_uni> and YouTube<https://www.youtube.com/user/universityworcester>

**Comment by benjjneb** [comment]
I'd suggest restarting R, and loading ShortRead first then dada2.

**Comment by Apanphil** [comment]
Yes, it worked. Thank you

Godfrey Philliam Apangu
PhD Student
National Pollen and Aerobiology Research Unit/School of Science and the Environment
Office: St Johns Campus, Binyon North, BN1003 | Website: www.worcester.ac.uk<http://www.worcester.ac.uk/>
[University of Worcester]
Follow us on Facebook<https://www.facebook.com/UniversityOfWorcester>, Instagram<https://www.instagram.com/worcester_uni/>, Twitter<https://twitter.com/worcester_uni> and YouTube<https://www.youtube.com/user/universityworcester>

**Comment by Apanphil** [comment]
Hi there,
I am using dada2 version 1.14 to analyse air samples and assign fungal species using UNITE database v.8.2. From other methods, i know that species x exists in the air samples. However, dada2 is not detecting it. How do i use a more sensitive dada2 in order to detect the known species x in the air samples?
Any help is appreciated.
Thank you
Godfrey Philliam Apangu
PhD Student
National Pollen and Aerobiology Research Unit/School of Science and the Environment
Office: St Johns Campus, Binyon North, BN1003 | Website: www.worcester.ac.uk<http://www.worcester.ac.uk/>
[University of Worcester]
Follow us on Facebook<https://www.facebook.com/UniversityOfWorcester>, Instagram<https://www.instagram.com/worcester_uni/>, Twitter<https://twitter.com/worcester_uni> and YouTube<https://www.youtube.com/user/universityworcester>

**Comment by benjjneb** [comment]
@Apanphil If your problem isn't related to the issue (as is the case now) you should open a new issue.
