### ISSUE TITLE
Adding color to my ordination plot 

### ISSUE THREAD

**Issue by marz29** [benjjneb/dada2#865]
I had been using the dada2 tutorial for my sequences analysis but by the time i want to create my ordination plot appears this problem.
I made my phyloseq object as said in the tutorial, so i do not know which could be the cause. 

![Captura de Pantalla 2019-10-17 a la(s) 13 09 51](https://user-images.githubusercontent.com/56695673/67035513-68e93d00-f0df-11e9-9a45-334b35628919.png)

**Comment by benjjneb** [comment]
You probably want to post this at the phyloseq Issue tracker, since it is a phyloseq command you are talking about.

But the issue here is that your sample metadata does not have a `$samples` column in it, which is what ggplot2 is looking for when you tell it `color="samples"`.
