### ISSUE TITLE
problem found and problem solved in ITS pipeline 

### ISSUE THREAD

**Issue by Vilchez-Vargas** [benjjneb/dada2#867]
I found a problem running these two lines:

cutadapt <- "/Users/nbetrap/miniconda2/bin/cutadapt" # CHANGE ME to the cutadapt path on your machine
system2(cutadapt, args = "--version") # Run shell commands from R

The message was either command not found or error while running the command

However, typing:

system2("cutadapt", args = "--version;")

the output is:

1.18

**Comment by benjjneb** [comment]
Yeah, the `"/Users/nbetrap/miniconda2/bin/cutadapt"` bit needs to be changed to whatever the path is on your machine. It looks like you have cutadapt in your path, so just the simple `"cutadapt"` worked, but for many others they will need to provide a full path as in the tutorial example.
