### ISSUE TITLE
Running dada2 on samples of different nature (e.g. experiment, blanks, mock communities)

### ISSUE THREAD

**Issue by aloria85** [benjjneb/dada2#869]
Dear Dr. Callahan,
First of all thank you for developing such a useful tool.
I am using dada2 to analyze 96 libraries represented by COI amplicons from zooplankton eDNA collected over time from ponds experiencing different environmental stressors (eutrophication and glyphosate) in a mesocosm set-up. 
Along with the samples directly collected from the ponds, I also sequenced few blanks, few extraction controls and few mock communities that I amplified with the experimental samples. My question is, would you advice to run Dada2 on all, pooled libraries (experimental samples, blanks, controls, mocks) or would you group them in some way? 
I don't have replicates in my experimental samples group. Eight ponds (4 mesotrophic and 4 eutrophic) were sampled over time and were subjected to pulses of an insecticide of different intensities. At first, I thought to group the samples by pond ID; however, their composition over time may change drastically and that is the exact aspect we want to study (and possibly the impact of genetic diversity of some species). How about running dada2 on each separate library (e.g. I sequenced a plate so 96 libraries all analyzed individually and then merged afterwards)?
Thanks a lot for your help.

**Comment by benjjneb** [comment]
What is important for DADA2 is that all the samples were processed in the same way and thus have the same error profile. So, is that the case here? Did you use identical PCR protocols and sequencing protocols on all samples? If so, you can just run everything as one big batch through DADA2.

> How about running dada2 on each separate library (e.g. I sequenced a plate so 96 libraries all analyzed individually and then merged afterwards)?

If the plates were sequenced separately, perhaps even on different machines, then it would be appropriate to process each plate separately. These would then constitute the batches of samples that were amplified/sequenced in identical fashion, and thus should be processed together (i.e. with a shared error model) in DADA2.
