### ISSUE TITLE
Different taxonomic annotations between silva, rdp & greengene

### ISSUE THREAD

**Issue by FabianRoger** [benjjneb/dada2#87]
Hej

I tried to assign the taxonomy using each of the provided reference files, and looked at the consistency of the assignments. 

I wrote a function to categorise each assignment as "all three agree" "two agree" , "all NA" and some other categories that seemed useful to me and visualised the frequency of the "agreement categories" for each rank. 

The idea was to produce a consensus taxonomy (where each entry would be appended by the degree of consensus) but I realised that the nomenclature used in the three reference files is not coherent. 

as such there is e.g.  `OP3` (gg) and `Candidate_division_OP3` (silva), `Spirochaetes` (gg, rdp) and `Spirochaetae` (silva) and `Cyanobacteria/Chloroplast` (rdp) and `Cyanobacteria`(gg, silva).

(also, all gg entry are prepended by there rank as in `k__Bacteria` although this is easy to remove with e.g. `sub()`)

It would be really nice if the labels were comparable so that identical sequences in the three reference files had the same sequence annotation. 

Would you agree that this would be useful?

**Comment by benjjneb** [comment]
I agree that would be useful, however that is not something that we can change. The training datasets we provide are directly derived from the taxonomic nomenclature of Silva/GG/RDP, and changing those assignments conflicts with workflows that depend on the particular nomenclature.

The differences, which are often cosmetic, are annoying. But ultimately this is an issue that has to be solved (or not) by the maintainers of these taxonomic databases.

I guess downstream of the databases a "translation dictionary" between them could be developed and would be really nice, but it also sounds like a lot of work.

**Comment by FabianRoger** [comment]
Point taken. Its a pity though that this limits comparison to very simple metrics like *how much assigned at each taxon level using each reference file* which doesn't provide much added value compared to just pick one of the three randomly. 

It's the strategy I'll stick with for now though, as - as you point out - doing anything about it is likely to be painstaking...
