### ISSUE TITLE
Costomized database has no NA assigned

### ISSUE THREAD

**Issue by Aircus** [benjjneb/dada2#871]
Thanks a lot for making DADA2! Now our group is using this pipeline only.

For now, I am trying to use DADA2 for analysing anaerobic fungi groups, we used the customized database from here: https://anaerobicfungi.org/tools/
They don't have a ready-to-use database for DADA2, so I twist it a bit by my own to fit dada2 formation:
[Fu_seq_03-4_2019_02_08_TL.fasta.zip](https://github.com/benjjneb/dada2/files/3763099/Fu_seq_03-4_2019_02_08_TL.fasta.zip)

It is a quite small database. But when I used it in DADA2 pipeline, I got no NA in barplot, each reads got an assigned taxonomy, which I don't think it's true. 

In the assignTaxonomy function, I can only change the minboot parameter, I don't think it will help for such a small database because it will quickly found one taxon no matter how many time the program runs. i.e., assign to the same taxonomy in many bootstraps. Am I understand correct?

If so, can I set a threshold like e value for assign taxonomy?

Thank a lot!

Tong

**Comment by benjjneb** [comment]
The way the naive Bayesian classifier works, is that it relies on there being outgroups present in order to know when there is insufficient confidence to assign taxonomy to a sequence. What I'd reocommend then, is supplementing your custom database with a general-purpose set of sequences that span a broad taxonomic range.

You could also consider using an alternative method like IDTaxa, which does incorporate some sense of a %id threshold I believe.

**Comment by Aircus** [comment]
Hi!
Thanks for the reply!
Yes, I tried to add my customized database from https://anaerobicfungi.org/tools/
to the one in your DADA2 ITS pipeline sh_general_release_dynamic_s_01.12.2017.fasta, by just copy and paste mine below yours.  Then all my reads were assigned to your database. I guess that is because of my entry in the database are generally much shorter than yours, then the reads get a higher score with your database. thus, it doesn't work as I expected.  

Are there any other algorithms/functions compatible with DADA2? I will also try IDTaxa as you suggested, Thanks!

Best regards!
Tong

**Comment by benjjneb** [comment]
> Are there any other algorithms/functions compatible with DADA2? I will also try IDTaxa as you suggested, Thanks!

In R, IDTaxa is the one I would suggest trying. But you can also use any program you want outside of R as well. You can write out the DADA2 ASVs to a fasta file, and then operate on them with other programs (as long as they can read fasta files).

**Comment by Aircus** [comment]
> > Are there any other algorithms/functions compatible with DADA2? I will also try IDTaxa as you suggested, Thanks!
> 
> In R, IDTaxa is the one I would suggest trying. But you can also use any program you want outside of R as well. You can write out the DADA2 ASVs to a fasta file, and then operate on them with other programs (as long as they can read fasta files).

Ok, thanks a lot!
I will try that

Best
Tong
