### ISSUE TITLE
Verifying presence and orientation of ITS primers 

### ISSUE THREAD

**Issue by kbealsmicrobe** [benjjneb/dada2#873]
I am following the dada2 ITS amplicon processing tutorial, and have run into a problem in the identifying primers stage, where my forward primer is found in the forward reads in its reverse orientation and in the reverse reads in its forward orientation (see attached). The tutorial shows that the forward primer should be found in the forward reads in its forward orientation and in the reverse reads in its reverse-complement orientation.   
![dada2_ITS_screenshot](https://user-images.githubusercontent.com/56979594/67521587-301a0c80-f679-11e9-9dc9-4040ebd2665b.png)

**Comment by benjjneb** [comment]
You can think of it this way: In your datasets the REV primer is on the forward reads. So... treat that as the FWD primer in the tutorial (which was also found on the forward reads in forward orientation).

Your FWD primer is found on the reverse reads in its forward orientation. So... treat that as the reverse complement of the REV primer in the tutorial (which was found on the reverse reads).

So everything is OK, you just need to replace FWD with REV, and replace rc(REV) with FWD in the tutorial going forward, and things should work as expected. But double-check after running cutadapt... you should see the primers all gone (all 0s or close to it above).

**Comment by kbealsmicrobe** [comment]
1) Would I do this after the identifying primers step? 
2) Would it be: FWD <- FWD.orients[["Reverse]] and RevComp <- Rev.orients[["Forward"]]

**Comment by benjjneb** [comment]
> FWD <- FWD.orients[["Reverse]] and RevComp <- Rev.orients[["Forward"]]

```
FWD <- REV
REV <- FWD
```

You would do it after the identifying primers, and before doing the cutadapt block.

**Comment by kbealsmicrobe** [comment]
Great, thank you!

Unfortunately now, however, my "cutadapt" file is not filling with the sequences. I am able to create my "cutadapt" folder:
path.cut <- file.path(path, "cutadapt")
if(!dir.exists(path.cut)) dir.create(path.cut)

But for whatever reason, the folder stays empty after I run cutadapt:
for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, 
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], 
                             fnFs.filtN[i], fnRs.filtN[i])) 
}

**Comment by benjjneb** [comment]
Do you have cutadapt installed and in your path? What did you define as the `cutadapt` variable? 

The system2 call is calling a command line application, so you have to have cutadapt installed and have the correct path to it defined.

**Comment by kbealsmicrobe** [comment]
I have cutadapt installed. system2(cutadapt, args = "--version") verified that I have the most updated version, 2.6. 

I found cutadapt in my path I had listed: "/Users/kendallb/miniconda3/bin/cutadapt"

What do you mean by "cutadapt variable?"

**Comment by benjjneb** [comment]
> I have cutadapt installed. system2(cutadapt, args = "--version") verified that I have the most updated version, 2.6.

OK, that indicates you do have the right path then.

The next guess would be that you have somethiing wrong with your paths. What are the results of:

```
head(cbind(fnFs, fnFs.filtN, fnFs.cut))
head(cbind(fnRs, fnRs.filtN, fnRs.cut))
table(file.exists(fnFs))
table(file.exists(fnFs.filtN))
table(file.exists(fnFs.cut))
```

**Comment by kbealsmicrobe** [comment]
When I started working in my shell, I noticed a typo in my working directory path. I re-ran the tutorial after editing the working directory path, and got everything to run smoothly. Thanks for all the help! I now have identified fungi in my samples!

**Comment by marclliros** [comment]
Dear all
thanks for dada2 program and tutorials and community.
Just to verify that I understood correctly my ITS pipeline output
> rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.filtN[[1]]), FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.filtN[[1]]), REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.filtN[[1]]), REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.filtN[[1]]))
                 Forward Complement Reverse RevComp
FWD.ForwardReads       0          0       0       0
FWD.ReverseReads       0          0       0  178716
REV.ForwardReads       0          0       0  212053
REV.ReverseReads       0          0       0       0
> 

That looks like my reads are all in "reverse" mode, right?
Accordingly I should change forward by reverse and reverse by forward but not by rc(FWD) before cutadapt run

Thanks for all

Marc

**Comment by benjjneb** [comment]
@marclliros No, that looks fine. It seems like your data does not contain primers at the start of the reads (hence the 0s in the top-left/bottom-left). The reverse complement of the opposite primer is showing up on many reads (the big numbers in the right column) which is expected when the reads are longer than the amplified sequence, as then the read "reads into" the primer at the end.

As long as the ITS region you are sequencing is sometimes shorter than the read length you are using, this data looks OK.

**Comment by marclliros** [comment]
> 

@benjjneb thanks a lot for the quick replay and positive insights!
Awesome!

**Comment by marclliros** [comment]
> @marclliros No, that looks fine. It seems like your data does not contain primers at the start of the reads (hence the 0s in the top-left/bottom-left). The reverse complement of the opposite primer is showing up on many reads (the big numbers in the right column) which is expected when the reads are longer than the amplified sequence, as then the read "reads into" the primer at the end.
> 
> As long as the ITS region you are sequencing is sometimes shorter than the read length you are using, this data looks OK.

@benjjneb thanks a lot for the quick replay and positive insights!
Awesome!
