### ISSUE TITLE
An error was encountered while running DADA2 in R (return code -11)

### ISSUE THREAD

**Issue by Alenap26** [benjjneb/dada2#874]
Hello, 
I'm trying to run:
```
qiime dada2 denoise-paired \
  --i-demultiplexed-seqs paired-end-demux.qza \
  --p-trunc-len-f 1 \
  --p-trunc-len-r 1200 \
  --o-representative-sequences rep-seqs-dada2.qza \
  --o-table table-dada2.qza \
  --o-denoising-stats stats-dada2.qza \
  --verbose 
```

but these lines provided the follow error:
`Running external command line application(s). This may print messages to stdout and/or stderr.
The command(s) being run are below. These commands cannot be manually re-run as they will depend on temporary files that no longer exist.

Command: run_dada_paired.R /var/folders/pd/pypspsts0ws8y40wwky7j3d00000gp/T/tmple2vmcv8/forward /var/folders/pd/pypspsts0ws8y40wwky7j3d00000gp/T/tmple2vmcv8/reverse /var/folders/pd/pypspsts0ws8y40wwky7j3d00000gp/T/tmple2vmcv8/output.tsv.biom /var/folders/pd/pypspsts0ws8y40wwky7j3d00000gp/T/tmple2vmcv8/track.tsv /var/folders/pd/pypspsts0ws8y40wwky7j3d00000gp/T/tmple2vmcv8/filt_f /var/folders/pd/pypspsts0ws8y40wwky7j3d00000gp/T/tmple2vmcv8/filt_r 1 1200 0 0 2.0 2.0 2 consensus 1.0 1 1000000

R version 3.5.2 (2018-12-20) 
Carico il pacchetto richiesto: Rcpp

 *** caught segfault ***
address 0x18, cause 'memory not mapped'

Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
 3: loadNamespace(package, lib.loc)
 4: doTryCatch(return(expr), name, parentenv, handler)
 5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 6: tryCatchList(expr, classes, parentenv, handlers)
 7: tryCatch({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps)}, error = function(e) {    P <- if (!is.null(cc <- conditionCall(e)))         paste(" in", deparse(cc)[1L])    else ""    msg <- gettextf("package or namespace load failed for %s%s:\n %s",         sQuote(package), P, conditionMessage(e))    if (logical.return)         message(paste("Error:", msg), domain = NA)    else stop(msg, call. = FALSE, domain = NA)})
 8: library(pkg, character.only = TRUE, logical.return = TRUE, lib.loc = lib.loc,     quietly = quietly)
 9: .getRequiredPackages2(pkgInfo, quietly = quietly)
10: library(dada2)
11: withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning"))
12: suppressWarnings(library(dada2))
An irrecoverable exception occurred. R is aborting now ...
Traceback (most recent call last):
  File "/Users/Alessandro/anaconda3/envs/Metagenomics/lib/python3.6/site-packages/q2_dada2/_denoise.py", line 234, in denoise_paired
    run_commands([cmd])
  File "/Users/Alessandro/anaconda3/envs/Metagenomics/lib/python3.6/site-packages/q2_dada2/_denoise.py", line 36, in run_commands
    subprocess.run(cmd, check=True)
  File "/Users/Alessandro/anaconda3/envs/Metagenomics/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['run_dada_paired.R', '/var/folders/pd/pypspsts0ws8y40wwky7j3d00000gp/T/tmple2vmcv8/forward', '/var/folders/pd/pypspsts0ws8y40wwky7j3d00000gp/T/tmple2vmcv8/reverse', '/var/folders/pd/pypspsts0ws8y40wwky7j3d00000gp/T/tmple2vmcv8/output.tsv.biom', '/var/folders/pd/pypspsts0ws8y40wwky7j3d00000gp/T/tmple2vmcv8/track.tsv', '/var/folders/pd/pypspsts0ws8y40wwky7j3d00000gp/T/tmple2vmcv8/filt_f', '/var/folders/pd/pypspsts0ws8y40wwky7j3d00000gp/T/tmple2vmcv8/filt_r', '1', '1200', '0', '0', '2.0', '2.0', '2', 'consensus', '1.0', '1', '1000000']' died with <Signals.SIGSEGV: 11>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Alessandro/anaconda3/envs/Metagenomics/lib/python3.6/site-packages/q2cli/commands.py", line 327, in __call__
    results = action(**arguments)
  File "</Users/Alessandro/anaconda3/envs/Metagenomics/lib/python3.6/site-packages/decorator.py:decorator-gen-459>", line 2, in denoise_paired
  File "/Users/Alessandro/anaconda3/envs/Metagenomics/lib/python3.6/site-packages/qiime2/sdk/action.py", line 240, in bound_callable
    output_types, provenance)
  File "/Users/Alessandro/anaconda3/envs/Metagenomics/lib/python3.6/site-packages/qiime2/sdk/action.py", line 383, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/Users/Alessandro/anaconda3/envs/Metagenomics/lib/python3.6/site-packages/q2_dada2/_denoise.py", line 249, in denoise_paired
    " and stderr to learn more." % e.returncode)
Exception: An error was encountered while running DADA2 in R (return code -11), please inspect stdout and stderr to learn more.

Plugin error from dada2:

  An error was encountered while running DADA2 in R (return code -11), please inspect stdout and stderr to learn more.

See above for debug info.`

**Comment by benjjneb** [comment]
For the QIIME2 plugin, you are best served to look for assistance at the QIIME2 forum: https://forum.qiime2.org/

That said, your truncation lengths don't make sense. You're truncating the forward reads after 1nt, and the reverse reads after 1200? That's probably your problem.
