### ISSUE TITLE
How to build reference files for taxonomy assignment

### ISSUE THREAD

**Issue by saharbagheri** [benjjneb/dada2#879]
Dear All,

I was looking into the files generated as reference files for taxonomy assignment step used by dada2 (RDP, SILVA, GG). I am building the same using a custom reference database. Something that I didn’t understand was that there were more sequences in the species file compared to genus reference file. It makes more sense to me if there are equal or less number of sequences in the species file. Since there might be some sequences not assigned to species but genus level. 
Could you please guide me how you made the reference files that there are more sequences in the species file? This means that there are some sequences in the species file that are not represented in the genus file. Have you done something like clustering at a specific threshold? 
I really appreciate your help.

**Comment by benjjneb** [comment]
The curation processes are different for the taxonomy and species Silva training fastas. The taxonomy assignment fasta is based on the mothur-teams curated Silva training set, which is described here: http://blog.mothur.org/2018/01/10/SILVA-v132-reference-files/

The species assignment fasta uses a different process, and aims to keep every sequences with a consistent genus=species annotation, without setting any %Id threshold, which is probably why it has more sequences in it. The full details are availabe in code as part of the `dada2:::makeSpeciesFasta_Silva`, which is the code run to create the Silva species training fasta.
