### ISSUE TITLE
Removal of singletons in non-overlapping reads

### ISSUE THREAD

**Issue by dcastaneda5** [benjjneb/dada2#882]
Hi,

Thank you for such an amazing software. I was wondering if you guys could help me as I am trying to determine haplotypes across 20 samples with malaria. So far I have determined their amplicon sequence variants, however I am getting a number up to 200 or 250 variants which is more than I was expecting. I sequenced a 800 bp region with 2x250 illumina miseq in paired end mode (reads previously fragmented with nextera). I changed the concatenation to TRUE during the merging process but now I am getting more ASVs. Could it be that dada2 reconstructs these ASVs across many regions that span over the 800 bp, and thus I'm getting such a high number? Or does DADA2 performs haplotype reconstruction somehow? I was thinking to remove singletons and low abundance reads to remove noise, would that be a better approach? Thanks a lot!

**Comment by benjjneb** [comment]
Non-overlapping reads are simply concatenated without any check as to whether the reads really were coming from the same DNA molecule. Normally the requirement of matching over the overlap region ensures the paired reads really did come from a common DNA molecule, but with non-overlapping reads there is no similar enforcement. As a result, there do tend to be more residual low-abundance artefacts that can get through in non-overlapping reads. So you may want to consider a low-abundance filter.

Alternatively, there could also be more variation in these sequences than you expected.
