### ISSUE TITLE
Priors for paired end data

### ISSUE THREAD

**Issue by alexpiper** [benjjneb/dada2#883]
Hi Ben, 

I've seen from #496 that priors need to be provided in "amplicon" format, however i'm unclear how this works with paired end data. Do the priors have to match the reads exactly? in which case would i have to provide separate priors for forward and reverse reads as the dada inference comes before mergePairs?

Cheers,
Alex

**Comment by benjjneb** [comment]
> Do the priors have to match the reads exactly? in which case would i have to provide separate priors for forward and reverse reads as the dada inference comes before mergePairs?

Yes, that is the state of things at the moment. Progress towards making priors more flexible will show up on #496 

For standard 16S setups, where both forward and reverse reads are trucnated to a fixed length, this can be worked with though. Just cut out the forward `truncLen` bases after the forward primer, and the reverse `truncLen` bases prior to the reverse primer, and gives those as the priors (but remember to reverse-complement the reverse priors to match the orientation fo the reverse reads).

**Comment by alexpiper** [comment]
Thanks for the quick response Ben, I will proceed as suggested.
