### ISSUE TITLE
Multiplex dataset analysis

### ISSUE THREAD

**Issue by Melirax** [benjjneb/dada2#884]
Hi, 
I have a dataset corresponding to 380 samples (closely related species collected on different islands). We sequenced 10 genes per sample using a PCR multiplex + Illumina amplicon sequencing approach.
I have two questions:
- first, I know that dada2 has not been built for this, but can I use it knowing that our aim is to study the systematic/phylogeny of species?
- second, should I make the model learn errors on the overall dataset or should I "demultiplex" the sequences based on primer sequences first and make the model learn errors for each gene separately?

Thank you
Best regards

**Comment by benjjneb** [comment]
> first, I know that dada2 has not been built for this, but can I use it knowing that our aim is to study the systematic/phylogeny of species?

Yes. The core DADA2 method is totally agnostic about the specific genetic locus(i) being studied, and can be applied to any amplicon.

> second, should I make the model learn errors on the overall dataset or should I "demultiplex" the sequences based on primer sequences first and make the model learn errors for each gene separately?

I would recommend separating the reads out by sample at a minimum. Given that the different loci are completely separate, it would also make sense to separate out each locus as well, but the algorithm will actually work in essentially the same way even if you don't separate the loci.

**Comment by Melirax** [comment]
Hi, 
I am trying to adapt the its workflow to demultiplex the data based on each gene. For now, I've only tried with one gene. The primers are cut but all sequences are kept. From what I see in Cutadapt documentation one has to add  {name1}{name2} in the outputfile name to make it work.
When I do: 
`for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, 
                             "-o", {name1}-{name2}.fnFs.cut[i], "-p", {name1}-{name2}.fnRs.cut[i], 
                             fnFs.filtN[i], fnRs.filtN[i]))
}`

I get the following error:

Erreur : unexpected symbol in:
"  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, 
                             "-o", {name1}-{name2}.fnFs.cut"
>                              fnFs.filtN[i], fnRs.filtN[i]))
Erreur : ',' inattendu(e) in "                             fnFs.filtN[i],"
> }
Erreur : '}' inattendu(e) in "}"
>
 
Do you have any clue on what is wrong?

**Comment by benjjneb** [comment]
What is wrong is that `{name1}-{name2}.fnFs.cut[i]` is not a valid expression in R.

I think what you are trying to do is to generate a different output filename? If so, you will need to construct it out of strings in R. `fnFs.cut[i]` is a filename string, that is defined earlier in our workflow. You can prepend to that string, with e.g. `paste0("prepend_", fnFs.cut[i])`, but you need ot be using valid R string manipulation syntax.
