### ISSUE TITLE
Retracing which dereplicated sequences are put into which ASVs

### ISSUE THREAD

**Issue by lafrue** [benjjneb/dada2#889]
I wanted to create some rank-abundance curves with abundance information of dereplicated sequences. I checked the derep_fastq outputfile in my dada2 workflow and I was wondering where to get the information on which dereplicated amplicons are later then clustered in which ASVs. So what I basically want to know is which ASV consists of which dereplicated sequences and how many replicates there are for each dereplicated sequence.

**Comment by benjjneb** [comment]
Both `derep-class` and `dada-class` objects have a `$map` component, that provides the map from the raw reads to the dereplicated sequences, and from the dereplicated sequences to the denoised ASVs respectively.

So to get what you want, just inspect the `dadaObj$map` vector. It will be a vector of length the number of dereplicated sequences, with the nth value corresponding to the ASV to which the nth dereplicated sequence was mapped. `NA` values indicate that dereplicated sequence was discarded at the denoising step.
