### ISSUE TITLE
Formula for abundance

### ISSUE THREAD

**Issue by audy** [benjjneb/dada2#89]
Is abundance calculated as the number of reads per OTU (what are we calling it now) or the number of unique reads per OTU?

**Comment by benjjneb** [comment]
Abundances = # of **reads** assigned to the inferred sequence variant (SV)*

If you are interested in the number of **unique sequences** assigned to each SV, the dadaObj$clustering data.frame has that information (see dadaObj$clustering$nunq) along with other diagnostic info.

* or OTU if you prefer

**Comment by audy** [comment]
That's what I thought. I just couldn't find it in the docs. Thanks

--austin

**Comment by joey711** [comment]
On the nomenclature, see this thread:

https://github.com/benjjneb/dada2/issues/62

(very unlikely we're going to call it an OTU...)
