### ISSUE TITLE
index (forward and reverse) in merged output

### ISSUE THREAD

**Issue by mattoslmp** [benjjneb/dada2#890]
Dear Benjamin, I would like to ask a question about dada2,

I have a doubt about the step of merge:
Example code:
mergers_t1 <- mergePairs(dadaFs_t1, derep_forward , dadaRs_t1, derep_reverse, verbose=TRUE, trimOverhang=TRUE)

Example of part of my result, head (mergers):

abundance forward reverse nmatch nmismatch nindel prefer accept
6         176       3       6    100         0      0      2   TRUE
7         138       6      10    108         0      0      2   TRUE
8         137      13      12    104         0      0      2   TRUE
9         125       8      11    100         0      0      2   TRUE
10        125       1     137    102         0      0      1   TRUE
11        118       9       9    100         0      0      2   TRUE

I have distinct index (forward and reverse). Is this correct or any problem with it?

Thanks,
Leandro

**Comment by benjjneb** [comment]
This is very hard to interpret. What is you are concerned about? I think that you are seeing a lot of failed merging? More than you expected?

If my guess is close than basic information is needed such as: What amplicon are you sequencing? What primer set? What trimming/truncation parameters did you use?

**Comment by golrokh51** [comment]
It is 16s
V4-V5
This is my cutadapt command: cutadapt -a ^GTGYCAGCMGCCGCGGTAA...AAACTYAAAKRAATTGRCGG -A ^CCGYCAATTYMTTTRAGTTT...TTACCGCGGCKGCTGRCAC -m 200 -M 285  -o ../data/trimmed/${sample}_sub_R1_trimmed.fq.gz -p ../data/trimmed/${sample}_sub_R2_trimmed.fq.gz --untrimmed-output ../results/_cutadapt/${sample}_untrimmed_R1.fastq --untrimmed-paired-output ../results/_cutadapt/${sample}_untrimmed_R2.fastq $f1 $f2

I am loosing 50% in chimera removing step not lots in merging 

I really need some advice.
Is it ok not to remove chimera?

Thanks really 

Golrokh

**Comment by mdemmel** [comment]
Hello,

I had the same question as described above, so I hoped I could elaborate on my own data to clarify. I have paired-end V4 16S reads sequenced on a 2x250bp Miseq platform. I am using the big data analysis pipeline, and up to 50% of my reads are lost during the merge step, even after experimenting with many different filterAndTrim parameters, including varying truncation lengths. 

After looking at the top of the mergers object, I can see that many forward and reverse indices are mismatched:
abundance forward reverse nmatch nmismatch nindel prefer accept
         444       	1    	    1          87         	0     	0        1  	 TRUE
         251       	3    	    3         88         	0      	0        1  	 TRUE
         231      	2    	    2         87         	0      	0        1  	 TRUE
         166      	15   	    7         87         	0      	0        2  	 TRUE
         156       	5          4        88         	0      	0        2  	 TRUE
         155       	6          29      87         	0      	0        1  	 TRUE
         142       	7    	    5         87         	0      	0        1  	 TRUE
         139      	18  	    21       87         	0      	0        1  	 TRUE
         129      	23  	    22       87         	0      	0        1  	 TRUE
         118     	115      96       87         	0     	0        1  	 TRUE
         113     	107      108     87         	0     	0        1  	 TRUE
         111      	49       135      87        	0      	0        1  	 TRUE
        108       	2          71        87         	0      	0        1  	 TRUE

My understanding of the merge step is that the forward and reverse values should mostly be equivalent. Is this mismatch associated with the low yield of merged sequences, or am I misunderstanding what these forward and reverse indices represent?

Thanks!

**Comment by mdemmel** [comment]
Hello,

I had the same question as described above, so I hoped I could elaborate on my own data to clarify. I have paired-end V4 16S reads sequenced on a 2x250bp Miseq platform. I am using the big data analysis pipeline, and up to 50% of my reads are lost during the merge step, even after experimenting with many different filterAndTrim parameters, including varying truncation lengths. 

After looking at the top of the mergers object, I can see that many forward and reverse indices are mismatched:
<img width="598" alt="Screen Shot 2019-11-19 at 9 51 27 AM" src="https://user-images.githubusercontent.com/15065876/69156943-3487e880-0ab2-11ea-83e2-da2f87d5bc59.png">


My understanding of the merge step is that the forward and reverse values should mostly be equivalent. Is this mismatch associated with the low yield of merged sequences, or am I misunderstanding what these forward and reverse indices represent?

Thanks!

**Comment by benjjneb** [comment]
> My understanding of the merge step is that the forward and reverse values should mostly be equivalent.

Not necessarily. The index values represent the order in which each ASV was identified in the forward and reverse read data. While these often do line up fairly well for the most abundant ASVs, that correspondence can decay quickly, and there are lots of reasons that things get uncorrelated later on. So the kind of pattern you are seeing above does not indicate a problem, it looks pretty normal actually.

**Comment by mdemmel** [comment]
Ok, thanks very much. It's useful to know that the issue with merging is arising elsewhere.

**Comment by rainbow218** [comment]
Dear Benjamin,

I have a few question related to this topic. 
Is it normal to observe the number of unique ASVs after merging to be higher than the number of unique ASVs of dada forward and dada reverse object? 
Is information from fastq header of paired reads (ie. cluster coordinates within lane tiles) preserved and considered during the merging process? 

thank you for your kind attention,
Chan

**Comment by benjjneb** [comment]
@rainbow218 

> Is it normal to observe the number of unique ASVs after merging to be higher than the number of unique ASVs of dada forward and dada reverse object?

I'm not sure it's "normal", but it is not necessarily abnormal either. Especially with longer amplicons, there can be single forward ASVs that match with multiple reverse ASVs, because some variation exists only in the part of the gene covered by the reverse read.

> Is information from fastq header of paired reads (ie. cluster coordinates within lane tiles) preserved and considered during the merging process?

No.

**Comment by rainbow218** [comment]
@benjjneb 

thank you for your response, I have a follow up question:
How is the abundance of the merged ASVs determined? Is it based on the minimum ASV count out of the forward ASV and reverse ASV that is merged?

**Comment by benjjneb** [comment]
> How is the abundance of the merged ASVs determined?

On a read-by-read basis. Each read-pair is denoised, then merged if they overlap (perfectly by default).

**Comment by rainbow218** [comment]
@benjjneb 

For this following example:
![image](https://user-images.githubusercontent.com/54792999/95805729-a60afe00-0d38-11eb-96ea-6d96b110011b.png)
please correct me if my understanding is wrong: The abundance value of the first merged ASV is 24527, would either forward ASV index 1 or reverse ASV index 1 also have abundance of 24527? The other merged ASVs with forward ASV index 1 have different abundance values, hence those abundance values are coming from the Reverse ASVs?  

Thank you for your kind attention!

**Comment by benjjneb** [comment]
> would either forward ASV index 1 or reverse ASV index 1 also have abundance of 24527?

Probably neither. That abundance is the total number of paired reads where the forward member of the pair was denoised to FWD-ASV1 and the reverse reads was denoised to REV-ASV1.

It isn't clear from that data.frame, but those numbers come from read-by-read counting of the number of paired reads that were FWD-ASV1 -- REV-ASV1. The total number of forward reads denoised to FWD-ASV1, and the total number of reverse reads denoised to REV-ASV1, are probably different, since some of those will be paired to reads that denoised differently.
