### ISSUE TITLE
Separate training classifier from classifying to save time?

### ISSUE THREAD

**Issue by JCSzamosi** [benjjneb/dada2#893]
The `assignTaxonomy()` function takes a very long time to run, even when few sequences are being classified. I assume this is because it is constructing its kmer array or otherwise training the classifier anew each time. Would it be possible to separate these functions to speed up classification, since people do often assign taxonomy using the same database over and over.

**Comment by benjjneb** [comment]
This is a decent idea. It is possible, but it comes with some downsides (a less flexible and easily understood intermediate "trained" data object file).

This should probably be merged in with the larger issue on improving the performance and memory scaling of `assignTaxonomy` #239

**Comment by pooranis** [comment]
Yes, please!  I just went looking through the source code to see if I could save the reference classifier object separately, so I could then use it to iterate through a large number of sequences and deal with some memory issues I'm having.  

I don't think having a classifier object is a downside, as they are used in other bioconductor packages.  DECIPHER, for example, has a trained classifier you can download from their site to use with IdTaxa.  However, you could also use some abstraction, and just split apart the assignTaxonomy function underneath, so it still works the same way, but have the separate functions available for "advanced" users, so they can train the classifier separately and save the output.

**Comment by benjjneb** [comment]
Closing this in favor of the main tracking issue on `assignTaxonomy` performance improvements #239
