### ISSUE TITLE
losing lots of reads for only some samples in a run

### ISSUE THREAD

**Issue by pandan74** [benjjneb/dada2#895]
Hi All,
i have similar problem, but I have 2 type of samples in one run: lung and fecal. Fecal samples look just fine but for the the lung samples I lost almost all reads after chimera removing and merging:
[sequence_pipeline_stats.txt](https://github.com/benjjneb/dada2/files/3875851/sequence_pipeline_stats.txt)

Any suggestions?
This is 2x150 V4 fragment, all samples were processed and sequenced together. Demultiplexing was done with idemp.

_Originally posted by @pandan74 in https://github.com/benjjneb/dada2/issues/887#issuecomment-557180332_

**Comment by benjjneb** [comment]
That is a dramatic difference. Given this

> all samples were processed and sequenced together

I'm assuming that its not a difference in library design or primer removal between the sample types or anything similar. An alternative explanation could be in lung samples, which typically have a much lower bacterial biomass, that most of the DNA is from non-target sources, e.g. contaminants, or cross-contaminants or something.

If you take a look at the top 10 ASVs in a few lung samples, in just the forward reads or just the reverse reads (i.e. before merging) what do those look like? I.e. what taxonomy are they assigned? What does it look like when you BLAST those sequences against nt?

**Comment by pandan74** [comment]
I did blast several forward sequences from 2 different lung samples and most results were .... Mus musculus mitochondrion, complete genome. It makes sens now. I did not think to blast those seqs. Thank you.
