### ISSUE TITLE
Sequence length V3-V4

### ISSUE THREAD

**Issue by CRichard21** [benjjneb/dada2#896]
Hello,

I am novice in 16S sequencing analysis and I need some clarifications on the results I obtained with dada2.

I have 63 samples sequenced with primers Pro341F - Pro805R (PMID 25144201) with a MiSeq sequencer to generate reads of 284 bases x2 after primer trimming.

The quality of foward and reverse fastQ of two samples are as follow :

![Quality_Fs](https://user-images.githubusercontent.com/38983967/69480637-94132a80-0e09-11ea-9edf-af57545fe4b0.png)
![Quality_Rs](https://user-images.githubusercontent.com/38983967/69480642-9bd2cf00-0e09-11ea-8079-bf875ddd6c57.png)

I decided two use filterAndTrim as follow : 
`out <- filterAndTrim(fwd=fnFs, filt=filtFs, rev=fnRs, filt.rev=filtRs,
              trimLeft=10, truncLen=c(270, 200), maxN=0, maxEE=2,
              compress=TRUE, verbose=TRUE, multithread = FALSE)`

Giving a total length of 450 bases for a region of about 410 bases (after trimLeft=10). In average, 90% of reads passed the filter. 

However, after all the following steps, when I take a look at sequence length I get  :
![sequence_length](https://user-images.githubusercontent.com/38983967/69480844-54e5d900-0e0b-11ea-85b6-2cf0079f306c.PNG)

I really do not understand how can I have such a large range of length values. I thought I should have values around 407 bases. Is that right ? When I keep sequences from 402 to 412 bases, it only represents :

`sum(seqtab2)/sum(seqtab)
[1] 0.5912875`

Can you tell me if something goes wrong in my reasoning.

Thanks in advance,

Corentin

**Comment by benjjneb** [comment]
There's a bimodal length distribution of the V3V4 region in nature, which includes a shorter length mode ~385 bases long, which you are seeing in your data.

**Comment by CRichard21** [comment]
Thank you for your quick return ! 
Can you advice me a "cutting band" to use here ? And also, do the filtering parameters seem adapted to my data ?

Corentin

**Comment by benjjneb** [comment]
> Can you advice me a "cutting band" to use here ?

Roughly you want to keep the data within those two biological length modes, so something like 380-415 is probably reasonable, but you can inspect the ASVs outside that range to improve the exact cutoffs.

> And also, do the filtering parameters seem adapted to my data ?

They seem fine, it keeps enough overlap that even the long V3V4 ASVs are still merging properly.
