### ISSUE TITLE
Problem with uniquesToFasta with seqtab file 

### ISSUE THREAD

**Issue by mguid73** [benjjneb/dada2#899]
I'm trying to get a rep-seqs.fna file with the code below:
`uniquesToFasta(seqtab, fout= "seqtab_rep-seqs.fna", ids=colnames(seqtab))`
I keep receiving the error: 
`Error in getUniques(unqs, collapse = FALSE) : 
  Unrecognized format: Requires named integer vector, dada-class, derep-class, sequence matrix, or a data.frame with $sequence and $abundance columns.`
I think I've deduced that my seqtab file is not in the correct format. I've attached a screenshot of it here. Any advice for making my seqtab file recognizable to 'getUniques'? Do I need to add in headers? 
<img width="838" alt="Screen Shot 2019-11-26 at 10 09 23 AM" src="https://user-images.githubusercontent.com/42591287/69651406-a8d40600-1035-11ea-856c-bdc642628d33.png">

Thanks in advance, 
Megan

**Comment by benjjneb** [comment]
Are you able to read the seqtab file into R?
The ASV (or "representative") sequences are just the entires in the first column of your seqtab file.
If you get those as a charcter vector, you can output them to a fasta file with `writeFasta(ASVseqs, "outputfile.fna")`

**Comment by mguid73** [comment]
Oh, okay! I do have the seqtab file in R, and from there I can just pull out that first column and write into a fasta (just like you said). Thanks for the solution! It was a lot simpler than I was making it out to be.

**Comment by mguid73** [comment]
Checking in again. I ran the following lines:
`seqtab <- read.csv("seqtabtrans_clean.csv", sep = ",", comment.char = "", header = T)
ASVseq <- seqtab$X
writeFasta(ASVseq, "rep-seqs.fna")`

I received the following error message: 
`Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘writeFasta’ for signature ‘"factor"’`

Any ideas what this means?
Thanks.

**Comment by benjjneb** [comment]
A classic R annoyance. By default R converts character vectors into "factors" when it imports data, and without telling the user that's what it is doing.

This should work:

```
library(dada2)
writeFasta(as.character(ASVseq), "rep-seqs.fna")
```

**Comment by mguid73** [comment]
That did the trick. Thanks so much.

**Comment by mguid73** [comment]
Hello again. I've run into a challenge with the output of my rep-seqs.fna file. I believe when I used the 'writeFasta' function, it labels my feature sequences with numbers. See below. 

> head rep-seqs.fna 

> >1
> TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGTGCGTAGGCGGCCTTTTAAGTTGGATGTGAAAGCCCCGGGCTCAACCTGGGAACGGCATCCAAAACTGAGAGGCTAGAGTGCGGAAGAGGAGTGTGGAATTTCCTGTGTAGCGGTGAAATGCGTAGATATAGGAAGGAACACCAGTGGCGAAGGCGACACTCTGGTCTGACACTGACGCTGAGGTACGAAAGCGTGGGGAGCAAACAGG
> >2
> TACGTAGGGGGCGAACGTTGTTCGGAATCACTGGGCGTAAAGGGTGCGCAGGCTGCTCATCAAGTCAGTTGTGAAATTTCGTGGCTCAACCACGAAGCTGCTGCTGATACTGTTGGGCTAGAGTCATAGATAGAGGTAGCGGGAATTCCTGGTGTAGGAGTGAAATCTGTAGATATCAGGAGGAACACCAAGGGTGAAGACAAGCTACTGGGTAATGACTGACGCTGAGGCACGAAAGCTAGGGGAGCAAATGGG
> >3
> TACGGGAGTGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGCGTCCGCAGGCGGTCTTTTAAGTCTGCTGTTAAAGCGTGGAGCTTAACTCCATTTCGGCAGTGGAAACTGGAAGACTAGAGTGTGGTAGGGGCAGAGGGAATTCCCGGTGTAGCGGTGAAATGCGTAGATATCGGGAAGAACACCAGTGGCGAAGGCGCTCTGCTGGGCCATAACTGACGCTCATGGACGAAAGCCAGGGGAGCGAAAGGG
> >4
> TACATAGGGTGCAAGCGTTATCCGGAATTATTGGGCGTAAAGCGTTCGTAGGCGGTTTATTAAGTCTGAAGTTAAAGCTCGGTGCTCAACACCGACCCGCTTTGGATACTGATAGACTAGAGTTATATAGAGGTTAGCGGAACTCCATGTGAAGCGGTGGAATGCGTAGATATATGGAAGAACACCAATGGCGAAGGCAGCTAACTGGATATACACTGACGCTGAGGAACGAAAGCGTGGGGAGCAAACAGG
> >5
> TACGGGAGTGGCAAGCGTTATCCGGAATTATTGGGCGTAAAGCGTCCGCAGGCGGTCTTGTAAGTCTGTTGTTAAAGCGTGGAGCTTAACTCCATTTCAGCAATGGAAACTGTAAGACTAGAGTGTGGTAGGGGCAGAGGGAATTCCCGGTGTAGCGGTGAAATGCGTAGATATCGGGAAGAACACCAGTGGCGAAGGCGCTCTGCTGGGCCATAACTGACGCTCATGGACGAAAGCCAGGGGAGCGAAAGGG

In QIIME2 I did the follow steps successfully:

> ##import rep-seq .fna file (made in the project dir) into Qiime2
> qiime tools import \
> --input-path rep-seqs.fna \
> --type 'FeatureData[Sequence]' \
> --output-path rep-seqs.qza
> 
> qiime tools export taxonomy.silva.qza --output-dir taxonomy-with-spaces
> qiime metadata tabulate --m-input-file /work/mguid73/work_fall2019OysterMicrobiome/taxonomy-with-spaces/taxonomy.tsv --o-visualization taxonomy-as-metadata.qzv
> qiime tools export taxonomy-as-metadata.qzv --output-dir taxonomy-as-metadata
> qiime tools import --type 'FeatureData[Taxonomy]' --input-path taxonomy-as-metadata/metadata.tsv --output-path taxonomy-without-spaces.qza
> qiime taxa filter-table --i-table table.qza --i-taxonomy taxonomy-without-spaces.qza --p-include 'D_0__Bacteria;D_1__' --o-filtered-table table-with-phyla.qza

On the last line(taxa filter-table), I received an error saying:
```
Plugin error from taxa:
  All features ids must be present in taxonomy, but the following feature ids are not: CACGTAGGATCCGAGCGTTATCCGAATTTACTGGGCGTAAAGCGCGTGTAGGCGGTCAGGTAAGTTGGACGTGAAAGCTCCTGGCTCAACTAGGAGAGGTCGTTCAAAACTGCCGGACTAGAGGGCGACAGAGGGAGGTGGAATTCCCGGTGTAGTGGTGAAATGCGTAGATATCGGGAGGAACACCAGTGGCGAAGGCGGCCTCCTGGGTCGCACCTGACGCTCAGACGCGAAAGCTAGGGGAGCGAACGGG, TACGAAGGGGGCTAGCGTTGTTCGGAATTACTGGGCGTAAAGGGTACGCAGGCGGTCTATCAAGTCAGGGGTGAAATCCCGGAGCTCAACTCCGGAACTGCCTTTGAAACTGGTAGACTAGAGTCCGAGAGAGGATGGTGGAATTCCTAGTGTAGAGGTGAAATTCGTAGATATTAGGAGGAACACCGGTGGCGAAGGCGGCCATCTGGCTCGGTACTGACGCTGAGGTACGAAAGCGTGGGGAGCAAACAGG, TACGTAGGTGGCAAGCGTTGTCCGGAATTATTGGGCGTAAAGCGCGCGCAGGCGGTTTCTTAAGTCTGATGTGAAAGCCCACGGCTCAACCGTGGAGGGTCATTGGAAACTGGGGAACTTGAGTGCAGAAGAGGAAAGTGGAATTCCACGTGTAGCGGTGAAATGCGTAGAGATGTGGAGGAACACCAGTGGCGAAGGCGACTTTCTGGTCTGTAACTGACGCTGAGGCGCGAAAGCGTGGGGAGCAAACAGG, CACGAACTGTGCAAACGTTATTCGGAATTACTGGGCTTAAAGAGTTCGTAGGCGGCTCGGTTAGTCGGGTGTGAAATCCCCCAGCTCAACTGGGGAACTGCGCTCGATACTGCCGAGCTTGAGGGAGATAGAGGTGAGCGGAACTGATGGTGGAGCGGTGAAATGCGTTGATATCATCAGGAACACCGGTTGCGAAAGCGGCTCACTGGGTCTCTTCTGACGCTGAGGAACGAAAGCTAGGGGAGCAAACGGG, TACGGAGGGTGCAAGCGTTATCCGGATTTATTGGGTTT....
```

When I look at my 'taxonomy.tsv' file (shown below), it has the feature-ID listed as numbers instead of the sequences in the rep-seqs file. My 'table.qza' has the sequences listed as the OTU IDs and the filter-table function can't match up the numbers in the taxonomy file to the sequences in the table.qza file. 
<img width="588" alt="Screen Shot 2019-12-05 at 12 37 49 PM" src="https://user-images.githubusercontent.com/42591287/70264091-601afc00-175d-11ea-9c5c-5115635c3644.png">

Is there a way to write out the rep-seqs file so that QIIME can still recognize the sequences?
Thanks in advance!

**Comment by benjjneb** [comment]
Just assign what you want as the ids to the `names` of the sequences. I.e.

```
foo <- as.character(ASVseq)
names(foo) <- my.fasta.ids
writeFasta(foo, "myfile.fa")
```

I don't know what the IDs exactly are the QIIME2 is expecting though, so you might need to check with them on that.
