### ISSUE TITLE
plotQualityProfile documentation improvement

### ISSUE THREAD

**Issue by michberr** [benjjneb/dada2#90]
Hi @benjjneb, 

I'm having lots of fun playing with dada2! I would suggest some additional documentation for the `plotQualityProfile` function. It's not clear what each of the orange/green lines are. I had to look at the source code to determine that the green line was the mean, orange is the Q50, and the dashed orange are the Q25 and Q75. Seems obvious enough now, but there's no reason to make a new user think for an extra minute about this. 

Do you think this should be added to the tutorial, doc pages, or both?

**Comment by spholmes** [comment]
Thanks so much Michelle,
We will also add it to the Bioconductor workflow caption in the
F1000Research paper,
all improvements welcome!!
Susan

On Mon, Jul 11, 2016 at 9:52 AM, Michelle Berry <notifications@github.com>
wrote:

> Hi @benjjneb <https://github.com/benjjneb>,
>
> I'm having lots of fun playing with dada2! I would suggest some additional
> documentation for the plotQualityProfile function. It's not clear what
> each of the orange/green lines are. I had to look at the source code to
> determine that the green line was the mean, orange is the Q50, and the
> dashed orange are the Q25 and Q75. Seems obvious enough now, but there's no
> reason to make a new user think for an extra minute about this.
>
> Do you think this should be added to the tutorial, doc pages, or both?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/benjjneb/dada2/issues/90>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABJcvWq0_L6T3BDc-x7HE5JYFyJO4uF1ks5qUnTdgaJpZM4JJkGs>
> .
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Samter Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by benjjneb** [comment]
Thanks for the suggestion.

Definitely should be in the doc pages. Probably the tutorial as well.

**Comment by benjjneb** [comment]
Improved `plotQualityProfile` documentation as suggested: a5f683e67b57a08ed12cef55926e4611877b72c9
