### ISSUE TITLE
Orientation mixups DADA2 ITS

### ISSUE THREAD

**Issue by marz29** [benjjneb/dada2#905]
Hi, the sequences I'm working with got the following orientation mixups in the workflow. 
![Captura de Pantalla 2019-12-06 a la(s) 14 04 36](https://user-images.githubusercontent.com/56695673/70352708-5d89d680-1831-11ea-9d4b-58616edbb5d8.png)

I'm pretty new at this so i don't understand in which part of the pipeline I need to include  "(REV <- REV.orient[["RevComp"]])" or other commands in order to have my reads in the correct orientation

**Comment by benjjneb** [comment]
What's the mixup? The forward orientation of the FWD primer is on the forward reads, and the forward orientation of the REV primer is on the reverse reads. That's what is typically expected, and the same as seen in the ITS tutorial.

**Comment by marz29** [comment]
I misunderstood that part of the tutorial. I thought that could be the problem when I still have presence of primers in my cutadapt-ed reads
