### ISSUE TITLE
addSpecies shouldn't need to rely on the first part of binomial name matching the genus in lineage

### ISSUE THREAD

**Issue by wbazant** [benjjneb/dada2#907]
I have been investigating the taxonomy in SILVA 132, and how it builds on the NCBI taxonomy for unknown samples. It is sometimes self-inconsistent (e.g. AX201179.1.1500 and HV226634.1.1500 in file `SILVA_132_SSURef_Nr99_tax_silva.fasta.gz` assign genus `Enterovibrio` to a species `Vibrio cholerae`, and most of the other entries assign the canonical genus `Vibrio`) but I think the SILVA lineages are overall better than NCBI lineages, and I would like to use them consistently as far as possible.

Sometimes SILVA lineages don't conform to the convention `addSpecies` requires, even when they are provided consistently - either with no ambiguity, or same lineage is provided for a species in over half of the headers.
Here's a list:
[silva_132.species_to_lineage.txt](https://github.com/benjjneb/dada2/files/3945978/silva_132.species_to_lineage.txt)
Out of 138746 species in this file, I count 56872 species where addSpecies would be unable to work using 
```
 perl -nE 'chomp; /^(.*?) .*?;([^;]*)$/ and $1 ne $2 and say'  silva_132.species_to_lineage.txt | wc -l
```

A few examples currently missed are
- `E. coli` (you already handle it with a special case)
- `'Brenneria populi' Hauben et al. 1998`, genus Brenneria
- chloroplasts (order `Chloroplast`, named after corresponding plant species)
- species marked under genus `Acetivibrio` in NCBI that SILVA assigns to other genera

Counterexamples are species like `unidentified bacterium` or `wallaby gut metagenome` - SILVA does not consistently assign a lineage to them.

This issue aims to achieve improving addSpecies' ability to add species. It proposes letting addSpecies reference fasta contain a lineage after the tab, e.g.
```
>Escherichia coli	Bacteria;Proteobacteria;Gammaproteobacteria;Enterobacteriales;Enterobacteriaceae;Escherichia/Shigella
```
It suggests to change the current code as follows:
- do not reject headers containing `;` if they also contain a tab
- if an asv matches a reference for which lineage is provided, and a lineage for the asv up to genus level matches the lineage, also assign species to the asv based on the reference
- if lineage is provided but doesn't match, do not assign anthing new to the asv
- If the lineage is not present for a reference, preserve the current behaviour of relying on the first part of the binomial name

Do you think this is a good solution? I am considering changing it locally, and I am also happy to submit a patch to the project - but before I start, I wanted to check with you what you might think -  if you see any problems with such solution, whether there could be a better one, and if it matters to be able to assign all these non-canonically named species.

**Comment by benjjneb** [comment]
This is great that you are looking more closely into this, and I have no doubt that the current way we digest the Silva db to produce the species-assignment reference db could be improved. First off, I wanted to make sure you had seen the code that does this currently, which is included in the dada2 package as the unexported function dada2:::makeSpeciesFasta_Silva: https://github.com/benjjneb/dada2/blob/master/R/taxonomy.R#L534 

Another historical note, one important reason we included the requirement for matching the binomial genus and the lineage genus was because in the past there have been errors in Silva releases, including one that assigned the same genus-species binomial to every entry in the database that didn't already have one. Without the consistency check, this resulted in a grossly incorrect species assignment reference fasta. Hopefully that won't happen again, but it has added to our caution.

On the specific changes you are suggesting:

> do not reject headers containing ; if they also contain a tab

The key part of this functionality that needs to be maintained is detecting when the assignTaxonomy database is provded to assignSpecies, and giving a useful error message when that happens. That is a common little mistake in practice.

> if an asv matches a reference for which lineage is provided, and a lineage for the asv up to genus level matches the lineage, also assign species to the asv based on the reference

This could be a preferable behavior, but I would want to see an evaluation of the accuracy of new species names added this way in practice. Are the new genus-species binomials generated this way appropriate in most cases?

> if lineage is provided but doesn't match, do not assign anthing new to the asv

Sure.

> If the lineage is not present for a reference, preserve the current behaviour of relying on the first part of the binomial name

Sure.

> Do you think this is a good solution? I am considering changing it locally, and I am also happy to submit a patch to the project - but before I start, I wanted to check with you what you might think - if you see any problems with such solution, whether there could be a better one, and if it matters to be able to assign all these non-canonically named species.

What I would suggest if you want to contribute to the project (which would be great) is to separate this into two things.  (1) A different digestion of the Silva database that preserves more entries, preferably that works with the current `assignSpecies` code. (2) An R-based implementation of the new `addSpecies` genus-matching proposed. This could leverage the current `assignSpecies` code, and then additional code that perhaps reads in auxiliary data on the lineages of the entries in the species assignment database and then performs the `addSpecies` logic of combining (or not) the species-assignments with the lineages from `assignTaxonomy`.

**Comment by wbazant** [comment]
(https://github.com/benjjneb/dada2/issues/912#issuecomment-575244315 related)

I agree that it would be really valuable to consider a different digest format of the reference database.

For example, I think that skipping species that don't have one lineage would ideally be done while digesting the database, same as skipping species named ".* sp. " or "unidentified/uncultured bacterium".

I think the whole thing is being made a bit more difficult than it needs to be by assuming the Linnean taxonomy, i.e. treating taxonomic lineages as "Kingdom, Phylum..., Genus, Species" tuples instead of  arbitrary paths in the taxonomy tree. I originally thought that assigning Kingdoms to ASVs helps with then assigning Phyla, etc. but as far as I understand the k-mer method DADA2 uses, it's not the case, right?. 

I'm struggling to propose something complete, because it would have to involve changing the package API. The format of files it accepts as reference feels like a big thing to change (even though it would be possible to provide backwards compatibility), and I feel discussing this with you would be beneficial first.

So starting from the format of reference files, a proposal would be
```
train_set.fa
>lineage;
[ACTG]+
...

species_assignment.fa
>lineage;species;
[ACTG]+
```
changing these:
- lineage can be arbitrary string, even if it has lots of ;s , like the lineages for Eukaryota in SILVA
- no sequence ID in species_assignment.fa
- lineage present in species_assignment.fa

The final output would either be unchanged, or the user would be given a function to convert from lineage strings to Linnean tuples after assignTaxonomy / addSpecies.

The burden of preparing the reference files well would sort-of still be on users, but `dada2` would still help by preparing pre-processed reference files from major databases like currently.

**Comment by benjjneb** [comment]
A couple things: The RDP naive Bayesian classifier assumes a fixed number of taxonoimc levels, and thus cannot accept arbitrary numbers of ";" in the ID strings of the training file. Unless a new assignment method is being implemented, that is a hard requirement, and lineage cannot be an arbitrary string.

The idea that lineage;species might be more inclusive is fine, but from what you have described I am unconvinced that this would result in (a) better digestion of the Silva db if we account for the possibility of errors there and (b) more useful results in the cases in which we reject those entries for the disagreement at the genus level between the lineage and the genus-species binomial name.

What you're describing are significant changes. That doesn't mean they are wrong, and I understand the motivation behind some of this, but those changes need to be supported by evidence that they do better before they can be considered as potential new defaults.

**Comment by wbazant** [comment]
Thank you for considering the proposal and giving a thoughtful answer!
> The RDP naive Bayesian classifier assumes a fixed number of taxonomic levels

This was the crux for me, I've spent some time trying to understand this, went to read the code and the paper and stuff, and then it found that "For higher-rank assignments, we sum the results for all genera under each taxon." (pmid 17586664) which I imagine could work for any tree - am I missing a reason for which the fixed number of taxonomic levels is needed for the RDP naive Bayesian classifier to work?

The software engineer in me always cheers for more general solutions to problems and addressing edge cases when I see one: a more general solution has less potential for errors, opens more space for development on top of it, etc. -  but totally, it's not a very strong reason and not sufficient for a scale of the change.

Pragmatically, the species where genus isn't the scientific name seem mostly to be the weird or rare ones, and the ability to identify them down to a species level in a sample from a child's diaper or whatever, using a method giving data resolution that is barely sufficient for identifying individual species, may not be very important.
I'm not sure if the matches can get worse, although I might be overlooking something: since addSpecies uses an identity match, it can only get better when it matches to a more inclusive set?

I don't know how rarely the rare species come up in datasets, but I'm very interested! I'll try to generate some data on this, to try answer whether `dada2` being able to call all 138746 species in SILVA instead of the current 56872 would actually improve anyone's results.

**Comment by benjjneb** [comment]
> I don't know how rarely the rare species come up in datasets, but I'm very interested! I'll try to generate some data on this, to try answer whether dada2 being able to call all 138746 species in SILVA instead of the current 56872 would actually improve anyone's results.

I would be very interested in your results, positive, or negative!

**Comment by wbazant** [comment]
So I have some results (that I can link here) that has, all together:
```
384917 ASVs
211683 had a genus
14000 had a species assigned through `addSpecies`
```

I did some multiple sequence alignments that check that the ASVs assigned to species actually match, which mostly checked that I used `dada2` correctly as opposed to anything about `dada2` and it all worked: they do align back to reference sequences and so on.

I've not gotten anywhere hunting for rare species, and I've lost the logs that say the fraction of species lost between `assignSpecies` and `addSpecies` calls. I could run `assignSpecies` on the 211683-14000 ASVs and see how many would additionally be picked up, but I'm not sure what I'd do afterwards: would it be a conclusive result that resolving this issue is a good idea if e.g. it found 2000 more species?

**Comment by benjjneb** [comment]
> would it be a conclusive result that resolving this issue is a good idea if e.g. it found 2000 more species?

That alone wouldn't be enough. There would need to be some measure of quality of those additional assignments. I.e. what is the evidence that XX% of the additional assignments are correct?

**Comment by wbazant** [comment]
I believe the correctness of the assignments does not change depending on what the species are named - the algorithm used in `assignSpecies` does not need to change for this issue to be resolved. I am just searching for a way to remove the loss of information between `assignSpecies` and `addSpecies` which happens because matching species names to lineages based on the species' generic names can not work fully reliably.

If I understand the history of the project well, `assignSpecies` and `addSpecies` is relatively new - assigning to species used to happen like assigning other levels of the taxonomy, until that paper which showed it is not reliable to base species assignments on k-mers, so you implemented an exact / substring match using PDict. I don't know why this format for a reference species assignment was chosen - maybe to make the two reference files sufficiently different that people won't confuse them?

I wanted to propose some way to measure this loss of information that currently happens, to help considering this issue from a software engineering perspective: whether addressing the issue has enough value to make it worth making the change.

**Comment by benjjneb** [comment]
> If I understand the history of the project well, assignSpecies and addSpecies is relatively new - assigning to species used to happen like assigning other levels of the taxonomy, until that paper which showed it is not reliable to base species assignments on k-mers, so you implemented an exact / substring match using PDict. I don't know why this format for a reference species assignment was chosen - maybe to make the two reference files sufficiently different that people won't confuse them?

You are perceptive! Yes, to all of that.

> I wanted to propose some way to measure this loss of information that currently happens, to help considering this issue from a software engineering perspective: whether addressing the issue has enough value to make it worth making the change.

I defiinitely think there is space to make this better. As you've noticed, there is some inefficiency in what we do that is basically just historical. However, as I noted in the pull request, treating species+strain as species is not the answer. That't not to say that at least allowing strain to be reported is bad, that would be good really, but that treating those strain strings like a "principled" taxonomic level is too much.

> I am just searching for a way to remove the loss of information between assignSpecies and addSpecies which happens because matching species names to lineages based on the species' generic names can not work fully reliably.

I'm very open to better ideas about how to harmonize better between species assignment and full tax lineages, especially in Silva (which I think is the best db going by a margin).

**Comment by salix-d** [comment]
If the fasta file for the species assignment could retain the data for the other taxonomic ranks (possibly in one chunk, to leave genus and species seperate and easy to extract), when using `addSpecies()` and the genus from the taxonomy (assigned with `assignTaxonomy()`) is NA, that extra taxonomic data could be parse to check if it match other taxonomic level, or simply to replace them all.

For example :
ref file could be formated like :
```
>Kingdom;Phylum;Class;Order;Family Genus Species
AATTCGGCAGCGGGATTTTAGAGCGAGTTGGCCCAAAAGGT
```
Then assignSpecies changed to return a matrix with 3 columns instead of two (taxInfo, genus, species) .
And then addSpecies changed so when `is.na(tax.gen)`, `strsplit(taxInfo, ";|>")[[1]][-1]` would give the full taxonomy, and then the function could try to match it to the lineage (or just overwrite them).

**Comment by benjjneb** [comment]
As an update, due to conversations with the Silva developers, there will be some potentially fundamental changes to come in how we parse and interpret the species binomials in the Silva db (which are NOT part of the official Silva taxonomy). More to come.
