### ISSUE TITLE
losing sequences with shorter target region 

### ISSUE THREAD

**Issue by lafrue** [benjjneb/dada2#908]
I am currently evaluating a Illumina MiSeqdataset targeting the V9 region of 18S rDNA targeting protists and I am specifically interested in species with a very short hypervariable region (only 96bp), whereas all other organisms have about 110-120 bp variable region length. When I do the dada workflow, in the later taxonomic assignment, I have no genomic traces and no ASVs corresponding to my target species, although it is the most abundant species in morphological observations, so it HAS to be in the dataset. Any idea how to solve this and not lose the sequences that are shorter then the normal region? I guess I cannot trim the longer sequences to the length of my target organism....

**Comment by benjjneb** [comment]
Is this paired-end sequencing, or single-read? What parameters are you using for the `filterAndTrim` step?

**Comment by lafrue** [comment]
its paired end, two files (R1 and R2) with about 200 bp length. For cutting I used truncLen of 90 nucleotides and maxEE of 2 for both fwd and rev reads

**Comment by benjjneb** [comment]
I'm not sure, those truncation parameters should work fine given the numbers you've described. Can you confirm that sequences are in the raw data? You can do the following:

```
sq <- "ACGTACGT" # REPLACE with the V9 sequence of this organism
drpF <- derepFastq("example_FWD_reads.fastq")
reads.drp <- getSequences(drpF)
ham <- unname(nwhamming(sq, reads.drp, vec=TRUE))
sort(ham)[1:10]
```

If the organism is really there, you should see some very low hamming distance show up from the above, which aligns the target sequence to all the (dereplicated) reads in an example file, and reports the smallest hamming distances between among those alignments.

**Comment by lafrue** [comment]
Hi Benjamin, thanks for your advice. I tried the command and got the following output for the "ham" object. The 0 means that there us 0 hamming distance. Also, I checked already for that V9 seq in the raw fastqfiles and they are present. 
![ham_object](https://user-images.githubusercontent.com/55782737/70866189-f376dd00-1f66-11ea-8d0a-a1989e479fe5.png)

**Comment by benjjneb** [comment]
Yes that should mean that the sequence is present in the data. Next, can you output those sequences with the zero hamming distance? 

```
# Run code from comment above, then...
dada2:::pfasta(reads.drp[ham==0], ids=drpF$uniques[ham==0])
```

**Comment by lafrue** [comment]
I got rid of the problem by just using te forward R1 files, since they had such good quality there was no need for overlapping the paired end reads and i got full coverage of the 120ish bp V9 region AND the target organism is present and abundant ! 
The output of the command gave a list of 501 sequences with zero hamming distance. So I guess case closed :) Thank you!
