### ISSUE TITLE
454 dada2

### ISSUE THREAD

**Issue by Balakulandai** [benjjneb/dada2#909]
Hi 
I am new to dada2, I have demultiplexed 454 sequence contain 20 samples. I am not able to adapt the illumina workflow so any one can send the script. It would be timely help and very helpful.
Please help me in this issue.

Thank you for your valuable time.

**Comment by dswan** [comment]
https://benjjneb.github.io/dada2/faq.html#can-i-use-dada2-with-my-454-or-ion-torrent-data
