### ISSUE TITLE
Out of memory..

### ISSUE THREAD

**Issue by mtsiknia** [benjjneb/dada2#91]
Hi!!
First of all, thank you for dada2!!
I want to use dada2 pipeline for my project (I have 113 samples for 16S) but my laptop's ram (8GB) is not enough for analyzing all samples at once. I was wondering if I can separately run my samples in groups of 20-25 and then combine the outputs, but I'm not sure if there will be a problem with that, in terms of algorithm's logic.
It may be a silly question but I'm not very familiar with programming, I'm just a user..
Thank you for your time!!
Best regards,
Myrto

**Comment by benjjneb** [comment]
Hi Myrto,
Yes, it it completely possible to process samples in batches, or really even individually.

What I would recommend is that you use a subset of your samples to estimate the error rate parameters on your data (i.e. run dada(..., selfConsist=TRUE)), and then use those estimated error rates to run all of your samples. In that way you can keep memory requirements very low.

Then, at the end, use `makeSequenceTable` on all of the processed samples, and you're done.

**Comment by mtsiknia** [comment]
benjjneb thank you very much for your reply and your recommendation, which I followed and now I can analyze my samples!!
