### ISSUE TITLE
"Bad" quality profiles of reverse reads from DADA2

### ISSUE THREAD

**Issue by sfeds** [benjjneb/dada2#910]
Hi,

We're running a set of (human fecal) samples through DADA2. It's a sequencing run on a MiSeq, V4 region used.
While the quality profiles we get from the MiSeq look ok, the ones from DADA2 are a bit worrysome.
Here the MiSeq (F & R);
![image](https://user-images.githubusercontent.com/20225551/70906015-ae55b800-2005-11ea-8a78-b8247586bb76.png)

Here the DADA2 for a couple of samples (FWD):
![image](https://user-images.githubusercontent.com/20225551/70906030-b6adf300-2005-11ea-9620-dcd9b378d502.png)

And REV
![image](https://user-images.githubusercontent.com/20225551/70906035-ba417a00-2005-11ea-90c3-21ada5e1fead.png)

Any idea why they look so "bad"? We can still use them, as the FWD reads are very good and we don't need much more from the REV, but still, would be good to know why they look like this.

Some additional information on the sequencing run:
We're using V3 chemistry kits, density was 723 (with over 25% PhiX), and Q30 r1=95.4, Q30 r2=82.9. 

Thanks!

**Comment by benjjneb** [comment]
I think the plot at the top and the . plot at the bottom are from the same data, right? It's just a different way to visualize the quality score distribution -- in particular the green line in the DADA2 quality profile plot shows the median quality score at each position, which is difficult to discern in the heat map at the top.

That data is very much usable, I'd probably just truncate the reverse reads at ~140-150 nts to remove the lower quality stuff at the end. Or you could also just go with the forward reads, up to you.

**Comment by sfeds** [comment]
Hi Ben,
indeed plots are from the same data, the 2 visualizations (Illumina and DADA2).
I always prefer to use the REV reads, even if they look like this.
Good to know that it's not too troublesome, I was even going for truncating at 50bp :)

Thanks for the quick response!
