### ISSUE TITLE
Necessity of derepFastq()

### ISSUE THREAD

**Issue by kohlkopf** [benjjneb/dada2#919]
How will `derepFastq()` change the dada2 workflow? I noticed it used in the outdated Big Data workflow, but I do not see it in the main tutorial in the [Tutorial section](https://benjjneb.github.io/dada2/tutorial.html) of the dada2 site.

I have 115 samples and would love to save on computation time. I'm having issues losing reads (~70%) during the chimera step and am looking closely at every step to see what is going wrong. I wondered if `derepFastq()` could have an effect at the chimera-removal step.

**Comment by benjjneb** [comment]
`derepFastq` just gets called silently in the updated workflows which is both simpler syntax-wise and also typically preferred computationally as it allows samples to be streamed into memory one at a time. There is no different in output from calling `derepFastq` explicitly though.

> I'm having issues losing reads (~70%) during the chimera step and am looking closely at every step to see what is going wrong

In >90% of cases, this is caused by primers or other technical nucleotides (e.g. heterogenity spacers) that have not been removed from the reads. I'd double check your amplicon layout and make sure to remove primers.

**Comment by kohlkopf** [comment]
I didn't know it was being run implicitly. Thanks!

I've visually checked my primers against my seqs as you recommended in issue #900. I'm not exactly sure what tipped you off that the user hadn't removed primers though

We used:
341F: CCTAYGGGRBGCASCAG
806R: GGACTACNNGGGTATCTAAT

`> dada2:::pfasta(getSequences(drpF)[1:20])
>1
TAGCTTCCTATGGGGTGCAGCAGTGAGGAATATTGGTCAATGGGCGCTAGCCTGAACCAGCCAAGTAGCGTGAAGGATGACTGCCCTATGGGTTGTAAACTTCTTTTATATGGGAATAAAGTGCAGTATGTATACTGCTTTGCATGTACCTTATGAATAAGGATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAG
>2
TAGCTTCCTATGGGATGCAGCAGTGAGGAATATTGGTCAATGGGCGCTAGCCTGAACCAGCCAAGTAGCGTGAAGGATGACTGCCCTATGGGTTGTAAACTTCTTTTATATGGGAATAAAGTGCAGTATGTATACTGCTTTGCATGTACCTTATGAATAAGGATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAG
>3
TAGCTTCCTATGGGGTGCAGCAGTGAGGAATATTGGTCAATGGGCGCGAGCCTGAACCAGCCAAGTCGCGTGAGGGATGACGGTCCTACGGATTGTAAACCTCTTTTGCCGGGGAGCAAGCGTGCGTTCGTGAACGCGCGTCGAGAGTACCCGGAGAAAAAGCATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTA
>4
TAGCTTCCTATGGGGTGCAGCAGTGAGGAATATTGGTCAATGGGCGCAAGCCTGAACCAGCCAAGTCGCGTGAGGGAAGACGGCCCTACGGGTTGTAAACCTCTTTTGCCGGGGAGCAAGCCTGAGCACGTGTGCCCAGGCGGAGAGTACCCGGAGAAAAAGCATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGCA
>5
TAGCTTCCTATGGGATGCAGCAGTGAGGAATATTGGTCAATGGGCGCAAGCCTGAACCAGCCAAGTCGCGTGAGGGAAGACGGCCCTACGGGTTGTAAACCTCTTTTGCCGGGGAGCAAGCCTGAGCACGTGTGCCCAGGCGGAGAGTACCCGGAGAAAAAGCATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGCA
>6
TAGCTTCCTATGGGGTGCAGCAGTGGGGAATATTGCACAATGGGGGAAACCCTGATGCAGCGACGCCGCGTGAGTGAAGAAGTATTTCGGTATGTAAAGCTCTATCAGCAGGGAAGAAATACTGACCATAGGGTCAGCAGACGGTACTTGACTAAGAAGCCCCGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGAC
>7
TAGCTTCCTATGGGATGCAGCAGTGGGGAATATTGCACAATGGGGGAAACCCTGATGCAGCGACGCCGCGTGAGTGAAGAAGTATTTCGGTATGTAAAGCTCTATCAGCAGGGAAGAAATACTGACCATAGGGTCAGCAGACGGTACTTGACTAAGAAGCCCCGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGGGGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGTAGAC
>8
TAGCTTCCTATGGGATGCAGCAGTGAGGAATATTGGTCAATGGGCGCGAGCCTGAACCAGCCAAGTCGCGTGAGGGATGACGGTCCTACGGATTGTAAACCTCTTTTGCCGGGGAGCAAGCGTGCGTTCGTGAACGCGCGTCGAGAGTACCCGGAGAAAAAGCATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTA
>9
TAGCTTCCTATGGGGTGCAGCAGTGAGGAATATTGGTCAATGGGCGCGAGCCTGAACCAGCCAAGTCGCGTGAGGGATGACGGCCCTACGGGTTGTAAACCTCTTTTGTCGGGGAGCAAATTCCGCCACGTGTGGCGGAGTCGAGAGTACCCGAAGAAAAAGCATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTA
>10
TAGCTTCCTATGGGATGCAGCAGTGAGGAATATTGGTCAATGGGCGCGAGCCTGAACCAGCCAAGTCGCGTGAGGGATGACGGCCCTACGGGTTGTAAACCTCTTTTGTCGGGGAGCAAATTCCGCCACGTGTGGCGGAGTCGAGAGTACCCGAAGAAAAAGCATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTA
>11
TAGCTTCCTATGGGGTGCAGCAGTGAGGAATATTGGTCAATGGGAGAGATCCTGAACCAGCCAAGCCGCGTGAGGGAAGACGGCCCTATGGGTTGTAAACCTCTTTTGTCGGAGAACAAAACCCGGGACGTGTCCCGGACTGCGTGTATCCGAAGAAAAAGCATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTAG
>12
TAGCTTCCTATGGGATGCAGCAGTGAGGAATATTGGTCAATGGGAGAGATCCTGAACCAGCCAAGCCGCGTGAGGGAAGACGGCCCTATGGGTTGTAAACCTCTTTTGTCGGAGAACAAAACCCGGGACGTGTCCCGGACTGCGTGTATCCGAAGAAAAAGCATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTAG
>13
TAGCTTCCTATGGGGTGCAGCAGTAGGGAATTTTCGTCAATGGGCGCAAGCCTGAACGAGCAATGCCGCGTGAACGAGGAAGGTCTTCGGATCGTAAAGTTCTGTTGAAGGGGAAAAAGAGCGGAGAGAGGAAATGGTCTCCGATTGATATTACCCTTCGAGGAAGTCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCGAGCGTTATCCGGAATGATTGGGCGTAAAGGGTG
>14
TAGCTTCCTATGGGATGCAGCAGTGAGGAATATTGGTCAATGGGCGCGAGCCTGAACCAGCCAAGTCGCGTGAGGGATGACGGCCCTACGGGTTGTAAACCTCTTTTGTCGGGGAGCAAATTCCGTTACGTGTAACGGAGTCGAGAGTACCCGAAGAAAAAGCATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTA
>15
TAGCTTCCTATGGGGTGCAGCAGTGAGGAATATTGGTCAATGGGCGGAAGCCTGAACCAGCCAAGTCGCGTGAGGGATTAAGGCCCTGCGGGTCGTAAACCTCTTTTGCCGGGGAGCAGTGGTCCGGACGTGTCCGGGCCGGGAGAGTACCCGGAGAAAAAGCATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTA
>16
TAGCTTCCTATGGGGTGCAGCAGTGAGGAATATTGGTCAATGGGCGCGAGCCTGAACCAGCCAAGTCGCGTGAGGGATGACGGCCCTACGGGTTGTAAACCTCTTTTGTCGGGGAGCAAATTCCGTTACGTGTAACGGAGTCGAGAGTACCCGAAGAAAAAGCATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTA
>17
TAGCTTCCTATGGGAGGCAGCAGTGAGGAATATTGGTCAATGGGCGCTAGCCTGAACCAGCCAAGTAGCGTGAAGGATGACTGCCCTATGGGTTGTAAACTTCTTTTATATGGGAATAAAGTGCAGTATGTATACTGCTTTGCATGTACCTTATGAATAAGGATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGAGCGTAG
>18
TAGCTTCCTATGGGATGCAGCAGTGAGGAATATTGGTCAATGGGCGCGAGCCTGAACCAGCCAAGTCGCGTGAGAGATGACGGCCCTACGGGTTGTAAACCTCTTTTGTCGGGGAGCAAATTCCGCCACGCGTGGCGGAGTCGAGAGTACCCGAAGAAAAAGCATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTA
>19
TAGCTTCCTATGGGGTGCAGCAGTGAGGAATATTGGTCAATGGGCGCGAGCCTGAACCAGCCAAGTCGCGTGAGAGATGACGGCCCTACGGGTTGTAAACCTCTTTTGTCGGGGAGCAAATTCCGCCACGCGTGGCGGAGTCGAGAGTACCCGAAGAAAAAGCATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTA
>20
TAGCTTCCTATGGGATGCAGCAGTGAGGAATATTGGTCAATGGGCGCGAGCCTGAACCAGCCAAGTCGCGTGAGGGATGACGGCCCTACGGGTTGTAAACCTCTTTTGTCGGGGAGCAAATTCCGCCACGCGTGGCGGAGTCGAGAGTACCCGAAGAAAAAGCATCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGATGCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTA`

**Comment by benjjneb** [comment]
> 1
> TAGCTT**CCTATGGGGTGCAGCAG**TGAGGAATATTGGTCAATGGGCGCTAGCCT...

The bolded is the forward primer sequence, and its present in the same place in all these reads. You'll need to remove those (and reverse primers, which are probably also there) either with an external program, or more easily with `trimLeft` during the `filterAndTrim` step.

**Comment by kohlkopf** [comment]
Primer presence confirmed! Thank you.
![image](https://user-images.githubusercontent.com/28633777/72300076-fd503680-361f-11ea-9d11-20b739eea970.png)

**Comment by kohlkopf** [comment]
|                  | Forward | Complement | Reverse | RevComp |
| ---------------- | ------- | ---------- | ------- | ------- |
| FWD.ForwardReads | 156300  | 0          | 0       | 0       |
| FWD.ReverseReads | 0       | 0          | 0       | 531     |
| REV.ForwardReads | 0       | 0          | 0       | 398     |
| REV.ReverseReads | 158624  | 0          | 0       | 0       |
