### ISSUE TITLE
Add officially supported COI database?

### ISSUE THREAD

**Issue by benjjneb** [benjjneb/dada2#922]
Probably derived from iBOL: https://www.gbif.org/dataset/040c5662-da76-4782-a48e-cdea1892d14c

Ideal would be to work out a solution like we did for UNITE where one of the official release files on their end can be sniffed and parsed as is, w/o additional reformatting, but not sure if that is possible here.

**Comment by cjfields** [comment]
@benjjneb this might be easier than you think:

https://github.com/terrimporter/CO1Classifier/
https://github.com/terrimporter/CO1Classifier/issues/2

**Comment by cjfields** [comment]
I'll add (as we have a project looking at CO1 data) the approach used in the above links was not terribly satisfactory compared to the results obtained when using the BOLD website's tools (odd mis-assignments).  Not sure why yet, as we haven't had time to delve into this much more though I suspect this has to do with the database containing a mix of different amplicon data sets as we found that a BLAST analysis against RefSeq full mitochondrial sequences worked quite well.

**Comment by benjjneb** [comment]
Thanks for the update!

This is something I still want to do (albeit at a time TBD), but that reconfirms that we should probably stick with iBOL/BOLD as the source db.

**Comment by cliffbueno** [comment]
@cjfields thanks for your comments and the links to Dr. Porter's database. I just tried the CO1Classifer too within dada2 and also found it to give pretty low resolution taxonomic assignments compared to GBIF https://www.gbif.org/tools/sequence-id. Also going to try the insect R package and the BOLDigger python program.

**Comment by Roxe4228** [comment]
Even if we have a low resolution with dada2 for CO1, can someone show me how you did with the https://github.com/terrimporter/CO1Classifier/ ? I tried so many hours and I still can't run the "assigntaxonomy" function.

**Comment by benjjneb** [comment]
@Roxe4228 The training files provided at your link are for use with the RDP Classifier (this I think: https://github.com/rdpstaff/classifier). They aren't formatted to be used with `assignTaxonomy`.

**Comment by Roxe4228** [comment]
Yeah, it's what I thought! But I was wondering how @cliffbueno did do make it work and say that the taxonomic resolution is low compared to GBIF ? Also, thank you very much for your fast response !!!

**Comment by cjfields** [comment]
@Roxe4228 not sure what @cliffbueno did, but when I did this I used the code in https://github.com/terrimporter/CO1Classifier/issues/2.  The primary issue is ensuring that you have the ranks set up properly.

**Comment by Roxe4228** [comment]
Great! Ok thank you very much. I'm gonna try using terrimporter/CO1Classifier#2 instead!

**Comment by cliffbueno** [comment]
@Roxe4228 I also used terrimporter/CO1Classifier#2. But ultimately I used the BOLD database because it gave more genus and species level assignments. To assign the taxonomy I used BOLDigger https://pypi.org/project/boldigger/. Good luck!
