### ISSUE TITLE
Forward vs. paired-end reads

### ISSUE THREAD

**Issue by rozlynboutin** [benjjneb/dada2#924]
Hi,

I have been using DADA2 to process sequencing data that was sequenced as paired-end reads. However, the reverse reads were of very poor quality, so we decided to use only the forward reads and to not truncate the reads. I was wondering if it is acceptable to reverse transcribe the forward reads and use these as reverse reads to run the DADA2 paired-end read pipeline?

Thanks in advance!

**Comment by benjjneb** [comment]
That wouldn't really make sense. You just want to use the forward reads only.

That can be done by following the tutorial as is, but skipping the reverse read and merging steps. Then create the sequence table from the `dada-class` objects, i.e: `seqtab <- makeSequenceTable(dadaFs)`

**Comment by rozlynboutin** [comment]
Okay, great-thanks! Just for my own understanding of what is happening "under the hood", do you think the reverse transcribing would introduce a bias or change the results of what we get in the final ASV table?

**Comment by benjjneb** [comment]
Reverse transcribing the forward reads isn't adding new information, as actual reverse reads would do, it's just duplicating the information already in the forward reads. If you're just using the forward reads, then just use the forward reads -- there's no gain and only (small) potential loss by adding "pseudo" reverse reads via reverse complementation.

**Comment by rozlynboutin** [comment]
Okay, I will just use the forward then-thanks so much for quick reply!
