### ISSUE TITLE
Removing samples with only few reads

### ISSUE THREAD

**Issue by darjniki** [benjjneb/dada2#925]
Hello, 
I'm making microbiome analysis following DADA2 tutorial, but I have faced the problem.
When I make "track" file, some of the samples after removing chimeras have only a few reads, so I want to remove them from the analysis. 

getN <- function(x) sum(getUniques(x))
track <- cbind(out, sapply(dadaFs, getN), sapply(mergers, getN), rowSums(seqtab), rowSums(seqtab.nochim))
colnames(track) <- c("input", "filtered", "denoised", "merged", "tabled", "nonchim")
rownames(track) <- sample.names
head(track)

       input filtered denoised merged tabled nonchim
I09927 53485    49400    49314  48186  48186   47935
I09928 56868    51424    51358  50520  50520   50415
I09929 10086      137       73     62     62      53
I09930   721       49       18     14     14      14
I09931  5483     4985     4893   4253   4253    4217
I09932 56616    50667    50600  49438  49438   48183

As I found in other issue discussion (https://github.com/benjjneb/dada2/issues/238), I use this code to filter some samples from seqtab.nochim file:

st <- seqtab.nochim[rowSums(seqtab.nochim) >= 10000,]
Then "st" file doesn't have samples which reads are < 10000- evething is OK. But when I'm running next code, I have warning message and don't know how to fix it:

getN <- function(x) sum(getUniques(x))
track2 <- cbind(out, sapply(dadaFs, getN), sapply(mergers, getN), rowSums(seqtab), rowSums(st))

Warning message:
In cbind(out, sapply(dadaFs, getN), sapply(mergers, getN), rowSums(seqtab),  :
  number of rows of result is not a multiple of vector length (arg 5)

If I go further, an offset occurs in the nonchim column , but those samples are not deleted from the main "track2" file.

colnames(track2) <- c("input", "filtered", "denoised", "merged", "tabled", "nonchim")
rownames(track2) <- sample.names
head(track2)

       input filtered denoised merged tabled nonchim
I09927 53485    49400    49314  48186  48186   47935
I09928 56868    51424    51358  50520  50520   50415
I09929 10086      137       73     62     62   48183
I09930   721       49       18     14     14   36434
I09931  5483     4985     4893   4253   4253   52070
I09932 56616    50667    50600  49438  49438   37917

How can I filtred track2 file by "st" file?

**Comment by wbazant** [comment]
Are you getting this warning when calling one of the `dada2` functions? Or does it occur in the later part, where you try to transform the results into a particular format?

**Comment by darjniki** [comment]
Yes, that is on a dada2 stage.

**Comment by wbazant** [comment]
Your error looks like it's coming from cbind, and I think it's because you're trying to put together tables of different dimensions: those with the filtered content are shorter. You could try assigning ` sapply(dadaFs, getN), sapply(mergers, getN), rowSums(seqtab), rowSums(st)` to variables first and seeing what shape / dimensions they have to check whether this is the right suggestion.
