### ISSUE TITLE
Losing large number of reads due to removal of non-target length sequences

### ISSUE THREAD

**Issue by chriskellogg** [benjjneb/dada2#927]
My lab recently set up a workflow mainly following the DADA2 tutorial with some tweaks based on AstroBioMike's Happy Belly Bioinformatics page. We're processing Illumina MiSeq, 2 x 250bp, 16S rRNA V4 sequence data. 

Since I'm new at this workflow (and working with Illumina data rather than 454), I've been working through it using two different datasets (one smaller, one larger, from two different sequence vendors) to get a feel for where I need to make dataset specific choices. With both datasets, I've found that I experience major sequence loss between merging (that all looks good) and chimera removal (also looks good). Specifically, when I inspect the distribution of sequence lengths after merging using

     seqtab <- makeSequenceTable(mergers)
     table (nchar(getSequences(seqtab)))

I get a wide range of sequence sizes (e.g., from 118 to >300) and so I choose to remove the non-target length sequences using

     seqtab2 <- seqtab[,nchar(colnames(seqtab)) %in% 250:256]

This results in a loss of 50-90% of the original number of sequences, e.g., see column labeled 'restrict_seq' in the sequence table (Summary_tab_filtration_scores.xlsx):

[Summary_tab_filtration_scores.xlsx](https://github.com/benjjneb/dada2/files/4109393/Summary_tab_filtration_scores.xlsx)

To be clear, nothing in the workflow is doing anything unexpected. I can see what is happening at each step and have confirmed that the sequences I've removed add up to the the number that are lost in that step. My question is whether other people routinely see this in their data (because if you don't do that inspection step, you wouldn't know how many sequences might be an unexpected size). If you DO routinely do this, do you lose this many sequences? Basically, is this a 'cost of doing business' using Illumina OR have I had the misfortune to encounter two poor quality sequencing vendors in a row? In which case, please offer suggestions for more reliable ones, not that it will save these datasets since I can't afford to rerun them. All insights appreciated!

**Comment by benjjneb** [comment]
No, I typically would not see such a large loss in the number of reads when enforcing a length distribution restriction, especially on V4 data which has a highly evolutionarily conserved length.

Could you show the results of `table(nchar(getSequences(seqtab)))`?
Also, the distribution of the read counts by length might be useful too:

```
reads.by.len <- tapply(colSums(seqtab), nchar(colnames(seqtab)), sum)
plot(as.numeric(names(reads.by.len)), reads.by.len,  xlab="Length", ylab="Total Reads")
```

**Comment by chriskellogg** [comment]
# Inspect distribution of sequence lengths 
table(nchar(getSequences(seqtab))) 

# 118  158  169  185  187  188  189  191  192  195  196 
# 1    1    3    1    2    1    5    1    1    1    1 
# 197  198  202  203  204  205  209  216  217  218  220 
# 1    3    1    2    1    1    2    1    1    1    1 
# 221  222  223  224  225  226  227  229  230  235  237 
# 17    6    2    3    3    1   18    3    1    1    1 
# 244  245  250  251  252  253  254  255  256  257  258 
# 2    1    3   10  311 3728  308   10    3    2    4

**Comment by chriskellogg** [comment]
# Inspect distribution of sequence lengths 
table(nchar(getSequences(seqtab))) 

![Screen Shot 2020-01-24 at 1 19 12 PM](https://user-images.githubusercontent.com/12253104/73093262-238d9600-3eac-11ea-89bc-e9287945e23c.png)

**Comment by chriskellogg** [comment]
reads.by.len <- tapply(colSums(seqtab), nchar(colnames(seqtab)), sum)
plot(as.numeric(names(reads.by.len)), reads.by.len,  xlab="Length", ylab="Total Reads")

![Screen Shot 2020-01-24 at 1 21 30 PM](https://user-images.githubusercontent.com/12253104/73093432-83843c80-3eac-11ea-95cc-0694aa1ca474.png)

**Comment by benjjneb** [comment]
Well, we found the issue: There is 1-3 ASVs of length 169 that account for ~1/2 of all the reads in your data. The next question is, what are those sequences?

```
sq <- getSequences(seqtab)
sq.169 <- sq[nchar(sq) == 169]
dada2:::pfasta(sq.169, ids = colSums(seqtab)[,sq.169])
```

**Comment by chriskellogg** [comment]
No problem with the first 2 lines, but 3rd line results in:

Error in colSums(seqtab)[, sq.169] : incorrect number of dimensions

**Comment by benjjneb** [comment]
Sorry, remove the extraneous comma I left in there, i.e. `colSums(seqtab)[sq.169]`

**Comment by chriskellogg** [comment]
Sorry, I'm too remedial at R to recognize the error I knew had to be in there somewhere. That comma looked totally legit! I've pasted resulting sequences below, but the money answer is that I blasted them and they are coral mitochondria. So it's amplification of the host's mitochondria (bet it's the same in my other dataset, also derived from coral, but now I can confirm, thanks!) I thought I was using the same primer set as other coral micro people, but worth a few emails to see if others have had this same experience or are using modified primers to avoid it.

>1068862
ACTTAAGGGTTTGTTTTTTAGAAAAAGCAGAAAGCGTGTAAAGGTAAAACATTTAAAATAAATAGAATTTTTTTAGTAATGGTGCAATATTAAAAGAAAAAAAAGAATTTTTTTATGTGAAGACAATTTATTTTTTTTCTTTAACACGAAGGTTCTGGGAGCGAACAGG
>985162
ACTTAAGGGGTTGTTTTTTAGAAAAAGCAGAAAGCGTGTAAAGGTAAAACATTTAAAATAAATAGAATTTTTTTAGTAATGGTGCAATATTAAAAGAAAAAAAAGAATTTTTTTATGTGAAGACAATTTATTTTTTTTCTTTAACACGAAGGTTCTGGGAGCGAACAGG
>7673
ACTTTAGGGGTTGTTTTTTAGAAAAAGCAGAAAGCGTGTAAAGGTAAAACATTTAAAATAAATAGAATTTTTTTAGTAATGGTGCAATATTAAAAGAAAAAAAAGAATTTTTTTATGTGAAGACAATTTATTTTTTTTCTTTAACACGAAGGTTCTGGGAGCGAACAGG

**Comment by benjjneb** [comment]
Mystery solved!

A better primer set that didn't amplify up the mito DNA would be more efficient, but you can still use the non-mito fraction of this data as you had hoped to. The cost you pay is just the effectively lower library sizes since much of the sequencing was "wasted" on mitochondria.

**Comment by chriskellogg** [comment]
Some literature sleuthing reveals that this has been a known problem for coral microbiome datasets. Some have chosen to use primers that target a different variable region (e.g., V5-V6 with 784F/1061R) while others have accepted this problem in order to keep targeting the V4 region to maintain consistency with larger datasets like the Earth Microbiome Project.
