### ISSUE TITLE
ITS workflow -- cutadapt file sorting

### ISSUE THREAD

**Issue by ewmorr** [benjjneb/dada2#930]
Hi,

Running through the ITS workflow with some real data, and finding that if there are files that do not pass the N filtering step (first call to `filterAndTrim`), cutadapt may subsequently write to the wrong files. Looks like the offending lines are
```
fnFs.cut <- file.path(path.cut, basename(fnFs))
fnRs.cut <- file.path(path.cut, basename(fnRs))
```
and the following should work correctly?
```
fnFs.cut <- file.path(path.cut, basename(fnFs.filtN))
fnRs.cut <- file.path(path.cut, basename(fnRs.filtN))
```
#### EDIT
also in the for loop for cutadapt `for(i in seq_along(fnFs)){` --> `for(i in seq_along(fnFs.filtN)){`

**Comment by benjjneb** [comment]
A standard way to deal with this potential issue of losing files in filtering, is to add a check for and removal of all non-existing files after the filter and trim step. e.g.

```
fnFs.filtN <- file.path(path, "filtN", basename(fnFs)) # Put N-filterd files in filtN/ subdirectory
fnRs.filtN <- file.path(path, "filtN", basename(fnRs))
filterAndTrim(fnFs, fnFs.filtN, fnRs, fnRs.filtN, maxN = 0, multithread = TRUE)
fnFs.filtN <- fnFs.filtN[file.exists(fnFs.filtN)] # Drops files that failed filter entirely and weren't written
fnFs.filtR <- fnFs.filtR[file.exists(fnFs.filtR)]  # Drops files that failed filter entirely and weren't written
```

**Comment by ewmorr** [comment]
Aha. Thanks, and nice trick!

I think the issue I was having is slightly different though, in that as written in the tutorial the cutadapt call is writing to the original file list (e.g., the file list before filtering for Ns (`fnFs` NOT `fnFs.filtN`) are given to the `fnFs.cut` object). So even if the files are dropped in the filtN folder, cut adapt will write to files that should have been dropped.
