### ISSUE TITLE
Let filterAndTrim create empty files 

### ISSUE THREAD

**Issue by bernt-matthias** [benjjneb/dada2#931]
Filters might remove everything or the data might just contain no useful read information at all (I have this for blank samples) 

```
The filter removed all reads: FILENAME not written.


  No reads passed the filter. Please revisit your filtering parameters.
```

In these cases the output files are not created with makes automated processing in a pipeline more difficult than it should be. I was wondering if it would be an option to create empty fastq or fastq.gz files in these cases.

**Comment by benjjneb** [comment]
The recommended solution for this is to do a `file.exists()` check after `filterAndTrim`, especially in automated pipelines. That will subset down to the files that passed the filter. e.g.

```
out <- filterAndTrim(fn, filt, maxEE=2)
filt <- filt[file.exists(filt)]
```

The alternative of propagating blank "fastq" files or zero-read samples introduces a number of edge cases, and is not managed well by the I/O library we are using.

**Comment by bernt-matthias** [comment]
Thanks for the fast answer. Lets see how we implement this best in the Galaxy wrappers. 

Out of curiosity .. and because I would love some feedback of the developers .. did someone of your team check out the dada2 Galaxy tools that are available, e.g. of usegalaxy.org?

**Comment by nhoffman** [comment]
In case this is of any use to you or anyone else - I encountered the same issue writing a pipeline for dada2 in nextflow. I use this wrapper script for the filtering step:

```R
#!/usr/bin/env Rscript

suppressWarnings(suppressMessages(library(argparse, quietly = TRUE)))
suppressWarnings(suppressMessages(library(jsonlite, quietly = TRUE)))
suppressWarnings(suppressMessages(library(dada2, quietly = TRUE)))

main <- function(arguments){
  parser <- ArgumentParser()
  parser$add_argument('--infiles', nargs='+', help='input R1,R2 fq.gz')
  parser$add_argument('--params',
                      help=paste(
                          'json file containing optional parameters for ',
                          'fastqPairedFilter (see README)'))
  parser$add_argument('--outfiles', nargs='+', help='output R1,R2 fq.gz')
  parser$add_argument('--nthreads', type='integer', default=0,
                      help='number of processes; defaults to number available')

  args <- parser$parse_args(arguments)
  multithread <- if(args$nthreads == 0){ TRUE }else{ args$nthreads }

  if(is.null(args$params)){
    params <- list()
  }else{
    params <- fromJSON(args$params)$fastqPairedFilter
  }

  ## params overrides any values in the first argument
  funcargs <- modifyList(
      list(fn=args$infiles,
           fout=args$outfiles,
           compress=TRUE,
           multithread=multithread,
           verbose=TRUE),
      params)

  do.call(dada2::fastqPairedFilter, funcargs)

  ## There is no error if all reads have been eliminated, but no files
  ## are written in this case. Check for the output files, and if they
  ## don't exist, create empty ones.
  for(fn in args$outfiles){
    if(!file.exists(fn)){
      cat(gettextf('creating empty file %s\n', fn))
      gzf = gzfile(fn)
      cat('', file=gzf, fill=FALSE)
      close(gzf)
    }
  }

}

main(commandArgs(trailingOnly=TRUE))
```

Parameters are provided in a json file that looks something like this (I use a similar approach for other steps and consolidate all of the parameters into one file):

```json
{
  "fastqPairedFilter": {
    "trimLeft": 15,
    "truncLen": [240, 220],
    "maxN": 0,
    "maxEE": 1,
    "truncQ": 2
  },
  "dada": {
    "selfConsist": true,
    "BAND_SIZE": 4,
    "OMEGA_A": 1e-100,
    "OMEGA_C": 1e-40
  },
  "mergePairs": {
    "maxMismatch": 0
  },
  "removeBimeraDenovo": {
    "minFoldParentOverAbundance": 2
  }
}
```

**Comment by bernt-matthias** [comment]
Thanks for sharing @nhoffman. Am I right that you only allow fastq.gz input?

Did you ever have problems with: 

> zero-read samples introduces a number of edge cases, and is not managed well by the I/O library we are using

**Comment by nhoffman** [comment]
Hi @bernt-matthias - yes, I'm expecting fastq.gz in this script. I should also point out that this is written to process a single pair at a time. 

With respect to "edge cases": yes, there are a number of places in the pipeline where specimens with zero or only a few reads can result in errors. I try to anticipate these and generate empty files (with 0 exit status), but of course I probably haven't run into every possible case! Here's the pipeline that the filterAndTrim wrapper came from - there are additional scripts for managing other steps with additional exception-handling: https://github.com/nhoffman/dada2-nf/tree/master/bin (sorry there isn't much documentation - it's really only meant for my own use at this point).

It would be lovely if some of this exception-handling was built into the package itself (at least for common cases), but trying to anticipate each one would certainly add to the overall complexity of the code, and I completely understand the decision not to.
