### ISSUE TITLE
Number of RSVs differ drastically between two Miseq run with same samples.

### ISSUE THREAD

**Issue by Shriram369** [benjjneb/dada2#934]
Hello dada2 dev,
Recently, we have received data from Two MiSeq run data on same set of samples (16S rRNA sequencing V3-V4 region).
**Run-1 was failed** (or had low passing filter) due to over-clustering. 
So, Run2 was kept again on same set of samples and went okay.

So, now we have data from both the run and I analyzed them using standard dada2 pipeline.

Cut-adapt was used for adapter trimming:
**Run1 trimming parameter:**
truncLen=c(259,229), trimLeft=c(17,21), maxEE=c(1,1), truncQ=c(2,2), maxN=0, rm.phix=TRUE
**Run2 trimming parameter:**
truncLen=c(261,227), trimLeft=c(17,21), maxEE=c(1,1), truncQ=c(2,2), maxN=0, rm.phix=TRUE

TruncLen was decided based on figaro (Zymo-Research/figaro) evaluation and worked perfectly upon comparison with different TruncLen.

**My issue is:**
From Run1, we detected 6835 RSVs. While, in Run2 14735 RSVs were detected.

Run2 which is a good run has almost double amount of RSVs compared to Run1 which is over-clustered.

Upon comparison of sequence variants, both runs shares most abundant RSVs and difference is in the rare variants.

If identification of lower number of sequence variants in Run1 has anything to do with over-clustering or sequencer not being able to discriminate between clusters during base calling step?

Your insights will be helpful in this matter.

Thanks
Shriram

**Comment by benjjneb** [comment]
> Run2 which is a good run has almost double amount of RSVs compared to Run1 which is over-clustered.
>
> .Upon comparison of sequence variants, both runs shares most abundant RSVs and difference is in the rare variants.

This sounds like exactly what you'd expect. The higher quality, and hence higher effective number of quality reads per sample, in Run 2 allowed you to identify more rare variants.

**Comment by Shriram369** [comment]
Thanks. It makes lots of sense now.
