### ISSUE TITLE
Merging different runs query

### ISSUE THREAD

**Issue by wasimbt** [benjjneb/dada2#940]
Hello, 

I have been analyzing different sequencing runs (from the same project) through dada2. I understood that I have to analyze each run independently in order to remove run specific sequencing errors and merge them before performing chimera filtering (and rest of the downstream steps). For this, I am keeping all the trimming, quality filtering criteria same for all the runs. 

My question/doubt is, 
(i) If the same ASVs across the runs will merge automatically while merging the tables or do we need to run later something like collapseNoMismatch?
(ii)  Also is there any script available to merge the run at this step. 

I will be gratefull to your answers! 

Best, Wasim

**Comment by benjjneb** [comment]
> (ii) Also is there any script available to merge the run at this step.

`mergeSequenceTables` should do exactly what you are looking for, just give it the sequence tables from each run as arguments and it will merge them into a common table.

> (i) If the same ASVs across the runs will merge automatically while merging the tables

Yes, in particular because you kept your trimming/truncation parameters the same.

**Comment by wasimbt** [comment]
Hi Benjamin, 

Many thanks for your answers! I will do as you suggested. 

Best , 
Wasim

**Comment by claraqin** [comment]
Hi Benjamin,

I had a related question: if you're working with ITS sequences, for which truncating to a standard length is discouraged, is it possible that different sequencing runs with different overall quality scores will produce multiple length-variants of the same ASV? One scenario where I could see this happening is when different quality profiles lead to sequences hitting `truncQ` at different lengths. And if this does happen, would it be necessary to run `collapseNoMismatch()` on ITS sequence tables produced by merging different runs?

Best,
Clara

**Comment by benjjneb** [comment]
> is it possible that different sequencing runs with different overall quality scores will produce multiple length-variants of the same ASV? One scenario where I could see this happening is when different quality profiles lead to sequences hitting truncQ at different lengths.

Yes. We do not recommend using `truncQ` for that reason. (Well, `truncQ=2` is OK because it marks the end of usable sequence, at least in early Illumina, but no more).

> if this does happen, would it be necessary to run collapseNoMismatch() on ITS sequence tables produced by merging different runs?

Yes. And that should largely fix the issue of artefactual length variation induced by filtering/trimming causing differences between runs. But it doesnt fix the lower sensitivity caused by inducing artefactual length variation. So... don't use trimming methods that induce length variation based on quality scores!
