### ISSUE TITLE
n0 n1 nunq relationship clarification

### ISSUE THREAD

**Issue by pneumowidow** [benjjneb/dada2#943]
Hi,

I just wanted to get a better clarification of **n0**, **n1** and **nunq** and their relationship to one another or the abundance.  I guess if n0 matches the reads and nunq is the number of unique reads, then n1 reflects the reads that don't match the output sequence? Would it be correct to also say that these reads were those that were predicted to actually be a part of partition 1 but had a few errors and were consequently corrected? Or not all of them were corrected?

Thank you.

**Comment by benjjneb** [comment]
`n0`: Reads with no substitution errors relative to the inferred correct ASV.
`n1`: Reads with 1 substitution error that were corrected to this ASV.
`nunq`: The number of unique sequences that were corrected to this ASV.

**Comment by pneumowidow** [comment]
Thank you!
