### ISSUE TITLE
Running dada2 in Ion torrent single end ITS sequences

### ISSUE THREAD

**Issue by MarwaElnaiem** [benjjneb/dada2#945]
Dear All, 

I would like to know if anyone here familiar with using dada2 to analyze single end ITS sequences generated by the Ion torrent platform. 
When I tried the filtering and trimming step, I received an error. 
out <- filterAndTrim(data, filteredReads, maxN = 0, maxEE = c(2, 2), truncQ = 2, minLen = 50, rm.phix = TRUE, compress = TRUE, multithread = TRUE)  # on windows, set multithread = FALSE
The error:
Creating output directory: /home/marwa/ITS_tutorial/Marwa_ITS1_Raw_fastq_files (2)/filtered
Error in filterAndTrim(data, filteredReads, maxN = 0, maxEE = c(2, 2),  : 
  These are the errors (up to 5) encountered in individual cores...
 Filtering and trimming arguments should be of length 1 when processing single-end (rather than paired-end) data.

Would you please help me with that?
Marwa

**Comment by benjjneb** [comment]
> maxEE=c(2,2)

That is for paired end reads, hence the two values. Change that to just `2` and you should be good to go.

**Comment by MarwaElnaiem** [comment]
Thanks very much @benjjneb it worked successfully with me.

**Comment by MarwaElnaiem** [comment]
Hi, 
@benjjneb 
Once again, I obtained these warnings when I'm trying to plot error. 
 plotErrors(errorrate, nominalQ = TRUE)
Warning messages:
1: Transformation introduced infinite values in continuous y-axis 
2: Transformation introduced infinite values in continuous y-axis 

Would you please help me to understand it.

Marwa

**Comment by benjjneb** [comment]
This is just a warning and you can ignore it.

It derives from the fact that `plotErrors` plots on the log-scale, but there were some zero-values that got transformed to -Inf. It doesn't affect anything important though.

**Comment by MarwaElnaiem** [comment]
Thank you very much.
