### ISSUE TITLE
Allow any header format of the reference taxonomy

### ISSUE THREAD

**Issue by wbazant** [benjjneb/dada2#946]
This issue proposes adding an argument to `assignTaxonomy`, `reference.format` which will facilitate parsing different references (both common and arbitrary), as an alternative to the current solution of pre-processing the references.

Users of the package would be able to provide an argument from a provided list, which would mean a name of the reference database, like "silva", "rdp", etc. These would be explained in the documentation / tutorial, together with original download links:
```
| argument value | example | download link |
| "silva" |  >AY846380.1.2583 Eukaryota;Archaeplastida;Chloroplastida;Chlorophyta;Chlorophyceae;Monoraphidium minutum | https://www.arb-silva.de/no_cache/download/archive/current/Exports/|
| "unite" | >Glomeraceae|AM076560|SH146432.05FU|refs|k__Fungi;p__Glomeromycota;c__Glomeromycetes;o__Glomerales;f__Glomeraceae;g__;s__uncultured_Glomus | https://unite.ut.ee/repository.php |
...
```
No argument value would correspond to a canonical format of our choice. I propose
```
>kingdom;phylum...;genus\tspecies
```
The tab after the lineage, and species, would be optional to provide.

We would also allow providing the argument in a function format, even though we will not be expecting users to typically provide it like that. It would, however, guide the implementation, since each "silva"/"rdp"/"greengenes" argument would correspond to a function that we would maintain. Indeed all the logic for how to convert between references is already written in `taxonomy.R`, except you run them yourself and post the results up for download, instead of making it happen during package run.

The types of this function could be
```
typedef Lineage = List String
typedef SpeciesName = String
typedef Header = String
lineageAndMaybeSpeciesNameFromHeader :: Header -> PairOf [Lineage, Optional [ SpeciesName]]
```
or an alternative would be two functions
```
lineageFromHeaderForAssigningUpToGenus :: Header -> Lineage
lineageAndSpeciesFromHeaderForThenAssigningTheSpecies :: Header -> Optional [PairOf [Lineage, SpeciesName]]
```

I believe this is the correct abstraction. To assign taxonomy up to the genus we need to get lineage representing a list of taxonomic levels (but we don't skip any entries from the reference to assign genera), and to then assign the species we need both the same lineage to match it up, and the species name, but we skip many references for the species assignment (ones that say "unidentified species", for example).

With no additional effort we would also be able to provide formatters between references in the supported formats and our canonical format. This would probably be of interest to those integrating dada2 in large pipelines or someone who wants to pre-process the reference more, but not a typical user.

Potential advantages:
- the package would regain some simplicity of use by coming back to one reference file instead of two. After this change, addSpecies can get moved into assignTaxonomy, available through an argument like `species.use.exact.match` 
- less work for the maintainer: no more making zenodo/figshare entries each time one of the databases makes a new release
- dada2 can maintain a suite of tests documenting what happens to lineages and which species get taken for reference, so it's much easier for outside contributors to add an issue, another test or a line
- new references could be contributed in a sustainable way: now someone might provide a file to post on the references page, but it will go out of date, with no way to refresh or improve it. Meanwhile, formats of references are not as likely to change.
- because the users won't need to provide the reference taxonomy in the canonical format, it can suit the package's needs better at the cost of being a bit less intuitive, or changing over time

I am happy to spend time making this happen since dada2 having this feature will be really useful for a future direction of MicrobiomeDB we were talking about - doing taxonomic assignments with multiple references, so that the references themselves can be compared on our data. Also @bernt-matthias would solving this issue this meet your needs for https://github.com/benjjneb/dada2/issues/912 and (if you're still working on it) keeping dada2 available in Galaxy workflows?

@benjjneb do you think this is a good idea and a direction you would be happy for the package to go in?

**Comment by benjjneb** [comment]
I'll come back to this with more later, but a first note...

`assignTaxonomy` already has a bit of this, in that it sniffs the UNITE formatted reference fastas and then uses their release files directly.

**Comment by bernt-matthias** [comment]
@wbazant I'm not working on https://github.com/benjjneb/dada2/issues/912. But I'm happy to integrate updates for dada2 in the corresponding Galaxy tools .. in particular any new reference data or functionality to generate updated reference data.
