### ISSUE TITLE
Can I use DADA2 for WGS read level data?

### ISSUE THREAD

**Issue by archiesachdeva18** [benjjneb/dada2#948]
Hi I am new to DADA2 and am trying to learn how to convert sequencing data into OTU tables. I have a WGS read level data where I have fastq paired end data files for each sample.  Can I process this data through the DADA2 pipeline or is it just meant for 16sRNA sequencing data?

**Comment by benjjneb** [comment]
It's only meant for amplicon sequencing data (e.g. 16S), not for WGS data.

**Comment by archiesachdeva18** [comment]
Okay. Thanks!
