### ISSUE TITLE
How long will it take to assign taxonomy for fungal ITS1 sequences ? 

### ISSUE THREAD

**Issue by MarwaElnaiem** [benjjneb/dada2#949]
Hi, 

I'm running ITS microbiome data analysis using dada2 R package, and want to know how long does it take to assign taxonomy to 6197 sequences in 93 samples. 
I'm running on 16 GB RAM computer.

Regards, 
Marwa

**Comment by benjjneb** [comment]
What version of the package do you have, and can. you post the exact command you are running?
How long has it been running thus far without finishing?

**Comment by MarwaElnaiem** [comment]
Hi, 
Sorry for not including such important information. 
The dada2 package version is 1.15.0. 
The command was
 > taxa <- assignTaxonomy(seqtab.nochim, unite.ref, multithread = TRUE, tryRC = TRUE)

the line appeared and then it started running without finishing for several days. 
UNITE fungal taxonomic reference detected.
I tried to stop the running job but it gave me this message:
Terminating R will cause your R session to immediately abort. Active computations will be interrupted and unsaved source file changes and workspace objects will be discarded.

**Comment by benjjneb** [comment]
This is longer than it should take. I suspect a bug that was introduced into `assignTaxonomy(..., multithread=TRUE)` in release 1.14 may be responsible here.

Could you try installing the patched version 1.15.1 and seeing if this resolved the issue (i.e. taxonomic assignment should finish w/in a day at the most, perhaps in just ~hour depending on compute resources). See instructions here: https://github.com/benjjneb/dada2/issues/916#issuecomment-588367932

**Comment by benjjneb** [comment]
Assuming the update fixed this, but please re-open if needed.
