### ISSUE TITLE
Merge Seq Tables from Different Runs

### ISSUE THREAD

**Issue by jeffkimbrel** [benjjneb/dada2#95]
Is there a way to merge seq tables from two different MiSeq runs, where the RSV names from the first run are retained and applied to the second run?

I have one seq table already made from ~200 samples, using let's say RSV0001 through RSV1000. I now have a new seq table from new data, and I want RSVs found in the first dataset to be named the same, and then new RSVs not found in the first dataset to start numbering RSV1001, etc. This doesn't seem to be addressed by the "pooling" faq, which looks like it will just generate new names. 

Additionally, what happens if the sequences aren't the exact same length, because of different end trimming based on Illumina quality (before the DADA2 algorithm is run)? If dataset1 is 233nt, and dataset2 is 232nt, is it safe to consider them identical if the 232nt is wholly contained within the 233nt? 

Thanks for your help.

**Comment by benjjneb** [comment]
I should add in a convenience function to do this. For now this is some code I used for this purpose.

```
st2 <- readRDS("samtab_run02.rds")
st3 <- readRDS("samtab_run03.rds")
st4 <- readRDS("samtab_run04.rds")
st5 <- readRDS("samtab_run05.rds")
st6 <- readRDS("samtab_run06.rds")
st7 <- readRDS("samtab_run07.rds")
st8 <- readRDS("samtab_run08.rds")
sts <- list(st2, st3, st4, st5, st6, st7, st8)

unqs <- unique(c(sapply(sts, colnames), recursive=TRUE))
st <- matrix(0L, nrow=sum(sapply(sts, nrow)), ncol=length(unqs))
rownames(st) <- c(sapply(sts, rownames), recursive=TRUE)
colnames(st) <- unqs
for(sti in sts) {
  st[rownames(sti), colnames(sti)] <- sti
}
st <- st[,order(colSums(st), decreasing=TRUE)]
```

Note, this assumes you have left the sequences as the rownames of the sequence tables up to this point, as those serve as consistent labels across runs (unlike OTU001 etc.).

It also assumes that you have trimmed the runs in the same fashion, which is what I would recommend if you are combining runs. If you didn't, but the difference is just a couple extra nts at the end of one run, you can just trim them off (eg. rownames(st2) <- substr(rownames(st2, 1, 232))). For merged reads this is less of an issue generally, as long as you used the same trimLeft parameters in each run, as differences in truncLen shouldn't affect the length of the merged sequence.

**Comment by benjjneb** [comment]
Added `mergeSequenceTables`: 4682eea89c3e8adf6699ba88e49721ea094f347b

**Comment by jeffkimbrel** [comment]
Thanks Ben, I will give it a try. I haven't had any luck getting two runs with the primer sets to be the same length (233 vs 276), so I need to see what might be going on before attempting a merge.

**Comment by shan-e-s** [comment]
Is it important at what stage i merge my sequence tables from different runs? In the Big Data tutorial this occurs directly before removing chimeras. Considering im using the "consensus" method of chimera detection, can i merge after removing chimeras?

Furthermore, as DADA2 uses ASV's instead of OTU's, can i merge Sequence Tables after assigning taxonomy because sequences are no longer pooled by similarity?

**Comment by benjjneb** [comment]
> Is it important at what stage i merge my sequence tables from different runs? In the Big Data tutorial this occurs directly before removing chimeras. Considering im using the "consensus" method of chimera detection, can i merge after removing chimeras?

You can remove chimeras before merging runs. For the highest consistency of chimera identification across runs, we recommend removing chimeras after merging runs as in the Big Data tutorial.

> Furthermore, as DADA2 uses ASV's instead of OTU's, can i merge Sequence Tables after assigning taxonomy because sequences are no longer pooled by similarity?

Yes, although we don't have an automated function for merging taxonomy tables that is equivalent to `mergeSequenceTables`. It can be done pretty easily with a bit of R code though.

**Comment by shan-e-s** [comment]
Great, thanks for the quick reply! Really appreciate the great package.

Shane
