### ISSUE TITLE
Error in rval[sapply(rval, is.character)] : invalid subscript type 'list'

### ISSUE THREAD

**Issue by dgroso** [benjjneb/dada2#959]
Hello,

I am having difficulty with the last few lines of code (Filtering); I get the error described in the title, Error in rval[sapply(rval, is.character)] : invalid subscript type 'list'. I am not sure if I need to adjust my parameters, or if there is another issue. Any suggestions? Thank you in advance.

# DADA2 Workflow
## Filtering

library(dada2); packageVersion("dada2")
# Filename parsing
path <- "path/to/saliva_16S_data" # CHANGE ME to the directory containing your demultiplexed fastq files
filtpath <- file.path(path, "filtered") # Filtered files go into the filtered/ subdirectory
fns <- list.files(path, pattern="fastq.gz") # CHANGE if different file extensions
# Filtering (On Windows, Multithread = FALSE)
filterAndTrim(file.path(path,fns), file.path(filtpath,fns), 
              truncLen=100, maxEE=3, truncQ=12, rm.phix=TRUE,
              compress=TRUE, verbose=TRUE, multithread=FALSE)
unlist(filterAndTrim, recursive = TRUE, use.names = TRUE)

**Comment by benjjneb** [comment]
```
unlist(filterAndTrim, recursive = TRUE, use.names = TRUE)
```

Is this the line of code that is causing the error?

**Comment by dgroso** [comment]
> ```
> unlist(filterAndTrim, recursive = TRUE, use.names = TRUE)
> ```
> 
> Is this the line of code that is causing the error?

Nope; it is this line (which did not format properly, my apologies): 

filterAndTrim(file.path(path,fns), file.path(filtpath,fns),
          truncLen=100, maxEE=3, truncQ=12, rm.phix=TRUE,
          compress=TRUE, verbose=TRUE, multithread=FALSE)

The unlisting function was my attempt to remedy the error by converting the list into a vector, but I am still getting the error when I run that line of code.

**Comment by benjjneb** [comment]
What is the output of:

```
path
filtpath
head(fns)
```

**Comment by dgroso** [comment]
`> path
[1] "path/to/saliva_16S_data"
> filtpath
[1] "path/to/saliva_16S_data/filtered"
> head(fns)
character(0)`

**Comment by dgroso** [comment]
> What is the output of:
> 
> ```
> path
> filtpath
> head(fns)
> ```

`> path
[1] "path/to/saliva_16S_data"
> filtpath
[1] "path/to/saliva_16S_data/filtered"
> head(fns)
character(0)`

**Comment by dgroso** [comment]
> What is the output of:
> 
> ```
> path
> filtpath
> head(fns)
> ```

> path
[1] "path/to/saliva_16S_data"
> filtpath
[1] "path/to/saliva_16S_data/filtered"
> head(fns)
character(0)

**Comment by benjjneb** [comment]
Your `fns` filename vector is empty, which is likely what is causing the error.
Check the filename format of the fastq file in `path` and see if you need to, for example, change the `pattern` that `list.files` is checking for.

**Comment by Kodwings22** [comment]
Hi Author, thank you very much I read some of your posts whenever I have time. Your posts have been very helpful to me. Thanks. Go ahead like this. I visit this website from time to time ( https://kodlogs.net/276/invalid-subscript-type-list-r )
