### ISSUE TITLE
DADA2 with a run containing two types of amplicons ?

### ISSUE THREAD

**Issue by amerkt** [benjjneb/dada2#96]
I am very beginner with metagenomics analyses and I would like to identify fungi taxa from a MiSeq run using two couples of primers (ITS1-ITS4 and Glo454-NDL22). I guess that I should first separate sequences from the two amplicons prior using DADA2 pipeline. Is that right? Could anyone help me to do that?

**Comment by benjjneb** [comment]
Yes, it is recommended to separate the two amplicon pools. If there were different barcodes used between the ITS and Glo454 amplicons, this can be done straigthforwardly by separating the individual fastq files after demultiplexing.

A caveat though: Right now the dada2 pipeline is probably not appropriate for ITS amplicons, as it requires reads to be trimmed to a uniform length before processing. The length of the ITS region varies dramatically, and so this requirement may preclude using dada2 on your ITS data.
