### ISSUE TITLE
system cannot find cutadapt

### ISSUE THREAD

**Issue by leixuRRH** [benjjneb/dada2#960]
Hello!

I am trying to use cutadapt in dada2, following the tutorial of DADA2 ITS pipeline workflow (1.8).  I installed cutadapt in my server, but system2 command cannot seem to find it after I typed in the link to the command.   Your help will be much appreciated!

L

**Comment by benjjneb** [comment]
You need to determine the path to cutadapt, and provide R the full path in that section of the tutorial.

`which cutadapt` in the shell might help you find that path.

**Comment by leixuRRH** [comment]
Thank you for your suggestion.  I did type in the path to cutadapt in R studio under dada2.  The codes are below:


Ø  cutadapt <- "C:/Users/LXU/AppData/Local/Packages/CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc/LocalState/rootfs/home/lei_xurrh/miniconda3/bin/cutadapt"

Ø  system2(cutadapt, args = “—version”)

I installed cutadapt under miniconda3 and verified it is indeed in that folder and it looks like cutadapt is functional in that folder.  But the system2 command I typed in Rstudio didn’t seem to work, since if cutadapt is run, the prompt should return 2.8 (the version 2.8), but nothing came up.

I also tried the “which cutadapt” command under Ubuntu.  It gave me the path of /home/lei_xurrh/.local/bin/cutadapt, which is a bit different from the path above.  I typed in this new path, still nothing showed up after system2.

When I typed “which cutadapt” directly under windows powershell (c:/), nothing came up.    Perhaps because I installed it under ubundu?

Your help is much appreciated!

**Comment by benjjneb** [comment]
If I understand correctly, cutadapt is installed on Ubuntu, and you are trying to call it from R running on Windows? The issue here is likely caused by the interface between the Windows and Ubuntu filesystems then, and some failure in navigating the path from within R.

Apologies though, I do not know how to diagnose that sot of issue. Could cutadapt be installed on Windows, or R run on the Ubuntu machine, to avoid this bridging problem? Otherwise, you may need to seek local IT support.

**Comment by leixuRRH** [comment]
Yes, cutadapt was installed on Ubuntu (Linux shell) and R was run from Windows.  I think you are right.  The interface between these two must be the problem.  I do not know how to install cutadapt on Windows – the installation instruction does not include Windows as an option.  Do you have any tips?   I did try to install R studio in Ubuntu but it failed – IT was trying to help with that and they also could not figure out how to proceed.

**Comment by henry-w-g-birt** [comment]
If anyone needs a windows copy of cutadapt you can find it on github https://github.com/marcelm/cutadapt/releases
