### ISSUE TITLE
too many chimeras detected after merging reads, but not before

### ISSUE THREAD

**Issue by djiang77** [benjjneb/dada2#961]
Hi! I've been using dada2 on many sequencing runs for our lab. Most of them are 2X250 bp EMP protocol paired-end reads. And I always get reasonable results after removing chimeras (<25% chimeric)

However, one of the runs is 2x150 bp EMP and I'm getting weird results from chimera removal. When I run removeBimeraDenovo() on merged reads, I get:

ncol(seqtab.nochim)/ncol(seqtab) ##0.06355245
sum(seqtab.nochim)/sum(seqtab) ##0.6996633

But if I do run removeBimeraDenovo() on forward or reverse reads seperately, I get:

ncol(seqtab.R1.nochim)/ncol(seqtab.R1)  ## 0.3110391
sum(seqtab.R1.nochim)/sum(seqtab.R1) ## 0.8454428

ncol(seqtab.R2.nochim)/ncol(seqtab.R2)  ## 0.2286682
sum(seqtab.R2.nochim)/sum(seqtab.R2) ## 0.7876381

I found this really weird because somehow merging the reads cause most of my ASVs to be detected as chimeras... Do you have any ideas why this would be the case? Most of my reads will merge, and the yields are around 90% for the merging read step.

We are conducting a meta-analysis and the result from this run is definitely very different from the others, which are all 2X250 PE. We would like to make sure it's not artificial differences introduced by the pipeline. I personally don't think the primers cause an issue here because 1) it's the EMP protocol; 2) I've ran cutadapt just to make sure but it didn't help.

Thank so you much!!

**Comment by benjjneb** [comment]
16% and 21% chimeric reads are not out of bounds values, they happen in real experiments, albeit ones that did not do a good job optimizing their PCR parameters.

What I would triple-check is whether there any possibility the primers, even a part of them, could be included on the reads. To be clear, I suspect this is just unideal PCR conditions, but it's worth triple-checking the primer angle.

**Comment by djiang77** [comment]
Thanks for the response!

Did you see my result for the merged reads though? I got 31% chimeric reads after merging! And only 6% of the ASVs. I know that 16% and 21% are not bad, but these are the results for the forward and reverse reads. I need the results from merged reads. And I find it weird that the percentage dropped so much after merging. With my other runs, the percentage for chimeras in merged reads is about the average of forward and reverse reads, by themselves. 
It is not possible that the primers are included because I made sure that it was taken care of by cutadapt... All 3' and 5' primer sequences are removed.

Do you having any idea why more chimeras are detected after merging reads? Thanks!

**Comment by benjjneb** [comment]
That is unusual in my experience. Not sure what could be going on.

It is possible to get a higher chimera fraction in merged reads here though. Chimeras can occur at any point along the reads. In the forward and reverse reads you have ~150nts to detect a chimera. In the merged reads you have ~250nts to detect a chimera.

Actually, 250/150 is close to 31%/19%. I don't know for sure, but can't rule out that it might just be bad PCR protocol leading to high chimera formation.
