### ISSUE TITLE
Question: impact of samples on error learning

### ISSUE THREAD

**Issue by aistBMRG** [benjjneb/dada2#962]
Small question. 

Often, dataset may contain both mock samples and complex samples. For error learning, is any benchmarking data available evaluating the impact of which samples are used for error learning? Would any different results in terms of denoised reads be expected using the mock or actual samples for error leaning? Related, can we specify which samples are used for error learning, or could we achieve that be specific ordering of the samples?

Thanks a lot!

Dieter

**Comment by benjjneb** [comment]
> Would any different results in terms of denoised reads be expected using the mock or actual samples for error leaning?

They will typically be close. The exception is in the case of very high diversity samples, which are harder to learn the error rates from.

> Related, can we specify which samples are used for error learning, or could we achieve that be specific ordering of the samples?

Sure, just give `learnErrors` the specific samples you want it to use. You can also do it by ordering, put the samples you want it to use at the front.

**Comment by aistBMRG** [comment]
Thanks.
