### ISSUE TITLE
Running learnErrors after trimming with fastp

### ISSUE THREAD

**Issue by scra88le** [benjjneb/dada2#963]
I'm new dada2 and would like to use it on a set of sample files that have already been trimmed with fastp. Is it possible to do this when I try:

```
# Place filtered files in filtered/ subdirectory
filtFs <- file.path("data_analysis_files/edna_data/trimmed_reads", paste0(sample.names, "_1.fastq.gz"))
filtRs <- file.path("data_analysis_files/edna_data/trimmed_reads", paste0(sample.names, "_2.fastq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names

# Learn forward error rates
errF <- learnErrors(filtFs, multithread=TRUE)
# Learn reverse error rates
errR <- learnErrors(filtRs, multithread=TRUE)
```

I get the following error:

```
17108463 total bases in 56944 reads from 1 samples will be used for learning the error rates.

Error in dada(drps, err = NULL, errorEstimationFunction = errorEstimationFunction, : Invalid derep$uniques vector. Sequences must be made up only of A/C/G/T.
```

I looked at my file and I cannot see any sequences that contain anything but ACGT. Any ideas what I'm doing wrong here?

**Comment by benjjneb** [comment]
> I looked at my file and I cannot see any sequences that contain anything but ACGT. Any ideas what I'm doing wrong here?

There are non-ACGT characters that you aren't catching by eye. You can use `filterAndTrim` to remove those paired-end reads.

**Comment by scra88le** [comment]
Ok. Thanks. That did seem to solve the issue. Seems odd that `fastp` would introduce non ACGT characters. Can the same be achieved by just using the native `filterAndTrim` dada function?

**Comment by benjjneb** [comment]
> Can the same be achieved by just using the native filterAndTrim dada function?

Yes probably. `filterAndTrim` handles almost all filtering/trimming needs, except for variable length primer designs. See `?filterAndTrim` for more info.
