### ISSUE TITLE
unexpected behavior for technical replicates

### ISSUE THREAD

**Issue by aistBMRG** [benjjneb/dada2#967]
Hi Ben,

We are using DADA2 for an inter-laboratory study, with hopefully improvements over other tools in terms of reproducibility of the final measurement results.

Now, I am running into a somewhat unexpected finding.

Analyzing two technical replicates, I found that in one of the replicates (PCR replicates and sequencing in a single run) an ASV completely drops out. It seemed that this was due to a mismatch in the de-noised sequence, since allowing a mismatch during merging fixed the issue. Note that no other closely related sequences are in this mock sample. 

Did you observe such behavior previously? Or any idea what may be the cause for this?

FYI, below is the ASV and counts using both settings:

## allowing no mismatches during merging ##
asvSequence | rep1 | rep2
-- | -- | --
TACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTAGGCGGCCTTTTAAGTCAGCGGTGAAAGTCTGTGGCTCAACCATAGAATTGCCGTTGAAACTGGGGGGCTTGAGTATGTTTGAGGCAGGCGGAATGCGTGGTGTAGCGGTGAAATGCATAGATATCACGCAGAACCCCGATTGCGAAGGCAGCCTGCCAAGCCATTACTGACGCTGATGCACGAAAGCGTGGGGATCAAACAGG | 6391 | 0

## allowing one mismatches during merging ##
asvSequence | rep1 | rep2
-- | -- | --
TACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTAGGCGGCCTTTTAAGTCAGCGGTGAAAGTCTGTGGCTCAACCATAGAATTGCCGTTGAAACTGGGGGGCTTGAGTATGTTTGAGGCAGGCGGAATGCGTGGTGTAGCGGTGAAATGCATAGATATCACGCAGAACCCCGATTGCGAAGGCAGCCTGCCAAGCCATTACTGACGCTGATGCACGAAAGCGTGGGGATCAAACAGG | **6391** | **0**

asvSequence | rep1 | rep2
-- | -- | --
TACGGAGGATCCGAGCGTTATCCGGATTTATTGGGTTTAAAGGGTGCGTAGGCGGCCTTTTAAGTCAGCGGTGAAAGTCTGTGGCTCAACCATAGAATTGCCGTTGAAACTGGGGGGCTTGAGTATGTTTGAGGCAGGCGGAATGCGTGGTGTAGCGGTGAAATGCATAGATATCACGCAGAACCCCGATTGCGAAGGCAGCCTGCCAAGCCATTACTGACGCTGATGCACGAAAGCGTGGGGATCAAACAGG | **6391** | **5331**

The results are just a specific case, but I sporadically found this type of behavior -- that is an ASV resulting in zero reads for some replicates while it is abundant in other replicates. 

Any insights would be great.

Thanks,

Dieter.

**Comment by aistBMRG** [comment]
seems the tables got scrambled but I think the issue should be clear, 0 reads in rep2 when allowing 0 mismatches during merging.

**Comment by benjjneb** [comment]
That is interesting, I'm not sure...

Can you tell me a little bit more about your sequencing: I.e. what locus, what sequencing instrument? Also, are these technical replicates from the same run or different runs? What parameters are you using for filtering/trimming and for the rest of the pipeline (just defaults after filtering/trimming?).

**Comment by benjjneb** [comment]
Please re-open with updates if still looking for assistance.
