### ISSUE TITLE
Need to Compare ASVs and Original OTUs from a Single Bacterial Class DADA2 

### ISSUE THREAD

**Issue by enriqueza** [benjjneb/dada2#969]
Hello everyone,

I am super new to sequencing and DADA, and am relatively new to Github. I apologize if something like this has been posted before, I just couldn't find anything about it. I followed through the DADA2 MiSeq pipeline, and now I need to be able to take out the fasta files from a single class so I can compare the ASVs. I don't really know how to isolate them, is there any guidance on this? I'm also using phyloseq just like in the DADA tutorial. Any help is appreciated!

**Comment by benjjneb** [comment]
> now I need to be able to take out the fasta files from a single class so I can compare the ASVs

Can you clarify a bit what you are trying to do here? I think... you want to write all the ASV sequences from a single taxonomic Class out to a fasta file? Is that right?

**Comment by enriqueza** [comment]
Yeah, sorry I am looking for the ASV sequences from a class, "Zetaproteobacteria" to a single .fasta file.

**Comment by benjjneb** [comment]
It might be easiest to do this before going into phyloseq, if that makes sense for you. So, starting from the end of the dada2 part of the tutorial (i.e. before going into the phyloseq part):

```
is.zeta <- taxa[,"Class"] %in% "Zetaproteobacteria"
uniquesToFasta(getUniques(seqtab.nochim)[is.zeta], "path/to/ouput.fasta")
```

That will create a fasta file with all the Zeta ASVs, with id lines that include their abundance in the total dataset in uchime format. You can also define the fasta id lines by hand if you want, see `?uniquesToFasta` for more info.

**Comment by enriqueza** [comment]
It works! Thank you
