### ISSUE TITLE
DADA2 installation failed - Rcpp.h: No such file or directory

### ISSUE THREAD

**Issue by andreatorti** [benjjneb/dada2#97]
Hello,

I got the following message while trying to install DADA2 on R3.3.1 (Windows7) using the devtools method:

The downloaded binary packages are in
        C:\Users\torti\AppData\Local\Temp\RtmpkX86oo\downloaded_packages
"C:/PROGRA~1/R/R-33~1.1/bin/i386/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/torti/AppData/Local/Temp/RtmpkX86oo/devtoolsfa82397633/benjjneb-dada2-0962a7e" --library="\\ad.nfit.au.dk/NFDFS/Users/torti/Documents/R/win-library/3.3"  \
  --install-tests 

* installing *source* package 'dada2' ...
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -std=c++0x -I"C:/PROGRA~1/R/R-33~1.1/include" -DNDEBUG    -I"\\ad.nfit.au.dk/NFDFS/Users/torti/Documents/R/win-library/3.3/Rcpp/include" -I"\\ad.nfit.au.dk/NFDFS/Users/torti/Documents/R/win-library/3.3/RcppParallel/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
In file included from ../inst/include/dada2.h:7:0,
                 from RcppExports.cpp:4:
../inst/include/dada2_RcppExports.h:7:18: fatal error: Rcpp.h: No such file or directory
 #include <Rcpp.h>
                  ^
compilation terminated.
make: *** [RcppExports.o] Error 1
Warning: running command 'make -f "Makevars" -f "C:/PROGRA~1/R/R-33~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.1/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="dada2.dll" OBJECTS="RcppExports.o Rmain.o chimera.o cluster.o error.o evaluate.o filter.o misc.o nwalign_endsfree.o nwalign_vectorized.o pval.o strmap.o taxonomy.o"' had status 2
ERROR: compilation failed for package 'dada2'
* removing '\\ad.nfit.au.dk/NFDFS/Users/torti/Documents/R/win-library/3.3/dada2'
Error: Command failed (1)

I am not very familiar with R and coding in general, so I would appreciate any help.
Thanks!

**Comment by benjjneb** [comment]
Have you already installed Rtools (https://cran.r-project.org/bin/windows/Rtools/)? You need that to install from source on Windows.

If you're not very familiar with R/coding, it would probably be easier to install the release version from Bioconductor. You will need to have the current R3.3 version for that though.

**Comment by benjjneb** [comment]
I see you do have R3.3.1

Unless you really need multithreading, I'd go with the Bioconductor install then:

```
## try http:// if https:// URLs are not supported
source("https://bioconductor.org/biocLite.R")
biocLite("dada2")
```

**Comment by andreatorti** [comment]
Yes, I already have RTools installed.

The installation with Bioconductor ran smoothly, but when I tried to load DADA2, I got the following:

> library("dada2")
Error: package ‘Rcpp’ required by ‘dada2’ could not be found
> traceback()
3: stop(gettextf("package %s required by %s could not be found", 
       sQuote(pkg), sQuote(pkgname)), call. = FALSE, domain = NA)
2: .getRequiredPackages2(pkgInfo, quietly = quietly)
1: library("dada2")

which is weird because I could see that Rcpp was properly installed together will all the other packages while running > biocLite("dada2"):

package ‘Rcpp’ successfully unpacked and MD5 sums checked

**Comment by benjjneb** [comment]
Hm...

Try removing Rcpp and reinstalling?

```
remove.packages("Rcpp") # repeat until you get an error that it isn't there
biocLite("Rcpp")
```

Then maybe reinstall dada2 as well.

**Comment by andreatorti** [comment]
I ran biocLite("Rcpp") and it worked, but then library("dada") returned

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘BiocParallel’
Error: package or namespace load failed for ‘dada2’

I then tried to install BiocParallel, without much success:

> biocLite("BiocParallel")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.3 (BiocInstaller 1.22.3), R 3.3.1 (2016-06-21).
Installing package(s) ‘BiocParallel’
also installing the dependencies ‘lambda.r’, ‘futile.options’, ‘futile.logger’, ‘snow’


  There is a binary version available but the source version is later:
             binary source needs_compilation
BiocParallel  1.6.2  1.6.3             FALSE

trying URL 'https://mirrors.ebi.ac.uk/CRAN/bin/windows/contrib/3.3/lambda.r_1.1.9.zip'
Content type 'application/zip' length 73386 bytes (71 KB)
downloaded 71 KB

trying URL 'https://mirrors.ebi.ac.uk/CRAN/bin/windows/contrib/3.3/futile.options_1.0.0.zip'
Content type 'application/zip' length 16710 bytes (16 KB)
downloaded 16 KB

trying URL 'https://mirrors.ebi.ac.uk/CRAN/bin/windows/contrib/3.3/futile.logger_1.4.3.zip'
Content type 'application/zip' length 91816 bytes (89 KB)
downloaded 89 KB

trying URL 'https://mirrors.ebi.ac.uk/CRAN/bin/windows/contrib/3.3/snow_0.4-1.zip'
Content type 'application/zip' length 65289 bytes (63 KB)
downloaded 63 KB

package ‘lambda.r’ successfully unpacked and MD5 sums checked
package ‘futile.options’ successfully unpacked and MD5 sums checked
package ‘futile.logger’ successfully unpacked and MD5 sums checked
package ‘snow’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\torti\AppData\Local\Temp\Rtmpe0lazZ\downloaded_packages
installing the source package ‘BiocParallel’

trying URL 'https://bioconductor.org/packages/3.3/bioc/src/contrib/BiocParallel_1.6.3.tar.gz'
Content type 'application/x-gzip' length 621097 bytes (606 KB)
downloaded 606 KB

'\\ad.nfit.au.dk\NFDFS\Users\torti\Documents'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
* installing *source* package 'BiocParallel' ...
** R
** inst
** preparing package for lazy loading
** help
Warning in packageDescription("BiocParallel") :
  no package 'BiocParallel' was found
Error : C:/Users/torti/AppData/Local/Temp/RtmpGGLquq/R.INSTALLd3457174861/BiocParallel/man/BiocParallel-package.Rd:21: $ operator is invalid for atomic vectors
ERROR: installing Rd objects failed for package 'BiocParallel'
* removing '\\ad.nfit.au.dk/NFDFS/Users/torti/Documents/R/win-library/3.3/BiocParallel'

The downloaded source packages are in
        ‘C:\Users\torti\AppData\Local\Temp\Rtmpe0lazZ\downloaded_packages’
Warning messages:
1: running command '"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" CMD INSTALL -l "\\ad.nfit.au.dk\NFDFS\Users\torti\Documents\R\win-library\3.3" C:\Users\torti\AppData\Local\Temp\Rtmpe0lazZ/downloaded_packages/BiocParallel_1.6.3.tar.gz' had status 1 
2: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘BiocParallel’ had non-zero exit status

**Comment by andreatorti** [comment]
Repeating DADA2 installation also did not help

**Comment by benjjneb** [comment]
Did you try to do a source install of RcppParallel when prompted? If so, don't. Just install the earlier version that's available as a binary.

Could you also post the output of the `.libPaths()` command (from an R session)?

**Comment by andreatorti** [comment]
I  don't recall being prompted to install RcppParallel at all, however:

> packageVersion("RcppParallel")
[1] ‘4.3.19’

Is that the right one?

Regarding the library paths:

> .libPaths()
[1] "\\\\ad.nfit.au.dk/NFDFS/Users/torti/Documents/R/win-library/3.3" "C:/Program Files/R/R-3.3.1/library"

**Comment by benjjneb** [comment]
The question is whether the packages are being installed into the directories in your libPath (i.e. where R can find them).

As I understand it, when you try to load dada2, it is failing because it can't load RcppParallel? Can you repeat the error message you get when you `library(dada2)` at this point?

**Comment by benjjneb** [comment]
Also, do you have full permissions to read and write to "\\ad.nfit.au.dk/NFDFS/Users/torti/Documents/R/win-library/3.3"?
