### ISSUE TITLE
Memory error in dereplication for PacBio sequences

### ISSUE THREAD

**Issue by mjamy** [benjjneb/dada2#970]
Hi! 

I'm processing 4200 base pair rDNA amplicon data from microbial eukaryotic communities. These were sequenced with Sequel II, so the input file contains close to 500,000 sequences. 

The filtration steps work okay with around 335,000 (~66%) sequences filtered through. However, I get an error when I dereplicate. I'm running R version 3.6.2 and DADA2 version 1.14.1.

Input:
``` drp1 <- derepFastq(filt1, verbose=TRUE)```

Output:
```
Dereplicating sequence entries in Fastq file: pt_008_001.ccsreads.fastq.gz
Error in asMethod(object) : long vectors not supported yet: memory.c:3717
```
It seems like a limitation of R, but I wonder if you have any suggestions on how I could proceed. Any help would be greatly appreciated!

Thank you,
Mahwash

**Comment by benjjneb** [comment]
Yeah, you are probably running up against a current hard limit on the size of R vectors at ~2^32.

One thing I would try is to look at a subset of this data, to check if all the sequences are unique. For example, try to `head -n 40000 myseqs.fastq > my10Kseqs.fastq` (in shell) and then `derepFastq("my10Kseqs.fastq", verbose=TRUE)` (in R). Are all the sequences unique? If so, the dada2 pipeline might not be appropriate for your data.

**Comment by mjamy** [comment]
Thanks for your fast response! 

It does seem indeed that the dada2 pipeline is not appropriate for this data. I processed around half the sequences this time (~220,000 sequences), and got the following output after dereplication:

```
Encountered 222627 unique sequences from 223166 total sequences read.
```

I am however still interested in using DADA2 for the initial filtration. Is it possible to export the output of the following as a fasta file?

```
track <- filterAndTrim(nop, filt, minQ=3, minLen=3000, maxLen=6000, maxN=0, rm.phix=FALSE, maxEE=4, verbose=TRUE)
```

Thanks in advance!

**Comment by benjjneb** [comment]
>  Is it possible to export the output of the following as a fasta file?

Converting fastq to fasta is easy via the ShortRead package in R:

```
library(ShortRead)
fn <- "path/to/my.fastq"
writeFasta(readFastq(fn), "~/Desktop/test.fa", width=20000L)
```

will produce a fasta file from the fastq (you're basically reading in the fastq, then writing it out as a fasta).

**Comment by mjamy** [comment]
Ah, sorry, I meant exporting the _filtered_ sequences as a fasta. In particular, after running the ```filterAndTrim``` command. 

Many thanks!

**Comment by benjjneb** [comment]
Yep, same as above just use `filt` instead of `fn`.

**Comment by mjamy** [comment]
Ah of course! Thank you!
