### ISSUE TITLE
PCR Duplicates

### ISSUE THREAD

**Issue by RoundTab1er** [benjjneb/dada2#973]
I was reading the paper for the original dada algorithm, and it states that one of the assumptions is that each sequence came from a unique mrna molecule. Is dada2 able to remove pcr duplicates?

**Comment by benjjneb** [comment]
> Is dada2 able to remove pcr duplicates?

What exactly do you mean by PCR duplicates here? Like, if two reads came from the same original PCR molecule, will dada2 remove one of them? The answer to that is no. In order to do that you have to use a UMI type approach that labels the original molecules.

**Comment by RoundTab1er** [comment]
That is what I meant. I recently saw this issue (https://github.com/benjjneb/dada2/issues/755) regarding using dada2 on ig repertoire sequencing. I was considering using dada2 for the analysis, but I have 2x250bp miseq reads with UMIs. It sounds like this might not be the best approach

**Comment by benjjneb** [comment]
There are dedicated UMI-sequencing methods out there, which may be more appropriate in your case, at least if the sequencing you did actually had high read-coverage per UMI.
