### ISSUE TITLE
When to worry about error plots?

### ISSUE THREAD

**Issue by mcamarareis** [benjjneb/dada2#975]
Hi, 

First I would like to thank you for developing this great tool and for being so helpful with all the users.

I've used dada2 to denoise 16S rRNA Miseq 2x250 reads only for few times and recently I got this kind of error plots after running the error models.
I used a sample of 2e8 bases of the data and randomize=TRUE

[errF_200210_1.pdf](https://github.com/benjjneb/dada2/files/4361136/errF_200210_1.pdf)
[errR_200210_1.pdf](https://github.com/benjjneb/dada2/files/4361137/errR_200210_1.pdf)

The first thing that called my attention was the dots that appear quite far from the model line. Besides the T2C at the forward plot (which increase around Q30) and the C2G in the reverse model that appears under the red line.

Should I worry about these models or can I proceed to the other steps?
This is a recurrent doubt that I have, when I should really worry about the error plots. 

Thank you in advance.

**Comment by benjjneb** [comment]
The error plots you shared are probably fine. The "hook" at the end of some transitions is something that comes up in some datasets. It is typically driven by a very high density of maximum quality score bases, which interacts with the weighted loess-score error-model fitting. In theory this could lead to some false-positives for bases in the area of the "hook", i.e. ~34-39, but in practice this occurs when there are very few of such bases and so has little effect.

For me, I would just proceed to further steps. If you want ot be super careful, you could enforce monotonicity on the error models by hand.

**Comment by mcamarareis** [comment]
Hi, 
thanks a lot for helping me to understand the error plots.
Regarding the C2G in the reverse plot (that appears under the red line) isn't it something to worry about?  The estimated error rate under the expected for the quality score?

**Comment by benjjneb** [comment]
I am not concerned by that error plot at all. The red lines are what Q scores should mean, but in practice they don't exactly match their theoretical definition.

The C2G in the reverse plot is a bit under the red line, but the model (black line) fits the observations (black points) well, and overall is showing decreasing error rates with higher quality scores just as expected. Looks fine to me.
