### ISSUE TITLE
ITS primer orientation

### ISSUE THREAD

**Issue by BoraKim2018** [benjjneb/dada2#977]
Hello, 

Thank you for developing a nice pipeline. 
I am following the ITS tutorial using my ITS data set. At the step for checking primer orientation, my data set showed: 

![image](https://user-images.githubusercontent.com/45657095/77350384-be83de80-6d3c-11ea-9a4e-f4533abad524.png)

Which is very strange. I could suspect RevComp would be due to short ITS length but it's difficult imagine why there is no Forward count.  Would you kindly explain any possibility? Thank you in advance for your time.

**Comment by benjjneb** [comment]
The FWD primer (that you defined in R) is showing up in the reverse-complement orientation on the reverse reads.

The REV primer (that you defined in R) is showing up in the reverse-complement orientation on the forward reads.

Nothing concerning about that really, this is just letting you know that the primers are on your reads in different orientation than you probably expected.

**Comment by BoraKim2018** [comment]
@benjjneb Thank you very much for your fast response. 

I think I made it! (although I am very confident..). 

These were my original primer sequence: 
Forward- CTTGGTCATTTAGAGGAAGTAA
Reverse- GCTGCGTTCTTCATCGATGC

For this time, I used previous reverse as new Forward and previous reverse-complement of forward as a new Reverse:

New forward - GCATCGATGAAGAACGCAGC
New reverse - TTACTTCCTCTAAATGACCAAG

And tada! 

![image](https://user-images.githubusercontent.com/45657095/77353846-078a6180-6d42-11ea-90b4-175173f0a80f.png)


Just to be clear, when I remove primers in my sequences, I should use new forward and reverse orientation, right?

**Comment by benjjneb** [comment]
> Is it nicely done? and just to be clear, when I remove primers in my sequences, I should use new forward and reverse orientation, right?

Yep that should work with the tutorial.

**Comment by BoraKim2018** [comment]
@benjjneb Great! Thank you very much! Have a good day.

**Comment by BoraKim2018** [comment]
Hi @benjjneb , I've got other problem. I thought successfully removed primer in my sequence by cutadapt and then I wanted to check quality plot, but I've got error said, 

```
plotQualityProfile(cutFs[4])
```
> Error in data.frame(sequence = names(freqtbl$top), count = as.integer(freqtbl$top),  :  arguments imply differing number of rows: 0, 1

So I've tried 

```
fn <- cutFs[4]
srq <- readFastq(fn)
seqlen.tab <- table(width(srq)) # Table of how many RSVs have a given length in nts
seqlen.tab
```
>table of extent 0 

I checked output files after cutadapt, and the size of all files were 0 kb. 
Seems like cutadapt remove all my sequence? 
Can you help me to solve this problem?

Cutadapt worked fine in my system
```
system2(cutadapt, args = "--version")
```
>1.18

In case here is one of traceback when the cutadapt was running


>This is cutadapt 1.18 with Python 3.7.6
Command line parameters: -g GCATCGATGAAGAACGCAGC -a CTTGGTCATTTAGAGGAAGTAA -G TTACTTCCTCTAAATGACCAAG -A GCTGCGTTCTTCATCGATGC -n 2 -m 1 -o /home/bkim/Ricebiome/rice_sequencing_process/Rice_ITS_Bora/ITS_adapter_trim/cutadapt/R-Q9-r_R1_trim.fastq -p /home/bkim/Ricebiome/rice_sequencing_process/Rice_ITS_Bora/ITS_adapter_trim/cutadapt/R-Q9-r_R2_trim.fastq /home/bkim/Ricebiome/rice_sequencing_process/Rice_ITS_Bora/ITS_adapter_trim/filtN/R-Q9-r_R1_trim.fastq /home/bkim/Ricebiome/rice_sequencing_process/Rice_ITS_Bora/ITS_adapter_trim/filtN/R-Q9-r_R2_trim.fastq
Processing reads on 1 core in paired-end mode ...
Traceback (most recent call last):
  File "/home/bkim/miniconda3/bin/cutadapt", line 12, in <module>
    sys.exit(main())
  File "/home/bkim/miniconda3/lib/python3.7/site-packages/cutadapt/__main__.py", line 798, in main
    stats = runner.run()
  File "/home/bkim/miniconda3/lib/python3.7/site-packages/cutadapt/pipeline.py", line 188, in run
    (n, total1_bp, total2_bp) = self.process_reads()
  File "/home/bkim/miniconda3/lib/python3.7/site-packages/cutadapt/pipeline.py", line 317, in process_reads
    for read1, read2 in self._reader:
  File "/home/bkim/miniconda3/lib/python3.7/site-packages/cutadapt/seqio.py", line 400, in __iter__
    r1 = next(it1)
  File "src/cutadapt/_seqio.pyx", line 136, in __iter__
  File "/home/bkim/miniconda3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by benjjneb** [comment]
Your `fnFs.noN` files are gzipped, but don't have a `.gz` extension, hence cutadapt is failing to understand the file (it is expecting a flat fastq files).

You can remedy this by going to the previous step, and using the `compress=FALSE` option. I.e.

```
fnFs.filtN <- file.path(path, "filtN", basename(fnFs)) # Put N-filterd files in filtN/ subdirectory
fnRs.filtN <- file.path(path, "filtN", basename(fnRs))
filterAndTrim(fnFs, fnFs.filtN, fnRs, fnRs.filtN, maxN = 0, multithread = TRUE, compress=FALSE)
```

Or you could just gzip all your files at the beginning.
