### ISSUE TITLE
Couldn't find SILVA_SSU_r132_March2018.RData to download

### ISSUE THREAD

**Issue by akalichen** [benjjneb/dada2#979]
Hi Ben, 

While I was going through your new tutorial, I found myself lost when trying to download the SILVA_SSU_r132_March2018.RData. Could you kindly remind me where I may find this? I could not find it on the SILVA website. 

Best,
Cheng

**Comment by dswan** [comment]
They're from DECIPHER

www2.decipher.codes/Classification/TrainingSets/SILVA_SSU_r132_March2018.RData

**Comment by akalichen** [comment]
Thanks @dswan!
