### ISSUE TITLE
only few merged reads remain

### ISSUE THREAD

**Issue by HenrikEckermann** [benjjneb/dada2#980]
Hi,

I have read the FAQ and saw this question is addressed but I do not know how to proceed.

I have 742 paired end samples from Ilumnina HiSeq runs that I demultiplexed. Barcodes and primers (515F - 806Rd)  are removed and I have one fastq.gz file per sample as in the dada2 tutorial. This is the first time that I process raw data for taxonomic assignment. I walked through the exact steps of the tutorial once with the example data and the with my data.

I attach some quality plots as example.

I used two strategies (bases on the FAQ). For the first attempt, I used `filterAndTrim` with the settings as in the tutorial. Out of the e.g. 237219 reads there remain a little less after filtering/trimming etc. But after merging it drops to 0-50. Then I tried without truncating in the hope that this might be the issue. But again only few sequences are left after merging. What can I do to find the problem?

edit: I also attached the error plot. 

<img width="689" alt="Screenshot 2020-03-25 at 11 41 33" src="https://user-images.githubusercontent.com/22709846/77528130-aa032b80-6e8d-11ea-836d-64eb88b4a100.png">
<img width="678" alt="Screenshot 2020-03-25 at 11 41 18" src="https://user-images.githubusercontent.com/22709846/77528135-acfe1c00-6e8d-11ea-9e0f-99625ae385a0.png">
<img width="674" alt="Screenshot 2020-03-25 at 11 40 40" src="https://user-images.githubusercontent.com/22709846/77528137-ae2f4900-6e8d-11ea-976a-95572e6a6c8f.png">
<img width="680" alt="Screenshot 2020-03-25 at 11 40 19" src="https://user-images.githubusercontent.com/22709846/77528139-ae2f4900-6e8d-11ea-959c-1cbe25e0a83e.png">
<img width="694" alt="Screenshot 2020-03-25 at 13 23 40" src="https://user-images.githubusercontent.com/22709846/77536111-14bb6380-6e9c-11ea-9743-3193e24dc10c.png">

**Comment by benjjneb** [comment]
My strong suspicion is that the amplicon you have sequenced is not actually 515F/806R, but is something else.

Could you post the output of the following, on the raw (i.e. unfiltered/untrimmed) sequencing data from an example sample?

```{r}
dada2:::pfasta(getSequences(derepFastq("path/to/example_R1.fastq.gz"))[1:5])
dada2:::pfasta(getSequences(derepFastq("path/to/example_R2.fastq.gz"))[1:5])
```

**Comment by HenrikEckermann** [comment]
Hi benjjneb,

thanks so much for support.

Here the output:

Forward library 1

```
>1
GATCGGAAGAGCACACGTCTGAACTCCAGTCACAGAAGCCTATCTCGTATGCCGTCTTCTGCTTGAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
>2
GATCGGAAGAGCACACGTCTGAACTCCAGTCACAGAAGCCTATCGCGTATGCCGTCTTCTGCTTGAAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
>3
GGTAGAATGTGTGTCAGCCGCCGCGGTAATACGTATGGTGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGCAGGCGGTGCGGCAAGTCTGATGTGAAAGCCCGGGGCTCAACCCCGGTACTGCATTGGAAACTGTCGTACTAGA
>4
AAGGAGCGGTGTGCCAGCCGCCGCGGTAATACGTATGGTGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGCAGGCGGTGCGGCAAGTCTGATGTGAAAGCCCGGGGCTCAACCCCGGTACTGCATTGGAAACTGTCGTACTAGA
>5
GATCGGAAGAGCACACGTCTGAACTCCAGTCACAGAAGCCTATCTCGTATGCCGTCTTCTGCTTGAACAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
```


Reverse library 1:

```
>1
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
>2
CATAAGCGGTGTGCCAGCCGCCGCGGTAATACGTAGGGTGCAAGCGTTATCCGGAATTATTGGGCGTAAAGGGCTCGTAGGCGGTTCGTCGCGTCCGGTGTGAAAGTCCATCGCTTAACGGTGGATCCGCGCCGGGTACGGGCGGGCTTGA
>3
CATAAGCGGTGTGTCAGCCGCCGCGGTAATACGTAGGGTGCAAGCGTTATCCGGAATTATTGGGCGTAAAGGGCTCGTAGGCGGTTCGTCGCGTCCGGTGTGAAAGTCCATCGCTTAACGGTGGATCCGCGCCGGGTACGGGCGGGCTTGA
>4
CGCAAGCTGTGTGTCAGCCGCCGCGGTAATACGTAGGGTGCAAGCGTTATCCGGAATTATTGGGCGTAAAGGGCTCGTAGGCGGTTCGTCGCGTCCGGTGTGAAAGTCCATCGCTTAACGGTGGATCCGCGCCGGGTACGGGCGGGCTTGA
>5
AAGGAGCGGTGTGCCAGCAGCCGCGGTAATACGTATGGTGCAAGCGTTATCCGGATTTACTGGGTGTAAAGGGAGCGCAGGCGGTGCGGCAAGTCTGATGTGAAAGCCCGGGGCTCAACCCCGGTACTGCATTGGAAACTGTCGTACTAGA
```

**Comment by benjjneb** [comment]
A few things going on here. First, as is clear from the above, you have some significant low-complexity infiltration in your libraries. You can inspect this more using `plotComplexity("path/to/example.fastq.gz")`.

Second, these forward and reverse sequences do not appear to be in consistent expected orientations. For example, forward read 3 and Reverse read 5 are the same sequence over the non-barcode-primer region. What orientations of reads did this library preparation produce?

Third, these are 2x151 reads, so 302 total nucleotides. The primers are sequenced, and there also appears to be an additional 10nts sequence in front of the primers (barcode? adapter?). So, you're "sequenced amplicon" is ~252nts (V4) + ~20nts (primers) + ~20 nts (nts before primers) = ~310 nts. That is, they are longer than your total read length, and your reads will not overlap.

You could try to just analyze the forward reads alone, assuming the low-complexity infiltration is not so bad it overwhelms the libraries entirely. Or you could redo the sequencing with a an appropriate sequencing/library method.

**Comment by HenrikEckermann** [comment]
Just so I understood correctly: The `path/to/example_R1.fastq.gz` in the example of `dada2:::pfasta(getSequences(derepFastq("path/to/example_R1.fastq.gz"))[1:5])` should be the file that is not yet demultiplexed (that still has primers and barcodes), right?  In my specific case, I had 24 files because there were 12 libraries with forward and reverse reads. So above, that file is a file of the entire first library with primers and barcodes.

Or should I have given the output of one sample that has been demultiplexed already? If that is the case, see this for one sample:  

sample 1 forward (primers and barcodes removed)

```
>1
TCCTGTTTGCTACCCATGCTTTCGAGCCTCAGCGTCAGTTGGTGCCCAGTAGACCGCCTTCGCCACTGGTGTTCCTCCCGATATCTACGCATTCCACCGCTACACCGGGAATTCCATCTACC
>2
AACGTAGGGTGCAAGCGTTGTCCGGAATTACTGGGTGTAAAGGGAGCGCAGGCGGGAAGACAAGTTGGAAGTGAAAACCATGGGCTCAACCCATGAATTGCTTTCAAAACTGTTTTTCTTGA
>3
TCCTGTTTGCTCCCCACGCTTTCGAGCCTCAACGTCAGTTACCGTCCAGTAAGCCGCCTTCGCCACTGGTGTTCCTCCTAATATCTACGCATTTCACCGCTACACTAGGAATTCCGCTTACC
>4
TCCTGTTTGCTACCCACACTTTCGAGCCTCAGCGTCAGTTGGTGCCCAGTAGGCCGCCTTCGCCACTGGTGTTCCTCCCGATATCTACGCATTCCACCGCTACACCGGGAATTCCGCCTACC
>5
TACGTAGGGTGCAAGCGTTATCCGGAATTATTGGGCGTAAAGGGCTCGTAGGCGGTTCGTCGCGTCCGGTGTGAAAGTCCATCGCTTAACGGTGGATCCGCGCCGGGTACGGGCGGGCTTGA
```

sample 1 reverse (primers and barcode removed)

```
>1
CCTGTTTGCTACCCATGCTTTCGAGCCTCAGCGTCAGTTGGTGCCCAGTAGACCGCCTTCGCCACTGGTGTTCCTCCCGATATCTACGCATTCCACCGCTACACCGGGAATTCCATCTACC
>2
ACGTAGGGTGCAAGCGTTGTCCGGAATTACTGGGTGTAAAGGGAGCGCAGGCGGGAAGACAAGTTGGAAGTGAAAACCATGGGCTCAACCCATGAATTGCTTTCAAAACTGTTTTTCTTGA
>3
CCTGTTTGCTCCCCACGCTTTCGAGCCTCAACGTCAGTTACCGTCCAGTAAGCCGCCTTCGCCACTGGTGTTCCTCCTAATATCTACGCATTTCACCGCTACACTAGGAATTCCGCTTACC
>4
CCTGTTTGCTACCCACACTTTCGAGCCTCAGCGTCAGTTGGTGCCCAGTAGGCCGCCTTCGCCACTGGTGTTCCTCCCGATATCTACGCATTCCACCGCTACACCGGGAATTCCGCCTACC
>5
ACGTAGGGTGCAAGCGTTATCCGGAATTATTGGGCGTAAAGGGCTCGTAGGCGGTTCGTCGCGTCCGGTGTGAAAGTCCATCGCTTAACGGTGGATCCGCGCCGGGTACGGGCGGGCTTGA
```

Complexity for this one sample:

```
plotComplexity(sample_1_F)
```

<img width="440" alt="Screenshot 2020-03-26 at 16 39 13" src="https://user-images.githubusercontent.com/22709846/77665911-92589f80-6f80-11ea-8138-57b54dc0ee81.png">


Complexity for the entire first library (forward reads)

```
plotComplexity(library_1_F)
``` 

<img width="428" alt="Screenshot 2020-03-26 at 16 41 41" src="https://user-images.githubusercontent.com/22709846/77666092-cc29a600-6f80-11ea-9d56-7cc712fddf6e.png">

**Comment by benjjneb** [comment]
Yes it is OK to look at the primer-removed files as well. There you see your forward reads are 121 nts and reverse reads are 122 nts, which is not enough to overlap with each other, since the targeted V4 amplicon is ~252nts, and 252 > 121+122.

Given that the demultiplexing seems to remove the low-complexity part of the data (i.e. the secondary mode in the library plot), you are probably fine to go forward with this data, but just using the forward reads.

**Comment by HenrikEckermann** [comment]
Thanks a lot for your time and effort benjjneb. With that information I can go on!
