### ISSUE TITLE
Taxonomy Assignments:

### ISSUE THREAD

**Issue by katieloutogher1** [benjjneb/dada2#981]
Hi, 

I was hoping you could help me trouble shoot a project I am working with. The samples are 16S mucousal using 926F-1392wR primers. I processed the sample through R with the latest dada2 release.

When I assign against GreenGenes I get 'Rickettsiales mitochondria' as the dominant ASV for most samples. See excel attached. (Sequence Below)

Is it possible that this is an accurate assignment? Or would it be resulting from not enough filtering? OR perhaps contamination? And if so how would you recommend I handle it?

If I keep the assignments would you  recommend to filter out? Or should this be kept in the downstream analysis? (There does seem to be a variation (reaching  significance) in the amount of this ASV between one of my groupings)

Thanks, 
Katie

filter <- filterAndTrim(fwd=file.path(pathF, fastqFs), filt=file.path(filtpathF, fastqFs),
              rev=file.path(pathR, fastqRs), filt.rev=file.path(filtpathR, fastqRs),
              trimLeft=c(20,15), truncLen=c(280,240),
              maxEE=2, maxN=0, truncQ=2, rm.phix=TRUE,
              verbose=TRUE, multithread=FALSE)

[Total ASV Count_B.xlsx](https://github.com/benjjneb/dada2/files/4390197/Total.ASV.Count_B.xlsx)

TACTTTATATCCATCTAGAGGAGCCTGTTCTATAATCGATAAACCCCGCTCTACCTCACCATCTCTTGCTAATTCAGCCTATATACCGCCATCTTCAGCAAACCCTAAAAAGGTATTAAAGTAAGCAAAAGAATCAAACATAAAAACGTTAGGTCAAGGTGTAGCCAATGAAATGGGAAGAAATGGGCTACATTTTCTTATAAAAGAACATTACTATACCCTTTATGAAACTAAAGGACTAAGGAGGATTTAGTAGTAAATTAAGAATAGAGAGCTTAATTGAATTGAGCAATGAAGTAC

**Comment by benjjneb** [comment]
> When I assign against GreenGenes I get 'Rickettsiales mitochondria' as the dominant ASV for most samples. See excel attached. (Sequence Below)
>
>Is it possible that this is an accurate assignment? Or would it be resulting from not enough filtering? OR perhaps contamination? And if so how would you recommend I handle it?

When I Blast that sequence against nt, I get a 100% match to mus musculus mitochondria.

So, my guess is that this is mouse microbiome data, and unfortunately the primers you've chosen are amplifying the mouse mitochondria, which is therefore dominating your total reads.

I'd recommend explicitly filtering out any data that is a close match to mouse mitochondria, and then you might be in business.

ps: GreenGenes is essentially defunct at this point, it has not been updated in years (2013?).

**Comment by katieloutogher1** [comment]
Thank you very much. 

Yes mouse samples. 
I assigned against SILVA also and was originally just removing this ASV as a SILVA NA. So that is what I will proceed with 

I have always employed a downstream filtering of removing any samples <1000 OTU; before I starting using dada2 and ASV. Would you recommend doing the same with the samples < 1000 ASVs?

**Comment by benjjneb** [comment]
> I have always employed a downstream filtering of removing any samples <1000 OTU; before I starting using dada2 and ASV. Would you recommend doing the same with the samples < 1000 ASVs?

Do you mean <1000 reads?

If so, that kind of filtering can be appropriate. The specific cutoff value that is appropriate depends on your dataset though. Typically, I will plot the library sizes of all my samples, and usually find a very small number that "failed" and produced very few reads, and choose a cutoff value to remove those. The cutoff of 1000 is not a bad default value though.
