### ISSUE TITLE
cutadapt: error: unrecognized arguments:

### ISSUE THREAD

**Issue by AMFBio** [benjjneb/dada2#984]
Hi there, 

I'm having issues with running the "# Run Cutadapt" command in the ITS primer trimming tutorial. 

I.e. this step:

for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                             fnFs.filtN[i], fnRs.filtN[i])) # input files

I get a long list of errors that look like this:

cutadapt: error: unrecognized arguments: Files/R resources/GEM analyses/GEM15 Sequence files (DADA2 format)/cutadapt/SAMPLE1_1.fastq.gz Z:/PhD Files/R resources/GEM analyses/GEM15 Sequence files (DADA2 format)/filtN/SAMPLE1_2.fastq.gz Z:/PhD Files/R resources/GEM analyses/GEM15 Sequence files (DADA2 format)/filtN/SAMPLE1_1.fastq.gz
Run "cutadapt --help" to see command-line options.
See https://cutadapt.readthedocs.io/ for full documentation.

And then if I run the following command to see further info:

rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.cut[[1]]), 
    FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.cut[[1]]), 
    REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.cut[[1]]), 
    REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.cut[[1]]))

I get this error:
Error: Input/Output
  no input files found
  dirPath: Z:/PhD Files/R resources/GEM analyses/GEM15 Sequence files (DADA2 format)/cutadapt/SAMPLE1_2.fastq.gz
  pattern: character(0)

I'm not sure if it makes a difference, but my FWD and REV files were mixed up somehow (they were given to me like that) so FWD is actually R2 and REV is R1. This is what I get when I check for the primers:

                 Forward Complement Reverse RevComp
FWD.ForwardReads   15386          0       0       0
FWD.ReverseReads       0          0       0     253
REV.ForwardReads       0          0       0     264
REV.ReverseReads   16145          0       0       0

Prior to swapping the R1 and R2s around the table looked strange (FWD was in reverse reads etc). 

Not sure how to fix the error above, so any help would be appreciated! :)

I'm running in RStudio, Version 1.2.1335

**Comment by AMFBio** [comment]
To give some more back ground, here's my full code:

library(dada2)
packageVersion("dada2")
library(ShortRead)
packageVersion("ShortRead")
library(Biostrings)
packageVersion("Biostrings")


path<- "Z:/PhD Files/R resources/GEM analyses/GEM15 Sequence files (DADA2 format)"

list.files(path)

#DADA2 sequence processing

#Note that FWD are R2
fnFs <- sort(list.files(path, pattern = "_2.fastq.gz", full.names = TRUE))

#Note that REV are R1
fnRs <- sort(list.files(path, pattern = "_1.fastq.gz", full.names = TRUE))

FWD <- "TCGATGAAGAACGYAGYRAA"

REV <- "TCCTCCGCTTATTGATATGC"

allOrients <- function(primer) {
    # Create all orientations of the input sequence
    require(Biostrings)
    dna <- DNAString(primer)  # The Biostrings works w/ DNAString objects rather than character vectors
    orients <- c(Forward = dna, Complement = complement(dna), Reverse = reverse(dna), 
        RevComp = reverseComplement(dna))
    return(sapply(orients, toString))  # Convert back to character vector
}
FWD.orients <- allOrients(FWD)
REV.orients <- allOrients(REV)

FWD.orients

fnFs.filtN <- file.path(path, "filtN", basename(fnFs)) # Put N-filterd files in filtN/ subdirectory

fnRs.filtN <- file.path(path, "filtN", basename(fnRs))


filterAndTrim(fnFs, fnFs.filtN, fnRs, fnRs.filtN, maxN = 0, multithread = FALSE) #This takes around 7 minutes
#multithread is FALSE because I'm working in RStudio in Windows

primerHits <- function(primer, fn) {
    # Counts number of reads in which the primer is found
    nhits <- vcountPattern(primer, sread(readFastq(fn)), fixed = FALSE)
    return(sum(nhits > 0))
}

rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.filtN[[1]]), 
    FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.filtN[[1]]), 
    REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.filtN[[1]]), 
    REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.filtN[[1]]))

                                   Forward Complement Reverse RevComp
FWD.ForwardReads   15386             0                 0            0
FWD.ReverseReads       0                  0                0           253
REV.ForwardReads       0                   0                0            264
REV.ReverseReads   16145                0                0            0


cutadapt <- "C:/Users/yolan/AppData/Roaming/Python/Python37/Scripts/cutadapt"

system2(cutadapt, args = "--version") # Run shell commands from R
#shows version 2.9

path.cut <- file.path(path, "cutadapt")
if(!dir.exists(path.cut)) dir.create(path.cut)
fnFs.cut <- file.path(path.cut, basename(fnFs))
fnRs.cut <- file.path(path.cut, basename(fnRs))

FWD.RC <- dada2:::rc(FWD)
REV.RC <- dada2:::rc(REV)

# Trim FWD and the reverse-complement of REV off of R1 (forward reads)
##NOTE that I have changed this to R2 for FWD
R2.flags <- paste("-G", FWD, "-A", REV.RC) 

# Trim REV and the reverse-complement of FWD off of R2 (reverse reads)
##NOTE that I have changed this to R1 for REV
R1.flags <- paste("-g", REV, "-a", FWD.RC) 
# Run Cutadapt
##this is where i run into problems:

for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                             fnFs.filtN[i], fnRs.filtN[i])) # input files

**Comment by AMFBio** [comment]
![image](https://user-images.githubusercontent.com/44623561/78626212-6cf95900-78d1-11ea-817f-fdcbeb30eeaf.png)

My files are in .gz format. I double checked this by opening in a text editor and it was all nonsense. I even tried the compress=FALSE command, just to be sure, and it didn't help.

**Comment by AMFBio** [comment]
Here is my filtered forward and reverse files for sample 1, just in case it helps. 

[SAMPLE1_R_filt.fastq.gz](https://github.com/benjjneb/dada2/files/4441843/SAMPLE1_R_filt.fastq.gz)
[SAMPLE1_F_filt.fastq.gz](https://github.com/benjjneb/dada2/files/4441846/SAMPLE1_F_filt.fastq.gz)

**Comment by benjjneb** [comment]
> RStudio is running on my local laptop, and the folders I'm working in (the screen shot above) is on a university network that I'm connecting through to via VPN. Not sure if that could be causing any issues.

Yes that is almost certainly the issue. Can you check that if you try to run cutadapt on a couple files on your local machine that it works OK?

> dirPath: Z:/PhD Files/R resources/GEM analyses/GEM15 Sequence files (DADA2 format)/cutadapt/SAMPLE1_2.fastq.gz

Can you clarify whether R can detect a file at that location at all? I.e. what is the output of `file.exists(INSERT_THAT_FILENAME)`?

**Comment by AMFBio** [comment]
Thanks very much for getting back to me. Unfortunately moving my files to my local computer and running it again didn't fix the issue; the same error is appearing. Prior to removing the primers using cutadapt I ran the 1.12 DADA2 pipeline from my local linking through to the files on my uni server with no issues. It seems that incorporating the cutadapt step has thrown a spanner in the works.

**Comment by benjjneb** [comment]
> Unfortunately moving my files to my local computer and running it again didn't fix the issue; the same error is appearing.

What was the path to the files on your local computer? Did it contain any spaces or parentheses? It is possible that is what is tripping up cutadapt. In general, it is a good idea go avoid spaces or parentheses in file/directory names, especially when working with command line applications.

**Comment by AMFBio** [comment]
Ahhh... Well this is demoralising, but yes it was the spaces in the file path. Thanks very much, and sorry for wasting your time!

**Comment by juanboja** [comment]
Hello,

I am having a similar issue. I have been following all the ITS workflow. Everything is working until:

```
# Run Cutadapt
for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                             fnFs.filtN[i], fnRs.filtN[i])) # input files
}

rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.cut[[1]]), 
      FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.cut[[1]]), 
      REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.cut[[1]]), 
      REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.cut[[1]]))
```

I get the following error: 

 Error: Input/Output
  no input files found
  dirPath: C:/Users/gabj8/OneDrive/Desktop/dada2_amplicon_ex_workflow/cutadapt/B1_sub_R1.fastq
  pattern: character(0) 

After the cutadapt code, I checked the /cutadapt folder to check if anything has been created, but the folder is empty. I guess that is why the error pops, but I don't know why the trimmed files are not there. I don;t get any error after running the For loop and as you can see there are no spaces in file path. 

I am running in Rstudio Version 1.2.1335 and R version 3.6.3 in Windows 10.

Could you any idea what is the problem? Thanks for the help

**Comment by hlfreund** [comment]
> Hello,
> 
> I am having a similar issue. I have been following all the ITS workflow. Everything is working until:
> 
> ```
> # Run Cutadapt
> for(i in seq_along(fnFs)) {
>   system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
>                              "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
>                              fnFs.filtN[i], fnRs.filtN[i])) # input files
> }
> 
> rbind(FWD.ForwardReads = sapply(FWD.orients, primerHits, fn = fnFs.cut[[1]]), 
>       FWD.ReverseReads = sapply(FWD.orients, primerHits, fn = fnRs.cut[[1]]), 
>       REV.ForwardReads = sapply(REV.orients, primerHits, fn = fnFs.cut[[1]]), 
>       REV.ReverseReads = sapply(REV.orients, primerHits, fn = fnRs.cut[[1]]))
> ```
> 
> I get the following error:
> 
> Error: Input/Output
> no input files found
> dirPath: C:/Users/gabj8/OneDrive/Desktop/dada2_amplicon_ex_workflow/cutadapt/B1_sub_R1.fastq
> pattern: character(0)
> 
> After the cutadapt code, I checked the /cutadapt folder to check if anything has been created, but the folder is empty. I guess that is why the error pops, but I don't know why the trimmed files are not there. I don;t get any error after running the For loop and as you can see there are no spaces in file path.
> 
> I am running in Rstudio Version 1.2.1335 and R version 3.6.3 in Windows 10.
> 
> Could you any idea what is the problem? Thanks for the help

Hi! I am no expert, but I have been following the DADA2 tutorial/ITS tutorial all week. I didn't resolve this in R, but I did was able to download cutadapt via the command line (https://cutadapt.readthedocs.io/en/stable/installation.html) and ran a loop (I will share the code with you below) to run cutadapt through all of my reads to remove primers, and then used these sequences as my input for the DADA2 1.12 tutorial. One thing I noticed was that my file names had a "-" in them, which I changed to a "_", and I think this helped with cutadapt. 

`#!/bin/bash
# go to directory where fastqs are located before running this script
for f in *.fastq
do
fname=$(basename file)
cutadapt -a CTTGGTCATTTAGAGGAAGTAA -o "/path/to/output/directory/${fname}" $file
done`

**Comment by juanboja** [comment]
> `#!/bin/bash
> # go to directory where fastqs are located before running this script
> 
> for f in *.fastq
> do
> fname=$(basename file)
> cutadapt -a CTTGGTCATTTAGAGGAAGTAA -o "/path/to/output/directory/${fname}" $file
> done`

Thanks for the code. I am new at programming. Is this for a Linux system? I am currently working in Windows. If you could briefly guide me on how to do it in python. I have installed the Anaconda program.

I also checked the R script and outputs generated, and I found something strange. After running the prefiltering of sequences with N characters code: 

```
# “Pre-filter” the sequences just to remove those with Ns, but perform no other filtering.

fnFs.filtN <- file.path(path, "filtN", basename(fnFs)) # Put N-filtered files in filtN/ subdirectory
fnRs.filtN <- file.path(path, "filtN", basename(fnRs))
filterAndTrim(fnFs, fnFs.filtN, fnRs, fnRs.filtN, maxN = 0, multithread = FALSE)
```

**The files in the filtN directory after running the prefiltering of sequences with N characters are not fastq files. The have no sequences and strange characters. Any idea why?** 

I thought this was affecting so I reran the cutadapt for loop but now changing the **input files** to the originals fastq files:

```
# Run Cutadapt
for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                             fnFs[i], fnRs[i])) # input files
}
```

But the result is the same. No files were created in the cutadapt directory and the same INPUT/OUTPUT error.

Thanks for the help

**Comment by juanboja** [comment]
I have kept trying to figure it out and solved everything else, and the only thing I know is that for some reason the code
```
for(i in seq_along(fnFs)) {
  system2(cutadapt, args = c(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                             "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                             fnFs[i], fnRs[i])) # input files
}
```
is not creating the output files. Could it be that cutadapt is not working properly in windows through R? I have run the line `system2(cutadapt, args = "--version")` and no error comes out.

Any hints how I can check it if it is working?

**Comment by benjjneb** [comment]
> I have run the line system2(cutadapt, args = "--version") and no error comes out.
> Any hints how I can check it if it is working?

Does the cutadapt version get output in your R console? Or does nothing happen at all, i.e. no output in the console?

**Comment by juanboja** [comment]
> 

> Does the cutadapt version get output in your R console? Or does nothing happen at all, i.e. no output in the console?

It doesn't show any output. What should I get?

**Comment by benjjneb** [comment]
It should show a numeric version, e.g.

> 2.8

If it shows nothing, then the path you are giving R to call cutadapt is not working.

What is the output when you enter `cutadapt`? Does that look like the right path to call the cutadapt executable?

**Comment by juanboja** [comment]
The output is

```
> cutadapt
[1] "C:/ProgramData/Anaconda3/Lib/site-packages/cutadapt"
```
It seems to be correct. Sorry but I'm new at this. What should the files/folder look like?

**Comment by benjjneb** [comment]
> Now cutadapt starts to run

Progress!

> but I encountered a new problem

Can you post the output of the following:

```
i <- 1
paste(R1.flags, R2.flags, "-n", 2, # -n 2 required to remove FWD and REV from reads
                              "-o", fnFs.cut[i], "-p", fnRs.cut[i], # output files
                              fnFs.filtN[i], fnRs.filtN[i])
```

That should give us the argument line being passed to cutadapt.

**Comment by juanboja** [comment]
This is the ouput:

`[1] "-g GTGCCAGCMGCCGCGGTAA , -a ATTAGAWACCCBDGTAGTCC -G GGACTACHVGGGTWTCTAAT , -A TTACCGCGGCKGCTGGCAC -n 2 -o C:/Users/gabj8/OneDrive/Desktop/MBCA/dada2_amplicon_ex_workflow/cutadapt/B1_sub_R1.fastq -p C:/Users/gabj8/OneDrive/Desktop/MBCA/dada2_amplicon_ex_workflow/cutadapt/B1_sub_R2.fastq C:/Users/gabj8/OneDrive/Desktop/MBCA/dada2_amplicon_ex_workflow/filtN/B1_F_filtN.fastq C:/Users/gabj8/OneDrive/Desktop/MBCA/dada2_amplicon_ex_workflow/filtN/B1_R_filtN.fastq"`

And after checking it, I can finally see the problem. For some reason I included a "," in the R1 and R2.flags. That was the unrecognized argument in cutadapt.

Thank you very much for all the help!! I have learnt a ton! now it is working perfectly!

**Comment by azizlashari3** [comment]
> > I have run the line system2(cutadapt, args = "--version") and no error comes out.
> > Any hints how I can check it if it is working?
> 
> Does the cutadapt version get output in your R console? Or does nothing happen at all, i.e. no output in the console?

I am facing problem of cutadapt version not getting output in  R console-Please help

**Comment by juanboja** [comment]
> > > I have run the line system2(cutadapt, args = "--version") and no error comes out.
> > > Any hints how I can check it if it is working?
> > 
> > 
> > Does the cutadapt version get output in your R console? Or does nothing happen at all, i.e. no output in the console?
> 
> I am facing problem of cutadapt version not getting output in R console-Please help

What operating system are you working on? Regardless of it, the critical part is to detect where is cutadapt installed. Remember that cutadapt works on python, therefore it is installed outside the R environment. I hope this helps, keep us posted on how it goes. Good luck

**Comment by azizlashari3** [comment]
> python

Thanks @juanboja  I installed python and it worked. I successfully assign the taxonomy by code unite.ref <- "E:/sh_general_release_dynamic_04.02.2020.fasta"  # CHANGE ME to location on your machine
taxa <- assignTaxonomy(seqtab.nochim, unite.ref, multithread = FALSE, tryRC = TRUE)
and
taxa.print <- taxa  # Removing sequence rownames for display only
rownames(taxa.print) <- NULL
head(taxa.print)

I got display of the species. How I can export these taxonomy?

**Comment by benjjneb** [comment]
@azizlashari3 Where do you want to export them?

A common way would be to use the `write.table` or `write.csv` functions to export the taxonomy table to a delimited format file, which many other programs can use.

**Comment by azizlashari3** [comment]
> @azizlashari3 Where do you want to export them?
> 
> A common way would be to use the `write.table` or `write.csv` functions to export the taxonomy table to a delimited format file, which many other programs can use.

Thanks for the reply. I want to export it in excel file. 'Can you please share full command in this regard. Thanks

**Comment by azizlashari3** [comment]
> > @azizlashari3 Where do you want to export them?
> > A common way would be to use the `write.table` or `write.csv` functions to export the taxonomy table to a delimited format file, which many other programs can use.
> 
> Thanks for the reply. I want to export it in excel file. 'Can you please share full command in this regard. Thanks

@benjjneb Thanks for the command. I used the write.table command and got the out  put in console. Can you please let me know how they can be exported in excel file or other file in the computer drive. Thanks

**Comment by azizlashari3** [comment]
> > > @azizlashari3 Where do you want to export them?
> > > A common way would be to use the `write.table` or `write.csv` functions to export the taxonomy table to a delimited format file, which many other programs can use.
> > 
> > 
> > Thanks for the reply. I want to export it in excel file. 'Can you please share full command in this regard. Thanks
> 
> @benjjneb Thanks for the command. I used the write.table command and got the out put in console. Can you please let me know how they can be exported in excel file or other file in the computer drive. Thanks

Thanks. I got the file by code write.csv(taxa, file="E:/Book2.csv"), but I am unable to see the sample ID. Just sequence and taxonomy.

**Comment by benjjneb** [comment]
> Thanks. I got the file by code write.csv(taxa, file="E:/Book2.csv"), but I am unable to see the sample ID. Just sequence and taxonomy.

A sequence doesn't have a "sample ID". It is a sequence that was observed in the dataset, perhaps in many samples.

I think you need to think about and clearly define the table you are trying to output. What exactly are the rows and columns and entires that you are trying to create. Then, you want to form that table in R. The easy part is probably the output once you have the desired table correctly defined.
