### ISSUE TITLE
Error with filenames in Big Data DADA2 workflow

### ISSUE THREAD

**Issue by sandradiazg** [benjjneb/dada2#985]
Hello everybody!

I am doing a microbiome analysis on the fungal ITS sequence and I started with the ITS dada2 workflow, but at some point in the dereplication step R is killed and I can not continue with the analysis. I have 288 samples so I moved to the Big Data Workflow and try to go through the "Infer sequence variants" section with the already filtered data. However, I think there is something wrong with my file names, so I can not follow the workflow. Could someone help me? My file names look like this:

42969_ID1362_2_14BST0_ITS_S2_L001_R1_001.fastq.gz
42969_ID1362_2_14BST0_ITS_S2_L001_R2_001.fastq.gz

Thanks!

Sandra

**Comment by benjjneb** [comment]
In the current version 1.12 of the DADA2 tutorial, there is no longer any dereplication step, and memory requirements are controlled throughout. Are you using that up-to-date version (also with version 1.12 or later of the dada2 R package)?

As for your filenames, what part of the filename is the unique sample name?

**Comment by sandradiazg** [comment]
As I had ITS sequences, I started to follow this tutorial : https://benjjneb.github.io/dada2/ITS_workflow.html, and the problem came in the step "Dereplicate identical reads". That's why I moved to BigData tutorial for paired-end sequences: https://benjjneb.github.io/dada2/bigdata_paired.html. But here I think I have problems with the filenames. I have the latest version of dada2 R package.

The unique sample name is the following part:
42969_ID1362_2_14BST0 

Thanks,

**Comment by benjjneb** [comment]
From the tutorial:

```
# Extract sample names, assuming filenames have format: SAMPLENAME_XXX.fastq
sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
```
> Considerations for your own data: The string manipulations may have to be modified if your filename format is different

Your filenames are not in that format, that is you have underscores in your filenames, so you need to change the sample name extraction command (or remove the underscores from your sample names in the files).

If your sample names are consistently in the format you described, i.e. always have 4 fields separated by three underscores, then the following should work:

```
sample.names <- sapply(strsplit(basename(fnFs), "_"), function(x) {paste(x[1:4], collapse="_")})
```

**Comment by slambrechts** [comment]
Maybe this could work in case the amount of underscores differs between sample names?

```
sample.names <- sapply(strsplit(basename(filtFs), "_R1.fastq.gz"), `[`, 1) # Assumes filename = samplename_XXX.fastq.gz

sample.namesR <- sapply(strsplit(basename(filtRs), "_R2.fastq.gz"), `[`, 1) # Assumes filename = samplename_XXX.fastq.gz
```
