### ISSUE TITLE
Can .fna file input in the dada2 for analysis?

### ISSUE THREAD

**Issue by guangingmai** [benjjneb/dada2#987]
I have some .fna files after quality control. Now i want to use these files to run through microbiome workflow in R, but i don't know how to read these files in R and process these. Can dada2 read these files and process? Or, any other way can achieve?

**Comment by benjjneb** [comment]
Not directly. What you want to use DADA2 are per-sample (i.e. demultiplexed) fastq files, not fasta files.

Usually .fna files are non-demultiplexed fasta files that were generated by the old QIIME1 platform.

Ideally you would go back to the original data and generate per-sample fastq files instead.

**Comment by guangingmai** [comment]
Thanks for your message.
