### ISSUE TITLE
Issues with merging

### ISSUE THREAD

**Issue by cchgm** [benjjneb/dada2#988]
Hi all,

I have V4V5 (515F and 926R) data made up of environmental (sediment) and specimen samples. 
The specimen samples are doing OK. I lose around 38 % of input sequences but there is still plenty to work with. The environmental samples don't fare as well. With those, I lose around 84%. 

A fair number are lost at each stage but most fail to merge. I have tried varying truncation lengths to balance overlap and read quality. Here is the tracked output from a 98bp overlap. I think that's probably the limit, given the quality scores of the initial reads (I've attached some examples). I trimmed at 250 and 220. 

[track_example.txt](https://github.com/benjjneb/dada2/files/4494417/track_example.txt)
[sr2_noAR_test7_fnRs_1-10.pdf](https://github.com/benjjneb/dada2/files/4494474/sr2_noAR_test7_fnRs_1-10.pdf)
[sr2_noAR_test7_fnFs_1-10.pdf](https://github.com/benjjneb/dada2/files/4494475/sr2_noAR_test7_fnFs_1-10.pdf)

There are half as many input reads from the environmental samples compared to the specimen samples so I'm expecting to get less but this seems a bit extreme. 
I am told that libraries targeting environmental samples can be fairly messy but is this discrepancy normal considering these samples were prepped and sequenced at the same time? 

Thanks for your help!

**Comment by benjjneb** [comment]
Three things would be useful to try and diagnosis what is going on: 

(1) Run `plotComplexity` on the input files of a couple environmental (is that the same as contorl?) samples and specimen samples. Any evidence of low complexity sequences?

(2) Try running the pipeline with `dada(..., pool="pseudo")`. Does that change the number of reads that make it through the steps noticably?

My top concern here is how few reads are passing the denoising step in the environmental samples (only about half). Those might give clues as to why that is. Also, what does your `plotErrors` look like?

**Comment by cchgm** [comment]
Thanks for your reply! 

1)Here are complexity plots of the first 3 environmental samples. They aren't controls for the 5 specimen samples in the test set but are controls taken from the environment where other specimens in the data set were isolated. All of the environmental samples seem to suffer the same problem. 

[E1_R1_complexity.pdf](https://github.com/benjjneb/dada2/files/4494924/E1_R1_complexity.pdf)
[E1_R2_complexity.pdf](https://github.com/benjjneb/dada2/files/4494925/E1_R2_complexity.pdf)
[E2_R1_complexity.pdf](https://github.com/benjjneb/dada2/files/4494926/E2_R1_complexity.pdf)
[E2_R2_complexity.pdf](https://github.com/benjjneb/dada2/files/4494927/E2_R2_complexity.pdf)
[E3_R1_complexity.pdf](https://github.com/benjjneb/dada2/files/4494928/E3_R1_complexity.pdf)
[E3_R2_complexity.pdf](https://github.com/benjjneb/dada2/files/4494929/E3_R2_complexity.pdf)

2)That was which pseudo pooling enabled. 

Error plots look OK. 
[sr2_noAR_test7_errR.pdf](https://github.com/benjjneb/dada2/files/4494972/sr2_noAR_test7_errR.pdf)
[sr2_noAR_test7_errF.pdf](https://github.com/benjjneb/dada2/files/4494973/sr2_noAR_test7_errF.pdf)

**Comment by benjjneb** [comment]
Hm... nothing too obvious.

One more to try: Can you run `learnErrors` on only specimen samples, and then post the `plotErrors` result after that?

**Comment by cchgm** [comment]
Here are the error plots for both specimen samples only and environmental samples only. 
Hmm ... quite different! 

[sr2_specimen_test_errF.pdf](https://github.com/benjjneb/dada2/files/4495496/sr2_specimen_test_errF.pdf)
[sr2_specimen_test_errR.pdf](https://github.com/benjjneb/dada2/files/4495497/sr2_specimen_test_errR.pdf)

[sr2_env_test_errF.pdf](https://github.com/benjjneb/dada2/files/4495494/sr2_env_test_errF.pdf)
[sr2_env_test_errR.pdf](https://github.com/benjjneb/dada2/files/4495495/sr2_env_test_errR.pdf)

**Comment by benjjneb** [comment]
My recommendation then is to use the specimen-based error rates in your denoising step.

Something we have slowly started to become aware of, is that error-rate estimation is much harder in extremely diverse samples, like the sediment sample might be. Thus, the estimates from your less-diverse specimen samples are probably a lot more accurate. My guess is that this will help quite a bit in the denoising step, which previously was using quite over-estimated error rates.

But the proof is in the pudding. Can you try denoising the sample with the specimen-estimated error rates, and let us know if the fraction of reads passing denoising improves, especially in the sediment samples? W/ the same setting (eg. pool="pseudo") as before.

**Comment by cchgm** [comment]
Apologies. I think that original track table I uploaded was from a different filtering parameter test. 
I repeated to make sure. 

Here is with the error model from all samples...
[sr2_test7_redo_track.txt](https://github.com/benjjneb/dada2/files/4497436/sr2_test7_redo_track.txt)
and here is just using the specimen error model ... 
[sr2_test7_specimen_Err_track.txt](https://github.com/benjjneb/dada2/files/4497438/sr2_test7_specimen_Err_track.txt)

Less sequences after denoising with the specimen error rates.

**Comment by benjjneb** [comment]
Hm. I don't know.

If you'd like to share an example set of samples (maybe like 3 each of env and specimen samples) I can take a closer look myself.

**Comment by cchgm** [comment]
Sure. Thanks. Can I send them by email?

**Comment by benjjneb** [comment]
Yep. If you include a link to this issue in the email, even better.

benjamin DOT j DOT callahan AT gmail DOT com

**Comment by benjjneb** [comment]
I'm pretty sure we did figure this out over email, but feel free to reopen if that wasn't the case.
