### ISSUE TITLE
dada2 using 16S long read data from Loop genomics

### ISSUE THREAD

**Issue by jabaho9523** [benjjneb/dada2#991]
Hi, have you established/tested ways to analyse 16S long read data generated by Loop genomics with dada2?

**Comment by benjjneb** [comment]
More to come soon.
For now we suggest following the PacBio long-read workflow (example [here](https://benjjneb.github.io/LRASManuscript/LRASms_fecal.html)) with a couple parameter modifications:

```
filterAndTrim(..., maxEE=1, minLen=1400, maxLen=1600,) 
# But relax maxEE if if too few reads are passing the filter
# Also change minLen and maxLen depending on gene being sequenced. This is for full-length 16S
dada(..., OMEGA_A=1e-10, DETECT_SINGLETONS=TRUE) 
# But leave DETECT_SINGLETONS false if you don't care about rare stuff
assignTaxonomy(..., minBoot=80)
```

**Comment by jabaho9523** [comment]
Thank you for the quick reply. It seems to work. Haven't fully benchmark the data yet but the results looks promising so far.

**Comment by jabaho9523** [comment]
Assigning taxonomy down to genus level works well but the species annotation is less than what I get from the same samples analysed with a short illumina read. Do you recommend some modifications in the species annotation step?

These are the comands used:
```
RefDataBase = "silva_nr_v132_train_set.fa.gz"
SpeciesDB = "silva_species_assignment_v132.fa.gz"
tax <- assignTaxonomy(st, RefDataBase, multithread=TRUE, minBoot=80)
tax.species <- addSpecies(tax, refFasta = SpeciesDB, allowMultiple = TRUE)
```

Based on Illumina 16S short amlicons I get the following annotation:
```
        assigned total PC_assigned
domain      1168  1168       100.0
phylum      1159  1168        99.2
class       1157  1168        99.1
order       1139  1168        97.5
family      1093  1168        93.6
genus        900  1168        77.1
species      296  1168        25.3
```
Based on long read 16S I get the following annotation:
```
        assigned total PC_assigned
Kingdom     4012  4013       100.0
Phylum      4008  4013        99.9
Class       4007  4013        99.9
Order       4000  4013        99.7
Family      3944  4013        98.3
Genus       3508  4013        87.4
Species       84  4013         2.1
```
As you can see the taxonomy is better at all levels except of the Species level. 
Any advice is highly appreciated.

**Comment by benjjneb** [comment]
> tax.species <- addSpecies(tax, refFasta = SpeciesDB, allowMultiple = TRUE)

The `addSpecies` command was created and intended for short-read 16S data only, and is far too conservative for accurate long-read data like LoopSeq provides. See more discussion in issue #990

**Comment by jabaho9523** [comment]
Thank you. It sounds very promising what you are working on.

Can you guide to a silva 16S reference database with species or how to generate it correctly? Then I will test the `assignTaxonomy`.

**Comment by benjjneb** [comment]
> Can you guide to a silva 16S reference database with species or how to generate it correctly?

This is in progress, but we hope to have an apppropriate speces-level Silva db out sometime in the next month.

**Comment by cjfields** [comment]
@jabaho9523 regarding taxonomic assignment, see https://github.com/benjjneb/dada2/issues/990#issuecomment-685879034

**Comment by benjjneb** [comment]
The Silva v138.1 database reformatted to include species-level taxonomy, and thus suitable for species-level assignment to long-read 16S, is available: https://doi.org/10.5281/zenodo.3731174
