### ISSUE TITLE
dada2 Filter and Trim issues

### ISSUE THREAD

**Issue by peggy17688** [benjjneb/dada2#992]
Hi all, 

I am still quite new to dada2 and I have been looking at the tutorials and they are really helpful so far. 

However, I have some pesky (and weird) issues when running the Filter and Trim function of dada2. I am running dada2 on Illumina MiSeq300 paired-end sequences and I trimmed off the primers (515f-806r) and adapters with Trimmomatic prior to running dada2. But when I applied truncLen=c(250, 200) and maxEE=c(2,2) which I read off from my plotQualityProfile plots, corresponding to the quality drop, more than half my reads were filtered off. When I look at the plots again, the scaled proportion of reads graph was sloping downwards instead of constant length, is that why it is causing the problem? The plots are shown below.

Also, I did a random run without truncLen and most of my reads got retained. But it resulted in a very large dataset which overwhelmed my 8GB laptop. :/

I am just wondering what proportion of reads should be retained to be considered normal? 

Advice would be really be much appreciated! Thanks!
![Rplot_R1](https://user-images.githubusercontent.com/64371748/80314296-4a4cc700-8823-11ea-92b2-9f983a71109c.png)
![Rplot_R2](https://user-images.githubusercontent.com/64371748/80314299-4c168a80-8823-11ea-802f-5a8126fba888.png)

**Comment by benjjneb** [comment]
HI Peggy
Could you say a bit more about what pre-filtering you have done to these reads?
The red line in those plots shows the cumulative percentage of reads that extend out to that number of bases. It appears that almost all of your reads have already been truncated before their original length of 300nts.

This is not recommended, and probably explains much of the loss you are seing in the `filterAndTrim` step. Can you work with the original reads instead?

**Comment by peggy17688** [comment]
I used Trimmomatic to remove the Illumina adapters but I ran it with the default TruSeq3 filter on Galaxy because I couldn't run Cutadapt on my own laptop. Maybe the cropping parameters weren't right and it cropped my reads too short. 

But won't dada2 work with sequences containing primers if I were to run the original reads?

**Comment by benjjneb** [comment]
I would recommend not doing the Galaxy/Trimmomatic filtering, it is doing more than just removing primers.

If your FWD and REV primers are at the start of the reads, as iis usual, they are easily removed by 'filterAndrim(..., trimLeft=c(FWD_LEN,, REV_LEN)`.

**Comment by peggy17688** [comment]
Oh I see. but what about the 3' end with the adapter? would I have to specify with TrimRight or it will just be removed when I specify truncLen?

**Comment by peggy17688** [comment]
I am now a bit stuck with the trimming. I tried using TrimLeft and now only the R1 file went through. 

Was asking about the 3'-end because I saw this and now I am not sure how I should apply the trimming code.
![adapter](https://user-images.githubusercontent.com/64371748/80333454-b6a9e380-8880-11ea-91fe-075c9570cdf3.jpg)

**Comment by benjjneb** [comment]
The v4 region you are sequencing is about 252nts long, with very little length variation. As long as your truncation lengths are <252 + PRIMER_LEN, you won't get any of the other primer on the reads. So you should be OK if you are using truncation lengths of 250 or less.

**Comment by peggy17688** [comment]
I see, now I understand. Thanks for the explanation!
