### ISSUE TITLE
estimated error rates

### ISSUE THREAD

**Issue by wangjiawen2013** [benjjneb/dada2#993]
Dear,
Does this estimated error rates plot looks good ?
It is always worthwhile, as a sanity check if nothing else, to visualize the estimated error make sense ?
![errF](https://user-images.githubusercontent.com/29703450/80338752-b6651480-888f-11ea-811b-a78756c36efd.png)
And here is the one of the fastqc files:
![QQ图片20200427140402](https://user-images.githubusercontent.com/29703450/80338864-fe843700-888f-11ea-9f95-36611b4c5326.png)

**Comment by benjjneb** [comment]
What instrument are you doing your sequencing on? Or more specifically (if you know) is your data using binned quality scores?

**Comment by wangjiawen2013** [comment]
Illumina Hiseq2000

**Comment by benjjneb** [comment]
So this looks like the same issue with binned quality scores that has previously been reported and discussed on issue #791 

Can you take a look at that discussion and see if it helps? There are a couple solutions suggested to the underestimation of error rates in that Q30-36 range.
