### ISSUE TITLE
Non-corresponding derep-class and dada-class objects during `mergePairs`

### ISSUE THREAD

**Issue by LijMeh** [benjjneb/dada2#994]
Hello, 

Firstly, thanks for creating and maintaining this awesome utility. 

I'm at the `mergePairs` step, and for some reason after successfully merging the first 3 samples it quits on the 4th sample with the following error `Error in FUN(X[[i]], ...) : Non-corresponding derep-class and dada-class objects.`

I tried looking around, but I didn't see much on this error, any help would be greatly appreciated.

**Comment by benjjneb** [comment]
Do you get the same lengths for each of the `derep-class` and `dada-class` lists? If your following the tutorial, what is the output of:

```
length(dadaFs)
length(derepFs)
length(dadaRs)
length(derepRs)
```

If all those lengths are the same, is there any place in your script where you might have re-ordered these lists some how, for instance by 'sort'-ing?

**Comment by LijMeh** [comment]
Thanks, I get the following output. 
```
> length(dadaFs)
[1] 91
> length(dadaRs)
[1] 91
> length(filtFs)
[1] 91
> length(filtRs)
[1] 91
```
They shouldn't have been reordered beyond whats outlined in the pipeline tutorial:
`dadaFs <- readRDS("dadaFs.rds") dadaRs <- readRDS("dadaRs.rds")` and `cutFs <- sort(list.files(path.cut, pattern = "_R1_001.fastq.gz", full.names = TRUE))`
I've been running through 3 sequencing projects using the same code and I haven't seen this issue in the other 2. Do you think it would be worth just going back to the beginning and re-running the pipeline from scratch?

**Comment by benjjneb** [comment]
> Do you think it would be worth just going back to the beginning and re-running the pipeline from scratch?

I think yes, if only because this error is almost never reported. I'd also double-check the script is using the same files at the `dada` and `mergePairs` stage.

**Comment by LijMeh** [comment]
Ok! I'll run back through from the start and make sure I don't have any typos etc.

**Comment by LijMeh** [comment]
Thanks for the advice, I ran through again from scratch and it worked this time.
