### ISSUE TITLE
stitching reads without N's

### ISSUE THREAD

**Issue by dcastaneda5** [benjjneb/dada2#996]
Hi Ben,

I hope you are doing well. I am currently working on microbiome 16S v3-v4 data where I have 176 patients for cohort 1, 176 for cohort 2, and 9 for my controls. Because of my low number of controls, I decided to take data from SRA. The problem with the control data I was able to obtain, is that whenever I download the forward reads (278 bp), and reverse reads (278 bp), the merging process from DADA2 does not really work. The data that was uploaded to SRA was previously merged and filtered, so the SRA toolkit provides me with the forward and reverse reads unstitched without any overlap of the merged regions... In summary, I have 278 forward and 278 reverse bp that need to be stitched together to make a 556 bp read. I tried using "justConcatenate=TRUE", but it is giving me reads of 310 bp long, instead of 556 bp (plus I have the N's that I don't need). Is there any way of bypassing this problem?

Thanks for your help,

Daniel

**Comment by benjjneb** [comment]
Yeah you can just remove the 10Ns from the sequences after you get your sequence table.

```
new.seqs <- gsub("NNNNNNNNNN", "", getSequences(sta))
colnames(sta) <- new.seqs
```

**Comment by dcastaneda5** [comment]
Great! Thanks a lot, I will give it a try! Is there any reason why I am getting the 310 bp? I set truncLen=c(150,150) thinking that the FilterandTrim function would remove reads shorter than 150 bp in forward and reverse reads as it is indicated in the package help " Default 0 (no truncation). Truncate reads after truncLen bases. Reads shorter than this are discarded"... Does that mean it just trims down to 150 bp instead? Is DADA2 shortening my reads to 150 each and adding 10 bases to make 310 bp? Sorry if I was confused about this! 

I tried just removing the truncLen option, but if I do that, then none of my reads are passing the filter for some reason... Is this normal? I basically want to remove reads lower than 150 bp in length, and keep the rest as they are so I can stitch them together and remove the extra 10 N's that I am getting.

**Comment by benjjneb** [comment]
> Reads shorter than this are discarded"... Does that mean it just trims down to 150 bp instead? Is DADA2 shortening my reads to 150 each and adding 10 bases to make 310 bp? Sorry if I was confused about this!

Yes. `truncLen' is the truncation length. If you set is to `c(150, 150)` it is truncating the forward and reverse reads at 150, and throwing away reads that don't reach that far.

> I basically want to remove reads lower than 150 bp in length

You can use the `minLen` filter for that.

> I tried just removing the truncLen option, but if I do that, then very little amount of reads are passing the filter for some reason... Is this normal?

Very few passing probably isn't normal, but it depends on the read quality. If you don't want to filter, just turn off the quality filters too, e.g. `maxEE=0`.

**Comment by dcastaneda5** [comment]
That worked! Thanks a lot! Great software! (: 👍

**Comment by dcastaneda5** [comment]
Sorry, I am probably missing something... But after I run this: 

```
seqtab3 <- makeSequenceTable(mergers3)
#data.class(seqtab3_2) character
seqtab3_2 <- gsub("NNNNNNNNNN","",getSequences(seqtab3))
colnames(seqtab3)<-seqtab3_2
```

I get a character variable instead of a matrix. I am sure I am missing something because when I look for the dimension of my variable it returns null... I tried converting it into a matrix by doing:

`seqtab3_2<-as.matrix(seqtab3_2)`

But when I try running this, it just gives me an invalid number of dimensions...

```
Error in seqtab3_2[, nchar(colnames(seqtab3)) %in% 460:600] : 
  incorrect number of dimensions
```

Is gsub changing my matrix into something else? Thanks!!!!!!!

**Comment by benjjneb** [comment]
This line is the issue:

```
seqtab3_2 <- gsub("NNNNNNNNNN","",getSequences(seqtab3))
```

A `seqtab` is a matrix with entires that are abundances, column names that are the ASVs, and rownames that are the sample names. `getSequences` extracts the column names. So that command assigned just the column names, a character vector of sequences, to `seqtab3_2`.

However, the next line:

```
colnames(seqtab3)<-seqtab3_2
```

gives you what you want actually. `seqtab3` is now the sequence table, with column names in which the 10Ns have been replaced by nothing.

So, you can use your code, but to make it less confusing, change the variable name `seqtab3_2` to `new.seqs` (because that variable is not holding a sequence table, it's holding new sequences).

And in the end your `seqtab3` will be what you want. You can check yourself that it has the sequences w/ no Ns by looking at `head(getSuquences(seqtab3))` at the end.
