### ISSUE TITLE
removePrimers match

### ISSUE THREAD

**Issue by arnold3** [benjjneb/dada2#998]
Hello! I'm a big dada2 fan, and am working with several datasets for a meta-analysis. Because of this, each dataset has a different set of adaptors and primers. Unfortunately, information on adaptors is harder to find than just primer information, so I'm wondering if I can remove primers without having to remove adaptors as described in the dada2 ITS pipeline workflow here: 

https://benjjneb.github.io/dada2/ITS_workflow.html

Cheers,

**Comment by benjjneb** [comment]
Yep, the adapters will be "behind" the primers, and will get removed with the primers by cutadapt in the ITS workflow.

**Comment by arnold3** [comment]
Hey, thanks a bunch! I just wasn't sure if primer matching only occurred at front / tail end of sequence.
