### ISSUE TITLE
Too many reads detected a chimeras / weird reads distribution

### ISSUE THREAD

**Issue by jecom21** [benjjneb/dada2#999]
Hi, 
I have a MiSEQ 16S dataset (V3-V4, 341F-805F) that I ran through Dada2. Prior, I removed primers using cutadapt. At first, I thought all was fine as I retained most of the reads after merging and chimeras removal, but when looking more closely I realized that the number of ASVs was extremely low. When looking at the distribution of sequence lengths, I saw that there were 2 groups of different lengths. I tried to cut and focus on the one closer to the expected size of amplicons. This did not really improve the number of ASVs and dropped the number of reads as nonchim. I then played with some arguments in FilterAndTrim (mostly TruncLen) with no great improvement (I initially worked with FWD:260, REV:190). I continued on investigating parameters at the RemoveBimera step and played with the method (consensus, per-sample) and MinFoldParentOverAbundance. The latter did improved the number of ASVs detected though. I am attaching files that I think may be relevant and would appreciate your feedbacks and suggestions on the best way to analyse this dataset (may have to accept a high number of chimeras due to PCR or experimental setup). 
Thank you
[Query_to_Developpers.pdf](https://github.com/benjjneb/dada2/files/4564148/Query_to_Developpers.pdf)
[RplotREV.pdf](https://github.com/benjjneb/dada2/files/4564155/RplotREV.pdf)
[Rplot_FWD.pdf](https://github.com/benjjneb/dada2/files/4564157/Rplot_FWD.pdf)
[seqtab2.RDS.zip](https://github.com/benjjneb/dada2/files/4564162/seqtab2.RDS.zip)
[seqtab.rds.zip](https://github.com/benjjneb/dada2/files/4564176/seqtab.rds.zip)

**Comment by benjjneb** [comment]
> When looking at the distribution of sequence lengths, I saw that there were 2 groups of different lengths

This is expected. There is a bimodal distribution of biological lengths of the V3V4 region of the 16S gene, that are about 20 nts apart.

> At first, I thought all was fine as I retained most of the reads after merging and chimeras removal, but when looking more closely I realized that the number of ASVs was extremely low.

More informative is the number of reads passing through each step. Can you create the table shown in the tutorial: [https://benjjneb.github.io/dada2/tutorial.html#track-reads-through-the-pipeline](https://benjjneb.github.io/dada2/tutorial.html#track-reads-through-the-pipeline)

**Comment by jecom21** [comment]
Thanks for the reply. I did produce this table.
![SequenceQualityTable](https://user-images.githubusercontent.com/64642611/80815471-b6208e00-8b9b-11ea-8907-591d6d45ab32.jpg)
My concern was that, I end up with so few ASW at the end (n=271) from 7533 before chimeras removal. I can improve this when changing parameters from the RemoveBimeraDenovo (method and minFoldParentOverAbudance). I was wondering if there were other aspects to consider or if I was missing something.
Thank you

**Comment by benjjneb** [comment]
Usually the fraction of reads retained is a better diagnostic, and 83% of reads being retained is pretty normal (albeit not great) especially for multi-v-region amplicons.

Feel free to increase `minFoldParentOverAbundance` as desired, there is a good argument that values higher than the default (e.g. 4-8) might be a better choice in some cases, but what you're showing doesn't indicate any major cause of concern to me.

**Comment by jecom21** [comment]
Great thanks!
